health_terms = {
    'genomics': ['genetic mapping', 'DNA sequencing', 'gene profiling', 'hereditary analysis'],
    'telemedicine': ['remote consultation', 'digital healthcare', 'virtual diagnosis', 'online clinical care'],
    'biotechnology': ['bioengineering', 'genetic manipulation', 'molecular innovation', 'bioprocessing'],
    'pharmacology': ['drug science', 'therapeutics', 'medicinal chemistry', 'toxicology'],
    'immunology': ['immune response', 'antibody study', 'infection resistance', 'immunity research'],
    'pathology': ['disease analysis', 'tissue examination', 'diagnostic histology', 'medical pathology'],
    'epidemiology': ['disease distribution', 'public health tracking', 'infection mapping', 'population health study'],
    'cardiology': ['heart medicine', 'vascular care', 'circulatory health', 'cardiac diagnostics'],
    'neurology': ['brain science', 'nervous system study', 'neural medicine', 'neurodiagnostics'],
    'oncology': ['cancer study', 'tumor analysis', 'malignancy research', 'chemotherapy development'],
    'hematology': ['blood study', 'cell morphology', 'hematologic testing', 'blood pathology'],
    'radiology': ['medical imaging', 'x-ray diagnostics', 'CT scanning', 'MRI evaluation'],
    'dermatology': ['skin medicine', 'cutaneous treatment', 'dermal science', 'aesthetic dermatology'],
    'orthopedics': ['bone medicine', 'joint repair', 'musculoskeletal therapy', 'skeletal correction'],
    'pediatrics': ['child health', 'infant medicine', 'adolescent care', 'neonatal science'],
    'geriatrics': ['elder care', 'age medicine', 'senior health', 'longevity study'],
    'gynecology': ['women’s health', 'reproductive medicine', 'obstetric study', 'fertility care'],
    'urology': ['urinary medicine', 'renal care', 'bladder science', 'male reproductive health'],
    'endocrinology': ['hormonal study', 'metabolic medicine', 'glandular science', 'diabetes research'],
    'nutrition': ['dietary science', 'food metabolism', 'nutrient analysis', 'dietetics'],
    'kinesiology': ['movement science', 'exercise physiology', 'body mechanics', 'biomechanics'],
    'physiotherapy': ['rehabilitation therapy', 'physical recovery', 'movement therapy', 'manual treatment'],
    'occupational_therapy': ['functional rehab', 'skill restoration', 'adaptive training', 'ergonomic therapy'],
    'speech_therapy': ['language rehabilitation', 'speech correction', 'communication therapy', 'voice training'],
    'audiology': ['hearing science', 'auditory testing', 'sound perception', 'ear diagnostics'],
    'ophthalmology': ['eye medicine', 'vision science', 'ocular health', 'retinal study'],
    'dentistry': ['oral medicine', 'tooth care', 'dental hygiene', 'periodontal study'],
    'psychiatry': ['mental health medicine', 'clinical psychology', 'behavioral therapy', 'psychopathology'],
    'psychology': ['mind science', 'behavioral study', 'cognitive research', 'emotional analysis'],
    'neuroscience': ['brain research', 'neural analysis', 'cognitive neuroscience', 'neurobiology'],
    'anesthesiology': ['pain management', 'sedation science', 'surgical anesthesia', 'perioperative care'],
    'microbiology': ['microbe study', 'bacteriology', 'virology', 'pathogen analysis'],
    'biochemistry': ['chemical biology', 'metabolic chemistry', 'molecular interaction', 'enzyme study'],
    'molecular_biology': ['cellular genetics', 'gene function', 'DNA study', 'protein synthesis'],
    'bioinformatics': ['biological data science', 'computational genomics', 'sequence analysis', 'genetic modeling'],
    'health_informatics': ['clinical data systems', 'medical databases', 'EHR analytics', 'digital recordkeeping'],
    'public_health': ['community health', 'preventive medicine', 'population wellness', 'epidemiologic control'],
    'environmental_health': ['ecological safety', 'toxic exposure study', 'air quality research', 'sanitation science'],
    'occupational_health': ['workplace safety', 'industrial hygiene', 'ergonomic assessment', 'hazard prevention'],
    'sports_medicine': ['athletic medicine', 'performance recovery', 'injury prevention', 'sports rehabilitation'],
    'fitness_science': ['exercise physiology', 'strength conditioning', 'physical performance', 'body training'],
    'mental_health': ['emotional wellness', 'psychological stability', 'stress management', 'mindfulness'],
    'nursing': ['clinical care', 'patient management', 'health monitoring', 'medical assistance'],
    'phlebotomy': ['blood collection', 'specimen handling', 'sample extraction', 'venipuncture'],
    'surgery': ['operative medicine', 'surgical technique', 'tissue repair', 'operative care'],
    'robotic_surgery': ['automated operation', 'mechanical assistance', 'surgical robotics', 'precision surgery'],
    'nanomedicine': ['nano therapy', 'molecular targeting', 'nanoparticle drug delivery', 'nano diagnostics'],
    'gene_therapy': ['genetic treatment', 'DNA modification', 'hereditary correction', 'molecular therapy'],
    'stem_cell_therapy': ['regenerative medicine', 'cell renewal', 'tissue restoration', 'cellular repair'],
    'diagnostics': ['disease detection', 'clinical testing', 'medical analysis', 'screening process'],
    'AI_diagnostics': ['algorithmic analysis', 'machine detection', 'predictive diagnosis', 'automated screening'],
    'biostatistics': ['statistical epidemiology', 'clinical data modeling', 'health metrics', 'data inference'],
    'pharmaceuticals': ['drug manufacturing', 'medication design', 'therapeutic development', 'formulation science'],
    'toxicology': ['poison study', 'hazard assessment', 'chemical safety', 'toxin evaluation'],
    'imaging_technology': ['radiologic imaging', 'ultrasound scanning', '3D diagnostics', 'image processing'],
    'medical_AI': ['intelligent healthcare', 'clinical automation', 'predictive medicine', 'AI-assisted treatment'],
    'digital_health': ['connected care', 'remote monitoring', 'smart healthcare', 'mobile medicine'],
    'wearable_technology': ['health trackers', 'biosensors', 'fitness devices', 'real-time monitoring'],
    'data_medicine': ['predictive analytics', 'health data modeling', 'AI prediction', 'computational diagnosis'],
    'genetic_engineering': ['DNA modification', 'gene splicing', 'chromosome editing', 'biogenetics'],
    'microbiome_science': ['gut bacteria study', 'microbial ecology', 'flora analysis', 'intestinal research'],
    'virology': ['virus study', 'viral genetics', 'infection biology', 'immunopathology'],
    'bacteriology': ['bacterial science', 'pathogen research', 'infection mechanics', 'antibiotic study'],
    'cytology': ['cell study', 'microscopic biology', 'cellular pathology', 'histological analysis'],
    'histology': ['tissue structure', 'anatomical study', 'microscopic anatomy', 'biological tissue science'],
    'anatomy': ['body structure', 'organ study', 'physiological mapping', 'morphological science'],
    'physiology': ['body function', 'organ processes', 'system regulation', 'biological dynamics'],
    'pathophysiology': ['disease mechanism', 'functional disorder', 'biological disturbance', 'pathogenic dynamics'],
    'toxicogenomics': ['genetic toxicity study', 'molecular toxicology', 'DNA damage analysis', 'hazard genomics'],
    'metabolomics': ['metabolic profiling', 'biochemical pathway study', 'cellular metabolism', 'molecular fingerprinting'],
    'proteomics': ['protein mapping', 'biomolecular analysis', 'enzyme profiling', 'mass spectrometry'],
    'lipidomics': ['fat metabolism study', 'lipid profiling', 'biochemical lipid analysis', 'cell membrane research'],
    'glycomics': ['sugar biology', 'carbohydrate profiling', 'glycan analysis', 'biochemical mapping'],
    'clinical_trials': ['experimental medicine', 'drug testing', 'treatment evaluation', 'trial research'],
    'vaccine_development': ['immunization science', 'antigen research', 'preventive therapy', 'disease prophylaxis'],
    'neuroprosthetics': ['bionic implants', 'brain–machine interface', 'neural devices', 'assistive prosthetics'],
    'rehabilitation': ['recovery therapy', 'physical restoration', 'functional regain', 'post-injury care'],
    'nutrition_science': ['diet research', 'nutrient analysis', 'food metabolism', 'dietary study'],
    'hydration': ['fluid balance', 'water regulation', 'electrolyte management', 'hydration therapy'],
    'sleep_science': ['restorative biology', 'circadian rhythm study', 'sleep therapy', 'fatigue analysis'],
    'stress_management': ['relaxation techniques', 'mental resilience', 'emotional balance', 'psychological coping'],
    'mindfulness': ['awareness training', 'conscious focus', 'mental clarity', 'present-centered therapy'],
    'yoga_therapy': ['meditative exercise', 'mind-body balance', 'postural therapy', 'spiritual fitness'],
    'alternative_medicine': ['holistic care', 'naturopathy', 'herbal medicine', 'integrative therapy'],
    'homeopathy': ['natural remedy', 'energy medicine', 'symptom balance', 'dilution therapy'],
    'acupuncture': ['needle therapy', 'meridian healing', 'energy flow treatment', 'traditional Chinese medicine'],
    'chiropractic': ['spinal adjustment', 'musculoskeletal therapy', 'alignment correction', 'back care'],
    'aromatherapy': ['scent therapy', 'essential oil healing', 'olfactory treatment', 'fragrance therapy'],
    'massage_therapy': ['manual therapy', 'muscle relaxation', 'soft tissue treatment', 'therapeutic massage'],
    'nutrition_therapy': ['diet management', 'nutritional counseling', 'metabolic adjustment', 'clinical dietetics'],
    'sports_psychology': ['athletic mindset', 'motivation science', 'mental training', 'performance focus'],
    'cognitive_behavioral_therapy': ['thought restructuring', 'behavior modification', 'mental correction', 'psychological reframing'],
    'art_therapy': ['creative healing', 'expressive therapy', 'emotional art', 'visual self-expression'],
    'music_therapy': ['sound healing', 'auditory relaxation', 'rhythmic therapy', 'musical intervention'],
    'dance_therapy': ['movement healing', 'expressive motion', 'body rhythm therapy', 'psychomotor treatment'],
    'pet_therapy': ['animal-assisted therapy', 'emotional comfort', 'companion healing', 'therapeutic interaction'],
    'occupational_psychology': ['work behavior', 'job motivation', 'organizational health', 'employee wellness'],
    'clinical_ethics': ['medical morality', 'bioethical principles', 'clinical judgment', 'patient rights'],
    'medical_law': ['healthcare regulation', 'biolegal study', 'medical policy', 'ethical compliance'],
    'biomechanics': ['movement mechanics', 'physical dynamics', 'kinetic structure', 'muscular motion'],
    'sports_nutrition': ['athletic diet', 'performance fueling', 'energy balance', 'muscle recovery'],
    'AI_healthcare': ['machine medicine', 'predictive care', 'digital diagnosis', 'smart treatment'],
    'digital_therapy': ['app-based care', 'virtual intervention', 'online treatment', 'AI counseling'],
    'telehealth_monitoring': ['remote observation', 'vital tracking', 'digital follow-up', 'virtual nursing'],
    'genetic_counseling': ['hereditary consultation', 'family risk analysis', 'gene advice', 'DNA guidance'],
    'precision_medicine': ['personalized therapy', 'targeted treatment', 'individualized care', 'genetic-based medicine'],
    'bioethics': ['moral biology', 'ethical research', 'clinical conduct', 'scientific responsibility'],
    'pandemic_response': ['disease control', 'infection management', 'public protection', 'emergency health'],
    'vital_sign_monitoring': ['heart rate tracking', 'respiratory observation', 'blood pressure analysis', 'temperature measurement'],
    'emergency_medicine': ['critical care', 'urgent response', 'trauma treatment', 'rescue medicine'],
    'intensive_care': ['critical support', 'life-saving management', 'ventilation therapy', 'acute observation'],
    'paramedicine': ['prehospital care', 'emergency service', 'first responder medicine', 'ambulance treatment'],
    'biomedical_engineering': ['medical device design', 'bioinstrumentation', 'prosthetic development', 'healthcare robotics'],
    'clinical_engineering': ['hospital technology', 'medical device management', 'equipment calibration', 'clinical systems'],
    'health_economics': ['medical cost analysis', 'policy budgeting', 'economic health modeling', 'healthcare finance'],
    'AI_epidemiology': ['disease modeling', 'infection forecasting', 'data-based prevention', 'algorithmic outbreak analysis']
}



