synonyms = {
    "northern dewberry": ["american dewberry", "rubus flagellaris"],
    "northern dune tansy": ["tanacetum douglasii"],
    "northern flying squirrel": ["glaucomys sabrinus"],
    "northern holly fern": ["polystichum lonchitis"],
    "northern jacob's ladder": ["polemonium boreale"],
    "northern marianas": ["northern mariana islands"],
    "northern oriole": ["icterus galbula"],
    "northern phalarope": ["lobipes lobatus"],
    "northern pike": ["esox lucius"],
    "northern pocket gopher": ["thomomys talpoides"],
    "northern red oak": ["quercus borealis", "quercus rubra"],
    "northern sea robin": ["prionotus carolinus"],
    "northern shrike": ["lanius borealis"],
    "northern whiting": ["menticirrhus saxatilis"],
    "northernmost": ["northmost"],
    "northrop": ["john howard northrop"],
    "northwest": ["nor'-west", "northwestward", "nw"],
    "northwest by north": ["nwbn"],
    "northwest by west": ["nwbw"],
    "northwest wind": ["northwester"],
    "northwesterly": ["northwest"],
    "northwestern": ["northwest", "northwesterly"],
    "northwestward": ["northwestwardly"],
    "nortriptyline": ["pamelor"],
    "noruz": ["nowrooz", "nowruz"],
    "norway": ["kingdom of norway", "noreg", "norge"],
    "norway lobster": ["nephrops norvegicus"],
    "norway maple": ["acer platanoides"],
    "norway spruce": ["picea abies"],
    "norwegian": ["norse", "norseman"],
    "norwegian elkhound": ["elkhound"],
    "norwegian krone": ["krone"],
    "norwegian lobster": ["langoustine", "scampo"],
    "nose": ["olfactory organ"],
    "nose cone": ["ogive"],
    "nose job": ["rhinoplasty"],
    "nosebag": ["feedbag"],
    "noseband": ["nosepiece"],
    "nosebleed": ["epistaxis"],
    "nosh": ["snack"],
    "nosher": ["snacker"],
    "nosiness": ["prying", "snoopiness"],
    "nosology": ["diagnostics"],
    "nostocaceae": ["family nostocaceae"],
    "nostradamus": ["michel de notredame"],
    "nostril": ["anterior naris"],
    "nosy": ["nosey", "prying", "snoopy"],
    "not": ["non"],
    "nota bene": ["n.b.", "nb"],
    "notarize": ["notarise"],
    "notary": ["notary public"],
    "notation": ["notational system"],
    "notch": ["nick", "snick"],
    "note": ["observe", "take note"],
    "notebook": ["notebook computer"],
    "notechis": ["genus notechis"],
    "notemigonus": ["genus notemigonus"],
    "noteworthy": ["notable"],
    "nothing": ["aught", "cipher", "cypher", "goose egg", "nada", "naught", "nil", "nix", "null", "zero", "zilch", "zip", "zippo"],
    "nothingness": ["nihility", "nullity", "void"],
    "nothofagus": ["genus nothofagus"],
    "nothosauria": ["suborder nothosauria"],
    "notice": ["mark", "note"],
    "notification": ["notice"],
    "notion": ["whim", "whimsey", "whimsy"],
    "notional": ["speculative"],
    "notomys": ["genus notomys"],
    "notonecta": ["genus notonecta"],
    "notonectidae": ["family notonectidae"],
    "notophthalmus": ["genus notophthalmus"],
    "notoriety": ["ill fame"],
    "notornis": ["notornis mantelli", "takahe"],
    "notoryctidae": ["family notoryctidae"],
    "notoryctus": ["genus notoryctus"],
    "notostraca": ["order notostraca"],
    "notropis": ["genus notropis"],
    "noumenon": ["thing-in-itself"],
    "noun phrase": ["nominal", "nominal phrase"],
    "nourish": ["nurture", "sustain"],
    "nouveau-riche": ["parvenu", "parvenue", "upstart"],
    "nova scotia lox": ["nova lox", "nova salmon", "nova scotia salmon", "nova style salmon"],
    "nova scotian": ["bluenose"],
    "novaya zemlya": ["nova zembla"],
    "novel": ["refreshing"],
    "novelette": ["novella"],
    "novelization": ["novelisation"],
    "novelize": ["fictionalise", "fictionalize", "novelise"],
    "novelty": ["freshness"],
    "november": ["nov"],
    "novice": ["beginner", "initiate", "tiro", "tyro"],
    "novitiate": ["noviciate"],
    "now": ["at present"],
    "nowadays": ["now", "today"],
    "nowise": ["to no degree"],
    "nox": ["night"],
    "noyes": ["alfred noyes"],
    "nozzle": ["nose"],
    "nth": ["n-th"],
    "nuance": ["nicety", "refinement", "shade", "subtlety"],
    "nub": ["nubble"],
    "nucifraga": ["genus nucifraga"],
    "nuclear": ["atomic"],
    "nuclear chemist": ["radiochemist"],
    "nuclear explosion": ["atomic explosion"],
    "nuclear family": ["conjugal family"],
    "nuclear magnetic resonance": ["nmr", "proton magnetic resonance"],
    "nuclear physics": ["atomic physics", "nucleonics"],
    "nuclear reactor": ["reactor"],
    "nuclear regulatory commission": ["nrc"],
    "nuclear rna": ["nrna"],
    "nuclear weapon": ["atomic weapon"],
    "nucleated": ["nucleate"],
    "nucleolus": ["nucleole"],
    "nucleolus organizer": ["nucleolar organiser", "nucleolar organizer", "nucleolus organiser"],
    "nucleoplasm": ["karyoplasm"],
    "nucleoside reverse transcriptase inhibitor": ["nrti"],
    "nucleotide": ["base"],
    "nucleus": ["cell nucleus", "karyon"],
    "nuda": ["class nuda"],
    "nude": ["nude person"],
    "nudge": ["poke at", "prod"],
    "nudibranchia": ["order nudibranchia"],
    "nudism": ["naturism"],
    "nudist": ["naturist"],
    "nudnik": ["nudnick"],
    "nuffield": ["first viscount nuffield", "william richard morris"],
    "nuke": ["atomise", "atomize", "zap"],
    "null": ["void"],
    "nullification": ["override"],
    "numb": ["benumb", "blunt", "dull"],
    "numbat": ["anteater", "banded anteater", "myrmecobius fasciatus"],
    "number": ["list"],
    "numbers": ["book of numbers"],
    "numbers pool": ["numbers", "numbers game", "numbers racket"],
    "numbly": ["insensibly"],
    "numdah": ["nammad", "numdah rug"],
    "numenius": ["genus numenius"],
    "numeral": ["number"],
    "numeration system": ["number representation system", "number system", "system of numeration"],
    "numeric": ["numerical"],
    "numerical": ["mathematical"],
    "numerous": ["legion"],
    "numerousness": ["multiplicity", "numerosity"],
    "numida": ["genus numida"],
    "numididae": ["numidinae", "subfamily numididae", "subfamily numidinae"],
    "numismatics": ["coin collecting", "coin collection", "numismatology"],
    "numismatist": ["coin collector", "numismatologist"],
    "nummulitidae": ["family nummulitidae"],
    "nuncio": ["papal nuncio"],
    "nuphar": ["genus nuphar"],
    "nuremberg": ["nurnberg"],
    "nureyev": ["rudolf nureyev"],
    "nurse practitioner": ["np", "nurse clinician"],
    "nurse shark": ["ginglymostoma cirratum"],
    "nursed": ["suckled"],
    "nursery": ["baby's room"],
    "nursing": ["breast feeding"],
    "nursing aide": ["nurse's aide"],
    "nursing school": ["school of nursing"],
    "nursling": ["nurseling", "suckling"],
    "nut-leaved screw tree": ["helicteres isora"],
    "nutgrass": ["cyperus rotundus", "nut grass", "nut sedge", "nutsedge"],
    "nuthatch": ["nutcracker"],
    "nutmeg": ["myristica fragrans", "nutmeg tree"],
    "nutmeg hickory": ["carya myristicaeformis", "carya myristiciformis"],
    "nutrient artery": ["arteria nutricia"],
    "nutrify": ["aliment", "nourish"],
    "nutriment": ["aliment", "alimentation", "nourishment", "nutrition", "sustenance", "victuals"],
    "nutritional": ["nutritionary"],
    "nutritiousness": ["nutritiveness"],
    "nuttall oak": ["nuttall's oak", "quercus nuttalli"],
    "nutter": ["wacko", "whacko"],
    "nutty": ["nutlike"],
    "nuytsia": ["genus nuytsia"],
    "nuzzle": ["nose"],
    "nyala": ["tragelaphus angasi"],
    "nybble": ["nibble"],
    "nyctaginaceae": ["allioniaceae", "family allioniaceae", "family nyctaginaceae", "four-o'clock family"],
    "nyctaginia": ["genus nyctaginia"],
    "nyctalopia": ["moon blindness", "night blindness"],
    "nyctanassa": ["genus nyctanassa"],
    "nyctereutes": ["genus nyctereutes"],
    "nycticebus": ["genus nycticebus"],
    "nycticorax": ["genus nycticorax"],
    "nyctimene": ["genus nyctimene"],
    "nylons": ["nylon stocking", "rayon stocking", "rayons", "silk stocking"],
    "nymph": ["houri"],
    "nymphaea": ["genus nymphaea"],
    "nymphaeaceae": ["family nymphaeaceae", "water-lily family"],
    "nymphalid": ["brush-footed butterfly", "four-footed butterfly", "nymphalid butterfly"],
    "nymphalidae": ["family nymphalidae"],
    "nymphalis": ["genus nymphalis"],
    "nymphicus": ["genus nymphicus"],
    "nymphomaniac": ["nympho"],
    "nymphomaniacal": ["nymphomaniac"],
    "nynorsk": ["landsmaal", "landsmal", "new norwegian"],
    "nyssa": ["genus nyssa"],
    "nyssaceae": ["family nyssaceae", "sour-gum family", "tupelo family"],
    "nystatin": ["mycostatin", "nystan"],
    "o'brien": ["edna o'brien"],
    "o'casey": ["sean o'casey"],
    "o'connor": ["flannery o'connor", "mary flannery o'connor"],
    "o'flaherty": ["liam o'flaherty"],
    "o'hara": ["john henry o'hara"],
    "o'keeffe": ["georgia okeeffe"],
    "o'neill": ["eugene gladstone o'neill", "eugene o'neill"],
    "o'toole": ["peter o'toole", "peter seamus o'toole"],
    "oahu": ["oahu island"],
    "oak": ["oak tree"],
    "oak fern": ["gymnocarpium dryopteris", "thelypteris dryopteris"],
    "oak-leaved goosefoot": ["chenopodium glaucum", "oakleaf goosefoot"],
    "oakley": ["annie oakley"],
    "oarfish": ["king of the herring", "regalecus glesne", "ribbonfish"],
    "oarsman": ["rower"],
    "oat cell carcinoma": ["small cell carcinoma"],
    "oates": ["titus oates"],
    "oath": ["swearing"],
    "oatmeal": ["burgoo"],
    "oaxaca": ["oaxaca de juarez"],
    "ob": ["ob river"],
    "obadiah": ["abdias"],
    "obbligato": ["obligato"],
    "obeah": ["obi"],
    "obeche": ["arere", "obechi", "samba", "triplochiton scleroxcylon"],
    "obedience": ["obeisance"],
    "obediently": ["yieldingly"],
    "obiter dictum": ["passing comment"],
    "obituary": ["necrology", "obit"],
    "object": ["physical object"],
    "object language": ["target language"],
    "object program": ["target program"],
    "object-oriented programming": ["object-oriented programing"],
    "object-oriented programming language": ["object-oriented programing language"],
    "objectionable": ["obnoxious"],
    "objective": ["object glass", "object lens", "objective lens"],
    "objectivity": ["objectiveness"],
    "objet d'art": ["art object", "piece"],
    "oblate": ["pumpkin-shaped"],
    "oblateness": ["ellipticity"],
    "oblation": ["offering"],
    "obligation": ["indebtedness"],
    "oblige": ["accommodate"],
    "obliger": ["accommodator"],
    "obligingly": ["accommodatingly"],
    "oblique": ["oblique case"],
    "oblique vein of the left atrium": ["vena obliqua atrii sinistri"],
    "obliquely": ["aslant", "athwart"],
    "obliterable": ["removable"],
    "obliterate": ["efface"],
    "oblivion": ["limbo"],
    "oblivious": ["unmindful"],
    "obliviousness": ["oblivion"],
    "obloquy": ["opprobrium"],
    "oboe": ["hautbois", "hautboy"],
    "obscenity": ["dirty word", "filth", "smut", "vulgarism"],
    "obscure": ["becloud", "befog", "cloud", "fog", "haze over", "mist", "obnubilate"],
    "obscureness": ["abstruseness", "obscurity", "reconditeness"],
    "obscurity": ["obscureness"],
    "obsequiously": ["servilely", "subserviently"],
    "obsequiousness": ["servility", "subservience"],
    "observant": ["observing"],
    "observantly": ["observingly"],
    "observation": ["reflection", "reflexion"],
    "observe": ["keep"],
    "observer": ["commentator"],
    "obsessed": ["possessed"],
    "obsession": ["fixation"],
    "obsessional": ["obsessive"],
    "obsessiveness": ["obsessivity"],
    "obsoleteness": ["superannuation"],
    "obstacle": ["obstruction"],
    "obstetric": ["obstetrical"],
    "obstetrical toad": ["alytes obstetricans", "midwife toad"],
    "obstetrician": ["accoucheur"],
    "obstetrics": ["midwifery", "ob", "tocology"],
    "obstreperously": ["clamorously", "loudly"],
    "obstruct": ["block", "blockade", "embarrass", "hinder", "stymie", "stymy"],
    "obstruction": ["blockage"],
    "obstructionist": ["obstructer", "obstructor", "resister", "thwarter"],
    "obstructively": ["hinderingly"],
    "obtainment": ["obtention"],
    "obtrusive": ["noticeable"],
    "obturator vein": ["vena obturatoria"],
    "obtuse": ["purblind"],
    "obtuse triangle": ["obtuse-angled triangle"],
    "obviate": ["eliminate", "rid of"],
    "obviation": ["forestalling", "preclusion"],
    "obviously": ["apparently", "evidently", "manifestly", "patently", "plain", "plainly"],
    "obviousness": ["noticeability", "noticeableness", "patency"],
    "oca": ["oka", "oxalis crenata", "oxalis tuberosa"],
    "ocarina": ["sweet potato"],
    "occam": ["ockham", "william of occam", "william of ockham"],
    "occam's razor": ["law of parsimony", "ockham's razor", "principle of parsimony"],
    "occasionally": ["at times", "from time to time", "now and again", "now and then", "on occasion", "once in a while"],
    "occidental": ["hesperian"],
    "occidentalize": ["occidentalise", "westernise", "westernize"],
    "occipital lobe": ["occipital cortex"],
    "occipital vein": ["vena occipitalis"],
    "occluded": ["sorbed"],
    "occluded front": ["occlusion"],
    "occult": ["occult arts"],
    "occupancy": ["tenancy"],
    "occupation": ["military control"],
    "occupation license": ["occupation licence"],
    "occupational disease": ["industrial disease"],
    "occupational group": ["vocation"],
    "occupational safety and health act": ["federal job safety law"],
    "occupational safety and health administration": ["osha"],
    "occupied": ["tenanted"],
    "occupy": ["fill"],
    "occur": ["come"],
    "ocean": ["sea"],
    "ocean floor": ["davy jones", "davy jones's locker", "ocean bottom", "sea bottom", "sea floor", "seabed"],
    "ocean pout": ["macrozoarces americanus"],
    "ocean sunfish": ["headfish", "mola", "sunfish"],
    "ocean trip": ["voyage"],
    "oceangoing": ["seafaring", "seagoing"],
    "oceania": ["oceanica"],
    "oceanic": ["eastern malayo-polynesian"],
    "oceanites": ["genus oceanites"],
    "oceanography": ["oceanology"],
    "ocellated turkey": ["agriocharis ocellata"],
    "ocelot": ["felis pardalis", "panther cat"],
    "ocher": ["ochre"],
    "ochna": ["genus ochna"],
    "ochnaceae": ["family ochnaceae", "ochna family"],
    "ochoa": ["severo ochoa"],
    "ochotona": ["genus ochotona"],
    "ochotonidae": ["family ochotonidae"],
    "ochroma": ["genus ochroma"],
    "ochs": ["adolph simon ochs"],
    "ocimum": ["genus ocimum"],
    "oconee bells": ["shortia galacifolia"],
    "ocotillo": ["coachwhip", "fouquieria splendens", "jacob's staff", "vine cactus"],
    "octal numeration system": ["octal number system"],
    "octane number": ["octane rating"],
    "octangular": ["octagonal"],
    "octave": ["musical octave"],
    "octavo": ["8vo", "eightvo"],
    "octet": ["octette"],
    "october": ["oct"],
    "octopoda": ["order octopoda"],
    "octopodidae": ["family octopodidae"],
    "octopus": ["devilfish"],
    "octuple": ["eight-fold", "eightfold"],
    "ocular": ["opthalmic", "optic", "optical"],
    "ocular muscle": ["eye muscle"],
    "oculomotor": ["nervus oculomotorius", "oculomotor nerve", "third cranial nerve"],
    "oculus dexter": ["od"],
    "oculus sinister": ["os"],
    "ocyurus": ["genus ocyurus"],
    "odd": ["unmatched", "unmated", "unpaired"],
    "odd-pinnate": ["imparipinnate"],
    "odd-toed ungulate": ["perissodactyl", "perissodactyl mammal"],
    "oddity": ["oddness"],
    "odds": ["betting odds"],
    "odds and ends": ["farrago", "gallimaufry", "hodgepodge", "hotchpotch", "melange", "mingle-mangle", "mishmash", "oddments", "omnium-gatherum", "ragbag"],
    "odds-maker": ["handicapper"],
    "oder": ["oder river"],
    "odessa": ["odesa"],
    "odets": ["clifford odets"],
    "odoacer": ["odovacar", "odovakar"],
    "odobenidae": ["family odobenidae"],
    "odobenus": ["genus odobenus"],
    "odocoileus": ["genus odocoileus"],
    "odometer": ["hodometer", "mileometer", "milometer"],
    "odonata": ["order odonata"],
    "odontoceti": ["suborder odontoceti"],
    "odontophorus": ["genus odontophorus"],
    "odoriferous": ["odorous"],
    "odorize": ["odourise", "scent"],
    "odorless": ["inodorous", "odourless"],
    "oecanthus": ["genus oecanthus"],
    "oedipus": ["king oedipus", "oedipus rex"],
    "oedipus complex": ["oedipal complex"],
    "oedogoniaceae": ["family oedogoniaceae"],
    "oedogoniales": ["order oedogoniales"],
    "oedogonium": ["genus oedogonium"],
    "oenanthe": ["genus oenanthe"],
    "oenothera": ["genus oenothera"],
    "oersted": ["hans christian oersted"],
    "oestridae": ["family hypodermatidae", "family oestridae", "hypodermatidae"],
    "oestrus": ["genus oestrus"],
    "oeuvre": ["body of work", "work"],
    "off": ["away"],
    "off and on": ["on and off"],
    "off the beaten track": ["out-of-the-way"],
    "off-center": ["off-centered"],
    "off-hand": ["ex tempore"],
    "off-limits": ["out-of-bounds"],
    "off-line equipment": ["auxiliary equipment"],
    "off-the-rack": ["off-the-peg", "off-the-shelf", "ready-to-wear"],
    "offenbach": ["jacques offenbach"],
    "offended": ["pained"],
    "offense": ["offence"],
    "offenseless": ["offenceless"],
    "offensive": ["violative"],
    "offensively": ["objectionably", "obnoxiously"],
    "offensiveness": ["distastefulness", "odiousness"],
    "offer": ["offer up"],
    "offerer": ["offeror"],
    "offhand": ["offhanded", "offhandedly"],
    "office": ["power"],
    "office building": ["office block"],
    "office of inspector general": ["oig"],
    "office of intelligence support": ["ois"],
    "office of management and budget": ["omb"],
    "office of naval intelligence": ["oni"],
    "officeholder": ["officer"],
    "officer": ["ship's officer"],
    "official": ["functionary"],
    "officialize": ["officialise"],
    "officiate": ["function"],
    "offish": ["standoffish"],
    "offprint": ["reprint", "separate"],
    "offset": ["countervail"],
    "offshore": ["seaward"],
    "offside": ["offsides"],
    "offspring": ["issue", "progeny"],
    "offstage": ["backstage"],
    "ogcocephalidae": ["family ogcocephalidae"],
    "ogden": ["c. k. ogden", "charles kay ogden"],
    "ogee": ["cyma reversa"],
    "ogee arch": ["keel arch"],
    "oglala": ["ogalala"],
    "ohio": ["ohio river"],
    "ohioan": ["buckeye"],
    "ohm": ["georg simon ohm"],
    "oil": ["oil color", "oil colour"],
    "oil burner": ["oil furnace"],
    "oil future": ["petroleum future"],
    "oil heater": ["kerosene heater", "kerosine heater", "oilstove"],
    "oil industry": ["oil business", "refining industry"],
    "oil lamp": ["kerosene lamp", "kerosine lamp"],
    "oil refinery": ["petroleum refinery"],
    "oil tanker": ["oiler", "tank ship", "tanker"],
    "oil well": ["oiler"],
    "oilbird": ["guacharo", "steatornis caripensis"],
    "oilfish": ["ruvettus pretiosus"],
    "oilseed": ["oil-rich seed"],
    "oilskin": ["slicker"],
    "ointment": ["balm", "salve", "unction", "unguent"],
    "ojibwa": ["chippewa", "ojibway"],
    "okapi": ["okapia johnstoni"],
    "okapia": ["genus okapia"],
    "okay": ["all right", "alright", "o.k."],
    "okeechobee": ["lake okeechobee"],
    "oken": ["lorenz oken", "lorenz okenfuss", "okenfuss"],
    "okinawa": ["okinawa campaign"],
    "oklahoma": ["ok", "sooner state"],
    "oklahoma city": ["capital of oklahoma"],
    "oklahoman": ["sooner"],
    "okra": ["abelmoschus esculentus", "gumbo", "hibiscus esculentus", "lady's-finger", "okra plant"],
    "oktoberfest": ["octoberfest"],
    "ola": ["olla"],
    "olaf ii": ["olav ii", "saint olaf", "saint olav", "st. olaf", "st. olav"],
    "old": ["older"],
    "old age": ["age", "eld", "geezerhood", "years"],
    "old boy": ["old man"],
    "old church slavonic": ["church slavic", "old bulgarian", "old church slavic"],
    "old english": ["anglo-saxon"],
    "old english sheepdog": ["bobtail"],
    "old growth": ["virgin forest"],
    "old man": ["graybeard", "greybeard", "methuselah"],
    "old man of the mountain": ["alpine sunflower", "hymenoxys grandiflora", "tetraneuris grandiflora"],
    "old squaw": ["clangula hyemalis", "oldwife"],
    "old style": ["old style font"],
    "old world beaver": ["castor fiber"],
    "old world buffalo": ["buffalo"],
    "old world chat": ["chat"],
    "old world coot": ["fulica atra"],
    "old world crayfish": ["ecrevisse"],
    "old world flycatcher": ["flycatcher", "true flycatcher"],
    "old world hop hornbeam": ["ostrya carpinifolia"],
    "old world least weasel": ["mustela nivalis"],
    "old world monkey": ["catarrhine"],
    "old world oriole": ["oriole"],
    "old world scops owl": ["otus scops"],
    "old world warbler": ["true warbler"],
    "old world white pelican": ["pelecanus onocrotalus"],
    "old world yew": ["english yew", "taxus baccata"],
    "old-age pension": ["retirement benefit", "retirement check", "retirement fund", "retirement pension", "superannuation"],
    "old-maidish": ["old-womanish"],
    "old-man-of-the-woods": ["strobilomyces floccopus"],
    "old-time": ["olde worlde", "quaint"],
    "old-timer": ["antique", "gaffer", "old geezer", "oldtimer"],
    "oldenburg": ["claes oldenburg", "claes thure oldenburg"],
    "oldfield": ["barney oldfield", "berna eli oldfield"],
    "oldie": ["golden oldie"],
    "oldline": ["old-line"],
    "oldster": ["golden ager", "old person", "senior citizen"],
    "olea": ["genus olea"],
    "oleaceae": ["family oleaceae", "olive family"],
    "oleales": ["order oleales"],
    "oleander": ["nerium oleander", "rose bay"],
    "oleander fern": ["oleandra mollis", "oleandra neriiformis"],
    "oleandra": ["genus oleandra"],
    "oleandraceae": ["family oleandraceae"],
    "olearia": ["genus olearia"],
    "olecranon": ["olecranon process"],
    "olfactory": ["olfactive"],
    "olfactory nerve": ["first cranial nerve", "nervii olfactorii"],
    "olfactory property": ["aroma", "odor", "odour", "scent", "smell"],
    "olfersia": ["genus olfersia"],
    "oligarchic": ["oligarchical"],
    "oligocene": ["oligocene epoch"],
    "oligochaeta": ["class oligochaeta"],
    "oligochaete": ["oligochaete worm"],
    "oligodendroglia": ["oligodendria"],
    "oligoplites": ["genus oligoplites"],
    "oligoporus": ["genus oligoporus"],
    "olive": ["european olive tree", "olea europaea"],
    "olive drab": ["drab"],
    "olive green": ["olive-green"],
    "olive-colored": ["olive-coloured"],
    "olive-drab": ["drab"],
    "olive-grey": ["olive-gray"],
    "olive-tree agaric": ["pleurotus phosphoreus"],
    "olivelike": ["olive-like"],
    "oliver": ["joseph oliver", "king oliver"],
    "olivier": ["baron olivier of birghton", "laurence olivier", "sir laurence kerr olivier"],
    "olla podrida": ["spanish burgoo"],
    "olm": ["proteus anguinus"],
    "olmsted": ["frederick law olmsted"],
    "olympia": ["capital of washington"],
    "olympian": ["olympic god"],
    "olympian games": ["olympic games"],
    "olympic games": ["olympiad", "olympics"],
    "olympic salamander": ["rhyacotriton olympicus"],
    "olympus": ["mount olympus", "mt. olympus", "olimbos"],
    "omaha": ["maha"],
    "oman": ["muscat and oman", "sultanate of oman"],
    "ombu": ["bella sombra", "phytolacca dioica"],
    "omdurman": ["battle of omdurman"],
    "omega-3 fatty acid": ["omega-3"],
    "omega-6 fatty acid": ["omega-6"],
    "omelet": ["omelette"],
    "omelet pan": ["omelette pan"],
    "omen": ["portent", "presage", "prodigy", "prognostic", "prognostication"],
    "omeprazole": ["prilosec"],
    "omission": ["deletion"],
    "omnidirectional antenna": ["nondirectional antenna"],
    "omnipresent": ["ubiquitous"],
    "omnirange": ["omnidirectional radio range", "omnidirectional range"],
    "omomyid": ["omomyid group"],
    "omphaloskepsis": ["navel-gazing"],
    "omphalotus": ["genus omphalotus"],
    "on guard": ["on one's guard", "on your guard", "upon one's guard"],
    "on paper": ["in writing"],
    "on the average": ["on average"],
    "on the coattails": ["one one's coattails"],
    "on the fence": ["undecided"],
    "on the nose": ["on the button"],
    "on the one hand": ["on one hand"],
    "on the other hand": ["but then", "then again"],
    "on the road": ["on tour"],
    "on the spur of the moment": ["suddenly"],
    "on the way": ["en route"],
    "on-key": ["true"],
    "on-line": ["online"],
    "on-the-spot": ["on-the-scene"],
    "onager": ["equus hemionus"],
    "onagraceae": ["evening-primrose family", "family onagraceae"],
    "once": ["at one time", "erst", "erstwhile", "formerly"],
    "once-over": ["look-over"],
    "onchocerciasis": ["river blindness"],
    "oncidium": ["butterfly orchid", "butterfly plant", "dancing lady orchid"],
    "oncogene": ["transforming gene"],
    "oncological": ["oncologic"],
    "oncorhynchus": ["genus oncorhynchus"],
    "ondaatje": ["michael ondaatje", "philip michael ondaatje"],
    "ondatra": ["genus ondatra"],
    "one": ["ace", "single", "unity"],
    "one by one": ["one after another", "one at a time"],
    "one hundred eighty": ["180", "clxxx"],
    "one hundred fifteen": ["115", "cxv"],
    "one hundred fifty": ["150", "cl"],
    "one hundred fifty-five": ["155", "clv"],
    "one hundred five": ["105", "cv"],
    "one hundred forty": ["140", "cxl"],
    "one hundred forty-five": ["145", "cxlv"],
    "one hundred ninety": ["190", "xcl"],
    "one hundred seventy": ["170", "clxx"],
    "one hundred seventy-five": ["175", "clxxv"],
    "one hundred sixty": ["160", "clx"],
    "one hundred sixty-five": ["165", "clxv"],
    "one hundred ten": ["110", "cx"],
    "one hundred thirty": ["130", "cxxx"],
    "one hundred thirty-five": ["135", "cxxxv"],
    "one hundred twenty": ["120", "cxx"],
    "one hundred twenty-five": ["125", "cxxv"],
    "one-billionth": ["billionth"],
    "one-dimensionality": ["linearity"],
    "one-eighth": ["eighth"],
    "one-fifth": ["fifth", "fifth part", "twenty percent"],
    "one-flowered wintergreen": ["moneses uniflora", "one-flowered pyrola", "pyrola uniflora"],
    "one-fourth": ["fourth", "fourth part", "one-quarter", "quarter", "quartern", "twenty-five percent"],
    "one-half": ["half"],
    "one-hitter": ["1-hitter"],
    "one-humped": ["single-humped"],
    "one-hundredth": ["hundredth", "one percent"],
    "one-man": ["one-person", "one-woman"],
    "one-millionth": ["millionth"],
    "one-ninth": ["ninth"],
    "one-on-one": ["person-to-person"],
    "one-quadrillionth": ["quadrillionth"],
    "one-quintillionth": ["quintillionth"],
    "one-seventh": ["seventh"],
    "one-sixteenth": ["sixteenth", "sixteenth part"],
    "one-sixth": ["sixth"],
    "one-sixtieth": ["sixtieth"],
    "one-sixty-fourth": ["sixty-fourth"],
    "one-ten-thousandth": ["ten-thousandth"],
    "one-tenth": ["ten percent", "tenth", "tenth part"],
    "one-third": ["third", "tierce"],
    "one-thirty-second": ["thirty-second", "thirty-second part"],
    "one-thousandth": ["thousandth"],
    "one-trillionth": ["trillionth"],
    "one-twelfth": ["duodecimal", "twelfth", "twelfth part"],
    "one-way light time": ["owlt"],
    "oneness": ["unity"],
    "ongoing": ["on-going"],
    "onion": ["allium cepa", "onion plant"],
    "onion mildew": ["peronospora destructor"],
    "onion smut": ["urocystis cepulae"],
    "onion stem": ["lepiota cepaestipes"],
    "onion thrips": ["onion louse", "thrips tobaci"],
    "onionskin": ["flimsy"],
    "oniscidae": ["family oniscidae"],
    "oniscus": ["genus oniscus"],
    "onlooker": ["looker-on"],
    "only": ["only if", "only when"],
    "ono": ["yoko ono"],
    "onobrychis": ["genus onobrychis"],
    "onoclea": ["genus onoclea"],
    "onomatopoeic": ["onomatopoetic"],
    "ononis": ["genus ononis"],
    "onopordum": ["genus onopordon", "genus onopordum", "onopordon"],
    "onosmodium": ["genus onosmodium"],
    "onsager": ["lars onsager"],
    "onset": ["oncoming"],
    "onychium": ["genus onychium"],
    "onychogalea": ["genus onychogalea"],
    "onychomys": ["genus onychomys"],
    "onychophora": ["class onychophora"],
    "onychophoran": ["peripatus", "velvet worm"],
    "ooh": ["aah"],
    "oomycetes": ["class oomycetes"],
    "oophorectomy": ["ovariectomy"],
    "oort": ["jan hendrix oort"],
    "oozing": ["oozy", "seeping"],
    "opacity": ["opaqueness"],
    "opah": ["lampris regius", "moonfish"],
    "opal glass": ["milk glass"],
    "opalescence": ["iridescence"],
    "opalize": ["opalise"],
    "opaque": ["unintelligible"],
    "opel": ["wilhelm von opel"],
    "open": ["open up"],
    "open fire": ["fire"],
    "open frame": ["break"],
    "open interval": ["unbounded interval"],
    "open-air market": ["market square", "open-air marketplace"],
    "open-door policy": ["open door"],
    "open-end credit": ["charge account credit", "revolving credit"],
    "open-end wrench": ["tappet wrench"],
    "open-face sandwich": ["open sandwich"],
    "opencast": ["opencut"],
    "opening": ["gap"],
    "openness": ["nakedness"],
    "openside plane": ["rabbet plane"],
    "opepe": ["nauclea diderrichii", "sarcocephalus diderrichii"],
    "opera": ["opera house"],
    "opera cloak": ["opera hood"],
    "opera star": ["operatic star"],
    "operable": ["practicable"],
    "operate": ["run"],
    "operate on": ["operate"],
    "operating capability": ["performance capability"],
    "operating expense": ["budget items", "operating cost", "overhead"],
    "operating room": ["operating theater", "operating theatre", "or", "surgery"],
    "operating system": ["os"],
    "operation": ["functioning", "performance"],
    "operation code": ["order code"],
    "operational": ["in operation", "operating"],
    "operational damage": ["operational casualty"],
    "operations": ["trading operations"],
    "operator": ["manipulator"],
    "operculate": ["operculated"],
    "operetta": ["light opera"],
    "opheodrys": ["genus opheodrys"],
    "ophidiidae": ["family ophidiidae"],
    "ophiodon": ["genus ophiodon"],
    "ophiodontidae": ["family ophiodontidae"],
    "ophioglossaceae": ["family ophioglossaceae"],
    "ophioglossales": ["order ophioglossales"],
    "ophioglossum": ["genus ophioglossum"],
    "ophiolatry": ["serpent-worship"],
    "ophiophagus": ["genus ophiophagus"],
    "ophisaurus": ["genus ophisaurus"],
    "ophiurida": ["subclass ophiurida"],
    "ophiuroidea": ["class ophiuroidea"],
    "ophrys": ["genus ophrys"],
    "ophthalmia": ["ophthalmitis"],
    "ophthalmic artery": ["arteria ophthalmica"],
    "ophthalmic vein": ["vena ophthalmica"],
    "ophthalmologist": ["eye doctor", "oculist"],
    "opine": ["animadvert", "sound off", "speak out", "speak up"],
    "opinion": ["view"],
    "opinionated": ["opinionative", "self-opinionated"],
    "opisthobranchia": ["subclass opisthobranchia"],
    "opisthocomidae": ["family opisthocomidae"],
    "opisthocomus": ["genus opisthocomus"],
    "opisthognathidae": ["family opisthognathidae"],
    "opium addict": ["opium taker"],
    "opium poppy": ["papaver somniferum"],
    "opossum": ["possum"],
    "oppenheimer": ["robert oppenheimer"],
    "opponent": ["opposing"],
    "opportuneness": ["patness", "timeliness"],
    "opportunism": ["expedience", "self-interest", "self-seeking"],
    "opportunist": ["self-seeker"],
    "opportunity": ["chance"],
    "opposable": ["apposable"],
    "oppose": ["counterbalance"],
    "opposite": ["paired"],
    "opposition": ["oppositeness"],
    "oppress": ["crush", "suppress"],
    "oppression": ["oppressiveness"],
    "oppressive": ["tyrannical", "tyrannous"],
    "opsonization": ["opsonisation"],
    "opt out": ["cop out"],
    "optative mood": ["optative"],
    "optic chiasma": ["chiasma opticum", "optic chiasm"],
    "optic cup": ["eyecup"],
    "optic nerve": ["nervus opticus", "optic tract", "second cranial nerve"],
    "optic radiation": ["radiatio optica"],
    "optical crown": ["crown glass", "optical crown glass"],
    "optical density": ["absorbance", "photographic density", "transmission density"],
    "optical disk": ["optical disc"],
    "optical fiber": ["glass fiber", "glass fibre", "optical fibre"],
    "optical flint": ["flint glass"],
    "optical pyrometer": ["pyroscope"],
    "optician": ["lens maker"],
    "optimization": ["optimisation"],
    "optimize": ["optimise"],
    "optimum": ["optimal"],
    "option": ["alternative", "choice"],
    "optometrist": ["oculist"],
    "opuntia": ["genus opuntia"],
    "opuntiales": ["order opuntiales"],
    "or circuit": ["or gate"],
    "orach": ["orache"],
    "oral": ["oral exam", "oral examination", "viva", "viva voce"],
    "oral herpes": ["cold sore", "fever blister", "herpes labialis"],
    "oral sex": ["head"],
    "oral stage": ["oral phase"],
    "orally": ["by word of mouth"],
    "orange": ["orange tree"],
    "orange bat": ["orange horseshoe bat", "rhinonicteris aurantius"],
    "orange daisy": ["erigeron aurantiacus", "orange fleabane"],
    "orange grass": ["hypericum gentianoides", "nitweed", "pine-weed", "pineweed"],
    "orange group": ["ov"],
    "orange hawkweed": ["hieracium aurantiacum", "pilosella aurantiaca"],
    "orange milkwort": ["candyweed", "polygala lutea", "yellow bachelor's button", "yellow milkwort"],
    "orange order": ["association of orangemen"],
    "orange peel": ["orange rind"],
    "orange pekoe": ["pekoe"],
    "orange sneezeweed": ["helenium hoopesii", "owlclaws"],
    "orange tortrix": ["argyrotaenia citrana", "tortrix"],
    "orange yellow": ["saffron"],
    "orange-blossom orchid": ["sarcochilus falcatus"],
    "orange-colored": ["orange-coloured", "orange-hued"],
    "orange-red": ["orangish-red"],
    "orangutan": ["orang", "orangutang", "pongo pygmaeus"],
    "orator": ["public speaker", "rhetorician", "speechifier", "speechmaker"],
    "orb": ["orbit", "revolve"],
    "orbiculate": ["orbicular"],
    "orbignya": ["genus orbignya"],
    "orbison": ["roy orbison"],
    "orbit": ["electron orbit"],
    "orbital rotation": ["orbital motion"],
    "orbitale": ["orbital point"],
    "orchard grass": ["cocksfoot", "cockspur", "dactylis glomerata"],
    "orchard oriole": ["icterus spurius"],
    "orchestia": ["genus orchestia"],
    "orchestiidae": ["family orchestiidae"],
    "orchestra pit": ["pit"],
    "orchestration": ["instrumentation"],
    "orchid": ["orchidaceous plant"],
    "orchidaceae": ["family orchidaceae", "orchid family"],
    "orchidales": ["order orchidales"],
    "orchidectomy": ["orchiectomy"],
    "orchil": ["archil", "cudbear"],
    "orcinus": ["genus orcinus"],
    "orczy": ["baroness emmusca orczy"],
    "ord kangaroo rat": ["dipodomys ordi"],
    "ordain": ["enact"],
    "ordeal": ["trial by ordeal"],
    "order": ["dictate", "prescribe"],
    "order myxobacteria": ["myxobacterales", "myxobacteriales", "order myxobacterales", "order myxobacteriales"],
    "order of magnitude": ["magnitude"],
    "order of the purple heart": ["purple heart"],
    "order paper": ["order book"],
    "orderer": ["systematiser", "systematist", "systematizer", "systemiser", "systemizer"],
    "ordering": ["order", "ordination"],
    "orderliness": ["order"],
    "orderly": ["hospital attendant"],
    "ordinal number": ["no.", "ordinal"],
    "ordinariness": ["mundaneness", "mundanity"],
    "ordinary": ["ordinary bicycle"],
    "ordination": ["ordinance"],
    "ordovician": ["ordovician period"],
    "oreamnos": ["genus oreamnos"],
    "orectolobidae": ["family orectolobidae"],
    "orectolobus": ["genus orectolobus"],
    "oregano": ["marjoram", "origanum vulgare", "pot marjoram", "wild marjoram", "winter sweet"],
    "oregon": ["beaver state", "or"],
    "oregon ash": ["fraxinus latifolia", "fraxinus oregona"],
    "oregon cedar": ["chamaecyparis lawsoniana", "lawson's cedar", "lawson's cypress", "port orford cedar"],
    "oregon crab apple": ["malus fusca"],
    "oregon grape": ["mahonia nervosa"],
    "oregon maple": ["acer macrophyllum", "big-leaf maple"],
    "oregon white oak": ["garry oak", "oregon oak", "quercus garryana"],
    "oregonian": ["beaver"],
    "oreo": ["oreo cookie"],
    "oreopteris": ["genus oreopteris"],
    "oreortyx": ["genus oreortyx"],
    "orff": ["carl orff"],
    "organ": ["pipe organ"],
    "organ pipe": ["pipe", "pipework"],
    "organdy": ["organdie"],
    "organelle": ["cell organ", "cell organelle"],
    "organic": ["organic fertiliser", "organic fertilizer"],
    "organic light-emitting diode": ["oled"],
    "organic process": ["biological process"],
    "organism": ["being"],
    "organismal": ["organismic"],
    "organization": ["organisation"],
    "organization for the prohibition of chemical weapons": ["opcw"],
    "organization of american states": ["oas"],
    "organization of petroleum-exporting countries": ["opec"],
    "organizational": ["organisational"],
    "organize": ["organise"],
    "organized": ["organised", "unionised", "unionized"],
    "organized crime": ["gangdom", "gangland"],
    "organizer": ["labor organizer", "organiser"],
    "orgasm": ["climax", "coming", "sexual climax"],
    "orgy": ["binge", "splurge"],
    "oriel": ["oriel window"],
    "orient": ["point"],
    "oriental": ["oriental person"],
    "oriental arborvitae": ["platycladus orientalis", "thuja orientalis"],
    "oriental beetle": ["anomala orientalis", "asiatic beetle"],
    "oriental cherry": ["japanese cherry", "japanese flowering cherry", "prunus serrulata"],
    "oriental cockroach": ["asiatic cockroach", "blackbeetle", "blatta orientalis", "oriental roach"],
    "oriental plane": ["platanus orientalis"],
    "oriental poppy": ["papaver orientale"],
    "oriental scops owl": ["otus sunia"],
    "oriental spruce": ["picea orientalis"],
    "orientalism": ["oriental studies"],
    "orientalize": ["orientalise"],
    "orientation course": ["orientation"],
    "oriented": ["orientated"],
    "orienting": ["orientating"],
    "orifice": ["opening", "porta"],
    "origin": ["inception", "origination"],
    "original": ["archetype", "pilot"],
    "originate": ["arise", "develop", "grow", "rise", "spring up", "uprise"],
    "originator": ["conceiver", "mastermind"],
    "orinasal phone": ["orinasal"],
    "orinoco": ["orinoco river"],
    "oriolidae": ["family oriolidae"],
    "oriolus": ["genus oriolus"],
    "orion": ["hunter"],
    "orites": ["genus orites"],
    "orleans": ["siege of orleans"],
    "orlop deck": ["fourth deck", "orlop"],
    "ormandy": ["eugene ormandy"],
    "ormazd": ["ahura mazda", "ormuzd"],
    "ormer": ["haliotis tuberculata", "sea-ear"],
    "ormosia": ["genus ormosia"],
    "ornamentation": ["embellishment"],
    "ornateness": ["elaborateness"],
    "ornithischia": ["order ornithischia"],
    "ornithischian": ["ornithischian dinosaur"],
    "ornithogalum": ["genus ornithogalum"],
    "ornithologist": ["bird watcher"],
    "ornithomimida": ["suborder ornithomimida"],
    "ornithopod": ["ornithopod dinosaur"],
    "ornithorhynchidae": ["family ornithorhynchidae"],
    "ornithorhynchus": ["genus ornithorhynchus"],
    "orobanchaceae": ["broomrape family", "family orobanchaceae"],
    "oroide": ["oreide"],
    "orology": ["orography"],
    "orontium": ["genus orontium"],
    "orotund": ["pear-shaped", "rotund", "round"],
    "orozco": ["jose clemente orozco", "jose orozco"],
    "orphanage": ["orphanhood"],
    "orphenadrine": ["norflex"],
    "orpine": ["live-forever", "livelong", "orpin", "sedum telephium"],
    "orr": ["bobby orr", "robert orr"],
    "orrisroot": ["orris"],
    "ortalis": ["genus ortalis"],
    "ortega": ["daniel ortega", "daniel ortega saavedra"],
    "ortega y gasset": ["jose ortega y gasset"],
    "orthicon": ["image orthicon"],
    "orthilia": ["genus orthilia"],
    "orthodontics": ["dental orthopaedics", "dental orthopedics", "orthodontia", "orthodonture"],
    "orthodox": ["eastern orthodox", "greek orthodox", "russian orthodox"],
    "orthodox church": ["eastern church", "eastern orthodox", "eastern orthodox church", "orthodox catholic church"],
    "orthodox judaism": ["jewish orthodoxy"],
    "orthodox sleep": ["nonrapid eye movement", "nonrapid eye movement sleep", "nrem", "nrem sleep"],
    "orthogonal": ["rectangular"],
    "orthogonality": ["orthogonal opposition", "perpendicularity"],
    "orthography": ["writing system"],
    "orthopedic": ["orthopaedic", "orthopedical"],
    "orthopedics": ["orthopaedics"],
    "orthopedist": ["orthopaedist"],
    "orthopristis": ["genus orthopristis"],
    "orthopter": ["ornithopter"],
    "orthoptera": ["order orthoptera"],
    "orthopterous insect": ["orthopteran", "orthopteron"],
    "orthostatic hypotension": ["postural hypotension"],
    "orthotomus": ["genus orthotomus"],
    "ortolan": ["emberiza hortulana", "ortolan bunting"],
    "orwell": ["eric arthur blair", "eric blair", "george orwell"],
    "orycteropodidae": ["family orycteropodidae"],
    "orycteropus": ["genus orycteropus"],
    "oryctolagus": ["genus oryctolagus"],
    "oryx": ["pasang"],
    "oryza": ["genus oryza"],
    "oryzomys": ["genus oryzomys"],
    "oryzopsis": ["genus oryzopsis"],
    "osage": ["osage river"],
    "osage orange": ["bow wood", "maclura pomifera", "mock orange"],
    "osborne": ["john james osborne", "john osborne"],
    "oscheocele": ["oscheocoele"],
    "oscillate": ["vibrate"],
    "oscillation": ["vibration"],
    "oscillatoriaceae": ["family oscillatoriaceae"],
    "oscillatory": ["oscillating"],
    "oscilloscope": ["cathode-ray oscilloscope", "cro", "scope"],
    "oscine": ["oscine bird"],
    "oscines": ["passeres", "suborder oscines", "suborder passeres"],
    "oscitancy": ["oscitance"],
    "oslo": ["capital of norway", "christiania"],
    "osman i": ["othman i"],
    "osmanthus": ["genus osmanthus"],
    "osmeridae": ["family osmeridae"],
    "osmerus": ["genus osmerus"],
    "osmiridium": ["iridosmine"],
    "osmium": ["atomic number 76", "os"],
    "osmundaceae": ["family osmundaceae"],
    "osprey": ["fish eagle", "fish hawk", "pandion haliaetus", "sea eagle"],
    "osseous": ["bony", "osteal"],
    "ossicle": ["bonelet", "ossiculum"],
    "ossicular": ["ossiculate"],
    "ossification": ["conformity"],
    "ostariophysi": ["order ostariophysi"],
    "osteichthyes": ["class osteichthyes"],
    "ostensible": ["ostensive"],
    "ostentation": ["fanfare", "flash"],
    "ostentatious": ["pretentious"],
    "ostentatiously": ["showily"],
    "osteoarthritis": ["degenerative arthritis", "degenerative joint disease"],
    "osteoblast": ["bone-forming cell"],
    "osteoglossidae": ["family osteoglossidae"],
    "osteoglossiformes": ["order osteoglossiformes"],
    "osteologist": ["osteologer"],
    "osteopath": ["osteopathist"],
    "osteopetrosis": ["albers-schonberg disease", "marble bones disease"],
    "osteosarcoma": ["osteogenic sarcoma"],
    "osteostracan": ["cephalaspid"],
    "osteostraci": ["cephalaspida", "suborder cephalaspida", "suborder osteostraci"],
    "ostraciidae": ["family ostraciidae", "family ostraciontidae"],
    "ostracize": ["ostracise"],
    "ostracoda": ["subclass ostracoda"],
    "ostracodermi": ["order ostracodermi"],
    "ostrea": ["genus ostrea"],
    "ostreidae": ["family ostreidae"],
    "ostrich": ["struthio camelus"],
    "ostrich fern": ["fiddlehead", "matteuccia struthiopteris", "onoclea struthiopteris", "pteretis struthiopteris", "shuttlecock fern"],
    "ostrya": ["genus ostrya"],
    "ostryopsis": ["genus ostryopsis"],
    "ostwald": ["wilhelm ostwald"],
    "ostyak": ["khanty"],
    "oswald": ["lee harvey oswald"],
    "otaheite arrowroot": ["otaheite arrowroot starch"],
    "otaria": ["genus otaria"],
    "otariidae": ["family otariidae"],
    "otherness": ["distinctness", "separateness"],
    "otic": ["auricular"],
    "otic ganglion": ["otoganglion"],
    "otides": ["suborder otides"],
    "otididae": ["family otididae"],
    "otiose": ["pointless", "purposeless", "senseless", "superfluous", "wasted"],
    "otis": ["elisha graves otis"],
    "oto": ["otoe"],
    "otoscope": ["auriscope", "auroscope"]
}
