synonyms = {
    "airedale": ["airedale terrier"],
    "airfield": ["field", "flying field", "landing field"],
    "airflow": ["air flow", "flow of air"],
    "airfoil": ["aerofoil", "control surface", "surface"],
    "airheaded": ["dizzy", "empty-headed", "featherbrained", "giddy", "light-headed", "lightheaded", "silly"],
    "airiness": ["buoyancy"],
    "airless": ["close", "stuffy", "unaired"],
    "airlift": ["lift"],
    "airline": ["air hose"],
    "airlock": ["air lock"],
    "airmail": ["airpost"],
    "airmail letter": ["aerogram", "aerogramme", "air letter"],
    "airplane": ["aeroplane", "plane"],
    "airplane propeller": ["airscrew", "prop"],
    "airport": ["aerodrome", "airdrome", "drome"],
    "airs": ["pose"],
    "airship": ["dirigible"],
    "airsick": ["air sick", "carsick", "seasick"],
    "airsickness": ["air sickness"],
    "airspace": ["air space"],
    "airstrip": ["flight strip", "landing strip", "strip"],
    "airtight": ["air-tight"],
    "airy": ["impractical", "laputan", "visionary", "windy"],
    "aisle": ["gangway"],
    "aix": ["genus aix"],
    "aizoaceae": ["carpetweed family", "family aizoaceae", "family tetragoniaceae", "tetragoniaceae"],
    "ajaia": ["genus ajaia"],
    "ajuga": ["genus ajuga"],
    "akaryocyte": ["acaryote", "akaryote"],
    "akee": ["akee tree", "blighia sapida"],
    "akeridae": ["family akeridae"],
    "akhenaton": ["akhenaten", "amenhotep iv", "ikhanaton"],
    "akin": ["kindred"],
    "akinesis": ["akinesia"],
    "aksa martyrs brigades": ["al-aksa martyrs brigades", "martyrs of al-aqsa"],
    "al aqabah": ["akaba", "aqaba"],
    "al itihaad al islamiya": ["aiai", "al-itihaad al-islamiya", "islamic unity"],
    "al ladhiqiyah": ["latakia"],
    "al sunna wal jamma": ["followers of the phrophet"],
    "al-fatah": ["al-asifa", "fatah"],
    "al-gama'a al-islamiyya": ["islamic group"],
    "al-jihad": ["egyptian islamic jihad", "islamic jihad", "vanguards of conquest"],
    "al-qaeda": ["al-qa'ida", "al-qaida", "base", "qaeda"],
    "al-tawhid": ["al tawhid", "divine unity"],
    "alabama": ["alabama river"],
    "alabaman": ["alabamian"],
    "alabaster": ["mexican onyx", "onyx marble", "oriental alabaster"],
    "alacrity": ["briskness", "smartness"],
    "aland islands": ["aaland islands", "ahvenanmaa"],
    "alar": ["daminozide"],
    "alarm": ["alert"],
    "alarm clock": ["alarm"],
    "alaska": ["ak", "last frontier"],
    "alaska fur seal": ["callorhinus ursinus"],
    "alaska king crab": ["alaska crab", "alaskan king crab", "king crab"],
    "alaska native": ["alaskan native", "native alaskan"],
    "alaska rein orchid": ["habenaria unalascensis"],
    "alaska standard time": ["yukon time"],
    "alaskan brown bear": ["kodiak", "kodiak bear", "ursus arctos middendorffi", "ursus middendorffi"],
    "alaskan pipeline": ["trans-alaska pipeline"],
    "alastrim": ["cuban itch", "kaffir pox", "milk pox", "pseudosmallpox", "pseudovariola", "variola minor", "west indian smallpox", "white pox"],
    "alate": ["alated"],
    "alauda": ["genus alauda"],
    "alaudidae": ["family alaudidae"],
    "albacore": ["long-fin tunny", "thunnus alalunga"],
    "albania": ["republic of albania"],
    "albany": ["capital of new york"],
    "albatrellus": ["genus albatrellus"],
    "albatrellus ovinus": ["sheep polypore"],
    "albatross": ["millstone"],
    "albedo": ["reflective power"],
    "albee": ["edward albee", "edward franklin albeen"],
    "albers": ["josef albers"],
    "albert": ["albert francis charles augustus emmanuel", "prince albert"],
    "alberti": ["leon battista alberti"],
    "albigenses": ["cathari", "cathars"],
    "albigensianism": ["catharism"],
    "albinal": ["albinic", "albinistic", "albinotic"],
    "albite": ["white feldspar"],
    "albizzia": ["albizia"],
    "albright's disease": ["polyostotic fibrous dysplasia"],
    "albuginaceae": ["family albuginaceae"],
    "albugo": ["genus albugo"],
    "albula": ["genus albula"],
    "albulidae": ["family albulidae"],
    "album": ["record album"],
    "albumin": ["albumen"],
    "albuminuria": ["proteinuria"],
    "albuterol": ["proventil", "ventolin"],
    "alca": ["genus alca"],
    "alcaic": ["alcaic verse"],
    "alcea": ["genus alcea"],
    "alcedinidae": ["family alcedinidae"],
    "alcedo": ["genus alcedo"],
    "alcelaphus": ["genus alcelaphus"],
    "alces": ["genus alces"],
    "alchemic": ["alchemical"],
    "alchemistic": ["alchemistical"],
    "alchemize": ["alchemise"],
    "alcidae": ["family alcidae"],
    "alcohol": ["alcoholic beverage", "alcoholic drink", "inebriant", "intoxicant"],
    "alcohol abuse": ["alcoholic abuse", "alcoholism abuse"],
    "alcohol group": ["alcohol radical"],
    "alcohol thermometer": ["alcohol-in-glass thermometer"],
    "alcoholic": ["alky", "boozer", "dipsomaniac", "lush", "soaker", "souse"],
    "alcoholic dementia": ["alcohol amnestic disorder", "korsakoff's psychosis", "korsakoff's syndrome", "korsakov's psychosis", "korsakov's syndrome", "polyneuritic psychosis"],
    "alcoholics anonymous": ["aa"],
    "alcoholism": ["alcohol addiction", "drunkenness", "inebriation"],
    "alcoholize": ["alcoholise"],
    "alcott": ["louisa may alcott"],
    "alcove": ["bay"],
    "alcyonacea": ["suborder alcyonacea"],
    "alcyonaria": ["order alcyonaria"],
    "alcyone": ["halcyon"],
    "aldehyde group": ["aldehyde radical"],
    "alder": ["alder tree"],
    "alder buckthorn": ["alder dogwood", "rhamnus frangula"],
    "alderfly": ["alder fly", "sialis lutaria"],
    "alderleaf juneberry": ["alder-leaved serviceberry", "amelanchier alnifolia"],
    "aldermanic": ["aldermanly"],
    "aldol": ["aldehyde-alcohol"],
    "aldosteronism": ["hyperaldosteronism"],
    "aldrovanda": ["genus aldrovanda"],
    "alectis": ["genus alectis"],
    "alectoria": ["genus alectoria"],
    "alectoris": ["genus alectoris"],
    "alectura": ["genus alectura"],
    "alendronate": ["fosamax"],
    "aleph-null": ["aleph-nought", "aleph-zero"],
    "alepisaurus": ["genus alepisaurus"],
    "alert": ["qui vive"],
    "alertness": ["alerting"],
    "aletris": ["genus aletris"],
    "aleuria aurantia": ["orange peel fungus"],
    "aleurites": ["genus aleurites"],
    "aleut": ["aleutian"],
    "aleutian islands": ["aleutians"],
    "alewife": ["alosa pseudoharengus", "pomolobus pseudoharengus"],
    "alex boncayao brigade": ["abb", "revolutionary proletarian army", "rpa-abb"],
    "alexander": ["alexanders", "black lovage", "horse parsley", "smyrnium olusatrum"],
    "alexander i": ["aleksandr pavlovich", "czar alexander i"],
    "alexander ii": ["alexander the liberator", "czar alexander ii"],
    "alexander iii": ["czar alexander iii"],
    "alexander vi": ["borgia", "pope alexander vi", "rodrigo borgia"],
    "alexandria": ["el iskandriyah"],
    "alexandria senna": ["alexandrian senna", "cassia acutifolia", "cassia augustifolia", "indian senna", "senna alexandrina", "tinnevelly senna", "true senna"],
    "alexandrian laurel": ["calophyllum inophyllum"],
    "alexic": ["word-blind"],
    "aleyrodes": ["genus aleyrodes"],
    "aleyrodidae": ["family aleyrodidae"],
    "alfalfa": ["lucerne", "medicago sativa"],
    "alfred": ["alfred the great"],
    "alfresco": ["open-air"],
    "alga": ["algae"],
    "algarroba": ["algarobilla", "algarrobilla"],
    "algebraic": ["algebraical"],
    "alger": ["horatio alger"],
    "algeria": ["algerie", "democratic and popular republic of algeria"],
    "algerian dinar": ["dinar"],
    "algeripithecus": ["genus algeripithecus"],
    "algiers": ["algerian capital"],
    "algin": ["alginic acid"],
    "algolagnia": ["algophilia"],
    "algometric": ["algometrical"],
    "algonkian": ["algonkin"],
    "algonquian": ["algonquin"],
    "algorithm": ["algorithmic program", "algorithmic rule"],
    "algren": ["nelson algren"],
    "alhazen": ["al-hasan ibn al-haytham", "al-haytham", "alhacen", "ibn al-haytham"],
    "ali": ["cassius clay", "cassius marcellus clay", "muhammad ali"],
    "alias": ["assumed name", "false name"],
    "alidade": ["alidad"],
    "alien": ["alienate"],
    "alienage": ["alienism"],
    "alienated": ["anomic", "disoriented"],
    "alienation": ["estrangement"],
    "alienee": ["grantee"],
    "alight": ["light", "perch"],
    "align": ["array"],
    "aligning": ["positioning"],
    "alike": ["likewise"],
    "alimentary": ["alimental", "nourishing", "nutrient", "nutritious", "nutritive"],
    "alimentary canal": ["alimentary tract", "digestive tract", "digestive tube", "gastrointestinal tract", "gi tract"],
    "alimony": ["maintenance"],
    "aliquant": ["aliquant part"],
    "aliquot": ["aliquot part"],
    "alisma": ["genus alisma"],
    "alismataceae": ["family alismataceae", "water-plantain family"],
    "alismatidae": ["subclass alismatidae"],
    "aliterate": ["aliterate person"],
    "alive": ["live"],
    "alizarin": ["alizarine"],
    "alizarin carmine": ["alizarin crimson", "alizarin red"],
    "alkahest": ["alcahest", "universal solvent"],
    "alkalescent": ["alcalescent"],
    "alkali grass": ["zigadenus elegans"],
    "alkali metal": ["alkaline metal"],
    "alkaline": ["alkalic"],
    "alkaline earth": ["alkaline-earth metal"],
    "alkalinize": ["alkalinise"],
    "alkalinuria": ["alkaluria"],
    "alkalize": ["alkalify", "alkalise", "basify"],
    "alkapton": ["alcapton", "homogentisic acid"],
    "alkaptonuria": ["alcaptonuria"],
    "alkene": ["olefin", "olefine"],
    "alkyd": ["alkyd resin"],
    "alkyl": ["alkyl group", "alkyl radical"],
    "alkyl halide": ["haloalkane"],
    "all along": ["right along"],
    "all fours": ["high-low-jack"],
    "all in": ["beat", "bushed", "dead"],
    "all in all": ["altogether", "on the whole", "tout ensemble"],
    "all of a sudden": ["all at once"],
    "all over": ["over"],
    "all right": ["alright"],
    "all saints' day": ["allhallows", "hallowmas", "hallowmass", "november 1"],
    "all souls' day": ["november 2"],
    "all the way": ["the whole way"],
    "all together": ["all at once"],
    "all too": ["only too"],
    "all-around": ["all-round", "well-rounded"],
    "all-important": ["all important", "crucial", "essential", "of the essence"],
    "all-knowing": ["omniscient"],
    "all-or-none": ["all-or-nothing"],
    "all-out": ["full-scale"],
    "all-rounder": ["all arounder"],
    "allantoid": ["sausage-shaped"],
    "allegation": ["allegement"],
    "allege": ["aver", "say"],
    "alleged": ["so-called", "supposed"],
    "alleghenies": ["allegheny mountains"],
    "allegheny": ["allegheny river"],
    "allegheny chinkapin": ["castanea pumila", "chinquapin", "dwarf chestnut", "eastern chinquapin"],
    "allegheny plum": ["alleghany plum", "prunus alleghaniensis", "sloe"],
    "allegheny spurge": ["allegheny mountain spurge", "pachysandra procumbens"],
    "allegiance": ["fealty"],
    "allegorical": ["allegoric"],
    "allegorize": ["allegorise"],
    "allegorizer": ["allegoriser"],
    "allele": ["allelomorph"],
    "allelic": ["allelomorphic"],
    "allemande": ["allemande sauce"],
    "allen": ["grace ethel cecile rosalie allen", "gracie", "gracie allen"],
    "allergic": ["hypersensitised", "hypersensitive", "hypersensitized", "sensitised", "sensitized", "supersensitised", "supersensitive", "supersensitized"],
    "allergy": ["allergic reaction"],
    "alleviated": ["eased", "relieved"],
    "alleviative": ["alleviatory", "lenitive", "mitigative", "mitigatory", "palliative"],
    "alley": ["alleyway", "back street"],
    "alliaceae": ["family alliaceae"],
    "alliance": ["confederation"],
    "alliaria": ["genus alliaria"],
    "allice shad": ["allice", "allis", "allis shad", "alosa alosa"],
    "allied": ["confederate", "confederative"],
    "allied command atlantic": ["aclant"],
    "allied command europe": ["ace"],
    "alligator": ["gator"],
    "alligator snapping turtle": ["alligator snapper", "macroclemys temmincki"],
    "alligator weed": ["alligator grass", "alternanthera philoxeroides"],
    "alligatored": ["cracked"],
    "alligatorfish": ["aspidophoroides monopterygius"],
    "alligatoridae": ["family alligatoridae"],
    "allionia": ["genus allionia"],
    "alliteration": ["beginning rhyme", "head rhyme", "initial rhyme"],
    "allium": ["genus allium"],
    "allocable": ["allocatable", "apportionable"],
    "allocate": ["apportion"],
    "allocation": ["storage allocation"],
    "allocator": ["distributor"],
    "allopurinol": ["zyloprim"],
    "allosaur": ["allosaurus"],
    "allotment": ["allocation"],
    "allotropic": ["allotropical"],
    "allotropy": ["allotropism"],
    "allow": ["grant"],
    "allowance": ["adjustment"],
    "alloy": ["metal"],
    "alloy iron": ["alloy cast iron"],
    "allspice": ["allspice tree", "pimenta dioica", "pimento tree"],
    "allspice tree": ["pimenta officinalis"],
    "allude": ["advert", "touch"],
    "allure": ["allurement", "temptingness"],
    "alluring": ["beguiling", "enticing", "tempting"],
    "alluvial fan": ["alluvial cone"],
    "alluvial flat": ["alluvial plain"],
    "alluvial sediment": ["alluvial deposit", "alluvion", "alluvium"],
    "ally": ["friend"],
    "allyl": ["allyl group", "allyl radical"],
    "allyl alcohol": ["propenyl alcohol"],
    "almanac": ["farmer's calendar"],
    "almandite": ["almandine"],
    "almaty": ["alma-ata"],
    "almighty": ["all-powerful", "omnipotent"],
    "almond": ["amygdalus communis", "prunus amygdalus", "prunus dulcis", "sweet almond"],
    "almond cookie": ["almond crescent"],
    "almond moth": ["cadra cautella", "fig moth"],
    "almond oil": ["expressed almond oil", "sweet almond oil"],
    "almond willow": ["black hollander", "salix amygdalina", "salix triandra"],
    "almond-shaped": ["amygdaliform", "amygdaloid", "amygdaloidal"],
    "almoner": ["medical social worker"],
    "alms dish": ["alms tray"],
    "alms-giving": ["almsgiving"],
    "alnus": ["genus alnus"],
    "alocasia": ["elephant ear", "elephant's ear"],
    "aloeaceae": ["aloe family", "family aloeaceae"],
    "aloes": ["bitter aloes"],
    "aloha": ["ciao"],
    "alone": ["solo", "unaccompanied"],
    "aloneness": ["loneliness", "lonesomeness", "solitariness"],
    "along": ["on"],
    "alonso": ["alicia alonso"],
    "aloof": ["distant", "upstage"],
    "aloofness": ["remoteness", "standoffishness", "withdrawnness"],
    "alopecurus": ["genus alopecurus"],
    "alopex": ["genus alopex"],
    "alopiidae": ["family alopiidae"],
    "alopius": ["genus alopius"],
    "alosa": ["genus alosa"],
    "alouatta": ["genus alouatta"],
    "aloud": ["out loud"],
    "alpaca": ["lama pacos"],
    "alpestrine": ["subalpine"],
    "alpha blocker": ["alpha-adrenergic blocker", "alpha-adrenergic blocking agent", "alpha-blocker"],
    "alpha centauri": ["rigil", "rigil kent"],
    "alpha fetoprotein": ["afp", "alpha foetoprotein"],
    "alpha radiation": ["alpha ray"],
    "alpha receptor": ["alpha-adrenergic receptor", "alpha-adrenoceptor"],
    "alpha rhythm": ["alpha wave"],
    "alpha-beta brass": ["muntz metal", "yellow metal"],
    "alpha-naphthol test": ["molisch reaction", "molisch test", "molisch's test"],
    "alphabetic": ["alphabetical"],
    "alphabetic writing": ["alphabetic script"],
    "alphabetization": ["alphabetisation"],
    "alphabetize": ["alphabetise"],
    "alphabetized": ["alphabetised"],
    "alphabetizer": ["alphabetiser"],
    "alphanumeric": ["alphameric", "alphamerical", "alphanumerical"],
    "alphanumerics": ["alphanumeric characters"],
    "alpine anemone": ["anemone tetonensis", "mountain anemone"],
    "alpine ash": ["eucalyptus delegatensis", "mountain oak"],
    "alpine azalea": ["loiseleuria procumbens", "mountain azalea"],
    "alpine bearberry": ["arctostaphylos alpina", "black bearberry"],
    "alpine besseya": ["besseya alpina"],
    "alpine celery pine": ["phyllocladus alpinus"],
    "alpine clover": ["trifolium alpinum"],
    "alpine clubmoss": ["lycopodium alpinum"],
    "alpine coltsfoot": ["homogyne alpina", "tussilago alpina"],
    "alpine enchanter's nightshade": ["circaea alpina"],
    "alpine fir": ["abies lasiocarpa", "subalpine fir"],
    "alpine glacier": ["alpine type of glacier"],
    "alpine gold": ["alpine hulsea", "hulsea algida"],
    "alpine goldenrod": ["solidago multiradiata"],
    "alpine lady fern": ["athyrium distentifolium"],
    "alpine milk vetch": ["astragalus alpinus"],
    "alpine mouse-ear": ["arctic mouse-ear", "cerastium alpinum"],
    "alpine salamander": ["salamandra atra"],
    "alpine totara": ["podocarpus nivalis"],
    "alpine woodsia": ["flower-cup fern", "northern woodsia", "woodsia alpina"],
    "alpinia": ["genus alpinia", "genus languas", "genus zerumbet"],
    "alprazolam": ["xanax"],
    "alps": ["the alps"],
    "alsace": ["alsatia", "elsass"],
    "alsobia": ["genus alsobia"],
    "alsophila": ["genus alsophila"],
    "alstonia": ["genus alstonia"],
    "alstroemeriaceae": ["family alstroemeriaceae"],
    "altai mountains": ["altay mountains"],
    "altaic": ["altaic language"],
    "altar": ["communion table", "lord's table"],
    "altar wine": ["sacramental wine"],
    "altarpiece": ["reredos"],
    "alter": ["castrate", "neuter", "spay"],
    "alteration": ["adjustment", "modification"],
    "altered": ["neutered"],
    "alternanthera": ["genus alternanthera"],
    "alternate": ["jump"],
    "alternating current": ["ac", "alternating electric current"],
    "alternation of generations": ["heterogenesis", "xenogenesis"],
    "alternative birth": ["alternative birthing"],
    "alternative pleading": ["pleading in the alternative"],
    "alternatively": ["instead", "or else"],
    "althea": ["althaea", "hollyhock"],
    "altitude": ["height"],
    "alto": ["contralto"],
    "alto clef": ["viola clef"],
    "alto relievo": ["alto rilievo", "high relief"],
    "alto saxophonist": ["altoist"],
    "altocumulus": ["altocumulus cloud"],
    "altogether": ["all told", "in all"],
    "altostratus": ["altostratus cloud"],
    "altruism": ["selflessness"],
    "altruistic": ["selfless"],
    "altruistically": ["selflessly"],
    "alula": ["calypter"],
    "alum": ["ammonia alum", "ammonium alum"],
    "alumina": ["aluminium oxide", "aluminum oxide"],
    "aluminize": ["aluminise"],
    "aluminum": ["al", "aluminium", "atomic number 13"],
    "aluminum bronze": ["aluminium bronze"],
    "aluminum business": ["aluminum industry"],
    "aluminum chloride": ["aluminium chloride"],
    "aluminum foil": ["aluminium foil", "tin foil"],
    "aluminum hydroxide": ["aluminium hydroxide", "hydrated aluminium oxide", "hydrated aluminum oxide"],
    "alumnus": ["alum", "alumna", "grad", "graduate"],
    "alumroot": ["alumbloom"],
    "alveolar artery": ["arteria alveolaris"],
    "alveolar consonant": ["alveolar", "dental", "dental consonant"],
    "alveolar rhabdomyosarcoma": ["alveolar rhabdosarcoma"],
    "alveolar ridge": ["alveolar process", "gum ridge"],
    "alveolate": ["cavitied", "faveolate", "honeycombed", "pitted"],
    "alveolitis": ["dry socket"],
    "alveolus": ["air cell", "air sac"],
    "always": ["e'er", "ever"],
    "alyssum": ["madwort"],
    "alytes": ["genus alytes"],
    "alzheimer's disease": ["alzheimer's", "alzheimers"],
    "amabilis fir": ["abies amabilis", "christmas tree", "pacific silver fir", "red silver fir", "white fir"],
    "amalgam": ["dental amalgam"],
    "amalgamate": ["amalgamated", "coalesced", "consolidated", "fused"],
    "amalgamation": ["merger", "uniting"],
    "amanita": ["genus amanita"],
    "amaranthaceae": ["amaranth family", "family amaranthaceae"],
    "amaranthine": ["unfading"],
    "amaranthus": ["genus amaranthus"],
    "amarelle": ["prunus cerasus caproniana"],
    "amaryllidaceae": ["amaryllis family", "family amaryllidaceae"],
    "amaterasu": ["amaterasu omikami"],
    "amateur": ["recreational", "unpaid"],
    "amateurish": ["amateur", "inexpert", "unskilled"],
    "amati": ["nicola amati", "nicolo amati"],
    "amative": ["amorous"],
    "amatory": ["amorous", "romantic"],
    "amauropelta": ["genus amauropelta"],
    "amaze": ["astonish", "astound"],
    "amazed": ["astonied", "astonished", "astounded", "stunned"],
    "amazing": ["astonishing"],
    "amazingly": ["astonishingly", "surprisingly"],
    "amazon": ["virago"],
    "amazon ant": ["polyergus rufescens"],
    "amazona": ["genus amazona"],
    "ambassador": ["embassador"],
    "amber": ["gold"],
    "amber lily": ["anthericum torreyi"],
    "amberboa": ["genus amberboa"],
    "amberjack": ["amberfish"],
    "ambiance": ["ambience"],
    "ambidexterity": ["ambidextrousness"],
    "ambidextrous": ["two-handed"],
    "ambiguity": ["equivocalness"],
    "ambiguously": ["equivocally"],
    "ambition": ["aspiration", "dream"],
    "ambitious": ["challenging"],
    "ambitiously": ["determinedly"],
    "ambivalence": ["ambivalency"],
    "amble": ["mosey"],
    "ambloplites": ["genus ambloplites"],
    "amblyrhynchus": ["genus amblyrhynchus"],
    "amboina pine": ["agathis alba", "agathis dammara", "amboyna pine"],
    "amboyna": ["andaman redwood"],
    "ambrose": ["saint ambrose", "st. ambrose"],
    "ambrosia": ["nectar"],
    "ambrosiaceae": ["family ambrosiaceae"],
    "ambrosial": ["ambrosian", "nectarous"],
    "ambulant": ["ambulatory"],
    "ambulant plague": ["ambulatory plague", "pestis ambulans"],
    "ambush": ["ambuscade", "bushwhack", "lie in wait", "lurk", "scupper", "waylay"],
    "ambystoma": ["genus ambystoma"],
    "ambystomatidae": ["family ambystomatidae"],
    "ambystomid": ["ambystomid salamander"],
    "ameba": ["amoeba"],
    "amebiasis": ["amebiosis", "amoebiasis", "amoebiosis"],
    "amebic dysentery": ["amoebic dysentery"],
    "ameboid": ["amoeboid"],
    "ameiuridae": ["family ameiuridae"],
    "ameiurus": ["genus ameiurus"],
    "amelanchier": ["genus amelanchier"],
    "ameliorating": ["ameliorative", "amelioratory", "meliorative"],
    "amelioration": ["betterment", "melioration"],
    "amen": ["amon", "amun"],
    "amen-ra": ["amon-ra", "amun ra"],
    "amenability": ["amenableness", "cooperativeness"],
    "amenable": ["tractable"],
    "amendable": ["correctable"],
    "amenorrhea": ["amenia", "amenorrhoea"],
    "amenorrheic": ["amenorrheal", "amenorrhoeal", "amenorrhoeic"],
    "amentiferae": ["group amentiferae"],
    "amentiferous": ["amentaceous"],
    "american agave": ["agave americana"],
    "american alligator": ["alligator mississipiensis"],
    "american angelica tree": ["aralia spinosa", "devil's walking stick", "hercules'-club"],
    "american arborvitae": ["northern white cedar", "thuja occidentalis", "white cedar"],
    "american badger": ["taxidea taxus"],
    "american baptist convention": ["northern baptist convention"],
    "american barberry": ["berberis canadensis"],
    "american basswood": ["american lime", "tilia americana"],
    "american beech": ["fagus americana", "fagus grandifolia", "red beech", "white beech"],
    "american bison": ["american buffalo", "bison bison", "buffalo"],
    "american bittern": ["botaurus lentiginosus", "stake driver"],
    "american black bear": ["black bear", "euarctos americanus", "ursus americanus"],
    "american bog asphodel": ["narthecium americanum"],
    "american bugbane": ["cimicifuga americana", "summer cohosh"],
    "american chameleon": ["anole", "anolis carolinensis"],
    "american chestnut": ["american sweet chestnut", "castanea dentata"],
    "american civil war": ["united states civil war", "war between the states"],
    "american cockroach": ["periplaneta americana"],
    "american coot": ["fulica americana", "marsh hen", "mud hen", "water hen"],
    "american copper": ["lycaena hypophlaeas"],
    "american crab apple": ["garland crab", "malus coronaria"],
    "american cranberry": ["large cranberry", "vaccinium macrocarpon"],
    "american crow": ["corvus brachyrhyncos"],
    "american dewberry": ["rubus canadensis"],
    "american dog violet": ["viola conspersa"],
    "american egret": ["egretta albus", "great white heron"],
    "american elder": ["black elderberry", "sambucus canadensis", "sweet elder"],
    "american elm": ["rock elm", "ulmus americana", "water elm", "white elm"],
    "american english": ["american", "american language"],
    "american federation of labor": ["afl"],
    "american federation of labor and congress of industrial organizations": ["afl-cio"],
    "american feverfew": ["parthenium integrifolium", "prairie dock", "wild quinine"],
    "american flag": ["old glory", "star-spangled banner", "stars and stripes"],
    "american fly honeysuckle": ["fly honeysuckle", "lonicera canadensis"],
    "american football": ["american football game"],
    "american frogbit": ["limnodium spongia"],
    "american gallinule": ["porphyrula martinica"],
    "american germander": ["teucrium canadense", "wood sage"],
    "american ginseng": ["panax quinquefolius", "sang"],
    "american green toad": ["bufo debilis"],
    "american hackberry": ["celtis occidentalis"],
    "american harvest mouse": ["harvest mouse"],
    "american hazel": ["corylus americana"],
    "american holly": ["christmas holly"],
    "american hop": ["humulus americanus"],
    "american hornbeam": ["carpinus caroliniana"],
    "american lady crab": ["calico crab", "lady crab", "ovalipes ocellatus"],
    "american larch": ["black larch", "larix laricina", "tamarack"],
    "american lobster": ["maine lobster", "northern lobster"],
    "american magpie": ["pica pica hudsonia"],
    "american maidenhair fern": ["adiantum pedatum", "five-fingered maidenhair fern"],
    "american marten": ["american sable", "martes americana"],
    "american mastodon": ["american mastodont", "mammut americanum"],
    "american merganser": ["mergus merganser americanus"],
    "american mink": ["mustela vison"],
    "american mistletoe": ["phoradendron flavescens", "phoradendron serotinum"],
    "american mountain ash": ["sorbus americana"],
    "american oil palm": ["elaeis oleifera"],
    "american parasol": ["lepiota americana"],
    "american party": ["know-nothing party"],
    "american pasqueflower": ["american pulsatilla", "anemone ludoviciana", "blue tulip", "eastern pasque flower", "lion's beard", "prairie anemone", "pulsatilla patens", "wild crocus"],
    "american persimmon": ["diospyros virginiana", "possumwood"],
    "american plaice": ["hippoglossoides platessoides"],
    "american quaking aspen": ["american aspen", "populus tremuloides"],
    "american raspberry": ["rubus idaeus strigosus", "rubus strigosus"],
    "american rattlebox": ["crotalaria sagitallis"],
    "american red elder": ["red-berried elder", "sambucus pubens", "stinking elder"],
    "american red plum": ["august plum", "goose plum", "prunus americana"],
    "american red squirrel": ["red squirrel", "sciurus hudsonicus", "spruce squirrel", "tamiasciurus hudsonicus"],
    "american redstart": ["redstart", "setophaga ruticilla"],
    "american revolution": ["american revolutionary war", "american war of independence", "war of american independence"],
    "american rock brake": ["american parsley fern", "cryptogramma acrostichoides"],
    "american samoa": ["as", "eastern samoa"],
    "american shrew mole": ["neurotrichus gibbsii"],
    "american smelt": ["rainbow smelt"],
    "american smokewood": ["chittamwood", "cotinus americanus", "cotinus obovatus"],
    "american smooth dogfish": ["mustelus canis"],
    "american spikenard": ["aralia racemosa", "life-of-man", "petty morel"],
    "american staffordshire terrier": ["american pit bull terrier", "pit bull terrier", "staffordshire terrier"],
    "american standard code for information interchange": ["ascii"],
    "american standard version": ["american revised version"],
    "american star grass": ["hypoxis hirsuta"],
    "american stock exchange": ["amex", "curb"],
    "american sycamore": ["american plane", "buttonwood", "platanus occidentalis"],
    "american toad": ["bufo americanus"],
    "american turkey oak": ["quercus laevis", "turkey oak"],
    "american twinflower": ["linnaea borealis americana"],
    "american water ouzel": ["cinclus mexicanus"],
    "american water shrew": ["sorex palustris"],
    "american watercress": ["cardamine rotundifolia", "mountain watercress"],
    "american white birch": ["betula cordifolia", "betula papyrifera", "canoe birch", "paper birch", "paperbark birch"],
    "american white oak": ["quercus alba"],
    "american white pine": ["eastern white pine", "pinus strobus", "weymouth pine"],
    "american widgeon": ["anas americana", "baldpate"],
    "american wistaria": ["american wisteria", "wisteria frutescens"],
    "american woodcock": ["philohela minor", "woodcock snipe"],
    "american wormseed": ["chenopodium ambrosioides", "mexican tea", "spanish tea", "wormseed"],
    "americanization": ["americanisation"],
    "americanize": ["americanise"],
    "americium": ["am", "atomic number 95"],
    "amerind": ["american indian", "american-indian language", "amerindian language", "indian"],
    "amerindian": ["native american"],
    "ametabolic": ["ametabolous"],
    "amharic": ["ethiopian language"],
    "amia": ["genus amia"],
    "amiable": ["good-humored", "good-humoured"],
    "amianthum": ["genus amianthum"],
    "amicability": ["amicableness"],
    "amicus curiae": ["friend of the court"],
    "amidships": ["amidship", "midships"],
    "amiidae": ["family amiidae"],
    "amine": ["aminoalkane"],
    "amino": ["amino group"],
    "amino acid": ["aminoalkanoic acid"],
    "amino plastic": ["amino resin", "aminoplast"],
    "aminopyrine": ["amidopyrine"],
    "amiodarone": ["cordarone"],
    "amiss": ["awry", "haywire", "wrong"],
    "amitriptyline": ["amitriptyline hydrochloride", "elavil"],
    "amity": ["cordiality"],
    "amlodipine besylate": ["norvasc"],
    "amman": ["capital of jordan"],
    "ammodytes": ["genus ammodytes"],
    "ammodytidae": ["family ammodytidae"],
    "ammonia water": ["ammonia", "ammonium hydroxide"],
    "ammoniac": ["gum ammoniac"],
    "ammonite": ["ammonoid"],
    "ammonium": ["ammonium ion"],
    "ammonium chloride": ["sal ammoniac"],
    "ammotragus": ["genus ammotragus"],
    "ammunition": ["ammo"],
    "amnesia": ["blackout", "memory loss"],
    "amnesic": ["amnesiac"],
    "amnestic": ["amnesic"],
    "amnesty": ["free pardon", "pardon"],
    "amniocentesis": ["amnio"],
    "amnion": ["amnios", "amniotic sac"],
    "amniotic": ["amnic", "amnionic"],
    "amniotic fluid": ["amnionic fluid", "waters"],
    "amobarbital sodium": ["amytal", "blue", "blue angel", "blue devil"],
    "amoebic": ["ameban", "amebic", "amebous", "amoeban", "amoebous"],
    "amoebida": ["amoebina", "order amoebida", "order amoebina"],
    "amok": ["amuck"],
    "amorousness": ["enamoredness"],
    "amorphous": ["formless", "shapeless"],
    "amortization": ["amortisation"],
    "amortize": ["amortise"],
    "amos": ["book of amos"],
    "amour propre": ["conceit", "self-love", "vanity"],
    "amoxicillin": ["amoxil", "augmentin", "larotid", "polymox", "trimox"],
    "ampere": ["international ampere"],
    "amphetamine": ["pep pill", "speed", "upper"],
    "amphetamine sulfate": ["amphetamine sulphate"],
    "amphibia": ["class amphibia"],
    "amphibian": ["amphibious vehicle"],
    "amphibiotic": ["semiaquatic"],
    "amphibious": ["amphibian"],
    "amphibolips": ["genus amphibolips"],
    "amphibology": ["amphiboly"],
    "amphicarpaea": ["amphicarpa", "genus amphicarpa", "genus amphicarpaea"],
    "amphigory": ["nonsense verse"],
    "amphineura": ["subclass amphineura"],
    "amphioxidae": ["branchiostomidae", "family amphioxidae", "family branchiostomidae"],
    "amphipoda": ["order amphipoda"],
    "amphiprion": ["genus amphiprion"],
    "amphiprostylar": ["amphiprostyle", "amphistylar", "porticoed"],
    "amphisbaena": ["amphisbaenia", "genus amphisbaena", "genus amphisbaenia"],
    "amphisbaenidae": ["family amphisbaenidae"],
    "amphitheater": ["amphitheatre"],
    "amphitheatric": ["amphitheatrical"],
    "amphiuma": ["blind eel", "congo eel", "congo snake"],
    "amphiumidae": ["family amphiumidae"],
    "amphoteric": ["amphiprotic"],
    "ampicillin": ["polycillin", "principen", "sk-ampicillin"],
    "ample": ["sizable", "sizeable"],
    "amplification": ["gain"],
    "amplitude": ["bountifulness", "bounty"],
    "amplitude modulation": ["am"],
    "amply": ["richly"],
    "ampullar": ["ampullary"],
    "amputate": ["cut off"],
    "amrinone": ["inocor"],
    "amsinckia": ["genus amsinckia"],
    "amsonia": ["genus amsonia"],
    "amsterdam": ["capital of the netherlands", "dutch capital"],
    "amuck": ["amok", "berserk", "demoniac", "demoniacal", "possessed"],
    "amulet": ["talisman"],
    "amundsen": ["roald amundsen"],
    "amur": ["amur river", "heilong", "heilong jiang"],
    "amur privet": ["ligustrum amurense"],
    "amuse": ["disport", "divert"],
    "amused": ["diverted", "entertained"],
    "amusement park": ["funfair", "pleasure ground"],
    "amusing": ["amusive", "diverting"],
    "amusingly": ["divertingly"],
    "amygdala": ["amygdaloid nucleus", "corpus amygdaloideum"],
    "amygdalaceae": ["family amygdalaceae"],
    "amygdalus": ["genus amygdalus"],
    "amyloid plaque": ["amyloid protein plaque"],
    "amyotrophia": ["amyotrophy"],
    "amyotrophic lateral sclerosis": ["als", "lou gehrig's disease"],
    "anabantidae": ["family anabantidae"],
    "anabas": ["genus anabas"],
    "anabolism": ["constructive metabolism"],
    "anabrus": ["genus anabrus"],
    "anacanthini": ["order anacanthini"],
    "anacardiaceae": ["family anacardiaceae", "sumac family"],
    "anacardium": ["genus anacardium"],
    "anachronic": ["anachronistic", "anachronous"],
    "anachronism": ["misdating", "mistiming"],
    "anacoluthia": ["anacoluthon"],
    "anaconda": ["eunectes murinus"],
    "anacyclus": ["genus anacyclus"],
    "anadenanthera": ["genus anadenanthera"],
    "anadenanthera colubrina": ["piptadenia macrocarpa"],
    "anadiplosis": ["reduplication"],
    "anaerobic": ["anaerobiotic"],
    "anaesthetic": ["anesthetic"],
    "anagallis": ["genus anagallis"],
    "anagasta": ["genus anagasta"],
    "anaglyphic": ["anaglyphical", "anaglyptic", "anaglyptical"],
    "anagogic": ["anagogical"],
    "anagram": ["anagrammatise", "anagrammatize"],
    "anagrammatic": ["anagrammatical"],
    "anagyris": ["genus anagyris"],
    "anal": ["anal retentive"],
    "anal personality": ["anal retentive personality"],
    "anal sphincter": ["musculus sphincter ani", "sphincter ani"],
    "anal stage": ["anal phase"],
    "analects": ["analecta"],
    "analgesic": ["anodyne", "pain pill", "painkiller"],
    "analog computer": ["analogue computer"],
    "analogize": ["analogise"],
    "analogous": ["correspondent"],
    "analogue": ["analog", "parallel"],
    "analphabet": ["analphabetic"],
    "analphabetic": ["unlettered"],
    "analysis": ["analytic thinking"],
    "analysis of variance": ["anova"],
    "analyst": ["psychoanalyst"],
    "analytic": ["analytical"],
    "analytic geometry": ["analytical geometry", "coordinate geometry"],
    "analytical balance": ["chemical balance"],
    "analyzable": ["decomposable"],
    "analyze": ["analyse"],
    "analyzer": ["analyser"],
    "anamnestic response": ["anamnestic reaction"],
    "anamorphosis": ["anamorphism"],
    "ananas": ["genus ananas"],
    "anapest": ["anapaest"],
    "anapestic": ["anapaestic"],
    "anaphalis": ["genus anaphalis"],
    "anapsid": ["anapsid reptile"],
    "anapsida": ["subclass anapsida"],
    "anarchic": ["anarchical", "lawless"],
    "anarchist": ["nihilist", "syndicalist"],
    "anarchy": ["lawlessness"],
    "anarhichadidae": ["family anarhichadidae"],
    "anarhichas": ["genus anarhichas"],
    "anas": ["genus anas"],
    "anasa": ["genus anasa"],
    "anaspida": ["order anaspida"],
    "anastatica": ["genus anastatica"],
    "anastigmatic": ["stigmatic"],
    "anastomose": ["inosculate"],
    "anastomosis": ["inosculation"],
    "anastomotic vein": ["vena anastomotica"],
    "anastomus": ["genus anastomus"],
    "anastrophe": ["inversion"],
    "anathema": ["bete noire"],
    "anathematization": ["anathematisation"],
    "anatidae": ["family anatidae"],
    "anatolian": ["anatolian language"],
    "anatomic": ["anatomical"],
    "anatomical reference": ["anatomical"],
    "anatomize": ["anatomise"],
    "anatomy": ["general anatomy"],
    "anatoxin": ["toxoid"],
    "anatropous": ["inverted"],
    "ancestor": ["antecedent", "ascendant", "ascendent", "root"],
    "ancestral": ["hereditary", "patrimonial", "transmissible"],
    "ancestry": ["derivation", "filiation", "lineage"],
    "anchor": ["ground"],
    "anchor chain": ["anchor rope"],
    "anchor light": ["riding lamp", "riding light"],
    "anchorage": ["anchorage ground"],
    "anchorite": ["hermit"],
    "anchoritic": ["eremitic", "eremitical", "hermitic", "hermitical"],
    "anchovy pear": ["anchovy pear tree", "grias cauliflora"],
    "ancient": ["antediluvian"],
    "ancient pine": ["pinus longaeva"],
    "ancientness": ["antiquity"],
    "anconeous muscle": ["musculus anconeus"],
    "ancylidae": ["family ancylidae"],
    "ancylostomatidae": ["family ancylostomatidae"],
    "ancylus": ["genus ancylus"],
    "and circuit": ["and gate"],
    "and how": ["you bet", "you said it"],
    "and so forth": ["and so on", "etc.", "etcetera"],
    "andalusia": ["andalucia"],
    "andean condor": ["vultur gryphus"],
    "andersen": ["hans christian andersen"],
    "anderson": ["sherwood anderson"],
    "andira": ["genus andira"],
    "andiron": ["dog", "dog-iron", "firedog"],
    "andorra": ["principality of andorra"],
    "andreaea": ["genus andreaea"],
    "andreaeales": ["order andreaeales"],
    "andrena": ["andrenid", "mining bee"],
    "andrenidae": ["family andrenidae"],
    "andrew": ["saint andrew", "saint andrew the apostle", "st. andrew"],
    "andrews": ["roy chapman andrews"],
    "andricus": ["genus andricus"],
    "androgen": ["androgenic hormone"],
    "androgenesis": ["androgeny"],
    "androgenetic": ["androgenous"],
    "androgyny": ["bisexuality", "hermaphroditism"],
    "android": ["humanoid", "mechanical man"],
    "andromeda": ["japanese andromeda", "lily-of-the-valley tree", "pieris japonica"],
    "andropogon": ["genus andropogon"],
    "anecdotic": ["anecdotal", "anecdotical"],
    "anecdotist": ["raconteur"],
    "aneides": ["genus aneides"],
    "anemia": ["anaemia"],
    "anemic": ["anaemic"],
    "anemometer": ["wind gage", "wind gauge"],
    "anemometric": ["anemometrical"],
    "anemone": ["windflower"],
    "anemonella": ["genus anemonella"],
    "anemopsis": ["genus anemopsis"],
    "anencephalic": ["anencephalous"],
    "anencephaly": ["anencephalia"],
    "aneroid barometer": ["aneroid"],
    "anesthesia": ["anaesthesia"],
    "anesthesiologist": ["anaesthetist", "anesthetist"],
    "anesthetic": ["anaesthetic", "anaesthetic agent", "anesthetic agent"],
    "anesthetize": ["anaesthetise", "anaesthetize", "anesthetise", "put out", "put under"],
    "anestrous": ["anestric", "anoestrous"],
    "anestrus": ["anestrum", "anoestrum", "anoestrus"],
    "anethum": ["genus anethum"],
    "aneurysm": ["aneurism"],
    "aneurysmal": ["aneurismal", "aneurismatic", "aneurysmatic"],
    "angara": ["angara river", "tunguska", "upper tunguska"],
    "angel": ["backer"],
    "angel cake": ["angel food cake"],
    "angel shark": ["angelfish", "monkfish", "squatina squatina"],
    "angel's trumpet": ["brugmansia suaveolens", "datura suaveolens"],
    "angel-wing begonia": ["begonia cocchinea"],
    "angelic": ["angelical"],
    "angelica": ["angelique"],
    "angelim": ["andelmin"],
    "angelus bell": ["angelus"],
    "anger": ["see red"],
    "angered": ["enraged", "furious", "infuriated", "maddened"],
    "angevin": ["angevine"],
    "angina pectoris": ["angina"],
    "anginal": ["anginose", "anginous"],
    "angiocarpic": ["angiocarpous"],
    "angioedema": ["atrophedema", "giant hives", "periodic edema", "quincke's edema"],
    "angiopteris": ["angiopteris evecta", "giant fern"],
    "angiosperm": ["flowering plant"],
    "angiospermae": ["anthophyta", "class angiospermae", "division anthophyta", "division magnoliophyta", "magnoliophyta"],
    "angiospermous tree": ["flowering tree"],
    "angiotensin": ["angiotonin", "hypertensin"],
    "angiotensin converting enzyme": ["ace", "angiotensin-converting enzyme"],
    "angle bracket": ["angle iron"],
    "angle of extinction": ["extinction angle"],
    "angle of incidence": ["incidence angle"],
    "angled loofah": ["luffa acutangula", "sing-kwa"],
    "angler": ["troller"],
    "anglesey": ["anglesea", "anglesea island", "anglesey island", "mona"],
    "anglican church": ["anglican communion", "church of england"],
    "anglicise": ["anglicize"],
    "anglicism": ["briticism", "britishism"],
    "anglicization": ["anglicisation"],
    "anglo-catholicism": ["high anglicanism"],
    "anglo-french": ["anglo-norman"],
    "anglophile": ["anglophil"],
    "angola": ["republic of angola"],
    "angora": ["angora goat"],
    "angostura bark": ["angostura"],
    "angoumois moth": ["angoumois grain moth", "sitotroga cerealella"],
    "angry": ["furious", "raging", "tempestuous", "wild"],
    "angstrom": ["angstrom unit"],
    "anguidae": ["family anguidae"],
    "anguilla": ["genus anguilla"],
    "anguillidae": ["family anguillidae"],
    "anguilliformes": ["order anguilliformes", "order apodes"],
    "anguillula": ["genus anguillula", "genus turbatrix", "turbatrix"],
    "anguis": ["genus anguis"],
    "anguish": ["torment", "torture"],
    "anguished": ["tormented", "tortured"],
    "angular": ["angulate"],
    "angular artery": ["arteria angularis"],
    "angular shape": ["angularity"],
    "angular vein": ["vena angularis"],
    "angus og": ["aengus", "angus", "oengus"],
    "angwantibo": ["arctocebus calabarensis", "golden potto"],
    "anhidrosis": ["anhydrosis"],
    "anhima": ["genus anhima"],
    "anhimidae": ["family anhimidae"],
    "anhingidae": ["family anhingidae"],
    "anigozanthus": ["genus anigozanthus"],
    "anil": ["indigo", "indigotin"],
    "aniline": ["aminobenzine", "aniline oil", "phenylamine"],
    "animal": ["animate being", "beast", "brute", "creature", "fauna"],
    "animal fiber": ["animal fibre"],
    "animal foot": ["foot"],
    "animal toxin": ["zootoxin"],
    "animal trainer": ["handler"],
    "animalcule": ["animalculum"],
    "animalia": ["animal kingdom", "kingdom animalia"],
    "animalism": ["physicality"],
    "animality": ["animal nature"],
    "animalize": ["animalise"],
    "animate": ["quicken", "reanimate", "recreate", "renovate", "repair", "revive", "revivify", "vivify"],
    "animated": ["alive"],
    "animateness": ["aliveness", "liveness"],
    "animating": ["enlivening"],
    "animation": ["aliveness", "life", "living"],
    "anime": ["gum anime"],
    "animist": ["animistic"],
    "animize": ["animate", "animise"],
    "animosity": ["animus", "bad blood"],
    "anionic detergent": ["anionic", "non-ionic detergent"],
    "anise": ["anise plant", "pimpinella anisum"],
    "anise hyssop": ["agastache foeniculum"],
    "anisette": ["anisette de bordeaux"],
    "anisogamic": ["anisogamous"],
    "anisometric": ["unsymmetrical"],
    "anisoptera": ["suborder anisoptera"],
    "anisotremus": ["genus anisotremus"],
    "ankara": ["angora", "capital of turkey", "turkish capital"],
    "ankle": ["ankle joint", "articulatio talocruralis", "mortise joint"],
    "ankle-deep": ["knee-deep"],
    "anklebone": ["astragal", "astragalus", "talus"],
    "anklet": ["anklets", "bobbysock", "bobbysocks"],
    "ankylosaur": ["ankylosaurus"],
    "ankylose": ["ancylose"],
    "ankylosing spondylitis": ["marie-strumpell disease", "rheumatoid spondylitis"],
    "ankylosis": ["anchylosis"],
    "annals": ["chronological record"],
    "annapolis": ["capital of maryland"],
    "annapurna": ["anapurna"],
    "anneal": ["normalize", "temper"],
    "annealing": ["tempering"],
    "annelid": ["annelid worm", "segmented worm"],
    "annelida": ["phylum annelida"],
    "annex": ["annexe", "extension", "wing"],
    "annexation": ["appropriation"],
    "anniellidae": ["family anniellidae"],
    "annihilated": ["exterminated", "wiped out"],
    "annihilating": ["devastating", "withering"],
    "annihilation": ["disintegration"],
    "annihilative": ["annihilating", "devastating", "withering"],
    "anniversary": ["day of remembrance"],
    "annona": ["genus annona"],
    "annonaceae": ["custard-apple family", "family annonaceae"],
    "annotate": ["footnote"],
    "annotation": ["annotating"],
    "announce": ["denote"],
    "announced": ["proclaimed"],
    "announcement": ["promulgation"],
    "annoy": ["bother", "chafe", "devil", "get at", "get to", "gravel", "irritate", "nark", "nettle", "rag", "rile", "vex"],
    "annoyance": ["chafe", "vexation"],
    "annoyed": ["harassed", "harried", "pestered", "vexed"],
    "annoying": ["bothersome", "galling", "irritating", "nettlesome", "pesky", "pestering", "pestiferous", "plaguey", "plaguy", "teasing", "vexatious", "vexing"],
    "annual": ["yearbook", "yearly"],
    "annual fern": ["anogramma leptophylla", "jersey fern"],
    "annual ring": ["growth ring"],
    "annually": ["each year", "every year", "yearly"],
    "annuity": ["rente"],
    "annular": ["annulate", "annulated", "circinate", "doughnut-shaped", "ring-shaped", "ringed"],
    "annulet": ["roundel"],
    "annulment": ["invalidation"],
    "annulus": ["skirt"],
    "annunciation": ["annunciation day", "lady day", "march 25"],
    "annwfn": ["annwn"],
    "anoa": ["anoa depressicornis", "dwarf buffalo"],
    "anobiidae": ["family anobiidae"],
    "anodic": ["anodal"],
    "anodize": ["anodise"],
    "anodonta": ["genus anodonta"],
    "anoectochilus": ["genus anoectochilus"],
    "anogramma": ["genus anogramma"],
    "anoint": ["anele", "embrocate", "inunct", "oil"],
    "anointing": ["anointment"],
    "anointing of the sick": ["extreme unction", "last rites"],
    "anolis": ["genus anolis"],
    "anomala": ["genus anomala"],
    "anomalopidae": ["family anomalopidae"],
    "anomalops": ["flashlight fish"],
    "anomalopteryx": ["anomalopteryx oweni"],
    "anomaly": ["anomalousness"],
    "anomia": ["genus anomia"],
    "anomie": ["anomy"],
    "anomiidae": ["family anomiidae"],
    "anonymity": ["namelessness"],
    "anonymous": ["anon."],
    "anonymous ftp": ["anonymous file transfer protocol"],
    "anopheles": ["genus anopheles"],
    "anoplura": ["order anoplura"],
    "anorchism": ["anorchia", "anorchidism"],
    "anorectic": ["anorexigenic"],
    "anorexic": ["anorectic"],
    "anosmic": ["anosmatic"],
    "anostraca": ["order anostraca"],
    "another": ["some other"],
    "anouilh": ["jean anouilh"],
    "ansar al islam": ["ansar al-islam", "supporters of islam"],
    "anselm": ["saint anselm", "st. anselm"],
    "anser": ["genus anser"],
    "anseres": ["suborder anseres"],
    "anseriformes": ["order anseriformes"]
}
