synonyms = {
    "jamming": ["electronic jamming", "jam"],
    "jampot": ["jamjar"],
    "jangling": ["jangly"],
    "jansen": ["cornelis jansen", "cornelius jansenius"],
    "january": ["jan"],
    "janus-faced": ["two-faced"],
    "jap": ["nip"],
    "japan": ["nihon", "nippon"],
    "japan allspice": ["chimonanthus praecox", "japanese allspice", "winter sweet"],
    "japan current": ["kuroshio", "kuroshio current"],
    "japan wax": ["japan tallow"],
    "japanese": ["nipponese"],
    "japanese angelica tree": ["aralia elata"],
    "japanese apricot": ["mei", "prunus mume"],
    "japanese banana": ["musa basjoo"],
    "japanese barberry": ["berberis thunbergii"],
    "japanese beetle": ["popillia japonica"],
    "japanese bittersweet": ["celastric articulatus", "celastrus orbiculatus", "japan bittersweet", "oriental bittersweet"],
    "japanese black pine": ["black pine", "pinus thunbergii"],
    "japanese brome": ["bromus japonicus", "japanese chess"],
    "japanese cedar": ["cryptomeria japonica", "japan cedar", "sugi"],
    "japanese chestnut": ["castanea crenata"],
    "japanese clover": ["jap clover", "japan clover", "lespedeza striata"],
    "japanese deer": ["cervus nipon", "cervus sika", "sika"],
    "japanese flowering cherry": ["prunus sieboldii"],
    "japanese honeysuckle": ["lonicera japonica"],
    "japanese hop": ["humulus japonicus"],
    "japanese iris": ["iris kaempferi"],
    "japanese lilac": ["syringa villosa"],
    "japanese linden": ["japanese lime", "tilia japonica"],
    "japanese maple": ["acer palmatum"],
    "japanese millet": ["billion-dollar grass", "echinochloa frumentacea", "japanese barnyard millet", "sanwa millet"],
    "japanese morning glory": ["ipomoea nil"],
    "japanese oak": ["quercus grosseserrata", "quercus mongolica"],
    "japanese oyster": ["ostrea gigas"],
    "japanese pagoda tree": ["chinese scholar tree", "chinese scholartree", "sophora japonica", "sophora sinensis"],
    "japanese persimmon": ["diospyros kaki", "kaki"],
    "japanese pink": ["dianthus chinensis heddewigii"],
    "japanese plum": ["prunus salicina"],
    "japanese poinsettia": ["euphorbia heterophylla", "mole plant", "paint leaf"],
    "japanese privet": ["ligustrum japonicum"],
    "japanese quince": ["chaenomeles speciosa"],
    "japanese red army": ["anti-imperialist international brigade", "jra"],
    "japanese red pine": ["japanese table pine", "pinus densiflora"],
    "japanese snowbell": ["styrax japonicum"],
    "japanese spurge": ["pachysandra terminalis"],
    "japanese tree lilac": ["syringa amurensis japonica", "syringa reticulata"],
    "japanese umbrella pine": ["sciadopitys verticillata"],
    "japanese wistaria": ["wisteria floribunda"],
    "japanese yew": ["taxus cuspidata"],
    "japonica": ["camellia japonica"],
    "jar": ["bump around", "shake up"],
    "jargoon": ["jargon"],
    "jarrell": ["randall jarrell"],
    "jarvik heart": ["jarvik artificial heart"],
    "jasminum": ["genus jasminum"],
    "jaspers": ["karl jaspers", "karl theodor jaspers"],
    "jassidae": ["family jassidae"],
    "jatropha": ["genus jatropha"],
    "jaundice": ["icterus"],
    "jaundice of the newborn": ["icterus neonatorum", "physiological jaundice of the newborn"],
    "jaundiced": ["icteric", "yellow"],
    "jauntiness": ["dapperness", "nattiness", "rakishness"],
    "jaunting car": ["jaunty car"],
    "java man": ["trinil man"],
    "java sparrow": ["java finch", "padda oryzivora", "ricebird"],
    "javanese": ["javan"],
    "javanthropus": ["genus javanthropus"],
    "javelle water": ["eau de javelle", "javel water"],
    "jawless vertebrate": ["agnathan", "jawless fish"],
    "jay": ["john jay"],
    "jazz band": ["combo", "jazz group"],
    "jazz musician": ["jazzman"],
    "jazz up": ["ginger up", "juice up", "pep up"],
    "jealous": ["green-eyed", "overjealous"],
    "jealousy": ["green-eyed monster"],
    "jean": ["blue jean", "denim"],
    "jeanne d'arc": ["joan of arc", "saint joan"],
    "jebel musa": ["abila", "abyla"],
    "jeddah": ["jed'dah", "jidda", "jiddah"],
    "jeep": ["landrover"],
    "jeer": ["barrack", "flout", "gibe", "scoff"],
    "jeeringly": ["gibingly", "mockingly"],
    "jeffers": ["john robinson jeffers", "robinson jeffers"],
    "jefferson": ["president jefferson", "thomas jefferson"],
    "jefferson city": ["capital of missouri"],
    "jefferson davis' birthday": ["davis' birthday", "june 3"],
    "jeffrey pine": ["black pine", "jeffrey's pine", "pinus jeffreyi"],
    "jejunal artery": ["intestinal artery"],
    "jejunity": ["jejuneness", "tameness", "vapidity", "vapidness"],
    "jell": ["congeal", "set"],
    "jellify": ["jelly"],
    "jello": ["jell-o"],
    "jelly bean": ["jelly egg"],
    "jellyroll": ["swiss roll"],
    "jemaah islamiyah": ["islamic community", "islamic group", "ji", "malaysia militant group", "malaysian mujahidin group"],
    "jena": ["battle of jena"],
    "jenner": ["edward jenner"],
    "jennet": ["jenny", "jenny ass"],
    "jenny": ["william le baron jenny"],
    "jensen": ["johannes vilhelm jensen"],
    "jerboa kangaroo": ["kangaroo jerboa"],
    "jeremiah": ["book of jeremiah"],
    "jerez": ["jerez de la frontera"],
    "jerk": ["twitch"],
    "jerkwater": ["one-horse", "pokey", "poky"],
    "jerky": ["jerk", "jerked meat"],
    "jeroboam": ["jeroboam i"],
    "jerome": ["eusebius hieronymus", "eusebius sophronius hieronymus", "hieronymus", "saint jerome", "st. jerome"],
    "jerry-built": ["shoddy"],
    "jersey": ["island of jersey"],
    "jersey elm": ["guernsey elm", "ulmus campestris sarniensis", "ulmus campestris wheatleyi", "ulmus sarniensis", "wheately elm"],
    "jerusalem": ["capital of israel"],
    "jerusalem artichoke": ["girasol", "helianthus tuberosus", "jerusalem artichoke sunflower"],
    "jerusalem cherry": ["madeira winter cherry", "solanum pseudocapsicum", "winter cherry"],
    "jerusalem oak": ["atriplex mexicana", "chenopodium botrys", "feather geranium", "mexican tea"],
    "jerusalem sage": ["phlomis fruticosa"],
    "jerusalem thorn": ["horsebean", "parkinsonia aculeata"],
    "jespersen": ["jens otto harry jespersen", "otto jespersen"],
    "jest": ["jocularity", "joke"],
    "jester": ["fool", "motley fool"],
    "jesting": ["jocose", "jocular", "joking"],
    "jesuitical": ["jesuit", "jesuitic"],
    "jesuitism": ["jesuitry"],
    "jesus": ["christ", "deliverer", "good shepherd", "jesus christ", "jesus of nazareth", "redeemer", "savior", "saviour", "the nazarene"],
    "jet": ["gush"],
    "jeth": ["jyaistha"],
    "jetting": ["spouting", "spurting", "squirting"],
    "jevons": ["william stanley jevons"],
    "jew": ["hebrew", "israelite"],
    "jew's harp": ["jews' harp", "mouth bow"],
    "jew's-ear": ["auricularia auricula", "ear fungus", "jew's-ears"],
    "jewbush": ["jew bush", "jew-bush", "pedilanthus tithymaloides", "redbird cactus", "redbird flower"],
    "jewel": ["gem"],
    "jeweler": ["jeweller"],
    "jewelled headdress": ["jeweled headdress"],
    "jewelry": ["jewellery"],
    "jewelry dealer": ["jewelry store"],
    "jewelry maker": ["jeweler", "jeweller"],
    "jewels-of-opar": ["talinum paniculatum"],
    "jewelweed": ["celandine", "impatiens capensis", "lady's earrings", "orange balsam", "touch-me-not"],
    "jewfish": ["mycteroperca bonaci"],
    "jewish": ["judaic"],
    "jewish calendar": ["hebrew calendar"],
    "jewish rye bread": ["jewish rye"],
    "jewison": ["norman jewison"],
    "jibe": ["change course", "gybe", "jib"],
    "jig": ["gigue"],
    "jiggermast": ["jigger"],
    "jiggle": ["joggle", "wiggle"],
    "jigsaw": ["fretsaw", "scroll saw"],
    "jihad": ["international jihad", "jehad"],
    "jilted": ["rejected", "spurned"],
    "jimdandy": ["crackerjack", "jimhickey"],
    "jimenez": ["juan ramon jimenez"],
    "jimenez de cisneros": ["francisco jimenez de cisneros"],
    "jimmies": ["sprinkles"],
    "jimmy": ["jemmy"],
    "jimsonweed": ["apple of peru", "common thorn apple", "datura stramonium", "jamestown weed", "jimson weed"],
    "jinghpo": ["chingpo", "jinghpaw"],
    "jingle": ["jangle", "jingle-jangle"],
    "jingling": ["jingly"],
    "jinks": ["high jinks", "high jinx", "hijinks"],
    "jinnah": ["muhammad ali jinnah"],
    "jinrikisha": ["ricksha", "rickshaw"],
    "jiqui": ["malpighia obovata"],
    "jitteriness": ["jumpiness", "nervousness", "restiveness"],
    "jitters": ["heebie-jeebies", "screaming meemies"],
    "joachim": ["joseph joachim"],
    "job": ["book of job"],
    "job interview": ["employment interview"],
    "jobber": ["middleman", "wholesaler"],
    "jocosely": ["jocular"],
    "jocoseness": ["humorousness", "jocosity", "merriness"],
    "jocosity": ["jocularity"],
    "jocundity": ["jocularity"],
    "jodhpur": ["jodhpur boot", "jodhpur shoe"],
    "jodhpurs": ["jodhpur breeches", "riding breeches"],
    "joe-pye weed": ["eupatorium purpureum", "marsh milkweed", "purple boneset", "trumpet weed"],
    "joel": ["book of joel"],
    "joffre": ["joseph jacques cesaire joffre"],
    "joffrey": ["robert joffrey"],
    "jog": ["lope", "trot"],
    "joggle": ["jiggle"],
    "john": ["john lackland", "king john"],
    "john chrysostom": ["st. john chrysostom"],
    "john doe": ["joe bloggs", "joe blow", "man in the street"],
    "john dory": ["zeus faber"],
    "john of gaunt": ["duke of lancaster"],
    "john paul i": ["albino luciano"],
    "john paul ii": ["karol wojtyla"],
    "john the baptist": ["st. john the baptist"],
    "john xxiii": ["angelo guiseppe roncalli"],
    "johnnycake": ["johnny cake", "journey cake"],
    "johns": ["jasper johns"],
    "johnson": ["dr. johnson", "samuel johnson"],
    "johnson grass": ["aleppo grass", "evergreen millet", "means grass", "sorghum halepense"],
    "johnston": ["j. e. johnston", "joseph eggleston johnston"],
    "join": ["fall in", "get together"],
    "joined": ["united"],
    "joining": ["connection", "connexion"],
    "joint": ["articulate"],
    "joint chiefs of staff": ["joint chiefs"],
    "joint direct attack munition": ["jdam"],
    "jointed charlock": ["raphanus raphanistrum", "runch", "wild radish", "wild rape"],
    "jointed rush": ["juncus articulatus"],
    "jointer": ["jointer plane", "jointing plane", "long plane"],
    "jointly": ["collectively", "conjointly", "together with"],
    "jointure": ["legal jointure"],
    "joke": ["jest"],
    "joker": ["turkey"],
    "jokingly": ["jestingly"],
    "joliot": ["jean-frederic joliot", "jean-frederic joliot-curie", "joliot-curie"],
    "joliot-curie": ["irene joliot-curie"],
    "jolliet": ["joliet", "louis joliet", "louis jolliet"],
    "jollity": ["jolliness", "joviality"],
    "jolly boat": ["jolly"],
    "jolson": ["al jolson", "asa yoelson"],
    "jolt": ["jar"],
    "jolted": ["shaken"],
    "jonah": ["jinx"],
    "jonah crab": ["cancer borealis"],
    "jones": ["mary harris jones", "mother jones"],
    "jones' penstemon": ["penstemon dolius"],
    "jong": ["erica jong"],
    "jonquil": ["narcissus jonquilla"],
    "jonson": ["ben jonson", "benjamin jonson"],
    "joplin": ["janis joplin"],
    "jordan": ["jordan river"],
    "jordanella": ["genus jordanella"],
    "jordanian dinar": ["dinar"],
    "joseph": ["chief joseph"],
    "josephus": ["flavius josephus", "joseph ben matthias"],
    "joshua": ["book of joshua", "josue"],
    "joshua tree": ["yucca brevifolia"],
    "jostle": ["shove"],
    "jot down": ["jot"],
    "jotting": ["jot"],
    "jotun": ["jotunn"],
    "joule": ["watt second"],
    "journalism": ["news media"],
    "journey": ["journeying"],
    "joust": ["tilt"],
    "jovian planet": ["gas giant"],
    "jowett": ["benjamin jowett"],
    "joy": ["joyfulness", "joyousness"],
    "joyce": ["james augustine aloysius joyce", "james joyce"],
    "joyride": ["tool", "tool around"],
    "juan carlos": ["juan carlos victor maria de borbon y borbon"],
    "judah": ["juda"],
    "judaic": ["judaical"],
    "judaism": ["hebraism", "jewish religion"],
    "judas": ["judas iscariot"],
    "judas tree": ["circis siliquastrum", "love tree"],
    "judder": ["shake"],
    "jude": ["judas", "saint jude", "st. jude", "thaddaeus"],
    "judea": ["judaea"],
    "judeo-spanish": ["ladino"],
    "judge": ["adjudicate", "try"],
    "judges": ["book of judges"],
    "judgeship": ["judicature"],
    "judgment": ["judgement", "mind"],
    "judgment day": ["crack of doom", "day of judgement", "day of judgment", "day of reckoning", "doomsday", "end of the world", "eschaton", "judgement day", "last day", "last judgement", "last judgment"],
    "judgment in personam": ["judgement in personam", "personal judgement", "personal judgment"],
    "judgment in rem": ["judgement in rem"],
    "judgment of dismissal": ["dismissal", "judgement of dismissal"],
    "judgment on the merits": ["judgement on the merits"],
    "judicial": ["juridic", "juridical"],
    "judiciary": ["judicatory", "judicature", "judicial system"],
    "judicious": ["heady", "wise"],
    "judiciousness": ["sagaciousness", "sagacity"],
    "judith": ["book of judith"],
    "jug": ["jugful"],
    "jugale": ["jugal point"],
    "juggernaut": ["steamroller"],
    "juggle": ["beguile", "hoodwink"],
    "juglandaceae": ["family juglandaceae", "walnut family"],
    "juglandales": ["order juglandales"],
    "juglans": ["genus juglans"],
    "jugular vein": ["jugular", "vena jugularis"],
    "juice": ["succus"],
    "juicy": ["luscious", "red-hot", "toothsome", "voluptuous"],
    "juju": ["fetich", "fetish", "hoodoo", "voodoo"],
    "jujube": ["christ's-thorn", "jerusalem thorn", "jujube bush", "ziziphus jujuba"],
    "jujutsu": ["jiujitsu", "jujitsu"],
    "juke": ["jook", "jook house", "jook joint", "juke house", "juke joint"],
    "jukebox": ["nickelodeon"],
    "julep": ["mint julep"],
    "julian": ["flavius claudius julianus", "julian the apostate"],
    "julian calendar": ["old style calendar"],
    "julienne": ["julienne vegetable"],
    "jumada i": ["jomada i"],
    "jumada ii": ["jomada ii"],
    "jumble": ["mingle"],
    "jumbojet": ["jumbo jet"],
    "jumby bead": ["jumbie bead", "ormosia coarctata"],
    "jump": ["jump off", "leap"],
    "jump rope": ["skip rope", "skipping rope"],
    "jump suit": ["jumpsuit"],
    "jumper": ["pinafore", "pinny"],
    "jumper cable": ["booster cable", "jumper lead", "lead"],
    "jumping bean": ["jumping seed", "mexican jumping bean"],
    "jumping bristletail": ["machilid"],
    "jumping orchid": ["catasetum macrocarpum"],
    "jumping plant louse": ["psylla", "psyllid"],
    "jumping-off place": ["point of departure"],
    "jumpstart": ["jump", "jump-start"],
    "juncaceae": ["family juncaceae", "rush family"],
    "junco": ["snowbird"],
    "junction": ["colligation", "conjugation", "conjunction"],
    "junction barrier": ["barrier strip"],
    "juncture": ["critical point", "crossroads"],
    "juncus": ["genus juncus"],
    "jund-ul-islam": ["soldiers of god"],
    "june beetle": ["june bug", "may beetle", "may bug"],
    "juneau": ["capital of alaska"],
    "juneberry": ["service tree", "serviceberry", "shadblow", "shadbush"],
    "jung": ["carl gustav jung", "carl jung"],
    "jungermanniaceae": ["family jungermanniaceae"],
    "jungermanniales": ["order jungermanniales"],
    "jungle cat": ["felis chaus"],
    "jungle fowl": ["gallina"],
    "junior": ["jnr", "jr"],
    "junior high school": ["junior high"],
    "junior varsity": ["jv"],
    "junior-grade": ["lower-ranking", "lowly", "petty", "secondary", "subaltern"],
    "juniperus": ["genus juniperus"],
    "junk bond": ["high-yield bond"],
    "junkers": ["hugo junkers"],
    "junketeer": ["junket"],
    "junoesque": ["statuesque"],
    "jupati": ["jupati palm", "jupaty", "raffia taedigera"],
    "jupiter": ["jove"],
    "jupiter fidius": ["protector of boundaries"],
    "jupiter fulgur": ["jupiter fulminator", "lightning hurler"],
    "jupiter optimus maximus": ["best and greatest"],
    "jupiter pluvius": ["rain-giver"],
    "jupiter tonans": ["thunderer"],
    "jupiter's beard": ["anthyllis barba-jovis", "silver-bush", "silverbush"],
    "jural": ["juristic"],
    "jurassic": ["jurassic period"],
    "juridical": ["juridic"],
    "jurisprudence": ["law", "legal philosophy"],
    "jurist": ["legal expert"],
    "juror": ["juryman", "jurywoman"],
    "jury": ["panel"],
    "jussieu": ["antoine laurent de jussieu"],
    "just": ["simply"],
    "just-noticeable difference": ["jnd"],
    "justice": ["justness"],
    "justiciar": ["justiciary"],
    "justificative": ["justificatory", "vindicatory"],
    "justify": ["warrant"],
    "justinian": ["justinian i", "justinian the great"],
    "justly": ["right"],
    "justness": ["nicety", "rightness"],
    "jutland": ["jylland"],
    "jutting": ["projected", "projecting", "protruding", "relieved", "sticking", "sticking out"],
    "juvenal": ["decimus junius juvenalis"],
    "juvenile": ["juvenile person"],
    "juxtaposition": ["apposition", "collocation"],
    "jynx": ["genus jynx"],
    "k2": ["dapsang", "godwin austen", "mount godwin austen"],
    "kaaba": ["caaba"],
    "kabbalah": ["cabala", "cabbala", "cabbalah", "kabala", "kabbala", "qabbala", "qabbalah"],
    "kabbalism": ["cabalism"],
    "kabob": ["kebab", "shish kebab"],
    "kabul": ["capital of afghanistan"],
    "kachaturian": ["aram kachaturian"],
    "kachin": ["kachinic"],
    "kadai": ["kadai language", "kam-tai"],
    "kaffir": ["caffer", "caffre", "kafir"],
    "kaffir boom": ["erythrina lysistemon", "transvaal kafferboom"],
    "kaffir bread": ["encephalartos caffer"],
    "kaffir cat": ["caffer cat", "felis ocreata"],
    "kafka": ["franz kafka"],
    "kahane chai": ["kach"],
    "kahikatea": ["dacrycarpus dacrydioides", "new zealand dacryberry", "new zealand white pine", "podocarpus dacrydioides"],
    "kahn": ["louis isadore kahn"],
    "kahoolawe": ["kahoolawe island"],
    "kakatoe": ["cacatua", "genus cacatua", "genus kakatoe"],
    "kaki": ["himantopus novae-zelandiae"],
    "kalahari": ["kalahari desert"],
    "kalapooia": ["calapooya", "calapuya", "kalapuya"],
    "kalapooian": ["kalapuyan"],
    "kale": ["borecole", "brassica oleracea acephala", "cole", "colewort", "kail"],
    "kaleidoscopic": ["kaleidoscopical"],
    "kalinin": ["mikhail ivanovich kalinin", "mikhail kalinin"],
    "kaliuresis": ["kaluresis"],
    "kalotermes": ["genus kalotermes"],
    "kalotermitidae": ["family kalotermitidae"],
    "kalumpang": ["java olives", "sterculia foetida"],
    "kamchatkan sea eagle": ["haliaeetus pelagicus", "stellar's sea eagle"],
    "kamehameha i": ["kamehameha the great"],
    "kampala": ["capital of uganda"],
    "kampong": ["campong"],
    "kanamycin": ["kantrex"],
    "kananga": ["luluabourg"],
    "kanara": ["canara"],
    "kanarese": ["canarese"],
    "kanawha": ["kanawha river"],
    "kanchenjunga": ["kanchanjanga", "kinchinjunga", "mount kanchenjunga"],
    "kanchil": ["tragulus kanchil"],
    "kandahar": ["qandahar"],
    "kandinsky": ["kandinski", "wassily kandinski", "wassily kandinsky"],
    "kangaroo apple": ["poroporo", "solanum aviculare"],
    "kangaroo mouse": ["dwarf pocket rat"],
    "kangaroo paw": ["anigozanthus manglesii", "australian sword lily", "kangaroo's paw", "kangaroo's-foot", "kangaroo-foot plant"],
    "kangaroo rat": ["desert rat", "dipodomys phillipsii"],
    "kannada": ["kanarese"],
    "kansa": ["kansas"],
    "kansas": ["kansas river", "kaw river"],
    "kant": ["immanuel kant"],
    "kaon": ["k particle", "k-meson", "kappa-meson"],
    "kaplan group": ["association of islamic groups and communities", "caliphate state"],
    "kapok": ["silk cotton", "vegetable silk"],
    "kapuka": ["griselinia littoralis"],
    "kara kum": ["qara qum", "turkestan desert"],
    "karakoram": ["karakoram range", "karakorum range", "mustagh", "mustagh range"],
    "karat": ["carat", "kt"],
    "karelian": ["carelian"],
    "karen": ["karenic"],
    "karlfeldt": ["erik axel karlfeldt"],
    "karloff": ["boris karloff", "william henry pratt"],
    "karnataka": ["mysore"],
    "karpov": ["anatoli karpov", "anatoli yevgenevich karpov"],
    "karsavina": ["tamara karsavina"],
    "kartik": ["karttika"],
    "kartikeya": ["karttikeya"],
    "kasai": ["kasai river", "river kasai"],
    "kasbah": ["casbah"],
    "kashmir": ["cashmere", "jammu and kashmir"],
    "kasparov": ["gary kasparov", "gary weinstein"],
    "kassite": ["cassite"],
    "kastler": ["alfred kastler"],
    "kat": ["african tea", "arabian tea", "cat", "khat", "qat", "quat"],
    "katabatic": ["catabatic"],
    "katabatic wind": ["catabatic wind"],
    "kathmandu": ["capital of nepal", "katmandu"],
    "katsura tree": ["cercidiphyllum japonicum"],
    "katsuwonidae": ["family kasuwonidae"],
    "katsuwonus": ["genus katsuwonus"],
    "kauai": ["kauai island"],
    "kaufman": ["george s. kaufman", "george simon kaufman"],
    "kaunas": ["kovna", "kovno"],
    "kaunda": ["kenneth david kaunda", "kenneth kaunda"],
    "kauri": ["kauri copal", "kauri gum", "kauri resin"],
    "kauri pine": ["dammar pine"],
    "kava": ["kavakava"],
    "kawaka": ["libocedrus plumosa"],
    "kawasaki disease": ["mucocutaneous lymph node syndrome"],
    "kazak": ["kazakh"],
    "kazakhstan": ["kazak", "kazakh", "kazakstan", "republic of kazakhstan"],
    "kazan": ["elia kazan", "elia kazanjoglous"],
    "kea": ["nestor notabilis"],
    "kean": ["edmund kean"],
    "keaton": ["buster keaton", "joseph francis keaton"],
    "keats": ["john keats"],
    "keble": ["john keble"],
    "keeled garlic": ["allium carinatum"],
    "keen-eyed": ["sharp-eyed"],
    "keep": ["stay fresh"],
    "keep off": ["avoid"],
    "keep one's eyes peeled": ["keep one's eyes open", "keep one's eyes skinned"],
    "keep open": ["hold open", "keep", "save"],
    "keep quiet": ["keep one's mouth shut", "shut one's mouth"],
    "keep step": ["keep pace"],
    "keep up": ["follow", "keep abreast"],
    "keepsake": ["relic", "souvenir", "token"],
    "keg": ["kegful"],
    "kegel exercises": ["pubococcygeus exercises"],
    "kei apple": ["dovyalis caffra", "kei apple bush"],
    "kekule": ["friedrich august kekule", "friedrich august kekule von stradonitz"],
    "keller": ["helen adams keller", "helen keller"],
    "kellogg": ["w. k. kellogg", "will keith kellog"],
    "kelly": ["emmett kelly", "weary willie"],
    "keloid": ["cheloid"],
    "kelp greenling": ["hexagrammos decagrammus"],
    "kelpy": ["kelpie"],
    "kelvin": ["first baron kelvin", "william thompson"],
    "kelvin scale": ["absolute scale"],
    "kempt": ["tidy"],
    "kenaf": ["deccan hemp"],
    "kendal green": ["kendal"],
    "kendall": ["edward calvin kendall", "edward kendall"],
    "kendrew": ["sir john cowdery kendrew"],
    "kennan": ["george f. kennan", "george frost kennan"],
    "kennedia": ["genus kennedia", "genus kennedya", "kennedya"],
    "kennedy": ["jack kennedy", "jfk", "john fitzgerald kennedy", "president john f. kennedy", "president kennedy"],
    "kennel": ["dog house", "doghouse"],
    "kennelly": ["a. e. kennelly", "arthur edwin kennelly"],
    "kent": ["rockwell kent"],
    "kentish": ["jutish"],
    "kentuckian": ["bluegrass stater"],
    "kentucky": ["bluegrass state", "ky"],
    "kentucky black bass": ["micropterus pseudoplites", "spotted black bass"],
    "kentucky bluegrass": ["june grass", "kentucky blue", "kentucy blue grass", "poa pratensis"],
    "kentucky coffee tree": ["bonduc", "chicot", "gymnocladus dioica"],
    "kentucky wonder": ["kentucky wonder bean"],
    "kentucky yellowwood": ["cladrastis kentukea", "cladrastis lutea", "gopherwood"],
    "kenya": ["republic of kenya"],
    "kenyan shilling": ["shilling"],
    "kenyapithecus": ["genus kenyapithecus"],
    "kenyata": ["jomo kenyata"],
    "kepi": ["peaked cap", "service cap", "yachting cap"],
    "kepler": ["johan kepler", "johannes kepler"],
    "kepler's law": ["kepler's law of planetary motion"],
    "kepler's second law": ["law of areas", "law of equal areas"],
    "kepler's third law": ["harmonic law"],
    "kept up": ["maintained", "well-kept"],
    "keratin": ["ceratin"],
    "keratinization": ["keratinisation"],
    "keratinize": ["keratinise"],
    "keratoderma": ["keratodermia"],
    "keratoplasty": ["corneal graft", "corneal transplant"],
    "keratosis blennorrhagica": ["keratoderma blennorrhagica"],
    "keratosis follicularis": ["darier's disease"],
    "kerbala": ["karbala", "kerbela"],
    "kerensky": ["aleksandr feodorovich kerensky"],
    "kern": ["jerome david kern", "jerome kern"],
    "kernel": ["meat"],
    "kerosene": ["coal oil", "kerosine", "lamp oil"],
    "kerouac": ["jack kerouac", "jean-louis lebris de kerouac"],
    "kerygma": ["kerugma"],
    "kesey": ["ken elton kesey", "ken kesey"],
    "kestrel": ["falco tinnunculus"],
    "ketamine": ["ketalar", "ketamine hydrochloride"],
    "ketembilla": ["ceylon gooseberry", "dovyalis hebecarpa", "ketembilla tree", "kitambilla", "kitembilla"],
    "ketoacidosis": ["diabetic acidosis"],
    "ketone body": ["acetone body"],
    "ketonemia": ["acetonemia", "ketosis"],
    "ketonuria": ["acetonuria", "ketoaciduria"],
    "ketoprofen": ["orudis", "orudis kt", "oruvail"],
    "ketorolac": ["torodal"],
    "ketorolac tromethamine": ["acular", "toradol"],
    "kettering": ["charles franklin kettering", "charles kettering"],
    "kettle": ["kettleful"],
    "kettle hole": ["kettle"],
    "keuka lake": ["lake keuka"],
    "keurboom": ["virgilia divaricata"],
    "key": ["francis scott key"],
    "key palm": ["silver thatch", "silvertop palmetto", "thrinax keyensis", "thrinax microcarpa", "thrinax morrisii"],
    "key signature": ["signature"],
    "keyhole limpet": ["diodora apertura", "fissurella apertura"],
    "keynes": ["john maynard keynes"],
    "keynote speech": ["keynote address"],
    "keystone": ["headstone", "key"],
    "keystroke": ["key stroke"],
    "khachaturian": ["aram ilich khachaturian", "aram khachaturian"],
    "khadi": ["khaddar"],
    "khalkha": ["kalka", "khalka"],
    "khama": ["sir seretse khama"],
    "khanty": ["ostyak"],
    "kharkov": ["kharkiv"],
    "khartoum": ["capital of sudan"],
    "khaya": ["genus khaya"],
    "khmer rouge": ["communist party of kampuchea", "kr", "party of democratic kampuchea"],
    "khoikhoin": ["hottentot", "khoikhoi"],
    "khoisan": ["khoisan language"],
    "khomeini": ["ayatollah khomeini", "ayatollah ruholla khomeini", "ruholla khomeini"],
    "khrushchev": ["nikita khrushchev", "nikita sergeyevich khrushchev"],
    "kiang": ["equus kiang"],
    "kibibit": ["kibit"],
    "kibitz": ["kibbitz"],
    "kichaga": ["chaga", "chagga"],
    "kick": ["give up"],
    "kick around": ["kick about", "knock about"],
    "kick back": ["kick", "recoil"],
    "kick in": ["kick down"],
    "kick one's heels": ["cool one's heels"],
    "kick starter": ["kick start"],
    "kickoff": ["send-off", "start-off"],
    "kicksorter": ["pulse height analyzer"],
    "kid": ["banter", "chaff", "jolly", "josh"],
    "kid glove": ["suede glove"],
    "kidd": ["captain kidd", "william kidd"],
    "kidnap": ["abduct", "nobble", "snatch"],
    "kidnapper": ["abductor", "kidnaper", "snatcher"],
    "kidnapping": ["snatch"],
    "kidney bean": ["frijol", "frijole"],
    "kidney disease": ["nephropathy", "nephrosis", "renal disorder"],
    "kidney fern": ["trichomanes reniforme"],
    "kidney stone": ["nephrolith", "renal calculus", "urinary calculus"],
    "kidney vetch": ["anthyllis vulneraria"],
    "kierkegaard": ["soren aabye kierkegaard", "soren kierkegaard"],
    "kieslowski": ["krzysztof kieslowski"],
    "kigali": ["capital of rwanda"],
    "kiggelaria": ["genus kiggelaria"],
    "kike": ["hymie", "sheeny", "yid"],
    "kilimanjaro": ["mount kilimanjaro"],
    "kiliwa": ["kiliwi"],
    "kill": ["defeat", "shoot down", "vote down", "vote out"],
    "kill oneself": ["overexert oneself"],
    "kill zone": ["killing zone"],
    "killarney fern": ["trichomanes speciosum"],
    "killdeer": ["charadrius vociferus", "kildeer", "killdeer plover"],
    "killer": ["slayer"],
    "killer t cell": ["cd8 cell", "cd8 t cell", "cytotoxic t cell", "killer cell"],
    "killer whale": ["grampus", "killer", "orca", "orcinus orca", "sea wolf"],
    "killing": ["cleanup"],
    "killingly": ["sidesplittingly"],
    "kilobit": ["kb", "kbit"],
    "kilobyte": ["kb"],
    "kilogram": ["kg", "kilo"],
    "kilohertz": ["kc", "khz", "kilocycle", "kilocycle per second"],
    "kiloliter": ["cubic meter", "cubic metre", "kilolitre"],
    "kilometer": ["kilometre", "klick", "km"],
    "kilometers per hour": ["kilometres per hour", "km/h", "kph"],
    "kilovolt": ["kv"],
    "kilowatt": ["kw"],
    "kilowatt hour": ["b.t.u.", "board of trade unit", "kw-hr"],
    "kilter": ["kelter"],
    "kin": ["family", "kinsperson"],
    "kind": ["form", "sort", "variety"],
    "kindhearted": ["kind-hearted"],
    "kindheartedness": ["kind-heartedness"],
    "kindle": ["inflame"],
    "kindliness": ["helpfulness"],
    "kindling": ["punk", "spunk", "tinder", "touchwood"],
    "kindness": ["benignity"],
    "kinescope": ["picture tube", "television tube"],
    "kinesthesia": ["feeling of movement", "kinaesthesia"],
    "kinesthesis": ["kinaesthesia", "kinaesthesis", "kinesthesia", "kinesthetics", "muscle sense", "sense of movement"],
    "kinesthetic": ["kinaesthetic"],
    "kinesthetically": ["kinaesthetically"],
    "kinetic energy": ["k.e."],
    "kinetic theory": ["kinetic theory of gases"],
    "king": ["billie jean king", "billie jean moffitt king"],
    "king crab": ["alaska crab", "alaska king crab", "alaskan king crab", "paralithodes camtschatica"],
    "king devil": ["hieracium praealtum", "yellow hawkweed"],
    "king mackerel": ["cavalla", "cero", "scomberomorus cavalla"],
    "king of england": ["king of great britain"],
    "king penguin": ["aptenodytes patagonica"],
    "king snake": ["kingsnake"],
    "king vulture": ["sarcorhamphus papa"],
    "king whiting": ["menticirrhus americanus"],
    "king william pine": ["athrotaxis selaginoides"],
    "king's english": ["queen's english"],
    "king's spear": ["asphodeline lutea", "yellow asphodel"],
    "king-size": ["king-sized"],
    "kingbird": ["tyrannus tyrannus"],
    "kingbolt": ["kingpin", "swivel pin"],
    "kingdom": ["land", "realm"],
    "kingfish": ["seriola grandis"],
    "kingfisher daisy": ["felicia bergeriana"],
    "kingly": ["kinglike"],
    "kingpin": ["bigwig", "top banana"],
    "kingston": ["capital of jamaica", "jamaican capital"],
    "kingwood": ["dalbergia cearensis", "kingwood tree"],
    "kinin": ["cytokinin"],
    "kink": ["twirl", "twist"],
    "kinkajou": ["honey bear", "potos caudivolvulus", "potos flavus", "potto"],
    "kinky": ["perverted"],
    "kino": ["gum kino", "kino gum"],
    "kinosternidae": ["family kinosternidae"],
    "kinosternon": ["genus kinosternon"],
    "kinsey": ["alfred charles kinsey"],
    "kinshasa": ["leopoldville"],
    "kinship": ["family relationship", "relationship"],
    "kip": ["upstart"],
    "kipling": ["joseph rudyard kipling", "rudyard kipling"],
    "kipper": ["kippered herring"],
    "kirchhoff": ["g. r. kirchhoff", "gustav robert kirchhoff"],
    "kirchner": ["ernst ludwig kirchner"],
    "kirghiz": ["khirghiz", "kirgiz"],
    "kiribati": ["republic of kiribati"],
    "kirkia": ["genus kirkia"],
    "kishinev": ["capital of moldova", "chisinau"],
    "kishke": ["stuffed derma"],
    "kislev": ["chislev"],
    "kismet": ["kismat"],
    "kiss": ["candy kiss"],
    "kisser": ["osculator"],
    "kissimmee": ["kissimmee river"],
    "kissing cousin": ["kissing kin"],
    "kissinger": ["henry alfred kissinger", "henry kissinger"],
    "kit": ["outfit"],
    "kit fox": ["vulpes macrotis"],
    "kit out": ["kit", "kit up"],
    "kitbag": ["kit bag"],
    "kitchen cabinet": ["brain trust"],
    "kitchen garden": ["vegetable garden", "vegetable patch"],
    "kitchen police": ["kp"],
    "kitchener": ["first earl kitchener of khartoum", "herbert kitchener", "horatio herbert kitchener"],
    "kitten": ["kitty"],
    "kittenish": ["frisky"],
    "kitty": ["kitty-cat", "puss", "pussy", "pussycat"],
    "kivu": ["lake kivu"],
    "kiwi": ["chinese gooseberry", "kiwi fruit"],
    "klaipeda": ["memel"],
    "klamath": ["klamath river"],
    "klammath weed": ["hypericum perforatum"],
    "klansman": ["kluxer", "ku kluxer"],
    "klaproth": ["martin heinrich klaproth"],
    "klaxon": ["claxon"],
    "klee": ["paul klee"],
    "klein": ["felix klein"],
    "kleist": ["bernd heinrich wilhelm von kleist", "heinrich von kleist"],
    "klimt": ["gustav klimt"],
    "kline": ["franz joseph kline", "franz kline"],
    "klinefelter": ["harry f. klinefelter", "harry fitch kleinfelter"],
    "klinefelter's syndrome": ["klinefelter syndrome", "xxy-syndrome"],
    "klopstock": ["friedrich gottlieb klopstock"],
    "knackered": ["drained"],
    "knackwurst": ["knockwurst"],
    "knawel": ["knawe", "scleranthus annuus"],
    "knead": ["work"],
    "knee": ["articulatio genus", "genu", "human knee", "knee joint"],
    "knee bend": ["squat", "squatting"],
    "knee jerk": ["knee-jerk reflex", "patellar reflex"],
    "knee-deep": ["knee-high"],
    "knee-high": ["knee-hi"],
    "kneel": ["kneeling"],
    "knesset": ["knesseth"],
    "knickknack": ["novelty"],
    "knife": ["stab"],
    "knife edge": ["cutting edge"],
    "knife fight": ["cut-and-thrust", "snickersnee"],
    "knight": ["dub"],
    "knight bachelor": ["bachelor", "bachelor-at-arms"],
    "knight banneret": ["banneret", "knight of the square flag"],
    "knight errantry": ["quixotism"],
    "knight templar": ["templar"],
    "knightia": ["genus knightia"],
    "kniphofia": ["flame flower", "flame-flower", "flameflower", "tritoma"],
    "knit": ["entwine"],
    "knob": ["pommel"],
    "knobby": ["knobbly"],
    "knobcone pine": ["pinus attenuata"],
    "knobkerrie": ["knobkerry"],
    "knock": ["strike hard"],
    "knock cold": ["kayo", "knock out"],
    "knock-down": ["powerful"],
    "knock-knee": ["genu valgum", "tibia valga"],
    "knockdown-dragout": ["knock-down-and-drag-out"],
    "knocked out": ["kayoed", "ko'd", "out", "stunned"],
    "knocker": ["doorknocker", "rapper"],
    "knockoff": ["clone"],
    "knockout": ["kayo", "ko"],
    "knoll": ["hammock", "hillock", "hummock", "mound"],
    "knossos": ["cnossos", "cnossus"],
    "knot": ["gnarl"],
    "knotgrass": ["paspalum distichum"],
    "knotty": ["snarled", "snarly"],
    "know": ["experience", "live"],
    "know the score": ["be on the ball", "be with it", "know what's going on", "know what's what"],
    "know-it-all": ["know-all"],
    "knowable": ["cognisable", "cognizable", "cognoscible"],
    "knower": ["apprehender"],
    "knowing": ["wise", "wise to"],
    "knowledge domain": ["domain", "knowledge base"],
    "knowledgeability": ["initiation", "knowledgeableness"],
    "knowledgeable": ["knowing"],
    "knowlton's cactus": ["pediocactus knowltonii"],
    "knox": ["john knox"],
    "knuckle": ["knuckle joint", "metacarpophalangeal joint"],
    "knuckle joint": ["hinge joint"],
    "knuckleball": ["knuckler"],
    "koala": ["kangaroo bear", "koala bear", "native bear", "phascolarctos cinereus"],
    "kob": ["kobus kob"],
    "kobus": ["genus kobus"],
    "koch": ["robert koch"],
    "kodiak": ["kodiak island"],
    "koestler": ["arthur koestler"],
    "kogia": ["genus kogia"],
    "kohlrabi": ["brassica oleracea gongylodes"],
    "kokka shinto": ["kokka"],
    "kola": ["cola acuminata", "goora nut", "kola nut", "kola nut tree"],
    "kola nut": ["cola nut"],
    "kolkata": ["calcutta"],
    "kolkwitzia": ["genus kolkwitzia"],
    "komi": ["zyrian"],
    "komodo dragon": ["dragon lizard", "giant lizard", "komodo lizard", "varanus komodoensis"],
    "konini": ["fuchsia excorticata", "native fuchsia", "tree fuchsia"],
    "konoe": ["fumimaro konoe", "fumimaro konoye", "konoye", "prince fumimaro konoe", "prince fumimaro konoye"],
    "kook": ["odd fellow", "odd fish", "odd man out", "queer bird", "queer duck"],
    "kookaburra": ["dacelo gigas", "laughing jackass"],
    "koopmans": ["tjalling charles koopmans", "tjalling koopmans"],
    "kopek": ["copeck", "kopeck"],
    "kopje": ["koppie"],
    "koran": ["al-qur'an", "book", "quran"],
    "korbut": ["olga korbut"],
    "korchnoi": ["viktor korchnoi", "viktor lvovich korchnoi"],
    "korda": ["sandor kellner", "sir alexander korda"],
    "korea": ["dae-han-min-gook", "han-gook", "korean peninsula"],
    "korean lawn grass": ["japanese lawn grass", "zoysia japonica"],
    "korean lespedeza": ["lespedeza stipulacea"],
    "korean strait": ["korea strait"],
    "korzybski": ["alfred habdank skarbek korzybski", "alfred korzybski"],
    "kos": ["coss"],
    "kosciusko": ["kosciuszko", "tadeusz andrzej bonawentura kosciuszko", "thaddeus kosciusko"],
    "kosher": ["cosher"],
    "kosteletzya": ["genus kosteletzya"],
    "kota": ["kotar"],
    "koumiss": ["kumis"],
    "koussevitzky": ["serge koussevitzky", "sergei aleksandrovich koussevitzky"],
    "kowhai": ["sophora tetraptera"],
    "kowtow": ["kotow"],
    "krafft-ebing": ["baron richard von krafft-ebing", "richard von krafft-ebing"],
    "kraft": ["kraft paper"],
    "krakatau": ["krakatao", "krakatoa"],
    "krasner": ["lee krasner"],
    "kraut": ["boche", "hun", "jerry", "krauthead"],
    "krebs": ["hans adolf krebs", "sir hans adolf krebs"],
    "krebs cycle": ["citric acid cycle", "krebs citric acid cycle", "tricarboxylic acid cycle"],
    "kreisler": ["fritz kreisler"],
    "kris": ["crease", "creese"],
    "kroeber": ["alfred kroeber", "alfred louis kroeber"],
    "kronecker": ["leopold kronecker"],
    "kropotkin": ["prince peter kropotkin", "pyotr alexeyevich kropotkin"],
    "kroto": ["harold kroto", "harold w. kroto", "sir harold walter kroto"],
    "krubi": ["amorphophallus titanum", "titan arum"],
    "kruger": ["oom paul kruger", "stephanus johannes paulus kruger"],
    "krummhorn": ["cromorne", "crumhorn"],
    "krupp": ["alfred krupp"],
    "krypterophaneron": ["genus krypterophaneron"],
    "krypton": ["atomic number 36", "kr"],
    "ku klux klan": ["kkk", "klan"],
    "kublai khan": ["kubla khan", "kublai kaan"],
    "kubrick": ["stanley kubrick"],
    "kuchean": ["kuchean dialect", "west tocharian"],
    "kudu": ["koodoo", "koudou"],
    "kudzu": ["kudzu vine", "pueraria lobata"],
    "kuhn": ["richard kuhn"],
    "kuiper": ["gerard kuiper", "gerard peter kuiper"],
    "kuiper belt": ["edgeworth-kuiper belt"],
    "kuiper belt object": ["kbo"],
    "kuki": ["chin", "kuki-chin"],
    "kumquat": ["cumquat", "kumquat tree"],
    "kunlun": ["kuenlun", "kuenlun mountains", "kunlan shan", "kunlun mountains"],
    "kuomintang": ["guomindang"],
    "kura": ["kura river"],
    "kurdistan workers party": ["kurdistan labor pary", "partiya karkeran kurdistan", "ppk"],
    "kurosawa": ["akira kurosawa"],
    "kurrajong": ["brachychiton populneus", "currajong"],
    "kurus": ["piaster", "piastre"],
    "kutuzov": ["mikhail ilarionovich kutuzov", "prince of smolensk"],
    "kuwait": ["capital of kuwait", "koweit", "kuwait city"],
    "kuwaiti dinar": ["dinar"],
    "kuwaiti dirham": ["dirham"],
    "kuznets": ["simon kuznets"],
    "kwan-yin": ["kuan yin"],
    "kwanzaa": ["kwanza"],
    "kyanite": ["cyanite"],
    "kyd": ["kid", "thomas kid", "thomas kyd"],
    "kylie": ["kiley"],
    "kylix": ["cylix"],
    "kymograph": ["cymograph"],
    "kyphosidae": ["family kyphosidae"],
    "kyphosis": ["humpback", "hunchback"],
    "kyphosus": ["genus kyphosus"],
    "kyrgyzstan": ["kirghiz", "kirghizia", "kirghizstan", "kirgiz", "kirgizia", "kirgizstan", "kyrgyz republic"],
    "kyyiv": ["capital of the ukraine", "kiev"],
    "kyzyl kum": ["kizil kum", "qizil qum"],
    "l'enfant": ["charles l'enfant", "pierre charles l'enfant"],
    "l-dopa": ["bendopa", "brocadopa", "larodopa", "levodopa"],
    "la": ["lah"],
    "la fontaine": ["jean de la fontaine"],
    "la paz": ["capital of bolivia"],
    "la rochefoucauld": ["francois de la rochefoucauld"],
    "la tour": ["georges de la tour"],
    "laager": ["lager"],
    "lab": ["laboratory", "research lab", "research laboratory", "science lab", "science laboratory"],
    "lab bench": ["laboratory bench"],
    "lab coat": ["laboratory coat"],
    "laban": ["rudolph laban"],
    "labdanum": ["gum labdanum"],
    "label": ["recording label"],
    "labeled": ["labelled", "tagged"],
    "labetalol": ["labetalol hydrochloride", "normodyne", "trandate"],
    "labial artery": ["arteria labialis"],
    "labial consonant": ["labial"],
    "labial vein": ["vena labialis"],
    "labiatae": ["family labiatae", "family lamiaceae", "lamiaceae", "mint family"],
    "labiate": ["liplike"],
    "labiodental consonant": ["labiodental"],
    "lablab": ["genus lablab"],
    "labor": ["dig", "drudge", "fag", "grind", "labour", "moil", "toil", "travail"],
    "labor camp": ["labour camp"],
    "labor coach": ["birthing coach", "doula", "monitrice"],
    "labor contract": ["collective agreement", "labor agreement"],
    "labor force": ["labor pool"],
    "labor movement": ["labor", "trade union movement"],
    "labor of love": ["labour of love"],
    "labor party": ["labour party"],
    "labor-intensive": ["labour-intensive"],
    "labored": ["laboured", "strained"],
    "laborer": ["jack", "labourer", "manual laborer"],
    "laboriousness": ["operoseness", "toilsomeness"],
    "laborsaving": ["laboursaving"],
    "labrador tea": ["crystal tea", "ledum groenlandicum"],
    "labrador-ungava peninsula": ["labrador peninsula"],
    "labridae": ["family labridae"],
    "labrouste": ["henri labrouste"],
    "laburnum": ["genus laburnum"],
    "labyrinthine": ["labyrinthian", "mazy"],
    "labyrinthine artery": ["artery of the labyrinth", "internal auditory artery"],
    "labyrinthine vein": ["internal auditory vein"],
    "labyrinthitis": ["otitis interna"],
    "labyrinthodontia": ["labyrinthodonta", "superorder labyrinthodonta", "superorder labyrinthodontia"],
    "laccopetalum": ["genus laccopetalum"],
    "lace": ["lace up"],
    "lace fern": ["cheilanthes gracillima"],
    "lace making": ["tatting"],
    "lace-flower vine": ["alsobia dianthiflora", "episcia dianthiflora"],
    "lacebark": ["hoheria populnea", "houhere", "ribbonwood"],
    "laced": ["tied"],
    "lacerate": ["lacerated"],
    "lacerta": ["genus lacerta"],
    "lacertid lizard": ["lacertid"],
    "lacertidae": ["family lacertidae"],
    "lacewing": ["lacewing fly"],
    "lachaise": ["gaston lachaise"],
    "lachnolaimus": ["genus lachnolaimus"],
    "lack": ["deficiency", "want"],
    "lackey": ["flunkey", "flunky"],
    "lacking": ["absent", "missing", "wanting"],
    "lackluster": ["lacklustre", "lusterless", "lustreless"],
    "laconically": ["drily", "dryly"],
    "laconism": ["laconicism"],
    "lacrimal": ["lachrymal"],
    "lacrimal artery": ["arteria lacrimalis"],
    "lacrimal duct": ["lachrymal duct", "tear duct"],
    "lacrimal gland": ["lachrymal gland", "tear gland"],
    "lacrimal sac": ["dacryocyst", "tear sac"],
    "lacrimal secretion": ["lachrymal secretion"],
    "lacrimal vein": ["vena lacrimalis"],
    "lacrimation": ["lachrymation", "tearing", "watering"],
    "lacrimatory": ["lachrymatory"],
    "lactarius": ["genus lactarius"],
    "lactase": ["lactaid"],
    "lactobacillaceae": ["family lactobacillaceae", "family lactobacteriaceae", "lactobacteriaceae"],
    "lactophrys": ["genus lactophrys"],
    "lactose": ["milk sugar"],
    "lactose intolerance": ["lactase deficiency", "milk intolerance"],
    "lactuca": ["genus lactuca"],
    "lacuna": ["blank"],
    "lacy": ["netlike", "netted", "webbed", "webby", "weblike"],
    "ladder": ["run"],
    "ladder truck": ["aerial ladder truck"],
    "ladder-back": ["ladder-back chair"],
    "laden": ["ladened", "loaded"],
    "ladies' room": ["powder room"],
    "ladies' tobacco": ["antennaria plantaginifolia", "lady's tobacco"],
    "ladies' tresses": ["lady's tresses"],
    "ladle": ["lade", "laden"],
    "lady": ["noblewoman", "peeress"],
    "lady fern": ["athyrium filix-femina"],
    "lady tulip": ["candlestick tulip", "tulipa clusiana"],
    "lady's slipper": ["ladies' slipper", "lady-slipper", "slipper orchid"],
    "lady's smock": ["cardamine pratensis", "cuckoo flower", "cuckooflower", "meadow cress"],
    "lady's-eardrop": ["fuchsia coccinea", "ladies'-eardrop", "ladies'-eardrops", "lady's-eardrops"],
    "lady-of-the-night": ["brunfelsia americana"],
    "ladybug": ["lady beetle", "ladybeetle", "ladybird", "ladybird beetle"],
    "ladyfish": ["elops saurus", "tenpounder"],
    "ladylove": ["dulcinea"],
    "lafayette": ["la fayette", "marie joseph paul yves roch gilbert du motier", "marquis de lafayette"],
    "laffer": ["arthur laffer"],
    "laffite": ["jean laffite", "jean lafitte", "lafitte"],
    "lag": ["dawdle", "fall back", "fall behind"],
    "lag screw": ["lag bolt"],
    "lagan": ["lagend", "ligan"],
    "lagarostrobus": ["genus lagarostrobus"],
    "lagenaria": ["genus lagenaria"],
    "lagenophera": ["genus lagenophera"],
    "lager": ["lager beer"],
    "lagerstroemia": ["genus lagerstroemia"],
    "lagidium": ["genus lagidium"],
    "lagodon": ["genus lagodon"],
    "lagomorph": ["gnawing mammal"],
    "lagomorpha": ["order lagomorpha"],
    "lagoon": ["laguna", "lagune"],
    "lagopus": ["genus lagopus"],
    "lagorchestes": ["genus lagorchestes"],
    "lagostomus": ["genus lagostomus"],
    "lagothrix": ["genus lagothrix"],
    "laguncularia": ["genus laguncularia"],
    "laic": ["lay", "secular"],
    "laicize": ["laicise"],
    "laid": ["set"],
    "laid low": ["stricken"],
    "laid-back": ["mellow"],
    "lair": ["den"],
    "laity": ["temporalty"],
    "lake albert": ["lake albert nyanza", "mobuto lake"],
    "lake aral": ["aral sea"],
    "lake bed": ["lake bottom"],
    "lake chad": ["chad"],
    "lake champlain": ["champlain"],
    "lake district": ["lakeland"],
    "lake dwelling": ["pile dwelling"],
    "lake erie": ["erie"],
    "lake geneva": ["lake leman"],
    "lake herring": ["cisco"],
    "lake huron": ["huron"],
    "lake ilmen": ["ilmen"],
    "lake ladoga": ["ladoga"],
    "lake michigan": ["michigan"],
    "lake nasser": ["nasser"],
    "lake nyasa": ["lake malawi"]
}
