synonyms = {
    "automobile horn": ["alarm", "alarm system", "car horn", "hooter", "horn", "motor horn", "warning device"],
    "automobile industry": ["industry"],
    "automobile insurance": ["car insurance", "insurance", "no fault automobile insurance", "no fault insurance"],
    "automobile loan": ["auto loan", "car loan", "consumer loan", "personal loan"],
    "automobile mechanic": ["auto-mechanic", "car-mechanic", "grease monkey", "maintenance man", "mechanic", "repairman", "service man"],
    "automobile race": ["auto race", "car race", "grand prix", "race", "rally"],
    "automobile traffic": ["car traffic", "vehicle traffic", "vehicular traffic"],
    "automotive": [],
    "automotive engineer": ["applied scientist", "engineer", "technologist"],
    "automotive technology": ["automotive engineering", "engineering", "technology"],
    "automysophobia": ["simple phobia"],
    "autonomic": [],
    "autonomic ganglion": ["ganglion", "otic ganglion", "otoganglion"],
    "autonomic nervous system": ["ans", "neural structure"],
    "autonomic plexus": ["nerve plexus", "plexus autonomici"],
    "autonomous": ["independent", "self-governing", "sovereign"],
    "autonomy": ["independence", "independency", "self-direction", "self-reliance", "self-sufficiency"],
    "autophyte": ["autophytic plant", "autotroph", "autotrophic organism", "flora", "plant", "plant life"],
    "autopilot": ["automatic pilot", "device", "robot pilot"],
    "autoplastic": [],
    "autoplasty": ["anaplasty", "plastic surgery", "reconstructive surgery"],
    "autopsy": ["examine", "see"],
    "autoradiograph": ["radiogram", "radiograph", "shadowgraph", "skiagram", "skiagraph"],
    "autoradiographic": [],
    "autoradiography": ["radiography", "skiagraphy"],
    "autoregulation": ["biological process", "organic process"],
    "autosemantic": [],
    "autosexing": ["breeding"],
    "autosomal": [],
    "autosomal dominant disease": ["autosomal dominant disorder", "congenital disease", "genetic abnormality", "genetic defect", "genetic disease", "genetic disorder", "hereditary condition", "hereditary disease", "huntington's chorea", "huntington's disease", "inherited disease", "inherited disorder", "malignant hyperthermia", "marfan's syndrome", "neurofibromatosis", "osteogenesis imperfecta", "von recklinghausen's disease"],
    "autosomal recessive disease": ["autosomal recessive defect", "congenital disease", "genetic abnormality", "genetic defect", "genetic disease", "genetic disorder", "hereditary condition", "hereditary disease", "infantile amaurotic idiocy", "inherited disease", "inherited disorder", "limb-girdle muscular dystrophy", "niemann-pick disease", "sachs disease", "tay-sachs", "tay-sachs disease", "thrombasthenia", "tyrosinemia", "werdnig-hoffman disease"],
    "autosome": ["chromosome", "somatic chromosome"],
    "autostrada": ["expressway", "freeway", "motorway", "pike", "state highway", "superhighway", "throughway", "thruway"],
    "autosuggestion": ["auto-suggestion", "self-improvement", "self-reformation", "self-suggestion"],
    "autotelic": [],
    "autotelism": ["belief"],
    "autotomic": [],
    "autotomize": ["autotomise", "cast", "cast off", "drop", "shake off", "shed", "throw", "throw away", "throw off"],
    "autotomy": ["remotion", "removal"],
    "autotrophic": ["autophytic"],
    "autotype": ["autotypy", "photography"],
    "autotypic": [],
    "autumn crocus": ["bulbous plant", "colchicum autumnale", "meadow saffron", "naked lady"],
    "autumn sneezeweed": ["helenium autumnale", "sneezeweed"],
    "autumn-flowering": ["autumn-blooming", "fall-blooming", "fall-flowering", "late-blooming", "late-flowering"],
    "autumnal": [],
    "autumnal equinox": ["equinox", "fall equinox", "september equinox"],
    "auvergne": [],
    "auxesis": ["development", "growing", "growth", "maturation", "ontogenesis", "ontogeny"],
    "auxetic": [],
    "auxiliary": ["subsidiary", "supplemental", "supplementary"],
    "auxiliary airfield": ["airfield", "field", "flying field", "landing field"],
    "auxiliary boiler": ["boiler", "donkey boiler", "steam boiler"],
    "auxiliary cell": ["radical cell", "terrorist cell"],
    "auxiliary engine": ["donkey engine", "engine"],
    "auxiliary operation": ["off-line operation", "operation"],
    "auxiliary pump": ["donkey pump", "pump"],
    "auxiliary research submarine": ["pigboat", "sub", "submarine", "u-boat"],
    "auxiliary storage": ["external storage", "memory device", "secondary storage", "storage device"],
    "auxiliary verb": ["modal", "modal auxiliary", "modal auxiliary verb", "modal verb", "verb"],
    "auxin": ["growth regulator", "iaa", "indoleacetic acid", "indolebutyric acid", "phytohormone", "plant hormone"],
    "auxinic": [],
    "avadavat": ["amadavat", "weaver", "weaver finch", "weaverbird"],
    "avahi": ["genus avahi", "mammal genus"],
    "avail": ["aid", "assist", "help"],
    "available": ["uncommitted"],
    "avalanche": ["come down", "descend", "fall", "go down", "roll down"],
    "avalanche lily": ["erythronium montanum", "liliaceous plant"],
    "avalokitesvara": ["avalokiteshvara"],
    "avant-garde": ["art movement", "artistic movement", "new wave", "van", "vanguard"],
    "avaram": ["cassia auriculata", "senna", "senna auriculata", "tanner's cassia"],
    "avarice": ["avariciousness", "covetousness", "cupidity", "greed"],
    "avaricious": ["covetous", "grabby", "grasping", "greedy", "prehensile"],
    "avariciously": ["covetously", "greedily"],
    "avascular": [],
    "avatar": ["hindu deity"],
    "ave maria": ["hail mary"],
    "avellan": ["avellane"],
    "avena": ["genus avena", "plant genus"],
    "avenged": [],
    "avenger": ["aggressor", "assailant", "assaulter", "attacker", "retaliator"],
    "avens": ["bennet", "chocolate root", "clover-root", "cloveroot", "geum alleppicum strictum", "geum canadense", "geum macrophyllum", "geum rivale", "geum strictum", "geum triflorum", "geum urbanum", "geum virginianum", "herb bennet", "indian chocolate", "prairie smoke", "purple avens", "subshrub", "suffrutex", "water avens", "white avens", "wood avens", "yellow avens"],
    "avenue": ["boulevard", "street"],
    "average": ["add up", "amount", "average out", "come", "number", "total"],
    "average cost": ["cost", "monetary value", "price"],
    "averageness": ["normalcy", "normality"],
    "averrhoa": ["genus averrhoa", "rosid dicot genus"],
    "averroes": ["abul-walid mohammed ibn-ahmad ibn-mohammed ibn-roshd", "ibn-roshd"],
    "aversion": ["averting", "avoidance", "dodging", "shunning", "turning away"],
    "aversion therapy": ["behavior modification", "behavior therapy"],
    "aversive": [],
    "aversive conditioning": ["conditioning"],
    "aversive stimulus": ["negative stimulus"],
    "avert": ["turn", "turn away"],
    "averting": ["bar", "prevention"],
    "aves": ["class", "class aves"],
    "avesta": ["zend-avesta"],
    "avestan": ["iranian", "iranian language", "zend"],
    "avian": [],
    "avianize": ["alter", "avianise", "change", "vary"],
    "aviary": ["bird sanctuary", "building", "edifice", "volary"],
    "aviation": ["accumulation", "aggregation", "air power", "assemblage", "collection"],
    "aviator": ["aeronaut", "airman", "airplane pilot", "airwoman", "aviatress", "aviatrix", "flier", "flyer", "pilot", "skilled worker", "skilled workman", "trained worker"],
    "aviatrix": ["aeronaut", "airman", "airwoman", "aviator", "aviatress", "flier", "flyer"],
    "avicenna": ["abu ali al-husain ibn abdallah ibn sina", "ibn-sina"],
    "avicennia": ["asterid dicot genus", "genus avicennia"],
    "avicenniaceae": ["asterid dicot family", "family avicenniaceae"],
    "avid": ["devouring", "esurient", "greedy"],
    "avidly": [],
    "avifauna": ["fauna", "zoology"],
    "avifaunal": ["avifaunistic"],
    "avignon": [],
    "avionic": [],
    "avionics": ["aeronautics", "astronautics"],
    "avirulent": [],
    "avitaminosis": ["alpine scurvy", "beriberi", "hypovitaminosis", "maidism", "mal de la rosa", "mal rosso", "malnutrition", "mayidism", "moon blindness", "night blindness", "nyctalopia", "pellagra", "rachitis", "rickets", "saint ignatius' itch", "scorbutus", "scurvy"],
    "avitaminotic": [],
    "avo": ["macao monetary unit"],
    "avocado": ["avocado tree", "fruit tree", "persea americana"],
    "avocation": ["by-line", "hobby", "interest", "pastime", "pursuit", "sideline", "spare-time activity", "spelaeology", "speleology"],
    "avocational": [],
    "avocet": ["limicoline bird", "shore bird", "shorebird"],
    "avogadro": ["amedeo avogadro"],
    "avogadro's law": ["avogadro's hypothesis", "law", "law of nature"],
    "avogadro's number": ["avogadro number", "constant"],
    "avoid": ["fiddle", "goldbrick", "shirk", "shrink from"],
    "avoidance": ["aversion", "averting", "dodging", "escape", "near thing", "rejection", "shunning", "turning away"],
    "avoirdupois": ["avoirdupois weight", "system of weights", "weight"],
    "avoirdupois unit": ["cental", "centner", "cwt", "dram", "grain", "gross ton", "half pound", "hundredweight", "kiloton", "lb", "long hundredweight", "long ton", "mass unit", "megaton", "net ton", "ounce", "oz.", "pound", "quarter", "quarter pound", "quintal", "short hundredweight", "short ton", "stone", "ton"],
    "avon": ["river avon"],
    "avow": ["acknowledge", "admit", "avouch"],
    "avowal": ["affirmation", "affirmative", "assertion", "asseveration", "averment", "avouchment", "professing", "profession", "reaffirmation", "reassertion"],
    "avowed": ["professed"],
    "avowedly": ["professedly"],
    "avower": ["communicator"],
    "avulse": ["separate"],
    "avulsion": ["alteration", "change", "modification"],
    "avuncular": [],
    "awake": [],
    "awaken": ["affect", "impress", "move", "strike"],
    "awakened": [],
    "awakening": ["arousal", "reveille", "rousing", "wakening", "waking up"],
    "award": ["give", "grant", "pension", "pension off"],
    "award-winning": [],
    "aware": ["cognisant", "cognizant"],
    "awareness": ["consciousness", "sentience"],
    "away": [],
    "away game": ["game", "road game"],
    "awayness": ["absence"],
    "awe": ["affright", "cow", "fright", "frighten", "overawe", "scare"],
    "aweary": ["weary"],
    "awed": ["awestricken", "awestruck"],
    "aweigh": [],
    "aweless": ["awless"],
    "awful": ["dire", "direful", "dread", "dreaded", "dreadful", "fearful", "fearsome", "frightening", "horrendous", "horrific", "terrible"],
    "awfulness": ["dreadfulness", "frightfulness", "horridness", "terribleness", "unpleasantness"],
    "awheel": [],
    "awhile": ["for a while"],
    "awkward": ["bunglesome", "clumsy", "ungainly"],
    "awkwardly": [],
    "awkwardness": ["clumsiness", "ineptitude", "ineptness", "maladroitness", "rustiness", "slowness", "unskillfulness"],
    "awl": ["bradawl", "hand tool", "pricker", "scratch awl", "scribe", "scriber"],
    "awl-shaped": [],
    "awlwort": ["aquatic plant", "hydrophyte", "hydrophytic plant", "subularia aquatica", "water plant"],
    "awn": ["beard"],
    "awned": ["awny"],
    "awning": ["canopy", "sunblind", "sunshade"],
    "awninged": [],
    "awnless": [],
    "awnless bromegrass": ["brome", "bromegrass", "bromus inermis"],
    "awol": ["absentee"],
    "awry": ["amiss"],
    "ax": ["axe", "end", "terminate"],
    "ax handle": ["axe handle", "grip", "handgrip", "handle", "hold"],
    "ax head": ["axe head", "wedge"],
    "axe": ["ax", "chop", "hack"],
    "axenic": [],
    "axial": [],
    "axial muscle": ["skeletal muscle", "striated muscle"],
    "axial rotation": ["axial motion", "gyration", "revolution", "roll", "rotation", "wallow"],
    "axial skeleton": ["skeletal structure"],
    "axially": [],
    "axil": ["angle"],
    "axile": ["axial"],
    "axile placentation": ["placentation"],
    "axillary": ["alar"],
    "axillary artery": ["arteria", "arteria axillaris", "arterial blood vessel", "artery"],
    "axillary node": ["lymph gland", "lymph node", "node"],
    "axillary vein": ["vein", "vena", "vena axillaris", "venous blood vessel"],
    "axiological": [],
    "axiology": ["philosophy"],
    "axiom": ["euclid's axiom", "euclid's postulate", "euclidean axiom", "proposition"],
    "axiomatic": ["aphoristic"],
    "axiomatically": [],
    "axis": ["rachis", "spadix", "stalk", "stem"],
    "axle": ["dead axle", "driving axle", "journal", "live axle", "shaft"],
    "axle bar": ["axletree"],
    "axle grease": ["grease", "lubricating oil"],
    "axletree": ["axle bar", "dead axle"],
    "axolemma": ["membrane", "tissue layer"],
    "axolotl": ["ambystoma mexicanum", "ambystomid", "ambystomid salamander", "mud puppy"],
    "axon": ["axone", "nerve fiber", "nerve fibre"],
    "axonal": [],
    "axseed": ["coronilla", "coronilla varia", "crown vetch"],
    "ayah": ["domestic", "domestic help", "house servant"],
    "ayapana": ["ayapana triplinervis", "eupatorium aya-pana", "herb", "herbaceous plant"],
    "ayatollah": ["religious leader"],
    "aye-aye": ["daubentonia madagascariensis", "lemur"],
    "ayin": ["alphabetic character", "letter", "letter of the alphabet"],
    "ayr": [],
    "ayrshire": ["dairy cattle", "dairy cow", "milch cow", "milcher", "milk cow", "milker"],
    "aythya": ["bird genus", "genus aythya"],
    "ayurveda": [],
    "az zarqa": ["zarqa"],
    "azadirachta": ["genus azadirachta", "rosid dicot genus"],
    "azadirachtin": ["organic compound"],
    "azalea": ["rhododendron"],
    "azathioprine": ["imuran", "medicament", "medication", "medicinal drug", "medicine"],
    "azerbaijan": ["azerbaijani republic", "azerbajdzhan", "azerbajdzhan republic"],
    "azerbaijani": ["turki"],
    "azerbaijani monetary unit": ["manat", "monetary unit", "qepiq"],
    "azeri": ["ethnic group", "ethnos"],
    "azide": ["chemical compound", "compound", "hydrazoite"],
    "azido": [],
    "azido group": ["azido radical", "chemical group", "group", "radical"],
    "azimuth": ["angle", "az"],
    "azimuthal": [],
    "azithromycin": ["antibacterial", "antibacterial drug", "bactericide", "zithromax"],
    "azo": [],
    "azo dye": ["congo red", "dye", "dyestuff", "methyl orange"],
    "azo group": ["azo radical", "chemical group", "group", "radical"],
    "azoic": [],
    "azolla": ["fern genus", "genus azolla"],
    "azollaceae": ["family azollaceae", "fern family"],
    "azonal": [],
    "azonic": [],
    "azores": ["acores"],
    "azote": ["atomic number 7", "n", "nitrogen"],
    "azotemic": ["uraemic", "uremic"],
    "azotic": ["nitric", "nitrous"],
    "azoturia": ["pathology"],
    "aztec": ["nahuatl"],
    "aztecan": ["uto-aztecan", "uto-aztecan language"],
    "aztreonam": ["antibiotic", "antibiotic drug", "azactam"],
    "azure": ["color", "color in", "colorise", "colorize", "colour", "colour in", "colourise", "colourize"],
    "azure aster": ["aster"],
    "azurite": ["malachite"],
    "azygos vein": ["azygous vein", "vein", "vena", "vena azygos", "venous blood vessel"],
    "azygous": ["azygos"],
    "azymia": ["pathology"],
    "b": ["alphabetic character", "letter", "letter of the alphabet"],
    "b battery": ["battery", "electric battery"],
    "b cell": ["b lymphocyte", "lymph cell", "lymphocyte"],
    "b-52": [],
    "b-complex vitamin": ["adermin", "aneurin", "antiberiberi factor", "antipernicious anemia factor", "b", "b complex", "b vitamin", "biotin", "choline", "cobalamin", "cyanocobalamin", "folacin", "folate", "folic acid", "hepatoflavin", "inositol", "lactoflavin", "niacin", "nicotinic acid", "ovoflavin", "pantothen", "pantothenic acid", "pteroylglutamic acid", "pteroylmonoglutamic acid", "pyridoxal", "pyridoxamine", "pyridoxine", "riboflavin", "thiamin", "thiamine", "vitamin b", "vitamin b complex", "vitamin b1", "vitamin b12", "vitamin b2", "vitamin b6", "vitamin bc", "vitamin g", "vitamin h", "vitamin m", "water-soluble vitamin"],
    "b-flat clarinet": ["clarinet", "licorice stick"],
    "b-girl": ["adult female", "bar girl", "woman"],
    "b-horizon": ["b horizon"],
    "b-meson": ["meson", "mesotron"],
    "b-scan ultrasonography": ["echography", "sonography", "ultrasonography", "ultrasound"],
    "baa": ["cry"],
    "baa-lamb": ["lamb"],
    "baader meinhof gang": ["baader-meinhof gang"],
    "baal": [],
    "baas": ["boss", "chief", "foreman", "gaffer", "honcho"],
    "baba": ["baba au rhum", "cake", "rum baba"],
    "baba au rhum": ["baba", "rum baba"],
    "babar": [],
    "babassu": ["babassu palm", "coco de macao", "feather palm", "orbignya martiana", "orbignya phalerata", "orbignya spesiosa"],
    "babassu nut": ["seed"],
    "babassu oil": ["babacu oil", "oil"],
    "babbitt": ["line"],
    "babbitt metal": ["alloy", "babbitt", "metal"],
    "babbitting": ["facing", "lining"],
    "babble": ["mouth", "speak", "talk", "utter", "verbalise", "verbalize"],
    "babbler": ["cackler", "oscine", "oscine bird"],
    "babel": ["confusion"],
    "babelike": [],
    "babesiidae": ["family babesiidae", "protoctist family"],
    "babinski": ["babinski reflex", "babinski sign", "inborn reflex", "innate reflex", "instinctive reflex", "physiological reaction", "reflex", "reflex action", "reflex response", "unconditioned reflex"],
    "babirusa": ["babiroussa", "babirussa", "babyrousa babyrussa", "swine"],
    "babka": ["coffee cake", "coffeecake"],
    "baboon": ["catarrhine", "chacma", "chacma baboon", "drill", "mandrill", "mandrillus leucophaeus", "mandrillus sphinx", "old world monkey", "papio ursinus"],
    "baboonish": [],
    "babu": ["adult male", "baboo", "man"],
    "babushka": ["headscarf"],
    "baby": ["fetus", "foetus"],
    "baby bed": ["article of furniture", "baby's bed", "bassinet", "carrycot", "cot", "cradle", "crib", "furniture", "piece of furniture"],
    "baby blue-eyes": ["herb", "herbaceous plant", "nemophila menziesii"],
    "baby boom": ["baby-boom generation", "generation"],
    "baby boomer": ["boomer", "individual", "mortal", "person", "somebody", "someone", "soul"],
    "baby buggy": ["baby carriage", "bassinet", "carriage", "go-cart", "perambulator", "pram", "pushchair", "pusher", "stroller", "wheeled vehicle"],
    "baby buster": ["buster", "individual", "mortal", "person", "somebody", "someone", "soul"],
    "baby doctor": ["medical specialist", "paediatrician", "pediatrician", "pediatrist", "specialist"],
    "baby farmer": ["keeper"],
    "baby grand": ["baby grand piano", "grand", "grand piano", "parlor grand", "parlor grand piano", "parlour grand", "parlour grand piano"],
    "baby oil": ["balm", "ointment", "salve", "unction", "unguent"],
    "baby powder": ["powder"],
    "baby shoe": ["shoe"],
    "baby talk": ["babytalk", "motherese", "non-standard speech"],
    "baby's breath": ["babies'-breath", "flower", "gypsophila paniculata"],
    "baby's tears": ["baby tears", "ground cover", "groundcover", "helxine soleirolia", "soleirolia soleirolii"],
    "baby-faced": [],
    "baby-sit": ["guard"],
    "baby-wise": ["baby-like"],
    "babyish": [],
    "babylon": [],
    "babylonia": ["chaldaea", "chaldea"],
    "babylonian": ["semite", "sumerian"],
    "babylonian captivity": [],
    "babyminder": ["baby minder", "keeper", "minder"],
    "babyrousa": ["genus babyrousa", "mammal genus"],
    "babysitter": ["baby-sitter", "keeper", "sitter"],
    "babysitting": ["aid", "attention", "baby sitting", "care", "tending"],
    "baccalaureate": ["discourse", "preaching", "sermon"],
    "baccarat": ["card game", "cards", "chemin de fer"],
    "baccate": ["berrylike"],
    "bacchanalian": ["bacchanal", "bacchic", "carousing", "orgiastic"],
    "bacchant": ["bacchanal", "buff", "devotee", "fan", "lover"],
    "bacchante": ["votary"],
    "bacchantic": [],
    "baccharis": ["asterid dicot genus", "genus baccharis"],
    "bacchus": [],
    "baccivorous": [],
    "bach": ["johann sebastian bach"],
    "bachelor": ["bach", "live"],
    "bachelor girl": ["adult female", "bachelorette", "woman"],
    "bachelor of arts": ["ab", "artium baccalaurens", "ba", "baccalaureate", "bachelor's degree"],
    "bachelor of arts in library science": ["abls", "baccalaureate", "bachelor's degree"],
    "bachelor of arts in nursing": ["baccalaureate", "bachelor's degree", "ban"],
    "bachelor of divinity": ["baccalaureate", "bachelor's degree", "bd"],
    "bachelor of laws": ["law degree", "llb"],
    "bachelor of literature": ["baccalaureate", "bachelor's degree", "blitt"],
    "bachelor of medicine": ["baccalaureate", "bachelor's degree", "mb"],
    "bachelor of music": ["baccalaureate", "bachelor's degree", "bmus"],
    "bachelor of naval science": ["baccalaureate", "bachelor's degree", "bns"],
    "bachelor of science": ["baccalaureate", "bachelor's degree", "bs", "sb"],
    "bachelor of science in architecture": ["baccalaureate", "bachelor's degree", "bsarch"],
    "bachelor of science in engineering": ["baccalaureate", "bachelor's degree"],
    "bachelor of theology": ["baccalaureate", "bachelor's degree", "thb"],
    "bachelor party": ["smoker", "stag party"],
    "bachelor's degree": ["ab", "abls", "academic degree", "artium baccalaurens", "ba", "baccalaureate", "bachelor of arts", "bachelor of arts in library science", "bachelor of arts in nursing", "bachelor of divinity", "bachelor of literature", "bachelor of medicine", "bachelor of music", "bachelor of naval science", "bachelor of science", "bachelor of science in architecture", "bachelor of science in engineering", "bachelor of theology", "ban", "bd", "blitt", "bmus", "bns", "bs", "bsarch", "degree", "mb", "sb", "thb"],
    "bachelorhood": ["time of life"],
    "bacillaceae": ["bacteria family", "family bacillaceae"],
    "bacillar": ["bacillary"],
    "bacillariophyceae": ["class", "class bacillariophyceae", "class diatomophyceae", "diatomophyceae"],
    "bacillus": ["anthrax bacillus", "b", "bacillus anthracis", "bacillus globigii", "bacillus subtilis", "eubacteria", "eubacterium", "grass bacillus", "hay bacillus", "true bacteria", "yersinia pestis"],
    "bacillus anthracis": ["anthrax bacillus", "b", "bacillus", "bioarm", "biological weapon", "bioweapon"],
    "bacillus subtilis": ["b", "bacillus", "bacillus globigii", "grass bacillus", "hay bacillus"],
    "bacitracin": ["antibiotic", "antibiotic drug"],
    "back": ["lie"],
    "back and forth": ["backward and forward", "to and fro"],
    "back brace": ["brace"],
    "back burner": ["precedence", "precedency", "priority"],
    "back channel": ["channel", "communication channel", "line"],
    "back circle": ["acrobatic feat", "acrobatic stunt"],
    "back door": ["access", "access code", "backdoor"],
    "back exercise": ["exercise", "exercising", "physical exercise", "physical exertion", "workout"],
    "back judge": ["football official"],
    "back matter": ["end matter", "matter"],
    "back of beyond": ["depth"],
    "back out": ["back"],
    "back porch": ["porch"],
    "back room": ["room"],
    "back tooth": ["posterior", "tooth"],
    "back up": ["back down", "back off", "draw back", "move back", "pull away", "pull back", "recede", "retire", "retreat", "withdraw"],
    "back-channel": [],
    "back-formation": ["word"],
    "back-geared": ["double-geared"],
    "back-to-back": ["consecutive"],
    "backache": ["ache", "aching", "lumbago", "lumbar pain"],
    "backband": ["band"],
    "backbeat": ["beat", "musical rhythm", "rhythm"],
    "backbench": ["seat"],
    "backbencher": ["legislator"],
    "backbend": ["acrobatic feat", "acrobatic stunt"],
    "backbite": ["bitch", "complain", "kick", "kvetch", "plain", "quetch", "sound off"],
    "backblast": ["back-blast", "backfire", "blowback"],
    "backboard": ["basketball backboard", "game equipment"],
    "backbone": ["fortitude", "grit", "gumption", "guts", "moxie", "sand"],
    "backcross": ["cross", "crossbreed", "hybridise", "hybridize", "interbreed"],
    "backdate": ["effect"],
    "backdrop": ["backcloth", "background", "scene", "scenery"],
    "backed": [],
    "backfield": ["formation"],
    "backfire": ["backlash", "come about", "fall out", "go on", "hap", "happen", "occur", "pass", "pass off", "recoil", "take place"],
    "backflow": ["backflowing", "flow", "flowing", "regurgitation"],
    "backgammon": ["board game"],
    "backgammon board": ["board", "gameboard"],
    "background": ["accent", "accentuate", "downplay", "emphasise", "emphasize", "play down", "punctuate", "soft-pedal", "stress", "wave off"],
    "background noise": ["background", "background signal", "ground noise", "surface noise"],
    "background processing": ["backgrounding", "priority processing"],
    "background radiation": ["background", "background signal"],
    "backgrounder": ["news conference", "press conference"],
    "backhand": ["hit"],
    "backhand drive": ["drive"],
    "backhanded": [],
    "backhander": ["blow"],
    "backhoe": ["digger", "excavator", "power shovel", "shovel"],
    "backing": ["bed", "layer", "mount", "reinforcement", "strengthener"],
    "backlash": ["reaction", "white backlash", "whitelash"],
    "backless": [],
    "backlighting": ["lighting"],
    "backlog": ["accumulate", "amass", "conglomerate", "cumulate", "gather", "pile up"],
    "backmost": ["hindermost", "hindmost", "rearmost"],
    "backpack": ["hike", "pack"],
    "backpacker": ["hiker", "packer", "tramp", "tramper"],
    "backpacking tent": ["collapsible shelter", "pack tent", "tent"],
    "backpedal": ["bicycle", "bike", "cycle", "pedal", "wheel"],
    "backplate": ["armor plate", "armor plating", "armour plate", "plate armor", "plate armour"],
    "backroom": ["facility", "installation"],
    "backroom boy": ["adviser", "advisor", "brain truster", "consultant"],
    "backsaw": ["back saw", "carpenter's saw", "hand saw", "handsaw"],
    "backscatter": ["break up", "disperse", "scatter"],
    "backscratcher": ["opportunist", "self-seeker"],
    "backseat": ["inferiority", "lower rank", "lower status"],
    "backseat driver": ["meddler"],
    "backslap": ["act", "behave", "do"],
    "backslapper": ["enthusiast", "partisan", "partizan"],
    "backsliding": ["failure", "lapse", "lapsing", "recidivism", "relapse", "relapsing", "reversion", "reverting"],
    "backspace": ["type", "typewrite"],
    "backspace character": ["ascii control character", "control character"],
    "backspace key": ["backspace", "backspacer", "key"],
    "backspin": ["spin"],
    "backstage": [],
    "backstair": ["backstairs", "furtive"],
    "backstairs": ["staircase", "stairway"],
    "backstay": ["stay"],
    "backstitch": ["run up", "sew", "sew together", "stitch"],
    "backstop": ["play"],
    "backstroke": ["swim"],
    "backstroker": ["swimmer"],
    "backswept": ["sweptback"],
    "backswimmer": ["bug", "hemipteran", "hemipteron", "hemipterous insect", "notonecta undulata"],
    "backsword": ["blade", "brand", "steel", "sword"],
    "backtrack": ["double back", "return", "turn back"],
    "backup": ["accretion", "accumulation"],
    "backup file": ["computer file"],
    "backup system": ["adp system", "adps", "automatic data processing system", "computer system", "computing system"],
    "backward": ["backwards"],
    "backwater": ["body of water", "water"],
    "backwoods": ["back country", "boondocks", "country", "hinterland", "rural area"],
    "backyard": ["curtilage", "grounds", "yard"],
    "bacon": ["roger bacon"],
    "bacon and eggs": ["dish"],
    "bacon rind": ["rind"],
    "bacon strip": ["bacon"],
    "bacon-lettuce-tomato sandwich": ["blt", "sandwich"],
    "bacteremia": ["bacteriaemia", "bacteriemia", "pathology"],
    "bacteremic": [],
    "bacteria": ["acidophil", "acidophile", "bacterium", "bacteroid", "calymmatobacterium", "diplococcus", "eubacteria", "eubacterium", "francisella", "genus calymmatobacterium", "genus francisella", "gonococcus", "legionella", "legionella pneumophilia", "micro-organism", "microorganism", "neisseria gonorrhoeae", "nitrobacterium", "penicillin-resistant bacteria", "probiotic", "probiotic bacterium", "probiotic flora", "probiotic microflora", "pus-forming bacteria", "rod", "superbug", "true bacteria"],
    "bacteria bed": ["filter"],
    "bacteria family": ["actinomycetaceae", "athiorhodaceae", "bacillaceae", "bacteroidaceae", "chlamydiaceae", "corynebacteriaceae", "enterobacteriaceae", "family", "family actinomycetaceae", "family athiorhodaceae", "family bacillaceae", "family bacteroidaceae", "family chlamydiaceae", "family corynebacteriaceae", "family enterobacteriaceae", "family lactobacillaceae", "family lactobacteriaceae", "family micrococcaceae", "family mycobacteriaceae", "family mycoplasmataceae", "family myxobacteriaceae", "family myxophyceae", "family nostocaceae", "family oscillatoriaceae", "family polyangiaceae", "family pseudomonodaceae", "family rhizobiaceae", "family rickettsiaceae", "family schizophyceae", "family spirillaceae", "family spirochaetaceae", "family streptomycetaceae", "family thiobacteriaceae", "family treponemataceae", "lactobacillaceae", "lactobacteriaceae", "micrococcaceae", "mycobacteriaceae", "mycoplasmataceae", "myxobacteriaceae", "myxophyceae", "nostocaceae", "oscillatoriaceae", "polyangiaceae", "pseudomonodaceae", "rhizobiaceae", "rickettsiaceae", "schizophyceae", "spirillaceae", "spirochaetaceae", "streptomycetaceae", "thiobacteriaceae", "treponemataceae"],
    "bacteria genus": ["aerobacter", "agrobacterium", "bacteroides", "family nitrobacteriaceae", "genus", "genus actinomyces", "genus aerobacter", "genus agrobacterium", "genus bacillus", "genus bacteroides", "genus borrelia", "genus chlamydia", "genus clostridium", "genus corynebacterium", "genus diplococcus", "genus erwinia", "genus escherichia", "genus heliobacter", "genus klebsiella", "genus lactobacillus", "genus leptospira", "genus listeria", "genus micrococcus", "genus mycobacterium", "genus mycoplasma", "genus nitrobacter", "genus nitrosomonas", "genus nostoc", "genus polyangium", "genus pseudomonas", "genus rhizobium", "genus rickettsia", "genus salmonella", "genus serratia", "genus shigella", "genus spirillum", "genus spirochaeta", "genus staphylococcus", "genus streptococcus", "genus streptomyces", "genus thiobacillus", "genus treponema", "genus trichodesmium", "genus vibrio", "genus xanthomonas", "heliobacter", "micrococcus", "nitrobacter", "nitrobacteriaceae", "nitrosomonas", "polyangium", "pseudomonas", "rhizobium", "serratia", "spirochaeta", "xanthomonas"],
    "bacteria order": ["order", "ordering", "ordination"],
    "bacteria species": ["aerobacter aerogenes", "agrobacterium tumefaciens", "calymmatobacterium granulomatis", "francisella tularensis", "h. pylori", "heliobacter pylori", "pseudomonas pyocanea", "serratia marcescens", "species", "streptococcus anhemolyticus"],
    "bacterial": [],
    "bacterial toxin": ["anatoxin", "botulin", "botulinus toxin", "botulismotoxin", "clostridium perfringens epsilon toxin", "epsilon toxin", "toxin", "toxoid"],
    "bacterially": [],
    "bactericidal": ["disinfectant", "germicidal"],
    "bactericide": ["bacteriacide", "chemical", "chemical substance"],
    "bacteriochlorophyll": ["pigment"],
    "bacteriological": ["bacteriologic"],
    "bacteriologist": ["biologist", "life scientist"],
    "bacteriology": ["medical specialty", "medicine"],
    "bacteriolysis": ["lysis"],
    "bacteriolytic": [],
    "bacteriophage": ["coliphage", "phage", "typhoid bacteriophage", "virus"],
    "bacteriophagic": ["bacteriophagous"],
    "bacteriostasis": ["biological process", "organic process"],
    "bacteriostat": ["agent"],
    "bacteriostatic": [],
    "bacterize": ["bacterise", "subject"],
    "bacteroid": ["bacteria", "bacterium"],
    "bacteroidaceae": ["bacteria family", "family bacteroidaceae"],
    "bacteroidal": ["bacterioid", "bacterioidal", "bacteroid"],
    "bacteroides": ["bacteria genus", "genus bacteroides"],
    "bactrian camel": ["camel", "camelus bactrianus"],
    "bad": ["badness", "evil", "inadvisability", "liability", "quality", "undesirability", "unsoundness", "unworthiness", "worse"],
    "bad block": ["block"],
    "bad check": ["bad cheque", "bank check", "check", "cheque"],
    "bad debt": ["debt"],
    "bad egg": ["bad person"],
    "bad fairy": ["evil spirit"],
    "bad guy": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "bad lands": ["badlands"],
    "bad luck": ["chance", "fortune", "hazard", "luck", "mischance", "mishap"],
    "bad manners": ["ill-breeding", "impoliteness"],
    "bad person": ["bad egg", "debauchee", "decadent", "defiler", "destroyer", "individual", "libertine", "mortal", "offender", "panderer", "person", "polluter", "rounder", "ruiner", "scalawag", "scallywag", "seducer", "shocker", "snake", "snake in the grass", "somebody", "someone", "soul", "trampler", "undoer", "uprooter", "varmint", "vermin", "victimiser", "victimizer", "waster", "wrongdoer"],
    "bad temper": ["anger", "choler", "conniption", "fit", "ill temper", "irascibility", "ire", "quick temper", "scene", "short temper", "spleen", "tantrum"],
    "bad weather": ["atmospheric condition", "cloud cover", "cloudiness", "conditions", "inclemency", "inclementness", "overcast", "raw weather", "storminess", "turbulence", "weather", "weather condition"],
    "badaga": ["dravidian"],
    "baddeleyite": ["mineral"],
    "bade": ["west chadic"],
    "badge": ["label", "mark", "tag"],
    "badger": ["persuade"],
    "badgering": ["bedevilment", "harassment", "molestation", "torment", "worrying"],
    "badinage": ["backchat", "banter", "give-and-take", "raillery"],
    "badlands": ["ground", "land", "soil"],
    "badlands national park": [],
    "badly": [],
    "badminton": ["battledore", "battledore and shuttlecock", "court game", "doubles", "singles"],
    "badminton court": ["court"],
    "badminton equipment": ["bird", "birdie", "shuttle", "shuttlecock", "sports equipment"],
    "badminton racket": ["badminton racquet", "battledore", "racket", "racquet"],
    "badmouth": ["asperse", "besmirch", "calumniate", "defame", "denigrate", "drag through the mud", "malign", "slander", "smear", "smirch", "sully", "traduce"],
    "badness": ["distressfulness", "foulness", "intensity", "intensiveness", "raininess", "seriousness", "severeness", "severity"],
    "baedeker": ["karl baedeker"],
    "baffin bay": [],
    "baffin island": [],
    "baffle": ["bound", "confine", "limit", "regulate", "restrain", "restrict", "throttle", "trammel"],
    "baffled": ["people"],
    "baffling": ["elusive", "knotty", "problematic", "problematical", "tough"],
    "bag": ["droop", "flag", "sag", "swag"],
    "bag lady": ["homeless", "homeless person"],
    "bag of tricks": ["know-how"],
    "bag-shaped": [],
    "bagasse": ["pulp"],
    "bagassosis": ["alveolitis", "bagascosis"],
    "bagatelle": ["composition", "musical composition", "opus", "piece", "piece of music"],
    "bagel": ["beigel", "bun", "onion bagel", "roll"],
    "baggage": ["adult female", "woman"],
    "baggage car": ["car", "luggage van", "railcar", "railroad car", "railway car"],
    "baggage claim": ["area"],
    "baggageman": ["attendant", "attender", "tender"],
    "bagger": ["machine"],
    "baggy": ["loose-fitting", "sloppy"],
    "baghdad": ["bagdad", "capital of iraq"],
    "bagman": ["racketeer"],
    "bagpipe": ["musette", "pipe", "shepherd's pipe"],
    "baguet": ["baguette", "french bread"],
    "bahai": ["adherent", "disciple", "instructor", "teacher"],
    "bahaism": ["faith", "religion", "religious belief"],
    "bahamas": ["bahama islands", "commonwealth of the bahamas"],
    "bahamian": ["west indian"],
    "bahamian dollar": ["dollar"],
    "bahia blanca": [],
    "bahia grass": ["grass", "paspalum notatum"],
    "bahrain": ["bahrain island", "bahrein", "bahrein island"],
    "bahrain dinar": ["bahrainian monetary unit", "dinar"],
    "bahraini": ["arab", "arabian", "bahreini"],
    "bahrainian monetary unit": ["bahrain dinar", "dinar", "monetary unit"],
    "baht": ["thai monetary unit", "tical"],
    "bai": ["baic", "tibeto-burman", "tibeto-burman language"],
    "baikal": ["baykal", "lake baikal", "lake baykal"],
    "bail": ["free", "liberate", "loose", "release", "unloose", "unloosen"],
    "bail out": ["free", "liberate", "loose", "release", "unloose", "unloosen"],
    "bailable": [],
    "bailee": ["agent"],
    "bailey": ["pearl bailey", "pearl mae bailey"],
    "bailey bridge": ["bridge", "span"],
    "bailiff": ["functionary", "official"],
    "bailiffship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "bailiwick": ["jurisdiction"],
    "bailment": ["delivery", "legal transfer", "livery"],
    "bailor": ["deliverer"],
    "bain-marie": ["pan"],
    "baiomys": ["genus baiomys", "mammal genus"],
    "bairava": [],
    "bairdiella": ["fish genus", "genus bairdiella"],
    "bairn": ["child", "fry", "kid", "minor", "nestling", "nipper", "shaver", "small fry", "tiddler", "tike", "tyke", "youngster"],
    "baisakh": ["hindu calendar month", "vaisakha"],
    "bait": ["entice", "lure", "tempt"],
    "bait and switch": ["marketing", "merchandising", "selling"],
    "bait casting": ["cast", "casting"],
    "baiting": ["harassment", "molestation"],
    "baiza": ["baisa", "omani monetary unit"],
    "baize": ["cloth", "fabric", "material", "textile"],
    "bake": ["be", "broil"],
    "baked": [],
    "baked alaska": ["afters", "dessert", "sweet"],
    "baked goods": ["bread", "breadstuff", "cake", "food", "pastry", "solid food", "staff of life"],
    "baked potato": ["irish potato", "jacket potato", "murphy", "potato", "spud", "tater", "white potato"],
    "bakelite": ["plastic"],
    "baker": ["merchandiser", "merchant"],
    "baker's eczema": ["allergic eczema"],
    "baker's yeast": ["brewer's yeast", "saccharomyces cerevisiae", "yeast"],
    "bakersfield": [],
    "bakery": ["bakehouse", "bakeshop", "patisserie", "shop", "store", "work", "workplace"],
    "baking": ["creating from raw materials"],
    "baking powder": ["leaven", "leavening"],
    "baking-powder biscuit": ["biscuit", "shortcake"],
    "bakke decision": [],
    "baklava": ["pastry"],
    "baku": ["capital of azerbaijan"],
    "bakunin": ["mikhail aleksandrovich bakunin", "mikhail bakunin"],
    "balaclava": ["balaclava helmet", "cap"],
    "balaena": ["genus balaena", "mammal genus"],
    "balaeniceps": ["bird genus", "genus balaeniceps"],
    "balaenicipitidae": ["bird family", "family balaenicipitidae"],
    "balaenidae": ["family balaenidae", "mammal family"],
    "balaenoptera": ["genus balaenoptera", "mammal genus"],
    "balaenopteridae": ["family balaenopteridae", "mammal family"],
    "balagan": ["bedlam", "chaos", "pandemonium", "topsy-turvydom", "topsy-turvyness"],
    "balalaika": ["chordophone"],
    "balance": ["be"],
    "balance beam": ["beam", "exerciser", "gymnastic apparatus"],
    "balance of payments": ["accounting", "balance of international payments"],
    "balance of power": ["equilibrium"],
    "balance of trade": ["balance", "trade balance", "trade gap", "visible balance"],
    "balance sheet": ["record"],
    "balance wheel": ["balance", "wheel"],
    "balance-of-payments problem": ["job", "problem"],
    "balanced": [],
    "balanced budget": ["budget"],
    "balanced diet": ["diet"],
    "balancer": ["acrobat"],
    "balanchine": ["george balanchine"],
    "balanidae": ["arthropod family", "family balanidae"],
    "balanitis": ["inflammation", "redness", "rubor"],
    "balanoposthitis": ["inflammation", "redness", "rubor"],
    "balanus": ["arthropod genus", "genus balanus"],
    "balarama": [],
    "balas": ["balas ruby", "ruby spinel", "spinel ruby"],
    "balata": ["gum", "gutta balata"],
    "balaton": ["lake balaton", "plattensee"],
    "balboa": ["panamanian monetary unit"],
    "balbriggan": ["knit"],
    "balconied": [],
    "balcony": ["construction", "first balcony", "loge", "mezzanine", "structure"],
    "bald": ["grow", "turn"],
    "bald cypress": ["cypress", "pond bald cypress", "southern cypress", "swamp cypress", "taxodium distichum"],
    "bald eagle": ["american eagle", "bird of jove", "eagle", "haliaeetus leucocephalus"],
    "bald-faced": [],
    "bald-faced hornet": ["hornet", "vespula maculata", "white-faced hornet"],
    "baldachin": ["canopy"],
    "balder": ["baldr"],
    "balderdash": ["bunk", "fiddle-faddle", "hokum", "meaninglessness", "nonsense", "nonsensicality", "piffle"],
    "baldhead": ["baldpate", "baldy", "individual", "mortal", "person", "somebody", "someone", "soul"],
    "balding": [],
    "baldly": [],
    "baldness": ["alopecia", "depilation", "hairlessness", "male pattern baldness", "male-patterned baldness", "phalacrosis"],
    "baldric": ["baldrick", "belt"],
    "baldwin": ["james arthur baldwin", "james baldwin"],
    "bale": ["accumulate", "amass", "collect", "compile", "hoard", "pile up", "roll up"],
    "balearic islands": [],
    "baleen whale": ["balaena mysticetus", "balaenoptera musculus", "blue whale", "bowhead", "bowhead whale", "devilfish", "eschrichtius gibbosus", "eschrichtius robustus", "gray whale", "greenland whale", "grey whale", "humpback", "humpback whale", "megaptera novaeangliae", "razorback", "right whale", "rorqual", "sulfur bottom", "whale", "whalebone whale"],
    "baleful": ["baneful"],
    "balefully": [],
    "balenciaga": ["cristobal balenciaga"],
    "balfour": ["1st earl of balfour", "arthur james balfour"],
    "bali": [],
    "balinese": ["bahasa", "bahasa indonesia", "indonesian"],
    "baling wire": ["wire"],
    "balistes": ["fish genus", "genus balistes"],
    "balistidae": ["family balistidae", "fish family"],
    "balk": ["area", "baulk", "expanse", "surface area"],
    "balkan": ["european"],
    "balkan country": ["balkan nation", "balkan state", "european country", "european nation", "greece"],
    "balkan peninsula": ["balkans"],
    "balkan wars": [],
    "balkanize": ["balkanise", "carve up", "dissever", "divide", "separate", "split", "split up"],
    "balkans": ["balkan mountain range", "balkan mountains"],
    "balker": ["baulker", "individual", "mortal", "negativist", "noncompliant", "person", "somebody", "someone", "soul"],
    "balkiness": ["intractability", "intractableness"],
    "balking": ["balky"],
    "balkline": ["baulk-line", "line", "string line"],
    "ball": ["roll", "twine", "wind", "wrap"],
    "ball and chain": ["bond", "hamper", "shackle", "trammel"],
    "ball bearing": ["bearing", "needle bearing", "roller bearing"],
    "ball boy": ["boy", "male child"],
    "ball carrier": ["football player", "footballer", "forward passer", "passer", "runner", "rusher"],
    "ball cartridge": ["cartridge"],
    "ball field": ["athletic field", "baseball field", "diamond", "field", "playing area", "playing field"],
    "ball game": ["ballgame", "baseball", "baseball game", "field game"],
    "ball gown": ["gown"],
    "ball hawk": ["athlete", "jock"],
    "ball hawking": ["maneuver", "manoeuvre", "play"],
    "ball valve": ["valve"],
    "ball-and-socket joint": ["articulatio coxae", "articulatio humeri", "articulatio spheroidea", "articulatio synovialis", "cotyloid joint", "coxa", "diarthrosis", "enarthrodial joint", "enarthrosis", "hip", "hip joint", "shoulder", "shoulder joint", "spheroid joint", "synovial joint"],
    "ball-buster": ["adult female", "ball-breaker", "woman"],
    "ball-hawking": [],
    "ball-peen hammer": ["hammer"],
    "ball-shaped": ["global", "globose", "globular", "orbicular", "spheric", "spherical"],
    "ballad": ["lay", "minstrelsy", "song", "vocal"],
    "ballade": ["poem", "verse form"],
    "ballast": ["brace", "stabilise", "stabilize", "steady"],
    "ballast resistor": ["ballast", "barretter", "resistance", "resistor"],
    "ballcock": ["ball cock", "regulator"],
    "balldress": ["evening clothes", "evening dress", "eveningwear", "formalwear"],
    "ballerina": ["ballet dancer", "danseuse", "prima ballerina"],
    "ballet": ["music"],
    "ballet company": ["company", "troupe"],
    "ballet dancer": ["ballerina", "dancer", "danseur", "danseur noble", "danseuse", "professional dancer", "terpsichorean"],
    "ballet master": ["dancer", "professional dancer", "terpsichorean"],
    "ballet mistress": ["dancer", "professional dancer", "terpsichorean"],
    "ballet position": ["arabesque", "attitude", "position", "posture"],
    "ballet skirt": ["skirt", "tutu"],
    "balletic": [],
    "balletomane": ["enthusiast", "partisan", "partizan"],
    "balletomania": ["enthusiasm"],
    "ballgame": ["new ballgame", "situation", "state of affairs"],
    "ballistic": [],
    "ballistic galvanometer": ["moving-coil galvanometer"],
    "ballistic identification": ["ballistic fingerprinting", "bullet fingerprinting", "identification"],
    "ballistic missile": ["icbm", "intercontinental ballistic missile", "missile"],
    "ballistic missile defense organization": ["agency", "authority", "bmdo", "bureau", "federal agency", "government agency", "office"],
    "ballistic pendulum": ["compound pendulum", "gun pendulum", "physical pendulum"],
    "ballistics": ["ballistic trajectory", "flight", "trajectory"],
    "ballistocardiogram": ["graph", "graphical record"],
    "ballistocardiograph": ["cardiograph", "medical instrument"],
    "balloon": ["aviate", "fly", "pilot"],
    "balloon bomb": ["bomb", "fugo"],
    "balloon flower": ["penstemon palmeri", "scented penstemon", "wild flower", "wildflower"],
    "balloon sail": ["canvas", "canvass", "sail", "sheet"],
    "balloon vine": ["cardiospermum halicacabum", "heart pea", "soapberry vine"],
    "balloonfish": ["diodon holocanthus", "spiny puffer"],
    "ballooning": ["flight", "flying"],
    "balloonist": ["skilled worker", "skilled workman", "trained worker"],
    "ballot": ["vote"],
    "ballot box": ["box"],
    "ballota": ["asterid dicot genus", "genus ballota"],
    "ballottement": ["palpation", "tactual exploration"],
    "ballpark": ["arena", "bowl", "park", "sports stadium", "stadium"],
    "ballplayer": ["athlete", "base runner", "baseball player", "batsman", "batter", "big leaguer", "bush leaguer", "fielder", "hitter", "hurler", "jock", "little leaguer", "major leaguer", "minor leaguer", "participant", "pitcher", "player", "runner", "slugger", "twirler", "utility man"],
    "ballpoint": ["ballpen", "ballpoint pen", "biro", "pen"],
    "ballroom": ["dance hall", "dance palace", "disco", "discotheque", "room"],
    "ballroom dancing": ["ballroom dance", "beguine", "bunny hug", "carioca", "cha-cha", "cha-cha-cha", "charleston", "conga", "cotilion", "cotillion", "fox-trot", "foxtrot", "minuet", "one-step", "paso doble", "quickstep", "rhumba", "round dance", "round dancing", "rumba", "samba", "social dancing", "tango", "two-step", "valse", "waltz"],
    "ballup": ["balls-up", "cockup", "error", "fault", "mess-up", "mistake"],
    "bally": ["blinking", "bloody", "blooming", "crashing", "flaming", "fucking"],
    "ballyhoo": ["advertise", "advertize", "publicise", "publicize"],
    "balm": ["balm of gilead", "balsam"],
    "balm of gilead": ["balm"],
    "balminess": ["clemency", "mildness", "softness"],
    "balmoral": ["shoe"],
    "balmoral castle": [],
    "balmy": ["around the bend", "barmy", "bats", "batty", "bonkers", "buggy", "cracked", "crackers", "daft", "dotty", "fruity", "haywire", "kookie", "kooky", "loco", "loony", "loopy", "nuts", "nutty", "round the bend", "wacky", "whacky"],
    "balochi": ["baluchi", "iranian", "iranian language"],
    "baloney": ["bilgewater", "boloney", "bosh", "bunk", "drool", "hokum", "humbug", "meaninglessness", "nonsense", "nonsensicality", "taradiddle", "tarradiddle", "tommyrot", "tosh", "twaddle"],
    "balsa": ["balsa wood", "wood"],
    "balsa raft": ["kon tiki", "raft"],
    "balsam": ["balm", "balsam of tolu", "oleoresin", "tolu", "tolu balsam"],
    "balsam apple": ["gourd", "gourd vine", "momordica balsamina"],
    "balsam fir": ["abies balsamea", "balm of gilead", "canada balsam", "silver fir"],
    "balsam of peru": ["balsam of tolu", "tolu", "tolu balsam"],
    "balsam pear": ["gourd", "gourd vine", "momordica charantia"],
    "balsam poplar": ["hackmatack", "poplar", "poplar tree", "populus balsamifera", "tacamahac"],
    "balsam willow": ["salix pyrifolia", "willow", "willow tree"],
    "balsam woolly aphid": ["adelges piceae", "adelgid"],
    "balsam-scented": [],
    "balsamic": ["balsamy"],
    "balsaminaceae": ["balsam family", "family balsaminaceae", "rosid dicot family"],
    "balsamorhiza": ["asterid dicot genus", "genus balsamorhiza"],
    "balsamroot": ["herb", "herbaceous plant"],
    "balthazar": ["balthasar"],
    "baltic": ["baltic sea"],
    "baltic state": ["baltic republic", "geographic area", "geographic region", "geographical area", "geographical region"],
    "baltic-finnic": ["carelian", "esthonian", "estonian", "fennic", "finnic", "finnish", "ingrian", "karelian", "livonian", "ludian", "non-ugric", "suomi", "veps", "vepse", "vepsian"],
    "baltimore": [],
    "baltimore oriole": ["baltimore bird", "firebird", "hangbird", "icterus galbula", "icterus galbula galbula", "northern oriole"],
    "balto-slavic": ["baltic", "baltic language", "balto-slavic language", "balto-slavonic", "indo-european", "indo-european language", "indo-hittite", "slavic", "slavic language", "slavonic", "slavonic language"],
    "baluster": ["support"],
    "balzac": ["honore balzac", "honore de balzac"],
    "balzacian": [],
    "bam": [],
    "bamako": [],
    "bamboo": ["wood"],
    "bamboo curtain": ["ideological barrier"],
    "bamboo fern": ["coniogramme japonica", "fern"],
    "bamboo palm": ["raffia farinifera", "raffia palm", "raffia ruffia", "raffia vinifera"],
    "bamboo shoot": ["veg", "vegetable", "veggie"],
    "bamboozle": ["betray", "deceive", "hoodwink", "lead astray", "lead by the nose", "play false", "pull the wool over someone's eyes", "snow"],
    "bambusa": ["genus bambusa", "liliopsid genus", "monocot genus"],
    "bambuseae": ["tribe", "tribe bambuseae"],
    "ban": ["censor", "criminalise", "criminalize", "embargo", "illegalise", "illegalize", "outlaw"],
    "banal": ["commonplace", "hackneyed", "old-hat", "shopworn", "stock", "threadbare", "timeworn", "tired", "trite", "well-worn"],
    "banana": ["abaca", "banana tree", "dwarf banana", "edible banana", "herb", "herbaceous plant", "japanese banana", "manila hemp", "musa acuminata", "musa basjoo", "musa paradisiaca", "musa paradisiaca sapientum", "musa textilis", "plantain", "plantain tree"],
    "banana boat": ["cargo ship", "cargo vessel"],
    "banana bread": ["quick bread"],
    "banana oil": ["ester"],
    "banana passion fruit": ["passiflora mollissima", "passionflower", "passionflower vine"],
    "banana peel": ["banana skin", "peel", "skin"],
    "banana quit": ["honeycreeper"],
    "banana republic": ["country", "land", "state"],
    "banana split": ["split"],
    "banausic": [],
    "band": ["bind", "tie"],
    "band aid": ["adhesive bandage"],
    "band oneself": ["fall in", "get together", "join", "league together"],
    "band together": ["confederate", "unify", "unite"],
    "band-tailed pigeon": ["band-tail pigeon", "bandtail", "columba fasciata", "pigeon"],
    "bandage": ["dress", "ligate"],
    "bandaged": ["bound"],
    "bandanna": ["bandana", "handkerchief", "hankey", "hankie", "hanky"],
    "bandbox": ["box"],
    "banded": [],
    "banded gecko": ["gecko"],
    "banded krait": ["banded adder", "bungarus fasciatus", "krait"],
    "banded palm civet": ["civet", "civet cat", "hemigalus hardwickii"],
    "banded purple": ["brush-footed butterfly", "four-footed butterfly", "limenitis arthemis", "nymphalid", "nymphalid butterfly", "white admiral"],
    "banded sand snake": ["chilomeniscus cinctus", "sand snake"],
    "banded stilt": ["australian stilt", "cladorhyncus leucocephalum", "stilt"],
    "banderilla": ["dart"],
    "banderillero": ["bullfighter", "toreador"],
    "bandicoot": ["bilby", "macrotis lagotis", "marsupial", "pouched mammal", "rabbit bandicoot", "rabbit-eared bandicoot"],
    "bandicoot rat": ["mole rat", "rat"],
    "bandit": ["brigand", "stealer", "thief"],
    "banditry": ["pillage", "pillaging", "plundering"],
    "bandleader": ["conductor", "director", "music director"],
    "bandmaster": ["conductor", "director", "music director"],
    "bandoleer": ["bandolier", "cartridge belt"],
    "bandoneon": ["concertina"],
    "bandsaw": ["band saw", "power saw", "saw", "sawing machine"],
    "bandsman": ["instrumentalist", "musician", "player"],
    "bandstand": ["outdoor stage", "platform", "stand"],
    "bandung": [],
    "bandwagon": ["style", "trend", "vogue"],
    "bandwagon effect": ["consequence", "effect", "event", "issue", "outcome", "result", "upshot"],
    "bandwidth": ["information measure"],
    "bandy": ["play", "shuttlecock"],
    "bandy about": ["discuss", "hash out", "talk over"],
    "bane": ["affliction", "curse", "nemesis", "scourge"],
    "baneberry": ["berry"],
    "baneful": ["deadly", "pernicious", "pestilent"],
    "banefully": ["perniciously"],
    "banff": [],
    "bang": ["go", "sound"],
    "bang out": ["play", "spiel"],
    "bang up": ["damage", "smash", "smash up"],
    "bang-up": ["bully", "corking", "cracking", "dandy", "great", "groovy", "keen", "neat", "nifty", "not bad", "peachy", "slap-up", "smashing", "swell"],
    "bangalore": [],
    "bangalore torpedo": ["torpedo"],
    "banger": ["pork sausage"],
    "bangiaceae": ["family bangiaceae", "protoctist family"],
    "banging": ["noise"],
    "bangkok": ["capital of thailand", "krung thep"],
    "bangladesh": ["bangla desh", "east pakistan", "people's republic of bangladesh"],
    "bangladeshi": ["asian", "asiatic"],
    "bangladeshi monetary unit": ["monetary unit", "taka"],
    "bangle": ["adornment", "bauble", "fallal", "gaud", "gewgaw", "novelty", "trinket"],
    "bangor": [],
    "bangui": ["capital of central africa"],
    "banish": ["ban", "expel", "kick out", "rusticate", "throw out"],
    "banishment": ["coventry", "exclusion", "ostracism"],
    "banjo": ["stringed instrument"],
    "banjul": ["capital of gambia"],
    "bank": ["transact"],
    "bank account": ["account", "business relationship", "checking account", "chequing account", "current account", "giro account", "savings account"],
    "bank card": ["charge card", "charge plate", "credit card", "plastic"],
    "bank charter": ["charter"],
    "bank closing": ["closedown", "closing", "closure", "shutdown"],
    "bank commissioner": ["commissioner"],
    "bank draft": ["banker's draft", "bill of exchange", "draft", "order of payment"],
    "bank examination": ["examination", "scrutiny"],
    "bank examiner": ["examiner", "inspector"],
    "bank failure": ["failure"],
    "bank gravel": ["crushed rock", "gravel", "pit run", "pit-run gravel"],
    "bank guard": ["security guard", "watcher", "watchman"],
    "bank holding company": ["holding company", "multibank holding company"],
    "bank holiday": ["legal holiday", "national holiday", "public holiday"],
    "bank identification number": ["aba transit number", "bin", "identification number", "number"],
    "bank loan": ["business loan", "commercial loan", "interbank loan", "loan"],
    "bank manager": ["director", "manager", "managing director"],
    "bank martin": ["bank swallow", "martin", "riparia riparia", "sand martin"],
    "bank of england": ["central bank"],
    "bank of japan": ["central bank"],
    "bank rate": ["bank discount", "discount", "discount rate"],
    "bank robber": ["robber"],
    "bank run": ["bank withdrawal"],
    "bank shot": ["basketball shot"],
    "bank statement": ["financial statement", "statement"],
    "bank withdrawal": ["bank run", "withdrawal"],
    "bank-depositor relation": ["fiduciary relation"],
    "bankable": [],
    "bankbook": ["passbook", "record"],
    "banker": ["bank clerk", "cashier", "financier", "moneyman", "teller"],
    "bankhead": ["tallulah bankhead"],
    "bankia": ["genus bankia", "mollusk genus"],
    "banking": ["finance"],
    "banking game": ["gambling game", "game of chance"],
    "banking industry": ["banking system", "farm credit system", "fcs", "hawala", "industry"],
    "bankroll": ["fund"],
    "bankrupt": ["break", "impoverish", "ruin", "smash"],
    "bankruptcy": ["failure"],
    "banks": ["sir joseph banks"],
    "banksia": ["australian honeysuckle", "banksia integrifolia", "bush", "coast banksia", "honeysuckle", "shrub"],
    "banksia rose": ["rosa banksia", "rose", "rosebush"],
    "banned": ["prohibited"],
    "banner": ["flag", "streamer"],
    "bannerlike": [],
    "banning-order": ["ban", "prohibition", "proscription"],
    "bannister": ["roger bannister", "sir roger gilbert bannister"],
    "bannock": ["flatbread"],
    "bannockburn": [],
    "banns": ["announcement", "promulgation"],
    "banquet": ["dinner", "dinner party", "feast", "gaudy"],
    "banquette": ["bench"],
    "banshee": ["banshie", "disembodied spirit", "spirit"],
    "bantam": ["domestic fowl", "fowl", "poultry"],
    "bantamweight": ["grappler", "matman", "wrestler"],
    "banteng": ["banting", "bos banteng", "ox", "tsine", "wild ox"],
    "banter": ["backchat", "badinage", "give-and-take", "persiflage", "raillery", "repartee"],
    "bantering": ["facetious", "tongue-in-cheek"],
    "banteringly": ["tongue-in-cheek"],
    "banti's disease": ["banti's syndrome", "blood disease", "blood disorder"],
    "banting": ["f. g. banting", "sir frederick grant banting"],
    "bantoid": [],
    "bantu": ["african", "batswana", "bechuana", "chiluba", "herero", "hutu", "luba", "shona", "sotho", "tswana", "tutsi", "watusi", "watutsi"],
    "bantu-speaking": [],
    "banyan": ["banian", "banian tree", "banyan tree", "east indian fig tree", "ficus bengalensis", "fig tree", "indian banyan"],
    "banzai": ["cheer"],
    "banzai attack": ["attack", "banzai charge", "onrush", "onset", "onslaught"],
    "baobab": ["adansonia digitata", "angiospermous tree", "flowering tree", "monkey-bread tree"],
    "bap": ["bread", "breadstuff", "staff of life"],
    "baphia": ["genus baphia", "rosid dicot genus"],
    "baptisia": ["genus baptisia", "rosid dicot genus"],
    "baptism": ["affusion", "aspersion", "christening", "immersion", "sacrament", "sprinkling"],
    "baptismal": [],
    "baptismal font": ["baptistery", "baptistry", "basin", "font"],
    "baptist": ["dunkard", "dunker", "northern baptist", "protestant", "southern baptist", "tunker"],
    "baptist church": ["baptists", "protestant denomination"],
    "baptist denomination": ["arminian baptist", "calvinistic baptist", "church of the brethren", "dippers", "dunkers", "general baptist", "particular baptist", "protestant denomination"],
    "baptistic": [],
    "baptistic doctrine": ["protestantism"],
    "baptize": ["baptise", "call", "christen", "name"],
    "baptized": ["baptised"],
    "bar": ["fasten", "fix", "secure"],
    "bar bit": ["bit"],
    "bar chart": ["bar graph", "chart", "histogram"],
    "bar code": ["code", "universal product code"],
    "bar examination": ["bar exam", "exam", "examination", "test"],
    "bar fly": ["drinker", "imbiber", "juicer", "toper"],
    "bar line": ["double bar", "line", "musical notation"],
    "bar magnet": ["magnet"],
    "bar mask": ["catcher's mask"],
    "bar mitzvah": ["covenant"],
    "bar printer": ["impact printer"],
    "bar sinister": ["bend sinister", "brand", "mark", "ordinary", "stain", "stigma"],
    "bar soap": ["soap"],
    "bar-shaped": [],
    "baraka": ["imamu amiri baraka", "leroi jones"],
    "barany": ["robert barany"],
    "barb": ["alter", "change", "modify"],
    "barbadian": ["west indian"],
    "barbados": [],
    "barbados cherry": ["acerola", "dicot", "dicotyledon", "exogen", "magnoliopsid", "malpighia glabra", "surinam cherry", "west indian cherry"],
    "barbados dollar": ["dollar"],
    "barbados gooseberry": ["barbados-gooseberry vine", "pereskia aculeata", "vine"],
    "barbarea": ["dilleniid dicot genus", "genus barbarea"],
    "barbarian": ["barbaric", "savage", "uncivilised", "uncivilized", "wild"],
    "barbaric": [],
    "barbarization": ["barbarisation", "debasement", "degradation"],
    "barbarize": ["barbarise", "change"],
    "barbarossa": ["khayr ad-din"],
    "barbarous": ["brutal", "cruel", "fell", "roughshod", "savage", "vicious"],
    "barbarously": [],
    "barbary": [],
    "barbary ape": ["macaca sylvana", "macaque"],
    "barbary coast": ["city district"],
    "barbasco": ["bush", "jacquinia keyensis", "joewood", "shrub"],
    "barbecue": ["barbeque", "dish"],
    "barbecue pit": ["cavity", "pit"],
    "barbecue sauce": ["sauce"],
    "barbecued": ["grilled"],
    "barbecued spareribs": ["dish", "spareribs"],
    "barbecued wing": ["dish"],
    "barbecuing": ["roasting"],
    "barbed": ["biting", "mordacious", "nipping", "pungent"],
    "barbed wire": ["barbwire", "concertina", "wire"],
    "barbel": ["feeler", "tentacle"],
    "barbell": ["exercising weight", "free weight", "weight"],
    "barbeque": ["barbecue", "cook out", "grill"],
    "barber": ["groom", "neaten"],
    "barber chair": ["chair"],
    "barber's pole": ["visual signal"],
    "barberry": ["american barberry", "berberis canadensis", "berberis thunbergii", "berberis vulgaris", "bush", "common barberry", "european barberry", "japanese barberry", "shrub"],
    "barbershop": ["shop", "store"],
    "barbershop quartet": ["quartet", "quartette"],
    "barberton daisy": ["african daisy", "gerbera jamesonii", "transvaal daisy"],
    "barbet": ["piciform bird"],
    "barbette": ["hill", "mound"],
    "barbette carriage": ["gun carriage"],
    "barbican": ["barbacan", "tower"],
    "barbital": ["barbitone", "barbiturate", "diethylbarbituric acid", "diethylmalonylurea", "veronal"],
    "barbiturate": ["amobarbital", "barbital", "barbitone", "diethylbarbituric acid", "diethylmalonylurea", "luminal", "mebaral", "mephobarbital", "nembutal", "pentobarbital", "pentobarbital sodium", "pentothal", "phenobarbital", "phenobarbitone", "purple heart", "red devil", "secobarbital", "secobarbital sodium", "seconal", "sedative-hypnotic", "sedative-hypnotic drug", "sodium thiopental", "thiopental", "thiopental sodium", "thiopentobarbital sodium", "veronal", "yellow jacket"],
    "barbituric acid": ["acid", "malonylurea"],
    "barbu": ["polydactylus virginicus", "threadfin"],
    "barbuda": [],
    "barcarole": ["barcarolle", "song", "vocal"],
    "barcelona": [],
    "bard": ["poet"],
    "bardeen": ["john bardeen"],
    "bardic": [],
    "bardolatry": ["idolisation", "idolization"],
    "bare": ["expose", "uncover"],
    "bare bone": ["bone", "os"],
    "bare bones": ["center", "centre", "core", "essence", "gist", "heart", "heart and soul", "inwardness", "kernel", "marrow", "meat", "nitty-gritty", "nub", "pith", "substance", "sum"],
    "bare-assed": ["bare-ass", "in the altogether", "in the buff", "in the raw", "naked as a jaybird", "peeled", "raw", "stark naked"],
    "bare-breasted": ["braless", "topless"],
    "bareback": ["barebacked"],
    "bareboat": ["vessel", "watercraft"],
    "bareboating": ["boating", "yachting"],
    "barefoot": ["barefooted", "shoeless"],
    "barefooted": ["barefoot"],
    "barehanded": [],
    "bareheaded": ["bared"],
    "barelegged": [],
    "barely": ["hardly", "just", "scarce", "scarcely"],
    "bareness": ["nakedness", "nudeness", "nudity"],
    "barents sea": []
}
