synonyms = {
    "despiteful": ["spiteful", "vindictive"],
    "despitefully": ["spitefully"],
    "despoiled": ["pillaged", "raped", "ravaged", "sacked"],
    "despond": ["despair"],
    "despondency": ["depression", "despondence", "disconsolateness", "heartsickness"],
    "despondent": ["heartsick"],
    "despotic": ["despotical"],
    "desquamate": ["exuviate", "molt", "moult", "peel off", "shed", "slough"],
    "desquamation": ["organic phenomenon", "peeling", "shedding"],
    "dessert": ["afters", "ambrosia", "baked alaska", "blancmange", "charlotte", "compote", "course", "dumpling", "flan", "frozen dessert", "fruit compote", "junket", "mold", "mould", "mousse", "pavlova", "peach melba", "pud", "pudding", "sabayon", "sillabub", "sweet", "syllabub", "tiramisu", "whip", "zabaglione"],
    "dessert plate": ["plate"],
    "dessert spoon": ["spoon"],
    "dessert wine": ["straw wine", "vino", "wine"],
    "dessertspoon": ["containerful", "dessertspoonful"],
    "dessiatine": ["area unit", "square measure"],
    "destabilization": ["alteration", "change", "modification"],
    "destabilize": ["change", "destabilise"],
    "destain": ["get rid of", "remove"],
    "destalinization": ["de-stalinisation", "de-stalinization", "destalinisation", "social process"],
    "destalinize": ["destalinise", "transform", "transmute", "transubstantiate"],
    "destination": ["end", "goal", "terminus"],
    "destine": ["designate", "doom", "fate", "ordain"],
    "destiny": ["causal agency", "causal agent", "cause", "fate"],
    "destitute": ["impoverished", "indigent", "necessitous", "needy", "poverty-stricken"],
    "destitution": ["impoverishment", "poorness", "poverty"],
    "destroy": ["break apart", "break up", "demolish", "demyelinate", "destruct", "dilapidate", "disassemble", "dismantle", "do away with", "eliminate", "end", "eradicate", "exterminate", "extinguish", "extirpate", "fracture", "get rid of", "interdict", "kill", "level", "pull down", "pulverise", "pulverize", "rase", "raze", "root out", "self-destroy", "self-destruct", "sweep away", "take apart", "take down", "tear down", "undo", "unmake", "uproot", "wipe out"],
    "destroyable": [],
    "destroyed": ["ruined"],
    "destroyer": ["annihilator", "bad person", "diversionist", "iconoclast", "image breaker", "ruiner", "saboteur", "undoer", "uprooter", "vandal", "waster", "wrecker"],
    "destroyer escort": ["combat ship", "war vessel", "warship"],
    "destroying angel": ["agaric", "amanita verna"],
    "destruct": ["destroy", "destruct"],
    "destructibility": ["vulnerability"],
    "destructible": [],
    "destruction": ["annihilation", "conclusion", "demolition", "depredation", "disintegration", "ending", "eradication", "finish", "obliteration", "rack", "ravage", "razing", "ruin", "ruination", "wipeout", "wrack", "wrecking"],
    "destruction fire": ["fire", "firing"],
    "destructive": [],
    "destructive distillation": ["carbonisation", "carbonization", "fractional process", "fractionation"],
    "destructive-metabolic": ["energy-releasing"],
    "destructively": [],
    "destructiveness": ["harmfulness", "injuriousness", "poison", "quality"],
    "desuetude": ["inaction", "inactiveness", "inactivity"],
    "desulfurize": ["desulphurize", "get rid of", "remove"],
    "desultory": [],
    "desynchronize": ["change by reversal", "desynchronise", "reverse", "turn"],
    "detach": ["divide", "separate"],
    "detachable": [],
    "detached": ["isolated", "separated", "set-apart"],
    "detached house": ["house", "single dwelling"],
    "detachment": ["army unit", "bodyguard", "patrol", "picket", "press gang", "provost guard", "rearguard"],
    "detail": ["dilate", "elaborate", "enlarge", "expand", "expatiate", "exposit", "expound", "flesh out", "lucubrate"],
    "detailed": ["elaborate", "elaborated"],
    "details": ["dope", "info", "information", "inside information", "low-down", "poop", "the skinny"],
    "detainee": ["captive", "political detainee", "prisoner"],
    "detect": ["catch out", "discover", "find", "find out", "instantiate", "notice", "observe", "see", "sense", "sight", "spy", "trace"],
    "detectable": ["noticeable"],
    "detected": [],
    "detection": ["perception", "sensing"],
    "detective": ["investigator", "operative", "pi", "private detective", "private eye", "private investigator", "shamus", "sherlock", "sleuth", "sleuthhound"],
    "detective agency": ["agency"],
    "detective novel": ["mystery novel", "novel"],
    "detective story": ["mystery", "mystery story", "whodunit"],
    "detector": ["demodulator", "rectifier"],
    "detente": ["alleviation", "easement", "easing", "relief"],
    "detention": ["confinement", "custody", "detainment", "hold"],
    "detention basin": ["basin", "catchment area", "catchment basin", "drainage area", "drainage basin", "river basin", "watershed"],
    "detention home": ["correctional institution", "detention camp", "detention house", "house of detention"],
    "deter": ["disapprove", "discourage", "reject"],
    "deterge": ["wipe away", "wipe off"],
    "detergency": ["detergence", "usefulness", "utility"],
    "detergent": ["anionic", "anionic detergent", "cationic detergent", "invert soap", "non-ionic detergent", "sls", "sodium lauryl sulfate", "sodium lauryl sulphate", "surface-active agent", "surfactant", "wetter", "wetting agent"],
    "deteriorate": ["crumble", "decay", "dilapidate", "go to pot", "go to the dogs", "wear", "wear down", "wear off", "wear out", "wear thin"],
    "deterioration": ["corrosion", "decay", "decrepitude", "desolation", "devastation", "dilapidation", "impairment", "wear"],
    "determent": ["deterrence", "discouragement", "intimidation"],
    "determinable": [],
    "determinant": ["square matrix"],
    "determinate": [],
    "determinateness": ["conclusiveness", "decisiveness", "definiteness", "finality", "predictability"],
    "determination": ["deciding", "decision making"],
    "determine": ["ascertain", "check", "find out", "learn", "see", "test", "watch"],
    "determined": [],
    "determinedly": ["unfalteringly", "unshakably"],
    "determiner": ["article", "closed-class word", "determinative", "function word"],
    "determinism": ["fatalism", "philosophical doctrine", "philosophical theory"],
    "deterministic": [],
    "deterrence": ["discouragement", "hinderance", "hindrance", "interference", "nuclear deterrence"],
    "deterrent": [],
    "detestably": ["abominably", "odiously", "repulsively"],
    "dethrone": ["disinvest", "divest"],
    "detick": ["get rid of", "remove"],
    "detonate": ["blow up", "explode"],
    "detonating fuse": ["fuse", "fusee", "fuze", "fuzee", "primer", "priming"],
    "detonation": ["burst", "explosion", "percussion"],
    "detonative": [],
    "detonator": ["blasting cap", "cap", "detonating device", "explosive device", "percussion cap"],
    "detour": ["deviate", "divert"],
    "detox": ["care for", "detoxify", "treat"],
    "detoxification": ["intervention", "treatment"],
    "detoxify": ["detoxicate", "remove", "take", "take away", "withdraw"],
    "detraction": ["depreciation", "derogation", "disparagement", "petty criticism"],
    "detractive": [],
    "detractor": ["backbiter", "cynic", "defamer", "depreciator", "disparager", "faultfinder", "hatemonger", "knocker", "libeler", "maligner", "muckraker", "mudslinger", "slanderer", "traducer", "vilifier"],
    "detrain": ["get off"],
    "detransitivize": ["alter", "change", "detransitivise", "intransitivise", "intransitivize", "modify"],
    "detribalization": ["detribalisation", "social control"],
    "detribalize": ["acculturate", "detribalise"],
    "detriment": ["damage", "expense", "harm", "hurt", "impairment"],
    "detrimentally": ["harmfully", "noxiously"],
    "detritus": ["material", "stuff"],
    "detroit": ["motor city", "motown"],
    "detroit river": [],
    "detumescence": ["decline", "diminution"],
    "deuce": ["tie"],
    "deus ex machina": ["causal agency", "causal agent", "cause"],
    "deuteranopia": ["daltonism", "green-blindness", "red-green color blindness", "red-green colour blindness", "red-green dichromacy"],
    "deuteranopic": ["green-blind"],
    "deuterium": ["heavy hydrogen", "hydrogen atom", "isotope"],
    "deuteromycetes": ["class", "class deuteromycetes"],
    "deuteromycota": ["deuteromycotina", "division", "fungi imperfecti", "subdivision deuteromycota", "subdivision deuteromycotina"],
    "deuteron": ["particle", "subatomic particle"],
    "deuteronomy": ["book of deuteronomy"],
    "deutzia": ["hydrangea"],
    "devaluation": ["regulating", "regulation"],
    "devalue": ["cheapen", "degrade", "demonetise", "demonetize", "devaluate"],
    "devanagari": ["devanagari script", "nagari", "nagari script", "script", "syllabary", "syllabic script"],
    "devastate": ["overcome", "overpower", "overtake", "overwhelm", "sweep over", "whelm"],
    "devastation": ["blight", "desolation", "deterioration", "impairment", "ruin", "ruination"],
    "devein": ["get rid of", "remove"],
    "develop": ["alter", "change", "modify", "redevelop", "solarise", "solarize", "underdevelop"],
    "developed": ["highly-developed"],
    "developer": ["creator"],
    "developing": ["underdeveloped"],
    "developing country": ["body politic", "commonwealth", "country", "land", "nation", "res publica", "state"],
    "development": ["improvement", "melioration", "underdevelopment"],
    "developmental": [],
    "developmental age": ["age"],
    "developmental anatomy": ["anatomy", "general anatomy"],
    "developmental learning": ["accommodation", "acquisition", "assimilation", "learning"],
    "developmental psychology": ["child psychology", "genetic psychology", "psychological science", "psychology"],
    "developmentally": [],
    "devi": [],
    "deviate": ["aberrate", "belie", "contradict", "depart", "differ", "diverge", "negate", "vary"],
    "deviated nasal septum": ["deviated septum"],
    "deviated septum": ["abnormalcy", "abnormality", "deviated nasal septum"],
    "deviation": ["departure", "difference", "discrepancy", "divergence", "driftage", "flection", "flexion", "fluctuation", "inflection", "variance", "variant", "variation"],
    "deviationism": ["abandonment", "defection", "desertion"],
    "deviationist": ["defector", "deserter"],
    "device": ["conceit", "expressive style", "rhetorical device", "style"],
    "devices": ["disposition", "inclination", "tendency"],
    "devil": ["cook", "fix", "make", "prepare", "ready"],
    "devil ray": ["devilfish", "manta", "manta ray", "mobula hypostoma"],
    "devil worshiper": ["believer", "diabolist", "satanist", "worshiper", "worshipper"],
    "devil's advocate": ["arguer", "debater"],
    "devil's cigar": ["sarcosomataceae"],
    "devil's food": ["chocolate cake", "devil's food cake"],
    "devil's tongue": ["amorphophallus rivieri", "aroid", "arum", "snake palm", "umbrella arum"],
    "devil's urn": ["sarcosomataceae"],
    "devil-may-care": ["raffish", "rakish"],
    "deviled egg": ["dish", "stuffed egg"],
    "devilish": ["rascally", "roguish"],
    "devilishly": ["devilish"],
    "devilize": ["alter", "change", "devilise", "diabolise", "diabolize", "modify"],
    "deviltry": ["devilry", "evil", "immorality", "iniquity", "wickedness"],
    "devilwood": ["american olive", "osmanthus americanus", "tree"],
    "devious": ["shifty"],
    "deviously": [],
    "deviousness": ["indirectness", "obliqueness"],
    "devisal": ["contrivance", "invention"],
    "devise": ["bequeath", "leave", "will"],
    "devisee": ["beneficiary", "donee"],
    "devising": ["cartography", "fashioning", "film making", "making", "mapmaking", "movie making", "moviemaking", "production"],
    "devisor": ["testate", "testator"],
    "devitalization": ["decrease", "devitalisation", "diminution", "reduction", "step-down"],
    "devitalize": ["devitalise", "eviscerate", "weaken"],
    "devitrify": ["crystalise", "crystalize", "crystallize", "effloresce"],
    "devoice": ["articulate", "enounce", "enunciate", "pronounce", "say", "sound out"],
    "devoir": ["civility", "politeness"],
    "devolution": ["delegating", "delegation", "deputation", "devolvement", "relegating", "relegation"],
    "devolve": ["assign", "delegate", "depute", "designate"],
    "devon": ["devonshire"],
    "devonian": ["age of fishes", "devonian period"],
    "devote": ["reserve"],
    "devoted": [],
    "devotedly": [],
    "devotion": ["devotedness", "love"],
    "devotional": ["divine service", "religious service", "service"],
    "devour": ["bask", "enjoy", "relish", "savor", "savour"],
    "devourer": ["eater", "feeder"],
    "devout": ["god-fearing"],
    "devoutly": ["piously"],
    "devoutness": ["pietism", "piety", "piousness", "religionism", "religiosity", "religiousism", "religiousness"],
    "devries": ["de vries", "hugo de vries", "hugo devries"],
    "dew": ["condensate", "condensation"],
    "dew point": ["saturation point", "temperature"],
    "dewar": ["sir james dewar"],
    "dewar flask": ["dewar", "vacuum bottle", "vacuum flask"],
    "dewberry": ["american dewberry", "blackberry", "blackberry bush", "dewberry bush", "european dewberry", "northern dewberry", "rubus caesius", "rubus canadensis", "rubus flagellaris", "rubus hispidus", "rubus trivialis", "running blackberry", "southern dewberry", "swamp blackberry", "swamp dewberry"],
    "dewdrop": ["bead", "drop", "pearl"],
    "dewey": ["melvil dewey", "melville louis kossuth dewey"],
    "dewey decimal classification": ["classification system", "decimal system of classification", "dewey decimal system"],
    "deweyan": [],
    "dewlap": ["cutis", "skin", "tegument"],
    "dexamethasone": ["adrenal cortical steroid", "anti-inflammatory", "anti-inflammatory drug", "corticoid", "corticosteroid", "decadron", "dexamethasone intensol", "dexone", "hexadrol", "oradexon"],
    "dexter": [],
    "dexterity": ["adeptness", "adroitness", "deftness", "facility", "manual dexterity", "quickness", "sleight"],
    "dexterously": ["deftly", "dextrously"],
    "dextral": [],
    "dextrin": ["polyose", "polysaccharide"],
    "dextroamphetamine sulphate": ["amphetamine", "dexedrine", "pep pill", "speed", "upper"],
    "dextrocardia": ["abnormalcy", "abnormality"],
    "dextrorotary": ["dextrorotatory", "right-handed"],
    "dextrorotation": ["clockwise rotation", "gyration", "revolution", "rotation"],
    "dextrorse": ["dextrorsal"],
    "dextrose": ["dextroglucose", "glucose", "grape sugar"],
    "dhahran": [],
    "dhak": ["butea frondosa", "butea monosperma", "dak", "palas", "tree"],
    "dhaka": ["capital of bangladesh", "dacca"],
    "dharma": ["hindu deity"],
    "dhaulagiri": [],
    "dhawa": ["dhava", "tree"],
    "dhegiha": ["kansa", "kansas", "maha", "omaha", "osage", "ponca", "ponka", "quapaw", "siouan", "sioux"],
    "dhobi itch": ["ringworm", "roundworm", "tinea"],
    "dhole": ["cuon alpinus", "wild dog"],
    "dhoti": ["breechcloth", "breechclout", "loincloth"],
    "dhow": ["sailing ship", "sailing vessel"],
    "dhu'l-hijja": ["dhu al-hijja", "dhu al-hijjah", "dhu'l-hijjah", "islamic calendar month"],
    "dhu'l-qa'dah": ["dhu al-qadah", "islamic calendar month"],
    "di-iodotyrosine": ["iodotyrosine"],
    "diabatic": [],
    "diabetes": ["diabetes insipidus", "diabetes mellitus", "dm", "polygenic disease", "polygenic disorder"],
    "diabetes insipidus": ["diabetes", "nephrogenic diabetes insipidus"],
    "diabetes mellitus": ["adult-onset diabetes", "adult-onset diabetes mellitus", "autoimmune diabetes", "chemical diabetes", "diabetes", "dm", "growth-onset diabetes", "iddm", "insulin-dependent diabetes mellitus", "juvenile diabetes", "juvenile-onset diabetes", "ketoacidosis-prone diabetes", "ketoacidosis-resistant diabetes", "ketoacidosis-resistant diabetes mellitus", "ketosis-prone diabetes", "ketosis-resistant diabetes", "ketosis-resistant diabetes mellitus", "latent diabetes", "mature-onset diabetes", "maturity-onset diabetes", "maturity-onset diabetes mellitus", "niddm", "non-insulin-dependent diabetes", "non-insulin-dependent diabetes mellitus", "type i diabetes", "type ii diabetes"],
    "diabetic": ["diseased person", "sick person", "sufferer"],
    "diabetic coma": ["coma", "comatoseness", "kussmaul's coma"],
    "diabetic diet": ["diet"],
    "diabetic retinopathy": ["retinopathy"],
    "diabolatry": ["demonolatry", "devil-worship", "worship"],
    "diabolically": ["devilishly", "fiendishly"],
    "diabolism": ["black art", "black magic", "demonism", "necromancy", "satanism", "sorcery"],
    "diacalpa": ["fern genus", "genus diacalpa"],
    "diachronic": ["historical"],
    "diacritic": ["diacritical"],
    "diacritical mark": ["accent", "accent mark", "breve", "cedilla", "circumflex", "diacritic", "diaeresis", "dieresis", "hacek", "macron", "mark", "tilde", "umlaut", "wedge"],
    "diadophis": ["genus diadophis", "reptile genus"],
    "diadromous": [],
    "diaghilev": ["sergei diaghilev", "sergei pavlovich diaghilev"],
    "diagnosable": [],
    "diagnose": ["analyse", "analyze", "canvas", "canvass", "examine", "explore", "study"],
    "diagnosis": ["blood typing", "designation", "diagnosing", "identification", "medical diagnosis", "uranalysis", "urinalysis"],
    "diagnostic": [],
    "diagnostic procedure": ["auscultation", "cardiography", "diagnostic technique", "echocardiography", "echoencephalography", "electrocardiography", "electromyography", "mammography", "prenatal diagnosis", "procedure", "process", "roentgenography", "thermography", "x-ray photography"],
    "diagnostic program": ["service program", "utility", "utility program"],
    "diagnostic test": ["assay", "biopsy", "cloze procedure", "cloze test", "diagnostic assay", "faecal occult test", "fecal occult test", "gi series", "glucose tolerance test", "pap test", "papanicolaou test", "pku test", "queckenstedt's test", "radioactive iodine test", "rubin test", "skin test", "smear test", "stool test", "tissue typing", "vital capacity"],
    "diagnostician": ["aetiologist", "etiologist", "medical specialist", "pathologist", "specialist"],
    "diagonal": ["straight line"],
    "diagonal matrix": ["scalar matrix", "square matrix"],
    "diagonalizable": [],
    "diagonalization": ["diagonalisation", "resolution", "resolving"],
    "diagonalize": ["diagonalise", "transform", "translate"],
    "diagonally": [],
    "diagram": ["draw", "graph", "plot"],
    "diagrammatic": ["diagrammatical"],
    "diagrammatically": ["graphically"],
    "diakinesis": ["phase", "stage"],
    "dial": ["control", "operate"],
    "dial telephone": ["dial phone", "phone", "telephone", "telephone set"],
    "dialect": ["accent", "eye dialect", "idiom", "non-standard speech", "patois"],
    "dialect atlas": ["atlas", "book of maps", "linguistic atlas", "map collection"],
    "dialect geography": ["linguistic geography", "linguistics"],
    "dialectal": [],
    "dialectic": ["contradiction"],
    "dialectical materialism": ["materialism", "physicalism"],
    "dialectically": [],
    "dialectician": ["logician", "logistician"],
    "dialectics": ["principle", "rationale"],
    "dialectology": ["linguistics", "philology"],
    "dialeurodes": ["arthropod genus", "genus dialeurodes"],
    "dialog box": ["panel", "window"],
    "dialogue": ["dialog", "duologue", "talk", "talking"],
    "dialyse": ["dialyze", "separate"],
    "dialysis": ["apheresis", "chemical analysis", "haemodialysis", "hemodialysis", "pheresis", "qualitative analysis"],
    "dialyzer": ["artificial kidney", "dialysis machine", "hemodialyzer", "medical instrument"],
    "diamagnet": ["material", "stuff"],
    "diamagnetic": [],
    "diamagnetism": ["magnetic attraction", "magnetic force", "magnetism"],
    "diamante": ["cloth", "fabric", "material", "textile"],
    "diamantine": [],
    "diameter": ["straight line"],
    "diametral": ["diametric", "diametrical"],
    "diametric": ["diametrical", "opposite", "polar"],
    "diametrically": [],
    "diamine": ["organic compound"],
    "diamond": ["adamant", "atomic number 6", "black diamond", "c", "carbon", "carbonado", "transparent gem"],
    "diamond jubilee": ["jubilee"],
    "diamond point": ["point"],
    "diamond wedding anniversary": ["diamond wedding", "wedding anniversary"],
    "diamondback": ["crotalus adamanteus", "diamondback rattlesnake", "rattler", "rattlesnake"],
    "diamondback terrapin": ["malaclemys centrata", "terrapin"],
    "diana": ["lady diana frances spencer", "princess diana", "princess of wales"],
    "diane de poitiers": ["duchesse de valentinois"],
    "dianoetic": ["discursive"],
    "dianthus": ["caryophylloid dicot genus", "genus dianthus"],
    "diapason": ["diapason stop", "organ stop"],
    "diapedesis": ["organic phenomenon"],
    "diapensia": ["subshrub", "suffrutex"],
    "diapensiaceae": ["diapensia family", "dilleniid dicot family", "family diapensiaceae"],
    "diapensiales": ["order diapensiales", "plant order"],
    "diaper": ["cloth", "fabric", "material", "textile"],
    "diaper rash": ["dermatitis", "diaper dermatitis"],
    "diaphanous": ["cobwebby", "filmy", "gauze-like", "gauzy", "gossamer", "see-through", "sheer", "transparent", "vaporous", "vapourous"],
    "diapheromera": ["diapheromera femorata", "stick insect", "walking stick", "walkingstick"],
    "diaphone": ["foghorn"],
    "diaphoretic": ["medicament", "medication", "medicinal drug", "medicine"],
    "diaphragm": ["membrane", "midriff", "muscle system", "muscular structure", "musculature", "tissue layer"],
    "diaphyseal": ["diaphysial"],
    "diaphysis": ["long bone", "os longum", "shaft"],
    "diapir": ["formation", "geological formation"],
    "diapsid": ["archosaur", "archosaurian", "archosaurian reptile", "crocodilian", "crocodilian reptile", "diapsid reptile", "ophidian", "reptile", "reptilian", "saurian", "serpent", "snake", "sphenodon punctatum", "tuatara"],
    "diapsida": ["reptile", "reptilian", "subclass diapsida"],
    "diarchy": ["dyarchy", "form of government", "political system"],
    "diarist": ["diary keeper", "journalist", "writer"],
    "diarrhea": ["diarrhoea", "looseness", "looseness of the bowels", "montezuma's revenge", "symptom", "the shits", "the trots"],
    "diarrheal": ["diarrheic", "diarrhetic", "diarrhoeal", "diarrhoeic", "diarrhoetic"],
    "diary": ["blog", "journal", "piece of writing", "web log", "writing", "written material"],
    "dias": ["bartholomeu dias", "bartholomeu diaz", "diaz"],
    "diaspididae": ["arthropod family", "family diaspididae"],
    "diaspora": ["body"],
    "diastasis": ["dislocation"],
    "diastema": ["gap", "opening"],
    "diastole": ["beat", "heartbeat", "pulsation", "pulse"],
    "diastolic": [],
    "diastolic pressure": ["blood pressure"],
    "diastrophism": ["geologic process", "geological process"],
    "diathermy": ["modality"],
    "diathermy machine": ["medical instrument", "microwave diathermy machine", "shortwave diathermy machine"],
    "diathesis": ["predisposition", "sensitivity"],
    "diatom": ["alga", "algae", "phytoplankton"],
    "diatomaceous earth": ["diatomite", "earth", "filter", "ground", "kieselguhr"],
    "diatomic": [],
    "diatonic": [],
    "diatonic scale": ["mode", "musical mode", "musical scale", "scale"],
    "diazepam": ["benzodiazepine", "valium"],
    "diazo": [],
    "diazonium": ["cation"],
    "diazotize": ["convert"],
    "diazoxide": ["hyperstat", "vasodilative", "vasodilator"],
    "dibasic acid": ["acid"],
    "dibasic salt": ["salt"],
    "dibble": ["plant", "set"],
    "dibranchiata": ["class", "dibranchia", "subclass dibranchia", "subclass dibranchiata"],
    "dibranchiate": ["cephalopod", "cephalopod mollusk", "dibranch", "dibranchiate mollusk"],
    "dibs": ["claim"],
    "dibucaine": ["intravenous anesthetic"],
    "dicamptodon": ["dicamptodontid", "salamander"],
    "dicamptodontidae": ["amphibian family", "family dicamptodontidae"],
    "dicarboxylic": [],
    "dice": ["gamble"],
    "dice cup": ["container", "dice box"],
    "dicentra": ["dilleniid dicot genus", "genus dicentra"],
    "dicer": ["mechanical device"],
    "diceros": ["genus diceros", "mammal genus"],
    "dichloride": ["bichloride", "chloride"],
    "dichlorodiphenyltrichloroethane": ["ddt", "insect powder", "insecticide", "pollutant"],
    "dichondra": ["dichondra micrantha", "vine"],
    "dichotomization": ["dichotomisation", "division"],
    "dichotomize": ["assort", "class", "classify", "dichotomise", "separate", "sort", "sort out"],
    "dichotomous": [],
    "dichotomously": [],
    "dichotomy": ["categorisation", "categorization", "classification", "duality"],
    "dichroism": ["pleochroism"],
    "dichromacy": ["color blindness", "color vision deficiency", "colour blindness", "colour vision deficiency", "dichromasy", "dichromatism", "dichromatopsia", "dichromia", "red-green color blindness", "red-green colour blindness", "red-green dichromacy", "yellow-blue color blindness", "yellow-blue dichromacy"],
    "dichromat": ["color-blind person", "uniocular dichromat"],
    "dichromatic": [],
    "dichromic acid": ["acid"],
    "dick": ["detective", "gumshoe", "hawkshaw", "investigator", "police detective", "tec"],
    "dick test": ["skin test"],
    "dickens": ["charles dickens", "charles john huffam dickens"],
    "dickensian": [],
    "dicker": ["bargain", "chaffer", "haggle", "higgle", "huckster", "negociate", "negotiate", "talk terms"],
    "dickey": ["backseat", "dickey-seat", "dickie", "dickie-seat", "dicky", "dicky-seat"],
    "dickeybird": ["bird", "dickey-bird", "dicky-bird", "dickybird"],
    "dickinson": ["emily dickinson"],
    "dicksonia": ["fern genus", "genus dicksonia"],
    "dicksoniaceae": ["family dicksoniaceae", "fern family"],
    "dicky": ["dickey"],
    "diclinous": [],
    "diclofenac potassium": ["cataflam", "nonsteroidal anti-inflammatory", "nonsteroidal anti-inflammatory drug", "nsaid"],
    "diclofenac sodium": ["nonsteroidal anti-inflammatory", "nonsteroidal anti-inflammatory drug", "nsaid", "voltaren"],
    "dicloxacillin": ["antibacterial", "antibacterial drug", "bactericide", "dynapen"],
    "dicot": ["acerola", "angiosperm", "barbados cherry", "cyrilla family", "cyrilliaceae", "dicotyledon", "exogen", "family cyrilliaceae", "flowering plant", "jiqui", "magnoliopsid", "malpighia glabra", "malpighia obovata", "surinam cherry", "titi family", "west indian cherry"],
    "dicot family": ["aceraceae", "amygdalaceae", "anacardiaceae", "apocynaceae", "aquifoliaceae", "aristolochiaceae", "asclepiadaceae", "asterid dicot family", "birthwort family", "bladdernut family", "box family", "broomrape family", "buckbean family", "buckthorn family", "buckwheat family", "buxaceae", "cannabidaceae", "caryophylloid dicot family", "casuarinaceae", "cecropiaceae", "celastraceae", "chloranthaceae", "combretaceae", "combretum family", "convolvulaceae", "corkwood family", "crowberry family", "cucurbitaceae", "daphne family", "dilleniid dicot family", "dogbane family", "droseraceae", "ebenaceae", "ebony family", "elaeagnaceae", "elm family", "empetraceae", "family", "family aceraceae", "family amygdalaceae", "family anacardiaceae", "family apocynaceae", "family aquifoliaceae", "family aristolochiaceae", "family asclepiadaceae", "family buxaceae", "family cannabidaceae", "family casuarinaceae", "family cecropiaceae", "family celastraceae", "family chloranthaceae", "family combretaceae", "family convolvulaceae", "family cucurbitaceae", "family droseraceae", "family ebenaceae", "family elaeagnaceae", "family empetraceae", "family gentianaceae", "family goodeniaceae", "family haloragaceae", "family haloragidaceae", "family hippocastanaceae", "family hydnoraceae", "family juglandaceae", "family lecythidaceae", "family leitneriaceae", "family linaceae", "family lobeliaceae", "family loganiaceae", "family lythraceae", "family menyanthaceae", "family moraceae", "family myricaceae", "family myrsinaceae", "family myrtaceae", "family nepenthaceae", "family nyssaceae", "family oleaceae", "family orobanchaceae", "family piperaceae", "family plantaginaceae", "family plumbaginaceae", "family polygonaceae", "family primulaceae", "family proteaceae", "family punicaceae", "family rafflesiaceae", "family rhamnaceae", "family rhizophoraceae", "family roridulaceae", "family salvadoraceae", "family sapindaceae", "family sapotaceae", "family sarraceniaceae", "family saururaceae", "family staphylaceae", "family styracaceae", "family symplocaceae", "family theophrastaceae", "family thymelaeaceae", "family trapaceae", "family ulmaceae", "family urticaceae", "family vitaceae", "flax family", "gentian family", "gentianaceae", "goodenia family", "goodeniaceae", "gourd family", "grapevine family", "haloragaceae", "haloragidaceae", "hamamelid dicot family", "hemp family", "hippocastanaceae", "holly family", "horse-chestnut family", "hydnoraceae", "juglandaceae", "leadwort family", "lecythidaceae", "leitneriaceae", "linaceae", "lizard's-tail family", "lobelia family", "lobeliaceae", "loganiaceae", "loosestrife family", "lythraceae", "magnoliid dicot family", "magnoliopsid family", "mangrove family", "maple family", "menyanthaceae", "milkweed family", "moraceae", "morning-glory family", "mulberry family", "myricaceae", "myrsinaceae", "myrsine family", "myrtaceae", "myrtle family", "nepenthaceae", "nettle family", "nyssaceae", "oleaceae", "oleaster family", "olive family", "orobanchaceae", "pepper family", "piperaceae", "pitcher-plant family", "plantaginaceae", "plantain family", "plumbaginaceae", "polygonaceae", "primrose family", "primulaceae", "protea family", "proteaceae", "punicaceae", "rafflesiaceae", "rhamnaceae", "rhizophoraceae", "roridulaceae", "rosid dicot family", "salvadora family", "salvadoraceae", "sapindaceae", "sapodilla family", "sapotaceae", "sarraceniaceae", "saururaceae", "sea-lavender family", "soapberry family", "sour-gum family", "spindle-tree family", "staff-tree family", "staphylaceae", "storax family", "styracaceae", "styrax family", "sumac family", "sundew family", "sweetleaf family", "symplocaceae", "theophrastaceae", "thymelaeaceae", "trapaceae", "tupelo family", "ulmaceae", "urticaceae", "vitaceae", "vitidaceae", "walnut family", "water-milfoil family", "wax-myrtle family"],
    "dicot genus": ["acer", "achras", "acocanthera", "acokanthera", "adenium", "aesculus", "aldrovanda", "alstonia", "amsonia", "anacardium", "anagallis", "anemopsis", "apocynum", "araujia", "ardisia", "argyreia", "aristolochia", "armeria", "artocarpus", "asarum", "asclepias", "asterid dicot genus", "astronium", "bartle frere", "beaumontia", "bertholletia", "blighia", "boehmeria", "broussonetia", "bumelia", "buxus", "calocarpum", "calystegia", "cardiospermum", "carya", "caryophylloid dicot genus", "catharanthus", "cecropia", "celastrus", "celtis", "centaurium", "centunculus", "chionanthus", "chloranthus", "chrysophyllum", "citrullus", "clethra", "cliftonia", "colubrina", "comptonia", "conocarpus", "conospermum", "cordia", "cotinus", "cucumis", "cucurbita", "cuscuta", "darlingtonia", "dilleniid dicot genus", "dimocarpus", "dionaea", "diospyros", "dipladenia", "dipteronia", "dirca", "dodonaea", "drosera", "drosophyllum", "ecballium", "elaeagnus", "embothrium", "empetrum", "eugenia", "euonymus", "eustoma", "exacum", "fagopyrum", "ficus", "frasera", "fraxinus", "gelsemium", "gentiana", "gentianella", "gentianopsis", "genus", "genus acer", "genus achras", "genus acocanthera", "genus acokanthera", "genus adenium", "genus aesculus", "genus aldrovanda", "genus allamanda", "genus alstonia", "genus amsonia", "genus anacardium", "genus anagallis", "genus anemopsis", "genus apocynum", "genus araujia", "genus ardisia", "genus argyreia", "genus aristolochia", "genus armeria", "genus artocarpus", "genus asarum", "genus asclepias", "genus astronium", "genus banksia", "genus bartle-frere", "genus beaumontia", "genus bertholletia", "genus blighia", "genus boehmeria", "genus broussonetia", "genus bryonia", "genus buddleia", "genus bumelia", "genus buxus", "genus calocarpum", "genus calystegia", "genus cannabis", "genus cardiospermum", "genus carissa", "genus carya", "genus casuarina", "genus catharanthus", "genus cecropia", "genus celastrus", "genus celtis", "genus centaurium", "genus centunculus", "genus chionanthus", "genus chloranthus", "genus chrysophyllum", "genus citrullus", "genus clethra", "genus cliftonia", "genus colubrina", "genus combretum", "genus comptonia", "genus conocarpus", "genus conospermum", "genus convolvulus", "genus cordia", "genus cotinus", "genus cucumis", "genus cucurbita", "genus cuscuta", "genus cyclamen", "genus cynancum", "genus cyrilla", "genus daphne", "genus darlingtonia", "genus dichondra", "genus dimocarpus", "genus dionaea", "genus diospyros", "genus dipladenia", "genus dipteronia", "genus dirca", "genus dodonaea", "genus drosera", "genus drosophyllum", "genus ecballium", "genus elaeagnus", "genus embothrium", "genus empetrum", "genus eriogonum", "genus eucalyptus", "genus eugenia", "genus euonymus", "genus eustoma", "genus exacum", "genus fagopyrum", "genus feijoa", "genus ficus", "genus forestiera", "genus forsythia", "genus frasera", "genus fraxinus", "genus fuchsia", "genus gelsemium", "genus gentiana", "genus gentianella", "genus gentianopsis", "genus glaux", "genus grevillea", "genus grias", "genus guevina", "genus hakea", "genus halenia", "genus halesia", "genus hamamelidanthum", "genus hamamelidoxylon", "genus hamamelites", "genus harpullia", "genus heliamphora", "genus helxine", "genus holarrhena", "genus hottonia", "genus houttuynia", "genus hoya", "genus humulus", "genus ilex", "genus ipomoea", "genus jacquinia", "genus jambos", "genus jasminum", "genus juglans", "genus knightia", "genus lagenaria", "genus lambertia", "genus laportea", "genus leitneria", "genus leucadendron", "genus ligustrum", "genus limonium", "genus litchi", "genus lobelia", "genus logania", "genus lomatia", "genus luffa", "genus lysimachia", "genus lythrum", "genus macadamia", "genus maclura", "genus malosma", "genus mandevilla", "genus mangifera", "genus manilkara", "genus melicocca", "genus melicoccus", "genus menyanthes", "genus momordica", "genus monardella", "genus morus", "genus myrciaria", "genus myrica", "genus myriophyllum", "genus myrsine", "genus myrtus", "genus nepenthes", "genus nephelium", "genus nerium", "genus nopalea", "genus nyssa", "genus oenothera", "genus olea", "genus orites", "genus osmanthus", "genus pachysandra", "genus palaquium", "genus paliurus", "genus parietaria", "genus parthenocissus", "genus payena", "genus peperomia", "genus periploca", "genus persoonia", "genus phillyrea", "genus pilea", "genus pimenta", "genus piper", "genus pipturus", "genus pistacia", "genus planera", "genus plantago", "genus plumbago", "genus plumeria", "genus polygonum", "genus pomaderris", "genus pouteria", "genus primula", "genus protea", "genus psidium", "genus pterocarya", "genus punica", "genus rauvolfia", "genus rauwolfia", "genus rhamnus", "genus rheum", "genus rhizophora", "genus rhodosphaera", "genus rhus", "genus roridula", "genus rumex", "genus sabbatia", "genus salvadora", "genus samolus", "genus sapindus", "genus sarcostemma", "genus sarracenia", "genus saururus", "genus schinus", "genus soleirolia", "genus spondias", "genus stapelia", "genus staphylea", "genus stenocarpus", "genus stephanotis", "genus strophanthus", "genus styrax", "genus swertia", "genus symplocus", "genus syringa", "genus syzygium", "genus tabernaemontana", "genus telopea", "genus thevetia", "genus toxicodendron", "genus trachelospermum", "genus trapa", "genus trema", "genus ulmus", "genus urtica", "genus vinca", "genus vincetoxicum", "genus vitis", "genus xylomelum", "genus ziziphus", "glaux", "goodenia", "green dinosaur", "grias", "guevina", "hakea", "halenia", "halesia", "hamamelid dicot genus", "hamamelidanthum", "hamamelidoxylon", "hamamelites", "heliamphora", "helxine", "holarrhena", "hottonia", "houttuynia", "humulus", "ilex", "ipomoea", "jacquinia", "jambos", "jasminum", "juglans", "knightia", "lagenaria", "lambertia", "laportea", "leitneria", "leucadendron", "ligustrum", "limonium", "logania", "lysimachia", "lythrum", "maclura", "magnoliid dicot genus", "magnoliopsid genus", "malosma", "mandevilla", "mangifera", "manilkara", "melicocca", "melicoccus", "menyanthes", "momordica", "monardella", "morus", "myrcia", "myrciaria", "myrica", "myriophyllum", "myrsine", "myrtus", "nepenthes", "nephelium", "nerium", "nopalea", "nyssa", "oenothera", "olea", "orites", "osmanthus", "palaquium", "paliurus", "parietaria", "parthenocissus", "payena", "periploca", "persoonia", "phillyrea", "pilea", "pimenta", "piper", "pipturus", "pistacia", "planera", "plantago", "plumeria", "plumiera", "polygonum", "pomaderris", "pouteria", "psidium", "pterocarya", "punica", "rhamnus", "rheum", "rhizophora", "rhodosphaera", "rhus", "rosid dicot genus", "rumex", "salvadora", "samolus", "sapindus", "sarcostemma", "sarracenia", "saururus", "schinus", "soleirolia", "spondias", "staphylea", "stenocarpus", "swertia", "symplocus", "syringa", "syzygium", "tabernaemontana", "telopea", "thevetia", "toxicodendron", "trachelospermum", "trapa", "trema", "ulmus", "urtica", "vinca", "vincetoxicum", "vitis", "xylomelum", "ziziphus"],
    "dicotyledones": ["class", "class dicotyledonae", "class dicotyledones", "class magnoliopsida", "dicotyledonae", "magnoliopsida"],
    "dicotyledonous": [],
    "dicranaceae": ["family dicranaceae", "moss family"],
    "dicranales": ["order dicranales", "plant order"],
    "dicranopteris": ["fern genus", "genus dicranopteris"],
    "dicranum": ["genus dicranum", "moss genus"],
    "dicrostonyx": ["genus dicrostonyx", "mammal genus"],
    "dictamnus": ["genus dictamnus", "rosid dicot genus"],
    "dictaphone": ["tape machine", "tape recorder"],
    "dictate": ["govern", "grind down", "rule", "tyrannise", "tyrannize"],
    "dictation": ["language", "oral communication", "speech", "speech communication", "spoken communication", "spoken language", "voice communication"],
    "dictator": ["speaker", "talker", "utterer", "verbaliser", "verbalizer"],
    "dictatorial": [],
    "dictatorially": ["autocratically", "magisterially"],
    "dictatorship": ["absolutism", "autarchy", "authoritarianism", "autocracy", "caesarism", "despotism", "monocracy", "one-man rule", "police state", "shogunate", "stalinism", "totalitarianism", "tyranny"],
    "dictionary": ["bilingual dictionary", "collegiate dictionary", "desk dictionary", "etymological dictionary", "gazetteer", "learner's dictionary", "lexicon", "little dictionary", "pocket dictionary", "school dictionary", "spell-checker", "spelling checker", "unabridged", "unabridged dictionary", "wordbook"],
    "dictionary definition": ["definition"],
    "dictostylium": ["cellular slime mold"],
    "dictyophera": ["fungus genus", "genus dictyophera"],
    "dictyoptera": ["animal order", "order dictyoptera"],
    "dictyopteran": [],
    "dictyopterous insect": ["cockroach", "insect", "mantid", "mantis", "roach"],
    "dicumarol": ["anticoagulant", "anticoagulant medication", "decoagulant", "dicoumarol"],
    "dicynodont": ["protomammal", "therapsid"],
    "dicynodontia": ["division", "division dicynodontia"],
    "didactic": ["didactical"],
    "didactically": ["pedagogically"],
    "didacticism": ["communication"],
    "didelphidae": ["family didelphidae", "mammal family"],
    "didelphis": ["genus didelphis", "mammal genus"],
    "dideoxycytosine": ["antiviral", "antiviral agent", "antiviral drug", "ddc", "zalcitabine"],
    "dideoxyinosine": ["antiviral", "antiviral agent", "antiviral drug", "ddi", "didanosine"],
    "diderot": ["denis diderot"],
    "didion": ["joan didion"],
    "dido": [],
    "die": ["endure", "suffer"],
    "die back": ["die down", "shrink", "shrivel", "shrivel up", "wither"],
    "die down": ["weaken"],
    "die out": ["die off", "disappear", "go away", "vanish"],
    "die-cast": [],
    "die-hard": ["rock-ribbed"],
    "dieback": ["plant disease"],
    "dieffenbachia": ["genus dieffenbachia", "liliopsid genus", "monocot genus"],
    "diegueno": ["hoka", "hokan"],
    "dielectric heating": ["electrical phenomenon"],
    "diemaker": ["artificer", "artisan", "craftsman", "die-sinker", "diesinker", "journeyman"],
    "dien bien phu": [],
    "diencephalon": ["betweenbrain", "interbrain", "neural structure", "thalmencephalon"],
    "diervilla": ["asterid dicot genus", "genus diervilla"],
    "dies irae": [],
    "diesel": ["rudolf christian karl diesel", "rudolf diesel"],
    "diesel locomotive": ["diesel-electric", "diesel-electric locomotive", "diesel-hydraulic", "diesel-hydraulic locomotive", "engine", "locomotive", "locomotive engine", "railway locomotive"],
    "diesel oil": ["derv", "diesel fuel", "fuel"],
    "diesel-electric locomotive": ["diesel locomotive", "diesel-electric"],
    "diesel-hydraulic locomotive": ["diesel locomotive", "diesel-hydraulic"],
    "diestock": ["device"],
    "diestrous": ["diestrual", "dioestrous", "dioestrual"],
    "diestrus": ["anestrum", "anestrus", "anoestrum", "anoestrus", "diestrum"],
    "diet": ["fast"],
    "dietary": ["fare"],
    "dietary supplement": ["diet", "vitamin pill"],
    "dieter": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "dietetics": ["bioscience", "life science", "macrobiotics"],
    "diethylaminoethyl cellulose": ["cellulose", "deae cellulose"],
    "diethylstilbesterol": ["des", "nonsteroid", "nonsteroidal", "stilbesterol"],
    "diethylstilbestrol": ["des", "diethylstilboestrol", "estrogen", "oestrogen", "stilbestrol", "stilboestrol"],
    "dietician": ["dietitian", "nutritionist", "specialiser", "specialist", "specializer"],
    "dietrich": ["maria magdalene von losch", "marlene dietrich"],
    "differ": ["contrast", "counterpoint", "depart", "deviate", "diverge", "vary"],
    "difference": ["change"],
    "difference threshold": ["difference limen", "differential limen", "differential threshold", "jnd", "just-noticeable difference", "limen", "threshold"],
    "different": [],
    "differentia": ["difference"],
    "differentiable": [],
    "differential": ["difference"],
    "differential analyzer": ["analog computer", "analogue computer"],
    "differential blood count": ["blood count"],
    "differential calculus": ["calculus", "infinitesimal calculus", "method of fluxions"],
    "differential diagnosis": ["medical diagnosis"],
    "differential equation": ["equation", "maxwell's equations", "partial differential equation", "schrodinger equation", "schrodinger wave equation", "wave equation"],
    "differential gear": ["bevel gear", "differential", "pinion and crown wheel", "pinion and ring gear"],
    "differential psychology": ["psychological science", "psychology"],
    "differentially": [],
    "differentiate": ["calculate", "cipher", "compute", "cypher", "figure", "reckon", "work out"],
    "differentiated": [],
    "differentiation": ["contradistinction", "contrast", "demarcation", "discrimination", "distinction", "dividing line", "hairsplitting", "line", "secernment", "word-splitting"],
    "differentiator": ["discriminator", "individual", "mortal", "person", "somebody", "someone", "soul"],
    "differently": ["other than", "otherwise"],
    "difficult": ["hard"],
    "difficulty": ["bitch", "condition", "fix", "hard time", "hole", "jam", "job", "kettle of fish", "mess", "mire", "muddle", "pickle", "pinch", "plight", "predicament", "problem", "quandary", "rattrap", "rough sledding", "situation", "status", "strain", "stress", "urinary hesitancy", "wall"],
    "diffidence": ["hesitance", "hesitancy", "self-distrust", "self-doubt", "timidity", "timidness", "timorousness", "unassertiveness"],
    "diffident": [],
    "diffidently": [],
    "difflugia": ["protozoan", "protozoon"],
    "diffract": ["part", "separate", "split"],
    "diffraction": ["optical phenomenon", "x-ray diffraction"],
    "diffraction grating": ["echelon", "grating", "optical device"],
    "diffuse": ["bleed", "creep", "distribute", "fan out", "mantle", "percolate", "run", "spread", "spread out"],
    "diffuse nebula": ["gaseous nebula", "hunter", "nebula", "orion"],
    "diffused": [],
    "diffusely": [],
    "diffuseness": ["scatter", "spread"],
    "diffuser": ["baffle", "baffle board", "diffusor"],
    "diffusing": ["diffusive", "dispersive", "disseminative"],
    "diffusion": ["action", "activity", "natural action", "natural process", "osmosis", "permeation", "pervasion", "suffusion", "transport"],
    "diflunisal": ["dolobid", "nonsteroidal anti-inflammatory", "nonsteroidal anti-inflammatory drug", "nsaid"],
    "dig": ["dig out", "dig up", "excavate", "unearth"],
    "dig out": ["disengage", "free"],
    "digest": ["predigest", "process", "stomach", "treat"],
    "digester": ["autoclave", "steriliser", "sterilizer"],
    "digestibility": ["digestibleness", "edibility", "edibleness"],
    "digestible": [],
    "digestion": ["chemical action", "chemical change", "chemical process"],
    "digestive": ["substance"],
    "digestive gland": ["duct gland", "exocrine", "exocrine gland"],
    "digestive juice": ["bile", "digestive fluid", "gall", "gastric acid", "gastric juice", "juice", "pancreatic juice", "succus"],
    "digestive system": ["gastrointestinal system", "system", "systema alimentarium", "systema digestorium"],
    "digger": ["ditch digger", "jack", "laborer", "labourer", "manual laborer", "mud digger", "trencher"],
    "digger wasp": ["cicada killer", "sphecius speciosis", "sphecoid", "sphecoid wasp"],
    "diggings": ["digs", "excavation"],
    "dighted": [],
    "digit": ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "ace", "binary digit", "captain hicks", "cinque", "cipher", "cypher", "decimal digit", "deuce", "deuce-ace", "duodecimal digit", "eight", "eighter", "eighter from decatur", "ennead", "figure", "fin", "five", "fivesome", "four", "foursome", "half a dozen", "heptad", "hexad", "hexadecimal digit", "i", "ii", "iii", "integer", "iv", "ix", "leash", "little joe", "little phoebe", "nina from carolina", "nine", "niner", "nought", "octad", "octal digit", "octet", "octonary", "ogdoad", "one", "pentad", "phoebe", "quadruplet", "quartet", "quatern", "quaternary", "quaternion", "quaternity", "quint", "quintet", "quintuplet", "septenary", "septet", "sestet", "seven", "sevener", "sextet", "sextuplet", "significant digit", "significant figure", "single", "sise", "six", "sixer", "tercet", "ternary", "ternion", "terzetto", "tetrad", "three", "threesome", "tierce", "trey", "triad", "trine", "trinity", "trio", "triplet", "troika", "two", "unity", "v", "vi", "vii", "viii", "whole number", "zero"],
    "digital": [],
    "digital arteries": ["arteria", "arteria digitalis", "arterial blood vessel", "artery"],
    "digital audiotape": ["audiotape", "dat"],
    "digital camera": ["camera", "photographic camera", "webcam"],
    "digital clock": ["clock"],
    "digital communication": ["asynchronous transfer mode", "atm", "data communication", "electronic communication"],
    "digital communications technology": ["communications technology"],
    "digital computer": ["bbs", "bulletin board", "bulletin board system", "computer", "computing device", "computing machine", "data processor", "electronic bulletin board", "electronic computer", "file server", "information processing system", "mainframe", "mainframe computer", "microcomputer", "minicomputer", "multiprocessor", "pc", "personal computer", "von neumann machine", "workstation"],
    "digital display": ["alphanumeric display", "display", "lcd", "liquid crystal display", "video display"],
    "digital photography": ["photography"],
    "digital plethysmograph": ["plethysmograph"],
    "digital subscriber line": ["dsl", "line", "phone line", "subscriber line", "telephone circuit", "telephone line"],
    "digital vein": ["vein", "vena", "vena digitalis", "venous blood vessel"],
    "digital voltmeter": ["electronic voltmeter"],
    "digital watch": ["ticker", "watch"],
    "digital-analog converter": ["data converter", "digital-to-analog converter"],
    "digitalis": ["cardiac glucoside", "cardiac glycoside", "digitalin", "digitalis glycoside", "digitoxin", "digoxin", "lanoxin"],
    "digitalization": ["digitalisation", "medical aid", "medical care"],
    "digitalize": ["administer", "dispense"],
    "digitally": [],
    "digitaria": ["genus digitaria", "liliopsid genus", "monocot genus"],
    "digitate": ["fingerlike"],
    "digitately": [],
    "digitigrade": [],
    "digitigrade mammal": ["digitigrade", "eutherian", "eutherian mammal", "placental", "placental mammal"],
    "digitization": ["conversion", "digitisation"],
    "digitize": ["alter", "change", "digitalise", "digitalize", "digitise", "modify"],
    "digitizer": ["analog-digital converter", "analog-to-digital converter", "data converter", "digitiser"],
    "digitoxin": ["digitalin", "digitalis", "digitalis glycoside"],
    "dignified": ["self-respectful", "self-respecting"],
    "dignify": ["elevate", "lift", "raise"],
    "dignifying": ["ennobling"],
    "dignity": ["position", "status"],
    "digoxin": ["digitalin", "digitalis", "digitalis glycoside", "lanoxin"],
    "digraph": ["alphabetic character", "digram", "letter", "letter of the alphabet"],
    "digress": ["divagate", "stray", "tell", "wander"],
    "digression": ["aside", "content", "divagation", "excursus", "message", "parenthesis", "subject matter", "substance"],
    "digressive": ["tangential"],
    "dihybrid": ["cross", "crossbreed", "hybrid"],
    "dihybrid cross": ["cross", "crossbreeding", "crossing", "hybridisation", "hybridization", "hybridizing", "interbreeding"],
    "dihydrostreptomycin": ["antibiotic", "antibiotic drug"],
    "dijon": [],
    "dik-dik": ["antelope"],
    "dika bread": ["food", "solid food"],
    "dika nut": ["edible seed"],
    "dike": ["close in", "dyke", "enclose", "inclose", "shut in"],
    "dilapidate": ["destroy", "destruct"],
    "dilapidation": ["decay", "ruin"],
    "dilatation": ["distension", "distention", "ectasia", "ectasis", "physical condition", "physiological condition", "physiological state", "tympanites", "varicocele"],
    "dilate": ["distend", "widen"],
    "dilation": ["discourse", "discussion", "treatment"],
    "dilation and curettage": ["d and c", "dilatation and curettage", "operation", "surgery", "surgical operation", "surgical procedure", "surgical process"],
    "dilator": ["body part"],
    "dilatoriness": ["deliberateness", "deliberation", "procrastination", "slowness", "unhurriedness"],
    "dilatory": ["laggard", "pokey", "poky"],
    "dilatory plea": ["plea"],
    "dildo": ["vibrator"],
    "dilemma": ["double bind", "perplexity", "quandary"],
    "dilettante": ["dilettanteish", "dilettantish", "sciolistic"],
    "diligence": ["assiduity", "assiduousness", "concentration", "determination", "industriousness", "industry", "purpose", "sedulity", "sedulousness", "studiousness"],
    "diligent": ["persevering"],
    "diligently": [],
    "dill": ["anethum graveolens", "herb", "herbaceous plant"],
    "dill pickle": ["pickle"],
    "dill seed": ["flavorer", "flavoring", "flavourer", "flavouring", "seasoner", "seasoning"],
    "dillenia": ["angiospermous tree", "flowering tree"],
    "dilleniaceae": ["dilleniid dicot family", "family dilleniaceae"],
    "dilleniid dicot family": ["actinidiaceae", "begonia family", "begoniaceae", "bombacaceae", "brassicaceae", "canella family", "canellaceae", "caper family", "capparidaceae", "caricaceae", "caryocaraceae", "cistaceae", "clethraceae", "clusiaceae", "cruciferae", "diapensia family", "diapensiaceae", "dicot family", "dilleniaceae", "dipterocarpaceae", "elaeocarpaceae", "elaeocarpus family", "epacridaceae", "epacris family", "ericaceae", "family actinidiaceae", "family begoniaceae", "family bombacaceae", "family brassicaceae", "family canellaceae", "family capparidaceae", "family caricaceae", "family caryocaraceae", "family cistaceae", "family clethraceae", "family clusiaceae", "family cruciferae", "family diapensiaceae", "family dilleniaceae", "family dipterocarpaceae", "family elaeocarpaceae", "family epacridaceae", "family ericaceae", "family flacourtiaceae", "family fouquieriaceae", "family fumariaceae", "family guttiferae", "family hypericaceae", "family lennoaceae", "family loasaceae", "family loranthaceae", "family malvaceae", "family monotropaceae", "family ochnaceae", "family papaveraceae", "family passifloraceae", "family pyrolaceae", "family resedaceae", "family santalaceae", "family sterculiaceae", "family tamaricaceae", "family theaceae", "family tiliaceae", "family violaceae", "family viscaceae", "flacourtia family", "flacourtiaceae", "fouquieriaceae", "fumariaceae", "fumitory family", "guttiferae", "heath family", "hypericaceae", "lennoaceae", "linden family", "loasa family", "loasaceae", "loranthaceae", "magnoliopsid family", "mallow family", "malvaceae", "mignonette family", "mistletoe family", "monotropaceae", "mustard family", "ochna family", "ochnaceae", "papaveraceae", "papaya family", "passifloraceae", "passionflower family", "poppy family", "pyrolaceae", "resedaceae", "rockrose family", "sandalwood family", "santalaceae", "st john's wort family", "sterculia family", "sterculiaceae", "tamaricaceae", "tamarisk family", "tea family", "theaceae", "tiliaceae", "violaceae", "violet family", "viscaceae", "white-alder family", "wintergreen family"],
    "dilleniid dicot genus": ["abelmoschus", "abutilon", "actinidia", "adansonia", "adlumia", "aethionema", "alcea", "alliaria", "alyssum", "anastatica", "arabidopsis", "arabis", "arceuthobium", "arctostaphylos", "aristotelia", "armoracia", "astroloma", "azaleastrum", "barbarea", "berteroa", "biscutella", "bombax", "brachychiton", "brassica", "bruckenthalia", "cakile", "callirhoe", "calluna", "calophyllum", "camelina", "capparis", "capsella", "cardamine", "carica", "caryocar", "cassiope", "ceiba", "chamaedaphne", "cheiranthus", "chelidonium", "chimaphila", "cistus", "cleome", "cochlearia", "cola", "comandra", "corchorus", "corydalis", "crambe", "crateva", "daboecia", "dendromecon", "dentaria", "descurainia", "dicentra", "dicot genus", "diplotaxis", "dovyalis", "durio", "elaeocarpus", "entelea", "epigaea", "eruca", "erysimum", "eschscholtzia", "eucarya", "false flax", "firmiana", "flacourtia", "fouquieria", "fremontia", "fremontodendron", "fumaria", "fusanus", "garcinia", "gaultheria", "gaylussacia", "genus abelmoschus", "genus abutilon", "genus actinidia", "genus adansonia", "genus adlumia", "genus aethionema", "genus alcea", "genus alliaria", "genus althaea", "genus alyssum", "genus anastatica", "genus andromeda", "genus arabidopsis", "genus arabis", "genus arbutus", "genus arceuthobium", "genus arctostaphylos", "genus argemone", "genus aristotelia", "genus armoracia", "genus astroloma", "genus barbarea", "genus begonia", "genus berteroa", "genus biscutella", "genus bocconia", "genus bombax", "genus brachychiton", "genus brassica", "genus bruckenthalia", "genus bryanthus", "genus buckleya", "genus cakile", "genus callirhoe", "genus calluna", "genus calophyllum", "genus camelina", "genus camellia", "genus canella", "genus capparis", "genus capsella", "genus cardamine", "genus carica", "genus caryocar", "genus cassiope", "genus ceiba", "genus chamaedaphne", "genus cheiranthus", "genus chelidonium", "genus chimaphila", "genus cistus", "genus cleome", "genus clusia", "genus cochlearia", "genus cola", "genus comandra", "genus corchorus", "genus corydalis", "genus crambe", "genus crateva", "genus daboecia", "genus dendromecon", "genus dentaria", "genus descurainia", "genus diapensia", "genus dicentra", "genus dillenia", "genus diplotaxis", "genus dombeya", "genus dovyalis", "genus draba", "genus durio", "genus elaeocarpus", "genus entelea", "genus epacris", "genus epigaea", "genus erica", "genus eruca", "genus erysimum", "genus eschscholtzia", "genus eucarya", "genus firmiana", "genus flacourtia", "genus fouquieria", "genus fremontia", "genus fremontodendron", "genus fumaria", "genus fusanus", "genus galax", "genus garcinia", "genus gaultheria", "genus gaylussacia", "genus glaucium", "genus gossypium", "genus grewia", "genus helianthemum", "genus helicteres", "genus heliophila", "genus heritiera", "genus hermannia", "genus hesperis", "genus hibbertia", "genus hibiscus", "genus hoheria", "genus hudsonia", "genus hugueninia", "genus hunnemania", "genus hybanthus", "genus hydnocarpus", "genus hymenanthera", "genus hypericum", "genus hypopitys", "genus iberis", "genus idesia", "genus iliamna", "genus isatis", "genus kalmia", "genus kiggelaria", "genus kosteletzya", "genus lavatera", "genus ledum", "genus leiophyllum", "genus lepidium", "genus lesquerella", "genus leucothoe", "genus loasa", "genus lobularia", "genus loiseleuria", "genus loranthus", "genus lunaria", "genus lyonia", "genus macleaya", "genus malacothamnus", "genus malcolmia", "genus malope", "genus malva", "genus malvastrum", "genus malvaviscus", "genus mammea", "genus matthiola", "genus meconopsis", "genus melicytus", "genus mentzelia", "genus menziesia", "genus mesua", "genus moneses", "genus monotropa", "genus montezuma", "genus muntingia", "genus myricaria", "genus napaea", "genus nasturtium", "genus nuytsia", "genus ochna", "genus ochroma", "genus orthilia", "genus oxydendrum", "genus papaver", "genus passiflora", "genus pavonia", "genus phoradendron", "genus phyllodoce", "genus physaria", "genus pieris", "genus plagianthus", "genus platystemon", "genus polanisia", "genus pritzelago", "genus pseudobombax", "genus pterospermum", "genus pyrola", "genus pyrularia", "genus pyxidanthera", "genus radyera", "genus raphanus", "genus reseda", "genus rhododendron", "genus richea", "genus romneya", "genus rorippa", "genus sanguinaria", "genus santalum", "genus sarcodes", "genus schizopetalon", "genus shorea", "genus shortia", "genus sida", "genus sidalcea", "genus sinapis", "genus sisymbrium", "genus sloanea", "genus sparmannia", "genus sphaeralcea", "genus stanleya", "genus stephanomeria", "genus sterculia", "genus stylomecon", "genus stylophorum", "genus styphelia", "genus subularia", "genus tamarix", "genus taraktagenos", "genus taraktogenos", "genus tarrietia", "genus terrietia", "genus theobroma", "genus thespesia", "genus thlaspi", "genus thysanocarpus", "genus tilia", "genus triplochiton", "genus turritis", "genus vaccinium", "genus vesicaria", "genus viola", "genus viscum", "genus xylosma", "glaucium", "gossypium", "grewia", "helicteres", "heritiera", "hermannia", "hesperis", "hibbertia", "hoheria", "hudsonia", "hugueninia", "hunnemannia", "hybanthus", "hydnocarpus", "hymenanthera", "hypericum", "hypopitys", "iberis", "iliamna", "isatis", "kiggelaria", "kosteletzya", "lavatera", "ledum", "leiophyllum", "lepidium", "lesquerella", "lobularia", "loiseleuria", "loranthus", "lunaria", "lyonia", "macleaya", "magnoliopsid genus", "malacothamnus", "malcolmia", "malva", "malvastrum", "malvaviscus", "mammea", "matthiola", "meconopsis", "melicytus", "mentzelia", "menziesia", "mesua", "moneses", "monotropa", "muntingia", "myricaria", "napaea", "nasturtium", "nuytsia", "ochna", "ochroma", "orthilia", "oxydendrum", "papaver", "passiflora", "phoradendron", "phyllodoce", "physaria", "pieris", "plagianthus", "platystemon", "polanisia", "pritzelago", "pseudobombax", "pterospermum", "pyrularia", "pyxidanthera", "radyera", "raphanus", "richea", "romneya", "rorippa", "sanguinaria", "santalum", "sarcodes", "shorea", "sida", "sidalcea", "sinapis", "sloanea", "sparmannia", "sphaeralcea", "stanleya", "stephanomeria", "stylomecon", "stylophorum", "styphelia", "subgenus azalea", "subgenus azaleastrum", "subularia", "tamarix", "taraktagenos", "taraktogenos", "tarrietia", "terrietia", "theobroma", "thespesia", "thlaspi", "thysanocarpus", "tilia", "triplochiton", "turritis", "vaccinium", "vesicaria", "viola", "viscum"],
    "dilleniidae": ["class", "subclass dilleniidae"],
    "diltiazem": ["calcium blocker", "calcium-channel blocker", "cardizem"],
    "dilutant": ["agent", "diluent", "thinner"],
    "dilute": ["cut", "reduce", "thin", "thin out", "water down", "weaken"],
    "diluted": ["dilute"],
    "dilution": ["solution"],
    "diluvian": ["diluvial"],
    "dim": ["change intensity", "dip"],
    "dim sum": ["cuisine", "culinary art"],
    "dim-sighted": ["near-blind", "purblind", "sand-blind", "visually challenged", "visually impaired"],
    "dim-witted": ["simple", "simple-minded"],
    "dimaggio": ["joe dimaggio", "joseph paul dimaggio"],
    "dimash": ["capital of syria", "damascus"],
    "dime": ["coin"],
    "dime bag": ["deck", "dime"],
    "dime novel": ["novel", "penny dreadful"],
    "dimenhydrinate": ["antiemetic", "antiemetic drug", "antihistamine", "dramamine"],
    "dimension": ["mark"],
    "dimensional": [],
    "dimensionality": ["flatness", "linearity", "one-dimensionality", "planeness", "spatial property", "spatiality", "third-dimensionality", "three-dimensionality", "two-dimensionality"],
    "dimensioning": [],
    "dimer": ["chemical compound", "compound"],
    "dimetapp": ["antihistamine", "nasal decongestant"],
    "dimethylglyoxime": ["precipitant"],
    "dimetrodon": ["synapsid", "synapsid reptile"],
    "diminish": ["belittle", "decrease", "lessen", "minify"],
    "diminished": ["lessened", "vitiated", "weakened"],
    "diminishing": [],
    "diminution": ["statement"],
    "diminutive": ["word"],
    "diminutiveness": ["littleness", "minuteness", "petiteness", "smallness", "tininess", "weeness"],
    "dimity": ["cloth", "fabric", "material", "textile"],
    "dimly": ["murkily"],
    "dimmed": ["dim"],
    "dimmer": ["rheostat", "variable resistor"],
    "dimness": ["duskiness", "semidarkness"],
    "dimocarpus": ["dicot genus", "genus dimocarpus", "magnoliopsid genus"],
    "dimorphic": ["dimorphous"],
    "dimorphism": ["pleomorphism", "polymorphism"],
    "dimorphotheca": ["asterid dicot genus", "genus dimorphotheca"],
    "dimple": ["mark"],
    "dimpled chad": ["chad", "dimple", "pregnant chad"],
    "dimwit": ["doofus", "half-wit", "nitwit", "simple", "simpleton"],
    "din": ["inculcate", "infuse", "instill"],
    "dine": ["eat"],
    "diner": ["carver", "cutter", "dining companion", "eater", "feeder", "tablemate"],
    "dinesen": ["baroness karen blixen", "blixen", "isak dinesen", "karen blixen"],
    "dinette": ["room"],
    "ding": ["dingdong", "dong", "peal", "ring"],
    "ding-dong": ["noise"],
    "dingbat": ["simple", "simpleton"],
    "dingdong": [],
    "dinge": ["batter", "change form", "change shape", "deform"],
    "dinghy": ["dory", "rowboat", "rowing boat", "small boat", "wherry"],
    "dingily": ["grubbily", "grungily"],
    "dinginess": ["dinge", "dirtiness", "uncleanness"],
    "dingo": ["canis dingo", "warragal", "warrigal", "wild dog"],
    "dining": ["dutch treat", "eating", "feeding"],
    "dining area": ["area"],
    "dining car": ["buffet car", "carriage", "coach", "diner", "dining compartment", "passenger car"],
    "dining room": ["dining-hall", "dining-room", "mess", "mess hall", "room", "triclinium"],
    "dining table": ["board", "dining-room table", "dinner table", "high table", "refectory table", "table", "triclinium"],
    "dining-hall": ["dining room", "dining-room", "refectory"],
    "dining-room attendant": ["busboy", "captain", "employee", "headwaiter", "maitre d'", "maitre d'hotel", "restaurant attendant", "server", "waiter", "waiter's assistant"],
    "dining-room furniture": ["article of furniture", "dining-room table", "furniture", "piece of furniture"],
    "dining-room table": ["board", "dining table", "dining-room furniture"],
    "diningroom suite": ["diningroom set", "suite"],
    "dink": ["couple", "match", "mates"],
    "dinka": ["nilotic", "nilotic language"],
    "dinky": ["dinkey", "engine", "locomotive", "locomotive engine", "railway locomotive"],
    "dinner": ["banquet", "beanfeast", "dinner party", "feast", "party"],
    "dinner bell": ["bell"],
    "dinner dress": ["dinner gown", "evening clothes", "evening dress", "evening gown", "eveningwear", "formal", "formalwear", "gown"],
    "dinner jacket": ["black tie", "evening clothes", "evening dress", "eveningwear", "formalwear", "tux", "tuxedo"],
    "dinner napkin": ["napkin", "serviette", "table napkin"],
    "dinner pail": ["bucket", "dinner bucket", "pail"],
    "dinner plate": ["plate"],
    "dinner service": ["dinner set", "service", "table service"],
    "dinner table": ["board", "dining table"],
    "dinner theater": ["dinner theatre", "house", "theater", "theatre"],
    "dinnertime": ["mealtime", "suppertime"],
    "dinnerware": ["tableware"],
    "dinoceras": ["dinocerate", "uintathere"],
    "dinocerata": ["animal order", "order dinocerata"],
    "dinocerate": ["dinoceras", "hoofed mammal", "uintathere", "ungulate"],
    "dinoflagellata": ["animal order", "cilioflagellata", "order cilioflagellata", "order dinoflagellata"],
    "dinoflagellate": ["flagellate", "flagellate protozoan", "flagellated protozoan", "mastigophoran", "mastigophore", "noctiluca", "noctiluca miliaris", "peridinian"],
    "dinornis": ["bird genus", "genus dinornis"],
    "dinornithidae": ["bird family", "family dinornithidae"],
    "dinornithiformes": ["animal order", "order dinornithiformes"],
    "dinosaur": ["archosaur", "archosaurian", "archosaurian reptile", "argentinosaur", "diplodocus", "ground-shaker", "iguanodon", "ornithischian", "ornithischian dinosaur", "saurischian", "saurischian dinosaur", "seismosaur", "titanosaur", "titanosaurian"],
    "dint": ["agency", "means", "way"],
    "diocesan": ["bishop"],
    "diocese": ["archdiocese", "bishopric", "eparchy", "episcopate", "exarchate", "jurisdiction"],
    "diocletian": ["gaius aurelius valerius diocletian"],
    "diode": ["electron tube", "rectifying tube", "rectifying valve", "thermionic tube", "thermionic vacuum tube", "thermionic valve", "tube", "vacuum tube"],
    "diodon": ["fish genus", "genus diodon"],
    "diodontidae": ["family diodontidae", "fish family"],
    "dioecious": ["dioecian"],
    "diogenes": [],
    "diol": ["alcohol", "dihydric alcohol", "glycol"],
    "diomedeidae": ["bird family", "family diomedeidae"],
    "dionaea": ["dicot genus", "genus dionaea", "magnoliopsid genus"],
    "dionysia": ["bacchanalia", "festival", "fete"],
    "dionysian": [],
    "dionysius": ["dionysius the elder"],
    "dionysus": [],
    "dioon": ["cycad"],
    "diophantus": [],
    "diopter": ["dioptre", "unit", "unit of measurement"],
    "dior": ["christian dior"],
    "diorite": ["igneous rock"],
    "dioscorea": ["genus dioscorea", "plant genus"],
    "dioscoreaceae": ["family dioscoreaceae", "plant family", "yam family"],
    "diospyros": ["dicot genus", "genus diospyros", "magnoliopsid genus"],
    "dioxide": ["carbon dioxide", "carbonic acid gas", "chlorine dioxide", "co2", "nitrogen dioxide", "oxide", "sulfur dioxide", "sulphur dioxide"],
    "dioxin": ["hydrocarbon"],
    "dip": ["draw", "draw off", "take out", "withdraw"],
    "dip into": ["read"],
    "dip solder": ["solder"],
    "dip switch": ["dual inline package switch", "on-off switch", "on/off switch", "toggle", "toggle switch"],
    "diphenhydramine": ["antihistamine", "benadryl"],
    "diphenylbutyl piperidine": ["antipsychotic", "antipsychotic agent", "antipsychotic drug", "major tranquilizer", "major tranquilliser", "major tranquillizer", "neuroleptic", "neuroleptic agent", "neuroleptic drug", "pimozide"],
    "diphenylhydantoin": ["dilantin", "hydantoin", "phenytoin"],
    "diphtheria": ["contagion", "contagious disease"],
    "diphthong": ["vowel", "vowel sound"],
    "diphthongize": ["break", "change", "diphthongise", "shift", "switch"],
    "diphylla": ["genus diphylla", "mammal genus"],
    "diplegia": ["palsy", "paralysis"],
    "diplococcus": ["bacteria", "bacterium", "diplococcus pneumoniae", "pneumococcus"],
    "diplodocus": ["dinosaur"],
    "diploic vein": ["vein", "vena", "vena diploica", "venous blood vessel"],
    "diploid": ["being", "organism"],
    "diploidy": ["condition"],
    "diploma": ["certificate", "certification", "credential", "credentials", "higher national diploma", "hnd", "sheepskin"],
    "diplomacy": ["dialogue", "diplomatic negotiations", "dollar diplomacy", "gunboat diplomacy", "negotiation", "power politics", "recognition", "shuttle diplomacy", "talks"],
    "diplomat": ["go-between", "intercessor", "intermediary", "intermediator", "mediator"],
    "diplomate": ["medical specialist", "specialist"],
    "diplomatic": [],
    "diplomatic building": ["consulate", "embassy", "government building"],
    "diplomatic immunity": ["exemption", "freedom"],
    "diplomatic mission": ["commission", "delegacy", "delegation", "deputation", "foreign mission", "legation", "mission"],
    "diplomatic pouch": ["mail pouch", "mailbag"],
    "diplomatic service": ["corps", "corps diplomatique", "diplomatic corps"],
    "diplomatically": [],
    "diplopia": ["double vision", "vision defect", "visual defect", "visual disorder", "visual impairment"],
    "diplopoda": ["class", "class diplopoda", "class myriapoda", "myriapoda"],
    "diplopterygium": ["fern genus", "genus diplopterygium"],
    "diplotaxis": ["dilleniid dicot genus", "genus diplotaxis"],
    "diplotene": ["phase", "stage"],
    "dipnoi": ["class", "subclass dipnoi"],
    "dipodidae": ["family dipodidae", "mammal family"],
    "dipodomys": ["genus dipodomys", "mammal genus"],
    "dipogon": ["genus dipogon", "rosid dicot genus"],
    "dipolar": [],
    "dipole": ["couple", "electric dipole", "electric doublet", "magnetic dipole"],
    "dipole molecule": ["molecule"],
    "dipole moment": ["electric dipole moment", "magnetic dipole moment", "moment"],
    "dipped": ["lordotic", "swayback", "swaybacked"],
    "dipper": ["ladle"],
    "dipsacaceae": ["asterid dicot family", "family dipsacaceae"],
    "dipsacus": ["asterid dicot genus", "genus dipsacus"],
    "dipsomania": ["alcoholism", "cacoethes", "mania", "passion", "potomania"],
    "dipsosaurus": ["genus dipsosaurus", "reptile genus"],
    "dipstick": ["gage", "gauge"],
    "diptera": ["animal order", "order diptera"],
    "dipterocarp": ["red lauan", "red lauan tree", "shorea teysmanniana", "tree"],
    "dipterocarpaceae": ["dilleniid dicot family", "family dipterocarpaceae"],
    "dipteronia": ["dicot genus", "genus dipteronia", "magnoliopsid genus"],
    "dipterous": [],
    "dipterous insect": ["bee killer", "crane fly", "daddy longlegs", "dipteran", "dipteron", "fly", "fruit fly", "fungus gnat", "gall gnat", "gall midge", "gallfly", "gnat", "hippoboscid", "insect", "louse fly", "mosquito", "pomace fly", "robber fly", "sciara", "sciarid", "two-winged insects"],
    "diptych": ["art", "fine art"],
    "dipus": ["genus dipus", "mammal genus"],
    "dipylon": [],
    "dipylon gate": ["dipylon"],
    "dirac": ["paul adrien maurice dirac"],
    "dirca": ["dicot genus", "genus dirca", "magnoliopsid genus"],
    "direct": ["administer", "care", "deal", "give", "guide", "handle", "have", "head", "hold", "lead", "make", "manage", "operate", "run", "steer", "throw"],
    "direct action": ["civil disobedience", "dissent", "job action", "nonviolence", "nonviolent resistance", "objection", "passive resistance", "protest", "recusancy"],
    "direct antonym": ["antonym", "opposite", "opposite word"],
    "direct current": ["dc", "direct electric current", "electrical energy", "electricity"],
    "direct discourse": ["account", "direct quotation", "report"],
    "direct dye": ["dye", "dyestuff", "substantive dye"],
    "direct evidence": ["evidence"],
    "direct examination": ["examination", "interrogation", "interrogatory"],
    "direct fire": ["fire", "firing"],
    "direct flight": ["flight"],
    "direct loan": ["loan"],
    "direct mail": ["ad", "advert", "advertisement", "advertising", "advertizement", "advertizing"],
    "direct mailer": ["distributor"],
    "direct marketing": ["marketing"],
    "direct object": ["object", "object of the verb"],
    "direct primary": ["closed primary", "open primary", "primary", "primary election"],
    "direct sum": ["join", "sum", "union"],
    "direct support": ["military mission", "mission"],
    "direct supporting fire": ["supporting fire"],
    "direct tax": ["revenue enhancement", "tax", "taxation"],
    "direct tide": ["high tide", "high water", "highwater"],
    "direct transmission": ["transmission mechanism"],
    "direct trust": ["express trust", "trust"],
    "direct-grant school": ["school"],
    "directed": [],
    "directed study": ["class", "course", "course of instruction", "course of study"],
    "directed verdict": ["finding of fact", "verdict"],
    "directing": ["directional", "directive", "guiding"],
    "direction": ["compass north", "compass point", "east", "frontage", "leeward", "magnetic north", "north", "northeast", "northwest", "opposition", "orientation", "point", "position", "seaward", "south", "southeast", "southwest", "spatial relation", "west", "windward"],
    "direction finder": ["goniometer", "radio compass", "receiver", "receiving system"],
    "directional": [],
    "directional antenna": ["aerial", "antenna", "array", "dish", "dish aerial", "dish antenna", "saucer", "transmitting aerial", "yagi", "yagi aerial"],
    "directional microphone": ["cardioid microphone", "microphone", "mike"],
    "directionality": ["spatial property", "spatiality"],
    "directive": ["dictum", "presidential directive", "pronouncement", "say-so"],
    "directivity": ["directiveness", "quality"],
    "directly": [],
    "directness": ["characteristic", "downrightness", "immediacy", "immediateness", "pointedness", "straightforwardness", "straightness"],
    "director": ["committee member"],
    "director of central intelligence": ["administrator", "dci", "executive"],
    "director-stockholder relation": ["fiduciary relation"],
    "directorate": ["board", "board of directors", "staggered board of directors"],
    "directorate for inter-services intelligence": ["inter-services intelligence", "international intelligence agency", "isi"],
    "directorship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "directory": ["list", "listing", "subdirectory"],
    "direfully": [],
    "dirge": ["coronach", "keen", "lament", "requiem", "song", "threnody", "vocal"],
    "diriment impediment": ["balk", "baulk", "check", "deterrent", "handicap", "hinderance", "hindrance", "impediment"],
    "dirk": ["dagger", "sticker"],
    "dirndl": ["gathered skirt"],
    "dirt": ["dirtiness", "filth", "grease", "grime", "grunge", "soil", "stain", "uncleanness"],
    "dirt cheap": [],
    "dirt track": ["racecourse", "racetrack", "raceway", "track"],
    "dirtily": [],
    "dirtiness": ["befoulment", "defilement", "dinge", "dinginess", "dirt", "dustiness", "feculence", "filth", "grease", "grime", "griminess", "grubbiness", "grunge", "pollution", "sanitary condition", "smuttiness", "soil", "sootiness", "sordidness", "squalidness", "squalor", "stain", "uncleanness"],
    "dirty": ["alter", "begrime", "bemire", "blemish", "change", "colly", "contaminate", "crock", "foul", "grime", "mire", "modify", "muck", "muck up", "mud", "muddy", "muddy up", "pollute", "slime", "smear", "soil", "splash", "spot"],
    "dirty bomb": ["a-bomb", "atom bomb", "atomic bomb", "fission bomb", "plutonium bomb"],
    "dirty joke": ["blue joke", "blue story", "dirty story", "gag", "jape", "jest", "joke", "laugh"],
    "dirty linen": ["affairs", "dirty laundry", "personal business", "personal matters"],
    "dirty old man": ["middle-aged man"],
    "dirty pool": ["behavior", "behaviour", "conduct", "doings"],
    "dirty trick": ["antic", "caper", "joke", "prank", "put-on", "trick"],
    "dirty tricks": ["behavior", "behaviour", "conduct", "doings"],
    "dirty war": ["offence", "offense", "offensive"],
    "dirty word": ["word"],
    "dirty-faced": [],
    "dirty-minded": [],
    "dis": ["orcus"],
    "disa": ["orchid", "orchidaceous plant"],
    "disability": ["amputation", "anorgasmia", "astasia", "bandy leg", "bandy legs", "bandyleg", "bow leg", "bow legs", "bowleg", "descensus", "disability of walking", "disablement", "disintegration", "dysomia", "dysphasia", "genu valgum", "genu varum", "handicap", "hearing disorder", "hearing impairment", "hypesthesia", "hypoesthesia", "impairment", "knock-knee", "pigeon toes", "prolapse", "prolapsus", "softness", "tibia valga", "tibia vara", "unfitness", "vision defect", "visual defect", "visual disorder", "visual impairment"],
    "disability benefit": ["benefit"],
    "disability check": ["disability payment", "regular payment"],
    "disability insurance": ["social insurance"],
    "disability of walking": ["abasia", "claudication", "disability", "disablement", "gameness", "gimp", "gimpiness", "handicap", "impairment", "lameness", "limping"],
    "disable": ["alter", "change", "confine", "disenable", "hold", "incapacitate", "lay up", "modify", "nobble", "pinion", "restrain"],
    "disabled": ["handicapped", "people", "the halt"],
    "disabling": ["disqualifying"],
    "disabuse": ["inform"],
    "disabused": ["undeceived"],
    "disaccharidase": ["enzyme", "invertase", "lactaid", "lactase", "saccharase", "sucrase"],
    "disaccharide": ["lactose", "malt sugar", "maltose", "milk sugar", "oligosaccharide", "saccharose", "sucrose"],
    "disadvantage": ["discriminate", "disfavor", "disfavour", "hamper", "handicap", "hinder", "prejudice", "separate", "single out"],
    "disadvantageous": [],
    "disaffected": ["ill-affected", "malcontent", "rebellious"],
    "disaffection": ["disloyalty"],
    "disagree": ["be", "disaccord", "discord"],
    "disagree with": ["hurt"],
    "disagreeable": [],
    "disagreeableness": ["abrasiveness", "acridity", "acridness", "pleasantness", "sweetness", "unpalatability", "unpalatableness"],
    "disagreeably": [],
    "disagreement": ["conflict", "dissension", "dissonance", "disunity", "divide"],
    "disambiguate": ["clarify", "clear up", "elucidate"],
    "disambiguation": ["clarification", "elucidation", "illumination", "lexical disambiguation"],
    "disambiguator": ["natural language processing application", "natural language processor"],
    "disappear": ["absent", "blow over", "desorb", "die", "die off", "die out", "evanesce", "fade", "fall", "fall away", "fall off", "fleet", "go", "go away", "pass", "pass off", "remove", "skip town", "take a powder", "vanish", "wither"],
    "disappearance": ["happening", "natural event", "occurrence", "occurrent"],
    "disappoint": ["baffle", "betray", "bilk", "come short", "cross", "disenchant", "disillusion", "fail", "fall short", "foil", "frustrate", "let down", "queer", "scotch", "spoil", "thwart"],
    "disappointedly": [],
    "disappointing": ["dissatisfactory", "unsatisfying"],
    "disappointingly": [],
    "disappointment": ["defeat", "dissatisfaction", "frustration", "letdown"],
    "disapprobation": ["animadversion", "censure", "condemnation", "demonisation", "demonization", "disapproval"],
    "disapproval": ["dislike"],
    "disapprove": ["deprecate", "deter", "discourage", "evaluate", "judge", "object", "pass judgment", "reject"],
    "disapproving": [],
    "disapprovingly": [],
    "disarm": ["convert", "convince", "win over"],
    "disarming": ["demobilisation", "demobilization", "disarmament"],
    "disarrange": ["dishevel", "displace", "mess up", "move", "muss", "ruffle", "ruffle up", "rumple", "tangle", "tousle", "tussle"],
    "disarranged": [],
    "disarray": ["disorderliness", "messiness", "untidiness"],
    "disarrayed": [],
    "disassemble": ["break apart", "break up", "destroy", "destruct", "dismantle", "take apart"],
    "disassociate": ["break", "break up", "disjoint", "dissociate", "disunite", "divorce", "part", "separate", "split", "split up"],
    "disassociation": ["separation"],
    "disassortative mating": ["conjugation", "coupling", "mating", "pairing", "sexual union", "union"],
    "disaster": ["destruction", "devastation"],
    "disaster area": ["area", "country"],
    "disastrously": [],
    "disavow": ["deny"],
    "disavowable": [],
    "disavowal": ["abjuration", "denial", "disclaimer", "recantation", "retraction"],
    "disband": ["break up", "dispel", "disperse", "dissipate", "scatter"],
    "disbandment": ["group action"],
    "disbar": ["disqualify"],
    "disbarment": ["banishment", "proscription"],
    "disbelieve": ["discredit", "distrust", "doubt", "mistrust", "reject", "suspect"],
    "disbeliever": ["atheist", "irreligionist", "materialist", "nonbeliever", "nonreligious person", "unbeliever"],
    "disbelieving": ["sceptical", "skeptical", "unbelieving"],
    "disbud": ["clip", "crop", "cut back", "dress", "lop", "prune", "snip", "trim"],
    "disburse": ["pay", "pay out"],
    "discalced": ["discalceate", "unshod"],
    "discard": ["abandon", "cast aside", "cast away", "cast out", "chuck out", "close out", "de-access", "deep-six", "dispose", "dump", "fling", "get rid of", "give it the deep six", "jettison", "junk", "liquidize", "put away", "remove", "retire", "scrap", "sell out", "sell up", "throw away", "throw out", "toss", "toss away", "toss out", "trash", "unlearn", "waste"],
    "discernability": ["distinctness", "legibility", "sharpness"],
    "discernible": [],
    "discerning": ["discreet"],
    "discernment": ["perception", "perceptiveness"],
    "discerp": ["cut", "lop", "sever"],
    "discharge": ["remove", "take", "take away", "withdraw"],
    "discharge lamp": ["lamp"],
    "discharge pipe": ["hydrant", "pipage", "pipe", "piping"],
    "discharged": ["dismissed", "fired", "laid-off", "pink-slipped"],
    "disciform": [],
    "discina": ["discina macrospora", "false morel"],
    "discina macrospora": ["discina"],
    "disciotis venosa": ["cup morel", "morel"],
    "disciple": ["absolutist", "adherent", "amoralist", "animist", "antinomian", "apostle", "aristotelean", "aristotelian", "arminian", "bahai", "clericalist", "diabolist", "donatist", "druse", "druze", "dualist", "follower", "hinayanist", "hussite", "ismaili", "ismailian", "jainist", "lamaist", "lutheran", "mahayanist", "mahdist", "manichaean", "manichean", "manichee", "mithraist", "monophysite", "neoplatonist", "peripatetic", "rasta", "rastafarian", "satanist", "shintoist", "sikh", "socinian", "tantrist", "tao", "taoist", "totalitarian", "trinitarian", "unitarian", "votary", "zen buddhist", "zoroastrian"],
    "discipleship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "disciplinary": [],
    "discipline": ["check", "condition", "develop", "make grow", "mortify", "train"],
    "disciplined": [],
    "disclaim": ["foreswear", "quit", "relinquish", "renounce"],
    "disclaimer": ["renunciation", "repudiation"],
    "disclose": ["bring out", "expose", "face", "reveal", "uncover", "unveil"],
    "disclosed": [],
    "disclosure": ["discovery", "display", "divulgement", "divulgence", "exposure", "giveaway", "informing", "leak", "news leak", "ratting", "revealing", "revelation", "singing", "speech act", "tattle", "telling"],
    "disco": ["dance", "trip the light fantastic", "trip the light fantastic toe"],
    "discocephali": ["animal order", "order discocephali"],
    "discoglossidae": ["amphibian family", "family discoglossidae"],
    "discography": ["catalog", "catalogue"],
    "discoid": ["disc-shaped", "disclike", "discoidal", "disk-shaped", "disklike"],
    "discoid lupus erythematosus": ["autoimmune disease", "autoimmune disorder", "dle", "lupus"],
    "discolor": ["change", "wash out"],
    "discoloration": ["change of color", "discolouration"],
    "discombobulated": ["disconcerted"],
    "discomfiture": ["anxiety", "discomposure", "disconcertion", "disconcertment", "embarrassment"],
    "discomfort": ["condition", "hangover", "incommodiousness", "inconvenience", "katzenjammer", "malaise", "status", "uncomfortableness", "unease", "uneasiness", "wretchedness"],
    "discomposed": [],
    "discomposure": ["disposition", "disquiet", "fluster", "perturbation", "temperament", "unease", "uneasiness"],
    "discomycete": ["aleuria aurantia", "ascomycete", "ascomycetous fungus", "blood cup", "caloscypha fulgens", "cup fungus", "fairy cup", "galiella rufa", "jafnea semitosta", "leotia lubrica", "mitrula elegans", "orange peel fungus", "peziza coccinea", "peziza domicilina", "sarcoscypha coccinea", "scarlet cup", "urn fungus", "urnula craterium"],
    "discomycetes": ["class", "subclass discomycetes"],
    "discomycetous": [],
    "disconcerting": ["upsetting"],
    "disconcertingly": [],
    "disconfirming": ["invalidating"],
    "disconnect": ["decouple", "detach", "disunite", "divide", "part", "separate", "uncouple"],
    "disconnected": ["disunited", "fragmented", "split"],
    "disconnection": ["disjunction", "separation"],
    "discontent": ["dissatisfy"],
    "discontented": ["discontent"],
    "discontentedly": [],
    "discontentment": ["discontent", "discontentedness", "disgruntlement", "dissatisfaction", "dysphoria", "hungriness", "longing", "yearning"],
    "discontinuance": ["conclusion", "discontinuation", "disfranchisement", "disinheritance", "dismount", "ending", "phase-out", "prorogation", "termination"],
    "discontinue": ["cease", "end", "expire", "finish", "fizzle", "fizzle out", "leave off", "peter out", "run out", "stop", "taper off", "terminate"],
    "discontinued": [],
    "discontinuity": ["separation"],
    "discontinuous": [],
    "discord": ["disorder", "strife"],
    "discordance": ["discord", "dissonance"],
    "discordant": ["disharmonious", "dissonant", "inharmonic"],
    "discordantly": ["unharmoniously"],
    "discorporate": ["bodiless", "disembodied", "unbodied", "unembodied"],
    "discount": ["allow", "mark down", "rebate"],
    "discount business": ["business", "business enterprise", "commercial enterprise"],
    "discount chain": ["chain"],
    "discount house": ["discount store", "discounter", "mercantile establishment", "outlet", "retail store", "sales outlet", "wholesale house"],
    "discount rate": ["interest rate", "rate of interest"],
    "discountenance": ["shame"],
    "discourage": ["cast down", "deject", "demoralise", "demoralize", "depress", "dishearten", "dismay", "dispirit", "get down", "intimidate", "pour cold water on", "put off", "restrain", "throw cold water on"],
    "discouraged": [],
    "discouragement": ["despair", "disheartenment", "dismay", "intimidation"],
    "discouraging": [],
    "discouragingly": [],
    "discourse": ["address", "cover", "deal", "descant", "discuss", "handle", "plow", "talk about", "talk shop", "treat"],
    "discourteous": ["ungracious"],
    "discourtesy": ["abruptness", "boorishness", "brusqueness", "cheekiness", "contempt", "crust", "curtness", "disrespect", "freshness", "gall", "gruffness", "impertinence", "impoliteness", "impudence", "incivility", "insolence", "manner", "personal manner", "rudeness", "shortness", "ungraciousness"],
    "discover": ["rediscover"],
    "discovered check": ["check"],
    "discovery": ["disclosure", "revealing", "revelation"],
    "discredit": ["belittle", "disgrace", "disparage", "pick at"],
    "discreditable": [],
    "discredited": ["damaged"],
    "discreet": [],
    "discreetly": [],
    "discrepancy": ["departure", "deviation", "difference", "divergence", "variance", "variant"],
    "discrepant": ["incompatible"],
    "discrete": ["distinct"],
    "discreteness": ["distinctness", "separateness", "separation", "severalty"],
    "discretion": ["liberty"],
    "discretionary": [],
    "discretionary trust": ["trust"],
    "discriminable": [],
    "discriminate": ["differentiate", "disadvantage", "disfavor", "disfavour", "distinguish", "hive off", "insulate", "isolate", "redline", "secern", "secernate", "segregate", "separate", "severalise", "severalize", "single out", "tell", "tell apart"],
    "discriminating": [],
    "discrimination": ["appreciation", "basic cognitive process", "differentiation", "discernment", "distinction", "individualisation", "individualization", "individuation", "perceptiveness", "secernment", "taste"],
    "discriminative": ["discriminatory"],
    "discriminative stimulus": ["cue", "input", "stimulant", "stimulation", "stimulus"],
    "discriminatory": ["invidious"],
    "discursively": ["ramblingly"],
    "discursiveness": ["indirectness"],
    "discus": ["field event"],
    "discussant": ["adducer", "participant"],
    "discussion": ["argument", "argumentation", "conference", "debate", "deliberation", "dialogue", "give-and-take", "group discussion", "language", "negotiation", "oral communication", "panel discussion", "post-mortem", "postmortem", "public discussion", "speech", "speech communication", "spoken communication", "spoken language", "talks", "ventilation", "voice communication", "word"],
    "disdainful": ["haughty", "imperious", "lordly", "overbearing", "prideful", "sniffy", "supercilious", "swaggering"],
    "disdainfully": ["cavalierly"],
    "disease": ["animal disease", "anthrax", "aspergillosis", "autoimmune disease", "autoimmune disorder", "blackwater", "boutonneuse fever", "cat scratch disease", "communicable disease", "complication", "congenital disease", "crud", "cystic breast disease", "cystic mastitis", "deficiency disease", "disease of the neuromuscular junction", "disease of the skin", "endemic", "endemic disease", "enteropathy", "exanthema subitum", "eye disease", "fibrocystic breast disease", "fibrocystic disease of the breast", "filariasis", "genetic abnormality", "genetic defect", "genetic disease", "genetic disorder", "goiter", "goitre", "hereditary condition", "hereditary disease", "illness", "incompetence", "indian tick fever", "industrial disease", "inflammatory disease", "inherited disease", "inherited disorder", "kawasaki disease", "kenya fever", "liver disease", "malady", "malignance", "malignancy", "marseilles fever", "meniere's disease", "milk sickness", "mimesis", "mucocutaneous lymph node syndrome", "occupational disease", "onychosis", "ozaena", "ozena", "pappataci fever", "periarteritis nodosa", "periodontal disease", "periodontitis", "phlebotomus", "plant disease", "polyarteritis nodosa", "pseudorubella", "pycnosis", "pyknosis", "respiratory disease", "respiratory disorder", "respiratory illness", "rheumatism", "roseola infantilis", "roseola infantum", "sandfly fever", "sickness", "skin disease", "skin disorder", "struma", "thyromegaly", "unwellness"],
    "disease of the neuromuscular junction": ["carcinomatous myopathy", "disease", "eaton-lambert syndrome", "lambert-eaton syndrome", "myasthenia", "myasthenia gravis", "myasthenic syndrome"],
    "diseased": ["morbid", "pathologic", "pathological"],
    "disembark": ["debark", "land", "set down"],
    "disembarrassment": ["easing", "moderation", "relief"]
}
