synonyms = {
    "oriental cherry": ["japanese cherry", "japanese flowering cherry", "prunus serrulata"],
    "oriental cockroach": ["asiatic cockroach", "blackbeetle", "blatta orientalis", "oriental roach"],
    "oriental plane": ["platanus orientalis"],
    "oriental poppy": ["papaver orientale"],
    "oriental scops owl": ["otus sunia"],
    "oriental spruce": ["picea orientalis"],
    "orientalism": ["oriental studies"],
    "orientalize": ["orientalise"],
    "orientation course": ["orientation"],
    "oriented": ["orientated"],
    "orienting": ["orientating"],
    "orifice": ["opening", "porta"],
    "origin": ["inception", "origination"],
    "original": ["archetype", "pilot"],
    "originate": ["arise", "develop", "grow", "rise", "spring up", "uprise"],
    "originator": ["conceiver", "mastermind"],
    "orinasal phone": ["orinasal"],
    "orinoco": ["orinoco river"],
    "oriolidae": ["family oriolidae"],
    "oriolus": ["genus oriolus"],
    "orion": ["hunter"],
    "orites": ["genus orites"],
    "orleans": ["siege of orleans"],
    "orlop deck": ["fourth deck", "orlop"],
    "ormandy": ["eugene ormandy"],
    "ormazd": ["ahura mazda", "ormuzd"],
    "ormer": ["haliotis tuberculata"],
    "ormosia": ["genus ormosia"],
    "ornamentation": ["embellishment"],
    "ornateness": ["elaborateness"],
    "ornithischia": ["order ornithischia"],
    "ornithischian": ["ornithischian dinosaur"],
    "ornithogalum": ["genus ornithogalum"],
    "ornithologist": ["bird watcher"],
    "ornithomimida": ["suborder ornithomimida"],
    "ornithopod": ["ornithopod dinosaur"],
    "ornithorhynchidae": ["family ornithorhynchidae"],
    "ornithorhynchus": ["genus ornithorhynchus"],
    "orobanchaceae": ["broomrape family", "family orobanchaceae"],
    "oroide": ["oreide"],
    "orology": ["orography"],
    "orontium": ["genus orontium"],
    "orotund": ["rotund", "round"],
    "orozco": ["jose clemente orozco", "jose orozco"],
    "orphanage": ["orphanhood"],
    "orphenadrine": ["norflex"],
    "orpine": ["livelong", "orpin", "sedum telephium"],
    "orr": ["bobby orr", "robert orr"],
    "orrisroot": ["orris"],
    "ortalis": ["genus ortalis"],
    "ortega": ["daniel ortega", "daniel ortega saavedra"],
    "ortega y gasset": ["jose ortega y gasset"],
    "orthicon": ["image orthicon"],
    "orthilia": ["genus orthilia"],
    "orthodontics": ["dental orthopaedics", "dental orthopedics", "orthodontia", "orthodonture"],
    "orthodox": ["eastern orthodox", "greek orthodox", "russian orthodox"],
    "orthodox church": ["eastern church", "eastern orthodox", "eastern orthodox church", "orthodox catholic church"],
    "orthodox judaism": ["jewish orthodoxy"],
    "orthodox sleep": ["nonrapid eye movement", "nonrapid eye movement sleep", "nrem", "nrem sleep"],
    "orthogonal": ["rectangular"],
    "orthogonality": ["orthogonal opposition", "perpendicularity"],
    "orthography": ["writing system"],
    "orthopedic": ["orthopaedic", "orthopedical"],
    "orthopedics": ["orthopaedics"],
    "orthopedist": ["orthopaedist"],
    "orthopristis": ["genus orthopristis"],
    "orthopter": ["ornithopter"],
    "orthoptera": ["order orthoptera"],
    "orthopterous insect": ["orthopteran", "orthopteron"],
    "orthostatic hypotension": ["postural hypotension"],
    "orthotomus": ["genus orthotomus"],
    "ortolan": ["emberiza hortulana", "ortolan bunting"],
    "orwell": ["eric arthur blair", "eric blair", "george orwell"],
    "orycteropodidae": ["family orycteropodidae"],
    "orycteropus": ["genus orycteropus"],
    "oryctolagus": ["genus oryctolagus"],
    "oryx": ["pasang"],
    "oryza": ["genus oryza"],
    "oryzomys": ["genus oryzomys"],
    "oryzopsis": ["genus oryzopsis"],
    "osage": ["osage river"],
    "osage orange": ["bow wood", "maclura pomifera", "mock orange"],
    "osborne": ["john james osborne", "john osborne"],
    "oscheocele": ["oscheocoele"],
    "oscillate": ["vibrate"],
    "oscillation": ["vibration"],
    "oscillatoriaceae": ["family oscillatoriaceae"],
    "oscillatory": ["oscillating"],
    "oscilloscope": ["cro", "scope"],
    "oscine": ["oscine bird"],
    "oscines": ["passeres", "suborder oscines", "suborder passeres"],
    "oscitancy": ["oscitance"],
    "oslo": ["capital of norway", "christiania"],
    "osman i": ["othman i"],
    "osmanthus": ["genus osmanthus"],
    "osmeridae": ["family osmeridae"],
    "osmerus": ["genus osmerus"],
    "osmiridium": ["iridosmine"],
    "osmium": ["os"],
    "osmundaceae": ["family osmundaceae"],
    "osprey": ["fish eagle", "fish hawk", "pandion haliaetus", "sea eagle"],
    "osseous": ["bony", "osteal"],
    "ossicle": ["bonelet", "ossiculum"],
    "ossicular": ["ossiculate"],
    "ossification": ["conformity"],
    "ostariophysi": ["order ostariophysi"],
    "osteichthyes": ["class osteichthyes"],
    "ostensible": ["ostensive"],
    "ostentation": ["fanfare", "flash"],
    "ostentatious": ["pretentious"],
    "ostentatiously": ["showily"],
    "osteoarthritis": ["degenerative arthritis", "degenerative joint disease"],
    "osteoglossidae": ["family osteoglossidae"],
    "osteoglossiformes": ["order osteoglossiformes"],
    "osteologist": ["osteologer"],
    "osteopath": ["osteopathist"],
    "osteopetrosis": ["marble bones disease"],
    "osteosarcoma": ["osteogenic sarcoma"],
    "osteostracan": ["cephalaspid"],
    "osteostraci": ["cephalaspida", "suborder cephalaspida", "suborder osteostraci"],
    "ostraciidae": ["family ostraciidae", "family ostraciontidae"],
    "ostracize": ["ostracise"],
    "ostracoda": ["subclass ostracoda"],
    "ostracodermi": ["order ostracodermi"],
    "ostrea": ["genus ostrea"],
    "ostreidae": ["family ostreidae"],
    "ostrich": ["struthio camelus"],
    "ostrich fern": ["fiddlehead", "matteuccia struthiopteris", "onoclea struthiopteris", "pteretis struthiopteris", "shuttlecock fern"],
    "ostrya": ["genus ostrya"],
    "ostryopsis": ["genus ostryopsis"],
    "ostwald": ["wilhelm ostwald"],
    "ostyak": ["khanty"],
    "oswald": ["lee harvey oswald"],
    "otaheite arrowroot": ["otaheite arrowroot starch"],
    "otaria": ["genus otaria"],
    "otariidae": ["family otariidae"],
    "otherness": ["distinctness", "separateness"],
    "otic": ["auricular"],
    "otic ganglion": ["otoganglion"],
    "otides": ["suborder otides"],
    "otididae": ["family otididae"],
    "otiose": ["pointless", "purposeless", "senseless", "superfluous", "wasted"],
    "otis": ["elisha graves otis"],
    "oto": ["otoe"],
    "otoscope": ["auriscope", "auroscope"],
    "ottawa": ["canadian capital", "capital of canada"],
    "otter shrew": ["potamogale", "potamogale velox"],
    "otterhound": ["otter hound"],
    "otto i": ["otho i", "otto the great"],
    "ottoman": ["osmanli", "ottoman turk"],
    "ottoman empire": ["turkish empire"],
    "otus": ["genus otus"],
    "ouachita": ["ouachita river"],
    "ouija": ["ouija board"],
    "ounce": ["troy ounce"],
    "ouranopithecus": ["genus ouranopithecus"],
    "ouranos": ["uranus"],
    "ouse": ["ouse river"],
    "oust": ["boot out", "drum out", "expel", "kick out", "throw out"],
    "ouster": ["ejector"],
    "out": ["come out"],
    "out of hand": ["beyond control"],
    "out of practice": ["rusty"],
    "out of sight": ["out of view"],
    "out of thin air": ["from nowhere", "out of nothing"],
    "out of true": ["untrue"],
    "out of wedlock": ["outside marriage"],
    "outaouais": ["ottawa", "ottawa river"],
    "outback": ["remote"],
    "outboard motor": ["outboard"],
    "outboard motorboat": ["outboard"],
    "outbound": ["outward"],
    "outbreak": ["eruption", "irruption"],
    "outburst": ["burst"],
    "outcast": ["castaway", "ishmael", "pariah"],
    "outcaste": ["casteless"],
    "outcrop": ["outcropping", "rock outcrop"],
    "outdated": ["superannuated"],
    "outdistance": ["distance", "outstrip"],
    "outdo": ["best", "outflank", "scoop", "trump"],
    "outdoor": ["outside"],
    "outdoor sport": ["field sport"],
    "outdoors": ["open", "open air"],
    "outer space": ["space"],
    "outermost": ["outmost"],
    "outerwear": ["overclothes"],
    "outfit": ["getup", "rig", "turnout"],
    "outflank": ["go around"],
    "outflow": ["effluence", "efflux"],
    "outgo": ["expenditure", "outlay", "spending"],
    "outgrowth": ["branch", "offset", "offshoot"],
    "outhouse": ["jakes", "privy"],
    "outlandishness": ["bizarreness", "weirdness"],
    "outlaw": ["criminalise", "criminalize", "illegalise", "illegalize"],
    "outline": ["lineation"],
    "outlive": ["outlast", "survive"],
    "outmaneuver": ["outmanoeuvre", "outsmart"],
    "outpoint": ["outscore"],
    "output": ["production", "yield"],
    "output signal": ["output"],
    "outrageously": ["atrociously"],
    "outrageousness": ["enormity"],
    "outright": ["unlimited"],
    "outrival": ["outvie"],
    "outshout": ["outcry"],
    "outside": ["exterior"],
    "outsider art": ["naive art", "primitive art", "vernacular art"],
    "outsize": ["outsized", "oversize", "oversized"],
    "outskirt": ["fringe"],
    "outspoken": ["vocal"],
    "outspread": ["spread"],
    "outstanding": ["owing", "undischarged"],
    "outstation": ["outpost"],
    "outward": ["outwards"],
    "outwardly": ["externally"],
    "outwardness": ["externality"],
    "outwit": ["beat", "circumvent", "outfox", "outsmart", "overreach"],
    "ovalipes": ["genus ovalipes"],
    "ovarian artery": ["arteria ovarica"],
    "ovarian vein": ["vena ovarica"],
    "ovation": ["standing ovation"],
    "oven stuffer": ["oven stuffer roaster"],
    "ovenbird": ["seiurus aurocapillus"],
    "over and over": ["again and again", "over and over again", "time and again", "time and time again"],
    "over the counter stock": ["otc stock", "unlisted stock"],
    "overabundance": ["overmuch", "overmuchness", "superabundance"],
    "overabundant": ["plethoric", "rife"],
    "overact": ["ham", "ham it up", "overplay"],
    "overage": ["overaged", "superannuated"],
    "overall": ["boilers suit", "boilersuit"],
    "overarch": ["arch over"],
    "overawe": ["cow"],
    "overbid": ["overcall"],
    "overcapitalization": ["overcapitalisation"],
    "overcapitalize": ["overcapitalise"],
    "overcast": ["cloud"],
    "overcharge": ["fleece", "gazump", "hook", "pluck", "plume", "rob", "soak", "surcharge"],
    "overcloud": ["cloud over", "cloud up"],
    "overcoat": ["overcoating"],
    "overcome": ["get over", "master", "subdue", "surmount"],
    "overcrop": ["overcultivate"],
    "overcup oak": ["quercus lyrata"],
    "overdo": ["exaggerate"],
    "overdraft credit": ["check overdraft credit"],
    "overdramatize": ["overdramatise"],
    "overdress": ["overclothe"],
    "overemotional": ["sloppy"],
    "overemphasize": ["overemphasise", "overstress"],
    "overestimate": ["overrate"],
    "overexploitation": ["overuse", "overutilisation", "overutilization"],
    "overflow": ["brim over", "overrun", "run over", "well over"],
    "overgarment": ["outer garment"],
    "overgeneralize": ["overgeneralise"],
    "overgrow": ["grow over"],
    "overhand": ["overarm", "overhanded"],
    "overhang": ["beetle"],
    "overhaul": ["modernise", "modernize"],
    "overhead": ["smash"],
    "overindulgence": ["excess"],
    "overladen": ["overloaded"],
    "overlap": ["convergence", "intersection"],
    "overlarge": ["too large"],
    "overlay": ["cover"],
    "overlie": ["overlay"],
    "overload": ["overcharge", "surcharge"],
    "overlooked": ["unmarked", "unnoted"],
    "overlord": ["lord", "master"],
    "overlying": ["superimposed"],
    "overmuch": ["too much"],
    "overnighter": ["overnight bag", "overnight case"],
    "overpass": ["flyover"],
    "overplus": ["embarrassment", "plethora", "superfluity"],
    "overpower": ["overmaster", "overwhelm"],
    "overpowering": ["overwhelming"],
    "overprint": ["print over"],
    "overproduction": ["overrun"],
    "overreaching": ["vaulting"],
    "overrefined": ["superfine"],
    "overriding": ["paramount", "predominant", "predominate", "preponderant", "preponderating"],
    "overrule": ["override", "overthrow", "overturn", "reverse"],
    "oversea": ["overseas"],
    "overseas": ["abroad"],
    "oversee": ["manage", "superintend", "supervise"],
    "overseer": ["superintendent"],
    "overshadow": ["dominate", "eclipse"],
    "oversight": ["inadvertence"],
    "oversimplification": ["simplism"],
    "overspecialize": ["overspecialise"],
    "overstate": ["amplify", "exaggerate", "hyperbolise", "hyperbolize", "magnify", "overdraw"],
    "overstay": ["outstay"],
    "overstrain": ["overextend"],
    "overt": ["open"],
    "overtake": ["catch", "catch up with"],
    "overthrow": ["bring down", "overturn", "subvert"],
    "overtime": ["extra time"],
    "overtire": ["overfatigue", "overweary"],
    "overtone": ["partial", "partial tone"],
    "overture": ["advance", "approach", "feeler"],
    "overturn": ["bowl over", "knock over", "tip over", "tump over", "turn over", "upset"],
    "overturned": ["upset", "upturned"],
    "overuse": ["overdrive"],
    "overvalue": ["overestimate"],
    "overweening": ["uppity"],
    "overwhelm": ["overcome", "overpower", "overtake", "sweep over", "whelm"],
    "overwhelmingly": ["irresistibly", "overpoweringly"],
    "overwork": ["exploit"],
    "ovibos": ["genus ovibos"],
    "ovid": ["publius ovidius naso"],
    "ovis": ["genus ovis"],
    "ovolo": ["quarter round", "thumb"],
    "ovulation method of family planning": ["ovulation method"],
    "ovum": ["egg cell"],
    "owen": ["robert owen"],
    "owens": ["james cleveland owens", "jesse owens"],
    "owl": ["bird of minerva", "bird of night", "hooter"],
    "own": ["have", "possess"],
    "owner": ["possessor"],
    "ox": ["wild ox"],
    "oxalacetate": ["oxaloacetate"],
    "oxalacetic acid": ["oxaloacetic acid"],
    "oxalic acid": ["ethanedioic acid"],
    "oxalidaceae": ["family oxalidaceae"],
    "oxalis": ["sorrel", "wood sorrel"],
    "oxandra": ["genus oxandra"],
    "oxaprozin": ["daypro"],
    "oxazepam": ["serax"],
    "oxeye daisy": ["chrysanthemum maximum", "leucanthemum maximum"],
    "oxford english dictionary": ["oed"],
    "oxford university": ["oxford"],
    "oxidant": ["oxidiser", "oxidizer", "oxidizing agent"],
    "oxidation": ["oxidisation", "oxidization"],
    "oxidation number": ["oxidation state"],
    "oxidise": ["oxidate", "oxidize"],
    "oxidize": ["oxidate", "oxidise"],
    "oxidized": ["oxidised"],
    "oxlip": ["paigle", "primula elatior"],
    "oxtongue": ["bitterweed", "bristly oxtongue", "bugloss", "picris echioides"],
    "oxyacid": ["oxygen acid"],
    "oxybelis": ["genus oxybelis"],
    "oxycephaly": ["acrocephaly"],
    "oxydendrum": ["genus oxydendrum"],
    "oxygenate": ["aerate", "oxygenise", "oxygenize"],
    "oxygenize": ["oxygenise"],
    "oxyhemoglobin": ["oxyhaemoglobin"],
    "oxylebius": ["genus oxylebius"],
    "oxyphenbutazone": ["tandearil"],
    "oxyphencyclimine": ["daricon"],
    "oxytetracycline": ["hydroxytetracycline", "oxytetracycline hydrochloride", "terramycin"],
    "oxytocic": ["oxytocic drug"],
    "oxytocin": ["pitocin"],
    "oxytropis": ["genus oxytropis"],
    "oxyura": ["genus oxyura"],
    "oxyuranus": ["genus oxyuranus"],
    "oxyuridae": ["family oxyuridae"],
    "oyster bed": ["oyster bank", "oyster park"],
    "oyster crab": ["pinnotheres ostreum"],
    "oyster fish": ["oysterfish"],
    "oyster mushroom": ["oyster agaric", "oyster fungus", "pleurotus ostreatus"],
    "oyster plant": ["vegetable oyster"],
    "oyster stuffing": ["oyster dressing"],
    "oystercatcher": ["oyster catcher"],
    "ozark chinkapin": ["castanea ozarkensis", "chinquapin", "ozark chinquapin"],
    "ozarks": ["ozark mountains", "ozark plateau"],
    "ozawa": ["seiji ozawa"],
    "ozena": ["ozaena"],
    "ozone layer": ["ozonosphere"],
    "ozonium": ["genus ozonium"],
    "ozonize": ["ozonise"],
    "ozothamnus": ["genus ozothamnus"],
    "paca": ["cuniculus paca"],
    "pace": ["step"],
    "pacemaker": ["cardiac pacemaker", "sa node", "sinoatrial node"],
    "pacer": ["pacemaker", "pacesetter"],
    "pacesetter": ["pacemaker"],
    "pachisi": ["parchesi", "parchisi"],
    "pachycephala": ["genus pachycephala"],
    "pachycephalosaur": ["pachycephalosaurus"],
    "pachydermatous": ["pachydermal", "pachydermic", "pachydermous"],
    "pachyrhizus": ["genus pachyrhizus"],
    "pacific": ["pacific ocean"],
    "pacific bottlenose dolphin": ["tursiops gilli"],
    "pacific cod": ["alaska cod", "gadus macrocephalus"],
    "pacific giant salamander": ["dicamptodon ensatus"],
    "pacific halibut": ["hippoglossus stenolepsis"],
    "pacific herring": ["clupea harengus pallasii"],
    "pacific ridley": ["lepidochelys olivacea", "olive ridley"],
    "pacific sardine": ["sardinops caerulea"],
    "pacific spiny dogfish": ["squalus suckleyi"],
    "pacific sturgeon": ["acipenser transmontanus", "sacramento sturgeon", "white sturgeon"],
    "pacific time": ["pacific standard time", "pst"],
    "pacific tree toad": ["hyla regilla"],
    "pacific tripletail": ["lobotes pacificus"],
    "pacific walrus": ["odobenus divergens"],
    "pacific yew": ["california yew", "taxus brevifolia", "western yew"],
    "pacification": ["mollification"],
    "pacifism": ["pacificism", "passivism"],
    "pacifist": ["disarmer", "pacificist"],
    "pacify": ["appease", "assuage", "conciliate", "gentle", "gruntle", "lenify", "mollify", "placate"],
    "pack": ["bundle", "compact", "wad"],
    "pack animal": ["sumpter"],
    "pack ice": ["ice pack"],
    "pack of cards": ["deck", "deck of cards"],
    "package": ["bundle", "packet", "parcel"],
    "package store": ["liquor store"],
    "package tour": ["package holiday"],
    "packaging company": ["packaging concern"],
    "packer": ["bagger", "boxer"],
    "packera": ["genus packera"],
    "packing": ["boxing"],
    "packing box": ["packing case"],
    "packing material": ["packing", "wadding"],
    "packinghouse": ["packing plant"],
    "packrat": ["bushytail woodrat", "neotoma cinerea", "pack rat", "trade rat"],
    "pad": ["fill out"],
    "padauk": ["amboyna", "padouk", "pterocarpus indicus"],
    "padda": ["genus padda"],
    "padding": ["cushioning"],
    "paddle": ["boat paddle"],
    "paddlefish": ["duckbill", "polyodon spathula"],
    "paddlewheel": ["paddle wheel"],
    "paddy": ["mick", "mickey"],
    "pademelon": ["paddymelon"],
    "paderewski": ["ignace jan paderewski", "ignace paderewski"],
    "padua": ["padova", "patavium"],
    "paean": ["pean"],
    "paeonia": ["genus paeonia"],
    "paeoniaceae": ["family paeoniaceae", "peony family"],
    "paganini": ["niccolo paganini"],
    "paganism": ["heathenism", "pagan religion"],
    "paganize": ["paganise"],
    "page": ["sir frederick handley page"],
    "pageant": ["pageantry"],
    "pagellus": ["genus pagellus"],
    "paget": ["sir james paget"],
    "pagination": ["folio", "page number", "paging"],
    "pago pago": ["pango pango"],
    "pagoda tree": ["plumeria acutifolia", "temple tree"],
    "pagophila": ["genus pagophila"],
    "pagophilus": ["genus pagophilus"],
    "pagrus": ["genus pagrus"],
    "paguridae": ["family paguridae"],
    "pagurus": ["genus pagurus"],
    "pahautea": ["libocedrus bidwillii", "mountain pine"],
    "pahlavi": ["mohammed reza pahlavi", "mohammed reza pahlevi", "pahlevi", "shah pahlavi"],
    "paige": ["leroy robert paige", "satchel paige"],
    "pail": ["pailful"],
    "paillasse": ["palliasse"],
    "pain": ["anguish", "hurt"],
    "paine": ["robert treat paine"],
    "painfully": ["sorely"],
    "painfulness": ["distressingness"],
    "painstakingly": ["fastidiously"],
    "paint": ["pigment"],
    "painted beauty": ["vanessa virginiensis"],
    "painted daisy": ["chrysanthemum coccineum", "pyrethrum", "tanacetum coccineum"],
    "painted greenling": ["convict fish", "convictfish", "oxylebius pictus"],
    "painted nettle": ["coleus blumei", "solenostemon blumei", "solenostemon scutellarioides"],
    "painted sandgrouse": ["pterocles indicus"],
    "painted tongue": ["salpiglossis sinuata"],
    "painted turtle": ["chrysemys picta", "painted terrapin", "painted tortoise"],
    "painting": ["picture"],
    "pair": ["couple", "pair off", "partner off"],
    "pair production": ["pair creation", "pair formation"],
    "paiute": ["piute"],
    "pajama": ["pyjama"],
    "pakistan": ["islamic republic of pakistan", "west pakistan"],
    "pakistani rupee": ["rupee"],
    "pal": ["chum up", "pal up"],
    "palace": ["castle"],
    "palaemon": ["genus palaemon"],
    "palaemonidae": ["family palaemonidae"],
    "palanquin": ["palankeen"],
    "palaquium": ["genus palaquium"],
    "palatability": ["palatableness"],
    "palatable": ["toothsome"],
    "palatal": ["palatine"],
    "palatalize": ["palatalise"],
    "palate": ["roof of the mouth"],
    "palatinate": ["pfalz"],
    "palatine": ["palsgrave"],
    "palatine artery": ["arteria palatina"],
    "palatine vein": ["vena palatina"],
    "palatopharyngoplasty": ["ppp", "uppp", "uvulopalatopharyngoplasty"],
    "palau": ["republic of palau", "tt"],
    "palaver": ["empty talk", "empty words", "hot air", "rhetoric"],
    "pale": ["blanch", "blench"],
    "pale violet": ["cream violet", "striped violet", "viola striata"],
    "pale yellow": ["straw", "wheat"],
    "paleacrita": ["genus paleacrita"],
    "paleencephalon": ["palaeencephalon", "paleoencephalon"],
    "paleness": ["blondness", "fairness"],
    "paleoanthropology": ["human palaeontology", "human paleontology", "palaeoanthropology"],
    "paleobiology": ["palaeobiology"],
    "paleobotany": ["palaeobotany"],
    "paleocene": ["paleocene epoch"],
    "paleoclimatology": ["palaeoclimatology"],
    "paleodendrology": ["palaeodendrology"],
    "paleoecology": ["palaeoecology"],
    "paleoethnography": ["palaeoethnography"],
    "paleogeography": ["palaeogeography"]
}
