synonyms = {
    "encyclia": ["genus encyclia", "liliopsid genus", "monocot genus"],
    "encyclical": ["encyclical letter", "letter", "missive"],
    "encyclopedia": ["book of facts", "book of knowledge", "cyclopaedia", "cyclopedia", "encyclopaedia", "reference", "reference book", "reference work"],
    "encyclopedic": ["encyclopaedic"],
    "encyclopedist": ["compiler", "encyclopaedist"],
    "encysted": [],
    "end": ["be", "close", "terminate"],
    "end man": ["corner man", "minstrel"],
    "end organ": ["end-plate", "endplate", "motor end plate", "organ", "osmoreceptor"],
    "end point": ["end", "endpoint", "terminal", "termination", "terminus"],
    "end product": ["body of work", "crop", "oeuvre", "output", "product", "production", "turning", "work"],
    "end run": ["run", "running", "running game", "running play", "sweep"],
    "end user": ["user"],
    "end-all": ["end", "goal"],
    "end-plate": ["end organ", "endplate", "motor end plate"],
    "end-rhymed": [],
    "end-stopped": [],
    "end-to-end": [],
    "endameba": ["ameba", "amoeba", "endamoeba histolytica"],
    "endamoeba": ["genus endamoeba", "protoctist genus"],
    "endamoeba histolytica": ["endameba"],
    "endamoebidae": ["family", "family endamoebidae"],
    "endanger": ["be", "exist", "imperil", "jeopardise", "jeopardize", "menace", "peril", "threaten"],
    "endangered": [],
    "endangered species": ["australian lungfish", "neoceratodus forsteri", "queensland lungfish", "species"],
    "endarterectomy": ["ablation", "cutting out", "excision", "extirpation"],
    "endarteritis": ["inflammation", "redness", "rubor"],
    "endear": ["delight", "please"],
    "endearment": ["benignity", "kindness"],
    "endeavor": ["assay", "attempt", "be at pains", "buck", "endeavour", "essay", "seek", "strive", "struggle", "take pains", "try"],
    "endecott": ["endicott", "john endecott", "john endicott"],
    "endemic": ["disease", "endemic disease"],
    "enderby land": [],
    "endergonic": [],
    "endermic": ["endermatic"],
    "endgame": ["end", "end game", "final stage", "last"],
    "ending": ["conclusion", "defeat", "demolition", "destruction", "end", "final result", "final stage", "finish", "foregone conclusion", "halt", "happening", "last", "licking", "matter of course", "natural event", "occurrence", "occurrent", "omega", "outcome", "result", "resultant", "stop", "termination", "triumph", "victory", "wipeout", "z"],
    "endive": ["cichorium endivia", "herb", "herbaceous plant", "witloof"],
    "endless": ["eternal", "interminable"],
    "endlessly": [],
    "endlessness": ["ceaselessness", "continuousness", "duration", "incessancy", "incessantness", "length"],
    "endocarditis": ["carditis", "subacute bacterial endocarditis"],
    "endocardium": ["serosa", "serous membrane"],
    "endocentric": [],
    "endocervicitis": ["inflammation", "redness", "rubor"],
    "endocranium": ["membrane", "tissue layer"],
    "endocrine": ["endocrinal"],
    "endocrine gland": ["adenohypophysis", "adrenal", "adrenal cortex", "adrenal gland", "adrenal medulla", "anterior pituitary", "anterior pituitary gland", "corpus luteum", "ductless gland", "endocrine", "epiphysis", "epiphysis cerebri", "gland", "gonad", "hypophysis", "islands of langerhans", "isles of langerhans", "islets of langerhans", "neurohypophysis", "parathyroid", "parathyroid gland", "pars anterior", "pars distilis", "pars intermedia", "pars nervosa", "pineal body", "pineal gland", "pituitary", "pituitary body", "pituitary gland", "posterior pituitary", "posterior pituitary gland", "prostate", "prostate gland", "secreter", "secretor", "secretory organ", "sex gland", "suprarenal gland", "thymus", "thymus gland", "thyroid", "thyroid gland"],
    "endocrine system": ["system"],
    "endocrinologist": ["medical specialist", "specialist"],
    "endocrinology": ["medical specialty", "medicine"],
    "endoderm": ["endoblast", "entoblast", "entoderm", "germ layer", "hypoblast"],
    "endodontic": [],
    "endodontics": ["dental medicine", "dentistry", "endodontia", "odontology"],
    "endodontist": ["dental practitioner", "dentist", "tooth doctor"],
    "endoergic": ["energy-absorbing"],
    "endoergic reaction": ["nuclear reaction"],
    "endogamous": ["endogamic"],
    "endogamy": ["inmarriage", "intermarriage", "marriage", "matrimony", "spousal relationship", "union", "wedlock"],
    "endogenic": ["endogenetic"],
    "endogenous": [],
    "endogenous depression": ["clinical depression", "depression", "depressive disorder"],
    "endogenously": [],
    "endogeny": ["geological phenomenon"],
    "endolymph": ["bodily fluid", "body fluid", "humor", "humour", "liquid body substance"],
    "endometrial": [],
    "endometrial carcinoma": ["carcinoma", "endometrial cancer"],
    "endometriosis": ["adenomyosis", "pathology"],
    "endometrium": ["mucosa", "mucous membrane"],
    "endomorph": ["individual", "mortal", "person", "pudge", "somebody", "someone", "soul"],
    "endomorphic": ["pyknic"],
    "endomorphy": ["body type", "pyknic type", "somatotype"],
    "endomycetales": ["fungus order", "order endomycetales"],
    "endoneurium": ["connective tissue"],
    "endonuclease": ["nuclease", "restriction endonuclease", "restriction enzyme", "restriction nuclease"],
    "endoparasite": ["endozoan", "entoparasite", "entozoan", "entozoon", "parasite"],
    "endoparasitic": [],
    "endoplasm": ["cytol", "cytoplasm"],
    "endorphin": ["beta endorphin", "enkephalin", "neurochemical", "peptide"],
    "endorse": ["co-sign", "cosign", "indorse", "sign", "visa"],
    "endorsement": ["blurb", "indorsement", "packaging", "promotion", "promotional material", "publicity"],
    "endorser": ["accommodation endorser", "indorser", "signatory", "signer"],
    "endoscope": ["arthroscope", "colonoscope", "culdoscope", "flexible sigmoidoscope", "gastroscope", "laparoscope", "medical instrument", "proctoscope", "sigmoidoscope"],
    "endoscopic": [],
    "endoscopy": ["celioscopy", "colonoscopy", "culdoscopy", "examination", "flexible sigmoidoscopy", "gastroscopy", "hysteroscopy", "proctoscopy", "scrutiny", "sigmoidoscopy"],
    "endoskeleton": ["frame", "skeletal system", "skeleton", "systema skeletale"],
    "endosperm": ["reproductive structure"],
    "endospore": ["spore"],
    "endospore-forming bacteria": ["eubacteria", "eubacterium", "true bacteria"],
    "endosteum": ["membrane", "tissue layer"],
    "endothelial": [],
    "endothelium": ["epithelial tissue", "epithelium"],
    "endothermic": ["endothermal", "heat-absorbing"],
    "endothermic reaction": ["chemical reaction", "reaction"],
    "endotoxin": ["toxin"],
    "endotracheal tube": ["catheter", "nasotracheal tube"],
    "endow": ["cover", "empower", "enable", "endue", "gift", "indue", "invest"],
    "endowed": [],
    "endowment": ["capital", "chantry", "endowment fund", "patrimony"],
    "endowment insurance": ["life assurance", "life insurance"],
    "endurance": ["long-sufferance", "long-suffering", "stamina", "staying power", "strength", "sufferance", "tolerance", "toughness"],
    "endurance riding": ["horseback riding", "riding"],
    "enduring": ["long-suffering"],
    "enduringly": [],
    "endways": ["endwise"],
    "enema": ["barium enema", "clyster", "colonic", "colonic irrigation", "irrigation"],
    "enemy": ["adversary", "antagonist", "besieger", "foe", "foeman", "opponent", "opposer", "opposition", "resister"],
    "energetic": ["gumptious", "industrious", "up-and-coming"],
    "energetically": [],
    "energid": ["body part", "protoplast"],
    "energizer": ["actor", "animator", "doer", "energiser", "vitaliser", "vitalizer", "worker"],
    "energizing": ["activating", "activation", "activity", "animation", "electrification", "invigoration", "vivification"],
    "energy": ["ch'i", "chi", "good health", "healthiness", "juice", "ki", "qi", "vim", "vitality"],
    "energy level": ["energy", "energy state", "free energy"],
    "enervate": ["weaken"],
    "enervation": ["weakness"],
    "enesco": ["george enescu", "georges enesco"],
    "enets": ["entsi", "entsy", "samoyed", "samoyedic", "yenisei", "yenisei-samoyed", "yeniseian"],
    "enfant terrible": ["nonconformist", "recusant"],
    "enfeeble": ["debilitate", "drain", "emaciate", "macerate", "waste", "weaken"],
    "enfeoff": ["give"],
    "enfeoffment": ["deed", "deed of conveyance", "title"],
    "enfilade": ["rake"],
    "enflurane": ["diethyl ether", "divinyl ether", "ether", "ethoxyethane", "ethrane", "ethyl ether", "vinyl ether"],
    "enforce": ["compel", "impose", "obligate", "oblige"],
    "enforceable": [],
    "enforced": ["implemented"],
    "enforcement": ["carrying out", "coercion", "execution", "implementation", "imposition", "infliction", "law enforcement", "social control"],
    "enfranchise": ["accord", "allot", "grant"],
    "enfranchised": [],
    "enfranchisement": ["freedom"],
    "engage": ["employ", "engage", "hire"],
    "engaged": [],
    "engagement": ["contact", "impinging", "interlocking", "mesh", "meshing", "striking"],
    "engagement ring": ["band", "ring"],
    "engaging": ["piquant"],
    "engelmann spruce": ["engelmann's spruce", "picea engelmannii", "spruce"],
    "engelmannia": ["wild flower", "wildflower"],
    "engels": ["friedrich engels"],
    "engender": ["breed", "cause", "do", "make", "spawn"],
    "engine": ["causal agency", "causal agent", "cause"],
    "engine block": ["block", "cast", "casting", "cylinder block"],
    "engine failure": ["breakdown", "equipment failure"],
    "engineer": ["design", "plan"],
    "engineer's chain": ["chain"],
    "engineering": ["aeronautical engineering", "applied science", "architectural engineering", "bailiwick", "bioengineering", "bionics", "biotechnology", "chemical engineering", "civil engineering", "computer science", "computing", "discipline", "ee", "electrical engineering", "engineering science", "ergonomics", "field", "field of study", "industrial engineering", "industrial management", "information technology", "it", "mechanical engineering", "nanotechnology", "naval engineering", "nuclear engineering", "rocketry", "study", "subject", "subject area", "subject field", "technology"],
    "enginery": ["machinery"],
    "england": [],
    "english": ["country", "english people", "land", "nation"],
    "english channel": [],
    "english civil war": [],
    "english department": ["academic department", "department of english"],
    "english elm": ["elm", "elm tree", "european elm", "ulmus procera"],
    "english foxhound": ["foxhound"],
    "english hawthorn": ["crataegus monogyna", "haw", "hawthorn"],
    "english horn": ["cor anglais", "double reed", "double-reed instrument"],
    "english iris": ["flag", "fleur-de-lis", "iris", "iris xiphioides", "sword lily"],
    "english lady crab": ["portunus puber", "swimming crab"],
    "english lavender": ["lavandula angustifolia", "lavandula officinalis", "lavender"],
    "english muffin": ["bread", "breadstuff", "staff of life"],
    "english person": ["anglo-indian", "anglo-saxon", "brit", "britisher", "briton", "brummie", "brummy", "cantabrigian", "englishman", "englishwoman", "geordie", "hanoverian", "lancastrian", "liverpudlian", "londoner", "mackem", "mancunian", "oxonian", "pom", "pommy", "sassenach", "scouser", "tyke"],
    "english plantain": ["buckthorn", "narrow-leaved plantain", "plantago lanceolata", "plantain", "ribgrass", "ribwort", "ripple-grass"],
    "english primrose": ["primrose", "primula", "primula vulgaris"],
    "english revolution": ["bloodless revolution", "glorious revolution"],
    "english saddle": ["english cavalry saddle", "saddle"],
    "english setter": ["setter"],
    "english sole": ["lemon sole", "parophrys vitulus", "sole"],
    "english sparrow": ["house sparrow", "passer domesticus", "sparrow", "true sparrow"],
    "english springer": ["english springer spaniel", "springer", "springer spaniel"],
    "english teacher": ["english professor", "instructor", "teacher"],
    "english toy spaniel": ["blenheim spaniel", "toy spaniel"],
    "english walnut": ["circassian walnut", "english walnut tree", "juglans regia", "persian walnut", "walnut", "walnut tree"],
    "english-speaking": [],
    "englishman": ["burgess", "burgher", "cornishman", "english person", "jacobean", "john bull", "limey", "tory", "whig"],
    "englishwoman": ["cornishwoman", "english person"],
    "engorgement": ["hyperaemia", "hyperemia"],
    "engram": ["memory", "memory trace"],
    "engraulidae": ["family engraulidae", "fish family"],
    "engraulis": ["fish genus", "genus engraulis"],
    "engrave": ["affect", "impress", "move", "strike"],
    "engraved": ["etched", "graven", "incised", "inscribed"],
    "engraver": ["lapidary", "lapidist", "skilled worker", "skilled workman", "trained worker"],
    "engraving": ["dry point", "etching", "halftone", "line engraving", "linecut", "print", "steel engraving", "wood engraving", "woodcut"],
    "engrossed": [],
    "engulf": ["enclose", "enfold", "envelop", "enwrap", "wrap"],
    "enhance": ["ameliorate", "amend", "better", "follow up", "improve", "meliorate", "retouch", "touch up"],
    "enhanced": [],
    "enhancement": ["improvement", "sweetening"],
    "enhydra": ["genus enhydra", "mammal genus"],
    "enid": [],
    "enigma canon": ["canon", "enigmatic canon", "enigmatical canon", "riddle canon"],
    "enigmatic": ["enigmatical", "puzzling"],
    "eniwetok": [],
    "enjambment": ["enjambement", "inflection", "prosody"],
    "enjoin": ["disallow", "forbid", "interdict", "nix", "prohibit", "proscribe", "veto"],
    "enjoy": ["experience", "go through", "see"],
    "enjoyable": ["gratifying", "pleasurable"],
    "enjoyableness": ["pleasantness", "sweetness"],
    "enjoyer": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "enjoyment": ["gusto", "joie de vivre", "pleasance", "pleasure", "relish", "zest", "zestfulness"],
    "enkephalin": ["endorphin"],
    "enki": [],
    "enkidu": [],
    "enlarge": ["amplify", "grow", "magnify"],
    "enlarged": [],
    "enlargement": ["lump", "pseudobulb", "puffiness", "state", "swelling"],
    "enlarger": ["photographic equipment"],
    "enlighten": ["edify", "instruct", "learn", "teach"],
    "enlightened": [],
    "enlightening": ["illuminating", "informative"],
    "enlightenment": ["age of reason", "reform movement"],
    "enlil": ["en-lil"],
    "enlist": ["draft", "enrol", "enroll", "enter", "inscribe", "levy", "muster in", "raise", "recruit"],
    "enlisted man": ["armorer", "armourer", "artificer", "buck private", "charge of quarters", "common soldier", "enlisted person", "military recruit", "private", "recruit"],
    "enlisted person": ["enlisted man", "enlisted woman", "kitchen police", "kp", "man", "military man", "military personnel", "serviceman", "soldier"],
    "enlisted woman": ["enlisted person"],
    "enlistment": ["duty tour", "hitch", "period", "period of time", "term of enlistment", "time period", "tour", "tour of duty"],
    "enliven": ["animate", "arouse", "brace", "energise", "energize", "ginger up", "inspirit", "invigorate", "jazz up", "juice up", "liven", "liven up", "pep up", "perk up", "spirit", "spirit up", "stimulate"],
    "enlivened": [],
    "enmesh": ["ensnarl", "entangle", "mat", "mesh", "snarl", "tangle"],
    "enmeshed": ["intermeshed"],
    "ennoble": ["dignify", "honor", "honour", "reward"],
    "ennoblement": ["condition", "status"],
    "ennobling": ["exalting"],
    "enol": ["organic compound"],
    "enolic": [],
    "enologist": ["fermentologist", "oenologist", "specialiser", "specialist", "specializer"],
    "enology": ["art", "artistry", "oenology", "prowess"],
    "enophile": ["appreciator", "oenophile"],
    "enormity": ["enormousness", "grandness", "greatness", "immenseness", "immensity", "sizeableness", "vastness", "wideness"],
    "enormous": ["tremendous"],
    "enormously": ["hugely", "staggeringly", "tremendously"],
    "enormousness": ["bigness", "enormity", "grandness", "greatness", "immenseness", "immensity", "largeness", "sizeableness", "vastness", "wideness"],
    "enosis": ["union"],
    "enough": ["fill", "relative quantity", "sufficiency"],
    "enovid": ["anovulant", "anovulatory drug", "birth control pill", "contraceptive pill", "oral contraceptive", "oral contraceptive pill", "pill"],
    "enrage": ["anger"],
    "enrich": ["add", "feather one's nest"],
    "enrichment": ["gift"],
    "enrobe": ["coat", "surface"],
    "enroll": ["draft", "enlist", "enrol", "enter", "inscribe", "matriculate", "muster in", "recruit", "register", "unionise", "unionize"],
    "enrollee": ["educatee", "individual", "mortal", "person", "pupil", "somebody", "someone", "soul", "student"],
    "ensconce": ["lay", "place", "pose", "position", "put", "set", "settle"],
    "ensemble": ["cast", "cast of characters", "dramatis personae", "supporting players"],
    "ensete": ["genus ensete", "liliopsid genus", "monocot genus"],
    "enshrine": ["fear", "revere", "reverence", "saint", "venerate"],
    "ensiform": ["bladelike", "sword-shaped", "swordlike"],
    "ensiform leaf": ["simple leaf"],
    "ensign": ["commissioned naval officer"],
    "ensile": ["store"],
    "ensis": ["genus ensis", "mollusk genus"],
    "ensky": ["exalt", "extol", "glorify", "laud", "proclaim"],
    "enslave": ["subject", "subjugate"],
    "enslavement": ["captivity", "subjection", "subjugation"],
    "ensnare": ["cozen", "deceive", "delude", "entrap", "frame", "lead on", "set up"],
    "ensuing": [],
    "ent man": ["ear-nose-and-throat doctor", "medical specialist", "otolaryngologist", "otorhinolaryngologist", "rhinolaryngologist", "specialist"],
    "entablature": ["construction", "structure"],
    "entail": ["imply", "mean", "necessitate"],
    "entandrophragma": ["genus entandrophragma", "rosid dicot genus"],
    "entangle": ["involve", "mire"],
    "entangled": [],
    "entasis": ["convex shape", "convexity"],
    "entebbe": [],
    "entelea": ["dilleniid dicot genus", "genus entelea"],
    "entelechy": ["actuality"],
    "entellus": ["hanuman", "langur", "presbytes entellus", "semnopithecus entellus"],
    "entente": ["alignment", "alinement", "alliance", "coalition", "entente cordiale"],
    "enter": ["board", "call at", "come in", "dock", "encroach upon", "file in", "get in", "get into", "get on", "go in", "go into", "intrude", "intrude on", "invade", "irrupt", "move into", "obtrude upon", "out in", "penetrate", "perforate", "pop in", "re-enter", "take the field", "take water", "turn in", "walk in"],
    "enter upon": ["acquire", "come upon", "get", "luck into"],
    "enteric": ["enteral"],
    "enteric bacteria": ["enterics", "enterobacteria", "entric", "erwinia", "escherichia", "eubacteria", "eubacterium", "klebsiella", "salmonella", "shigella", "true bacteria"],
    "enteric-coated aspirin": ["acetylsalicylic acid", "aspirin", "bayer", "empirin", "st. joseph"],
    "enteritis": ["inflammation", "necrotizing enteritis", "redness", "rubor"],
    "enterobacteriaceae": ["bacteria family", "family enterobacteriaceae"],
    "enterobiasis": ["infection", "infestation"],
    "enterobius": ["genus enterobius", "worm genus"],
    "enterokinase": ["enzyme"],
    "enterolith": ["calculus", "concretion"],
    "enterolithiasis": ["lithiasis"],
    "enterolobium": ["genus enterolobium", "rosid dicot genus"],
    "enteron": ["alimentary canal", "alimentary tract", "digestive tract", "digestive tube", "gastrointestinal tract", "gi tract"],
    "enteropathy": ["disease", "ileus", "intestinal obstruction"],
    "enteroptosis": ["descensus", "prolapse", "prolapsus"],
    "enterostenosis": ["stenosis", "stricture"],
    "enterostomy": ["enterotomy", "operation", "surgery", "surgical operation", "surgical procedure", "surgical process"],
    "enterotoxemia": ["animal disease"],
    "enterotoxin": ["cytotoxin", "staphylococcal enterotoxin"],
    "enterovirus": ["coxsackie virus", "coxsackievirus", "echovirus", "hepatitis a virus", "picornavirus", "poliovirus"],
    "enterprise": ["business", "business concern", "business organisation", "business organization", "collective", "commercial enterprise", "concern", "giant", "organisation", "organization"],
    "enterprise zone": ["city district"],
    "enterprising": [],
    "enterprisingly": [],
    "entertain": ["amuse", "disport", "divert", "host", "socialise", "socialize"],
    "entertainer": ["attracter", "attraction", "attractor", "bombshell", "busker", "draw", "drawing card", "emcee", "host", "humorist", "humourist", "individual", "master of ceremonies", "mortal", "performer", "performing artist", "person", "pleaser", "somebody", "someone", "soul"],
    "entertaining": [],
    "entertainingly": [],
    "entertainment": ["amusement", "beguilement", "distraction", "diversion", "edutainment", "extravaganza", "militainment", "night life", "nightlife", "recreation", "show"],
    "entertainment center": ["wall unit"],
    "entertainment deduction": ["business deduction"],
    "entertainment industry": ["industry", "show biz", "show business"],
    "enthrone": ["enthrone", "invest", "throne", "vest"],
    "enthuse": ["bring down", "excite"],
    "enthusiasm": ["avidity", "avidness", "eagerness", "exuberance", "feeling", "gusto", "keenness", "relish", "technophilia", "zest", "zestfulness"],
    "enthusiast": ["addict", "admirer", "backslapper", "balletomane", "booster", "champion", "fan", "fanatic", "fiend", "freak", "friend", "gadgeteer", "junkie", "junky", "nut", "partisan", "partizan", "protagonist", "rooter", "shutterbug", "sports fan", "supporter"],
    "enthusiastic": [],
    "enthusiastically": [],
    "entice": ["bait", "call", "decoy", "hook", "lead on", "lure", "provoke", "seduce", "snare", "stimulate", "stool", "tempt", "tweedle"],
    "enticement": ["allurement", "blandishment", "influence", "leading astray", "leading off", "seduction", "solicitation", "temptation", "wheedling"],
    "entire": [],
    "entire leaf": ["foliage", "leaf", "leafage"],
    "entirely": ["alone", "exclusively", "only", "solely"],
    "entirety": ["completeness", "entireness", "full treatment", "integrality", "kit and boodle", "kit and caboodle", "totality", "whole caboodle", "whole kit", "whole kit and boodle", "whole kit and caboodle", "whole shebang", "whole works", "works"],
    "entitle": ["authorise", "authorize", "empower"],
    "entitled": [],
    "entitlement": ["claim", "title"],
    "entity": ["abstract entity", "abstraction", "physical entity", "thing"],
    "entlebucher": ["sennenhunde"],
    "entoloma": ["fungus genus", "genus entoloma"],
    "entoloma aprile": ["agaric"],
    "entoloma lividum": ["agaric", "entoloma sinuatum"],
    "entolomataceae": ["family entolomataceae", "fungus family"],
    "entomion": ["craniometric point"],
    "entomological": ["entomologic"],
    "entomologist": ["animal scientist", "bug-hunter", "bugologist", "butterfly collector", "lepidopterist", "lepidopterologist", "zoologist"],
    "entomology": ["bugology", "lepidopterology", "lepidoptery", "zoological science", "zoology"],
    "entomophilous": [],
    "entomophobia": ["zoophobia"],
    "entomophthora": ["fungus genus", "genus entomophthora"],
    "entomophthoraceae": ["family entomophthoraceae", "fungus family"],
    "entomophthorales": ["fungus order", "order entomophthorales"],
    "entomostraca": ["class", "subclass entomostraca"],
    "entopic pregnancy": ["gestation", "maternity", "pregnancy"],
    "entoproct": ["invertebrate"],
    "entoprocta": ["endoprocta", "phylum", "phylum entoprocta"],
    "entozoan": ["endozoan"],
    "entozoic": ["endozoic", "entozoan"],
    "entr'acte": ["interlude"],
    "entrain": ["board", "get on"],
    "entrance": ["hypnotise", "hypnotize", "mesmerise", "mesmerize", "spellbind"],
    "entrance examination": ["entrance exam", "exam", "examination", "test"],
    "entrance fee": ["admission", "admission charge", "admission fee", "admission price", "entrance money", "fee", "price of admission"],
    "entrancement": ["delectation", "delight", "ravishment"],
    "entrant": ["interloper", "intruder", "traveler", "traveller", "trespasser"],
    "entrapment": ["defence", "defense", "demurrer", "denial"],
    "entreaty": ["adjuration", "appeal", "asking", "courting", "courtship", "demagoguery", "demagogy", "plea", "prayer", "request", "solicitation", "suit", "supplication", "wooing"],
    "entrecote": ["cut", "cut of meat"],
    "entree": ["course", "main course", "plate"],
    "entrench": ["dig in"],
    "entrenched": [],
    "entrenching tool": ["hand shovel", "trenching spade"],
    "entrenchment": ["fortification", "intrenchment", "munition", "retrenchment"],
    "entrepot": ["port", "transshipment center"],
    "entrepreneur": ["bourgeois", "businessperson", "enterpriser"],
    "entrepreneurial": [],
    "entrust": ["give", "hand", "leave", "pass", "pass on", "reach", "turn over"],
    "entry": ["accounting", "accounting entry", "accounting system", "adjusting entry", "credit", "credit entry", "debit", "debit entry", "ledger entry", "method of accounting"],
    "enucleate": ["remove", "take", "take away", "withdraw"],
    "enucleation": ["operation", "surgery", "surgical operation", "surgical procedure", "surgical process"],
    "enumerate": ["identify", "itemise", "itemize", "list", "name", "recite"],
    "enumeration": ["list", "listing", "numbering"],
    "enunciation": ["articulation", "diction", "mumbling"],
    "enured": ["hardened", "inured"],
    "enuresis": ["bed-wetting", "incontinence", "incontinency", "overflow incontinence", "stress incontinence", "urge incontinence", "urinary incontinence"],
    "envelop": ["bathe", "benight", "capsulate", "capsule", "capsulise", "capsulize", "cocoon", "cover", "enclose", "enfold", "engulf", "enshroud", "enwrap", "hide", "sheathe", "shroud", "tube", "wrap"],
    "envelope": ["curve", "curved shape"],
    "enveloping": [],
    "enviable": [],
    "enviably": [],
    "enviously": ["covetously", "jealously"],
    "environment": ["area", "arena", "background", "circumstance", "context", "domain", "ecology", "field", "home", "milieu", "orbit", "scope", "setting", "situation", "sphere", "state of affairs", "street", "surroundings"],
    "environmental": [],
    "environmental condition": ["climate", "clime", "condition", "deforestation", "depopulation", "erosion", "glaciation", "inhospitableness", "meteorological conditions", "pollution", "status"],
    "environmental protection agency": ["epa", "independent agency"],
    "environmentalism": ["philosophical doctrine", "philosophical theory"],
    "environmentalist": ["conservationist", "crusader", "green", "meliorist", "reformer", "reformist", "social reformer", "tree hugger"],
    "environmentally": [],
    "environs": ["geographic area", "geographic region", "geographical area", "geographical region", "purlieu"],
    "envision": ["conceive of", "envisage", "foresee", "ideate", "imagine"],
    "envisioned": ["pictured", "visualised", "visualized"],
    "envoy": ["diplomat", "diplomatist", "envoy extraordinary", "minister plenipotentiary"],
    "envy": ["admire", "look up to"],
    "enzootic": [],
    "enzymatic": [],
    "enzyme": ["accelerator", "ada", "adenosine deaminase", "amylase", "beta-lactamase", "catalase", "catalyst", "cholinesterase", "chymosin", "coagulase", "collagenase", "complement", "cox", "cyclooxygenase", "de-iodinase", "decarboxylase", "disaccharidase", "elastase", "enterokinase", "fibrinolysin", "histaminase", "hyaluronidase", "hyazyme", "isomerase", "kinase", "lipase", "lysozyme", "mao", "monoamine oxidase", "muramidase", "nitrogenase", "nuclease", "oxidase", "oxidoreductase", "papain", "penicillinase", "pepsin", "pepsinogen", "peptidase", "phosphatase", "plasmin", "polymerase", "protease", "protein", "proteinase", "proteolytic enzyme", "reductase", "rennin", "secretase", "sod", "spreading factor", "streptodornase", "streptokinase", "superoxide dismutase", "telomerase", "transferase", "trypsin", "urease", "zymase"],
    "enzyme-linked-immunosorbent serologic assay": ["assay", "elisa"],
    "enzymologist": ["biochemist"],
    "enzymology": ["biochemistry"],
    "eocene": ["eocene epoch"],
    "eohippus": ["dawn horse", "equus caballus", "horse"],
    "eolith": ["tool"],
    "eolithic": [],
    "eolithic age": ["eolithic"],
    "eon": ["aeon", "geologic time", "geological time"],
    "eonian": ["aeonian"],
    "eoraptor": ["bird-footed dinosaur", "theropod", "theropod dinosaur"],
    "eos": [],
    "eosin": ["bromeosin", "fluorescein", "fluoresceine", "fluorescent dye", "resorcinolphthalein"],
    "eosinopenia": ["symptom"],
    "eosinophil": ["eosinophile", "leucocyte", "leukocyte", "wbc", "white blood cell", "white blood corpuscle", "white cell", "white corpuscle"],
    "eosinophilia": ["symptom"],
    "eosinophilic": [],
    "epacridaceae": ["dilleniid dicot family", "epacris family", "family epacridaceae"],
    "epacris": ["australian heath", "blunt-leaf heath", "common heath", "epacris impressa", "epacris obtusifolia", "epacris purpurascens", "port jackson heath"],
    "epanalepsis": ["repetition"],
    "epanaphora": ["anaphora", "repetition"],
    "epanodos": ["recap", "recapitulation", "review"],
    "epanorthosis": ["rhetorical device"],
    "eparch": ["bishop"],
    "eparchial": [],
    "eparchy": ["province", "state"],
    "epaulet": ["adornment", "epaulette", "shoulder board", "shoulder mark"],
    "epauliere": ["armor plate", "armor plating", "armour plate", "plate armor", "plate armour"],
    "epee": ["fencing sword"],
    "ependyma": ["membrane", "tissue layer"],
    "epenthesis": ["articulation"],
    "epenthetic": ["parasitic"],
    "epergne": ["centerpiece", "centrepiece"],
    "ephah": ["dry measure", "dry unit", "epha"],
    "ephedra": ["bush", "ephedra sinica", "joint fir", "mahuang", "shrub"],
    "ephedraceae": ["family ephedraceae", "gymnosperm family"],
    "ephedrine": ["alkaloid", "bronchodilator"],
    "ephemera": ["time"],
    "ephemeral": ["fugacious", "passing", "short-lived", "transient", "transitory"],
    "ephemerality": ["ephemeralness", "fleetingness", "transience", "transiency", "transitoriness"],
    "ephemerid": ["dayfly", "ephemeropteran", "insect", "mayfly", "plectophera", "shadfly"],
    "ephemeridae": ["arthropod family", "family ephemeridae"],
    "ephemeris": ["annual", "yearbook", "yearly"],
    "ephemeron": ["ephemeral", "insect"],
    "ephemeroptera": ["animal order", "ephemerida", "order ephemerida", "order ephemeroptera"],
    "ephesian": ["greek", "hellene"],
    "ephestia": ["arthropod genus", "genus ephestia"],
    "ephesus": [],
    "ephippidae": ["family ephippidae", "fish family"],
    "ephippiorhynchus": ["bird genus", "genus ephippiorhynchus"],
    "epic": ["epical"],
    "epic poem": ["chanson de geste", "epic", "epos", "heroic", "heroic meter", "heroic poem", "heroic verse", "poem", "rhapsody", "verse form"],
    "epicalyx": ["bract", "calycle", "calyculus", "false calyx"],
    "epicanthus": ["epicanthic fold", "fold", "plica"],
    "epicardia": ["passage", "passageway"],
    "epicardium": ["serosa", "serous membrane", "visceral pericardium"],
    "epicarp": ["exocarp", "pericarp", "seed vessel"],
    "epicarpal": [],
    "epicenter": ["epicentre", "geographic point", "geographical point"],
    "epicondyle": ["appendage", "lateral epicondyle", "outgrowth", "process"],
    "epicondylitis": ["inflammation", "lateral epicondylitis", "lateral humeral epicondylitis", "redness", "rubor", "tennis elbow"],
    "epicranium": ["body covering"],
    "epictetus": [],
    "epicure": ["bon vivant", "epicurean", "foodie", "gastronome", "gourmet", "sensualist"],
    "epicurean": [],
    "epicureanism": ["doctrine", "ism", "philosophical system", "philosophy", "school of thought"],
    "epicurism": ["disposition", "temperament"],
    "epicurus": [],
    "epicycle": ["circle"],
    "epicyclic": ["epicyclical"],
    "epicyclic train": ["epicyclic gear train", "gear", "gearing", "geartrain", "power train", "train"],
    "epicycloid": ["cardioid", "line roulette", "roulette"],
    "epideictic": ["epideictical"],
    "epideictic oratory": ["oratory"],
    "epidemic": ["eruption", "irruption", "outbreak", "pandemic"],
    "epidemic disease": ["bornholm disease", "diaphragmatic pleurisy", "epidemic myalgia", "epidemic pleurodynia", "infectious disease", "myosis", "pest", "pestilence", "pestis", "plague"],
    "epidemic pleurodynia": ["bornholm disease", "diaphragmatic pleurisy", "epidemic disease", "epidemic myalgia", "myosis"],
    "epidemiologic": ["epidemiological"],
    "epidemiologist": ["medical scientist"],
    "epidemiology": ["medical specialty", "medicine"],
    "epidendron": ["orchid", "orchidaceous plant"],
    "epidendrum": ["genus epidendrum", "liliopsid genus", "monocot genus"],
    "epidermal cell": ["melanoblast", "melanocyte", "skin cell"],
    "epidermis": ["cuticle", "mantle", "pallium", "stratum"],
    "epidiascope": ["projector"],
    "epididymis": ["canal", "channel", "duct", "epithelial duct"],
    "epididymitis": ["inflammation", "redness", "rubor"],
    "epidural": ["extradural"],
    "epidural anesthesia": ["epidural", "epidural anaesthesia", "regional anaesthesia", "regional anesthesia"],
    "epidural injection": ["injection"],
    "epigaea": ["dilleniid dicot genus", "genus epigaea"],
    "epigastric": [],
    "epigastric artery": ["arteria", "arteria epigastrica", "arterial blood vessel", "artery"],
    "epigastric vein": ["inferior epigastric vein", "superficial epigastric vein", "superior epigastric veins", "vein", "vena", "vena epigastrica inferior", "vena epigastrica superficialis", "venae epigastricae superiores", "venous blood vessel"],
    "epigastrium": ["area", "region"],
    "epigenesis": ["metamorphism"],
    "epiglottis": ["cartilaginous structure"],
    "epiglottitis": ["inflammation", "redness", "rubor"],
    "epigone": ["ape", "aper", "copycat", "emulator", "epigon", "imitator"],
    "epigram": ["expression", "locution", "quip", "saying"],
    "epigraph": ["citation", "quotation", "quote"],
    "epigraphy": ["paleography"],
    "epikeratophakia": ["corneal graft", "corneal transplant", "keratoplasty"],
    "epilachna": ["arthropod genus", "genus epilachna"],
    "epilate": ["depilate", "remove", "take", "take away", "withdraw"],
    "epilating wax": ["depilator", "depilatory", "epilator"],
    "epilation": ["loss", "psilosis"],
    "epilepsy": ["akinetic epilepsy", "brain disease", "brain disorder", "cortical epilepsy", "encephalopathy", "epilepsia major", "epilepsia minor", "focal epilepsy", "generalized epilepsy", "grand mal", "grand mal epilepsy", "lafora's disease", "myoclonus epilepsy", "petit mal", "petit mal epilepsy", "posttraumatic epilepsy", "procursive epilepsy", "psychomotor epilepsy", "reflex epilepsy", "status epilepticus", "temporal lobe epilepsy", "tonic epilepsy", "traumatic epilepsy"],
    "epileptic": ["diseased person", "sick person", "sufferer"],
    "epileptic seizure": ["convulsion", "epilepsia major", "epilepsia minor", "generalized seizure", "grand mal", "petit mal"],
    "epilithic": [],
    "epilobium": ["genus epilobium", "rosid dicot genus"],
    "epilogue": ["close", "closing", "conclusion", "end", "ending", "epilog"],
    "epimedium": ["genus epimedium", "magnoliid dicot genus"],
    "epimetheus": ["titan"],
    "epimorphic": [],
    "epinephelus": ["fish genus", "genus epinephelus"],
    "epinephrine": ["adrenalin", "adrenaline", "catecholamine", "endocrine", "epinephrin", "hormone", "internal secretion", "neurotransmitter", "pressor", "vasoconstrictive", "vasoconstrictor"],
    "epipactis": ["genus epipactis", "liliopsid genus", "monocot genus"],
    "epipactis helleborine": ["helleborine"],
    "epiphany": ["christian holy day", "epiphany of our lord", "january 6", "three kings' day", "twelfth day"],
    "epiphenomenon": ["by-product", "byproduct"],
    "epiphora": ["epistrophe", "repetition"],
    "epiphyllum": ["cactus", "orchid cactus"],
    "epiphyseal": ["epiphysial"],
    "epiphysis": ["long bone", "os longum"],
    "epiphytic": [],
    "epiphytotic": [],
    "epiplexis": ["rhetorical device"],
    "epipremnum": ["genus epipremnum", "liliopsid genus", "monocot genus"],
    "epirus": [],
    "episcia": ["houseplant"],
    "episcleral veins": ["capillary vein", "venae episclerales", "venula", "venule"],
    "episcleritis": ["inflammation", "redness", "rubor"],
    "episcopacy": ["episcopate", "people"],
    "episcopal": ["episcopalian"],
    "episcopal church": ["anglican church", "anglican communion", "church of england", "episcopal church of scotland"],
    "episcopalian": ["protestant"],
    "episcopalianism": ["theological doctrine"],
    "episcopate": ["incumbency", "tenure", "term of office"],
    "episiotomy": ["perineotomy"],
    "episode": ["chapter", "drama", "dramatic event", "happening", "idyll", "natural event", "occurrence", "occurrent"],
    "episodic": [],
    "episodic memory": ["long-term memory", "ltm", "personal memory"],
    "episodically": [],
    "episome": ["deoxyribonucleic acid", "desoxyribonucleic acid", "dna"],
    "epispadias": ["birth defect", "congenital abnormality", "congenital anomaly", "congenital defect", "congenital disorder"],
    "episteme": ["cognition", "knowledge", "noesis"],
    "epistemic": ["epistemological"],
    "epistemic logic": ["modal logic"],
    "epistemologist": ["philosopher"],
    "epistemology": ["methodological analysis", "methodology", "philosophy"],
    "epistle": ["letter", "missive"],
    "epistle of james": ["james"],
    "epistle of jude": ["jude"],
    "epistle of paul the apostle to philemon": ["epistle to philemon", "philemon"],
    "epistle of paul the apostle to the colossians": ["colossians", "epistle to the colossians"],
    "epistle of paul the apostle to the ephesians": ["ephesians", "epistle to the ephesians"],
    "epistle of paul the apostle to the galatians": ["epistle to the galatians", "galatians"],
    "epistle of paul the apostle to the philippians": ["epistle to the philippians", "philippians"],
    "epistle of paul the apostle to the romans": ["epistle to the romans", "romans"],
    "epistle of paul the apostle to titus": ["epistle to titus", "titus"],
    "epistle to the hebrews": ["hebrews"],
    "epistolary": ["epistolatory"],
    "epitaph": ["commemoration", "memorial", "remembrance"],
    "epitaxy": ["growing"],
    "epithalamium": ["ode", "prothalamion", "prothalamium"],
    "epithelial": [],
    "epithelial cell": ["columnar cell", "columnar epithelial cell", "cuboidal cell", "cuboidal epithelial cell", "goblet cell", "gustatory cell", "hair cell", "somatic cell", "squamous cell", "taste cell", "vegetative cell"],
    "epitheliod": [],
    "epithelioma": ["skin cancer"],
    "epithelium": ["animal tissue", "decidua", "endothelium", "epithelial tissue", "mesothelium", "neuroepithelium"],
    "epithet": ["characterisation", "characterization", "delineation", "depiction", "picture", "word picture", "word-painting"],
    "epitome": ["abstract", "outline", "precis", "synopsis"],
    "epizoan": ["ectozoan"],
    "epizoic": [],
    "epizootic": [],
    "epoch": ["date", "date of reference"],
    "epochal": ["epoch-making"],
    "epona": [],
    "eponym": ["name"],
    "eponymous": ["eponymic"],
    "eponymy": ["derivation"],
    "epos": ["poesy", "poetry", "verse"],
    "epoxy": ["glue", "paste"],
    "epsilon": ["alphabetic character", "letter", "letter of the alphabet"],
    "epsilon aurigae": [],
    "epsilon toxin": ["bacterial toxin", "clostridium perfringens epsilon toxin"],
    "epsom salts": ["bitter salts", "magnesium sulfate"],
    "epstein": ["jacob epstein", "sir jacob epstein"],
    "epstein-barr virus": ["ebv", "herpes", "herpes virus"],
    "eptatretus": ["hag", "hagfish", "slime eels"],
    "eptesicus": ["genus eptesicus", "mammal genus"],
    "equable": [],
    "equably": [],
    "equal": ["compete", "contend", "match", "rival", "touch", "vie"],
    "equal opportunity": ["civil right"],
    "equal protection of the laws": ["civil right"],
    "equal sign": ["sign"],
    "equal temperament": ["temperament"],
    "equal-area projection": ["equal-area map projection", "homolosine projection", "map projection", "sanson-flamsteed projection", "sinusoidal projection"],
    "equality": ["egalite", "egality", "equation", "equivalence", "par", "position", "status", "tie"],
    "equality before the law": ["human right"],
    "equalization": ["act", "balancing", "deed", "equalisation", "equating", "equation", "human action", "human activity", "leveling", "reconciliation"],
    "equalize": ["equalise", "get even", "hit", "rack up", "score", "tally"],
    "equalizer": ["electronic equipment", "equaliser"],
    "equalizing dividend": ["dividend"],
    "equally": ["as", "every bit"],
    "equatability": ["equality"],
    "equate": ["be", "correspond", "equal"],
    "equation": ["biquadratic", "biquadratic equation", "differential equation", "exponential equation", "linear equation", "mathematical statement", "quadratic", "quadratic equation", "regression equation", "regression of y on x", "simultaneous equations"],
    "equator": ["circle"],
    "equatorial": ["scope", "telescope"],
    "equatorial current": ["north equatorial current", "ocean current", "south equatorial current"],
    "equatorial guinea": ["republic of equatorial guinea", "spanish guinea"],
    "equerry": ["functionary", "official"],
    "equestrian": [],
    "equestrian sport": ["cross-country jumping", "cross-country riding", "dressage", "equitation", "horseback riding", "riding", "showjumping", "stadium jumping", "three-day event"],
    "equetus": ["fish genus", "genus equetus"],
    "equiangular": [],
    "equidae": ["family equidae", "mammal family"],
    "equidistant": [],
    "equidistribution": ["distribution", "statistical distribution"],
    "equilateral": ["figure"],
    "equilateral triangle": ["delta", "equiangular triangle", "regular polygon", "triangle", "trigon", "trilateral"],
    "equilibrate": ["change state", "turn"],
    "equilibration": ["stabilisation", "stabilization"],
    "equilibrium": ["balance", "balance of power", "dynamic balance", "homeostasis", "isostasy", "nash equilibrium", "poise", "situation", "state of affairs", "thermal equilibrium"],
    "equilibrium constant": ["constant", "dissociation constant"],
    "equilibrium law": ["law", "law of chemical equilibrium", "law of nature"],
    "equine": ["ass", "equid", "equus caballus", "equus quagga", "hinny", "horse", "mule", "odd-toed ungulate", "perissodactyl", "perissodactyl mammal", "quagga", "zebra"],
    "equine distemper": ["distemper", "strangles"],
    "equine encephalitis": ["cephalitis", "encephalitis", "equine encephalomyelitis", "phrenitis"],
    "equinoctial": [],
    "equinoctial point": ["autumnal equinox", "celestial point", "equinox", "vernal equinox"],
    "equinox": ["autumnal equinox", "cosmic time", "fall equinox", "march equinox", "september equinox", "spring equinox", "vernal equinox"],
    "equip": ["accouter", "accoutre", "adorn", "appoint", "armor", "armour", "clothe", "collar", "commission", "fin", "fit", "fit out", "furnish", "fuse", "horseshoe", "instrument", "invest", "kit", "kit out", "kit up", "mechanise", "mechanize", "motorise", "motorize", "muzzle", "outfit", "provide", "re-equip", "refit", "rejig", "render", "rig", "set", "set up", "shaft", "spar", "spur", "stave", "stock", "supply", "turn out", "wire"],
    "equipment": ["apparatus", "appurtenance", "artificial satellite", "automation", "cooling system", "electrical system", "electronic equipment", "engine cooling system", "equipage", "fuel system", "game equipment", "gear", "instrumentality", "instrumentation", "life support", "life-support system", "material", "materiel", "naval equipment", "orbiter", "paraphernalia", "photographic equipment", "radiotherapy equipment", "recorder", "recording equipment", "recording machine", "rescue equipment", "robotics equipment", "satellite", "setup", "sports equipment", "stock-in-trade", "teaching aid", "test equipment"],
    "equipoised": [],
    "equipotent": [],
    "equipped": ["fitted out"],
    "equiprobable": [],
    "equisetaceae": ["family equisetaceae", "fern family", "horsetail family"],
    "equisetales": ["order equisetales", "plant order"],
    "equisetum": ["fern genus", "genus equisetum"],
    "equitable": ["just"],
    "equitably": [],
    "equity": ["assets"],
    "equivalence": ["equality", "parity"],
    "equivalent": ["cognition", "counterpart", "knowledge", "noesis", "opposite number", "replacement", "substitute", "vis-a-vis"],
    "equivalent-binary-digit factor": ["divisor", "factor"],
    "equivocal": [],
    "equivocation": ["ambiguity", "equivocalness", "evasiveness", "prevarication", "untruthfulness"],
    "equus": ["genus equus", "mammal genus"],
    "era": ["age", "day", "epoch", "historic period", "modern era", "period", "period of time", "time period"],
    "eradicable": [],
    "eradication": ["demolition", "destruction", "obliteration", "wipeout"],
    "eragrostis": ["genus eragrostis", "liliopsid genus", "monocot genus"],
    "eranthis": ["genus eranthis", "magnoliid dicot genus"],
    "erasable programmable read-only memory": ["eprom", "fixed storage", "read-only memory", "read-only storage", "rom"],
    "erase": ["cancel", "cut out", "delete", "efface", "rub out", "score out", "scratch out", "sponge", "wipe off"],
    "eraser": ["blackboard eraser", "implement", "ink eraser", "pencil eraser", "rubber", "rubber eraser"],
    "erasmian": [],
    "erasmus": ["desiderius erasmus", "geert geerts", "gerhard gerhards"],
    "erastianism": ["byzantinism", "caesaropapism", "theological doctrine"],
    "erasure": ["correction"],
    "erato": [],
    "eratosthenes": [],
    "erb's palsy": ["erb-duchenne paralysis", "palsy", "paralysis"],
    "erbium": ["atomic number 68", "er", "metal", "metallic element"],
    "ercilla": ["caryophylloid dicot genus", "genus ercilla"],
    "erebus": [],
    "erect": ["upright", "vertical"],
    "erect bugle": ["ajuga genevensis", "blue bugle", "bugle", "bugleweed"],
    "erectile": [],
    "erectile dysfunction": ["disfunction", "dysfunction", "ed", "impotence", "impotency", "male erecticle dysfunction"],
    "erectile organ": ["button", "clit", "clitoris", "member", "organ", "penis", "phallus"],
    "erectile tissue": ["animal tissue"],
    "erecting": ["building", "construction", "erection"],
    "erecting prism": ["optical prism", "prism"],
    "erection": ["hard-on", "sexual arousal"],
    "erectly": ["straight-backed"],
    "erectness": ["stance", "uprightness"],
    "eremite": ["anchorite", "hermit", "religious"],
    "eremitic": ["eremitical"],
    "eremitism": ["monasticism"],
    "ereshkigal": ["eresh-kigal", "ereshkigel"],
    "erethism": ["abnormalcy", "abnormality"],
    "erethizon": ["genus erethizon", "mammal genus"],
    "erethizontidae": ["family erethizontidae", "mammal family"],
    "eretmochelys": ["genus eretmochelys", "reptile genus"],
    "erewhon": [],
    "erg": ["energy unit", "heat unit", "work unit"],
    "ergo": [],
    "ergodic": [],
    "ergodicity": ["haphazardness", "noise", "randomness", "stochasticity"],
    "ergonomic": [],
    "ergonovine": ["alkaloid", "ergotrate maleate"],
    "ergosterol": ["steroid alcohol", "sterol"],
    "ergot": ["plant disease"],
    "ergotamine": ["alkaloid"],
    "ergotic": [],
    "ergotism": ["intoxication", "poisoning", "toxic condition"],
    "ergotropic": [],
    "ergotropism": ["tropism"],
    "erianthus": ["genus erianthus", "liliopsid genus", "monocot genus"],
    "erica": ["bell heather", "briar", "brier", "cornish heath", "cross-leaved heath", "erica arborea", "erica carnea", "erica cinerea", "erica lusitanica", "erica perspicua", "erica tetralix", "erica vagans", "fine-leaved heath", "heath", "heather bell", "portuguese heath", "prince of wales heath", "prince-of-wales'-heath", "spanish heath", "spring heath", "tree heath", "true heath", "winter heath"],
    "ericaceae": ["dilleniid dicot family", "ericales", "family ericaceae", "heath family", "order ericales"],
    "ericales": ["ericaceae", "family ericaceae", "heath family", "order ericales", "plant order"],
    "eridanus": [],
    "erie": ["iroquois"],
    "erie canal": [],
    "erigeron": ["asterid dicot genus", "genus erigeron"],
    "erignathus": ["genus erignathus", "mammal genus"],
    "erin": [],
    "erinaceidae": ["family erinaceidae", "mammal family"],
    "erinaceus": ["genus erinaceus", "mammal genus"],
    "eriobotrya": ["genus eriobotrya", "rosid dicot genus"],
    "eriocaulaceae": ["family eriocaulaceae", "liliopsid family", "monocot family", "pipewort family"],
    "eriocaulon": ["genus eriocaulon", "liliopsid genus", "monocot genus"],
    "eriodictyon": ["asterid dicot genus", "genus eriodictyon"],
    "eriogonum": ["california buckwheat", "erigonum fasciculatum", "eriogonum allenii", "subshrub", "suffrutex", "umbrella plant", "wild buckwheat"],
    "eriophorum": ["genus eriophorum", "liliopsid genus", "monocot genus"],
    "eriophyllum": ["asterid dicot genus", "genus eriophyllum"],
    "eriosoma": ["arthropod genus", "genus eriosoma"],
    "eris": [],
    "eristic": ["art", "artistry", "prowess"],
    "erithacus": ["bird genus", "genus erithacus"],
    "eritrea": ["state of eritrea"],
    "eritrean": ["ethiopian"],
    "erlang": ["telephone unit"],
    "erlenmeyer": ["richard august carl emil erlenmeyer"],
    "erlenmeyer flask": ["flask"],
    "ermine": ["fur", "pelt"],
    "ern": ["erne", "european sea eagle", "gray sea eagle", "grey sea eagle", "haliatus albicilla", "sea eagle", "white-tailed sea eagle"],
    "ernst": ["max ernst"],
    "erode": ["crumble", "decay", "dilapidate", "eat at", "gnaw", "gnaw at", "wear away"],
    "eroded": ["scoured"],
    "erodium": ["genus erodium", "rosid dicot genus"],
    "erogenous": [],
    "erogenous zone": ["area", "region"],
    "erolia": ["bird genus", "genus erolia"],
    "eros": [],
    "erose": ["jagged", "jaggy", "notched", "toothed"],
    "erose leaf": ["foliage", "leaf", "leafage"],
    "erosion": ["environmental condition"],
    "erosive": [],
    "erotic": ["sensualist"],
    "erotically": [],
    "eroticism": ["erotism", "sexual arousal"],
    "eroticize": ["alter", "change", "modify", "sex up"],
    "err": ["fall for", "misjudge", "misremember", "mistake", "slip", "slip up", "stumble", "trip up"],
    "errancy": ["unacceptability", "unacceptableness"],
    "errand": ["trip"],
    "errant": [],
    "erratic": ["planetary", "wandering"],
    "erratically": ["unpredictably"],
    "errhine": [],
    "erring": ["error-prone"],
    "erroneous": [],
    "erroneousness": ["deviation", "error", "incorrectness", "wrongness"],
    "error": ["algorithm error", "computer error", "happening", "hardware error", "natural event", "occurrence", "occurrent", "programming error", "software error"],
    "error correction code": ["code", "computer code", "cyclic redundancy check", "ecc"],
    "errorless": [],
    "ersatz": ["replacement", "substitute"],
    "erstwhile": ["former", "old", "one-time", "onetime", "quondam", "sometime"],
    "eruca": ["dilleniid dicot genus", "genus eruca"],
    "erudite": ["learned"],
    "eruditely": ["learnedly"],
    "eruditeness": ["education", "encyclopaedism", "encyclopedism", "erudition", "learnedness", "learning", "letters", "scholarship"],
    "erupt": ["blow out", "catch", "catch fire", "change state", "combust", "conflagrate", "ignite", "light up", "take fire", "turn"],
    "eruption": ["eczema vaccinatum", "efflorescence", "enanthem", "enanthema", "exanthem", "exanthema", "kaposi's varicelliform eruption", "rash", "roseola", "skin eruption", "skin rash", "symptom"],
    "eruptive": [],
    "erving": ["dr. j", "julius erving", "julius winfield erving"],
    "erwinia": ["enteric bacteria", "enterics", "enterobacteria", "entric"],
    "eryngium": ["genus eryngium", "rosid dicot genus"],
    "eryngo": ["eringo", "subshrub", "suffrutex"],
    "erysimum": ["dilleniid dicot genus", "genus erysimum"],
    "erysipelas": ["saint anthony's fire"],
    "erysiphaceae": ["family erysiphaceae", "fungus family"],
    "erysiphales": ["fungus order", "order erysiphales"],
    "erysiphe": ["fungus genus", "genus erysiphe"],
    "erythema": ["erythema multiforme", "erythema nodosum", "erythema solare", "erythroderma", "hickey", "love bite", "sunburn", "windburn"],
    "erythema multiforme": ["erythema"],
    "erythema nodosum": ["enl", "erythema", "erythema nodosum leprosum"],
    "erythema nodosum leprosum": ["enl", "erythema nodosum"],
    "erythematous": [],
    "erythrite": ["cobalt bloom", "mineral"],
    "erythroblast": ["embryonic cell", "formative cell", "sideroblast"],
    "erythroblastosis": ["blood disease", "blood disorder"],
    "erythroblastosis fetalis": ["anaemia", "anemia"],
    "erythrocebus": ["genus erythrocebus", "mammal genus"],
    "erythrocyte sedimentation rate": ["esr", "rate", "sed rate", "sedimentation rate"],
    "erythroderma": ["disease of the skin", "erythema", "flare", "skin disease", "skin disorder"],
    "erythroid": [],
    "erythromycin": ["antibiotic", "antibiotic drug", "e-mycin", "erythrocin", "ethril", "ilosone", "pediamycin"],
    "erythronium": ["genus erythronium", "liliid monocot genus"],
    "erythropoiesis": ["biological process", "organic process"],
    "erythropoietic": [],
    "erythropoietin": ["glycoprotein"],
    "erythroxylaceae": ["family erythroxylaceae", "plant family"],
    "erythroxylon": ["erythroxylum", "genus erythroxylon", "genus erythroxylum", "plant genus"],
    "erythroxylon coca": ["bush", "coca", "coca plant", "shrub"],
    "erythroxylon truxiuense": ["bush", "shrub"],
    "esaki": ["leo esaki"],
    "esau": [],
    "escadrille": ["squadron"],
    "escalade": ["climb", "climb up", "go up", "mount"],
    "escalader": ["climber"],
    "escalate": ["increase", "intensify", "redouble", "step up"],
    "escalation": ["increase", "step-up"],
    "escalator": ["moving staircase", "moving stairway", "staircase", "stairway"],
    "escalator clause": ["article", "clause", "escalator"],
    "escalope de veau orloff": ["dish"],
    "escapade": ["diversion", "lark", "recreation", "sexcapade"],
    "escape": ["break loose", "escape", "get away"],
    "escape hatch": ["hatchway", "opening", "scuttle"],
    "escape mechanism": ["dodging", "escape", "evasion"],
    "escape velocity": ["speed", "velocity"],
    "escape wheel": ["cogwheel", "gear", "gear wheel", "geared wheel"],
    "escapee": ["fugitive", "fugitive from justice"],
    "escapement": ["mechanical device"],
    "escapist": ["daydreamer", "dreamer", "wishful thinker", "woolgatherer"],
    "escapologist": ["conjurer", "conjuror", "escape expert", "illusionist", "magician", "prestidigitator"],
    "escapology": ["bailiwick", "discipline", "field", "field of study", "study", "subject", "subject area", "subject field"],
    "escargot": ["meat", "snail"],
    "escarpment": ["incline", "scarp", "side", "slope"],
    "eschar": ["scab"],
    "eschatological": [],
    "eschatologically": [],
    "eschatologist": ["theologian", "theologiser", "theologist", "theologizer"],
    "eschatology": ["divinity", "theology"],
    "escheat": ["reversion"],
    "escherichia": ["e. coli", "enteric bacteria", "enterics", "enterobacteria", "entric", "escherichia coli"],
    "escherichia coli": ["e. coli", "escherichia"],
    "eschrichtiidae": ["family eschrichtiidae", "mammal family"],
    "eschrichtius": ["genus eschrichtius", "mammal genus"],
    "eschscholtzia": ["dilleniid dicot genus", "genus eschscholtzia"],
    "escolar": ["gempylid", "lepidocybium flavobrunneum"],
    "escort": ["accompany", "chaperon", "chaperone", "convoy", "safeguard", "squire"],
    "escrow": ["written agreement"],
    "escrow funds": ["cash in hand", "finances", "funds", "monetary resource", "pecuniary resource"],
    "escutcheon": ["plate"],
    "esker": ["ridge"],
    "eskimo": ["american indian", "esquimau", "indian", "inuit", "red indian"],
    "eskimo curlew": ["curlew", "numenius borealis"],
    "eskimo dog": ["husky", "working dog"],
    "eskimo-aleut": ["aleut", "eskimo", "eskimo-aleut language", "esquimau", "natural language", "tongue"],
    "esmolol": ["beta blocker", "beta-adrenergic blocker", "beta-adrenergic blocking agent", "beta-blocking agent", "brevibloc"],
    "esocidae": ["family esocidae", "fish family"],
    "esophageal": [],
    "esophageal smear": ["alimentary tract smear"],
    "esophageal veins": ["oesophageal veins", "vein", "vena", "venae esophageae", "venous blood vessel"],
    "esophagitis": ["inflammation", "oesophagitis", "redness", "rubor"],
    "esophagogastric junction": ["articulation", "join", "joint", "junction", "juncture", "oesophagogastric junction"],
    "esophagoscope": ["oesophagoscope", "optical instrument"],
    "esophagus": ["gorge", "gullet", "muscle system", "muscular structure", "musculature", "oesophagus", "passage", "passageway"],
    "esoteric": [],
    "esoterica": ["arcanum", "secret"],
    "esox": ["fish genus", "genus esox"],
    "espadrille": ["sandal"],
    "espagnole": ["sauce", "sauce espagnole"],
    "espalier": ["treillage", "trellis"],
    "especial": ["exceptional", "particular", "special"],
    "esperantido": ["artificial language"],
    "esperanto": ["artificial language"],
    "espionage": ["spying", "undercover work"],
    "espionage agent": ["spy", "undercover agent"],
    "espionage network": ["network", "web"],
    "esplanade": ["mall", "promenade"],
    "espoo": [],
    "espouse": ["accept", "adopt", "embrace", "fasten on", "hook on", "latch on", "seize on", "sweep up", "take up"],
    "espresso": ["caffe latte", "coffee", "java", "latte"],
    "espresso maker": ["coffee maker"],
    "espresso shop": ["cafe", "coffee bar", "coffee shop", "coffeehouse"],
    "esprit": ["life", "liveliness", "spirit", "sprightliness"],
    "esprit de corps": ["disposition", "morale", "team spirit", "temperament"],
    "esprit de l'escalier": ["humor", "humour", "wit", "witticism", "wittiness"],
    "esquire": ["attendant", "attender", "tender"],
    "essay": ["composition", "disquisition", "memoir", "paper", "piece of writing", "report", "thanatopsis", "theme", "writing", "written material"],
    "essayist": ["author", "litterateur", "writer"],
    "esselen": ["hoka", "hokan"],
    "essen": [],
    "essence": ["substance"],
    "essene": ["hebrew", "israelite", "jew"],
    "essential": [],
    "essential amino acid": ["amino acid", "aminoalkanoic acid", "arginine", "histidine", "isoleucine", "leucine", "lysine", "methionine", "phenylalanine", "threonine", "tryptophan", "tryptophane", "valine"],
    "essential condition": ["prerequisite", "requirement", "sine qua non"],
    "essential hypertension": ["high blood pressure", "hyperpiesia", "hyperpiesis", "hypertension"],
    "essential oil": ["absinthe oil", "atar", "athar", "attar", "bitter almond oil", "clove oil", "costus oil", "eucalyptus oil", "ilang-ilang", "linalool", "oil", "oil of cloves", "oil of turpentine", "ottar", "spirit of turpentine", "turpentine", "turps", "volatile oil", "wormwood oil"],
    "essential thrombocytopenia": ["thrombocytopenia", "thrombopenia"],
    "essential tremor": ["tremor"],
    "essentiality": ["essentialness", "importance", "indispensability", "indispensableness", "vitalness"],
    "essex": [],
    "establish": ["found", "launch", "open", "open up", "set up"],
    "established": [],
    "established church": ["faith", "organized religion", "religion"],
    "establishment": ["action", "activity", "ecesis", "natural action", "natural process"],
    "establishmentarianism": ["doctrine", "establishmentism", "ism", "philosophical system", "philosophy", "school of thought"],
    "estaminet": ["cafe", "coffee bar", "coffee shop", "coffeehouse"],
    "estate": ["belongings", "estate for life", "gross estate", "holding", "jointure", "legal jointure", "life estate", "net estate", "property"],
    "estate of the realm": ["class", "commons", "estate", "first estate", "fourth estate", "lords spiritual", "lords temporal", "second estate", "social class", "socio-economic class", "stratum", "the three estates", "third estate"],
    "estates general": ["states general"],
    "estazolam": ["benzodiazepine", "prosom"],
    "esteem": ["honor", "honour", "laurels", "regard", "respect", "stature"],
    "esteemed": ["honored", "prestigious"],
    "ester": ["banana oil", "base", "cellulose ester", "citrate", "cyclohexanol phthalate", "ethyl acetate", "glyceryl ester", "lactate", "maleate", "nucleotide", "organic compound", "polyester", "urethane"],
    "esterify": ["change state", "turn"],
    "esther": [],
    "esthete": ["aesthete", "cognoscente", "connoisseur"],
    "esthetician": ["aesthetician", "skilled worker", "skilled workman", "trained worker"],
    "estimable": ["good", "honorable", "respectable"],
    "estimate": ["approximate", "assess", "calculate", "cipher", "compute", "count", "cypher", "figure", "gauge", "give", "guess", "guesstimate", "judge", "lowball", "make", "misgauge", "place", "put", "quantise", "quantize", "reckon", "set", "truncate", "underestimate", "work out"],
    "estimated tax": ["income tax"],
    "estivate": ["aestivate", "catch some z's", "kip", "log z's", "sleep", "slumber"],
    "estivation": ["aestivation", "dormancy", "quiescence", "quiescency"],
    "estonia": ["esthonia", "republic of estonia"],
    "estonian": ["baltic-finnic", "esthonian"],
    "estonian monetary unit": ["kroon", "monetary unit", "sent"],
    "estoppel": ["rule of evidence"],
    "estradiol": ["estrogen", "oestradiol", "oestrogen"],
    "estradiol patch": ["skin patch", "transdermal patch"],
    "estrange": ["move out", "remove", "take out"],
    "estranging": [],
    "estrilda": ["bird genus", "genus estrilda"],
    "estriol": ["estrogen", "oestriol", "oestrogen"],
    "estrogen": ["des", "diethylstilbestrol", "diethylstilboestrol", "estradiol", "estriol", "estrone", "estronol", "hexestrol", "mestranol", "oestradiol", "oestriol", "oestrogen", "oestrone", "sex hormone", "steroid", "steroid hormone", "stilbestrol", "stilboestrol", "theelin"],
    "estrogen antagonist": ["antagonist", "tamoxifen"],
    "estrogenic": [],
    "estrone": ["estrogen", "estronol", "ketosteroid", "oestrogen", "oestrone", "theelin"],
    "estrous": [],
    "estrus": ["heat", "oestrus", "physical condition", "physiological condition", "physiological state", "rut"],
    "estuarine": ["estuarial"],
    "estuary": ["body of water", "firth", "water"],
    "et al": ["et al.", "et alia", "et aliae", "et alii"],
    "eta": ["alphabetic character", "letter", "letter of the alphabet"],
    "etagere": ["article of furniture", "furniture", "piece of furniture"],
    "etamine": ["cloth", "etamin", "fabric", "material", "textile"],
    "etanercept": ["anti-tnf compound", "enbrel"],
    "etcetera": ["stuff"],
    "etch": ["show"],
    "etcher": ["artist", "creative person"],
    "etching": ["aquatint", "engraving"],
    "eternal life": ["aliveness", "animation", "life", "life eternal", "living"],
    "eternity": ["interval", "time interval"],
    "eternize": ["perpetuate"],
    "ethacrynic acid": ["diuretic", "diuretic drug", "edecrin", "water pill"],
    "ethane": ["alkane", "alkane series", "c2h6", "hydrocarbon", "methane series", "paraffin", "paraffin series"],
    "ethchlorvynol": ["placidyl", "sedative-hypnotic", "sedative-hypnotic drug"],
    "ethelbert": [],
    "ethelred": ["ethelred ii", "ethelred the unready"],
    "ether": ["organic compound"],
    "ethereal": [],
    "etherealize": ["alter", "change", "etherialise", "modify"],
    "etherify": ["change state", "turn"],
    "etherize": ["anaesthetise", "anaesthetize", "anesthetise", "anesthetize", "etherise", "put out", "put under"],
    "ethernet": ["lan", "local area network"],
    "ethernet cable": ["coax", "coax cable", "coaxial cable"],
    "ethic": ["double standard", "ethical code", "system", "system of rules"],
    "ethical": [],
    "ethical motive": ["christ within", "conscience", "ethics", "hedonism", "inner light", "light", "light within", "moral sense", "morality", "morals", "motivation", "motive", "need", "scruples", "sense of right and wrong"],
    "ethically": [],
    "ethicism": ["doctrine", "ism", "philosophical system", "philosophy", "school of thought"],
    "ethicist": ["ethician", "philosopher"],
    "ethics": ["bioethics", "casuistry", "endaemonism", "eudemonism", "hedonism", "moral philosophy", "philosophy"],
    "ethics committee": ["commission", "committee", "ethics panel"],
    "ethiopia": ["abyssinia", "federal democratic republic of ethiopia", "yaltopya"],
    "ethiopian": ["african", "amhara", "eritrean"],
    "ethiopian monetary unit": ["birr", "monetary unit"],
    "ethmoid": ["bone", "ethmoid bone", "os"],
    "ethmoid sinus": ["ethmoidal sinus", "sinus", "sinus ethmoidales"],
    "ethmoidal artery": ["arteria", "arteria ethmoidalis", "arterial blood vessel", "artery"],
    "ethmoidal vein": ["vein", "vena", "vena ethmoidalis", "venous blood vessel"],
    "ethnarch": ["ruler", "swayer"],
    "ethnic": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "ethnic cleansing": ["group action"],
    "ethnic group": ["abo", "aboriginal", "aborigine", "australian aborigine", "azeri", "bengali", "ethnic minority", "ethnos", "flemish", "group", "grouping", "hebrews", "igbo", "israelites", "kurd", "mbundu", "native australian", "nubian", "ovimbundu", "tadzhik", "tajik", "walloons"],
    "ethnic joke": ["gag", "jape", "jest", "joke", "laugh"],
    "ethnic minority": ["arab-berbers", "berbers", "dagestani", "ethnic group", "ethnos", "maori", "mayas", "pashtun", "pathan"],
    "ethnic slur": ["aspersion", "slur"],
    "ethnically": [],
    "ethnicity": ["quality"],
    "ethnocentric": [],
    "ethnocentrism": ["partiality", "partisanship"],
    "ethnographer": ["anthropologist"],
    "ethnographic": ["ethnographical"],
    "ethnography": ["anthropology", "descriptive anthropology"],
    "ethnological": ["ethnologic"],
    "ethnologist": ["anthropologist"],
    "ethnology": ["anthropology"],
    "ethologist": ["animal scientist", "zoologist"],
    "ethology": ["zoological science", "zoology"],
    "ethos": ["attribute"],
    "ethosuximide": ["anticonvulsant", "anticonvulsant drug", "antiepileptic", "antiepileptic drug", "emeside", "zarontin"],
    "ethyl": ["alkyl", "alkyl group", "alkyl radical", "ethyl group", "ethyl radical"],
    "ethyl acetate": ["ester"],
    "ethyl alcohol": ["absolute alcohol", "alcohol", "denatured alcohol", "ethanol", "fermentation alcohol", "grain alcohol", "plant product", "spirits of wine"],
    "ethyl chloride": ["local", "local anaesthetic", "local anesthetic", "topical anaesthetic", "topical anesthetic"],
    "ethylene": ["alkene", "ethene", "gas", "olefin", "olefine", "tce", "trichloroethane", "trichloroethylene"],
    "ethylene glycol": ["antifreeze", "ethanediol", "glycol"],
    "ethylenediaminetetraacetic acid": ["edta", "molecule"],
    "etiolate": ["weaken"],
    "etiolation": ["appearance", "visual aspect"],
    "etiological": ["aetiologic", "aetiological", "etiologic"],
    "etiologist": ["aetiologist", "diagnostician", "pathologist"],
    "etiology": ["aetiology", "cause"],
    "etiquette": ["prescript", "protocol", "punctilio", "rule"],
    "etna": ["mount etna", "mt etna"],
    "etodolac": ["lodine", "nonsteroidal anti-inflammatory", "nonsteroidal anti-inflammatory drug", "nsaid"],
    "eton collar": ["collar", "neckband"],
    "eton college": ["public school"],
    "eton jacket": ["jacket"],
    "etonian": ["educatee", "pupil", "student"],
    "etropus": ["fish genus", "genus etropus"],
    "etruria": []
}
