synonyms = {
    "stopcock": ["cock", "faucet", "spigot", "turncock"],
    "stopes": ["marie charlotte carmichael stopes", "marie stopes"],
    "stoplight": ["brake light", "visual signal"],
    "stopover": ["stop", "way station"],
    "stoppable": [],
    "stoppard": ["sir tom stoppard", "thomas straussler", "tom stoppard"],
    "stopped": ["stopped up", "stopped-up"],
    "stopper": ["plug", "secure", "stop up", "stopple"],
    "stopper knot": ["knot", "matthew walker", "matthew walker knot"],
    "stoppered": [],
    "stopping": ["double stopping", "playing"],
    "stopping point": ["close", "conclusion", "end", "ending", "finale", "finis", "finish", "last"],
    "stopwatch": ["stop watch", "timer"],
    "storage": ["computer operation", "fragmentation", "machine operation"],
    "storage battery": ["accumulator", "galvanic battery", "lead-acid accumulator", "lead-acid battery", "nicad", "nickel-cadmium accumulator", "nickel-iron accumulator", "nickel-iron battery", "voltaic battery"],
    "storage cell": ["cell", "electric cell", "secondary cell"],
    "storage medium": ["data-storage medium", "magnetic medium", "magnetic storage", "magnetic storage medium", "medium"],
    "storage ring": ["container"],
    "storage space": ["area", "cache", "cellar", "closet", "cupboard", "drawer", "root cellar", "stacks", "wine cellar"],
    "storax": ["natural resin"],
    "store": ["bottle", "ensile", "garage", "garner", "hold on", "keep", "loft", "mothball", "reposit", "tank", "warehouse", "wharf"],
    "store detective": ["operative", "pi", "private detective", "private eye", "private investigator", "shamus", "sherlock"],
    "stored program": ["computer program", "computer programme", "program", "programme"],
    "stored-program": [],
    "storehouse": ["deposit", "depositary", "depository", "depot", "dump", "entrepot", "garner", "granary", "magazine", "powder magazine", "powder store", "railhead", "repository", "storage", "storage warehouse", "store", "treasure house", "warehouse"],
    "storeria": ["genus storeria", "reptile genus"],
    "storeroom": ["buttery", "chandlery", "larder", "lumber room", "pantry", "room", "stock room", "stockroom", "storage room", "stowage", "strongroom"],
    "storied": ["storeyed"],
    "stork": ["adjutant", "adjutant bird", "adjutant stork", "black stork", "black-necked stork", "ciconia ciconia", "ciconia nigra", "ephippiorhynchus senegalensis", "flinthead", "jabiru", "jabiru mycteria", "leptoptilus crumeniferus", "leptoptilus dubius", "marabou", "marabou stork", "marabout", "mycteria americana", "openbill", "policeman bird", "saddlebill", "wader", "wading bird", "white stork", "wood ibis", "wood stork", "xenorhyncus asiaticus"],
    "storksbill": ["alfilaria", "alfileria", "clocks", "erodium cicutarium", "erodium moschatum", "erodium texanum", "filaree", "filaria", "geranium", "heron's bill", "musk clover", "muskus grass", "pin clover", "pin grass", "redstem storksbill", "texas storksbill", "white-stemmed filaree"],
    "storm": [],
    "storm cellar": ["cyclone cellar", "shelter", "tornado cellar"],
    "storm center": ["commotion", "disruption", "disturbance", "flutter", "hoo-ha", "hoo-hah", "hurly burly", "kerfuffle", "storm centre", "to-do"],
    "storm cloud": ["cloud"],
    "storm cone": ["storm signal"],
    "storm door": ["door"],
    "storm petrel": ["hydrobates pelagicus", "mother carey's chicken", "mother carey's hen", "northern storm petrel", "oceanites oceanicus", "petrel", "stormy petrel"],
    "storm signal": ["sign", "signal", "signaling", "storm cone"],
    "storm trooper": ["german nazi", "nazi"],
    "storm window": ["storm sash", "window"],
    "storm-beaten": [],
    "stormbound": [],
    "stormily": ["passionately", "turbulently"],
    "storminess": ["bad weather", "boisterousness", "breeziness", "choppiness", "inclemency", "inclementness", "rough water", "roughness", "tempestuousness", "windiness"],
    "stormproof": [],
    "stormy": ["tempestuous"],
    "stormy petrel": ["hydrobates pelagicus", "northern storm petrel", "storm petrel"],
    "story": ["adventure story", "allegory", "apologue", "fable", "fiction", "heroic tale", "legend", "love story", "mystery", "mystery story", "myth", "parable", "plot", "romance", "short story", "whodunit"],
    "storybook": ["book"],
    "storyline": ["plot", "plot line"],
    "storyteller": ["fabricator", "fibber", "liar", "prevaricator"],
    "stotinka": ["bulgarian monetary unit"],
    "stoup": ["drinking vessel"],
    "stout": ["ale", "guinness"],
    "stout-billed": [],
    "stout-stemmed": [],
    "stoutheartedness": ["braveness", "bravery", "courage", "courageousness"],
    "stoutly": [],
    "stoutness": ["stalwartness", "strength"],
    "stove": ["charcoal burner", "cooking stove", "cookstove", "electric range", "gas cooker", "gas range", "gas stove", "kitchen appliance", "kitchen range", "kitchen stove", "potbelly", "potbelly stove", "primus", "primus stove", "range", "spirit stove"],
    "stove bolt": ["bolt"],
    "stovepipe": ["chimney"],
    "stovepipe iron": ["plate iron"],
    "stovepiped": [],
    "stovepiping": ["retrieval"],
    "stover": ["fodder"],
    "stow": ["pack"],
    "stow away": ["hide", "hide out"],
    "stowage": ["charge"],
    "stowaway": ["passenger", "rider"],
    "stowe": ["harriet beecher stowe", "harriet elizabeth beecher stowe"],
    "stp": ["atm", "atmosphere", "s.t.p.", "standard atmosphere", "standard pressure", "standard temperature"],
    "strabismus": ["abnormalcy", "abnormality", "convergent strabismus", "cross-eye", "crossed eye", "divergent strabismus", "esotropia", "exotropia", "squint", "walleye"],
    "strabotomy": ["operation", "surgery", "surgical operation", "surgical procedure", "surgical process"],
    "strachey": ["giles lytton strachey", "lytton strachey"],
    "stradavarius": ["fiddle", "strad", "violin"],
    "straddle": ["be"],
    "stradivari": ["antonio stradivari", "antonius stradivarius", "stradivarius"],
    "strafe": ["assail", "attack"],
    "strafer": ["combat pilot"],
    "straggle": ["group", "grouping"],
    "straggler": ["dawdler", "drone", "laggard", "lagger", "poke", "strayer", "trailer"],
    "straggly": [],
    "straight": ["poker hand"],
    "straight and narrow": ["path", "strait and narrow", "way", "way of life"],
    "straight angle": ["angular unit"],
    "straight chain": ["open chain"],
    "straight chair": ["chair", "side chair", "windsor chair"],
    "straight face": ["facial expression", "facial gesture"],
    "straight flush": ["poker hand"],
    "straight flute": ["bore bit", "borer", "rock drill", "stone drill", "straight-fluted drill"],
    "straight hang": ["hang"],
    "straight line": ["asymptote", "bias", "chord", "diagonal", "diameter", "element", "line", "perpendicular", "radius", "secant", "tangent", "vector"],
    "straight man": ["performer", "performing artist", "second banana"],
    "straight pin": ["pin"],
    "straight poker": ["poker", "poker game"],
    "straight razor": ["razor"],
    "straight sinus": ["sinus", "sinus rectus", "tentorial sinus", "venous sinus"],
    "straight ticket": ["ballot", "balloting", "vote", "voting"],
    "straight-arm": ["evasive action", "maneuver", "manoeuvre"],
    "straight-backed": [],
    "straight-billed": [],
    "straight-grained": [],
    "straight-legged": [],
    "straight-line method": ["depreciation", "straight-line method of depreciation", "wear and tear"],
    "straightarrow": [],
    "straightaway": ["section", "segment", "straight", "stretch"],
    "straightedge": ["hand tool"],
    "straighten": ["change posture", "unbend"],
    "straightener": ["device"],
    "straightforward": [],
    "straightness": ["curvature", "curve"],
    "straightway": [],
    "strain": ["tense", "tighten"],
    "strain gauge": ["gage", "gauge", "strain gage"],
    "strained": [],
    "strainer": ["colander", "cullender", "filter", "screen", "sieve", "tea-strainer"],
    "strait": ["channel", "narrow", "sound"],
    "strait of dover": ["pas de calais", "strait of calais"],
    "strait of georgia": [],
    "strait of gibraltar": [],
    "strait of hormuz": ["strait of ormuz"],
    "strait of magellan": [],
    "strait of messina": [],
    "straiten": ["bother", "discommode", "disoblige", "distress", "incommode", "inconvenience", "put out", "trouble"],
    "straitjacket": ["balk", "baulk", "check", "deterrent", "handicap", "hinderance", "hindrance", "impediment"],
    "strand": ["land"],
    "strange": ["unusual"],
    "strange attractor": ["attracter", "attractor", "chaotic attractor"],
    "strange particle": ["elementary particle", "fundamental particle"],
    "strange quark": ["quark", "squark"],
    "strangeness": ["flavor", "flavour"],
    "stranger": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "strangle": ["garotte", "garrote", "garrotte", "kill", "scrag", "strangulate", "throttle"],
    "stranglehold": ["chokehold", "power", "powerfulness", "throttlehold"],
    "strangler": ["aerophyte", "air plant", "clusia major", "clusia rosea", "epiphyte", "epiphytic plant", "pitch apple", "strangler fig", "strangler tree"],
    "strangulate": ["compact", "compress", "constrict", "contract", "press", "squeeze"],
    "strangulation": ["disorder", "upset"],
    "strap": ["bind", "hobble", "hopple", "tie"],
    "strap fern": ["campyloneurum augustifolium", "central american strap fern", "cow-tongue fern", "fern", "florida strap fern", "hart's-tongue fern", "narrow-leaved strap fern"],
    "strap hinge": ["flexible joint", "hinge", "joint hinge"],
    "straphanger": ["commuter"],
    "strapless": ["dress", "frock"],
    "straplike": [],
    "strappado": ["strapado", "torture", "torturing"],
    "strasberg": ["israel strassberg", "lee strasberg"],
    "strasbourg": ["strassburg"],
    "strategic": ["strategical"],
    "strategic arms limitation talks": ["salt"],
    "strategic buyout": ["buyout"],
    "strategic intelligence": ["intelligence", "intelligence activity", "intelligence operation"],
    "strategic warning": ["warning", "warning of war"],
    "strategically": [],
    "strategics": ["science", "scientific discipline"],
    "strategist": ["contriver", "deviser", "market strategist", "planner", "strategian"],
    "strategy": ["military science"],
    "stratford-on-avon": ["stratford-upon-avon"],
    "stratification": ["condition", "social stratification"],
    "stratified": ["bedded"],
    "stratified language": ["programing language", "programming language"],
    "stratified sample": ["proportional sample", "representative sample", "sample", "sample distribution", "sampling"],
    "stratified sampling": ["proportional sampling", "representative sampling", "sampling"],
    "stratify": ["change"],
    "stratigraphy": ["geology"],
    "stratosphere": ["layer"],
    "stratum": ["bed", "cambium", "corium", "corneum", "cuticle", "derma", "dermis", "epidermis", "horizon", "horny layer", "layer", "malpighian layer", "paries", "rete malpighii", "seam", "stratum basale", "stratum corneum", "stratum germinativum", "stratum granulosum", "stratum lucidum", "substrate", "substratum", "superstrate", "superstratum", "wall"],
    "stratum corneum": ["corneum", "horny layer", "stratum"],
    "stratum germinativum": ["malpighian layer", "rete malpighii", "stratum", "stratum basale"],
    "stratum granulosum": ["stratum"],
    "stratum lucidum": ["stratum"],
    "stratus": ["altostratus", "altostratus cloud", "cloud", "stratus cloud"],
    "strauss": ["richard strauss"],
    "stravinsky": ["igor fyodorovich stravinsky", "igor stravinsky"],
    "stravinskyan": ["stravinskian"],
    "straw": ["cover"],
    "straw boss": ["assistant foreman", "boss", "chief", "foreman", "gaffer", "honcho"],
    "straw man": ["specious argument", "strawman"],
    "straw mushroom": ["agaric", "chinese mushroom", "volvariella volvacea"],
    "straw vote": ["canvass", "opinion poll", "poll", "public opinion poll", "straw poll"],
    "straw wine": ["dessert wine"],
    "straw-colored": ["straw-coloured"],
    "strawberry": ["beach strawberry", "chilean strawberry", "cultivated strawberry", "fragaria ananassa", "fragaria chiloensis", "fragaria vesca", "fragaria virginiana", "garden strawberry", "herb", "herbaceous plant", "scarlet strawberry", "virginia strawberry", "wild strawberry", "wood strawberry"],
    "strawberry blite": ["chenopodium capitatum", "goosefoot", "indian paint", "strawberry pigweed"],
    "strawberry bush": ["bush", "euonymus americanus", "shrub", "wahoo"],
    "strawberry daiquiri": ["daiquiri", "rum cocktail"],
    "strawberry geranium": ["breakstone", "mother-of-thousands", "rockfoil", "saxifraga sarmentosam", "saxifraga stolonifera", "saxifrage", "strawberry saxifrage"],
    "strawberry hemangioma": ["haemangioma", "hemangioma", "strawberry haemangioma"],
    "strawberry ice cream": ["ice cream", "icecream"],
    "strawberry jam": ["jam", "strawberry preserves"],
    "strawberry tomato": ["dwarf cape gooseberry", "ground cherry", "husk tomato", "physalis pruinosa"],
    "strawberry tree": ["arbutus", "arbutus unedo", "irish strawberry"],
    "strawboard": ["cardboard", "composition board"],
    "strawflower": ["bellwort", "cornflower", "merry bells", "uvularia grandiflora", "wild oats"],
    "strawworm": ["jointworm", "larva"],
    "stray": ["drift", "err", "go", "locomote", "move", "travel"],
    "straying": [],
    "streak": ["move"],
    "streaked": ["streaky"],
    "streaker": ["exhibitionist", "flasher", "nude", "nude person"],
    "stream": ["be adrift", "blow", "drift", "float"],
    "stream of consciousness": ["prose"],
    "stream orchid": ["chatterbox", "epipactis gigantea", "giant helleborine", "helleborine"],
    "streambed": ["bed", "bottom", "creek bed", "dry wash", "wash"],
    "streamer": ["light", "visible light", "visible radiation"],
    "streamer fly": ["fly"],
    "streaming": [],
    "streamline": ["contour"],
    "streamline flow": ["flow", "laminar flow"],
    "streamlined": ["aerodynamic", "flowing", "sleek"],
    "streamliner": ["railroad train", "train"],
    "streep": ["meryl streep"],
    "street": ["environment"],
    "street address": ["address"],
    "street arab": ["gamin", "guttersnipe", "street urchin", "throwaway"],
    "street cleaner": ["cleaner", "street sweeper"],
    "street clothes": ["article of clothing", "clothing", "habiliment", "vesture", "wear", "wearable"],
    "street credibility": ["believability", "cred", "credibility", "credibleness", "street cred"],
    "street fighter": ["challenger", "competition", "competitor", "contender", "rival"],
    "street name": ["appellation", "appellative", "denomination", "designation"],
    "street sign": ["address", "sign"],
    "street smarts": ["astuteness", "perspicaciousness", "perspicacity", "shrewdness"],
    "street urchin": ["gamin", "gamine", "guttersnipe", "street arab", "throwaway", "urchin"],
    "street-walk": ["prostitute", "streetwalk"],
    "streetcar": ["horsecar", "self-propelled vehicle", "tram", "tramcar", "trolley", "trolley car"],
    "streetlight": ["lamp", "street lamp"],
    "streetwalker": ["bawd", "cocotte", "cyprian", "fancy woman", "floozie", "floozy", "harlot", "hooker", "hustler", "lady of pleasure", "prostitute", "slattern", "sporting lady", "street girl", "tart", "whore", "woman of the street", "working girl"],
    "streetwise": ["street smart", "with-it"],
    "streisand": ["barbra joan streisand", "barbra streisand"],
    "strekelia": ["genus strekelia", "liliid monocot genus"],
    "strelitzia": ["genus strelitzia", "liliopsid genus", "monocot genus"],
    "strelitziaceae": ["family strelitziaceae", "liliopsid family", "monocot family", "strelitzia family"],
    "strength": ["prosperity", "successfulness"],
    "strengthen": ["alter", "batten", "batten down", "beef up", "brace", "brace up", "buttress", "change", "confirm", "fortify", "modify", "reenforce", "reinforce", "restrengthen", "ruggedise", "ruggedize", "secure", "stabilise", "stabilize", "steady", "substantiate", "undergird", "vitalise", "vitalize"],
    "strengthener": ["backing", "brace", "bracing", "device", "mount", "reinforcement", "safety arch"],
    "strengthening": ["shift", "transformation", "transmutation"],
    "strenuous": [],
    "strenuously": [],
    "strepera": ["bird genus", "genus strepera"],
    "strepsirhini": ["animal order", "suborder strepsirhini"],
    "streptobacillus": ["rod"],
    "streptocarpus": ["cape primrose", "flower"],
    "streptococcal": ["strep", "streptococcic"],
    "streptococcal sore throat": ["infection", "pharyngitis", "raw throat", "septic sore throat", "sore throat", "strep throat", "streptococcus tonsilitis", "throat infection"],
    "streptococcus": ["eubacteria", "eubacterium", "strep", "streptococci", "true bacteria"],
    "streptococcus anhemolyticus": ["bacteria species"],
    "streptodornase": ["enzyme"],
    "streptokinase": ["enzyme"],
    "streptolysin": ["erythrocytolysin", "erythrolysin", "haemolysin", "hemolysin"],
    "streptomyces": ["actinomycete", "potato scab bacteria", "streptomyces erythreus", "streptomyces griseus", "streptomyces scabies"],
    "streptomyces erythreus": ["streptomyces"],
    "streptomyces griseus": ["streptomyces"],
    "streptomycetaceae": ["bacteria family", "family streptomycetaceae"],
    "streptomycin": ["antibiotic", "antibiotic drug"],
    "streptopelia": ["bird genus", "genus streptopelia"],
    "streptopelia turtur": ["turtledove"],
    "streptosolen": ["asterid dicot genus", "genus streptosolen"],
    "streptothricin": ["antibiotic", "antibiotic drug"],
    "stress": ["accent", "accentuate", "background", "bear down", "bring out", "downplay", "drive home", "emphasise", "emphasize", "evince", "express", "play down", "point up", "press home", "punctuate", "ram home", "re-emphasise", "re-emphasize", "set off", "show", "topicalize", "underline", "underscore"],
    "stress incontinence": ["enuresis", "urinary incontinence"],
    "stress mark": ["accent", "accent mark"],
    "stress test": ["assay", "check", "treadmill test"],
    "stressed": ["distressed"],
    "stressor": ["agent"],
    "stretch": ["be", "stretch along"],
    "stretch mark": ["band", "banding", "stria", "striation"],
    "stretch pants": ["pant", "trouser"],
    "stretch receptor": ["receptor", "sense organ", "sensory receptor"],
    "stretch reflex": ["inborn reflex", "innate reflex", "instinctive reflex", "myotactic reflex", "physiological reaction", "reflex", "reflex action", "reflex response", "unconditioned reflex"],
    "stretchable": ["stretchy"],
    "stretched": [],
    "stretcher": ["framework"],
    "stretcher party": ["company", "party"],
    "stretcher-bearer": ["attendant", "attender", "litter-bearer", "tender"],
    "stretching": ["enlargement", "expansion", "extension", "tension"],
    "streusel": ["pastry"],
    "strew": ["bestrew", "distribute", "litter", "spread", "straw"],
    "stria": ["channel", "groove", "striation"],
    "striate": ["mark"],
    "striate cortex": ["area 17 of brodmann", "brodmann's area 17", "cortical area", "cortical region", "first visual area", "striate area"],
    "striated muscle cell": ["muscle cell", "muscle fiber", "muscle fibre", "striated muscle fiber"],
    "striated muscle tissue": ["muscle", "muscular tissue"],
    "strickland": ["william strickland"],
    "strickle": ["even", "even out", "flush", "level"],
    "strictly": ["stringently"],
    "strictness": ["conscientiousness", "painstakingness", "stringency"],
    "stricture": ["criticism", "unfavorable judgment"],
    "stride": ["walk"],
    "strident": ["shrill"],
    "stridently": [],
    "strider": ["footer", "pedestrian", "walker"],
    "stridor": ["symptom"],
    "stridulate": ["clitter", "make noise", "noise", "resound"],
    "stridulation": ["noise"],
    "strife": ["battle", "conflict", "countercurrent", "crosscurrent", "discord", "discordance", "struggle"],
    "strigidae": ["bird family", "family strigidae"],
    "strigiformes": ["animal order", "order strigiformes"],
    "strike": ["dissent", "protest", "resist", "walk out"],
    "strike a blow": ["affect", "bear on", "bear upon", "impact", "touch", "touch on"],
    "strike a chord": ["arouse", "elicit", "enkindle", "evoke", "fire", "kindle", "provoke", "raise", "touch a chord"],
    "strike down": ["kill"],
    "strike dumb": ["affect", "impress", "move", "strike"],
    "strike leader": ["leader"],
    "strike out": ["fail", "go wrong", "miscarry"],
    "strike pay": ["earnings", "pay", "remuneration", "salary", "wage"],
    "strike up": ["initiate", "pioneer"],
    "strike zone": ["zone"],
    "strike-slip fault": ["break", "fault", "faulting", "fracture", "geological fault", "shift"],
    "strikebound": [],
    "strikebreaking": ["confrontation", "opposition"],
    "strikeout": ["out", "whiff"],
    "striker": ["athlete", "jock"],
    "strikingly": [],
    "strindberg": ["august strindberg", "johan august strindberg"],
    "string": ["advance", "go on", "march on", "move on", "pass on", "progress", "string along"],
    "string bean": ["green bean"],
    "string cheese": ["cheese"],
    "string of words": ["language", "linguistic communication", "linguistic string", "sentence", "string", "syntagm", "syntagma", "word string"],
    "string orchestra": ["orchestra"],
    "string out": ["arrange", "set up", "spread out"],
    "string quartet": ["quartet", "quartette", "string quartette"],
    "string section": ["section", "strings", "violin section"],
    "string theory": ["framework", "model", "theoretical account"],
    "string tie": ["necktie", "tie"],
    "stringed instrument": ["banjo", "bowed stringed instrument", "chordophone", "cither", "clavichord", "clavier", "dulcimer", "forte-piano", "guitar", "instrument", "klavier", "koto", "musical instrument", "piano", "pianoforte", "psaltery", "samisen", "shamisen", "sitar", "string", "zither", "zithern"],
    "stringency": ["deficiency", "lack", "tightness", "want"],
    "stringer": ["participant", "player"],
    "stringy": ["wiry"],
    "stringybark": ["eucalypt", "eucalyptus", "eucalyptus tree", "eucalyptusd eugenioides", "thin-leaved stringybark", "white stringybark"],
    "stringybark pine": ["callitris parlatorei", "cypress pine"],
    "strip": ["remove", "take", "take away", "withdraw"],
    "strip alert": ["alert", "qui vive"],
    "strip cropping": ["agriculture", "farming", "husbandry"],
    "strip lighting": ["light", "light source"],
    "strip mall": ["mercantile establishment", "outlet", "retail store", "sales outlet"],
    "strip mine": ["mine", "surface mine", "surface-mine"],
    "strip miner": ["miner", "mineworker"],
    "strip mining": ["excavation", "mining", "opencast mining"],
    "strip poker": ["poker", "poker game"],
    "strip search": ["frisk", "frisking"],
    "strip steak": ["beefsteak", "new york strip"],
    "strip-mined": [],
    "strip-search": ["search"],
    "stripe": ["mark"],
    "stripe blight": ["blight"],
    "striped": ["stripy"],
    "striped bass": ["bass", "sea bass", "striper"],
    "striped button quail": ["bustard quail", "button quail", "button-quail", "hemipode", "turnix sylvatica"],
    "striped coral root": ["coral root", "corallorhiza striata"],
    "striped drum": ["drum", "drumfish", "equetus pulcher"],
    "striped gentian": ["gentian", "gentiana villosa"],
    "striped hyena": ["hyaena", "hyaena hyaena", "hyena"],
    "striped killifish": ["fundulus majalis", "killifish", "may fish", "mayfish"],
    "striped marlin": ["makaira mitsukurii", "marlin"],
    "striped muishond": ["ictonyx striata", "muishond"],
    "striped mullet": ["gray mullet", "grey mullet", "mugil cephalus", "mullet"],
    "striped skunk": ["mephitis mephitis", "polecat", "skunk", "wood pussy"],
    "striper": ["man", "military man", "military personnel", "serviceman"],
    "striping": ["marking"],
    "stripped": ["stripped-down"],
    "stripper": ["chemical compound", "compound"],
    "stripper well": ["oil well", "oiler", "stripper"],
    "strive": ["bother", "drive", "extend oneself", "inconvenience oneself", "kill oneself", "labor", "labour", "overexert oneself", "push", "reach", "strain", "trouble", "trouble oneself", "tug"],
    "striving": ["attempt", "effort", "endeavor", "endeavour", "jehad", "jihad", "nisus", "pains", "strain", "try"],
    "strix": ["bird genus", "genus strix"],
    "strobilomyces": ["fungus genus", "genus strobilomyces"],
    "stroboscope": ["scientific instrument", "strobe", "strobe light"],
    "stroheim": ["erich von stroheim"],
    "stroke": ["caress", "fondle", "lap", "lick", "touch"],
    "stroll": ["saunter", "walk"],
    "stroma": ["plant tissue"],
    "stromateidae": ["family stromateidae", "fish family"],
    "strombidae": ["family strombidae", "mollusk family"],
    "strombus": ["genus strombus", "mollusk genus"],
    "strong": [],
    "strong breeze": ["air", "breeze", "gentle wind", "zephyr"],
    "strong gale": ["gale"],
    "strong interaction": ["color force", "fundamental interaction", "interaction", "strong force"],
    "strong suit": ["long suit"],
    "strong-arm": ["do by", "handle", "treat"],
    "strong-boned": [],
    "strong-flavored": [],
    "strong-minded": ["strong-willed"],
    "strong-smelling": ["strong-scented"],
    "strongbox": ["box", "cashbox", "deedbox", "deposit box", "lockbox", "money box", "safe", "safe-deposit", "safe-deposit box", "safety deposit box", "safety-deposit", "till"],
    "stronghold": ["bastion", "blockhouse", "citadel", "defence", "defense", "defensive structure", "donjon", "dungeon", "fastness", "hold", "keep", "redoubt"],
    "strongly": [],
    "strongman": ["performer", "performing artist"],
    "strongroom": ["bank vault", "storage room", "storeroom", "stowage", "vault"],
    "strongylodon": ["genus strongylodon", "rosid dicot genus"],
    "strontianite": ["mineral"],
    "strontium": ["atomic number 38", "metal", "metallic element", "sr", "strontium 90"],
    "strontium 90": ["atomic number 38", "sr", "strontium"],
    "strop": ["sharpen"],
    "strophanthin": ["glycoside"],
    "strophanthus": ["bush", "shrub", "strophanthus kombe"],
    "strophanthus kombe": ["strophanthus"],
    "stropharia": ["fungus genus", "genus stropharia", "ring-stalked fungus"],
    "stropharia ambigua": ["agaric"],
    "stropharia hornemannii": ["agaric"],
    "stropharia rugoso-annulata": ["agaric"],
    "strophariaceae": ["family strophariaceae", "fungus family"],
    "strophe": ["stanza"],
    "structural": [],
    "structural formula": ["molecular formula"],
    "structural gene": ["cistron", "factor", "gene"],
    "structural genomics": ["genomics"],
    "structural iron": ["atomic number 26", "fe", "iron"],
    "structural member": ["beam", "brace", "bracing", "plate", "riser", "sill", "support", "tread", "upright", "vertical"],
    "structural steel": ["steel"],
    "structuralism": ["linguistics", "structural linguistics"],
    "structurally": [],
    "structure": ["coordinate", "organise", "organize", "reconstitute", "restructure"],
    "structured": [],
    "strudel": ["pastry"],
    "struggle": ["endeavor", "endeavour", "strive"],
    "struggler": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "struggling": [],
    "strum": ["sound", "thrum"],
    "strung": [],
    "strut": ["brace", "bracing"],
    "struthio": ["bird genus", "genus struthio"],
    "struthiomimus": ["ornithomimid"],
    "struthionidae": ["bird family", "family struthionidae"],
    "struthioniformes": ["animal order", "order struthioniformes"],
    "strychnine": ["alkaloid", "phytotoxin", "plant toxin"],
    "strymon": ["arthropod genus", "genus strymon"],
    "strymon melinus": ["hairstreak", "hairstreak butterfly"],
    "stuart": ["gilbert charles stuart", "gilbert stuart"],
    "stub": ["deracinate", "extirpate", "root out", "uproot"],
    "stub nail": ["nail"],
    "stub out": ["crush out", "end", "extinguish", "press out", "terminate"],
    "stubble": ["beard", "face fungus", "whiskers"],
    "stubborn": ["obstinate", "unregenerate"],
    "stubbornly": ["cussedly", "mulishly", "obdurately", "obstinately", "pig-headedly"],
    "stubbornness": ["intractability", "intractableness", "mulishness", "obstinacy", "obstinance"],
    "stubbs": ["william stubbs"],
    "stubby": [],
    "stucco": ["adorn", "beautify", "decorate", "embellish", "grace", "ornament"],
    "stuck": [],
    "stud": ["add"],
    "stud farm": ["farm"],
    "stud finder": ["permanent magnet", "static magnet"],
    "studbook": ["register", "registry"],
    "studded": [],
    "student": ["art student", "auditor", "catechumen", "college boy", "college man", "collegian", "crammer", "educatee", "enrollee", "etonian", "ivy leaguer", "law student", "major", "medical student", "medico", "neophyte", "nonachiever", "nonreader", "overachiever", "passer", "pupil", "scholar", "seminarian", "seminarist", "sixth-former", "skipper", "underachiever", "underperformer", "withdrawer", "wykehamist"],
    "student center": ["center", "centre"],
    "student lamp": ["reading lamp"],
    "student teacher": ["college student", "practice teacher", "university student"],
    "student union": ["building", "edifice"],
    "studentship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "studied": [],
    "studio": ["work", "workplace"],
    "studio apartment": ["apartment", "flat", "studio"],
    "studio couch": ["convertible", "day bed", "sofa bed"],
    "studious": [],
    "studiously": [],
    "studiousness": ["bookishness", "diligence", "industriousness", "industry"],
    "study": ["chew over", "compare", "consider", "contemplate", "equate", "excogitate", "factor", "factor in", "factor out", "liken", "meditate", "mull", "mull over", "muse", "ponder", "reflect", "ruminate", "speculate", "think over"],
    "study hall": ["period", "period of time", "time period"],
    "stuff": ["chock up", "cram", "fill out", "jam", "jampack", "overstuff", "pad", "ram", "wad"],
    "stuffed": [],
    "stuffed cabbage": ["dish"],
    "stuffed mushroom": ["hors d'oeuvre"],
    "stuffed peppers": ["dish"],
    "stuffed shirt": ["bore", "dullard"],
    "stuffed tomato": ["cold stuffed tomato", "dish"],
    "stuffer": ["bill", "broadsheet", "broadside", "circular", "flier", "flyer", "handbill", "throwaway"],
    "stuffily": ["stodgily"],
    "stuffiness": ["congestion"],
    "stuffing": ["concoction", "dressing", "farce", "forcemeat", "intermixture", "mixture", "oyster dressing", "oyster stuffing", "turkey stuffing"],
    "stuffing box": ["chamber", "packing box"],
    "stuffing nut": ["nut", "packing nut"],
    "stuffy": [],
    "stultification": ["befooling", "derision"],
    "stultify": ["demonstrate", "establish", "prove", "shew", "show"],
    "stumble": ["come by", "come into", "hit"],
    "stumblebum": ["boxer", "palooka", "pugilist"],
    "stumbler": ["footer", "pedestrian", "tripper", "walker"],
    "stumbling block": ["obstacle"],
    "stump": ["campaign", "run"],
    "stump speech": ["oratory"],
    "stumping": ["campaigning", "candidacy", "candidature", "electioneering", "political campaign"],
    "stun": ["bedaze", "daze", "desensitise", "desensitize"],
    "stun gun": ["arm", "stun baton", "weapon", "weapon system"],
    "stunner": ["surprise"],
    "stunning": [],
    "stunt": ["dwarf", "hinder", "impede"],
    "stupa": ["shrine", "tope"],
    "stupefaction": ["amazement", "astonishment", "daze", "shock", "stupor"],
    "stupefying": [],
    "stupendously": [],
    "stupid": ["berk", "blockhead", "bonehead", "dolt", "dullard", "dumbass", "dunce", "dunderhead", "fuckhead", "hammerhead", "klutz", "knucklehead", "loggerhead", "lunkhead", "muttonhead", "numskull", "pillock", "poor fish", "pudden-head", "pudding head", "shithead", "simple", "simpleton", "stupe", "stupid person"],
    "stupidity": ["backwardness", "craziness", "denseness", "dullness", "dumbness", "folly", "foolishness", "inability", "madness", "mental retardation", "obtuseness", "retardation", "slow-wittedness", "slowness", "subnormality", "vacuousness"],
    "stupidly": ["doltishly"],
    "sturdily": [],
    "sturdiness": ["good health", "healthiness"],
    "sturdy": ["tough"],
    "sturgeon": ["acipenser huso", "acipenser transmontanus", "beluga", "ganoid", "ganoid fish", "hausen", "pacific sturgeon", "sacramento sturgeon", "white sturgeon"],
    "sturnella": ["bird genus", "genus sturnella"],
    "sturnidae": ["bird family", "family sturnidae"],
    "sturnus": ["bird genus", "genus sturnus"],
    "stuttgart": [],
    "stuyvesant": ["peter stuyvesant", "petrus stuyvesant"],
    "sty": ["eye infection", "hordeolum", "infection", "stye"],
    "stygian": [],
    "style": ["create", "make", "pompadour"],
    "style sheet": ["piece of paper", "sheet", "sheet of paper"],
    "styleless": ["unstylish"],
    "stylet": ["style"],
    "stylish": ["fashionable"],
    "stylishly": [],
    "stylist": ["artist", "creative person"],
    "stylistic": [],
    "stylistically": [],
    "stylite": ["abstainer", "ascetic"],
    "stylization": ["conventionalisation", "conventionalization", "normalisation", "normalization", "standardisation", "standardization", "stylisation"],
    "stylize": ["conventionalize", "interpret", "represent", "stylise"],
    "styloid process": ["appendage", "outgrowth", "process"],
    "stylomastoid vein": ["vein", "vena", "vena stylomastoidea", "venous blood vessel"],
    "stylomecon": ["dilleniid dicot genus", "genus stylomecon"],
    "stylophorum": ["dilleniid dicot genus", "genus stylophorum"],
    "stylopodium": ["style"],
    "stylus": ["device", "needle", "phonograph needle"],
    "stymie": ["position", "situation", "stymy"],
    "styphelia": ["dilleniid dicot genus", "genus styphelia"],
    "styptic": ["hemostatic"],
    "styracaceae": ["dicot family", "family styracaceae", "magnoliopsid family", "storax family", "styrax family"],
    "styracosaur": ["ceratopsian", "horned dinosaur", "styracosaurus"],
    "styrax": ["bush", "japanese snowbell", "shrub", "snowbell", "styrax japonicum", "styrax obassia", "styrax texana", "texas snowbell", "texas snowbells"],
    "styrene": ["cinnamene", "phenylethylene", "polystyrene", "polyvinyl resin", "vinyl polymer", "vinyl resin", "vinylbenzene"],
    "styrofoam": ["foam", "polystyrene"],
    "styron": ["william styron"],
    "styx": ["river styx"],
    "suavely": [],
    "suavity": ["blandness", "graciousness", "smoothness", "suaveness"],
    "sub judice": [],
    "sub rosa": [],
    "sub-assembly": ["assembly"],
    "sub-interval": ["interval"],
    "sub-rosa": ["behind-the-scenes", "under-the-table"],
    "sub-saharan": [],
    "sub-saharan africa": ["black africa"],
    "sub-test": ["mental test", "mental testing", "psychometric test", "test"],
    "subacid": [],
    "subacute": [],
    "subacute bacterial endocarditis": ["endocarditis"],
    "subacute sclerosing panencephalitis": ["bosin's disease", "dawson's encephalitis", "inclusion body encephalitis", "panencephalitis", "sclerosing leukoencephalitis", "sspe", "subacute inclusion body encephalitis", "subacute sclerosing leukoencephalitis", "van bogaert encephalitis"],
    "subalpine larch": ["larch", "larch tree", "larix lyallii"],
    "subaltern": ["commissioned military officer"],
    "subaqueous": ["subaquatic", "submerged", "submersed", "underwater"],
    "subarachnoid space": ["space"],
    "subarctic": [],
    "subartesian": [],
    "subatomic": [],
    "subbase": ["molding", "moulding"],
    "subbing": ["substituting", "work"],
    "subclass": ["taxon", "taxonomic category", "taxonomic group"],
    "subclavian": [],
    "subclavian artery": ["arteria", "arteria subclavia", "arterial blood vessel", "artery"],
    "subclavian vein": ["vein", "vena", "vena subclavia", "venous blood vessel"],
    "subclinical": [],
    "subclinical absence": ["absence", "absence seizure"],
    "subcommittee": ["commission", "committee"],
    "subcompact": ["auto", "automobile", "car", "machine", "motorcar", "subcompact car"],
    "subconscious": [],
    "subconscious mind": ["brain", "head", "mind", "nous", "psyche", "subconscious"],
    "subconsciously": [],
    "subconsciousness": ["cognitive state", "state of mind"],
    "subcontinent": ["land mass", "landmass"],
    "subcontract": ["employ", "engage", "farm out", "hire", "job"],
    "subcontractor": ["contractor"],
    "subcortical": [],
    "subculture": ["psychedelia", "social group", "suburbia", "youth culture"],
    "subcutaneous injection": ["injection", "shot"],
    "subcutaneously": [],
    "subdata base": ["database"],
    "subdeacon": ["clergyman", "holy order", "man of the cloth", "order", "reverend"],
    "subdirectory": ["directory"],
    "subdivide": ["divide", "part", "separate"],
    "subdivider": ["divider"],
    "subdivision": ["parcel", "parcel of land", "piece of ground", "piece of land", "tract"],
    "subdominant": ["musical note", "note", "tone"],
    "subduable": ["subjugable"],
    "subduction": ["geologic process", "geological process"],
    "subdued": [],
    "subduer": ["controller", "overcomer", "restrainer", "surmounter"],
    "subdural": [],
    "subeditor": ["editor", "editor in chief"],
    "suberic acid": ["carboxylic acid", "octanedioic acid"],
    "subfamily": ["latinae", "taxon", "taxonomic category", "taxonomic group"],
    "subfigure": ["branch", "facet", "figure", "flank", "hemisphere", "leg", "ramification"],
    "subfusc": [],
    "subgenus": ["taxon", "taxonomic category", "taxonomic group"],
    "subgenus azalea": ["azaleastrum", "dilleniid dicot genus", "subgenus azaleastrum"],
    "subgenus calliopsis": ["asterid dicot genus"],
    "subgross": [],
    "subgroup": ["bench", "group", "grouping"],
    "subheading": ["head", "header", "heading", "subhead", "title"],
    "subhuman": [],
    "subjacent": [],
    "subject": ["affect", "bacterise", "bacterize", "bear on", "bear upon", "expose", "impact", "incur", "put", "refract", "shipwreck", "touch", "touch on", "vitriol"],
    "subjective": [],
    "subjectively": [],
    "subjectivism": ["philosophical doctrine", "philosophical theory"],
    "subjectivist": ["intellect", "intellectual"],
    "subjectivity": ["judgement", "judgment", "perspicacity", "sound judgement", "sound judgment", "subjectiveness"],
    "subjoin": ["append", "hang on", "tack", "tack on", "tag on"],
    "subjugate": ["dominate", "dragoon", "enslave", "master", "subject"],
    "subjugated": [],
    "subjugation": ["bondage", "captivity", "confinement", "enslavement", "oppression", "peonage", "relationship", "repression", "slavery", "subjection", "thraldom", "thrall", "thralldom"],
    "subjugator": ["conqueror", "vanquisher"],
    "subjunctive": [],
    "subjunctive mood": ["modality", "mode", "mood", "subjunctive"],
    "subkingdom": ["metazoa", "parazoa", "subkingdom metazoa", "subkingdom parazoa", "taxon", "taxonomic category", "taxonomic group"],
    "sublease": ["lease", "letting", "rental", "sublet"],
    "sublet": ["lease", "let", "rent", "sublease"],
    "sublieutenant": ["lieutenant"],
    "sublimate": ["airt", "desexualise", "desexualize", "redirect"],
    "sublimation": ["shift", "transformation", "transmutation"],
    "sublime": ["aerify", "gasify", "sublimate", "vaporise", "vaporize"],
    "sublimed": ["sublimated"],
    "sublimely": [],
    "subliminal": [],
    "sublimity": ["grandeur", "magnanimousness", "nobility", "nobleness"],
    "sublingual": [],
    "sublingual gland": ["salivary gland", "sublingual salivary gland"],
    "sublingual vein": ["vein", "vena", "vena sublingualis", "venous blood vessel"],
    "subliterary": [],
    "sublittoral": [],
    "sublunar": ["cislunar", "sublunary"],
    "subluxate": ["injure", "wound"],
    "subluxation": ["luxation"],
    "submachine gun": ["bren", "bren gun", "burp gun", "kalashnikov", "light machine gun", "machine gun", "machine pistol", "sten gun", "thompson submachine gun", "tommy gun", "uzi"],
    "submarine": ["skid", "slew", "slide", "slip", "slue"],
    "submarine ball": ["delivery", "pitch", "submarine pitch"],
    "submarine torpedo": ["torpedo"],
    "submariner": ["bluejacket", "navy man", "sailor", "sailor boy"],
    "submaxillary gland": ["mandibular gland", "salivary gland", "submandibular gland", "submandibular salivary gland", "submaxillary salivary gland"],
    "submediant": ["musical note", "note", "tone"],
    "submerge": ["dive", "go down", "go under", "settle", "sink", "submerse"],
    "submerged": ["submersed", "underwater"],
    "submergence": ["dip", "immersion", "sinking", "submerging", "submersion"],
    "submersible": ["apparatus", "bathyscape", "bathyscaph", "bathyscaphe", "bathysphere", "diving bell", "minisub", "minisubmarine", "setup"],
    "submersion": ["dousing", "ducking", "immersion", "wetting"],
    "submission": ["condition", "status"],
    "submissive": [],
    "submissiveness": ["obedience", "obsequiousness", "passiveness", "passivity", "servility", "subordination", "subservience"],
    "submit": ["subject"],
    "submitter": ["follower"],
    "submucosa": ["connective tissue"],
    "subnormal": ["simple", "simpleton"],
    "subnormality": ["abnormalcy", "abnormality"],
    "suboceanic": ["subocean"],
    "suborbital": [],
    "suborder": ["taxon", "taxonomic category", "taxonomic group"],
    "suborder ceratosaura": ["animal order"],
    "suborder pachycephalosaurus": ["animal order"],
    "subordinate": ["grade", "order", "outclass", "place", "range", "rank", "rate"],
    "subordinate clause": ["clause", "dependent clause", "descriptive clause", "nonrestrictive clause", "restrictive clause"],
    "subordinateness": ["handmaid", "handmaiden", "inferiority", "junior status", "lower rank", "lower status", "servant", "subservience", "subservientness", "subsidiarity"],
    "subordinating": ["subordinative"],
    "subordinating conjunction": ["conjunction"],
    "subordination": ["dependance", "dependence", "dependency"],
    "suborn": ["corrupt", "debase", "debauch", "demoralise", "demoralize", "deprave", "misdirect", "pervert", "profane", "subvert", "vitiate"],
    "subornation": ["incitement", "provocation", "subornation of perjury"],
    "subornation of perjury": ["subornation"],
    "subpart": ["component", "component part", "constituent", "part", "portion"],
    "subphylum": ["taxon", "taxonomic category", "taxonomic group"],
    "subpoena": ["process", "serve", "swear out"],
    "subpoena duces tecum": ["judicial writ", "writ"],
    "subpopulation": ["population", "universe"],
    "subrogate": ["exchange", "interchange", "replace", "substitute"],
    "subrogation": ["commutation", "exchange", "substitution"],
    "subscribe": ["bid", "offer", "tender"],
    "subscribed": [],
    "subscriber": ["admirer", "booster", "champion", "endorser", "friend", "indorser", "protagonist", "ratifier", "supporter"],
    "subscript": ["character", "grapheme", "graphic symbol", "inferior"],
    "subscription": ["payment"],
    "subscription right": ["pre-emption", "preemption"],
    "subscription warrant": ["stock warrant", "stock-purchase warrant", "warrant"],
    "subsection": ["section", "segment", "subdivision"],
    "subsequent": [],
    "subsequently": ["after", "afterward", "afterwards", "later", "later on"],
    "subserve": ["aid", "assist", "help"],
    "subservience": ["condition", "status"],
    "subservient": [],
    "subset": ["set"],
    "subshrub": ["aeonium haworthii", "american feverfew", "american spikenard", "amsonia tabernaemontana", "aralia hispida", "aralia nudicaulis", "aralia racemosa", "argyranthemum frutescens", "avens", "babies' slippers", "bacon and eggs", "bastard pimpernel", "beach heather", "beggar lice", "beggar's lice", "beggar's-ticks", "beggar-ticks", "bird's foot clover", "bird's foot trefoil", "bloodleaf", "blue curls", "blue star", "bristly sarsaparilla", "bristly sarsparilla", "bur marigold", "burdock", "burr marigold", "bush", "california tree poppy", "caltrop", "cassia fasciculata", "cassia tora", "centaury", "chaffweed", "chamaecrista fasciculata", "chrysanthemum frutescens", "cleome pinnata", "clotbur", "compass plant", "coral gem", "corchorus", "cube", "darling pea", "deer grass", "desert plume", "devil's weed", "diapensia", "dryas octopetala", "dwarf elder", "eringo", "eriogonum", "eryngo", "false heather", "false pimpernel", "false sarsaparilla", "french honeysuckle", "germander", "golden heather", "guayule", "hedysarum boreale", "hedysarum coronarium", "hippocrepis comosa", "hoary pea", "horseshoe vetch", "hudsonia ericoides", "hudsonia tomentosa", "indian beet", "jerusalem sage", "kiss-me-over-the-garden-gate", "life-of-man", "linnaea borealis", "loosestrife", "lotus americanus", "lotus berthelotii", "lotus corniculatus", "lupinus perennis", "marguerite", "marguerite daisy", "marsh rosemary", "matchbush", "matchweed", "matilija poppy", "meadow beauty", "milkwort", "mountain avens", "old-maid's bonnet", "ononis repens", "ononis spinosa", "pachysandra", "paris daisy", "parthenium argentatum", "parthenium integrifolium", "partridge pea", "periwinkle", "petty morel", "phlomis", "phlomis fruticosa", "pinwheel", "poison bush", "polygonum orientale", "poverty grass", "prairie bird's-foot trefoil", "prairie dock", "prairie lotus", "prairie trefoil", "prince's-feather", "prince's-plume", "princess feather", "prunus besseyi", "rest-harrow", "restharrow", "rocky mountains cherry", "romneya coulteri", "sage brush", "sagebrush", "sea lavender", "senna obtusifolia", "sensitive pea", "shrub", "sicklepod", "st john's wort", "stanleya pinnata", "statice", "sticktight", "suffrutex", "sulla", "sundial lupine", "sweet vetch", "thrift", "tick trefoil", "tribulus terestris", "twinflower", "western sand cherry", "wild lupine", "wild quinine", "wild sarsaparilla", "wild sarsparilla", "wild sensitive plant", "woodruff", "wormwood"],
    "subside": ["dip", "sink"],
    "subsidiary company": ["company", "subsidiary"],
    "subsidiary ledger": ["account book", "book", "book of account", "ledger", "leger"],
    "subsidization": ["money", "subsidisation"],
    "subsidize": ["pay", "subsidise"],
    "subsidized": ["subsidised"],
    "subsidizer": ["bestower", "conferrer", "donor", "giver", "presenter", "subsidiser"],
    "subsidy": ["grant", "price support", "subvention"],
    "subsistence": ["endurance", "survival"],
    "subsistence farming": ["agriculture", "farming", "husbandry"],
    "subsoil": ["dirt", "soil", "undersoil"],
    "subsonic": [],
    "subspace": ["mathematical space", "topological space"],
    "subspecies": ["race", "taxon", "taxonomic category", "taxonomic group"],
    "substance": ["physical entity"],
    "substance abuse": ["abuse", "alcohol abuse", "alcoholic abuse", "alcoholism abuse", "drug abuse", "habit", "misuse"],
    "substantia nigra": ["locus niger", "neural structure", "nucleus niger"],
    "substantial": ["substantive"],
    "substantiality": ["corporality", "corporeality", "materiality", "physicalness", "solidness", "substantialness"],
    "substantially": [],
    "substantiate": ["beef up", "fortify", "strengthen"],
    "substantival": [],
    "substantive": ["noun", "word"],
    "substation": ["station"],
    "substitutable": [],
    "substitute": ["cover", "deputise", "deputize", "replace", "step in", "supercede", "supersede", "supervene upon", "supplant"],
    "substitution": ["fluctuation", "permutation", "replacement", "switch", "transposition", "variation"],
    "substitution class": ["category", "class", "family", "paradigm"],
    "substrate": ["substance"],
    "substring": ["string"],
    "subsume": ["include"],
    "subsumption": ["categorisation", "categorization", "classification", "sorting"],
    "subsurface": [],
    "subsystem": ["scheme", "system"],
    "subtend": ["be", "delimit"],
    "subterfuge": ["blind", "deceit", "deception", "misrepresentation"],
    "subterminal": [],
    "subterranean": ["subterraneous"],
    "subthalamic nucleus": ["cell nucleus", "karyon", "nucleus"],
    "subthalamus": ["neural structure"],
    "subtilin": ["antibiotic", "antibiotic drug"],
    "subtilize": ["discriminate", "know apart"],
    "subtitle": ["furnish", "provide", "render", "supply"],
    "subtle": [],
    "subtlety": ["difficultness", "difficulty", "niceness"],
    "subtly": [],
    "subtonic": ["leading tone", "musical note", "note", "tone"],
    "subtopia": ["conurbation", "sprawl", "urban sprawl"],
    "subtotal": ["amount", "sum", "total"],
    "subtract": ["calculate", "carry back", "cipher", "compute", "cypher", "deduct", "figure", "reckon", "take off", "work out"],
    "subtracter": ["calculator", "computer", "estimator", "figurer", "reckoner"],
    "subtraction": ["arithmetic operation", "minus"],
    "subtractive": [],
    "subtrahend": ["number"],
    "subtreasury": ["exchequer", "treasury"],
    "subtropical": ["semitropic", "semitropical", "subtropic"],
    "subtropics": ["climatic zone", "semitropics"],
    "subularia": ["dilleniid dicot genus", "genus subularia"],
    "suburb": ["addition", "bedroom community", "community", "faubourg", "residential area", "residential district", "stockbroker belt", "suburban area", "suburbia"],
    "suburban": [],
    "suburbanite": ["occupant", "occupier", "resident"],
    "suburbanize": ["change", "suburbanise"],
    "suburbanized": ["suburbanised"],
    "suburbia": ["subculture"],
    "subvention": ["subsidy"],
    "subversion": ["overthrow", "subversive activity"],
    "subvert": ["destroy", "ruin"],
    "subvocalize": ["articulate", "enounce", "enunciate", "pronounce", "say", "sound out", "subvocalise"],
    "subvocalizer": ["articulator", "subvocaliser"],
    "subway fare": ["train fare"],
    "subway station": ["depot", "terminal", "terminus"],
    "subway token": ["token"],
    "subway train": ["railroad train", "train"],
    "subwoofer": ["loudspeaker", "loudspeaker system", "speaker", "speaker system", "speaker unit"],
    "succedaneum": ["replacement", "substitute"],
    "succeed": ["accomplish", "achieve", "act", "arrive", "attain", "bring home the bacon", "bring off", "carry off", "clear", "come through", "deliver the goods", "get in", "go far", "hit", "hit the jackpot", "luck out", "make it", "manage", "nail", "nail down", "negociate", "pan out", "pass", "peg", "pull off", "reach", "run", "win", "work"],
    "succeeding": [],
    "success": ["big time", "pay dirt", "prosperity", "successfulness"],
    "successful": [],
    "successfully": [],
    "succession": ["action", "activity", "ecological succession", "natural action", "natural process"],
    "successively": ["in turn"],
    "successor": ["compeer", "equal", "match", "peer", "replacement"],
    "succinctly": ["compactly"],
    "succinic": [],
    "succinic acid": ["carboxylic acid"],
    "succinylcholine": ["muscle relaxant"],
    "succor": ["aid", "assist", "help", "succour"],
    "succorer": ["recoverer", "rescuer", "saver", "succourer"],
    "succotash": ["dish"],
    "succoth": ["church festival", "feast of booths", "feast of tabernacles", "jewish holy day", "religious festival", "succos", "sukkoth", "tabernacles"],
    "succubus": ["daemon", "daimon", "demon", "devil", "fiend", "succuba"],
    "succulence": ["appetisingness", "appetizingness", "juiciness", "succulency"],
    "succulent": ["aloe", "cactus", "carpobrotus edulis", "dorotheanthus bellidiformis", "flowering stone", "hottentot fig", "hottentot's fig", "lithops", "living granite", "living rock", "living stone", "livingstone daisy", "mesembryanthemum edule", "sour fig", "stone life face", "stone mimicry plant", "stone plant", "stone-face", "stoneface", "tracheophyte", "vascular plant"],
    "succumb": ["buy the farm", "cash in one's chips", "choke", "conk", "croak", "decease", "die", "drop dead", "exit", "expire", "give-up the ghost", "go", "kick the bucket", "pass", "pass away", "perish", "pop off", "snuff it", "yield"],
    "succuss": ["agitate", "shake", "shake up"],
    "succussion": ["auscultation"],
    "such": [],
    "suchlike": [],
    "suck": ["absorb", "suck in", "take in"],
    "suck in": ["core out", "draw in", "hollow", "hollow out"],
    "sucker": ["shoot"],
    "sucker punch": ["biff", "clout", "lick", "poke", "punch", "slug"],
    "sucking": ["consumption", "ingestion", "intake", "suck", "suction", "uptake"],
    "sucking pig": ["piggy", "piglet", "shoat", "shote"],
    "suckle": ["eat", "feed"],
    "suckling": ["sir john suckling"],
    "suckling reflex": ["inborn reflex", "innate reflex", "instinctive reflex", "physiological reaction", "reflex", "reflex action", "reflex response", "unconditioned reflex"],
    "sucralfate": ["carafate", "medicament", "medication", "medicinal drug", "medicine"],
    "sucre": ["ecuadoran monetary unit"],
    "sucrose": ["brain sugar", "disaccharide", "galactose", "plant product", "saccharose"],
    "suction": [],
    "suction cup": ["device"],
    "suction curettage": ["curettage", "curettement", "induced abortion", "vacuum aspiration"],
    "suction pump": ["pump", "stomach pump", "sump pump"],
    "suction stop": ["click", "occlusive", "plosive", "plosive consonant", "plosive speech sound", "stop", "stop consonant"],
    "suctorial": [],
    "sudan": ["republic of the sudan", "soudan"],
    "sudanese": ["african"],
    "sudanese monetary unit": ["monetary unit", "pound", "sudanese pound"],
    "sudanese pound": ["pound", "sudanese monetary unit"],
    "sudatorium": ["bagnio", "bathhouse", "sudatory"],
    "sudbury": [],
    "sudden": [],
    "sudden death": ["extra time", "overtime"],
    "sudden infant death syndrome": ["cot death", "crib death", "death", "infant death", "sids", "sleep apnea"],
    "suddenly": ["all of a sudden", "of a sudden"],
    "sudoku": ["mystifier", "puzzle", "puzzler", "teaser"],
    "sudorific": ["medicament", "medication", "medicinal drug", "medicine", "sudatory"],
    "sudra": ["shudra", "varna"],
    "suds": ["launder", "wash"],
    "sue": ["eugene sue"],
    "suede": ["leather", "suede leather"],
    "suede cloth": ["cloth", "fabric", "material", "suede", "textile", "ultrasuede"],
    "suer": ["complainant", "petitioner", "plaintiff"],
    "suet": ["edible fat"],
    "suet pudding": ["pudding", "spotted dick"],
    "suety": [],
    "suez": [],
    "suez canal": [],
    "suffer": ["be given", "incline", "lean", "run", "tend"],
    "sufferance": ["endurance"],
    "suffering": ["miserableness", "misery", "woe", "wretchedness"],
    "suffice": ["answer", "bridge over", "do", "fulfil", "fulfill", "function", "go a long way", "go around", "keep going", "live up to", "measure up", "qualify", "satisfy", "serve", "tide over"],
    "sufficiency": ["wealth", "wealthiness"],
    "sufficient": [],
    "sufficiently": [],
    "suffix": ["affix"],
    "suffixation": ["affixation"],
    "suffocate": ["asphyxiate", "block", "choke", "close up", "impede", "jam", "obstruct", "obturate", "occlude", "stifle"],
    "suffocation": ["asphyxiation", "hypoxia"],
    "suffragan": ["bishop", "suffragan bishop"],
    "suffragette": ["feminist", "libber", "suffragist", "women's liberationist", "women's rightist"],
    "suffragism": ["belief"],
    "suffragist": ["advocate", "advocator", "exponent", "proponent", "suffragette"],
    "suffrutescent": [],
    "suffuse": ["change"],
    "suffusive": [],
    "sufi": ["moslem", "muslim"],
    "sufism": ["mysticism", "religious mysticism"],
    "sugar": ["dulcify", "dulcorate", "edulcorate", "saccharify", "sweeten"],
    "sugar beet": ["beet", "beta vulgaris", "common beet"],
    "sugar bowl": ["dish"],
    "sugar candy": ["candy", "confect"],
    "sugar cookie": ["biscuit", "cookie", "cooky"],
    "sugar daddy": ["steady", "sweetheart", "sweetie", "truelove"],
    "sugar maple": ["acer saccharum", "maple", "rock maple"],
    "sugar palm": ["arenga pinnata", "gomuti", "gomuti palm", "sago palm"],
    "sugar refinery": ["refinery"],
    "sugar snap pea": ["edible-pod pea", "edible-podded pea", "pisum sativum macrocarpon", "snap pea"],
    "sugar spoon": ["spoon", "sugar shell"],
    "sugar syrup": ["sirup", "syrup"],
    "sugar water": ["drinking water"],
    "sugar-bush": ["rhus ovata", "shumac", "sugar sumac", "sumac", "sumach"],
    "sugarberry": ["celtis laevigata", "hackberry", "nettle tree"],
    "sugarcane": ["cane", "sugar cane"],
    "sugarcoat": ["candy", "dulcify", "dulcorate", "edulcorate", "glaze", "sweeten"],
    "sugared": ["sweet", "sweet-flavored", "sweetened"],
    "sugariness": ["sweet", "sweetness"],
    "sugarless": ["nonsweet"],
    "sugarloaf": ["loaf", "loaf sugar", "refined sugar", "sugar", "sugar loaf"],
    "sugarplum": ["candy", "confect"],
    "sugary": [],
    "suggest": ["imply", "intimate", "make out"],
    "suggester": ["conceiver", "mastermind", "originator", "proposer"],
    "suggestibility": ["susceptibility", "susceptibleness"],
    "suggestible": [],
    "suggestion": ["persuasion", "prompting", "suasion"],
    "suggestive": [],
    "suggestively": [],
    "suharto": [],
    "sui generis": [],
    "suicide": ["felo-de-se", "killer", "slayer"],
    "suicide bomber": ["kamikaze", "terrorist"],
    "suicide bombing": ["bombing"],
    "suicide mission": ["charge", "commission", "martyr operation", "mission", "sacrifice operation"],
    "suicide pact": ["agreement", "understanding"],
    "suicide pill": ["poison pill"],
    "suicide squeeze play": ["squeeze play", "suicide squeeze"],
    "suidae": ["family suidae", "mammal family"],
    "suillus": ["fungus genus", "genus suillus"],
    "suillus albivelatus": ["bolete"],
    "suit": ["agree", "be"],
    "suitability": ["appropriateness", "convenience", "fitness", "fittingness", "quality", "suitableness"],
    "suitable": ["suited"],
    "suite": ["bedroom set", "bedroom suite", "diningroom set", "diningroom suite", "livingroom set", "livingroom suite", "set"],
    "suited": [],
    "suiting": ["cloth", "fabric", "material", "textile"],
    "suitor": ["admirer", "adorer", "prince charming", "suer", "wooer"],
    "sukarno": ["achmad sukarno"],
    "sukiyaki": ["dish"],
    "suksdorfia": ["herb", "herbaceous plant", "suksdorfia violaceae", "violet suksdorfia"],
    "sukur": ["biu-mandara"],
    "sula": ["bird genus", "genus sula"],
    "sulcate": [],
    "sulcus": ["calcarine fissure", "calcarine sulcus", "central sulcus", "fissure", "fissure of rolando", "fissure of sylvius", "lateral cerebral sulcus", "parieto-occipital fissure", "parieto-occipital sulcus", "rolando's fissure", "sulcus centralis", "sulcus lateralis cerebri", "sylvian fissure"],
    "sulfa drug": ["antibacterial", "antibacterial drug", "bactericide", "gantanol", "gantrisin", "sulamyd", "sulfa", "sulfacetamide", "sulfadiazine", "sulfamethazine", "sulfamethoxazole", "sulfamezathine", "sulfanilamide", "sulfapyridine", "sulfisoxazole", "sulfonamide", "sulpha", "thiosulfil"],
    "sulfacetamide": ["sulamyd", "sulfa", "sulfa drug", "sulfonamide", "sulpha"],
    "sulfadiazine": ["sulfa", "sulfa drug", "sulfonamide", "sulpha"],
    "sulfamethazine": ["sulfa", "sulfa drug", "sulfamezathine", "sulfonamide", "sulpha"],
    "sulfamethoxazole": ["gantanol", "sulfa", "sulfa drug", "sulfonamide", "sulpha"],
    "sulfanilamide": ["sulfa", "sulfa drug", "sulfonamide", "sulpha"],
    "sulfanilic acid": ["acid", "sulphanilic acid"],
    "sulfapyridine": ["sulfa", "sulfa drug", "sulfonamide", "sulpha"],
    "sulfate": ["convert"],
    "sulfide": ["cadmium sulfide", "chemical compound", "compound", "hydrogen sulfide", "iron disulfide", "pyrites", "sulphide", "zinc sulfide", "zinc sulphide"],
    "sulfisoxazole": ["gantrisin", "sulfa", "sulfa drug", "sulfonamide", "sulpha"],
    "sulfonate": ["alkylbenzenesulfonate", "salt"],
    "sulfonic acid": ["acid", "sulphonic acid"],
    "sulfonylurea": ["antidiabetic", "antidiabetic drug", "orinase", "tolazamide", "tolbutamide", "tolinase"],
    "sulfur": ["atomic number 16", "brimstone", "chemical element", "element", "native sulfur", "native sulphur", "s", "sulphur"],
    "sulfur dioxide": ["dioxide", "gas", "pollutant", "sulphur dioxide"],
    "sulfur hexafluoride": ["fluoride", "greenhouse emission", "greenhouse gas", "sulphur hexafluoride"],
    "sulfur oxide": ["oxide", "sulphur oxide"],
    "sulfur paintbrush": ["castilleja sulphurea", "indian paintbrush", "painted cup"],
    "sulfur-yellow": ["sulphur-yellow"],
    "sulfurette": ["combine", "compound", "sulphurette"],
    "sulfurous": ["sulphurous"],
    "sulidae": ["bird family", "family sulidae"],
    "sulindac": ["clinoril", "nonsteroidal anti-inflammatory", "nonsteroidal anti-inflammatory drug", "nsaid"],
    "sulk": ["brood", "grizzle", "pout", "stew"],
    "sulkily": [],
    "sulkiness": ["bitterness", "gall", "huffishness", "rancor", "rancour", "resentment"],
    "sulky": ["horse-drawn vehicle"],
    "sulla": ["lucius cornelius sulla felix"],
    "sullivan": ["louis henri sullivan", "louis henry sullivan", "louis sullivan"],
    "sully": ["thomas sully"],
    "sulphur": ["process", "sulfur", "treat"],
    "sulphur butterfly": ["butterfly", "sulfur butterfly"],
    "sulphur mine": ["mine", "sulfur mine"],
    "sulphur-crested cockatoo": ["cacatua galerita", "cockatoo", "kakatoe galerita"],
    "sulphuretted": ["sulfuretted", "sulfurized"],
    "sulphuric": ["sulfuric"],
    "sultan": ["grand turk", "ruler", "swayer"],
    "sultana": ["vinifera grape"],
    "sultanate": ["country", "land", "state"],
    "sultriness": ["hot weather"],
    "sultry": ["stifling", "sulfurous", "sulphurous"],
    "sum": ["advance", "amount", "amount of money", "assets", "cash advance", "cash surrender value", "contribution", "coverage", "deductible", "defalcation", "figure", "gain", "gross", "insurance coverage", "loss", "payroll", "paysheet", "peanuts", "purse", "receipts", "red", "red ink", "revenue", "sum of money"],
    "sum up": ["abstract", "docket", "ingeminate", "iterate", "precis", "recap", "recapitulate", "reiterate", "repeat", "restate", "resume", "retell", "summarise", "summarize"],
    "sumac": ["wood"],
    "sumatra": [],
    "sumatran": ["indonesian"],
    "sumer": [],
    "sumerian": ["babylonian"],
    "sumerology": ["archaeology", "archeology"],
    "summa cum laude": [],
    "summarily": [],
    "summarization": ["account", "report", "summarisation"],
    "summarize": ["say", "state", "sum", "sum up", "summarise", "tell"],
    "summary": ["abridgement", "abridgment", "abstract", "argument", "capitulation", "capsule", "compendium", "condensation", "conspectus", "curriculum vitae", "cv", "line score", "literary argument", "outline", "overview", "precis", "resume", "roundup", "rundown", "sketch", "statement", "sum-up", "summation", "summing up", "survey", "synopsis"],
    "summary judgment": ["judgement", "judgement on the pleadings", "judgment", "judgment on the pleadings", "judicial decision", "summary judgement"],
    "summate": ["combine"],
    "summation": ["biological process", "organic process"],
    "summational": ["summative"],
    "summer": ["pass", "spend"],
    "summer cypress": ["bassia scoparia", "belvedere", "burning bush", "bush", "fire bush", "fire-bush", "kochia scoparia", "shrub"],
    "summer flounder": ["lefteye flounder", "lefteyed flounder", "paralichthys dentatus"],
    "summer house": ["country house"],
    "summer hyacinth": ["cape hyacinth", "galtonia candicans", "hyacinth", "hyacinthus candicans"],
    "summer savory": ["satureia hortensis", "satureja hortensis", "savory"],
    "summer school": ["academic session", "academic term", "school term", "session"],
    "summer solstice": ["june 21", "midsummer", "solstice"],
    "summer squash": ["cucurbita pepo melopepo", "cymling", "marrow", "marrow squash", "pattypan squash", "spaghetti squash", "squash", "squash vine", "summer squash vine", "vegetable marrow", "yellow squash"],
    "summer stock": ["staging", "theatrical production"],
    "summer tanager": ["piranga rubra", "summer redbird", "tanager"],
    "summer-flowering": ["summer-blooming"],
    "summercaters": ["vacationer", "vacationist"],
    "summerize": ["fix", "gear up", "prepare", "ready", "set", "set up", "summerise"],
    "summery": [],
    "summit": ["arrive at", "attain", "breast", "gain", "hit", "make", "reach"],
    "summon": ["beckon", "buzz", "call", "convene", "convoke", "page", "send for"],
    "summons": ["call up", "order"],
    "summum bonum": ["good", "goodness"],
    "sumner": ["william graham sumner"],
    "sumo": ["grappling", "rassling", "sport", "wrestling"],
    "sumo ring": ["ring"],
    "sumo wrestler": ["grappler", "matman", "wrestler"],
    "sump": ["reservoir"],
    "sump pump": ["suction pump"],
    "sumpsimus": ["expression", "locution", "saying"],
    "sumptuary": [],
    "sumptuously": ["opulently"],
    "sun": ["expose", "insolate", "solarise", "solarize"],
    "sun bathing": ["bathing"],
    "sun city": [],
    "sun dance": ["ceremonial dance", "ritual dance", "ritual dancing"],
    "sun deck": ["deck"],
    "sun gear": ["cogwheel", "gear", "gear wheel", "geared wheel"],
    "sun god": ["deity", "divinity", "god", "immortal"],
    "sun parlor": ["room", "solarium", "sun lounge", "sun parlour", "sun porch", "sunporch", "sunroom"],
    "sun pitcher": ["pitcher plant"]
}
