synonyms = {
    "tactful": [],
    "tactfully": [],
    "tactic": ["maneuver", "manoeuvre", "plan of action", "tactics"],
    "tactical": [],
    "tactical intelligence": ["combat intelligence", "intelligence", "intelligence activity", "intelligence operation", "terrain intelligence"],
    "tactical warning": ["warning", "warning of attack"],
    "tactically": [],
    "tactician": ["contriver", "deviser", "planner"],
    "tactics": ["military science"],
    "tactile": ["tactual"],
    "tactile property": ["feel", "property", "texture", "touch"],
    "tactless": ["untactful"],
    "tactlessly": [],
    "tactlessness": ["inconsiderateness", "inconsideration", "thoughtlessness"],
    "tactual sensation": ["skin perceptiveness", "somaesthesia", "somaesthesis", "somataesthesis", "somatesthesia", "somatic sense", "somatic sensory system", "somatosensory system", "somesthesia", "somesthesis", "tactility", "touch perception"],
    "tactually": ["haptically"],
    "tad": ["shade", "small indefinite amount", "small indefinite quantity"],
    "tadalafil": ["anti-impotence drug", "cialis", "virility drug"],
    "tadarida": ["genus tadarida", "mammal genus"],
    "tadorna": ["bird genus", "genus tadorna"],
    "tadpole": ["larva", "polliwog", "pollywog"],
    "tadpole shrimp": ["branchiopod", "branchiopod crustacean", "branchiopodan"],
    "tadpole-shaped": [],
    "tae kwon do": ["martial art", "taekwondo"],
    "taegu": ["tegu"],
    "tael": ["weight", "weight unit"],
    "taenia": ["fillet", "headband", "tenia"],
    "taeniidae": ["family taeniidae", "worm family"],
    "taffeta": ["cloth", "fabric", "material", "textile"],
    "taffrail": ["rail", "railing"],
    "taffy": ["candy", "confect", "molasses taffy"],
    "taft": ["lorado taft"],
    "tag": ["rhyme", "rime"],
    "tag along": ["accompany"],
    "tagalog": ["filipino"],
    "tagalong": ["follower", "hanger-on"],
    "tagasaste": ["bush", "chamaecytisus palmensis", "cytesis proliferus", "shrub"],
    "tageteste": ["asterid dicot genus", "genus tagetes"],
    "tagger": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "tagliatelle": ["alimentary paste", "pasta"],
    "tagore": ["rabindranath tagore", "sir rabindranath tagore"],
    "taguan": ["asiatic flying squirrel", "flying cat", "flying marmot", "petaurista petaurista"],
    "tagus": ["tagus river"],
    "tahini": ["paste", "spread"],
    "tahiti": [],
    "tahitian": ["polynesian"],
    "tahoka daisy": ["machaeranthera tanacetifolia", "tansy leaf aster", "wild flower", "wildflower"],
    "tai": ["black tai", "bouyei", "buyi", "central thai", "chinese shan", "dehong dai", "kadai", "kadai language", "kam muang", "kam-tai", "khamti", "khuen", "lao", "nung", "red tai", "saek", "shan", "siamese", "southern tai", "tai dam", "tai long", "tai lue", "tai nuea", "tai yuan", "tay", "thai", "tho", "white tai", "xishuangbanna dai", "yay", "zhuang"],
    "tai dam": ["black tai", "tai"],
    "tai long": ["shan", "tai"],
    "tai lue": ["tai", "xishuangbanna dai"],
    "tai nuea": ["chinese shan", "dehong dai", "tai"],
    "tai yuan": ["kam muang", "tai"],
    "taichung": [],
    "taif": [],
    "tail": ["pinch", "top"],
    "tail feather": ["flight feather", "pinion", "quill", "quill feather", "sickle feather"],
    "tail fin": ["decoration", "fin", "ornament", "ornamentation", "tailfin"],
    "tail gate": ["gate"],
    "tail rotor": ["anti-torque rotor", "rotor"],
    "tail-shaped": [],
    "tailback": ["back"],
    "tailed": [],
    "tailed frog": ["anuran", "ascaphus trui", "batrachian", "bell toad", "frog", "ribbed toad", "salientian", "tailed toad", "toad", "toad frog"],
    "tailgate": ["follow"],
    "tailgater": ["driver"],
    "tailless tenrec": ["tendrac", "tenrec", "tenrec ecaudatus"],
    "taillight": ["lamp", "rear lamp", "rear light", "tail lamp"],
    "tailor": ["accommodate", "adapt", "orient"],
    "tailor's chalk": ["chalk"],
    "tailor's tack": ["embroidery stitch", "sewing stitch"],
    "tailor-made": ["article of clothing", "clothing", "habiliment", "vesture", "wear", "wearable"],
    "tailorbird": ["old world warbler", "orthotomus sutorius", "true warbler"],
    "tailored": ["trim"],
    "tailoring": ["craft", "trade"],
    "tailpiece": ["appendage"],
    "tailpipe": ["pipage", "pipe", "piping"],
    "tailrace": ["watercourse", "waterway"],
    "tailspin": ["agitation"],
    "tailstock": ["support"],
    "tailwind": ["air current", "current of air", "wind"],
    "taimyr peninsula": ["taymyr peninsula"],
    "taipan": ["elapid", "elapid snake", "oxyuranus scutellatus"],
    "taipei": ["capital of taiwan", "taipeh"],
    "taiwan": ["china", "nationalist china", "republic of china"],
    "taiwan dollar": ["dollar"],
    "taiwanese": ["asian", "asiatic"],
    "taiyuan": [],
    "taj mahal": [],
    "tajik": ["asian", "asiatic", "tadzhik"],
    "tajiki": ["iranian", "iranian language", "tadzhik", "tajik"],
    "tajikistan": ["republic of tajikistan", "tadjik", "tadzhik", "tadzhikistan", "tajik"],
    "tajikistani": [],
    "tajikistani monetary unit": ["monetary unit", "ruble", "tanga"],
    "taka": ["bangladeshi monetary unit"],
    "takakkaw": [],
    "takayasu's arteritis": ["arteritis", "pulseless disease"],
    "take": ["act", "move"],
    "take a bow": ["accept"],
    "take a dare": [],
    "take a dive": ["affect", "dissemble", "feign", "pretend", "sham"],
    "take a hit": ["do drugs", "drug", "snort"],
    "take a joke": ["abide", "bear", "brook", "digest", "endure", "put up", "stand", "stick out", "stomach", "suffer", "support", "tolerate"],
    "take a look": ["get a load", "have a look", "look"],
    "take after": ["resemble"],
    "take away": ["take"],
    "take back": ["relate"],
    "take care": ["act", "move"],
    "take down": ["abase", "chagrin", "degrade", "dehumanise", "dehumanize", "demean", "disgrace", "humble", "humiliate", "mortify", "put down", "reduce"],
    "take effect": ["become", "get", "go"],
    "take five": ["break", "intermit", "pause"],
    "take heart": ["buck up", "cheer", "embolden", "hearten", "recreate"],
    "take hold": ["head", "lead", "move in on", "take charge", "take control"],
    "take home": ["bring home", "bring in", "clear", "earn", "gain", "make", "pull in", "realise", "realize", "take in"],
    "take in": ["domiciliate", "house", "put up"],
    "take in vain": ["abuse", "misuse", "pervert"],
    "take it on the chin": ["fail", "go wrong", "miscarry"],
    "take kindly to": ["be given", "incline", "lean", "run", "tend"],
    "take lying down": ["abide", "bear", "brook", "digest", "endure", "put up", "stand", "stick out", "stomach", "suffer", "support", "tolerate"],
    "take notice": ["mark", "note", "notice"],
    "take off": ["break up", "cut off", "disrupt", "interrupt", "take time off"],
    "take office": ["accede", "adopt", "assume", "enter", "start", "take on", "take over", "take up"],
    "take one's lumps": ["get one's lumps", "pay"],
    "take orders": ["obey"],
    "take out": ["call in", "clear", "estrange", "move out", "remove"],
    "take over": ["discharge", "free", "relieve", "spell"],
    "take pains": ["be at pains", "endeavor", "endeavour", "strive"],
    "take pride": ["experience", "feel", "pride oneself"],
    "take ten": ["break", "intermit", "pause"],
    "take the bull by the horns": ["confront", "face"],
    "take the cake": ["win"],
    "take the count": ["lose", "remain down"],
    "take the field": ["come in", "enter", "get in", "get into", "go in", "go into", "move into"],
    "take the fifth": ["declare", "take the fifth amendment"],
    "take the floor": ["arise", "get up", "rise", "stand up", "uprise"],
    "take the road": ["tour"],
    "take the stage": ["take stage"],
    "take the veil": ["profess"],
    "take time by the forelock": ["act", "move"],
    "take to": [],
    "take up": ["fill", "occupy"],
    "take water": ["come in", "enter", "get in", "get into", "go in", "go into", "move into"],
    "take-home": [],
    "take-home pay": ["earnings", "pay", "remuneration", "salary", "wage"],
    "take-in": ["deceit", "deception", "dissembling", "dissimulation"],
    "take-up": ["device"],
    "takeaway": ["concession"],
    "takedown": ["fall", "pin"],
    "takelma": ["penutian"],
    "taken": [],
    "takeoff": ["ascension", "ascent", "rise", "rising"],
    "takeout": ["convenience food", "takeaway", "takeout food"],
    "takeover": ["buyout", "friendly takeover", "hostile takeover"],
    "takeover attempt": ["attempt", "bear hug", "effort", "endeavor", "endeavour", "proxy fight", "try"],
    "takeover bid": ["any-and-all bid", "tender offer", "two-tier bid"],
    "taker": ["client", "customer"],
    "takilman": ["penutian", "takelma"],
    "takin": ["budorcas taxicolor", "gnu goat", "goat antelope"],
    "taklimakan desert": ["taklamakan desert"],
    "tala": ["western samoan monetary unit"],
    "talapoin": ["cercopithecus talapoin", "guenon", "guenon monkey"],
    "talaria": ["sandal"],
    "talbot": ["fox talbot", "william henry fox talbot"],
    "talc": ["powder"],
    "talcum": ["bath powder", "dusting powder", "talcum powder", "toilet powder"],
    "talent": ["expert"],
    "talent agent": ["agent"],
    "talented": ["gifted"],
    "talentlessness": ["inaptitude"],
    "taliban": ["religious movement", "taleban"],
    "talinum": ["caryophylloid dicot genus", "genus talinum"],
    "talipes calcaneus": ["clubfoot", "talipes"],
    "talipes equinus": ["clubfoot", "talipes"],
    "talipes valgus": ["clubfoot", "talipes"],
    "talipot": ["corypha umbraculifera", "fan palm", "talipot palm"],
    "talismanic": [],
    "talk": ["butterfly", "carry on", "chat up", "cheek", "communicate", "continue", "converse", "coquet", "coquette", "dally", "discourse", "dish the dirt", "dissertate", "dogmatise", "dogmatize", "flirt", "go on", "gossip", "hold forth", "intercommunicate", "level", "mash", "monologuise", "monologuize", "orate", "philander", "pontificate", "proceed", "rap", "romance", "soliloquise", "soliloquize", "speak", "spiel", "talk down", "talk turkey"],
    "talk down": ["speak", "talk"],
    "talk into": ["persuade"],
    "talk of": ["blaspheme", "discuss", "hash out", "mouth", "speak", "talk", "talk about", "talk over", "utter", "verbalise", "verbalize"],
    "talk out of": ["deter", "dissuade"],
    "talk shop": ["discourse", "discuss", "talk about"],
    "talk show": ["broadcast", "chat show", "phone-in", "program", "programme"],
    "talk through one's hat": ["affect", "bull", "bullshit", "dissemble", "fake", "feign", "pretend", "sham"],
    "talk turkey": ["speak", "talk"],
    "talking book": ["audio", "audio recording", "sound recording"],
    "talking head": ["speaker", "talker", "utterer", "verbaliser", "verbalizer"],
    "talking picture": ["film", "flick", "motion picture", "motion-picture show", "movie", "moving picture", "moving-picture show", "pic", "picture", "picture show", "talkie"],
    "talking point": ["point"],
    "tall": ["size"],
    "tall bellflower": ["bellflower", "campanula", "campanula americana"],
    "tall cupflower": ["cupflower", "nierembergia", "nierembergia frutescens"],
    "tall gallberry holly": ["holly"],
    "tall goldenrod": ["goldenrod"],
    "tall mallow": ["cheese", "cheeseflower", "high mallow", "mallow", "malva sylvestris"],
    "tall oat grass": ["arrhenatherum elatius", "evergreen grass", "false oat", "french rye", "grass", "tall meadow grass"],
    "tall oil": ["oil"],
    "tall order": ["labor", "large order", "project", "task", "undertaking"],
    "tall tale": ["narration", "narrative", "story", "tale"],
    "tall yellow-eye": ["xyris operculata", "yellow-eyed grass"],
    "tallahassee": ["capital of florida"],
    "tallapoosa": ["tallapoosa river"],
    "tallchief": ["maria tallchief"],
    "talleyrand": ["charles maurice de talleyrand"],
    "tallgrass": ["grass", "tall-grass"],
    "tallinn": ["capital of estonia", "tallin"],
    "tallis": ["thomas tallis"],
    "tallish": [],
    "tallness": ["height", "stature"],
    "tallow": ["animal oil", "beef tallow", "dubbin", "mutton tallow"],
    "tallow oil": ["animal oil"],
    "tally": ["chalk up", "enter", "put down", "record"],
    "tallyman": ["bagman", "commercial traveler", "commercial traveller", "roadman", "traveling salesman", "travelling salesman"],
    "talmud": [],
    "talmudic literature": ["hagada", "haggada", "haggadah", "halacha", "halaka", "halakah", "religious text", "religious writing", "sacred text", "sacred writing"],
    "talon": ["claw"],
    "talpidae": ["family talpidae", "mammal family"],
    "talus": ["formation", "geological formation", "scree"],
    "tam": ["cap", "tam-o'-shanter", "tammy"],
    "tamable": ["tameable"],
    "tamale": [],
    "tamale pie": ["dish"],
    "tamandua": ["anteater", "lesser anteater", "new world anteater", "tamandu", "tamandua tetradactyla"],
    "tamarau": ["anoa mindorensis", "bubalus mindorensis", "buffalo", "old world buffalo", "tamarao"],
    "tamaricaceae": ["dilleniid dicot family", "family tamaricaceae", "tamarisk family"],
    "tamarin": ["leoncita", "leontocebus oedipus", "leontocebus rosalia", "lion marmoset", "lion monkey", "marmoset", "pinche", "silky tamarin"],
    "tamarind": ["bean tree", "tamarind tree", "tamarindo", "tamarindus indica"],
    "tamarindus": ["genus tamarindus", "rosid dicot genus"],
    "tamarisk": ["bush", "shrub"],
    "tamarisk gerbil": ["gerbil", "gerbille", "meriones unguiculatus"],
    "tamarix": ["dilleniid dicot genus", "genus tamarix"],
    "tambala": ["malawian monetary unit"],
    "tambour": ["embroidery frame", "embroidery hoop", "framework"],
    "tambourine": ["drum", "membranophone", "tympan"],
    "tame": ["alter", "change", "chasten", "modify", "subdue"],
    "tamed": [],
    "tamely": [],
    "tameness": ["domestication", "flexibility", "tractability", "tractableness"],
    "tamer": ["animal trainer", "handler"],
    "tamerlane": ["tamburlaine", "timur", "timur lenk"],
    "tamias": ["genus tamias", "mammal genus"],
    "tamiasciurus": ["genus tamiasciurus", "mammal genus"],
    "tamil": ["dravidian"],
    "tamil nadu": ["madras"],
    "tamm": ["igor tamm", "igor yevgeneevich tamm"],
    "tammany hall": ["organisation", "organization", "tammany", "tammany society"],
    "tammuz": ["jewish calendar month", "thammuz"],
    "tammy": ["cloth", "fabric", "material", "textile"],
    "tamp": ["stemmer", "tamper", "tamping bar", "tool"],
    "tamp down": ["compact", "compress", "pack", "pack together", "tamp"],
    "tampa": [],
    "tampa bay": [],
    "tampax": ["tampon"],
    "tamper": ["fiddle", "manipulate", "monkey"],
    "tampere": ["tammerfors"],
    "tampico": [],
    "tampion": ["plug", "stopper", "stopple", "tompion"],
    "tampon": ["plug", "secure", "stop up"],
    "tamponade": ["blockage", "cardiac tamponade", "obstruction", "tamponage"],
    "tamus": ["genus tamus", "plant genus"],
    "tan": ["bark", "convert"],
    "tanacetum": ["asterid dicot genus", "genus tanacetum"],
    "tanager": ["firebird", "hepatic tanager", "oscine", "oscine bird", "piranga flava hepatica", "piranga ludoviciana", "piranga olivacea", "piranga rubra", "redbird", "scarlet tanager", "summer redbird", "summer tanager", "western tanager"],
    "tanakh": ["hebrew scripture", "tanach"],
    "tanbark": ["bark"],
    "tanbark oak": ["japanese oak", "lithocarpus densiflorus", "lithocarpus glaber", "lithocarpus glabra", "tree"],
    "tancred": [],
    "tandem": ["arrangement", "placement"],
    "tandem trailer": ["articulated lorry", "rig", "semi", "tractor trailer", "trailer truck", "trucking rig"],
    "tandoor": ["oven"],
    "tandy": ["jessica tandy"],
    "tanekaha": ["celery pine", "phyllocladus trichomanoides"],
    "taney": ["roger brooke taney", "roger taney"],
    "tang": ["dynasty", "tang dynasty"],
    "tanga": ["tajikistani monetary unit"],
    "tanganyika": [],
    "tange": ["kenzo tange"],
    "tangelo": ["citrus", "citrus tangelo", "citrus tree", "tangelo tree", "ugli fruit"],
    "tangency": ["contact"],
    "tangent": ["straight line"],
    "tangent plane": ["plane", "sheet"],
    "tangential": [],
    "tangentially": [],
    "tangerine": ["citrus reticulata", "mandarin", "mandarin orange", "mandarin orange tree", "tangerine tree"],
    "tangibility": ["corporality", "corporeality", "materiality", "palpability", "physicalness", "tangibleness"],
    "tangible": [],
    "tangible possession": ["belongings", "holding", "material possession", "property"],
    "tangibly": [],
    "tangier": ["tangiers"],
    "tangier pea": ["lalthyrus tingitanus", "tangier peavine", "wild pea"],
    "tangle": ["hair ball", "hairball", "natural object", "shag", "trichobezoar"],
    "tangle orchid": ["orchid", "orchidaceous plant"],
    "tanglebush": ["desert olive", "forestiera", "forestiera neomexicana"],
    "tangled": [],
    "tango": ["dance", "trip the light fantastic", "trip the light fantastic toe"],
    "tangram": ["puzzle"],
    "tangshan": [],
    "tanguy": ["yves tanguy"],
    "tank": ["store"],
    "tank car": ["freight car", "tank"],
    "tank circuit": ["circuit", "electric circuit", "electrical circuit"],
    "tank destroyer": ["armored vehicle", "armoured vehicle"],
    "tank engine": ["engine", "locomotive", "locomotive engine", "railway locomotive", "tank locomotive"],
    "tank farm": ["area", "country"],
    "tank furnace": ["furnace"],
    "tank iron": ["plate iron"],
    "tank shell": ["shell"],
    "tank top": ["shirt"],
    "tanka": ["poem", "verse form"],
    "tankage": ["indefinite quantity"],
    "tankard": ["drinking vessel"],
    "tanker": ["soldier", "tank driver"],
    "tanker plane": ["aeroplane", "airplane", "plane"],
    "tanned": [],
    "tannenberg": ["battle of tannenberg"],
    "tanner": ["artificer", "artisan", "craftsman", "journeyman"],
    "tannery": ["work", "workplace"],
    "tannic": [],
    "tannin": ["catechin", "cutch", "kutch", "phenol", "tannic acid"],
    "tanning": ["activity", "bodily function", "bodily process", "body process"],
    "tannish": [],
    "tannoy": ["loudspeaker", "loudspeaker system", "speaker", "speaker system", "speaker unit"],
    "tanoan": ["american indian", "american-indian language", "amerind", "amerindian language", "indian", "kiowa", "tanoan language"],
    "tansy": ["composite", "composite plant", "golden buttons", "scented fern", "tanacetum vulgare"],
    "tansy mustard": ["descurainia pinnata", "herb", "herbaceous plant"],
    "tansy-leaved rocket": ["herb", "herbaceous plant", "hugueninia tanacetifolia", "sisymbrium tanacetifolia"],
    "tansy-scented": ["tansy-smelling"],
    "tantalite": ["mineral"],
    "tantalizer": ["persecutor", "tantaliser", "tormenter", "tormentor"],
    "tantalizing": ["tantalising"],
    "tantalizingly": ["invitingly"],
    "tantalum": ["atomic number 73", "metal", "metallic element", "ta"],
    "tantalus": [],
    "tantilla": ["genus tantilla", "reptile genus"],
    "tantra": ["sanskrit literature"],
    "tantric": ["tantrik"],
    "tantrism": ["buddhism"],
    "tantrist": ["adherent", "disciple"],
    "tanzania": ["united republic of tanzania"],
    "tanzanian": ["african"],
    "tanzanian monetary unit": ["monetary unit", "shilling", "tanzanian shilling"],
    "tanzanian shilling": ["shilling", "tanzanian monetary unit"],
    "tao": ["principle"],
    "taoiseach": ["chancellor", "premier", "prime minister"],
    "taoism": ["religious order", "religious sect", "sect"],
    "taoist": ["adherent", "disciple", "tao"],
    "taoist trinity": [],
    "taos": ["pueblo"],
    "tap": ["furnish", "provide", "render", "supply"],
    "tap dance": ["dance", "trip the light fantastic", "trip the light fantastic toe"],
    "tap dancer": ["dancer", "professional dancer", "tapper", "terpsichorean"],
    "tap dancing": ["buck-and-wing", "clog", "clog dance", "clog dancing", "hoofing", "soft-shoe", "soft-shoe dancing", "soft-shoe shuffle", "step dancing", "tap dance"],
    "tap water": ["h2o", "water"],
    "tap wrench": ["spanner", "wrench"],
    "tapa": ["bark", "tapa bark", "tappa", "tappa bark"],
    "tapdance": ["dance", "tap", "trip the light fantastic", "trip the light fantastic toe"],
    "tape": ["attach", "scotch tape", "sellotape"],
    "tape cartridge": ["cartridge"],
    "tape deck": ["cassette deck", "electronic equipment"],
    "tape drive": ["mechanism", "tape transport", "transport"],
    "tape grass": ["aquatic plant", "eelgrass", "hydrophyte", "hydrophytic plant", "vallisneria spiralis", "water plant", "wild celery"],
    "tape player": ["electronic equipment"],
    "tape record": ["record", "tape"],
    "tape recorder": ["dictaphone", "magnetic recorder", "tape machine", "vcr", "videocassette recorder"],
    "taped": ["tape-recorded"],
    "tapenade": ["paste", "spread"],
    "taper": ["decrease", "diminish", "fall", "lessen"],
    "taper file": ["file"],
    "taper off": ["discontinue", "fizzle", "fizzle out", "peter out"],
    "tapered": ["narrowing", "tapering"],
    "tapering": ["lowering"],
    "tapestried": [],
    "tapestry": ["complexity", "complexness"],
    "tapeworm": ["cestode", "echinococcus", "flatworm", "platyhelminth", "taenia"],
    "tapeworm infection": ["infection"],
    "taphephobia": ["simple phobia"],
    "tapioca": ["food product", "foodstuff"],
    "tapioca pudding": ["pudding"],
    "tapir": ["indian tapir", "malayan tapir", "new world tapir", "odd-toed ungulate", "perissodactyl", "perissodactyl mammal", "tapirus indicus", "tapirus terrestris"],
    "tapiridae": ["family tapiridae", "mammal family"],
    "tapirus": ["genus tapirus", "mammal genus"],
    "tapotement": ["massage"],
    "tappan": ["arthur tappan"],
    "tappan zee bridge": [],
    "tapped": [],
    "tapper": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "tappet": ["lever"],
    "tapping": ["rat-a-tat", "rat-a-tat-tat", "rat-tat", "sound"],
    "taproot": ["root"],
    "taps": ["bugle call", "lights-out"],
    "tapster": ["publican", "tapper", "tavern keeper"],
    "tar": ["coat", "surface"],
    "tar pit": ["cavity", "pit"],
    "tar-and-feather": ["penalise", "penalize", "punish"],
    "tara": [],
    "tarabulus": ["tarabulus ash-sham", "trablous", "tripoli"],
    "taracahitian": ["american indian", "cahita", "indian", "red indian", "tarahumara"],
    "tarahumara": ["taracahitian"],
    "tarahumara frog": ["rana tarahumarae", "ranid", "true frog"],
    "tarantella": ["dance music"],
    "tarantino": ["quentin jerome tarantino", "quentin tarantino"],
    "tarantism": ["chorea"],
    "tarantula": ["spider"],
    "tarawa": ["bairiki"],
    "taraxacum": ["asterid dicot genus", "genus taraxacum"],
    "tarbell": ["ida m. tarbell", "ida minerva tarbell", "ida tarbell"],
    "tardigrada": ["class", "class tardigrada"],
    "tardigrade": ["arthropod"],
    "tardiness": ["timing"],
    "tardive": [],
    "tardive dyskinesia": ["dyskinesia"],
    "tare": ["adjustment", "allowance"],
    "tareekh e kasas": ["movement for revenge"],
    "taret organ": ["organ"],
    "target": ["address", "aim", "direct", "home in", "place", "point", "range in", "take", "take aim", "train", "zero in"],
    "target acquisition system": ["shipboard system"],
    "target cell": ["somatic cell", "vegetative cell"],
    "target company": ["company", "sleeping beauty", "takeover target"],
    "target organ": ["organ"],
    "target practice": ["drill", "exercise", "practice", "practice session", "recitation"],
    "target-hunting": [],
    "taricha": ["amphibian genus", "genus taricha"],
    "tariff": ["tax"],
    "tarkovsky": ["andrei arsenevich tarkovsky", "andrei tarkovsky"],
    "tarmacadam": ["pavement", "paving", "paving material", "tarmac"],
    "tarn": ["lake"],
    "tarnish": ["blob", "blot", "darken", "defile", "fleck", "maculate", "spot", "stain", "sully"],
    "tarnished plant bug": ["lygus bug", "lygus lineolaris"],
    "taro": ["cocoyam", "dasheen", "eddo", "root"],
    "tarot card": ["card", "tarot"],
    "tarpan": ["equus caballus gomelini", "wild horse"],
    "tarpaulin": ["canvas", "canvass", "tarp"],
    "tarpon": ["elops saurus", "ladyfish", "malacopterygian", "soft-finned fish", "tarpon atlanticus", "tenpounder"],
    "tarquin": ["lucius tarquinius superbus", "tarquin the proud", "tarquinius", "tarquinius superbus"],
    "tarragon": ["artemisia", "artemisia dracunculus", "estragon"],
    "tarred-and-feathered": [],
    "tarriance": ["delay", "holdup", "lingering"],
    "tarrietia": ["dilleniid dicot genus", "genus tarrietia"],
    "tarry": ["go away", "go forth", "leave", "linger"],
    "tarsal": ["bone", "os", "tarsal bone"],
    "tarsier": ["primate", "tarsius glis", "tarsius syrichta"],
    "tarsiidae": ["family tarsiidae", "mammal family"],
    "tarsioidea": ["animal order", "suborder tarsioidea"],
    "tarsitis": ["inflammation", "redness", "rubor"],
    "tarsius": ["genus tarsius", "mammal genus"],
    "tarsius glis": ["tarsier"],
    "tarsius syrichta": ["tarsier"],
    "tarsus": ["skeletal structure"],
    "tart": ["apple tart", "lobster tart", "pie", "quiche", "tartlet"],
    "tart up": ["adorn", "beautify", "decorate", "embellish", "grace", "ornament"],
    "tartan": ["cloth", "fabric", "material", "plaid", "textile"],
    "tartar": ["calculus", "crust", "encrustation", "incrustation", "tophus"],
    "tartar emetic": ["antimony potassium tartrate", "mordant", "tartrate"],
    "tartare sauce": ["sauce", "tartar sauce"],
    "tartaric": [],
    "tartaric acid": ["hydroxy acid", "racemic acid"],
    "tartary": ["tatary"],
    "tartlet": ["tart"],
    "tartly": [],
    "tartrate": ["antimony potassium tartrate", "bitartrate", "salt", "tartar emetic"],
    "tartu": [],
    "tartuffe": ["dissembler", "dissimulator", "hypocrite", "phoney", "phony", "pretender", "tartufe"],
    "tarweed": ["chile tarweed", "herb", "herbaceous plant", "madia oil plant", "madia sativa", "melosa"],
    "tarwood": ["conifer", "coniferous tree", "dacrydium bidwilli", "halocarpus bidwilli", "new zealand mountain pine", "tar-wood"],
    "tarzan": ["adult male", "man"],
    "tashkent": ["capital of uzbek", "taskent"],
    "tashmit": ["tashmitum"],
    "task": ["assign", "delegate", "depute", "designate"],
    "task force": ["social unit", "unit"],
    "taskmaster": ["slave driver", "supervisor", "taskmistress"],
    "taskmistress": ["taskmaster"],
    "tasman": ["abel janszoon tasman", "abel tasman"],
    "tasman dwarf pine": ["bush", "microstrobos niphophilus", "shrub"],
    "tasman sea": [],
    "tasmania": [],
    "tasmanian": [],
    "tasmanian devil": ["dasyurid", "dasyurid marsupial", "sarcophilus hariisi", "ursine dasyure"],
    "tassel": ["adornment", "sword knot"],
    "tassel flower": ["emilia sagitta", "herb", "herbaceous plant"],
    "tassel hyacinth": ["grape hyacinth", "muscari comosum"],
    "tassel-shaped": [],
    "tasseled": ["tasselled"],
    "tasset": ["armor plate", "armor plating", "armour plate", "plate armor", "plate armour", "tasse"],
    "tasso": ["torquato tasso"],
    "taste": ["savor", "savour", "smack", "taste"],
    "taste cell": ["epithelial cell", "gustatory cell"],
    "taste property": ["acidity", "bitter", "bitterness", "palatability", "palatableness", "property", "rancidness", "sour", "sourness", "spice", "spicery", "spiciness", "sweet", "sweetness", "unpalatability", "unpalatableness"],
    "tastebud": ["chemoreceptor", "gustatory organ", "taste bud"],
    "tasteful": [],
    "tastefully": ["tastily"],
    "tastefulness": ["elegance"],
    "tasteless": [],
    "tastelessly": [],
    "tastelessness": ["brashness", "cheapness", "flashiness", "garishness", "gaudiness", "glitz", "inelegance", "loudness", "meretriciousness", "sleaze", "tackiness", "tat", "tawdriness"],
    "taster": ["critic", "sampler", "taste tester", "taste-tester", "wine taster"],
    "tastily": [],
    "tasting": ["sample"],
    "tasty": [],
    "tat": ["create from raw material", "create from raw stuff", "intertwine"],
    "tatahumara": ["uto-aztecan", "uto-aztecan language"],
    "tatar": ["mongol", "mongol tatar", "mongolian", "tartar"],
    "tate": ["allen tate", "john orley allen tate"],
    "tati": ["jacques tati", "jacques tatischeff"],
    "tatouay": ["armadillo", "cabassous", "cabassous unicinctus"],
    "tattered": ["tatterdemalion"],
    "tatting": ["needlecraft", "needlework"],
    "tattle": ["disclosure", "revealing", "revelation", "singing", "telling"],
    "tattler": ["catoptrophorus semipalmatus", "heteroscelus incanus", "polynesian tattler", "sandpiper", "willet"],
    "tattletale": ["blabbermouth", "gossip", "gossiper", "gossipmonger", "newsmonger", "rumormonger", "rumourmonger", "talebearer", "taleteller", "tattler", "telltale"],
    "tattletale grey": ["gray", "grayness", "grey", "greyness", "tattletale gray"],
    "tattoo": ["stain"],
    "tatum": ["edward lawrie tatum"],
    "tau": ["alphabetic character", "letter", "letter of the alphabet"],
    "tau coefficient of correlation": ["kendall rank correlation", "kendall test", "kendall's tau"],
    "tau cross": ["cross", "st. anthony's cross"],
    "tauntingly": ["teasingly"],
    "tauon": ["lepton", "tau-minus particle"],
    "taupe": ["brown", "brownness"],
    "taurine": ["chemical compound", "compound"],
    "taurotragus": ["genus taurotragus", "mammal genus"],
    "taurus": ["bull", "individual", "mortal", "person", "somebody", "someone", "soul"],
    "taut": [],
    "tauten": ["firm", "tighten"],
    "tautly": [],
    "tautog": ["blackfish", "tautoga onitis", "wrasse"],
    "tautoga": ["fish genus", "genus tautoga"],
    "tautogolabrus": ["fish genus", "genus tautogolabrus"],
    "tautology": ["true statement", "truth"],
    "tavern": ["beer garden", "bucket shop", "building", "edifice", "gin mill", "pothouse", "pub", "public house", "rathskeller", "saloon", "shebeen", "tap house", "taphouse"],
    "taw": ["alphabetic character", "letter", "letter of the alphabet"],
    "tawney": ["richard henry tawney"],
    "tawniness": ["complexion", "skin color", "skin colour"],
    "tawny": ["tawny-brown"],
    "tawny eagle": ["aquila rapax", "bird of jove", "eagle"],
    "tawny owl": ["bird of minerva", "bird of night", "hooter", "owl", "strix aluco"],
    "tawny-colored": ["tawny-coloured"],
    "tawse": ["strap"],
    "tax": ["assess", "determine", "set"],
    "tax advantage": ["advantage", "vantage"],
    "tax assessment": ["assessment"],
    "tax assessor": ["administrative official", "assessor", "bureaucrat", "lister"],
    "tax avoidance": ["minimisation", "minimization"],
    "tax base": ["assets"],
    "tax benefit": ["deduction", "tax break", "tax deduction", "tax write-off"],
    "tax bill": ["account", "bill", "invoice"],
    "tax collection": ["aggregation", "assembling", "collecting", "collection"],
    "tax collector": ["administrative official", "bureaucrat", "collector of internal revenue", "exciseman", "internal revenue agent", "taxman"],
    "tax credit": ["decrease", "diminution", "reduction", "step-down"],
    "tax cut": ["cut"],
    "tax evasion": ["evasion", "nonpayment"],
    "tax form": ["form"],
    "tax haven": ["country", "land", "state"],
    "tax income": ["government income", "government revenue", "internal revenue", "revenue", "tax revenue", "taxation"],
    "tax law": ["jurisprudence", "law"],
    "tax liability": ["liabilities"],
    "tax lien": ["federal tax lien", "lien", "state tax lien"],
    "tax program": ["program", "programme", "tax policy"],
    "tax rate": ["charge per unit", "rate"],
    "tax return": ["amended return", "declaration of estimated tax", "estimated tax return", "false return", "income tax return", "information return", "instrument", "joint return", "legal document", "legal instrument", "official document", "return"],
    "tax shelter": ["decrease", "diminution", "reduction", "shelter", "step-down"],
    "tax system": ["legal system"],
    "tax write-off": ["business deduction", "deduction", "exemption", "tax benefit", "tax break", "tax deduction", "write-down", "write-off"],
    "tax-exempt": ["tax-free", "untaxed"],
    "tax-exempt security": ["certificate", "security", "tax-exempt"],
    "tax-increase": ["increase", "increment", "tax boost", "tax hike"],
    "taxability": ["liability"],
    "taxable": ["nonexempt"],
    "taxaceae": ["family taxaceae", "gymnosperm family", "yew family"],
    "taxales": ["order taxales", "plant order"],
    "taxation": ["imposition", "infliction"],
    "taxer": ["administrative official", "bureaucrat"],
    "taxi": ["cab", "ride"],
    "taxi dancer": ["dancer", "professional dancer", "terpsichorean"],
    "taxidea": ["genus taxidea", "mammal genus"],
    "taxidermist": ["animal stuffer", "artificer", "artisan", "craftsman", "journeyman", "stuffer"],
    "taxidermy": ["art", "artistry", "prowess"],
    "taxidriver": ["cabby", "cabdriver", "cabman", "driver", "hack driver", "hack-driver", "livery driver", "taximan"],
    "taximeter": ["meter"],
    "taxis": ["chemotaxis", "reaction", "response"],
    "taxiway": ["paved surface", "taxi strip"],
    "taxodiaceae": ["gymnosperm family", "redwood family", "subfamily taxodiaceae"],
    "taxodium": ["genus taxodium", "gymnosperm genus"],
    "taxonomic": ["systematic", "taxonomical"],
    "taxonomic group": ["adapid", "adapid group", "amentiferae", "biological group", "centrospermae", "class", "family", "form", "genus", "group amentiferae", "group centrospermae", "group pteridospermae", "group pteridospermaphyta", "kingdom", "monotype", "omomyid", "omomyid group", "order", "phycomycetes", "phycomycetes group", "phylum", "pteridospermae", "pteridospermaphyta", "race", "species", "strain", "subclass", "subfamily", "subgenus", "subkingdom", "suborder", "subphylum", "subspecies", "superclass", "superfamily", "superorder", "superphylum", "taxon", "taxonomic category", "tribe", "type", "var.", "variant", "variety"],
    "taxonomically": [],
    "taxonomist": ["biologist", "divider", "life scientist", "lumper", "splitter", "systematist", "taxonomer"],
    "taxonomy": ["hierarchy"],
    "taxopsida": ["class", "class taxopsida", "subdivision taxophytina", "taxophytina"],
    "taxpayer": ["payer", "ratepayer", "remunerator"],
    "taxpaying": [],
    "taxus": ["genus taxus", "gymnosperm genus"],
    "tay": ["tai"],
    "tay-sachs disease": ["autosomal recessive defect", "autosomal recessive disease", "infantile amaurotic idiocy", "lipidosis", "monogenic disease", "monogenic disorder", "sachs disease", "tay-sachs"],
    "tayalic": ["atayalic", "formosan"],
    "tayassu": ["genus pecari", "genus tayassu", "mammal genus"],
    "tayassuidae": ["family tayassuidae", "mammal family"],
    "taylor": ["deems taylor", "joseph deems taylor"],
    "tayra": ["eira barbara", "mustelid", "musteline", "musteline mammal", "taira"],
    "tazir crime": ["crime", "criminal offence", "criminal offense", "law-breaking", "offence", "offense"],
    "tbilisi": ["capital of georgia", "tiflis"],
    "tchaikovsky": ["peter ilich tchaikovsky", "peter tchaikovsky", "pyotr ilych tchaikovsky", "pyotr tchaikovsky"],
    "te deum": [],
    "te kanawa": ["dame kiri janette te kanawa", "dame kiri te kanawa"],
    "tea": ["bush", "camellia sinensis", "shrub"],
    "tea bag": ["tea", "tea leaf"],
    "tea ball": ["kitchen utensil"],
    "tea bread": ["bun", "roll"],
    "tea cart": ["serving cart", "tea trolley", "tea wagon", "teacart"],
    "tea ceremony": ["ceremony", "chanoyu"],
    "tea chest": ["chest"],
    "tea cloth": ["tablecloth"],
    "tea garden": ["garden"],
    "tea gown": ["gown"],
    "tea maker": ["spoon"],
    "tea napkin": ["napkin", "serviette", "table napkin"],
    "tea party": ["party"],
    "tea rose": ["rosa odorata", "rose", "rosebush"],
    "tea service": ["tableware", "tea set"],
    "tea table": ["table"],
    "tea tortrix": ["homona coffearia", "tortricid", "tortricid moth", "tortrix"],
    "tea tray": ["tray"],
    "tea urn": ["urn"],
    "tea-like drink": ["beverage", "drink", "drinkable", "potable"],
    "tea-scented": [],
    "tea-strainer": ["strainer"],
    "teaberry": ["checkerberry", "creeping wintergreen", "gaultheria procumbens", "ground-berry", "groundberry", "mountain tea", "shrublet", "wintergreen"],
    "teacake": ["biscuit", "cookie", "cooky", "tea biscuit"],
    "teach": ["catechise", "catechize", "coach", "condition", "develop", "drill", "edify", "educate", "enlighten", "ground", "indoctrinate", "induct", "inform", "instruct", "learn", "lecture", "mentor", "prepare", "reinforce", "reward", "spoonfeed", "talk", "train", "tutor", "unteach"],
    "teach-in": ["conference", "group discussion"],
    "teacher": ["art teacher", "bahai", "catechist", "coach", "dance master", "dancing-master", "demonstrator", "docent", "don", "educator", "english professor", "english teacher", "french teacher", "governess", "instructor", "instructress", "math teacher", "mathematics teacher", "missionary", "music teacher", "pedagog", "pedagogue", "preceptor", "private instructor", "reading teacher", "riding master", "school teacher", "schoolteacher", "science teacher", "section man", "teaching fellow", "tutor"],
    "teacher's pet": ["darling", "dearie", "deary", "ducky", "favorite", "favourite", "pet"],
    "teacher-student relation": ["academic relation"],
    "teachership": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "teaching": ["commandment", "doctrine", "golden rule", "ism", "mitsvah", "mitzvah", "philosophical system", "philosophy", "precept", "school of thought"],
    "teaching aid": ["audiovisual", "audiovisual aid", "equipment"],
    "teaching certificate": ["certificate", "certification", "credential", "credentials", "teacher's certificate"],
    "teaching fellow": ["instructor", "teacher"],
    "teaching method": ["maieutic method", "method", "pedagogics", "pedagogy", "socratic method"],
    "teaching reading": ["instruction", "pedagogy", "phonics", "teaching", "whole-word method"],
    "teacup": ["containerful", "teacupful"],
    "teak": ["teakwood", "wood"],
    "teakettle": ["boiler", "kettle"],
    "teal": ["anas crecca", "anas discors", "anas querquedula", "blue-winged teal", "bluewing", "duck", "garganey", "green-winged teal", "greenwing"],
    "team": ["aggroup", "group", "team up"],
    "team sport": ["athletics", "sport"],
    "team teaching": ["didactics", "education", "educational activity", "instruction", "pedagogy", "teaching"],
    "teammate": ["associate", "mate"],
    "teamster": ["driver"],
    "teamsters union": ["industrial union", "vertical union"],
    "teamwork": ["cooperation"],
    "teapot": ["pot"],
    "teapot dome": ["teapot dome scandal"],
    "tear": ["belt along", "buck", "bucket along", "cannonball along", "charge", "hasten", "hie", "hotfoot", "pelt along", "race", "rip", "rush", "rush along", "shoot", "shoot down", "speed", "step on it"],
    "tear away": ["remove", "take", "take away", "tear off", "withdraw"],
    "tear gas": ["chemical weapon", "chloroacetophenone", "chlorobenzylidenemalononitrile", "cn gas", "cs gas", "gas", "lachrymator", "lacrimator", "nitrochloromethane", "teargas"],
    "tear sheet": ["piece of paper", "sheet", "sheet of paper"],
    "tearaway": ["daredevil", "harum-scarum", "hothead", "lunatic", "madcap", "swashbuckler"],
    "teardrop": ["bead", "drop", "pearl"],
    "tearful": [],
    "tearfully": [],
    "teargas": ["gas"],
    "tearjerker": ["narration", "narrative", "story", "tale"],
    "tearless": ["dry-eyed"],
    "teary": ["teary-eyed", "watery-eyed"],
    "teasdale": ["sara teasdale"],
    "tease": ["control", "keep in line", "manipulate"],
    "teased": ["titillated"],
    "teasel": ["common teasel", "dipsacus fullonum", "dipsacus sativus", "dipsacus sylvestris", "fuller's teasel", "herb", "herbaceous plant", "teasle", "teazel", "wild teasel"],
    "teaser": ["worker"],
    "teashop": ["buttery", "eatery", "eating house", "eating place", "restaurant", "tea parlor", "tea parlour", "teahouse", "tearoom"],
    "teasing": ["caper", "frolic", "gambol", "play", "romp"],
    "teaspoon": ["containerful", "teaspoonful"],
    "tebaldi": ["renata tebaldi"],
    "tebet": ["jewish calendar month", "tevet"],
    "tebibit": ["computer memory unit", "tibit"],
    "techie": ["technician", "tekki"],
    "technetium": ["atomic number 43", "metal", "metallic element", "tc"],
    "technical": ["military vehicle", "pickup", "pickup truck"],
    "technical analysis": ["analysis", "technical analysis of stock trends"],
    "technical foul": ["foul", "technical"],
    "technical knockout": ["kayo", "knockout", "ko", "tko"],
    "technical school": ["engineering school", "polytechnic", "polytechnic institute", "school", "tech"],
    "technical sergeant": ["sergeant"],
    "technical-grade": ["technical grade"],
    "technicality": ["detail", "item", "point", "trifle", "triviality"],
    "technically": [],
    "technician": ["expert"],
    "technicolor": ["method"],
    "technique": ["antialiasing", "benday process", "bonding", "computer simulation", "emulation", "immunofluorescence", "method", "photomechanics", "simulation"],
    "techno": ["dance music"],
    "technobabble": ["jargon"],
    "technocracy": ["form of government", "political system"],
    "technocrat": ["expert"],
    "technological": [],
    "technologically": [],
    "technology": ["aeronautical engineering", "application", "automotive engineering", "automotive technology", "chemical engineering", "communications technology", "computer technology", "engineering", "high tech", "high technology", "practical application", "profession", "rail technology", "railroading"],
    "technology administration": ["agency", "authority", "bureau", "federal agency", "government agency", "office"],
    "technophile": ["enthusiast", "fancier"],
    "technophilia": ["enthusiasm"],
    "technophilic": [],
    "technophobe": ["naysayer"],
    "technophobia": ["dislike"],
    "technophobic": [],
    "tecophilaeacea": ["family tecophilaeacea", "liliid monocot family"],
    "tectaria": ["fern genus", "genus tectaria"],
    "tectona": ["asterid dicot genus", "genus tectona"],
    "tectonic": [],
    "tectonics": ["geomorphology", "morphology", "plate tectonic theory", "plate tectonics"],
    "tecumseh": ["tecumtha"],
    "ted": ["plug-ugly", "teddy boy", "tough guy"],
    "teddy": ["plaything", "teddy bear", "toy"],
    "teddy boys": ["youth subculture"],
    "tediousness": ["drag", "dullness", "tedium", "tiresomeness"],
    "tee": ["lay", "place", "pose", "position", "put", "set", "tee up"],
    "tee hinge": ["flexible joint", "hinge", "t hinge"],
    "tee off": ["play"],
    "tee up": ["arrange", "stage"],
    "teem": ["buzz", "crawl", "hum", "pullulate", "seethe", "swarm"],
    "teeming": [],
    "teens": ["time of life"],
    "teeoff": ["golf shot", "golf stroke", "swing"],
    "teeter": ["move", "seesaw", "totter"],
    "teeter-totter": ["play", "seesaw", "teetertotter"],
    "teethe": ["acquire", "develop", "get", "grow", "produce"],
    "teething": ["dentition", "development", "growing", "growth", "maturation", "odontiasis", "ontogenesis", "ontogeny", "precocious dentition"],
    "teetotal": ["abstain", "desist", "refrain"],
    "teetotaler": ["abstainer", "abstinent", "nondrinker", "teetotalist", "teetotaller"],
    "teetotaling": ["abstinence", "teetotalism"],
    "teff": ["bay grass", "eragrostic abyssinica", "eragrostis tef", "love grass", "teff grass"],
    "teflon": ["plastic", "polytetrafluoroethylene"],
    "teg": ["lamb"],
    "tegucigalpa": ["honduran capital"],
    "tegular": [],
    "teheran": ["capital of iran", "iranian capital", "tehran"],
    "teiid lizard": ["caiman lizard", "lizard", "teiid", "teju", "whiptail", "whiptail lizard"],
    "teiidae": ["family teiidae", "reptile family"],
    "teilhard de chardin": ["pierre teilhard de chardin"],
    "teju": ["teiid", "teiid lizard"],
    "tektite": ["natural glass"],
    "tel aviv": ["tel aviv-jaffa", "tel aviv-yalo"],
    "telanthera": ["caryophylloid dicot genus", "genus telanthera"],
    "telecast": ["air", "beam", "broadcast", "colorcast", "send", "televise", "transmit"],
    "telecaster": ["broadcaster"],
    "telecom hotel": ["building", "edifice", "telco building"],
    "telecommunicate": ["cable", "call", "call up", "communicate", "e-mail", "email", "facsimile", "fax", "intercommunicate", "netmail", "phone", "ring", "telefax", "telegraph", "telephone", "telex", "wire"],
    "telecommunication": ["broadcasting", "medium", "multiplex", "telecom", "telegraphy", "telephone", "telephony", "wireless"],
    "telecommunication system": ["communication system", "telecom equipment", "telecom system", "telecommunication equipment", "television", "television system"],
    "telecommuting": ["employment", "teleworking", "work"],
    "teleconference": ["conference", "group discussion", "teleconferencing"],
    "telefilm": ["film", "flick", "motion picture", "motion-picture show", "movie", "moving picture", "moving-picture show", "pic", "picture", "picture show"],
    "telegnosis": ["anomalous communication", "psychic communication", "psychical communication"],
    "telegnostic": [],
    "telegram": ["cable", "cablegram", "letter telegram", "message", "night letter", "overseas telegram", "wire"],
    "telegraph": ["apparatus", "setup", "telegraphy"],
    "telegraph form": ["form"],
    "telegraph key": ["key"],
    "telegraph plant": ["bush", "codariocalyx motorius", "desmodium gyrans", "desmodium motorium", "semaphore plant", "shrub"],
    "telegrapher": ["manipulator", "operator", "telegraph operator", "telegraphist"],
    "telegraphese": ["non-standard speech"],
    "telegraphic": [],
    "telegraphic signal": ["dah", "dash", "dit", "dot", "radiotelegraphic signal", "sign", "signal", "signaling"],
    "telegraphically": ["tersely"],
    "telegraphy": ["telecom", "telecommunication"],
    "telekinesis": ["parapsychology", "psychic phenomena", "psychic phenomenon", "psychokinesis"],
    "telemann": ["georg philipp telemann"],
    "telemark": ["turn", "turning"],
    "telemarketing": ["marketing", "merchandising", "selling", "telecommerce", "telephone order", "teleselling"],
    "telemeter": ["scientific instrument"],
    "telemetered": [],
    "telemetry": ["measure", "measurement", "measuring", "mensuration"],
    "telemetry intelligence": ["sigint", "signals intelligence", "telint"],
    "telencephalon": ["neural structure"],
    "teleological": [],
    "teleologist": ["advocate", "advocator", "exponent", "proponent"],
    "teleology": ["philosophical doctrine", "philosophical theory"],
    "teleost fish": ["acanthopterygian", "aulostomus maculatus", "bellows fish", "billfish", "bony fish", "cornetfish", "flying fish", "ganoid", "ganoid fish", "gar", "halfbeak", "malacopterygian", "needlefish", "pipefish", "saury", "scomberesox saurus", "shrimp-fish", "shrimpfish", "snipefish", "soft-finned fish", "spiny-finned fish", "sweeper", "teleost", "teleostan", "trumpetfish"],
    "teleostei": ["class", "subclass teleostei"],
    "telepathic": [],
    "telepathist": ["communicator", "mental telepathist", "mind reader", "thought-reader"],
    "telepathize": ["communicate", "intercommunicate", "telepathise"],
    "telepathy": ["anomalous communication", "psychic communication", "psychical communication", "thought transference"],
    "telephone": ["call", "call forwarding", "call waiting", "phone call", "telecom", "telecommunication", "telephone call", "telephony", "voice mail", "voicemail"],
    "telephone bell": ["electric bell"],
    "telephone booth": ["booth", "call box", "cubicle", "kiosk", "phone booth", "stall", "telephone box", "telephone kiosk"],
    "telephone company": ["phone company", "phone service", "public utility", "public utility company", "public-service corporation", "telco", "telephone service", "utility"],
    "telephone conversation": ["conversation"],
    "telephone cord": ["phone cord", "telegraph line", "telegraph wire", "telephone line", "telephone wire"],
    "telephone interview": ["interview"],
    "telephone jack": ["jack", "phone jack"],
    "telephone line": ["connecter", "connection", "connective", "connector", "connexion", "digital subscriber line", "dsl", "hot line", "land line", "landline", "line", "party line", "phone line", "private line", "subscriber line", "telephone circuit", "toll line", "trunk line", "wats", "wats line"],
    "telephone operator": ["manipulator", "operator", "switchboard operator", "telephonist"],
    "telephone order": ["telecommerce", "telemarketing", "teleselling"],
    "telephone plug": ["male plug", "phone plug", "plug"],
    "telephone pole": ["post", "telegraph pole", "telegraph post"],
    "telephone receiver": ["earphone", "earpiece", "headphone", "headset", "phone", "receiver"],
    "telephone system": ["communication system", "medline", "phone system"],
    "telephone unit": ["erlang", "unit", "unit of measurement"],
    "telephone wire": ["conducting wire", "phone cord", "telegraph line", "telegraph wire", "telephone cord", "telephone line", "wire"],
    "telephonic": [],
    "telephoto lens": ["camera lens", "optical lens", "zoom lens"],
    "telephotograph": ["exposure", "photo", "photograph", "pic", "picture", "radiophoto", "radiophotograph"],
    "telephotography": ["radiophotography", "transmission", "transmittal", "transmitting"],
    "teleport": ["transport"],
    "teleportation": ["conveyance", "transfer", "transferral", "transport", "transportation"],
    "teleprompter": ["autocue", "prompter"],
    "telerobotics": ["robotics"],
    "telescope": ["crush", "mash", "squash", "squeeze", "squelch"],
    "telescoped": ["shortened"],
    "telescopic": [],
    "telescopic sight": ["gun-sight", "gunsight", "telescope sight"],
    "telescopically": [],
    "telescopium": [],
    "telescopy": ["art", "artistry", "prowess"],
    "telethermometer": ["thermometer"],
    "teletypewriter": ["character printer", "character-at-a-time printer", "serial printer", "teleprinter", "teletype machine", "telex", "telex machine"],
    "televangelism": ["evangelism"],
    "televangelist": ["evangelist", "gospeler", "gospeller", "revivalist"],
    "television": ["broadcasting", "cable", "cable television", "hdtv", "high-definition television", "telecasting", "tv", "video"],
    "television antenna": ["nondirectional antenna", "omnidirectional antenna", "rabbit ears", "tv-antenna"],
    "television camera": ["camcorder", "camera", "television equipment", "tv camera", "video equipment"],
    "television equipment": ["camera", "electronic equipment", "television camera", "tv camera", "video equipment"],
    "television monitor": ["monitor", "tv monitor"],
    "television news": ["news", "news program", "news show"],
    "television program": ["broadcast", "colorcast", "colourcast", "pilot", "pilot film", "pilot program", "program", "programme", "sitcom", "situation comedy", "special", "television show", "tv program", "tv show"],
    "television receiver": ["boob tube", "goggle box", "idiot box", "receiver", "receiving system", "television", "television set", "telly", "tv", "tv set"],
    "television reporter": ["anchor", "anchorman", "anchorperson", "newsman", "newsperson", "reporter", "television newscaster", "tv newsman", "tv reporter"],
    "television room": ["room", "tv room"],
    "television star": ["lead", "principal", "star", "tv star"],
    "television station": ["broadcast station", "broadcasting station", "channel", "television channel", "tv channel", "tv station"],
    "television transmitter": ["sender", "transmitter"],
    "television-camera tube": ["electron tube", "iconoscope", "image orthicon", "orthicon", "television pickup tube", "thermionic tube", "thermionic vacuum tube", "thermionic valve", "tube", "vacuum tube"],
    "telex": ["telecommunicate"],
    "teliospore": ["chlamydospore"],
    "tell": ["evidence", "inform"],
    "tell off": ["bawl out", "berate", "brush down", "call down", "call on the carpet", "chew out", "chew up", "chide", "dress down", "have words", "jaw", "lambast", "lambaste", "lecture", "rag", "rebuke", "remonstrate", "reprimand", "reproof", "scold", "take to task", "trounce"],
    "tell on": ["affect", "bear on", "bear upon", "impact", "touch", "touch on"],
    "teller": ["edward teller"],
    "tellima": ["genus tellima", "rosid dicot genus"],
    "telling": ["apprisal", "informing", "making known", "notice", "notification", "warning"],
    "tellingly": [],
    "tellurian": ["denizen", "dweller", "earthling", "earthman", "habitant", "indweller", "inhabitant", "worldling"],
    "telluric": [],
    "telluride": ["chemical compound", "compound"],
    "tellurium": ["atomic number 52", "chemical element", "element", "te"],
    "tellus": [],
    "telocentric": [],
    "telocentric chromosome": ["chromosome"],
    "telomerase": ["enzyme"],
    "telomere": ["end", "terminal"],
    "telopea": ["dicot genus", "genus telopea", "magnoliopsid genus"],
    "telophase": ["phase of cell division"],
    "telosporidia": ["class", "subclass telosporidia"],
    "telpher": ["conveyance", "telfer", "transport"],
    "telpherage": ["telferage", "transit", "transportation", "transportation system"],
    "telugu": ["dravidian"],
    "temazepam": ["benzodiazepine", "restoril"],
    "temnospondyli": ["animal order", "order temnospondyli"],
    "temp": ["temporary", "temporary worker", "worker"],
    "temper": ["harden", "modify"],
    "tempera": ["poster color", "poster colour", "poster paint", "water-base paint"],
    "temperament": ["emotionalism", "emotionality"],
    "temperamental": [],
    "temperamentally": [],
    "temperance": ["abstemiousness", "control", "dryness", "moderation", "natural virtue", "restraint", "sobriety"],
    "temperate": [],
    "temperate rain forest": ["rain forest", "rainforest"],
    "temperate zone": ["climatic zone"],
    "temperately": [],
    "temperature": ["cold", "coldness", "comfort zone", "heat", "somaesthesia", "somatesthesia", "somatic sensation", "somesthesia", "warmth"],
    "temperature change": ["action", "activity", "advection", "chilling", "climate change", "convection", "cooling", "global climate change", "heating", "natural action", "natural process", "temperature reduction", "warming"],
    "temperature gradient": ["gradient"],
    "temperature scale": ["absolute scale", "celsius scale", "centigrade scale", "fahrenheit scale", "graduated table", "international scale", "kelvin scale", "metric", "ordered series", "rankine scale", "reaumur scale", "scale", "scale of measurement", "system of measurement"],
    "temperature unit": ["degree", "degree day", "k", "kelvin", "millidegree", "rankine", "unit", "unit of measurement"],
    "tempered": ["hardened", "toughened", "treated"],
    "tempering": [],
    "tempest": ["windstorm"],
    "tempestuousness": ["storminess"],
    "template": ["example", "guide", "model", "rhythm", "speech rhythm", "templet"],
    "temple": ["feature", "lineament"],
    "temple of apollo": ["delphic oracle", "oracle of apollo", "oracle of delphi"],
    "temple of artemis": [],
    "temple of jerusalem": ["temple of solomon"],
    "temple orange": ["citrus nobilis", "king orange", "orange", "orange tree", "tangor", "temple orange tree"],
    "templetonia": ["genus templetonia", "rosid dicot genus"],
    "tempo": ["beats per minute", "bpm", "m.m.", "metronome marking", "pace", "rate"],
    "temporal": [],
    "temporal arrangement": ["chronological sequence", "chronological succession", "sequence", "succession", "successiveness", "temporal order", "temporal property", "timing"],
    "temporal arteritis": ["arteritis"],
    "temporal artery": ["anterior temporal artery", "arteria cerebri", "arteria temporalis anterior", "arteria temporalis intermedia", "arteria temporalis posterior", "cerebral artery", "intermediate temporal artery", "posterior temporal artery"],
    "temporal bone": ["bone", "os", "os temporale"],
    "temporal canthus": ["canthus"],
    "temporal gyrus": ["convolution", "gyrus"],
    "temporal lobe": ["lobe", "temporal ccortex"],
    "temporal property": ["duration", "length", "pace", "property", "rate", "temporal arrangement", "temporal order"],
    "temporal relation": ["antecedent", "asynchronism", "asynchrony", "chronology", "desynchronisation", "desynchronization", "desynchronizing", "forerunner", "relation", "synchroneity", "synchronicity", "synchronisation", "synchronism", "synchronization", "synchronizing", "synchrony"],
    "temporal role": ["participant role", "semantic role", "temporal"],
    "temporal vein": ["deep temporal vein", "middle temporal vein", "superficial temporal vein", "vein", "vena", "vena temporalis", "venous blood vessel"],
    "temporalis muscle": ["musculus temporalis", "skeletal muscle", "striated muscle", "temporal muscle", "temporalis"],
    "temporally": [],
    "temporalty": ["church property", "spirituality", "spiritualty", "temporality"],
    "temporarily": [],
    "temporariness": ["impermanence", "impermanency"],
    "temporary hookup": ["connecter", "connection", "connective", "connector", "connexion", "contrivance", "lash-up", "patch"],
    "temporary injunction": ["cease and desist order", "enjoining", "enjoinment", "injunction", "interlocutory injunction"],
    "temporary state": ["clutch", "depletion", "drowsiness", "drunkenness", "emergency", "fatigue", "frame of mind", "inebriation", "inebriety", "insobriety", "intoxication", "sleepiness", "sleeplessness", "soberness", "sobriety", "somnolence", "state", "state of mind", "tipsiness", "tiredness", "wakefulness", "weariness"],
    "temporize": ["draw out", "extend", "prolong", "protract", "temporise"],
    "temporizer": ["delayer", "temporiser"],
    "tempt": ["arouse", "excite", "sex", "turn on", "wind up"],
    "temptable": [],
    "temptation": ["desire"],
    "tempter": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "tempura": ["dish"],
    "temuco": [],
    "ten": ["10", "decade", "large integer", "tenner", "x"],
    "ten thousand": ["10000", "large integer", "myriad"],
    "ten-membered": ["10-membered"],
    "ten-sided": [],
    "ten-spined stickleback": ["gasterosteus pungitius", "prickleback", "stickleback"],
    "ten-spot": ["spot", "ten"],
    "tenable": ["well-founded"],
    "tenant": ["dwell", "inhabit", "live", "populate"],
    "tenant farmer": ["farmer", "granger", "husbandman", "sodbuster", "tenant"],
    "tenantry": ["accumulation", "aggregation", "assemblage", "collection"],
    "tench": ["cyprinid", "cyprinid fish", "tinca tinca"],
    "tend": ["be", "be given", "gravitate", "incline", "lean", "run", "suffer", "take kindly to"],
    "tendency": ["direction", "trend", "way"],
    "tendentious": ["tendencious"],
    "tendentiously": [],
    "tendentiousness": ["bias", "preconception", "prejudice"],
    "tender": ["gift", "give", "present"],
    "tender loving care": ["aid", "attention", "care", "tending", "tlc"],
    "tender offer": ["offer", "offering", "takeover bid"],
    "tenderfoot": ["beginner", "initiate", "novice", "tiro", "tyro"],
    "tendergreen": ["brassica perviridis", "brassica rapa perviridis", "crucifer", "cruciferous plant", "spinach mustard"],
    "tenderhearted": [],
    "tenderization": ["improvement", "tenderisation"],
    "tenderized": ["tenderised"],
    "tenderizer": ["chemical compound", "compound", "tenderiser"],
    "tenderloin": ["beef tenderloin", "cut", "cut of meat", "pork tenderloin", "undercut"],
    "tenderly": [],
    "tenderness": ["chafe", "chafing", "hurting", "pain", "rawness", "rebound tenderness", "soreness"],
    "tendinitis": ["inflammation", "lateral epicondylitis", "lateral humeral epicondylitis", "redness", "rubor", "tendonitis", "tendonous synovitis", "tendosynovitis", "tennis elbow", "tenonitis", "tenosynovitis"],
    "tendinous": ["sinewy"],
    "tendon": ["achilles tendon", "connective tissue", "hamstring", "hamstring tendon", "sinew", "tendon of achilles"],
    "tendril": ["cirrhus", "cirrus", "plant part", "plant structure"],
    "tendril-climbing": [],
    "tenebrionidae": ["arthropod family", "family tenebrionidae"],
    "tenebrous": ["tenebrific", "tenebrious"],
    "tenement": ["apartment building", "apartment house", "tenement house"],
    "tenement district": ["community", "residential area", "residential district"],
    "tenerife": [],
    "tenesmus": ["cramp", "muscle spasm", "spasm"],
    "tenfold": [],
    "tenge": ["turkmen monetary unit"],
    "tenner": ["bank bill", "bank note", "banker's bill", "banknote", "bill", "federal reserve note", "government note", "greenback", "note", "ten dollar bill"],
    "tennessean": ["american", "volunteer"],
    "tennessee": ["tennessee river"],
    "tennessee walker": ["mount", "plantation walking horse", "riding horse", "saddle horse", "tennessee walking horse", "walking horse"],
    "tenniel": ["sir john tenniel"],
    "tennis": ["court game", "court tennis", "doubles", "lawn tennis", "professional tennis", "real tennis", "royal tennis", "singles"],
    "tennis ball": ["ball"],
    "tennis camp": ["camp"],
    "tennis club": ["racket club"],
    "tennis coach": ["coach", "handler", "manager"],
    "tennis court": ["court"],
    "tennis elbow": ["epicondylitis", "lateral epicondylitis", "lateral humeral epicondylitis", "tendinitis", "tendonitis", "tenonitis"],
    "tennis lesson": ["lesson"],
    "tennis match": ["match"],
    "tennis player": ["athlete", "jock", "participant", "player", "professional tennis player", "receiver", "tennis pro"],
    "tennis pro": ["professional tennis player", "tennis player"],
    "tennis racket": ["racket", "racquet", "tennis racquet"],
    "tennis stroke": ["return", "serve", "service", "shot", "stroke", "tennis shot"],
    "tennyson": ["alfred lord tennyson", "alfred tennyson", "first baron tennyson"],
    "tenon": ["projection"],
    "tenor": ["singer", "vocaliser", "vocalist", "vocalizer"],
    "tenor clef": ["clef"],
    "tenor drum": ["drum", "membranophone", "tom-tom", "tympan"],
    "tenor saxophonist": ["saxist", "saxophonist", "tenorist"],
    "tenoretic": ["antihypertensive", "antihypertensive drug"],
    "tenoroon": ["bassoon"],
    "tenosynovitis": ["synovitis", "tendinitis", "tendonitis", "tendonous synovitis", "tendosynovitis", "tenonitis"],
    "tenpence": ["coin"],
    "tenpenny nail": ["nail"],
    "tenpin": ["bowling pin", "pin"],
    "tenpins": ["bowling", "tenpin bowling"],
    "tenrec": ["insectivore", "tailless tenrec", "tendrac", "tenrec ecaudatus"],
    "tenrecidae": ["family tenrecidae", "mammal family"],
    "tense": ["alter", "change", "modify"],
    "tense system": ["language system"],
    "tensed": [],
    "tensely": [],
    "tensile": [],
    "tensile strength": ["durability", "enduringness", "lastingness", "strength"],
    "tensimeter": ["manometer"],
    "tensiometer": ["measuring device", "measuring instrument", "measuring system"],
    "tension": ["condition", "status", "tautness", "tenseness", "tensity", "tone", "tonicity", "tonus"],
    "tension headache": ["cephalalgia", "head ache", "headache"],
    "tensional": [],
    "tensionless": [],
    "tensor": ["variable", "variable quantity"]
}
