synonyms = {
    "hydnum": ["fungus genus", "genus hydnum"],
    "hydra": ["mythical creature", "mythical monster"],
    "hydralazine": ["antihypertensive", "antihypertensive drug", "apresoline", "vasodilative", "vasodilator"],
    "hydramnios": ["abnormalcy", "abnormality"],
    "hydrangea": ["bush", "carpenteria", "carpenteria californica", "climbing hydrangea", "decumaria barbara", "decumaria barbata", "decumary", "deutzia", "fall-blooming hydrangea", "hortensia", "hydrangea anomala", "hydrangea arborescens", "hydrangea macrophylla hortensis", "hydrangea paniculata", "hydrangea petiolaris", "shrub", "wild hydrangea"],
    "hydrangeaceae": ["family hydrangeaceae", "hydrangea family", "rosid dicot family"],
    "hydrant": ["discharge pipe", "fire hydrant", "fireplug", "plug"],
    "hydrarthrosis": ["inflammation", "redness", "rubor", "water on the knee"],
    "hydrastis": ["genus hydrastis", "magnoliid dicot genus"],
    "hydrate": ["furnish", "provide", "render", "supply"],
    "hydration": ["association"],
    "hydraulic": [],
    "hydraulic brake": ["brake system", "brakes", "disc brake", "disk brake", "drum brake", "foot brake", "hydraulic brakes"],
    "hydraulic cement": ["cement", "portland cement"],
    "hydraulic engineering": ["civil engineering"],
    "hydraulic press": ["mechanical press", "press"],
    "hydraulic pump": ["hydraulic ram", "pump"],
    "hydraulic system": ["hydraulic transmission", "hydraulic transmission system", "mechanism"],
    "hydraulic transmission": ["hydraulic system", "hydraulic transmission system", "transmission", "transmission system"],
    "hydraulically": ["hydraulicly"],
    "hydrazine": ["reducer", "reducing agent", "reductant"],
    "hydrazo group": ["chemical group", "group", "hydrazo radical", "radical"],
    "hydrazoic acid": ["azoimide", "explosive", "hn", "hydride", "hydrogen azide"],
    "hydrazoite": ["azide"],
    "hydremia": ["blood disease", "blood disorder"],
    "hydric": [],
    "hydride": ["azoimide", "binary compound", "calcium hydride", "hn", "hydrazoic acid", "hydrogen azide", "hydrolith", "sodium hydride"],
    "hydrilla": ["aquatic plant", "hydrilla verticillata", "hydrophyte", "hydrophytic plant", "water plant"],
    "hydriodic acid": ["acid"],
    "hydrobates": ["bird genus", "genus hydrobates"],
    "hydrobatidae": ["bird family", "family hydrobatidae"],
    "hydrobromic acid": ["acid"],
    "hydrocarbon": ["aromatic compound", "aromatic hydrocarbon", "bitumen", "bottled gas", "butadiene", "c2h6", "chlorobenzene", "coal oil", "cymene", "dioxin", "ethane", "gas", "gas oil", "gasohol", "gasolene", "gasoline", "indene", "kerosene", "kerosine", "lamp oil", "liquefied petroleum gas", "naphtha", "naphthalene", "octane", "organic compound", "petrol", "provitamin", "pyrene", "terpene"],
    "hydrocele": ["disorder", "upset"],
    "hydrocephalic": [],
    "hydrocephalus": ["abnormalcy", "abnormality", "hydrocephaly"],
    "hydrocharis": ["genus hydrocharis", "liliopsid genus", "monocot genus"],
    "hydrocharitaceae": ["family hydrocharidaceae", "family hydrocharitaceae", "frog's-bit family", "frogbit family", "hydrocharidaceae", "liliopsid family", "monocot family"],
    "hydrochloric acid": ["acid", "chlorohydric acid", "muriatic acid"],
    "hydrochloride": ["complex", "coordination compound"],
    "hydrochlorofluorocarbon": ["cfc", "chlorofluorocarbon", "hcfc"],
    "hydrochlorothiazide": ["esidrix", "hydrodiuril", "microzide", "thiazide"],
    "hydrochoeridae": ["family hydrochoeridae", "mammal family"],
    "hydrochoerus": ["genus hydrochoerus", "mammal genus"],
    "hydrocolloid": ["jell-o", "jello", "substance"],
    "hydrocortisone": ["adrenal cortical steroid", "cortef", "corticoid", "corticosteroid", "cortisol", "hydrocortone"],
    "hydrocracking": ["cracking"],
    "hydrocyanic acid": ["acid", "prussic acid"],
    "hydrodamalis": ["genus hydrodamalis", "mammal genus"],
    "hydrodynamic": [],
    "hydrodynamics": ["fluid mechanics", "hydraulics", "hydrokinetics", "magnetohydrodynamics"],
    "hydroelectric": [],
    "hydroelectric turbine": ["francis turbine", "turbine"],
    "hydroelectricity": ["electricity"],
    "hydroflumethiazide": ["thiazide"],
    "hydrofluoric acid": ["acid"],
    "hydrofluorocarbon": ["fluorocarbon", "greenhouse emission", "greenhouse gas", "hfc"],
    "hydrofoil": ["device", "foil"],
    "hydrogel": ["colloidal gel", "gel"],
    "hydrogen": ["atomic number 1", "chemical element", "element", "gas", "h", "tritium"],
    "hydrogen atom": ["acid hydrogen", "acidic hydrogen", "atom", "deuterium", "heavy hydrogen"],
    "hydrogen bomb": ["atomic weapon", "bomb", "fusion bomb", "h-bomb", "nuclear weapon", "thermonuclear bomb"],
    "hydrogen bond": ["bond", "chemical bond"],
    "hydrogen bromide": ["bromide"],
    "hydrogen chloride": ["acid"],
    "hydrogen cyanide": ["chemical compound", "compound"],
    "hydrogen fluoride": ["fluoride"],
    "hydrogen iodide": ["iodide"],
    "hydrogen ion": ["cation", "proton"],
    "hydrogen ion concentration": ["concentration", "ph", "ph scale"],
    "hydrogen peroxide": ["oxidant", "oxidiser", "oxidizer", "oxidizing agent", "peroxide"],
    "hydrogen sulfide": ["sulfide", "sulphide"],
    "hydrogen-bomb": ["bomb", "bombard"],
    "hydrogenate": ["alter", "change", "modify"],
    "hydrogenation": ["chemical action", "chemical change", "chemical process"],
    "hydrographic": ["hydrographical"],
    "hydrography": ["oceanography", "oceanology"],
    "hydroiodic acid": ["acid"],
    "hydrokinetic": [],
    "hydrolize": ["affect", "bear on", "bear upon", "hydrolise", "impact", "saccharify", "touch", "touch on"],
    "hydrologist": ["geologist"],
    "hydrology": ["geophysical science", "geophysics"],
    "hydrolysate": ["product"],
    "hydrolysis": ["chemical reaction", "reaction"],
    "hydrolyzable": [],
    "hydrolyze": ["change", "hydrolyse"],
    "hydromancer": ["diviner"],
    "hydromancy": ["divination", "foretelling", "fortune telling", "soothsaying"],
    "hydromantes": ["amphibian genus", "genus hydromantes"],
    "hydromel": ["beverage", "drink", "drinkable", "potable"],
    "hydrometer": ["gravimeter", "measuring device", "measuring instrument", "measuring system", "salinometer", "thermogravimeter", "thermohydrometer"],
    "hydrometric": ["gravimetric"],
    "hydrometry": ["gravimetry", "measure", "measurement", "measuring", "mensuration"],
    "hydromorphone hydrochloride": ["analgesic", "anodyne", "dilaudid", "hydromorphone", "pain pill", "painkiller"],
    "hydromyinae": ["mammal family", "subfamily hydromyinae"],
    "hydromys": ["genus hydromys", "mammal genus"],
    "hydronephrosis": ["pathology"],
    "hydropathic": [],
    "hydropathy": ["hydrotherapy", "intervention", "treatment"],
    "hydrophidae": ["family hydrophidae", "reptile family"],
    "hydrophilic": [],
    "hydrophobia": ["symptom"],
    "hydrophobic": [],
    "hydrophobicity": ["property"],
    "hydrophyllaceae": ["asterid dicot family", "family hydrophyllaceae", "waterleaf family"],
    "hydrophyllum": ["asterid dicot genus", "genus hydrophyllum"],
    "hydrophytic": [],
    "hydroplane": ["aviate", "fly", "pilot", "seaplane"],
    "hydroplane racing": ["boat racing"],
    "hydroponics": ["agriculture", "aquiculture", "drip culture", "farming", "husbandry", "tank farming"],
    "hydrosphere": ["layer"],
    "hydrostatic": [],
    "hydrostatic head": ["force per unit area", "pressure", "pressure level"],
    "hydrostatics": ["fluid mechanics", "hydraulics"],
    "hydrothorax": ["congestion"],
    "hydrous": ["hydrated"],
    "hydroxide": ["aluminium hydroxide", "aluminum hydroxide", "calcium hydrate", "calcium hydroxide", "caustic lime", "caustic potash", "caustic soda", "chemical compound", "compound", "hydrated aluminium oxide", "hydrated aluminum oxide", "hydrated lime", "hydrated oxide", "lime", "lime hydrate", "magnesium hydroxide", "potash", "potassium hydroxide", "slaked lime", "sodium hydroxide"],
    "hydroxide ion": ["anion", "hydroxyl ion"],
    "hydroxy": [],
    "hydroxy acid": ["2-hydroxybenzoic acid", "acid", "hydroxybenzoic acid", "juniperic acid", "salicylic acid", "tartaric acid"],
    "hydroxybenzoic acid": ["hydroxy acid"],
    "hydroxybutyric acid": ["beta-hydroxybutyric acid", "butanoic acid", "butyric acid", "oxybutyric acid"],
    "hydroxychloroquine": ["anti-inflammatory", "anti-inflammatory drug", "plaquenil"],
    "hydroxyl": ["chemical group", "group", "hydroxyl group", "hydroxyl radical", "radical"],
    "hydroxymethyl": ["methyl", "methyl group", "methyl radical"],
    "hydroxyproline": ["amino acid", "aminoalkanoic acid"],
    "hydroxyzine hydrochloride": ["antianxiety drug", "anxiolytic", "anxiolytic drug", "atarax", "hydroxyzine", "minor tranquilizer", "minor tranquilliser", "minor tranquillizer", "vistaril"],
    "hydrozoa": ["class", "class hydrozoa"],
    "hydrozoan": ["cnidarian", "coelenterate", "hydra", "hydroid", "planula", "sertularian", "siphonophore"],
    "hydrus": [],
    "hyemoschus": ["genus hyemoschus", "mammal genus"],
    "hyena": ["aardwolf", "brown hyena", "canid", "canine", "crocuta crocuta", "hyaena", "hyaena brunnea", "hyaena hyaena", "laughing hyena", "proteles cristata", "spotted hyena", "strand wolf", "striped hyena"],
    "hygeia": [],
    "hygiene": ["sanitariness"],
    "hygienic": ["hygienical"],
    "hygienically": [],
    "hygienist": ["medical specialist", "specialist"],
    "hygrocybe": ["fungus genus", "genus hygrocybe"],
    "hygrocybe acutoconica": ["conic waxycap", "waxycap"],
    "hygrodeik": ["hygrometer"],
    "hygrometer": ["hygrodeik", "hygroscope", "measuring device", "measuring instrument", "measuring system", "psychrometer"],
    "hygrophoraceae": ["family hygrophoraceae", "fungus family"],
    "hygrophorus": ["fungus genus", "genus hygrophorus"],
    "hygrophorus borealis": ["waxycap"],
    "hygrophorus caeruleus": ["waxycap"],
    "hygrophorus inocybiformis": ["waxycap"],
    "hygrophorus kauffmanii": ["waxycap"],
    "hygrophorus marzuolus": ["waxycap"],
    "hygrophorus purpurascens": ["waxycap"],
    "hygrophorus russula": ["waxycap"],
    "hygrophorus sordidus": ["waxycap"],
    "hygrophorus tennesseensis": ["waxycap"],
    "hygrophorus turundus": ["waxycap"],
    "hygrophyte": ["flora", "plant", "plant life"],
    "hygrophytic": [],
    "hygroscope": ["hygrometer"],
    "hygroscopic": [],
    "hygrotrama": ["fungus genus", "genus hygrotrama"],
    "hygrotrama foetens": ["waxycap"],
    "hyla": ["amphibian genus", "genus hyla"],
    "hylactophryne": ["amphibian genus", "genus hylactophryne"],
    "hylidae": ["amphibian family", "family hylidae"],
    "hylobates": ["genus hylobates", "mammal genus"],
    "hylobatidae": ["family hylobatidae", "mammal family"],
    "hylocereus": ["caryophylloid dicot genus", "genus hylocereus"],
    "hylocichla": ["bird genus", "genus hylocichla"],
    "hylophylax": ["bird genus", "genus hylophylax"],
    "hymen": [],
    "hymenaea": ["genus hymenaea", "rosid dicot genus"],
    "hymenal": [],
    "hymenanthera": ["dilleniid dicot genus", "genus hymenanthera"],
    "hymeneal": ["anthem", "hymn"],
    "hymenium": ["reproductive structure"],
    "hymenogastrales": ["fungus order", "order hymenogastrales"],
    "hymenomycetes": ["class", "class hymenomycetes"],
    "hymenophyllaceae": ["family hymenophyllaceae", "fern family"],
    "hymenophyllum": ["fern genus", "genus hymenophyllum"],
    "hymenoptera": ["animal order", "order hymenoptera"],
    "hymenopterous": [],
    "hymenopterous insect": ["ant", "bee", "chalcid", "chalcid fly", "chalcid wasp", "chalcidfly", "emmet", "family mutillidae", "hymenopter", "hymenopteran", "hymenopteron", "ichneumon fly", "insect", "mutillidae", "pismire", "sawfly", "wasp"],
    "hymn": ["sing"],
    "hymnal": ["hymnary", "hymnbook", "songbook"],
    "hynerpeton": ["amphibian genus", "genus hynerpeton"],
    "hynerpeton bassetti": ["amphibian"],
    "hyoid": ["bone", "hyoid bone", "os", "os hyoideum"],
    "hyoscyamine": ["alkaloid", "poison", "poisonous substance", "toxicant"],
    "hyoscyamus": ["asterid dicot genus", "genus hyoscyamus"],
    "hypaethral": ["hypethral"],
    "hypallage": ["rhetorical device"],
    "hypanthium": ["calyx tube", "floral cup", "plant organ"],
    "hypatia": [],
    "hype": ["air", "bare", "publicise", "publicize"],
    "hype up": ["agitate", "charge", "charge up", "commove", "excite", "psych up", "rouse", "turn on"],
    "hypentelium": ["fish genus", "genus hypentelium"],
    "hyper-eutectoid steel": ["carbon steel"],
    "hyperacidity": ["acidity"],
    "hyperactive": ["overactive"],
    "hyperactivity": ["disorder", "upset"],
    "hyperacusis": ["auditory hyperesthesia", "hearing disorder", "hearing impairment", "hyperacusia"],
    "hyperbaric chamber": ["chamber"],
    "hyperbaton": ["rhetorical device"],
    "hyperbetalipoproteinemia": ["congenital disease", "genetic abnormality", "genetic defect", "genetic disease", "genetic disorder", "hereditary condition", "hereditary disease", "hyperlipoproteinemia", "inherited disease", "inherited disorder"],
    "hyperbilirubinemia": ["hyperbilirubinemia of the newborn", "neonatal hyperbilirubinemia", "pathology"],
    "hyperbilirubinemia of the newborn": ["hyperbilirubinemia", "neonatal hyperbilirubinemia"],
    "hyperbola": ["conic", "conic section"],
    "hyperbole": ["exaggeration", "figure", "figure of speech", "image", "trope"],
    "hyperbolic": [],
    "hyperbolic geometry": ["non-euclidean geometry"],
    "hyperbolically": ["exaggeratedly"],
    "hyperboloid": ["quadric", "quadric surface"],
    "hyperboloidal": [],
    "hyperborean": [],
    "hypercalcemia": ["hypercalcaemia", "symptom"],
    "hypercalciuria": ["hypercalcinuria", "symptom"],
    "hypercapnia": ["hypercarbia", "physical condition", "physiological condition", "physiological state"],
    "hypercatalectic": ["line of poetry", "line of verse"],
    "hypercellularity": ["cellularity"],
    "hypercholesterolemia": ["familial hypercholesterolemia", "hypercholesteremia", "symptom"],
    "hyperchromic anemia": ["anaemia", "anemia", "hyperchromic anaemia"],
    "hypercoaster": ["big dipper", "chute-the-chute", "roller coaster"],
    "hypercritical": ["overcritical"],
    "hyperemesis": ["disgorgement", "emesis", "hyperemesis gravidarum", "puking", "regurgitation", "vomit", "vomiting"],
    "hyperemesis gravidarum": ["hyperemesis"],
    "hyperemia": ["congestion", "engorgement", "hyperaemia"],
    "hyperemic": [],
    "hyperextend": ["exsert", "extend", "hold out", "put out", "stretch forth", "stretch out"],
    "hyperextension": ["extension"],
    "hyperfine": [],
    "hyperfocal distance": ["distance"],
    "hyperglycemia": ["hyperglycaemia", "symptom"],
    "hyperhidrosis": ["diaphoresis", "hidrosis", "hyperidrosis", "perspiration", "polyhidrosis", "sudation", "sweating"],
    "hypericaceae": ["dilleniid dicot family", "family hypericaceae"],
    "hypericism": ["dermatitis"],
    "hypericum": ["dilleniid dicot genus", "genus hypericum"],
    "hyperion": [],
    "hyperkalemia": ["symptom"],
    "hyperlink": ["link"],
    "hyperlipoproteinemia": ["hyperbetalipoproteinemia", "metabolic disorder"],
    "hypermarket": ["supermarket"],
    "hypermastigina": ["animal order", "order hypermastigina"],
    "hypermastigote": ["flagellate", "flagellate protozoan", "flagellated protozoan", "mastigophoran", "mastigophore"],
    "hypermedia": ["hypermedia system", "interactive multimedia", "interactive multimedia system", "multimedia", "multimedia system"],
    "hypermotility": ["illness", "malady", "sickness", "unwellness"],
    "hypernatremia": ["symptom"],
    "hypernym": ["superordinate", "superordinate word", "word"],
    "hypernymy": ["semantic relation", "superordination"],
    "hyperoglyphe": ["fish genus", "genus hyperoglyphe"],
    "hyperon": ["baryon", "heavy particle", "lambda hyperon", "lambda particle"],
    "hyperoodon": ["genus hyperoodon", "mammal genus"],
    "hyperope": ["visually impaired person"],
    "hyperopia": ["ametropia", "farsightedness", "hypermetropia", "hypermetropy", "longsightedness", "presbyopia"],
    "hyperopic": ["hypermetropic"],
    "hyperparathyroidism": ["adenosis", "gland disease", "glandular disease", "glandular disorder"],
    "hyperpigmentation": ["burn", "physical condition", "physiological condition", "physiological state", "sunburn", "suntan", "tan"],
    "hyperpituitarism": ["adenosis", "gland disease", "glandular disease", "glandular disorder"],
    "hyperplasia": ["benign prostatic hyperplasia", "bph", "dysplasia"],
    "hyperpnea": ["breathing", "external respiration", "respiration", "ventilation"],
    "hyperpyrexia": ["febricity", "febrility", "fever", "feverishness", "hyperthermia", "hyperthermy", "pyrexia"],
    "hypersecretion": ["secernment", "secretion"],
    "hypersensitivity": ["cryaesthesia", "cryesthesia", "hypersensitivity reaction", "predisposition", "sensitivity"],
    "hypersensitivity reaction": ["allergic reaction", "allergic rhinitis", "allergy", "anaphylaxis", "hives", "hypersensitivity", "nettle rash", "urticaria", "urtication"],
    "hypersomnia": ["catalepsy", "narcolepsy", "sleep disorder"],
    "hypersplenism": ["symptom"],
    "hypertensive": ["patient"],
    "hypertext": ["machine-readable text"],
    "hypertext markup language": ["html", "hypertext mark-up language", "markup language"],
    "hypertext system": ["object-oriented database management system"],
    "hypertext transfer protocol": ["communications protocol", "http", "protocol"],
    "hyperthermal": [],
    "hyperthermia": ["hyperpyrexia", "hyperthermy", "physical condition", "physiological condition", "physiological state"],
    "hyperthyroidism": ["adenosis", "exophthalmic goiter", "gland disease", "glandular disease", "glandular disorder", "graves' disease", "thyrotoxicosis"],
    "hypertonia": ["hypertonicity", "hypertonus", "tone", "tonicity", "tonus"],
    "hypertonic": [],
    "hypertonicity": ["osmotic pressure"],
    "hypertrophic cardiomyopathy": ["cardiomyopathy", "myocardiopathy"],
    "hypertrophied": ["enlarged"],
    "hypertrophy": ["grow"],
    "hypervelocity": ["speed", "velocity"],
    "hyperventilate": ["care for", "treat"],
    "hyperventilation": ["breathing", "external respiration", "respiration", "ventilation"],
    "hypervitaminosis": ["abnormalcy", "abnormality"],
    "hypervolemia": ["blood disease", "blood disorder", "hypervolaemia"],
    "hypha": ["conidiophore", "fibril", "filament", "rhizomorph", "strand"],
    "hyphantria": ["arthropod genus", "genus hyphantria"],
    "hyphantria cunea": ["webworm moth"],
    "hyphema": ["bleeding", "haemorrhage", "hemorrhage"],
    "hyphen": ["dash", "punctuation", "punctuation mark"],
    "hyphenate": ["hyphen", "spell", "write"],
    "hyphenation": ["punctuation"],
    "hypnagogue": ["agent", "hypnotic", "soporific"],
    "hypnoanalysis": ["analysis", "depth psychology", "psychoanalysis"],
    "hypnogenesis": ["induction"],
    "hypnoid": [],
    "hypnophobia": ["simple phobia"],
    "hypnos": [],
    "hypnosis": ["mental condition", "mental state", "psychological condition", "psychological state", "self-hypnosis"],
    "hypnotherapy": ["psychotherapy"],
    "hypnotic": [],
    "hypnotic trance": ["trance"],
    "hypnotically": [],
    "hypnotism": ["influence", "mesmerism", "suggestion"],
    "hypnotist": ["hypnotiser", "hypnotizer", "mesmerist", "mesmerizer", "psychologist"],
    "hypnotize": ["calm", "entrance", "hypnotise", "mesmerise", "mesmerize", "sedate", "spellbind", "tranquilize", "tranquillise", "tranquillize"],
    "hypo": ["fixer", "fixing agent", "sodium thiosulfate", "sodium thiosulphate"],
    "hypo-eutectoid steel": ["carbon steel"],
    "hypoactive": ["underactive"],
    "hypobasidium": ["plant organ"],
    "hypobetalipoproteinemia": ["abetalipoproteinemia", "hypolipoproteinemia"],
    "hypocalcemia": ["hypocalcaemia", "symptom"],
    "hypocapnia": ["acapnia", "physical condition", "physiological condition", "physiological state"],
    "hypocellularity": ["cellularity"],
    "hypochaeris": ["asterid dicot genus", "genus hypochaeris", "genus hypochoeris", "hypochoeris"],
    "hypochlorite": ["calcium hypochlorite", "salt", "sodium hypochlorite"],
    "hypochlorous acid": ["acid"],
    "hypochondria": ["anxiety", "anxiousness", "hypochondriasis"],
    "hypochondriac": ["patient"],
    "hypochondrium": ["area", "region"],
    "hypochromic anemia": ["anaemia", "anemia", "hypochromic anaemia", "mediterranean anaemia", "mediterranean anemia", "thalassaemia", "thalassemia"],
    "hypocreaceae": ["family hypocreaceae", "fungus family", "mushroom pimple"],
    "hypocreales": ["fungus order", "order hypocreales"],
    "hypocrisy": ["crocodile tears", "dissembling", "feigning", "lip service", "pretence", "pretense"],
    "hypocrite": ["beguiler", "charmer", "cheat", "cheater", "deceiver", "dissembler", "dissimulator", "phoney", "phony", "pretender", "slicker", "smoothie", "smoothy", "sweet talker", "tartufe", "tartuffe", "trickster", "whited sepulcher", "whited sepulchre"],
    "hypocritical": [],
    "hypocritically": [],
    "hypocycloid": ["line roulette", "roulette"],
    "hypoderma": ["arthropod genus", "genus hypoderma"],
    "hypodermal": [],
    "hypodermic": ["subcutaneous"],
    "hypodermic needle": ["needle"],
    "hypodermic syringe": ["autoinjector", "hypo", "hypodermic", "syringe"],
    "hypodermis": ["layer"],
    "hypoesthesia": ["disability", "disablement", "handicap", "hypesthesia", "impairment"],
    "hypogammaglobulinemia": ["immunodeficiency"],
    "hypogastric plexus": ["nerve plexus", "plexus hypogastricus"],
    "hypogastric vein": ["iliac vein", "internal iliac vein", "vena iliaca"],
    "hypoglossal": ["cranial nerve", "hypoglossal nerve", "nervus hypoglosus", "twelfth cranial nerve"],
    "hypoglycemia": ["hypoglycaemia", "symptom"],
    "hypoglycemic": ["hypoglycaemic"],
    "hypoglycemic agent": ["agent", "hypoglycaemic agent", "insulin", "orinase", "tolbutamide"],
    "hypogonadism": ["eunuchoidism", "incompetence", "kallman's syndrome", "male hypogonadism"],
    "hypokalemia": ["symptom"],
    "hypolipoproteinemia": ["hypobetalipoproteinemia", "metabolic disorder"],
    "hyponatremia": ["symptom"],
    "hyponitrous acid": ["acid"],
    "hyponym": ["subordinate", "subordinate word", "word"],
    "hyponymy": ["semantic relation", "subordination"],
    "hypopachus": ["amphibian genus", "genus hypopachus"],
    "hypoparathyroidism": ["adenosis", "gland disease", "glandular disease", "glandular disorder"],
    "hypophosphoric acid": ["oxyacid", "oxygen acid"],
    "hypophosphorous acid": ["orthophosphorous acid", "oxyacid", "oxygen acid", "phosphorous acid"],
    "hypophyseal": ["hypophysial"],
    "hypophyseal stalk": ["infundibulum"],
    "hypophysectomize": ["hypophysectomise", "remove", "take", "take away", "withdraw"],
    "hypophysectomized": ["hypophysectomised"],
    "hypophysectomy": ["ablation", "cutting out", "excision", "extirpation"],
    "hypopigmentation": ["albinism", "physical condition", "physiological condition", "physiological state"],
    "hypopitys": ["dilleniid dicot genus", "genus hypopitys"],
    "hypoplasia": ["dysplasia"],
    "hypoplastic anemia": ["anaemia", "anemia", "hypoplastic anaemia"],
    "hypopnea": ["breathing", "external respiration", "respiration", "ventilation"],
    "hypoproteinemia": ["symptom"],
    "hyposmia": ["dysomia"],
    "hypospadias": ["abnormalcy", "abnormality"],
    "hypostasis": ["biological process", "epistasis", "organic process"],
    "hypostatization": ["hypostatisation", "objectification", "reification"],
    "hypostatize": ["hypostatise", "reify"],
    "hypotension": ["cardiovascular disease", "orthostatic hypotension", "postural hypotension"],
    "hypotensive": ["patient"],
    "hypotenuse": ["flank"],
    "hypothalamic": [],
    "hypothalamically": [],
    "hypothalamus": ["neural structure"],
    "hypothecate": ["pledge"],
    "hypothermia": ["physical condition", "physiological condition", "physiological state"],
    "hypothermic": [],
    "hypothesis": ["proposal"],
    "hypothetical": ["hypothesis", "possibility", "theory"],
    "hypothetical creature": ["alien", "extraterrestrial", "extraterrestrial being", "imaginary being", "imaginary creature"],
    "hypothetical imperative": ["precept", "principle"],
    "hypothetically": [],
    "hypothrombinemia": ["blood disease", "blood disorder"],
    "hypothyroidism": ["adenosis", "cretinism", "gland disease", "glandular disease", "glandular disorder", "myxedema", "myxoedema"],
    "hypotonia": ["hypotonicity", "hypotonus", "tone", "tonicity", "tonus"],
    "hypotonic": [],
    "hypotonicity": ["osmotic pressure"],
    "hypovolemia": ["blood disease", "blood disorder", "hypovolaemia"],
    "hypovolemic": ["hypovolaemic"],
    "hypovolemic shock": ["shock"],
    "hypoxia": ["altitude sickness", "anemic hypoxia", "anoxia", "asphyxiation", "drive", "hypoxic hypoxia", "ischemic hypoxia", "stagnant hypoxia", "suffocation"],
    "hypoxic hypoxia": ["hypoxia"],
    "hypoxidaceae": ["family hypoxidaceae", "liliid monocot family"],
    "hypoxis": ["genus hypoxis", "liliid monocot genus"],
    "hypozeugma": ["rhetorical device"],
    "hypozeuxis": ["rhetorical device"],
    "hypsiglena": ["genus hypsiglena", "reptile genus"],
    "hypsiprymnodon": ["genus hypsiprymnodon", "mammal genus"],
    "hypsography": ["geology"],
    "hypsometer": ["altimeter"],
    "hypsometry": ["hypsography", "measure", "measurement", "measuring", "mensuration"],
    "hyracoidea": ["animal order", "order hyracoidea"],
    "hyracotherium": ["genus hyracotherium", "mammal genus"],
    "hyrax": ["coney", "cony", "das", "dassie", "eutherian", "eutherian mammal", "placental", "placental mammal", "procavia capensis", "rock hyrax", "rock rabbit"],
    "hyson": ["green tea"],
    "hyssop": ["herb", "herbaceous plant", "hyssopus officinalis"],
    "hyssop oil": ["oil"],
    "hyssopus": ["asterid dicot genus", "genus hyssopus"],
    "hysterectomy": ["ablation", "cutting out", "excision", "extirpation", "panhysterectomy", "radical hysterectomy", "total hysterectomy"],
    "hysteresis": ["physical phenomenon"],
    "hysteria": ["anxiety hysteria", "hysterical neurosis", "hysterocatalepsy", "neurosis", "neuroticism", "psychoneurosis"],
    "hysteric": ["mental case", "neurotic", "psychoneurotic"],
    "hysterical": [],
    "hysterically": [],
    "hysterics": ["attack"],
    "hysterocatalepsy": ["hysteria", "hysterical neurosis"],
    "hysteron proteron": ["rhetorical device"],
    "hysterosalpingogram": ["roentgenogram", "x ray", "x-ray", "x-ray photograph", "x-ray picture"],
    "hysteroscopy": ["endoscopy"],
    "hysterotomy": ["operation", "surgery", "surgical operation", "surgical procedure", "surgical process"],
    "hystricidae": ["family hystricidae", "mammal family"],
    "hystricomorpha": ["animal order", "suborder hystricomorpha"],
    "i": ["alphabetic character", "letter", "letter of the alphabet"],
    "i chronicles": ["1 chronicles"],
    "i esdra": ["1 esdras"],
    "i kings": ["1 kings"],
    "i maccabees": ["1 maccabees"],
    "i samuel": ["1 samuel"],
    "i-beam": ["girder"],
    "iago": [],
    "iamb": ["foot", "iambus", "metrical foot", "metrical unit"],
    "iambic": ["verse", "verse line"],
    "iapetus": [],
    "iatrogenic": [],
    "ibadan": [],
    "iberia": [],
    "iberian": ["asian", "asiatic"],
    "iberian peninsula": ["iberia"],
    "iberis": ["dilleniid dicot genus", "genus iberis"],
    "ibero-mesornis": ["bird"],
    "ibert": ["jacques francois antoine ibert"],
    "ibex": ["capra ibex", "wild goat"],
    "ibid": ["ib.", "ibid.", "ibidem"],
    "ibis": ["ibis ibis", "sacred ibis", "threskiornis aethiopica", "wader", "wading bird", "wood ibis", "wood stork"],
    "ibizan hound": ["hound", "hound dog", "ibizan podenco"],
    "ibolium privet": ["ibota privet", "ligustrum ibolium", "privet"],
    "ibsen": ["henrik ibsen", "henrik johan ibsen"],
    "ibsenian": [],
    "ibuprofen": ["advil", "isobutylphenyl propionic acid", "motrin", "nonsteroidal anti-inflammatory", "nonsteroidal anti-inflammatory drug", "nsaid", "nuprin"],
    "icarus": [],
    "ice": ["freeze"],
    "ice age": ["geological period", "glacial epoch", "glacial period", "period"],
    "ice ax": ["ax", "axe", "ice axe", "piolet"],
    "ice bear": ["bear", "polar bear", "thalarctos maritimus", "ursus maritimus"],
    "ice cream": ["chocolate ice cream", "frozen dessert", "icecream", "neapolitan ice cream", "peach ice cream", "strawberry ice cream", "tutti-frutti", "vanilla ice cream"],
    "ice crystal": ["crystal", "diamond dust", "frost mist", "frost snow", "ice needle", "poudrin", "snow mist"],
    "ice cube": ["cube", "square block"],
    "ice field": ["ice mass"],
    "ice floe": ["floe", "ice mass"],
    "ice fog": ["fog", "pogonip"],
    "ice hockey": ["athletic game", "contact sport", "hockey", "hockey game"],
    "ice hockey rink": ["ice", "ice rink", "ice-hockey rink", "ice-skating rink"],
    "ice lolly": ["frozen dessert", "lollipop", "lolly", "popsicle"],
    "ice machine": ["electric refrigerator", "fridge"],
    "ice maker": ["kitchen appliance"],
    "ice mass": ["berg", "floe", "formation", "geological formation", "glacier", "ice cap", "ice field", "ice floe", "iceberg", "icecap"],
    "ice milk": ["frozen dessert"],
    "ice pack": ["bag", "ice bag"],
    "ice plant": ["fig marigold", "icicle plant", "mesembryanthemum crystallinum", "pebble plant"],
    "ice rink": ["ice", "ice hockey rink", "ice-hockey rink", "ice-skating rink", "rink", "skating rink"],
    "ice show": ["show"],
    "ice skate": ["skate"],
    "ice skating": ["figure skating", "skating"],
    "ice storm": ["silver storm", "storm", "violent storm"],
    "ice tea": ["iced tea", "tea"],
    "ice tongs": ["pair of tongs", "tongs"],
    "ice up": ["change", "frost over", "ice over"],
    "ice wagon": ["ice-wagon", "waggon", "wagon"],
    "ice water": ["drinking water"],
    "ice-clogged": [],
    "ice-cold": [],
    "ice-cream bean": ["inga edulis", "tree"],
    "ice-cream cake": ["frozen dessert", "icebox cake"],
    "ice-cream cone": ["frozen dessert"],
    "ice-cream soda": ["drink", "float", "ice-cream float", "root beer float"],
    "ice-cream sundae": ["frozen dessert", "sundae"],
    "ice-free": [],
    "ice-skater": ["skater", "speed skater", "speedskater"],
    "iceberg": ["berg", "floater", "growler", "ice mass"],
    "iceboat": ["ice yacht", "scooter", "vessel", "watercraft"],
    "icebound": [],
    "icebreaker": ["iceboat", "ship"],
    "icecap": ["ice cap", "ice mass"],
    "iced coffee": ["coffee", "ice coffee", "java"],
    "iced-tea spoon": ["teaspoon"],
    "icefall": ["ice"],
    "icehouse": ["house"],
    "iceland": ["republic of iceland"],
    "iceland moss": ["cetraria islandica", "iceland lichen", "lichen"],
    "iceland poppy": ["arctic poppy", "papaver nudicaule", "poppy"],
    "iceland spar": ["calcite"],
    "icelander": ["european"],
    "icelandic": ["nordic", "norse", "north germanic", "north germanic language", "scandinavian", "scandinavian language"],
    "icelandic krona": ["icelandic monetary unit", "krona"],
    "icelandic monetary unit": ["eyrir", "icelandic krona", "krona", "monetary unit"],
    "icelandic-speaking": [],
    "iceman": ["deliverer", "delivery boy", "deliveryman"],
    "icepick": ["ice pick", "pick"],
    "icetray": ["tray"],
    "ichneumon": ["herpestes ichneumon", "mongoose"],
    "ichneumon fly": ["hymenopter", "hymenopteran", "hymenopteron", "hymenopterous insect"],
    "ichneumonidae": ["arthropod family", "family ichneumonidae"],
    "ichor": ["fluid"],
    "ichorous": ["sanious"],
    "ichthyolatry": ["animal-worship", "fish-worship", "zoolatry"],
    "ichthyologist": ["animal scientist", "zoologist"],
    "ichthyology": ["zoological science", "zoology"],
    "ichthyosaur": ["archosaur", "archosaurian", "archosaurian reptile", "ichthyosaurus", "stenopterygius", "stenopterygius quadrisicissus"],
    "ichthyosauria": ["animal order", "order ichthyosauria"],
    "ichthyosauridae": ["family ichthyosauridae", "reptile family"],
    "ichthyosaurus": ["ichthyosaur"],
    "ichthyosis": ["congenital disease", "genetic abnormality", "genetic defect", "genetic disease", "genetic disorder", "hereditary condition", "hereditary disease", "inherited disease", "inherited disorder", "xeroderma", "xerodermia"],
    "ichyostega": ["amphibian"],
    "icicle": ["ice", "water ice"],
    "icily": [],
    "icing": ["icing the puck", "maneuver", "manoeuvre", "play"],
    "icing sugar": ["powdered sugar"],
    "icky": ["crappy", "lousy", "rotten", "shitty", "stinking", "stinky"],
    "icon": ["symbol"],
    "iconic": [],
    "iconoclasm": ["heresy", "heterodoxy", "unorthodoxy"],
    "iconoclast": ["destroyer", "image breaker", "ruiner", "undoer", "uprooter", "waster"],
    "iconoclastic": [],
    "iconography": ["icon", "ikon", "image", "picture"],
    "iconolatry": ["idol worship", "idolatry"],
    "iconology": ["art history"],
    "iconoscope": ["television pickup tube", "television-camera tube"],
    "icosahedral": [],
    "icosahedron": ["polyhedron"],
    "ictal": ["ictic"],
    "ictalurus": ["fish genus", "genus ictalurus"],
    "icteria": ["bird genus", "genus icteria"],
    "icteridae": ["bird family", "family icteridae"],
    "icterogenic": [],
    "icterus": ["bird genus", "genus icterus"],
    "ictiobus": ["fish genus", "genus ictiobus"],
    "ictodosaur": ["synapsid", "synapsid reptile"],
    "ictodosauria": ["animal order", "order ictodosauria"],
    "ictonyx": ["genus ictonyx", "mammal genus"],
    "icy": [],
    "id": ["badge", "i.d.", "positive identification"],
    "id al-adha": ["feast day", "feast of sacrifice", "fete day"],
    "id al-fitr": ["feast day", "fete day"],
    "idaho": ["gem state", "id"],
    "idaho falls": [],
    "idahoan": ["american"],
    "idea": ["opinion", "persuasion", "sentiment", "thought", "view"],
    "ideal": ["apotheosis", "class act", "crackerjack", "humdinger", "jimdandy", "jimhickey", "model", "nonesuch", "nonpareil", "nonsuch", "paragon", "role model", "saint"],
    "ideal gas": ["gas", "perfect gas"],
    "idealism": ["philosophical doctrine", "philosophical theory"],
    "idealist": ["don quixote", "dreamer", "romantic", "visionary"],
    "ideality": ["quality"],
    "idealization": ["defence", "defence mechanism", "defence reaction", "defense", "defense mechanism", "defense reaction", "idealisation"],
    "idealize": ["consider", "deify", "glamorize", "glamourise", "idealise", "reckon", "regard", "romanticise", "romanticize", "see", "view"],
    "idealized": ["idealised"],
    "ideally": [],
    "ideation": ["cerebration", "intellection", "mentation", "thinking", "thought", "thought process"],
    "idempotent": [],
    "identical": ["selfsame", "very"],
    "identical twin": ["conjoined twin", "monozygotic twin", "monozygous twin", "siamese twin", "twin"],
    "identically": [],
    "identifiable": [],
    "identifiably": [],
    "identification": ["condition", "status"],
    "identification particle": ["atom", "corpuscle", "microtaggant", "molecule", "mote", "particle", "speck"],
    "identified": [],
    "identifier": ["symbol"],
    "identify": ["associate", "colligate", "connect", "link", "link up", "relate", "tie in"],
    "identikit": ["identikit picture", "likeness", "semblance"],
    "identity": ["identity element", "identity operator", "operator"],
    "identity crisis": ["mental condition", "mental state", "psychological condition", "psychological state"],
    "identity matrix": ["scalar matrix", "unit matrix"],
    "identity theft": ["fraud"],
    "ideogram": ["character", "grapheme", "graphic symbol", "ideograph", "logogram", "logograph"],
    "ideographic": [],
    "ideographically": [],
    "ideography": ["orthography", "writing system"],
    "ideological": [],
    "ideological barrier": ["bamboo curtain", "barrier", "color bar", "color line", "colour bar", "colour line", "iron curtain", "jim crow", "roadblock"],
    "ideologically": [],
    "ideologist": ["advocate", "advocator", "exponent", "ideologue", "proponent"],
    "ideology": ["theorisation", "theorization"],
    "ides": ["day"],
    "idesia": ["idesia polycarpa", "tree"],
    "idiocy": ["amentia", "backwardness", "mental retardation", "retardation", "slowness", "subnormality"],
    "idiographic": [],
    "idiolatry": ["autolatry", "self-worship", "worship"],
    "idiolect": ["language", "oral communication", "speech", "speech communication", "spoken communication", "spoken language", "voice communication"],
    "idiom": ["expression", "idiomatic expression", "locution", "phrasal idiom", "phrase", "ruralism", "rusticism", "saying", "set phrase"],
    "idiom neutral": ["artificial language"],
    "idiomatic": ["idiomatical"],
    "idiomatically": [],
    "idiopathic": [],
    "idiopathic disease": ["disorder", "idiopathic disorder", "idiopathy", "upset"],
    "idiosyncrasy": ["distinctiveness", "foible", "mannerism", "peculiarity", "speciality", "specialness", "specialty"],
    "idiosyncratic": [],
    "idiot": ["changeling", "cretin", "half-wit", "imbecile", "mongoloid", "moron", "retard", "simple", "simpleton"],
    "idiot light": ["red light", "warning light"],
    "idiot savant": ["simple", "simpleton"],
    "idiotically": [],
    "iditarod": ["cross country", "iditarod trail dog sled race"],
    "iditarod trail": [],
    "idle": ["arse about", "arse around", "bum", "bum about", "bum around", "daydream", "frig around", "fuck off", "laze", "lie about", "lie around", "loaf", "loll", "loll around", "lounge about", "lounge around", "moon", "moon around", "moon on", "ride the bench", "slug", "stagnate", "warm the bench", "waste one's time"],
    "idle pulley": ["block", "idle wheel", "idler pulley", "pulley", "pulley block", "pulley-block"],
    "idleness": ["dolce far niente", "idling", "inactivity", "loafing"],
    "idler": ["bum", "clock watcher", "couch potato", "dallier", "dawdler", "daydreamer", "dilly-dallier", "dillydallier", "do-nothing", "drone", "goldbrick", "good-for-naught", "good-for-nothing", "goof-off", "laggard", "lagger", "layabout", "lazybones", "lie-abed", "loafer", "loon", "lounger", "mope", "ne'er-do-well", "no-account", "nonworker", "poke", "shirker", "slacker", "slug", "slugabed", "sluggard", "spiv", "sunbather", "trailer", "trifler", "whittler", "woolgatherer"],
    "idly": ["lazily"],
    "ido": ["artificial language"],
    "idol": ["heartthrob", "lead", "matinee idol", "principal", "star"],
    "idolater": ["gentile", "heathen", "idol worshiper", "idolatress", "idoliser", "idolizer", "infidel", "pagan"],
    "idolatress": ["idol worshiper", "idolater", "idoliser", "idolizer"],
    "idolatrous": [],
    "idolatrously": [],
    "idolatry": ["anthropolatry", "bible-worship", "bibliolatry", "cultism", "devotion", "grammatolatry", "gynaeolatry", "gyneolatry", "lordolatry", "miracle-worship", "place-worship", "symbol-worship", "symbolatry", "symbololatry", "thaumatolatry", "topolatry", "veneration", "verbolatry", "woman-worship", "word-worship", "worship", "worship of man"],
    "idolization": ["bardolatry", "idolisation", "worship"],
    "idolize": ["adore", "drool over", "hero-worship", "idolise", "revere", "slobber over", "worship"],
    "idolizer": ["idoliser", "lover"],
    "idun": ["ithunn"],
    "idyll": ["episode"],
    "idyllic": [],
    "idyllically": [],
    "if not": [],
    "igbo": ["ethnic group", "ethnos", "nigerian"],
    "igigi": [],
    "iglesias": ["julio iglesias"],
    "igloo": ["hovel", "hut", "hutch", "iglu", "shack", "shanty"],
    "ignatius": ["saint ignatius", "st. ignatius"],
    "ignatius of loyola": ["loyola", "saint ignatius of loyola", "st. ignatius of loyola"],
    "igneous": ["pyrogenic", "pyrogenous"],
    "igneous rock": ["adesite", "andesite", "aplite", "batholite", "batholith", "diorite", "gabbro", "groundmass", "pegmatite", "peridotite", "pluton", "plutonic rock", "porphyritic rock", "porphyry", "rhyolite", "rock", "stone", "volcanic rock"],
    "ignescent": [],
    "ignite": ["burn", "combust", "conflagrate", "enkindle", "fire up", "flare up", "inflame", "kindle", "light", "light up", "reignite"],
    "ignited": ["enkindled", "kindled"],
    "igniter": ["firelighter", "fuel", "ignitor", "kindling", "lighter", "punk", "spunk", "tinder", "touchwood"],
    "ignition": ["fire", "flame", "flaming", "spontaneous combustion"],
    "ignition coil": ["induction coil"],
    "ignition key": ["key"],
    "ignition switch": ["electric switch", "electrical switch", "switch"],
    "ignoble": ["ungentle", "untitled"],
    "ignobleness": ["dishonorableness", "dishonourableness", "ignobility"],
    "ignoramus": ["aliterate", "aliterate person", "illiterate", "illiterate person", "know nothing", "nonreader", "uneducated person", "unskilled person"],
    "ignorance": ["cognitive content", "content", "ignorantness", "illiteracy", "inexperience", "mental object", "nescience", "rawness", "unenlightenment", "unknowing", "unknowingness"],
    "ignorant": ["unknowing", "unknowledgeable", "unwitting"],
    "ignorantly": [],
    "ignorantness": ["ignorance", "nescience", "unknowing", "unknowingness"],
    "ignoratio elenchi": ["logical fallacy"],
    "ignore": ["pass up"],
    "ignored": ["neglected", "unheeded"],
    "iguanid": ["amblyrhynchus cristatus", "american chameleon", "anole", "anolis carolinensis", "basilisk", "callisaurus draconoides", "chuckwalla", "collared lizard", "common iguana", "desert iguana", "dipsosaurus dorsalis", "earless lizard", "fringe-toed lizard", "gridiron-tailed lizard", "horned lizard", "horned toad", "horny frog", "iguana", "iguana iguana", "iguanid lizard", "leopard lizard", "lizard", "marine iguana", "sand lizard", "sauromalus obesus", "side-blotched lizard", "spiny lizard", "tree lizard", "uma notata", "urosaurus ornatus", "uta stansburiana", "zebra-tailed lizard"],
    "iguanidae": ["family iguania", "family iguanidae", "iguania", "reptile family"],
    "iguanodon": ["dinosaur"],
    "iguanodontidae": ["family iguanodontidae", "reptile family"],
    "iguazu": ["iguassu", "iguassu falls", "iguazu falls", "victoria falls"],
    "ii chronicles": ["2 chronicles"],
    "ii esdras": ["2 esdras"],
    "ii kings": ["2 kings"],
    "ii maccabees": ["2 maccabees"],
    "ii samuel": ["2 samuel"],
    "ijssel": ["ijssel river"],
    "ijsselmeer": [],
    "ijtihad": ["interpretation"],
    "ilama": ["annona diversifolia", "custard apple", "custard apple tree", "ilama tree"],
    "ilang-ilang": ["essential oil", "volatile oil"],
    "ile-de-france": [],
    "ile-st-louis": [],
    "ileal artery": ["arteria", "arteria ileum", "arterial blood vessel", "artery", "intestinal artery"],
    "ileitis": ["inflammation", "redness", "rubor"],
    "ileocecal valve": ["valve"],
    "ileocolic artery": ["arteria", "arteria ileocolica", "arterial blood vessel", "artery"],
    "ileocolic vein": ["vein", "vena", "vena ileocolica", "venous blood vessel"],
    "ileostomy": ["ostomy"],
    "ileum": ["small intestine"],
    "ilex": ["dicot genus", "genus ilex", "magnoliopsid genus"],
    "iliac": [],
    "iliac artery": ["arteria", "arteria iliaca", "arterial blood vessel", "artery", "common iliac artery", "external iliac artery", "hypogastric artery", "internal iliac artery"],
    "iliac vein": ["common iliac vein", "external iliac vein", "hypogastric vein", "internal iliac vein", "vein", "vena", "vena iliaca", "venous blood vessel"],
    "iliad": [],
    "iliamna": ["dilleniid dicot genus", "genus iliamna"],
    "iliolumbar artery": ["arteria", "arteria iliolumbalis", "arterial blood vessel", "artery"],
    "iliolumbar vein": ["vein", "vena", "vena iliolumbalis", "venous blood vessel"],
    "ilium": ["bone", "os"],
    "ill": ["badly"],
    "ill health": ["affliction", "biliousness", "dyscrasia", "harm", "health problem", "hurt", "illness", "infection", "injury", "invalidism", "malady", "pathological state", "pathology", "sickness", "softness", "trauma", "unfitness", "unhealthiness", "unwellness"],
    "ill humor": ["choler", "crossness", "distemper", "fretfulness", "fussiness", "humor", "humour", "ill humour", "irritability", "mood", "moodiness", "peevishness", "petulance", "temper"],
    "ill nature": ["asperity", "biliousness", "contrariness", "crabbedness", "crabbiness", "crankiness", "crossness", "crotchetiness", "disposition", "grumpiness", "impatience", "irritability", "moroseness", "peevishness", "pettishness", "sharpness", "shrewishness", "snappishness", "sourness", "sulkiness", "sullenness", "surliness", "temper", "temperament"],
    "ill-advised": ["unadvised"],
    "ill-being": ["adversity", "hard knocks", "hardship", "miserableness", "misery", "wretchedness"],
    "ill-bred": ["bounderish", "lowbred", "rude", "underbred", "yokelish"],
    "ill-conceived": ["misguided"],
    "ill-considered": ["ill-judged", "improvident", "shortsighted"],
    "ill-defined": ["unclear"],
    "ill-dressed": [],
    "ill-equipped": [],
    "ill-famed": ["infamous", "notorious"],
    "ill-favored": ["ill-favoured"],
    "ill-fed": ["underfed", "undernourished"],
    "ill-fitting": [],
    "ill-mannered": ["bad-mannered", "rude", "unmannered", "unmannerly"],
    "ill-natured": [],
    "ill-proportioned": [],
    "ill-sorted": ["incompatible", "mismated", "unsuited"],
    "ill-timed": ["unseasonable", "untimely", "wrong"],
    "illampu": [],
    "illative": ["inferential"],
    "illecebrum": ["caryophylloid dicot genus", "genus illecebrum"],
    "illegal": [],
    "illegal possession": ["criminal possession"],
    "illegality": ["infection", "lawlessness", "outlawry", "unlawfulness"],
    "illegally": ["illicitly", "lawlessly"],
    "illegibility": ["incomprehensibility"],
    "illegible": [],
    "illegibly": ["undecipherably", "unreadably"],
    "illegitimacy": ["unlawfulness"],
    "illegitimate": [],
    "illegitimately": ["illicitly"],
    "illiberal": ["intolerant"],
    "illiberality": ["stinginess"],
    "illicit": [],
    "illicitness": ["unlawfulness"],
    "illicium": ["genus illicium", "magnoliid dicot genus"],
    "illimani": [],
    "illimitable": ["limitless", "measureless"],
    "illinois": ["algonquian", "algonquin"],
    "illinois river": [],
    "illinoisan": ["american"],
    "illiteracy": ["ignorance"],
    "illiterate": ["analphabet", "analphabetic", "functional illiterate", "ignoramus", "illiterate person", "know nothing", "nonreader", "uneducated person"],
    "illness": ["aeroembolism", "ague", "air embolism", "amyloidosis", "anuresis", "anuria", "bends", "caisson disease", "catastrophic illness", "collapse", "condition", "decompression sickness", "disease", "food poisoning", "gas embolism", "gastrointestinal disorder", "growth", "health problem", "hypermotility", "ill health", "indisposition", "lead poisoning", "malady", "ozone sickness", "plumbism", "prostration", "saturnism", "sickness", "toxaemia", "toxaemia of pregnancy", "toxemia", "toxemia of pregnancy", "unhealthiness", "unwellness"],
    "illogical": ["unlogical"],
    "illogicality": ["illogic", "illogicalness", "inconsequence", "invalidity", "invalidness", "quality"],
    "illogically": [],
    "illuminance": ["brightness", "brightness level", "illumination", "light", "luminance", "luminosity", "luminousness"],
    "illuminant": ["fuel"],
    "illuminate": ["adorn", "beautify", "decorate", "embellish", "grace", "miniate", "ornament", "rubricate"],
    "illuminated": ["lighted", "lit", "well-lighted"],
    "illumination": ["dark", "darkness", "light", "lighting", "state"],
    "illumination unit": ["footcandle", "l", "lambert", "light unit", "lux", "lx", "phot"],
    "illusion": ["apparition", "appearance", "fantasm", "irradiation", "phantasm", "phantasma", "phantom", "phantom limb", "semblance", "shadow"],
    "illusional": ["illusionary"],
    "illusive": ["illusory"],
    "illustrate": ["depict", "picture", "render", "show"],
    "illustration": ["art", "artwork", "fig", "figure", "graphics", "nontextual matter", "pictorial matter", "picture"],
    "illustrator": ["artist", "commercial artist", "creative person"],
    "illustrious": [],
    "illustriously": [],
    "illyria": [],
    "illyrian": ["indo-european", "indo-european language", "indo-hittite"],
    "ilmenite": ["mineral"],
    "image": ["visualise", "visualize"],
    "image compression": ["compression"],
    "imaginary being": ["cadmus", "character", "fictional character", "fictitious character", "giant", "hobbit", "hypothetical creature", "imaginary creature", "imagination", "imaginativeness", "mermaid", "merman", "monster", "mythical being", "psychopomp", "sylph", "unicorn", "vision", "witch"],
    "imaginary part": ["imaginary part of a complex number", "pure imaginary number"],
    "imaginary place": ["afterworld", "annwfn", "annwn", "asgard", "atlantis", "brobdingnag", "cloud-cuckoo-land", "cockaigne", "dreamland", "dreamworld", "el dorado", "eldorado", "elysium", "faerie", "faery", "fairyland", "fictitious place", "hades", "heaven", "hell", "houyhnhnms", "imagination", "imaginativeness", "infernal region", "inferno", "laputa", "lilliput", "limbo", "midgard", "mythical place", "nether region", "netherworld", "never-never land", "perdition", "pit", "purgatory", "ruritania", "scheol", "sion", "spirit world", "underworld", "utopia", "vision", "wonderland", "zion"],
    "imagination": ["chimaera", "chimera", "dream", "dreaming", "envisioning", "evocation", "imagery", "imaging", "make-believe", "mental imagery", "mind's eye", "picturing", "pretence", "pretense", "representational process", "vision"],
    "imagination image": ["image", "mental image", "thought-image"],
    "imaginative": ["inventive"],
    "imaginative comparison": ["comparison"],
    "imaginatively": [],
    "imagine": ["conceive of", "create by mental act", "create mentally", "daydream", "dream", "envisage", "envision", "fancy", "fantasise", "fantasize", "fantasy", "figure", "foresee", "ideate", "image", "picture", "prefigure", "project", "see", "stargaze", "think", "visualise", "visualize", "woolgather"],
    "imaging": ["echography", "magnetic resonance imaging", "mri", "pet", "pictorial representation", "picturing", "positron emission tomography", "radiology", "radioscopy", "sonography", "tomography", "ultrasonography", "ultrasound", "x-radiation", "x-raying"],
    "imagism": ["art movement", "artistic movement"],
    "imago": ["epitome", "image", "paradigm", "prototype"],
    "imam": ["imaum", "leader", "moslem", "muslim"],
    "imaret": ["auberge", "hostel", "hostelry", "inn", "lodge"],
    "imbalance": ["disequilibrium", "instability", "unbalance"],
    "imbecile": ["idiotic", "imbecilic"],
    "imbecility": ["backwardness", "mental retardation", "retardation", "slowness", "subnormality"],
    "imbibe": ["absorb", "assimilate", "ingest", "take in"],
    "imbibition": ["absorption", "soaking up"],
    "imbricate": ["lay", "place", "pose", "position", "put", "set"],
    "imbrication": ["covering", "lapping", "overlapping"],
    "imbroglio": ["embroilment", "situation"],
    "imbrue": ["drench", "impregnate", "saturate"],
    "imbue": ["color", "color in", "colorise", "colorize", "colour", "colour in", "colourise", "colourize", "hue"],
    "imidazole": ["alkali", "base", "glyoxaline", "iminazole"],
    "imide": ["organic compound"],
    "imipramine": ["imavate", "impramine hydrochloride", "tofranil", "tricyclic", "tricyclic antidepressant", "tricyclic antidepressant drug"],
    "imitate": ["ape", "emulate", "follow suit", "resemble"],
    "imitation": ["doctrine", "ism", "mimesis", "philosophical system", "philosophy", "school of thought"],
    "imitative": [],
    "imitative electronic deception": ["electronic deception", "electronic imitative deception"],
    "immaculate": ["undefiled"],
    "immaculate conception": ["december 8", "holy day of obligation"],
    "immaculately": [],
    "immanence": ["immanency", "presence"],
    "immanent": ["subjective"],
    "immaterial": [],
    "immateriality": ["irrelevance", "irrelevancy"],
    "immaterialize": ["alter", "change", "disincarnate", "immaterialise", "modify", "unsubstantialise", "unsubstantialize"],
    "immature": [],
    "immaturely": ["jejunely"],
    "immaturity": ["adolescence", "babyhood", "callowness", "childhood", "greenness", "immatureness", "infancy", "jejuneness", "juvenility", "prematureness", "prematurity", "puerility", "state"],
    "immeasurable": ["immensurable", "unmeasurable", "unmeasured"],
    "immeasurably": [],
    "immediacy": ["immediate apprehension", "intuition"],
    "immediate": [],
    "immediate allergy": ["allergic reaction", "allergy", "atopic allergy", "atopy", "type i allergic reaction"],
    "immediate constituent": ["constituent", "grammatical constituent"],
    "immediately": [],
    "immemorial": [],
    "immerse": ["bury", "close in", "eat up", "enclose", "inclose", "shut in", "swallow", "swallow up"],
    "immersion": ["baptism", "trine immersion"],
    "immersion heater": ["heating element"],
    "immigrant": ["migrant", "migrator"],
    "immigrant class": ["class", "social class", "socio-economic class", "stratum"],
    "immigrate": ["migrate", "transmigrate"],
    "immigration": ["body"],
    "immigration and naturalization service": ["agency", "authority", "bureau", "federal agency", "government agency", "ins", "office"],
    "imminence": ["forthcomingness", "imminency", "imminentness", "impendence", "impendency", "state"],
    "imminent abortion": ["miscarriage", "spontaneous abortion", "stillbirth", "threatened abortion"],
    "imminently": [],
    "immiscible": ["non-miscible", "unmixable"],
    "immobile": [],
    "immobility": ["immotility", "immovability", "immovableness", "inertness", "quality"],
    "immobilization": ["immobilisation", "preservation", "saving"],
    "immobilize": ["immobilise", "keep back", "withhold"],
    "immoderate": [],
    "immoderately": [],
    "immoderation": ["degree", "excess", "excessiveness", "grade", "immoderateness", "inordinateness", "level"],
    "immodest": [],
    "immodestly": [],
    "immodesty": ["indecency"],
    "immolate": ["sacrifice"],
    "immolation": ["ritual killing", "sacrifice"],
    "immoral": [],
    "immorality": ["anomie", "anomy", "corruptibility", "corruption", "degeneracy", "depravation", "depravity", "evil", "evilness", "licentiousness", "putrefaction", "quality", "unrighteousness", "wantonness", "wrongness"],
    "immorally": ["amorally"],
    "immortal": ["celebrity", "famous person"],
    "immortality": ["afterlife", "hereafter"],
    "immortalize": ["alter", "change", "eternalise", "eternalize", "eternise", "eternize", "immortalise", "modify"],
    "immortelle": ["everlasting", "everlasting flower", "xeranthemum annuum"],
    "immotility": ["immobility"],
    "immovability": ["fastness", "firmness", "fixedness", "fixity", "fixture", "immobility", "immovableness", "secureness", "steadiness", "tautness", "tightness"],
    "immovable": ["immoveable", "stabile", "unmovable"],
    "immovable bandage": ["bandage", "patch"],
    "immovably": [],
    "immune": ["carrier", "immune carrier", "individual", "mortal", "person", "somebody", "someone", "soul"],
    "immune response": ["anamnestic reaction", "anamnestic response", "cell-mediated immune response", "complement fixation", "humoral immune response", "immune reaction", "immunologic response", "reaction", "response"],
    "immune system": ["system"],
    "immunity": ["acquired immunity", "condition", "immunogenicity", "innate immunity", "natural immunity", "resistance", "status"],
    "immunization": ["immunisation", "inoculation", "protection", "sensitisation", "sensitising", "sensitization", "sensitizing", "vaccination"],
    "immunize": ["immunise", "protect"],
    "immunized": ["immunised", "vaccinated"],
    "immunoassay": ["bio-assay", "bioassay", "immunochemical assay", "radioimmunoassay"],
    "immunochemical": [],
    "immunochemistry": ["chemical science", "chemistry", "chemoimmunology", "immunology"],
    "immunocompetence": ["ability"],
    "immunocompetent": [],
    "immunocompromised": [],
    "immunodeficiency": ["acquired immune deficiency syndrome", "agammaglobulinemia", "aids", "hypogammaglobulinemia", "immunological disorder", "scid", "severe combined immunodeficiency", "severe combined immunodeficiency disease"],
    "immunodeficient": [],
    "immunoelectrophoresis": ["cataphoresis", "dielectrolysis", "electrophoresis", "ionophoresis"],
    "immunofluorescence": ["technique"],
    "immunogen": ["antigen", "immunizing agent", "toxin antitoxin", "vaccine", "vaccinum"],
    "immunogenic": [],
    "immunogenicity": ["immunity", "resistance"],
    "immunoglobulin": ["antibody", "gamma globulin", "human gamma globulin", "ig", "iga", "igd", "ige", "igg", "igm", "immune gamma globulin", "immune globulin", "immune serum globulin", "immunoglobulin a", "immunoglobulin d", "immunoglobulin e", "immunoglobulin g", "immunoglobulin m", "tetanus immune globulin", "tetanus immunoglobulin"],
    "immunoglobulin a": ["ig", "iga", "immune gamma globulin", "immune globulin", "immune serum globulin", "immunoglobulin"],
    "immunoglobulin d": ["ig", "igd", "immune gamma globulin", "immune globulin", "immune serum globulin", "immunoglobulin"],
    "immunoglobulin e": ["ig", "ige", "immune gamma globulin", "immune globulin", "immune serum globulin", "immunoglobulin", "reagin"],
    "immunoglobulin g": ["ig", "igg", "immune gamma globulin", "immune globulin", "immune serum globulin", "immunoglobulin"],
    "immunoglobulin m": ["ig", "igm", "immune gamma globulin", "immune globulin", "immune serum globulin", "immunoglobulin"],
    "immunohistochemistry": ["assay"],
    "immunological": ["immunologic"],
    "immunological disorder": ["anergy", "disorder", "immunodeficiency", "immunosuppression", "upset"],
    "immunologically": [],
    "immunologist": ["medical scientist"],
    "immunology": ["chemoimmunology", "immunochemistry", "immunopathology", "medical specialty", "medicine"],
    "immunopathology": ["immunology"],
    "immunosuppressant": ["amethopterin", "immune suppressant drug", "immunosuppressive", "immunosuppressive drug", "immunosuppressor", "medicament", "medication", "medicinal drug", "medicine", "mercaptopurine", "methotrexate", "methotrexate sodium", "purinethol"],
    "immunosuppressed": [],
    "immunosuppression": ["immunological disorder"],
    "immunosuppressive": [],
    "immunotherapeutic": [],
    "immunotherapy": ["therapy"],
    "immutability": ["agelessness", "changelessness", "fixity", "immutableness", "unalterability", "unchangeability", "unchangeableness", "unchangingness"],
    "immutable": ["changeless"],
    "imp": ["brat", "child", "fry", "holy terror", "kid", "little terror", "minor", "monkey", "nestling", "nipper", "rapscallion", "rascal", "scalawag", "scallywag", "scamp", "shaver", "small fry", "terror", "tiddler", "tike", "tyke", "youngster"],
    "impact": ["force", "squeeze", "wedge"],
    "impact printer": ["bar printer", "chain printer", "printer", "printing machine", "stylus printer", "wire matrix printer", "wire printer"],
    "impacted": ["wedged"],
    "impacted fracture": ["break", "fracture"],
    "impaction": ["condition", "status"],
    "impair": ["damage"],
    "impaired": [],
    "impairer": ["agent"],
    "impairment": ["damage", "harm", "hurt", "scathe"],
    "impala": ["aepyceros melampus", "antelope"],
    "impala lily": ["adenium multiflorum", "adenium obesum", "bush", "desert rose", "kudu lily", "mock azalia", "shrub"],
    "impale": ["kill", "stake"],
    "impalement": ["cruelty", "inhuman treatment"],
    "impalpable": [],
    "impart": ["convey", "give", "leave", "pass on", "tell"],
    "impartial": [],
    "impartiality": ["candor", "candour", "disinterestedness", "disposition", "fair-mindedness", "fairness", "inclination", "nonpartisanship", "tendency"],
    "impartially": [],
    "impassable": ["unpassable"],
    "impassive": ["stolid"],
    "impassively": [],
    "impasto": ["painting"],
    "impatience": ["fidget", "fidgetiness", "restlessness"],
    "impatient": [],
    "impatiently": [],
    "impeach": ["challenge"],
    "impeachability": ["guilt", "guiltiness", "indictability"],
    "impeachment": ["instrument", "legal document", "legal instrument", "official document"],
    "impeccability": ["righteousness"],
    "impeccable": [],
    "impeccably": [],
    "impeccant": ["innocent", "sinless"],
    "impecuniousness": ["impoverishment", "pennilessness", "penuriousness", "poorness", "poverty"],
    "impede": ["block", "close up", "hinder", "hobble", "impede", "inhibit", "interfere", "jam", "keep", "obstruct", "obturate", "occlude", "prevent", "set back", "stunt"],
    "impeded": [],
    "impedimenta": ["baggage"],
    "impel": ["cause", "do", "force", "make"],
    "impellent": [],
    "impeller": ["blade", "vane"],
    "impelling": [],
    "impend": ["be"],
    "impenetrability": ["imperviousness", "quality"],
    "impenetrable": [],
    "impenitence": ["bullheadedness", "impenitency", "obstinacy", "obstinance", "pigheadedness", "self-will", "stubbornness"],
    "impenitent": [],
    "impenitently": ["unrepentantly"],
    "imperative": ["duty", "obligation", "responsibility"],
    "imperative mood": ["imperative", "imperative form", "jussive mood", "modality", "mode", "mood"],
    "imperatively": ["peremptorily"],
    "imperativeness": ["insistence", "insistency", "press", "pressure", "urgency"],
    "imperceptibility": ["physical property"],
    "imperceptible": ["unperceivable"],
    "imperceptibly": ["unnoticeably"],
    "imperfect": [],
    "imperfectibility": ["capability", "capableness", "potentiality"],
    "imperfectible": [],
    "imperfection": ["defect", "defectiveness", "failing", "fault", "faultiness", "flaw", "imperfectness", "state", "wart", "weakness"],
    "imperfective": ["durative", "durative aspect", "imperfective aspect"],
    "imperfectly": ["amiss"],
    "imperforate": [],
    "imperforate anus": ["anus"],
    "imperforate hymen": ["hymen", "maidenhead", "virginal membrane"],
    "imperial": ["beard", "face fungus", "imperial beard", "whiskers"],
    "imperial decree": ["decree", "edict", "fiat", "order", "pragmatic", "pragmatic sanction", "rescript", "ukase"],
    "imperial japanese morning glory": ["ipomoea imperialis", "morning glory"],
    "imperial mammoth": ["archidiskidon imperator", "imperial elephant", "mammoth"],
    "imperial moth": ["eacles imperialis", "saturniid", "saturniid moth"],
    "imperialism": ["foreign policy", "manifest destiny"],
    "imperialist": ["believer", "truster"],
    "imperialistic": ["imperialist"],
    "imperially": [],
    "imperiously": [],
    "imperiousness": ["arrogance", "domineeringness", "haughtiness", "hauteur", "high-handedness", "lordliness", "overbearingness"],
    "imperishability": ["imperishableness", "imperishingness", "permanence", "permanency"],
    "imperishable": [],
    "imperium": ["authorisation", "authority", "authorization", "dominance", "potency", "say-so"],
    "impermanence": ["duration", "impermanency", "length", "mortality", "temporariness", "transience", "transiency", "transitoriness"],
    "impermanent": ["temporary"],
    "impermeability": ["impermeableness", "nonabsorbency", "retention", "retentiveness", "retentivity", "solidity", "solidness"],
    "impermeable": [],
    "impermissibility": ["inadmissibility"],
    "impermissible": [],
    "impermissibly": [],
    "impersonal": [],
    "impersonally": [],
    "impersonate": ["act", "play", "portray", "represent"],
    "impersonation": ["acting", "apery", "mimicry", "performing", "personation", "playacting", "playing"],
    "impersonator": ["beguiler", "cheat", "cheater", "deceiver", "imitator", "mimic", "mimicker", "slicker", "trickster"],
    "impertinence": ["archness", "fun", "perkiness", "pertness", "playfulness", "sauciness"],
    "impertinent": ["irreverent", "pert", "saucy"],
    "impertinently": ["freshly", "impudently", "pertly", "saucily"],
    "imperturbable": ["unflappable"],
    "impervious": ["imperviable"],
    "impetiginous": [],
    "impetigo": ["disease of the skin", "skin disease", "skin disorder"],
    "impetuous": [],
    "impetuously": ["impulsively"],
    "impetuousness": ["impetuosity", "impulsiveness"],
    "impiety": ["godlessness", "impiousness", "irreligion", "irreligiousness", "undutifulness", "ungodliness", "unrighteousness"],
    "impinge": ["encroach", "entrench", "take advantage", "trench", "trespass"],
    "impingement": ["encroachment", "impact", "influence"],
    "impious": ["undutiful"],
    "impiously": [],
    "impishly": ["puckishly"],
    "impishness": ["fun", "mischievousness", "playfulness", "puckishness", "whimsicality"],
    "implacable": [],
    "implant": ["bury", "embed", "engraft", "enter", "imbed", "infix", "insert", "introduce", "nest", "plant", "pot", "sink"],
    "implantation": ["biological process", "nidation", "organic process"],
    "implausibility": ["implausibleness", "incredibility", "incredibleness"],
    "implausible": [],
    "implement": ["apply", "employ", "use", "utilise", "utilize"],
    "implemental": ["instrumental", "subservient"],
    "implementation": ["act", "agency", "deed", "effectuation", "human action", "human activity", "instrumentation", "invocation", "means", "motorisation", "motorization", "practice", "praxis", "way"],
    "implicate": ["affect", "involve", "regard"]
}
