synonyms = {
    "deferral": ["recess"],
    "defiance": ["rebelliousness"],
    "defiant": ["noncompliant"],
    "deficient": ["inferior", "substandard"],
    "deficit": ["shortage", "shortfall"],
    "deficit spending": ["compensatory spending", "pump priming"],
    "defile": ["cloud", "corrupt", "sully", "taint"],
    "defiled": ["maculate"],
    "define": ["delineate"],
    "defined": ["outlined"],
    "definitive": ["unequivocal"],
    "deflate": ["puncture"],
    "deflect": ["bend", "turn away"],
    "deflection": ["warp"],
    "deflective": ["refractive"],
    "deflower": ["ruin"],
    "defoe": ["daniel defoe"],
    "defoliate": ["defoliated"],
    "deforest": ["disafforest", "disforest"],
    "deforestation": ["disforestation"],
    "deform": ["distort", "strain"],
    "deformed": ["distorted", "malformed", "misshapen"],
    "deformity": ["malformation", "misshapenness"],
    "defrock": ["unfrock"],
    "defrost": ["deice"],
    "defroster": ["deicer"],
    "deft": ["dexterous", "dextrous"],
    "defy": ["refuse", "resist"],
    "degage": ["detached", "uninvolved"],
    "degas": ["edgar degas", "hilaire germain edgar degas"],
    "degeneracy": ["decadence", "decadency", "degeneration"],
    "degeneration": ["devolution"],
    "deglycerolize": ["deglycerolise"],
    "degradation": ["debasement"],
    "degrade": ["cheapen"],
    "degree": ["level", "point", "stage"],
    "degree centigrade": ["degree celsius"],
    "dehumanization": ["dehumanisation"],
    "dehumanize": ["dehumanise"],
    "dehumanized": ["dehumanised", "unhuman"],
    "dehydrate": ["desiccate"],
    "dehydrated food": ["dehydrated foods"],
    "dehydration": ["desiccation"],
    "deictic": ["deictic word"],
    "deification": ["apotheosis", "exaltation"],
    "deism": ["free thought"],
    "deist": ["freethinker"],
    "deity": ["divinity", "god", "immortal"],
    "dejectedly": ["in low spirits"],
    "dekagram": ["dag", "decagram", "dkg"],
    "dekaliter": ["dal", "decaliter", "decalitre", "dekalitre", "dkl"],
    "dekker": ["decker", "thomas decker", "thomas dekker"],
    "delacroix": ["eugene delacroix", "ferdinand victor eugene delacroix"],
    "delairea": ["genus delairea"],
    "delavirdine": ["rescriptor"],
    "delaware": ["delaware river"],
    "delawarean": ["delawarian"],
    "delay": ["detain", "hold up"],
    "delayed allergy": ["type iv allergic reaction"],
    "delbruck": ["max delbruck"],
    "delectability": ["deliciousness", "lusciousness", "toothsomeness"],
    "delectable": ["delicious", "luscious", "scrumptious", "toothsome", "yummy"],
    "delegate": ["depute"],
    "delegating": ["delegation", "deputation", "relegating", "relegation"],
    "delete": ["cancel"],
    "deleterious": ["hurtful", "injurious"],
    "deletion": ["cut", "excision"],
    "delhi": ["old delhi"],
    "deliberate": ["calculated", "measured"],
    "deliberate defense": ["deliberate defence"],
    "deliberation": ["advisement", "weighing"],
    "delibes": ["clement philibert leo delibes", "leo delibes"],
    "delicacy": ["discretion"],
    "delicate": ["soft"],
    "delicatessen": ["delicatessen food"],
    "delichon": ["genus delichon"],
    "deliciously": ["pleasurably"],
    "delight": ["enjoy", "revel"],
    "delightful": ["delicious"],
    "delineate": ["limn", "outline"],
    "delineated": ["delineate", "represented"],
    "delineation": ["depiction", "limning", "line drawing"],
    "delineative": ["depictive"],
    "delinquency": ["dereliction", "willful neglect"],
    "delinquent": ["juvenile delinquent"],
    "delirious": ["hallucinating"],
    "delirium tremens": ["dts"],
    "delius": ["frederick delius"],
    "deliver": ["redeem", "save"],
    "delivery": ["legal transfer", "livery"],
    "delivery truck": ["delivery van", "panel truck"],
    "deliveryman": ["deliverer", "delivery boy"],
    "dell": ["dingle"],
    "delmonico steak": ["club steak"],
    "delonix": ["genus delonix"],
    "delorme": ["philibert delorme"],
    "delphic": ["delphian"],
    "delphinapterus": ["genus delphinapterus"],
    "delphinidae": ["family delphinidae"],
    "delphinus": ["genus delphinus"],
    "delta rhythm": ["delta wave"],
    "deltoid": ["deltoid muscle", "musculus deltoideus"],
    "deltoid tuberosity": ["deltoid eminence"],
    "deluge": ["flood", "inundate", "swamp"],
    "delusion": ["psychotic belief"],
    "delusive": ["false"],
    "deluxe": ["gilded", "grand", "luxurious", "opulent", "princely", "sumptuous"],
    "demagnetization": ["demagnetisation"],
    "demagnetize": ["demagnetise"],
    "demagogic": ["demagogical"],
    "demagogue": ["demagog"],
    "demagoguery": ["demagogy"],
    "demand": ["exact"],
    "demarcate": ["delimit", "delimitate"],
    "dematerialize": ["dematerialise"],
    "dematiaceae": ["family dematiaceae"],
    "demeaning": ["humbling", "humiliating", "mortifying"],
    "demeanor": ["behavior", "behaviour", "conduct", "demeanour", "deportment"],
    "demeclocycline hydrochloride": ["declomycin"],
    "dementia": ["dementedness"],
    "demerara": ["demerara rum"],
    "demerit": ["fault"],
    "demetrius": ["demetrius i", "demetrius poliorcetes"],
    "demigod": ["superman", "ubermensch"],
    "demilitarize": ["demilitarise"],
    "demilitarized zone": ["dmz"],
    "demille": ["cecil blount demille"],
    "demineralization": ["demineralisation"],
    "demineralize": ["demineralise"],
    "demist": ["defog"],
    "demobilization": ["demobilisation"],
    "demobilize": ["demobilise", "inactivate"],
    "democracy": ["commonwealth", "republic"],
    "democrat": ["populist"],
    "democratic": ["popular"],
    "democratic front for the liberation of palestine": ["dflp", "pdflp", "popular democratic front for the liberation of palestine"],
    "democratization": ["democratisation"],
    "democratize": ["democratise"],
    "demographer": ["demographist", "population scientist"],
    "demography": ["human ecology"],
    "demolish": ["pulverise", "pulverize"],
    "demolished": ["dismantled", "razed"],
    "demonetization": ["demonetisation"],
    "demonetize": ["demonetise"],
    "demoniacally": ["frenetically"],
    "demonic": ["diabolic", "diabolical", "fiendish", "hellish", "infernal", "satanic", "unholy"],
    "demonization": ["demonisation"],
    "demonize": ["demonise"],
    "demonstrability": ["provability"],
    "demonstrable": ["provable"],
    "demonstrably": ["incontrovertibly", "provably"],
    "demonstrate": ["march"],
    "demonstration": ["demo"],
    "demonstrative": ["illustrative"],
    "demonstrative pronoun": ["demonstrative"],
    "demonstrator": ["sales demonstrator"],
    "demoralization": ["demoralisation"],
    "demoralized": ["demoralised", "discouraged", "disheartened"],
    "demoralizing": ["demoralising", "disheartening", "dispiriting"],
    "demote": ["break", "bump", "kick downstairs", "relegate"],
    "demotic": ["demotic script"],
    "dempsey": ["jack dempsey", "manassa mauler", "william harrison dempsey"],
    "demulcent": ["emollient", "salving", "softening"],
    "demur": ["except"],
    "demythologization": ["demythologisation"],
    "demythologize": ["demythologise"],
    "demythologized": ["demythologised"],
    "denationalization": ["denationalisation", "privatisation", "privatization"],
    "denationalize": ["denationalise"],
    "denaturalize": ["denaturalise"],
    "denatured": ["denaturised", "denaturized"],
    "dendranthema": ["genus dendranthema"],
    "dendroaspis": ["dendraspis", "genus dendraspis", "genus dendroaspis"],
    "dendrocalamus": ["genus dendrocalamus"],
    "dendrocolaptes": ["genus dendrocolaptes"],
    "dendrocolaptidae": ["family dendrocolaptidae"],
    "dendroctonus": ["genus dendroctonus"],
    "dendroica": ["genus dendroica"],
    "dendrolagus": ["genus dendrolagus"],
    "dendromecon": ["genus dendromecon"],
    "deng xiaoping": ["teng hsiaoping"],
    "dengue": ["breakbone fever", "dandy fever", "dengue fever"],
    "denial": ["disaffirmation"],
    "denigration": ["belittling"],
    "denim": ["dungaree", "jean"],
    "denisonia": ["genus denisonia"],
    "denmark": ["danmark", "kingdom of denmark"],
    "dennstaedtia": ["genus dennstaedtia"],
    "dennstaedtiaceae": ["family dennstaedtiaceae"],
    "denotative": ["explicit"],
    "denote": ["refer"],
    "denounce": ["betray", "give away", "grass", "rat", "shit", "shop", "snitch", "stag", "tell on"],
    "dense": ["heavy", "impenetrable"],
    "dense blazing star": ["liatris pycnostachya"],
    "densely": ["thickly"],
    "denseness": ["dumbness"],
    "densimeter": ["densitometer"],
    "density": ["denseness"],
    "dent": ["ding", "gouge", "nick"],
    "dent corn": ["zea mays indentata"],
    "dental floss": ["floss"],
    "dental plaque": ["bacterial plaque"],
    "dental school": ["school of dentistry"],
    "dental technician": ["denturist"],
    "dentaria": ["genus dentaria"],
    "dentine": ["dentin"],
    "dentist": ["dental practitioner", "tooth doctor"],
    "dentistry": ["dental medicine", "odontology"],
    "dentition": ["teeth"],
    "denture": ["dental plate", "plate"],
    "denudation": ["baring", "husking", "stripping", "uncovering"],
    "denude": ["bare", "denudate", "strip"],
    "denunciation": ["denouncement"],
    "denver": ["capital of colorado"],
    "deny": ["abnegate"],
    "deodar": ["cedrus deodara", "deodar cedar", "himalayan cedar"],
    "deodorant": ["deodourant"],
    "deodorize": ["deodorise", "deodourise"],
    "deoxidize": ["deoxidise", "reduce"],
    "deoxycytidine": ["cytidine"],
    "deoxyguanosine": ["guanosine"],
    "deoxyribonucleic acid": ["desoxyribonucleic acid", "dna"],
    "deoxythymidine": ["thymidine"],
    "depardieu": ["gerard depardieu"],
    "deparia": ["genus deparia"],
    "depart": ["part", "set forth", "set off", "set out", "start", "start out", "take off"],
    "departer": ["goer", "leaver"],
    "department": ["section"],
    "department of agriculture": ["agriculture", "agriculture department", "usda"],
    "department of commerce": ["commerce", "commerce department", "doc"],
    "department of defense": ["defense", "defense department", "dod", "united states department of defense"],
    "department of defense laboratory system": ["lablink"],
    "department of education": ["education", "education department"],
    "department of energy": ["doe", "energy", "energy department"],
    "department of energy intelligence": ["doei"],
    "department of health and human services": ["health and human services", "hhs"],
    "department of homeland security": ["homeland security"],
    "department of housing and urban development": ["housing and urban development", "hud"],
    "department of justice": ["doj", "justice", "justice department"],
    "department of justice canada": ["dojc"],
    "department of labor": ["dol", "labor", "labor department"],
    "department of state": ["dos", "state", "state department", "united states department of state"],
    "department of the interior": ["doi", "interior", "interior department"],
    "department of the treasury": ["treasury", "treasury department", "united states treasury"],
    "department of transportation": ["dot", "transportation"],
    "department of veterans affairs": ["va"],
    "department store": ["emporium"],
    "departure": ["going", "going away", "leaving"],
    "departure time": ["time of departure"],
    "depend on": ["depend upon", "devolve on", "hinge on", "hinge upon", "ride", "turn on"],
    "dependability": ["dependableness", "reliability", "reliableness"],
    "dependable": ["honest", "reliable", "true"],
    "dependant": ["dependent"],
    "dependence": ["dependance", "dependency"],
    "dependent": ["subordinate"],
    "depersonalization": ["depersonalisation", "depersonalisation disorder", "depersonalisation neurosis", "depersonalization disorder", "depersonalization neurosis"],
    "depersonalize": ["depersonalise", "objectify"],
    "depicted": ["pictured", "portrayed"],
    "depicting": ["depiction", "portrayal", "portraying"],
    "depiction": ["delineation", "portrayal"],
    "depilation": ["epilation"],
    "depilatory": ["depilator", "epilator"],
    "depleted": ["low"],
    "deplorable": ["execrable", "miserable", "woeful", "wretched"],
    "deplorably": ["lamentably", "sadly", "woefully"],
    "deplore": ["bemoan", "bewail", "lament"],
    "deplume": ["displume"],
    "depolarization": ["depolarisation"],
    "depolarize": ["depolarise"],
    "depopulate": ["desolate"],
    "depose": ["force out"],
    "deposit": ["bank"],
    "deposition": ["deposit"],
    "depository": ["deposit", "depositary", "repository"],
    "depository financial institution": ["bank", "banking company", "banking concern"],
    "depraved": ["perverse", "perverted", "reprobate"],
    "depravity": ["turpitude"],
    "deprecate": ["depreciate", "vilipend"],
    "deprecation": ["denigration"],
    "depreciate": ["devaluate", "devalue", "undervalue"],
    "depreciating": ["depreciative", "depreciatory"],
    "depreciation": ["wear and tear"],
    "depredation": ["predation"],
    "depress": ["cast down", "deject", "demoralise", "demoralize", "dismay", "dispirit", "get down"],
    "depressed": ["down"],
    "depressing": ["cheerless", "uncheerful"],
    "depression": ["great depression"],
    "depressive disorder": ["clinical depression", "depression"],
    "depressor": ["depressor muscle"],
    "depressurize": ["decompress", "depressurise"],
    "deprive": ["divest", "strip"],
    "deprived": ["disadvantaged"],
    "depth": ["deepness"],
    "depth charge": ["depth bomb"],
    "depth gauge": ["depth gage"],
    "deputation": ["commission", "delegacy", "delegation", "mission"],
    "depute": ["deputise", "deputize"],
    "deputy": ["surrogate"],
    "derail": ["jump"],
    "derain": ["andre derain"],
    "derangement": ["mental unsoundness", "unbalance"],
    "deregulation": ["deregulating"],
    "derelict": ["delinquent", "neglectful", "remiss"],
    "derision": ["ridicule"],
    "derisive": ["gibelike", "jeering", "mocking", "taunting"],
    "derisively": ["derisorily", "mockingly", "scoffingly"],
    "derivative instrument": ["derivative"],
    "derive": ["come", "descend"],
    "derived function": ["derivative", "differential", "differential coefficient", "first derivative"],
    "deriving": ["derivation", "etymologizing"],
    "dermacentor": ["genus dermacentor"],
    "dermal": ["dermic"],
    "dermaptera": ["order dermaptera"],
    "dermatobia": ["genus dermatobia"],
    "dermatologic": ["dermatological"],
    "dermatologist": ["skin doctor"],
    "dermatomycosis": ["dermatophytosis"],
    "dermestidae": ["family dermestidae"],
    "dermis": ["corium", "derma"],
    "dermochelyidae": ["family dermochelyidae"],
    "dermochelys": ["genus dermochelys"],
    "dermoptera": ["order dermoptera"],
    "derogative": ["derogatory", "disparaging"],
    "derrida": ["jacques derrida"],
    "derris root": ["derris elliptica", "tuba root"],
    "des moines": ["capital of iowa"],
    "desacralize": ["secularize"],
    "desalinate": ["desalinise", "desalinize", "desalt"],
    "desalination": ["desalinisation", "desalinization"],
    "descant": ["discant"],
    "descartes": ["rene descartes"],
    "descend": ["come down", "fall", "go down"],
    "descendant": ["descendent"],
    "descendants": ["posterity"],
    "descent": ["filiation", "line of descent", "lineage"],
    "describe": ["depict", "draw"],
    "description": ["verbal description"],
    "descriptive adjective": ["qualifying adjective"],
    "descry": ["espy", "spot", "spy"],
    "descurainia": ["genus descurainia"],
    "desecrate": ["outrage", "profane", "violate"],
    "desegrated": ["nonsegregated", "unsegregated"],
    "desegregate": ["integrate", "mix"],
    "desensitization": ["desensitisation"],
    "desensitization technique": ["desensitisation procedure", "desensitisation technique", "desensitization procedure", "systematic desensitisation", "systematic desensitization"],
    "desensitize": ["desensitise"],
    "desensitizing": ["desensitising"],
    "desert holly": ["atriplex hymenelytra"],
    "desert iguana": ["dipsosaurus dorsalis"],
    "desert mariposa tulip": ["calochortus kennedyi"],
    "desert paintbrush": ["castilleja chromosa"],
    "desert pea": ["clianthus formosus", "clianthus speciosus", "sturt pea"],
    "desert plant": ["xerophile", "xerophilous plant", "xerophyte", "xerophytic plant"],
    "desert plume": ["cleome pinnata", "stanleya pinnata"],
    "desert sand verbena": ["abronia villosa"],
    "desert selaginella": ["selaginella eremophila"],
    "desert soil": ["desertic soil"],
    "desert sunflower": ["gerea canescens"],
    "desert tortoise": ["gopherus agassizii"],
    "desert willow": ["chilopsis linearis"],
    "deserter": ["apostate", "ratter", "recreant", "renegade", "turncoat"],
    "desertion": ["abandonment", "defection"],
    "deserts": ["comeupance", "comeuppance"],
    "deserve": ["merit"],
    "deserving": ["worth"],
    "deservingness": ["merit", "meritoriousness"],
    "desexualize": ["desexualise"],
    "desiccant": ["drier", "drying agent", "siccative"],
    "design": ["plan"],
    "designate": ["denominate"],
    "designation": ["identification"],
    "designed": ["intentional"],
    "designer": ["intriguer"],
    "designing": ["scheming"],
    "desirability": ["desirableness"],
    "desirable": ["suitable", "worthy"],
    "desire": ["want"],
    "desire to know": ["lust for learning", "thirst for knowledge"],
    "desirous": ["wishful"],
    "desk clerk": ["hotel clerk", "hotel desk clerk"],
    "desk dictionary": ["collegiate dictionary"],
    "desk sergeant": ["deskman", "station keeper"],
    "desmanthus": ["genus desmanthus"],
    "desmidiaceae": ["family desmidiaceae"],
    "desmidium": ["genus desmidium"],
    "desmodium": ["genus desmodium"],
    "desmodontidae": ["family desmodontidae"],
    "desmodus": ["genus desmodus"],
    "desmograthus": ["genus desmograthus"],
    "desolately": ["disconsolately"],
    "despair": ["desperation"],
    "despairing": ["desperate"],
    "despairingly": ["despondently"],
    "desperado": ["desperate criminal"],
    "desperate": ["dire"],
    "desperate straits": ["dire straits"],
    "despicable": ["slimy", "ugly", "unworthy", "vile", "worthless", "wretched"],
    "despisal": ["despising"],
    "despised": ["detested", "hated", "scorned"],
    "despiteful": ["spiteful", "vindictive"],
    "despitefully": ["spitefully"],
    "despoiled": ["pillaged", "raped", "ravaged", "sacked"],
    "despondency": ["despondence", "disconsolateness", "heartsickness"],
    "despondent": ["heartsick"],
    "despotic": ["despotical"],
    "desquamate": ["peel off"],
    "desquamation": ["peeling", "shedding"],
    "dessert": ["afters", "sweet"],
    "dessertspoon": ["dessertspoonful"],
    "destabilization": ["destabilisation"],
    "destabilize": ["destabilise"],
    "destalinization": ["destalinisation"],
    "destalinize": ["destalinise"],
    "destination": ["terminus"],
    "destine": ["designate", "doom", "fate"],
    "destiny": ["fate"],
    "destitute": ["impoverished", "indigent", "necessitous", "needy"],
    "destroy": ["destruct"],
    "destroyed": ["ruined"],
    "destroyer": ["ruiner", "undoer", "uprooter", "waster"],
    "destroying angel": ["amanita verna"],
    "destruction": ["demolition", "wipeout"],
    "desulfurize": ["desulphurize"],
    "desynchronize": ["desynchronise"],
    "detach": ["come away", "come off"],
    "detached": ["isolated", "separated"],
    "detached house": ["single dwelling"],
    "detachment": ["disengagement"],
    "detail": ["item", "particular"],
    "detailed": ["elaborate", "elaborated"],
    "details": ["inside information"],
    "detainee": ["political detainee"],
    "detect": ["discover", "find", "notice", "observe"],
    "detectable": ["noticeable"],
    "detection": ["sensing"],
    "detective": ["investigator", "police detective", "tec"],
    "detective novel": ["mystery novel"],
    "detector": ["demodulator"],
    "detention": ["custody", "detainment", "hold"],
    "detention home": ["detention camp", "detention house", "house of detention"],
    "deter": ["discourage"],
    "detergency": ["detergence"],
    "detergent": ["detersive"],
    "deterioration": ["impairment"],
    "determent": ["deterrence", "intimidation"],
    "determinant": ["causal factor", "determinative", "determiner", "determining factor"],
    "determinateness": ["definiteness"],
    "determination": ["purpose"],
    "determine": ["ascertain", "check", "find out", "learn", "see", "watch"],
    "determined": ["dictated", "set"],
    "determinedly": ["unfalteringly", "unshakably"],
    "determiner": ["determinative"],
    "detestably": ["abominably", "odiously", "repulsively"],
    "detonate": ["blow up", "explode"],
    "detonator": ["cap", "detonating device"],
    "detour": ["roundabout way"],
    "detox": ["detoxify"],
    "detoxify": ["detoxicate"],
    "detraction": ["petty criticism"],
    "detractor": ["depreciator", "disparager", "knocker"],
    "detransitivize": ["detransitivise", "intransitivise", "intransitivize"],
    "detribalization": ["detribalisation"],
    "detribalize": ["detribalise"],
    "detriment": ["hurt"],
    "detrimentally": ["harmfully", "noxiously"],
    "detroit": ["motor city", "motown"],
    "deuce": ["two"],
    "deuteranopia": ["daltonism"],
    "deuterium": ["heavy hydrogen"],
    "deuteromycetes": ["class deuteromycetes"],
    "deuteromycota": ["deuteromycotina", "fungi imperfecti", "subdivision deuteromycota", "subdivision deuteromycotina"],
    "deuteronomy": ["book of deuteronomy"],
    "devalue": ["devaluate"],
    "devanagari": ["devanagari script", "nagari", "nagari script"],
    "devastation": ["desolation"],
    "develop": ["acquire", "evolve"],
    "developing": ["underdeveloped"],
    "development": ["evolution"],
    "developmental psychology": ["child psychology", "genetic psychology"],
    "deviate": ["depart", "diverge", "vary"],
    "deviation": ["departure", "difference", "divergence"],
    "device": ["gimmick", "twist"],
    "devil": ["daemon", "daimon", "demon", "fiend"],
    "devil ray": ["mobula hypostoma"],
    "deviled egg": ["stuffed egg"],
    "devilish": ["rascally", "roguish"],
    "devilishly": ["devilish"],
    "devilize": ["devilise", "diabolise", "diabolize"],
    "deviltry": ["devilry"],
    "devilwood": ["american olive", "osmanthus americanus"],
    "devious": ["shifty"],
    "deviousness": ["obliqueness"],
    "devisal": ["contrivance"],
    "devising": ["fashioning", "making"],
    "devitalization": ["devitalisation"],
    "devitalize": ["devitalise"],
    "devolution": ["devolvement"],
    "devolve": ["degenerate", "deteriorate", "drop"],
    "devon": ["devonshire"],
    "devonian": ["age of fishes", "devonian period"]
}
