synonyms = {
    "copacetic": ["copasetic", "copesetic", "copesettic"],
    "copaiba": ["balsam capivi", "copaiba balsam"],
    "copalite": ["copaline", "fossil copal"],
    "cope": ["contend", "deal", "get by", "grapple", "make do", "make out", "manage"],
    "copenhagen": ["danish capital", "kobenhavn"],
    "copepod": ["copepod crustacean"],
    "copepoda": ["subclass copepoda"],
    "copernicia": ["genus copernicia"],
    "copernicus": ["mikolaj kopernik", "nicolaus copernicus"],
    "copilot": ["co-pilot"],
    "copious": ["voluminous"],
    "copland": ["aaron copland"],
    "copley": ["john copley", "john singleton copley"],
    "copolymerize": ["copolymerise"],
    "copper": ["atomic number 29", "cu"],
    "copper beech": ["fagus purpurea", "fagus sylvatica atropunicea", "fagus sylvatica purpurea", "purple beech"],
    "copper rockfish": ["sebastodes caurinus"],
    "copper sulfate": ["copper sulphate", "cupric sulfate", "cupric sulphate"],
    "copperhead": ["agkistrodon contortrix"],
    "copperplate": ["copperplate engraving"],
    "coppery": ["copper colored"],
    "coppola": ["francis ford coppola"],
    "coprinaceae": ["family coprinaceae"],
    "coprinus": ["genus coprinus"],
    "coprolith": ["faecalith", "fecalith", "stercolith"],
    "coprophagy": ["coprophagia"],
    "coptis": ["genus coptis"],
    "copula": ["copulative", "linking verb"],
    "copulate": ["couple", "mate", "pair"],
    "copy": ["re-create"],
    "copy editor": ["copyreader", "text editor"],
    "copycat": ["ape", "aper", "emulator", "imitator"],
    "copyist": ["scribe", "scrivener"],
    "copyread": ["copyedit", "subedit"],
    "copyright": ["right of first publication"],
    "copyright infringement": ["infringement of copyright"],
    "coquette": ["flirt", "minx", "prickteaser", "tease", "vamp", "vamper"],
    "coquettish": ["flirtatious"],
    "coquettishly": ["flirtatiously"],
    "coracias": ["genus coracias"],
    "coraciidae": ["family coraciidae"],
    "coraciiformes": ["order coraciiformes"],
    "coragyps": ["genus coragyps"],
    "coral": ["precious coral", "red coral"],
    "coral bean tree": ["erythrina corallodendrum"],
    "coral bush": ["flame bush", "templetonia retusa"],
    "coral drops": ["bessera elegans"],
    "coral gem": ["lotus berthelotii"],
    "coral necklace": ["illecebrum verticullatum"],
    "coral sea": ["battle of the coral sea"],
    "coral snake": ["old world coral snake"],
    "coral tree": ["erythrina"],
    "coral vine": ["kennedia coccinea"],
    "coral-root bittercress": ["cardamine bulbifera", "coralroot", "coralwort", "dentaria bulbifera"],
    "coralbells": ["heuchera sanguinea"],
    "coralberry": ["indian currant", "symphoricarpos orbiculatus"],
    "corallorhiza": ["genus corallorhiza"],
    "coralwood": ["adenanthera pavonina", "barbados pride", "coral-wood", "peacock flower fence", "red sandalwood"],
    "corbel": ["truss"],
    "corbel step": ["corbie-step", "corbiestep", "crow step"],
    "corbett": ["gentleman jim", "james john corbett", "jim corbett"],
    "corbina": ["menticirrhus undulatus"],
    "corchorus": ["genus corchorus"],
    "cord": ["electric cord"],
    "cordaitaceae": ["family cordaitaceae"],
    "cordaitales": ["order cordaitales"],
    "cordaites": ["genus cordaites"],
    "cordate": ["cordiform", "heart-shaped"],
    "corday": ["charlotte corday", "marie anne charlotte corday d'armont"],
    "corded": ["twilled"],
    "cordgrass": ["cord grass"],
    "cordia": ["genus cordia"],
    "cordial reception": ["hospitality"],
    "cordoba": ["cordova", "francisco fernandez cordoba", "francisco fernandez de cordova"],
    "cords": ["corduroys"],
    "cordylidae": ["family cordylidae"],
    "cordyline": ["genus cordyline"],
    "cordylus": ["genus cordylus"],
    "core": ["core group", "nucleus"],
    "coreferential": ["co-referent"],
    "coregonidae": ["family coregonidae"],
    "coregonus": ["genus coregonus"],
    "coreid bug": ["coreid"],
    "coreidae": ["family coreidae"],
    "corelli": ["arcangelo corelli"],
    "coreopsis": ["tick-weed", "tickseed", "tickweed"],
    "corespondent": ["co-respondent"],
    "corgi": ["welsh corgi"],
    "coriaceous": ["leathered", "leatherlike", "leathery"],
    "coriander": ["chinese parsley", "cilantro", "coriander plant", "coriandrum sativum"],
    "coriandrum": ["genus coriandrum"],
    "corinth": ["korinthos"],
    "corixa": ["genus corixa"],
    "corixidae": ["family corixidae"],
    "cork": ["cork up"],
    "cork oak": ["quercus suber"],
    "cork tree": ["phellodendron amurense"],
    "corked": ["corky"],
    "corkscrew": ["spiral"],
    "corkwood": ["corkwood tree", "leitneria floridana"],
    "cormorant": ["phalacrocorax carbo"],
    "cormous": ["cormose"],
    "corn": ["clavus"],
    "corn borer": ["pyrausta nubilalis"],
    "corn chamomile": ["anthemis arvensis", "corn mayweed", "field chamomile"],
    "corn cockle": ["agrostemma githago", "corn campion", "crown-of-the-field"],
    "corn dab": ["corn dodger", "dodger"],
    "corn earworm": ["cotton bollworm", "heliothis zia", "tobacco budworm", "tomato fruitworm", "vetchworm"],
    "corn marigold": ["chrysanthemum segetum", "field marigold"],
    "corn mint": ["field mint", "mentha arvensis"],
    "corn poppy": ["field poppy", "flanders poppy", "papaver rhoeas"],
    "corn snake": ["elaphe guttata", "red rat snake"],
    "corn speedwell": ["veronica arvensis"],
    "corn spurry": ["corn spurrey", "spergula arvensis"],
    "corn whiskey": ["corn", "corn whisky"],
    "cornaceae": ["dogwood family", "family cornaceae"],
    "corncob": ["corn cob"],
    "corncrake": ["crex crex", "land rail"],
    "corned": ["cured"],
    "corneille": ["pierre corneille"],
    "cornelian cherry": ["cornus mas"],
    "cornell": ["katherine cornell"],
    "corneous": ["hornlike", "horny"],
    "corner": ["tree"],
    "cornet": ["horn", "trump", "trumpet"],
    "cornfield": ["corn field"],
    "cornflower": ["bachelor's button", "bluebottle", "centaurea cyanus"],
    "cornice": ["pelmet", "valance", "valance board"],
    "cornish": ["cornish fowl"],
    "cornish heath": ["erica vagans"],
    "cornmeal": ["indian meal"],
    "cornpone": ["pone"],
    "cornsilk": ["corn silk"],
    "cornsmut": ["corn smut"],
    "cornstalk": ["corn stalk"],
    "cornstarch": ["cornflour"],
    "cornus": ["genus cornus"],
    "cornwallis": ["charles cornwallis", "first marquess cornwallis"],
    "corokia": ["genus corokia"],
    "corona discharge": ["corona", "corposant", "electric glow", "saint elmo's fire", "saint elmo's light", "saint ulmo's fire", "saint ulmo's light", "st. elmo's fire"],
    "coronal suture": ["sutura coronalis"],
    "coronary artery": ["arteria coronaria"],
    "coronary bypass": ["cabg", "coronary artery bypass graft", "coronary bypass surgery"],
    "coronary insufficiency": ["cardiac insufficiency"],
    "coronary sinus": ["sinus coronarius"],
    "coronary thrombosis": ["coronary"],
    "coronation": ["enthronement", "enthronisation", "enthronization", "investiture"],
    "coroner": ["medical examiner"],
    "coroneted": ["highborn", "titled"],
    "coronoid process": ["processus coronoideus"],
    "corot": ["jean baptiste camille corot"],
    "corozo": ["corozo palm"],
    "corporate": ["collective"],
    "corporate executive": ["business executive"],
    "corporation": ["corp"],
    "corporeal": ["material"],
    "corps": ["army corps"],
    "corps de ballet": ["ensemble"],
    "corpulence": ["adiposis", "overweight", "stoutness"],
    "corpulent": ["obese", "rotund", "weighty"],
    "corpus striatum": ["striate body", "striatum"],
    "corpuscular radiation": ["particulate radiation"],
    "corpuscular theory": ["corpuscular theory of light"],
    "correct": ["rectify", "right"],
    "correction": ["fudge factor"],
    "corrections": ["department of corrections"],
    "corrective": ["restorative"],
    "correctly": ["aright", "right"],
    "correctness": ["rightness"],
    "correggio": ["antonio allegri da correggio"],
    "correlate": ["correlative"],
    "correlation": ["correlativity"],
    "correlation coefficient": ["coefficient of correlation", "correlation"],
    "correlative": ["correlate", "correlated"],
    "correspondent": ["newspaperman", "newspaperwoman", "newswriter", "pressman"],
    "corroborate": ["bear out", "support", "underpin"],
    "corrode": ["eat", "rust"],
    "corrosion": ["corroding", "erosion"],
    "corrugated board": ["corrugated cardboard"],
    "corrugated fastener": ["wiggle nail"],
    "corrupt": ["debase", "debauch", "demoralise", "demoralize", "deprave", "misdirect", "pervert", "profane", "subvert", "vitiate"],
    "corrupted": ["debased", "vitiated"],
    "corruptible": ["bribable", "dishonest", "purchasable", "venal"],
    "corrupting": ["degrading"],
    "corruption": ["degeneracy", "depravation", "depravity", "putrefaction"],
    "corruptive": ["perversive", "pestiferous"],
    "corruptly": ["corruptedly"],
    "corruptness": ["corruption"],
    "corsair": ["barbary pirate"],
    "corse": ["corsica"],
    "corselet": ["corslet"],
    "corset": ["girdle", "stays"],
    "cortaderia": ["genus cortaderia"],
    "cortege": ["entourage", "retinue", "suite"],
    "cortes": ["cortez", "hernan cortes", "hernan cortez", "hernando cortes", "hernando cortez"],
    "cortical area": ["cortical region"],
    "cortical epilepsy": ["focal epilepsy"],
    "corticium": ["genus corticium"],
    "corticoafferent": ["corticipetal"],
    "corticoefferent": ["corticifugal", "corticofugal"],
    "corticosteroid": ["adrenal cortical steroid", "corticoid"],
    "cortinariaceae": ["family cortinariaceae"],
    "cortinarius": ["genus cortinarius"],
    "cortinarius mutabilis": ["purple-staining cortinarius"],
    "cortisone": ["cortone acetate"],
    "corundom": ["corundum"],
    "corvidae": ["family corvidae"],
    "corvus": ["crow"],
    "coryanthes": ["genus coryanthes"],
    "corydalidae": ["family corydalidae"],
    "corydalis": ["genus corydalis"],
    "corydalus": ["corydalis", "genus corydalis", "genus corydalus"],
    "corylaceae": ["family corylaceae", "subfamily corylaceae"],
    "corylopsis": ["genus corylopsis"],
    "corylus": ["genus corylus"],
    "corynebacteriaceae": ["family corynebacteriaceae"],
    "corynebacterium diphtheriae": ["c. diphtheriae", "klebs-loeffler bacillus"],
    "corypha": ["genus corypha"],
    "coryphaenidae": ["family coryphaenidae"],
    "corythosaur": ["corythosaurus"],
    "cos": ["cos lettuce", "romaine", "romaine lettuce"],
    "cos lettuce": ["lactuca sativa longifolia", "romaine lettuce"],
    "cosecant": ["cosec"],
    "coseismic": ["coseismal"],
    "cosign": ["co-sign"],
    "cosigner": ["cosignatory"],
    "cosimo de medici": ["cosimo the elder"],
    "cosine": ["cos"],
    "cosmetic": ["decorative", "ornamental"],
    "cosmetic surgeon": ["plastic surgeon"],
    "cosmic background radiation": ["cbr", "cmb", "cmbr", "cosmic microwave background", "cosmic microwave background radiation"],
    "cosmocampus": ["genus cosmocampus"],
    "cosmographer": ["cosmographist"],
    "cosmologic": ["cosmogenic", "cosmogonic", "cosmogonical", "cosmological"],
    "cosmology": ["cosmogeny", "cosmogony"],
    "cosmopolitan": ["cosmopolite"],
    "cosmos": ["cosmea"],
    "cost": ["be"],
    "cost of capital": ["capital cost"],
    "cost-efficient": ["cost-effective"],
    "costa rica": ["republic of costa rica"],
    "costate": ["ribbed"],
    "costermonger": ["barrow-boy", "barrow-man"],
    "costia": ["costia necatrix"],
    "costliness": ["dearness", "preciousness"],
    "costly": ["dear", "high-priced", "pricey", "pricy"],
    "costmary": ["alecost", "balsam herb", "bible leaf", "chrysanthemum balsamita", "mint geranium", "tanacetum balsamita"],
    "costume": ["dress up"],
    "costumier": ["costume designer", "costumer"],
    "costusroot": ["saussurea costus", "saussurea lappa"],
    "cosy": ["cozy", "tea cosy", "tea cozy"],
    "cot": ["camp bed"],
    "cotangent": ["cotan"],
    "cotillion": ["cotilion"],
    "cotinga": ["chatterer"],
    "cotingidae": ["family cotingidae"],
    "cotinus": ["genus cotinus"],
    "cotswolds": ["cotswold hills"],
    "cottage cheese": ["farm cheese", "farmer's cheese", "pot cheese"],
    "cottage pink": ["dianthus plumarius", "grass pink"],
    "cottager": ["cottage dweller"],
    "cotter": ["cottar"],
    "cottidae": ["family cottidae"],
    "cotton": ["cotton fiber", "cotton wool"],
    "cotton candy": ["candyfloss", "spun sugar"],
    "cotton flannel": ["canton flannel"],
    "cotton gin": ["gin"],
    "cotton grass": ["cotton rush"],
    "cotton mouse": ["peromyscus gossypinus"],
    "cotton rat": ["sigmodon hispidus"],
    "cotton rose": ["confederate rose", "confederate rose mallow", "hibiscus mutabilis"],
    "cotton thistle": ["onopordon acanthium", "onopordum acanthium", "scotch thistle", "woolly thistle"],
    "cottonseed cake": ["cotton cake"],
    "cottonwick": ["haemulon malanurum"],
    "cottus": ["genus cottus"],
    "cotula": ["genus cotula"],
    "coturnix": ["genus coturnix"],
    "cotyledon": ["seed leaf"],
    "coude telescope": ["coude system"],
    "coue": ["emile coue"],
    "cougar": ["catamount", "felis concolor", "mountain lion", "painter", "panther", "puma"],
    "cough": ["coughing"],
    "cough drop": ["pastil", "pastille", "troche"],
    "cough up": ["pony up", "spit up"],
    "coulisse": ["wing flat"],
    "coulomb": ["ampere-second"],
    "coumarone-indene resin": ["coumarone resin"],
    "coumarouna": ["dipteryx", "genus coumarouna", "genus dipteryx"],
    "council member": ["councillor"],
    "councillorship": ["councilorship"],
    "counselor": ["counsellor"],
    "counselorship": ["counsellorship"],
    "count": ["number"],
    "count per minute": ["counts/minute"],
    "countable": ["denumerable", "enumerable", "numerable"],
    "countenance": ["kisser", "mug", "phiz", "physiognomy", "smiler", "visage"],
    "counter": ["heel counter"],
    "counteract": ["counterbalance", "countervail", "neutralize"],
    "counterattack": ["counterstrike"],
    "counterbalance": ["offset"],
    "counterbalanced": ["counterpoised"],
    "counterbore": ["countersink", "countersink bit"],
    "counterchange": ["interchange", "transpose"],
    "countercheck": ["counteract"],
    "counterclockwise": ["anticlockwise"],
    "countercurrent": ["crosscurrent"],
    "counterfactual": ["contrary to fact"],
    "counterfeit": ["forgery"],
    "counterglow": ["gegenschein"],
    "counterpart": ["opposite number", "vis-a-vis"],
    "counterperson": ["counterman", "counterwoman"],
    "counterplot": ["counterplan"],
    "counterpunch": ["counter", "parry"],
    "counterrevolutionist": ["counter-revolutionist", "counterrevolutionary"],
    "countersignature": ["countersign"],
    "counterspy": ["mole"],
    "countertenor": ["alto"],
    "counterterror": ["counterterrorist"],
    "counterterrorist center": ["ctc"],
    "counterweight": ["counterpoise", "counterpose"],
    "countless": ["infinite", "innumerable", "innumerous", "multitudinous", "myriad", "numberless", "uncounted", "unnumberable", "unnumbered", "unnumerable"],
    "countrified": ["countryfied", "rustic"],
    "country": ["rural area"],
    "country borage": ["coleus amboinicus", "coleus aromaticus", "plectranthus amboinicus"],
    "country music": ["c and w", "country and western"],
    "country people": ["countryfolk"],
    "country store": ["general store", "trading post"],
    "country-dance": ["contra danse", "contradance", "contredanse", "country dancing"],
    "countryman": ["ruralist"],
    "countrywide": ["nationwide"],
    "county agent": ["agricultural agent", "extension agent"],
    "county seat": ["county courthouse"],
    "county town": ["shire town"],
    "coup d'etat": ["coup", "putsch", "takeover"],
    "couperin": ["francois couperin"],
    "couple": ["couple on", "couple up"],
    "coupled": ["joined", "linked"],
    "coupling": ["coupler"],
    "coupon": ["voucher"],
    "coupon bond": ["bearer bond"],
    "courage": ["braveness", "bravery", "courageousness"],
    "courbaril": ["hymenaea courbaril"],
    "courbet": ["gustave courbet"],
    "courlan": ["aramus guarauna"],
    "course": ["trend"],
    "course catalog": ["course catalogue", "prospectus"],
    "course of study": ["curriculum", "program", "programme", "syllabus"],
    "course session": ["class period", "recitation"],
    "court": ["margaret court"],
    "courteous": ["gracious", "nice"],
    "courtesy": ["good manners"],
    "courtly": ["formal", "stately"],
    "courtship": ["courting", "suit", "wooing"],
    "cousin": ["cousin-german", "first cousin", "full cousin"],
    "cousteau": ["jacques costeau", "jacques yves costeau"],
    "couthie": ["couthy"],
    "couturier": ["clothes designer", "designer", "fashion designer"],
    "covalence": ["covalency"],
    "covenant": ["compact", "concordat"],
    "cover": ["continue", "extend"],
    "cover charge": ["cover"],
    "cover girl": ["lovely", "pin-up"],
    "cover glass": ["cover slip"],
    "coverage": ["insurance coverage"],
    "covered wagon": ["conestoga", "conestoga wagon", "prairie schooner", "prairie wagon"],
    "covering": ["cover", "natural covering"],
    "covering letter": ["cover letter"],
    "coveted": ["desired", "in demand", "sought after"],
    "covetous": ["envious", "jealous"],
    "cow": ["moo-cow"],
    "cow parsley": ["anthriscus sylvestris", "wild chervil"],
    "cow parsnip": ["heracleum sphondylium", "hogweed"],
    "cow pen": ["cattle pen", "corral"],
    "cow pie": ["cowpie"],
    "cow shark": ["hexanchus griseus", "six-gilled shark"],
    "cow town": ["cowtown"],
    "cowage": ["bengal bean", "benghal bean", "florida bean", "mucuna aterrima", "mucuna deeringiana", "mucuna pruriens utilis", "stizolobium deeringiana", "velvet bean"],
    "coward": ["noel coward", "sir noel pierce coward"],
    "cowardice": ["cowardliness"],
    "cowardly": ["fearful"],
    "cowbarn": ["byre", "cow barn", "cowhouse", "cowshed"],
    "cowberry": ["foxberry", "lingberry", "lingenberry", "lingonberry", "mountain cranberry", "vaccinium vitis-idaea"],
    "cowboy": ["rodeo rider"],
    "cowboy hat": ["ten-gallon hat"],
    "cowfish": ["lactophrys quadricornis"],
    "cowherb": ["cow cockle", "saponaria vaccaria", "vaccaria hispanica", "vaccaria pyramidata"],
    "cowhide": ["cowskin"],
    "cownose ray": ["cow-nosed ray", "rhinoptera bonasus"],
    "cowpea": ["black-eyed pea"],
    "cowpen daisy": ["butter daisy", "golden crown beard", "golden crownbeard", "verbesina encelioides", "ximenesia encelioides"],
    "cowpens": ["battle of cowpens"],
    "cowper": ["william cowper"],
    "cowper's gland": ["bulbourethral gland"],
    "cowpox": ["vaccinia"],
    "cowrie": ["cowry"],
    "cowslip": ["paigle", "primula veris"],
    "coxcomb": ["cockscomb"],
    "coxsackievirus": ["coxsackie virus"],
    "coxswain": ["cox"],
    "coy": ["demure", "overmodest"],
    "coyness": ["demureness"],
    "coyol": ["acrocomia vinifera", "coyol palm"],
    "coyote": ["brush wolf", "canis latrans", "prairie wolf"],
    "coyote brush": ["baccharis pilularis", "chaparral broom", "coyote bush", "kidney wort"],
    "coypu": ["myocastor coypus", "nutria"],
    "cozily": ["cosily"],
    "coziness": ["cosiness", "snugness"],
    "cozy": ["informal", "intimate"],
    "cozy up": ["cotton up", "play up", "shine up", "sidle up", "suck up"],
    "cpu board": ["mother board"],
    "crab": ["crabby person"],
    "crab apple": ["crabapple", "cultivated crab apple"],
    "crab cactus": ["schlumbergera truncatus", "thanksgiving cactus", "zygocactus truncatus"],
    "crab louse": ["crab", "phthirius pubis", "pubic louse"],
    "crab-eating dog": ["crab-eating fox", "dusicyon cancrivorus"],
    "crab-eating macaque": ["croo monkey", "macaca irus"],
    "crab-eating raccoon": ["procyon cancrivorus"],
    "crabbed": ["bad-tempered", "crabby", "cross", "fussy", "grouchy", "grumpy", "ill-tempered"],
    "crabbiness": ["crabbedness", "crossness"],
    "crabeater seal": ["crab-eating seal"],
    "crabgrass": ["crab grass", "finger grass"],
    "crabwise": ["sideways"],
    "cracidae": ["family cracidae"],
    "crack": ["break", "check"],
    "crack addict": ["binger"],
    "crack up": ["break up", "collapse", "crack", "crock up"],
    "crack willow": ["brittle willow", "salix fragilis", "snap willow"],
    "crackbrained": ["idiotic"],
    "cracker": ["cracker bonbon", "snapper"],
    "cracker-barrel": ["folksy", "homespun"],
    "crackle": ["crackling", "crepitation"],
    "crackpot": ["crank", "fruitcake", "nut", "nut case", "screwball"],
    "cracow": ["krakau", "krakow"],
    "cracticidae": ["family cracticidae"],
    "cracticus": ["genus cracticus"],
    "craft": ["trade"],
    "craftily": ["artfully", "cunningly", "foxily", "knavishly", "slyly", "trickily"],
    "craftiness": ["deceitfulness", "guile"],
    "craftsman": ["crafter"],
    "crafty": ["cunning", "dodgy", "foxy", "guileful", "knavish", "slick", "sly", "tricksy", "tricky", "wily"],
    "cragged": ["craggy", "hilly", "mountainous"],
    "craigie": ["sir william alexander craigie", "william a. craigie"],
    "cram": ["bone", "bone up", "drum", "get up", "grind away", "mug up", "swot", "swot up"],
    "crambe": ["genus crambe"],
    "cramp": ["cramp iron"],
    "crampon": ["crampoon"],
    "cranberry bush": ["american cranberry bush", "cranberry tree", "highbush cranberry", "viburnum trilobum"],
    "crane": ["stretch out"],
    "crane fly": ["daddy longlegs"],
    "cranesbill": ["crane's bill"],
    "crangon": ["genus crangon"],
    "crangonidae": ["family crangonidae"],
    "cranial cavity": ["intracranial cavity"],
    "craniometric": ["craniometrical"],
    "cranium": ["braincase", "brainpan"],
    "crank": ["crank up"],
    "crank handle": ["starting handle"],
    "crankiness": ["contrariness", "crotchetiness", "grumpiness"],
    "cranky": ["fractious", "irritable", "nettlesome", "peckish", "peevish", "pettish", "petulant", "scratchy", "techy", "testy", "tetchy"],
    "crap": ["dirt", "poop", "shit", "shite", "turd"],
    "crap shooting": ["crap game", "crapshoot"],
    "crapaud": ["leptodactylus pentadactylus", "south american bullfrog"],
    "crape": ["crepe"],
    "crape fern": ["leptopteris superba", "prince-of-wales feather", "prince-of-wales fern", "prince-of-wales plume", "todea superba"],
    "crape jasmine": ["adam's apple", "coffee rose", "crepe gardenia", "crepe jasmine", "east indian rosebay", "nero's crown", "pinwheel flower", "tabernaemontana divaricate"],
    "crape myrtle": ["crepe flower", "crepe myrtle", "lagerstroemia indica"],
    "craps": ["snake eyes"],
    "crapulent": ["crapulous"],
    "crash": ["break apart", "break up"],
    "crash course": ["crash program", "crash programme"],
    "craspedia": ["genus craspedia"],
    "crassness": ["crassitude"],
    "crassostrea": ["genus crassostrea"],
    "crassula": ["genus crassula"],
    "crassulaceae": ["family crassulaceae", "stonecrop family"],
    "crataegus": ["genus crataegus"],
    "crate": ["crateful"],
    "crateva": ["genus crateva"],
    "crave": ["hunger", "lust", "starve", "thirst"],
    "craved": ["desired"],
    "craven": ["recreant"],
    "craw": ["crop"],
    "crawford": ["thomas crawford"],
    "crawl": ["creep"],
    "crawler": ["creeper"],
    "crawlspace": ["crawl space"],
    "crax": ["genus crax"],
    "crayfish": ["crawdad", "crawfish", "ecrevisse"],
    "crayon": ["wax crayon"],
    "craze": ["delirium", "frenzy", "fury", "hysteria"],
    "crazed": ["deranged", "half-crazed"],
    "craziness": ["daftness", "flakiness"],
    "crazy": ["looney", "loony", "nutcase", "weirdo"],
    "crazy horse": ["tashunca-uitco"],
    "creak": ["creaking"],
    "creakily": ["creakingly", "screakily"],
    "creaky": ["decrepit", "derelict", "flea-bitten", "run-down", "woebegone"],
    "cream": ["bat", "clobber", "drub", "lick", "thrash"],
    "cream of tartar": ["potassium bitartrate", "potassium hydrogen tartrate", "tartar"],
    "cream off": ["skim off"],
    "cream pitcher": ["creamer"],
    "cream puff": ["chou"],
    "cream-colored": ["creamy-colored", "creamy-white"],
    "cream-colored courser": ["cursorius cursor"],
    "cream-of-tartar tree": ["adansonia gregorii", "sour gourd"],
    "creamcups": ["platystemon californicus"],
    "creaminess": ["soupiness"],
    "creaseless": ["uncreased"],
    "creaseproof": ["crease-resistant", "wrinkle-resistant", "wrinkleproof"],
    "create": ["make"],
    "create by mental act": ["create mentally"],
    "create from raw material": ["create from raw stuff"],
    "creatine": ["creatin"],
    "creation": ["conception"],
    "creative": ["originative"],
    "creativity": ["creative thinking", "creativeness"],
    "creature": ["puppet", "tool"],
    "creche": ["foundling hospital"],
    "crecy": ["battle of crecy"],
    "credence": ["acceptance"],
    "credenza": ["credence"],
    "credibility": ["believability", "credibleness"],
    "credible": ["believable"],
    "credibly": ["believably", "plausibly", "probably"],
    "credit": ["credit entry"],
    "credit account": ["charge account", "open account"],
    "credit card": ["charge card", "charge plate", "plastic"],
    "credit crunch": ["liquidity crisis", "squeeze"],
    "credit line": ["bank line", "line", "line of credit", "personal credit line", "personal line of credit"],
    "credit order": ["bill-me order"],
    "credit rating": ["credit"],
    "creditworthy": ["responsible"],
    "credulously": ["believingly"],
    "credulousness": ["gullibility"],
    "creed": ["credo"],
    "creedal": ["credal"],
    "creep": ["spook", "weirdie", "weirdo", "weirdy"],
    "creep up": ["sneak up"],
    "creeper": ["tree creeper"],
    "creeping bellflower": ["campanula rapunculoides"],
    "creeping bent": ["agrostis palustris", "creeping bentgrass"],
    "creeping bugle": ["ajuga reptans"],
    "creeping buttercup": ["creeping crowfoot", "ranunculus repens"],
    "creeping fern": ["hartford fern", "lygodium palmatum"],
    "creeping juniper": ["juniperus horizontalis"],
    "creeping oxalis": ["creeping wood sorrel", "oxalis corniculata"],
    "creeping snowberry": ["gaultheria hispidula", "maidenhair berry", "moxie plum"],
    "creeping soft grass": ["holcus mollis"],
    "creeping spike rush": ["eleocharis palustris"],
    "creeping st john's wort": ["hypericum calycinum"],
    "creeping willow": ["salix repens"],
    "creeping zinnia": ["sanvitalia procumbens"],
    "creepy": ["creepy-crawly"],
    "crematory": ["crematorium"],
    "crenate": ["crenated", "scalloped"],
    "crenel": ["crenelate", "crenellate"],
    "crenelation": ["crenellation"],
    "crenulate": ["crenulated"],
    "creole-fish": ["paranthias furcifer"],
    "creosote": ["coal-tar creosote"],
    "creosote bush": ["coville", "hediondilla", "larrea tridentata"],
    "crepe": ["crepe paper"],
    "crepe fern": ["king fern", "todea barbara"],
    "crepis": ["genus crepis"],
    "crepitate": ["crackle"],
    "crescent": ["crescent-shaped", "lunate", "semilunar"],
    "crescent roll": ["croissant"],
    "crescentia": ["genus crescentia"],
    "cresol": ["methyl phenol"],
    "cress": ["cress plant"],
    "cress green": ["cresson", "watercress"],
    "crested": ["topknotted", "tufted"],
    "crested cariama": ["cariama cristata", "seriema"],
    "crested coral root": ["hexalectris spicata"],
    "crested myna": ["acridotheres tristis"],
    "crested wheatgrass": ["agropyron cristatum", "crested wheat grass", "fairway crested wheat grass"],
    "cretaceous": ["cretaceous period"],
    "crete": ["kriti"],
    "creutzfeldt-jakob disease": ["cjd", "jakob-creutzfeldt disease"],
    "crevalle jack": ["caranx hippos", "jack crevalle"],
    "crevice": ["chap", "crack", "cranny", "fissure"],
    "crew cut": ["flattop"],
    "crew neck": ["crew neckline"],
    "crewman": ["crew member"],
    "crex": ["genus crex"],
    "crib": ["cot"],
    "cribbage": ["crib"],
    "cricetidae": ["family cricetidae"],
    "cricetus": ["genus cricetus"],
    "crichton": ["james crichton", "the admirable crichton"],
    "crick": ["kink", "rick", "wrick"],
    "cricket bat": ["bat"],
    "cricket-bat willow": ["salix alba caerulea"],
    "crime": ["criminal offence", "criminal offense", "law-breaking", "offence", "offense"],
    "criminal": ["crook", "felon", "malefactor", "outlaw"],
    "criminal intelligence services of canada": ["cisc"],
    "criminal investigation command": ["cid"],
    "criminal negligence": ["culpable negligence"],
    "criminal record": ["record"],
    "criminalism": ["criminality", "criminalness"],
    "criminalization": ["criminalisation"],
    "criminally": ["reprehensively"],
    "criminative": ["criminatory", "incriminating", "incriminatory"],
    "crimp": ["pinch"],
    "crimson": ["deep red", "ruby"],
    "crimson clover": ["italian clover", "trifolium incarnatum"],
    "cringing": ["groveling", "grovelling", "wormlike", "wormy"],
    "cringle": ["eyelet", "grommet", "grummet", "loop"],
    "crinkled": ["crinkly", "rippled", "wavelike", "wavy"],
    "crinkleroot": ["cardamine diphylla", "crinkle root", "crinkle-root", "dentaria diphylla", "pepper root", "toothwort"],
    "crinoidea": ["class crinoidea"],
    "cripple": ["stultify"],
    "crippled": ["game", "gimpy", "halt", "halting", "lame"],
    "crippling": ["disabling", "incapacitating"],
    "crisp": ["crispy"],
    "crispen": ["crisp", "toast"],
    "crisphead lettuce": ["iceberg", "iceberg lettuce"],
    "crispin": ["saint crispin", "st. crispin"],
    "crisscross": ["cross", "mark"],
    "criterial": ["criterional"],
    "criterion": ["standard"],
    "critical": ["vital"],
    "critical appraisal": ["critical analysis"],
    "criticality": ["criticalness", "cruciality"],
    "criticism": ["unfavorable judgment"],
    "criticize": ["criticise"],
    "croak": ["cronk"],
    "croaky": ["guttural"],
    "croatia": ["hrvatska", "republic of croatia"],
    "croatian": ["croat"],
    "crocethia": ["genus crocethia"],
    "crochet": ["hook"],
    "crochet needle": ["crochet hook"],
    "crock": ["earthenware jar"],
    "crockery": ["dishware"],
    "crockett": ["david crockett", "davy crockett"],
    "crocodile bird": ["pluvianus aegyptius"],
    "crocodilian reptile": ["crocodilian"],
    "crocodylia": ["crocodilia", "order crocodilia", "order crocodylia"],
    "crocodylidae": ["family crocodylidae"],
    "crocodylus": ["crocodilus", "genus crocodilus", "genus crocodylus"],
    "crocuta": ["genus crocuta"],
    "crohn": ["burrill bernard crohn"],
    "cromwell": ["ironsides", "oliver cromwell"],
    "cronartium": ["genus cronartium"],
    "cronyn": ["hume blake cronyn", "hume cronyn"],
    "crook": ["curve"],
    "crookback": ["crookbacked", "gibbous", "humpbacked", "humped", "hunchbacked", "kyphotic"],
    "crooked": ["corrupt"],
    "crookedness": ["deviousness"],
    "crookes": ["sir william crookes", "william crookes"],
    "crookneck": ["crookneck squash", "summer crookneck"],
    "crooner": ["balladeer"],
    "crop": ["graze", "pasture"],
    "crop up": ["pop", "pop up"],
    "crop-dusting": ["spraying"],
    "crosby": ["bing crosby", "harry lillis crosby"],
    "crosier": ["crozier"],
    "cross": ["span", "sweep", "traverse"],
    "cross bun": ["hot cross bun"],
    "cross examine": ["cross question"],
    "cross hair": ["cross wire"],
    "cross off": ["cross out", "mark", "strike off", "strike out"],
    "cross vine": ["bignonia capreolata", "quarter-vine", "quartervine", "trumpet flower"],
    "cross-classification": ["cross-division"],
    "cross-country riding": ["cross-country jumping"],
    "cross-examiner": ["cross-questioner"],
    "cross-eye": ["convergent strabismus", "crossed eye", "esotropia"],
    "cross-fertilization": ["cross-fertilisation"],
    "cross-fertilize": ["cross-fertilise"],
    "cross-file": ["register"],
    "cross-florida waterway": ["okeechobee waterway"],
    "cross-leaved heath": ["bell heather", "erica tetralix"],
    "cross-link": ["cross-linkage"],
    "cross-reference": ["cross-index"],
    "cross-section": ["cross-sectional"],
    "crossbill": ["loxia curvirostra"],
    "crossbreed": ["cross", "hybridise", "hybridize", "interbreed"],
    "crosscut": ["cut across"],
    "crosscut saw": ["crosscut handsaw", "cutoff saw"],
    "crossheading": ["crosshead"],
    "crossing": ["crossover", "crosswalk"],
    "crossing over": ["crossover"],
    "crossjack": ["mizzen course"],
    "crossly": ["grouchily", "grumpily"],
    "crossopterygian": ["lobe-finned fish", "lobefin"],
    "crossopterygii": ["subclass crossopterygii"],
    "crossover voter": ["crossover"],
    "crosstalk": ["xt"],
    "crosstown": ["cross-town"],
    "crossword puzzle": ["crossword"],
    "crotalaria": ["rattlebox"],
    "crotalidae": ["family crotalidae"],
    "crotalus": ["genus crotalus"],
    "crotaphytus": ["genus crotaphytus"],
    "crotch": ["fork"],
    "croton": ["codiaeum variegatum"],
    "crotophaga": ["genus crotophaga"],
    "crottle": ["crotal", "crottal"],
    "crouch": ["bend", "bow", "stoop"],
    "croup": ["spasmodic laryngitis"],
    "crouse": ["russel crouse"],
    "crow garlic": ["allium vineale", "false garlic", "field garlic", "stag's garlic", "wild garlic"],
    "crow pheasant": ["centropus sinensis"],
    "crow's foot": ["crow's feet", "laugh line"],
    "crowbait": ["crow-bait"],
    "crowbar": ["pry", "pry bar", "wrecking bar"],
    "crowd": ["crowd together"],
    "crown": ["coronate"],
    "crown daisy": ["chrysanthemum coronarium"],
    "crown imperial": ["fritillaria imperialis"],
    "crown of thorns": ["christ plant", "christ thorn", "euphorbia milii"],
    "crownbeard": ["crown beard", "crown-beard"],
    "crucial": ["important"],
    "crucian carp": ["carassius carassius", "carassius vulgaris"],
    "cruciate": ["cruciform"],
    "crucible": ["melting pot"],
    "crucifer": ["cruciferous plant"],
    "cruciferae": ["brassicaceae", "family brassicaceae", "family cruciferae", "mustard family"],
    "crucifix": ["rood", "rood-tree"],
    "crucifixion": ["excruciation"],
    "cruddy": ["filthy", "foul", "nasty", "smutty"],
    "crude": ["rough"],
    "crudeness": ["crudity", "primitiveness", "primitivism", "rudeness"],
    "cruel plant": ["araujia sericofera"],
    "cruelty": ["mercilessness", "pitilessness", "ruthlessness"],
    "cruet": ["crewet"],
    "cruise": ["sail"],
    "cruise ship": ["cruise liner"],
    "cruiser": ["patrol car", "police car", "police cruiser", "prowl car", "squad car"],
    "cruller": ["twister"],
    "crumble": ["break down", "collapse", "crumple", "tumble"],
    "crumbliness": ["friability"],
    "crumbly": ["friable"],
    "crump": ["scrunch", "thud"],
    "crunch": ["cranch", "craunch", "grind"],
    "crusade": ["agitate", "campaign", "fight", "press", "push"],
    "crush": ["demolish", "smash"],
    "crushed leather": ["crush"],
    "crushing": ["devastating"],
    "crust": ["encrustation", "incrustation"],
    "crustacea": ["class crustacea"],
    "crustaceous": ["crustacean"],
    "crustal movement": ["tectonic movement"],
    "crusted": ["crustlike", "crusty", "encrusted"],
    "crusty": ["curmudgeonly", "gruff", "ill-humored", "ill-humoured"],
    "crux": ["crux of the matter"],
    "cry": ["blazon out"],
    "cry out for": ["cry for"],
    "cryesthesia": ["cryaesthesia"],
    "crying": ["tears", "weeping"],
    "cryoanesthesia": ["cryoanaesthesia"],
    "cryogenics": ["cryogeny"],
    "cryolite": ["greenland spar"],
    "cryptacanthodes": ["genus cryptacanthodes"],
    "cryptanalysis": ["cryptanalytics", "cryptography", "cryptology"],
    "cryptanalyst": ["cryptographer", "cryptologist"],
    "cryptanalytic": ["cryptographic", "cryptographical", "cryptologic", "cryptological"],
    "cryptic": ["cryptical", "deep", "inscrutable", "mysterious", "mystifying"],
    "cryptically": ["enigmatically", "mysteriously"],
    "cryptobranchidae": ["family cryptobranchidae"],
    "cryptobranchus": ["genus cryptobranchus"],
    "cryptocercidae": ["family cryptocercidae"],
    "cryptocercus": ["genus cryptocercus"],
    "cryptocoryne": ["water trumpet"],
    "cryptogamic": ["cryptogamous"],
    "cryptogram": ["cryptograph", "secret writing"],
    "cryptogramma": ["genus cryptogramma"],
    "cryptogrammataceae": ["family cryptogrammataceae"],
    "cryptography": ["coding", "secret writing", "steganography"],
    "cryptomeria": ["genus cryptomeria"],
    "cryptomonad": ["cryptophyte"],
    "cryptophyceae": ["class cryptophyceae"],
    "cryptophyta": ["phylum cryptophyta"],
    "cryptoprocta": ["genus cryptoprocta"],
    "cryptorchidy": ["cryptorchidism", "cryptorchism"],
    "cryptotermes": ["genus cryptotermes"],
    "cryptotis": ["genus cryptotis"],
    "crystal": ["crystallization"],
    "crystal oscillator": ["quartz oscillator"],
    "crystalline": ["crystal clear", "limpid", "lucid", "pellucid", "transparent"],
    "crystallization": ["crystallisation", "crystallizing"],
    "crystallize": ["crystalise", "crystalize", "crystallise"],
    "crystallized": ["crystallised"],
    "ctene": ["comb-plate"],
    "ctenizidae": ["family ctenizidae"],
    "ctenocephalides": ["genus ctenocephalides"],
    "ctenocephalus": ["genus ctenocephalus"],
    "ctenoid": ["comb-like"],
    "ctenophora": ["phylum ctenophora"],
    "ctenophore": ["comb jelly"],
    "cub": ["greenhorn", "rookie"],
    "cuba": ["republic of cuba"],
    "cuban bast": ["blue mahoe", "hibiscus elatus", "mahagua", "mahoe", "majagua"],
    "cuban peso": ["peso"],
    "cubby": ["cubbyhole", "snug", "snuggery"],
    "cubbyhole": ["pigeonhole"],
    "cube": ["dice"],
    "cubeb": ["cubeb vine", "java pepper", "piper cubeba"],
    "cubelike": ["cube-shaped", "cubical", "cubiform", "cuboid", "cuboidal"],
    "cubic": ["three-dimensional"],
    "cubic foot": ["cu ft"],
    "cubic inch": ["cu in"],
    "cubic kilometer": ["cubic kilometre"],
    "cubic millimeter": ["cubic millimetre"],
    "cubic yard": ["yard"],
    "cubist": ["cubistic"],
    "cuboidal cell": ["cuboidal epithelial cell"],
    "cucking stool": ["ducking stool"],
    "cuckoopint": ["arum maculatum", "jack-in-the-pulpit", "lords-and-ladies"],
    "cuculidae": ["family cuculidae"],
    "cuculiformes": ["order cuculiformes"],
    "cuculus": ["genus cuculus"],
    "cucumber": ["cucumber vine", "cucumis sativus"],
    "cucumber tree": ["magnolia acuminata"],
    "cucumis": ["genus cucumis"],
    "cucurbita": ["genus cucurbita"],
    "cucurbitaceae": ["family cucurbitaceae", "gourd family"],
    "cud": ["rechewed food"],
    "cuddle": ["draw close", "nest", "nestle", "nuzzle", "snuggle"],
    "cuddlesome": ["cuddly"],
    "cudgel": ["fustigate"],
    "cue": ["cue stick", "pool cue", "pool stick"],
    "cuff": ["whomp"],
    "cuisine": ["culinary art"],
    "cul": ["cul de sac", "dead end"],
    "culbertson": ["ely culbertson"],
    "culcita": ["genus culcita"],
    "culex": ["genus culex"],
    "culex quinquefasciatus": ["culex fatigans"],
    "culicidae": ["family culicidae"],
    "cull": ["reject"],
    "cull out": ["winnow"],
    "culminate": ["climax"],
    "cult": ["cultus", "religious cult"],
    "cultivate": ["crop", "work"],
    "cultivated land": ["farmland", "ploughland", "plowland", "tillage", "tilled land", "tilth"],
    "cultivated rice": ["oryza sativa"],
    "cultivator": ["tiller"],
    "cultural": ["ethnic", "ethnical"],
    "cultural revolution": ["great proletarian cultural revolution"],
    "culture": ["civilisation", "civilization"],
    "culture medium": ["medium"],
    "culver's root": ["culver's physic", "culvers physic", "culvers root", "veronicastrum virginicum", "whorlywort"],
    "cumberland": ["butcher cumberland", "duke of cumberland", "william augustus"],
    "cumberland mountains": ["cumberland plateau"],
    "cumbersome": ["cumbrous"],
    "cumin": ["cuminum cyminum"],
    "cuminum": ["genus cuminum"],
    "cummings": ["e. e. cummings", "edward estlin cummings"],
    "cumulative preferred": ["cumulative preferred stock"],
    "cumulonimbus": ["cumulonimbus cloud", "thundercloud"],
    "cumulus": ["cumulus cloud"],
    "cunaxa": ["battle of cunaxa"],
    "cuneate": ["wedge-shaped"],
    "cuniculus": ["genus cuniculus"],
    "cunner": ["bergall", "tautogolabrus adspersus"],
    "cunnilingus": ["cunnilinctus"],
    "cunning": ["cute"],
    "cunningham": ["merce cunningham"],
    "cunningly": ["cutely"],
    "cunoniaceae": ["cunonia family", "family cunoniaceae"],
    "cunt": ["bitch"],
    "cuon": ["cyon", "genus cuon", "genus cyon"],
    "cup": ["transfuse"],
    "cup of tea": ["bag", "dish"],
    "cupboard": ["closet"],
    "cupflower": ["nierembergia"],
    "cupid": ["amor"],
    "cuppa": ["cupper"],
    "cupressaceae": ["cypress family", "family cupressaceae"],
    "cupressus": ["genus cupressus"],
    "cupric": ["cuprous"],
    "cupular": ["cupulate"],
    "cupule": ["acorn cup"],
    "cuquenan": ["cuquenan falls", "kukenaam", "kukenaam falls"],
    "cur": ["mongrel", "mutt"],
    "curability": ["curableness"],
    "curacao": ["curacoa"],
    "curate": ["minister", "minister of religion", "parson", "pastor", "rector"],
    "curative": ["alterative", "healing", "remedial", "sanative", "therapeutic"],
    "curator": ["conservator"],
    "curb": ["curb bit"],
    "curbstone": ["kerbstone"],
    "curculionidae": ["family curculionidae"],
    "curcuma": ["genus curcuma"],
    "curdle": ["clabber", "clot"],
    "curdling": ["clotting", "coagulation"],
    "cured": ["healed", "recovered"],
    "curettage": ["curettement"],
    "curette": ["curet"],
    "curie": ["ci"],
    "curie temperature": ["curie point"],
    "curio": ["curiosity", "oddity", "oddment", "peculiarity", "rarity"],
    "curiosity": ["wonder"],
    "curious": ["funny", "odd", "peculiar", "queer", "rum", "rummy", "singular"],
    "curiously": ["inquisitively", "interrogatively"],
    "curiousness": ["inquisitiveness"],
    "curium": ["atomic number 96", "cm"],
    "curl": ["wave"],
    "curl up": ["curl", "draw in"],
    "curled": ["curling"],
    "curled leaf pondweed": ["curly pondweed", "potamogeton crispus"],
    "curler": ["crimper", "hair curler", "roller"],
    "curlew sandpiper": ["calidris ferruginea"],
    "curliness": ["waviness"],
    "curly grass": ["curly grass fern", "schizaea pusilla"],
    "curly-grained": ["cross-grained", "wavy-grained"],
    "curly-haired": ["curly-coated"],
    "curly-heads": ["clematis ochreleuca"],
    "curly-leaved": ["curly-leafed"],
    "curlycup gumweed": ["grindelia squarrosa"],
    "currant": ["currant bush"],
    "currawong": ["bell magpie"],
    "current": ["electric current"],
    "currentness": ["currency", "up-to-dateness"],
    "curriculum vitae": ["cv", "resume"],
    "currier": ["nathaniel currier"],
    "currishly": ["ignobly"],
    "curry favor": ["court favor", "court favour", "curry favour"],
    "curse": ["anathemise", "anathemize", "bedamn", "beshrew", "damn", "imprecate", "maledict"],
    "cursed": ["damned", "doomed", "unredeemed", "unsaved"],
    "cursed crowfoot": ["celery-leaved buttercup", "ranunculus sceleratus"],
    "cursed with": ["stuck with"],
    "cursor": ["pointer"],
    "cursorily": ["quickly"],
    "cursorius": ["genus cursorius"],
    "curtain": ["drape", "drapery", "mantle", "pall"],
    "curtainless": ["uncurtained"],
    "curtis": ["william curtis"],
    "curtisia": ["genus curtisia"],
    "curtiss": ["glenn curtiss", "glenn hammond curtiss"],
    "curtly": ["short", "shortly"],
    "curtsy": ["curtsey"],
    "curvaceously": ["buxomly"],
    "curvaceousness": ["shapeliness", "voluptuousness"],
    "curvature": ["curve"],
    "curve": ["curved shape"],
    "curved": ["curving"],
    "curvet": ["vaulting"],
    "curvilineal": ["curvilinear"],
    "curvilinear correlation": ["nonlinear correlation", "skew correlation"],
    "curvy": ["curvey"],
    "cuscuta": ["genus cuscuta"],
    "cush-cush": ["dioscorea trifida"],
    "cushaw": ["cucurbita argyrosperma", "cucurbita mixta"],
    "cushing": ["harvery williams cushing", "harvey cushing"],
    "cushing's disease": ["hyperadrenalism"],
    "cushing's syndrome": ["hyperadrenocorticism"],
    "cushion": ["buffer", "soften"],
    "cushion flower": ["hakea laurina", "pincushion hakea"],
    "cushioned": ["cushiony", "padded"],
    "cushy": ["easygoing", "soft"],
    "cusk": ["brosme brosme", "torsk"],
    "cusp": ["leaflet"],
    "cuspate": ["cuspated", "cusped", "cuspidal", "cuspidate", "cuspidated"],
    "cussed": ["obdurate", "obstinate", "unrepentant"],
    "cussedness": ["orneriness"],
    "custard apple": ["custard apple tree"],
    "custer": ["general custer", "george armstrong custer"],
    "custodial": ["tutelar", "tutelary"],
    "custodian": ["keeper", "steward"],
    "custom": ["tradition"],
    "custom-built": ["made-to-order"],
    "custom-made": ["custom-built"],
    "custom-make": ["customise", "customize", "tailor-make"],
    "customer": ["client"],
    "customhouse": ["customshouse"],
    "customize": ["customise"],
    "customs": ["custom", "customs duty", "impost"],
    "cut": ["skip"],
    "cut back": ["flash back"],
    "cut down": ["cut out"],
    "cut off": ["cut out"],
    "cut short": ["break off", "break short"],
    "cut-and-dried": ["cut-and-dry"],
    "cut-in": ["insert"],
    "cutaneous": ["cutaneal", "dermal"],
    "cutaneous anthrax": ["malignant pustule"],
    "cutaneous leishmaniasis": ["aleppo boil", "delhi boil", "old world leishmaniasis", "oriental sore", "tropical sore"],
    "cutaneous sensation": ["haptic sensation", "skin sensation"],
    "cutaneous vein": ["vena cutanea"],
    "cutaway": ["cutaway drawing", "cutaway model"],
    "cutch": ["kutch"],
    "cute": ["precious"],
    "cuterebra": ["genus cuterebra"],
    "cuterebridae": ["family cuterebridae"],
    "cuticular": ["dermal", "epidermal", "epidermic"],
    "cutlas": ["cutlass"],
    "cutlassfish": ["frost fish", "hairtail"],
    "cutleaved coneflower": ["rudbeckia laciniata"],
    "cutlery": ["eating utensil"],
    "cutlet": ["escallop", "scallop", "scollop"],
    "cutter": ["carver"],
    "cutthroat": ["bowelless", "fierce"],
    "cutting": ["slip"],
    "cuttlefish": ["cuttle"],
    "cuvier": ["baron georges cuvier", "georges cuvier", "georges leopold chretien frederic dagobert cuvier"],
    "cuzco": ["cusco"],
    "cy pres": ["cy pres doctrine", "rule of cy pres"]
}
