synonyms = {
    "blanch": ["cook", "parboil"],
    "blancmange": ["afters", "dessert", "sweet"],
    "bland": ["flat", "flavorless", "flavourless", "insipid", "savorless", "savourless", "vapid"],
    "bland diet": ["diet", "ulcer diet"],
    "blandfordia": ["genus blandfordia", "liliid monocot genus"],
    "blandishment": ["cajolery", "flattery", "palaver"],
    "blandly": [],
    "blandness": ["insipidity", "insipidness", "unappetisingness", "unappetizingness"],
    "blank": ["keep", "prevent"],
    "blank check": ["bank check", "blank cheque", "check", "cheque"],
    "blank endorsement": ["endorsement", "endorsement in blank", "indorsement"],
    "blank out": ["edit", "redact"],
    "blank verse": ["poem", "verse form"],
    "blanket": ["cover", "spread over"],
    "blanket flower": ["fire wheel", "fire-wheel", "gaillardia", "gaillardia pulchella", "indian blanket"],
    "blanket jam": ["block", "jam"],
    "blanket stitch": ["embroidery stitch", "sewing stitch"],
    "blanketed": [],
    "blankly": [],
    "blankness": ["emptiness"],
    "blanquillo": ["percoid", "percoid fish", "percoidean", "tilefish"],
    "blantyre": [],
    "blare": ["blaring", "cacophony", "clamor", "din", "noise"],
    "blare out": ["announce", "blat out", "denote"],
    "blarina": ["genus blarina", "mammal genus"],
    "blaring": ["blasting"],
    "blarney": ["coaxing", "flattery", "soft soap", "sweet talk"],
    "blarney stone": [],
    "blase": ["worldly"],
    "blaspheme": ["talk about", "talk of"],
    "blasphemer": ["nonreligious person", "swearer"],
    "blasphemous": ["profane", "sacrilegious"],
    "blasphemously": [],
    "blasphemy": ["discourtesy", "disrespect", "profanity"],
    "blast": ["blare", "make noise", "noise", "resound"],
    "blast furnace": ["furnace"],
    "blast off": ["launch"],
    "blast trauma": ["harm", "hurt", "injury", "trauma"],
    "blasted": ["blame", "blamed", "blessed", "damn", "damned", "darned", "deuced", "goddam", "goddamn", "goddamned", "infernal"],
    "blastema": ["cell"],
    "blastemal": ["blastematic", "blastemic"],
    "blaster": ["chargeman", "working man", "working person", "workingman", "workman"],
    "blasting": ["ruinous"],
    "blasting cap": ["cap", "detonating device", "detonator"],
    "blasting gelatin": ["explosive mixture"],
    "blastocladia": ["fungus genus", "genus blastocladia"],
    "blastocladiales": ["fungus order", "order blastocladiales"],
    "blastocoel": ["blastocele", "blastocoele", "bodily cavity", "cavity", "cavum", "cleavage cavity", "segmentation cavity"],
    "blastocoelic": [],
    "blastocyst": ["blastodermic vessicle", "blastosphere", "blastula"],
    "blastocyte": ["embryonic cell", "formative cell"],
    "blastoderm": ["blastodisc", "germinal area", "germinal disc", "layer"],
    "blastodermatic": ["blastodermic"],
    "blastodiaceae": ["family blastodiaceae", "fungus family"],
    "blastoff": ["rocket firing", "rocket launching", "shot"],
    "blastogenesis": ["agamogenesis", "asexual reproduction"],
    "blastogenetic": [],
    "blastoma": ["blastocytoma", "embryonal carcinosarcoma", "neoplasm", "tumor", "tumour"],
    "blastomere": ["cell"],
    "blastomeric": [],
    "blastomyces": ["fungus genus", "genus blastomyces"],
    "blastomycete": ["fungus"],
    "blastomycosis": ["chromoblastomycosis", "fungal infection", "mycosis"],
    "blastomycotic": [],
    "blastoporal": ["blastoporic"],
    "blastopore": ["opening", "orifice", "porta"],
    "blastospheric": ["blastular"],
    "blastula": ["blastocyst", "blastodermic vessicle", "blastosphere", "conceptus", "embryo", "fertilized egg"],
    "blatancy": ["distastefulness", "noticeability", "noticeableness", "obviousness", "odiousness", "offensiveness", "patency"],
    "blatant": ["blazing", "conspicuous"],
    "blatantly": [],
    "blather": ["blatherskite", "gibber", "gibberish"],
    "blatta": ["arthropod genus", "genus blatta"],
    "blattella": ["arthropod genus", "genus blattella"],
    "blattidae": ["arthropod family", "family blattidae"],
    "blattodea": ["animal order", "blattaria", "suborder blattaria", "suborder blattodea"],
    "blaxploitation": ["exploitation", "using", "victimisation", "victimization"],
    "blaze": ["beam", "shine"],
    "blaze away": ["do", "execute", "perform"],
    "blazer": ["jacket", "sport coat", "sport jacket", "sports coat", "sports jacket"],
    "blazing": ["blinding", "dazzling", "fulgent", "glaring", "glary"],
    "blazing star": ["flower", "mentzelia laevicaulis", "mentzelia livicaulis"],
    "bleach": ["bleach out", "decolor", "decolorise", "decolorize", "decolour", "decolourise", "decolourize", "discolor", "discolorise", "discolorize", "discolourise"],
    "bleach liquor": ["solution"],
    "bleached": ["colored", "coloured", "dyed"],
    "bleacher": ["worker"],
    "bleachers": ["stand"],
    "bleaching agent": ["agent", "benzoyl peroxide", "blanching agent", "bleach", "bleaching powder", "calcium hypochlorite", "chloride of lime", "chlorinated lime", "chlorine dioxide", "chlorine water", "clorox", "sodium hypochlorite", "whitener"],
    "bleaching clay": ["bleaching earth", "clay", "mud"],
    "bleaching powder": ["blanching agent", "bleach", "bleaching agent", "chloride of lime", "chlorinated lime", "whitener"],
    "bleak": ["cutting", "raw"],
    "bleakly": [],
    "bleakness": ["bareness", "desolation", "gloom", "gloominess", "glumness", "nakedness"],
    "bleary": ["blear", "blear-eyed", "bleary-eyed"],
    "bleat": ["complain", "kick", "kvetch", "plain", "quetch", "sound off"],
    "blebbed": ["blebby"],
    "blebby": ["blistery"],
    "blechnaceae": ["family blechnaceae", "fern family"],
    "blechnum": ["fern genus", "genus blechnum"],
    "bleed": ["extort", "gouge", "rack", "squeeze", "wring"],
    "bleeding": ["blood extravasation", "cerebral hemorrhage", "epistaxis", "haemorrhage", "haemorrhagic stroke", "harm", "hemorrhage", "hemorrhagic stroke", "hurt", "hyphema", "injury", "metrorrhagia", "nosebleed", "trauma", "ulemorrhagia"],
    "bleeding heart": ["dicentra spectabilis", "herb", "herbaceous plant", "lyre-flower", "lyreflower"],
    "bleeding tooth": ["nerita peloronta", "neritid", "neritid gastropod"],
    "bleep": ["go", "sound"],
    "blemish": ["begrime", "bemire", "colly", "dirty", "grime", "soil", "spot"],
    "blemished": ["flawed"],
    "blend": ["accord", "agree", "blend in", "concord", "consort", "fit in", "go", "harmonise", "harmonize"],
    "blend in": ["blend", "coalesce", "combine", "commingle", "conflate", "cut in", "flux", "fuse", "immix", "meld", "merge", "mix", "mix in"],
    "blended": [],
    "blended whiskey": ["blended whisky", "whiskey", "whisky"],
    "blender": ["liquidiser", "liquidizer", "mixer"],
    "blenheim": [],
    "blenheim spaniel": ["english toy spaniel"],
    "blenniidae": ["family blenniidae", "fish family"],
    "blennioid fish": ["blennioid", "blenny", "bracketed blenny", "catfish", "clinid", "clinid fish", "combtooth blenny", "cryptacanthodes maculatus", "eelpout", "ghostfish", "gunnel", "percoid", "percoid fish", "percoidean", "pikeblenny", "pout", "prickleback", "wolf fish", "wolffish", "wrymouth"],
    "blennioidea": ["animal order", "suborder blennioidea"],
    "blennius": ["fish genus", "genus blennius"],
    "blenny": ["blennioid", "blennioid fish", "blennius pholis", "combtooth blenny", "molly miller", "scartella cristata", "shanny"],
    "blepharism": ["twitch", "twitching", "vellication"],
    "blepharitis": ["inflammation", "redness", "rubor"],
    "blepharospasm": ["cramp", "muscle spasm", "spasm"],
    "blephilia": ["asterid dicot genus", "genus blephilia"],
    "bleriot": ["louis bleriot"],
    "bless": ["bestow", "confer"],
    "blessed": [],
    "blessed event": ["happy event", "live birth"],
    "blessed thistle": ["cnicus benedictus", "sweet sultan", "thistle"],
    "blessedly": [],
    "blessedness": ["beatification", "beatitude", "enlightenment", "felicity", "happiness", "nirvana"],
    "blessing": ["boon", "good fortune", "good luck", "luckiness", "mercy"],
    "bletia": ["orchid", "orchidaceous plant"],
    "bletilla": ["genus bletilla", "liliopsid genus", "monocot genus"],
    "bletilla striata": ["bletia striata", "orchid", "orchidaceous plant"],
    "bleu": ["bavarian blue", "blue cheese", "cheese", "danish blue", "gorgonzola", "roquefort", "stilton"],
    "bleu cheese dressing": ["blue cheese dressing", "dressing", "salad dressing"],
    "blewits": ["agaric", "clitocybe nuda"],
    "blida": [],
    "bligh": ["captain bligh", "william bligh"],
    "blighia": ["dicot genus", "genus blighia", "magnoliopsid genus"],
    "blight": ["afflict", "plague", "smite"],
    "blight canker": ["fire blight", "pear blight"],
    "blighted": ["spoilt"],
    "blighty": ["britain", "great britain", "u.k.", "uk", "united kingdom", "united kingdom of great britain and northern ireland"],
    "blighty wound": ["combat injury", "injury", "wound"],
    "blimp": ["airship", "dirigible", "sausage", "sausage balloon"],
    "blimpish": [],
    "blind": ["bedazzle", "daze", "dazzle", "seel", "snow-blind"],
    "blind alley": ["cul de sac", "dead-end street", "impasse", "thoroughfare"],
    "blind corner": ["corner", "street corner", "turning point"],
    "blind curve": ["bend", "blind bend", "curve"],
    "blind date": ["date", "escort"],
    "blind flying": ["blind landing", "flight", "flying"],
    "blind person": ["visually impaired person"],
    "blind side": ["side"],
    "blind snake": ["leptotyphlops humilis", "ophidian", "serpent", "snake", "western blind snake", "worm snake"],
    "blind spot": ["issue", "matter", "subject", "topic"],
    "blind stitching": ["sewing", "stitching"],
    "blind trust": ["trust"],
    "blinded": [],
    "blindfold": ["cover"],
    "blindly": [],
    "blindman's bluff": ["blindman's buff", "child's game"],
    "blindness": ["anopia", "cecity", "eyelessness", "figural blindness", "legal blindness", "sightlessness", "snow-blindness", "snowblindness", "vision defect", "visual defect", "visual disorder", "visual impairment"],
    "blindside": ["surprise"],
    "blindworm": ["anguid lizard", "anguis fragilis", "slowworm"],
    "bling": ["bling bling", "jewellery", "jewelry"],
    "blini": ["battercake", "bliny", "flannel cake", "flannel-cake", "flapcake", "flapjack", "griddlecake", "hot cake", "hotcake", "pancake"],
    "blink": ["act involuntarily", "act reflexively", "bat", "flutter", "nictate", "nictitate", "palpebrate", "wink"],
    "blink of an eye": ["bit", "flash", "heartbeat", "instant", "jiffy", "minute", "mo", "moment", "new york minute", "second", "split second", "trice", "twinkling", "wink"],
    "blinker": ["cover"],
    "blinking": ["winking"],
    "blinks": ["blinking chickweed", "indian lettuce", "montia lamprosperma", "water chickweed"],
    "blintz": ["battercake", "blintze", "flannel cake", "flannel-cake", "flapcake", "flapjack", "griddlecake", "hot cake", "hotcake", "pancake"],
    "blip": ["blow", "shock"],
    "bliss": ["blissfulness", "cloud nine", "ecstasy", "elation", "rapture", "seventh heaven", "walking on air"],
    "blissful": [],
    "blissfully": [],
    "blissus": ["arthropod genus", "genus blissus"],
    "blister": ["assail", "assault", "attack", "lash out", "round", "scald", "snipe", "whip"],
    "blister beetle": ["beetle", "meloid", "oil beetle", "spanish fly"],
    "blister blight": ["blight"],
    "blister copper": ["atomic number 29", "copper", "cu"],
    "blister pack": ["bubble pack", "packaging"],
    "blister rust": ["rust", "white pine blister rust", "white-pine rust"],
    "blistering": ["blistery"],
    "blithe": [],
    "blitz": ["assail", "attack"],
    "blitzkrieg": ["war"],
    "blitzstein": ["marc blitzstein"],
    "blizzard": ["snowstorm", "storm", "violent storm"],
    "bloat": ["distend", "swell"],
    "bloater": ["herring"],
    "blob": ["amorphous shape"],
    "bloc": ["alignment", "alinement", "alliance", "axis", "coalition", "scheduled territories", "sterling area", "sterling bloc"],
    "bloch": ["ernest bloch"],
    "block": ["operate", "run"],
    "block and tackle": ["hoist"],
    "block diagram": ["diagram"],
    "block grant": ["grant", "subsidisation", "subsidization"],
    "block letter": ["alphabetic character", "block capital", "letter", "letter of the alphabet"],
    "block out": ["adumbrate", "outline", "sketch"],
    "block plane": ["carpenter's plane", "plane", "woodworking plane"],
    "block vote": ["ballot", "balloting", "vote", "voting"],
    "blockade": ["block", "block off", "close up", "impede", "jam", "obstruct", "obturate", "occlude"],
    "blockade-runner": ["ship"],
    "blockading": [],
    "blockage": ["block", "breech closer", "breechblock", "closure", "impediment", "impedimenta", "obstructer", "obstruction", "obstructor", "occlusion", "plug", "stop", "stoppage", "stopper", "stopple", "vapor lock", "vapour lock"],
    "blockbuster": ["general-purpose bomb", "gp bomb"],
    "blocked": ["out of use"],
    "blocker": ["football player", "footballer"],
    "blockheaded": ["boneheaded", "duncical", "duncish", "fatheaded", "loggerheaded", "thick", "thick-skulled", "thickheaded", "wooden-headed"],
    "blockhouse": ["fastness", "stronghold"],
    "blocking": ["block", "interference", "obstruction", "parry", "trap block"],
    "blockish": ["blocky"],
    "bloemfontein": [],
    "blog": ["communicate", "intercommunicate"],
    "blogger": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "blok": ["aleksandr aleksandrovich blok", "alexander alexandrovich blok"],
    "blolly": ["bush", "chiococca alba", "shrub", "west indian snowberry"],
    "blond": ["blonde", "individual", "mortal", "peroxide blond", "peroxide blonde", "person", "platinum blond", "platinum blonde", "somebody", "someone", "soul", "towhead"],
    "blood": ["daub", "smear"],
    "blood agar": ["agar", "nutrient agar"],
    "blood bank": ["bank"],
    "blood blister": ["bleb", "blister", "bulla"],
    "blood brother": ["ally", "friend"],
    "blood brotherhood": ["friendly relationship", "friendship"],
    "blood cell": ["blood corpuscle", "corpuscle", "erythrocyte", "leucocyte", "leukocyte", "packed cells", "rbc", "red blood cell", "somatic cell", "vegetative cell", "wbc", "white blood cell", "white blood corpuscle", "white cell", "white corpuscle"],
    "blood clam": ["bivalve", "lamellibranch", "pelecypod"],
    "blood clot": ["blood", "grume"],
    "blood coagulation": ["blood clotting", "clotting", "coagulation", "curdling"],
    "blood count": ["count"],
    "blood cup": ["cup fungus", "discomycete", "fairy cup", "peziza coccinea"],
    "blood disease": ["acanthocytosis", "acidemia", "afibrinogenemia", "agranulocytosis", "agranulosis", "alkalemia", "anaemia", "analbuminemia", "anemia", "banti's disease", "banti's syndrome", "bleeder's disease", "blood disorder", "blood dyscrasia", "blood poisoning", "cytopenia", "erythroblastosis", "granulocytopenia", "haemoglobinopathy", "haemophilia", "hemoglobinopathy", "hemophilia", "histiocytosis", "hydremia", "hypervolaemia", "hypervolemia", "hypothrombinemia", "hypovolaemia", "hypovolemia", "leucocytosis", "leucopenia", "leukocytosis", "leukopenia", "lymphocytopenia", "lymphocytosis", "lymphopenia", "microcytosis", "parasitaemia", "parasitemia", "peliosis", "polycythemia", "purpura", "septicaemia", "septicemia", "thrombocytopenia", "thrombopenia", "uratemia", "uricaciduria"],
    "blood donor": ["donor", "universal donor"],
    "blood dyscrasia": ["blood disease", "blood disorder", "dyscrasia"],
    "blood extravasation": ["bleeding", "extravasation", "haemorrhage", "hemorrhage"],
    "blood flower": ["asclepias curassavica", "milkweed", "silkweed", "swallowwort"],
    "blood group": ["a", "ab", "b", "blood", "blood type", "group a", "group ab", "group b", "group o", "o", "rh negative", "rh positive", "rh-negative blood", "rh-negative blood type", "rh-positive blood type", "type a", "type ab", "type b", "type o"],
    "blood lily": ["bulbous plant", "cape tulip", "haemanthus coccineus"],
    "blood meal": ["feed", "provender"],
    "blood money": ["compensation"],
    "blood poisoning": ["blood disease", "blood disorder", "childbed fever", "fowl cholera", "puerperal fever", "pyaemia", "pyemia", "sepsis", "septicaemia", "septicemia", "shipping fever", "shipping pneumonia", "toxaemia", "toxemia"],
    "blood pressure": ["arterial pressure", "diastolic pressure", "force per unit area", "pressure", "pressure level", "systolic pressure", "venous pressure", "vital sign"],
    "blood relation": ["blood relative", "cognate", "relation", "relative", "sib"],
    "blood sausage": ["black pudding", "blood pudding", "sausage"],
    "blood spavin": ["spavin"],
    "blood sport": ["athletics", "bullfighting", "cockfighting", "hunt", "hunting", "sport", "tauromachy"],
    "blood sugar": ["blood glucose", "glucose"],
    "blood test": ["agglutination test", "biopsy", "complement fixation test", "psa blood test"],
    "blood typing": ["diagnosing", "diagnosis"],
    "blood vessel": ["arteria", "arterial blood vessel", "artery", "capillary", "capillary vessel", "ductus arteriosus", "vas", "vasa vasorum", "vein", "vena", "venous blood vessel", "vessel"],
    "blood-and-guts": [],
    "blood-brain barrier": ["barrier"],
    "blood-filled": [],
    "blood-oxygenation level dependent functional magnetic resonance imaging": ["bold fmri", "fmri", "functional magnetic resonance imaging"],
    "bloodbath": ["battue", "bloodletting", "bloodshed", "butchery", "carnage", "mass murder", "massacre", "slaughter"],
    "bloodberry": ["blood berry", "houseplant", "rivina humilis", "rouge plant", "rougeberry"],
    "bloodcurdling": ["hair-raising", "nightmarish"],
    "bloodguilt": ["guilt", "guiltiness"],
    "bloodguilty": [],
    "bloodhound": ["hound", "hound dog", "sleuthhound"],
    "bloodily": [],
    "bloodiness": ["physical condition", "physiological condition", "physiological state"],
    "bloodleaf": ["beef plant", "beefsteak plant", "iresine herbstii", "iresine reticulata", "subshrub", "suffrutex"],
    "bloodless": [],
    "bloodlessly": [],
    "bloodletting": ["cupping", "medical aid", "medical care", "phlebotomy", "venesection"],
    "bloodlust": ["desire"],
    "bloodmobile": ["automotive vehicle", "motor vehicle"],
    "bloodroot": ["herb", "herbaceous plant", "puccoon", "redroot", "sanguinaria canadensis", "tetterwort"],
    "bloodshed": ["execution", "gore", "murder", "slaying"],
    "bloodshot": [],
    "bloodstain": ["discoloration", "discolouration", "stain"],
    "bloodstained": ["gory"],
    "bloodstock": ["breed", "stock", "strain"],
    "bloodstone": ["calcedony", "chalcedony", "heliotrope"],
    "bloodstream": ["blood", "blood stream"],
    "bloodsucking": [],
    "bloodthirsty": ["bloody-minded", "sanguinary"],
    "bloodwood tree": ["kiaat", "pterocarpus angolensis", "tree"],
    "bloodworm": ["polychaete", "polychaete worm", "polychete", "polychete worm"],
    "bloodwort": ["herb", "herbaceous plant"],
    "bloody": ["cover", "spread over"],
    "bloody mary": ["bloody shame", "cocktail", "virgin mary"],
    "bloody-minded": ["cantankerous"],
    "bloom": ["blossom", "burst forth", "develop", "effloresce", "flower"],
    "bloomer": ["flower"],
    "bloomeria": ["genus bloomeria", "liliid monocot genus"],
    "bloomers": ["drawers", "knickers", "pants", "underpants"],
    "bloomfield": ["leonard bloomfield"],
    "blooming": ["biological process", "bloom", "organic process"],
    "bloomington": [],
    "bloomsbury": [],
    "bloomsbury group": ["camp", "clique", "coterie", "ingroup", "inner circle", "pack"],
    "blossom": ["blossom forth", "blossom out", "develop", "unfold"],
    "blossoming": ["anthesis", "development", "efflorescence", "florescence", "flowering", "growing", "growth", "inflorescence", "maturation", "ontogenesis", "ontogeny"],
    "blot": ["absorb", "draw", "imbibe", "soak up", "sop up", "suck", "suck up", "take in", "take up"],
    "blotch": ["blot", "daub", "slur", "smear", "smirch", "smudge", "splodge", "splotch", "spot"],
    "blotched": ["blotchy", "splotched"],
    "blotchy": [],
    "blotted out": ["obliterate", "obliterated"],
    "blotter": ["charge sheet", "day book", "police blotter", "rap sheet", "written account", "written record"],
    "blotting paper": ["blotter", "paper"],
    "blouse": ["garibaldi", "guimpe", "middy", "middy blouse", "shirtwaist", "shirtwaister", "top"],
    "bloviate": ["orate"],
    "blow": ["bluster", "breeze", "set in", "squall", "storm", "waft"],
    "blow gas": ["blowing gas", "gas"],
    "blow off": ["come away", "come off", "detach"],
    "blow out": ["catch fire", "combust", "conflagrate", "erupt", "ignite", "take fire"],
    "blow up": ["enlarge", "increase", "magnify"],
    "blow-by-blow": [],
    "blow-dry": ["dry", "dry out"],
    "blowback": ["back-blast", "backblast", "backfire", "blowup", "detonation", "explosion"],
    "blower": ["bellows", "blow drier", "blow dryer", "device", "hair drier", "hair dryer", "hand blower"],
    "blowfish": ["fugu", "puffer", "pufferfish", "saltwater fish", "sea squab"],
    "blowfly": ["blow fly", "bluebottle", "calliphora vicina", "fly", "greenbottle", "greenbottle fly"],
    "blowgun": ["blow tube", "blowpipe", "blowtube", "tube", "tubing"],
    "blowhole": ["spiracle"],
    "blowing": ["insufflation", "processing"],
    "blown": [],
    "blown-up": ["enlarged"],
    "blowout": ["malfunction"],
    "blowsy": ["blowzy", "slatternly", "sluttish"],
    "blowtorch": ["blowlamp", "burner", "oxyacetylene torch", "torch"],
    "blowtube": ["blow tube", "blowpipe", "tube", "tubing"],
    "blowy": ["breezy", "windy"],
    "blubber": ["blubber out", "mouth", "speak", "talk", "utter", "verbalise", "verbalize"],
    "blubberer": ["crier", "weeper"],
    "blubbery": [],
    "blucher": ["full general", "g. l. von blucher", "gebhard leberecht von blucher", "general", "von blucher"],
    "bludgeon": ["coerce", "force", "hale", "pressure", "squeeze"],
    "bludgeoner": ["aggressor", "assailant", "assaulter", "attacker"],
    "blue": ["color", "colour", "discolor", "discolour"],
    "blue ash": ["ash", "ash tree", "fraxinus quadrangulata"],
    "blue baby": ["babe", "baby", "infant"],
    "blue book": ["report", "study", "written report"],
    "blue catfish": ["blue cat", "blue channel cat", "blue channel catfish", "channel cat", "channel catfish", "ictalurus punctatus"],
    "blue cheese dressing": ["dressing", "roquefort dressing", "salad dressing"],
    "blue chip": ["blue-chip stock", "common shares", "common stock", "ordinary shares"],
    "blue cohosh": ["blueberry root", "bush", "caulophyllum thalictrioides", "caulophyllum thalictroides", "papoose root", "papooseroot", "shrub", "squaw root", "squawroot"],
    "blue columbine": ["aquilege", "aquilegia", "aquilegia caerulea", "aquilegia scopulorum calcarea", "columbine"],
    "blue crab": ["crab", "crabmeat"],
    "blue curls": ["bastard pennyroyal", "black sage", "california romero", "camphorweed", "subshrub", "suffrutex", "trichostema dichotomum", "trichostema lanatum", "trichostema lanceolatum", "turpentine camphor weed", "vinegarweed", "wooly blue curls"],
    "blue daisy": ["blue marguerite", "felicia amelloides", "flower"],
    "blue elder": ["blue elderberry", "elder", "elderberry bush", "sambucus caerulea"],
    "blue false indigo": ["baptisia australis", "false indigo", "wild indigo"],
    "blue flag": ["flag", "fleur-de-lis", "iris", "iris versicolor", "sword lily"],
    "blue fleabane": ["erigeron acer", "fleabane"],
    "blue fox": ["alopex lagopus", "arctic fox", "white fox"],
    "blue goose": ["chen caerulescens", "goose", "snow goose"],
    "blue grama": ["bouteloua gracilis", "grama", "grama grass", "gramma", "gramma grass"],
    "blue gum": ["eucalypt", "eucalyptus", "eucalyptus globulus", "eucalyptus tree", "fever tree"],
    "blue jasmine": ["blue jessamine", "clematis", "clematis crispa", "curly clematis", "marsh clematis"],
    "blue jay": ["cyanocitta cristata", "jaybird", "new world jay"],
    "blue law": ["law"],
    "blue lotus": ["nymphaea stellata", "water lily"],
    "blue marlin": ["makaira nigricans", "marlin"],
    "blue mockingbird": ["melanotis caerulescens", "oscine", "oscine bird"],
    "blue mold fungus": ["downy mildew", "false mildew", "peronospora tabacina"],
    "blue moon": ["age", "long time", "years"],
    "blue mountain tea": ["goldenrod", "solidago odora", "sweet goldenrod"],
    "blue murder": ["call", "cry", "outcry", "shout", "vociferation", "yell"],
    "blue nile": [],
    "blue note": ["musical note", "note", "tone"],
    "blue orchid": ["vanda", "vanda caerulea"],
    "blue pea": ["butterfly pea", "clitoria turnatea", "vine"],
    "blue peafowl": ["bird of juno", "pavo cristatus", "peafowl"],
    "blue peter": ["code flag", "nautical signal flag"],
    "blue pike": ["blue pickerel", "blue pikeperch", "blue walleye", "dory", "jack salmon", "stizostedion vitreum", "strizostedion vitreum glaucum", "walleye", "walleyed pike"],
    "blue pimpernel": ["blue skullcap", "herb", "herbaceous plant", "mad-dog skullcap", "mad-dog weed", "scutellaria lateriflora"],
    "blue point siamese": ["siamese", "siamese cat"],
    "blue poppy": ["meconopsis betonicifolia", "poppy"],
    "blue racer": ["black racer", "blacksnake", "coluber constrictor", "coluber constrictor flaviventris"],
    "blue ribbon": ["badge", "cordon bleu"],
    "blue ribbon commission": ["blue ribbon committee", "commission", "committee"],
    "blue ridge mountains": ["blue ridge"],
    "blue sage": ["sage", "salvia", "salvia lancifolia", "salvia reflexa"],
    "blue shark": ["great blue shark", "prionace glauca", "requiem shark"],
    "blue sky": ["blue", "blue air", "sky", "wild blue yonder"],
    "blue sky law": ["law"],
    "blue star": ["amsonia tabernaemontana", "subshrub", "suffrutex"],
    "blue succory": ["catananche", "catananche caerulea", "cupid's dart"],
    "blue tit": ["parus caeruleus", "tit", "titmouse", "tomtit"],
    "blue toadflax": ["butter-and-eggs", "devil's flax", "linaria canadensis", "linaria vulgaris", "old-field toadflax", "toadflax", "wild snapdragon"],
    "blue vitriol": ["blue copperas", "blue stone", "chalcanthite", "copper sulfate", "copper sulphate", "cupric sulfate", "cupric sulphate"],
    "blue wall of silence": ["blue wall", "cover-up", "wall of silence"],
    "blue whale": ["balaenoptera musculus", "baleen whale", "sulfur bottom", "whalebone whale"],
    "blue-black": ["bluish black"],
    "blue-chip": [],
    "blue-collar": [],
    "blue-eyed": ["fair-haired", "white-haired"],
    "blue-eyed african daisy": ["arctotis stoechadifolia", "arctotis venusta", "flower"],
    "blue-eyed grass": ["iridaceous plant"],
    "blue-eyed mary": ["collinsia verna", "wild flower", "wildflower"],
    "blue-flowered": [],
    "blue-fruited": [],
    "blue-grey": ["blue-gray", "bluish-gray", "bluish-grey"],
    "blue-headed vireo": ["vireo", "vireo solitarius solitarius"],
    "blue-lilac": ["bluish-lilac"],
    "blue-purple": ["bluish-purple"],
    "blue-ribbon": ["select"],
    "blue-sky": [],
    "blue-violet": ["bluish-violet"],
    "blue-white": ["bluish-white", "cool-white"],
    "bluebeard": [],
    "blueberry": ["bilberry", "blaeberry", "blueberry bush", "bog bilberry", "bog whortleberry", "bush", "deerberry", "dryland berry", "dryland blueberry", "dwarf bilberry", "dwarf blueberry", "evergreen blueberry", "evergreen huckleberry", "farkleberry", "grouse whortleberry", "grouse-berry", "grouseberry", "high-bush blueberry", "huckleberry", "low blueberry", "low-bush blueberry", "moor berry", "mountain blue berry", "rabbit-eye blueberry", "rabbiteye", "rabbiteye blueberry", "shrub", "sparkleberry", "squaw huckleberry", "swamp blueberry", "tall bilberry", "thin-leaved bilberry", "vaccinium angustifolium", "vaccinium arboreum", "vaccinium ashei", "vaccinium caespitosum", "vaccinium corymbosum", "vaccinium myrsinites", "vaccinium ovatum", "vaccinium pallidum", "vaccinium pennsylvanicum", "vaccinium scoparium", "vaccinium stamineum", "vaccinium uliginosum alpinum", "viccinium membranaceum", "viccinium myrtillus", "whinberry", "whortleberry"],
    "blueberry pie": ["pie"],
    "blueberry yogurt": ["yoghourt", "yoghurt", "yogurt"],
    "bluebird": ["thrush"],
    "bluebonnet": ["buffalo clover", "lupin", "lupine", "lupinus subcarnosus", "texas bluebonnet"],
    "bluebottle": ["blow fly", "blowfly", "calliphora vicina"],
    "bluecoat": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "bluefin": ["bluefin tuna", "tuna", "tuna fish", "tunny"],
    "bluefish": ["saltwater fish"],
    "bluegill": ["bream", "freshwater bream", "lepomis macrochirus"],
    "bluegrass": ["blue grass", "grass", "june grass", "kentucky blue", "kentucky bluegrass", "kentucy blue grass", "poa pratensis"],
    "bluehead": ["thalassoma bifasciatum", "wrasse"],
    "bluejack oak": ["oak", "oak tree", "quercus incana", "turkey oak"],
    "bluejacket": ["coastguardsman", "man", "military man", "military personnel", "navy man", "navy seal", "sailor", "sailor boy", "seal", "serviceman", "striker", "submariner"],
    "bluepoint": ["blue point", "huitre", "oyster"],
    "blueprint": ["design", "draft", "draught", "plan"],
    "blueprint paper": ["paper"],
    "blues": ["blue devils", "depression", "megrims", "vapors", "vapours"],
    "bluestem": ["andropogon furcatus", "andropogon gerardii", "blue stem", "grass"],
    "bluestocking": ["adult female", "bas bleu", "woman"],
    "bluestone": ["sandstone"],
    "bluethroat": ["erithacus svecicus", "thrush"],
    "bluethroat pikeblenny": ["chaenopsis ocellata", "pikeblenny"],
    "bluetick": ["hound", "hound dog"],
    "bluetongue": ["catarrhal fever"],
    "blueweed": ["blue devil", "blue thistle", "echium vulgare", "herb", "herbaceous plant", "viper's bugloss"],
    "bluewing": ["anas discors", "blue-winged teal", "teal"],
    "bluff": ["bluff out", "go", "move"],
    "bluffer": ["beguiler", "cheat", "cheater", "deceiver", "four-flusher", "slicker", "trickster"],
    "bluffly": ["bluntly", "brusquely", "flat out", "roundly"],
    "bluffness": ["frankness", "outspokenness"],
    "bluing": ["blue", "blueing", "dye", "dyestuff"],
    "bluish green": ["blue green", "cyan", "green", "greenness", "teal", "viridity"],
    "blunder": ["bloomer", "blooper", "bobble", "boner", "boo-boo", "botch", "bull", "bungle", "clanger", "error", "fault", "faux pas", "flub", "fluff", "foul-up", "fuckup", "fumble", "gaffe", "gaucherie", "howler", "misstep", "mistake", "muff", "pratfall", "slip", "snafu", "solecism", "spectacle", "stumble", "trip", "trip-up"],
    "blunderbuss": ["musket"],
    "blunt": ["weaken"],
    "blunt file": ["file"],
    "blunt trauma": ["harm", "hurt", "injury", "trauma"],
    "blunted": ["dulled"],
    "bluntness": ["inconsiderateness", "inconsideration", "thoughtlessness"],
    "blur": ["alter", "change", "modify"],
    "blurred": ["clouded"],
    "blurt out": ["blunder", "blunder out", "blurt", "ejaculate", "mouth", "speak", "talk", "utter", "verbalise", "verbalize"],
    "blush": ["redden"],
    "blush wine": ["pink wine", "rose", "rose wine", "vino", "wine"],
    "blushful": ["blushing", "red-faced"],
    "blushing mushroom": ["agaric", "amanita rubescens", "blusher"],
    "bluster": ["blow"],
    "blustering": ["blusterous", "blustery"],
    "blustery": ["bullying"],
    "bo hai": ["po hai"],
    "boa": ["anaconda", "boa constrictor", "charina bottae", "constrictor", "constrictor constrictor", "eunectes murinus", "lichanura trivirgata", "python", "rosy boa", "rubber boa", "tow-headed snake"],
    "boa constrictor": ["boa", "constrictor constrictor"],
    "boann": [],
    "boar": ["swine"],
    "board": ["dwell", "inhabit", "live", "populate", "room"],
    "board foot": ["capacity measure", "capacity unit", "cubage unit", "cubature unit", "cubic content unit", "cubic measure", "displacement unit", "volume unit"],
    "board game": ["backgammon", "beano", "bingo", "checkers", "chess", "chess game", "chinese checkers", "chinese chequers", "darts", "draughts", "go", "go game", "halma", "keno", "lotto", "ludo", "mah-jongg", "mahjong", "monopoly", "noughts and crosses", "pachisi", "parchesi", "parchisi", "parlor game", "parlour game", "scrabble", "shove-ha'penny", "shove-halfpenny", "shovel board", "snakes and ladders", "tic-tac-toe", "tick-tack-toe", "ticktacktoe", "ticktacktoo", "tit-tat-toe"],
    "board measure": ["metric", "system of measurement"],
    "board meeting": ["committee meeting", "group meeting", "meeting"],
    "board member": ["fellow member", "member"],
    "board of regents": ["governing board"],
    "board of selectmen": ["board"],
    "board of trustees": ["governing board"],
    "board rule": ["measure", "measuring rod", "measuring stick"],
    "board up": ["cover"],
    "boarder": ["interloper", "intruder", "trespasser"],
    "boarding": ["boards", "construction", "flashboard", "flashboarding", "structure"],
    "boarding card": ["boarding pass", "laissez passer", "pass"],
    "boarding house": ["bed and breakfast", "bed-and-breakfast", "boardinghouse", "house"],
    "boarding school": ["private school"],
    "boardroom": ["council chamber", "divan", "diwan", "room"],
    "boards": ["theater stage", "theatre stage"],
    "boardwalk": ["duckboard", "paseo", "walk", "walkway"],
    "boarfish": ["acanthopterygian", "spiny-finned fish"],
    "boarhound": ["hound", "hound dog"],
    "boast": ["amplify", "blow", "bluster", "brag", "crow", "exaggerate", "gas", "gasconade", "gloat", "hyperbolise", "hyperbolize", "magnify", "overdraw", "overstate", "puff", "shoot a line", "swash", "tout", "triumph", "vaunt"],
    "boastful": ["big", "braggart", "bragging", "braggy", "cock-a-hoop", "crowing", "self-aggrandising", "self-aggrandizing"],
    "boastfully": ["big", "large", "vauntingly"],
    "boastfulness": ["conceit", "conceitedness", "vainglory", "vanity"],
    "boat": ["canoe", "kayak", "motorboat", "paddle", "ride", "row", "sail", "yacht"],
    "boat deck": ["upper deck"],
    "boat hook": ["hook"],
    "boat race": ["race", "sailing-race", "yacht race"],
    "boat racing": ["hydroplane racing", "racing"],
    "boat train": ["railroad train", "train"],
    "boat whistle": ["whistle"],
    "boat-race": ["race", "run"],
    "boat-shaped": [],
    "boatbill": ["boat-billed heron", "broadbill", "cochlearius cochlearius", "heron"],
    "boatbuilder": ["builder", "constructor"],
    "boater": ["chapeau", "hat", "leghorn", "lid", "panama", "panama hat", "sailor", "skimmer", "straw hat"],
    "boathouse": ["shed"],
    "boating": ["bareboating", "seafaring", "water travel", "yachting"],
    "boatload": ["carload", "large indefinite amount", "large indefinite quantity", "shipload"],
    "boatman": ["boater", "canoeist", "ferryman", "gondolier", "gondoliere", "oarsman", "paddler", "punter", "rower", "waterman", "worker"],
    "boatmanship": ["seamanship"],
    "boatswain": ["bo's'n", "bo'sun", "bos'n", "bosun", "gob", "jack", "jack-tar", "mariner", "old salt", "sea dog", "seafarer", "seaman", "tar"],
    "boatswain's chair": ["bosun's chair", "seat"],
    "boatyard": ["place", "property"],
    "bob": ["bob about", "bob around", "dabble", "move"],
    "bob around": ["bob", "bob about"],
    "bob under": ["disappear", "go away", "vanish"],
    "bobbin": ["filature", "reel", "shuttle", "spool", "winder"],
    "bobble": ["bloomer", "blooper", "blunder", "boner", "boo-boo", "botch", "bungle", "flub", "foul-up", "fuckup", "pratfall"],
    "bobby": ["officer", "police officer", "policeman"],
    "bobby pin": ["grip", "hairgrip", "hairpin"],
    "bobbysoxer": ["bobby-socker", "jeune fille", "lass", "lassie", "young girl"],
    "bobcat": ["bay lynx", "catamount", "lynx", "lynx rufus"],
    "bobolink": ["american oriole", "dolichonyx oryzivorus", "new world oriole", "oriole", "reedbird", "ricebird"],
    "bobsled": ["bob", "sled", "sleigh"],
    "bobsledding": ["sledding"],
    "bobtail": ["bob", "dock", "tail"],
    "bobwhite": ["bobwhite quail", "colinus virginianus", "northern bobwhite", "partridge", "quail"],
    "boccaccio": ["giovanni boccaccio"],
    "bocce": ["bocci", "boccie", "bowling"],
    "bocce ball": ["ball", "bocci ball", "boccie ball"],
    "bocconia": ["angiospermous tree", "bocconia frutescens", "flowering tree", "tree celandine"],
    "bock": ["bock beer", "lager", "lager beer"],
    "bodacious": [],
    "bode": ["augur", "auspicate", "bespeak", "betoken", "forecast", "foreshadow", "foreshow", "foretell", "indicate", "omen", "point", "portend", "predict", "prefigure", "presage", "prognosticate", "signal", "threaten"],
    "bodega": ["shop", "store"],
    "bodhisattva": ["boddhisatva"],
    "bodice": ["top"],
    "bodice ripper": ["romance"],
    "bodied": ["corporal", "corporate", "embodied", "incarnate"],
    "bodiless": ["bodyless"],
    "bodily": [],
    "bodily process": ["ablactation", "activity", "anastalsis", "biological process", "bodily function", "body process", "breath", "breathing", "consumption", "control", "crying", "diaphoresis", "discharge", "emission", "expectoration", "expelling", "external respiration", "festering", "healing", "hidrosis", "hypostasis", "ingestion", "insemination", "intake", "lachrymation", "lacrimation", "lactation", "maturation", "opsonisation", "opsonization", "organic process", "overactivity", "peristalsis", "perspiration", "phagocytosis", "pinocytosis", "placentation", "psilosis", "reaction", "respiration", "response", "sex", "sex activity", "sexual activity", "sexual practice", "sleeping", "sudation", "suppuration", "sweating", "tanning", "tearing", "tears", "transpiration", "uptake", "ventilation", "vermiculation", "watering", "weeping"],
    "bodily property": ["attitude", "avoirdupois", "bearing", "bipedalism", "blubber", "body-build", "build", "carriage", "dominance", "fat", "fatness", "habitus", "height", "laterality", "leanness", "physiological property", "physiology", "physique", "position", "posture", "property", "spareness", "stature", "thinness"],
    "bodkin": ["hairpin"],
    "bodo-garo": ["barish", "kamarupan"],
    "bodoni": ["gianbattista bodoni"],
    "body": ["be", "embody", "personify"],
    "body armor": ["armor", "armour", "body armour", "bulletproof vest", "cataphract", "chain armor", "chain armour", "chain mail", "coat of mail", "corselet", "corslet", "cuirass", "mail", "ring armor", "ring armour", "ring mail", "suit of armor", "suit of armour"],
    "body bag": ["bag", "human remains pouch", "personnel pouch"],
    "body count": ["count"],
    "body covering": ["cover", "covering", "cutis", "epicranium", "exoskeleton", "exuviae", "feather", "hair", "headful", "hide", "natural covering", "pelt", "plumage", "plume", "protective covering", "skin", "tegument"],
    "body english": ["motility", "motion", "move", "movement"],
    "body guard": ["protect"],
    "body hair": ["hair"],
    "body language": ["visual communication"],
    "body length": ["linear measure", "linear unit"],
    "body lotion": ["lotion"],
    "body louse": ["cootie", "louse", "pediculus corporis", "sucking louse"],
    "body mass index": ["bmi", "index", "index number", "indicant", "indicator"],
    "body odor": ["b.o.", "body odour", "fetidness", "foulness", "malodorousness", "rankness", "stinkiness"],
    "body of water": ["backwater", "bay", "briny", "channel", "crossing", "drink", "embayment", "estuary", "falls", "flowage", "ford", "gulf", "high sea", "inlet", "international waters", "lake", "main", "mid-water", "ocean", "offing", "polynya", "pool", "puddle", "recess", "sea", "seven seas", "shallow", "shoal", "sound", "stream", "territorial waters", "thing", "water", "watercourse", "waterfall", "waterway"],
    "body pad": ["protective garment"],
    "body part": ["abdomen", "adnexa", "ambulacrum", "ampulla", "anatomical structure", "annexa", "apparatus", "appendage", "area", "arse", "articulatio", "articulation", "ass", "back", "backside", "behind", "belly", "bodily structure", "body", "body structure", "bottom", "bum", "buns", "butt", "buttock", "buttocks", "can", "cannon", "cheek", "chest", "complex body part", "croup", "croupe", "derriere", "dilator", "dock", "dorsum", "energid", "external body part", "fanny", "feature", "flank", "fornix", "fundament", "gaskin", "groove", "haunch", "hind end", "hindquarters", "hip", "horseback", "joint", "keister", "lineament", "lobe", "loin", "loins", "lumbus", "mentum", "nates", "organ", "outgrowth", "part", "partition", "pectus", "piece", "posterior", "prat", "process", "protoplast", "rear", "rear end", "rectum", "region", "rudiment", "rump", "saddle", "seat", "shank", "shin", "shoulder", "small", "stern", "stomach", "structure", "stump", "system", "tail", "tail end", "thorax", "tissue", "toe", "tooshie", "torso", "trunk", "tush", "underpart", "vallecula", "venter", "withers"],
    "body plethysmograph": ["plethysmograph"],
    "body servant": ["gentleman", "gentleman's gentleman", "man", "retainer", "servant", "valet", "valet de chambre"],
    "body stocking": ["undergarment", "unmentionable"],
    "body substance": ["achromatin", "bodily fluid", "body fluid", "chromatin", "chromatin granule", "ground substance", "humor", "humour", "intercellular substance", "linin", "liquid body substance", "matrix", "solid body substance", "substance"],
    "body temperature": ["basal body temperature", "basal temperature", "blood heat", "temperature", "vital sign"],
    "body type": ["asthenic type", "athletic type", "body-build", "build", "ectomorphy", "endomorphy", "habitus", "mesomorphy", "physique", "pyknic type", "somatotype"],
    "body waste": ["barf", "bm", "dejection", "excrement", "excreta", "excretion", "excretory product", "faecal matter", "faeces", "fecal matter", "feces", "fecula", "guano", "human waste", "ordure", "pee", "piddle", "piss", "puke", "stool", "urine", "vomit", "vomitus", "waste", "waste material", "waste matter", "waste product", "water", "weewee", "wormcast"],
    "body weight": ["reporting weight", "weight"],
    "body-surf": ["glide"],
    "bodybuilder": ["individual", "mortal", "muscle builder", "muscle-builder", "musclebuilder", "muscleman", "person", "somebody", "someone", "soul"],
    "bodybuilding": ["anaerobic exercise", "exercise", "exercising", "muscle building", "musclebuilding", "physical exercise", "physical exertion", "weight gaining", "weightlift", "weightlifting", "workout"],
    "bodyguard": ["beefeater", "defender", "escort", "guardian", "outrider", "praetorian", "praetorian guard", "protector", "shielder", "yeoman", "yeoman of the guard"],
    "bodypaint": ["paint"],
    "bodywork": ["body"],
    "boehme": ["behmen", "boehm", "bohme", "jakob behmen", "jakob boehm", "jakob boehme", "jakob bohme"],
    "boehmenism": ["behmenism", "theological doctrine"],
    "boehmeria": ["dicot genus", "genus boehmeria", "magnoliopsid genus"],
    "boell": ["heinrich boell", "heinrich theodor boell"],
    "boeotia": [],
    "boeotian": [],
    "boer war": [],
    "boethius": ["anicius manlius severinus boethius"],
    "boffin": ["investigator", "research worker", "researcher"],
    "boffo": [],
    "bofors gun": ["ack-ack", "ack-ack gun", "antiaircraft", "antiaircraft gun", "flack", "flak", "pom-pom"],
    "bog": ["mire", "morass", "peat bog", "quag", "quagmire", "slack", "slough", "wetland"],
    "bog asphodel": ["american bog asphodel", "european bog asphodel", "liliaceous plant", "narthecium americanum", "narthecium ossifragum"],
    "bog aster": ["aster"],
    "bog bilberry": ["blueberry", "blueberry bush", "bog whortleberry", "moor berry", "vaccinium uliginosum alpinum"],
    "bog down": ["bog", "slow", "slow down", "slow up"],
    "bog pimpernel": ["anagallis tenella", "pimpernel"],
    "bog rein orchid": ["bog candles", "habenaria dilatata", "rein orchid", "rein orchis"],
    "bog rose": ["arethusa", "arethusa bulbosa", "dragon's mouth", "wild pink"],
    "bog rosemary": ["andromeda", "andromeda glaucophylla", "moorwort"],
    "bog soil": ["dirt", "soil"],
    "bog spavin": ["spavin"],
    "bog star": ["grass-of-parnassus", "parnassia", "parnassia palustris"],
    "bogart": ["humphrey bogart", "humphrey deforest bogart"],
    "bogartian": [],
    "bogey": ["shoot"],
    "bogeyman": ["booger", "boogeyman", "bugaboo", "bugbear", "monster"],
    "boggle": ["hesitate", "waffle", "waver"],
    "boggy": ["marshy", "miry", "mucky", "muddy", "quaggy", "sloppy", "sloughy", "soggy", "squashy", "swampy", "waterlogged"],
    "bogota": ["capital of colombia"],
    "bogus": ["bastard", "fake", "phoney", "phony"],
    "bogy": ["aircraft", "bogey", "bogie"],
    "bohemia": [],
    "bohemian": ["european"],
    "bohemian waxwing": ["bombycilla garrulus", "waxwing"],
    "bohemianism": ["behavior", "behaviour", "conduct", "doings"],
    "bohr": ["niels bohr", "niels henrik david bohr"],
    "bohr theory": ["atomic theory"],
    "bohrium": ["atomic number 107", "bh", "chemical element", "element", "element 107"],
    "boidae": ["family boidae", "reptile family"],
    "boil": ["boil over", "change state", "overboil", "turn"],
    "boil down": ["concentrate", "decoct", "decrease", "diminish", "fall", "lessen", "reduce"],
    "boil over": ["boil", "overboil"],
    "boil smut": ["corn smut", "cornsmut", "ustilago maydis"],
    "boiled": ["poached", "stewed"],
    "boiled dinner": ["dish", "new england boiled dinner"],
    "boiled egg": ["coddled egg", "dish", "hard-boiled egg", "hard-cooked egg"],
    "boiler": ["auxiliary boiler", "donkey boiler", "steam boiler", "vessel"],
    "boilerplate": ["expression", "formulation"],
    "boiling": ["decoction mashing", "decoction process", "evaporation", "heating", "vapor", "vaporisation", "vaporization", "vapour", "warming"],
    "boiling point": ["boil", "temperature"],
    "boiling water reactor": ["bwr", "water-cooled reactor"],
    "boise": ["capital of idaho"],
    "boisterous": ["knockabout"],
    "boisterousness": ["storminess"],
    "bok choy": ["bok choi", "brassica rapa chinensis", "chinese white cabbage", "crucifer", "cruciferous plant", "pak choi", "pakchoi"],
    "bokmal": ["bokmaal", "dano-norwegian", "norwegian", "riksmaal", "riksmal"],
    "bola": ["rope"],
    "bolbitis": ["fern genus", "genus bolbitis"],
    "bold": [],
    "boldface": ["impress", "print"],
    "boldly": [],
    "boldness": ["adventurousness", "audaciousness", "audacity", "brazenness", "daredevilry", "daredeviltry", "daring", "fearlessness", "hardihood", "hardiness", "shamelessness", "temerity", "venturesomeness"],
    "bole": ["dirt", "pigment", "soil"],
    "bolero": ["dance music"],
    "boletaceae": ["family boletaceae", "fungus family"],
    "bolete": ["boletellus russellii", "boletus chrysenteron", "boletus edulis", "boletus frostii", "boletus luridus", "boletus mirabilis", "boletus pallidus", "boletus pulcherrimus", "boletus pulverulentus", "boletus roxanae", "boletus subvelutipes", "boletus variipes", "boletus zelleri", "frost's bolete", "fungus", "fuscoboletinus paluster", "fuscoboletinus serotinus", "leccinum fibrillosum", "old-man-of-the-woods", "phylloporus boletinoides", "strobilomyces floccopus", "suillus albivelatus"],
    "boletellus": ["fungus genus", "genus boletellus"],
    "boletellus russellii": ["bolete"],
    "boletus": ["fungus genus", "genus boletus"],
    "boletus chrysenteron": ["bolete"],
    "boletus edulis": ["bolete"],
    "boletus luridus": ["bolete"],
    "boletus mirabilis": ["bolete"],
    "boletus pallidus": ["bolete"],
    "boletus pulcherrimus": ["bolete"],
    "boletus pulverulentus": ["bolete"],
    "boletus roxanae": ["bolete"],
    "boletus subvelutipes": ["bolete"],
    "boletus variipes": ["bolete"],
    "boletus zelleri": ["bolete"],
    "boleyn": ["anne boleyn"],
    "bolide": ["fireball", "meteor", "shooting star"],
    "bolivar": ["venezuelan monetary unit"],
    "bolivia": ["republic of bolivia"],
    "bolivian": ["south american"],
    "bolivian monetary unit": ["boliviano", "monetary unit"],
    "boliviano": ["bolivian monetary unit"],
    "boll": ["capsule"],
    "boll weevil": ["anthonomus grandis", "weevil"],
    "bollard": ["bitt", "post", "riding bitt"],
    "bollock": ["block", "bullock block", "pulley", "pulley block", "pulley-block"],
    "bollworm": ["caterpillar", "corn earworm", "cotton bollworm", "gelechia gossypiella", "heliothis zia", "pink bollworm", "tobacco budworm", "tomato fruitworm", "vetchworm"],
    "bollywood": ["film industry", "movie industry"],
    "bolo": ["bolo knife", "knife"],
    "bolo tie": ["bola", "bola tie", "bolo", "necktie", "tie"],
    "bologna": [],
    "bolognese pasta sauce": ["pasta sauce", "spaghetti sauce"],
    "bologram": ["bolograph", "recording"],
    "bolographic": [],
    "bolometer": ["measuring device", "measuring instrument", "measuring system"],
    "bolometric": [],
    "bolshevik": ["bolshevist", "commie", "communist"],
    "bolshevism": ["collectivism", "communism", "revisionism", "sovietism"],
    "bolshy": ["stroppy"],
    "bolster": ["prop", "prop up", "shore", "shore up"],
    "bolt": ["move"],
    "bolt cutter": ["cutlery", "cutter", "cutting tool"],
    "bolt-hole": ["hole"],
    "bolti": ["cichlid", "cichlid fish", "tilapia nilotica"],
    "boltonia": ["asterid dicot genus", "genus boltonia"],
    "boltzmann": ["ludwig boltzmann"],
    "boltzmann's constant": ["constant"],
    "bolus": ["ball", "globe", "orb"],
    "bolzano": [],
    "bomarea": ["genus bomarea", "liliid monocot genus"],
    "bomb": ["a-bomb", "aerosol bomb", "anti-personnel bomb", "antipersonnel bomb", "arms", "atom bomb", "atomic bomb", "balloon bomb", "bomblet", "bombshell", "briefcase bomb", "car bomb", "chemical bomb", "cluster bomb", "cluster bomblet", "cruise missile", "daisy cutter", "depth bomb", "depth charge", "dumb bomb", "e-bomb", "explosive device", "firebomb", "fission bomb", "fragmentation bomb", "fuel-air bomb", "fugo", "fusion bomb", "gas bomb", "gas shell", "general-purpose bomb", "gp bomb", "gravity bomb", "grenade", "h-bomb", "hydrogen bomb", "implements of war", "incendiary", "incendiary bomb", "infernal machine", "letter bomb", "megaton bomb", "microwave bomb", "munition", "package bomb", "parcel bomb", "penetration bomb", "pipe bomb", "plastic bomb", "plutonium bomb", "remote-control bomb", "smart bomb", "smoke bomb", "smoke grenade", "stench bomb", "stink bomb", "thermobaric bomb", "thermonuclear bomb", "time bomb", "vacuum bomb", "volume-detonation bomb", "weaponry", "weapons system"],
    "bomb blast": ["atomic explosion", "blast", "nuclear explosion"],
    "bomb calorimeter": ["bomb", "calorimeter"],
    "bomb out": ["bomb", "bombard"],
    "bomb rack": ["carrier"],
    "bomb shelter": ["air-raid shelter", "bombproof", "chamber"],
    "bomb site": ["land site", "site"],
    "bomb up": ["lade", "laden", "load", "load up"],
    "bombacaceae": ["dilleniid dicot family", "family bombacaceae"],
    "bombard": ["assail", "atom-bomb", "atomise", "atomize", "attack", "blast", "bomb", "bomb out", "carpet bomb", "dive-bomb", "firebomb", "glide-bomb", "hydrogen-bomb", "letter bomb", "nuke", "pattern-bomb", "shell", "skip-bomb", "zap"],
    "bombardier": ["enlisted officer", "noncom", "noncommissioned officer"],
    "bombardier beetle": ["carabid beetle", "ground beetle"],
    "bombardment": ["radiation"],
    "bombardon": ["bass", "bombard", "shawm"],
    "bombast": ["blah", "claptrap", "fustian", "grandiloquence", "grandiosity", "magniloquence", "ornateness", "rant", "rhetoric"],
    "bombastic": ["declamatory", "large", "orotund", "tumid", "turgid"],
    "bombastically": ["grandiosely"],
    "bombax": ["dilleniid dicot genus", "genus bombax"],
    "bombazine": ["cloth", "fabric", "material", "textile"],
    "bomber": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "bomber crew": ["air crew", "aircrew", "bomber aircrew"],
    "bomber jacket": ["jacket"],
    "bombie": ["bomblet", "cluster bomblet"],
    "bombina": ["amphibian genus", "genus bombina"],
    "bombing": ["sabotage", "suicide bombing"],
    "bombing run": ["bombardment", "bombing", "dive-bombing", "loft bombing", "toss bombing"],
    "bomblet": ["bomb", "bombie", "cluster bomblet"],
    "bombproof": ["proof"],
    "bombshell": ["entertainer"],
    "bombsight": ["sights"],
    "bombus": ["arthropod genus", "genus bombus"],
    "bombycid": ["bombycid moth", "bombyx mori", "domestic silkworm moth", "domesticated silkworm moth", "moth", "silkworm moth"],
    "bombycidae": ["arthropod family", "family bombycidae"],
    "bombycilla": ["bird genus", "genus bombycilla"],
    "bombycillidae": ["bird family", "family bombycillidae"],
    "bombyliidae": ["arthropod family", "family bombyliidae"],
    "bombyx": ["arthropod genus", "genus bombyx"],
    "bon mot": ["humor", "humour", "mot", "wit", "witticism", "wittiness"],
    "bon voyage": ["farewell", "send-off", "word of farewell"],
    "bona fide": [],
    "bonaire": [],
    "bonanza": ["mineral vein", "vein"],
    "bonasa": ["bird genus", "genus bonasa"],
    "bonbon": ["candy", "confect"],
    "bond": ["mortgage"],
    "bond issue": ["bond", "bond certificate"],
    "bond rating": ["evaluation", "rating", "valuation"],
    "bond servant": ["bondmaid", "bondman", "bondsman", "bondswoman", "bondwoman", "slave", "thrall"],
    "bond trading": ["bond-trading activity", "trading"],
    "bondable": [],
    "bondage": ["subjection", "subjugation"],
    "bonded labor": ["bondage", "slavery", "thraldom", "thrall", "thralldom"],
    "bonderize": ["bonderise", "coat", "surface"],
    "bondholder": ["holder", "investor"],
    "bonding": ["female bonding", "male bonding", "maternal-infant bonding", "personal relation", "personal relationship"],
    "bondman": ["bond servant", "bondsman"],
    "bondsman": ["benefactor", "bondswoman", "helper"],
    "bonduc": ["bonduc tree", "caesalpinia bonduc", "caesalpinia bonducella", "tree"],
    "bonduc nut": ["nicker nut", "nicker seed", "seed"],
    "bondwoman": ["bond servant", "bondmaid", "bondswoman"],
    "bone": ["debone", "remove", "take", "take away", "withdraw"],
    "bone age": ["age"],
    "bone ash": ["ash"],
    "bone black": ["animal black", "animal charcoal", "bone char", "char"],
    "bone cell": ["megakaryocyte", "osteoclast", "osteocyte", "somatic cell", "vegetative cell"],
    "bone china": ["china"],
    "bone fat": ["animal fat"],
    "bone of contention": ["subject", "theme", "topic"],
    "bone oil": ["animal oil"],
    "bone spavin": ["spavin"],
    "bone-ash cup": ["cupel", "refractory pot", "vessel"],
    "bone-covered": [],
    "bone-dry": ["bone dry"],
    "bone-headed dinosaur": ["ornithischian", "ornithischian dinosaur", "pachycephalosaur", "pachycephalosaurus"],
    "bone-idle": ["bone-lazy"],
    "boned": ["deboned"],
    "bonefish": ["albula vulpes", "malacopterygian", "soft-finned fish"],
    "boneless": [],
    "bonelike": [],
    "bonemeal": ["organic", "organic fertiliser", "organic fertilizer"],
    "bones": ["castanets", "clappers", "finger cymbals", "percussion instrument", "percussive instrument"],
    "boneset": ["agueweed", "eupatorium perfoliatum", "herb", "herbaceous plant", "thoroughwort"],
    "bonesetter": ["caregiver", "health care provider", "health professional", "pcp", "primary care provider"],
    "boneshaker": ["wheeled vehicle"],
    "bonete": [],
    "bonfire": ["balefire", "fire"],
    "bonfire night": ["guy fawkes night", "november 5"],
    "bong": ["echo", "resound", "reverberate", "ring"],
    "bongo": ["bongo drum", "drum", "membranophone", "tympan"],
    "bonheur": ["happiness"],
    "bonhoeffer": ["dietrich bonhoeffer"],
    "boniface": ["apostle of germany", "saint boniface", "st. boniface", "winfred", "wynfrith"],
    "boniface viii": ["benedetto caetani"],
    "bonito": ["tuna", "tuna fish", "tunny"],
    "bonito shark": ["blue pointed", "isurus glaucus", "mako", "mako shark"],
    "bonn": [],
    "bonnet": ["hat"],
    "bonnet macaque": ["bonnet monkey", "capped macaque", "crown monkey", "macaca radiata", "macaque"],
    "bonney": ["billie the kid", "william h. bonney"],
    "bonnily": [],
    "bonny": ["bonnie", "comely", "fair", "sightly"],
    "bonsai": ["ming tree", "tree"],
    "bontemps": ["arna wendell bontemps"],
    "bonus": ["dividend", "incentive", "payment", "premium", "sales incentive"],
    "bony": ["cadaverous", "emaciated", "gaunt", "haggard", "pinched", "skeletal", "wasted"],
    "bony fish": ["crossopterygian", "fish", "lobe-finned fish", "lobefin", "lungfish", "teleost", "teleost fish", "teleostan"],
    "bony labyrinth": ["anatomical structure", "bodily structure", "body structure", "complex body part", "osseous labyrinth", "structure"],
    "bony-plated": [],
    "bonyness": ["boniness", "emaciation", "gauntness", "leanness", "maceration", "spareness", "thinness"],
    "bonzer": [],
    "boo": ["condemn", "hiss"],
    "booboisie": ["class", "social class", "socio-economic class", "stratum"],
    "booby": ["gannet"],
    "booby prize": ["prize", "trophy", "wooden spoon"],
    "boodle": ["bread", "cabbage", "clams", "dinero", "dough", "gelt", "kale", "lettuce", "lolly", "loot", "lucre", "money", "moolah", "pelf", "scratch", "shekels", "simoleons", "sugar", "wampum"],
    "booger": ["mucous secretion", "mucus"],
    "boogie": ["dance", "trip the light fantastic", "trip the light fantastic toe"],
    "boojum tree": ["candlewood", "cirio", "fouquieria columnaris", "idria columnaris"],
    "book": ["register"],
    "book agent": ["salesman"],
    "book bag": ["bag"],
    "book fair": ["bookfair", "fair"],
    "book jacket": ["dust cover", "dust jacket", "dust wrapper", "jacket"],
    "book lung": ["respiratory organ"],
    "book of common prayer": [],
    "book of knowledge": ["cyclopaedia", "cyclopedia", "encyclopaedia", "encyclopedia"],
    "book of mormon": [],
    "book review": ["critical review", "critique", "review", "review article"],
    "book scorpion": ["chelifer cancroides", "false scorpion", "pseudoscorpion"],
    "book token": ["coupon", "voucher"],
    "book up": ["reserve"],
    "book value": ["capital stock", "value"],
    "bookable": [],
    "bookbinder": ["artificer", "artisan", "craftsman", "journeyman"],
    "bookbindery": ["shop", "workshop"],
    "bookbinding": ["handicraft"],
    "bookcase": ["article of furniture", "furniture", "piece of furniture"],
    "bookclub": ["club", "gild", "guild", "lodge", "order", "social club", "society"],
    "bookdealer": ["book seller", "merchandiser", "merchant"],
    "booked": ["engaged", "set-aside"],
    "bookend": ["support"],
    "booker": ["agent", "booking agent", "impresario", "promoter", "showman"],
    "booking": ["employment", "engagement", "reservation"],
    "bookish": ["studious"],
    "bookishness": ["studiousness"],
    "bookkeeper": ["accountant", "comptroller", "controller"],
    "bookkeeping": ["accountancy", "accounting", "clerking", "double entry", "double-entry bookkeeping", "single entry", "single-entry bookkeeping"],
    "booklet": ["blue book", "book", "brochure", "folder", "leaflet", "pamphlet", "ticket book"],
    "booklouse": ["book louse", "common booklouse", "deathwatch", "liposcelis divinatorius", "psocopterous insect", "trogium pulsatorium"],
    "bookmaker": ["maker", "shaper"],
    "bookmark": ["bookmarker", "marker"],
    "bookmobile": ["van"],
    "bookplate": ["ex libris", "gummed label", "paster", "sticker"],
    "bookseller": ["owner", "proprietor"],
    "bookshelf": ["shelf"],
    "bookshop": ["bookstall", "bookstore", "shop", "store"],
    "bookworm": ["reader"],
    "boole": ["george boole"],
    "boolean": [],
    "boolean logic": ["boolean algebra", "formal logic", "mathematical logic", "symbolic logic"],
    "boolean operation": ["binary arithmetic operation", "binary operation", "operation"],
    "boom": ["din", "go", "sound"],
    "boom town": ["town"],
    "boomerang": ["return"],
    "booming": ["flourishing", "palmy", "prospering", "prosperous", "roaring", "thriving"],
    "boon": [],
    "boondoggle": ["work"],
    "boone": ["daniel boone"],
    "boorish": ["loutish", "neandertal", "neanderthal", "oafish", "swinish"],
    "boorishly": [],
    "boorishness": ["discourtesy", "rudeness"],
    "boost": ["thrust"],
    "boost up": ["push up"],
    "booster": ["lifter", "shoplifter", "stealer", "thief"],
    "boot": ["kick"],
    "boot camp": ["bivouac", "camp", "cantonment", "encampment"],
    "boot-shaped": [],
    "bootblack": ["shoeblack", "unskilled person"],
    "booted": [],
    "bootee": ["bootie", "carpet slipper", "slipper"],
    "bootes": [],
    "booth": ["john wilkes booth"],
    "boothose": ["stocking"],
    "bootjack": ["device"],
    "bootlace": ["lace", "lacing"],
    "bootleg": ["sell"],
    "bootlegger": ["criminal", "crook", "felon", "malefactor", "moonshiner", "outlaw"],
    "bootlegging": ["marketing", "merchandising", "selling"],
    "bootless": ["fruitless", "futile", "sleeveless", "vain"],
    "bootlicking": ["fawning", "obsequious", "sycophantic", "toadyish"],
    "bootmaker": ["boot maker", "cobbler", "shoemaker"],
    "bootstrap": ["aid", "assist", "help"],
    "boott's goldenrod": ["goldenrod"],
    "bop": ["bebop", "dance", "trip the light fantastic", "trip the light fantastic toe"],
    "borage": ["borago officinalis", "herb", "herbaceous plant", "tailwort"],
    "boraginaceae": ["borage family", "family boraginaceae", "plant family"],
    "borago": ["genus borago", "plant genus"],
    "borassus": ["genus borassus", "liliopsid genus", "monocot genus"],
    "borate": ["salt"],
    "borated": [],
    "borax": ["mineral"],
    "bordeaux": [],
    "bordeaux mixture": ["antifungal", "antifungal agent", "antimycotic", "antimycotic agent", "fungicide"],
    "bordelaise": ["sauce"],
    "border": ["edge", "furnish", "provide", "render", "supply"],
    "border collie": ["sheep dog", "sheepdog", "shepherd dog"],
    "border on": ["approach", "approximate", "come close", "converge"],
    "border patrol": ["patrol"],
    "border patrolman": ["law officer", "lawman", "peace officer"],
    "border terrier": ["terrier"],
    "bordered": [],
    "borderer": ["denizen", "dweller", "habitant", "indweller", "inhabitant"],
    "borderland": ["border district", "district", "dominion", "march", "marchland", "territorial dominion", "territory"],
    "borderline": ["marginal"],
    "borderline intelligence": ["i.q.", "intelligence quotient", "iq"],
    "borderline schizophrenia": ["dementia praecox", "latent schizophrenia", "schizophrenia", "schizophrenic disorder", "schizophrenic psychosis"],
    "bore": ["tire"],
    "bore bit": ["borer", "cross bit", "drill", "rock drill", "star drill", "stone drill", "straight flute", "straight-fluted drill"],
    "boreal": [],
    "boreas": [],
    "bored": ["world-weary"],
    "boredom": ["blahs", "dissatisfaction", "ennui", "fatigue", "tedium"],
    "borges": ["jorge borges", "jorge luis borges"],
    "borgia": ["duchess of ferrara", "lucrezia borgia"],
    "boric": ["boracic"],
    "boric acid": ["acid", "orthoboric acid"],
    "boring": ["drilling", "oil production", "production"],
    "boringly": ["tediously", "tiresomely"],
    "boringness": ["dreariness", "dullness", "insipidity", "insipidness"],
    "born": ["max born"],
    "born-again": ["converted", "reborn"],
    "born-again christian": ["christian"],
    "bornean": ["bruneian", "malaysian"],
    "borneo": ["kalimantan"],
    "bornite": ["mineral", "peacock ore"],
    "borodin": ["aleksandr borodin", "aleksandr porfirevich borodin"],
    "borodino": [],
    "boron": ["atomic number 5", "b", "chemical element", "element"],
    "boron chamber": ["ionization chamber", "ionization tube"],
    "boron counter tube": ["proportional counter", "proportional counter tube"],
    "boron trifluoride": ["fluoride"],
    "boronic": [],
    "borosilicate": ["salt"],
    "borough": ["administrative district", "administrative division", "territorial division"],
    "borough english": ["heritage", "inheritance"],
    "borrelia": ["spirochaete", "spirochete"],
    "borrelia burgdorferi": ["lime disease spirochete", "spirochaete", "spirochete"],
    "borrow": ["acquire", "get"],
    "borrow pit": ["cavity", "pit"],
    "borrower": ["freeloader", "receiver", "recipient"],
    "borrowing": ["dealing", "dealings", "pawn", "transaction"],
    "borrowing cost": ["cost"],
    "borsch": ["borscht", "borsh", "borshch", "borsht", "bortsch", "soup"],
    "borscht circuit": ["borscht belt", "borsht belt", "borsht circuit", "playground", "resort area", "vacation spot"],
    "borstal": ["reform school", "reformatory", "training school"],
    "borzoi": ["russian wolfhound", "wolfhound"],
    "bos": ["genus bos", "mammal genus"],
    "bosc": ["pear"],
    "bosch": ["hieronymus bosch", "jerom bos"],
    "bose": ["satyendra n. bose", "satyendra nath bose"],
    "bose-einstein statistics": ["law", "law of nature"],
    "boselaphus": ["genus boselaphus", "mammal genus"],
    "bosk": ["forest", "wood", "woods"],
    "boskop man": ["homo sapiens"],
    "boskopoid": [],
    "bosky": ["brushy"],
    "bosnia": [],
    "bosnia and herzegovina": ["bosna i hercegovina", "bosnia", "bosnia-herzegovina", "republic of bosnia and herzegovina"],
    "bosnian": [],
    "bosom": ["conceal", "hide"],
    "bosomed": [],
    "bosomy": ["busty", "buxom", "curvaceous", "curvy", "full-bosomed", "sonsie", "sonsy", "stacked", "voluptuous", "well-endowed"],
    "boson": ["gauge boson", "meson", "mesotron", "particle", "subatomic particle"],
    "bosporus": [],
    "bosporus bridge": [],
    "boss": ["drug baron", "drug lord", "leader"],
    "boss-eyed": [],
    "bossism": ["domination"],
    "boston": ["bean town", "beantown", "capital of massachusetts", "hub of the universe"],
    "boston baked beans": ["dish"],
    "boston bull": ["boston terrier", "terrier"],
    "boston cream pie": ["cake"],
    "boston fern": ["nephrolepis exaltata", "nephrolepis exaltata bostoniensis", "sword fern"],
    "boston harbor": [],
    "boston ivy": ["japanese ivy", "parthenocissus tricuspidata", "vine"],
    "boston lettuce": ["butterhead lettuce"],
    "boston rocker": ["rocker", "rocking chair"],
    "boston tea party": [],
    "bostonian": ["american"],
    "boswell": ["james boswell"],
    "boswellia": ["genus boswellia", "rosid dicot genus"],
    "boswellia carteri": ["incense tree"],
    "bosworth field": [],
    "bot": ["larva"],
    "bota": ["wine bottle"],
    "botanic": ["botanical"],
    "botanical": ["drug"],
    "botanist": ["biologist", "life scientist", "mycologist", "phytologist", "plant scientist", "pomologist", "propagator"],
    "botanize": ["analyse", "analyze", "botanise", "break down", "dissect", "take apart"],
    "botany": ["algology", "biological science", "biology", "mycology", "palaeobotany", "paleobotany", "phycology", "phytology", "pomology", "pteridology"],
    "botaurus": ["bird genus", "genus botaurus"],
    "botch": ["ball up", "blow", "bobble", "bodge", "bollix", "bollix up", "bollocks", "bollocks up", "botch up", "bumble", "bungle", "fail", "flub", "fluff", "foul up", "fuck up", "fumble", "go wrong", "louse up", "mess up", "miscarry", "mishandle", "muck up", "muff", "screw up", "spoil"],
    "botchy": ["butcherly", "unskillful"],
    "botfly": ["dermatobia hominis", "gadfly", "gasterophilus intestinalis", "horse botfly", "human botfly", "oestrus ovis", "sheep botfly", "sheep gadfly"],
    "both": [],
    "bother": ["intrude", "irrupt"],
    "bothered": ["daunted", "fazed"],
    "bothidae": ["family bothidae", "fish family"],
    "bothrops": ["genus bothrops", "reptile genus"],
    "botonee": ["botonnee"],
    "botrychium": ["fern genus", "genus botrychium"],
    "botryoid": ["botryoidal", "boytrose"],
    "botswana": ["republic of botswana"],
    "botswana monetary unit": ["monetary unit", "pula", "thebe"],
    "botswanan": []
}
