synonyms = {
    "injured": [],
    "injuriously": [],
    "injury": ["birth trauma", "bite", "blast trauma", "bleeding", "blunt trauma", "brain damage", "break", "bruise", "bump", "burn", "contusion", "cryopathy", "dislocation", "electric shock", "fracture", "frostbite", "haemorrhage", "harm", "health problem", "hemorrhage", "hurt", "ill health", "insect bite", "intravasation", "lesion", "penetrating injury", "penetrating trauma", "pinch", "pull", "rupture", "sting", "strain", "trauma", "twist", "unhealthiness", "wale", "weal", "welt", "wheal", "whiplash", "whiplash injury", "wound", "wrench"],
    "injustice": ["inequity", "unfairness", "unjustness", "unrighteousness", "wrong", "wrongfulness"],
    "ink": ["sign"],
    "ink bottle": ["bottle", "inkpot"],
    "ink cartridge": ["cartridge"],
    "ink eraser": ["eraser"],
    "ink-black": ["inky", "inky-black"],
    "ink-jet": [],
    "ink-jet printer": ["bubble jet printer", "bubble-jet printer", "bubblejet", "dot matrix printer", "dot printer", "matrix printer"],
    "inkberry": ["evergreen winterberry", "gall-berry", "gallberry", "holly", "ilex glabra"],
    "inkblot": ["blot", "daub", "slur", "smear", "smirch", "smudge", "spot"],
    "inkle": ["tape"],
    "inkling": ["glimmer", "glimmering", "intimation", "suggestion"],
    "inkstand": ["tray"],
    "inkwell": ["inkstand", "well"],
    "inky cap": ["agaric", "coprinus atramentarius", "inky-cap mushroom"],
    "inlaid": [],
    "inland": [],
    "inland bill": ["bill of exchange", "draft", "order of payment"],
    "inland passage": ["inside passage"],
    "inland revenue": ["administrative body", "administrative unit", "ir"],
    "inland sea": [],
    "inlay": ["adorn", "beautify", "damascene", "decorate", "embellish", "grace", "hatch", "ornament"],
    "inlet": ["body of water", "cove", "fiord", "fjord", "loch", "recess", "water"],
    "inlet manifold": ["manifold"],
    "inmarry": ["conjoin", "espouse", "get hitched with", "get married", "hook up with", "marry", "wed"],
    "inmate": ["occupant", "occupier", "resident"],
    "inmost": ["innermost"],
    "innately": [],
    "innateness": ["changelessness", "unchangeability", "unchangeableness", "unchangingness"],
    "inner": [],
    "inner city": ["center", "centre", "eye", "heart", "middle"],
    "inner ear": ["internal ear", "labyrinth", "receptor", "sense organ", "sensory receptor"],
    "inner hebrides": [],
    "inner light": ["christ within", "ethical motive", "ethics", "light", "light within", "morality", "morals"],
    "inner mongolia": ["nei monggol"],
    "inner resource": ["resource"],
    "inner tube": ["tube", "tubing"],
    "innervate": ["furnish", "provide", "render", "supply"],
    "innervation": ["dispersion", "distribution"],
    "inning": ["division", "frame", "part", "section"],
    "innings": ["follow-on", "play", "turn"],
    "innocence": ["blamelessness", "clear", "condition", "guiltlessness", "inculpability", "inculpableness", "status"],
    "innocency": ["artlessness", "ingenuousness", "innocence", "naturalness"],
    "innocent": ["boy scout", "dear", "individual", "inexperienced person", "lamb", "mortal", "naif", "person", "somebody", "someone", "soul", "virgin"],
    "innocent iii": ["lotario di segni"],
    "innocent viii": ["giovanni battista cibo"],
    "innocent xi": ["benedetto odescalchi"],
    "innocent xii": ["antonio pignatelli"],
    "innocently": [],
    "innocuous": ["unobjectionable"],
    "innominate artery": ["arteria", "arterial blood vessel", "artery"],
    "innovative": ["groundbreaking", "innovational"],
    "innovativeness": ["originality"],
    "innoxious": [],
    "innsbruck": [],
    "innumerableness": ["countlessness", "figure", "number"],
    "innumerate": [],
    "inoculant": ["inoculum", "substance"],
    "inoculate": ["inform"],
    "inoculating": ["protection", "ring vaccination", "vaccinating", "variolation", "variolization"],
    "inoculation": ["immunisation", "immunization", "vaccination"],
    "inoculator": ["medical man", "medical practitioner", "vaccinator"],
    "inoffensive": ["unoffending"],
    "inoffensively": [],
    "inoperable": [],
    "inoperative": [],
    "inopportune": [],
    "inopportunely": ["malapropos"],
    "inopportuneness": ["inconvenience", "untimeliness"],
    "inordinately": ["extraordinarily"],
    "inorganic": [],
    "inorganic chemistry": ["chemical science", "chemistry"],
    "inorganic compound": ["carbide", "chemical compound", "compound"],
    "inorganically": [],
    "inosine": ["nucleoside"],
    "inositol": ["b", "b complex", "b vitamin", "b-complex vitamin", "vitamin b", "vitamin b complex"],
    "inpatient": ["inmate", "patient"],
    "inpouring": ["inflow", "influx", "inpour", "inrush"],
    "input": ["enter", "infix", "insert", "introduce"],
    "input file": ["computer file", "input data"],
    "input program": ["service program", "utility", "utility program"],
    "input routine": ["service routine", "utility routine"],
    "input signal": ["input", "sign", "signal", "signaling"],
    "inquest": ["enquiry", "inquiry"],
    "inquirer": ["asker", "canvasser", "cross-examiner", "cross-questioner", "enquirer", "examiner", "headcounter", "inquisitor", "interrogator", "interviewer", "poll taker", "pollster", "querier", "questioner", "quizzer", "speaker", "talker", "tester", "utterer", "verbaliser", "verbalizer"],
    "inquiring": [],
    "inquiringly": ["enquiringly"],
    "inquiry": ["canvass", "empirical research", "enquiry", "experiment", "experimentation", "heraldry", "investigation", "nature study", "opinion poll", "poll", "probe", "problem solving", "public opinion poll", "research"],
    "inquiry agent": ["operative", "pi", "private detective", "private eye", "private investigator", "shamus", "sherlock"],
    "inquisition": ["court", "judicature", "tribunal"],
    "inquisitive": [],
    "inquisitor": ["functionary", "grand inquisitor", "official"],
    "inquisitorial": [],
    "inquisitory": ["probing", "searching"],
    "inroad": ["invasion"],
    "insalubrious": ["unhealthful", "unhealthy"],
    "insalubrity": ["insalubriousness", "unhealthfulness"],
    "insane": [],
    "insanely": ["crazily", "dementedly", "madly"],
    "insanity": ["craziness", "daftness", "dementedness", "dementia", "derangement", "flakiness", "insaneness", "irrationality", "lunacy", "madness", "mental disease", "mental illness", "mental unsoundness", "psychopathy", "unbalance", "unreason"],
    "insanity plea": ["plea", "plea of insanity"],
    "insatiably": ["unsatiably"],
    "insatiate": ["insatiable", "unsatiable"],
    "inscribe": ["delineate", "describe", "draw", "line", "trace"],
    "inscribed": [],
    "inscription": ["epigraph", "epitaph", "lettering", "piece of writing", "superscription", "writing", "written material"],
    "inscriptive": [],
    "inscriptively": [],
    "inscrutability": ["incomprehensibility"],
    "inscrutably": [],
    "insect": ["arthropod", "beetle", "bird louse", "biting louse", "bug", "collembolan", "defoliator", "dictyopterous insect", "dipteran", "dipteron", "dipterous insect", "earwig", "ephemeral", "ephemerid", "ephemeron", "ephemeropteran", "flea", "gallfly", "hemipteran", "hemipteron", "hemipterous insect", "heteropterous insect", "holometabola", "homopteran", "homopterous insect", "hymenopter", "hymenopteran", "hymenopteron", "hymenopterous insect", "imago", "leaf miner", "leaf-miner", "lepidopteran", "lepidopteron", "lepidopterous insect", "louse", "mecopteran", "metabola", "neuropteran", "neuropteron", "neuropterous insect", "odonate", "orthopteran", "orthopteron", "orthopterous insect", "phasmid", "phasmid insect", "plecopteran", "pollinator", "proturan", "psocopterous insect", "pupa", "queen", "social insect", "springtail", "stone fly", "stonefly", "sucking louse", "telsontail", "termite", "thysanopter", "thysanopteron", "thysanopterous insect", "thysanuran insect", "thysanuron", "trichopteran", "trichopteron", "trichopterous insect", "two-winged insects", "web spinner", "white ant", "worker"],
    "insecta": ["class", "class hexapoda", "class insecta", "hexapoda"],
    "insectan": [],
    "insecticidal": [],
    "insecticidally": [],
    "insecticide": ["ddt", "dichlorodiphenyltrichloroethane", "insect powder", "larvacide", "lead arsenate", "lindane", "malathion", "organophosphate", "parathion", "paris green", "pesticide", "pyrethrum", "rotenone"],
    "insectifuge": ["insect repellant", "insect repellent", "repellant", "repellent"],
    "insectivora": ["animal order", "order insectivora"],
    "insectivore": ["erinaceus europaeus", "erinaceus europeaeus", "eutherian", "eutherian mammal", "hedgehog", "mole", "otter shrew", "placental", "placental mammal", "potamogale", "potamogale velox", "shrew", "shrewmouse", "tendrac", "tenrec"],
    "insectivorous": [],
    "insecure": ["unsafe"],
    "insecurely": [],
    "insecureness": ["insecurity"],
    "insecurity": ["danger", "insecureness"],
    "inseminate": ["seed", "sow", "sow in"],
    "insemination": ["planting"],
    "insensately": [],
    "insensibility": ["unconsciousness"],
    "insensible": ["unaffected"],
    "insensitive": [],
    "insensitively": [],
    "insensitivity": ["callosity", "callousness", "crassitude", "crassness", "hardness", "inability", "insensibility", "insensitiveness", "tin ear", "unfeelingness", "unfitness", "unkindness", "unperceptiveness"],
    "insentience": ["inanimateness", "lifelessness"],
    "insentient": ["insensate"],
    "inseparable": [],
    "inseparably": [],
    "insert": ["attach", "cannulate", "cannulise", "cannulize", "canulate", "connect", "embed", "engraft", "enter", "graft", "imbed", "implant", "infix", "input", "instil", "instill", "introduce", "intubate", "penetrate", "plant", "plug in", "plug into", "sandwich", "transplant"],
    "insertion": ["blood transfusion", "cannulation", "cannulisation", "cannulization", "canulation", "canulisation", "canulization", "enclosing", "enclosure", "envelopment", "inclosure", "injection", "instillation", "instillment", "instilment", "introduction", "intromission", "intubation", "movement", "perfusion", "transfusion"],
    "insertional mutagenesis": ["mutagenesis"],
    "insessores": ["animal order", "order insessores", "percher", "perching bird"],
    "inset": ["enclose", "inclose", "insert", "introduce", "put in", "stick in"],
    "inshore": [],
    "inside": ["interior", "midland", "midst", "part", "penetralia", "region", "thick"],
    "inside caliper": ["caliper", "calliper"],
    "inside clinch": ["clench", "clinch"],
    "inside job": ["evildoing", "transgression"],
    "inside loop": ["loop", "loop-the-loop"],
    "inside out": [],
    "inside track": ["course", "path", "track"],
    "insider": ["business executive", "corporate executive"],
    "insider information": ["info", "information"],
    "insider trading": ["trading"],
    "insidious": [],
    "insidiously": ["perniciously"],
    "insidiousness": ["harmfulness", "injuriousness"],
    "insight": ["perceptiveness", "perceptivity", "sensibility"],
    "insightful": [],
    "insightfulness": ["acumen", "astuteness", "perspicaciousness", "perspicacity", "shrewdness"],
    "insignia": ["badge", "caduceus", "cordon", "hash mark", "hashmark", "insignia of rank", "service stripe", "shoulder flash", "wings"],
    "insignia of rank": ["insignia"],
    "insignificance": ["inconsequence", "meaninglessness", "unimportance"],
    "insignificant": ["unimportant"],
    "insignificantly": [],
    "insincere": [],
    "insincerely": [],
    "insincerity": ["falseness", "hollowness", "hypocrisy", "untruthfulness"],
    "insinuate": ["bring in", "introduce"],
    "insinuatingly": [],
    "insinuation": ["implication", "innuendo"],
    "insipid": ["jejune"],
    "insipidly": [],
    "insist": ["assert", "asseverate", "hold firm", "maintain", "stand fast", "stand firm", "stand pat", "take a firm stand"],
    "insistence": ["demand", "insisting", "purism"],
    "insistent": ["repetitive"],
    "insistently": [],
    "insofar": ["in so far", "so far", "to that degree", "to that extent"],
    "insolation": ["solar radiation"],
    "insole": ["innersole", "sole"],
    "insolence": ["discourtesy", "offence", "offense", "offensive activity"],
    "insolently": [],
    "insolubility": ["quality"],
    "insoluble": [],
    "insolvable": ["unresolvable", "unsoluble", "unsolvable"],
    "insolvency": ["bankruptcy", "failure", "financial condition"],
    "insolvent": [],
    "insomnia": ["sleep disorder"],
    "insomniac": ["diseased person", "sick person", "sleepless person", "sufferer"],
    "insomuch": [],
    "inspan": ["harness", "tackle", "yoke"],
    "inspect": ["case", "examine", "go over", "perambulate", "review", "see", "survey", "vet"],
    "inspection": ["check", "check-out procedure", "checkout", "examination", "review", "scrutiny"],
    "inspector": ["officer", "police officer", "policeman"],
    "inspector general": ["military officer", "officer"],
    "inspector maigret": ["commissaire maigret"],
    "inspectorate": ["body"],
    "inspectorship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "inspiration": ["afflatus", "germ", "idea", "mother", "seed", "source", "thought"],
    "inspirational": [],
    "inspirationally": [],
    "inspiratory": [],
    "inspire": ["animate", "encourage", "enliven", "exalt", "excite", "invigorate", "shake", "shake up", "stimulate", "stir"],
    "inspiring": [],
    "inspissation": ["dehydration", "desiccation", "drying up", "evaporation"],
    "instability": ["disorder"],
    "install": ["enthrone", "induct", "instal", "invest", "seat", "vest"],
    "installation": ["beginning", "commencement", "installing", "installment", "instalment", "start"],
    "installation charge": ["charge"],
    "installment": ["payment"],
    "installment credit": ["consumer credit", "installment loan", "loan"],
    "installment debt": ["debt"],
    "installment plan": ["hire-purchase", "installment buying", "never-never", "regular payment", "time plan"],
    "instant": ["inst"],
    "instant coffee": ["coffee", "java"],
    "instantaneous": ["instant"],
    "instantaneously": ["in a flash", "instantly", "outright"],
    "instantiate": ["represent"],
    "instantiation": ["internal representation", "mental representation", "representation"],
    "instar": ["arthropod"],
    "instep": ["arch", "fallen arch", "sunken arch"],
    "instigator": ["bad hat", "firebrand", "inciter", "instigant", "mischief-maker", "provoker", "ringleader", "trouble maker", "troublemaker", "troubler"],
    "instill": ["add", "bestow", "breathe", "bring", "contribute", "impart", "lend", "transfuse"],
    "instillation": ["liquid"],
    "instillator": ["apparatus", "setup"],
    "instinct": ["aptitude", "id", "inherent aptitude"],
    "instinctively": [],
    "institute": ["bring", "create", "make"],
    "institution": ["academy", "charity", "company", "educational institution", "establishment", "faith", "financial institution", "financial organisation", "financial organization", "honorary society", "issuer", "medical institution", "organisation", "organization", "organized religion", "religion", "vicariate", "vicarship"],
    "institutional": [],
    "institutionalized": ["institutionalised"],
    "institutionally": [],
    "instroke": ["cam stroke", "stroke", "throw"],
    "instruct": ["apprise", "apprize", "brief", "direct", "inform"],
    "instruction": ["call", "code", "command", "command line", "computer code", "link", "macro", "macro instruction", "program line", "statement", "system error", "toggle"],
    "instruction book": ["book of facts", "reference", "reference book", "reference work"],
    "instruction manual": ["book of instructions", "instructions", "manual", "operating instructions"],
    "instructional": [],
    "instructive": ["informative"],
    "instructorship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "instructress": ["instructor", "teacher"],
    "instrument": ["equip", "fit", "fit out", "outfit"],
    "instrument flying": ["navigation", "pilotage", "piloting"],
    "instrument landing": ["aircraft landing", "airplane landing"],
    "instrument of execution": ["chair", "death chair", "death chamber", "electric chair", "gallows", "garotte", "garrote", "garrotte", "gas chamber", "guillotine", "hot seat", "instrument", "iron collar", "stake"],
    "instrument of punishment": ["cangue", "cucking stool", "ducking stool", "instrument", "instrument of torture", "paddle", "pillory", "stocks", "switch"],
    "instrument of torture": ["boot", "instrument of punishment", "iron boot", "iron heel", "iron maiden", "rack", "the boot", "thumbscrew", "wheel"],
    "instrumental": [],
    "instrumental conditioning": ["operant conditioning"],
    "instrumental music": ["music"],
    "instrumental role": ["instrument", "participant role", "semantic role"],
    "instrumentalism": ["pragmatism"],
    "instrumentality": ["social unit", "unit"],
    "instrumentation": ["arrangement", "musical arrangement"],
    "insubordinate": [],
    "insubordination": ["defiance", "rebelliousness"],
    "insubstantial": ["jejune"],
    "insubstantiality": ["weakness"],
    "insubstantially": ["impalpably"],
    "insufficiency": ["failing", "inadequacy", "weakness"],
    "insufficient": ["deficient"],
    "insufficiently": [],
    "insufflate": ["administer"],
    "insufflation": ["blowing"],
    "insular": [],
    "insulate": ["alter", "change", "modify", "soundproof", "weatherstrip"],
    "insulating material": ["building material", "corkboard", "insulant", "insulation", "lagging"],
    "insulation": ["detachment", "insularism", "insularity", "isolation"],
    "insulator": ["bushing", "dielectric", "glass wool", "material", "mineral wool", "nonconductor", "rock wool", "stuff"],
    "insulin": ["endocrine", "hormone", "humulin", "hypoglycaemic agent", "hypoglycemic agent", "internal secretion", "lente iletin", "lente insulin", "recombinant human insulin"],
    "insulin shock": ["insulin reaction", "shock"],
    "insult": ["affront", "discourtesy", "indignity", "offence", "offense", "offensive activity", "outrage", "scandalisation", "scandalization"],
    "insultingly": [],
    "insuperable": ["unconquerable"],
    "insuperably": [],
    "insurability": ["eligibility"],
    "insurable": [],
    "insurable interest": ["interest", "stake"],
    "insurance": ["assurance", "automobile insurance", "business interruption insurance", "car insurance", "coinsurance", "fire insurance", "group insurance", "hazard insurance", "health insurance", "liability insurance", "life assurance", "life insurance", "malpractice insurance", "protection", "reinsurance", "security", "self-insurance", "term insurance"],
    "insurance broker": ["agent", "broker", "factor", "general agent", "insurance agent", "underwriter"],
    "insurance claim": ["claim"],
    "insurance company": ["insurance firm", "insurance underwriter", "insurer", "nondepository financial institution", "underwriter"],
    "insure": ["coinsure", "protect", "reinsure"],
    "insured": ["individual", "insured person", "mortal", "person", "somebody", "someone", "soul"],
    "insurgency": ["insurgence", "insurrection", "rebellion", "revolt", "rising", "uprising"],
    "insurgent": ["crusader", "freedom fighter", "insurrectionist", "meliorist", "mutineer", "rebel", "reformer", "reformist", "revolutionary", "revolutionist", "social reformer", "subversive", "subverter", "young turk"],
    "insurmountable": ["unsurmountable"],
    "insurrectional": ["insurrectionary"],
    "insurrectionism": ["principle"],
    "intact": ["inviolate"],
    "intactness": ["flawlessness", "ne plus ultra", "perfection"],
    "intaglio": ["diaglyph", "glyptic art", "glyptography"],
    "intaglio printing": ["gravure", "intaglio", "photogravure", "printing", "printing process"],
    "intake": ["air horn", "inlet", "opening", "siamese", "siamese connection"],
    "intake manifold": ["manifold"],
    "intake valve": ["valve"],
    "intangibility": ["immateriality", "impalpability", "incorporeality", "intangibleness"],
    "intangible": ["assets", "good will", "goodwill", "intangible asset"],
    "integer": ["characteristic", "common multiple", "digit", "divisor", "double digit", "factor", "figure", "large integer", "modulus", "number", "population", "whole number"],
    "integral": ["calculation", "computation", "definite integral", "figuring", "indefinite integral", "reckoning"],
    "integral calculus": ["calculus", "infinitesimal calculus"],
    "integrally": [],
    "integrate": ["calculate", "cipher", "compute", "cypher", "figure", "reckon", "work out"],
    "integrated": ["structured"],
    "integrated circuit": ["computer circuit", "microcircuit"],
    "integrated data processing": ["adp", "automatic data processing", "idp"],
    "integrated logistic support": ["logistic assistance", "logistic support"],
    "integration": ["desegregation", "group action", "integrating"],
    "integrative": [],
    "integrator": ["measuring device", "measuring instrument", "measuring system", "planimeter"],
    "integrity": ["completeness", "incompleteness", "rawness", "state", "unity", "wholeness"],
    "integument": ["cover", "covering", "natural covering"],
    "integumentary": ["integumental"],
    "integumentary system": ["system"],
    "intellectual": ["alchemist", "anomalist", "aphorist", "bel esprit", "bookman", "brain", "brainiac", "clever clogs", "clever dick", "creative thinker", "decipherer", "decoder", "doubter", "egghead", "einstein", "exponent", "expositor", "expounder", "genius", "highbrow", "idealogue", "illusionist", "individual", "intellect", "mastermind", "mentor", "mind", "mortal", "person", "sceptic", "scholar", "scholarly person", "seer", "skeptic", "somebody", "someone", "soul", "specifier", "student", "subjectivist", "synthesiser", "synthesist", "synthesizer", "theoretician", "theoriser", "theorist", "theorizer", "thinker", "visionary", "wise man", "wonderer"],
    "intellectual property": ["belongings", "holding", "property"],
    "intellectualization": ["defence", "defence mechanism", "defence reaction", "defense", "defense mechanism", "defense reaction", "intellectualisation"],
    "intellectually": [],
    "intelligence": ["administrative body", "administrative unit", "ic", "intelligence agency", "intelligence community", "intelligence service", "international intelligence agency", "military intelligence", "military intelligence agency", "national intelligence community", "united states intelligence agency", "united states intelligence community"],
    "intelligence analyst": ["analyst"],
    "intelligence cell": ["radical cell", "terrorist cell"],
    "intelligence community": ["ic", "intelligence", "intelligence agency", "intelligence service", "national intelligence community", "united states intelligence community"],
    "intelligence quotient": ["adult intelligence", "borderline intelligence", "i.q.", "iq", "ratio"],
    "intelligence test": ["binet-simon scale", "iq test", "mental test", "mental testing", "psychometric test", "stanford-binet test", "test"],
    "intelligent": ["well-informed"],
    "intelligently": [],
    "intelligentsia": ["clerisy", "culturati", "elite", "elite group", "literati"],
    "intelligibility": ["comprehensibility", "readability", "speech intelligibility", "understandability"],
    "intelligible": [],
    "intelligibly": ["clearly", "understandably"],
    "intelnet": ["computer network"],
    "intemperance": ["gluttony", "unrestraint"],
    "intemperate": [],
    "intend": ["aim", "calculate", "design", "designate", "destine", "direct", "mean", "plan", "slate", "specify"],
    "intended": [],
    "intense": [],
    "intensely": [],
    "intensification": ["increase", "step-up"],
    "intensified": [],
    "intensifier": ["intensive", "modifier", "qualifier"],
    "intensify": ["alter", "change", "modify"],
    "intensifying": [],
    "intension": ["connotation", "import", "meaning", "significance", "signification"],
    "intensional": [],
    "intensity": ["acoustic power", "candlepower", "field intensity", "field strength", "half-intensity", "intensity level", "light intensity", "magnitude", "radio brightness", "sound pressure level", "strength", "threshold level"],
    "intensive": [],
    "intensive care": ["medical aid", "medical care"],
    "intensive care unit": ["coronary care unit", "icu", "neonatal intensive care unit", "nicu", "social unit", "unit"],
    "intensively": [],
    "intent": ["import", "meaning", "purport", "significance", "signification", "spirit"],
    "intention": ["end", "goal"],
    "intentional": ["knowing"],
    "intentionality": ["deliberateness", "deliberation"],
    "intentionally": ["advisedly", "by choice", "by design", "deliberately", "designedly", "on purpose", "purposely"],
    "intently": [],
    "intentness": ["assiduity", "assiduousness", "concentration", "engrossment"],
    "inter alia": [],
    "inter-service support": ["logistic assistance", "logistic support"],
    "interact": ["act", "affiliate", "assemble", "associate", "assort", "collude", "combine", "communicate", "condescend", "connect", "consort", "conspire", "control", "do by", "fall all over", "foregather", "forgather", "gather", "get in touch", "handle", "have", "intercommunicate", "interfere", "interpose", "intervene", "invite", "keep in line", "manipulate", "marginalise", "marginalize", "meet", "move", "patronise", "patronize", "pay for", "philander", "reach out", "relate", "socialise", "socialize", "step in", "touch base", "transact", "treat", "womanise", "womanize"],
    "interaction": ["color force", "electromagnetic interaction", "fundamental interaction", "gravitational interaction", "physical phenomenon", "strong force", "strong interaction", "weak force", "weak interaction"],
    "interactional": ["interactive"],
    "interbank loan": ["bank loan"],
    "interbred": [],
    "intercalary": [],
    "intercalate": ["add"],
    "intercapitular vein": ["vein", "vena", "vena intercapitalis", "venous blood vessel"],
    "intercede": ["arbitrate", "intermediate", "liaise", "mediate", "negociate", "negotiate", "talk terms"],
    "intercellular": [],
    "intercept": ["catch", "cut off", "cut out", "grab", "stop", "take hold of"],
    "interception": ["bar", "prevention"],
    "interceptor": ["attack aircraft", "fighter", "fighter aircraft"],
    "intercession": ["orison", "petition", "prayer"],
    "interchange": ["alternate", "change by reversal", "flip", "flip-flop", "reverse", "switch", "tack", "turn"],
    "interchangeable": [],
    "interchangeably": [],
    "interchurch": ["interdenominational"],
    "intercollegiate": [],
    "intercommunicate": ["communicate", "complect", "interconnect", "interlink"],
    "intercommunication": ["communicating", "communication", "intercourse", "social intercourse"],
    "intercommunication system": ["communication system", "intercom", "interphone"],
    "intercommunion": ["communion", "holy communion", "manduction", "sacramental manduction"],
    "interconnect": ["connect", "interlink", "link", "link up", "tie"],
    "interconnected": ["interrelated"],
    "interconnection": ["connectedness", "connection", "interconnectedness", "link"],
    "intercontinental": [],
    "intercontinental ballistic missile": ["ballistic missile", "icbm", "minuteman"],
    "intercostal": ["intercostal muscle", "musculus intercostalis", "skeletal muscle", "striated muscle"],
    "intercostal artery": ["arteria", "arteria intercostalis", "arterial blood vessel", "artery"],
    "intercostal vein": ["vein", "vena", "vena intercostalis", "venous blood vessel"],
    "intercourse": ["communion", "intercommunication", "sharing", "social intercourse"],
    "interdepartmental": [],
    "interdepartmental support": ["interagency support", "logistic assistance", "logistic support"],
    "interdependent": ["mutualist", "mutually beneficial"],
    "interdict": ["destroy", "destruct"],
    "interdiction": ["prohibition"],
    "interdiction fire": ["fire", "firing"],
    "interdisciplinary": [],
    "interest": ["absorb", "arouse", "elicit", "engage", "engross", "enkindle", "evoke", "fascinate", "fire", "grip", "kindle", "occupy", "provoke", "raise", "spellbind", "transfix"],
    "interest expense": ["disbursal", "disbursement", "expense"],
    "interest rate": ["bank discount", "base rate", "charge per unit", "discount", "discount rate", "prime interest rate", "rate", "rate of interest", "usury", "vigorish"],
    "interest-bearing": [],
    "interested": [],
    "interestedness": ["cognitive state", "state of mind"],
    "interesting": [],
    "interestingly": [],
    "interface": ["cli", "command line interface", "computer program", "computer programme", "graphical user interface", "gui", "program", "programme", "user interface"],
    "interfacial": [],
    "interfacial tension": ["interfacial surface tension", "surface tension"],
    "interfaith": [],
    "interfere": ["hinder", "impede"],
    "interference": ["block", "blocking"],
    "interfering": ["busy", "busybodied", "meddlesome", "meddling", "officious"],
    "interferometer": ["measuring device", "measuring instrument", "measuring system"],
    "interferon": ["alpha-interferon", "antiviral", "antiviral agent", "antiviral drug", "beta-interferon", "gamma-interferon"],
    "intergalactic": [],
    "intergalactic space": ["part", "region"],
    "interim": ["interregnum", "interval", "lag", "meantime", "meanwhile", "time interval"],
    "interim overhaul": ["inspection and repair", "overhaul", "service"],
    "interior": [],
    "interior angle": ["angle", "internal angle", "reentering angle", "reentrant angle"],
    "interior decoration": ["decor", "decoration", "ornament", "ornamentation"],
    "interior design": ["architecture"],
    "interior designer": ["decorator", "designer", "house decorator", "interior decorator", "room decorator", "specialiser", "specialist", "specializer"],
    "interior door": ["accordion door", "bi-fold door", "door", "folding door"],
    "interior live oak": ["live oak", "quercus wislizenii", "quercus wizlizenii"],
    "interior monologue": ["prose"],
    "interject": ["break up", "come in", "cut off", "disrupt", "inject", "interpose", "interrupt", "put in", "throw in"],
    "interjection": ["break", "disruption", "gap", "interpellation", "interpolation", "interposition", "interruption"],
    "interlacing": ["interlinking", "interlocking", "interwoven"],
    "interlaken": [],
    "interlayer": ["bed", "layer"],
    "interleaf": ["folio", "leaf"],
    "interleave": ["furnish", "provide", "render", "supply"],
    "interleukin": ["lymphokine"],
    "interlinear": ["interlineal"],
    "interlingua": ["artificial language"],
    "interlobular": [],
    "interlock": ["bosom", "embrace", "hug", "lock", "squeeze"],
    "interlocutor": ["middleman", "minstrel"],
    "interlocutory": [],
    "interlope": ["interfere", "interpose", "intervene", "step in"],
    "interlude": ["perform"],
    "intermarry": ["conjoin", "espouse", "get hitched with", "get married", "hook up with", "marry", "wed"],
    "intermaxillary suture": ["fibrous joint", "sutura", "sutura intermaxillaris", "suture"],
    "intermediate": ["chemical", "chemical substance"],
    "intermediate host": ["host"],
    "intermediate temporal artery": ["arteria temporalis intermedia", "temporal artery"],
    "intermediate vector boson": ["gauge boson"],
    "intermediate wheatgrass": ["agropyron intermedium", "elymus hispidus", "wheat-grass", "wheatgrass"],
    "intermediately": [],
    "intermezzo": ["movement"],
    "interminably": ["endlessly"],
    "intermission": ["pause"],
    "intermittence": ["intermittency", "irregularity", "unregularity"],
    "intermittent": [],
    "intermittent claudication": ["claudication", "gameness", "gimp", "gimpiness", "lameness", "limping"],
    "intermittently": [],
    "intermolecular": [],
    "intermural": [],
    "intern": ["confine", "detain"],
    "internal": ["intragroup"],
    "internal auditor": ["auditor"],
    "internal carotid artery": ["arteria carotis", "carotid artery"],
    "internal cerebral vein": ["cerebral vein", "vena cerebri", "vena cerebrum internus"],
    "internal combustion": ["burning", "combustion"],
    "internal control": ["control", "inventory control", "management control", "quality control"],
    "internal drive": ["drive"],
    "internal iliac artery": ["arteria iliaca", "hypogastric artery", "iliac artery"],
    "internal jugular vein": ["jugular", "jugular vein", "vena jugularis"],
    "internal maxillary artery": ["arteria maxillaris", "maxillary artery"],
    "internal medicine": ["general medicine", "medical specialty", "medicine"],
    "internal organ": ["bowel", "breadbasket", "entrails", "excretory organ", "gut", "heart", "hindgut", "innards", "intestine", "liver", "organ", "pump", "respiratory organ", "stomach", "ticker", "tum", "tummy", "urinary organ", "viscera", "viscus"],
    "internal revenue": ["revenue", "tax income", "tax revenue", "taxation"],
    "internal revenue service": ["agency", "authority", "bureau", "federal agency", "government agency", "irs", "office"],
    "internal rhyme": ["rhyme", "rime"],
    "internal-combustion engine": ["diesel", "diesel engine", "diesel motor", "four-stroke engine", "four-stroke internal-combustion engine", "gas engine", "gasoline engine", "heat engine", "ice", "outboard", "outboard motor", "petrol engine", "radial engine", "reciprocating engine", "rotary engine", "valve-in-head engine"],
    "internalization": ["acquisition", "incorporation", "internalisation", "introjection", "learning"],
    "internalize": ["ascribe", "assign", "attribute", "impute", "interiorise", "interiorize", "internalise"],
    "internally": [],
    "internasal suture": ["fibrous joint", "sutura", "sutura internasalis", "suture"],
    "international": ["socialism", "socialist economy"],
    "international atomic energy agency": ["iaea", "un agency", "united nations agency"],
    "international bank for reconstruction and development": ["ibrd", "un agency", "united nations agency", "world bank"],
    "international candle": ["candlepower unit", "luminous intensity unit"],
    "international civil aviation organization": ["icao", "un agency", "united nations agency"],
    "international court of justice": ["court", "judicature", "tribunal", "world court"],
    "international development association": ["ida", "un agency", "united nations agency"],
    "international finance corporation": ["ifc", "un agency", "united nations agency"],
    "international flight": ["flight"],
    "international grandmaster": ["grandmaster"],
    "international intelligence agency": ["a'man", "canadian security intelligence service", "central intelligence machinery", "cim", "cisc", "communications security establishment", "criminal intelligence services of canada", "cse", "csis", "directorate for inter-services intelligence", "foreign intelligence service", "general security services", "iis", "intelligence", "intelligence agency", "intelligence service", "inter-services intelligence", "international relations and security network", "iraqi intelligence service", "iraqi mukhabarat", "isi", "isn", "mi", "military intelligence section 5", "military intelligence section 6", "mossad", "secret intelligence service", "security intelligence review committee", "security service", "shin bet", "sirc", "sluzhba vneshney razvedki", "svr"],
    "international islamic front for jihad against jews and crusaders": [],
    "international labor organization": ["ilo", "international labour organization", "un agency", "united nations agency"],
    "international law": ["admiralty law", "jurisprudence", "law", "law of nations", "marine law", "maritime law"],
    "international law enforcement agency": ["administrative body", "administrative unit", "department of justice canada", "dojc", "interpol", "mounties", "rcmp", "royal canadian mounted police"],
    "international maritime organization": ["imo", "un agency", "united nations agency"],
    "international monetary fund": ["imf", "un agency", "united nations agency"],
    "international relations and security network": ["international intelligence agency", "isn"],
    "international terrorism": ["act of terrorism", "terrorism", "terrorist act"],
    "international wanted notice": ["red notice", "wanted notice", "wanted poster"],
    "internationale": [],
    "internationalism": ["doctrine", "ism", "philosophical system", "philosophy", "school of thought"],
    "internationalist": ["advocate", "advocator", "exponent", "proponent"],
    "internationality": ["ambit", "compass", "internationalism", "orbit", "range", "reach", "scope"],
    "internationalization": ["group action", "internationalisation"],
    "internationalize": ["command", "control", "internationalise"],
    "internationally": [],
    "internecine": [],
    "internee": ["captive", "prisoner"],
    "internet": ["computer network", "cyberspace", "net"],
    "internet explorer": ["explorer", "ie"],
    "internist": ["medical specialist", "specialist"],
    "internment": ["captivity", "immurement", "imprisonment", "incarceration"],
    "internode": ["segment"],
    "internship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "internuncio": ["diplomat", "diplomatist"],
    "interoception": ["proprioception", "sensibility", "sensitiveness", "sensitivity", "somaesthesia", "somaesthesis", "somataesthesis", "somatesthesia", "somatic sense", "somatic sensory system", "somatosensory system", "somesthesia", "somesthesis"],
    "interoceptive": [],
    "interoceptor": ["enteroceptor", "receptor", "sense organ", "sensory receptor"],
    "interoperability": ["ability"],
    "interoperable": [],
    "interpellate": ["query", "question"],
    "interpellation": ["order", "parliamentary law", "parliamentary procedure", "rules of order"],
    "interpenetrate": ["invade", "penetrate", "perforate", "permeate"],
    "interpenetration": ["incursion", "penetration"],
    "interpersonal": [],
    "interphalangeal joint": ["ginglymoid joint", "ginglymus", "hinge joint"],
    "interphone": ["intercom", "intercommunication system"],
    "interplanetary": [],
    "interplanetary dust": ["dust"],
    "interplanetary gas": ["plasma"],
    "interplanetary medium": ["interplanetary space"],
    "interplanetary space": ["interplanetary medium", "part", "region"],
    "interplay": ["interaction"],
    "interpol": ["international law enforcement agency"],
    "interpolate": ["calculate", "cipher", "compute", "cypher", "extrapolate", "figure", "reckon", "work out"],
    "interpolation": ["content", "insertion", "message", "subject matter", "substance"],
    "interpose": [],
    "interposition": ["emplacement", "intervention", "locating", "location", "placement", "position", "positioning"],
    "interpret": ["do", "execute", "perform", "render", "sing"],
    "interpretation": ["account", "clarification", "construal", "construction", "eisegesis", "elucidation", "exegesis", "explanation", "exposition", "expounding", "ijtihad", "illumination", "literal interpretation", "misinterpretation", "mistaking", "misunderstanding", "popularisation", "popularization", "reading", "reconstruction", "twist", "version"],
    "interpretative": ["interpretive"],
    "interpreted": ["taken"],
    "interpreter": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "interpretive dance": ["interpretative dance", "interpretative dancing", "interpretive dancing", "modern dance"],
    "interracial": [],
    "interracially": [],
    "interreflection": ["reflection", "reflexion"],
    "interregnum": ["interim", "lag", "meantime", "meanwhile"],
    "interrelate": ["associate", "colligate", "connect", "link", "link up", "relate", "tie in"],
    "interrelation": ["interrelatedness", "interrelationship", "psychodynamics", "relation"],
    "interrogate": ["air", "beam", "broadcast", "send", "transmit"],
    "interrogation": ["transmission"],
    "interrogative": [],
    "interrogative mood": ["interrogative", "modality", "mode", "mood"],
    "interrogatively": [],
    "interrupt": ["barge in", "block", "break", "break in", "break off", "break up", "burst in on", "burst upon", "butt in", "chime in", "chisel in", "come in", "cut", "cut in", "cut off", "discontinue", "disrupt", "heckle", "inject", "interject", "intermit", "interpose", "jam", "pause", "punctuate", "put aside", "put away", "put in", "stop", "stop over", "take off", "take time off", "throw in"],
    "interrupted": [],
    "interrupted fern": ["flowering fern", "osmund", "osmunda clatonia"],
    "interrupter": ["device"],
    "interruption": ["abatement", "break", "dislocation", "disruption", "eclipse", "happening", "hiatus", "natural event", "occultation", "occurrence", "occurrent", "punctuation", "reprieve", "respite", "suspension"],
    "interscholastic": ["interschool"],
    "intersect": ["come across", "cross", "encounter", "meet", "run across", "run into", "see"],
    "intersection": ["origin", "set"],
    "intersexual": [],
    "interspecies": ["interspecific"],
    "intersperse": ["interleave", "lay", "place", "pose", "position", "put", "set"],
    "interspersion": ["combination", "combining", "compounding", "interspersal"],
    "interstate": ["highway", "interstate highway", "main road"],
    "interstate commerce commission": ["icc", "independent agency"],
    "interstellar": [],
    "interstellar medium": ["interstellar space"],
    "interstellar space": ["interstellar medium", "part", "region"],
    "interstice": ["anatomical structure", "areola", "bodily structure", "body structure", "complex body part", "structure"],
    "interstitial": [],
    "interstitial fluid": ["ecf", "extracellular fluid"],
    "interstitial pneumonia": ["respiratory disease", "respiratory disorder", "respiratory illness"],
    "interstitial tissue": ["animal tissue", "glia", "neuroglia", "plant tissue"],
    "interstratify": ["stratify"],
    "intertidal": [],
    "intertribal": [],
    "intertrigo": ["chafing"],
    "intertwine": ["distort", "enlace", "entwine", "interlace", "knot", "lace", "plash", "pleach", "ravel", "splice", "tangle", "twine", "twist", "wattle", "wind", "wreathe"],
    "interval": ["fifth", "fourth", "half step", "musical interval", "musical notation", "musical octave", "octave", "quarter tone", "quarter-tone", "semitone", "seventh", "sixth", "step", "third", "tone", "whole step", "whole tone"],
    "intervene": ["lie"],
    "intervening": [],
    "intervenor": ["party"],
    "intervention": ["foreign policy", "interference"],
    "interventricular foramen": ["foramen", "foramen of monro", "hiatus", "monro's foramen"],
    "intervertebral": [],
    "intervertebral disc": ["disc", "disk", "intervertebral disk", "saucer"],
    "intervertebral vein": ["vein", "vena", "vena intervertebralis", "venous blood vessel"],
    "interview": ["converse", "discourse"],
    "interviewee": ["answerer", "don't-know", "respondent", "responder"],
    "interviewer": ["asker", "enquirer", "inquirer", "querier", "questioner"],
    "intestacy": ["situation", "state of affairs"],
    "intestate": [],
    "intestinal": ["enteral", "enteric"],
    "intestinal bypass": ["operation", "surgery", "surgical operation", "surgical procedure", "surgical process"],
    "intestinal flora": ["micro-organism", "microorganism"],
    "intestinal juice": ["secretion"],
    "intestinal obstruction": ["blockage", "enteropathy", "ileus", "obstruction"],
    "intestine": ["bowel", "gut", "internal organ", "large intestine", "small intestine", "viscus"],
    "inti": ["peruvian monetary unit"],
    "intifada": ["insurrection", "intifadah", "rebellion", "revolt", "rising", "uprising"],
    "intima": ["membrane", "tissue layer"],
    "intimal": [],
    "intimate": ["adumbrate", "hint", "insinuate", "suggest"],
    "intimidate": ["dash", "daunt", "discourage", "frighten away", "frighten off", "pall", "restrain", "scare", "scare away", "scare off"],
    "intimidated": [],
    "intimidation": ["discouragement", "disheartenment", "dismay"],
    "intolerable": ["unbearable", "unendurable"],
    "intolerance": ["attitude", "bigotry", "dogmatism", "fanaticism", "fanatism", "mental attitude", "narrow-mindedness", "narrowness", "religionism", "zealotry", "zero tolerance"],
    "intolerant": [],
    "intolerantly": [],
    "intonate": ["intone", "judge", "label", "pronounce"],
    "intonation": ["drone", "droning", "inflection", "intonation pattern", "modulation", "monotone", "pitch contour", "prosody", "singsong"],
    "intonation pattern": ["intonation", "modulation", "pitch contour"],
    "intoxicant": ["drug"],
    "intoxicate": ["affect", "befuddle", "fuddle", "inebriate", "soak"],
    "intoxicated": ["drunk"],
    "intoxication": ["excitement", "exhilaration"],
    "intra vires": [],
    "intracapsular surgery": ["cataract surgery"],
    "intracellular": [],
    "intracellular fluid": ["bodily fluid", "body fluid", "humor", "humour", "liquid body substance"],
    "intracerebral": [],
    "intracranial": [],
    "intracranial aneurysm": ["aneurism", "aneurysm"],
    "intractability": ["balkiness", "defiance", "disobedience", "fractiousness", "intractableness", "mulishness", "obstinacy", "obstinance", "rebelliousness", "recalcitrance", "recalcitrancy", "refractoriness", "stubbornness", "trait", "unmanageableness", "unruliness", "wildness", "wilfulness", "willfulness"],
    "intractable": [],
    "intractably": [],
    "intradepartmental": [],
    "intradermal": ["intracutaneous", "intradermic"],
    "intradermal injection": ["injection", "shot"],
    "intradermal test": ["skin test", "subcutaneous test"],
    "intradermally": [],
    "intrados": ["curve", "curved shape"],
    "intralinguistic": [],
    "intralobular": [],
    "intramolecular": [],
    "intramural": [],
    "intramuscular": [],
    "intramuscular injection": ["injection", "shot"],
    "intramuscularly": [],
    "intranet": ["computer network"],
    "intransigency": ["bullheadedness", "intransigence", "obstinacy", "obstinance", "pigheadedness", "self-will", "stubbornness"],
    "intransitive": [],
    "intransitive verb": ["intransitive", "intransitive verb form", "verb"],
    "intransitively": [],
    "intransitivity": ["grammatical relation", "intransitiveness"],
    "intraocular lens": ["lens", "lens system", "lense"],
    "intraocular pressure": ["force per unit area", "iop", "pressure", "pressure level"],
    "intrapulmonary": [],
    "intrasentential": [],
    "intraspecies": ["intraspecific"],
    "intrastate": [],
    "intrauterine": [],
    "intrauterine device": ["birth control device", "contraceptive", "contraceptive device", "iud", "loop", "preventative", "preventive", "prophylactic device"],
    "intravasation": ["harm", "hurt", "injury", "trauma"],
    "intravenous": ["endovenous"],
    "intravenous anesthetic": ["anaesthetic", "anaesthetic agent", "anesthetic", "anesthetic agent", "dibucaine", "tribromoethanol", "tribromoethyl alcohol", "truth drug", "truth serum"],
    "intravenous drip": ["dribble", "drip", "trickle"],
    "intravenous feeding": ["alimentation", "feeding", "iv"],
    "intravenous injection": ["fix", "injection", "shot"],
    "intravenous pyelogram": ["ivp", "pyelogram"],
    "intravenous pyelography": ["ivp", "pyelography"],
    "intravenously": [],
    "intraventricular": [],
    "intricate": [],
    "intrigue": ["fascinate", "grab", "interest", "matter to", "seize"],
    "intriguing": [],
    "intrinsic": ["intrinsical"],
    "intrinsic factor": ["factor"],
    "intrinsic fraud": ["fraud"],
    "intrinsically": ["as such", "in and of itself", "per se"],
    "intro": ["musical passage", "passage"],
    "introduce": ["debut", "initiate", "innovate", "open up", "phase in", "pioneer"],
    "introduction": ["proposal"],
    "introductory": [],
    "introit": ["composition", "musical composition", "opus", "piece", "piece of music"],
    "introitus": ["opening", "orifice", "porta"],
    "introject": ["change"],
    "introjected": [],
    "introjection": ["incorporation", "internalisation", "internalization"],
    "intron": ["deoxyribonucleic acid", "desoxyribonucleic acid", "dna", "noncoding dna"],
    "introspect": ["chew over", "contemplate", "excogitate", "meditate", "mull", "mull over", "muse", "ponder", "reflect", "ruminate", "speculate", "think over"],
    "introspection": ["contemplation", "examen", "examination", "musing", "reflection", "reflexion", "rumination", "self-analysis", "self-contemplation", "self-examination", "soul-searching", "thoughtfulness"],
    "introspective": ["introverted", "self-examining"],
    "introspectiveness": ["thoughtfulness"],
    "introuvable": [],
    "introversion": ["internality", "inwardness", "unsociability", "unsociableness"],
    "introversive": ["introvertive"],
    "introvert": ["alter", "change", "modify"],
    "introvertish": ["shut-in"],
    "intrude": ["horn in", "look", "nose", "poke", "pry", "search"],
    "intrude on": ["come in", "encroach upon", "enter", "foray into", "get in", "get into", "go in", "go into", "invade", "move into", "obtrude upon", "raid"],
    "intruder": ["alien", "boarder", "crasher", "encroacher", "entrant", "gatecrasher", "infiltrator", "interloper", "invader", "penetrator", "persona non grata", "prowler", "pusher", "sneak", "squatter", "stalker", "stranger", "thruster", "trespasser", "unknown", "unwelcome guest", "unwelcome person"],
    "intruding": [],
    "intrusion": ["geologic process", "geological process"],
    "intrusive": [],
    "intrusiveness": ["aggressiveness", "meddlesomeness", "officiousness"],
    "intuit": ["apprehend", "compass", "comprehend", "dig", "get the picture", "grasp", "grok", "savvy"],
    "intuition": ["belief", "bosom", "feeling", "heart", "hunch", "impression", "notion", "opinion", "suspicion"],
    "intuitionism": ["philosophical doctrine", "philosophical theory"],
    "intuitionist": [],
    "intuitive": [],
    "intuitively": [],
    "intumescence": ["haematoma", "hematoma", "intumescency", "lump", "puffiness", "swelling"],
    "intussuscept": ["introvert", "invaginate"],
    "intussusception": ["development", "growing", "growth", "maturation", "ontogenesis", "ontogeny"],
    "inula": ["elecampane", "herb", "herbaceous plant", "inula helenium"],
    "inulin": ["polyose", "polysaccharide"],
    "inundate": ["deluge", "flood", "submerge"],
    "inure": ["accustom", "brace oneself for", "callous", "cauterise", "cauterize", "habituate", "harden", "indurate", "prepare for", "steel oneself against", "steel onself for"],
    "inutile": [],
    "inutility": ["futility", "impracticability", "impracticableness", "impracticality", "quality", "unusefulness", "uselessness", "worthlessness"],
    "invade": ["infest", "inhabit", "overrun"],
    "invader": ["encroacher", "interloper", "intruder", "trespasser"],
    "invaginate": ["sheathe"],
    "invagination": ["condition", "introversion"],
    "invalid": ["remove"],
    "invalidate": ["annul", "avoid", "break", "cancel", "nullify", "quash", "stet", "strike down", "void"],
    "invalidated": ["nullified"],
    "invalidator": ["functionary", "nullifier", "official", "voider"],
    "invalidism": ["health problem", "ill health", "unhealthiness"],
    "invalidity": ["fallaciousness", "illogic", "illogicality", "illogicalness", "inconsequence", "invalidness"],
    "invaluable": ["priceless"],
    "invaluableness": ["gold", "preciousness", "pricelessness", "valuableness", "value"],
    "invar": ["alloy", "metal"],
    "invariability": ["changelessness", "invariableness", "invariance", "unchangeability", "unchangeableness", "unchangingness", "unvariedness"],
    "invariable": [],
    "invariance": ["constancy", "stability"],
    "invariant": ["characteristic", "feature"],
    "invasion": ["encroachment", "entering", "entrance", "intrusion"],
    "invasion of privacy": ["civil wrong", "tort"],
    "invasive": [],
    "invent": ["contrive", "create by mental act", "create mentally", "devise", "excogitate", "forge", "formulate"],
    "invention": ["conception", "concoction", "contrivance", "creative thinking", "creativeness", "creativity", "design", "excogitation", "innovation"],
    "inventively": [],
    "inventiveness": ["cleverness", "creative thinking", "creativeness", "creativity", "imagination", "ingeniousness", "ingenuity", "resource", "resourcefulness"],
    "inventor": ["artificer", "creator", "discoverer", "patentee"],
    "inventory": ["list", "stock-take", "take stock"],
    "inventory accounting": ["accountancy", "accounting", "fifo", "first in first out", "last in first out", "lifo"],
    "inventory control": ["internal control"],
    "inventory item": ["item", "point"],
    "inverse": ["additive inverse", "multiplicative inverse", "opposite", "oppositeness", "opposition", "reciprocal"],
    "inverse function": ["function", "map", "mapping", "mathematical function", "single-valued function"],
    "inversely": ["reciprocally"],
    "inversion": ["abnormalcy", "abnormality"],
    "invert": ["alter", "change", "modify"],
    "invert sugar": ["carbohydrate", "saccharide", "sugar"],
    "invertase": ["disaccharidase", "saccharase", "sucrase"],
    "invertebrate": ["animal", "animate being", "arthropod", "beast", "borer", "brachiopod", "brute", "bryozoan", "cnidarian", "coelenterate", "comb jelly", "creature", "ctenophore", "echinoderm", "ectoproct", "entoproct", "fauna", "lamp shell", "lampshell", "mollusc", "mollusk", "moss animal", "parazoan", "peanut worm", "phoronid", "polyzoan", "poriferan", "rotifer", "sea mat", "sea moss", "shellfish", "sipunculid", "sponge", "symbion pandora", "woodborer", "worm", "zoophyte"],
    "inverted": ["upside-down"],
    "inverted hang": ["hang"],
    "inverted pleat": ["plait", "pleat"],
    "inverter": ["electrical converter"],
    "invertible": [],
    "invest": ["adorn", "clothe", "equip", "fit", "fit out", "outfit"],
    "investigate": ["analyse", "analyze", "canvas", "canvass", "examine", "experiment", "explore", "look into", "probe", "research", "search", "study"],
    "investigation": ["analysis", "count", "counting", "empiricism", "enquiry", "enumeration", "examination", "inquiry", "investigating", "numeration", "police investigation", "police work", "reckoning", "research", "scrutiny", "search", "tabulation", "tally", "tap", "testing", "wiretap", "work"],
    "investigator": ["adjuster", "adjustor", "claim agent", "claims adjuster", "claims adjustor", "coroner", "detective", "examiner", "expert", "inspector", "medical examiner", "ombudsman"],
    "investing": ["arbitrage", "finance", "foreign direct investment", "investment", "leverage", "leveraging"],
    "investment": ["assets", "investment funds", "speculation", "venture"],
    "investment adviser": ["adviser", "advisor", "consultant", "investment advisor"],
    "investment banker": ["agent", "broker", "factor", "killer bee", "underwriter"],
    "investment company": ["closed-end fund", "closed-end investment company", "face-amount certificate company", "fixed investment trust", "fund", "hedge fund", "hedgefund", "investment firm", "investment trust", "mutual fund", "mutual fund company", "nondepository financial institution", "nondiscretionary trust", "open-end fund", "open-end investment company", "real estate investment trust", "reit", "unit investment trust", "unit trust"],
    "investment letter": ["letter of intent"],
    "investor": ["bear", "bondholder", "bull", "caller", "capitalist", "contrarian", "depositor", "lender", "loaner", "rentier", "shareholder", "shareowner", "stockholder"],
    "investors club": ["club", "gild", "guild", "lodge", "order", "social club", "society"],
    "invidiously": [],
    "invigilate": ["follow", "keep an eye on", "observe", "proctor", "watch", "watch over"],
    "invigilation": ["oversight", "superintendence", "supervising", "supervision"],
    "invigilator": ["monitor", "proctor"],
    "invigorate": ["arouse", "brace", "energise", "energize", "perk up", "reinvigorate", "stimulate"],
    "invigorating": [],
    "invincible": ["unbeatable", "unvanquishable"],
    "invincibly": [],
    "inviolable": [],
    "invisibility": ["inconspicuousness", "invisibleness", "physical property"],
    "invisible": ["unseeable"],
    "invisible balance": ["balance"],
    "invisibly": [],
    "invitation": ["asking", "bidding", "invite", "letter", "missive", "request", "summons"],
    "invitational": [],
    "invitatory": [],
    "invite": ["interact", "pay for"],
    "inviting": [],
    "invocation": ["orison", "petition", "prayer", "rogation", "supplication"],
    "invoice": ["bill", "charge"],
    "invoke": ["advert", "appeal", "bring up", "cite", "mention", "name", "refer"],
    "involucrate": [],
    "involucre": ["bract"],
    "involuntarily": [],
    "involuntary": [],
    "involute": ["rolled"],
    "involution": ["biological process", "organic process"],
    "involutional depression": ["major depressive episode"],
    "involve": ["admit", "drag", "drag in", "embroil", "entangle", "include", "let in", "mire", "sweep", "sweep up", "tangle"],
    "involved": [],
    "involvement": ["comprehension", "connectedness", "connection", "connexion", "implication", "inclusion"],
    "invulnerability": ["impregnability", "safety"],
    "invulnerable": [],
    "inward": ["inwards"],
    "inward-developing": [],
    "inward-moving": [],
    "inwardly": ["inside"],
    "inwardness": ["cognitive state", "state of mind"],
    "inweave": ["interweave", "weave"],
    "inwrought": [],
    "io": [],
    "io moth": ["automeris io", "saturniid", "saturniid moth"],
    "iodic acid": ["acid"],
    "iodide": ["halide", "hydrogen iodide", "potassium iodide", "silver iodide", "sodium iodide"],
    "iodinate": ["alter", "change", "modify"],
    "iodinated": ["iodised", "iodized"],
    "iodinating": [],
    "iodination": ["chemical action", "chemical change", "chemical process"],
    "iodine": ["atomic number 53", "chemical element", "element", "halogen", "i", "iodin", "iodine-125", "iodine-131"],
    "iodine-125": ["atomic number 53", "i", "iodin", "iodine", "radioisotope"],
    "iodine-131": ["atomic number 53", "i", "iodin", "iodine", "radioisotope"],
    "iodize": ["iodise", "process", "treat"],
    "iodoamino acid": ["amino acid", "aminoalkanoic acid", "iodothyronine", "iodotyrosine"],
    "iodochlorhydroxyquin": ["antifungal", "antifungal agent", "antimycotic", "antimycotic agent", "clioquinol", "fungicide"],
    "iodocompound": ["chemical compound", "compound"],
    "iodoform": ["haloform", "tri-iodomethane"],
    "iodoprotein": ["iodinated protein", "protein", "thyroglobulin", "thyroprotein"],
    "iodopsin": ["photopigment"],
    "iodothyronine": ["iodoamino acid", "tri-iodothyronine"],
    "iodotyrosine": ["di-iodotyrosine", "iodoamino acid", "mono-iodotyrosine"],
    "ion": ["anion", "cation", "particle", "subatomic particle"],
    "ion beam": ["ionic beam", "particle beam"],
    "ion engine": ["reaction engine", "reaction-propulsion engine"],
    "ion exchange": ["action", "activity", "natural action", "natural process"],
    "ion pump": ["air pump", "vacuum pump"],
    "ionate": ["alter", "change", "modify"],
    "ionesco": ["eugene ionesco"],
    "ionia": [],
    "ionian": ["greek", "hellene"],
    "ionian sea": [],
    "ionic": [],
    "ionic bond": ["bond", "chemical bond", "electrostatic bond", "electrovalent bond"],
    "ionic charge": ["constant"],
    "ionic order": ["ionian order", "order"],
    "ionization": ["condition", "ionisation", "status"],
    "ionization chamber": ["boron chamber", "geiger tube", "geiger-muller tube", "ionization tube", "measuring device", "measuring instrument", "measuring system"],
    "ionize": ["change", "ionise"],
    "ionized": ["ionised"],
    "ionizing radiation": ["alpha radiation", "alpha ray", "beta radiation", "beta ray", "cosmic ray", "electron radiation", "neutron radiation", "radiation", "roentgen ray", "x ray", "x-radiation", "x-ray"],
    "ionosphere": ["part", "region"],
    "ionospheric wave": ["sky wave"],
    "iontophoresis": ["electromotive drug administration", "emda", "ionic medication", "iontotherapy", "therapy"],
    "iota": ["alphabetic character", "letter", "letter of the alphabet"],
    "iou": ["note", "note of hand", "promissory note"],
    "iowa": ["ioway", "siouan", "sioux"],
    "iowa crab": ["bechtel crab", "crab apple", "crabapple", "flowering crab", "iowa crab apple", "malus ioensis", "prairie crab", "western crab apple", "wild apple"],
    "iowan": ["american"],
    "ipecac": ["emetic", "nauseant", "vomit", "vomitive"],
    "iphigenia": [],
    "ipod": ["stereo", "stereo system", "stereophonic system", "stereophony", "video ipod"],
    "ipomoea": ["dicot genus", "genus ipomoea", "magnoliopsid genus"],
    "ipratropium bromide": ["atrovent", "bronchodilator"],
    "iproclozide": ["maoi", "monoamine oxidase inhibitor"],
    "ipse dixit": ["assertion", "asseveration", "averment", "ipsedixitism"],
    "ipsilateral": [],
    "ipso facto": [],
    "ipsus": ["battle of ipsus"],
    "iran": ["islamic republic of iran", "persia"],
    "iran-iraq war": ["gulf war"],
    "irani": ["asian", "asiatic", "farsi", "iranian", "persian"],
    "iranian": ["afghan", "afghani", "avestan", "balochi", "baluchi", "dari", "dari persian", "farsi", "gathic", "indo-iranian", "indo-iranian language", "iranian language", "kurdish", "ossete", "pahlavi", "pashto", "pashtu", "paxto", "pehlevi", "persian", "scythian", "tadzhik", "tajik", "tajiki", "zend"],
    "iranian dinar": ["dinar", "iranian monetary unit"],
    "iranian monetary unit": ["dinar", "iranian dinar", "iranian rial", "monetary unit", "rial"],
    "iranian rial": ["iranian monetary unit", "rial"],
    "iraq": ["al-iraq", "irak", "republic of iraq"],
    "iraqi": ["asian", "asiatic", "hajji", "iraki"],
    "iraqi dinar": ["dinar", "iraqi monetary unit"],
    "iraqi intelligence service": ["iis", "international intelligence agency", "iraqi mukhabarat"],
    "iraqi kurdistan": [],
    "iraqi monetary unit": ["dinar", "iraqi dinar", "monetary unit"],
    "iraqi national congress": ["inc", "opposition"],
    "irascibility": ["bad temper", "ill temper", "quick temper", "short temper", "spleen"],
    "irate": ["ireful"],
    "irately": [],
    "ireland": ["eire", "irish republic", "republic of ireland"],
    "irena": ["bird genus", "genus irena"],
    "irenaeus": ["saint irenaeus", "st. irenaeus"],
    "irenic": [],
    "irenidae": ["bird family", "family irenidae"],
    "iresine": ["caryophylloid dicot genus", "genus iresine"],
    "iridaceae": ["family iridaceae", "genus iris", "iris family", "liliid monocot family"],
    "iridaceous": [],
    "iridaceous plant": ["belamcanda chinensis", "blackberry-lily", "blue-eyed grass", "bulbous plant", "corn lily", "crocus", "flag", "fleur-de-lis", "freesia", "glad", "gladiola", "gladiolus", "iris", "leopard lily", "sword lily"],
    "iridectomy": ["eye operation", "eye surgery"],
    "iridesce": ["be", "opalesce"],
    "iridescent": ["nacreous", "opalescent", "opaline", "pearlescent"],
    "iridic": [],
    "iridium": ["atomic number 77", "ir", "metal", "metallic element"],
    "iridocyclitis": ["inflammation", "redness", "rubor"],
    "iridokeratitis": ["inflammation", "redness", "rubor"],
    "iridoncus": ["lump", "puffiness", "swelling"],
    "iridoprocne": ["bird genus", "genus iridoprocne"],
    "iridotomy": ["eye operation", "eye surgery"],
    "iris": ["bearded iris", "beardless iris", "blue flag", "bulbous iris", "dwarf iris", "english iris", "flag", "fleur-de-lis", "gladdon", "gladdon iris", "iridaceous plant", "iris cristata", "iris foetidissima", "iris persica", "iris pseudacorus", "iris verna", "iris versicolor", "iris virginica", "iris xiphioides", "persian iris", "roast beef plant", "southern blue flag", "stinking gladwyn", "stinking iris", "sword lily", "vernal iris", "yellow flag", "yellow iris", "yellow water flag"],
    "iris scanning": ["biometric authentication", "biometric identification", "identity verification"],
    "irish": ["country", "irish people", "land", "nation"],
    "irish coffee": ["coffee", "java"],
    "irish monetary unit": ["irish pound", "irish punt", "monetary unit", "pound", "punt"],
    "irish moss": ["carageen", "carrageen", "carragheen", "chondrus crispus", "red algae"],
    "irish national liberation army": ["catholic reaction force", "inla", "people's liberation army", "people's republican army"],
    "irish person": ["dubliner", "european", "irelander", "irishman", "irishwoman"],
    "irish pound": ["irish monetary unit", "irish punt", "pound", "punt"],
    "irish republican army": ["ira", "provisional ira", "provisional irish republican army", "provos"],
    "irish sea": [],
    "irish setter": ["red setter", "setter"],
    "irish soda bread": ["quick bread"],
    "irish stew": ["stew"],
    "irish terrier": ["terrier"],
    "irish water spaniel": ["water spaniel"],
    "irish wolfhound": ["wolfhound"],
    "irishman": ["irelander", "irish person", "mick", "mickey", "paddy"],
    "irishwoman": ["irelander", "irish person"],
    "iritic": [],
    "iritis": ["inflammation", "redness", "rubor"],
    "iron": ["iron out", "mangle", "press"],
    "iron age": [],
    "iron blue": ["davy's gray", "davy's grey", "gray", "grayness", "grey", "greyness", "steel gray", "steel grey"],
    "iron cage": ["cage"],
    "iron curtain": ["ideological barrier"],
    "iron deficiency anemia": ["anaemia", "anemia", "chlorosis", "greensickness", "iron deficiency anaemia"],
    "iron disulfide": ["sulfide", "sulphide"],
    "iron filing": ["metal filing"],
    "iron fist": ["control"],
    "iron foundry": ["foundry", "metalworks"],
    "iron horse": ["engine", "locomotive", "locomotive engine", "railway locomotive"],
    "iron lung": ["inhalator", "respirator"],
    "iron maiden": ["instrument of torture"],
    "iron man": ["adult male", "ironman", "man"],
    "iron mold": ["discoloration", "discolouration", "iron mould", "stain"],
    "iron ore": ["chalybite", "chamosite", "goethite", "gothite", "haematite", "hematite", "lepidocrocite", "limonite", "magnetic iron-ore", "magnetite", "ore", "raddle", "reddle", "ruddle", "siderite", "taconite"],
    "iron out": ["ameliorate", "amend", "better", "improve", "meliorate", "put right", "straighten out"],
    "iron perchloride": ["perchloride"],
    "iron putty": ["cement"],
    "iron trap": ["snare", "trap"],
    "iron tree": ["angiospermous tree", "flowering tree", "iron-tree", "ironwood", "ironwood tree"],
    "iron-grey": ["gray", "grayness", "grey", "greyness", "iron-gray"],
    "ironclad": ["combat ship", "war vessel", "warship"],
    "ironed": [],
    "ironic": ["ironical"],
    "ironically": [],
    "ironing": ["flat wash", "flatwork", "garment", "household linen", "white goods"],
    "ironing board": ["board"],
    "ironlike": [],
    "ironmonger": ["bargainer", "dealer", "hardwareman", "monger", "trader"],
    "ironmongery": ["merchandise", "product", "ware"],
    "irons": ["bond", "chains", "hamper", "shackle", "trammel"],
    "ironshod": [],
    "ironside": ["adult male", "man"],
    "ironweed": ["herb", "herbaceous plant", "vernonia"],
    "ironwood": ["wood"],
    "ironwork": ["piece of work", "work"],
    "ironworker": ["maker", "puddler", "shaper"],
    "ironworks": ["work", "workplace"],
    "irony": ["dramatic irony", "figure", "figure of speech", "image", "trope"],
    "iroquoian": ["american indian", "american-indian language", "amerind", "amerindian language", "cayuga", "cherokee", "indian", "iroquoian language", "iroquois", "mohawk", "oneida", "onondaga", "seneca", "tuscarora"],
    "iroquois": ["american indian", "cayuga", "cherokee", "erie", "indian", "mohawk", "oneida", "onondaga", "red indian", "seneca", "tuscarora"],
    "iroquois league": ["five nations", "league", "league of iroquois", "six nations"],
    "irradiate": ["lighten", "lighten up"],
    "irradiation": ["condition", "status"],
    "irrational": [],
    "irrational hostility": ["bias", "preconception", "prejudice"],
    "irrational impulse": ["compulsion", "irrational motive", "irresistible impulse"],
    "irrational motive": ["cacoethes", "compulsion", "irrational impulse", "mania", "motivation", "motive", "need", "obsession", "passion"],
    "irrational number": ["algebraic number", "irrational", "real", "real number", "transcendental number"],
    "irrationality": ["insanity", "unreason"],
    "irrationally": [],
    "irrawaddy": ["irrawaddy river"],
    "irreclaimable": ["irredeemable", "unredeemable", "unreformable"],
    "irreconcilable": ["unreconcilable"],
    "irredeemable": [],
    "irredenta": ["irridenta", "region"],
    "irredentism": ["doctrine", "irridentism", "ism", "philosophical system", "philosophy", "school of thought"],
    "irredentist": ["advocate", "advocator", "exponent", "irridentist", "proponent"],
    "irreducible": [],
    "irregardless": [],
    "irregular": ["merchandise", "product", "second", "ware"],
    "irregularity": ["asymmetry", "dissymmetry", "geometrical irregularity", "imbalance"],
    "irregularly": [],
    "irrelevance": ["immateriality", "inapplicability", "irrelevancy", "unconnectedness"],
    "irrelevant": [],
    "irrelevantly": [],
    "irreligionist": ["disbeliever", "nonbeliever", "unbeliever"],
    "irreligious": [],
    "irreligiousness": ["impiety", "impiousness", "irreligion"],
    "irremediable": [],
    "irremovable": [],
    "irreparable": [],
    "irreparably": []
}
