synonyms = {
    "black cohosh": ["black snakeroot", "cimicifuga racemosa"],
    "black cottonwood": ["populus trichocarpa", "western balsam poplar"],
    "black crappie": ["pomoxis nigromaculatus"],
    "black currant": ["european black currant", "ribes nigrum"],
    "black cypress pine": ["callitris calcarata", "callitris endlicheri", "red cypress pine"],
    "black death": ["black plague"],
    "black disease": ["distomatosis", "liver rot", "sheep rot"],
    "black duck": ["anas rubripes"],
    "black flag": ["blackjack", "jolly roger", "pirate flag"],
    "black forest": ["schwarzwald"],
    "black grama": ["bouteloua eriopoda"],
    "black guillemot": ["cepphus grylle"],
    "black haw": ["viburnum prunifolium"],
    "black hawk": ["makataimeshekiakiak"],
    "black horehound": ["ballota nigra", "black archangel", "fetid horehound", "stinking horehound"],
    "black huckleberry": ["gaylussacia baccata"],
    "black humor": ["black humour"],
    "black kite": ["milvus migrans"],
    "black locust": ["robinia pseudoacacia", "yellow locust"],
    "black maire": ["olea cunninghamii"],
    "black mallee": ["black gum", "black sally", "eucalytus stellulata"],
    "black mamba": ["dendroaspis augusticeps"],
    "black mangrove": ["aegiceras majus"],
    "black marlin": ["makaira marlina", "makaira mazara"],
    "black medick": ["hop clover", "medicago lupulina", "nonesuch clover", "yellow trefoil"],
    "black morel": ["conic morel", "morchella angusticeps", "morchella conica", "narrowhead morel"],
    "black mulberry": ["morus nigra"],
    "black mustard": ["brassica nigra"],
    "black nightshade": ["common nightshade", "poisonberry", "solanum nigrum"],
    "black oak": ["quercitron", "quercitron oak", "quercus velutina", "yellow oak"],
    "black olive": ["ripe olive"],
    "black out": ["blacken out"],
    "black pea": ["lathyrus niger"],
    "black pine": ["pinus nigra"],
    "black poplar": ["populus nigra"],
    "black race": ["negro race", "negroid race"],
    "black raspberry": ["blackcap", "blackcap raspberry", "rubus occidentalis", "thimbleberry"],
    "black rat": ["rattus rattus", "roof rat"],
    "black rat snake": ["blacksnake", "elaphe obsoleta", "mountain blacksnake", "pilot blacksnake"],
    "black rhinoceros": ["diceros bicornis"],
    "black root rot fungus": ["xylaria mali"],
    "black sage": ["california romero", "trichostema lanatum", "wooly blue curls"],
    "black salsify": ["scorzonera", "scorzonera hispanica"],
    "black sea": ["euxine sea"],
    "black sea bass": ["black bass", "centropistes striata"],
    "black spruce": ["picea mariana", "spruce pine"],
    "black stork": ["ciconia nigra"],
    "black swan": ["cygnus atratus"],
    "black vulture": ["carrion crow", "coragyps atratus"],
    "black walnut": ["black hickory", "black walnut tree", "juglans nigra"],
    "black wattle": ["acacia auriculiformis"],
    "black widow": ["latrodectus mactans"],
    "blackberry": ["blackberry bush"],
    "blackbird": ["european blackbird", "merl", "merle", "ousel", "ouzel", "turdus merula"],
    "blackboard": ["chalkboard"],
    "blackbuck": ["antilope cervicapra", "black buck"],
    "blackburn": ["blackburnian warbler", "dendroica fusca"],
    "blackcap": ["silvia atricapilla"],
    "blackcock": ["black cock"],
    "blacken": ["black", "melanise", "melanize", "nigrify"],
    "blackening": ["darkening"],
    "blackfly": ["aphis fabae", "bean aphid"],
    "blackfoot daisy": ["melampodium leucanthum"],
    "blackhead": ["comedo"],
    "blackheart": ["blackheart cherry"],
    "blackjack": ["cosh", "sap"],
    "blackjack oak": ["blackjack", "jack oak", "quercus marilandica"],
    "blacklist": ["black book", "shitlist"],
    "blackmail": ["blackjack", "pressure"],
    "blackmailer": ["extortioner", "extortionist"],
    "blackmouth bass": ["synagrops bellus"],
    "blackout": ["brownout", "dimout"],
    "blackpoll": ["dendroica striate"],
    "blacksnake": ["black racer", "coluber constrictor"],
    "blacktail jackrabbit": ["lepus californicus"],
    "blacktail prairie dog": ["cynomys ludovicianus"],
    "blackthorn": ["prunus spinosa", "sloe"],
    "blacktip shark": ["carcharhinus limbatus", "sandbar shark"],
    "blacktop": ["blacktopping"],
    "blackwash": ["black lotion"],
    "blackwood": ["blackwood tree"],
    "bladder": ["vesica"],
    "bladder campion": ["silene uniflora", "silene vulgaris"],
    "bladder senna": ["colutea arborescens"],
    "bladder sphincter": ["musculus sphincter vesicae"],
    "bladder stone": ["cystolith"],
    "bladderwrack": ["ascophyllum nodosum"],
    "bladdery": ["bladderlike"],
    "blade": ["leaf blade"],
    "blair": ["anthony charles lynton blair", "tony blair"],
    "blake": ["william blake"],
    "blame": ["find fault", "pick"],
    "blameless": ["inculpable", "irreproachable", "unimpeachable"],
    "blamelessness": ["guiltlessness", "inculpability", "inculpableness"],
    "blameworthiness": ["culpability", "culpableness"],
    "blameworthy": ["blamable", "blameable", "blameful", "censurable", "culpable"],
    "blanch": ["parboil"],
    "bland": ["flat", "flavorless", "flavourless", "insipid", "savorless", "savourless", "vapid"],
    "bland diet": ["ulcer diet"],
    "blandfordia": ["genus blandfordia"],
    "blandishment": ["cajolery", "palaver"],
    "blandness": ["insipidity", "insipidness"],
    "blank": ["blank shell", "dummy"],
    "blank check": ["blank cheque"],
    "blank endorsement": ["endorsement in blank"],
    "blanket": ["mantle"],
    "blanket flower": ["fire wheel", "gaillardia pulchella", "indian blanket"],
    "blanquillo": ["tilefish"],
    "blare": ["blaring", "cacophony", "clamor", "din"],
    "blare out": ["blat out"],
    "blarina": ["genus blarina"],
    "blaring": ["blasting"],
    "blarney": ["coaxing", "soft soap", "sweet talk"],
    "blase": ["worldly"],
    "blasphemous": ["profane", "sacrilegious"],
    "blast": ["blare"],
    "blasted": ["blame", "blamed", "blessed", "damn", "damned", "darned", "deuced", "goddam", "goddamn", "goddamned", "infernal"],
    "blastemal": ["blastematic", "blastemic"],
    "blaster": ["chargeman"],
    "blasting": ["ruinous"],
    "blastocladia": ["genus blastocladia"],
    "blastocladiales": ["order blastocladiales"],
    "blastocoel": ["blastocele", "blastocoele", "cleavage cavity", "segmentation cavity"],
    "blastocyst": ["blastodermic vessicle"],
    "blastoderm": ["blastodisc", "germinal area", "germinal disc"],
    "blastodermatic": ["blastodermic"],
    "blastodiaceae": ["family blastodiaceae"],
    "blastoff": ["shot"],
    "blastoma": ["blastocytoma", "embryonal carcinosarcoma"],
    "blastomyces": ["genus blastomyces"],
    "blastoporal": ["blastoporic"],
    "blastospheric": ["blastular"],
    "blastula": ["blastosphere"],
    "blatant": ["blazing", "conspicuous"],
    "blather": ["blatherskite"],
    "blatta": ["genus blatta"],
    "blattella": ["genus blattella"],
    "blattidae": ["family blattidae"],
    "blattodea": ["blattaria", "suborder blattaria", "suborder blattodea"],
    "blaze": ["blaze out"],
    "blaze away": ["blaze"],
    "blazer": ["sport coat", "sport jacket", "sports coat", "sports jacket"],
    "blazing": ["blinding", "dazzling", "fulgent", "glaring", "glary"],
    "blazing star": ["mentzelia laevicaulis", "mentzelia livicaulis"],
    "bleach": ["bleach out", "decolor", "decolorise", "decolorize", "decolour", "decolourise", "decolourize", "discolorise", "discolorize", "discolourise"],
    "bleached": ["colored", "coloured", "dyed"],
    "bleaching agent": ["blanching agent", "bleach", "whitener"],
    "bleaching clay": ["bleaching earth"],
    "bleaching powder": ["chloride of lime", "chlorinated lime"],
    "bleak": ["cutting", "raw"],
    "bleakness": ["bareness", "desolation", "nakedness"],
    "bleary": ["blear"],
    "bleat": ["baa", "blat", "blate"],
    "blebbed": ["blebby"],
    "blebby": ["blistery"],
    "blechnaceae": ["family blechnaceae"],
    "blechnum": ["genus blechnum"],
    "bleed": ["leech", "phlebotomise", "phlebotomize"],
    "bleeding": ["haemorrhage", "hemorrhage"],
    "bleeding heart": ["dicentra spectabilis", "lyreflower"],
    "bleeding tooth": ["nerita peloronta"],
    "blemish": ["spot"],
    "blemished": ["flawed"],
    "blend": ["blend in", "go"],
    "blend in": ["mix in"],
    "blended whiskey": ["blended whisky"],
    "blender": ["liquidiser", "liquidizer"],
    "blenniidae": ["family blenniidae"],
    "blennioid fish": ["blennioid"],
    "blennioidea": ["suborder blennioidea"],
    "blennius": ["genus blennius"],
    "blenny": ["combtooth blenny"],
    "blephilia": ["genus blephilia"],
    "bleriot": ["louis bleriot"],
    "bless": ["sign"],
    "blessed": ["blest"],
    "blessed event": ["happy event"],
    "blessed thistle": ["cnicus benedictus", "sweet sultan"],
    "blessedness": ["beatification", "beatitude"],
    "blessing": ["boon"],
    "bletilla": ["genus bletilla"],
    "bletilla striata": ["bletia striata"],
    "bleu": ["blue cheese"],
    "bleu cheese dressing": ["blue cheese dressing"],
    "blewits": ["clitocybe nuda"],
    "bligh": ["captain bligh", "william bligh"],
    "blighia": ["genus blighia"],
    "blight": ["plague"],
    "blighted": ["spoilt"],
    "blimp": ["sausage", "sausage balloon"],
    "blind": ["dim"],
    "blind alley": ["cul de sac", "impasse"],
    "blind curve": ["blind bend"],
    "blind flying": ["blind landing"],
    "blind snake": ["worm snake"],
    "blind spot": ["optic disc", "optic disk"],
    "blindfold": ["blindfolded"],
    "blindness": ["cecity", "sightlessness"],
    "blindworm": ["anguis fragilis", "slowworm"],
    "bling": ["bling bling"],
    "blini": ["bliny"],
    "blink": ["nictate", "nictitate", "wink"],
    "blink of an eye": ["flash", "heartbeat", "instant", "jiffy", "new york minute", "split second", "trice", "twinkling", "wink"],
    "blinker": ["trafficator", "turn indicator", "turn signal"],
    "blinking": ["winking"],
    "blinks": ["blinking chickweed", "montia lamprosperma", "water chickweed"],
    "blintz": ["blintze"],
    "blip": ["pip", "radar target"],
    "bliss": ["blissfulness", "cloud nine", "seventh heaven", "walking on air"],
    "blissus": ["genus blissus"],
    "blister": ["scald", "whip"],
    "blister beetle": ["meloid"],
    "blister pack": ["bubble pack"],
    "blister rust": ["white pine blister rust"],
    "blistering": ["blistery"],
    "blithe": ["blithesome", "lighthearted", "lightsome"],
    "blitz": ["blitzkrieg"],
    "blitzstein": ["marc blitzstein"],
    "blizzard": ["snowstorm"],
    "bloc": ["axis"],
    "bloch": ["ernest bloch"],
    "block": ["cube"],
    "block letter": ["block capital"],
    "blockade": ["block off"],
    "blockage": ["block", "closure", "occlusion", "stop", "stoppage"],
    "blockbuster": ["megahit", "smash hit"],
    "blocked": ["out of use"],
    "blocker": ["blocking agent"],
    "blockheaded": ["boneheaded", "duncical", "duncish", "fatheaded", "loggerheaded", "thick", "thickheaded"],
    "blocking": ["block"],
    "blockish": ["blocky"],
    "blok": ["aleksandr aleksandrovich blok", "alexander alexandrovich blok"],
    "blolly": ["chiococca alba", "west indian snowberry"],
    "blond": ["blonde"],
    "blood cell": ["blood corpuscle", "corpuscle"],
    "blood clot": ["grume"],
    "blood coagulation": ["blood clotting"],
    "blood cup": ["fairy cup", "peziza coccinea"],
    "blood disease": ["blood disorder"],
    "blood flower": ["asclepias curassavica", "swallowwort"],
    "blood group": ["blood type"],
    "blood poisoning": ["septicaemia", "septicemia"],
    "blood relation": ["blood relative", "cognate", "sib"],
    "blood sausage": ["black pudding", "blood pudding"],
    "blood sugar": ["blood glucose"],
    "bloodbath": ["battue", "bloodletting", "bloodshed"],
    "bloodberry": ["blood berry", "rivina humilis", "rouge plant", "rougeberry"],
    "bloodcurdling": ["nightmarish"],
    "bloodhound": ["sleuthhound"],
    "bloodiness": ["bloodthirstiness"],
    "bloodless": ["exsanguine", "exsanguinous"],
    "bloodroot": ["puccoon", "redroot", "sanguinaria canadensis", "tetterwort"],
    "bloodshed": ["gore"],
    "bloodstained": ["gory"],
    "bloodstone": ["heliotrope"],
    "bloodstream": ["blood stream"],
    "bloodthirsty": ["sanguinary"],
    "bloodwood tree": ["kiaat", "pterocarpus angolensis"],
    "bloody": ["damn"],
    "bloom": ["blossom", "flower"],
    "bloomeria": ["genus bloomeria"],
    "bloomers": ["drawers", "knickers", "pants"],
    "bloomfield": ["leonard bloomfield"],
    "blooming": ["bloom"],
    "blossom": ["blossom forth", "blossom out", "unfold"],
    "blossoming": ["anthesis", "efflorescence", "florescence", "flowering", "inflorescence"],
    "blot": ["smear", "smirch", "spot", "stain"],
    "blotch": ["splodge", "splotch"],
    "blotched": ["blotchy", "splotched"],
    "blotted out": ["obliterate", "obliterated"],
    "blotter": ["charge sheet", "day book", "police blotter", "rap sheet"],
    "blotting paper": ["blotter"],
    "blow": ["bump"],
    "blow gas": ["blowing gas"],
    "blow out": ["blow", "burn out"],
    "blow up": ["enlarge", "magnify"],
    "blowback": ["backfire"],
    "blowfish": ["puffer", "pufferfish", "sea squab"],
    "blowfly": ["blow fly"],
    "blowgun": ["blow tube", "blowpipe", "blowtube"],
    "blown": ["pursy", "winded"],
    "blowsy": ["blowzy", "slatternly", "sluttish"],
    "blowtorch": ["blowlamp", "torch"],
    "blowtube": ["blow tube", "blowpipe"],
    "blowy": ["breezy", "windy"],
    "blubber": ["blubber out"],
    "blucher": ["gebhard leberecht von blucher", "von blucher"],
    "blue": ["blueness"],
    "blue ash": ["fraxinus quadrangulata"],
    "blue catfish": ["blue cat", "blue channel cat", "blue channel catfish"],
    "blue cheese dressing": ["roquefort dressing"],
    "blue cohosh": ["blueberry root", "caulophyllum thalictrioides", "caulophyllum thalictroides", "papoose root", "papooseroot", "squaw root", "squawroot"],
    "blue columbine": ["aquilegia caerulea", "aquilegia scopulorum calcarea"],
    "blue crab": ["callinectes sapidus"],
    "blue daisy": ["blue marguerite", "felicia amelloides"],
    "blue elder": ["blue elderberry", "sambucus caerulea"],
    "blue false indigo": ["baptisia australis"],
    "blue flag": ["iris versicolor"],
    "blue fleabane": ["erigeron acer"],
    "blue goose": ["chen caerulescens"],
    "blue grama": ["bouteloua gracilis"],
    "blue gum": ["eucalyptus globulus", "fever tree"],
    "blue jasmine": ["blue jessamine", "clematis crispa", "curly clematis", "marsh clematis"],
    "blue jay": ["cyanocitta cristata", "jaybird"],
    "blue lotus": ["nymphaea stellata"],
    "blue marlin": ["makaira nigricans"],
    "blue mockingbird": ["melanotis caerulescens"],
    "blue mold fungus": ["peronospora tabacina"],
    "blue mountain tea": ["solidago odora", "sweet goldenrod"],
    "blue orchid": ["vanda caerulea"],
    "blue pea": ["butterfly pea", "clitoria turnatea"],
    "blue peafowl": ["pavo cristatus"],
    "blue pike": ["blue pickerel", "blue pikeperch", "blue walleye", "strizostedion vitreum glaucum"],
    "blue pimpernel": ["blue skullcap", "scutellaria lateriflora"],
    "blue poppy": ["meconopsis betonicifolia"],
    "blue racer": ["coluber constrictor flaviventris"],
    "blue ribbon": ["cordon bleu"],
    "blue ribbon commission": ["blue ribbon committee"],
    "blue ridge mountains": ["blue ridge"],
    "blue sage": ["salvia lancifolia", "salvia reflexa"],
    "blue shark": ["great blue shark", "prionace glauca"],
    "blue sky": ["blue", "blue air", "wild blue yonder"],
    "blue star": ["amsonia tabernaemontana"],
    "blue succory": ["catananche caerulea"],
    "blue tit": ["parus caeruleus", "tomtit"],
    "blue toadflax": ["linaria canadensis"],
    "blue vitriol": ["blue copperas", "blue stone", "chalcanthite"],
    "blue wall of silence": ["blue wall", "wall of silence"],
    "blue whale": ["balaenoptera musculus", "sulfur bottom"],
    "blueberry": ["blueberry bush"],
    "bluebonnet": ["buffalo clover", "lupinus subcarnosus", "texas bluebonnet"],
    "bluebottle": ["calliphora vicina"],
    "bluefin": ["bluefin tuna"],
    "bluefish": ["pomatomus saltatrix"],
    "bluegill": ["lepomis macrochirus"],
    "bluegrass": ["blue grass"],
    "bluehead": ["thalassoma bifasciatum"],
    "bluejack oak": ["quercus incana", "turkey oak"],
    "bluejacket": ["navy man", "sailor", "sailor boy"],
    "bluepoint": ["blue point"],
    "blueprint": ["draft", "draught"],
    "blues": ["blue devils", "megrims", "vapors", "vapours"],
    "bluestem": ["andropogon furcatus", "andropogon gerardii", "blue stem"],
    "bluestocking": ["bas bleu"],
    "bluethroat": ["erithacus svecicus"],
    "bluethroat pikeblenny": ["chaenopsis ocellata"],
    "blueweed": ["blue devil", "blue thistle", "echium vulgare"],
    "bluewing": ["anas discors"],
    "bluff": ["bluff out"],
    "bluffly": ["bluntly", "brusquely", "flat out", "roundly"],
    "bluing": ["blue", "blueing"],
    "bluish green": ["blue green", "teal"],
    "blunder": ["bloomer", "blooper", "boner", "botch", "bungle", "flub", "fuckup", "pratfall"],
    "blunt": ["candid", "forthright", "frank", "outspoken", "plainspoken"],
    "blunted": ["dulled"],
    "blur": ["blear"],
    "blurred": ["clouded"],
    "blurt out": ["blunder", "blunder out", "blurt", "ejaculate"],
    "blush": ["crimson", "flush", "redden"],
    "blush wine": ["pink wine", "rose", "rose wine"],
    "blushful": ["blushing"],
    "blushing mushroom": ["amanita rubescens", "blusher"],
    "blustering": ["blusterous", "blustery"],
    "blustery": ["bullying"],
    "bo hai": ["po hai"],
    "boa constrictor": ["constrictor constrictor"],
    "board": ["room"],
    "board meeting": ["committee meeting"],
    "boarding": ["embarkation", "embarkment"],
    "boarding card": ["boarding pass"],
    "boarding house": ["boardinghouse"],
    "boardroom": ["council chamber"],
    "boarfish": ["capros aper"],
    "boast": ["blow", "bluster", "brag", "gas", "gasconade", "shoot a line", "swash", "tout", "vaunt"],
    "boastful": ["big", "braggart", "bragging", "braggy", "crowing"],
    "boastfully": ["big", "large", "vauntingly"],
    "boastfulness": ["vainglory"],
    "boatbill": ["broadbill", "cochlearius cochlearius"],
    "boater": ["leghorn", "panama", "panama hat", "sailor", "skimmer", "straw hat"],
    "boating": ["yachting"],
    "boatload": ["carload", "shipload"],
    "boatman": ["boater", "waterman"],
    "boatswain": ["bosun"],
    "bob": ["bobber", "bobfloat", "cork"],
    "bob around": ["bob about"],
    "bobbin": ["reel", "spool"],
    "bobby pin": ["grip", "hairgrip"],
    "bobcat": ["bay lynx", "lynx rufus"],
    "bobolink": ["dolichonyx oryzivorus", "reedbird", "ricebird"],
    "bobsled": ["bob"],
    "bobtail": ["bob", "dock"],
    "bobwhite": ["bobwhite quail", "partridge"],
    "boccaccio": ["giovanni boccaccio"],
    "bocce": ["bocci", "boccie"],
    "bocce ball": ["bocci ball", "boccie ball"],
    "bocconia": ["bocconia frutescens", "tree celandine"],
    "bock": ["bock beer"],
    "bode": ["augur", "auspicate", "betoken", "forecast", "foreshadow", "foretell", "omen", "portend", "predict", "prefigure", "presage", "prognosticate"],
    "bodhisattva": ["boddhisatva"],
    "bodied": ["corporal", "corporate", "embodied", "incarnate"],
    "bodiless": ["bodyless"],
    "bodily": ["corporal", "corporeal", "somatic"],
    "bodily process": ["activity", "bodily function", "body process"],
    "bodkin": ["threader"],
    "bodoni": ["gianbattista bodoni"],
    "body": ["personify"],
    "body armor": ["body armour", "cataphract", "coat of mail", "suit of armor", "suit of armour"],
    "body bag": ["human remains pouch", "personnel pouch"],
    "body louse": ["cootie", "pediculus corporis"],
    "body mass index": ["bmi"],
    "body odor": ["body odour"],
    "body of water": ["water"],
    "body temperature": ["blood heat"],
    "body type": ["somatotype"],
    "body waste": ["excrement", "excreta", "excretion", "excretory product"],
    "bodybuilder": ["muscle builder", "musclebuilder", "muscleman"],
    "bodybuilding": ["anaerobic exercise", "muscle building", "musclebuilding"],
    "bodyguard": ["escort"],
    "boehme": ["behmen", "boehm", "bohme", "jakob behmen", "jakob boehm", "jakob boehme", "jakob bohme"],
    "boehmenism": ["behmenism"],
    "boehmeria": ["genus boehmeria"],
    "boell": ["heinrich boell", "heinrich theodor boell"],
    "boethius": ["anicius manlius severinus boethius"],
    "bog": ["peat bog"],
    "bog bilberry": ["bog whortleberry", "moor berry", "vaccinium uliginosum alpinum"],
    "bog down": ["bog"],
    "bog pimpernel": ["anagallis tenella"],
    "bog rein orchid": ["bog candles", "habenaria dilatata"],
    "bog rose": ["arethusa bulbosa", "wild pink"],
    "bog rosemary": ["andromeda glaucophylla", "moorwort"],
    "bog star": ["parnassia palustris"],
    "bogart": ["humphrey bogart", "humphrey deforest bogart"],
    "bogey": ["bogie", "bogy"],
    "bogeyman": ["booger", "boogeyman", "bugaboo", "bugbear"],
    "boggy": ["marshy", "miry", "mucky", "muddy", "quaggy", "sloppy", "sloughy", "soggy", "squashy", "swampy", "waterlogged"],
    "bogota": ["capital of colombia"],
    "bogus": ["bastard", "fake", "phoney", "phony"],
    "bogy": ["bogey", "bogie"],
    "bohemian waxwing": ["bombycilla garrulus"],
    "bohr": ["niels bohr", "niels henrik david bohr"],
    "bohrium": ["bh"],
    "boidae": ["family boidae"],
    "boil": ["furuncle"],
    "boil down": ["concentrate", "decoct", "reduce"],
    "boil over": ["overboil"],
    "boil smut": ["ustilago maydis"],
    "boiled": ["poached", "stewed"],
    "boiled dinner": ["new england boiled dinner"],
    "boiled egg": ["coddled egg"],
    "boiler": ["steam boiler"],
    "boiling": ["simmering", "stewing"],
    "boiling point": ["boil"],
    "boiling water reactor": ["bwr"],
    "boise": ["capital of idaho"],
    "boisterous": ["knockabout"],
    "bok choy": ["bok choi", "brassica rapa chinensis", "chinese white cabbage", "pak choi", "pakchoi"],
    "bokmal": ["bokmaal"],
    "bolbitis": ["genus bolbitis"],
    "boldface": ["bold", "bold face"],
    "boldness": ["daring", "hardihood", "hardiness"],
    "bole": ["bolanci"],
    "boletaceae": ["family boletaceae"],
    "boletellus": ["genus boletellus"],
    "boletus": ["genus boletus"],
    "boleyn": ["anne boleyn"],
    "bolide": ["fireball"],
    "bolivar": ["el libertador", "simon bolivar"],
    "bolivia": ["republic of bolivia"],
    "boll weevil": ["anthonomus grandis"],
    "bollard": ["bitt"],
    "bollock": ["bullock block"],
    "bolo": ["bolo knife"],
    "bolo tie": ["bola", "bola tie", "bolo"],
    "bologna": ["bologna sausage"],
    "bologram": ["bolograph"],
    "bolshevik": ["bolshevist"],
    "bolshevism": ["collectivism", "sovietism"],
    "bolshy": ["stroppy"],
    "bolster": ["bolster up"],
    "bolt": ["deadbolt"],
    "bolti": ["tilapia nilotica"],
    "boltonia": ["genus boltonia"],
    "boltzmann": ["ludwig boltzmann"],
    "bomarea": ["genus bomarea"],
    "bomb calorimeter": ["bomb"],
    "bomb shelter": ["bombproof"],
    "bombacaceae": ["family bombacaceae"],
    "bombard": ["bomb"],
    "bombardon": ["bombard"],
    "bombast": ["blah", "claptrap", "fustian", "rant"],
    "bombastic": ["declamatory", "large", "orotund", "tumid", "turgid"],
    "bombastically": ["grandiosely"],
    "bombax": ["genus bombax"],
    "bomber": ["cuban sandwich", "grinder", "hero", "hero sandwich", "hoagie", "hoagy", "italian sandwich", "poor boy", "sub", "submarine", "submarine sandwich", "torpedo", "wedge", "zep"],
    "bomber crew": ["bomber aircrew"],
    "bombina": ["genus bombina"],
    "bombing": ["bombardment"],
    "bomblet": ["cluster bomblet"],
    "bombproof": ["shellproof"],
    "bombshell": ["thunderbolt", "thunderclap"]
}
