synonyms = {
    "vestry": ["sacristy"],
    "vesuvianite": ["idocrase", "vesuvian"],
    "vesuvius": ["mount vesuvius"],
    "veteran": ["veteran soldier"],
    "veterans day": ["armistice day"],
    "veterans of foreign wars": ["vfw"],
    "veterinarian": ["vet", "veterinary", "veterinary surgeon"],
    "vetluga": ["vetluga river"],
    "veto": ["blackball", "negative"],
    "viatical settlement": ["viaticus settlement"],
    "viatication": ["viaticus"],
    "vibist": ["vibraphonist"],
    "vibrant": ["vivacious"],
    "vibraphone": ["vibes", "vibraharp"],
    "vibration": ["vibe"],
    "vibrio": ["vibrion"],
    "viburnum": ["genus viburnum"],
    "vicariate": ["vicarship"],
    "vice versa": ["contrariwise", "the other way around"],
    "viceroy": ["vicereine"],
    "vicia": ["genus vicia"],
    "vicinity": ["locality", "neck of the woods", "neighborhood", "neighbourhood"],
    "vicious circle": ["vicious cycle"],
    "viciously": ["brutally", "savagely"],
    "vicksburg": ["siege of vicksburg"],
    "victim": ["dupe"],
    "victimize": ["victimise"],
    "victimizer": ["victimiser"],
    "victor": ["master", "superior"],
    "victoria": ["queen victoria"],
    "victoria sandwich": ["victoria sponge"],
    "victorious": ["winning"],
    "victory": ["triumph"],
    "victory lap": ["lap of honour"],
    "victualer": ["victualler"],
    "vicugna": ["genus vicugna"],
    "vicuna": ["vicugna vicugna"],
    "vidal": ["eugene luther vidal", "gore vidal"],
    "video": ["picture"],
    "video recording": ["video"],
    "videocassette recorder": ["vcr"],
    "videodisk": ["dvd", "videodisc"],
    "videotape": ["tape"],
    "vidua": ["genus vidua"],
    "vienna": ["austrian capital", "capital of austria"],
    "vienne": ["council of vienne"],
    "vientiane": ["capital of laos", "laotian capital"],
    "vietnam": ["annam", "socialist republic of vietnam", "viet nam"],
    "vietnam war": ["vietnam"],
    "vietnamese": ["annamese"],
    "view": ["consider", "look at"],
    "view angle": ["angle of view"],
    "viewgraph": ["overhead"],
    "viewing audience": ["tv audience", "viewers"],
    "vigil": ["watch"],
    "vigil light": ["vigil candle"],
    "vigilante": ["vigilance man"],
    "vigilantly": ["watchfully"],
    "vigna": ["genus vigna"],
    "vigor": ["dynamism", "heartiness", "vigour"],
    "vigorously": ["smartly"],
    "vilify": ["rail", "revile", "vituperate"],
    "villa": ["doroteo arango", "francisco villa", "pancho villa"],
    "village": ["hamlet"],
    "villahermosa": ["villa hermosa"],
    "villain": ["baddie"],
    "villainy": ["villainousness"],
    "villard": ["henry villard"],
    "villeinage": ["villainage"],
    "villon": ["francois villon"],
    "vilnius": ["capital of lithuania", "vilna", "vilno", "wilno"],
    "viminaria": ["genus viminaria"],
    "vinblastine": ["velban"],
    "vinca": ["genus vinca"],
    "vincetoxicum": ["genus vincetoxicum"],
    "vincristine": ["oncovin"],
    "vindication": ["exoneration"],
    "vindictiveness": ["vengefulness"],
    "vine maple": ["acer circinatum"],
    "vinegar": ["acetum"],
    "vinegar eel": ["anguillula aceti", "turbatrix aceti", "vinegar worm"],
    "vinegariness": ["vinegarishness"],
    "vinegarroon": ["mastigoproctus giganteus"],
    "vinegary": ["vinegarish"],
    "vineyard": ["vinery"],
    "vinifera": ["common grape vine", "vinifera grape", "vitis vinifera"],
    "vinogradoff": ["sir paul gavrilovich vinogradoff"],
    "vinous": ["vinaceous"],
    "vinson": ["frederick moore vinson"],
    "vintage": ["time of origin"],
    "vintner": ["wine merchant"],
    "vinyl": ["vinyl group", "vinyl radical"],
    "vinyl polymer": ["polyvinyl resin", "vinyl resin"],
    "viola": ["genus viola"],
    "viola da gamba": ["bass viol", "gamba"],
    "violaceae": ["family violaceae", "violet family"],
    "violate": ["break", "go against"],
    "violation": ["infringement"],
    "violator": ["law offender", "lawbreaker"],
    "violence": ["force"],
    "violent": ["wild"],
    "violet": ["reddish blue"],
    "violet suksdorfia": ["suksdorfia violaceae"],
    "violet wood sorrel": ["oxalis violacea"],
    "violin": ["fiddle"],
    "violinist": ["fiddler"],
    "viomycin": ["viocin"],
    "vipera": ["genus vipera"],
    "viperidae": ["family viperidae"],
    "viperine grass snake": ["natrix maura"],
    "viral infection": ["virus infection"],
    "virchow": ["rudolf karl virchow", "rudolf virchow"],
    "viremia": ["viraemia"],
    "vireonidae": ["family vireonidae"],
    "virgil": ["publius vergilius maro", "vergil"],
    "virgilia": ["genus virgilia"],
    "virgin birth": ["nativity"],
    "virgin mary": ["bloody shame"],
    "virginal": ["pair of virginals"],
    "virginia": ["old dominion", "old dominion state", "va"],
    "virginia bluebell": ["mertensia virginica", "virginia cowslip"],
    "virginia chain fern": ["woodwardia virginica"],
    "virginia creeper": ["american ivy", "parthenocissus quinquefolia", "woodbine"],
    "virginia crownbeard": ["frostweed", "verbesina virginica"],
    "virginia deer": ["odocoileus virginianus", "white tail", "whitetail", "whitetail deer"],
    "virginia mallow": ["sida hermaphrodita"],
    "virginia reel": ["reel"],
    "virginia snakeroot": ["aristolochia serpentaria", "virginia serpentaria", "virginia serpentary"],
    "virginia spring beauty": ["claytonia virginica"],
    "virginia strawberry": ["fragaria virginiana", "scarlet strawberry"],
    "virginia thimbleweed": ["anemone virginiana"],
    "virginia waterleaf": ["hydrophyllum virginianum", "indian salad", "shawnee salad", "shawny"],
    "virginian stock": ["malcolmia maritima", "virginia stock"],
    "virginian witch hazel": ["hamamelis virginiana"],
    "virgo": ["virgin"],
    "viricidal": ["virucidal"],
    "viricide": ["virucide"],
    "viroid": ["virusoid"],
    "virtu": ["connoisseurship", "vertu"],
    "virtual": ["practical"],
    "virtual memory": ["virtual storage"],
    "virtue": ["chastity", "sexual morality"],
    "virulence": ["virulency"],
    "virus": ["computer virus"],
    "visayan": ["bisayan"],
    "visayan islands": ["bisayas"],
    "viscaceae": ["family viscaceae", "mistletoe family"],
    "viscacha": ["chinchillon", "lagostomus maximus"],
    "viscera": ["entrails", "innards"],
    "visceral": ["splanchnic"],
    "visceral leishmaniasis": ["assam fever", "dumdum fever"],
    "viscerally": ["unreasoningly"],
    "viscometer": ["viscosimeter"],
    "viscometric": ["viscosimetric"],
    "viscometry": ["viscosimetry"],
    "visconti": ["don luchino visconti conte di modrone", "luchino visconti"],
    "viscose rayon": ["viscose"],
    "viscosity": ["viscousness"],
    "viscountcy": ["viscounty"],
    "viscum": ["genus viscum"],
    "vise": ["bench vise"],
    "visibility": ["profile"],
    "visible": ["seeable"],
    "visible spectrum": ["color spectrum"],
    "vision": ["visual sensation"],
    "visionary": ["illusionist", "seer"],
    "visit": ["see"],
    "visitor": ["visitant"],
    "visor": ["vizor"],
    "vistula": ["vistula river"],
    "visual aphasia": ["alexia", "word blindness"],
    "visual area": ["visual cortex"],
    "visual display unit": ["vdu"],
    "visual field": ["field of regard", "field of vision"],
    "visual image": ["visualisation", "visualization"],
    "visual impairment": ["vision defect", "visual defect", "visual disorder"],
    "visual percept": ["visual image"],
    "visual perception": ["beholding", "seeing"],
    "visual purple": ["retinal purple", "rhodopsin"],
    "visualize": ["visualise"],
    "visualizer": ["visualiser"],
    "vitaceae": ["family vitaceae", "grapevine family", "vitidaceae"],
    "vital organ": ["vitals"],
    "vital principle": ["life principle"],
    "vitality": ["verve"],
    "vitalization": ["vitalisation"],
    "vitalize": ["vitalise"],
    "vitamin a": ["antiophthalmic factor", "axerophthol"],
    "vitamin bc": ["folacin", "folate", "folic acid", "pteroylglutamic acid", "pteroylmonoglutamic acid", "vitamin m"],
    "vitamin c": ["ascorbic acid"],
    "vitamin d": ["calciferol", "cholecalciferol", "ergocalciferol", "viosterol"],
    "vitamin e": ["tocopherol"],
    "vitamin k": ["antihemorrhagic factor", "naphthoquinone"],
    "vitamin p": ["bioflavinoid", "citrin"],
    "vitaminize": ["vitaminise"],
    "vitharr": ["vidar", "vithar"],
    "viticulture": ["viniculture"],
    "vitis": ["genus vitis"],
    "vitreous humor": ["vitreous body", "vitreous humour"],
    "vitriol": ["oil of vitriol", "sulfuric acid", "sulphuric acid"],
    "vittaria": ["genus vittaria"],
    "vittariaceae": ["family vittariaceae"],
    "vituperation": ["invective", "vitriol"],
    "vivaldi": ["antonio lucio vivaldi", "antonio vivaldi"],
    "viverra": ["genus viverra"],
    "viverricula": ["genus viverricula"],
    "viverridae": ["family viverridae", "family viverrinae", "viverrinae"],
    "viverrine": ["viverrine mammal"],
    "vivification": ["animation", "invigoration"],
    "viviparous eelpout": ["zoarces viviparus"],
    "vixen": ["harpy", "hellcat"],
    "vizcaino": ["sebastian vizcaino"],
    "vizsla": ["hungarian pointer"],
    "vlaminck": ["maurice de vlaminck"],
    "vocable": ["spoken word"],
    "vocabulary": ["lexicon", "mental lexicon"],
    "vocal cord": ["plica vocalis", "vocal band", "vocal fold"],
    "vocal music": ["vocal"],
    "vocalize": ["vocalise"],
    "vocational training": ["vocational education"],
    "vocative": ["vocative case"],
    "vociferate": ["shout out"],
    "vogue": ["style", "trend"],
    "vogul": ["mansi"],
    "voice": ["sound", "vocalise", "vocalize"],
    "voice mail": ["voicemail"],
    "voiced": ["soft", "sonant"],
    "void": ["emptiness", "vacancy", "vacuum"],
    "voider": ["gusset"],
    "volatility": ["unpredictability"],
    "volatilize": ["volatilise"],
    "volcanic crater": ["crater"],
    "volcanic eruption": ["eruption"],
    "volcanology": ["vulcanology"],
    "vole": ["field mouse"],
    "volga": ["volga river"],
    "volgograd": ["stalingrad", "tsaritsyn"],
    "volition": ["will"],
    "volkhov": ["volkhov river"],
    "volleyball": ["volleyball game"],
    "volta": ["conte alessandro giuseppe antonio anastasio volta", "conte alessandro volta", "count alessandro volta"],
    "voltage": ["electromotive force", "emf"],
    "voltaic": ["galvanic"],
    "voltaic battery": ["galvanic battery"],
    "voltaic cell": ["galvanic cell", "primary cell"],
    "voltaic pile": ["galvanic pile", "pile"],
    "voltaire": ["arouet"],
    "voltarian": ["voltarean"],
    "volume": ["intensity", "loudness"],
    "volume unit": ["capacity measure", "capacity unit", "cubage unit", "cubature unit", "cubic content unit", "cubic measure", "displacement unit"],
    "volumetric": ["volumetrical"],
    "volunteer": ["offer"],
    "voluptuary": ["sybarite"],
    "volvaria": ["genus volvaria"],
    "volvariaceae": ["family volvariaceae"],
    "volvariella": ["genus volvariella"],
    "volvocaceae": ["family volvocaceae"],
    "volvocales": ["order volvocales"],
    "volvox": ["genus volvox"],
    "vombatidae": ["family vombatidae"],
    "vomit": ["barf", "be sick", "cast", "cat", "chuck", "disgorge", "honk", "puke", "purge", "regorge", "regurgitate", "retch", "sick", "spew", "spue", "throw up", "upchuck", "vomit up"],
    "vomiter": ["spewer"],
    "von neumann": ["john von neumann", "neumann"],
    "von sternberg": ["josef von sternberg"],
    "vonnegut": ["kurt vonnegut"],
    "voodoo": ["hoodooism", "vodoun", "voodooism"],
    "vortex vein": ["vena vorticosum", "vorticose vein"],
    "vote": ["voter turnout"],
    "voter": ["elector"],
    "voting precinct": ["election district"],
    "voting system": ["electoral system"],
    "voucher": ["verifier"],
    "vow": ["consecrate"],
    "vowel": ["vowel sound"],
    "vowel system": ["vocalism"],
    "vox angelica": ["voix celeste"],
    "voyage": ["navigate", "sail"],
    "voyeur": ["peeper", "peeping tom"],
    "voyeuristic": ["voyeuristical"],
    "voznesenski": ["andrei voznesenski"],
    "vuillard": ["edouard vuillard", "jean edouard vuillard"],
    "vulcanization": ["vulcanisation"],
    "vulcanize": ["vulcanise"],
    "vulcanizer": ["vulcaniser"],
    "vulgarise": ["vulgarize"],
    "vulgarization": ["vulgarisation"],
    "vulgarize": ["vulgarise"],
    "vulgarizer": ["vulgariser"],
    "vulnerability": ["exposure"],
    "vulpes": ["genus vulpes"],
    "vulpine": ["vulpecular"],
    "vultur": ["genus vultur"],
    "vulvar": ["vulval"],
    "wabash": ["wabash river"],
    "wade": ["virginia wade"],
    "wading bird": ["wader"],
    "wag": ["waggle"],
    "wage": ["earnings", "pay", "remuneration", "salary"],
    "wage claim": ["pay claim"],
    "wage scale": ["wage schedule"],
    "wages": ["payoff", "reward"],
    "waggery": ["waggishness"],
    "wagner": ["otto wagner"],
    "wagon": ["coaster wagon"],
    "wagoner": ["waggoner"],
    "wagonwright": ["waggonwright", "wainwright"],
    "wagram": ["battle of wagram"],
    "wahhabi": ["wahabi"],
    "wahhabism": ["wahabism"],
    "wahoo": ["burning bush", "euonymus atropurpureus"],
    "waif": ["street child"],
    "wail": ["mewl", "pule", "whimper"],
    "wailing": ["bawling"],
    "wain": ["john barrington wain", "john wain"],
    "wainscot": ["dado"],
    "wainscoting": ["wainscotting"],
    "waist": ["waistline"],
    "waist pack": ["belt bag"],
    "wait": ["hold back", "hold off"],
    "waite": ["morrison remick waite", "morrison waite"],
    "waiter": ["server"],
    "waiting": ["ready and waiting"],
    "waive": ["dispense with", "forego", "foreswear", "forgo", "relinquish"],
    "wajda": ["andrzej wajda"],
    "wakashan": ["wakashan language"],
    "wake": ["backwash"],
    "wake board": ["wakeboard"],
    "wake island": ["wake"],
    "wake up": ["arouse", "awake", "awaken", "come alive", "wake", "waken"],
    "wakefulness": ["sleeplessness"],
    "waker": ["arouser", "rouser"],
    "waking": ["wakeful"],
    "walapai": ["hualapai", "hualpai"],
    "walbiri": ["warlpiri"],
    "waldenses": ["vaudois"],
    "waldheim": ["kurt waldheim"],
    "wale": ["weal", "welt", "wheal"],
    "wales": ["cambria", "cymru"],
    "walesa": ["lech walesa"],
    "walk": ["take the air"],
    "walk of life": ["walk"],
    "walk off": ["walk away"],
    "walker": ["john walker"],
    "walker hound": ["walker foxhound"],
    "walking fern": ["asplenium rhizophyllum", "camptosorus rhizophyllus", "walking leaf"],
    "walking leaf": ["leaf insect"],
    "walking papers": ["marching orders"],
    "walking stick": ["stick insect", "walkingstick"],
    "wall": ["fence", "fence in", "palisade", "surround"],
    "wall creeper": ["tichodroma muriaria", "tichodrome"],
    "wall germander": ["teucrium chamaedrys"],
    "wall in": ["wall up"],
    "wall pepper": ["sedum acre"],
    "wall rocket": ["diplotaxis muralis", "diplotaxis tenuifolia"],
    "wall rue": ["wall rue spleenwort"],
    "wall socket": ["electric outlet", "electric receptacle", "electrical outlet", "outlet", "wall plug"],
    "wall street": ["the street"],
    "wallaby": ["brush kangaroo"],
    "wallace": ["sir william wallace"],
    "wallboard": ["dry wall", "drywall"],
    "wallenstein": ["albrecht eusebius wenzel von wallenstein"],
    "waller": ["fats waller", "thomas wright waller"],
    "wallet": ["billfold", "notecase", "pocketbook"],
    "walleye": ["divergent strabismus", "exotropia"],
    "wallflower": ["cheiranthus cheiri", "erysimum cheiri"],
    "wallow": ["welter"],
    "wallpaper": ["paper"],
    "walnut": ["walnut tree"],
    "walpole": ["fourth earl of orford", "horace walpole", "horatio walpole"],
    "walrus": ["sea horse", "seahorse"],
    "walrus mustache": ["walrus moustache"],
    "walter": ["bruno walter"],
    "walton": ["sir william turner walton", "sir william walton", "william walton"],
    "waltz": ["waltz around"],
    "wamble": ["waggle"],
    "wampum": ["peag", "wampumpeag"],
    "wanamaker": ["john wanamaker"],
    "wanderer": ["bird of passage", "roamer", "rover"],
    "wandering": ["roving", "vagabondage"],
    "wandering albatross": ["diomedea exulans"],
    "wanderlust": ["itchy feet"],
    "wandflower": ["sparaxis tricolor"],
    "wangle": ["finagle", "manage"],
    "wankel engine": ["epitrochoidal engine", "wankel rotary engine"],
    "want": ["need", "require"],
    "wanted notice": ["wanted poster"],
    "wanter": ["needer"],
    "wanton": ["trifle away", "wanton away"],
    "wapiti": ["american elk", "cervus elaphus canadensis", "elk"],
    "war": ["state of war"],
    "war cry": ["battle cry", "cry", "rallying cry", "watchword"],
    "war god": ["god of war"],
    "war of the grand alliance": ["war of the league of augsburg"],
    "war of the roses": ["wars of the roses"],
    "waratah": ["telopea speciosissima"],
    "warble": ["quaver", "trill"],
    "warburg": ["otto heinrich warburg"],
    "ward": ["barbara ward", "baroness jackson of lodsworth"],
    "wardrobe": ["closet", "press"],
    "warehouse": ["storage warehouse"],
    "warehouser": ["warehouseman"],
    "warfarin": ["coumadin"],
    "warhead": ["load", "payload"],
    "warhol": ["andy warhol"],
    "wariness": ["chariness"],
    "warlike": ["martial"],
    "warm": ["warm up"],
    "warmheartedness": ["warmth"],
    "warmly": ["warm"],
    "warmongering": ["war advocacy"],
    "warmth": ["warmness"],
    "warn": ["admonish", "discourage", "monish"],
    "warner": ["charles dudley warner"],
    "warp": ["buckle"],
    "warplane": ["military plane"],
    "warrant": ["stock warrant"],
    "warren": ["robert penn warren"],
    "warrigal": ["warragal"],
    "warship": ["combat ship", "war vessel"],
    "warszawa": ["capital of poland", "warsaw"],
    "wart": ["verruca"],
    "warwick": ["earl of warwick", "kingmaker", "richard neville"],
    "wash": ["launder"],
    "wash down": ["flush down"],
    "wash up": ["do the dishes"],
    "washbasin": ["basin", "lavatory", "washbowl", "washstand"],
    "washboard": ["splashboard"],
    "washcloth": ["face cloth", "flannel", "washrag"],
    "washday": ["washing day"],
    "washer": ["automatic washer", "washing machine"],
    "washerman": ["laundryman"],
    "washington": ["booker taliaferro washington"],
    "washout": ["wash"],
    "washup": ["bathing"],
    "washwoman": ["laundress", "laundrywoman", "washerwoman"],
    "wassailer": ["carouser"],
    "wassermann": ["august von wassermann"],
    "wassermann test": ["wasserman reaction", "wassermann"],
    "waste": ["blow", "squander"],
    "waste of effort": ["waste of energy"],
    "wastefully": ["prodigally"],
    "wastepaper basket": ["circular file", "waste basket", "wastebasket"],
    "wastrel": ["waster"],
    "watch": ["follow", "keep an eye on", "observe", "watch over"],
    "watchband": ["bracelet", "watch bracelet", "watchstrap", "wristband"],
    "watchdog": ["guard dog"],
    "watchfulness": ["alertness", "vigilance", "wakefulness"],
    "watchmaker": ["horologer", "horologist"],
    "watchman": ["security guard", "watcher"],
    "water": ["irrigate"],
    "water avens": ["chocolate root", "geum rivale", "indian chocolate", "purple avens"],
    "water boatman": ["boat bug"],
    "water boy": ["waterer"],
    "water buffalo": ["asiatic buffalo", "bubalus bubalis", "water ox"],
    "water caltrop": ["trapa natans"],
    "water cannon": ["watercannon"],
    "water carpet": ["chrysosplenium americanum", "water mat"],
    "water chestnut": ["caltrop", "water chestnut plant"],
    "water chevrotain": ["hyemoschus aquaticus", "water deer"],
    "water chinquapin": ["american lotus", "nelumbo lutea", "yanquapin"],
    "water clock": ["clepsydra", "water glass"],
    "water closet": ["closet", "loo"],
    "water clover": ["marsilea quadrifolia"],
    "water company": ["waterworks"],
    "water crowfoot": ["ranunculus aquatilis", "water buttercup"],
    "water development": ["water program", "water project"],
    "water dog": ["water rat"],
    "water dropwort": ["hemlock water dropwort", "oenanthe crocata"],
    "water elm": ["ulmus laevis"],
    "water faucet": ["hydrant", "tap", "water tap"],
    "water fennel": ["oenanthe aquatica"],
    "water gauge": ["water gage", "water glass"],
    "water gillyflower": ["american featherfoil", "hottonia inflata"],
    "water gum": ["nyssa aquatica"],
    "water hemlock": ["cicuta verosa"],
    "water hickory": ["bitter pecan", "carya aquatica", "water bitternut"],
    "water horehound": ["lycopus americanus"],
    "water hyacinth": ["eichhornia crassipes", "eichhornia spesiosa", "water orchid"],
    "water ice": ["sorbet"],
    "water line": ["watermark"],
    "water lobelia": ["lobelia dortmanna"],
    "water locust": ["gleditsia aquatica", "swamp locust"],
    "water moccasin": ["agkistrodon piscivorus", "cottonmouth", "cottonmouth moccasin"],
    "water nymph": ["fragrant water lily", "nymphaea odorata", "pond lily"],
    "water oak": ["possum oak", "quercus nigra"],
    "water of crystallization": ["water of crystallisation", "water of hydration"],
    "water ouzel": ["dipper"],
    "water parsnip": ["sium suave"],
    "water pistol": ["squirt gun", "squirter", "water gun"],
    "water right": ["riparian right"],
    "water scooter": ["scooter", "sea scooter"],
    "water shamrock": ["bog myrtle", "bogbean", "buckbean", "marsh trefoil", "menyanthes trifoliata"],
    "water speedwell": ["veronica michauxii"],
    "water sport": ["aquatics"],
    "water sprite": ["water nymph", "water spirit"],
    "water star grass": ["heteranthera dubia", "mud plantain"],
    "water strider": ["water skater"],
    "water system": ["water", "water supply"],
    "water table": ["groundwater level", "water level"],
    "water travel": ["seafaring"]
}
