synonyms = {
    "lake onega": ["onega"],
    "lake ontario": ["ontario"],
    "lake st": ["lake saint clair", "lake st. clair"],
    "lake superior": ["superior"],
    "lake tana": ["lake tsana"],
    "lake tanganyika": ["tanganyika"],
    "lake trasimenus": ["battle of lake trasimenus"],
    "lake trout": ["salmon trout", "salvelinus namaycush"],
    "lake urmia": ["daryacheh-ye orumiyeh", "urmia"],
    "lake vanern": ["vanern"],
    "lake victoria": ["victoria nyanza"],
    "lake whitefish": ["coregonus clupeaformis"],
    "lakeside": ["lakeshore"],
    "lallans": ["scottish lallans"],
    "lally": ["lally column"],
    "lam into": ["lace into", "lay into", "pitch into", "tear into"],
    "lama": ["genus lama"],
    "lamaism": ["tibetan buddhism"],
    "lamarck": ["chevalier de lamarck", "jean baptiste de lamarck"],
    "lamaze method of childbirth": ["lamaze method"],
    "lamb": ["charles lamb", "elia"],
    "lamb chop": ["lamb-chop", "lambchop"],
    "lamb roast": ["roast lamb"],
    "lamb succory": ["arnoseris minima", "dwarf nipplewort"],
    "lamb's-quarter": ["pigweed", "wild spinach"],
    "lamb's-quarters": ["chenopodium album", "pigweed", "wild spinach"],
    "lambda particle": ["lambda hyperon"],
    "lambert": ["constant lambert", "leonard constant lambert"],
    "lambert-eaton syndrome": ["carcinomatous myopathy", "eaton-lambert syndrome", "myasthenic syndrome"],
    "lambertia": ["genus lambertia"],
    "lambis": ["genus lambis"],
    "lamboid suture": ["sutura lamboidea"],
    "lamellibranch": ["pelecypod", "pelecypodous"],
    "lamellicornia": ["superfamily lamellicornia"],
    "lameness": ["claudication", "gameness", "gimp", "gimpiness", "limping"],
    "lament": ["keen"],
    "lamentation": ["mourning"],
    "lamentations": ["book of lamentations"],
    "lamenting": ["wailful", "wailing"],
    "laminar": ["laminal"],
    "laminaria": ["genus laminaria"],
    "laminariaceae": ["family laminariaceae"],
    "laminariales": ["order laminariales"],
    "laminitis": ["founder"],
    "lamium": ["genus lamium"],
    "lamivudine": ["3tc"],
    "lammas": ["august 1", "lammas day"],
    "lamna": ["genus lamna"],
    "lamnidae": ["family lamnidae"],
    "lamp chimney": ["chimney"],
    "lamp house": ["lamp housing", "lamphouse"],
    "lamprey": ["lamper eel", "lamprey eel"],
    "lampridae": ["family lampridae"],
    "lampris": ["genus lampris"],
    "lampropeltis": ["genus lampropeltis"],
    "lampshade": ["lamp shade"],
    "lampyridae": ["family lampyridae"],
    "lanai": ["lanai island"],
    "lanate": ["woolly"],
    "lancaster": ["house of lancaster", "lancastrian line"],
    "lancelet": ["amphioxus"],
    "lancelot": ["sir lancelot"],
    "lanceolate": ["lancelike"],
    "lanceolate spleenwort": ["asplenium billotii"],
    "lancet": ["lance"],
    "lancet arch": ["lancet"],
    "lancetfish": ["lancet fish", "wolffish"],
    "lancewood": ["lancewood tree", "oxandra lanceolata"],
    "land": ["set ashore", "shore"],
    "land line": ["landline"],
    "land mine": ["booby trap", "ground-emplaced mine"],
    "land up": ["earth up"],
    "landau": ["lev davidovich landau"],
    "landed gentry": ["squirearchy"],
    "landing": ["landing place"],
    "landlocked salmon": ["lake salmon"],
    "landlubber": ["landman", "landsman"],
    "landmark": ["turning point", "watershed"],
    "landmass": ["land mass"],
    "landowner": ["landholder", "property owner"],
    "landowska": ["wanda landowska"],
    "landscape": ["landscape painting"],
    "landscape architect": ["landscape gardener", "landscaper", "landscapist"],
    "landscaping": ["landscape gardening"],
    "landslide": ["landslip"],
    "landsteiner": ["karl landsteiner"],
    "landward": ["landwards"],
    "laney": ["lucy craft laney"],
    "lange": ["dorothea lange"],
    "langley": ["samuel pierpoint langley"],
    "langmuir": ["irving langmuir"],
    "langside": ["battle of langside"],
    "langtry": ["emilie charlotte le breton", "jersey lillie", "lillie langtry"],
    "language": ["linguistic communication"],
    "language area": ["language zone"],
    "language unit": ["linguistic unit"],
    "langue d'oc": ["langue d'oc french"],
    "langue d'oil": ["langue d'oil french"],
    "languish": ["fade"],
    "languor": ["dreaminess"],
    "laniidae": ["family laniidae"],
    "lanius": ["genus lanius"],
    "lank": ["spindly"],
    "lanolin": ["wool fat", "wool grease"],
    "lanseh": ["lansa", "lansat", "lanset"],
    "lanseh tree": ["langsat", "langset", "lansium domesticum"],
    "lansing": ["capital of michigan"],
    "lansoprazole": ["prevacid"],
    "lantern fly": ["lantern-fly"],
    "lantern pinion": ["lantern wheel"],
    "lanthanotidae": ["family lanthanotidae"],
    "lanthanotus": ["genus lanthanotus"],
    "lanthanum": ["atomic number 57", "la"],
    "lanyard": ["laniard"],
    "lanzhou": ["lanchou", "lanchow"],
    "lao": ["laotian"],
    "lao-tzu": ["lao-tse", "lao-zi"],
    "laos": ["lao people's democratic republic"],
    "lap": ["swish", "swoosh", "swosh"],
    "lap joint": ["splice"],
    "laparoscopic cholecystectomy": ["lap choly"],
    "lapidary": ["lapidarist"],
    "lapidify": ["petrify"],
    "lapin": ["rabbit"],
    "lapis lazuli": ["lazuli"],
    "laplace": ["marquis de laplace", "pierre simon de laplace"],
    "laportea": ["genus laportea"],
    "lapp": ["lapplander", "saame", "saami", "same", "sami"],
    "lappet": ["lappet moth"],
    "lappic": ["lappish"],
    "lappland": ["lapland"],
    "lapse": ["backslide"],
    "lapsed": ["nonchurchgoing"],
    "laptop": ["laptop computer"],
    "lapwing": ["green plover", "peewit", "pewit"],
    "larboard": ["port"],
    "larcenist": ["larcener"],
    "larceny": ["stealing", "theft", "thievery", "thieving"],
    "larch": ["larch tree"],
    "lardizabala": ["genus lardizabala"],
    "lardizabalaceae": ["family lardizabalaceae", "lardizabala family"],
    "lardner": ["ring lardner", "ringgold wilmer lardner"],
    "large": ["big"],
    "large civet": ["viverra zibetha"],
    "large crabgrass": ["digitaria sanguinalis", "hairy finger grass"],
    "large indefinite quantity": ["large indefinite amount"],
    "large periwinkle": ["vinca major"],
    "large white": ["pieris brassicae"],
    "large white petunia": ["petunia axillaris"],
    "large yellow lady's slipper": ["cypripedium calceolus pubescens"],
    "large-capitalization": ["large-cap", "large-capitalisation"],
    "large-flowered calamint": ["calamintha grandiflora", "clinopodium grandiflorum", "satureja grandiflora"],
    "large-flowered fiddleneck": ["amsinckia grandiflora"],
    "large-leaved": ["large-leafed"],
    "large-leaved aster": ["aster macrophyllus"],
    "large-leaved magnolia": ["great-leaved macrophylla", "large-leaved cucumber tree", "magnolia macrophylla"],
    "largely": ["for the most part", "mostly"],
    "largemouth": ["largemouth bass", "largemouth black bass", "largemouthed bass", "largemouthed black bass", "micropterus salmoides"],
    "largeness": ["extensiveness"],
    "largess": ["largesse"],
    "lari": ["suborder lari"],
    "laricariidae": ["family laricariidae"],
    "laridae": ["family laridae"],
    "larix": ["genus larix"],
    "larousse": ["pierre athanase larousse", "pierre larousse"],
    "larrea": ["genus larrea"],
    "larus": ["genus larus"],
    "larvacea": ["class larvacea"],
    "laryngeal artery": ["arteria laryngea"],
    "laryngeal vein": ["vena laryngea"],
    "larynx": ["voice box"],
    "lasagna": ["lasagne"],
    "lasalle": ["rene-robert cavelier", "sieur de lasalle"],
    "lascivious": ["lewd", "libidinous", "lustful"],
    "lasciviously": ["salaciously"],
    "laser": ["optical maser"],
    "laser-assisted in situ keratomileusis": ["lasik"],
    "laser-assisted subepithelial keratomileusis": ["lasek"],
    "laser-guided bomb": ["lgb"],
    "lash": ["thong"],
    "lash-up": ["contrivance"],
    "lashkar-e-omar": ["al qanoon"],
    "lashkar-e-taiba": ["army of the pure", "army of the righteous", "lashkar-e-tayyiba", "lashkar-e-toiba", "let"],
    "lasiocampa": ["genus lasiocampa"],
    "lasiocampid": ["lasiocampid moth"],
    "lasiocampidae": ["family lasiocampidae"],
    "lasiurus": ["genus lasiurus"],
    "laskar jihad": ["holy war warriors"],
    "lass": ["jeune fille", "lassie", "young girl"],
    "lasso": ["rope"],
    "last": ["endure"],
    "last but not least": ["last not least"],
    "last in first out": ["lifo"],
    "last out": ["outride", "ride out", "stay"],
    "last supper": ["lord's supper"],
    "lasthenia": ["genus lasthenia"],
    "lastingness": ["durability", "enduringness", "strength"],
    "lastreopsis": ["genus lastreopsis"],
    "latanier": ["latanier palm"],
    "latch": ["door latch"],
    "late": ["belatedly", "tardily"],
    "late latin": ["biblical latin"],
    "lateen": ["lateen sail"],
    "latency stage": ["latency period", "latency phase"],
    "latent diabetes": ["chemical diabetes"],
    "latent heat": ["heat of transformation"],
    "latent hostility": ["tension"],
    "later": ["posterior", "ulterior"],
    "lateral": ["sidelong"],
    "lateral geniculate body": ["corpus geniculatum laterale", "lateral geniculate"],
    "lateral line": ["lateral line organ"],
    "lateral pass": ["lateral"],
    "laterality": ["dominance"],
    "lateralization": ["lateralisation", "laterality"],
    "lates": ["genus lates"],
    "latest": ["a la mode", "in style", "in vogue", "modish"],
    "latex paint": ["latex", "rubber-base paint"],
    "lathery": ["sudsy"],
    "lathi": ["lathee"],
    "lathyrus": ["genus lathyrus"],
    "latimeria": ["genus latimeria"],
    "latimeridae": ["family latimeridae"],
    "latin american": ["latino"],
    "latissimus dorsi": ["lat"],
    "latitude": ["line of latitude", "parallel", "parallel of latitude"],
    "latium": ["lazio"],
    "latrobe": ["benjamin henry latrobe"],
    "latrodectus": ["genus latrodectus"],
    "latter-day saint": ["mormon"],
    "lattice": ["fretwork", "latticework"],
    "latvia": ["republic of latvia"],
    "latvian": ["lettish"],
    "laud": ["exalt", "extol", "glorify", "proclaim"],
    "laudanum": ["tincture of opium"],
    "laudator": ["extoller", "lauder"],
    "laudatory": ["praiseful", "praising"],
    "lauder": ["harry lauder", "sir harry maclennan lauder"],
    "laugh": ["express joy", "express mirth"],
    "laugh off": ["laugh away"],
    "laughably": ["ludicrously", "preposterously", "ridiculously"],
    "laughing": ["riant"],
    "laughing gull": ["blackcap", "larus ridibundus", "pewit", "pewit gull"],
    "laughing owl": ["laughing jackass", "sceloglaux albifacies"],
    "laughton": ["charles laughton"],
    "launch": ["set in motion"],
    "launcher": ["rocket launcher"],
    "launching": ["launch"],
    "launching pad": ["launch area", "launch pad", "launchpad", "pad"],
    "launderette": ["laundromat"],
    "laundry": ["wash", "washables", "washing"],
    "lauraceae": ["family lauraceae", "laurel family"],
    "laurel": ["arthur stanley jefferson laurel", "stan laurel"],
    "laurel oak": ["pin oak", "quercus laurifolia"],
    "laurel sumac": ["malosma laurina", "rhus laurina"],
    "laurel-tree": ["persea borbonia", "red bay"],
    "laureled": ["crowned", "laurelled"],
    "laurelwood": ["calophyllum candidissimum", "lancewood tree"],
    "laurens": ["henry laurens"],
    "laurentian plateau": ["canadian shield", "laurentian highlands"],
    "lauric acid": ["dodecanoic acid"],
    "laurus": ["genus laurus"],
    "lauryl alcohol": ["1-dodecanol"],
    "lautaro youth movement": ["lautaro faction of the united popular action movement", "lautaro popular rebel forces"],
    "lavaliere": ["lavalier", "lavalliere"],
    "lavandula": ["genus lavandula"],
    "lavatera": ["genus lavatera"],
    "lave": ["lap", "wash"],
    "lavender": ["lilac", "lilac-colored"],
    "lavender cotton": ["santolina chamaecyparissus"],
    "laver": ["rod laver", "rodney george laver"],
    "lavish": ["shower"],
    "lavishly": ["extravagantly", "richly"],
    "lavishness": ["luxury", "sumptuosity", "sumptuousness"],
    "lavoisier": ["antoine laurent lavoisier", "antoine lavoisier"],
    "law": ["jurisprudence"],
    "law of constant proportion": ["law of definite proportions"],
    "law of equivalent proportions": ["law of reciprocal proportions"],
    "law of gravitation": ["newton's law of gravitation"],
    "law of multiple proportions": ["dalton's law"],
    "law school": ["school of law"],
    "law-abiding": ["observant"],
    "lawful": ["rule-governed"],
    "lawgiver": ["lawmaker"],
    "lawless": ["outlaw"],
    "lawlessness": ["outlawry"],
    "lawman": ["law officer", "peace officer"],
    "lawn bowling": ["bowls"],
    "lawn chair": ["garden chair"],
    "lawn mower": ["mower"],
    "lawrence": ["laurentius", "saint lawrence", "st. lawrence"],
    "lawrencium": ["atomic number 103", "lr"],
    "lawsuit": ["case", "causa", "cause", "suit"],
    "lawyer": ["attorney"],
    "lawyer cane": ["calamus australis"],
    "lawyer-client relation": ["attorney-client relation"],
    "lawyerbush": ["bush lawyer", "lawyer bush", "rubus australis", "rubus cissoides"],
    "lax": ["slack"],
    "laxly": ["leniently"],
    "laxness": ["laxity"],
    "lay": ["put down", "repose"],
    "lay down": ["establish", "make"],
    "lay over": ["stop over"],
    "lay waste to": ["desolate", "devastate", "ravage", "scourge", "waste"],
    "lay-up": ["layup"],
    "layer": ["bed"],
    "layered": ["superimposed"],
    "layia": ["genus layia"],
    "laying": ["egg laying"],
    "laying waste": ["ruin", "ruination", "ruining", "wrecking"],
    "layman": ["layperson", "secular"],
    "lazaretto": ["lazar house", "lazaret", "lazarette", "pesthouse"],
    "le carre": ["david john moore cornwell", "john le carre"],
    "le chatelier": ["henry le chatelier"],
    "le chatelier's principle": ["le chatelier principle", "le chatelier's law", "le chatelier-braun principle"],
    "le corbusier": ["charles edouard jeanneret"],
    "le gallienne": ["eva le gallienne"],
    "le notre": ["andre le notre"],
    "leach": ["percolate"],
    "leacock": ["stephen butler leacock", "stephen leacock"],
    "lead": ["top"],
    "lead acetate": ["sugar of lead"],
    "lead bank": ["agent bank"],
    "lead colic": ["painter's colic"],
    "lead line": ["sounding line"],
    "lead off": ["lead astray"],
    "lead poisoning": ["plumbism", "saturnism"],
    "lead tree": ["leucaena glauca", "leucaena leucocephala", "white popinac"],
    "lead up": ["initiate"],
    "lead-acid battery": ["lead-acid accumulator"],
    "lead-colored": ["lead-coloured"],
    "lead-free": ["nonleaded"],
    "leaded gasoline": ["leaded petrol"],
    "leaden": ["weighted"],
    "leadership": ["leaders"],
    "leading": ["preeminent"],
    "leading astray": ["leading off"],
    "leadplant": ["amorpha canescens", "lead plant"],
    "leadwort": ["plumbago europaea"],
    "leaf": ["foliage", "leafage"],
    "leaf beetle": ["chrysomelid"],
    "leaf bug": ["plant bug"],
    "leaf fat": ["leaf lard"],
    "leaf lettuce": ["lactuca sativa crispa"],
    "leaf miner": ["leaf-miner"],
    "leaf mold": ["leaf mould", "leaf soil"],
    "leaf roller": ["leaf-roller"],
    "leaf shape": ["leaf form"],
    "leaf-cutting bee": ["leaf-cutter", "leaf-cutter bee"],
    "leaf-footed bug": ["leaf-foot bug"],
    "leafed": ["leaved"],
    "leaflike": ["leaf-like"],
    "leafnose bat": ["leaf-nosed bat"],
    "leafy liverwort": ["scale moss"],
    "leafy spurge": ["euphorbia esula", "wolf's milk"],
    "league": ["conference"],
    "leak": ["leak out"],
    "leak fungus": ["rhizopus stolonifer", "ring rot fungus"],
    "leakey": ["richard erskine leakey", "richard leakey"],
    "lean": ["angle", "slant", "tilt", "tip"],
    "lean back": ["recline"],
    "lean on": ["lean against", "rest on"],
    "leaning": ["propensity", "tendency"],
    "leaning tower": ["leaning tower of pisa"],
    "leanness": ["spareness", "thinness"],
    "leap": ["jump"],
    "leap day": ["bissextile day", "february 29"],
    "leap out": ["jump", "jump out", "stand out", "stick out"],
    "leap year": ["366 days", "bissextile year", "intercalary year"],
    "lear": ["edward lear"],
    "learn": ["read", "study", "take"],
    "learned reaction": ["learned response"],
    "learner": ["assimilator", "scholar"],
    "learner's dictionary": ["school dictionary"],
    "learning": ["acquisition"],
    "learning disorder": ["learning disability"],
    "leary": ["tim leary", "timothy francis leary", "timothy leary"],
    "lease": ["let", "rent"],
    "leaseholder": ["lessee"],
    "leash": ["lead", "tether"],
    "least": ["to the lowest degree"],
    "least bittern": ["ixobrychus exilis"],
    "least effort": ["least resistance"],
    "least sandpiper": ["erolia minutilla", "stint"],
    "least shrew": ["cryptotis parva"],
    "least squares": ["method of least squares"],
    "leather fern": ["leatherleaf fern", "polystichum adiantiformis", "rumohra adiantiformis", "ten-day fern"],
    "leather flower": ["clematis viorna", "vase vine", "vase-fine"],
    "leather-leaved": ["leather-leafed"],
    "leatherback turtle": ["dermochelys coriacea", "leatherback", "leathery turtle"],
    "leatherette": ["imitation leather"],
    "leatherjacket": ["leatherfish"],
    "leatherleaf": ["coast polypody", "leathery polypody", "polypodium scouleri"],
    "leatherleaf saxifrage": ["leptarrhena pyrolifolia"],
    "leatherwood": ["dirca palustris", "moose-wood", "moosewood", "ropebark", "wicopy"],
    "leathery grape fern": ["botrychium multifidum"],
    "leave": ["allow", "allow for", "provide"],
    "leave office": ["quit", "resign", "step down"],
    "leaven": ["leavening"],
    "lebanese pound": ["pound"],
    "lebanon": ["lebanese republic"],
    "lebistes": ["genus lebistes"],
    "leboyer method of childbirth": ["leboyer method"],
    "lecanoraceae": ["family lecanoraceae"],
    "leccinum": ["genus leccinum"],
    "lechanorales": ["order lechanorales"],
    "lecherousness": ["lust", "lustfulness"],
    "lechwe": ["kobus leche"],
    "lectern": ["reading desk"],
    "lector": ["reader"],
    "lecture": ["talk"],
    "lecythidaceae": ["family lecythidaceae"],
    "ledbetter": ["huddie leadbetter", "leadbelly"],
    "ledge": ["shelf"],
    "ledger": ["account book", "book", "book of account", "leger"],
    "ledger line": ["leger line"],
    "ledum": ["genus ledum"],
    "lee": ["shelton jackson lee", "spike lee"],
    "leech": ["parasite", "sponge", "sponger"],
    "leek": ["allium porrum", "scallion"],
    "leery": ["mistrustful", "suspicious", "untrusting", "wary"],
    "leeward": ["upwind"],
    "leeward tide": ["lee tide"],
    "leflunomide": ["arava"],
    "left": ["left wing"],
    "left atrium": ["atrium sinistrum", "left atrium of the heart"],
    "left bank": ["latin quarter"],
    "left field": ["left", "leftfield"],
    "left gastric artery": ["arteria gastrica sinistra"],
    "left gastric vein": ["vena gastrica sinistra"],
    "left hemisphere": ["left brain"],
    "left-handed pitcher": ["left hander", "left-hander", "lefthander", "lefty", "southpaw"],
    "left-handedness": ["sinistrality"],
    "left-hander": ["lefty", "southpaw"],
    "lefteye flounder": ["lefteyed flounder"],
    "leftist": ["left-of-center", "left-wing"],
    "leftover": ["remnant"],
    "leg curl": ["leg curling"],
    "leg of lamb": ["gigot"],
    "leg-pull": ["leg-pulling"],
    "legal": ["effectual", "sound"],
    "legal action": ["action", "action at law"],
    "legal document": ["instrument", "legal instrument", "official document"],
    "legal holiday": ["national holiday", "public holiday"],
    "legal power": ["jurisdiction"],
    "legal principle": ["judicial doctrine", "judicial principle"],
    "legal profession": ["bar", "legal community"],
    "legal separation": ["judicial separation"],
    "legalization": ["legalisation", "legitimation"],
    "legalize": ["decriminalise", "decriminalize", "legalise", "legitimate", "legitimatise", "legitimatize", "legitimise", "legitimize"],
    "legally": ["de jure", "lawfully"],
    "legate": ["official emissary"],
    "legation": ["foreign mission"],
    "legato": ["smooth"],
    "legend": ["fable"],
    "leger": ["fernand leger"],
    "legging": ["leg covering", "leging"],
    "leggy": ["tall-growing"],
    "legibility": ["readability"],
    "legibly": ["decipherably", "readably"],
    "legionella pneumophilia": ["legionella"],
    "legionnaire": ["legionary"],
    "legislate": ["pass"],
    "legislation": ["statute law"],
    "legislative act": ["statute"],
    "legislature": ["general assembly", "law-makers", "legislative assembly", "legislative body"],
    "legitimate": ["logical"],
    "legitimately": ["lawfully", "licitly"],
    "lego": ["lego set"],
    "legume": ["leguminous plant"],
    "leguminosae": ["fabaceae", "family fabaceae", "family leguminosae", "legume family", "pea family"],
    "lehar": ["franz lehar"],
    "leibniz": ["gottfried wilhelm leibnitz", "gottfried wilhelm leibniz", "leibnitz"],
    "leibnizian": ["leibnitzian"],
    "leicestershire": ["leicester"],
    "leichtlin's camas": ["camassia leichtlinii"],
    "leiden": ["leyden"],
    "leiden jar": ["leyden jar"],
    "leigh": ["vivien leigh"],
    "leiopelma": ["genus leiopelma", "genus liopelma", "liopelma"],
    "leiopelmatidae": ["family leiopelmatidae", "family liopelmidae", "liopelmidae"],
    "leiophyllum": ["genus leiophyllum"],
    "leishmania": ["genus leishmania"],
    "leishmaniasis": ["kala azar", "leishmaniosis"],
    "leisure": ["leisure time"],
    "leitmotiv": ["leitmotif"],
    "leitneria": ["genus leitneria"],
    "leitneriaceae": ["corkwood family", "family leitneriaceae"],
    "lemaireocereus": ["genus lemaireocereus"],
    "lemaitre": ["edouard lemaitre", "georges henri lemaitre"],
    "lemma": ["flowering glume"],
    "lemmon": ["jack lemmon", "john uhler"],
    "lemmus": ["genus lemmus"],
    "lemna": ["genus lemna"],
    "lemnaceae": ["duckweed family", "family lemnaceae"],
    "lemniscus": ["fillet"],
    "lemnos": ["limnos"],
    "lemon": ["citrus limon", "lemon tree"],
    "lemon balm": ["bee balm", "beebalm", "garden balm", "melissa officinalis", "sweet balm"],
    "lemon curd": ["lemon cheese"],
    "lemon geranium": ["pelargonium limoneum"],
    "lemon lily": ["hemerocallis flava", "hemerocallis lilio-asphodelus"],
    "lemon mint": ["horsemint", "monarda citriodora"],
    "lemon peel": ["lemon rind"],
    "lemon shark": ["negaprion brevirostris"],
    "lemon sole": ["winter flounder"],
    "lemon-scented gum": ["eucalyptus citriodora", "eucalyptus maculata citriodora"],
    "lemongrass": ["lemon grass", "lemongrass oil"],
    "lemonwood": ["lemon-wood", "lemon-wood tree", "lemonwood tree", "psychotria capensis"],
    "lemony": ["lemonlike", "sourish", "tangy", "tart"],
    "lemuridae": ["family lemuridae"],
    "lemuroidea": ["suborder lemuroidea"],
    "lena": ["lena river"],
    "lenard": ["philipp lenard"],
    "lend": ["add", "bestow", "bring", "contribute", "impart"],
    "lend oneself": ["apply"],
    "lend-lease": ["lease-lend"],
    "lender": ["loaner"],
    "lending": ["loaning"],
    "lending library": ["circulating library"],
    "lendl": ["ivan lendl"],
    "lengthily": ["at length"],
    "lengthiness": ["continuation", "prolongation", "protraction"],
    "lengthways": ["lengthwise", "longitudinally", "longways", "longwise"],
    "lengthwise": ["lengthways"],
    "lenience": ["leniency", "lenity", "mildness"],
    "lenin": ["nikolai lenin", "vladimir ilich lenin", "vladimir ilich ulyanov", "vladimir ilyich lenin", "vladimir ilyich ulyanov", "vladimir lenin"],
    "leninism": ["marxism-leninism"],
    "lennoaceae": ["family lennoaceae"],
    "lennon": ["john lennon"],
    "lens": ["genus lens"],
    "lens cap": ["lens cover"],
    "lens cortex": ["cortex"],
    "lens implant": ["interocular lens implant", "iol"],
    "lens nucleus": ["nucleus"],
    "lent": ["lententide"],
    "lente insulin": ["lente iletin"],
    "lenten rose": ["black hellebore", "helleborus orientalis"],
    "lentibulariaceae": ["bladderwort family", "family lentibulariaceae"],
    "lenticular nucleus": ["lentiform nucleus"],
    "lentil": ["lens culinaris", "lentil plant"],
    "lentinus": ["genus lentinus"],
    "lento": ["slowly"],
    "leo": ["lion"],
    "leo i": ["leo the great", "st. leo i"],
    "leo ix": ["bruno", "bruno of toul"],
    "leo x": ["giovanni de'medici"],
    "leo xiii": ["gioacchino pecci", "giovanni vincenzo pecci"],
    "leonard": ["dutch leonard", "elmore john leonard", "elmore leonard"],
    "leonardo": ["da vinci", "leonardo da vinci"],
    "leonotis": ["genus leonotis"],
    "leontief": ["wassily leontief"],
    "leontocebus": ["genus leontideus", "genus leontocebus"],
    "leontodon": ["genus leontodon"],
    "leontopodium": ["genus leontopodium"],
    "leonurus": ["genus leonurus"],
    "leopard": ["panthera pardus"],
    "leopard cat": ["felis bengalensis"],
    "leopard frog": ["rana pipiens", "spring frog"],
    "leopard lily": ["lilium pardalinum", "panther lily"],
    "leopard's-bane": ["leopardbane"],
    "leotard": ["body suit", "cat suit", "unitard"],
    "lepadidae": ["family lepadidae"],
    "lepanto": ["battle of lepanto"],
    "lepas": ["genus lepas"],
    "lepechinia": ["genus lepechinia", "genus sphacele", "sphacele"],
    "leper": ["lazar"],
    "lepidium": ["genus lepidium"],
    "lepidobotryaceae": ["family lepidobotryaceae"],
    "lepidochelys": ["genus lepidochelys"],
    "lepidocybium": ["genus lepidocybium"],
    "lepidodendraceae": ["family lepidodendraceae"],
    "lepidodendrales": ["order lepidodendrales"],
    "lepidoptera": ["order lepidoptera"],
    "lepidopterist": ["butterfly collector", "lepidopterologist"],
    "lepidopterology": ["lepidoptery"],
    "lepidopterous insect": ["lepidopteran", "lepidopteron"],
    "lepidosauria": ["subclass lepidosauria"],
    "lepidote": ["leprose", "scabrous", "scaly", "scurfy"],
    "lepidothamnus": ["genus lepidothamnus"],
    "lepiotaceae": ["family lepiotaceae"],
    "lepisma": ["genus lepisma"],
    "lepismatidae": ["family lepismatidae"],
    "lepisosteidae": ["family lepisosteidae"],
    "lepisosteus": ["genus lepisosteus"],
    "lepomis": ["genus lepomis"],
    "leporid": ["leporid mammal"],
    "leporidae": ["family leporidae"],
    "leprosy": ["hansen's disease"],
    "leprosy bacillus": ["mycobacterium leprae"],
    "leptarrhena": ["genus leptarrhena"],
    "leptinotarsa": ["genus leptinotarsa"],
    "leptodactylid frog": ["leptodactylid"],
    "leptodactylidae": ["family leptodactylidae"],
    "leptodactylus": ["genus leptodactylus"],
    "leptoglossus": ["genus leptoglossus"],
    "leptopteris": ["genus leptopteris"],
    "leptoptilus": ["genus leptoptilus"],
    "leptorrhine": ["leptorhine", "leptorrhinian", "leptorrhinic"],
    "leptotyphlopidae": ["family leptotyphlopidae"],
    "leptotyphlops": ["genus leptotyphlops"],
    "lepus": ["genus lepus"],
    "lermontov": ["mikhail yurievich lermontov"],
    "lerner": ["alan jay lerner"],
    "lesbian": ["gay woman", "tribade"],
    "lesbianism": ["sapphism"],
    "lesbos": ["lesvos", "mytilene"],
    "lesotho": ["basutoland", "kingdom of lesotho"],
    "lesquerella": ["genus lesquerella"],
    "less": ["to a lesser extent"],
    "lesseps": ["ferdinand de lesseps", "vicomte ferdinand marie de lesseps"],
    "lesser antilles": ["caribees"],
    "lesser bullrush": ["narrow-leaf cattail", "narrow-leaved reedmace", "soft flag", "typha angustifolia"],
    "lesser butterfly orchid": ["habenaria bifolia", "platanthera bifolia"],
    "lesser calamint": ["calamintha nepeta", "calamintha nepeta glantulosa", "field balm", "satureja calamintha glandulosa", "satureja nepeta"],
    "lesser celandine": ["pilewort", "ranunculus ficaria"],
    "lesser centaury": ["centaurium minus"],
    "lesser galangal": ["alpinia officinalis", "alpinia officinarum"],
    "lesser knapweed": ["black knapweed", "centaurea nigra", "hardheads"],
    "lesser kudu": ["tragelaphus imberbis"],
    "lesser panda": ["ailurus fulgens", "bear cat", "cat bear", "panda", "red panda"],
    "lesser prairie chicken": ["tympanuchus pallidicinctus"],
    "lesser rorqual": ["balaenoptera acutorostrata", "minke whale", "piked whale"],
    "lesser scaup": ["aythya affinis", "lake duck", "lesser scaup duck"],
    "lesser spearwort": ["ranunculus flammula"],
    "lesser sunda islands": ["nusa tenggara"],
    "lesser twayblade": ["listera cordata"],
    "lesser whitethroat": ["sylvia curruca", "whitethroat"],
    "lesser wintergreen": ["pyrola minor"],
    "lesser yellowlegs": ["tringa flavipes"],
    "lessing": ["gotthold ephraim lessing"],
    "lessor": ["lease giver"],
    "let": ["allow", "permit"],
    "let alone": ["not to mention"],
    "let go of": ["let go", "release", "relinquish"],
    "let out": ["widen"],
    "lethargic": ["unenrgetic"],
    "lethargically": ["unenergetically"],
    "lethargy": ["lassitude", "sluggishness"],
    "lethe": ["river lethe"],
    "leto": ["latona"],
    "letter": ["alphabetic character", "letter of the alphabet"],
    "letter bomb": ["package bomb", "parcel bomb"],
    "letter of jeremiah": ["epistle of jeremiah"],
    "letter of marque": ["letter of mark and reprisal", "letters of marque"],
    "letter opener": ["paper knife", "paperknife"],
    "letter-perfect": ["word-perfect"],
    "letup": ["lull"],
    "leucadendron": ["genus leucadendron"],
    "leucaena": ["genus leucaena"],
    "leucanthemum": ["genus leucanthemum"],
    "leuciscus": ["genus leuciscus"],
    "leucocytozoan": ["leucocytozoon"],
    "leucogenes": ["genus leucogenes"],
    "leuctra": ["battle of leuctra"],
    "leukemia": ["cancer of the blood", "leucaemia", "leukaemia"],
    "leukocyte": ["leucocyte", "wbc", "white blood cell", "white blood corpuscle", "white cell", "white corpuscle"],
    "leukocytosis": ["leucocytosis"],
    "leukoma": ["leucoma"],
    "leukopenia": ["leucopenia"],
    "leukorrhea": ["leucorrhea"],
    "leuwenhoek": ["anton van leeuwenhoek", "anton van leuwenhoek", "leeuwenhoek"],
    "levallorphan": ["lorfan"],
    "levant": ["levant morocco"],
    "levant cotton": ["gossypium herbaceum"],
    "level": ["dismantle", "pull down", "rase", "raze", "take down", "tear down"],
    "level crossing": ["grade crossing"],
    "leveler": ["leveller"],
    "lever": ["lever tumbler"],
    "leverage": ["purchase"],
    "levi's": ["levis"],
    "levi-strauss": ["claude levi-strauss"],
    "levisticum": ["genus levisticum"],
    "levitate": ["hover"],
    "leviticus": ["book of leviticus"],
    "levorotary": ["left-handed", "levorotatory"],
    "levorotation": ["counterclockwise rotation"],
    "levy": ["impose"],
    "lewd": ["obscene", "raunchy", "salacious"],
    "lewdly": ["obscenely"],
    "lewis": ["jerry lee lewis"],
    "lewisia": ["genus lewisia"],
    "lexical entry": ["dictionary entry"],
    "lexicalization": ["lexicalisation"],
    "lexicalize": ["lexicalise"],
    "lexicalized": ["lexicalised"],
    "lexicographer": ["lexicologist"],
    "lexicographic": ["lexicographical"],
    "lexington": ["concord", "lexington and concord"],
    "leycesteria": ["genus leycesteria"],
    "leydig cell": ["leydig's cell"],
    "leymus": ["genus leymus"],
    "leyte": ["leyte invasion", "leyte island"],
    "lhasa": ["capital of tibet", "forbidden city", "lassa"],
    "liable": ["nonimmune", "nonresistant", "unresistant"],
    "liaison": ["contact", "inter-group communication", "link"],
    "liao": ["liao dynasty"],
    "liaodong peninsula": ["liaodong bandao"],
    "liar": ["prevaricator"],
    "liatris": ["genus liatris"],
    "libby": ["willard frank libby"],
    "liberal": ["liberalist", "progressive"],
    "liberality": ["liberalness"],
    "liberalization": ["liberalisation", "relaxation"],
    "liberalize": ["liberalise"],
    "liberally": ["generously", "munificently"],
    "liberate": ["set free"],
    "liberation": ["freeing", "release"],
    "liberation tigers of tamil eelam": ["ltte", "tamil tigers", "tigers", "world tamil association", "world tamil movement"],
    "liberia": ["republic of liberia"],
    "liberian coffee": ["coffea liberica"],
    "libertine": ["debauchee", "rounder"],
    "liberty island": ["bedloe's island"],
    "libocedrus": ["genus libocedrus"],
    "libra": ["balance"],
    "librarian": ["bibliothec"],
    "library": ["program library", "subroutine library"],
    "library card": ["borrower's card"],
    "library catalog": ["library catalogue"],
    "libreville": ["capital of gabon"],
    "libya": ["socialist people's libyan arab jamahiriya"],
    "libyan dinar": ["dinar"],
    "libyan dirham": ["dirham"],
    "libyan islamic fighting group": ["al-jama'a al-islamiyyah al-muqatilah bi-libya", "fig", "libyan fighting group", "libyan islamic group"],
    "license": ["certify", "licence"],
    "license number": ["registration number"],
    "license plate": ["numberplate"],
    "licensed practical nurse": ["lpn", "practical nurse"],
    "licensing fee": ["license fee", "license tax"],
    "licentiously": ["promiscuously", "wantonly"],
    "licentiousness": ["wantonness"],
    "lichanura": ["genus lichanura"],
    "lichen planus": ["lichen ruber planus"],
    "lichenales": ["order lichenales"],
    "lichenes": ["division lichenes"],
    "lichtenoid eczema": ["chronic eczema", "eczema hypertrophicum"],
    "lichtenstein": ["roy lichtenstein"],
    "lick": ["lap"],
    "lickety split": ["lickety cut"],
    "licorice": ["glycyrrhiza glabra", "liquorice"],
    "licorice fern": ["polypodium glycyrrhiza"],
    "lidless": ["sleepless"],
    "lidocaine": ["xylocaine"],
    "lie": ["rest"],
    "lie about": ["lie around"],
    "lie down": ["lie"],
    "lie-abed": ["slugabed"],
    "liechtenstein": ["principality of liechtenstein"],
    "liege": ["liege lord"],
    "lienal artery": ["arteria lienalis", "splenic artery"],
    "lieutenant": ["police lieutenant"],
    "lieutenant colonel": ["light colonel"],
    "lieutenant junior grade": ["lieutenant jg"],
    "life": ["life-time", "lifespan", "lifetime"],
    "life buoy": ["life belt", "life ring", "lifesaver"],
    "life estate": ["estate for life"],
    "life force": ["elan vital", "vital force", "vitality"],
    "life insurance": ["life assurance"],
    "life jacket": ["cork jacket", "life vest"],
    "life preserver": ["flotation device", "preserver"],
    "life raft": ["carling float"],
    "life science": ["bioscience"],
    "life sentence": ["life"],
    "life style": ["life-style", "lifestyle", "modus vivendi"],
    "life-and-death": ["life-or-death"],
    "life-giving": ["vitalizing"],
    "life-size": ["full-size", "life-sized", "lifesize"],
    "life-support system": ["life support"],
    "lifeguard": ["lifesaver"],
    "lifeless": ["exanimate"],
    "lifelike": ["natural"],
    "lifelong": ["womb-to-tomb"],
    "lift": ["raise"],
    "light": ["illume", "illuminate", "illumine", "light up"],
    "light bulb": ["bulb", "electric light", "electric-light bulb", "incandescent lamp", "lightbulb"],
    "light circuit": ["lighting circuit"],
    "light cream": ["coffee cream", "single cream"],
    "light filter": ["diffusing screen"],
    "light heavyweight": ["cruiserweight"],
    "light meter": ["exposure meter", "photometer"],
    "light pen": ["electronic stylus"],
    "light reflex": ["miosis", "myosis", "pupillary reflex"],
    "light up": ["fire up", "light"],
    "light year": ["light-year"],
    "light-armed": ["lightly-armed"],
    "light-blue": ["pale blue"],
    "light-emitting diode": ["led"],
    "light-fingered": ["nimble-fingered"],
    "light-heartedly": ["lightsomely"],
    "light-o'-love": ["light-of-love"],
    "light-sensitive": ["photosensitive"],
    "lighted": ["lit"],
    "lighten": ["buoy up", "lighten up"],
    "lighter": ["igniter", "ignitor", "light"],
    "lighterman": ["bargee", "bargeman"],
    "lightless": ["unilluminated", "unlighted", "unlit"],
    "lightly": ["light"],
    "lightly armored": ["lightly armoured"],
    "lightness": ["weightlessness"],
    "lightning rod": ["lightning conductor"],
    "lightproof": ["light-tight"],
    "lightsomely": ["trippingly"],
    "lightsomeness": ["lightness"],
    "lightwood": ["acacia melanoxylon"],
    "lignite": ["brown coal", "wood coal"],
    "lignum vitae": ["guaiac", "guaiacum"],
    "ligularia": ["genus ligularia"],
    "ligustrum": ["genus ligustrum"],
    "likable": ["likeable"],
    "like": ["the like", "the likes of"],
    "like hell": ["like crazy", "like mad", "like sin", "like the devil", "like thunder"],
    "likelihood": ["likeliness"],
    "likely": ["potential"],
    "likeness": ["alikeness", "similitude"],
    "lilac-blue": ["violet-blue"],
    "lilac-pink": ["lavender-pink", "violet-pink"],
    "liliaceae": ["family liliaceae", "lily family"],
    "liliales": ["order liliales"],
    "liliidae": ["subclass liliidae"],
    "lilium": ["genus lilium"],
    "liliuokalani": ["lydia kamekeha paki liliuokalani"],
    "lillie": ["beatrice lillie", "lady peel"],
    "lilongwe": ["capital of malawi"],
    "lilt": ["swing"],
    "lilting": ["swinging", "swingy", "tripping"],
    "lily of the valley": ["convallaria majalis", "may lily"],
    "lilyturf": ["lily turf", "liriope muscari"],
    "lima": ["capital of peru"],
    "lima bean": ["lima bean plant", "phaseolus limensis"],
    "limacidae": ["family limacidae"],
    "limacine": ["limacoid"],
    "limanda": ["genus limanda"],
    "limax": ["genus limax"],
    "limb": ["tree branch"],
    "limber": ["limber up"],
    "limber pine": ["pinus flexilis"],
    "limber up": ["loosen up", "warm up"],
    "limbic system": ["limbic brain", "visceral brain"],
    "lime": ["citrus aurantifolia", "lime tree"],
    "limelight": ["glare", "public eye", "spotlight"],
    "limenitis": ["genus limenitis"],
    "limestone fern": ["gymnocarpium robertianum", "northern oak fern"],
    "limestone salamander": ["hydromantes brunus"],
    "limey": ["john bull"],
    "limicolae": ["suborder limicolae"],
    "limit": ["circumscribe", "confine"],
    "limitation": ["restriction"],
    "limited": ["modified"],
    "limited company": ["ld.", "ltd."],
    "limiter": ["clipper"],
    "limnobium": ["genus limnobium"],
    "limnocryptes": ["genus limnocryptes"],
    "limnodromus": ["genus limnodromus"],
    "limonium": ["genus limonium"],
    "limosa": ["genus limosa"],
    "limousine": ["limo"],
    "limp": ["gimp", "hitch", "hobble"],
    "limpid": ["crystal clear", "lucid", "luculent", "pellucid", "perspicuous"],
    "limpkin": ["aramus pictus"],
    "limpopo": ["crocodile river"],
    "limulidae": ["family limulidae"],
    "limulus": ["genus limulus"],
    "lin": ["maya lin"],
    "linaceae": ["family linaceae", "flax family"],
    "linage": ["lineage"],
    "linanthus": ["genus linanthus"],
    "linaria": ["genus linaria"],
    "linchpin": ["lynchpin"],
    "lincoln": ["abraham lincoln", "president abraham lincoln", "president lincoln"],
    "lincoln's birthday": ["february 12"],
    "lincolnesque": ["lincolnian"],
    "lincomycin": ["lincocin"],
    "lind": ["jenny lind", "swedish nightingale"],
    "lindbergh": ["charles a. lindbergh", "charles augustus lindbergh", "charles lindbergh", "lucky lindy"],
    "linden": ["basswood", "lime", "lime tree", "linden tree"],
    "lindera": ["genus lindera"],
    "lindesnes": ["naze"],
    "lindheimera": ["genus lindheimera"],
    "lindsay": ["howard lindsay"],
    "lindy": ["lindy hop"],
    "line": ["run along"],
    "line of defense": ["line of defence"],
    "line of fate": ["line of destiny", "line of saturn"],
    "line of force": ["field line"],
    "line of heart": ["heart line", "love line", "mensal line"],
    "line of inquiry": ["line of questioning"],
    "line of least resistance": ["path of least resistance"],
    "line of life": ["life line", "lifeline"],
    "line of poetry": ["line of verse"],
    "line of sight": ["line of vision"],
    "line organization": ["line organisation"],
    "line printer": ["line-at-a-time printer"],
    "line storm": ["equinoctial storm"],
    "line up": ["come up", "find", "get hold"],
    "line-drive double": ["line double"],
    "line-drive single": ["line single"],
    "line-drive triple": ["line triple"],
    "lineage": ["ancestry", "blood", "blood line", "bloodline", "descent", "line", "line of descent", "origin", "parentage", "pedigree", "stemma", "stock"],
    "lineal": ["direct"],
    "linear": ["elongate"],
    "linear accelerator": ["linac"],
    "linear leaf": ["elongate leaf"],
    "linear regression": ["rectilinear regression"],
    "linear unit": ["linear measure"],
    "linearize": ["linearise"],
    "linebacker": ["line backer"],
    "linecut": ["line engraving"],
    "lined": ["seamed"],
    "lined snake": ["tropidoclonion lineatum"],
    "linen": ["linen paper"],
    "liner": ["lining"],
    "ling": ["ling ko", "trapa bicornis"],
    "ling-pao": ["mystic jewel"],
    "lingcod": ["ophiodon elongatus"],
    "linger": ["dawdle"],
    "lingerie": ["intimate apparel"],
    "lingeringly": ["protractedly"],
    "lingonberry": ["cowberry", "lowbush cranberry", "mountain cranberry"],
    "lingua franca": ["interlanguage", "koine"],
    "lingual artery": ["arteria lingualis"],
    "lingual vein": ["vena lingualis"],
    "linguine": ["linguini"],
    "linguist": ["linguistic scientist"],
    "linguistic": ["lingual"],
    "linguistic process": ["language"],
    "linguistically": ["lingually"],
    "linguistics": ["philology"],
    "linguistics department": ["department of linguistics"],
    "lingulate": ["tongue-shaped"],
    "liniment": ["embrocation"],
    "lining": ["liner"],
    "link": ["nexus"],
    "linkage": ["gene linkage"],
    "linkage group": ["linked genes"],
    "linkboy": ["linkman"],
    "links": ["golf links"],
    "linnaea": ["genus linnaea"],
    "linnaean": ["linnean"],
    "linnaeus": ["carl von linne", "carolus linnaeus", "karl linne"],
    "linnet": ["carduelis cannabina", "lintwhite"],
    "linoleic acid": ["linolic acid"],
    "linoleum": ["lino"],
    "linoleum knife": ["linoleum cutter"],
    "linotype": ["linotype machine"],
    "linseed": ["flaxseed"],
    "linseed oil": ["flaxseed oil"],
    "linum": ["genus linum"],
    "linz": ["lentia"],
    "liomys": ["genus liomys"],
    "lion": ["social lion"],
    "lion's foot": ["gall of the earth", "nabalus serpentarius", "prenanthes serpentaria"],
    "lion's-ear": ["leonotis nepetaefolia", "leonotis nepetifolia"],
    "lionize": ["celebrate", "lionise"],
    "lions club": ["international association of lions clubs"],
    "lip fern": ["lipfern"],
    "lip off": ["shoot one's mouth off"],
    "lip synchronization": ["lip sync", "lip synch", "lip synchronisation"],
    "lip-synch": ["lip-sync"],
    "liparididae": ["family liparidae", "family liparididae", "liparidae"],
    "liparis": ["genus liparis"],
    "lipchitz": ["jacques lipchitz"],
    "lipectomy": ["selective lipectomy"],
    "lipemia": ["hyperlipaemia", "hyperlipemia", "hyperlipidaemia", "hyperlipidemia", "hyperlipoidaemia", "hyperlipoidemia", "lipaemia", "lipidaemia", "lipidemia", "lipoidaemia", "lipoidemia"],
    "lipid": ["lipide", "lipoid"],
    "lipid-lowering medicine": ["lipid-lowering medication", "statin", "statin drug"],
    "lipless": ["unlipped"],
    "lipmann": ["fritz albert lipmann"],
    "lipoma": ["adipose tumor"],
    "lipophilic": ["lipotropic"],
    "liposcelis": ["genus liposcelis"],
    "liposuction": ["suction lipectomy"],
    "lipotyphla": ["suborder lipotyphla"],
    "lippi": ["filippino lippi"],
    "lippizan": ["lipizzan", "lippizaner"],
    "lippmann": ["walter lippmann"],
    "lipread": ["lip-read", "speech-read"],
    "lipscomb": ["william nunn lipscom jr."],
    "lipstick": ["lip rouge"],
    "lipstick plant": ["aeschynanthus radicans"],
    "liquefiable": ["liquifiable"],
    "liquefied": ["liquified"],
    "liquefied petroleum gas": ["bottled gas"],
    "liquefy": ["liquidise", "liquidize", "liquify"],
    "liquescent": ["melting"],
    "liqueur": ["cordial"],
    "liquid": ["liquid state", "liquidity", "liquidness"],
    "liquid assets": ["current assets", "quick assets"],
    "liquid body substance": ["bodily fluid", "body fluid", "humor", "humour"],
    "liquid crystal display": ["lcd"],
    "liquid oxygen": ["lox"],
    "liquid unit": ["liquid measure"],
    "liquidate": ["pay off"],
    "liquidation": ["settlement"],
    "liquidator": ["receiver"],
    "liquor": ["booze", "hard drink", "hard liquor", "john barleycorn", "spirits", "strong drink"],
    "liquor license": ["liquor licence"],
    "lir": ["ler"],
    "lira": ["maltese lira"],
    "liriodendron": ["genus liriodendron"],
    "liriope": ["genus liriope"],
    "lisbon": ["capital of portugal", "lisboa"]
}
