synonyms = {
    "lisinopril": ["prinival", "zestril"],
    "lisle": ["lisle thread"],
    "lisp": ["list-processing language"],
    "lissome": ["lissom", "lithe", "lithesome", "slender", "supple", "svelte", "sylphlike"],
    "lissomeness": ["litheness", "suppleness"],
    "list": ["lean"],
    "list system": ["scrutin de liste", "scrutin de liste system"],
    "listen": ["hear", "take heed"],
    "listen in": ["eavesdrop"],
    "listening": ["hearing"],
    "listening watch": ["continuous receiver watch"],
    "lister": ["baron lister", "joseph lister"],
    "listera": ["genus listera"],
    "listeria monocytogenes": ["l. monocytogenes"],
    "listeriosis": ["listeria meningitis"],
    "listing": ["itemisation", "itemization"],
    "listlessness": ["torpidity", "torpidness", "torpor"],
    "liston": ["charles liston", "sonny liston"],
    "liszt": ["franz liszt"],
    "litchi": ["lichee", "litchi chinensis", "litchi tree", "nephelium litchi"],
    "liter": ["cubic decimeter", "cubic decimetre", "litre"],
    "literalize": ["literalise"],
    "literary composition": ["literary work"],
    "literary criticism": ["lit crit"],
    "literate": ["literate person"],
    "literature": ["lit"],
    "lithium": ["atomic number 3", "li"],
    "lithium carbonate": ["eskalith", "lithane", "lithonate"],
    "lithocarpus": ["genus lithocarpus"],
    "lithodidae": ["family lithodidae"],
    "lithograph": ["lithograph machine"],
    "lithophragma": ["genus lithophragma"],
    "lithophyte": ["lithophytic plant"],
    "lithops": ["flowering stone", "living stone", "stone life face", "stone plant", "stone-face", "stoneface"],
    "lithospermum": ["genus lithospermum"],
    "lithosphere": ["geosphere"],
    "lithuania": ["lietuva", "republic of lithuania"],
    "litigant": ["litigator"],
    "litigation": ["judicial proceeding"],
    "litmus": ["litmus test"],
    "litocranius": ["genus litocranius"],
    "litotes": ["meiosis"],
    "litterbin": ["litter basket", "litter-basket"],
    "litterer": ["litter lout", "litterbug"],
    "little": ["small"],
    "little auk": ["dovekie", "plautus alle"],
    "little barley": ["hordeum pusillum"],
    "little bear": ["ursa minor"],
    "little bighorn": ["little bighorn river", "little horn"],
    "little black ant": ["monomorium minimum"],
    "little blue heron": ["egretta caerulea"],
    "little brown bat": ["little brown myotis", "myotis leucifugus"],
    "little chief hare": ["ochotona princeps"],
    "little dipper": ["dipper"],
    "little egret": ["egretta garzetta"],
    "little finger": ["pinkie", "pinky"],
    "little golden zinnia": ["zinnia grandiflora"],
    "little missouri": ["little missouri river"],
    "little owl": ["athene noctua"],
    "little potato": ["rosette", "russet scab", "stem canker"],
    "little rock": ["capital of arkansas"],
    "little skate": ["raja erinacea"],
    "little slam": ["small slam"],
    "little theater": ["little theatre"],
    "little wabash": ["little wabash river"],
    "little-head snakeweed": ["gutierrezia microcephala"],
    "littleneck": ["littleneck clam"],
    "littoral": ["litoral", "littoral zone", "sands"],
    "littorina": ["genus littorina"],
    "littorinidae": ["family littorinidae"],
    "littre": ["maximilien paul emile littre"],
    "liturgics": ["liturgiology"],
    "livable": ["liveable"],
    "live": ["unrecorded"],
    "live axle": ["driving axle"],
    "live in": ["sleep in"],
    "live load": ["superload"],
    "live out": ["sleep out"],
    "liveliness": ["life", "spirit", "sprightliness"],
    "lively": ["racy"],
    "liver cancer": ["cancer of the liver"],
    "liver fluke": ["fasciola hepatica"],
    "liver pudding": ["liver sausage", "liverwurst"],
    "liver-colored": ["liver"],
    "livermore": ["mary ashton rice livermore"],
    "liverpudlian": ["scouser"],
    "liverwort": ["hepatic"],
    "livestock": ["farm animal", "stock"],
    "lividness": ["achromasia", "lividity", "luridness", "paleness", "pallidness", "pallor", "wanness"],
    "living granite": ["living rock", "stone mimicry plant"],
    "living quarters": ["quarters"],
    "living rock": ["ariocarpus fissuratus"],
    "living room": ["front room", "living-room", "parlor", "parlour", "sitting room"],
    "living space": ["lebensraum"],
    "living thing": ["animate thing"],
    "living trust": ["inter vivos trust"],
    "livingroom suite": ["livingroom set"],
    "livingston": ["robert r. livingston"],
    "livingstone": ["david livingstone"],
    "livingstone daisy": ["dorotheanthus bellidiformis"],
    "livistona": ["genus livistona"],
    "livy": ["titus livius"],
    "liza": ["mugil liza"],
    "lizard orchid": ["himantoglossum hircinum"],
    "lizard's-tail": ["saururus cernuus", "swamp lily", "water dragon"],
    "lizardfish": ["snake-fish", "snakefish"],
    "lloyd": ["harold clayton lloyd", "harold lloyd"],
    "lloyd webber": ["andrew lloyd webber", "baron lloyd webber of sydmonton"],
    "load": ["charge"],
    "load line": ["plimsoll", "plimsoll line", "plimsoll mark"],
    "load-bearing": ["supporting"],
    "loading zone": ["loading area"],
    "loaf of bread": ["loaf"],
    "loanblend": ["hybrid", "loan-blend"],
    "loanword": ["loan"],
    "loasaceae": ["family loasaceae", "loasa family"],
    "loath": ["loth", "reluctant"],
    "loathsomeness": ["lousiness", "repulsiveness", "sliminess", "vileness", "wickedness"],
    "lobachevsky": ["nikolai ivanovich lobachevsky"],
    "lobata": ["order lobata"],
    "lobate": ["lobated"],
    "lobby": ["buttonhole"],
    "lobed": ["lobate"],
    "lobed spleenwort": ["asplenium pinnatifidum"],
    "lobeliaceae": ["family lobeliaceae", "lobelia family"],
    "lobipes": ["genus lobipes"],
    "loblolly pine": ["frankincense pine", "pinus taeda"],
    "lobotes": ["genus lobotes"],
    "lobotidae": ["family lobotidae"],
    "lobotomy": ["frontal lobotomy", "leucotomy", "leukotomy", "prefrontal leucotomy", "prefrontal leukotomy", "prefrontal lobotomy"],
    "lobscouse": ["lobscuse", "scouse"],
    "lobster newburg": ["lobster a la newburg"],
    "lobularia": ["genus lobularia"],
    "local anesthesia": ["local anaesthesia"],
    "local anesthetic": ["local", "local anaesthetic", "topical anaesthetic", "topical anesthetic"],
    "local area network": ["lan"],
    "local department": ["department of local government"],
    "local oscillator": ["heterodyne oscillator"],
    "local road": ["local street"],
    "localization": ["fix", "localisation", "locating", "location"],
    "localization of function": ["localisation", "localisation of function", "localisation principle", "localization", "localization principle"],
    "localize": ["focalise", "focalize", "localise"],
    "localized": ["localised"],
    "locally": ["topically"],
    "locate": ["place", "site"],
    "located": ["placed", "set", "situated"],
    "locative role": ["locative"],
    "locator": ["locater"],
    "loch ness monster": ["nessie"],
    "lock": ["interlace", "interlock"],
    "lock in": ["seal in"],
    "locke": ["john locke"],
    "locking": ["lockup"],
    "lockmaster": ["lockkeeper", "lockman"],
    "locknut": ["safety nut"],
    "lockring": ["lock ring", "lock washer"],
    "loco disease": ["locoism"],
    "locomotion": ["motive power", "motivity"],
    "locomotive": ["engine", "locomotive engine", "railway locomotive"],
    "locoweed": ["crazy weed", "crazyweed"],
    "locule": ["loculus"],
    "locum tenens": ["locum"],
    "locust tree": ["locust"],
    "locusta": ["genus locusta"],
    "loddon pondweed": ["potamogeton americanus", "potamogeton nodosus"],
    "lode": ["load"],
    "lodestar": ["loadstar"],
    "lodestone": ["loadstone"],
    "lodge": ["accommodate"],
    "lodger": ["boarder", "roomer"],
    "lodging house": ["rooming house"],
    "lodgment": ["lodgement"],
    "loeb": ["jacques loeb"],
    "loewe": ["frederick loewe"],
    "loewi": ["otto loewi"],
    "lofortyx": ["genus lofortyx"],
    "loft": ["pigeon loft"],
    "loft bombing": ["toss bombing"],
    "log": ["lumber"],
    "log in": ["log on", "log-in"],
    "log out": ["log off"],
    "log up": ["clock up"],
    "logan": ["mount logan"],
    "loganberry": ["rubus loganobaccus", "rubus ursinus loganobaccus"],
    "logania": ["genus logania"],
    "loganiaceae": ["family loganiaceae"],
    "logarithm": ["log"],
    "loggerhead": ["caretta caretta", "loggerhead turtle"],
    "loggerhead shrike": ["lanius lucovicianus"],
    "logic": ["logical system", "system of logic"],
    "logic bomb": ["slag code"],
    "logic diagram": ["logical diagram"],
    "logic operation": ["logical operation"],
    "logic programming": ["logic programing"],
    "logicality": ["logicalness"],
    "logician": ["logistician"],
    "loginess": ["logginess"],
    "logistic": ["logistical"],
    "logistic support": ["logistic assistance"],
    "logo": ["logotype"],
    "logogram": ["logograph"],
    "logogrammatic": ["logographic"],
    "logomach": ["logomachist"],
    "logorrhea": ["logomania"],
    "logwood": ["bloodwood tree", "campeachy", "haematoxylum campechianum", "logwood tree"],
    "loin": ["lumbus"],
    "loir": ["glis glis"],
    "loire": ["loire river"],
    "loiseleuria": ["genus loiseleuria"],
    "loiter": ["footle", "hang around", "lallygag", "linger", "loaf", "lollygag", "lounge", "lurk", "mess about", "mill about", "mill around", "tarry"],
    "loiterer": ["lingerer"],
    "lolium": ["genus lolium"],
    "lollipop": ["all-day sucker", "sucker"],
    "lollipop lady": ["lollipop woman"],
    "lolo": ["yi"],
    "lolo-burmese": ["burmese-yi"],
    "lomariopsidaceae": ["family lomariopsidaceae"],
    "lombard": ["langobard"],
    "lombardy": ["lombardia"],
    "lombardy poplar": ["populus nigra italica"],
    "lome": ["capital of togo"],
    "lomogramma": ["genus lomogramma"],
    "lonas": ["genus lonas"],
    "lonchocarpus": ["genus lonchocarpus"],
    "london": ["jack london", "john griffith chaney"],
    "london plane": ["platanus acerifolia"],
    "lone": ["lonely", "solitary"],
    "loneliness": ["solitariness"],
    "lonely": ["solitary", "unfrequented"],
    "loner": ["lone hand", "lone wolf"],
    "long ago": ["lang syne", "long since"],
    "long beech fern": ["dryopteris phegopteris", "narrow beech fern", "northern beech fern", "phegopteris connectilis", "thelypteris phegopteris"],
    "long bone": ["os longum"],
    "long chain": ["long-chain molecule"],
    "long distance": ["long-distance call", "trunk call"],
    "long hundred": ["120", "great hundred"],
    "long jump": ["broad jump"],
    "long pepper": ["piper longum"],
    "long run": ["long haul"],
    "long saphenous vein": ["great saphenous vein"],
    "long time": ["age", "years"],
    "long ton": ["gross ton", "ton"],
    "long trousers": ["long pants"],
    "long underwear": ["union suit"],
    "long-billed marsh wren": ["cistothorus palustris"],
    "long-clawed prawn": ["palaemon australis", "river prawn"],
    "long-eared owl": ["asio otus"],
    "long-familiar": ["well-known"],
    "long-handled": ["pole-handled"],
    "long-head coneflower": ["prairie coneflower", "ratibida columnifera"],
    "long-horned beetle": ["longicorn", "longicorn beetle"],
    "long-horned grasshopper": ["tettigoniid"],
    "long-play": ["long-playing"],
    "long-run": ["long-term", "semipermanent"],
    "long-spurred violet": ["viola rostrata"],
    "long-stalked": ["tall-stalked"],
    "long-sufferance": ["long-suffering"],
    "long-tailed porcupine": ["trichys lipura"],
    "long-term memory": ["ltm"],
    "long-winded": ["tedious", "verbose", "windy", "wordy"],
    "long-wool": ["long-wooled"],
    "longan": ["dimocarpus longan", "euphorbia litchi", "longanberry", "lungen", "nephelium longana"],
    "longanberry": ["dragon's eye"],
    "longed-for": ["wished-for", "yearned-for"],
    "longer": ["thirster", "yearner"],
    "longevity": ["length of service"],
    "longfellow": ["henry wadsworth longfellow"],
    "longfin mako": ["isurus paucus"],
    "longhand": ["cursive", "cursive script", "running hand"],
    "longheaded thimbleweed": ["anemone riparia"],
    "longhorn": ["texas longhorn"],
    "longing": ["hungriness", "yearning"],
    "longingly": ["yearningly"],
    "longleaf pine": ["georgia pine", "pinus palustris", "pitch pine", "southern yellow pine"],
    "longtail weasel": ["long-tailed weasel", "mustela frenata"],
    "longways": ["longways dance"],
    "lonicera": ["genus lonicera"],
    "loofa": ["loofah", "loufah sponge", "luffa"],
    "loofah": ["luffa cylindrica", "vegetable sponge"],
    "look": ["appear", "seem"],
    "look back": ["look backward"],
    "look out on": ["look across", "look out over", "overlook"],
    "lookdown": ["lookdown fish", "selene vomer"],
    "looking": ["looking for"],
    "looking glass": ["glass"],
    "looking glass tree": ["heritiera macrophylla"],
    "looking-glass plant": ["heritiera littoralis"],
    "lookout": ["lookout man", "picket", "scout", "sentinel", "sentry", "spotter", "watch"],
    "loom": ["hulk", "predominate", "tower"],
    "loon": ["diver"],
    "loop": ["intertwine"],
    "loop topology": ["loop"],
    "loos": ["adolf loos"],
    "loose": ["free"],
    "loose end": ["unfinished business"],
    "loose off": ["let drive", "let fly"],
    "loosely": ["slackly"],
    "loosen": ["loose"],
    "looseness": ["play"],
    "loosening": ["laxation"],
    "loot": ["plunder"],
    "looted": ["pillaged", "plundered", "ransacked"],
    "looting": ["robbery"],
    "lophiidae": ["family lophiidae"],
    "lophius": ["genus lophius"],
    "lophodytes": ["genus lophodytes"],
    "lopholatilus": ["genus lopholatilus"],
    "lophophora": ["genus lophophora"],
    "lophophorus": ["genus lophophorus"],
    "lophosoria": ["genus lophosoria"],
    "lophosoriaceae": ["family lophosoriaceae"],
    "lopsidedly": ["crookedly"],
    "lopsidedness": ["skewness"],
    "loquaciously": ["garrulously", "talkatively", "talkily"],
    "loquat": ["eriobotrya japonica", "japanese medlar", "japanese plum", "loquat tree"],
    "loranthaceae": ["family loranthaceae", "mistletoe family"],
    "loranthus": ["genus loranthus"],
    "lorazepam": ["ativan"],
    "lord": ["noble", "nobleman"],
    "lord chancellor": ["lord high chancellor"],
    "lord it over": ["act superior", "put on airs", "queen it over"],
    "lordless": ["masterless"],
    "lordosis": ["hollow-back"],
    "lore": ["traditional knowledge"],
    "loren": ["sofia scicolone", "sophia loren"],
    "lorentz": ["hendrik antoon lorentz"],
    "lorenz": ["konrad lorenz", "konrad zacharias lorenz"],
    "lorenzo de'medici": ["lorenzo the magnificent"],
    "loricata": ["order loricata"],
    "loriinae": ["subfamily loriinae"],
    "lorisidae": ["family lorisidae"],
    "lorraine": ["lothringen"],
    "lorraine cross": ["cross of lorraine"],
    "lorre": ["laszlo lowestein", "peter lorre"],
    "lorry": ["camion"],
    "los angeles": ["city of the angels"],
    "lose": ["turn a loss"],
    "loser": ["also-ran"],
    "losings": ["losses"],
    "loss": ["red", "red ink"],
    "lost": ["missed"],
    "lota": ["genus lota"],
    "lotion": ["application"],
    "lottery": ["drawing"],
    "lotto": ["beano", "bingo", "keno"],
    "lotus": ["genus lotus"],
    "lotus tree": ["ziziphus lotus"],
    "lotus-eater": ["stargazer"],
    "lotusland": ["lotus land"],
    "louche": ["shady"],
    "loudly": ["aloud", "loud"],
    "loudmouth": ["blusterer"],
    "loudspeaker": ["loudspeaker system", "speaker", "speaker system", "speaker unit"],
    "louis": ["joe louis", "joseph louis barrow"],
    "louis i": ["louis the pious"],
    "louis ii": ["louis le begue", "louis the german", "louis the stammerer"],
    "louis iv": ["louis d'outremer"],
    "louis ix": ["saint louis", "st. louis"],
    "louis v": ["louis le faineant"],
    "louis vi": ["louis the bruiser", "louis the far", "louis the wideawake"],
    "louis x": ["louis le hutin", "louis the quarreller"],
    "louis xiv": ["louis the great", "sun king"],
    "louisiana": ["la", "pelican state"],
    "louisianan": ["louisianian"],
    "lounge": ["waiting area", "waiting room"],
    "lounge lizard": ["lizard"],
    "lounging jacket": ["smoking jacket"],
    "lounging pajama": ["lounging pyjama"],
    "loupe": ["jeweler's loupe"],
    "louse": ["sucking louse"],
    "louse fly": ["hippoboscid"],
    "lout": ["clod", "gawk", "goon", "lubber", "lummox", "lump", "oaf", "stumblebum"],
    "louvar": ["luvarus imperialis"],
    "louver": ["fin", "louvre"],
    "louvered window": ["jalousie"],
    "louvre": ["louvre museum"],
    "lovable": ["loveable"],
    "lovage": ["levisticum officinale"],
    "lovastatin": ["mevacor"],
    "love": ["enjoy"],
    "love affair": ["romance"],
    "love grass": ["bay grass"],
    "love knot": ["lover's knot", "lovers' knot", "true lover's knot", "true lovers' knot"],
    "love letter": ["billet doux"],
    "love seat": ["loveseat", "tete-a-tete", "vis-a-vis"],
    "love song": ["love-song"],
    "love story": ["romance"],
    "love vine": ["cuscuta gronovii"],
    "love-in-a-mist": ["passiflora foetida", "running pop", "wild water lemon"],
    "love-in-winter": ["chimaphila corymbosa", "chimaphila umbellata", "western prince's pine"],
    "love-lies-bleeding": ["amaranthus caudatus", "tassel flower", "velvet flower"],
    "lovelace": ["richard lovelace"],
    "lovell": ["sir alfred charles bernard lovell", "sir bernard lovell"],
    "loverlike": ["loverly"],
    "lovingness": ["caring"],
    "lovoa": ["genus lovoa"],
    "low": ["depression"],
    "low frequency": ["lf"],
    "low german": ["plattdeutsch"],
    "low pitch": ["low frequency"],
    "low st andrew's cross": ["hypericum hypericoides"],
    "low status": ["lowliness", "lowness"],
    "low tide": ["low water"],
    "low-birth-weight baby": ["low-birth-weight infant"],
    "low-bush blueberry": ["low blueberry", "vaccinium angustifolium", "vaccinium pennsylvanicum"],
    "low-cost": ["affordable", "low-priced"],
    "low-density lipoprotein": ["beta-lipoprotein", "ldl"],
    "low-growing": ["flat-growing", "ground-hugging"],
    "low-key": ["low-keyed", "subdued"],
    "low-level": ["low-altitude"],
    "low-level formatting": ["initialisation", "initialization"],
    "low-lying": ["sea-level"],
    "low-sodium diet": ["low-salt diet", "salt-free diet"],
    "low-tension": ["low-voltage"],
    "lowball": ["underestimate"],
    "lowbrow": ["lowbrowed", "uncultivated"],
    "lowell": ["robert lowell", "robert traill spence lowell jr."],
    "lower": ["bring down", "get down", "let down", "take down"],
    "lower berth": ["lower"],
    "lower california": ["baja california"],
    "lower class": ["underclass"],
    "lower deck": ["third deck"],
    "lower jaw": ["jawbone", "jowl", "lower jawbone", "mandible", "mandibula", "mandibular bone", "submaxilla"],
    "lower respiratory tract smear": ["bronchoscopic smear", "sputum smear"],
    "lower-class": ["low-class"],
    "lowerclassman": ["underclassman"],
    "lowering": ["letting down"],
    "lowest common multiple": ["lcm", "least common multiple"],
    "lowland burrowing treefrog": ["northern casque-headed frog", "pternohyla fodiens"],
    "lowland fir": ["abies grandis", "giant fir", "grand fir", "lowland white fir"],
    "lowlander": ["lowland scot", "scottish lowlander"],
    "lowlands": ["lowlands of scotland"],
    "lowry": ["l. s. lowry", "laurence stephen lowry"],
    "lowset": ["low-set"],
    "loxapine": ["loxitane"],
    "loxia": ["genus loxia"],
    "loxodonta": ["genus loxodonta"],
    "loxoma": ["genus loxoma"],
    "loxomataceae": ["family loxomataceae"],
    "loxostege": ["genus loxostege"],
    "loyalist": ["stalwart"],
    "loyalty": ["trueness"],
    "lozier": ["clemence sophia harned lozier"],
    "lp": ["l-p"],
    "luanda": ["angolan capital"],
    "luba": ["chiluba"],
    "lubavitch": ["chabad", "chabad-lubavitch", "lubavitch movement"],
    "lubber's line": ["lubber line", "lubber's mark", "lubber's point"],
    "lubberly": ["landlubberly"],
    "lubitsch": ["ernst lubitsch"],
    "lubricant": ["lube", "lubricating substance", "lubricator"],
    "lubricate": ["lube"],
    "lubricated": ["greased"],
    "lubricating system": ["force feed", "force-feed lubricating system", "pressure feed", "pressure-feed lubricating system"],
    "lubricious": ["lustful", "prurient", "salacious"],
    "lubumbashi": ["elisabethville"],
    "lucanidae": ["family lucanidae"],
    "lucas": ["george lucas"],
    "luce": ["henry luce", "henry robinson luce"],
    "lucidly": ["limpidly", "pellucidly", "perspicuously"],
    "lucifugous": ["lucifugal"],
    "lucilia": ["genus lucilia"],
    "lucite": ["perspex"],
    "luck": ["fortune"],
    "luck it": ["luck through"],
    "luck out": ["hit the jackpot"],
    "lucrative": ["moneymaking", "remunerative"],
    "lucretius": ["titus lucretius carus"],
    "lucullus": ["licinius lucullus", "lucius licinius lucullus"],
    "luculus": ["lucius licinius luculus"],
    "luda": ["luta"],
    "ludi saeculares": ["secular games"],
    "lufengpithecus": ["genus lufengpithecus"],
    "luff": ["point"],
    "luffa": ["dishcloth gourd", "rag gourd", "sponge gourd", "strainer vine"],
    "luftwaffe": ["german luftwaffe"],
    "lug": ["tote", "tug"],
    "luger": ["slider"],
    "luggage compartment": ["automobile trunk", "trunk"],
    "luggage rack": ["roof rack"],
    "lugosi": ["bela ferenc blasko", "bela lugosi"],
    "lugsail": ["lug"],
    "lugworm": ["lobworm", "lug"],
    "luke": ["saint luke", "st. luke"],
    "lukewarm": ["tepid"],
    "lukewarmly": ["tepidly"],
    "lukewarmness": ["tepidity", "tepidness"],
    "lule burgas": ["battle of lule burgas"],
    "lull": ["calm down"],
    "lullaby": ["berceuse", "cradlesong"],
    "lully": ["ramon lully", "raymond lully"],
    "lumbago": ["lumbar pain"],
    "lumbar artery": ["arteria lumbalis"],
    "lumbar plexus": ["plexus lumbalis"],
    "lumbar puncture": ["spinal puncture", "spinal tap"],
    "lumbar vein": ["vena lumbalis"],
    "lumber": ["pound"],
    "lumberjack": ["lumber jacket"],
    "lumberman": ["faller", "feller", "logger", "lumberjack"],
    "lumbermill": ["sawmill"],
    "lumen": ["lm"],
    "luminary": ["guiding light", "leading light", "notability", "notable"],
    "luminescence": ["glow"],
    "luminosity": ["brightness", "brightness level", "light", "luminance", "luminousness"],
    "luminous intensity unit": ["candlepower unit"],
    "lump": ["chunk"],
    "lumpenus": ["genus lumpenus"],
    "lumpfish": ["cyclopterus lumpus"],
    "lumpish": ["lumpen", "unthinking"],
    "luna moth": ["actias luna"],
    "lunacy": ["insaneness", "madness"],
    "lunar excursion module": ["lem", "lunar module"],
    "lunar month": ["lunation", "moon", "synodic month"],
    "lunaria": ["genus lunaria"],
    "lunate bone": ["os lunatum", "semilunar bone"],
    "lunatic": ["madman", "maniac"],
    "lunch": ["dejeuner", "luncheon", "tiffin"],
    "lunch meat": ["luncheon meat"],
    "luncheon meeting": ["lunch meeting"],
    "lunchtime": ["lunch period"],
    "lunda": ["genus lunda"],
    "lunette": ["fenestella"],
    "lunge": ["hurl", "hurtle", "thrust"],
    "lungi": ["longyi", "lungyi"],
    "lungless salamander": ["plethodont"],
    "lunt": ["alfred lunt"],
    "luoyang": ["loyang"],
    "lupine": ["lupin"],
    "lupinus": ["genus lupinus"],
    "lupus erythematosus": ["le"],
    "lurch": ["pitch", "shift"],
    "lure": ["come-on", "enticement"],
    "lurid": ["shocking"],
    "lurk": ["skulk"],
    "lurker": ["lurcher", "skulker"],
    "lusaka": ["capital of zambia"],
    "luscinia": ["genus luscinia"],
    "lusciously": ["deliciously", "scrumptiously"],
    "lush": ["succulent"],
    "lushun": ["port arthur"],
    "lust": ["luxuria"],
    "lust after": ["lech after"],
    "luster": ["brilliancy", "lustre", "splendor", "splendour"],
    "lustful": ["concupiscent", "lusty"],
    "lute": ["luting"],
    "lutefisk": ["lutfisk"],
    "luteinizing hormone": ["icsh", "interstitial cell-stimulating hormone", "lh"],
    "lutetium": ["atomic number 71", "lu", "lutecium"],
    "luther": ["martin luther"],
    "lutist": ["lutanist", "lutenist"],
    "lutjanidae": ["family lutjanidae"],
    "lutjanus": ["genus lutjanus"],
    "lutra": ["genus lutra"],
    "lutrinae": ["subfamily lutrinae"],
    "lutyens": ["sir edwin landseer luytens", "sir edwin lutyens"],
    "lutzen": ["battle of lutzen"],
    "luvaridae": ["family luvaridae"],
    "luvarus": ["genus luvarus"],
    "luwian": ["luvian"],
    "lux": ["lx"],
    "luxembourg": ["grand duchy of luxembourg", "luxemburg"],
    "luxembourg-ville": ["capital of luxembourg", "luxembourg", "luxembourg city", "luxemburg"],
    "luxemburger": ["luxembourger"],
    "luxor": ["el-aksur"],
    "luxuriance": ["lushness", "voluptuousness"],
    "luxuriate": ["wanton"],
    "luxury": ["luxuriousness", "opulence", "sumptuousness"],
    "luxury liner": ["express luxury liner"],
    "lycaena": ["genus lycaena"],
    "lycaenid": ["lycaenid butterfly"],
    "lycaenidae": ["family lycaenidae"],
    "lycaeon": ["genus lycaeon"],
    "lychgate": ["lichgate"],
    "lychnis": ["catchfly"],
    "lycium": ["genus lycium"],
    "lycoperdaceae": ["family lycoperdaceae"],
    "lycoperdales": ["order lycoperdales"],
    "lycoperdon": ["genus lycoperdon"],
    "lycopersicon": ["genus lycopersicon", "genus lycopersicum", "lycopersicum"],
    "lycopodiaceae": ["clubmoss family", "family lycopodiaceae"],
    "lycopodiales": ["order lycopodiales"],
    "lycopodineae": ["class lycopodineae"],
    "lycopodium": ["genus lycopodium"],
    "lycopsida": ["class lycopodiate", "class lycopsida", "lycopodiate"],
    "lycopus": ["genus lycopus"],
    "lycosa": ["genus lycosa"],
    "lycosidae": ["family lycosidae"],
    "lygaeid": ["lygaeid bug"],
    "lygaeidae": ["family lygaeidae"],
    "lyginopteris": ["genus lyginopteris"],
    "lygodium": ["genus lygodium"],
    "lygus": ["genus lygus"],
    "lying": ["fabrication", "prevarication"],
    "lyly": ["john lyly"],
    "lymantria": ["genus lymantria"],
    "lymantriid": ["tussock moth"],
    "lymantriidae": ["family lymantriidae"],
    "lyme disease": ["lyme arthritis"],
    "lymph node": ["lymph gland", "node"],
    "lymph vessel": ["lymphatic vessel"],
    "lymphangiectasia": ["lymphangiectasis"],
    "lymphangiography": ["lymphography"],
    "lymphatic system": ["systema lymphaticum"],
    "lymphatic tissue": ["lymphoid tissue"],
    "lymphocyte": ["lymph cell"],
    "lymphocytopenia": ["lymphopenia"],
    "lymphogranuloma venereum": ["lgv", "lymphopathia venereum"],
    "lynx": ["catamount"],
    "lyon": ["lyons"],
    "lyonia": ["genus lyonia"],
    "lyonnaise sauce": ["brown onion sauce"],
    "lyons": ["second council of lyons"],
    "lyophilize": ["lyophilise"],
    "lyophilized": ["freeze-dried", "lyophilised"],
    "lyric": ["language", "words"],
    "lyricality": ["lyricism", "songfulness"],
    "lyricist": ["lyrist"],
    "lyrurus": ["genus lyrurus"],
    "lysenko": ["trofim denisovich lysenko"],
    "lysergic acid diethylamide": ["lsd"],
    "lysichiton": ["genus lysichiton", "genus lysichitum", "lysichitum"],
    "lysiloma": ["genus lysiloma"],
    "lysimachia": ["genus lysimachia"],
    "lysogenization": ["lysogenisation"],
    "lysogeny": ["lysogenicity"],
    "lysozyme": ["muramidase"],
    "lythraceae": ["family lythraceae", "loosestrife family"],
    "lythrum": ["genus lythrum"],
    "lytton": ["bulwer-lytton", "edward george earle bulwer-lytton", "first baron lytton"],
    "ma": ["mama", "mamma", "mammy", "mom", "momma", "mommy", "mum", "mummy"],
    "macaca": ["genus macaca"],
    "macadamia": ["macadamia tree"],
    "macadamia nut": ["macadamia nut tree", "macadamia ternifolia"],
    "macadamize": ["macadamise", "tarmac"],
    "macao": ["macau"],
    "macarthur": ["douglas macarthur"],
    "macaulay": ["first baron macaulay", "lord macaulay", "thomas babington macaulay"],
    "macdowell": ["edward macdowell"],
    "mace": ["chemical mace"],
    "macebearer": ["mace", "macer"],
    "macedon": ["macedonia", "makedonija"],
    "macgregor": ["rob roy", "robert macgregor"],
    "mach": ["ernst mach"],
    "machaeranthera": ["genus machaeranthera"],
    "machete": ["matchet", "panga"],
    "machiavelli": ["niccolo machiavelli"],
    "machilidae": ["family machilidae"],
    "machine": ["political machine"],
    "machine code": ["machine language"],
    "machine politician": ["hack", "political hack", "ward-heeler"],
    "machine readable": ["computer readable"],
    "machine readable dictionary": ["electronic dictionary", "mrd"],
    "machine stitch": ["sewing-machine stitch"],
    "machine translation": ["mt"],
    "machine wash": ["machine-wash"],
    "machine-accessible": ["connected"],
    "machinist": ["mechanic", "shop mechanic"],
    "machinist's vise": ["metalworking vise"],
    "macintosh": ["mac", "mack", "mackintosh"],
    "mackenzie": ["sir alexander mackenzie"],
    "mackerel scad": ["decapterus macarellus", "mackerel shad"],
    "mackinaw": ["mackinaw coat"],
    "mackintosh": ["macintosh"],
    "macleaya": ["genus macleaya"],
    "macleish": ["archibald macleish"],
    "macleod": ["john james rickard macleod", "john macleod"],
    "maclura": ["genus maclura"],
    "macon": ["maconnais"],
    "macowanites": ["genus macowanites"],
    "macrencephalic": ["macrencephalous"],
    "macro": ["macro instruction"],
    "macrocephalic": ["macrocephalous"],
    "macrocephalon": ["genus macrocephalon"],
    "macrocephaly": ["megacephaly", "megalocephaly"],
    "macrocheira": ["genus macrocheira"],
    "macroclemys": ["genus macroclemys"],
    "macrocytic anemia": ["macrocytic anaemia"],
    "macrodactylus": ["genus macrodactylus"],
    "macroeconomist": ["macroeconomic expert"],
    "macromolecule": ["supermolecule"],
    "macronectes": ["genus macronectes"],
    "macropodidae": ["family macropodidae"],
    "macropus": ["genus macropus"],
    "macrorhamphosidae": ["family macrorhamphosidae"],
    "macroscopic": ["macroscopical"],
    "macrothelypteris": ["genus macrothelypteris"],
    "macrotis": ["genus macrotis"],
    "macrotus": ["macrotus californicus"],
    "macrotyloma": ["genus macrotyloma"],
    "macrouridae": ["family macrouridae", "family macruridae", "macruridae"],
    "macrozoarces": ["genus macrozoarces"],
    "macula": ["macula lutea", "macular area", "yellow spot"],
    "macule": ["macula"],
    "madagascar": ["malagasy republic", "republic of madagascar"],
    "madagascar cat": ["lemur catta", "ring-tailed lemur"],
    "madagascar jasmine": ["stephanotis floribunda", "waxflower"],
    "madam": ["brothel keeper"],
    "madden": ["craze"],
    "madder": ["rubia tinctorum"],
    "madderwort": ["rubiaceous plant"],
    "madeira": ["madeira river"],
    "madeira cake": ["madeira sponge"],
    "madeira islands": ["madeiras"],
    "madia": ["genus madia"],
    "madison": ["james madison", "president madison"],
    "madly": ["frantically"],
    "madness": ["rabidity", "rabidness"],
    "madonna": ["madonna louise ciccone"],
    "madonna lily": ["annunciation lily", "lent lily", "lilium candidum", "white lily"],
    "madoqua": ["genus madoqua"],
    "madrasa": ["madrasah"],
    "madreporaria": ["order madreporaria"],
    "madrid": ["capital of spain", "spanish capital"],
    "madrona": ["arbutus menziesii", "madrono", "manzanita"],
    "mae west": ["air jacket"],
    "maeandra": ["genus maeandra"],
    "maestro": ["master"],
    "maeterlinck": ["count maurice maeterlinck"],
    "mafia": ["cosa nostra", "maffia"],
    "magazine": ["magazine publisher"],
    "magdalena": ["magdalena river"],
    "magellan": ["ferdinand magellan", "fernao magalhaes"],
    "magenta": ["battle of magenta"],
    "magh": ["magha"],
    "maghreb": ["mahgrib"],
    "magic": ["thaumaturgy"],
    "magic trick": ["conjuration", "conjuring trick", "deception", "illusion", "legerdemain", "magic", "thaumaturgy", "trick"],
    "magical ability": ["magical power"],
    "magically": ["as if by magic"],
    "magician": ["conjurer", "conjuror", "illusionist", "prestidigitator"],
    "magicicada": ["genus magicicada"],
    "maginot": ["andre maginot"],
    "magistracy": ["magistrature"],
    "magna carta": ["magna charta", "the great charter"],
    "magnesium": ["atomic number 12", "mg"],
    "magnetic": ["magnetised", "magnetized"],
    "magnetic core memory": ["core memory"],
    "magnetic declination": ["magnetic variation", "variation"],
    "magnetic disk": ["disc", "disk", "magnetic disc"],
    "magnetic field": ["flux", "magnetic flux"],
    "magnetic field strength": ["magnetic flux density", "magnetic induction", "magnetic intensity"],
    "magnetic levitation": ["maglev"],
    "magnetic moment": ["moment of a magnet"],
    "magnetic resonance imaging": ["mri"],
    "magnetic storage medium": ["magnetic medium", "magnetic storage"],
    "magnetic tape": ["mag tape", "tape"],
    "magnetism": ["magnetic attraction", "magnetic force"],
    "magnetite": ["magnetic iron-ore"],
    "magnetization": ["magnetisation"],
    "magnetize": ["bewitch", "magnetise", "mesmerise", "mesmerize", "spellbind"],
    "magneto": ["magnetoelectric machine"],
    "magnetometer": ["gaussmeter"],
    "magnificence": ["brilliance", "grandeur", "grandness", "splendor", "splendour"],
    "magnify": ["amplify"],
    "magnitude relation": ["quantitative relation"],
    "magnoliaceae": ["family magnoliaceae", "magnolia family"],
    "magnoliidae": ["ranalian complex", "subclass magnoliidae"],
    "magpie": ["pack rat", "scavenger"],
    "magritte": ["rene magritte"],
    "maguey": ["agave atrovirens"],
    "mah-jongg": ["mahjong"],
    "mahabharata": ["mahabharatam", "mahabharatum"],
    "mahan": ["alfred thayer mahan"],
    "maharaja": ["maharajah"],
    "maharani": ["maharanee"],
    "mahayana": ["mahayana buddhism"],
    "mahler": ["gustav mahler"],
    "mahoe": ["balibago", "hibiscus tiliaceus", "mahagua", "majagua", "purau"],
    "mahogany": ["mahogany tree"],
    "mahonia": ["genus mahonia"],
    "mahuang": ["ephedra sinica"],
    "maianthemum": ["genus maianthemum"],
    "maid": ["amah", "housemaid", "maidservant"],
    "maiden blue-eyed mary": ["collinsia parviflora"],
    "maiden over": ["maiden"],
    "maiden pink": ["dianthus deltoides"],
    "maidenhair": ["maidenhair fern"],
    "maidenhair spleenwort": ["asplenium trichomanes"],
    "maidenlike": ["maidenly"],
    "maiduguri": ["yerwa-maiduguri"],
    "maigre": ["maiger", "sciaena aquila"],
    "mail": ["get off"],
    "mail-clad": ["mailed"],
    "mail-order buying": ["catalog buying"],
    "mailbag": ["mail pouch"],
    "mailboat": ["mail boat", "packet", "packet boat"],
    "mailbox": ["letter box"],
    "mailer": ["norman mailer"],
    "mailing": ["posting"],
    "maillol": ["aristide maillol"],
    "maillot": ["tank suit"],
    "mailman": ["carrier", "letter carrier", "mail carrier", "postman"],
    "maimed": ["mutilated"],
    "maimonides": ["moses maimonides", "rabbi moses ben maimon"],
    "main": ["briny"],
    "main clause": ["independent clause"],
    "main deck": ["second deck"],
    "main diagonal": ["principal diagonal"],
    "main street": ["high street"],
    "maine": ["me", "pine tree state"],
    "mainer": ["down easter"],
    "mainframe": ["mainframe computer"],
    "maintain": ["defend"],
    "maintenance": ["criminal maintenance"],
    "maintenon": ["francoise d'aubigne", "madame de maintenon", "marquise de maintenon"],
    "maisonette": ["maisonnette"],
    "maitland": ["frederic william maitland"],
    "maja": ["genus maia", "genus maja", "maia"],
    "majestic": ["olympian"],
    "majidae": ["family majidae"],
    "majolica": ["maiolica"],
    "major": ["john major", "john r. major", "john roy major"],
    "major key": ["major mode"],
    "major league": ["big league", "majors"],
    "major leaguer": ["big leaguer"],
    "major premise": ["major premiss"],
    "major scale": ["major diatonic scale"],
    "major tranquilizer": ["antipsychotic", "antipsychotic agent", "antipsychotic drug", "major tranquilliser", "major tranquillizer", "neuroleptic", "neuroleptic agent", "neuroleptic drug"],
    "major-domo": ["seneschal"],
    "major-league team": ["major-league club"],
    "majorana": ["genus majorana"],
    "majority": ["legal age"],
    "majority rule": ["democracy"],
    "makaira": ["genus makaira"],
    "make": ["do"],
    "make a clean breast of": ["fess up", "own up"],
    "make a point": ["make sure"],
    "make bold": ["dare", "presume"],
    "make noise": ["noise", "resound"],
    "make sense": ["add up"],
    "make up": ["catch up with"],
    "make-believe": ["pretend"],
    "maker": ["shaper"],
    "makeshift": ["make-do", "stopgap"],
    "makeup": ["make-up"],
    "makeweight": ["filler"],
    "mako": ["mako shark"],
    "makomako": ["aristotelia racemosa", "aristotelia serrata", "new zealand wine berry", "wineberry"],
    "maktab al-khidmat": ["mak"],
    "malacanthidae": ["family malacanthidae"],
    "malacca": ["malacca cane"],
    "malachi": ["malachias"],
    "malaclemys": ["genus malaclemys"],
    "malaconotinae": ["subfamily malaconotinae"],
    "malacopterygii": ["superorder malacopterygii"],
    "malacosoma": ["genus malacosoma"],
    "malacostraca": ["subclass malacostraca"],
    "malacothamnus": ["genus malacothamnus"],
    "malaise": ["unease", "uneasiness"],
    "malamud": ["bernard malamud"],
    "malamute": ["alaskan malamute", "malemute"],
    "malapropism": ["malaprop"],
    "malarial mosquito": ["malaria mosquito"],
    "malawi": ["nyasaland", "republic of malawi"],
    "malawi kwacha": ["kwacha"],
    "malaxis": ["genus malaxis"],
    "malay": ["malayan"],
    "malay archipelago": ["east india", "east indies"],
    "malayan tapir": ["indian tapir", "tapirus indicus"],
    "malayo-polynesian": ["polynesian"],
    "malaysia": ["malaya"],
    "malaysian": ["bahasa kebangsaan", "bahasa malaysia", "bahasa melayu"],
    "malcolm stock": ["stock"],
    "malcolm x": ["malcolm little"],
    "malcolmia": ["genus malcolmia"],
    "maldives": ["republic of maldives"],
    "maldivian": ["maldivan"],
    "maldon": ["battle of maldon"],
    "male": ["male person"],
    "male chauvinism": ["antifeminism", "chauvinism"],
    "male chauvinist": ["sexist"],
    "male child": ["boy"],
    "male fern": ["dryopteris filix-mas"],
    "male genitalia": ["family jewels", "male genital organ", "male genitals"],
    "male hypogonadism": ["eunuchoidism"],
    "male offspring": ["man-child"],
    "male orchis": ["early purple orchid", "orchis mascula"],
    "male-patterned baldness": ["male pattern baldness"],
    "maleberry": ["he-huckleberry", "lyonia ligustrina", "male berry", "privet andromeda"],
    "malebranche": ["nicolas de malebranche"],
    "malecite": ["maleseet"],
    "malefic": ["evil", "malevolent", "malign"],
    "maleficence": ["balefulness", "mischief"],
    "maleness": ["masculinity"],
    "maleo": ["macrocephalon maleo"],
    "malevich": ["kazimir malevich", "kazimir severinovich malevich"],
    "malevolence": ["malignity"],
    "malformation": ["miscreation"],
    "malfunction": ["misfunction"],
    "malfunctioning": ["nonfunctional"],
    "malheur wire lettuce": ["stephanomeria malheurensis"],
    "mali": ["french sudan", "republic of mali"],
    "malice": ["maliciousness", "spite", "spitefulness", "venom"],
    "malignancy": ["malignance"],
    "malignant tumor": ["malignant neoplasm", "metastatic tumor"],
    "malignity": ["malignance", "malignancy"],
    "malinger": ["skulk"],
    "malingerer": ["shammer", "skulker"],
    "malingering": ["skulking"],
    "malinowski": ["bronislaw kasper malinowski", "bronislaw malinowski"],
    "mallard": ["anas platyrhynchos"],
    "mallarme": ["stephane mallarme"],
    "malleability": ["plasticity"],
    "mallee fowl": ["leipoa", "leipoa ocellata", "lowan"],
    "mallet": ["hammer"],
    "malleus": ["hammer"],
    "mallon": ["mary mallon", "typhoid mary"],
    "mallophaga": ["order mallophaga"],
    "mallotus": ["genus mallotus"],
    "malodor": ["fetor", "foetor", "malodour", "mephitis", "reek", "stench", "stink"],
    "malodorous": ["ill-smelling", "malodourous", "stinky", "unpleasant-smelling"],
    "malodorousness": ["fetidness", "foulness", "rankness", "stinkiness"],
    "malone": ["edmond malone", "edmund malone"],
    "malope": ["malope trifida"],
    "malopterurus": ["genus malopterurus"],
    "malory": ["sir thomas malory", "thomas malory"],
    "malosma": ["genus malosma"],
    "malpighi": ["marcello malpighi"],
    "malpighia": ["genus malpighia"],
    "malpighiaceae": ["family malpighiaceae"],
    "malpighian body": ["malpighian corpuscle", "renal corpuscle"],
    "malposition": ["misplacement"],
    "malraux": ["andre malraux"],
    "malt": ["malt liquor"],
    "malta": ["republic of malta"],
    "malted": ["malt", "malted milk"],
    "maltese": ["maltese language", "malti"],
    "maltese dog": ["maltese", "maltese terrier"],
    "maltha": ["mineral tar"],
    "malthus": ["thomas malthus", "thomas robert malthus"],
    "malthusianism": ["malthusian theory"],
    "maltose": ["malt sugar"],
    "maltreatment": ["abuse", "ill-treatment", "ill-usage"],
    "maltster": ["maltman"],
    "malus": ["genus malus"],
    "malva": ["genus malva"],
    "malvaceae": ["family malvaceae", "mallow family"],
    "malvales": ["order malvales"],
    "malvastrum": ["genus malvastrum"],
    "malvaviscus": ["genus malvaviscus"],
    "mamet": ["david mamet"],
    "mamey": ["mammee", "mammee apple"],
    "mamillary body": ["corpus mamillare", "mammillary body"],
    "mammal": ["mammalian"],
    "mammalia": ["class mammalia"],
    "mammary gland": ["mamma"],
    "mammea": ["genus mammea"],
    "mammee apple": ["mamey", "mammea americana", "mammee", "mammee tree"],
    "mammut": ["genus mammut", "genus mastodon"],
    "mammuthus": ["genus mammuthus"],
    "mammutidae": ["family mammutidae", "family mastodontidae"],
    "man": ["adult male"],
    "man hour": ["person hour"],
    "man of action": ["man of deeds"],
    "man of means": ["rich man", "wealthy man"],
    "man-made": ["semisynthetic", "synthetic"],
    "man-made fiber": ["synthetic fiber"],
    "man-of-the-earth": ["ipomoea leptophylla"],
    "man-of-war": ["ship of the line"],
    "man-on-a-horse": ["tricholoma flavovirens"],
    "manacle": ["cuff", "handcuff"],
    "manage": ["care", "deal", "handle"],
    "manageability": ["manageableness"],
    "management": ["direction"],
    "managua": ["capital of nicaragua", "nicaraguan capital"],
    "manama": ["capital of bahrain"],
    "manatee": ["trichechus manatus"],
    "manawydan": ["manawyddan"],
    "manchester terrier": ["black-and-tan terrier"],
    "mandaean": ["mandean"],
    "mandaeanism": ["mandeanism"],
    "mandamus": ["writ of mandamus"],
    "mandara": ["wandala"],
    "mandarin": ["citrus reticulata", "mandarin orange", "mandarin orange tree"],
    "mandarin duck": ["aix galericulata"],
    "mandatary": ["mandatory"],
    "mandate": ["mandatory"],
    "mandela": ["nelson mandela", "nelson rolihlahla mandela"],
    "mandelbrot": ["benoit mandelbrot"],
    "mandelstam": ["mandelshtam", "osip emilevich mandelstam", "osip mandelstam"],
    "mandevilla": ["dipladenia", "genus dipladenia", "genus mandevilla"],
    "mandibular": ["inframaxillary"],
    "mandibular joint": ["articulatio temporomandibularis", "temporomandibular joint"],
    "mandragora": ["genus mandragora"],
    "mandrake": ["devil's apples", "mandragora officinarum"],
    "mandrake root": ["mandrake"],
    "mandrill": ["mandrillus sphinx"],
    "mandrillus": ["genus mandrillus"],
    "manduca": ["genus manduca"],
    "mane": ["head of hair"],
    "manet": ["edouard manet"],
    "maneuver": ["manoeuver", "manoeuvre"],
    "maneuverability": ["manoeuvrability"],
    "maneuverable": ["manoeuvrable"],
    "maneuverer": ["manoeuvrer"],
    "manfully": ["manly"],
    "manfulness": ["manliness", "virility"],
    "manganese": ["atomic number 25", "mn"],
    "manganese bronze": ["high-strength brass"],
    "manganese steel": ["austenitic manganese steel"]
}
