synonyms = {
    "priest": ["non-christian priest"],
    "priestley": ["joseph priestley"],
    "priestly": ["hieratic", "hieratical", "sacerdotal"],
    "priggish": ["prim", "prissy", "prudish", "puritanical", "square-toed", "straight-laced", "straightlaced", "strait-laced", "straitlaced", "tight-laced", "victorian"],
    "priggishness": ["primness"],
    "prim": ["prim out", "prim up"],
    "prima donna": ["diva"],
    "primarily": ["in the first place"],
    "primary": ["primary feather", "primary quill"],
    "primary coil": ["primary", "primary winding"],
    "primary color": ["primary colour"],
    "primary color for light": ["primary colour for light"],
    "primary color for pigments": ["primary colour for pigments"],
    "primary sex characteristic": ["primary sex character", "primary sexual characteristic"],
    "primary subtractive color for light": ["primary subtractive colour for light"],
    "primary tooth": ["baby tooth", "deciduous tooth", "milk tooth"],
    "primates": ["order primates"],
    "prime": ["ground", "undercoat"],
    "prime minister": ["pm", "premier"],
    "primidone": ["mysoline"],
    "primigravida": ["gravida i"],
    "primipara": ["para i"],
    "primitive": ["primitive person"],
    "primitively": ["in the beginning", "originally"],
    "primly": ["prissily"],
    "primness": ["grundyism", "prudery", "prudishness"],
    "primordial dwarf": ["hypoplastic dwarf", "normal dwarf", "true dwarf"],
    "primordium": ["anlage"],
    "primrose": ["primula"],
    "primrose jasmine": ["jasminum mesnyi"],
    "primulaceae": ["family primulaceae", "primrose family"],
    "primulales": ["order primulales"],
    "primus stove": ["primus"],
    "prince albert yew": ["prince albert's yew", "saxe-gothea conspicua"],
    "prince's-feather": ["kiss-me-over-the-garden-gate", "polygonum orientale", "prince's-plume", "princess feather"],
    "prince-of-wales'-heath": ["erica perspicua", "prince of wales heath"],
    "princeton university": ["princeton"],
    "princewood": ["cordia gerascanthus", "spanish elm"],
    "principal": ["corpus", "principal sum"],
    "principal axis": ["optic axis"],
    "principal investigator": ["pi"],
    "principality": ["princedom"],
    "principle": ["precept"],
    "principle of superposition": ["superposition", "superposition principle"],
    "prinia": ["genus prinia"],
    "print": ["impress"],
    "print run": ["press run"],
    "print shop": ["printing shop"],
    "printer": ["pressman"],
    "printer's ink": ["printing ink"],
    "printing": ["printing process"],
    "printing concern": ["printing business", "printing company"],
    "printmaker": ["graphic artist"],
    "priodontes": ["genus priodontes"],
    "prionace": ["genus prionace"],
    "prionotus": ["genus prionotus"],
    "prioritize": ["prioritise"],
    "priority": ["antecedence", "antecedency", "anteriority", "precedence", "precedency"],
    "prism": ["optical prism"],
    "prison": ["prison house"],
    "prison camp": ["internment camp", "pow camp", "prisoner of war camp"],
    "prison guard": ["gaoler", "jailer", "jailor", "screw", "turnkey"],
    "prison term": ["sentence", "time"],
    "prisoner": ["captive"],
    "prisoner of war": ["pow"],
    "pristidae": ["family pristidae"],
    "pristis": ["genus pristis"],
    "pritzelago": ["genus pritzelago"],
    "privacy": ["concealment", "privateness", "secrecy"],
    "private": ["buck private", "common soldier"],
    "private detective": ["operative", "pi", "private eye", "private investigator", "shamus", "sherlock"],
    "privateer": ["privateersman"],
    "privately": ["in camera", "in private"],
    "privation": ["deprivation", "neediness", "want"],
    "privatize": ["privatise"],
    "privilege": ["favor", "favour"],
    "privy": ["secluded", "secret"],
    "prize": ["appreciate", "treasure", "value"],
    "prize winner": ["lottery winner"],
    "prizefight": ["prize fight"],
    "prizefighter": ["gladiator"],
    "pro forma": ["perfunctory"],
    "pro tem": ["pro tempore"],
    "proaccelerin": ["accelerator factor", "factor v", "prothrombin accelerator"],
    "probability": ["chance"],
    "probability theory": ["theory of probability"],
    "probable": ["likely"],
    "probably": ["belike", "in all likelihood", "in all probability", "likely"],
    "probate": ["probate will"],
    "probationary": ["provisional", "provisionary", "tentative"],
    "probationer": ["student nurse"],
    "probative": ["probatory"],
    "probe": ["dig into", "poke into"],
    "probiotic": ["probiotic bacterium", "probiotic flora", "probiotic microflora"],
    "problem": ["job"],
    "problem solver": ["convergent thinker", "solver"],
    "proboscidea": ["genus proboscidea"],
    "proboscidean": ["proboscidian"],
    "proboscis": ["trunk"],
    "proboscis monkey": ["nasalis larvatus"],
    "procaine": ["ethocaine"],
    "procaine hydrochloride": ["novocain", "novocaine"],
    "procavia": ["genus procavia"],
    "procaviidae": ["family procaviidae"],
    "procedure": ["process"],
    "proceed": ["continue", "go forward"],
    "proceeding": ["legal proceeding", "proceedings"],
    "procellaria": ["genus procellaria"],
    "procellariidae": ["family procellariidae"],
    "procellariiformes": ["order procellariiformes"],
    "process": ["treat"],
    "process cheese": ["processed cheese"],
    "processional": ["prosodion"],
    "processional march": ["recessional march"],
    "prociphilus": ["genus prociphilus"],
    "proclaim": ["exclaim", "promulgate"],
    "proclamation": ["promulgation"],
    "proclivity": ["leaning", "propensity"],
    "procnias": ["genus procnias"],
    "proconsulship": ["proconsulate"],
    "proconvertin": ["cothromboplastin", "factor vii", "stable factor"],
    "procrastinate": ["dilly-dally", "dillydally", "drag one's feet", "drag one's heels", "shillyshally", "stall"],
    "procrastination": ["cunctation", "shillyshally"],
    "procrastinator": ["cunctator", "postponer"],
    "procrustean standard": ["procrustean bed", "procrustean rule"],
    "proctoplasty": ["rectoplasty"],
    "proctor": ["monitor"],
    "procure": ["secure"],
    "procurement": ["procural", "procurance"],
    "procurer": ["securer"],
    "procyclidine": ["kemadrin"],
    "procyon": ["genus procyon"],
    "procyonidae": ["family procyonidae"],
    "prod": ["egg on", "incite"],
    "prodigal": ["profligate", "squanderer"],
    "prodromal": ["prodromic"],
    "prodrome": ["prodroma"],
    "produce": ["bring on", "bring out"],
    "producer gas": ["air gas"],
    "producer price index": ["wholesale price index"],
    "product": ["mathematical product"],
    "product-moment correlation coefficient": ["pearson product-moment correlation coefficient"],
    "production line": ["assembly line", "line"],
    "productively": ["fruitfully", "profitably"],
    "productiveness": ["productivity"],
    "proenzyme": ["zymogen"],
    "profanation": ["blasphemy", "desecration", "sacrilege"],
    "profane": ["secular"],
    "profaned": ["violated"],
    "profaneness": ["unsanctification"],
    "profess": ["pretend"],
    "profession": ["professing"],
    "professional": ["pro"],
    "professional organization": ["professional organisation"],
    "professionalization": ["professionalisation"],
    "professionalize": ["professionalise"],
    "professor": ["prof"],
    "professorship": ["chair"],
    "proficiency": ["technique"],
    "profit": ["benefit", "gain"],
    "profit and loss": ["profit and loss account"],
    "profit-maximizing": ["profit-maximising"],
    "profitableness": ["gainfulness", "lucrativeness", "profitability"],
    "profitlessly": ["gainlessly", "unprofitably"],
    "profligacy": ["dissipation", "dissolution", "licentiousness", "looseness"],
    "profligately": ["dissolutely"],
    "profound": ["unfathomed", "unplumbed", "unsounded"],
    "profoundly": ["deeply"],
    "profoundly deaf": ["deaf as a post", "stone-deaf", "unhearing"],
    "profundity": ["profoundness"],
    "profusion": ["cornucopia", "profuseness", "richness"],
    "progenitor": ["primogenitor"],
    "progesterone": ["lipo-lutin"],
    "progestin": ["progestogen"],
    "prognathous": ["hypognathous", "prognathic"],
    "progne": ["genus progne"],
    "prognosis": ["forecast"],
    "program": ["programme"],
    "program music": ["programme music"],
    "programmer": ["coder", "computer programmer", "software engineer"],
    "programming": ["computer programing", "computer programming", "programing"],
    "programming language": ["programing language"],
    "progress": ["advance", "come along", "come on", "get along", "get on", "shape up"],
    "progression": ["patterned advance"],
    "progressive": ["continuous tense", "imperfect", "imperfect tense", "progressive tense"],
    "progressive party": ["bull moose party"],
    "progressive rock": ["art rock"],
    "progressive tax": ["graduated tax"],
    "progressive vaccinia": ["vaccinia gangrenosa"],
    "progressiveness": ["progressivity"],
    "prohibition": ["prohibition era"],
    "prohibitive": ["prohibitory"],
    "proinflammatory": ["pro-inflammatory"],
    "project": ["cast", "contrive", "throw"],
    "projectile": ["missile"],
    "projection": ["acoustic projection", "sound projection"],
    "projective geometry": ["descriptive geometry"],
    "projective test": ["projective device", "projective technique"],
    "prokaryote": ["procaryote"],
    "prokaryotic": ["procaryotic"],
    "prokhorov": ["aleksandr mikjailovich prokhorov", "aleksandr prokhorov"],
    "prokofiev": ["sergei sergeyevich prokofiev"],
    "prolactin": ["lactogenic hormone", "luteotropin"],
    "prolapse": ["descensus", "prolapsus"],
    "prolate": ["watermelon-shaped"],
    "proletarian": ["prole", "worker"],
    "prolific": ["fertile"],
    "prolixity": ["long-windedness", "prolixness", "windiness", "wordiness"],
    "prolog": ["logic programing", "logic programming"],
    "prologize": ["prologise", "prologuize"],
    "prolong": ["keep up", "sustain"],
    "prolongation": ["lengthening", "perpetuation", "protraction"],
    "prolonge knot": ["sailor's breastplate"],
    "promenade": ["prom"],
    "promethazine": ["phenergan"],
    "promethium": ["atomic number 61", "pm"],
    "prominently": ["conspicuously"],
    "promiscuity": ["promiscuousness", "sleeping around"],
    "promiscuously": ["indiscriminately"],
    "promise": ["assure"],
    "promiser": ["promisor"],
    "promontory": ["foreland", "head", "headland"],
    "promote": ["advance", "boost", "encourage", "further"],
    "promoter": ["booster", "plugger"],
    "promotion": ["advancement", "furtherance"],
    "prompt": ["cue", "remind"],
    "prompt box": ["prompter's box"],
    "promptbook": ["prompt copy"],
    "prompter": ["theater prompter"],
    "promptly": ["quick", "quickly"],
    "promptness": ["promptitude"],
    "promulgated": ["published"],
    "prone": ["prostrate"],
    "pronged": ["tined"],
    "pronghorn": ["american antelope", "antilocapra americana", "prongbuck", "pronghorn antelope"],
    "pronominal phrase": ["pronominal"],
    "pronounce": ["articulate", "enounce", "enunciate", "say", "sound out"],
    "pronouncement": ["dictum", "say-so"],
    "pronunciation": ["orthoepy"],
    "proof": ["test copy", "trial impression"],
    "proofread": ["proof"],
    "proofreader": ["reader"],
    "prop up": ["prop", "shore", "shore up"],
    "propaedeutic": ["propaedeutics"],
    "propagandist": ["propagandistic"],
    "propagandize": ["propagandise"],
    "propagation": ["extension"],
    "propagator": ["disseminator"],
    "propanal": ["propionaldehyde"],
    "propanol": ["propyl alcohol"],
    "propanolol": ["inderal"],
    "propel": ["impel"],
    "propellant": ["propellent"],
    "propellant explosive": ["impulse explosive"],
    "propeller": ["propellor"],
    "propenal": ["acrolein"],
    "propenoate": ["acrylate"],
    "propenoic acid": ["acrylic acid"],
    "propenonitrile": ["acrylonitrile", "vinyl cyanide"],
    "proper": ["right"],
    "proper noun": ["proper name"],
    "properly": ["decent", "decently", "in good order", "right", "the right way"],
    "properly speaking": ["strictly speaking", "to be precise"],
    "propertied": ["property-owning"],
    "property": ["belongings", "holding"],
    "property man": ["property master", "propman"],
    "property tax": ["land tax"],
    "propertyless": ["blue-collar", "wage-earning", "working-class"],
    "prophecy": ["divination"],
    "prophesy": ["vaticinate"],
    "prophet": ["oracle", "prophesier", "seer", "vaticinator"],
    "prophetic": ["prophetical"],
    "prophets": ["nebiim"],
    "propionic acid": ["propanoic acid"],
    "propitiate": ["appease"],
    "propitiative": ["propitiatory"],
    "propjet": ["turbo-propeller plane", "turboprop"],
    "proportion": ["ratio"],
    "proportional": ["relative"],
    "proportional counter tube": ["proportional counter"],
    "proportionately": ["proportionally"],
    "proposal": ["proposition"],
    "propose": ["declare oneself", "offer", "pop the question"],
    "proposer": ["mover"],
    "propositional logic": ["propositional calculus"],
    "propoxyphene": ["darvon", "propoxyphene hydrochloride"],
    "proprietorship": ["proprietary"],
    "propriety": ["correctitude", "properness"],
    "proprionamide": ["propanamide"],
    "propulsion": ["actuation"],
    "propyl": ["propyl group", "propyl radical"],
    "propylene": ["propene"],
    "propylene glycol": ["propanediol"],
    "prosaically": ["unimaginatively"],
    "prosauropoda": ["suborder prosauropoda"],
    "proscenium": ["apron", "forestage"],
    "prosecute": ["engage", "pursue"],
    "prosecution": ["criminal prosecution"],
    "prosecutor": ["prosecuting attorney", "prosecuting officer", "public prosecutor"],
    "proselytize": ["proselytise"],
    "proserpina": ["proserpine"],
    "prosimii": ["suborder prosimii"],
    "prosiness": ["prosaicness"],
    "prosody": ["inflection"],
    "prosopis": ["genus prosopis"],
    "prosopium": ["genus prosopium"],
    "prospect": ["chance"],
    "prosperity": ["successfulness"],
    "prostate": ["prostatic"],
    "prostate cancer": ["prostatic adenocarcinoma"],
    "prostate gland": ["prostate"],
    "prostate specific antigen": ["psa"],
    "prosthesis": ["prosthetic device"],
    "prosthion": ["alveolar point", "prostheon"],
    "prosthodontics": ["prosthodontia"],
    "prostitute": ["bawd", "cocotte", "cyprian", "fancy woman", "harlot", "lady of pleasure", "sporting lady", "tart", "whore", "woman of the street", "working girl"],
    "prostitution": ["harlotry", "whoredom"],
    "prostrate": ["bow down"],
    "prostyle": ["pseudoprostyle"],
    "protactinium": ["atomic number 91", "pa", "protoactinium"],
    "protagonist": ["agonist"],
    "protanopia": ["red-blindness"],
    "protanopic": ["red-blind"],
    "proteaceae": ["family proteaceae", "protea family"],
    "proteales": ["order proteales"],
    "protease": ["peptidase", "proteinase", "proteolytic enzyme"],
    "protease inhibitor": ["pi"],
    "protected": ["saved"],
    "protection": ["shelter"],
    "protective covering": ["protection", "protective cover"],
    "protectorate": ["associated state"],
    "proteidae": ["family proteidae"],
    "protein folding": ["folding"],
    "proteles": ["genus proteles"],
    "proteosome vaccine": ["proteosome"],
    "proterochampsa": ["genus proterochampsa"],
    "proterozoic": ["proterozoic aeon", "proterozoic eon"],
    "protest": ["dissent", "resist"],
    "protestant church": ["protestant"],
    "proteus": ["genus proteus"],
    "prothalamion": ["prothalamium"],
    "prothrombin": ["factor ii"],
    "prothrombinase": ["factor x"],
    "protist": ["protistan"],
    "protista": ["division protista"],
    "protium": ["genus protium"],
    "proto-indo european": ["pie"],
    "protoarcheology": ["protoarchaeology"],
    "protocol": ["communications protocol"],
    "protoctista": ["kingdom protoctista"],
    "protohistory": ["protoanthropology"],
    "protoplasm": ["living substance"],
    "prototheria": ["subclass prototheria"],
    "prototype": ["epitome", "image", "paradigm"],
    "protozoa": ["phylum protozoa"],
    "protozoal": ["protozoan", "protozoic"],
    "protozoan": ["protozoon"],
    "protractile": ["protractible"],
    "protrusile": ["protrusible"],
    "protrusion": ["jut", "jutting", "projection"],
    "protura": ["order protura"],
    "proturan": ["telsontail"],
    "proudhon": ["pierre joseph proudhon"],
    "proust": ["marcel proust"],
    "prove": ["turn out", "turn up"],
    "proved": ["proven"],
    "provencal": ["occitan"],
    "proverb": ["adage", "byword", "saw"],
    "proverbs": ["book of proverbs"],
    "provide": ["bring home the bacon"],
    "providence": ["capital of rhode island"],
    "providential": ["divine"],
    "province": ["responsibility"],
    "provision": ["purvey"],
    "provitamin a": ["carotene", "carotin"],
    "provocation": ["incitement"],
    "provocatively": ["provokingly"],
    "provoke": ["call forth", "evoke", "kick up"],
    "prowl": ["lurch"],
    "prowler": ["sneak", "stalker"],
    "proxima": ["proxima centauri"],
    "proximity": ["law of proximity"],
    "proximo": ["prox"],
    "proxy": ["placeholder", "procurator"],
    "prude": ["puritan"],
    "prudently": ["providentially"],
    "prudishly": ["puritanically"],
    "prumnopitys": ["genus prumnopitys"],
    "prunella": ["genus prunella"],
    "prunellidae": ["family prunellidae"],
    "pruner": ["trimmer"],
    "prunus": ["genus prunus"],
    "prurience": ["carnality", "lasciviousness", "lubricity", "pruriency"],
    "prussia": ["preussen"],
    "pry": ["prise"],
    "przewalski's horse": ["equus caballus przevalskii", "equus caballus przewalskii", "przevalski's horse"],
    "psalmody": ["hymnody"],
    "psalms": ["book of psalms"],
    "psalter": ["book of psalms"],
    "psalterium": ["omasum", "third stomach"],
    "psaltriparus": ["genus psaltriparus"],
    "psammoma": ["sand tumor"],
    "psenes": ["genus psenes"],
    "psephurus": ["genus psephurus"],
    "psetta": ["genus psetta"],
    "psettichthys": ["genus psettichthys"],
    "pseudacris": ["genus pseudacris"],
    "pseudaletia": ["genus pseudaletia"],
    "pseudechis": ["genus pseudechis"],
    "pseudemys": ["genus pseudemys"],
    "pseudobombax": ["genus pseudobombax"],
    "pseudococcidae": ["family pseudococcidae"],
    "pseudococcus": ["genus pseudococcus"],
    "pseudocolus": ["genus pseudocolus"],
    "pseudohermaphroditic": ["pseudohermaphrodite"],
    "pseudolarix": ["genus pseudolarix"],
    "pseudomonadales": ["order pseudomonadales"],
    "pseudomonas": ["genus pseudomonas"],
    "pseudomonodaceae": ["family pseudomonodaceae"],
    "pseudonym": ["anonym", "nom de guerre"],
    "pseudopleuronectes": ["genus pseudopleuronectes"],
    "pseudopod": ["pseudopodium"],
    "pseudoryx": ["genus pseudoryx"],
    "pseudotaxus": ["genus pseudotaxus"],
    "pseudotsuga": ["genus pseudotsuga"],
    "pseudowintera": ["genus pseudowintera", "genus wintera", "wintera"],
    "psidium": ["genus psidium"],
    "psilocybin": ["psilocin"],
    "psilophytaceae": ["family psilophytaceae"],
    "psilophytales": ["order psilophytales"],
    "psilopsida": ["class psilopsida", "class psilotatae", "psilotatae"],
    "psilotaceae": ["family psilotaceae"],
    "psilotales": ["order psilotales"],
    "psilotum": ["genus psilotum"],
    "psithyrus": ["genus psithyrus"],
    "psittacidae": ["family psittacidae"],
    "psittaciformes": ["order psittaciformes"],
    "psittacosaur": ["psittacosaurus"],
    "psittacosis": ["parrot disease"],
    "psittacula": ["genus psittacula"],
    "psittacus": ["genus psittacus"],
    "psocidae": ["family psocidae"],
    "psocoptera": ["corrodentia", "order corrodentia", "order psocoptera"],
    "psophia": ["genus psophia"],
    "psophiidae": ["family psophiidae"],
    "psophocarpus": ["genus psophocarpus"],
    "psoralea": ["genus psoralea"],
    "psychedelic rock": ["acid rock"],
    "psychiatric": ["psychiatrical"],
    "psychiatrist": ["head-shrinker", "shrink"],
    "psychiatry": ["psychological medicine", "psychopathology"],
    "psychic": ["psychical"],
    "psychic communication": ["anomalous communication", "psychical communication"],
    "psychic energy": ["mental energy"],
    "psychic phenomena": ["parapsychology", "psychic phenomenon"],
    "psychoactive": ["psychotropic"],
    "psychoactive drug": ["consciousness-altering drug", "mind-altering drug", "psychoactive substance"],
    "psychoanalysis": ["analysis", "depth psychology"],
    "psychoanalytical": ["psychoanalytic"],
    "psychodidae": ["family psychodidae"],
    "psychogenetic": ["psychogenic"],
    "psychological operation": ["psyop"],
    "psychological state": ["mental condition", "mental state", "psychological condition"],
    "psychological warfare": ["war of nerves"],
    "psychology": ["psychological science"],
    "psychology department": ["department of psychology"],
    "psychometry": ["psychometrics", "psychometrika"],
    "psychomotor epilepsy": ["temporal lobe epilepsy"],
    "psychopathic": ["psychopathologic", "psychopathological"],
    "psychopsis": ["genus psychopsis"],
    "psychopsis krameriana": ["oncidium papilio kramerianum"],
    "psychopsis papilio": ["oncidium papilio"],
    "psychotherapist": ["clinical psychologist"],
    "psychotherapy": ["mental hygiene", "psychotherapeutics"],
    "psychotic": ["psycho", "psychotic person"],
    "psychotria": ["genus psychotria"],
    "psyllidae": ["chermidae", "family chermidae", "family psyllidae"],
    "pt boat": ["mosquito boat", "mosquito craft", "motor torpedo boat"],
    "pteridaceae": ["family pteridaceae"],
    "pteridium": ["genus pteridium"],
    "pteridophyta": ["division pteridophyta"],
    "pteridophyte": ["nonflowering plant"],
    "pteridospermae": ["group pteridospermae", "group pteridospermaphyta", "pteridospermaphyta"],
    "pteridospermopsida": ["class pteridospermopsida"],
    "pteriidae": ["family pteriidae"],
    "pteris": ["genus pteris"],
    "pternohyla": ["genus pternohyla"],
    "pterocarpus": ["genus pterocarpus"],
    "pterocarya": ["genus pterocarya"],
    "pterocles": ["genus pterocles"],
    "pteroclididae": ["family pteroclididae"],
    "pterocnemia": ["genus pterocnemia"],
    "pterodactylidae": ["family pterodactylidae"],
    "pterodactylus": ["genus pterodactylus"],
    "pterois": ["genus pterois"],
    "pteropogon": ["pteropogon humboltianum"],
    "pteropsida": ["subdivision pteropsida"],
    "pteropus": ["genus pteropus"],
    "pterosaur": ["flying reptile"],
    "pterosauria": ["order pterosauria"],
    "pterospermum": ["genus pterospermum"],
    "pterostylis": ["genus pterostylis"],
    "ptilocercus": ["genus ptilocercus"],
    "ptilocrinus": ["genus ptilocrinus"],
    "ptilonorhynchidae": ["family ptilonorhynchidae"],
    "ptilonorhynchus": ["genus ptilonorhynchus"],
    "ptloris": ["genus ptloris"],
    "ptolemy": ["claudius ptolemaeus"],
    "ptomaine": ["ptomain"],
    "ptyas": ["genus ptyas"],
    "ptychozoon": ["genus ptychozoon"],
    "pub-crawl": ["bar hop"],
    "puberty": ["pubescence"],
    "pubes": ["loins", "pubic region"],
    "pubic hair": ["bush", "crotch hair"],
    "pubis": ["os pubis", "pubic bone"],
    "public address system": ["p.a.", "p.a. system", "pa", "pa system"],
    "public discussion": ["ventilation"],
    "public house": ["gin mill", "pothouse", "pub", "saloon", "taphouse"],
    "public knowledge": ["general knowledge"],
    "public nuisance": ["common nuisance"],
    "public opinion": ["opinion", "popular opinion", "vox populi"],
    "public relations": ["pr"],
    "public speaking": ["oral presentation", "speaking", "speechmaking"],
    "public square": ["square"],
    "public toilet": ["comfort station", "convenience", "public convenience", "public lavatory", "restroom", "toilet facility", "wash room"],
    "public treasury": ["till", "trough"],
    "publican": ["tavern keeper"],
    "publication": ["publishing"],
    "publicist": ["publiciser", "publicizer"],
    "publicize": ["air", "bare", "publicise"],
    "publicized": ["publicised"],
    "publicly": ["in public", "publically"],
    "publish": ["write"],
    "publisher": ["newspaper publisher"],
    "publishing conglomerate": ["publishing empire"],
    "puccini": ["giacomo puccini"],
    "puccinia": ["genus puccinia"],
    "pucciniaceae": ["family pucciniaceae"],
    "puccoon": ["lithospermum caroliniense"],
    "puck": ["robin goodfellow"],
    "pucker": ["ruck", "ruck up"],
    "pudding": ["pud"],
    "pudding face": ["pudding-face"],
    "pudding stone": ["conglomerate"],
    "puddingwife": ["halicoeres radiatus", "pudding-wife"],
    "pudendal artery": ["arteria pudenda"],
    "pudendal cleft": ["pudendal cleavage", "pudendal slit", "rima pudendi", "rima vulvae", "urogenital cleft", "vulvar slit"],
    "pudendal vein": ["venae pudendum"],
    "puebla": ["heroica puebla de zaragoza", "puebla de zaragoza"],
    "pueraria": ["genus pueraria"],
    "puerperal fever": ["childbed fever"],
    "puerto rico": ["commonwealth of puerto rico", "porto rico", "pr"],
    "puff": ["drag", "draw"],
    "puff adder": ["bitis arietans"],
    "puff batter": ["pate a choux", "pouf paste"],
    "puff paste": ["pate feuillete"],
    "puffball": ["true puffball"],
    "puffer": ["blowfish", "globefish", "pufferfish"],
    "puffing": ["huffing", "snorting"],
    "puffinus": ["genus puffinus"],
    "puffy": ["intumescent", "tumescent", "tumid", "turgid"],
    "pug": ["pug-dog"],
    "pug-nosed": ["pug-nose", "short-nosed", "snub-nosed"],
    "pugin": ["augustus welby northmore pugin"],
    "puglia": ["apulia"],
    "pugnacious": ["rough"],
    "pujunan": ["maidu"],
    "puka": ["griselinia lucida"],
    "puka inti": ["red sun", "sol rojo"],
    "pukka": ["pucka"],
    "puku": ["adenota vardoni"],
    "pulasan": ["nephelium mutabile", "pulasan tree", "pulassan"],
    "pulex": ["genus pulex"],
    "pulicaria": ["genus pulicaria"],
    "pulicidae": ["family pulicidae"],
    "pulitzer": ["joseph pulitzer"],
    "pull": ["draw"],
    "pull back": ["draw"],
    "pull in": ["draw in", "get in", "move in"],
    "pull off": ["bring off", "carry off", "manage", "negociate"],
    "pull out": ["get out"],
    "pull the leg of": ["kid"],
    "pull-in": ["pull-up"],
    "pull-off": ["lay-by", "layby", "rest area", "rest stop"],
    "pull-up": ["chin-up"],
    "pullback": ["tieback"],
    "puller": ["dragger", "tugger"],
    "pulley": ["block", "pulley block", "pulley-block"],
    "pullman": ["pullman car"],
    "pullorum disease": ["bacillary white diarrhea", "bacillary white diarrhoea"],
    "pullover": ["slipover"],
    "pullulation": ["gemmation"],
    "pulmonary anthrax": ["anthrax pneumonia", "inhalation anthrax", "ragpicker's disease", "ragsorter's disease", "woolsorter's disease", "woolsorter's pneumonia"],
    "pulmonary artery": ["arteria pulmonalis"],
    "pulmonary plexis": ["plexus pulmonalis"],
    "pulmonary trunk": ["truncus pulmonalis"],
    "pulmonary tuberculosis": ["consumption", "phthisis", "wasting disease", "white plague"],
    "pulmonary vein": ["vena pulmonalis"],
    "pulmonata": ["order pulmonata"],
    "pulp": ["flesh"],
    "pulpy": ["squashy"],
    "pulsate": ["beat", "quiver"],
    "pulsatilla": ["genus pulsatilla"],
    "pulsation": ["impulse", "pulse", "pulsing"],
    "pulse": ["pulsate"],
    "pulverization": ["pulverisation"],
    "pumice": ["pumice stone"],
    "pummel": ["biff", "pommel"],
    "pump action": ["slide action"],
    "pump house": ["pumping station"],
    "pumped-up": ["pumped", "pumped up", "wired"],
    "pumpkin": ["autumn pumpkin", "cucurbita pepo", "pumpkin vine"],
    "pumpkin ash": ["fraxinus tomentosa"],
    "pumpkinseed": ["lepomis gibbosus"],
    "pun": ["paronomasia", "punning", "wordplay"],
    "punch": ["perforate"],
    "punch line": ["gag line", "laugh line", "tag line"],
    "punch-drunk": ["silly", "slaphappy"],
    "punched card": ["hollerith card", "punch card"],
    "punching bag": ["punch bag", "punchball", "punching ball"],
    "punctuality": ["promptness"],
    "punctually": ["duly"],
    "punctuate": ["mark"],
    "punctuated equilibrium": ["theory of punctuated equilibrium"],
    "punctuation": ["punctuation mark"],
    "pungapung": ["amorphophallus campanulatus", "amorphophallus paeonifolius", "elephant yam", "telingo potato"],
    "pungency": ["bite"],
    "pungent": ["acrid"],
    "punic": ["perfidious", "treacherous"],
    "punica": ["genus punica"],
    "punicaceae": ["family punicaceae"],
    "puniness": ["runtiness", "stuntedness"],
    "punish": ["penalise", "penalize"],
    "punishment": ["penalisation", "penalization", "penalty"],
    "punitive": ["punitory"],
    "punitive damages": ["exemplary damages", "smart money"],
    "punitively": ["penally", "punitorily"],
    "punjabi": ["panjabi"],
    "punk rock": ["punk"],
    "punk rocker": ["punk"],
    "punkie": ["biting midge", "no-see-um", "punkey", "punky"],
    "punt": ["pole"],
    "puny": ["runty", "shrimpy"],
    "pup": ["whelp"],
    "pup tent": ["shelter tent"],
    "pupillary sphincter": ["musculus sphincter pupillae"],
    "puppet": ["marionette"],
    "puppet government": ["pupet regime", "puppet state"],
    "puppet ruler": ["puppet leader"],
    "puppet show": ["puppet play"],
    "puppy": ["pup"],
    "puppy love": ["calf love", "crush", "infatuation"],
    "puppyish": ["puppylike"],
    "purcell": ["henry purcell"],
    "purchasable": ["for sale"],
    "purchase contract": ["purchase agreement"],
    "purdah": ["sex segregation"],
    "pure": ["vestal", "virgin", "virginal", "virtuous"],
    "pure absence": ["simple absence"],
    "puree": ["strain"],
    "purgative": ["aperient", "cathartic", "physic"],
    "purgatorial": ["purging", "purifying"],
    "purge": ["purgation", "purging"],
    "purification": ["purgation"],
    "purify": ["purge", "sanctify"],
    "purity": ["pureness"],
    "purkinje": ["jan evangelista purkinje", "johannes evangelista purkinje"],
    "purkinje network": ["purkinje's system", "purkinje's tissue"],
    "purl": ["purl stitch"],
    "purloo": ["chicken purloo", "poilu"],
    "purple": ["empurple", "purpurate"],
    "purple anise": ["illicium floridanum"],
    "purple apricot": ["black apricot", "prunus dasycarpa"],
    "purple chinese houses": ["collinsia bicolor", "collinsia heterophylla", "innocense"],
    "purple clematis": ["clematis verticillaris", "mountain clematis", "purple virgin's bower"],
    "purple cress": ["cardamine douglasii"],
    "purple emperor": ["apatura iris"],
    "purple finch": ["carpodacus purpureus"],
    "purple fringeless orchid": ["habenaria peramoena", "purple fringeless orchis"],
    "purple grackle": ["quiscalus quiscula"],
    "purple heather": ["brewer's mountain heather", "phyllodoce breweri"],
    "purple locoweed": ["oxytropis lambertii", "purple loco"],
    "purple loosestrife": ["lythrum salicaria", "spiked loosestrife"],
    "purple martin": ["progne subis"],
    "purple milk vetch": ["astragalus danicus"],
    "purple mullein": ["verbascum phoeniceum"],
    "purple onion": ["red onion"],
    "purple poppy mallow": ["callirhoe involucrata"],
    "purple rock brake": ["pellaea atropurpurea"],
    "purple sage": ["chaparral sage", "salvia leucophylla"],
    "purple sanicle": ["sanicula bipinnatifida"],
    "purple saxifrage": ["saxifraga oppositifolia"],
    "purple silkweed": ["asclepias purpurascens"],
    "purple trillium": ["birthroot", "red trillium", "trillium erectum"],
    "purple willow": ["basket willow", "purple osier", "red osier", "red willow", "salix purpurea"],
    "purple-black": ["purplish-black"],
    "purple-blue": ["purplish-blue"],
    "purple-brown": ["purplish-brown"],
    "purple-fringed orchid": ["habenaria psycodes", "purple-fringed orchis"],
    "purple-green": ["purplish-green"],
    "purple-lilac": ["purplish-lilac"],
    "purple-red": ["purplish-red"],
    "purple-tinged": ["purple-tinted"],
    "purple-white": ["purplish-white"],
    "purplish blue": ["royal blue"],
    "purplish red": ["purplish-red"],
    "purportedly": ["supposedly"],
    "purpose": ["resolve"],
    "purpose-built": ["purpose-made"],
    "purposefulness": ["sense of purpose"],
    "purposelessness": ["aimlessness"],
    "purpura": ["peliosis"],
    "purr": ["make vibrant sounds"],
    "purse": ["wrinkle"],
    "purslane speedwell": ["veronica peregrina"],
    "pursuance": ["prosecution"],
    "pursue": ["act on", "follow up on"],
    "pursued": ["chased"],
    "pursuer": ["chaser"],
    "pursuit": ["pursuance", "quest"],
    "purulence": ["purulency"],
    "purulent": ["pussy"],
    "purus": ["purus river"],
    "pus": ["pansa"],
    "pusey": ["edward bouverie pusey", "edward pusey"],
    "push": ["crowd"],
    "push aside": ["push away"],
    "push button": ["button", "push"],
    "push out": ["obtrude", "thrust out"],
    "push-down list": ["push-down stack", "stack"],
    "push-down storage": ["push-down store", "stack"],
    "pusher": ["thruster"],
    "pushful": ["pushy"],
    "pushkin": ["aleksandr sergeyevich pushkin", "alexander pushkin"],
    "pushup": ["press-up"],
    "pusillanimity": ["pusillanimousness"],
    "pusillanimous": ["poor-spirited", "unmanly"],
    "pusillanimously": ["simperingly"],
    "pussy willow": ["salix discolor"],
    "pussy-paw": ["calyptridium umbellatum", "pussy's-paw", "pussy-paws", "spraguea umbellatum"],
    "put": ["lay", "place", "pose", "position", "set"],
    "put away": ["put aside"],
    "put in": ["submit"],
    "put on": ["turn in"],
    "put option": ["put"],
    "put out": ["retire"],
    "put up": ["offer", "provide"],
    "put-down": ["squelch", "squelcher", "takedown"],
    "putin": ["vladimir putin", "vladimir vladimirovich putin"],
    "putrajaya": ["capital of malaysia"],
    "putrefaction": ["rot"],
    "putrefactive": ["putrefacient"],
    "putrescence": ["corruption", "putridness", "rottenness"],
    "putt": ["putting"],
    "putter": ["mess around", "monkey", "monkey around", "muck about", "muck around", "potter", "tinker"],
    "putterer": ["potterer"],
    "puttyroot": ["adam-and-eve", "aplectrum hyemale"],
    "puzzle": ["mystifier", "puzzler", "teaser"],
    "pycnanthemum": ["genus koellia", "genus pycnanthemum", "koellia"],
    "pycnogonida": ["order pycnogonida"],
    "pycnosis": ["pyknosis"],
    "pydna": ["battle of pydna"],
    "pyemia": ["pyaemia"],
    "pyemic": ["pyaemic"],
    "pygmy": ["pigmy"],
    "pygmy chimpanzee": ["bonobo", "pan paniscus"],
    "pygmy cypress": ["cupressus goveniana pigmaea", "cupressus pigmaea"],
    "pygmy marmoset": ["cebuella pygmaea"],
    "pygmy mouse": ["baiomys taylori"],
    "pygmy sperm whale": ["kogia breviceps"],
    "pygopodidae": ["family pygopodidae"],
    "pygopus": ["genus pygopus"],
    "pygoscelis": ["genus pygoscelis"],
    "pyknotic": ["pycnotic"],
    "pyle": ["howard pyle"],
    "pylodictus": ["genus pylodictus"],
    "pylon": ["power pylon"],
    "pyloric sphincter": ["musculus sphincter pylori", "pyloric valve"],
    "pyloric vein": ["right gastric vein", "vena gastrica-dextra"],
    "pynchon": ["thomas pynchon"],
    "pyongyang": ["capital of north korea"],
    "pyorrhea": ["pyorrhoea"],
    "pyracantha": ["fire thorn", "firethorn", "pyracanth"],
    "pyralid": ["pyralid moth"],
    "pyralidae": ["family pyralidae", "family pyralididae", "pyralididae"],
    "pyralis": ["genus pyralis"],
    "pyramid": ["great pyramid", "pyramids of egypt"],
    "pyramid bugle": ["ajuga pyramidalis"],
    "pyramidal": ["pyramidic", "pyramidical"],
    "pyramidal tract": ["corticospinal tract", "pyramidal motor system"],
    "pyrausta": ["genus pyrausta"],
    "pyre": ["funeral pyre"],
    "pyrenees daisy": ["chrysanthemum lacustre", "leucanthemum lacustre"],
    "pyrenomycetes": ["class pyrenomycetes"],
    "pyrethrum": ["chrysanthemum cinerariifolium", "dalmatia pyrethrum", "dalmatian pyrethrum", "tanacetum cinerariifolium"],
    "pyriform area": ["piriform area", "piriform lobe", "pyriform lobe"],
    "pyrite": ["fool's gold", "iron pyrite"],
    "pyrocephalus": ["genus pyrocephalus"],
    "pyrochemical process": ["pyrochemistry"],
    "pyroelectric": ["pyroelectrical"],
    "pyrogallol": ["pyrogallic acid"],
    "pyrogen": ["pyrectic"],
    "pyrogenic": ["pyrogenetic", "pyrogenous"],
    "pyrolaceae": ["family pyrolaceae", "wintergreen family"],
    "pyrolatry": ["fire-worship"],
    "pyroligneous": ["pyrolignic"],
    "pyroligneous acid": ["wood vinegar"],
    "pyromorphite": ["green lead ore"],
    "pyrophorus": ["genus pyrophorus"],
    "pyrotechnic": ["pyrotechnical"],
    "pyrotechnics": ["pyrotechny"],
    "pyroxylin": ["pyroxyline"],
    "pyrrhic": ["dibrach"],
    "pyrrhocoridae": ["family pyrrhocoridae"],
    "pyrrhotite": ["magnetic pyrites", "pyrrhotine"],
    "pyrrhula": ["genus pyrrhula"],
    "pyrrhuloxia": ["pyrrhuloxia sinuata"],
    "pyrrophyta": ["phylum pyrrophyta"],
    "pyrrosia": ["genus pyrrosia"],
    "pyrularia": ["genus pyrularia"],
    "pyrus": ["genus pyrus"],
    "pythia": ["pythoness"],
    "pythiaceae": ["family pythiaceae"],
    "pythonidae": ["family pythonidae"],
    "pythoninae": ["subfamily pythoninae"],
    "pyx": ["pix", "pix chest", "pyx chest"],
    "pyxidanthera": ["genus pyxidanthera"],
    "pyxidium": ["pyxis"],
    "pyxie": ["pixie", "pixy", "pyxidanthera barbulata"],
    "qaddafi": ["gaddafi", "khadafy", "muammar al-qaddafi", "muammar el-qaddafi", "qadhafi"],
    "qassam brigades": ["iz al-din al-qassam battalions", "salah al-din battalions"],
    "qatar": ["katar", "state of katar", "state of qatar"],
    "qatari": ["katari"],
    "qatari dirham": ["dirham"],
    "qatari riyal": ["riyal"],
    "qi": ["ch'i", "chi", "ki"],
    "qiang": ["qiangic"],
    "qin": ["ch'in", "ch'in dynasty", "qin dynasty"],
    "qin shi huang ti": ["ch'in shih huang ti"],
    "qindarka": ["qintar"],
    "qing": ["ch'ing", "ch'ing dynasty", "manchu", "manchu dynasty", "qing dynasty"],
    "quackery": ["empiricism"],
    "quad": ["space"],
    "quadragesima": ["quadrigesima sunday"],
    "quadrant": ["quarter-circle"],
    "quadraphonic": ["quadrasonic", "quadriphonic", "quadrisonic"],
    "quadraphony": ["quadraphonic system", "quadriphonic system"],
    "quadratic": ["quadratic polynomial"],
    "quadratic equation": ["quadratic"],
    "quadric": ["quadric surface"],
    "quadriceps": ["musculus quadriceps femoris", "quad", "quadriceps femoris"],
    "quadrilateral": ["quadrangle", "tetragon"],
    "quadripartite": ["four-party"],
    "quadrupedal": ["four-footed", "quadruped"],
    "quadruple": ["four-fold", "fourfold", "quadruplex", "quadruplicate"],
    "quadruplet": ["quad"],
    "quagga": ["equus quagga"],
    "quahaug": ["hard-shell clam", "quahog", "round clam"],
    "quahog": ["hard clam", "hard-shell clam", "mercenaria mercenaria", "quahaug", "round clam", "venus mercenaria"],
    "quail bush": ["atriplex lentiformis", "quail brush", "white thistle"],
    "quaker": ["trembler"],
    "quaking aspen": ["european quaking aspen", "populus tremula"],
    "qualification": ["making"],
    "qualify": ["measure up"],
    "quality": ["character", "lineament"],
    "quandong": ["eucarya acuminata", "fusanus acuminatus", "quandang", "quandong tree"],
    "quango": ["quasi-ngo"],
    "quantal": ["quantized"],
    "quantifiability": ["measurability"],
    "quantifier": ["logical quantifier"],
    "quantify": ["measure"],
    "quantitative analysis": ["quantitative chemical analysis"],
    "quantization": ["quantisation"],
    "quantize": ["quantise"],
    "quantum chromodynamics": ["qcd"],
    "quantum electrodynamics": ["qed"],
    "quantum leap": ["quantum jump"],
    "quark cheese": ["quark"],
    "quarrel": ["altercate", "argufy", "dispute", "scrap"],
    "quarreler": ["quarreller"],
    "quarrelsomeness": ["contentiousness"],
    "quarryman": ["quarrier"],
    "quart": ["dry quart"],
    "quarter": ["billet", "canton"],
    "quarter mile": ["440 yards"],
    "quarter note": ["crotchet"],
    "quarter tone": ["quarter-tone"],
    "quarter-hour": ["15 minutes"],
    "quarterback": ["field general", "signal caller"],
    "quarterly": ["every quarter"],
    "quartet": ["quartette"],
    "quarto": ["4to"],
    "quartz battery": ["quartz mill"],
    "quartz glass": ["crystal", "lechatelierite", "quartz", "vitreous silica"],
    "quasar": ["quasi-stellar radio source"],
    "quassia": ["bitterwood", "quassia amara"],
    "quatercentennial": ["quatercentenary"],
    "quaternary": ["age of man", "quaternary period"],
    "quaternate": ["quaternary"],
    "quaver": ["waver"],
    "quavering": ["tremulous"],
    "queasiness": ["qualm", "squeamishness"],
    "quebec": ["quebec city"],
    "quechua": ["kechua"],
    "quechuan": ["kechuan"],
    "queen": ["female monarch", "queen regnant"],
    "queen of the night": ["selenicereus grandiflorus"],
    "queen triggerfish": ["balistes vetula", "bessy cerca", "oldwench", "oldwife"],
    "queen's crape myrtle": ["lagerstroemia speciosa", "pride-of-india"],
    "queen's cup": ["bride's bonnet", "clintonia uniflora"],
    "queen-size": ["queen-sized"],
    "queenly": ["queenlike"],
    "queensland bottletree": ["brachychiton rupestris", "narrow-leaved bottletree", "sterculia rupestris"],
    "queensland grass-cloth plant": ["pipturus argenteus"],
    "queensland hemp": ["jellyleaf", "sida rhombifolia"],
    "queensland nut": ["macadamia tetraphylla"],
    "queer": ["endanger", "expose", "peril", "scupper"],
    "queerly": ["funnily", "oddly", "strangely"],
    "quell": ["appease", "stay"],
    "quelled": ["quenched", "squelched"],
    "quellung": ["quellung reaction"],
    "quench": ["allay", "assuage", "slake"],
    "quenched": ["satisfied", "slaked"],
    "quenchless": ["unquenchable"],
    "quercus": ["genus quercus"],
    "quest": ["seeking"],
    "quest for": ["go after", "pursue", "quest after"],
    "question": ["call into question", "oppugn"],
    "question mark": ["interrogation point"],
    "question master": ["quizmaster"],
    "question of fact": ["matter of fact"],
    "question of law": ["matter of law"],
    "questionable": ["confutable", "confutative", "refutable"],
    "questionably": ["dubiously"],
    "questioning": ["inquiring"],
    "questioningly": ["quizzically"],
    "quetzal": ["quetzal bird"],
    "queue": ["waiting line"],
    "quibble": ["bicker", "brabble", "niggle", "pettifog", "squabble"],
    "quibbler": ["caviler", "caviller", "pettifogger"],
    "quick": ["ready"],
    "quick study": ["sponge"],
    "quick-freeze": ["flash-freeze"],
    "quick-sighted": ["sharp-eyed", "sharp-sighted"],
    "quicken": ["invigorate"],
    "quickener": ["enlivener", "invigorator"],
    "quicker": ["faster"],
    "quickest": ["fastest"],
    "quickly": ["apace", "chop-chop", "rapidly", "speedily"],
    "quid pro quo": ["quid"],
    "quiddity": ["haecceity"],
    "quiescence": ["dormancy", "quiescency", "sleeping"],
    "quiet": ["restrained"],
    "quieten": ["hush", "pipe down", "quiesce", "quiet", "quiet down"],
    "quietly": ["quiet"],
    "quietness": ["soundlessness"],
    "quill": ["quill pen"],
    "quilt": ["comfort", "comforter", "puff"],
    "quinacrine": ["atabrine", "mepacrine", "quinacrine hydrochloride"],
    "quince": ["cydonia oblonga", "quince bush"],
    "quincentennial": ["quincentenary"],
    "quincy": ["josiah quincy"],
    "quine": ["w. v. quine", "willard van orman quine"],
    "quinidine": ["quinidex", "quinora"],
    "quinone": ["benzoquinone"],
    "quinquagesima": ["quinquagesima sunday"],
    "quinsy": ["peritonsillar abscess"],
    "quintessence": ["ether"],
    "quintet": ["quintette"],
    "quintuple": ["five-fold", "fivefold"],
    "quintuplet": ["quin", "quint"],
    "quirk bead": ["bead and quirk"],
    "quirk molding": ["quirk moulding"],
    "quiscalus": ["genus quiscalus"],
    "quitclaim": ["quitclaim deed"],
    "quite": ["quite a", "quite an"],
    "quito": ["capital of ecuador"],
    "quiver": ["palpitate", "quake"],
    "quixotic": ["romantic", "wild-eyed"],
    "quiz": ["test"],
    "quoin": ["coign", "coigne"],
    "quoits": ["horseshoes"],
    "quotation": ["citation", "quote"],
    "quotation mark": ["inverted comma", "quote"],
    "quote": ["cite"],
    "r-2": ["circle", "forget me drug", "mexican valium", "roach", "roofy", "rope", "rophy"],
    "ra": ["re"],
    "rabat": ["capital of morocco"],
    "rabato": ["rebato"],
    "rabbet": ["rebate"],
    "rabbinical": ["rabbinic"],
    "rabbit": ["hare"],
    "rabbit brush": ["chrysothamnus nauseosus", "rabbit bush"],
    "rabbit burrow": ["rabbit hole"],
    "rabbit-eared bandicoot": ["bilby", "macrotis lagotis", "rabbit bandicoot"],
    "rabbiteye blueberry": ["rabbit-eye blueberry", "rabbiteye", "vaccinium ashei"],
    "rabbitfish": ["chimaera monstrosa"],
    "rabbitweed": ["broom snakeroot", "broom snakeweed", "gutierrezia sarothrae", "rabbit-weed", "snakeweed", "turpentine weed"],
    "rabbitwood": ["buffalo nut", "pyrularia pubera"]
}
