synonyms = {
    "oligoporus leucospongia": ["polypore", "pore fungus", "pore mushroom"],
    "oligosaccharide": ["carbohydrate", "disaccharide", "saccharide", "sugar", "tetrasaccharide", "trisaccharide"],
    "oligospermia": ["physical condition", "physiological condition", "physiological state"],
    "oliguria": ["symptom"],
    "olive": ["fruit"],
    "olive brown": ["brown", "brownness"],
    "olive drab": ["drab", "olive"],
    "olive green": ["green", "greenness", "olive-green", "viridity"],
    "olive oil": ["oil", "vegetable oil"],
    "olive tree": ["black maire", "european olive tree", "fruit tree", "olea cunninghamii", "olea europaea", "olea lanceolata", "olive", "white maire"],
    "olive-brown": [],
    "olive-colored": ["olive-coloured"],
    "olive-drab": ["drab"],
    "olive-grey": ["olive-gray"],
    "olive-sized": [],
    "olive-tree agaric": ["agaric", "pleurotus phosphoreus"],
    "olivelike": ["olive-like"],
    "olivenite": ["mineral"],
    "oliver": ["joseph oliver", "king oliver"],
    "olivier": ["baron olivier of birghton", "laurence olivier", "sir laurence kerr olivier"],
    "olivine": ["chrysolite", "mineral"],
    "olla podrida": ["spanish burgoo", "stew"],
    "ollari": ["central dravidian"],
    "olm": ["proteus anguinus", "salamander"],
    "olmec": ["american indian", "indian", "red indian"],
    "olmsted": ["frederick law olmsted"],
    "ology": ["bailiwick", "discipline", "field", "field of study", "study", "subject", "subject area", "subject field", "symbology"],
    "olympia": ["capital of washington"],
    "olympiad": ["period", "period of time", "time period"],
    "olympian": ["athlete", "jock"],
    "olympian games": ["agon", "olympic games"],
    "olympian zeus": ["statue"],
    "olympic": [],
    "olympic games": ["athletic competition", "athletic contest", "athletics", "olympiad", "olympics", "winter olympic games", "winter olympics"],
    "olympic national park": [],
    "olympic salamander": ["rhyacotriton olympicus", "salamander"],
    "olympus": ["mount olympus", "mt. olympus", "olimbos"],
    "omaha": ["dhegiha", "maha"],
    "oman": ["muscat and oman", "sultanate of oman"],
    "omani": ["arab", "arabian"],
    "omani monetary unit": ["baisa", "baiza", "monetary unit", "omani rial", "rial", "riyal-omani"],
    "omar khayyam": [],
    "ombu": ["bella sombra", "phytolacca dioica", "pokeweed"],
    "ombudsman": ["investigator"],
    "omdurman": [],
    "omega": ["conclusion", "ending", "finish", "z"],
    "omega centauri": [],
    "omega-3 fatty acid": ["alpha-linolenic acid", "docosahexaenoic acid", "eicosapentaenoic acid", "omega-3", "polyunsaturated fatty acid"],
    "omega-6 fatty acid": ["linolenic acid", "omega-6", "polyunsaturated fatty acid"],
    "omelet": ["dish", "egg foo yong", "egg fu yung", "firm omelet", "fluffy omelet", "omelette"],
    "omelet pan": ["cooking pan", "omelette pan", "pan"],
    "omen": ["augury", "auspice", "death knell", "foreboding", "foretoken", "portent", "preindication", "presage", "prodigy", "prognostic", "prognostication", "sign"],
    "omentum": ["caul", "gastrocolic omentum", "greater omentum", "lesser omentum", "peritoneum"],
    "omeprazole": ["alkaliser", "alkalizer", "antacid", "antiacid", "gastric antacid", "prilosec"],
    "omerta": ["code", "codification"],
    "omicron": ["alphabetic character", "letter", "letter of the alphabet"],
    "ominously": [],
    "omissible": [],
    "omission": ["disuse", "neglect"],
    "omissive": [],
    "omiya": [],
    "ommastrephes": ["squid"],
    "ommatidium": ["ocellus", "simple eye", "stemma"],
    "omnibus": ["anthology"],
    "omnidirectional": [],
    "omnidirectional antenna": ["aerial", "antenna", "nondirectional antenna", "radio aerial", "radio antenna", "television antenna", "transmitting aerial", "tv-antenna"],
    "omnifarious": [],
    "omnipotence": ["god's will", "state"],
    "omnipresent": ["ubiquitous"],
    "omnirange": ["navigational system", "omnidirectional radio range", "omnidirectional range"],
    "omniscience": ["god's wisdom", "state"],
    "omnivore": ["eater", "feeder"],
    "omnivorous": [],
    "omomyid": ["omomyid group", "taxon", "taxonomic category", "taxonomic group"],
    "omophagia": ["eating", "feeding"],
    "omotic": ["afrasian", "afrasian language", "afro-asiatic", "afroasiatic", "afroasiatic language", "hamito-semitic"],
    "omphaloskepsis": ["navel-gazing", "self-absorption"],
    "omphalotus": ["fungus genus", "genus omphalotus"],
    "omsk": [],
    "on": [],
    "on air": [],
    "on all fours": [],
    "on approval": [],
    "on camera": [],
    "on earth": [],
    "on faith": [],
    "on guard": ["on one's guard", "on your guard", "upon one's guard"],
    "on hand": [],
    "on paper": ["in writing"],
    "on tap": [],
    "on the average": ["on average"],
    "on the coattails": ["one one's coattails"],
    "on the fence": ["undecided"],
    "on the fly": [],
    "on the go": [],
    "on the hook": [],
    "on the nose": ["on the button"],
    "on the offensive": [],
    "on the one hand": ["on one hand"],
    "on the other hand": ["but then", "then again"],
    "on the road": ["on tour", "travel", "traveling", "travelling"],
    "on the spot": [],
    "on the spur of the moment": ["suddenly"],
    "on the way": ["en route"],
    "on time": [],
    "on trial": [],
    "on-key": ["true"],
    "on-license": ["liquor licence", "liquor license"],
    "on-line": ["online"],
    "on-site": [],
    "on-street": [],
    "on-the-job": [],
    "on-the-spot": ["on-the-scene"],
    "onager": ["chigetai", "dziggetai", "equus hemionus", "equus hemionus hemionus", "wild ass"],
    "onagraceae": ["evening-primrose family", "family onagraceae", "rosid dicot family"],
    "once": [],
    "once-over": ["examination", "look-over", "scrutiny"],
    "onchocerciasis": ["infestation", "river blindness"],
    "oncidium": ["butterfly orchid", "butterfly plant", "dancing lady orchid", "orchid", "orchidaceous plant"],
    "oncogene": ["cistron", "factor", "gene", "transforming gene"],
    "oncological": ["oncologic"],
    "oncologist": ["medical specialist", "specialist"],
    "oncology": ["medical specialty", "medicine"],
    "oncoming": [],
    "oncorhynchus": ["fish genus", "genus oncorhynchus"],
    "ondaatje": ["michael ondaatje", "philip michael ondaatje"],
    "ondatra": ["genus ondatra", "mammal genus"],
    "one": ["1", "ace", "digit", "figure", "i", "monad", "monas", "single", "singleton", "unity"],
    "one by one": ["one after another", "one at a time"],
    "one hundred eighty": ["180", "clxxx"],
    "one hundred fifteen": ["115", "cxv"],
    "one hundred fifty": ["150", "cl"],
    "one hundred fifty-five": ["155", "clv"],
    "one hundred five": ["105", "cv"],
    "one hundred forty": ["140", "cxl"],
    "one hundred forty-five": ["145", "cxlv"],
    "one hundred ninety": ["190", "xcl"],
    "one hundred seventy": ["170", "clxx"],
    "one hundred seventy-five": ["175", "clxxv"],
    "one hundred sixty": ["160", "clx"],
    "one hundred sixty-five": ["165", "clxv"],
    "one hundred ten": ["110", "cx"],
    "one hundred thirty": ["130", "cxxx"],
    "one hundred thirty-five": ["135", "cxxxv"],
    "one hundred twenty": ["120", "cxx"],
    "one hundred twenty-five": ["125", "cxxv"],
    "one of the boys": ["boy"],
    "one-and-one": ["charity shot", "charity throw", "charity toss", "foul shot", "free throw", "penalty free throw"],
    "one-armed": [],
    "one-billionth": ["billionth", "common fraction", "simple fraction"],
    "one-dimensional language": ["programing language", "programming language"],
    "one-dimensionality": ["dimensionality", "linearity"],
    "one-eared": [],
    "one-eighth": ["common fraction", "eighth", "simple fraction"],
    "one-eyed": [],
    "one-fifth": ["common fraction", "fifth", "fifth part", "simple fraction", "twenty percent"],
    "one-flowered wintergreen": ["herb", "herbaceous plant", "moneses uniflora", "one-flowered pyrola", "pyrola uniflora"],
    "one-fourth": ["common fraction", "fourth", "fourth part", "one-quarter", "quarter", "quartern", "simple fraction", "twenty-five percent"],
    "one-half": ["common fraction", "fifty percent", "half", "mediety", "moiety", "simple fraction"],
    "one-handed": [],
    "one-hitter": ["1-hitter", "baseball", "baseball game"],
    "one-humped": ["single-humped"],
    "one-hundred-millionth": ["common fraction", "simple fraction"],
    "one-hundred-thousandth": ["common fraction", "simple fraction"],
    "one-hundredth": ["common fraction", "hundredth", "one percent", "simple fraction"],
    "one-liner": ["gag", "jape", "jest", "joke", "laugh"],
    "one-man": ["one-person", "one-woman"],
    "one-millionth": ["common fraction", "millionth", "simple fraction"],
    "one-night stand": ["promiscuity", "promiscuousness", "sleeping around"],
    "one-ninth": ["common fraction", "ninth", "simple fraction"],
    "one-off": ["happening", "natural event", "occurrence", "occurrent"],
    "one-on-one": ["person-to-person"],
    "one-party": [],
    "one-piece": [],
    "one-quadrillionth": ["common fraction", "quadrillionth", "simple fraction"],
    "one-quintillionth": ["common fraction", "quintillionth", "simple fraction"],
    "one-seventh": ["common fraction", "seventh", "simple fraction"],
    "one-sixteenth": ["common fraction", "simple fraction", "sixteenth", "sixteenth part"],
    "one-sixth": ["common fraction", "simple fraction", "sixth"],
    "one-sixtieth": ["common fraction", "simple fraction", "sixtieth"],
    "one-sixty-fourth": ["common fraction", "simple fraction", "sixty-fourth"],
    "one-spot": ["dice", "die", "domino"],
    "one-step": ["dance", "trip the light fantastic", "trip the light fantastic toe"],
    "one-ten-thousandth": ["common fraction", "simple fraction", "ten-thousandth"],
    "one-tenth": ["common fraction", "simple fraction", "ten percent", "tenth", "tenth part"],
    "one-third": ["common fraction", "simple fraction", "third", "tierce"],
    "one-thirty-second": ["common fraction", "simple fraction", "thirty-second", "thirty-second part"],
    "one-thousandth": ["common fraction", "simple fraction", "thousandth"],
    "one-to-one": [],
    "one-trillionth": ["common fraction", "simple fraction", "trillionth"],
    "one-twelfth": ["common fraction", "duodecimal", "simple fraction", "twelfth", "twelfth part"],
    "one-upmanship": ["pattern", "practice"],
    "one-way": [],
    "one-way light time": ["elapsed time", "owlt"],
    "one-way street": ["unilateralism"],
    "one-winged": [],
    "one-year-old": [],
    "oneida": ["iroquois"],
    "oneiric": [],
    "oneiromancer": ["diviner"],
    "oneiromancy": ["divination", "foretelling", "fortune telling", "soothsaying"],
    "oneness": ["identicalness", "identity", "indistinguishability", "unity"],
    "onerously": [],
    "ongoing": ["on-going"],
    "onion": ["bulb"],
    "onion bagel": ["bagel", "beigel"],
    "onion bread": ["bread", "breadstuff", "staff of life"],
    "onion butter": ["paste", "spread"],
    "onion dome": ["dome"],
    "onion mildew": ["downy mildew", "false mildew", "peronospora destructor"],
    "onion roll": ["bialy", "bialystoker", "bun", "roll"],
    "onion salt": ["flavorer", "flavoring", "flavourer", "flavouring", "seasoner", "seasoning"],
    "onion smut": ["smut", "smut fungus", "urocystis cepulae"],
    "onion stem": ["lepiota", "lepiota cepaestipes"],
    "onion thrips": ["onion louse", "thrip", "thripid", "thrips", "thrips tobaci"],
    "onion yellow dwarf": ["yellow dwarf"],
    "onion yellow-dwarf virus": ["plant virus"],
    "onionskin": ["flimsy", "typewriter paper", "typing paper"],
    "oniscidae": ["arthropod family", "family oniscidae"],
    "oniscus": ["arthropod genus", "genus oniscus"],
    "onlooker": ["looker", "looker-on", "spectator", "viewer", "watcher", "witness"],
    "only": ["only if", "only when"],
    "ono": ["yoko ono"],
    "onobrychis": ["genus onobrychis", "rosid dicot genus"],
    "onoclea": ["fern genus", "genus onoclea"],
    "onomancer": ["diviner"],
    "onomancy": ["divination", "foretelling", "fortune telling", "soothsaying"],
    "onomastic": [],
    "onomasticon": ["wordbook"],
    "onomastics": ["lexicology"],
    "onomatomania": ["compulsion", "obsession"],
    "onomatopoeia": ["rhetorical device"],
    "onomatopoeic": ["onomatopoetic"],
    "onondaga": ["iroquois"],
    "ononis": ["genus ononis", "rosid dicot genus"],
    "onopordum": ["asterid dicot genus", "genus onopordon", "genus onopordum", "onopordon"],
    "onosmodium": ["genus onosmodium", "plant genus"],
    "onrush": ["rush", "spate", "surge", "upsurge"],
    "onsager": ["lars onsager"],
    "onset": ["oncoming", "start"],
    "onshore": [],
    "onside": [],
    "onslaught": ["trouble"],
    "onstage": [],
    "ontario": [],
    "ontogenetic": [],
    "ontological": [],
    "ontology": ["arrangement", "organisation", "organization", "system"],
    "onychium": ["fern genus", "genus onychium"],
    "onychogalea": ["genus onychogalea", "mammal genus"],
    "onycholysis": ["onychosis"],
    "onychomys": ["genus onychomys", "mammal genus"],
    "onychophora": ["class", "class onychophora"],
    "onychophoran": ["arthropod", "peripatus", "plicatoperipatus jamaicensis", "velvet worm"],
    "onychosis": ["disease", "onycholysis"],
    "onymous": [],
    "onyx": ["calcedony", "chalcedony", "sardonyx"],
    "oocyte": ["gametocyte"],
    "oogenesis": ["gametogenesis"],
    "ooh": ["aah", "call out", "cry", "cry out", "exclaim", "outcry", "shout"],
    "oology": ["zoological science", "zoology"],
    "oolong": ["tea", "tea leaf"],
    "oomycetes": ["class", "class oomycetes"],
    "oophorectomy": ["ablation", "cutting out", "excision", "extirpation", "ovariectomy"],
    "oophoritis": ["inflammation", "redness", "rubor"],
    "oophorosalpingectomy": ["ablation", "cutting out", "excision", "extirpation"],
    "oort": ["jan hendrix oort"],
    "oort cloud": ["accumulation", "aggregation", "assemblage", "collection"],
    "oosphere": ["gamete"],
    "oospore": ["spore"],
    "ootid": ["egg cell", "ovum"],
    "ooze leather": ["leather"],
    "ooze through": ["penetrate", "perforate", "soak through", "sop"],
    "oozing": ["oozy", "seeping"],
    "op art": ["abstract art", "abstractionism"],
    "opacification": ["action", "activity", "natural action", "natural process"],
    "opacify": ["alter", "change", "modify"],
    "opacity": ["optical opacity", "physical phenomenon", "radio-opacity", "radiopacity"],
    "opah": ["lampris regius", "malacopterygian", "moonfish", "soft-finned fish"],
    "opal": ["black opal", "fire opal", "girasol", "harlequin opal", "mineral", "opaque gem"],
    "opal glass": ["glass", "milk glass"],
    "opalesce": ["reflect", "shine"],
    "opalescence": ["brightness", "iridescence"],
    "opalize": ["alter", "change", "modify", "opalise"],
    "opaque": ["unintelligible"],
    "opaque gem": ["cat's eye", "chrysoberyl", "coral", "gem", "gemstone", "jade", "jadestone", "jasper", "lapis lazuli", "lazuli", "opal", "precious coral", "red coral", "stone", "turquoise"],
    "opaquely": [],
    "opel": ["wilhelm von opel"],
    "open": [],
    "open account": ["bill-me order", "credit order"],
    "open chain": ["branched chain", "chain", "chemical chain", "straight chain"],
    "open circuit": ["circuit", "electric circuit", "electrical circuit"],
    "open door": ["door"],
    "open fire": ["blast", "fire", "shoot"],
    "open frame": ["break", "score"],
    "open house": ["party"],
    "open interval": ["interval", "unbounded interval"],
    "open letter": ["letter", "missive"],
    "open marriage": ["marriage", "matrimony", "spousal relationship", "union", "wedlock"],
    "open order": ["military formation"],
    "open primary": ["direct primary"],
    "open secret": ["secret"],
    "open sesame": ["bid", "bidding", "command", "dictation"],
    "open shop": ["company"],
    "open sight": ["gun-sight", "gunsight"],
    "open society": ["society"],
    "open university": ["university"],
    "open up": ["mouth", "speak", "talk", "utter", "verbalise", "verbalize"],
    "open weave": ["weave"],
    "open-air market": ["farmer's market", "flea market", "green market", "greenmarket", "market", "market place", "market square", "marketplace", "mart", "open-air marketplace", "souk"],
    "open-and-shut": [],
    "open-collared": [],
    "open-door policy": ["national trading policy", "open door", "trade policy"],
    "open-end credit": ["charge account", "charge account credit", "charge card", "charge plate", "check overdraft credit", "consumer credit", "credit account", "credit card", "debit card", "open account", "overdraft credit", "plastic", "revolving credit", "smart card"],
    "open-end wrench": ["s wrench", "spanner", "tappet wrench", "wrench"],
    "open-ended": [],
    "open-face sandwich": ["open sandwich", "sandwich"],
    "open-heart surgery": ["cabg", "coronary artery bypass graft", "coronary bypass", "coronary bypass surgery", "heart surgery"],
    "open-hearth": [],
    "open-hearth furnace": ["furnace"],
    "open-hearth process": ["steel production"],
    "open-minded": [],
    "open-plan": [],
    "open-source": [],
    "openbill": ["stork"],
    "opencast": ["opencut"],
    "opened": [],
    "opener": ["start"],
    "openhearted": [],
    "opening": ["chance", "opportunity"],
    "opening line": ["line"],
    "openly": [],
    "openness": ["patency", "spacing", "spatial arrangement"],
    "openside plane": ["carpenter's plane", "dado plane", "plane", "rabbet plane", "woodworking plane"],
    "openwork": ["piece of work", "work"],
    "opepe": ["nauclea diderrichii", "sarcocephalus diderrichii", "tree"],
    "opera": ["bouffe", "classical", "classical music", "comic opera", "grand opera", "musical drama", "opera bouffe", "opera comique", "serious music"],
    "opera cloak": ["cloak", "opera hood"],
    "opera company": ["company", "troupe"],
    "opera star": ["diva", "operatic star", "prima donna", "singer", "vocaliser", "vocalist", "vocalizer"],
    "operable": ["practicable"],
    "operagoer": ["frequenter", "patron"],
    "operand": ["quantity"],
    "operant": [],
    "operant conditioning": ["conditioning", "instrumental conditioning"],
    "operate": ["block", "direct", "financier", "run", "warm up", "work"],
    "operate on": ["care for", "desex", "desexualise", "desexualize", "face-lift", "fix", "lift", "operate", "sterilise", "sterilize", "treat", "trephine", "unsex", "venesect"],
    "operatic": [],
    "operating": [],
    "operating budget": ["budget"],
    "operating capability": ["capability", "capableness", "envelope", "performance capability"],
    "operating capital": ["capital", "working capital"],
    "operating expense": ["budget items", "disbursal", "disbursement", "expense", "operating cost", "overhead"],
    "operating microscope": ["binocular microscope"],
    "operating procedure": ["procedure", "process", "sop", "standard operating procedure", "standard procedure", "standing operating procedure"],
    "operating room": ["hospital room", "operating theater", "operating theatre", "or", "surgery"],
    "operating system": ["computer software", "disk operating system", "dos", "os", "package", "software", "software package", "software program", "software system", "unix", "unix operating system", "unix system", "windows"],
    "operating table": ["table"],
    "operation": ["action", "activeness", "activity", "commission", "idle", "running"],
    "operation code": ["code", "computer code", "order code"],
    "operation desert storm": [],
    "operational": [],
    "operational cell": ["radical cell", "terrorist cell"],
    "operational damage": ["damage", "equipment casualty", "operational casualty"],
    "operationalism": ["philosophical doctrine", "philosophical theory"],
    "operationalist": [],
    "operationally": [],
    "operations": ["dealing", "dealings", "trading operations", "transaction"],
    "operations research": ["research"],
    "operative": [],
    "operative field": ["field", "field of view"],
    "operatively": [],
    "operator": ["function", "identity", "identity element", "identity operator", "linear operator", "map", "mapping", "mathematical function", "single-valued function"],
    "operator gene": ["cistron", "factor", "gene"],
    "operculate": ["operculated"],
    "operculum": ["plate"],
    "operetta": ["bouffe", "comic opera", "light opera", "opera bouffe", "opera comique"],
    "operon": ["deoxyribonucleic acid", "desoxyribonucleic acid", "dna"],
    "opheodrys": ["genus opheodrys", "reptile genus"],
    "ophidiidae": ["family ophidiidae", "fish family"],
    "ophidism": ["intoxication", "poisoning", "toxic condition"],
    "ophiodon": ["fish genus", "genus ophiodon"],
    "ophiodontidae": ["family ophiodontidae", "fish family"],
    "ophioglossaceae": ["family ophioglossaceae", "fern family"],
    "ophioglossales": ["order ophioglossales", "plant order"],
    "ophioglossum": ["fern genus", "genus ophioglossum"],
    "ophiolatry": ["animal-worship", "serpent-worship", "zoolatry"],
    "ophiophagus": ["genus ophiophagus", "reptile genus"],
    "ophisaurus": ["genus ophisaurus", "reptile genus"],
    "ophiuchus": [],
    "ophiurida": ["class", "subclass ophiurida"],
    "ophiuroidea": ["class", "class ophiuroidea"],
    "ophryon": ["craniometric point"],
    "ophrys": ["genus ophrys", "liliopsid genus", "monocot genus"],
    "ophthalmectomy": ["ablation", "cutting out", "excision", "extirpation"],
    "ophthalmia": ["conjunctivitis", "ophthalmia neonatorum", "ophthalmitis", "pinkeye"],
    "ophthalmia neonatorum": ["ophthalmia", "ophthalmitis"],
    "ophthalmic": [],
    "ophthalmic artery": ["arteria", "arteria ophthalmica", "arterial blood vessel", "artery"],
    "ophthalmic vein": ["inferior ophthalmic vein", "superior ophthalmic vein", "vein", "vena", "vena ophthalmica", "venous blood vessel"],
    "ophthalmologist": ["eye doctor", "medical specialist", "oculist", "specialist"],
    "ophthalmology": ["medical specialty", "medicine"],
    "ophthalmoplegia": ["palsy", "paralysis"],
    "ophthalmoscope": ["medical instrument", "orthoscope"],
    "ophthalmoscopy": ["examination", "scrutiny"],
    "opiate": ["codeine", "diacetylmorphine", "fentanyl", "heroin", "laudanum", "morphia", "morphine", "narcotic", "sublimaze", "tincture of opium"],
    "opine": ["animadvert", "declare", "editorialise", "editorialize", "sound off", "speak out", "speak up"],
    "opinion": ["adverse opinion", "conjecture", "content", "guess", "hypothesis", "message", "position", "side", "speculation", "subject matter", "substance", "supposition", "surmisal", "surmise", "view"],
    "opinionated": ["opinionative", "self-opinionated"],
    "opisthobranchia": ["class", "subclass opisthobranchia"],
    "opisthocomidae": ["bird family", "family opisthocomidae"],
    "opisthocomus": ["bird genus", "genus opisthocomus"],
    "opisthognathidae": ["family opisthognathidae", "fish family"],
    "opisthognathous": [],
    "opisthorchiasis": ["infestation"],
    "opisthotonos": ["cramp", "muscle spasm", "spasm"],
    "opium": ["controlled substance", "narcotic"],
    "opium addict": ["drug addict", "junkie", "junky", "opium taker"],
    "opium den": ["building", "edifice"],
    "opium poppy": ["papaver somniferum", "poppy"],
    "opopanax": ["gum"],
    "opossum": ["common opossum", "crab-eating opossum", "didelphis marsupialis", "didelphis virginiana", "marsupial", "possum", "pouched mammal"],
    "opossum rat": ["marsupial", "pouched mammal"],
    "opossum shrimp": ["malacostracan crustacean"],
    "oppenheimer": ["robert oppenheimer"],
    "opponent": ["opposing"],
    "opportune": [],
    "opportunely": [],
    "opportuneness": ["convenience", "patness", "timeliness"],
    "opportunism": ["expedience", "self-interest", "self-seeking", "selfishness"],
    "opportunist": ["backscratcher", "bottom feeder", "carpetbagger", "hustler", "operator", "self-seeker", "selfish person", "timeserver", "wheeler dealer"],
    "opportunistic infection": ["aspergillosis", "infection"],
    "opportunity": ["audience", "brass ring", "chance", "clean slate", "crack", "day", "fresh start", "hearing", "hunting ground", "occasion", "opening", "possibility", "possibleness", "room", "say", "shot", "street", "tabula rasa", "throw"],
    "opportunity cost": ["capital cost", "carrying charge", "carrying cost", "cost", "cost of capital"],
    "opposable": ["apposable"],
    "oppose": ["contrast", "counterbalance", "counterpoint", "counterpoise", "counterpose", "counterweight"],
    "opposed": [],
    "opposite": [],
    "oppositely": [],
    "opposition": ["antagonism", "antipode", "antithesis", "conflict", "contradiction", "contradictoriness", "contrariety", "contrary", "contrast", "direct contrast", "flip side", "gradable opposition", "inverse", "mutual opposition", "opposite", "oppositeness", "polarity", "relation", "reverse", "sign", "tertium quid", "ungradable opposition"],
    "oppress": ["crush", "keep down", "quash", "reduce", "repress", "subdue", "subjugate", "suppress"],
    "oppression": ["subjection", "subjugation", "yoke"],
    "oppressive": [],
    "oppressively": [],
    "oppressor": ["authoritarian", "dictator", "disagreeable person", "meanie", "meany", "persecutor", "switcher", "tormenter", "tormentor", "torturer", "unkind person", "unpleasant person", "whipper"],
    "ops": [],
    "opsin": ["protein"],
    "opsonin": ["antibody"],
    "opsonization": ["activity", "bodily function", "bodily process", "body process", "opsonisation"],
    "opsonize": ["alter", "change", "modify"],
    "opt out": ["choose", "cop out", "opt", "prefer"],
    "optative": [],
    "optative mood": ["modality", "mode", "mood", "optative"],
    "optez": ["artificial language"],
    "optic axis": ["axis"],
    "optic chiasma": ["chiasm", "chiasma", "chiasma opticum", "decussation", "optic chiasm"],
    "optic cup": ["caliculus", "calycle", "calyculus", "eyecup"],
    "optic nerve": ["cranial nerve", "nervus opticus", "optic tract", "second cranial nerve"],
    "optic radiation": ["nerve pathway", "nerve tract", "pathway", "radiatio optica", "tract"],
    "optical": [],
    "optical bench": ["apparatus", "setup"],
    "optical crown": ["crown glass", "optical crown glass", "optical glass"],
    "optical density": ["absorbance", "denseness", "density", "photographic density", "transmission density"],
    "optical device": ["autofocus", "biprism", "camera lucida", "coelostat", "collimator", "device", "diffraction grating", "diffuser", "diffusor", "finder", "grating", "kerr cell", "laser", "lens", "lens system", "lense", "nicol prism", "optical maser", "optical prism", "planetarium", "polarimeter", "polariscope", "prism", "projector", "rochon prism", "stereoscope", "view finder", "viewer", "viewfinder", "wollaston prism"],
    "optical disk": ["cd", "compact disc", "compact disk", "dvd", "memory device", "optical disc", "storage device", "videodisc", "videodisk"],
    "optical fiber": ["fiber", "fibre", "glass fiber", "glass fibre", "optical fibre"],
    "optical flint": ["flint glass", "optical glass"],
    "optical glass": ["crown glass", "flint glass", "glass", "optical crown", "optical crown glass", "optical flint"],
    "optical illusion": ["apparent motion", "apparent movement", "mirage", "motion", "movement", "optical phenomenon"],
    "optical instrument": ["binoculars", "esophagoscope", "eyeglasses", "field glasses", "glasses", "instrument", "jeweler's glass", "oesophagoscope", "opera glasses", "periscope", "prism spectroscope", "projector", "sights", "specs", "spectacles", "spectroscope"],
    "optical opacity": ["opacity"],
    "optical phenomenon": ["aberration", "absorption band", "diffraction", "distortion", "fringe", "incidence", "interference fringe", "optical aberration", "optical illusion", "parallax", "physical phenomenon", "pleochroism", "polarisation", "polarization", "tyndall effect"],
    "optical pyrometer": ["pyrometer", "pyroscope"],
    "optical telescope": ["astronomical telescope", "reflecting telescope", "reflector", "refracting telescope"],
    "optically": [],
    "optician": ["lens maker", "skilled worker", "skilled workman", "trained worker"],
    "optics": ["catoptrics", "holography", "natural philosophy", "physics"],
    "optimally": [],
    "optimism": ["hope", "sanguineness", "sanguinity"],
    "optimist": ["chiliast", "individual", "millenarian", "millenarist", "mortal", "person", "somebody", "someone", "soul"],
    "optimistic": [],
    "optimistically": [],
    "optimization": ["improvement", "optimisation"],
    "optimize": ["hone", "optimise", "perfect"],
    "optimum": ["good", "goodness"],
    "option": ["call", "call option", "covered option", "derivative", "derivative instrument", "incentive option", "incentive stock option", "lock-up option", "naked option", "put", "put option", "stock option", "straddle"],
    "optional": [],
    "optionally": [],
    "optometrist": ["oculist", "specialiser", "specialist", "specializer"],
    "optometry": ["practice"],
    "opuntia": ["caryophylloid dicot genus", "genus opuntia"],
    "opuntiales": ["order opuntiales", "plant order"],
    "or circuit": ["gate", "logic gate", "or gate"],
    "orach": ["atriplex hortensis", "garden orache", "herb", "herbaceous plant", "mountain spinach", "orache"],
    "oracle": ["divination", "prophecy"],
    "oracular": [],
    "orad": [],
    "oral": ["exam", "examination", "oral exam", "oral examination", "test", "viva", "viva voce"],
    "oral cancer": ["carcinoma"],
    "oral contraception": ["contraception", "contraceptive method"],
    "oral contract": ["agreement", "understanding"],
    "oral herpes": ["cold sore", "fever blister", "herpes labialis", "herpes simplex"],
    "oral personality": ["personality"],
    "oral sex": ["cunnilinctus", "cunnilingus", "fellatio", "fellation", "head", "perversion", "sexual perversion", "sixty-nine", "soixante-neuf"],
    "oral smear": ["alimentary tract smear"],
    "oral stage": ["oral phase", "phase", "stage"],
    "orally": [],
    "oran": [],
    "orange": ["pigment"],
    "orange bat": ["leaf-nosed bat", "leafnose bat", "orange horseshoe bat", "rhinonicteris aurantius"],
    "orange daisy": ["erigeron aurantiacus", "fleabane", "orange fleabane"],
    "orange grass": ["hypericum gentianoides", "nitweed", "pine-weed", "pineweed", "st john's wort"],
    "orange group": ["ov"],
    "orange grove": ["grove", "orchard", "plantation", "woodlet"],
    "orange hawkweed": ["hieracium aurantiacum", "pilosella aurantiaca", "weed"],
    "orange juice": ["frozen orange juice", "fruit crush", "fruit juice", "orange-juice concentrate"],
    "orange liqueur": ["cordial", "curacao", "curacoa", "grand marnier", "liqueur", "triple sec"],
    "orange marmalade": ["marmalade"],
    "orange milkwort": ["candyweed", "milkwort", "polygala lutea", "yellow bachelor's button", "yellow milkwort"],
    "orange mushroom pimple": ["mushroom pimple"],
    "orange order": ["association of orangemen"],
    "orange peel": ["orange rind", "orange zest", "peel", "skin"],
    "orange pekoe": ["black tea", "pekoe"],
    "orange sneezeweed": ["helenium hoopesii", "owlclaws", "sneezeweed"],
    "orange soda": ["soft drink"],
    "orange toast": ["toast"],
    "orange tortrix": ["argyrotaenia citrana", "tortricid", "tortricid moth", "tortrix"],
    "orange yellow": ["ocher", "ochre", "saffron", "yellow", "yellowness"],
    "orange zest": ["orange peel", "orange rind"],
    "orange-blossom orchid": ["orchid", "orchidaceous plant", "sarcochilus falcatus"],
    "orange-brown": [],
    "orange-colored": ["orange-coloured", "orange-hued"],
    "orange-flowered": [],
    "orange-red": ["orangish-red"],
    "orange-sized": [],
    "orangeade": ["ade", "fruit drink"],
    "orangeman": ["protestant"],
    "orangery": ["glasshouse", "greenhouse", "nursery", "plantation"],
    "orangewood": ["wood"],
    "orangutan": ["great ape", "orang", "orangutang", "pongid", "pongo pygmaeus"],
    "orate": ["bloviate", "speak", "talk"],
    "oration": ["oratory", "peroration"],
    "orator": ["elocutionist", "eulogist", "haranguer", "panegyrist", "public speaker", "rhetorician", "speaker", "speechifier", "speechmaker", "spellbinder", "talker", "tub-thumper", "utterer", "verbaliser", "verbalizer"],
    "oratorical": [],
    "oratory": ["address", "declamation", "epideictic oratory", "keynote address", "keynote speech", "nominating address", "nominating speech", "nomination", "oration", "salutatory", "salutatory address", "salutatory oration", "speech", "stump speech", "valediction", "valedictory", "valedictory address", "valedictory oration"],
    "orb": ["circle", "circulate", "orbit", "retrograde", "revolve"],
    "orb web": ["spider web", "spider's web"],
    "orb-weaving": [],
    "orb-weaving spider": ["spider"],
    "orbiculate": ["orbicular"],
    "orbiculate leaf": ["simple leaf"],
    "orbignya": ["genus orbignya", "liliopsid genus", "monocot genus"],
    "orbison": ["roy orbison"],
    "orbit": ["electron orbit", "itinerary", "path", "route"],
    "orbit period": ["period"],
    "orbital": [],
    "orbital plane": ["plane", "sheet"],
    "orbital rotation": ["gyration", "orbital motion", "revolution", "rotation"],
    "orbitale": ["craniometric point", "orbital point"],
    "orchard grass": ["cocksfoot", "cockspur", "dactylis glomerata", "grass"],
    "orchard oriole": ["american oriole", "icterus spurius", "new world oriole", "oriole"],
    "orchestia": ["arthropod genus", "genus orchestia"],
    "orchestiidae": ["arthropod family", "family orchestiidae"],
    "orchestra": ["chamber orchestra", "musical group", "musical organisation", "musical organization", "philharmonic", "string orchestra", "symphony", "symphony orchestra"],
    "orchestra pit": ["area", "pit"],
    "orchestral": [],
    "orchestrate": ["score"],
    "orchestrated": [],
    "orchestration": ["arrangement", "musical arrangement"],
    "orchestrator": ["adapter", "arranger", "transcriber"],
    "orchid": ["adam-and-eve", "aerides", "angrecum", "aplectrum hyemale", "arethusa", "bee orchid", "bletia", "bletia striata", "bletilla striata", "brassavola", "brassia lawrenceana", "brassia verrucosa", "broad-leaved twayblade", "butterfly orchid", "butterfly orchis", "butterfly plant", "caladenia", "calanthe", "calopogon pulchellum", "calopogon tuberosum", "calypso", "calypso bulbosa", "catasetum macrocarpum", "cattleya", "cattleya citrina", "cleistes divaricata", "cleistes rosea", "coeloglossum bracteatum", "coeloglossum viride", "coelogyne", "common spotted orchid", "coral root", "crested coral root", "cymbid", "cymbidium", "cypripedia", "dactylorhiza fuchsii", "dactylorhiza maculata fuchsii", "dancing lady orchid", "dendrobium", "disa", "eburophyton austinae", "encyclia citrina", "encyclia tampensis", "encyclia venosa", "epidendron", "epidendrum tampense", "epidendrum venosum", "fairy-slipper", "fen orchid", "fen orchis", "flower", "fly orchid", "foxtail orchid", "fragrant orchid", "fringed orchid", "fringed orchis", "frog orchid", "funnel-crest rosebud orchid", "grass pink", "greater butterfly orchid", "green adder's mouth", "greenhood", "gymnadenia conopsea", "gymnadenia odoratissima", "habenaria bifolia", "habenaria chlorantha", "helleborine", "helmet orchid", "helmetflower", "hexalectris spicata", "hexalectris warnockii", "himantoglossum hircinum", "indian crocus", "jewel orchid", "jumping orchid", "ladies' slipper", "ladies' tresses", "lady's slipper", "lady's tresses", "lady-slipper", "laelia", "lesser butterfly orchid", "lesser twayblade", "liparis", "liparis loeselii", "listera convallarioides", "listera cordata", "listera ovata", "lizard orchid", "malaxis ophioglossoides", "malaxis-unifolia", "marsh orchid", "masdevallia", "maxillaria", "moth orchid", "moth plant", "odontoglossum", "oncidium", "ophrys apifera", "ophrys insectifera", "ophrys muscifera", "orange-blossom orchid", "orchidaceous plant", "orchis", "pansy orchid", "phaius", "phantom orchid", "platanthera bifolia", "platanthera chlorantha", "platanthera leucophea", "pleurothallis", "pogonia", "pogonia divaricata", "pogonia rosea", "prairie white-fringed orchid", "puttyroot", "rattlesnake orchid", "rattlesnake plantain", "rein orchid", "rein orchis", "rosebud orchid", "sarcochilus falcatus", "satyr orchid", "short-spurred fragrant orchid", "slipper orchid", "snow orchid", "sobralia", "spider orchid", "spreading pogonia", "stanhopea", "stelis", "swan orchid", "swan-flower", "swan-neck", "swanflower", "swanneck", "tangle orchid", "texas purple spike", "tongue-flower", "tongueflower", "tulip orchid", "twayblade", "vanda", "vanilla", "venus' slipper", "venus's shoe", "venus's slipper"],
    "orchidaceae": ["family orchidaceae", "liliopsid family", "monocot family", "orchid family"],
    "orchidales": ["order orchidales", "plant order"],
    "orchidalgia": ["hurting", "pain"],
    "orchidectomy": ["ablation", "cutting out", "excision", "extirpation", "orchiectomy"],
    "orchil": ["archil", "cudbear", "dye", "dyestuff"],
    "orchiopexy": ["operation", "surgery", "surgical operation", "surgical procedure", "surgical process"],
    "orchis": ["butterfly orchid", "butterfly orchis", "early purple orchid", "male orchis", "orchid", "orchidaceous plant", "orchis mascula", "orchis papilionaceae", "orchis spectabilis", "purple orchis", "purple-hooded orchis", "showy orchis"],
    "orchitis": ["inflammation", "redness", "rubor"],
    "orchotomy": ["incision", "section", "surgical incision"],
    "orcinus": ["genus orcinus", "mammal genus"],
    "orczy": ["baroness emmusca orczy"],
    "ord kangaroo rat": ["desert rat", "dipodomys ordi", "dipodomys phillipsii", "kangaroo rat"],
    "ordain": ["decree", "enact", "legislate", "pass", "reenact"],
    "ordained": [],
    "ordainer": ["churchman", "cleric", "divine", "ecclesiastic"],
    "ordeal": ["experience"],
    "order": ["bring down", "dictate", "impose", "inflict", "mandate", "prescribe", "visit"],
    "order arms": ["attitude", "position", "posture"],
    "order book": ["book", "volume"],
    "order form": ["form"],
    "order myxobacteria": ["animal order", "myxobacterales", "myxobacteriales", "order myxobacterales", "order myxobacteriales"],
    "order of magnitude": ["magnitude", "ratio"],
    "order of the day": ["agenda", "agendum", "order book", "order of business", "order paper"],
    "order of the purple heart": ["decoration", "laurel wreath", "medal", "medallion", "palm", "purple heart", "ribbon"],
    "order paper": ["order book", "order of the day"],
    "ordered": [],
    "orderer": ["buyer", "emptor", "purchaser", "vendee"],
    "ordering": ["arrangement", "bacteria order", "genetic code", "genome", "order", "ordination", "series", "word order"],
    "orderliness": ["condition", "kelter", "kilter", "order", "spit and polish", "status", "tidiness"],
    "orderly": ["attendant", "attender", "soldier", "tender"],
    "orderly sergeant": ["first sergeant", "sergeant first class"],
    "ordinal": [],
    "ordinal number": ["first", "no.", "number", "number 1", "number one", "ordinal"],
    "ordinance": ["legislative act", "statute"],
    "ordinand": ["clergyman", "man of the cloth", "reverend"],
    "ordinariness": ["averageness", "commonness", "commonplaceness", "everydayness", "expectedness", "mediocrity", "mundaneness", "mundanity", "quality"],
    "ordinary": ["condition"],
    "ordinary annuity": ["annuity", "rente"],
    "ordinate": ["cartesian coordinate"],
    "ordination": ["position", "status"],
    "ordnance survey": ["administrative body", "administrative unit"],
    "ordovician": ["ordovician period"],
    "ore": ["concentrate", "dressed ore", "iron ore", "lead ore", "mineral", "pay dirt", "uranium ore"],
    "ore bed": ["bed"],
    "oread": ["nymph"],
    "oreamnos": ["genus oreamnos", "mammal genus"],
    "orectolobidae": ["family orectolobidae", "fish family"],
    "orectolobus": ["fish genus", "genus orectolobus"],
    "oregano": ["marjoram", "origanum", "origanum vulgare", "pot marjoram", "wild marjoram", "winter sweet"],
    "oregon": ["beaver state", "or"],
    "oregon ash": ["ash", "ash tree", "fraxinus latifolia", "fraxinus oregona"],
    "oregon cedar": ["cedar", "cedar tree", "chamaecyparis lawsoniana", "lawson's cedar", "lawson's cypress", "port orford cedar"],
    "oregon crab apple": ["crab apple", "crabapple", "malus fusca", "wild apple"],
    "oregon grape": ["bush", "mahonia nervosa", "shrub"],
    "oregon maple": ["acer macrophyllum", "big-leaf maple", "maple"],
    "oregon white oak": ["garry oak", "oregon oak", "quercus garryana", "white oak"],
    "oregonian": ["american", "beaver"],
    "oreo": ["biscuit", "cookie", "cooky", "oreo cookie"],
    "oreopteris": ["fern genus", "genus oreopteris"],
    "oreortyx": ["bird genus", "genus oreortyx"],
    "orestes": [],
    "orff": ["carl orff"],
    "organ": ["agency", "authority", "bureau", "federal agency", "government agency", "office"],
    "organ donor": ["donor"],
    "organ loft": ["gallery"],
    "organ of corti": ["organ of hearing"],
    "organ of hearing": ["organ of corti", "receptor", "sense organ", "sensory receptor"],
    "organ pipe": ["flue", "flue pipe", "labial pipe", "organ stop", "pipe", "pipework", "reed pipe", "wind", "wind instrument"],
    "organ stop": ["diapason", "diapason stop", "dulciana", "flue stop", "organ pipe", "pipe", "pipework", "reed stop", "sourdine", "voix celeste", "vox angelica"],
    "organ-grinder": ["impresario", "promoter", "showman"],
    "organdy": ["muslin", "organdie"],
    "organelle": ["cell nucleus", "cell organ", "cell organelle", "centriole", "chondriosome", "cilium", "karyon", "lysosome", "mitochondrion", "nucleole", "nucleolus", "nucleus", "organ", "ribosome"],
    "organic": ["bonemeal", "fertiliser", "fertilizer", "fish meal", "guano", "manure", "neem cake", "organic fertiliser", "organic fertilizer", "plant food"],
    "organic brain syndrome": ["mental abnormality"],
    "organic chemistry": ["biochemistry", "chemical science", "chemistry", "phytochemistry"],
    "organic compound": ["acetal", "acid anhydrides", "acid halide", "acyl anhydrides", "acyl halide", "aldehyde", "aldehyde-alcohol", "aldol", "aliphatic compound", "alkaloid", "alkyl halide", "alkylbenzene", "amide", "amino acid", "aminoalkanoic acid", "azadirachtin", "cacodyl", "carbamide", "chemical compound", "coal-tar creosote", "compound", "creatine phosphate", "creatine phosphoric acid", "creosote", "cyanide", "cyanohydrin", "diamine", "enol", "erythrocytolysin", "erythrolysin", "ester", "ether", "furan", "furane", "furfuran", "glycoside", "haemolysin", "haloalkane", "halocarbon", "halon", "hemiacetal", "hemolysin", "humic substance", "hydrocarbon", "imide", "ketone", "macromolecule", "neurochemical", "nitril", "nitrile", "nitrobenzene", "nonsteroid", "nonsteroidal", "oxime", "peptone", "petrochemical", "phenol", "phosphocreatine", "proenzyme", "propylthiouracil", "pyrimidine", "quassia", "quaternary ammonium compound", "rennet", "resin", "rosin", "steroid", "supermolecule", "tetramethyldiarsine", "thiazine", "thiouracil", "urea", "xanthine", "zymogen"],
    "organic disorder": ["disorder", "upset"],
    "organic light-emitting diode": ["led", "light-emitting diode", "oled"],
    "organic phenomenon": ["abiogenesis", "alternation of generations", "annual ring", "autogenesis", "autogeny", "bioelectricity", "circulation", "cyclosis", "death", "decay", "decomposition", "dehiscence", "desquamation", "diapedesis", "dominance", "exfoliation", "facilitation", "food chain", "food cycle", "food pyramid", "food web", "gene expression", "greening", "growth ring", "heterogenesis", "histocompatibility", "life", "life cycle", "natural phenomenon", "peeling", "pleomorphism", "polymorphism", "recognition", "rejection", "rejuvenation", "sex linkage", "shedding", "spontaneous generation", "streaming", "xenogenesis"],
    "organic process": ["absorption", "activity", "adaptation", "adaption", "adjustment", "ageing", "agglutination", "aging", "anovulation", "antisepsis", "asepsis", "assimilation", "autoregulation", "bacteriostasis", "biological process", "birth", "birthing", "blistering", "bloom", "blooming", "bodily function", "bodily process", "body process", "carbon cycle", "catabolism", "cell division", "cellular division", "citric acid cycle", "crossing over", "crossover", "cytokinesis", "defoliation", "deossification", "destructive metabolism", "development", "digestion", "dissimilation", "eburnation", "ecchymosis", "effacement", "epistasis", "erythropoiesis", "eutrophication", "evolution", "expression", "extravasation", "folding", "gastrulation", "giving birth", "glycogenesis", "growing", "growth", "haematogenesis", "haematopoiesis", "haemogenesis", "haemopoiesis", "hematogenesis", "hematopoiesis", "hemogenesis", "hemopoiesis", "heredity", "humification", "hypostasis", "implantation", "infolding", "inhibition", "introversion", "intussusception", "invagination", "involution", "karyokinesis", "katabolism", "keratinisation", "keratinization", "krebs citric acid cycle", "krebs cycle", "lymphopoiesis", "lysogenisation", "lysogenization", "maturation", "maturement", "metabolic process", "metabolism", "metamorphosis", "nidation", "nitrogen cycle", "nitrogen fixation", "nondevelopment", "nutrition", "ontogenesis", "ontogeny", "organic evolution", "organification", "ossification", "ovulation", "oxidative phosphorylation", "parturition", "pathologic process", "pathological process", "perennation", "phylogenesis", "phylogeny", "physical process", "preservation", "process", "protein folding", "quellung", "quellung reaction", "quickening", "reabsorption", "regeneration", "regulation", "replication", "reproduction", "resorption", "ripening", "sanguification", "secernment", "secretion", "segregation", "senescence", "shedding", "sloughing", "summation", "symphysis", "synapsis", "synezesis", "synizesis", "transcription", "transduction", "translation", "translocation", "transpiration", "tricarboxylic acid cycle", "tumefaction", "ulceration", "vascularisation", "vascularization", "vesication", "vesiculation"],
    "organically": [],
    "organicism": ["scientific theory"],
    "organicistic": [],
    "organification": ["biological process", "organic process"],
    "organism": ["scheme", "system"],
    "organismal": ["organismic"],
    "organist": ["instrumentalist", "musician", "player"],
    "organization": ["adhocracy", "affiliate", "alignment", "alinement", "alliance", "association", "blue", "brotherhood", "bureaucracy", "coalition", "commission", "company", "defence", "defence force", "defense", "defense force", "delegacy", "delegation", "deputation", "enterprise", "establishment", "federation", "fiefdom", "fire brigade", "fire company", "force", "girl scouts", "gray", "grey", "hierarchy", "host", "institution", "labor union", "line of defence", "line of defense", "line organisation", "line organization", "machine", "mission", "musical group", "musical organisation", "musical organization", "ngo", "nongovernmental organization", "organisation", "party", "peace corps", "pecking order", "personnel", "political machine", "political party", "polity", "pool", "power structure", "professional organisation", "professional organization", "quango", "quasi-ngo", "social group", "social unit", "tammany", "tammany hall", "tammany society", "trade union", "trades union", "troupe", "union", "unit"],
    "organization chart": ["chart"],
    "organization expense": ["business expense", "trade expense"],
    "organization for the prohibition of chemical weapons": ["global organization", "international organisation", "international organization", "opcw", "world organisation", "world organization"],
    "organization man": ["employee"],
    "organization of american states": ["global organization", "international organisation", "international organization", "oas", "world organisation", "world organization"],
    "organization of petroleum-exporting countries": ["global organization", "international organisation", "international organization", "oil cartel", "opec", "world organisation", "world organization"],
    "organizational": ["organisational"],
    "organizationally": [],
    "organize": ["arrange", "care", "collectivise", "collectivize", "deal", "handle", "manage", "order", "organise", "put", "rationalise", "rationalize", "reorganise", "reorganize", "set up", "shake up", "territorialise", "territorialize"],
    "organized": ["organised", "unionised", "unionized"],
    "organized crime": ["black hand", "camorra", "crime syndicate", "family", "gangdom", "gangland", "maffia", "mafia", "mob", "sicilian mafia", "social group", "syndicate", "yakuza"],
    "organized labor": ["labor", "labour", "proletariat", "working class"],
    "organizer": ["labor organizer", "organiser", "union representative"],
    "organon": ["system", "system of rules"],
    "organophosphate": ["chlorpyrifos", "insect powder", "insecticide"],
    "organophosphate nerve agent": ["ga", "gb", "gd", "nerve agent", "nerve gas", "sarin", "soman", "tabun"],
    "organza": ["cloth", "fabric", "material", "textile"],
    "orgasm": ["climax", "coming", "consummation", "male orgasm", "sexual climax"],
    "orgiastic": [],
    "orgy": ["binge", "humoring", "indulgence", "indulging", "pampering", "splurge"],
    "oriel": ["bay window", "bow window", "oriel window"],
    "orient": ["lie", "point"],
    "oriental": ["asian", "asiatic", "evenki", "ewenki", "gook", "mongol", "mongolian", "oriental person", "slant-eye", "yellow man", "yellow woman"],
    "oriental arborvitae": ["arborvitae", "platycladus orientalis", "thuja orientalis"],
    "oriental beetle": ["anomala orientalis", "asiatic beetle", "scarabaean", "scarabaeid", "scarabaeid beetle"],
    "oriental cherry": ["flowering cherry", "japanese cherry", "japanese flowering cherry", "prunus serrulata"],
    "oriental cockroach": ["asiatic cockroach", "blackbeetle", "blatta orientalis", "cockroach", "oriental roach", "roach"],
    "oriental plane": ["plane tree", "platan", "platanus orientalis", "sycamore"],
    "oriental poppy": ["papaver orientale", "poppy"],
    "oriental scops owl": ["otus sunia", "scops owl"],
    "oriental spruce": ["picea orientalis", "spruce"],
    "orientalism": ["arts", "humanistic discipline", "humanities", "liberal arts", "oriental studies"],
    "orientalist": ["specialiser", "specialist", "specializer"],
    "orientalize": ["alter", "change", "modify", "orientalise"],
    "orientation": ["attitude", "direction", "horizontal", "quarter", "vertical"],
    "orientation course": ["class", "course", "course of instruction", "course of study", "orientation"],
    "oriented": ["orientated"],
    "orienting": ["orientating"],
    "orifice": ["anus", "aortic orifice", "blastopore", "cardia", "cervix", "cervix uteri", "external orifice", "fenestra", "fontanel", "fontanelle", "introitus", "mouth", "naris", "opening", "os", "passage", "passageway", "porta", "porta hepatis", "pylorus", "rima", "soft spot", "spiracle", "stoma", "urethral orifice", "uterine cervix", "vent"],
    "oriflamme": ["symbol", "symbolic representation", "symbolisation", "symbolization"],
    "origami": ["art", "artistic creation", "artistic production"],
    "origanum": ["cretan dittany", "crete dittany", "dittany of crete", "herb", "herbaceous plant", "hop marjoram", "knotted marjoram", "majorana hortensis", "marjoram", "oregano", "origanum dictamnus", "origanum majorana", "origanum vulgare", "pot marjoram", "sweet marjoram", "wild marjoram", "winter sweet"],
    "origen": [],
    "origin": ["source"],
    "original": ["archetype", "example", "model", "pilot"],
    "original sin": ["church doctrine", "creed", "gospel", "religious doctrine", "sin", "sinning"],
    "originalism": ["belief"],
    "originality": ["ability", "freshness", "innovativeness", "novelty", "power", "unconventionality"],
    "originally": [],
    "originate": ["begin", "start"],
    "originate in": ["stem"],
    "origination fee": ["fee"],
    "originator": ["beginner", "conceiver", "creator", "father", "founder", "founding father", "groundbreaker", "innovator", "mastermind", "mover", "pioneer", "proposer", "suggester", "trailblazer"],
    "orinasal phone": ["orinasal", "phone", "sound", "speech sound"],
    "orinoco": ["orinoco river"],
    "oriolidae": ["bird family", "family oriolidae"],
    "oriolus": ["bird genus", "genus oriolus"],
    "orion": [],
    "orissa": [],
    "orites": ["dicot genus", "genus orites", "magnoliopsid genus"],
    "oriya": ["indian"],
    "orizaba": [],
    "orkney islands": [],
    "orlando": [],
    "orleanais": [],
    "orleanism": ["ideology", "political orientation", "political theory"],
    "orleanist": ["monarchist", "royalist"],
    "orleans": [],
    "orlon": ["acrylic"],
    "orlop deck": ["deck", "fourth deck", "orlop"],
    "orly": [],
    "ormandy": ["eugene ormandy"],
    "ormazd": ["ahura mazda", "ormuzd"],
    "ormer": ["abalone", "ear-shell", "haliotis tuberculata", "sea-ear"],
    "ormolu": ["brass"],
    "ormosia": ["genus ormosia", "rosid dicot genus"],
    "ornament": ["adorn", "beautify", "deck", "decorate", "embellish", "grace"],
    "ornamental": ["flora", "flowering maple", "plant", "plant life"],
    "ornamentalism": ["pattern", "practice"],
    "ornamentally": [],
    "ornamentation": ["state"],
    "ornately": [],
    "ornateness": ["appearance", "elaborateness", "flamboyance", "floridity", "floridness", "fussiness", "showiness", "visual aspect"],
    "ornithine": ["amino acid", "aminoalkanoic acid"],
    "ornithischia": ["animal order", "order ornithischia"],
    "ornithischian": ["armored dinosaur", "bone-headed dinosaur", "ceratopsian", "dinosaur", "duck-billed dinosaur", "hadrosaur", "hadrosaurus", "horned dinosaur", "ornithischian dinosaur", "ornithopod", "ornithopod dinosaur", "pisanosaur", "pisanosaurus", "staurikosaur", "staurikosaurus"],
    "ornithogalum": ["genus ornithogalum", "liliid monocot genus"],
    "ornithological": [],
    "ornithologist": ["animal scientist", "bird watcher", "zoologist"],
    "ornithology": ["zoological science", "zoology"],
    "ornithomimid": ["bird-footed dinosaur", "deinocheirus", "struthiomimus", "theropod", "theropod dinosaur"],
    "ornithomimida": ["animal order", "suborder ornithomimida"],
    "ornithopod": ["ornithischian", "ornithischian dinosaur", "ornithopod dinosaur"],
    "ornithorhynchidae": ["family ornithorhynchidae", "mammal family"],
    "ornithorhynchus": ["genus ornithorhynchus", "mammal genus"],
    "orobanchaceae": ["broomrape family", "dicot family", "family orobanchaceae", "magnoliopsid family"],
    "orogeny": ["geologic process", "geological process"],
    "oroide": ["alloy", "metal", "oreide"],
    "orology": ["geology", "orography"],
    "orono": [],
    "orontium": ["genus orontium", "liliopsid genus", "monocot genus"],
    "oropharyngeal": [],
    "oropharynx": ["bodily cavity", "cavity", "cavum"],
    "orotund": ["pear-shaped", "rotund", "round"],
    "orozco": ["jose clemente orozco", "jose orozco"],
    "orphan": ["deprive", "divest", "strip"],
    "orphan site": ["superfund site", "toxic site", "toxic waste area"],
    "orphanage": ["condition", "orphanhood"],
    "orphaned": [],
    "orphenadrine": ["muscle relaxant", "norflex"],
    "orpheus": [],
    "orphic": [],
    "orphrey": ["edging"],
    "orpiment": ["mineral"],
    "orpine": ["live-forever", "livelong", "orpin", "sedum", "sedum telephium"],
    "orpington": ["chicken", "gallus gallus"],
    "orr": ["bobby orr", "robert orr"],
    "orrery": ["planetarium"],
    "orrisroot": ["orris", "root"],
    "ortalis": ["bird genus", "genus ortalis"],
    "ortega": ["daniel ortega", "daniel ortega saavedra"],
    "ortega y gasset": ["jose ortega y gasset"],
    "orthicon": ["image orthicon", "television pickup tube", "television-camera tube"],
    "orthilia": ["dilleniid dicot genus", "genus orthilia"],
    "orthochorea": ["chorea"],
    "orthochromatic film": ["film", "photographic film"],
    "orthoclase": ["feldspar", "felspar"],
    "orthodontic": [],
    "orthodontic treatment": ["intervention", "treatment"],
    "orthodontics": ["dental medicine", "dental orthopaedics", "dental orthopedics", "dentistry", "odontology", "orthodontia", "orthodonture"],
    "orthodontist": ["dental practitioner", "dentist", "tooth doctor"],
    "orthodox": ["eastern orthodox", "greek orthodox", "russian orthodox"],
    "orthodox church": ["catholic church", "eastern church", "eastern orthodox", "eastern orthodox church", "greek church", "greek orthodox church", "orthodox catholic church", "russian orthodox church"],
    "orthodox jew": ["chasid", "chassid", "hasid", "hassid", "hebrew", "israelite", "jew", "lubavitcher"],
    "orthodox judaism": ["chasidim", "chassidim", "hasidim", "hasidism", "hassidim", "hebraism", "jewish orthodoxy", "jewish religion", "judaism"],
    "orthodox sleep": ["nonrapid eye movement", "nonrapid eye movement sleep", "nrem", "nrem sleep", "sleep", "slumber"],
    "orthodoxy": ["conformism", "conformity", "orientation"],
    "orthoepist": ["phonologist"],
    "orthoepy": ["phonemics", "phonology"],
    "orthogonal": [],
    "orthogonality": ["opposition", "orthogonal opposition", "perpendicularity"],
    "orthographic": [],
    "orthography": ["alphabetic script", "alphabetic writing", "boustrophedon", "hieroglyph", "hieroglyphic", "ideography", "picture writing", "point system", "script", "spelling", "writing", "writing system"],
    "orthomolecular": [],
    "orthomyxovirus": ["myxovirus"],
    "orthopedic": ["orthopaedic", "orthopedical"],
    "orthopedics": ["medical science", "orthopaedics"],
    "orthopedist": ["medical specialist", "orthopaedist", "specialist"],
    "orthopnea": ["dyspnea", "dyspnoea"],
    "orthopristis": ["fish genus", "genus orthopristis"],
    "orthopter": ["heavier-than-air craft", "ornithopter"],
    "orthoptera": ["animal order", "order orthoptera"],
    "orthopterous insect": ["cricket", "grasshopper", "hopper", "insect", "orthopteran", "orthopteron"],
    "orthoptic": [],
    "orthoptics": ["intervention", "treatment"],
    "orthoptist": ["medical specialist", "specialist"],
    "orthoscope": ["ophthalmoscope"],
    "orthostatic": [],
    "orthostatic hypotension": ["hypotension", "postural hypotension"],
    "orthotomus": ["bird genus", "genus orthotomus"],
    "orthotropous": [],
    "orthotropous ovule": ["ovule"],
    "ortolan": ["bunting", "emberiza hortulana", "ortolan bunting"],
    "ortygan": ["wader", "wading bird"],
    "orwell": ["eric arthur blair", "eric blair", "george orwell"],
    "orwellian": [],
    "orycteropodidae": ["family orycteropodidae", "mammal family"],
    "orycteropus": ["genus orycteropus", "mammal genus"],
    "oryctolagus": ["genus oryctolagus", "mammal genus"],
    "oryx": ["antelope", "gemsbok", "gemsbuck", "oryx gazella", "pasang"],
    "oryza": ["genus oryza", "liliopsid genus", "monocot genus"],
    "oryzomys": ["genus oryzomys", "mammal genus"],
    "oryzopsis": ["genus oryzopsis", "liliopsid genus", "monocot genus"],
    "orzo": ["alimentary paste", "pasta"],
    "os": ["opening", "orifice", "porta"],
    "osage": ["dhegiha"],
    "osage orange": ["angiospermous yellowwood", "bow wood", "maclura pomifera", "mock orange"],
    "osaka": [],
    "osaka bay": [],
    "osasco": [],
    "osborne": ["john james osborne", "john osborne"],
    "oscan": ["italian"],
    "oscan-speaking": [],
    "oscheocele": ["lump", "oscheocoele", "puffiness", "swelling"],
    "oscillate": ["hunt", "librate", "sway", "swing", "vibrate"],
    "oscillation": ["action", "activity", "libration", "natural action", "natural process"],
    "oscillator": ["crystal oscillator", "generator", "heterodyne oscillator", "local oscillator", "quartz oscillator"],
    "oscillatoriaceae": ["bacteria family", "family oscillatoriaceae"],
    "oscillatory": ["oscillating"],
    "oscillogram": ["recording"],
    "oscillograph": ["recorder", "recording equipment", "recording machine"],
    "oscilloscope": ["cathode-ray oscilloscope", "cro", "electronic equipment", "scope"],
    "oscine": ["accentor", "american oriole", "australian magpie", "babbler", "bird of paradise", "blue mockingbird", "bluebird", "bowerbird", "cackler", "catbird", "corvine bird", "creeper", "dipper", "dumetella carolinensis", "fairy bluebird", "finch", "flycatcher", "gray catbird", "grey catbird", "honey eater", "honeycreeper", "honeysucker", "lark", "melanotis caerulescens", "mimus polyglotktos", "mocker", "mocking thrush", "mockingbird", "new world oriole", "new zealand wren", "nutcracker", "nuthatch", "old world flycatcher", "old world oriole", "oriole", "oscine bird", "passeriform bird", "passerine", "pipit", "shrike", "songbird", "songster", "starling", "swallow", "swallow shrike", "tanager", "thrasher", "thrush", "tit", "titlark", "titmouse", "tree creeper", "true flycatcher", "vireo", "wagtail", "warbler", "water ouzel", "waxwing", "weaver", "weaver finch", "weaverbird", "wood swallow"],
    "oscines": ["animal order", "passeres", "suborder oscines", "suborder passeres"],
    "oscitancy": ["drowsiness", "dullness", "obtuseness", "oscitance", "sleepiness", "somnolence"],
    "osco-umbrian": ["italic", "italic language", "oscan", "sabellian", "umbrian"],
    "osculate": ["be"],
    "osculation": ["contact"],
    "osier": ["withe", "withy"],
    "osiris": [],
    "oslo": ["capital of norway", "christiania"],
    "osman i": ["othman i"],
    "osmanthus": ["dicot genus", "genus osmanthus", "magnoliopsid genus"],
    "osmeridae": ["family osmeridae", "fish family"],
    "osmerus": ["fish genus", "genus osmerus"],
    "osmiridium": ["iridosmine", "mineral"],
    "osmium": ["atomic number 76", "metal", "metallic element", "os"],
    "osmoreceptor": ["end organ"],
    "osmosis": ["diffusion", "reverse osmosis"],
    "osmotic": [],
    "osmotic pressure": ["force per unit area", "hypertonicity", "hypotonicity", "pressure", "pressure level"],
    "osmotically": [],
    "osmundaceae": ["family osmundaceae", "fern family"],
    "osprey": ["fish eagle", "fish hawk", "hawk", "pandion haliaetus", "sea eagle"],
    "osseous": ["bony", "osteal"],
    "ossete": ["iranian", "iranian language"],
    "ossicle": ["auditory ossicle", "bone", "bonelet", "os", "ossiculum"],
    "ossicular": ["ossiculate"],
    "ossiferous": [],
    "ossification": ["calcification"],
    "ossify": ["alter", "change", "modify"],
    "osso buco": ["dish"],
    "ossuary": ["receptacle"],
    "ostariophysi": ["malacopterygian", "order ostariophysi", "soft-finned fish"],
    "osteal": [],
    "osteichthyes": ["class", "class osteichthyes"],
    "osteitis": ["inflammation", "osteitis deformans", "osteomyelitis", "paget's disease", "redness", "rubor"],
    "ostensible": ["ostensive"],
    "ostensive": [],
    "ostensive definition": ["definition"],
    "ostentation": ["bluster", "bravado", "display", "exhibitionism", "fanfare", "flash", "pedantry", "ritz", "splurge"],
    "ostentatious": ["pretentious"],
    "ostentatiously": ["showily"],
    "osteoarthritis": ["arthritis", "degenerative arthritis", "degenerative joint disease"],
    "osteoblast": ["bone-forming cell", "embryonic cell", "formative cell"],
    "osteoblastoma": ["benign tumor", "benign tumour", "nonmalignant neoplasm", "nonmalignant tumor", "nonmalignant tumour"],
    "osteochondroma": ["benign tumor", "benign tumour", "nonmalignant neoplasm", "nonmalignant tumor", "nonmalignant tumour"],
    "osteoclasis": ["intervention", "treatment"],
    "osteoclast": ["bone cell"],
    "osteocyte": ["bone cell"],
    "osteodystrophy": ["dystrophy"],
    "osteogenesis imperfecta": ["autosomal dominant disease", "autosomal dominant disorder"],
    "osteoglossidae": ["family osteoglossidae", "fish family"],
    "osteoglossiformes": ["animal order", "order osteoglossiformes"],
    "osteologist": ["anatomist", "osteologer"],
    "osteology": ["anatomy", "general anatomy"],
    "osteolysis": ["lysis"],
    "osteoma": ["benign tumor", "benign tumour", "nonmalignant neoplasm", "nonmalignant tumor", "nonmalignant tumour"],
    "osteomalacia": ["malacia"],
    "osteomyelitis": ["osteitis"],
    "osteopath": ["healer", "osteopathist", "therapist"],
    "osteopathy": ["intervention", "treatment"],
    "osteopetrosis": ["albers-schonberg disease", "congenital disease", "genetic abnormality", "genetic defect", "genetic disease", "genetic disorder", "hereditary condition", "hereditary disease", "inherited disease", "inherited disorder", "marble bones disease"],
    "osteophyte": ["appendage", "outgrowth", "process"],
    "osteoporosis": ["dowager's hump", "pathology"],
    "osteosarcoma": ["osteogenic sarcoma", "sarcoma"],
    "osteosclerosis": ["induration", "sclerosis"],
    "osteostracan": ["agnathan", "cephalaspid", "jawless fish", "jawless vertebrate"],
    "osteostraci": ["animal order", "cephalaspida", "suborder cephalaspida", "suborder osteostraci"],
    "osteotomy": ["operation", "surgery", "surgical operation", "surgical procedure", "surgical process"],
    "ostinato": ["ground bass", "musical phrase", "phrase", "riff"],
    "ostiole": ["pore"],
    "ostomy": ["colostomy", "ileostomy", "operation", "surgery", "surgical operation", "surgical procedure", "surgical process"],
    "ostraciidae": ["family ostraciidae", "family ostraciontidae", "fish family"],
    "ostracism": ["ejection", "exclusion", "expulsion", "riddance"],
    "ostracize": ["boycott", "exclude", "keep out", "ostracise", "shut", "shut out"],
    "ostracoda": ["class", "subclass ostracoda"],
    "ostracoderm": ["agnathan", "jawless fish", "jawless vertebrate"],
    "ostracodermi": ["animal order", "order ostracodermi"],
    "ostrava": [],
    "ostrea": ["genus ostrea", "mollusk genus"],
    "ostreidae": ["family ostreidae", "mollusk family"],
    "ostrich": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "ostrich fern": ["fern", "fiddlehead", "matteuccia struthiopteris", "onoclea struthiopteris", "pteretis struthiopteris", "shuttlecock fern"],
    "ostrogoth": ["goth"],
    "ostrya": ["genus ostrya", "hamamelid dicot genus"],
    "ostryopsis": ["genus ostryopsis", "hamamelid dicot genus"],
    "ostwald": ["wilhelm ostwald"],
    "ostyak": ["khanty", "russian"],
    "oswald": ["lee harvey oswald"],
    "otaheite arrowroot": ["amylum", "otaheite arrowroot starch", "starch"],
    "otaria": ["genus otaria", "mammal genus"],
    "otariidae": ["family otariidae", "mammal family"],
    "othello": [],
    "other": [],
    "otherness": ["difference", "distinctness", "separateness"],
    "otherwise": [],
    "otherworld": ["abstract entity", "abstraction"],
    "othonna": ["bush", "shrub"],
    "otic": ["auricular"],
    "otic ganglion": ["autonomic ganglion", "otoganglion"],
    "otides": ["animal order", "suborder otides"],
    "otididae": ["bird family", "family otididae"],
    "otiose": ["pointless", "purposeless", "senseless", "superfluous", "wasted"],
    "otis": ["elisha graves otis"],
    "otitis": ["inflammation", "labyrinthitis", "otitis externa", "otitis interna", "otitis media", "redness", "rubor"],
    "otitis externa": ["otitis"],
    "otitis media": ["otitis"],
    "oto": ["otoe", "siouan", "sioux"],
    "otology": ["audiology", "audiometry", "medical specialty", "medicine"],
    "otoplasty": ["anaplasty", "plastic surgery", "reconstructive surgery"],
    "otorrhea": ["pathology"],
    "otosclerosis": ["congenital disease", "genetic abnormality", "genetic defect", "genetic disease", "genetic disorder", "hereditary condition", "hereditary disease", "inherited disease", "inherited disorder"],
    "otoscope": ["auriscope", "auroscope", "medical instrument"],
    "ototoxic": [],
    "ottava rima": ["stanza"],
    "ottawa": ["algonquian", "algonquin"],
    "otter": ["fur", "pelt"],
    "otter shrew": ["insectivore", "potamogale", "potamogale velox"],
    "otterhound": ["hound", "hound dog", "otter hound"],
    "otto i": ["otho i", "otto the great"],
    "ottoman": ["osmanli", "ottoman turk", "turk"],
    "ottoman empire": ["turkish empire"],
    "ottumwa": [],
    "otus": ["bird genus", "genus otus"],
    "ouachita": ["ouachita river"],
    "oubliette": ["dungeon"],
    "ouguiya": ["mauritanian monetary unit"],
    "ouija": ["board", "gameboard", "ouija board"],
    "oujda": [],
    "ounce": ["apothecaries' ounce", "apothecaries' unit", "apothecaries' weight", "troy ounce", "troy unit"],
    "our lord's candle": ["yucca", "yucca whipplei"],
    "ouranopithecus": ["genus ouranopithecus", "mammal genus"],
    "ouranos": ["uranus"],
    "ouse": ["ouse river"],
    "oust": ["replace", "supercede", "supersede", "supervene upon", "supplant"],
    "ouster": ["ejector", "individual", "mortal", "person", "somebody", "someone", "soul"],
    "out": ["break", "bring out", "disclose", "discover", "divulge", "expose", "give away", "let on", "let out", "reveal", "unwrap"],
    "out of": [],
    "out of gear": [],
    "out of hand": ["beyond control"],
    "out of place": [],
    "out of play": [],
    "out of practice": ["rusty"],
    "out of print": [],
    "out of sight": ["out of view"],
    "out of stock": [],
    "out of the way": [],
    "out of thin air": ["from nowhere", "out of nothing"],
    "out of true": ["untrue"],
    "out of wedlock": ["outside marriage"]
}
