synonyms = {
    "hindustani": ["hindoostani", "hindostani"],
    "hinge": ["flexible joint"],
    "hinge joint": ["ginglymoid joint", "ginglymus"],
    "hinging post": ["swinging post"],
    "hint": ["suggest"],
    "hip": ["rose hip", "rosehip"],
    "hip boot": ["thigh boot"],
    "hip roof": ["hipped roof"],
    "hip tile": ["hipped tile"],
    "hipbone": ["innominate bone"],
    "hipflask": ["pocket flask"],
    "hippeastrum": ["hippeastrum puniceum"],
    "hippie": ["flower child", "hippy", "hipster"],
    "hippo": ["hippo regius"],
    "hippobosca": ["genus hippobosca"],
    "hippoboscidae": ["family hippoboscidae"],
    "hippocampus": ["genus hippocampus"],
    "hippocastanaceae": ["family hippocastanaceae"],
    "hippocrepis": ["genus hippocrepis"],
    "hippodamia": ["genus hippodamia"],
    "hippoglossoides": ["genus hippoglossoides"],
    "hippoglossus": ["genus hippoglossus"],
    "hippopotamidae": ["family hippopotamidae"],
    "hippopotamus": ["hippo", "hippopotamus amphibius", "river horse"],
    "hipposideridae": ["family hipposideridae"],
    "hipposideros": ["genus hipposideros"],
    "hippotragus": ["genus hippotragus"],
    "hipsurus": ["genus hipsurus"],
    "hire": ["employ", "engage"],
    "hire out": ["farm out", "rent out"],
    "hired hand": ["hand", "hired man"],
    "hireling": ["pensionary"],
    "hirohito": ["michinomiya hirohito"],
    "hirschfeld": ["al hirschfeld"],
    "hirschsprung": ["harold hirschsprung"],
    "hirsuteness": ["hirsutism"],
    "hirudinea": ["class hirudinea"],
    "hirudinidae": ["family hirudinidae"],
    "hirudo": ["genus hirudo"],
    "hirundinidae": ["family hirundinidae"],
    "hirundo": ["genus hirundo"],
    "hispanic": ["latino"],
    "hispaniola": ["haiti", "hayti"],
    "hispid pocket mouse": ["perognathus hispidus"],
    "hiss": ["whoosh"],
    "histamine headache": ["cluster headache"],
    "histological": ["histologic"],
    "historian": ["historiographer"],
    "historic": ["historical"],
    "historic period": ["age"],
    "historical document": ["historical paper", "historical record"],
    "historical linguistics": ["diachronic linguistics", "diachrony"],
    "history": ["account", "chronicle", "story"],
    "history department": ["department of history"],
    "histrionic": ["melodramatic"],
    "hit": ["come to", "strike"],
    "hit home": ["strike a chord", "strike a note", "strike home"],
    "hit the dirt": ["hit the deck"],
    "hitch": ["catch"],
    "hitchcock": ["alfred hitchcock", "alfred joseph hitchcock", "sir alfred hitchcock"],
    "hitchhike": ["hitch", "thumb"],
    "hitchings": ["george herbert hitchings"],
    "hitchrack": ["hitching bar"],
    "hitler": ["adolf hitler", "der fuhrer"],
    "hitter": ["striker"],
    "hizballah": ["hezbollah", "hizbollah", "hizbullah", "islamic jihad", "islamic jihad for the liberation of palestine", "lebanese hizballah", "organization of the oppressed on earth", "party of god", "revolutionary justice organization"],
    "hmong": ["miao"],
    "ho chi minh": ["nguyen tat thanh"],
    "ho chi minh city": ["saigon"],
    "hoagland": ["hudson hoagland"],
    "hoard": ["cache", "hive up", "lay away", "squirrel away", "stash"],
    "hoarsely": ["huskily"],
    "hoary": ["rusty"],
    "hoary alison": ["berteroa incana", "hoary alyssum"],
    "hoary golden bush": ["hazardia cana"],
    "hoary marmot": ["marmota caligata", "whistler", "whistling marmot"],
    "hoary plantain": ["plantago virginica"],
    "hoary puccoon": ["indian paint", "lithospermum canescens"],
    "hoary willow": ["sage willow", "salix candida"],
    "hoatzin": ["hoactzin", "opisthocomus hoazin", "stinkbird"],
    "hoax": ["play a joke on"],
    "hobbes": ["thomas hobbes"],
    "hobbler": ["limper"],
    "hobbs": ["john berry hobbs", "sir jack hobbs"],
    "hobby": ["hobbyhorse", "rocking horse"],
    "hobo camp": ["jungle"],
    "hod carrier": ["hodman"],
    "hodgkin": ["thomas hodgkin"],
    "hoffa": ["james riddle hoffa", "jimmy hoffa"],
    "hoffman": ["malvina hoffman"],
    "hoffmann": ["josef hoffmann"],
    "hoffmannsthal": ["hugo von hoffmannsthal"],
    "hog": ["pig"],
    "hog badger": ["arctonyx collaris", "sand badger"],
    "hog peanut": ["amphicarpa bracteata", "amphicarpaea bracteata", "wild peanut"],
    "hog plum": ["spondias mombin", "yellow mombin", "yellow mombin tree"],
    "hog sucker": ["hog molly", "hypentelium nigricans"],
    "hogan": ["ben hogan", "william benjamin hogan"],
    "hogarth": ["william hogarth"],
    "hogback": ["horseback"],
    "hogchoker": ["trinectes maculatus"],
    "hogfish": ["hog snapper", "lachnolaimus maximus"],
    "hogg": ["james hogg"],
    "hoggish": ["piggish", "piggy", "porcine", "swinish"],
    "hognose bat": ["choeronycteris mexicana"],
    "hognose snake": ["puff adder", "sand viper"],
    "hohenlinden": ["battle of hohenlinden"],
    "hohenzollern empire": ["second reich"],
    "hoheria": ["genus hoheria"],
    "hoist": ["run up"],
    "hokan": ["hoka"],
    "hokkaido": ["ezo", "yezo"],
    "hokusai": ["katsushika hokusai"],
    "holarrhena": ["genus holarrhena"],
    "holbein": ["hans holbein", "holbein the younger"],
    "holbrookia": ["genus holbrookia"],
    "holcus": ["genus holcus"],
    "hold": ["bear", "carry", "contain"],
    "hold forth": ["discourse", "dissertate"],
    "hold on": ["stop"],
    "hold up": ["stick up"],
    "holder": ["bearer"],
    "holding pen": ["holding paddock", "holding yard"],
    "holdover": ["hangover"],
    "holdup man": ["stickup man"],
    "hole": ["hole out"],
    "holey": ["porous"],
    "holiness": ["sanctitude", "sanctity"],
    "holism": ["holistic theory"],
    "holler": ["holler out"],
    "hollerith": ["herman hollerith"],
    "hollow": ["core out", "hollow out"],
    "hollowware": ["holloware"],
    "holly": ["buddy holly", "charles hardin holley"],
    "holly fern": ["cyrtomium aculeatum", "polystichum aculeatum"],
    "holm oak": ["evergreen oak", "holm tree", "quercus ilex"],
    "holmes": ["oliver wendell holmes"],
    "holmium": ["ho"],
    "holocaust": ["final solution"],
    "holocene": ["holocene epoch", "recent", "recent epoch"],
    "holocentridae": ["family holocentridae"],
    "holocentrus": ["genus holocentrus"],
    "holocephalan": ["holocephalian"],
    "holocephali": ["subclass holocephali"],
    "hologram": ["holograph"],
    "holographic": ["holographical"],
    "holometabola": ["metabola"],
    "holometabolic": ["holometabolous"],
    "holometabolism": ["holometaboly"],
    "holonym": ["whole name"],
    "holonymy": ["whole to part relation"],
    "holothuria": ["genus holothuria"],
    "holothuridae": ["family holothuridae"],
    "holothuroidea": ["class holothuroidea"],
    "holy eucharist": ["eucharist", "eucharistic liturgy", "holy sacrament", "liturgy", "sacrament of the eucharist"],
    "holy ghost": ["holy spirit", "paraclete"],
    "holy of holies": ["sanctum sanctorum"],
    "holy order": ["order"],
    "holy place": ["holy", "sanctum"],
    "holy see": ["state of the vatican city", "the holy see"],
    "holy sepulcher": ["holy sepulchre"],
    "holy week": ["passion week"],
    "homaridae": ["family homaridae"],
    "homarus": ["genus homarus"],
    "home": ["place"],
    "home appliance": ["household appliance"],
    "home away from home": ["home from home"],
    "home brew": ["homebrew"],
    "home economics": ["domestic science", "home ec", "household arts"],
    "home loan": ["equity credit line", "home equity credit", "home equity loan"],
    "home page": ["homepage"],
    "home plate": ["home", "home base", "plate"],
    "home range": ["home territory"],
    "home room": ["homeroom"],
    "home secretary": ["secretary of state for the home department"],
    "home theater": ["home theatre"],
    "homebound": ["housebound"],
    "homebuilder": ["housebuilder"],
    "homeless": ["homeless person"],
    "homelike": ["homely", "homey", "homy"],
    "homeliness": ["plainness"],
    "homely": ["plain"],
    "homeobox": ["homeobox gene"],
    "homeopath": ["homoeopath"],
    "homeopathy": ["homoeopathy"],
    "homeotherm": ["homoiotherm", "homotherm"],
    "homeowner": ["householder"],
    "homer": ["kor"],
    "homespun": ["nubbly", "nubby", "slubbed", "tweedy"],
    "homeward": ["homewards"],
    "homework": ["prep", "preparation"],
    "homicidal": ["murderous"],
    "homiletic": ["homiletical"],
    "homily": ["preachment"],
    "homing pigeon": ["homer"],
    "hominian": ["hominid"],
    "hominidae": ["family hominidae"],
    "hominoidea": ["superfamily hominoidea"],
    "homo": ["human", "human being", "man"],
    "homo sapiens sapiens": ["modern man"],
    "homobasidiomycetes": ["subclass homobasidiomycetes"],
    "homocyclic": ["isocyclic"],
    "homogeneity": ["homogeneousness"],
    "homogeneous": ["homogenous"],
    "homogenization": ["homogenisation"],
    "homogenize": ["homogenise"],
    "homogenized": ["homogenised"],
    "homograft": ["allograft"],
    "homogyne": ["genus homogyne"],
    "homoiothermic": ["homeothermic", "homothermic"],
    "homologic": ["homological"],
    "homologize": ["homologise"],
    "homomorphism": ["homomorphy"],
    "homona": ["genus homona"],
    "homonymic": ["homonymous"],
    "homoptera": ["suborder homoptera"],
    "homopterous insect": ["homopteran"],
    "homosexual": ["gay", "homo", "homophile"],
    "homosexuality": ["gayness", "homoeroticism", "homosexualism", "queerness"],
    "homostylous": ["homostyled", "homostylic"],
    "homyel": ["gomel", "homel"],
    "honduras": ["republic of honduras"],
    "honduras mahogany": ["swietinia macrophylla"],
    "honduras rosewood": ["dalbergia stevensonii"],
    "honegger": ["arthur honegger"],
    "honest": ["honorable"],
    "honestly": ["candidly", "frankly"],
    "honesty": ["lunaria annua", "money plant", "satin flower", "satinpod", "silver dollar"],
    "honey bell": ["hermannia verticillata", "honeybells", "mahernia verticillata"],
    "honey bun": ["caramel bun", "schnecken", "sticky bun"],
    "honey buzzard": ["pernis apivorus"],
    "honey eater": ["honeysucker"],
    "honey locust": ["gleditsia triacanthos"],
    "honey mesquite": ["prosopis glandulosa", "western honey mesquite"],
    "honey mushroom": ["armillariella mellea", "honey fungus"],
    "honeybee": ["apis mellifera"],
    "honeycreeper": ["hawaiian honeycreeper"],
    "honeydew": ["honeydew melon"],
    "honeyed": ["honied", "syrupy"],
    "honeyflower": ["lambertia formosa", "mountain devil"],
    "honeypot": ["king protea", "protea cynaroides"],
    "honeysuckle": ["australian honeysuckle", "banksia integrifolia", "coast banksia"],
    "honk": ["beep", "blare", "claxon", "toot"],
    "honker": ["branta canadensis", "canada goose", "canadian goose"],
    "honkytonk": ["dive"],
    "honolulu": ["capital of hawaii", "hawaiian capital"],
    "honor": ["honour", "reward"],
    "honor guard": ["guard of honor"],
    "honorable": ["honourable"],
    "honorableness": ["honourableness"],
    "honorably": ["uprightly"],
    "honorary degree": ["honoris causa"],
    "honoring": ["observance"],
    "honours": ["honours degree"],
    "honshu": ["hondo"],
    "hooch": ["hootch"],
    "hood": ["goon", "hoodlum", "punk", "thug", "tough", "toughie"],
    "hooded merganser": ["hooded sheldrake", "lophodytes cucullatus"],
    "hooded pitcher plant": ["sarracenia minor"],
    "hooded seal": ["bladdernose", "cystophora cristata"],
    "hooded skunk": ["mephitis macroura"],
    "hoofer": ["stepper"],
    "hoofprint": ["hoof mark"],
    "hook": ["cop", "glom", "knock off", "snitch", "thieve"],
    "hook of holland": ["hoek van holland"],
    "hook shot": ["hook"],
    "hook wrench": ["hook spanner"],
    "hookah": ["calean", "chicha", "kalian", "narghile", "nargileh", "sheesha", "shisha", "water pipe"],
    "hooke": ["robert hooke"],
    "hooker": ["fighting joe hooker", "joseph hooker"],
    "hooklike": ["hooked"],
    "hooks": ["maulers", "meat hooks"],
    "hookup": ["assemblage"],
    "hookworm": ["hookworm disease"],
    "hoop": ["ring"],
    "hoop pine": ["araucaria cunninghamii", "moreton bay pine"],
    "hoopoe": ["hoopoo"],
    "hoopskirt": ["crinoline"],
    "hoosegow": ["hoosgow"],
    "hoover": ["william henry hoover", "william hoover"],
    "hop": ["skip"],
    "hop clover": ["lesser yellow trefoil", "shamrock", "trifolium dubium"],
    "hop garden": ["hop field"],
    "hop on": ["bestride", "climb on", "get on", "jump on", "mount", "mount up"],
    "hop out": ["get off"],
    "hope": ["desire", "trust"],
    "hope chest": ["wedding chest"],
    "hopkins": ["mark hopkins"],
    "hopkinson": ["francis hopkinson"],
    "hopple": ["hobble"],
    "hopsacking": ["hopsack"],
    "horatian ode": ["sapphic ode"],
    "horatio hornblower": ["captain horatio hornblower"],
    "horde": ["host", "legion"],
    "hordeum": ["genus hordeum"],
    "horizon": ["celestial horizon"],
    "horizontal bar": ["high bar"],
    "horizontal integration": ["horizontal combination"],
    "horizontal stabilizer": ["horizontal stabiliser", "tailplane"],
    "horizontal surface": ["level"],
    "hormone": ["endocrine", "internal secretion"],
    "hormone replacement therapy": ["hrt"],
    "horn": ["tusk"],
    "horn fly": ["haematobia irritans"],
    "horn of plenty": ["cornucopia"],
    "horn poppy": ["glaucium flavum", "horned poppy", "sea poppy", "yellow horned poppy"],
    "horne": ["marilyn horne"],
    "horned chameleon": ["chamaeleo oweni"],
    "horned lizard": ["horned toad", "horny frog"],
    "horned pondweed": ["zannichellia palustris"],
    "horned pout": ["ameiurus melas", "hornpout", "pout"],
    "horned puffin": ["fratercula corniculata"],
    "horned screamer": ["anhima cornuta"],
    "horned violet": ["tufted pansy", "viola cornuta"],
    "horned viper": ["cerastes", "cerastes cornutus", "horned asp", "sand viper"],
    "horned whiff": ["citharichthys cornutus"],
    "horneophyton": ["genus horneophyton"],
    "horney": ["karen danielsen horney", "karen horney"],
    "hornfels": ["hornstone"],
    "horniness": ["hot pants", "hotness"],
    "hornpipe": ["pibgorn", "stockhorn"],
    "horny structure": ["unguis"],
    "horowitz": ["vladimir horowitz"],
    "horse": ["gymnastic horse"],
    "horse around": ["arse around", "fool", "fool around"],
    "horse balm": ["collinsonia canadensis", "horseweed", "richweed", "stone root", "stoneroot"],
    "horse botfly": ["gasterophilus intestinalis"],
    "horse cassia": ["cassia marginata", "cassia roxburghii"],
    "horse chestnut": ["aesculus hippocastanum", "buckeye"],
    "horse gram": ["dolichos biflorus", "horse grain", "macrotyloma uniflorum"],
    "horse mackerel": ["saurel", "trachurus trachurus"],
    "horse mushroom": ["agaricus arvensis"],
    "horse nettle": ["ball nettle", "ball nightshade", "bull nettle", "solanum carolinense"],
    "horse tick": ["hippobosca equina", "horsefly"],
    "horse trade": ["horse trading"],
    "horse wrangler": ["wrangler"],
    "horseback": ["ahorse", "ahorseback"],
    "horsefly": ["cleg", "clegg", "horse fly"],
    "horsehair lichen": ["horsetail lichen"],
    "horseman": ["equestrian", "horseback rider"],
    "horsemeat": ["horseflesh"],
    "horsemint": ["monarda punctata"],
    "horsepower": ["hp"],
    "horseradish": ["horseradish root"],
    "horseradish sauce": ["sauce albert"],
    "horseshoe": ["shoe"],
    "horseshoe crab": ["king crab", "limulus polyphemus", "xiphosurus polyphemus"],
    "horseshoe vetch": ["hippocrepis comosa"],
    "horseshoe whipsnake": ["coluber hippocrepis"],
    "horseweed": ["canadian fleabane", "conyza canadensis", "erigeron canadensis", "fleabane"],
    "horsy set": ["horsey set"],
    "horta": ["victor horta"],
    "hortensia": ["hydrangea macrophylla hortensis"],
    "horticulturist": ["plantsman"],
    "hose": ["hose down"],
    "hosea": ["book of hosea"],
    "hosiery": ["hose"],
    "hospital": ["infirmary"],
    "hospitalization": ["hospital care", "hospitalisation"],
    "hospitalization insurance": ["hospitalization"],
    "hospitalize": ["hospitalise"],
    "host": ["boniface", "innkeeper"],
    "hosta": ["funka", "genus funka", "genus hosta"],
    "hostaceae": ["family funkaceae", "family hostaceae", "funkaceae"],
    "hostage": ["surety"],
    "hostel": ["auberge", "hostelry", "inn", "lodge"],
    "hostile": ["uncongenial", "unfriendly"],
    "hostilities": ["belligerency"],
    "hostility": ["antagonism", "enmity"],
    "hot": ["raging"],
    "hot flash": ["flush"],
    "hot plate": ["hotplate"],
    "hot pot": ["hotpot"],
    "hot spot": ["hotspot"],
    "hot spring": ["thermal spring"],
    "hot stock": ["hot issue"],
    "hot stuff": ["voluptuousness"],
    "hot toddy": ["toddy"],
    "hotdog": ["hot dog"],
    "hotel detective": ["house detective", "house dick"],
    "hotel plan": ["meal plan"],
    "hotelier": ["hosteller", "hotel manager", "hotelkeeper", "hotelman"],
    "hoth": ["hoder", "hodr", "hodur", "hothr"],
    "hotheaded": ["brainish", "impetuous", "impulsive", "madcap", "tearaway"],
    "hotness": ["heat", "high temperature"],
    "hottentot fig": ["carpobrotus edulis", "mesembryanthemum edule", "sour fig"],
    "hottonia": ["genus hottonia"],
    "houdini": ["erik weisz", "harry houdini"],
    "houghton": ["henry oscar houghton"],
    "hound": ["hunt", "trace"],
    "houndstooth check": ["dogstooth check"],
    "hour": ["time of day"],
    "hour angle": ["ha"],
    "hour hand": ["little hand"],
    "housatonic": ["housatonic river"],
    "house": ["domiciliate", "put up"],
    "house centipede": ["scutigera coleoptrata"],
    "house finch": ["carpodacus mexicanus", "linnet"],
    "house guest": ["houseguest"],
    "house husband": ["househusband"],
    "house martin": ["delichon urbica"],
    "house mouse": ["mus musculus"],
    "house of cards": ["bubble"],
    "house of commons": ["british house of commons"],
    "house of lords": ["british house of lords"],
    "house paint": ["housepaint"],
    "house physician": ["resident", "resident physician"],
    "house wren": ["troglodytes aedon"],
    "housebreaker": ["cat burglar"],
    "housebreaking": ["breaking and entering"],
    "houseclean": ["clean", "clean house"],
    "housefly": ["house fly", "musca domestica"],
    "housewife": ["homemaker", "lady of the house", "woman of the house"],
    "housework": ["housekeeping"],
    "housewrecker": ["housebreaker"],
    "housing": ["living accommodations", "lodging"],
    "housing project": ["public housing"],
    "housman": ["alfred edward housman"],
    "houston": ["sam houston", "samuel houston"],
    "houttuynia": ["genus houttuynia"],
    "hovea": ["purple pea"],
    "hovel": ["hut", "hutch", "shack", "shanty"],
    "hover": ["oscillate", "vacillate", "vibrate"],
    "howard": ["leslie howard", "leslie howard stainer"],
    "howdah": ["houdah"],
    "howe": ["irving howe"],
    "howells": ["william dean howells"],
    "however": ["all the same", "even so", "nevertheless", "nonetheless", "notwithstanding", "still", "withal", "yet"],
    "howl": ["wrawl", "yammer", "yowl"],
    "howler monkey": ["howler"],
    "hoydenish": ["tomboyish"],
    "hoydenism": ["tomboyishness"],
    "hoyle": ["fred hoyle", "sir fred hoyle"],
    "huambo": ["nova lisboa"],
    "huang he": ["hwang ho", "yellow river"],
    "huarache": ["huaraches"],
    "hubbard": ["mount hubbard"],
    "hubbard squash": ["cucurbita maxima"],
    "hubble": ["edwin hubble", "edwin powell hubble"],
    "hubbub": ["brouhaha", "katzenjammer", "uproar"],
    "hubel": ["david hubel"],
    "huck": ["huckaback"],
    "huckleberry finn": ["huck finn"],
    "huckleberry oak": ["quercus vaccinifolia"],
    "huddle": ["cower"],
    "hudson": ["william henry hudson"],
    "hudson bay collared lemming": ["dicrostonyx hudsonius"],
    "hudson river school": ["romantic realism"],
    "hudsonia": ["genus hudsonia"],
    "hudsonian godwit": ["limosa haemastica"],
    "hudud": ["hudood"],
    "hue": ["chromaticity"],
    "huff": ["snort"],
    "huffish": ["sulky"],
    "huffy": ["feisty", "touchy"],
    "hug": ["clinch", "squeeze"],
    "huge": ["brobdingnagian", "immense", "vast"],
    "huggins": ["sir william huggins"],
    "hughes": ["edward james hughes", "ted hughes"],
    "hugo": ["victor hugo"],
    "hugueninia": ["genus hugueninia"],
    "huisache": ["acacia farnesiana", "cassie", "flame tree", "mimosa bush", "scented wattle", "sweet acacia", "sweet wattle"],
    "huitre": ["oyster"],
    "hula": ["hawaiian dancing"],
    "hulking": ["hulky"],
    "hull": ["isaac hull"],
    "hulsea": ["genus hulsea"],
    "hum": ["buzz", "seethe"],
    "human body": ["anatomy", "bod", "build", "chassis", "figure", "flesh", "form", "frame", "material body", "physical body", "physique", "shape", "soma"],
    "human botfly": ["dermatobia hominis"],
    "human chorionic gonadotropin": ["hcg", "human chorionic gonadotrophin"],
    "human immunodeficiency virus": ["hiv"],
    "humanism": ["secular humanism"],
    "humanist": ["humanitarian"],
    "humanistic": ["humanist"],
    "humanistic discipline": ["arts", "humanities", "liberal arts"],
    "humanitarian": ["improver"],
    "humanitarianism": ["humanism"],
    "humanization": ["humanisation"],
    "humanize": ["humanise"],
    "humanness": ["humanity", "manhood"],
    "humble": ["low", "lowly", "modest", "small"],
    "humbleness": ["lowliness", "obscureness", "unimportance"],
    "humbly": ["meekly"],
    "humboldt": ["baron karl wilhelm von humboldt", "baron wilhelm von humboldt"],
    "humbug": ["snake oil"],
    "humdrum": ["monotonous"],
    "hume": ["david hume"],
    "humeral veil": ["veil"],
    "humidify": ["moisturise", "moisturize"],
    "humidity": ["humidness"],
    "humiliate": ["abase", "chagrin", "humble", "mortify"],
    "humiliatingly": ["demeaningly"],
    "humiliation": ["mortification"],
    "humility": ["humbleness"],
    "hummus": ["hommos", "hoummos", "humous", "humus"],
    "humongous": ["banging", "thumping", "walloping", "whopping"],
    "humor": ["humour"],
    "humorist": ["humourist"],
    "humorless": ["humourless", "unhumorous"]
}
