synonyms = {
    "fiji dollar": ["dollar"],
    "fiji islands": ["fijis"],
    "fijian": ["polynesian"],
    "filaggrin": ["protein"],
    "filament": ["stalk", "stem"],
    "filamentous": ["filamentlike", "filiform", "threadlike", "thready"],
    "filar": [],
    "filaria": ["nematode", "nematode worm", "roundworm"],
    "filarial": [],
    "filariasis": ["disease"],
    "filariid": [],
    "filariidae": ["family filariidae", "worm family"],
    "filature": ["bobbin", "reel", "spool"],
    "file": ["march", "process"],
    "file allocation table": ["table", "tabular array"],
    "file clerk": ["clerk", "filer", "filing clerk"],
    "file folder": ["folder"],
    "file in": ["come in", "enter", "get in", "get into", "go in", "go into", "move into"],
    "file out": ["exit", "get out", "go out", "leave"],
    "file server": ["dedicated file server", "digital computer", "non-dedicated file server"],
    "file system": ["classification system", "filing system"],
    "file transfer protocol": ["anonymous file transfer protocol", "anonymous ftp", "communications protocol", "ftp", "protocol"],
    "file-like": [],
    "filefish": ["leatherfish", "leatherjacket", "plectognath", "plectognath fish"],
    "filename": ["computer file name", "computer filename", "file name", "name"],
    "filer": ["litigant", "litigator"],
    "filet": ["lace"],
    "filet mignon": ["filet", "fillet"],
    "filial": [],
    "filial duty": ["duty", "obedience", "obligation", "respect", "responsibility"],
    "filial love": ["love"],
    "filiate": ["determine", "set"],
    "filibuster": ["block", "blockade", "embarrass", "hinder", "obstruct", "stymie", "stymy"],
    "filicales": ["order filicales", "order polypodiales", "plant order", "polypodiales"],
    "filicide": ["parent"],
    "filicopsida": ["class", "class filicinae", "class filicopsida", "filicinae"],
    "filigree": ["craft"],
    "filing": ["fragment", "metal filing"],
    "filipino": ["aboriginal", "aborigine", "bisayan", "indigen", "indigene", "moro", "native", "tagalog", "visayan"],
    "fill": ["do work", "occupy", "take", "work"],
    "fill in": ["inform"],
    "fill up": ["eat", "fill"],
    "filled": [],
    "filler": ["mastic", "putty", "sealing material", "size", "sizing", "stiffener"],
    "fillet": ["adorn", "beautify", "decorate", "embellish", "filet", "grace", "ornament"],
    "filling": ["cement", "fill", "material", "stuff"],
    "fillmore": ["millard fillmore", "president fillmore"],
    "filly": ["female", "foal"],
    "film": ["cinematise", "cinematize", "create", "enter", "make", "microfilm", "put down", "record"],
    "film advance": ["mechanism"],
    "film clip": ["film", "photographic film"],
    "film company": ["company", "indie"],
    "film director": ["director", "film maker", "film producer", "filmmaker", "movie maker"],
    "film editing": ["creating by removal", "cutting"],
    "film festival": ["festival", "fete"],
    "film industry": ["bollywood", "filmdom", "hollywood", "industry", "movie industry", "screen", "screenland"],
    "film maker": ["auteur", "director", "film director", "film producer", "filmmaker", "movie maker", "new waver", "producer"],
    "film noir": ["film", "flick", "motion picture", "motion-picture show", "movie", "moving picture", "moving-picture show", "pic", "picture", "picture show"],
    "film over": ["blur", "glaze over"],
    "film star": ["lead", "movie actor", "movie star", "principal", "screen actor", "star"],
    "film-make": ["create", "make"],
    "filmable": [],
    "filmdom": ["film industry", "movie industry", "screen", "screenland"],
    "filmed": [],
    "filming": ["animation", "cinematography", "motion-picture photography", "photography", "picture taking", "take"],
    "filmy fern": ["fern", "film fern"],
    "filoviridae": ["family"],
    "filovirus": ["animal virus", "ebola virus", "marburg virus"],
    "fils": ["fractional monetary unit", "subunit"],
    "filter": ["filter out", "filtrate", "separate", "separate out", "strain"],
    "filter bed": ["filter"],
    "filter paper": ["paper"],
    "filter tip": ["air cleaner", "air filter"],
    "filter-tipped": [],
    "filter-tipped cigarette": ["butt", "cigaret", "cigarette", "coffin nail", "fag"],
    "filth": ["crud", "skank", "waste", "waste material", "waste matter", "waste product"],
    "filthiness": ["nefariousness", "ugliness", "vileness", "wickedness"],
    "filthy": ["foul", "nasty"],
    "filthy lucre": ["earnings", "lucre", "net", "net income", "net profit", "profit", "profits"],
    "filtrate": ["fluid", "percolate", "product"],
    "filtration": ["action", "activity", "infiltration", "natural action", "natural process", "percolation"],
    "filtration surgery": ["eye operation", "eye surgery"],
    "fimbria": ["appendage", "outgrowth", "process"],
    "fimbriate": [],
    "fin": ["equip", "fit", "fit out", "outfit"],
    "fin de siecle": [],
    "fin keel": ["centerboard", "centreboard", "drop keel", "plate", "sliding keel"],
    "finable": ["fineable"],
    "finagler": ["beguiler", "cheat", "cheater", "deceiver", "slicker", "trickster", "wangler"],
    "final": ["cup final", "match"],
    "final cause": ["aim", "design", "intent", "intention", "purpose"],
    "final cut": ["film", "flick", "motion picture", "motion-picture show", "movie", "moving picture", "moving-picture show", "pic", "picture", "picture show"],
    "final examination": ["exam", "examination", "final", "final exam", "test"],
    "final judgment": ["acquittal", "condemnation", "conviction", "final decision", "judgement", "judgment", "judgment of conviction", "judicial decision", "sentence"],
    "final period": ["division", "part", "section"],
    "finale": ["close", "closing", "coda", "conclusion", "end", "ending"],
    "finalist": ["challenger", "competition", "competitor", "contender", "rival"],
    "finality": ["conclusiveness", "decisiveness", "definiteness", "determinateness"],
    "finalization": ["closing", "completion", "culmination", "finalisation", "mop up", "windup"],
    "finalize": ["end", "finalise", "nail down", "settle", "terminate"],
    "finally": ["eventually"],
    "finance": ["credit"],
    "finance committee": ["commission", "committee"],
    "finance company": ["captive finance company", "commercial credit company", "commercial finance company", "consumer finance company", "nondepository financial institution", "sales finance company", "small loan company"],
    "finance minister": ["government minister", "minister", "minister of finance"],
    "financial analyst": ["analyst", "securities analyst"],
    "financial audit": ["attestation report", "attestation service", "audit", "audited account"],
    "financial center": ["center", "centre", "eye", "heart", "middle"],
    "financial condition": ["condition", "credit crunch", "easy money", "impoverishment", "insolvency", "liquidity crisis", "poorness", "poverty", "solvency", "squeeze", "status", "tight money", "wealth", "wealthiness"],
    "financial crimes enforcement network": ["fincen", "law enforcement agency"],
    "financial forecast": ["forecast", "prognosis"],
    "financial gain": ["capital gain", "gain", "income", "profits", "unearned increment", "win", "winnings"],
    "financial institution": ["acquirer", "bank", "banking company", "banking concern", "central bank", "clearing house", "depository financial institution", "establishment", "federal home loan bank system", "financial organisation", "financial organization", "foundation", "giro", "institution", "lending institution", "nondepository financial institution", "trust company", "trust corporation"],
    "financial loss": ["capital loss", "default", "depreciation", "losings", "loss", "losses", "nonpayment", "nonremittal", "wear and tear"],
    "financial management service": ["agency", "authority", "bureau", "federal agency", "government agency", "office"],
    "financially": [],
    "financier": ["operate", "run"],
    "financing": ["finance", "funding"],
    "finback": ["balaenoptera physalus", "common rorqual", "fin whale", "finback whale", "razorback", "rorqual"],
    "finch": ["brambling", "bullfinch", "bunting", "canary", "canary bird", "cardinal", "cardinal grosbeak", "cardinalis cardinalis", "carduelis cannabina", "carduelis carduelis", "carduelis cucullata", "carduelis flammea", "carduelis hornemanni", "carduelis spinus", "carpodacus mexicanus", "carpodacus purpureus", "chaffinch", "crossbill", "fringilla coelebs", "fringilla montifringilla", "goldfinch", "grosbeak", "grossbeak", "hawaiian honeycreeper", "honeycreeper", "house finch", "junco", "linnet", "lintwhite", "loxia curvirostra", "new world goldfinch", "new world sparrow", "oscine", "oscine bird", "pine finch", "pine siskin", "purple finch", "pyrrhula pyrrhula", "pyrrhuloxia", "pyrrhuloxia sinuata", "red siskin", "redbird", "redpoll", "richmondena cardinalis", "serin", "siskin", "snowbird", "spinus pinus", "spinus tristis", "towhee", "yellowbird"],
    "find": ["acquire", "attain", "chance on", "chance upon", "come across", "come upon", "discover", "fall upon", "feel", "get", "happen upon", "light upon", "locate", "regain", "rout out", "rout up", "strike", "turn up"],
    "find oneself": ["find", "grow", "maturate", "mature"],
    "find out": ["catch out", "detect", "discover", "find", "notice", "observe"],
    "finder": ["quester", "searcher", "seeker"],
    "finder's fee": ["fee"],
    "finding": ["object", "physical object"],
    "finding of law": ["conclusion of law", "finding"],
    "findings": ["accumulation", "aggregation", "assemblage", "collection"],
    "fine": ["amercement", "library fine", "mulct", "penalty"],
    "fine arts": ["architecture", "arts", "beaux arts", "carving", "humanistic discipline", "humanities", "liberal arts", "painting", "sculpture"],
    "fine print": ["qualification", "reservation", "small print"],
    "fine spray": ["downfall", "precipitation"],
    "fine structure": ["spectrum line"],
    "fine-leaved": ["fine-leafed"],
    "fine-looking": ["better-looking", "good-looking", "handsome", "well-favored", "well-favoured"],
    "fine-textured": ["smooth-textured"],
    "fine-tooth comb": ["comb", "fine-toothed comb"],
    "fine-toothed": ["fine-tooth"],
    "fine-tune": ["tune", "tune up", "tweak"],
    "finedraw": ["run up", "sew", "sew together", "stitch"],
    "finely": [],
    "fineness": ["narrowness", "thinness"],
    "finer": [],
    "finery": ["attire", "dress", "garb", "sunday best", "sunday clothes"],
    "fines herbes": ["herb"],
    "finespun": ["delicate"],
    "fingal's cave": [],
    "finger": ["look for", "search", "seek"],
    "finger bowl": ["bowl"],
    "finger food": ["aliment", "alimentation", "nourishment", "nutriment", "nutrition", "sustenance", "victuals"],
    "finger grass": ["chloris gayana", "chloris truncata", "creeping windmill grass", "grass", "rhodes grass", "star grass", "windmill grass"],
    "finger hole": ["hole"],
    "finger lakes": [],
    "finger millet": ["african millet", "coracan", "corakan", "eleusine coracana", "kurakkan", "millet", "ragee", "ragi"],
    "finger paint": ["fingerpaint", "paint", "pigment"],
    "finger plate": ["escutcheon", "protection", "protective cover", "protective covering", "scutcheon"],
    "finger scan": ["biometric authentication", "biometric identification", "finger scanning", "identity verification"],
    "finger spelling": ["fingerspelling", "sign language", "signing"],
    "finger wave": ["wave"],
    "finger-paint": ["paint"],
    "finger-painting": ["painting", "picture"],
    "finger-pointing": ["fingerpointing", "imputation"],
    "finger-roll": ["basketball shot"],
    "fingerboard": ["strip"],
    "fingered": [],
    "fingering": ["emplacement", "locating", "location", "placement", "position", "positioning"],
    "fingerless": [],
    "fingerling": ["fish"],
    "fingermark": ["blot", "daub", "fingerprint", "slur", "smear", "smirch", "smudge", "spot"],
    "fingernail": ["nail", "thumbnail"],
    "fingerpost": ["fingerboard", "guidepost", "signpost"],
    "fingerprint": ["reproduce"],
    "fingerprint expert": ["fingerprint man", "fingerprint specialist", "specialiser", "specialist", "specializer"],
    "fingerprinting": ["procedure", "process"],
    "fingerspell": ["communicate", "finger-spell", "intercommunicate"],
    "fingerstall": ["cot", "sheath"],
    "fingertip": ["tip"],
    "finial": ["decoration", "ornament", "ornamentation"],
    "finical": ["finicky", "fussy", "particular", "picky"],
    "finish": ["broom", "coat", "dress", "surface"],
    "finish coat": ["coat of paint", "finishing coat"],
    "finish up": ["act", "end up", "fetch up", "finish", "land up", "move", "wind up"],
    "finished": [],
    "finisher": ["automobile driver", "race driver", "racer"],
    "finishing line": ["destination", "finish", "finish line", "goal", "line", "tape", "wire"],
    "finishing school": ["school"],
    "finishing touch": ["capstone", "copestone", "touch"],
    "finite": [],
    "finitely": [],
    "finiteness": ["boundedness", "finitude", "quality"],
    "fink": ["blackleg", "do work", "rat", "scab", "work"],
    "finland": ["republic of finland", "suomi"],
    "finn": ["european"],
    "finnan haddie": ["finnan", "finnan haddock", "haddock", "smoked haddock"],
    "finnbogadottir": ["vigdis finnbogadottir"],
    "finnish": ["baltic-finnic", "suomi"],
    "finnish monetary unit": ["finnish mark", "markka", "monetary unit", "penni"],
    "finno-ugric": ["fennic", "finnic", "finno-ugrian", "non-ugric", "ugrian", "ugric", "uralic", "uralic language"],
    "finno-ugric-speaking": [],
    "fipple": ["plug", "stopper", "stopple"],
    "fipple flute": ["fipple pipe", "flageolet", "pennywhistle", "pipe", "recorder", "shepherd's pipe", "tin whistle", "treble recorder", "vertical flute", "whistle"],
    "fir": ["douglas fir", "wood"],
    "fir clubmoss": ["club moss", "club-moss", "little clubmoss", "lycopod", "lycopodium selago", "mountain clubmoss"],
    "fir cone": ["cone", "strobile", "strobilus"],
    "fire": ["chase away", "dispel", "drive away", "drive off", "drive out", "run off", "turn back"],
    "fire alarm": ["alarm", "alarum", "alert", "warning signal"],
    "fire and brimstone": ["damnation", "eternal damnation"],
    "fire ant": ["ant", "emmet", "pismire"],
    "fire bell": ["bell"],
    "fire blight": ["blight canker", "leaf blight", "pear blight"],
    "fire brigade": ["fire company", "organisation", "organization"],
    "fire chief": ["fire fighter", "fire marshal", "fire-eater", "firefighter", "fireman"],
    "fire code": ["code", "codification"],
    "fire control": ["preparation", "readying"],
    "fire control radar": ["naval radar"],
    "fire control system": ["naval weaponry"],
    "fire department": ["department of local government", "fire brigade", "local department"],
    "fire door": ["door"],
    "fire drill": ["drill", "exercise", "practice", "practice session", "recitation"],
    "fire engine": ["aerial ladder truck", "fire truck", "ladder truck", "motortruck", "truck"],
    "fire escape": ["emergency exit", "staircase", "stairway"],
    "fire extinguisher": ["asphyxiator", "device", "extinguisher"],
    "fire hose": ["hose", "hosepipe"],
    "fire insurance": ["insurance"],
    "fire iron": ["coal tongs", "fire hook", "fire tongs", "implement", "poker", "salamander", "shovel", "stove poker"],
    "fire marshall": ["functionary", "official"],
    "fire opal": ["girasol", "opal"],
    "fire pink": ["campion", "catchfly", "silene", "silene virginica"],
    "fire pit": ["cavity", "pit"],
    "fire sale": ["cut-rate sale", "sale", "sales event"],
    "fire screen": ["fireguard", "screen"],
    "fire ship": ["arm", "weapon", "weapon system"],
    "fire station": ["firehouse", "station"],
    "fire tongs": ["coal tongs", "fire iron", "pair of tongs", "tongs"],
    "fire tower": ["watchtower"],
    "fire trench": ["trench"],
    "fire walker": ["performer", "performing artist"],
    "fire walking": ["ceremonial", "ceremonial occasion", "ceremony", "observance"],
    "fire warden": ["coyote", "fire fighter", "fire-eater", "firefighter", "fireman", "forest fire fighter", "functionary", "official", "ranger"],
    "fire watcher": ["security guard", "watcher", "watchman"],
    "fire watching": ["civil defense"],
    "fire-bellied toad": ["anuran", "batrachian", "bombina bombina", "frog", "salientian", "toad", "toad frog"],
    "fire-eater": ["churl", "crank", "crosspatch", "grouch", "grump", "hothead"],
    "fire-on-the-mountain": ["euphorbia cyathophora", "mexican fire plant", "painted leaf", "spurge"],
    "fire-retardant": ["fire-resistant", "fire-resisting", "fire-resistive"],
    "firearm": [".22", "autoloader", "gun", "handgun", "muzzle loader", "piece", "pistol", "repeater", "repeating firearm", "rifle", "riot gun", "scattergun", "self-loader", "shooting iron", "shotgun", "side arm", "small-arm", "smoothbore", "twenty-two"],
    "fireball": ["ball", "globe", "orb"],
    "firebase": ["base", "base of operations"],
    "fireboat": ["boat"],
    "firebomb": ["bomb", "bombard"],
    "firebox": ["furnace"],
    "firebrat": ["bristletail", "thermobia domestica"],
    "firebreak": ["field", "fireguard"],
    "firebrick": ["brick"],
    "firebug": ["heteropterous insect"],
    "fireclay": ["clay"],
    "firecracker": ["banger", "cannon cracker", "cherry bomb", "cracker", "firework", "pyrotechnic", "whizbang", "whizzbang"],
    "firedamp": ["gas"],
    "firefly": ["elater", "elaterid", "elaterid beetle", "fire beetle", "pyrophorus noctiluca"],
    "firelight": ["light", "visible light", "visible radiation"],
    "firelighter": ["igniter", "ignitor", "lighter"],
    "fireman": ["defender", "fire chief", "fire fighter", "fire marshal", "fire warden", "fire-eater", "firefighter", "forest fire fighter", "guardian", "protector", "ranger", "shielder"],
    "fireman's ax": ["ax", "axe", "fireman's axe"],
    "fireman's carry": ["carry"],
    "firenze": ["florence"],
    "fireplace": ["fire", "hearth", "niche", "open fireplace", "recess"],
    "fireplug": ["fire hydrant", "hydrant", "plug"],
    "firepower": ["military capability", "military posture", "military strength", "posture", "strength"],
    "fireproof": ["proof"],
    "firestone": ["flint"],
    "firestorm": ["storm", "violent storm"],
    "firetrap": ["building", "edifice"],
    "firewall": ["security system"],
    "firewater": ["booze", "hard drink", "hard liquor", "john barleycorn", "liquor", "spirits", "strong drink"],
    "fireweed": ["epilobium angustifolium", "giant willowherb", "rosebay willowherb", "wickup", "willowherb"],
    "firewood": ["backlog", "brand", "cordwood", "firebrand", "fuel", "pine knot"],
    "firework": ["banger", "catherine wheel", "cracker", "firecracker", "fizgig", "low explosive", "maroon", "pinwheel", "pyrotechnic", "rocket", "roman candle", "serpent", "skyrocket", "sparkler", "squib", "torpedo"],
    "firing chamber": ["chamber", "gun chamber"],
    "firing line": ["line"],
    "firing pin": ["striker"],
    "firing range": ["practice range", "rocket range", "shooting gallery", "shooting range", "target range"],
    "firing squad": ["firing party", "squad"],
    "firkin": ["british capacity unit", "imperial capacity unit"],
    "firm": ["accounting firm", "auction house", "business", "business concern", "business firm", "business organisation", "business organization", "concern", "consulting company", "consulting firm", "corp", "corporation", "dealer", "house", "law firm", "publisher", "publishing company", "publishing firm", "publishing house"],
    "firm omelet": ["french omelet", "omelet", "omelette", "western omelet"],
    "firm up": ["arrange", "fix up"],
    "firmamental": [],
    "firmer chisel": ["chisel"],
    "firmiana": ["dilleniid dicot genus", "genus firmiana"],
    "firmness": ["soundness", "strength"],
    "firmware": ["code", "computer code", "microcode"],
    "first": ["former", "number one", "rank"],
    "first aid": ["aid", "attention", "care", "tending"],
    "first amendment": [],
    "first and last": ["above all"],
    "first base": ["bag", "base"],
    "first baseman": ["first sacker", "infielder"],
    "first blush": ["belief", "feeling", "impression", "notion", "opinion"],
    "first cause": ["causal agency", "causal agent", "cause", "prime mover", "primum mobile"],
    "first class": ["1st class", "1st-class mail", "correspondence", "first-class mail", "mail"],
    "first crusade": [],
    "first degree": ["degree"],
    "first epistle of john": ["i john"],
    "first epistle of paul the apostle to the corinthians": ["first epistle to the corinthians", "i corinthians"],
    "first epistle of paul the apostle to the thessalonians": ["first epistle to the thessalonians", "i thessalonians"],
    "first epistle of paul the apostle to timothy": ["first epistle to timothy", "i timothy"],
    "first epistle of peter": ["i peter"],
    "first estate": ["estate", "estate of the realm", "lords spiritual", "the three estates"],
    "first gear": ["first", "gear", "gear mechanism", "low", "low gear"],
    "first half": ["half"],
    "first in first out": ["fifo", "inventory accounting"],
    "first lady": ["achiever", "succeeder", "success", "winner"],
    "first lateran council": ["lateran council"],
    "first law of motion": ["law of motion", "newton's first law", "newton's first law of motion", "newton's law", "newton's law of motion"],
    "first lieutenant": ["1st lieutenant", "lieutenant"],
    "first mortgage": ["mortgage"],
    "first name": ["baptismal name", "christian name", "forename", "given name", "name", "praenomen"],
    "first of october antifascist resistance group": ["grapo"],
    "first offender": ["convict"],
    "first period": ["division", "part", "section"],
    "first person": ["person"],
    "first quarter": ["half-moon"],
    "first reading": ["presentation"],
    "first sergeant": ["orderly sergeant", "sergeant", "sergeant first class"],
    "first step": ["beginning", "commencement", "curtain raiser", "first base", "initiative", "opening", "opening move", "peace initiative", "start"],
    "first strike": ["strike"],
    "first trimester": ["trimester"],
    "first vatican council": ["vatican council", "vatican i"],
    "first water": ["high quality", "superiority"],
    "first-aid kit": ["kit", "outfit"],
    "first-aid station": ["aid station", "dressing station", "station"],
    "first-come-first-serve": ["rush"],
    "first-degree burn": ["burn", "erythema solare", "sunburn"],
    "first-nighter": ["playgoer", "theatergoer", "theatregoer"],
    "first-order correlation": ["partial correlation"],
    "first-place finish": ["win"],
    "first-rate": ["very well"],
    "first-rater": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "first-string": [],
    "firstborn": ["eldest", "issue", "offspring", "progeny"],
    "firsthand": ["at first hand"],
    "firth": ["j. r. firth", "john rupert firth"],
    "firth of clyde": [],
    "firth of forth": [],
    "fisc": ["exchequer", "treasury"],
    "fiscal": ["financial"],
    "fiscal policy": ["economic policy"],
    "fiscal year": ["financial year", "twelvemonth", "year", "yr"],
    "fiscally": ["in fiscal matters"],
    "fischer": ["hans fischer"],
    "fischer's slime mushroom": ["slime mushroom"],
    "fish": ["angle", "look for", "search", "seek"],
    "fish and chips": ["dish"],
    "fish cake": ["cake", "codfish ball", "codfish cake", "fish ball", "patty"],
    "fish chowder": ["chowder"],
    "fish doctor": ["eelpout", "gymnelis viridis", "pout"],
    "fish family": ["acanthuridae", "acipenseridae", "agonidae", "albulidae", "alopiidae", "ameiuridae", "amiidae", "ammodytidae", "anabantidae", "anarhichadidae", "anguillidae", "anomalopidae", "antennariidae", "apogonidae", "argentinidae", "ariidae", "atherinidae", "aulostomidae", "balistidae", "batrachoididae", "belonidae", "blenniidae", "bothidae", "bramidae", "branchiostegidae", "brotulidae", "callionymidae", "caproidae", "carangidae", "carapidae", "carcharhinidae", "carchariidae", "catostomidae", "centrarchidae", "centriscidae", "centropomidae", "ceratodontidae", "cetorhinidae", "chaetodontidae", "characidae", "characinidae", "chimaeridae", "chlorophthalmidae", "cichlidae", "clinidae", "clupeidae", "cobitidae", "congridae", "coregonidae", "coryphaenidae", "cottidae", "cyclopteridae", "cynoglossidae", "cyprinidae", "cyprinodontidae", "dactylopteridae", "dactyloscopidae", "dasyatidae", "diodontidae", "echeneididae", "electrophoridae", "eleotridae", "elopidae", "embiotocidae", "engraulidae", "ephippidae", "esocidae", "exocoetidae", "family", "family acanthuridae", "family acipenseridae", "family agonidae", "family albulidae", "family alopiidae", "family ameiuridae", "family amiidae", "family ammodytidae", "family anabantidae", "family anarhichadidae", "family anguillidae", "family anomalopidae", "family antennariidae", "family apogonidae", "family argentinidae", "family ariidae", "family atherinidae", "family aulostomidae", "family balistidae", "family batrachoididae", "family belonidae", "family blenniidae", "family bothidae", "family bramidae", "family branchiostegidae", "family brotulidae", "family callionymidae", "family caproidae", "family carangidae", "family carapidae", "family carcharhinidae", "family carchariidae", "family catostomidae", "family centrarchidae", "family centriscidae", "family centropomidae", "family ceratodontidae", "family cetorhinidae", "family chaetodontidae", "family characidae", "family characinidae", "family chimaeridae", "family chlorophthalmidae", "family cichlidae", "family clinidae", "family clupeidae", "family cobitidae", "family congridae", "family coregonidae", "family coryphaenidae", "family cottidae", "family cyclopteridae", "family cynoglossidae", "family cyprinidae", "family cyprinodontidae", "family dactylopteridae", "family dactyloscopidae", "family dasyatidae", "family diodontidae", "family echeneidae", "family echeneididae", "family electrophoridae", "family eleotridae", "family elopidae", "family embiotocidae", "family engraulidae", "family ephippidae", "family esocidae", "family exocoetidae", "family fistulariidae", "family gadidae", "family gasterosteidae", "family gempylidae", "family gerreidae", "family gerridae", "family gobiesocidae", "family gobiidae", "family gonorhynchidae", "family haemulidae", "family hemiramphidae", "family hexagrammidae", "family hexanchidae", "family holocentridae", "family istiophoridae", "family isuridae", "family kasuwonidae", "family kyphosidae", "family labridae", "family lamnidae", "family lampridae", "family laricariidae", "family latimeridae", "family lepisosteidae", "family liparidae", "family liparididae", "family lobotidae", "family lophiidae", "family lutjanidae", "family luvaridae", "family macrorhamphosidae", "family macrouridae", "family macruridae", "family malacanthidae", "family microdesmidae", "family mobulidae", "family molidae", "family monocanthidae", "family mugilidae", "family mullidae", "family muraenidae", "family myctophidae", "family myliobatidae", "family myxinidae", "family odontaspididae", "family ogcocephalidae", "family ophidiidae", "family ophiodontidae", "family opisthognathidae", "family orectolobidae", "family osmeridae", "family osteoglossidae", "family ostraciidae", "family ostraciontidae", "family pempheridae", "family percidae", "family percophidae", "family petromyzontidae", "family pholidae", "family pholididae", "family platycephalidae", "family pleuronectidae", "family poeciliidae", "family polynemidae", "family polyodontidae", "family pomacentridae", "family pomatomidae", "family priacanthidae", "family pristidae", "family rachycentridae", "family rajidae", "family regalecidae", "family rhincodontidae", "family rhinobatidae", "family salmonidae", "family scaridae", "family sciaenidae", "family scomberesocidae", "family scombresocidae", "family scombridae", "family scorpaenidae", "family scyliorhinidae", "family serranidae", "family sillaginidae", "family siluridae", "family soleidae", "family sparidae", "family sphyraenidae", "family sphyrnidae", "family squalidae", "family squatinidae", "family stichaeidae", "family stromateidae", "family syngnathidae", "family synodontidae", "family tetraodontidae", "family torpedinidae", "family toxotidae", "family trachipteridae", "family triakidae", "family trichiuridae", "family trichodontidae", "family triglidae", "family uranoscopidae", "family xiphiidae", "family zeidae", "family zoarcidae", "fistulariidae", "gadidae", "gasterosteidae", "gempylidae", "gerreidae", "gerridae", "gobiesocidae", "gobiidae", "gonorhynchidae", "haemulidae", "hemiramphidae", "hexagrammidae", "hexanchidae", "holocentridae", "istiophoridae", "isuridae", "katsuwonidae", "kyphosidae", "labridae", "lamnidae", "lampridae", "laricariidae", "latimeridae", "lepisosteidae", "liparidae", "liparididae", "lobotidae", "lophiidae", "lutjanidae", "luvaridae", "macrorhamphosidae", "macrouridae", "macruridae", "malacanthidae", "microdesmidae", "mobulidae", "molidae", "monocanthidae", "mugilidae", "mullidae", "muraenidae", "myctophidae", "myliobatidae", "myxinidae", "odontaspididae", "ogcocephalidae", "ophidiidae", "ophiodontidae", "opisthognathidae", "orectolobidae", "osmeridae", "osteoglossidae", "ostraciidae", "pempheridae", "percidae", "percophidae", "peristediinae", "petromyzontidae", "pholidae", "platycephalidae", "pleuronectidae", "poeciliidae", "polynemidae", "polyodontidae", "pomacentridae", "pomatomidae", "priacanthidae", "pristidae", "rachycentridae", "rajidae", "regalecidae", "rhincodontidae", "rhinobatidae", "salmonidae", "scaridae", "sciaenidae", "scomberesocidae", "scombresocidae", "scombridae", "scorpaenidae", "scyliorhinidae", "serranidae", "sillaginidae", "siluridae", "soleidae", "sparidae", "sphyraenidae", "sphyrnidae", "squalidae", "squatinidae", "stichaeidae", "stromateidae", "subfamily peristediinae", "subfamily triglinae", "syngnathidae", "synodontidae", "tetraodontidae", "torpedinidae", "toxotidae", "trachipteridae", "triakidae", "trichiuridae", "trichodontidae", "triglidae", "triglinae", "uranoscopidae", "xiphiidae", "zeidae", "zoarcidae"],
    "fish farm": ["work", "workplace"],
    "fish fly": ["fish-fly", "neuropteran", "neuropteron", "neuropterous insect"],
    "fish fry": ["cookout"],
    "fish genus": ["abramis", "abudefduf", "acanthocybium", "acanthurus", "achoerodus", "acipenser", "aetobatus", "agonus", "albula", "alectis", "alepisaurus", "alopius", "alosa", "ambloplites", "ameiurus", "amia", "ammodytes", "amphiprion", "anabas", "anarhichas", "anguilla", "anisotremus", "antigonia", "apogon", "archosargus", "argentina", "ariomma", "arius", "aspidophoroides", "astropogon", "atherinopsis", "aulostomus", "bairdiella", "balistes", "blennius", "brama", "brevoortia", "brosmius", "calamus", "capros", "caranx", "carassius", "carcharhinus", "carcharias", "carcharodon", "catostomus", "centropomus", "centropristis", "cetorhinus", "chaenopsis", "chaetodipterus", "chilomycterus", "chrysophrys", "citharichthys", "clupea", "coregonus", "cosmocampus", "cottus", "cryptacanthodes", "cyclopterus", "cynoscion", "cyprinus", "dactylopterus", "dasyatis", "decapterus", "diodon", "echeneis", "elagatis", "electrophorus", "elops", "engraulis", "epinephelus", "equetus", "esox", "etropus", "eucinostomus", "euthynnus", "fistularia", "fundulus", "gadus", "galeocerdo", "galeorhinus", "gambusia", "gasterosteus", "gempylus", "genus", "genus abramis", "genus abudefduf", "genus acanthocybium", "genus acanthurus", "genus achoerodus", "genus acipenser", "genus aetobatus", "genus agonus", "genus albula", "genus alectis", "genus alepisaurus", "genus alopius", "genus alosa", "genus ambloplites", "genus ameiurus", "genus amia", "genus ammodytes", "genus amphiprion", "genus anabas", "genus anarhichas", "genus anguilla", "genus anisotremus", "genus anomalops", "genus antigonia", "genus apogon", "genus archosargus", "genus argentina", "genus ariomma", "genus arius", "genus aspidophoroides", "genus astropogon", "genus atherinopsis", "genus aulostomus", "genus bairdiella", "genus balistes", "genus blennius", "genus brama", "genus brevoortia", "genus browmius", "genus calamus", "genus capros", "genus caranx", "genus carassius", "genus carcharhinus", "genus carcharias", "genus carcharodon", "genus catostomus", "genus centropomus", "genus centropristis", "genus ceratodus", "genus cetorhinus", "genus chaenopsis", "genus chaetodipterus", "genus chaetodon", "genus chilomycterus", "genus chimaera", "genus chrysophrys", "genus citharichthys", "genus clupea", "genus coregonus", "genus cosmocampus", "genus cottus", "genus cryptacanthodes", "genus cyclopterus", "genus cynoscion", "genus cyprinus", "genus dactylopterus", "genus dasyatis", "genus decapterus", "genus diodon", "genus echeneis", "genus elagatis", "genus electrophorus", "genus elops", "genus engraulis", "genus epinephelus", "genus eptatretus", "genus equetus", "genus esox", "genus etropus", "genus eucinostomus", "genus euthynnus", "genus fistularia", "genus fundulus", "genus gadus", "genus galeocerdo", "genus galeorhinus", "genus gambusia", "genus gasterosteus", "genus gempylus", "genus genyonemus", "genus gerres", "genus ginglymostoma", "genus gobiesox", "genus gobio", "genus gonorhynchus", "genus gymnelis", "genus gymnura", "genus haemulon", "genus halicoeres", "genus hemigrammus", "genus hemipteronatus", "genus hemitripterus", "genus hexagrammos", "genus hexanchus", "genus hippocampus", "genus hippoglossoides", "genus hippoglossus", "genus hipsurus", "genus holocentrus", "genus hypentelium", "genus hyperoglyphe", "genus ictalurus", "genus ictiobus", "genus istiophorus", "genus isurus", "genus jordanella", "genus katsuwonus", "genus krypterophaneron", "genus kyphosus", "genus lachnolaimus", "genus lactophrys", "genus lagodon", "genus lamna", "genus lampris", "genus lates", "genus latimeria", "genus lebistes", "genus lepidocybium", "genus lepisosteus", "genus lepomis", "genus leuciscus", "genus limanda", "genus liparis", "genus lobotes", "genus lophius", "genus lopholatilus", "genus lota", "genus lumpenus", "genus lutjanus", "genus luvarus", "genus macrozoarces", "genus makaira", "genus mallotus", "genus malopterurus", "genus manta", "genus maxostoma", "genus melanogrammus", "genus menticirrhus", "genus merlangus", "genus merluccius", "genus micropogonias", "genus micropterus", "genus microstomus", "genus mobula", "genus mola", "genus mollienesia", "genus molva", "genus monocanthus", "genus morone", "genus mugil", "genus mulloidichthys", "genus mullus", "genus mustelus", "genus mycteroperca", "genus myxine", "genus myxinikela", "genus myxocephalus", "genus naucrates", "genus negaprion", "genus neoceratodus", "genus notemigonus", "genus notropis", "genus ocyurus", "genus odontaspis", "genus oligoplites", "genus oncorhynchus", "genus ophiodon", "genus orectolobus", "genus orthopristis", "genus osmerus", "genus oxylebius", "genus pagellus", "genus pagrus", "genus palometa", "genus paprilus", "genus paracheirodon", "genus paralichthys", "genus paranthias", "genus parophrys", "genus perca", "genus percina", "genus periophthalmus", "genus peristedion", "genus petromyzon", "genus pholis", "genus photoblepharon", "genus phoxinus", "genus platichthys", "genus platypoecilus", "genus pleuronectes", "genus pollachius", "genus polydactylus", "genus polyodon", "genus polyprion", "genus pomacanthus", "genus pomacentrus", "genus pomatomus", "genus pomolobus", "genus pomoxis", "genus poronotus", "genus priacanthus", "genus prionace", "genus prionotus", "genus pristis", "genus prosopium", "genus psenes", "genus psephurus", "genus psetta", "genus psettichthys", "genus pseudopleuronectes", "genus pterois", "genus pylodictus", "genus rachycentron", "genus raja", "genus regalecus", "genus remilegia", "genus rhincodon", "genus rhinoptera", "genus rivulus", "genus roccus", "genus rutilus", "genus rypticus", "genus salmo", "genus salvelinus", "genus sarda", "genus sardina", "genus sardinia", "genus sardinops", "genus scardinius", "genus scartella", "genus sciaena", "genus sciaenops", "genus scleropages", "genus scomber", "genus scomberesox", "genus scomberomorus", "genus scombresox", "genus scophthalmus", "genus scorpaena", "genus sebastodes", "genus selar", "genus selene", "genus seriola", "genus seriphus", "genus serranus", "genus serrasalmus", "genus sillago", "genus silurus", "genus solea", "genus sphyraena", "genus sphyrna", "genus squalus", "genus squatina", "genus stenotomus", "genus stizostedion", "genus synagrops", "genus synanceja", "genus syngnathus", "genus tarpon", "genus tautoga", "genus tautogolabrus", "genus tetragonurus", "genus tetrapturus", "genus thalassoma", "genus thunnus", "genus tilapia", "genus tinca", "genus toxotes", "genus trachinotus", "genus trachipterus", "genus trachurus", "genus triaenodon", "genus triga", "genus trinectes", "genus umbrina", "genus urophycis", "genus xiphias", "genus xyphophorus", "genus zeus", "genus zoarces", "genyonemus", "gerres", "ginglymostoma", "gobiesox", "gobio", "gonorhynchus", "gymnelis", "gymnura", "haemulon", "halicoeres", "hemigrammus", "hemipteronatus", "hemitripterus", "hexagrammos", "hexanchus", "hippocampus", "hippoglossoides", "hippoglossus", "hipsurus", "holocentrus", "hypentelium", "hyperoglyphe", "ictalurus", "ictiobus", "istiophorus", "isurus", "jordanella", "katsuwonus", "krypterophaneron", "kyphosus", "lachnolaimus", "lactophrys", "lagodon", "lamna", "lampris", "lates", "latimeria", "lebistes", "lepidocybium", "lepisosteus", "lepomis", "leuciscus", "limanda", "liparis", "lobotes", "lophius", "lopholatilus", "lota", "lumpenus", "lutjanus", "luvarus", "macrozoarces", "makaira", "mallotus", "malopterurus", "maxostoma", "melanogrammus", "menticirrhus", "merlangus", "merluccius", "micropogonias", "micropterus", "microstomus", "mobula", "mollienesia", "molva", "monocanthus", "morone", "mugil", "mulloidichthys", "mullus", "mustelus", "mycteroperca", "myxine", "myxinikela", "myxocephalus", "naucrates", "negaprion", "neoceratodus", "notemigonus", "notropis", "ocyurus", "odontaspis", "oligoplites", "oncorhynchus", "ophiodon", "orectolobus", "orthopristis", "osmerus", "oxylebius", "pagellus", "pagrus", "paprilus", "paracheirodon", "paralichthys", "paranthias", "parophrys", "perca", "percina", "periophthalmus", "peristedion", "petromyzon", "pholis", "photoblepharon", "phoxinus", "platichthys", "platypoecilus", "pleuronectes", "pollachius", "polydactylus", "polyodon", "polyprion", "pomacanthus", "pomacentrus", "pomatomus", "pomolobus", "pomoxis", "poronotus", "priacanthus", "prionace", "prionotus", "pristis", "prosopium", "psenes", "psephurus", "psetta", "psettichthys", "pseudopleuronectes", "pterois", "pylodictus", "rachycentron", "raja", "reglaecus", "remilegia", "rhincodon", "rhinoptera", "roccus", "rutilus", "rypticus", "salmo", "salvelinus", "sarda", "sardina", "sardinops", "scardinius", "scartella", "sciaena", "sciaenops", "scleropages", "scomber", "scomberesox", "scomberomorus", "scombresox", "scophthalmus", "scorpaena", "sebastodes", "selar", "selene", "seriola", "seriphus", "serranus", "serrasalmus", "sillago", "silurus", "solea", "sphyraena", "sphyrna", "squalus", "squatina", "stenotomus", "stizostedion", "synagrops", "synanceja", "syngnathus", "tautoga", "tautogolabrus", "tetragonurus", "tetrapturus", "thalassoma", "thunnus", "tilapia", "tinca", "toxotes", "trachinotus", "trachipterus", "trachurus", "triaenodon", "triga", "trinectes", "umbrina", "urophycis", "xiphias", "xyphophorus", "zeus", "zoarces"],
    "fish geranium": ["bedding geranium", "geranium", "pelargonium hortorum", "zonal pelargonium"],
    "fish glue": ["animal product", "glue", "gum", "mucilage"],
    "fish house punch": ["punch"],
    "fish joint": ["butt", "butt joint"],
    "fish knife": ["table knife"],
    "fish ladder": ["passage"],
    "fish loaf": ["meat loaf", "meatloaf", "salmon loaf"],
    "fish louse": ["copepod", "copepod crustacean"],
    "fish meal": ["feed", "organic", "organic fertiliser", "organic fertilizer", "provender"],
    "fish mousse": ["mousse"],
    "fish scale": ["scale"],
    "fish slice": ["food turner", "turner"],
    "fish species": ["asian seabass", "australian arowana", "australian bonytongue", "barramundi", "dawson river salmon", "giant perch", "giant seaperch", "lates calcarifer", "northern barramundi", "saratoga", "scleropages jardinii", "scleropages leichardti", "species", "spotted barramundi", "spotted bonytongue", "white seabass"],
    "fish steak": ["flitch", "steak"],
    "fish stew": ["bouillabaisse", "matelote", "stew"],
    "fish stick": ["dish", "fish finger"],
    "fish-liver oil": ["animal oil", "fish oil", "tuna oil"],
    "fishbone": ["bone", "os"],
    "fishbowl": ["aquarium", "bowl", "fish bowl", "fish tank", "goldfish bowl", "marine museum"],
    "fisher": ["black cat", "fisher cat", "marten", "marten cat", "martes pennanti", "pekan"],
    "fisherman": ["angler", "fisher", "skilled worker", "skilled workman", "trained worker", "trawler", "troller"],
    "fisherman's bend": ["knot"],
    "fisherman's knot": ["knot", "true lover's knot", "truelove knot"],
    "fisherman's lure": ["bait", "decoy", "fish lure", "fly", "jig", "lure", "spinner", "troll"],
    "fishery": ["pearl fishery", "piscary", "work", "workplace"],
    "fisheye": ["wide-angle"],
    "fishhook": ["hook"],
    "fishing": ["business", "business enterprise", "commercial enterprise"],
    "fishing boat": ["dragger", "fishing smack", "fishing vessel", "trawler", "vessel", "watercraft"],
    "fishing eagle": ["haliaeetus leucorhyphus", "sea eagle"],
    "fishing expedition": ["investigation", "probe"],
    "fishing gear": ["appurtenance", "fishing rig", "fishing tackle", "gear", "paraphernalia", "rig", "tackle"],
    "fishing license": ["fishing licence", "fishing permit", "licence", "license", "permit"],
    "fishing line": ["cord", "hand line", "handline", "night-line", "setline", "spiller", "trawl", "trawl line", "trotline"],
    "fishing rod": ["fishing pole", "fly rod", "rod", "spinning rod"],
    "fishing season": ["season"],
    "fishmonger": ["bargainer", "dealer", "fishwife", "monger", "trader"],
    "fishnet": ["dragnet", "drift net", "fishing net", "gill net", "landing net", "net", "seine", "trammel", "trammel net", "trawl", "trawl net"],
    "fishpaste": ["paste", "spread"],
    "fishplate": ["plate"],
    "fishpole bamboo": ["bamboo", "gosan-chiku", "hotei-chiku", "phyllostachys aurea"],
    "fishpond": ["pond", "pool"],
    "fishtail": ["decelerate", "slow down"],
    "fishtail bit": ["blade bit", "drill bit", "drilling bit"],
    "fishtail palm": ["palm", "palm tree"],
    "fishy": [],
    "fissile": [],
    "fission": ["agamogenesis", "asexual reproduction", "schizogony"],
    "fissionable": ["fissile"],
    "fissiparity": ["agamogenesis", "asexual reproduction"],
    "fissiparous": [],
    "fissiped mammal": ["carnivore", "fissiped"],
    "fissipedia": ["eutherian", "eutherian mammal", "placental", "placental mammal"],
    "fissure": ["crack"],
    "fissure of rolando": ["central sulcus", "rolando's fissure", "sulcus", "sulcus centralis"],
    "fissure of sylvius": ["lateral cerebral sulcus", "sulcus", "sulcus lateralis cerebri", "sylvian fissure"],
    "fissurella": ["genus fissurella", "mollusk genus"],
    "fissurellidae": ["family fissurellidae", "mollusk family"],
    "fist": ["clenched fist", "hand", "manus", "mitt", "paw"],
    "fistfight": ["contend", "fight", "struggle"],
    "fistmele": ["linear measure", "linear unit"],
    "fistula": ["passage", "passageway", "sinus"],
    "fistular": ["fistulate", "fistulous"],
    "fistularia": ["fish genus", "genus fistularia"],
    "fistulariidae": ["family fistulariidae", "fish family"],
    "fistulina": ["fungus genus", "genus fistulina"],
    "fistulinaceae": ["family fistulinaceae", "fungus family"],
    "fistulous": [],
    "fistulous withers": ["animal disease", "fistula"],
    "fit": ["be", "fit", "go"],
    "fit the bill": ["conform to", "fill the bill", "fit", "meet"],
    "fitful": ["spasmodic"],
    "fitfully": [],
    "fitfulness": ["irregularity", "jerkiness", "spasticity", "unregularity"],
    "fitment": ["article of furniture", "furniture", "piece of furniture"],
    "fitness": ["condition", "fettle", "physical fitness", "shape"],
    "fits and starts": ["burst", "fit"],
    "fitted": [],
    "fitted out": ["outfitted"],
    "fitted sheet": ["bed sheet", "contour sheet", "sheet"],
    "fitter": ["sartor", "seamster", "tailor"],
    "fitting": ["accessory", "add-on", "appurtenance", "gas fitting", "pipe fitting", "pipefitting", "receptacle", "supplement"],
    "fitzgerald": ["edward fitzgerald"],
    "five": ["5", "cinque", "digit", "figure", "fin", "fivesome", "little phoebe", "pentad", "phoebe", "quint", "quintet", "quintuplet", "v"],
    "five hundred": ["500", "d", "large integer"],
    "five spice powder": ["spice"],
    "five-hitter": ["5-hitter", "baseball", "baseball game"],
    "five-hundredth": ["500th"],
    "five-lobed": [],
    "five-membered": ["5-membered"],
    "five-needled": [],
    "five-petaled": ["five-petalled"],
    "five-point bishop's cap": ["bishop's cap", "mitella pentandra", "miterwort", "mitrewort"],
    "five-pointed": [],
    "five-sided": [],
    "five-spot": ["nemophila", "nemophila maculata"],
    "five-year-old": [],
    "fivepence": ["coin"],
    "fiver": ["bank bill", "bank note", "banker's bill", "banknote", "bill", "federal reserve note", "five dollar bill", "five-spot", "government note", "greenback", "nickel", "nickel note", "note"],
    "fives": ["court game"],
    "fix": ["act upon", "influence", "work"],
    "fix up": ["cater", "ply", "provide", "supply"],
    "fixate": ["attach", "bind", "bond", "tie"],
    "fixation": ["attachment", "fastening"],
    "fixative": ["fixer", "fixing agent"],
    "fixed": ["rigid", "set"],
    "fixed charge": ["charge", "cover", "cover charge", "due", "fee", "fixed cost", "fixed costs", "interest"],
    "fixed intonation": ["intonation"],
    "fixed oil": ["fatty oil", "oil"],
    "fixed phagocyte": ["phagocyte", "scavenger cell"],
    "fixed star": ["star"],
    "fixed-combination drug": ["medicament", "medication", "medicinal drug", "medicine"],
    "fixed-cycle operation": ["operation"],
    "fixed-point notation": ["fixed-point representation system", "mathematical notation"],
    "fixed-point number": ["number"],
    "fixedly": [],
    "fixedness": ["changelessness", "unalterability", "unchangeability", "unchangeableness", "unchangingness"],
    "fixer": ["important person", "influence peddler", "influential person", "personage"],
    "fixer-upper": ["abode", "domicile", "dwelling", "dwelling house", "habitation", "home"],
    "fixing agent": ["chemical compound", "compound", "fixative", "fixer", "hypo", "sodium thiosulfate", "sodium thiosulphate"],
    "fixings": ["accessory", "add-on", "appurtenance", "supplement", "trimmings"],
    "fixture": ["artefact", "artifact", "bathroom fixture", "lighting fixture", "plumbing fixture", "soap dish"],
    "fizgig": ["firework", "pyrotechnic"],
    "fizz": ["beverage", "drink", "drinkable", "potable"],
    "fizzing": ["fizzy"],
    "fjord": ["fiord", "inlet", "recess"],
    "flab": ["adipose tissue", "fat", "fatty tissue"],
    "flabbergast": ["boggle", "bowl over", "surprise"],
    "flabbily": [],
    "flabbiness": ["flaccidity", "limpness", "softness"],
    "flaccid": [],
    "flaccid bladder": ["bladder disorder"],
    "flaccid paralysis": ["nervous disorder", "neurological disease", "neurological disorder"],
    "flacourtia": ["dilleniid dicot genus", "genus flacourtia"],
    "flacourtiaceae": ["dilleniid dicot family", "family flacourtiaceae", "flacourtia family"],
    "flag": ["adorn", "beautify", "decorate", "embellish", "grace", "ornament"],
    "flag captain": ["captain", "skipper"],
    "flag day": ["day", "june 14"],
    "flag down": ["stop"],
    "flag officer": ["admiral", "commissioned naval officer", "five-star admiral", "fleet admiral", "full admiral", "rear admiral", "vice admiral"],
    "flag rank": ["military rank", "military rating", "paygrade", "rating"],
    "flag smut": ["smut"],
    "flag smut fungus": ["smut", "smut fungus", "urocystis tritici", "wheat flag smut"],
    "flag waving": ["demagoguery", "demagogy", "jingoism"],
    "flagellant": ["masochist"],
    "flagellate": ["flog", "lash", "lather", "scourge", "slash", "strap", "trounce", "welt", "whip"],
    "flagellated cell": ["cell", "choanocyte", "collar cell"],
    "flagellation": ["beating", "drubbing", "lacing", "licking", "thrashing", "trouncing", "whacking"],
    "flagellum": ["appendage", "outgrowth", "process"],
    "flageolet": ["common bean", "haricot"],
    "flagfish": ["american flagfish", "jordanella floridae", "killifish"],
    "flagging": ["accumulation", "aggregation", "assemblage", "collection"],
    "flagitious": ["heinous"],
    "flagon": ["vessel"],
    "flagpole": ["flagstaff", "staff"],
    "flagrantly": [],
    "flagship": ["thing"],
    "flagstaff": [],
    "flail": ["beat", "flap", "thresh"],
    "flair": ["endowment", "genius", "gift", "natural endowment", "talent"],
    "flak catcher": ["flack", "flack catcher", "flak", "interpreter", "representative", "spokesperson", "voice"],
    "flake": ["form"],
    "flakiness": ["brittleness", "crispiness", "crispness"],
    "flaky": ["flakey"],
    "flambe": ["cook", "fix", "make", "prepare", "ready"],
    "flambeau": ["torch"],
    "flamboyance": ["elaborateness", "floridity", "floridness", "ornateness", "showiness"],
    "flamboyant": ["showy", "splashy"],
    "flamboyantly": ["flashily", "showily"],
    "flame": ["burn", "combust"],
    "flame cell": ["excretory organ", "urinary organ"],
    "flame fish": ["apogon maculatus", "cardinalfish", "flamefish"],
    "flame flower": ["flame-flower", "flameflower", "jewels-of-opar", "narrow-leaved flame flower", "pigmy talinum", "rock pink", "spiny talinum", "talinum augustissimum", "talinum aurantiacum", "talinum brevifolium", "talinum calycinum", "talinum paniculatum", "talinum spinescens", "wild flower", "wildflower"],
    "flame pea": ["bush", "shrub"],
    "flame tokay": ["tokay"],
    "flame tree": ["christmas tree", "fire tree", "nuytsia floribunda", "parasitic plant"],
    "flame-colored": ["flame-coloured"],
    "flame-out": ["power failure", "power outage"],
    "flamen": ["non-christian priest", "priest"],
    "flamenco": ["dance music"],
    "flameproof": ["flame-retardant"],
    "flamethrower": ["arm", "weapon", "weapon system"],
    "flamingo": ["wader", "wading bird"],
    "flamingo flower": ["anthurium", "anthurium andraeanum", "anthurium scherzerianum", "flamingo plant", "tail-flower", "tailflower"],
    "flaminian way": [],
    "flaminius": ["gaius flaminius"],
    "flammability": ["burnability", "combustibility", "combustibleness", "inflammability"],
    "flammable": ["inflammable"],
    "flammulina": ["fungus genus", "genus flammulina"],
    "flan": ["afters", "dessert", "sweet"],
    "flanders": [],
    "flange": ["projection", "rim"],
    "flank": ["lie"],
    "flank steak": ["beefsteak"],
    "flanker": ["soldier"],
    "flanker back": ["back", "flanker"],
    "flannel": ["gabardine", "pant", "trouser", "tweed", "white"],
    "flannelbush": ["bush", "california beauty", "flannel bush", "shrub"],
    "flannelette": ["cloth", "fabric", "material", "textile", "winceyette"],
    "flap": ["beat", "pound", "thump"],
    "flapper": ["fille", "girl", "miss", "missy", "young lady", "young woman"],
    "flare": ["beam", "flame", "shine"],
    "flare out": ["flare", "widen"],
    "flare pass": ["aerial", "flare", "forward pass"],
    "flare path": ["airstrip", "flight strip", "landing strip", "strip"],
    "flare star": ["red dwarf", "red dwarf star"],
    "flare up": ["ignite", "inflame", "kindle", "light"],
    "flash": ["blink", "flick", "flicker", "radiate", "twinkle", "wink", "winkle"],
    "flash camera": ["camera", "photographic camera"],
    "flash card": ["bill", "card", "flashcard", "notice", "placard", "poster", "posting"],
    "flash flood": ["alluvion", "deluge", "flashflood", "flood", "floodhead", "inundation"],
    "flash in the pan": ["failure", "loser", "nonstarter", "unsuccessful person"],
    "flash memory": ["non-volatile storage", "nonvolatile storage"],
    "flash point": ["criticality", "flashpoint"],
    "flash welding": ["butt welding", "butt-welding", "flash butt welding"],
    "flash-forward": ["transition"],
    "flash-frozen": ["frozen", "quick-frozen"],
    "flashback": ["recurrence", "return"],
    "flashboard": ["boarding", "flashboarding"],
    "flasher": ["electrical device"],
    "flashiness": ["brashness", "garishness", "gaudiness", "glitz", "loudness", "meretriciousness", "tastelessness", "tawdriness"],
    "flashing": ["sheet metal"],
    "flashlight": ["electric lamp", "penlight", "torch"],
    "flashlight battery": ["dry battery"],
    "flashlight fish": ["acanthopterygian", "photoblepharon palpebratus", "spiny-finned fish"],
    "flashover": ["arc", "discharge", "electric arc", "electric discharge", "spark"],
    "flashy": ["gaudy", "jazzy", "showy", "sporty"],
    "flask": ["containerful", "flaskful"],
    "flat": ["alluvial flat", "alluvial plain", "champaign", "field", "plain", "salt flat", "salt plain"],
    "flat arch": ["arch", "straight arch"],
    "flat bench": ["bench"],
    "flat bone": ["cut of beef"],
    "flat coat": ["coat of paint", "couch", "ground", "primer", "primer coat", "priming", "priming coat", "undercoat"],
    "flat file": ["file"],
    "flat out": ["like blue murder"],
    "flat panel display": ["display", "fpd", "video display"],
    "flat pea": ["bush", "platylobium formosum", "shrub"],
    "flat tip screwdriver": ["screwdriver"],
    "flat-bottomed": ["flat-bottom"],
    "flat-coated retriever": ["retriever"],
    "flat-footed": [],
    "flat-topped": ["flat-top"],
    "flat-topped white aster": ["aster"],
    "flatbed": ["truck bed"],
    "flatbed press": ["cylinder press", "press", "printing press"],
    "flatbottom": ["flatbottomed"],
    "flatbread": ["bannock", "bread", "breadstuff", "chapati", "chapatti", "flatbrod", "pita", "pocket bread", "staff of life"],
    "flatbrod": ["flatbread"],
    "flatcar": ["flat", "flatbed", "freight car"],
    "flatfish": ["fillet of sole", "flounder", "halibut", "saltwater fish", "sole"],
    "flatfoot": ["law officer", "lawman", "patrolman", "peace officer"],
    "flathead": ["scorpaenoid", "scorpaenoid fish"],
    "flathead catfish": ["catfish", "goujon", "mudcat", "pylodictus olivaris", "shovelnose catfish", "siluriform fish", "spoonbill catfish"],
    "flatiron": ["iron", "smoothing iron"],
    "flatlet": ["apartment", "flat"],
    "flatly": ["categorically", "unconditionally"],
    "flatmate": ["friend"],
    "flatness": ["expressive style", "style"],
    "flats": ["footgear", "footwear"],
    "flatten": ["form", "laminate", "roll", "roll out", "shape", "splat", "steamroll", "steamroller"],
    "flatter": ["adulate", "blandish", "bootlick", "brown-nose", "butter up", "fawn", "kotow", "kowtow", "praise", "soft-soap", "stroke", "suck up", "toady", "truckle"],
    "flatterer": ["adulator", "ass-kisser", "crawler", "follower", "lackey", "sycophant", "toady"],
    "flattering": [],
    "flattery": ["adulation", "blandishment", "blarney", "cajolery", "coaxing", "compliment", "palaver", "puffery", "soft soap", "sweet talk"],
    "flatulence": ["flatulency", "gas", "physical condition", "physiological condition", "physiological state"],
    "flatulent": [],
    "flatware": ["plate", "platter", "saucer", "tableware"],
    "flatwork": ["flat wash", "ironing"],
    "flatworm": ["cestode", "fluke", "planaria", "planarian", "platyhelminth", "tapeworm", "trematode", "trematode worm", "worm"],
    "flaubert": ["gustave flaubert"],
    "flaunt": ["display", "exhibit", "expose", "flash", "flex", "ostentate", "show off", "splurge", "swank"],
    "flaunty": [],
    "flavian dynasty": ["dynasty"],
    "flavin": ["ketone"],
    "flaviviridae": ["arborvirus", "arbovirus"],
    "flavivirus": ["animal virus", "west nile encephalitis virus", "west nile virus"],
    "flavone": ["chemical compound", "compound"],
    "flavonoid": ["phytochemical", "pigment"],
    "flavor": ["charm", "flavour", "form", "kind", "sort", "strangeness", "variety"],
    "flavorer": ["ail", "almond extract", "anchovy paste", "angelica", "anise", "anise seed", "aniseed", "benniseed", "bouillon cube", "caraway seed", "cardamom", "cardamon", "cardamum", "cassareep", "cayenne", "cayenne pepper", "celery salt", "celery seed", "chili powder", "cola extract", "common salt", "condiment", "coriander", "coriander seed", "curry powder", "dill seed", "fennel seed", "fenugreek", "fenugreek seed", "fixings", "flavoring", "flavourer", "flavouring", "garlic", "garlic chive", "garlic salt", "ginger", "gingerroot", "herb", "ingredient", "juniper berries", "lemon extract", "lemon oil", "mocha", "monosodium glutamate", "msg", "mustard seed", "nasturtium", "oil of wintergreen", "onion salt", "paprika", "pepper", "peppercorn", "peppermint oil", "poppy seed", "red pepper", "saffron", "salt", "sassafras", "seasoned salt", "seasoner", "seasoning", "sesame seed", "sour salt", "spearmint oil", "spice", "sweetener", "sweetening", "table salt", "turmeric", "vanilla", "vanilla bean", "vanilla extract", "wintergreen oil"],
    "flavorful": ["flavorous", "flavorsome", "flavourful", "flavourous", "flavoursome", "sapid", "saporous"],
    "flavorlessness": ["flavourlessness", "savorlessness", "savourlessness", "tastelessness", "unappetisingness", "unappetizingness"],
    "flavorsomeness": ["appetisingness", "appetizingness", "flavoursomeness", "sapidity", "sapidness", "savoriness"],
    "flaw": ["blemish", "damage"],
    "flawless": ["unflawed"],
    "flawlessly": ["cleanly"],
    "flax": ["plant fiber", "plant fibre"],
    "flax rust": ["flax rust fungus", "melampsora lini", "rust", "rust fungus"],
    "flaxen": ["sandy"],
    "flay": ["pare", "peel", "skin"],
    "flea": ["cat flea", "chigger", "chigoe", "chigoe flea", "ctenocephalides canis", "ctenocephalides felis", "dog flea", "echidnophaga gallinacea", "ectoparasite", "ectozoan", "ectozoon", "epizoan", "epizoon", "insect", "pulex irritans", "sticktight", "sticktight flea", "tunga penetrans"],
    "flea beetle": ["chrysomelid", "leaf beetle"],
    "flea bite": ["bite", "insect bite", "sting"],
    "flea market": ["market square", "open-air market", "open-air marketplace"],
    "fleabag": ["hotel"],
    "fleabane": ["feabane mullet", "herb", "herbaceous plant", "pulicaria dysenterica"],
    "fleapit": ["cinema", "movie house", "movie theater", "movie theatre", "picture palace"],
    "fleawort": ["plantago psyllium", "plantain", "psyllium", "spanish psyllium"],
    "flecainide": ["antiarrhythmic", "antiarrhythmic drug", "antiarrhythmic medication", "tambocor"],
    "fledge": ["bring up", "nurture", "parent", "raise", "rear"],
    "fledged": ["mature"],
    "fledgling": ["fledgeling", "young bird"],
    "flee": ["abscond", "absquatulate", "bolt", "break", "break away", "break loose", "bunk", "decamp", "defect", "desert", "elope", "escape", "fly", "fly the coop", "get away", "go off", "head for the hills", "high-tail", "hightail it", "lam", "make off", "run", "run away", "run off", "scarper", "scat", "stampede", "take flight", "take to the woods", "turn tail"],
    "fleece": ["shave", "shear", "trim"],
    "fleeceable": ["green", "gullible"],
    "fleer": ["simper", "smirk"],
    "fleet": ["accumulation", "aggregation", "assemblage", "collection"],
    "fleet admiral": ["five-star admiral", "flag officer"],
    "fleet ballistic missile submarine": ["pigboat", "sub", "submarine", "u-boat"],
    "fleet street": [],
    "fleeting": ["fugitive", "momentaneous", "momentary"],
    "fleetness": ["celerity", "quickness", "rapidity", "rapidness", "speediness"],
    "fleming": ["ian fleming", "ian lancaster fleming"],
    "flemish": ["ethnic group", "ethnos"],
    "flemish-speaking": [],
    "flense": ["get rid of", "remove"],
    "flesh": ["get rid of", "remove"],
    "flesh fly": ["fly", "sarcophaga carnaria"],
    "flesh wound": ["combat injury", "injury", "wound"],
    "flesh-colored": ["flesh-coloured"],
    "flesh-eating": ["meat-eating", "zoophagous"],
    "fleshed out": ["full-clad"],
    "fleshiness": ["adiposis", "avoirdupois", "blubber", "corpulence", "corpulency", "embonpoint", "exogenous obesity", "fat", "fatness", "obesity", "overweight", "plumpness", "roundness", "stoutness"],
    "fleshy": ["sarcoid"],
    "fletcher": ["john fletcher"],
    "fleur-de-lis": ["armorial bearing", "bearing", "charge", "fleur-de-lys", "heraldic bearing"],
    "flex": ["flash", "flaunt", "ostentate", "show off", "swank"],
    "flexibility": ["bendability", "flexibleness", "malleability", "plasticity", "pliability", "whip"],
    "flexible": [],
    "flexibly": [],
    "flexion": ["bending", "dorsiflexion", "flex", "flexure"],
    "flexor muscle": ["flexor", "skeletal muscle", "striated muscle"],
    "flexuous": [],
    "flexure": ["flection", "flexion", "physical condition", "physiological condition", "physiological state"],
    "flibbertigibbet": ["fool", "foolish woman", "muggins", "sap", "saphead", "tomfool"],
    "flick": ["flip", "leaf", "peruse", "riff", "riffle", "thumb"],
    "flicker": ["beam", "flick", "shine"],
    "flickering": ["aflicker"],
    "flickertail": ["citellus richardsoni", "gopher", "ground squirrel", "richardson ground squirrel", "spermophile"],
    "flier": ["flyer", "traveler", "traveller"],
    "flies": ["space"],
    "flight": ["pip", "shoot"],
    "flight control": ["control"],
    "flight deck": ["deck", "landing deck"],
    "flight engineer": ["aircrewman"],
    "flight feather": ["feather", "pinion", "plumage", "plume", "primary", "primary feather", "primary quill", "quill", "quill feather", "tail feather"],
    "flight line": ["line"],
    "flight maneuver": ["airplane maneuver", "bank", "chandelle", "evasive action", "loop", "loop-the-loop", "maneuver", "manoeuvre", "roll", "sideslip", "slip"],
    "flight path": ["itinerary", "path", "route"],
    "flight simulator": ["link trainer", "simulator", "trainer"],
    "flight surgeon": ["medic", "medical officer"],
    "flighted": [],
    "flightiness": ["arbitrariness", "capriciousness", "irresponsibility", "irresponsibleness", "whimsey", "whimsicality", "whimsy"],
    "flightless": [],
    "flighty": ["flyaway", "head-in-the-clouds", "scatterbrained"],
    "flim-flam": ["cozen", "deceive", "delude", "fob", "fox", "lead on", "play a joke on", "play a trick on", "play tricks", "pull a fast one on", "snooker", "trick"],
    "flimsily": [],
    "flimsiness": ["shoddiness", "weakness"],
    "flimsy": [],
    "flinch": ["cringe", "funk", "move", "quail", "recoil", "retract", "shrink", "shrink back", "squinch", "wince"],
    "flinders": ["matthew flinders", "sir matthew flinders"],
    "flindersia": ["genus flindersia", "rosid dicot genus"],
    "fling": ["move"],
    "flint": ["firestone", "flintstone", "gunflint", "silica", "silicon dioxide", "silicon oxide"],
    "flint corn": ["field corn", "flint maize", "yankee corn", "zea mays indurata"],
    "flintlock": ["firelock", "muzzle loader"],
    "flintstone": ["flint"],
    "flinty": [],
    "flip": ["move", "twitch"],
    "flip chart": ["chart"],
    "flip one's lid": ["blow a fuse", "blow one's stack", "blow up", "combust", "flip one's wig", "fly off the handle", "go ballistic", "have a fit", "have kittens", "hit the ceiling", "hit the roof", "lose one's temper", "rage", "throw a fit"],
    "flip side": ["oppositeness", "opposition"],
    "flip-flap": [],
    "flip-flop": ["sandal", "thong"],
    "flippancy": ["levity", "light-mindedness"],
    "flippant": ["light-minded"],
    "flippantly": ["airily"],
    "flipper": ["fin", "shoe"],
    "flipper-like": [],
    "flirt": ["caper", "coquetry", "dalliance", "flirtation", "flirting", "frolic", "gambol", "play", "romp", "toying"],
    "flit": ["butterfly", "dart", "fleet", "flutter", "hurry", "speed", "travel rapidly", "zip"],
    "flitch": ["fish steak"],
    "float": ["essay", "examine", "prove", "test", "try", "try out"],
    "floater": ["certificate of indebtedness", "debt instrument", "obligation"],
    "floating": ["dead-man's float", "natation", "prone float", "swim", "swimming"],
    "floating dock": ["dry dock", "drydock", "floating dry dock", "graving dock"],
    "floating fern": ["aquatic fern", "ceratopteris thalictroides", "water fern"],
    "floating mine": ["magnetic mine", "marine mine", "mine"],
    "floating-moss": ["aquatic fern", "salvinia auriculata", "salvinia rotundifolia", "water fern"],
    "floating-point notation": ["floating-point representation system", "mathematical notation"],
    "floating-point number": ["number"],
    "floating-point operation": ["computer operation", "flop", "machine operation"],
    "floatplane": ["hydroplane", "pontoon plane", "seaplane"],
    "floccose": [],
    "floccose chanterelle": ["agaric", "cantharellus floccosus"],
    "flocculate": ["alter", "change", "modify"],
    "flocculation": ["action", "activity", "natural action", "natural process"],
    "floccule": ["floc", "material", "stuff"],
    "flocculent": ["woolly", "wooly"],
    "flock": ["go", "locomote", "move", "travel"],
    "flodden": [],
    "flog": ["beat", "beat up", "birch", "cat", "cowhide", "flagellate", "horsewhip", "lash", "lather", "leather", "scourge", "slash", "strap", "switch", "trounce", "welt", "whip", "work over"],
    "flogger": ["scourger", "torturer"],
    "flood": ["furnish", "glut", "oversupply", "provide", "render", "supply"],
    "flood control": ["control"],
    "flood in": ["arrive", "come", "get"],
    "flood tide": ["flood", "rising tide", "tide"],
    "flooded gum": ["cider gum", "eucalypt", "eucalypt grandis", "eucalypt gunnii", "eucalypt tereticornis", "eucalyptus", "eucalyptus tree", "forest red gum", "rose gum"],
    "floodgate": ["restraint"],
    "floodhead": ["flash flood", "flashflood"],
    "floodlight": ["illume", "illuminate", "illumine", "light", "light up"],
    "floodlit": ["floodlighted"],
    "floodplain": ["champaign", "field", "flood plain", "plain"],
    "floor": ["earth's surface", "surface"],
    "floor cover": ["carpet", "carpeting", "covering", "floor covering", "mat", "parqueterie", "parquetry", "rug"],
    "floor joist": ["joist"],
    "floor lamp": ["lamp"],
    "floor leader": ["legislator"],
    "floor plan": ["architectural plan", "ground plan", "plan"],
    "floor wax": ["wax"],
    "floorboard": ["floor", "flooring"],
    "floored": [],
    "flooring": ["building material"],
    "floorwalker": ["employee", "shopwalker"],
    "flop": ["break", "cave in", "collapse", "fall in", "founder", "give", "give way"],
    "flophouse": ["dosshouse", "lodging house", "rooming house"],
    "floppy": [],
    "floral": [],
    "floral leaf": ["flower petal", "foliage", "leaf", "leafage", "petal", "sepal"],
    "floreal": ["revolutionary calendar month"],
    "florence": [],
    "florence fennel": ["fennel", "foeniculum dulce", "foeniculum vulgare dulce"],
    "florentine": ["italian"],
    "florentine iris": ["bearded iris", "iris florentina", "iris germanica florentina", "orris"],
    "florest's cineraria": ["flower", "pericallis hybrida"],
    "floret": ["bloom", "blossom", "flower", "floweret"],
    "florey": ["howard florey", "sir howard walter florey"],
    "floricultural": [],
    "florida": ["everglade state", "fl", "sunshine state"],
    "florida gallinule": ["gallinula chloropus cachinnans", "gallinule", "marsh hen", "swamphen", "water hen"],
    "florida pompano": ["pompano", "trachinotus carolinus"],
    "florida selaginella": ["little club moss", "selaginella eatonii", "spike moss", "spikemoss"],
    "florida smoothhound": ["mustelus norrisi", "smooth dogfish"],
    "florida strap fern": ["cow-tongue fern", "hart's-tongue fern", "strap fern"],
    "florida yew": ["taxus floridana", "yew"],
    "floridian": ["american"],
    "floridly": [],
    "florilegium": ["anthology", "garland", "miscellany"],
    "florio": ["john florio"],
    "florist": ["market keeper", "shopkeeper", "storekeeper", "tradesman"],
    "florist's chrysanthemum": ["chrysanthemum", "chrysanthemum morifolium", "dendranthema grandifloruom", "florists' chrysanthemum", "mum"],
    "florist's gloxinia": ["gloxinia", "gloxinia spesiosa", "sinningia speciosa"],
    "flory": ["paul john flory"],
    "floss": ["clean", "cleanse"],
    "flotation": ["floatation", "physical phenomenon"],
    "flotilla": ["fleet"],
    "flotsam": ["jetsam", "wreckage"],
    "flounce": ["walk"],
    "flounder": ["fight", "struggle"],
    "flour": ["dredge"],
    "flour beetle": ["darkling beetle", "darkling groung beetle", "flour weevil", "tenebrionid"],
    "flour bin": ["bin"],
    "flour mill": ["grinder", "mill", "milling machinery"],
    "flourish": ["embellishment", "paraph"],
    "floury": [],
    "flow": ["be", "exist"],
    "flow away": ["discharge", "empty", "flow off"],
    "flow chart": ["flow diagram", "flow sheet", "flowchart", "multidimensional language"],
    "flow out": ["effuse", "emanate"],
    "flowage": ["flow"],
    "flower": ["bloom", "blossom", "efflorescence", "flush", "golden age", "heyday", "peak", "period", "period of time", "prime", "time period"],
    "flower arrangement": ["arrangement", "bouquet", "chaplet", "coronal", "corsage", "decoration", "floral arrangement", "flower chain", "garland", "lei", "nosegay", "ornament", "ornamentation", "posy", "spray", "wreath"],
    "flower bud": ["bud", "clove"],
    "flower chain": ["daisy chain", "festoon", "festoonery", "floral arrangement", "flower arrangement"],
    "flower cluster": ["inflorescence", "raceme", "thyrse", "thyrsus"],
    "flower garden": ["garden", "parterre"],
    "flower gardening": ["floriculture", "gardening", "horticulture"],
    "flower girl": ["marketer", "seller", "trafficker", "vender", "vendor"],
    "flower head": ["inflorescence"],
    "flower people": ["hippies", "hipsters", "youth subculture"],
    "flower power": ["counterculture"],
    "flower-of-an-hour": ["black-eyed susan", "bladder ketmia", "flowers-of-an-hour", "hibiscus", "hibiscus trionum"],
    "flowerbed": ["bed", "bed of flowers", "bed of roses", "flower bed", "rose bed", "tulip bed"],
    "flowering": [],
    "flowering almond": ["almond tree", "prunus triloba"],
    "flowering ash": ["ash", "ash tree", "fraxinus dipetala"],
    "flowering cherry": ["cherry", "cherry tree", "fuji", "fuji cherry", "japanese cherry", "japanese flowering cherry", "oriental cherry", "prunus incisa", "prunus serrulata", "prunus sieboldii", "prunus subhirtella", "rosebud cherry", "winter flowering cherry"],
    "flowering fern": ["fern", "helminthostachys zeylanica"],
    "flowering maple": ["ornamental"],
    "flowering quince": ["bush", "chaenomeles japonica", "chaenomeles speciosa", "japanese quince", "japonica", "maule's quince", "shrub"],
    "flowering raspberry": ["purple-flowering raspberry", "raspberry", "raspberry bush", "rubus odoratus", "thimbleberry"],
    "flowering shrub": ["alpine golden chain", "asiatic sweetleaf", "bird of paradise", "bush", "caesalpinia gilliesii", "caesalpinia pulcherrima", "common laburnum", "flamboyant tree", "golden chain", "golden rain", "laburnum alpinum", "laburnum anagyroides", "paradise flower", "poinciana", "poinciana gilliesii", "poinciana pulcherrima", "pride of barbados", "sapphire berry", "scotch laburnum", "shrub", "symplocus paniculata"],
    "flowering tobacco": ["jasmine tobacco", "nicotiana alata", "tobacco", "tobacco plant"],
    "flowering wintergreen": ["bird-on-the-wing", "fringed polygala", "gaywings", "milkwort", "polygala paucifolia"],
    "flowerless": ["nonflowering"],
    "flowery": [],
    "floxuridine": ["antineoplastic", "antineoplastic drug", "cancer drug"],
    "fluctuate": ["displace", "move"],
    "fluctuating": [],
    "fluctuation": ["undulation", "wave"],
    "flue": ["chimney", "chimneystack", "conduit", "lamp chimney"],
    "flue pipe": ["flue", "labial pipe", "organ pipe", "pipe", "pipework"],
    "flue stop": ["organ stop"],
    "fluency": ["skillfulness"],
    "fluent": ["fluid", "liquid", "smooth"],
    "fluently": [],
    "fluff": ["material", "stuff"],
    "fluff up": ["agitate", "plump up", "shake", "shake up"],
    "fluffy omelet": ["omelet", "omelette"],
    "flugelhorn": ["brass", "brass instrument", "fluegelhorn"],
    "fluid": ["coolant", "filtrate", "ichor", "liquid", "substance"],
    "fluid drive": ["coupler", "coupling"],
    "fluid flywheel": ["flywheel"],
    "fluid mechanics": ["hydraulics", "hydrodynamics", "hydrokinetics", "hydrostatics", "mechanics"],
    "fluidity": ["fluidness", "liquidity", "liquidness", "runniness", "thinness"],
    "fluidounce": ["british capacity unit", "fluid ounce", "imperial capacity unit"],
    "fluidram": ["british capacity unit", "drachm", "fluid drachm", "fluid dram", "imperial capacity unit"],
    "fluke": ["barb"],
    "flume": ["watercourse", "waterway"],
    "flummery": ["pudding"],
    "flump": ["drop", "flump down"],
    "flunitrazepan": ["circle", "club drug", "forget me drug", "mexican valium", "r-2", "roach", "rohypnol", "roofy", "rope", "rophy"],
    "flunky": ["flunkey", "follower", "pushover", "stooge", "yes-man"],
    "fluorapatite": ["apatite"],
    "fluoresce": ["glow", "scintillate"],
    "fluorescein": ["absorption indicator", "bromeosin", "dye", "dyestuff", "eosin", "fluoresceine", "fluorescent dye", "resorcinolphthalein"],
    "fluorescein isothiocyanate": ["fluorescein isocyanate", "fluorochrome"],
    "fluorescence": ["autofluorescence", "light", "phosphorescence", "visible light", "visible radiation"],
    "fluorescence microscopy": ["indirect immunofluorescence", "microscopy"],
    "fluorescent": ["fluorescent fixture", "lighting fixture"],
    "fluorescent lamp": ["lamp"],
    "fluoridate": ["fluoridise", "fluoridize", "process", "treat"],
    "fluoridation": ["addition", "fluoridisation", "fluoridization"],
    "fluoride": ["boron trifluoride", "halide", "hydrogen fluoride", "stannous fluoride", "sulfur hexafluoride", "sulphur hexafluoride"],
    "fluorine": ["atomic number 9", "chemical element", "element", "f", "gas", "halogen"],
    "fluorite": ["fluor", "fluorspar", "mineral"],
    "fluoroboric acid": ["acid"],
    "fluoroboride": ["salt"],
    "fluorocarbon": ["cfc", "chlorofluorocarbon", "halocarbon", "hfc", "hydrofluorocarbon", "perfluorocarbon", "pfc", "tetrafluoroethylene"],
    "fluorocarbon plastic": ["plastic"],
    "fluorochrome": ["dye", "dyestuff", "fluorescein isocyanate", "fluorescein isothiocyanate"],
    "fluoroform": ["haloform", "trifluoromethane"],
    "fluoroscope": ["roentgenoscope", "x-ray machine"],
    "fluoroscopy": ["radiology", "radioscopy"],
    "fluorosis": ["pathology"],
    "fluorouracil": ["antimetabolite"],
    "fluosilicate": ["salt"],
    "fluosilicic acid": ["acid", "hydrofluosilicic acid"],
    "fluoxetine": ["fluoxetine hydrocholoride", "prozac", "sarafem", "selective-serotonin reuptake inhibitor", "ssri"],
    "fluphenazine": ["antipsychotic", "antipsychotic agent", "antipsychotic drug", "major tranquilizer", "major tranquilliser", "major tranquillizer", "neuroleptic", "neuroleptic agent", "neuroleptic drug"],
    "flurazepam": ["antianxiety drug", "anxiolytic", "anxiolytic drug", "dalmane", "flurazepam hydrochloride", "minor tranquilizer", "minor tranquilliser", "minor tranquillizer"],
    "flurbiprofen": ["ansaid", "nonsteroidal anti-inflammatory", "nonsteroidal anti-inflammatory drug", "nsaid"],
    "flurry": ["move"],
    "flush": ["glow"],
    "flush toilet": ["can", "commode", "crapper", "lavatory", "pot", "potty", "stool", "throne", "toilet"],
    "flush-seamed": [],
    "flushed": ["rose-cheeked", "rosy", "rosy-cheeked"],
    "flushless toilet": ["can", "commode", "crapper", "pot", "potty", "stool", "throne", "toilet"],
    "fluster": ["acquit", "bear", "behave", "carry", "comport", "conduct", "deport"],
    "flustered": ["hot and bothered", "perturbed", "rattled"],
    "flute": ["crimp", "pinch"],
    "flutist": ["flautist", "flute player", "instrumentalist", "musician", "player"],
    "flutter": ["beat", "flap"],
    "flutter kick": ["swimming kick"],
    "fluvastatin": ["lescol", "lipid-lowering medication", "lipid-lowering medicine", "statin", "statin drug"],
    "fluvial": [],
    "flux": ["neutron flux", "radiant flux", "rate"],
    "flux applicator": ["applicator", "applier"],
    "flux density": ["denseness", "density", "flux"],
    "flux density unit": ["electromagnetic unit", "emu", "gauss", "microgauss", "tesla"],
    "flux unit": ["magnetic flux", "magnetic flux unit", "maxwell", "mx", "wb", "weber"],
    "fluxmeter": ["meter"],
    "fly": ["show"],
    "fly agaric": ["agaric", "amanita muscaria"],
    "fly ash": ["ash"],
    "fly blind": ["aviate", "fly", "pilot"],
    "fly by": ["go by", "go past", "pass", "pass by", "surpass", "travel by"],
    "fly casting": ["cast", "casting"],
    "fly contact": ["aviate", "fly", "pilot"],
    "fly gallery": ["fly floor", "platform"],
    "fly high": ["experience", "feel"],
    "fly in the face of": ["break", "fly in the teeth of", "go against", "violate"],
    "fly in the ointment": ["inconvenience", "troublesomeness", "worriment"],
    "fly on": ["fly", "wing"],
    "fly open": ["open", "open up"],
    "fly orchid": ["orchid", "orchidaceous plant"],
    "fly poison": ["amianthum muscaetoxicum", "amianthum muscitoxicum", "liliaceous plant"],
    "fly rod": ["fishing pole", "fishing rod"],
    "fly tent": ["collapsible shelter", "tent"],
    "fly-by-night": ["debitor", "debtor"],
    "fly-fish": ["angle", "flyfish"],
    "fly-fishing": ["angling"],
    "flyaway": [],
    "flyblown": ["maggoty"],
    "flycatching warbler": ["american redstart", "new world warbler", "redstart", "setophaga ruticilla", "wood warbler"],
    "flying": ["fast", "quick"],
    "flying boat": ["hydroplane", "seaplane"],
    "flying bridge": ["bridge", "bridge deck", "fly bridge", "flybridge", "monkey bridge"],
    "flying buttress": ["arc-boutant", "buttress", "buttressing"],
    "flying carpet": ["carpet", "carpeting", "rug"],
    "flying colors": ["flying colours", "success"],
    "flying dutchman": ["apparition", "fantasm", "phantasm", "phantasma", "phantom", "specter", "spectre"],
    "flying fish": ["biplane flying fish", "four-wing flying fish", "monoplane flying fish", "teleost", "teleost fish", "teleostan", "two-wing flying fish"],
    "flying fox": ["fruit bat", "megabat"],
    "flying gecko": ["fringed gecko", "gecko", "ptychozoon homalocephalum"],
    "flying gurnard": ["butterflyfish", "flying robin", "scorpaenoid", "scorpaenoid fish"],
    "flying jib": ["jib"],
    "flying lemur": ["colugo", "cynocephalus variegatus", "eutherian", "eutherian mammal", "flying cat", "placental", "placental mammal"],
    "flying mare": ["grappling", "rassling", "wrestling"],
    "flying mouse": ["flying opossum", "flying phalanger", "flying squirrel"],
    "flying phalanger": ["flying mouse", "flying opossum", "flying squirrel", "opossum", "phalanger", "possum"],
    "flying school": ["school"],
    "flying squad": ["squad", "team"],
    "flying start": ["racing start", "running start"],
    "flying visit": ["visit"],
    "flyleaf": ["folio", "leaf"],
    "flyover": ["flight", "fly-by", "flying", "flypast"],
    "flypaper": ["paper"],
    "flyspeck": ["atom", "corpuscle", "molecule", "mote", "particle", "speck"],
    "flytrap": ["trap"],
    "flyweight": ["grappler", "matman", "wrestler"],
    "flywheel": ["fluid flywheel", "governor", "regulator"],
    "foal": ["bear", "birth", "deliver", "give birth", "have"],
    "foam": ["bubble", "effervesce", "fizz", "form bubbles", "froth", "lather", "seethe", "sparkle"],
    "foam at the mouth": ["froth at the mouth", "rage"],
    "foam rubber": ["caoutchouc", "foam", "gum elastic", "india rubber", "natural rubber", "rubber"],
    "foamflower": ["coolwart", "false miterwort", "false mitrewort", "herb", "herbaceous plant", "tiarella cordifolia"],
    "foaminess": ["gaseousness"],
    "foaming": ["foamy", "frothing"],
    "fob": ["vest pocket", "watch pocket"],
    "focal": [],
    "focal distance": ["distance", "focal length"],
    "focal infection": ["infection"],
    "focal ratio": ["f number", "ratio", "speed", "stop number"],
    "focal seizure": ["ictus", "raptus", "seizure"],
    "focalization": ["focalisation", "pathogenesis"],
    "focally": [],
    "focus": ["refocus", "sharpen"],
    "focus on": ["bear on", "center", "center on", "come to", "concentrate on", "concern", "have-to doe with", "pertain", "refer", "relate", "revolve about", "revolve around", "touch", "touch on"]
}
