synonyms = {
    "designate": ["denominate"],
    "designation": ["identification"],
    "designed": ["intentional"],
    "designer": ["intriguer"],
    "designing": ["scheming"],
    "desirability": ["desirableness"],
    "desirable": ["suitable", "worthy"],
    "desire": ["want"],
    "desire to know": ["lust for learning", "thirst for knowledge"],
    "desirous": ["wishful"],
    "desk clerk": ["hotel clerk", "hotel desk clerk"],
    "desk dictionary": ["collegiate dictionary"],
    "desk sergeant": ["deskman", "station keeper"],
    "desk-bound": ["deskbound"],
    "desmanthus": ["genus desmanthus"],
    "desmidiaceae": ["family desmidiaceae"],
    "desmidium": ["genus desmidium"],
    "desmodium": ["genus desmodium"],
    "desmodontidae": ["family desmodontidae"],
    "desmodus": ["genus desmodus"],
    "desmograthus": ["genus desmograthus"],
    "desolately": ["disconsolately"],
    "despair": ["desperation"],
    "despairing": ["desperate"],
    "despairingly": ["despondently"],
    "desperado": ["desperate criminal"],
    "desperate": ["do-or-die"],
    "desperate straits": ["dire straits"],
    "despicable": ["slimy", "ugly", "unworthy", "vile", "worthless", "wretched"],
    "despisal": ["despising"],
    "despised": ["detested", "hated", "scorned"],
    "despiteful": ["spiteful", "vindictive"],
    "despitefully": ["spitefully"],
    "despoiled": ["pillaged", "raped", "ravaged", "sacked"],
    "despondency": ["despondence", "disconsolateness", "heartsickness"],
    "despondent": ["heartsick"],
    "despotic": ["despotical"],
    "desquamate": ["peel off"],
    "desquamation": ["peeling", "shedding"],
    "dessert": ["afters", "sweet"],
    "dessertspoon": ["dessertspoonful"],
    "destabilization": ["destabilisation"],
    "destabilize": ["destabilise"],
    "destalinization": ["de-stalinisation", "de-stalinization", "destalinisation"],
    "destalinize": ["destalinise"],
    "destination": ["terminus"],
    "destine": ["designate", "doom", "fate"],
    "destiny": ["fate"],
    "destitute": ["impoverished", "indigent", "necessitous", "needy", "poverty-stricken"],
    "destroy": ["destruct"],
    "destroyed": ["ruined"],
    "destroyer": ["ruiner", "undoer", "uprooter", "waster"],
    "destroying angel": ["amanita verna"],
    "destruction": ["demolition", "wipeout"],
    "destructive-metabolic": ["energy-releasing"],
    "desulfurize": ["desulphurize"],
    "desynchronize": ["desynchronise"],
    "detach": ["come away", "come off"],
    "detached": ["isolated", "separated", "set-apart"],
    "detached house": ["single dwelling"],
    "detachment": ["disengagement"],
    "detail": ["item", "particular"],
    "detailed": ["elaborate", "elaborated"],
    "details": ["inside information"],
    "detainee": ["political detainee"],
    "detect": ["discover", "find", "notice", "observe"],
    "detectable": ["noticeable"],
    "detection": ["sensing"],
    "detective": ["investigator", "police detective", "tec"],
    "detective novel": ["mystery novel"],
    "detector": ["demodulator"],
    "detention": ["custody", "detainment", "hold"],
    "detention home": ["detention camp", "detention house", "house of detention"],
    "deter": ["discourage"],
    "detergency": ["detergence"],
    "detergent": ["detersive"],
    "deterioration": ["impairment"],
    "determent": ["deterrence", "intimidation"],
    "determinant": ["causal factor", "determinative", "determiner", "determining factor"],
    "determinateness": ["definiteness"],
    "determination": ["purpose"],
    "determine": ["ascertain", "check", "find out", "learn", "see", "watch"],
    "determined": ["dictated", "set"],
    "determinedly": ["unfalteringly", "unshakably"],
    "determiner": ["determinative"],
    "detestably": ["abominably", "odiously", "repulsively"],
    "detonate": ["blow up", "explode"],
    "detonator": ["cap", "detonating device"],
    "detour": ["roundabout way"],
    "detox": ["detoxify"],
    "detoxify": ["detoxicate"],
    "detraction": ["petty criticism"],
    "detractor": ["depreciator", "disparager", "knocker"],
    "detransitivize": ["detransitivise", "intransitivise", "intransitivize"],
    "detribalization": ["detribalisation"],
    "detribalize": ["detribalise"],
    "detriment": ["hurt"],
    "detrimentally": ["harmfully", "noxiously"],
    "detroit": ["motor city", "motown"],
    "deuce": ["two"],
    "deuteranopia": ["daltonism", "green-blindness"],
    "deuteranopic": ["green-blind"],
    "deuterium": ["heavy hydrogen"],
    "deuteromycetes": ["class deuteromycetes"],
    "deuteromycota": ["deuteromycotina", "fungi imperfecti", "subdivision deuteromycota", "subdivision deuteromycotina"],
    "deuteronomy": ["book of deuteronomy"],
    "devalue": ["devaluate"],
    "devanagari": ["devanagari script", "nagari", "nagari script"],
    "devastation": ["desolation"],
    "develop": ["acquire", "evolve"],
    "developed": ["highly-developed"],
    "developing": ["underdeveloped"],
    "development": ["evolution"],
    "developmental psychology": ["child psychology", "genetic psychology"],
    "deviate": ["depart", "diverge", "vary"],
    "deviation": ["departure", "difference", "divergence"],
    "device": ["gimmick", "twist"],
    "devil": ["daemon", "daimon", "demon", "fiend"],
    "devil ray": ["mobula hypostoma"],
    "devil's food": ["devil's food cake"],
    "devil's tongue": ["amorphophallus rivieri", "snake palm", "umbrella arum"],
    "devil-may-care": ["raffish", "rakish"],
    "deviled egg": ["stuffed egg"],
    "devilish": ["rascally", "roguish"],
    "devilishly": ["devilish"],
    "devilize": ["devilise", "diabolise", "diabolize"],
    "deviltry": ["devilry"],
    "devilwood": ["american olive", "osmanthus americanus"],
    "devious": ["shifty"],
    "deviousness": ["obliqueness"],
    "devisal": ["contrivance"],
    "devising": ["fashioning", "making"],
    "devitalization": ["devitalisation"],
    "devitalize": ["devitalise"],
    "devolution": ["devolvement"],
    "devolve": ["degenerate", "deteriorate", "drop"],
    "devon": ["devonshire"],
    "devonian": ["age of fishes", "devonian period"],
    "devotion": ["devotedness"],
    "devour": ["consume", "down", "go through"],
    "devout": ["god-fearing"],
    "devoutly": ["piously"],
    "devoutness": ["religiousness"],
    "devries": ["de vries", "hugo de vries", "hugo devries"],
    "dewar": ["sir james dewar"],
    "dewar flask": ["dewar"],
    "dewberry": ["dewberry bush", "running blackberry"],
    "dewey": ["melvil dewey", "melville louis kossuth dewey"],
    "dewey decimal classification": ["decimal system of classification", "dewey decimal system"],
    "dexamethasone": ["decadron", "dexamethasone intensol", "dexone", "hexadrol", "oradexon"],
    "dexterity": ["manual dexterity", "sleight"],
    "dexterously": ["deftly", "dextrously"],
    "dextroamphetamine sulphate": ["dexedrine"],
    "dextrorotary": ["dextrorotatory", "right-handed"],
    "dextrorotation": ["clockwise rotation"],
    "dextrorse": ["dextrorsal"],
    "dextrose": ["dextroglucose", "grape sugar"],
    "dhak": ["butea frondosa", "butea monosperma", "dak", "palas"],
    "dhaka": ["capital of bangladesh", "dacca"],
    "dhawa": ["dhava"],
    "dhole": ["cuon alpinus"],
    "dhu'l-hijja": ["dhu al-hijja", "dhu al-hijjah", "dhu'l-hijjah"],
    "dhu'l-qa'dah": ["dhu al-qadah"],
    "diabetes mellitus": ["dm"],
    "diabetic coma": ["kussmaul's coma"],
    "diabolatry": ["demonolatry", "devil-worship"],
    "diabolically": ["devilishly", "fiendishly"],
    "diabolism": ["demonism", "satanism"],
    "diacalpa": ["genus diacalpa"],
    "diachronic": ["historical"],
    "diacritic": ["diacritical"],
    "diacritical mark": ["diacritic"],
    "diadophis": ["genus diadophis"],
    "diaghilev": ["sergei diaghilev", "sergei pavlovich diaghilev"],
    "diagnose": ["name"],
    "diagnosis": ["diagnosing"],
    "diagnostic": ["symptomatic"],
    "diagnostic procedure": ["diagnostic technique"],
    "diagnostic test": ["diagnostic assay"],
    "diagnostician": ["pathologist"],
    "diagonal": ["bias"],
    "diagonalization": ["diagonalisation"],
    "diagonalize": ["diagonalise"],
    "diagram": ["plot"],
    "diagrammatic": ["diagrammatical"],
    "diagrammatically": ["graphically"],
    "dial": ["telephone dial"],
    "dial telephone": ["dial phone"],
    "dialect": ["accent", "idiom"],
    "dialect atlas": ["linguistic atlas"],
    "dialect geography": ["linguistic geography"],
    "dialectic": ["dialectical"],
    "dialeurodes": ["genus dialeurodes"],
    "dialog box": ["panel"],
    "dialogue": ["dialog", "duologue"],
    "dialyse": ["dialyze"],
    "dialyzer": ["dialysis machine"],
    "diameter": ["diam"],
    "diametral": ["diametric", "diametrical"],
    "diametric": ["diametrical", "opposite", "polar"],
    "diamond": ["adamant"],
    "diamond wedding anniversary": ["diamond wedding"],
    "diamondback": ["crotalus adamanteus", "diamondback rattlesnake"],
    "diamondback terrapin": ["malaclemys centrata"],
    "diana": ["lady diana frances spencer", "princess diana", "princess of wales"],
    "diane de poitiers": ["duchesse de valentinois"],
    "dianoetic": ["discursive"],
    "dianthus": ["genus dianthus"],
    "diapason": ["diapason stop"],
    "diapensiaceae": ["diapensia family", "family diapensiaceae"],
    "diapensiales": ["order diapensiales"],
    "diaper": ["napkin", "nappy"],
    "diaper rash": ["diaper dermatitis"],
    "diaphanous": ["cobwebby", "filmy", "gauze-like", "gauzy", "gossamer", "see-through", "sheer", "transparent", "vaporous", "vapourous"],
    "diapheromera": ["diapheromera femorata"],
    "diaphoretic": ["sudorific"],
    "diaphragm": ["midriff"],
    "diaphyseal": ["diaphysial"],
    "diaphysis": ["shaft"],
    "diapsid": ["diapsid reptile"],
    "diapsida": ["subclass diapsida"],
    "diarchy": ["dyarchy"],
    "diarist": ["diary keeper", "journalist"],
    "diarrhea": ["diarrhoea", "looseness", "looseness of the bowels"],
    "diarrheal": ["diarrheic", "diarrhetic", "diarrhoeal", "diarrhoeic", "diarrhoetic"],
    "diary": ["journal"],
    "dias": ["bartholomeu dias", "bartholomeu diaz", "diaz"],
    "diaspididae": ["family diaspididae"],
    "diatomaceous earth": ["diatomite", "kieselguhr"],
    "diazepam": ["valium"],
    "diazoxide": ["hyperstat"],
    "dibble": ["dibber"],
    "dibranchiata": ["dibranchia", "subclass dibranchia", "subclass dibranchiata"],
    "dibranchiate": ["dibranch", "dibranchiate mollusk"],
    "dicamptodon": ["dicamptodontid"],
    "dicamptodontidae": ["family dicamptodontidae"],
    "dice cup": ["dice box"],
    "dicentra": ["genus dicentra"],
    "diceros": ["genus diceros"],
    "dichloride": ["bichloride"],
    "dichlorodiphenyltrichloroethane": ["ddt"],
    "dichondra": ["dichondra micrantha"],
    "dichotomization": ["dichotomisation"],
    "dichotomize": ["dichotomise"],
    "dichotomy": ["duality"],
    "dichromacy": ["dichromasy", "dichromatism", "dichromatopsia", "dichromia"],
    "dick": ["gumshoe", "hawkshaw"],
    "dickens": ["charles dickens", "charles john huffam dickens"],
    "dicker": ["bargain"],
    "dickey": ["dickey-seat", "dickie", "dickie-seat", "dicky", "dicky-seat"],
    "dickeybird": ["dickey-bird", "dicky-bird", "dickybird"],
    "dickinson": ["emily dickinson"],
    "dicksonia": ["genus dicksonia"],
    "dicksoniaceae": ["family dicksoniaceae"],
    "dicky": ["dickey"],
    "diclofenac potassium": ["cataflam"],
    "diclofenac sodium": ["voltaren"],
    "dicloxacillin": ["dynapen"],
    "dicot": ["dicotyledon", "exogen", "magnoliopsid"],
    "dicot family": ["magnoliopsid family"],
    "dicot genus": ["magnoliopsid genus"],
    "dicotyledones": ["class dicotyledonae", "class dicotyledones", "class magnoliopsida", "dicotyledonae", "magnoliopsida"],
    "dicranaceae": ["family dicranaceae"],
    "dicranales": ["order dicranales"],
    "dicranopteris": ["genus dicranopteris"],
    "dicranum": ["genus dicranum"],
    "dicrostonyx": ["genus dicrostonyx"],
    "dictamnus": ["genus dictamnus"],
    "dictator": ["potentate"],
    "dictatorially": ["autocratically", "magisterially"],
    "dictatorship": ["absolutism", "authoritarianism", "caesarism", "despotism", "monocracy", "one-man rule", "shogunate", "stalinism", "totalitarianism", "tyranny"],
    "dictionary": ["lexicon"],
    "dictyophera": ["genus dictyophera"],
    "dictyoptera": ["order dictyoptera"],
    "dicumarol": ["dicoumarol"],
    "dicynodontia": ["division dicynodontia"],
    "didactic": ["didactical"],
    "didactically": ["pedagogically"],
    "didelphidae": ["family didelphidae"],
    "didelphis": ["genus didelphis"],
    "dideoxycytosine": ["ddc", "zalcitabine"],
    "dideoxyinosine": ["ddi", "didanosine"],
    "diderot": ["denis diderot"],
    "didion": ["joan didion"],
    "die": ["die out"],
    "die back": ["die down"],
    "die out": ["die off"],
    "die-hard": ["rock-ribbed"],
    "dieffenbachia": ["genus dieffenbachia"],
    "diemaker": ["die-sinker", "diesinker"],
    "diencephalon": ["betweenbrain", "interbrain", "thalmencephalon"],
    "diervilla": ["genus diervilla"],
    "diesel": ["rudolf christian karl diesel", "rudolf diesel"],
    "diesel oil": ["diesel fuel"],
    "diesel-electric locomotive": ["diesel-electric"],
    "diesel-hydraulic locomotive": ["diesel-hydraulic"],
    "diestrous": ["diestrual", "dioestrous", "dioestrual"],
    "diestrus": ["diestrum"],
    "diet": ["dieting"],
    "dietary": ["dietetic", "dietetical"],
    "diethylaminoethyl cellulose": ["deae cellulose"],
    "diethylstilbesterol": ["des", "stilbesterol"],
    "diethylstilbestrol": ["des", "diethylstilboestrol", "stilbestrol", "stilboestrol"],
    "dietician": ["dietitian", "nutritionist"],
    "dietrich": ["maria magdalene von losch", "marlene dietrich"],
    "difference threshold": ["difference limen", "differential limen", "differential threshold"],
    "differential calculus": ["method of fluxions"],
    "differential gear": ["differential"],
    "differentiation": ["distinction"],
    "differentiator": ["discriminator"],
    "differently": ["other than", "otherwise"],
    "difficult": ["hard"],
    "difficulty": ["difficultness"],
    "diffidence": ["self-distrust", "self-doubt"],
    "diffident": ["shy", "timid", "unsure"],
    "diffraction grating": ["grating"],
    "diffuse": ["fan out", "spread", "spread out"],
    "diffuse nebula": ["gaseous nebula"],
    "diffuser": ["diffusor"],
    "diffusing": ["diffusive", "dispersive", "disseminative"],
    "diflunisal": ["dolobid"],
    "dig": ["dig out", "dig up"],
    "digest": ["abide", "bear", "brook", "endure", "put up", "stand", "stick out", "stomach", "suffer", "support", "tolerate"],
    "digestibility": ["digestibleness"],
    "digestive juice": ["digestive fluid"],
    "digestive system": ["gastrointestinal system", "systema alimentarium", "systema digestorium"],
    "diggings": ["digs"],
    "digit": ["figure"],
    "digital arteries": ["arteria digitalis"],
    "digital audiotape": ["dat"],
    "digital communication": ["data communication"],
    "digital display": ["alphanumeric display"],
    "digital subscriber line": ["dsl"],
    "digital vein": ["vena digitalis"],
    "digital-analog converter": ["digital-to-analog converter"],
    "digitalis": ["digitalin", "digitalis glycoside"],
    "digitalization": ["digitalisation"],
    "digitaria": ["genus digitaria"],
    "digitate": ["fingerlike"],
    "digitigrade mammal": ["digitigrade"],
    "digitization": ["digitisation"],
    "digitize": ["digitalise", "digitalize", "digitise"],
    "digitizer": ["analog-digital converter", "analog-to-digital converter", "digitiser"],
    "dignified": ["self-respectful", "self-respecting"],
    "dignifying": ["ennobling"],
    "dignity": ["gravitas", "lordliness"],
    "digoxin": ["lanoxin"],
    "digraph": ["digram"],
    "digress": ["divagate", "stray", "wander"],
    "digression": ["aside", "divagation", "excursus", "parenthesis"],
    "digressive": ["tangential"],
    "dike": ["dyke"],
    "dilapidation": ["ruin"],
    "dilatation": ["distension", "distention"],
    "dilate": ["distend"],
    "dilation": ["dilatation"],
    "dilation and curettage": ["d and c", "dilatation and curettage"],
    "dilator": ["dilater"],
    "dilatoriness": ["procrastination"],
    "dilatory": ["laggard", "pokey", "poky"],
    "dilemma": ["quandary"],
    "dilettante": ["dilettanteish", "dilettantish", "sciolistic"],
    "diligence": ["industriousness", "industry"],
    "diligent": ["persevering"],
    "dill": ["anethum graveolens"],
    "dilleniaceae": ["family dilleniaceae"],
    "dilleniidae": ["subclass dilleniidae"],
    "diltiazem": ["cardizem"],
    "dilutant": ["diluent", "thinner"],
    "dilute": ["cut", "reduce", "thin", "thin out"],
    "diluted": ["dilute"],
    "diluvian": ["diluvial"],
    "dim": ["dip"],
    "dim-sighted": ["near-blind", "purblind", "sand-blind", "visually challenged", "visually impaired"],
    "dim-witted": ["simple", "simple-minded"],
    "dimaggio": ["joe dimaggio", "joseph paul dimaggio"],
    "dimash": ["capital of syria", "damascus"],
    "dime bag": ["dime"],
    "dime novel": ["penny dreadful"],
    "dimenhydrinate": ["dramamine"],
    "diminish": ["belittle"],
    "diminished": ["lessened", "vitiated", "weakened"],
    "diminutiveness": ["minuteness", "petiteness", "tininess", "weeness"],
    "dimly": ["murkily"],
    "dimmed": ["dim"],
    "dimness": ["duskiness"],
    "dimocarpus": ["genus dimocarpus"],
    "dimorphic": ["dimorphous"],
    "dimorphotheca": ["genus dimorphotheca"],
    "dimpled chad": ["dimple", "pregnant chad"],
    "dimwit": ["doofus", "half-wit", "nitwit"],
    "dinesen": ["baroness karen blixen", "blixen", "isak dinesen", "karen blixen"],
    "ding": ["dingdong", "dong"],
    "dinge": ["batter"],
    "dinghy": ["dory", "rowboat"],
    "dingily": ["grubbily", "grungily"],
    "dinginess": ["dinge"],
    "dingo": ["canis dingo", "warragal", "warrigal"],
    "dining car": ["buffet car", "diner", "dining compartment"],
    "dining room": ["dining-room"],
    "dining table": ["board"],
    "dining-room attendant": ["restaurant attendant"],
    "diningroom suite": ["diningroom set"],
    "dinky": ["dinkey"],
    "dinner": ["dinner party"],
    "dinner dress": ["dinner gown", "evening gown", "formal"],
    "dinner jacket": ["black tie", "tux", "tuxedo"],
    "dinner pail": ["dinner bucket"],
    "dinner service": ["dinner set"],
    "dinner theater": ["dinner theatre"],
    "dinnertime": ["suppertime"],
    "dinoceras": ["uintathere"],
    "dinocerata": ["order dinocerata"],
    "dinoflagellata": ["cilioflagellata", "order cilioflagellata", "order dinoflagellata"],
    "dinornis": ["genus dinornis"],
    "dinornithidae": ["family dinornithidae"],
    "dinornithiformes": ["order dinornithiformes"],
    "diocese": ["bishopric", "episcopate"],
    "diocletian": ["gaius aurelius valerius diocletian"],
    "diode": ["rectifying tube", "rectifying valve"],
    "diodon": ["genus diodon"],
    "diodontidae": ["family diodontidae"],
    "dioecious": ["dioecian"],
    "diol": ["dihydric alcohol", "glycol"],
    "diomedeidae": ["family diomedeidae"],
    "dionaea": ["genus dionaea"],
    "dionysia": ["bacchanalia"],
    "dionysius": ["dionysius the elder"],
    "diopter": ["dioptre"],
    "dior": ["christian dior"],
    "dioscorea": ["genus dioscorea"],
    "dioscoreaceae": ["family dioscoreaceae", "yam family"],
    "diospyros": ["genus diospyros"],
    "dip": ["sink"],
    "dip switch": ["dual inline package switch"],
    "diphenhydramine": ["benadryl"],
    "diphenylhydantoin": ["dilantin", "phenytoin"],
    "diphthongize": ["diphthongise"],
    "diphylla": ["genus diphylla"],
    "diploic vein": ["vena diploica"],
    "diploma": ["sheepskin"],
    "diplomacy": ["diplomatic negotiations"],
    "diplomat": ["diplomatist"],
    "diplomatic": ["diplomatical"],
    "diplomatic service": ["corps diplomatique", "diplomatic corps"],
    "diplopia": ["double vision"],
    "diplopoda": ["class diplopoda", "class myriapoda", "myriapoda"],
    "diplopterygium": ["genus diplopterygium"],
    "diplotaxis": ["genus diplotaxis"],
    "dipnoi": ["subclass dipnoi"],
    "dipodidae": ["family dipodidae"],
    "dipodomys": ["genus dipodomys"],
    "dipogon": ["genus dipogon"],
    "dipole": ["dipole antenna"],
    "dipped": ["lordotic", "swayback", "swaybacked"],
    "dipsacaceae": ["family dipsacaceae"],
    "dipsacus": ["genus dipsacus"],
    "dipsomania": ["alcoholism", "potomania"],
    "dipsosaurus": ["genus dipsosaurus"],
    "diptera": ["order diptera"],
    "dipterocarpaceae": ["family dipterocarpaceae"],
    "dipteronia": ["genus dipteronia"],
    "dipterous insect": ["dipteran", "dipteron", "two-winged insects"],
    "dipus": ["genus dipus"],
    "dipylon gate": ["dipylon"],
    "dirac": ["paul adrien maurice dirac"],
    "dirca": ["genus dirca"],
    "direct": ["verbatim"],
    "direct current": ["dc", "direct electric current"],
    "direct discourse": ["direct quotation"],
    "direct dye": ["substantive dye"],
    "direct object": ["object of the verb"],
    "direct trust": ["express trust"],
    "directing": ["directional", "directive", "guiding"],
    "direction": ["way"],
    "directivity": ["directiveness"],
    "directly": ["flat", "straight"],
    "directness": ["straightness"],
    "director": ["theater director", "theatre director"],
    "director of central intelligence": ["dci"],
    "directorate": ["board of directors"],
    "directorate for inter-services intelligence": ["inter-services intelligence", "isi"],
    "dirge": ["coronach", "lament", "requiem", "threnody"],
    "dirt": ["filth", "grease", "grime", "grunge", "soil", "stain"],
    "dirtily": ["filthily"],
    "dirtiness": ["uncleanness"],
    "dirty": ["begrime", "bemire", "colly", "grime", "soil"],
    "dirty joke": ["blue joke", "blue story", "dirty story"],
    "dirty linen": ["dirty laundry"],
    "dis": ["orcus"],
    "disability": ["disablement", "handicap", "impairment"],
    "disability check": ["disability payment"],
    "disable": ["disenable", "incapacitate"],
    "disabled": ["handicapped"],
    "disabling": ["disqualifying"],
    "disabused": ["undeceived"],
    "disadvantage": ["disfavor", "disfavour"],
    "disaffected": ["ill-affected", "malcontent", "rebellious"],
    "disagree": ["disaccord", "discord"],
    "disagreeable": ["unsympathetic"],
    "disagreement": ["dissension", "dissonance"],
    "disappear": ["go away", "vanish"],
    "disappearance": ["disappearing"],
    "disappoint": ["let down"],
    "disappointing": ["dissatisfactory", "unsatisfying"],
    "disappointment": ["letdown"],
    "disapprobation": ["condemnation"],
    "disapprove": ["reject"],
    "disarm": ["unarm"],
    "disarming": ["disarmament"],
    "disarray": ["disorderliness"],
    "disassemble": ["break apart", "break up", "dismantle", "take apart"],
    "disassociate": ["disjoint", "dissociate", "disunite", "divorce"],
    "disavowal": ["disclaimer"],
    "disband": ["dissolve"],
    "disbelieve": ["discredit"],
    "disbeliever": ["nonbeliever", "unbeliever"],
    "disbelieving": ["sceptical", "skeptical", "unbelieving"],
    "disburse": ["pay out"],
    "discalced": ["discalceate", "unshod"],
    "discard": ["cast aside", "cast away", "cast out", "chuck out", "dispose", "fling", "put away", "throw away", "throw out", "toss", "toss away", "toss out"],
    "discernability": ["legibility"],
    "discernible": ["evident", "observable"],
    "discerning": ["discreet"],
    "discernment": ["perceptiveness"],
    "discerp": ["lop", "sever"],
    "discharge": ["muster out"],
    "discharged": ["dismissed", "fired", "laid-off", "pink-slipped"],
    "disciotis venosa": ["cup morel"],
    "disciple": ["adherent"],
    "discipline": ["check", "condition", "train"],
    "disclose": ["expose"],
    "disclosure": ["revealing", "revelation"],
    "disco": ["disco music"],
    "discocephali": ["order discocephali"],
    "discoglossidae": ["family discoglossidae"],
    "discoid": ["disc-shaped", "disclike", "discoidal", "disk-shaped", "disklike"],
    "discoid lupus erythematosus": ["dle"],
    "discolor": ["color", "colour", "discolour"],
    "discoloration": ["discolouration"],
    "discombobulated": ["disconcerted"],
    "discomfiture": ["discomposure", "disconcertion", "disconcertment"],
    "discomfort": ["uncomfortableness"],
    "discomycete": ["cup fungus"],
    "discomycetes": ["subclass discomycetes"],
    "disconcerting": ["upsetting"],
    "disconfirming": ["invalidating"],
    "disconnected": ["disunited", "fragmented", "split"],
    "disconnection": ["disjunction"],
    "discontented": ["discontent"],
    "discontentment": ["discontent", "discontentedness"],
    "discontinuance": ["discontinuation"],
    "discontinue": ["cease", "give up", "lay off", "quit", "stop"],
    "discontinuous": ["noncontinuous"],
    "discord": ["strife"],
    "discordance": ["discord"],
    "discordant": ["disharmonious", "dissonant", "inharmonic"],
    "discordantly": ["unharmoniously"],
    "discorporate": ["bodiless", "disembodied", "unbodied", "unembodied"],
    "discount": ["deduction", "price reduction"],
    "discount house": ["discount store", "discounter", "wholesale house"],
    "discount rate": ["bank discount", "discount"],
    "discouragement": ["disheartenment", "dismay"],
    "discourse": ["discuss", "talk about"],
    "discourteous": ["ungracious"],
    "discourtesy": ["rudeness"],
    "discover": ["find"],
    "discovery": ["breakthrough", "find"],
    "discredit": ["disgrace"],
    "discredited": ["damaged"],
    "discrepancy": ["variance", "variant"],
    "discrepant": ["incompatible"],
    "discrete": ["distinct"],
    "discreteness": ["distinctness", "separateness", "severalty"],
    "discretion": ["circumspection", "discreetness", "prudence"],
    "discretionary": ["discretional"],
    "discriminate": ["separate", "single out"],
    "discrimination": ["secernment"],
    "discriminative": ["discriminatory"],
    "discriminative stimulus": ["cue"],
    "discriminatory": ["invidious"],
    "discursively": ["ramblingly"],
    "discus": ["saucer"],
    "discussion": ["give-and-take", "word"],
    "disdainful": ["haughty", "imperious", "lordly", "overbearing", "prideful", "sniffy", "supercilious", "swaggering"],
    "disdainfully": ["cavalierly"],
    "diseased": ["morbid", "pathologic", "pathological"],
    "disembark": ["debark", "set down"],
    "disembowel": ["draw", "eviscerate"],
    "disembowelment": ["evisceration"],
    "disenchant": ["disillusion"],
    "disenchanting": ["disillusioning"],
    "disenchantment": ["disillusion", "disillusionment"],
    "disenfranchise": ["disfranchise"],
    "disenfranchised": ["disfranchised", "voiceless", "voteless"],
    "disengage": ["withdraw"],
    "disengagement": ["fallback", "pullout"],
    "disentangle": ["straighten out", "unsnarl"],
    "disentangled": ["loosened", "unsnarled"],
    "disentangler": ["unraveler", "unraveller"],
    "disfavor": ["disfavour"],
    "disfigurement": ["deformity", "disfiguration"],
    "disgraceful": ["scandalous", "shameful", "shocking"],
    "disgracefully": ["discreditably", "dishonorably", "dishonourably", "ignominiously", "ingloriously", "shamefully"],
    "disgruntled": ["dissatisfied"],
    "disguise": ["mask"],
    "disgust": ["gross out", "repel", "revolt"],
    "disgusted": ["fed up", "sick", "sick of", "tired of"],
    "disgusting": ["disgustful", "distasteful", "foul", "loathly", "loathsome", "repellant", "repellent", "repelling", "revolting", "skanky", "wicked", "yucky"],
    "disgustingly": ["distastefully", "revoltingly", "sickeningly"],
    "disgustingness": ["distastefulness", "nauseatingness", "sickeningness", "unsavoriness"],
    "dish": ["dishful"],
    "dish the dirt": ["gossip"],
    "dishabille": ["deshabille"],
    "disharmonize": ["dissonate"],
    "disharmony": ["inharmoniousness"],
    "dishearten": ["put off"],
    "dished": ["dish-shaped", "patelliform"],
    "disheveled": ["dishevelled", "frowzled", "rumpled", "tousled"],
    "dishonest": ["dishonorable"],
    "dishonestly": ["deceitfully", "venally"],
    "dishonesty": ["knavery"],
    "dishonor": ["attaint", "disgrace", "dishonour", "shame"],
    "dishonorable": ["dishonourable"],
    "dishonorableness": ["dishonourableness"],
    "dishrag": ["dishcloth"],
    "dishtowel": ["dish towel", "tea towel"],
    "dishwasher": ["dish washer", "dishwashing machine"],
    "dishwasher detergent": ["dishwashing detergent", "dishwashing liquid"],
    "dishwashing": ["washup"],
    "disincentive": ["deterrence"],
    "disinfectant": ["antimicrobial", "antimicrobic", "germicide"],
    "disingenuous": ["artful"],
    "disingenuously": ["artfully"],
    "disinherit": ["disown"],
    "disintegrate": ["decay", "decompose"],
    "disinter": ["exhume"],
    "disinterest": ["neutrality"],
    "disinvolve": ["disembroil", "disentangle"],
    "disjoin": ["disjoint"],
    "disjoined": ["separate"],
    "disjoint": ["disarticulate"],
    "disjointed": ["dislocated", "separated"],
    "disjunct": ["isolated"],
    "disjunction": ["disconnectedness", "disconnection", "disjuncture"],
    "disk": ["disc", "saucer"],
    "disk brake": ["disc brake"],
    "disk drive": ["disc drive", "hard drive", "winchester drive"],
    "disk harrow": ["disc harrow"],
    "disk jockey": ["disc jockey", "dj"],
    "disk overhead": ["overhead"],
    "disk pack": ["disc pack"],
    "disk space": ["disc space"],
    "disk-jockey": ["disc-jockey", "dj"],
    "diskette": ["floppy", "floppy disk"],
    "dislocate": ["luxate", "slip", "splay"],
    "dislocation": ["disruption"],
    "dislodge": ["free"],
    "dislodgment": ["dislodgement"],
    "dismally": ["drearily"],
    "dismantling": ["disassembly", "dismantlement"],
    "dismay": ["alarm", "appal", "appall", "horrify"],
    "dismember": ["discerp", "take apart"],
    "dismemberment": ["taking apart"],
    "dismiss": ["drop", "send away", "send packing"],
    "dismissal": ["dismission", "pink slip"],
    "disney": ["walt disney", "walter elias disney"],
    "disobedience": ["noncompliance"],
    "disobedient": ["unruly"],
    "disobliging": ["uncooperative"],
    "disorder": ["disarray"],
    "disordered": ["unordered"],
    "disorderliness": ["disorder"],
    "disorderly": ["higgledy-piggledy", "hugger-mugger", "jumbled", "topsy-turvy"],
    "disorderly conduct": ["breach of the peace", "disorderly behavior", "disturbance of the peace"],
    "disorganization": ["disarrangement", "disorganisation"],
    "disorganize": ["disorganise"],
    "disorganized": ["disorganised"],
    "disorient": ["disorientate"],
    "disorientation": ["freak out"],
    "disown": ["renounce", "repudiate"],
    "disownment": ["disowning"],
    "disparage": ["belittle", "pick at"],
    "disparagement": ["depreciation", "derogation"],
    "disparagingly": ["slightingly"],
    "disparateness": ["distinctiveness"],
    "dispassion": ["dispassionateness", "dryness"],
    "dispassionate": ["cold-eyed"],
    "dispatch": ["complete", "discharge"],
    "dispatch case": ["dispatch box"],
    "dispensability": ["dispensableness"],
    "disperse": ["break up", "dispel", "dissipate", "scatter"],
    "dispersed": ["spread"],
    "dispersed phase": ["dispersed particles"],
    "dispersing phase": ["dispersing medium", "dispersion medium"],
    "dispersion": ["scattering"],
    "dispirited": ["listless"],
    "dispiritedly": ["hopelessly"],
    "displace": ["can", "dismiss", "fire", "force out", "give notice", "give the axe", "give the sack", "sack", "send away", "terminate"],
    "displaced person": ["dp", "stateless person"],
    "displacement": ["displacement reaction"],
    "display": ["show"],
    "display adapter": ["display adaptor"],
    "display panel": ["board", "display board"],
    "display window": ["shop window", "shopwindow", "show window"],
    "disposal": ["electric pig", "garbage disposal"],
    "dispose": ["incline"],
    "disposed": ["fain", "inclined", "prepared"],
    "disposition": ["temperament"],
    "dispossessed": ["homeless", "roofless"],
    "disproof": ["falsification", "refutation"],
    "disproportionate": ["disproportional"],
    "disprove": ["confute"],
    "disputant": ["controversialist", "eristic"],
    "disputatiously": ["argumentatively"],
    "dispute": ["conflict", "difference", "difference of opinion"],
    "disqualify": ["indispose", "unfit"],
    "disquiet": ["unease", "uneasiness"],
    "disquieted": ["distressed", "disturbed", "upset", "worried"],
    "disraeli": ["benjamin disraeli", "first earl of beaconsfield"],
    "disregard": ["neglect"],
    "disregarded": ["forgotten"],
    "disrepute": ["discredit"],
    "disrespect": ["disesteem"],
    "disrupting explosive": ["bursting explosive"],
    "disruption": ["perturbation"],
    "disruptive": ["riotous", "troubled", "tumultuous", "turbulent"],
    "diss": ["affront", "insult"],
    "dissemble": ["cloak", "mask"],
    "dissemination": ["airing", "public exposure", "spreading"],
    "dissenter": ["contestant", "dissident", "objector", "protester"],
    "dissentient": ["recusant"],
    "dissentious": ["divisive", "factious"],
    "dissertation": ["thesis"],
    "disservice": ["ill service", "ill turn"],
    "dissident": ["heretical", "heterodox"],
    "dissimilarity": ["unsimilarity"],
    "dissipated": ["betting", "card-playing", "sporting"],
    "dissociable": ["separable", "severable"],
    "dissociation": ["disassociation"],
    "dissolubility": ["solubleness"],
    "dissoluteness": ["incontinence", "self-gratification"],
    "dissolution": ["disintegration"],
    "dissolvable": ["dissoluble"],
    "dissolve": ["fade away", "fade out"],
    "dissolving": ["dissolution"],
    "dissuade": ["deter"],
    "distance": ["space"],
    "distant": ["remote"],
    "distasteful": ["unsavory", "unsavoury"],
    "distention": ["distension"],
    "distill": ["distil", "extract"],
    "distillate": ["distillation"],
    "distillation": ["distillment"],
    "distillery": ["still"],
    "distinct": ["distinguishable"],
    "distinctive": ["typical"],
    "distinctly": ["clearly"],
    "distinctness": ["sharpness"],
    "distinguish": ["differentiate", "mark"],
    "distinguished": ["grand", "imposing", "magisterial"],
    "distorted": ["misrepresented", "perverted", "twisted"],
    "distorted shape": ["distortion"],
    "distortion": ["deformation"],
    "distract": ["deflect"],
    "distracted": ["distrait"],
    "distraction": ["misdirection"],
    "distraught": ["overwrought"],
    "distress": ["hurt", "suffering"],
    "distress signal": ["distress call"],
    "distressed": ["hard put", "hard-pressed", "in a bad way"],
    "distressing": ["distressful", "disturbing", "perturbing", "troubling", "worrisome", "worrying"],
    "distribute": ["administer", "allot", "deal", "deal out", "dish out", "dispense", "dole out", "lot", "mete out", "parcel out", "shell out"],
    "distributed data processing": ["remote-access data processing", "teleprocessing"],
    "distribution": ["statistical distribution"],
    "distribution channel": ["channel"],
    "distributor": ["distributer"],
    "distributor point": ["breaker point", "point"],
    "district": ["dominion", "territorial dominion", "territory"],
    "district attorney": ["da"],
    "district of columbia": ["d.c.", "dc"],
    "distrust": ["mistrust", "suspect"],
    "distrustfully": ["mistrustfully"],
    "disturb": ["trouble", "upset"],
    "disturbance": ["perturbation", "upset"],
    "disturbed": ["maladjusted"],
    "disulfiram": ["antabuse"],
    "disunify": ["break apart"],
    "disused": ["obsolete"],
    "disyllable": ["dissyllable"],
    "dita": ["alstonia scholaris", "devil tree", "dita bark"],
    "ditch digger": ["mud digger"],
    "ditch reed": ["carrizo", "common reed", "phragmites communis"],
    "ditch spade": ["long-handled spade"],
    "dither": ["flap", "pother"],
    "dittany of crete": ["cretan dittany", "crete dittany", "hop marjoram", "origanum dictamnus", "winter sweet"],
    "ditto mark": ["ditto"],
    "diuretic drug": ["diuretic", "water pill"],
    "divan": ["diwan"],
    "dive": ["plunge", "plunk"],
    "diver": ["frogman", "underwater diver"],
    "divergence": ["divergency"],
    "divergent": ["diverging"],
    "divergent thinking": ["out-of-the-box thinking"],
    "diverging lens": ["concave lens"],
    "divers": ["diverse"],
    "diverse": ["various"],
    "diverseness": ["diversity", "multifariousness", "variety"],
    "diversification": ["variegation"],
    "diversify": ["radiate"],
    "diversion": ["diversionary attack"],
    "divert": ["hive off"],
    "divertimento": ["serenade"],
    "divest": ["disinvest"],
    "divi-divi": ["caesalpinia coriaria"],
    "divide": ["carve up", "dissever", "separate", "split", "split up"],
    "divided": ["dual-lane"],
    "divided highway": ["dual carriageway"],
    "divination": ["foretelling", "fortune telling", "soothsaying"],
    "divinatory": ["mantic", "sibyllic", "sibylline", "vatic", "vatical"],
    "divine": ["godlike"],
    "divine comedy": ["divina commedia"],
    "divine guidance": ["inspiration"],
    "divine right": ["divine right of kings"],
    "diving": ["diving event"],
    "diving suit": ["diving dress"],
    "divining rod": ["dowser", "dowsing rod", "water finder", "waterfinder"],
    "divinity": ["divinity fudge"],
    "division": ["air division"],
    "divisor": ["factor"],
    "divorce": ["split up"],
    "divorcee": ["grass widow"],
    "divulgence": ["divulgement"],
    "dix": ["dorothea dix", "dorothea lynde dix"],
    "dixie cup": ["paper cup"],
    "dizygotic": ["dizygous"],
    "dizzily": ["giddily", "light-headedly"],
    "dizziness": ["giddiness", "lightheadedness", "vertigo"],
    "dizzy": ["giddy", "vertiginous", "woozy"],
    "djibouti": ["capital of djibouti"],
    "dna fingerprint": ["genetic fingerprint"],
    "dnieper": ["dnieper river"],
    "dnipropetrovsk": ["yekaterinoslav"],
    "do": ["come", "fare", "get along", "make out"],
    "do well": ["had best"],
    "doberman": ["doberman pinscher"],
    "dobrich": ["tolbukhin"],
    "dobson": ["corydalus cornutus", "dobson fly", "dobsonfly"],
    "docile": ["teachable"],
    "dock": ["bob", "tail"],
    "dockage": ["docking fee"],
    "docking": ["dockage", "moorage", "tying up"],
    "doctor": ["dr."],
    "doctor of arts": ["artsd"],
    "doctor of dental medicine": ["dmd"],
    "doctor of dental surgery": ["dds"],
    "doctor of divinity": ["dd"],
    "doctor of education": ["ded", "edd"],
    "doctor of laws": ["lld"],
    "doctor of medicine": ["md"],
    "doctor of music": ["dmus", "musd"],
    "doctor of musical arts": ["amusd"],
    "doctor of optometry": ["od"],
    "doctor of osteopathy": ["do"],
    "doctor of public health": ["dph"],
    "doctor of sacred theology": ["std"],
    "doctor of science": ["ds", "scd"],
    "doctor of the church": ["doctor"],
    "doctor of theology": ["thd"],
    "doctor's degree": ["doctorate"],
    "doctoral": ["doctorial"],
    "doctorfish": ["acanthurus chirurgus", "doctor-fish"],
    "doctorow": ["e. l. doctorow", "edgard lawrence doctorow"],
    "doctrine": ["ism", "philosophical system", "philosophy", "school of thought"],
    "doctrine of analogy": ["analogy"],
    "document": ["papers", "written document"],
    "documentary": ["docudrama", "documentary film", "infotainment"],
    "documentation": ["certification", "corroboration"],
    "doddering": ["doddery", "gaga", "senile"],
    "dodecanese": ["dhodhekanisos"],
    "dodge": ["dodging", "scheme"],
    "dodger": ["fox", "slyboots"],
    "dodo": ["fogey", "fogy", "fossil"],
    "dodonaea": ["genus dodonaea"],
    "dog": ["canis familiaris", "domestic dog"],
    "dog days": ["canicular days", "canicule"],
    "dog fennel": ["eupatorium capillifolium"],
    "dog flea": ["ctenocephalides canis"],
    "dog grass": ["agropyron repens", "couch grass", "quack grass", "quackgrass", "quick grass", "witch grass", "witchgrass"],
    "dog laurel": ["dog hobble", "leucothoe editorum", "leucothoe fontanesiana", "switch-ivy"],
    "dog rose": ["rosa canina"],
    "dog shit": ["dog do", "dog turd", "doggy do"],
    "dog stinkhorn": ["mutinus caninus"],
    "dog violet": ["heath violet", "viola canina"],
    "dog's breakfast": ["dog's dinner"],
    "dog's mercury": ["dog mercury", "mercurialis perennis"],
    "dog-day cicada": ["harvest fly"],
    "dog-eared": ["eared"],
    "dogged": ["dour", "persistent", "pertinacious", "tenacious", "unyielding"],
    "doggedly": ["tenaciously"],
    "doggedness": ["perseverance", "persistence", "persistency", "pertinacity", "tenaciousness", "tenacity"],
    "doggerel": ["doggerel verse", "jingle"],
    "doggie bag": ["doggy bag"],
    "dogging": ["persisting"],
    "doggo": ["in hiding", "out of sight"],
    "dogie": ["dogy", "leppy"],
    "dogma": ["tenet"],
    "dogmatic": ["dogmatical"],
    "dogmatist": ["doctrinaire"],
    "dogmatize": ["dogmatise"],
    "dogsled": ["mush"],
    "dogtooth violet": ["dog's-tooth violet", "dogtooth"],
    "dogwood": ["cornel", "dogwood tree"],
    "doha": ["bida", "capital of qatar", "el beda"],
    "doily": ["doyley", "doyly"],
    "dolabriform": ["dolabrate"],
    "dolby": ["ray m. dolby"],
    "dole": ["pogey", "pogy"],
    "doleful": ["mournful"],
    "dolefully": ["sorrowfully"],
    "dolichocephalic": ["dolichocranial", "dolichocranic"],
    "dolichocephaly": ["dolichocephalism"],
    "dolichonyx": ["genus dolichonyx"],
    "dolichos": ["genus dolichos"],
    "dolichotis": ["genus dolichotis"],
    "doliolidae": ["family doliolidae"],
    "doll": ["dolly"],
    "doll up": ["do up", "glam up", "pretty up"],
    "dollar": ["buck", "clam", "dollar bill", "one dollar bill"],
    "dollar mark": ["dollar sign"],
    "dollar volume": ["turnover"],
    "dollarfish": ["poronotus triacanthus"],
    "dollhouse": ["doll's house"],
    "dolman": ["dolman jacket"],
    "dolmas": ["stuffed grape leaves"],
    "dolmen": ["cromlech", "portal tomb"],
    "dolomite": ["bitter spar"],
    "dolor": ["dolour"],
    "dolorous": ["dolourous", "lachrymose", "tearful", "weeping"],
    "dolphin striker": ["martingale"],
    "dolphinfish": ["mahimahi"],
    "domain": ["demesne", "land"],
    "dome": ["covered stadium", "domed stadium"],
    "domed": ["vaulted"],
    "domesday book": ["doomsday book"],
    "domestic": ["domestic help", "house servant"],
    "domestic animal": ["domesticated animal"],
    "domestic ass": ["donkey", "equus asinus"],
    "domestic carp": ["cyprinus carpio"],
    "domestic cat": ["felis catus", "felis domesticus", "house cat"],
    "domestic fowl": ["fowl", "poultry"],
    "domestic goat": ["capra hircus"],
    "domestic llama": ["lama peruana"],
    "domestic partner": ["significant other", "spousal equivalent", "spouse equivalent"],
    "domestic sheep": ["ovis aries"],
    "domestic silkworm moth": ["bombyx mori", "domesticated silkworm moth"],
    "domesticate": ["cultivate", "naturalise", "naturalize", "tame"],
    "domicile": ["legal residence"],
    "dominance": ["ascendance", "ascendancy", "ascendence", "ascendency", "control"],
    "dominant allele": ["dominant"],
    "dominate": ["command", "overlook", "overtop"],
    "dominated": ["henpecked"],
    "domination": ["mastery", "supremacy"],
    "domingo": ["placido domingo"],
    "dominic": ["domingo de guzman", "saint dominic", "st. dominic"],
    "dominica": ["commonwealth of dominica"],
    "dominican": ["black friar", "blackfriar", "friar preacher"],
    "dominican peso": ["peso"],
    "dominion": ["rule"],
    "dominion day": ["july 1"],
    "dominique": ["dominick"],
    "domino": ["antoine domino", "fats domino"],
    "dominoes": ["dominos"],
    "dominus": ["domine", "dominee", "dominie"],
    "domitian": ["titus flavius domitianus"],
    "don": ["father"],
    "donatello": ["donato di betto bardi"],
    "donatus": ["aelius donatus"],
    "done": ["through", "through with"],
    "done for": ["ruined", "sunk", "undone", "washed-up"],
    "done with": ["through with"],
    "donets basin": ["donbas", "donbass"],
    "donetsk": ["donetske", "stalino"],
    "donizetti": ["gaetano donizetti"],
    "donkin": ["bryan donkin"],
    "donne": ["john donne"],
    "donnean": ["donnian"],
    "donor": ["bestower", "conferrer", "giver", "presenter"],
    "doodad": ["doohickey", "doojigger", "gimmick", "gismo", "gizmo", "gubbins", "thingamabob", "thingamajig", "thingmabob", "thingmajig", "thingumabob", "thingumajig", "thingummy", "whatchamacallit", "whatchamacallum", "whatsis", "widget"],
    "doodia": ["rasp fern"],
    "doodlebug": ["ant lion", "antlion"],
    "doolittle": ["james harold doolittle", "jimmy doolittle"],
    "doom": ["day of reckoning", "doomsday", "end of the world"],
    "doomed": ["lost"],
    "door-to-door": ["house-to-house"],
    "doorbell": ["bell", "buzzer"],
    "doorframe": ["doorcase"],
    "doorjamb": ["doorpost"],
    "doorkeeper": ["ostiarius", "ostiary"],
    "doorknob": ["doorhandle"]
}
