synonyms = {
    "ape": ["imitate"],
    "ape-man": ["feral man", "wild man"],
    "apeldoorn": [],
    "apennines": [],
    "apercu": ["abstract", "outline", "precis", "synopsis"],
    "aperea": ["cavia porcellus", "cavy", "wild cavy"],
    "aperient": [],
    "aperiodic": ["nonperiodic"],
    "aperitif": ["alcohol", "alcoholic beverage", "alcoholic drink", "inebriant", "intoxicant"],
    "aperture": ["hole", "micropyle", "pore", "pupil", "stoma", "stomate"],
    "apery": ["impersonation", "mimicry", "mockery", "parody", "personation", "takeoff"],
    "apetalous": ["petalless"],
    "apetalous flower": ["bloom", "blossom", "flower"],
    "apex": ["apex of the sun's way", "celestial point", "solar apex"],
    "apgar score": ["assay", "check"],
    "aphaeresis": ["apheresis", "deletion", "omission"],
    "aphaeretic": ["apheretic"],
    "aphagia": ["pathology"],
    "aphakia": ["vision defect", "visual defect", "visual disorder", "visual impairment"],
    "aphakic": ["visually impaired person"],
    "aphanite": ["rock", "stone"],
    "aphanitic": [],
    "aphasia": ["acoustic aphasia", "alexia", "amnesic aphasia", "amnestic aphasia", "anomia", "anomic aphasia", "associative aphasia", "ataxic aphasia", "auditory aphasia", "brain disease", "brain disorder", "broca's aphasia", "conduction aphasia", "encephalopathy", "expressive aphasia", "fluent aphasia", "global aphasia", "impressive aphasia", "motor aphasia", "nominal aphasia", "nonfluent aphasia", "receptive aphasia", "sensory aphasia", "total aphasia", "transcortical aphasia", "visual aphasia", "wernicke's aphasia", "word blindness", "word deafness"],
    "aphasic": ["handicapped person"],
    "aphasmidia": ["class", "class aphasmidia"],
    "aphelion": ["apoapsis", "point of apoapsis"],
    "apheresis": ["dialysis", "pheresis", "plasmapheresis", "plateletpheresis"],
    "aphesis": ["deletion", "omission"],
    "aphetic": [],
    "aphid": ["ant cow", "aphis fabae", "aphis pomi", "apple aphid", "bean aphid", "blackfly", "green apple aphid", "greenfly", "louse", "plant louse", "woolly aphid", "woolly plant louse"],
    "aphid lion": ["aphis lion", "larva"],
    "aphididae": ["arthropod family", "family aphididae"],
    "aphidoidea": ["arthropod family", "superfamily aphidoidea"],
    "aphis": ["arthropod genus", "genus aphis"],
    "aphonia": ["defect of speech", "speech defect", "speech disorder", "voicelessness"],
    "aphonic": ["voiceless"],
    "aphorism": ["apophthegm", "apothegm", "axiom", "maxim"],
    "aphorist": ["intellect", "intellectual"],
    "aphoristic": ["apothegmatic", "epigrammatic"],
    "aphorize": ["aphorise", "communicate", "intercommunicate"],
    "aphotic": [],
    "aphriza": ["bird genus", "genus aphriza"],
    "aphrodisia": ["concupiscence", "eros", "physical attraction", "sexual desire"],
    "aphrodisiac": ["excitant", "stimulant", "stimulant drug"],
    "aphrodite": ["cytherea"],
    "aphrophora": ["arthropod genus", "genus aphrophora"],
    "aphthous ulcer": ["ulcer", "ulceration"],
    "aphyllanthaceae": ["family aphyllanthaceae", "liliid monocot family"],
    "aphyllanthes": ["genus aphyllanthes", "liliid monocot genus"],
    "aphyllophorales": ["fungus order", "order aphyllophorales"],
    "aphyllous": [],
    "apia": ["capital of western samoa"],
    "apian": [],
    "apiarian": [],
    "apiary": ["bee house", "shed"],
    "apical": [],
    "apical placentation": ["placentation"],
    "apiculate": [],
    "apicultural": [],
    "apidae": ["arthropod family", "family apidae"],
    "apios": ["genus apios", "rosid dicot genus"],
    "apis": ["arthropod genus", "genus apis"],
    "apish": ["apelike"],
    "apishamore": ["horse blanket", "saddle blanket", "saddlecloth"],
    "apium": ["genus apium", "rosid dicot genus"],
    "apivorous": [],
    "aplacental": [],
    "aplanatic": [],
    "aplasia": ["dysplasia"],
    "aplastic anemia": ["anaemia", "anemia", "aplastic anaemia"],
    "aplectrum": ["genus aplectrum", "liliopsid genus", "monocot genus"],
    "aplite": ["igneous rock"],
    "aplitic": [],
    "aplodontia": ["genus aplodontia", "mammal genus"],
    "aplodontiidae": ["family aplodontiidae", "mammal family"],
    "aplomb": ["assuredness", "calm", "calmness", "composure", "cool", "equanimity", "poise", "sang-froid"],
    "aplysia": ["genus aplysia", "genus tethus", "mollusk genus", "tethys"],
    "aplysiidae": ["family aplysiidae", "family tethyidae", "mollusk family", "tethyidae"],
    "apnea": ["periodic apnea of the newborn", "sleep apnea", "symptom"],
    "apneic": ["apnoeic"],
    "apoapsis": ["aphelion", "apogee", "apojove", "apolune", "aposelene", "celestial point", "point of apoapsis"],
    "apocalypse": ["calamity", "cataclysm", "catastrophe", "disaster", "tragedy"],
    "apocalyptic": [],
    "apocarpous": [],
    "apochromatic": [],
    "apocope": ["abbreviation"],
    "apocrine": [],
    "apocrine gland": ["sudoriferous gland", "sweat gland"],
    "apocrypha": ["religious text", "religious writing", "sacred text", "sacred writing"],
    "apocryphal": [],
    "apocynaceae": ["dicot family", "dogbane family", "family apocynaceae", "magnoliopsid family"],
    "apocynaceous": [],
    "apocynum": ["dicot genus", "genus apocynum", "magnoliopsid genus"],
    "apodal": ["apodous"],
    "apodeme": ["anatomical structure", "bodily structure", "body structure", "complex body part", "structure"],
    "apodemus": ["genus apodemus", "mammal genus"],
    "apodictic": ["apodeictic"],
    "apodidae": ["bird family", "family apodidae"],
    "apodiform bird": ["bird", "crested swift", "hummingbird", "swift", "tree swift"],
    "apodiformes": ["animal order", "order apodiformes"],
    "apoenzyme": ["protein"],
    "apogamic": ["apogametic", "apogamous"],
    "apogamy": ["apomixis"],
    "apogean": [],
    "apogee": ["culmination", "phase", "stage"],
    "apogon": ["fish genus", "genus apogon"],
    "apogonidae": ["family apogonidae", "fish family"],
    "apoidea": ["arthropod family", "superfamily apoidea"],
    "apojove": ["apoapsis", "point of apoapsis"],
    "apolemia": ["siphonophore"],
    "apolitical": ["unpolitical"],
    "apollinaire": ["guillaume apollinaire", "wilhelm apollinaris de kostrowitzki"],
    "apollo": ["phoebus", "phoebus apollo"],
    "apollo asteroid": [],
    "apollo program": [],
    "apologetic": ["excusatory"],
    "apologetically": [],
    "apologetics": ["divinity", "theology"],
    "apologist": ["advocate", "advocator", "exponent", "justifier", "proponent", "vindicator"],
    "apologize": ["apologise", "color", "colour", "defend", "excuse", "extenuate", "fend for", "gloss", "justify", "mitigate", "palliate", "plead", "rationalise", "rationalize", "support"],
    "apology": ["apologia", "defence", "defense", "vindication"],
    "apomict": ["flora", "plant", "plant life"],
    "apomictic": ["apomictical"],
    "apomixis": ["agamogenesis", "apogamy", "asexual reproduction", "parthenocarpy", "parthenogenesis", "parthenogeny"],
    "apomorphine": ["morphia", "morphine"],
    "aponeurosis": ["facia", "fascia"],
    "aponeurotic": [],
    "apopemptic": [],
    "apophasis": ["rhetorical device"],
    "apophatic": [],
    "apophatism": ["faith", "religion", "religious belief"],
    "apophyseal": [],
    "apophysis": ["enation", "plant process"],
    "apoplectic": [],
    "apoplectiform": ["apoplectoid"],
    "apoptosis": ["caspase-mediated cell death", "cell death", "necrobiosis", "programmed cell death"],
    "aporocactus": ["caryophylloid dicot genus", "genus aporocactus"],
    "aposelene": ["apoapsis", "apolune", "point of apoapsis"],
    "aposematic coloration": ["protective coloration", "warning coloration"],
    "aposiopesis": ["rhetorical device"],
    "aposiopetic": [],
    "apostasy": ["defection", "rejection", "renunciation"],
    "apostate": [],
    "apostatize": ["apostatise", "disown", "renounce", "repudiate", "tergiversate"],
    "apostle": ["believer", "truster"],
    "apostleship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "apostolic": ["apostolical"],
    "apostolic delegate": ["delegate"],
    "apostrophe": ["rhetorical device"],
    "apostrophic": [],
    "apostrophize": ["apostrophise", "write"],
    "apothecaries' unit": ["apothecaries' ounce", "apothecaries' pound", "apothecaries' weight", "drachm", "drachma", "dram", "grain", "ounce", "scruple", "troy ounce", "troy pound", "weight", "weight unit"],
    "apothecial": [],
    "apothecium": ["ascocarp", "elf cup"],
    "apothegmatic": ["apothegmatical"],
    "apotheosize": ["apotheose", "apotheosise", "deify"],
    "apotropaic": [],
    "appalachia": [],
    "appalachian": ["american"],
    "appalachians": ["appalachian mountains"],
    "appalling": ["experience"],
    "appallingly": [],
    "appaloosa": ["mount", "riding horse", "saddle horse"],
    "appanage": ["apanage", "fringe benefit", "perk", "perquisite"],
    "apparatchik": ["functionary", "official"],
    "apparatus": ["auditory apparatus", "body part"],
    "apparel": ["article of clothing", "clothes", "clothing", "dress", "habiliment", "vesture", "wear", "wearable", "wearing apparel", "workwear"],
    "apparel chain": ["chain"],
    "apparel industry": ["fashion business", "fashion industry", "garment industry", "industry", "rag trade"],
    "appareled": ["attired", "dressed", "garbed", "garmented", "habilimented", "robed"],
    "apparent": ["ostensible", "seeming"],
    "apparent motion": ["apparent movement", "motion", "movement", "optical illusion"],
    "apparently": ["on the face of it", "ostensibly", "seemingly"],
    "apparentness": ["apparency", "noticeability", "noticeableness", "obviousness", "patency"],
    "apparition": ["disembodied spirit", "fantasm", "flying dutchman", "phantasm", "phantasma", "phantom", "specter", "spectre", "spirit"],
    "apparitional": ["ghostlike", "ghostly", "phantasmal", "spectral", "spiritual"],
    "appeal": ["challenge", "take exception"],
    "appeal board": ["appeals board", "board", "board of appeals"],
    "appealable": [],
    "appealing": [],
    "appealingly": [],
    "appear": [],
    "appearance": ["apparition", "happening", "manifestation", "materialisation", "materialization", "natural event", "occurrence", "occurrent", "reappearance"],
    "appeasable": ["conciliable"],
    "appeasement": ["calming", "conciliation", "mollification", "pacification", "placation", "propitiation", "social control"],
    "appeaser": ["conciliator", "make-peace", "pacifier", "peacemaker", "reconciler"],
    "appeasing": ["placating", "placative", "placatory"],
    "appellant": ["litigant", "litigator", "plaintiff in error"],
    "appellate": ["appellant"],
    "appellate court": ["appeals court", "circuit court of appeals", "court", "court of appeals", "judicature", "tribunal"],
    "appellation": ["appellative", "byname", "cognomen", "denomination", "designation", "form of address", "moniker", "name", "nickname", "sobriquet", "soubriquet", "street name", "title", "title of respect"],
    "appellative": [],
    "append": ["add on", "affix", "annex", "attach", "supplement"],
    "appendage": ["appendicle", "grip", "handgrip", "handhold", "handle", "hold", "part", "portion", "tailpiece"],
    "appendaged": [],
    "appendant": [],
    "appendectomy": ["ablation", "appendicectomy", "cutting out", "excision", "extirpation"],
    "appendicitis": ["inflammation", "redness", "rubor"],
    "appendicle": ["appendage"],
    "appendicular": [],
    "appendicular artery": ["arteria", "arteria appendicularis", "arterial blood vessel", "artery"],
    "appendicular skeleton": ["skeletal structure"],
    "appendicular vein": ["vein", "vena", "vena appendicularis", "venous blood vessel"],
    "appendicularia": ["tunicate", "urochord", "urochordate"],
    "appendix": ["addendum", "codicil", "postscript", "shirttail", "supplement"],
    "appenzeller": ["sennenhunde"],
    "apperceive": ["comprehend", "perceive"],
    "apperception": ["basic cognitive process"],
    "apperceptive": [],
    "appetent": [],
    "appetite": ["appetence", "appetency", "craving", "stomach", "sweet tooth"],
    "appetitive": [],
    "appetizer": ["antipasto", "appetiser", "canape", "cocktail", "course", "crudites", "hors d'oeuvre", "starter"],
    "appetizing": ["appetising"],
    "appetizingness": ["appetisingness", "delectability", "deliciousness", "flavorsomeness", "flavoursomeness", "juiciness", "lusciousness", "palatability", "palatableness", "savoriness", "succulence", "succulency", "toothsomeness"],
    "appian way": [],
    "applaud": ["acclaim", "bravo", "clap", "gesticulate", "gesture", "motion", "spat"],
    "applaudable": ["commendable", "laudable", "praiseworthy"],
    "applause": ["approval", "clapping", "commendation", "hand", "hand clapping", "handclap", "round"],
    "apple": ["apple tree", "malus pumila", "orchard apple tree"],
    "apple aphid": ["aphid", "aphis pomi", "green apple aphid"],
    "apple blight": ["apple canker", "blight"],
    "apple butter": ["conserve", "conserves", "preserve", "preserves"],
    "apple dumpling": ["dumpling"],
    "apple fritter": ["fritter"],
    "apple geranium": ["geranium", "nutmeg geranium", "pelargonium odoratissimum"],
    "apple jelly": ["crabapple jelly", "jelly"],
    "apple juice": ["fruit crush", "fruit juice"],
    "apple maggot": ["fruit fly", "pomace fly", "railroad worm", "rhagoletis pomonella"],
    "apple mint": ["applemint", "mentha rotundifolia", "mentha suaveolens", "mint"],
    "apple of discord": ["prize", "trophy"],
    "apple of peru": ["herb", "herbaceous plant", "nicandra physaloides", "shoo fly"],
    "apple orchard": ["grove", "orchard", "plantation", "woodlet"],
    "apple pie": ["pie"],
    "apple polisher": ["ass-kisser", "bootlicker", "crawler", "fawner", "groveler", "groveller", "lackey", "sycophant", "toady", "truckler"],
    "apple rust": ["cedar-apple rust", "gymnosporangium juniperi-virginianae", "rust", "rust fungus"],
    "apple tart": ["tart"],
    "apple tree": ["apple", "crab apple", "crabapple", "cultivated crab apple", "fruit tree", "malus pumila", "orchard apple tree", "wild apple"],
    "apple turnover": ["turnover"],
    "apple-scented": [],
    "apple-shaped": [],
    "apple-sized": [],
    "applecart": ["planning", "preparation", "provision"],
    "applejack": ["brandy"],
    "applesauce": ["apple sauce", "dish"],
    "applesauce cake": ["cake"],
    "applet": ["application", "application program", "applications programme"],
    "appleton": ["edward appleton", "sir edward victor appleton"],
    "appleton layer": ["f layer", "f region"],
    "applewood": ["fruitwood"],
    "appliance": ["contraption", "contrivance", "convenience", "device", "gadget", "gadgetry", "gimbal", "gismo", "gizmo", "injector", "mod con", "widget"],
    "applicability": ["germaneness", "pertinence", "pertinency", "relevance", "relevancy"],
    "applicable": [],
    "applicant": ["applier", "aspirant", "aspirer", "bidder", "claimant", "hopeful", "individual", "job candidate", "material", "mortal", "person", "petitioner", "possible", "probable", "requester", "somebody", "someone", "soul", "submitter", "suppliant", "supplicant", "wannabe", "wannabee"],
    "application": ["active application", "applet", "application program", "applications programme", "browser", "computer program", "computer programme", "editor", "editor program", "frame", "job", "natural language processing application", "natural language processor", "program", "programme", "web browser", "word processing system", "word processor"],
    "application form": ["form"],
    "application-oriented language": ["high-level language", "job-control language", "problem-oriented language", "source language"],
    "applicative": ["applicatory"],
    "applicator": ["applier", "device", "flux applicator", "paintbrush", "spray gun"],
    "applied": [],
    "applied mathematics": ["applied math", "linear programming", "math", "mathematics", "maths", "probability theory", "statistics", "theory of probability"],
    "applied psychology": ["industrial psychology", "psychological science", "psychology"],
    "applique": ["adorn", "beautify", "decorate", "embellish", "grace", "ornament"],
    "apply": ["bear on", "come to", "concern", "go for", "have-to doe with", "hold", "pertain", "refer", "relate", "touch", "touch on"],
    "appoint": ["accredit", "assign", "authorise", "authorize", "charge", "create", "delegate", "depute", "deputise", "deputize", "designate", "empower", "make", "name", "nominate"],
    "appointed": ["decreed", "ordained", "prescribed"],
    "appointee": ["functionary", "official", "placeman", "placeseeker"],
    "appointive": [],
    "appointment": ["fitting", "furnishing"],
    "appointment book": ["appointment calendar", "book"],
    "apportioned": ["dealt out", "doled out", "meted out", "parceled out"],
    "appose": ["lay", "place", "pose", "position", "put", "set"],
    "apposite": ["apt", "pertinent"],
    "apposition": ["limiting", "modification", "qualifying"],
    "appositional": ["appositive"],
    "appositively": ["in apposition"],
    "appraisal": ["commercial document", "commercial instrument", "estimate", "estimation", "overappraisal", "overestimate", "overestimation", "overvaluation"],
    "appraiser": ["authenticator", "critic"],
    "appraising": ["evaluative"],
    "appreciable": [],
    "appreciably": [],
    "appreciate": ["acknowledge", "recognise", "recognize"],
    "appreciated": ["apprehended", "comprehended"],
    "appreciation": ["thanks"],
    "appreciative": [],
    "appreciatively": ["gratefully"],
    "appreciator": ["enophile", "individual", "mortal", "oenophile", "person", "somebody", "someone", "soul"],
    "apprehend": ["anticipate", "look for", "look to", "quail at"],
    "apprehender": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "apprehensible": ["graspable", "intelligible", "perceivable", "understandable"],
    "apprehension": ["apprehensiveness", "boding", "chill", "dread", "fear", "fearfulness", "foreboding", "fright", "gloom", "gloominess", "pall", "premonition", "presentiment", "somberness", "sombreness", "suspense", "trepidation"],
    "apprehensive": ["discerning"],
    "apprentice": ["prepare", "train"],
    "apprenticed": ["articled", "bound", "indentured"],
    "apprenticeship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "appressed": ["adpressed"],
    "appro": ["approval", "favorable reception", "favourable reception"],
    "approach": ["bear down on", "bear down upon", "close", "come", "come near", "come on", "come up", "crowd", "draw close", "draw near", "drive up", "edge in", "edge up", "go up", "near", "push"],
    "approach path": ["air lane", "airway", "approach", "flight path", "glide path", "glide slope", "skyway"],
    "approach trench": ["communication trench", "trench"],
    "approachability": ["accessibility", "friendliness"],
    "approachable": [],
    "approaching": ["coming", "forthcoming", "upcoming"],
    "approbate": ["authorise", "authorize", "clear", "pass"],
    "approbation": ["approval"],
    "appropriable": [],
    "appropriate": ["arrogate", "assume", "capture", "carry", "conquer", "seize", "take over", "usurp"],
    "appropriately": ["befittingly", "fitly", "fittingly", "suitably"],
    "appropriateness": ["correctitude", "properness", "propriety", "rightness"],
    "appropriation": ["money", "pork", "pork barrel"],
    "appropriation bill": ["bill", "measure"],
    "appropriative": [],
    "appropriator": ["acquirer", "kleptomaniac", "poacher", "pre-emptor", "preemptor"],
    "approval": ["acceptance", "appro", "favorable reception", "favourable reception"],
    "approve": ["authorise", "authorize", "back", "clear", "confirm", "endorse", "indorse", "o.k.", "okay", "pass", "plump for", "plunk for", "sanction", "support", "visa"],
    "approved": ["sanctioned"],
    "approver": ["authority"],
    "approving": ["affirmative", "approbative", "approbatory", "plausive"],
    "approvingly": [],
    "approximate": ["approach", "border on", "come close", "resemble"],
    "approximate range": ["ambit", "ballpark", "compass", "orbit", "range", "reach", "scope"],
    "approximately": ["about", "around", "close to", "just about", "more or less", "or so", "roughly", "some"],
    "approximation": ["version"],
    "apractic": ["apraxic"],
    "apraxia": ["brain disease", "brain disorder", "encephalopathy"],
    "apricot": ["apricot tree", "black apricot", "common apricot", "fruit tree", "japanese apricot", "mei", "prunus armeniaca", "prunus dasycarpa", "prunus mume", "purple apricot"],
    "apricot bar": ["fruit bar"],
    "apricot sauce": ["sauce"],
    "april": ["apr", "gregorian calendar month"],
    "april fool": ["butt", "goat", "laughingstock", "stooge"],
    "april fools'": ["all fools' day", "april fools' day", "day"],
    "apron": ["land site", "site"],
    "apron string": ["cord"],
    "apropos": [],
    "apse": ["apsis", "niche", "recess", "tribune"],
    "apsidal": [],
    "apsu": [],
    "apt": ["liable"],
    "aptenodytes": ["bird genus", "genus aptenodytes"],
    "apteral": [],
    "apterous": ["apteral"],
    "apterygidae": ["bird family", "family apterygidae"],
    "apterygiformes": ["animal order", "order apterygiformes"],
    "aptitude": ["ability", "capability", "capableness", "inherent aptitude", "instinct", "natural ability", "potentiality", "power"],
    "aptitudinal": [],
    "aptness": ["disposition", "propensity"],
    "apus": [],
    "aqua regia": ["acid", "nitrohydrochloric acid"],
    "aqua vitae": ["ardent spirits", "booze", "hard drink", "hard liquor", "john barleycorn", "liquor", "spirits", "strong drink"],
    "aquaculture": ["cultivation"],
    "aqualung": ["aqua-lung", "breathing apparatus", "breathing device", "breathing machine", "scuba", "ventilator"],
    "aquamarine": ["beryl", "transparent gem"],
    "aquanaut": ["oceanaut", "skilled worker", "skilled workman", "trained worker"],
    "aquaphobia": ["simple phobia"],
    "aquaplane": ["plane", "skim"],
    "aquarium": ["fish bowl", "fish tank", "fishbowl", "goldfish bowl", "marine museum", "storage tank", "tank", "vivarium"],
    "aquarius": ["individual", "mortal", "person", "somebody", "someone", "soul", "water bearer"],
    "aquatic": ["flora", "plant", "plant life"],
    "aquatic bird": ["bird", "gallinule", "marsh hen", "sea bird", "seabird", "seafowl", "swamphen", "swan", "wader", "wading bird", "water bird", "water hen", "waterbird", "waterfowl"],
    "aquatic fern": ["azolla caroliniana", "carolina pond fern", "ceratopteris pteridioides", "ceratopteris thalictroides", "clover fern", "fern", "floating fern", "floating-moss", "mosquito fern", "pepperwort", "pillwort", "pilularia globulifera", "regnellidium", "regnellidium diphyllum", "salvinia auriculata", "salvinia rotundifolia", "water fern", "water sprite"],
    "aquatic mammal": ["blower", "cetacean", "cetacean mammal", "eutherian", "eutherian mammal", "pinnatiped", "pinniped", "pinniped mammal", "placental", "placental mammal", "sea cow", "sirenian", "sirenian mammal"],
    "aquatic plant": ["american frogbit", "arrow arum", "awlwort", "bog myrtle", "bog plant", "bogbean", "buckbean", "caltrop", "cryptocoryne", "duckweed", "eelgrass", "eichhornia crassipes", "eichhornia spesiosa", "eriocaulon aquaticum", "feather-foil", "featherfoil", "frog's-bit", "frogbit", "golden club", "golden saxifrage", "golden spleen", "grass wrack", "heteranthera dubia", "hornwort", "hydrilla", "hydrilla verticillata", "hydrocharis morsus-ranae", "hydrophyte", "hydrophytic plant", "limnodium spongia", "marsh plant", "marsh trefoil", "menyanthes trifoliata", "mud plantain", "naiad", "orontium aquaticum", "pickerel weed", "pickerelweed", "pipewort", "pistia", "pistia stratiotes", "pistia stratoites", "pondweed", "pontederia cordata", "ranunculus aquatilis", "sea wrack", "subularia aquatica", "swamp plant", "tape grass", "tracheophyte", "vallisneria spiralis", "vascular plant", "veronica anagallis-aquatica", "veronica michauxii", "wampee", "water buttercup", "water cabbage", "water chestnut", "water chestnut plant", "water crowfoot", "water hyacinth", "water lettuce", "water lily", "water milfoil", "water nymph", "water orchid", "water pimpernel", "water plant", "water shamrock", "water speedwell", "water star grass", "water starwort", "water trumpet", "waterweed", "wild celery", "zostera marina"],
    "aquatic vertebrate": ["agnathan", "craniate", "fish", "jawless fish", "jawless vertebrate", "placoderm", "vertebrate"],
    "aquatint": ["etch"],
    "aquavit": ["akvavit", "booze", "hard drink", "hard liquor", "john barleycorn", "liquor", "spirits", "strong drink"],
    "aqueduct": ["conduit"],
    "aqueous": [],
    "aqueous humor": ["aqueous humour", "bodily fluid", "body fluid", "humor", "humour", "liquid body substance"],
    "aqueous solution": ["solution"],
    "aquicultural": ["aquacultural", "hydroponic"],
    "aquifer": ["formation", "geological formation"],
    "aquiferous": [],
    "aquifoliaceae": ["dicot family", "family aquifoliaceae", "holly family", "magnoliopsid family"],
    "aquila": [],
    "aquiline": ["hooked"],
    "aquinas": ["saint thomas", "saint thomas aquinas", "st. thomas", "st. thomas aquinas", "thomas aquinas"],
    "aquitaine": ["aquitania"],
    "ara": [],
    "arab": ["arabian", "bahraini", "bahreini", "bedouin", "beduin", "katari", "omani", "palestinian", "palestinian arab", "qatari", "saracen", "saudi", "saudi arabian", "semite", "yemeni"],
    "arab league": ["global organization", "international organisation", "international organization", "world organisation", "world organization"],
    "arab-israeli war": ["yom kippur war"],
    "arabesque": ["ballet position"],
    "arabian": ["arab", "mount", "riding horse", "saddle horse"],
    "arabian camel": ["camel", "camelus dromedarius", "dromedary"],
    "arabian coffee": ["coffea arabica", "coffee", "coffee tree"],
    "arabian desert": ["eastern desert"],
    "arabian jasmine": ["jasmine", "jasminum sambac"],
    "arabian nights' entertainment": ["arabian nights", "thousand and one nights"],
    "arabian peninsula": ["arabia"],
    "arabian sea": [],
    "arabic": ["arabic language", "semitic"],
    "arabic alphabet": ["alphabet", "unicameral script"],
    "arabic numeral": ["hindu numeral", "hindu-arabic numeral", "number", "numeral"],
    "arabidopsis": ["dilleniid dicot genus", "genus arabidopsis"],
    "arabidopsis lyrata": ["cress", "cress plant"],
    "arabidopsis thaliana": ["cress", "cress plant", "mouse-ear cress"],
    "arability": ["quality"],
    "arabis": ["dilleniid dicot genus", "genus arabis"],
    "arabist": ["bookman", "scholar", "scholarly person", "student"],
    "arable": ["cultivable", "cultivatable", "tillable"],
    "araceae": ["arum family", "family araceae", "liliopsid family", "monocot family"],
    "arachis": ["genus arachis", "rosid dicot genus"],
    "arachnid": ["acarine", "arachnoid", "arthropod", "daddy longlegs", "false scorpion", "harvestman", "phalangium opilio", "pseudoscorpion", "scorpion", "spider", "whip scorpion", "whip-scorpion"],
    "arachnida": ["class", "class arachnida"],
    "arachnoid": ["arachnoid membrane", "meninges", "meninx"],
    "arachnophobia": ["zoophobia"],
    "arafat": ["yasser arafat"],
    "arafura sea": [],
    "aragon": ["louis aragon"],
    "aragonite": ["mineral"],
    "araguaia": ["araguaia river", "araguaya", "araguaya river"],
    "arales": ["order arales", "plant order"],
    "aralia": ["ligneous plant", "woody plant"],
    "araliaceae": ["family araliaceae", "ivy family", "rosid dicot family"],
    "aram": [],
    "aramaic": ["assyrian", "assyrian neo-aramaic", "biblical aramaic", "mandaean", "mandean", "semitic"],
    "arame": ["seaweed"],
    "aramean": ["aramaean", "semite"],
    "aramus": ["bird genus", "genus aramus"],
    "aran islands": [],
    "aranea": ["araneus", "arthropod genus", "genus aranea", "genus araneus"],
    "araneae": ["animal order", "araneida", "order araneae", "order araneida"],
    "araneidal": ["araneidan"],
    "aranyaka": [],
    "arapaho": ["algonquian", "algonquin", "arapahoe", "buffalo indian", "plains indian"],
    "ararat": ["mount ararat", "mt. ararat"],
    "arariba": ["centrolobium robustum", "zebrawood", "zebrawood tree"],
    "araroba": ["chrysarobin", "goa powder", "powder"],
    "aras": ["araxes"],
    "arauca": [],
    "araucaria": ["araucaria araucana", "araucaria bidwillii", "araucaria columnaris", "araucaria cunninghamii", "araucaria excelsa", "araucaria heterophylla", "bunya bunya", "bunya bunya tree", "chile pine", "conifer", "coniferous tree", "hoop pine", "monkey puzzle", "moreton bay pine", "new caledonian pine", "norfolk island pine"],
    "araucariaceae": ["araucaria family", "family araucariaceae", "gymnosperm family"],
    "araujia": ["dicot genus", "genus araujia", "magnoliopsid genus"],
    "arawak": ["amerindian", "arawakan", "native american"],
    "arawakan": [],
    "arawn": [],
    "arbiter": ["expert", "supreme authority"],
    "arbitrable": [],
    "arbitrage": ["merchandise", "trade"],
    "arbitrageur": ["arb", "arbitrager", "businessman", "man of affairs"],
    "arbitral": ["arbitrational"],
    "arbitrary": [],
    "arbitration": ["mediation"],
    "arbitration clause": ["article", "clause"],
    "arbitrative": [],
    "arbor": ["tree"],
    "arbor day": ["day"],
    "arboraceous": ["arboreous", "woodsy", "woody"],
    "arboreal": ["arboreous", "arborescent", "arboresque", "arboriform", "dendriform", "dendroid", "dendroidal", "tree-shaped", "treelike"],
    "arboreal salamander": ["aneides lugubris", "climbing salamander"],
    "arborescent plant": ["australian grass tree", "grass tree", "ligneous plant", "woody plant"],
    "arboretum": ["botanical garden", "facility", "installation"],
    "arborical": ["arborary", "arboreal", "arborous"],
    "arboriculture": ["agriculture", "farming", "husbandry", "tree farming"],
    "arborize": ["arborise", "branch", "fork", "furcate", "ramify", "separate"],
    "arborolatry": ["tree-worship", "worship"],
    "arborvitae": ["american arborvitae", "canoe cedar", "conifer", "coniferous tree", "hiba arborvitae", "northern white cedar", "oriental arborvitae", "platycladus orientalis", "red cedar", "thuja occidentalis", "thuja orientalis", "thuja plicata", "thujopsis dolobrata", "western red cedar", "white cedar"],
    "arbovirus": ["arborvirus", "arenaviridae", "bunyaviridae", "flaviviridae", "reoviridae", "rhabdoviridae", "togaviridae", "virus"],
    "arbutus": ["arbutus menziesii", "arbutus unedo", "bush", "irish strawberry", "madrona", "madrono", "manzanita", "shrub", "strawberry tree"],
    "arc": ["curve", "curved shape", "limb"],
    "arc cosecant": ["arccosecant", "circular function", "inverse cosecant", "trigonometric function"],
    "arc cosine": ["arccos", "arccosine", "circular function", "inverse cosine", "trigonometric function"],
    "arc cotangent": ["arccotangent", "circular function", "inverse cotangent", "trigonometric function"],
    "arc lamp": ["arc light", "carbon arc", "carbon arc lamp", "electric lamp"],
    "arc secant": ["arcsec", "arcsecant", "circular function", "inverse secant", "trigonometric function"],
    "arc sine": ["arcsin", "arcsine", "circular function", "inverse sine", "trigonometric function"],
    "arc tangent": ["arctan", "arctangent", "circular function", "inverse tangent", "trigonometric function"],
    "arca": ["genus arca", "mollusk genus"],
    "arcade": ["amusement arcade", "passageway", "penny arcade"],
    "arcadia": [],
    "arcadian": ["greek", "hellene"],
    "arcadic": ["ancient greek", "arcadic dialect"],
    "arcane": [],
    "arced": ["arched", "arching", "arciform", "arcuate", "bowed"],
    "arcella": ["protozoan", "protozoon"],
    "arcellidae": ["family arcellidae", "protoctist family"],
    "arceuthobium": ["dilleniid dicot genus", "genus arceuthobium"],
    "arch": ["arc", "bend", "camber", "curve", "flex"],
    "arch support": ["support"],
    "archaebacteria": ["archaebacterium", "archaeobacteria", "archeobacteria", "halophil", "halophile", "methanogen", "moneran", "moneron", "thermoacidophile"],
    "archaeological": ["archaeologic", "archeologic", "archeological"],
    "archaeopteryx": ["archaeopteryx lithographica", "archeopteryx", "bird"],
    "archaeornis": ["bird"],
    "archaeornithes": ["class", "subclass archaeornithes"],
    "archaic": ["primitive"],
    "archaism": ["archaicism", "expression", "formulation"],
    "archaist": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "archaistic": [],
    "archaize": ["alter", "archaise", "change", "modify"],
    "archangel": ["angel", "gabriel", "michael", "raphael"],
    "archangelic": ["archangelical"],
    "archbishop": ["bishop", "metropolitan"],
    "archbishopric": ["jurisdiction"],
    "archdeacon": ["clergyman", "man of the cloth", "reverend"],
    "archdeaconry": ["jurisdiction"],
    "archdiocesan": [],
    "archdiocese": ["bishopric", "diocese", "episcopate"],
    "archducal": [],
    "archduchess": ["princess"],
    "archduchy": ["demesne", "domain", "land"],
    "archduke": ["prince"],
    "archean": ["archaeozoic", "archaeozoic aeon", "archean aeon", "archean eon", "archeozoic", "archeozoic eon"],
    "arched": [],
    "archegonial": ["archegoniate"],
    "archegonium": ["plant organ"],
    "archenteron": ["bodily cavity", "cavity", "cavum"],
    "archeological remains": ["relic", "remains"],
    "archeologist": ["anthropologist", "archaeologist", "egyptologist", "paleographer", "paleographist", "pothunter"],
    "archeology": ["anthropology", "archaeology", "assyriology", "egyptology", "marine archaeology", "marine archeology", "palaeoclimatology", "palaeoethnography", "palaeogeography", "palaeology", "palaeopathology", "palaetiology", "paleoclimatology", "paleoethnography", "paleogeography", "paleography", "paleology", "paleopathology", "paletiology", "protoanthropology", "protohistory", "sumerology", "underwater archaeology", "underwater archeology"],
    "archeozoic": ["archaeozoic"],
    "archer": ["bowman", "expert", "longbowman"],
    "archerfish": ["percoid", "percoid fish", "percoidean", "toxotes jaculatrix"],
    "archery": ["athletics", "sport"],
    "arches national park": [],
    "archespore": ["archesporium", "cell"],
    "archesporial": [],
    "archetypal": ["archetypical", "prototypal", "prototypic", "prototypical"],
    "archiannelid": ["annelid", "annelid worm", "segmented worm"],
    "archiannelida": ["class", "class archiannelida"],
    "archidiaconal": [],
    "archidiaconate": ["rank"],
    "archidiskidon": ["genus archidiskidon", "mammal genus"],
    "archiepiscopal": ["archepiscopal"],
    "archil": ["lecanora", "orchil"],
    "archilochus": ["bird genus", "genus archilochus"],
    "archilochus colubris": ["hummingbird"],
    "archimedes": [],
    "archimedes' principle": ["law", "law of archimedes", "law of nature"],
    "archine": ["linear measure", "linear unit"],
    "archipallium": ["cerebral cortex", "cerebral mantle", "cortex", "paleocortex", "pallium"],
    "archipelagic": [],
    "archipelago": ["dry land", "earth", "ground", "land", "solid ground", "terra firma"],
    "architect": ["creator", "designer", "ithiel town", "landscape architect", "landscape gardener", "landscaper", "landscapist", "town"],
    "architectonics": ["science", "scientific discipline", "tectonics"],
    "architectural": [],
    "architectural engineering": ["applied science", "engineering", "engineering science", "technology"],
    "architectural ornament": ["antefix", "crocket", "decoration", "dogtooth", "foliage", "foliation", "fret", "frieze", "greek fret", "greek key", "guilloche", "key pattern", "ornament", "ornamentation", "trefoil"],
    "architectural style": ["art form", "bauhaus", "byzantine architecture", "classical architecture", "gothic", "gothic architecture", "greco-roman architecture", "moorish", "moorish architecture", "romanesque", "romanesque architecture", "style of architecture", "type of architecture", "victorian architecture"],
    "architecturally": [],
    "architecture": ["bailiwick", "beaux arts", "discipline", "field", "field of study", "fine arts", "interior design", "landscape architecture", "study", "subject", "subject area", "subject field", "urban planning"],
    "architeuthis": ["giant squid", "squid"],
    "architrave": ["molding", "moulding"],
    "archival": [],
    "archive": ["collect", "file away", "pull in"],
    "archives": ["collection", "compendium"],
    "archivist": ["aggregator", "collector"],
    "archly": [],
    "archosargus": ["fish genus", "genus archosargus"],
    "archosaur": ["archosaurian", "archosaurian reptile", "diapsid", "diapsid reptile", "dinosaur", "flying reptile", "ichthyosaur", "nothosaur", "plesiosaur", "plesiosaurus", "pterosaur", "thecodont", "thecodont reptile"],
    "archosauria": ["class", "subclass archosauria"],
    "archosaurian": [],
    "archpriest": ["hierarch", "high priest", "prelate", "priest", "primate"],
    "arcidae": ["family arcidae", "mollusk family"],
    "arco": [],
    "arctic": ["arctic zone", "north frigid zone"],
    "arctic archipelago": [],
    "arctic char": ["char", "charr", "salvelinus alpinus"],
    "arctic circle": [],
    "arctic fox": ["alopex lagopus", "blue fox", "fox", "white fox"],
    "arctic ground squirrel": ["citellus parryi", "gopher", "ground squirrel", "parka squirrel", "spermophile"],
    "arctic ocean": [],
    "arctic willow": ["salix arctica", "willow", "willow tree"],
    "arctictis": ["genus arctictis", "mammal genus"],
    "arctiid": ["arctiid moth", "callimorpha jacobeae", "cinnabar", "cinnabar moth", "moth", "tiger moth"],
    "arctiidae": ["arthropod family", "family arctiidae"],
    "arctium": ["asterid dicot genus", "genus arctium"],
    "arctocebus": ["genus arctocebus", "mammal genus"],
    "arctocephalus": ["genus arctocephalus", "mammal genus"],
    "arctonyx": ["genus arctonyx", "mammal genus"],
    "arctostaphylos": ["dilleniid dicot genus", "genus arctostaphylos"],
    "arctotis": ["asterid dicot genus", "genus arctotis"],
    "arcturus": [],
    "arcuate artery": ["arteria", "arteria arcuata", "arterial blood vessel", "artery"],
    "arcuate artery of the kidney": ["arteria", "arterial blood vessel", "artery"],
    "arcuate vein of the kidney": ["vein", "vena", "vena arcuata renis", "venous blood vessel"],
    "arcus": ["arcus senilis", "cornea"],
    "ardea": ["bird genus", "genus ardea"],
    "ardeb": ["dry measure", "dry unit"],
    "ardeidae": ["bird family", "family ardeidae"],
    "ardennes": [],
    "ardent": ["fervent", "fervid", "fiery", "impassioned", "perfervid", "torrid"],
    "ardently": [],
    "ardisia": ["dicot genus", "genus ardisia", "magnoliopsid genus"],
    "ardor": ["ardour", "avidity", "avidness", "eagerness", "elan", "keenness", "zeal"],
    "arduous": ["straining", "strenuous"],
    "arduously": [],
    "arduousness": ["effortfulness", "strenuousness"],
    "are": ["ar", "area unit", "square measure"],
    "area": ["anchorage", "anchorage ground", "arena", "bed ground", "bed-ground", "bedground", "block", "broadcast area", "center", "centre", "city block", "clear", "corner", "country", "danger", "disaster area", "eye", "fireside", "free port", "free zone", "hangout", "haunt", "heart", "hearth", "high country", "hunting ground", "middle", "neighborhood", "no man's land", "no-go area", "open", "playground", "quadrant", "rain shadow", "refuge", "region", "repair", "resort", "resort area", "retreat", "safety", "scene", "section", "shrubbery", "space", "staging area", "stamping ground", "tank farm", "vacation spot", "winner's circle"],
    "area code": ["code"],
    "area of cardiac dullness": ["area", "region"],
    "area unit": ["acre", "agate line", "ar", "are", "arpent", "b", "barn", "centare", "column inch", "dessiatine", "em", "em quad", "hectare", "inch", "line", "morgen", "mutton quad", "perch", "pole", "quarter section", "rod", "sq ft", "sq in", "sq yd", "square foot", "square inch", "square measure", "square meter", "square metre", "square mile", "square yard", "unit", "unit of measurement"],
    "areal": [],
    "areaway": ["passageway"],
    "areca": ["areca catechu", "betel palm", "feather palm"],
    "arecidae": ["class", "subclass arecidae"],
    "areflexia": ["symptom"],
    "arena": ["area", "country"],
    "arena theater": ["house", "theater", "theater in the round", "theatre"],
    "arenaceous": ["sandlike", "sandy"],
    "arenaceous rock": ["sandstone", "sedimentary rock"],
    "arenaria": ["caryophylloid dicot genus", "genus arenaria"],
    "arenaviridae": ["arborvirus", "arbovirus"],
    "arenavirus": ["animal virus", "junin virus", "lassa virus", "lymphocytic choriomeningitis virus", "machupo virus"],
    "arendt": ["hannah arendt"],
    "arenga": ["genus arenga", "plant genus"],
    "arenicolous": [],
    "areola": ["interstice"],
    "areolar": ["areolate"],
    "areolar tissue": ["connective tissue"],
    "areopagite": ["fellow member", "member"],
    "areopagus": [],
    "arequipa": [],
    "ares": [],
    "arete": ["ridge", "ridgeline"],
    "arethusa": ["arethusa bulbosa", "bog rose", "dragon's mouth", "orchid", "orchidaceous plant", "wild pink"],
    "argali": ["argal", "ovis ammon", "wild sheep"],
    "argasidae": ["arthropod family", "family argasidae"],
    "argent": ["tincture"],
    "argentic": [],
    "argentiferous": [],
    "argentina": ["argentine republic"],
    "argentine": ["malacopterygian", "soft-finned fish"],
    "argentine hemorrhagic fever": ["haemorrhagic fever", "hemorrhagic fever", "vhf", "viral haemorrhagic fever", "viral hemorrhagic fever"],
    "argentine monetary unit": ["austral", "monetary unit"],
    "argentinian": ["south american"],
    "argentinidae": ["family argentinidae", "fish family"],
    "argentinosaur": ["dinosaur"],
    "argentite": ["mineral"],
    "argentous": [],
    "argil": ["clay"],
    "argillaceous": ["clayey"],
    "argillaceous rock": ["sedimentary rock"],
    "argillite": ["sedimentary rock"],
    "arginine": ["essential amino acid"],
    "argiope": ["arthropod genus", "genus argiope"],
    "argiopidae": ["arthropod family", "family argiopidae", "orb-weaver"],
    "argive": ["greek", "hellene"],
    "argo": [],
    "argon": ["ar", "argonon", "atomic number 18", "chemical element", "element", "inert gas", "noble gas"],
    "argonaut": ["adventurer", "venturer"],
    "argonauta": ["genus argonauta", "mollusk genus"],
    "argonautidae": ["family argonautidae", "mollusk family"],
    "argos": [],
    "argosy": ["fleet"],
    "arguable": [],
    "arguably": [],
    "argue": ["altercate", "argufy", "bicker", "brabble", "contend", "converse", "debate", "discourse", "dispute", "fence", "niggle", "oppose", "pettifog", "quarrel", "quibble", "scrap", "spar", "squabble", "stickle"],
    "argument": ["argumentation", "debate", "discussion", "give-and-take", "logomachy", "word"],
    "argumentation": ["abstract thought", "argument", "casuistry", "line", "line of inquiry", "line of questioning", "line of reasoning", "logical argument", "logical thinking", "policy", "reasoning"],
    "argumentative": [],
    "argun": ["argun river", "ergun he"],
    "argus": ["giant"],
    "argus-eyed": ["hawk-eyed", "keen-sighted", "lynx-eyed", "quick-sighted", "sharp-eyed", "sharp-sighted"],
    "argusianus": ["bird genus", "genus argusianus"],
    "argy-bargy": ["argle-bargle", "arguing", "argument", "contention", "contestation", "controversy", "disceptation", "disputation", "tilt"],
    "argyle": ["argyll", "design", "figure", "pattern"],
    "argyll": ["argyle", "boat", "gravy boat", "gravy holder", "sauceboat"],
    "argynnis": ["arthropod genus", "genus argynnis"],
    "argyranthemum": ["asterid dicot genus", "genus argyranthemum"],
    "argyreia": ["dicot genus", "genus argyreia", "magnoliopsid genus"],
    "argyrodite": ["mineral"],
    "argyrotaenia": ["arthropod genus", "genus argyrotaenia"],
    "argyroxiphium": ["asterid dicot genus", "genus argyroxiphium"],
    "arhat": ["arhant", "lohan"],
    "arhus": ["aarhus"],
    "aria": ["arietta", "short aria", "song", "vocal"],
    "ariadne": [],
    "ariana": [],
    "arianism": ["heresy", "theological doctrine", "unorthodoxy"],
    "arianist": ["christian"],
    "arianrhod": ["arianrod"],
    "arid": ["waterless"],
    "aridity": ["aridness", "dryness", "thirstiness", "waterlessness", "xerotes"],
    "aries": ["individual", "mortal", "person", "ram", "somebody", "someone", "soul"],
    "arietta": ["aria", "short aria"],
    "ariidae": ["family ariidae", "fish family"],
    "arikara": ["aricara", "caddo"],
    "aril": ["plant part", "plant structure"],
    "ariled": ["arillate"],
    "arilus": ["arthropod genus", "genus arilus"],
    "ariocarpus": ["caryophylloid dicot genus", "genus ariocarpus"],
    "ariomma": ["fish genus", "genus ariomma"],
    "ariose": ["songlike"],
    "arioso": ["recitative"],
    "arisaema": ["genus arisaema", "liliopsid genus", "monocot genus"],
    "arisarum": ["genus arisarum", "liliopsid genus", "monocot genus"],
    "arise": ["become", "bob up", "come up"],
    "arista": ["appendage", "outgrowth", "process"],
    "aristarchus": [],
    "aristarchus of samos": [],
    "aristocrat": ["baronet", "bart", "blue blood", "brahman", "brahmin", "female aristocrat", "highness", "leader", "male aristocrat", "patrician", "prince", "princess", "raja", "rajah", "ranee", "rani"],
    "aristocratic": ["aristocratical", "blue", "blue-blooded", "gentle", "patrician"],
    "aristocratically": [],
    "aristolochia": ["dicot genus", "genus aristolochia", "magnoliopsid genus"],
    "aristolochiaceae": ["birthwort family", "dicot family", "family aristolochiaceae", "magnoliopsid family"],
    "aristolochiales": ["order aristolochiales", "plant order"],
    "aristophanes": [],
    "aristotelia": ["dilleniid dicot genus", "genus aristotelia"],
    "aristotelian": ["adherent", "aristotelean", "disciple", "peripatetic"],
    "aristotelian logic": ["logic", "logical system", "system of logic"],
    "aristotelianism": ["peripateticism", "philosophical doctrine", "philosophical theory"],
    "aristotle": [],
    "arithmancy": ["divination", "foretelling", "fortune telling", "soothsaying"],
    "arithmetic": ["algorism", "pure mathematics"],
    "arithmetic mean": ["expectation", "expected value", "first moment", "mean", "mean value"],
    "arithmetic operation": ["addition", "division", "mathematical operation", "mathematical process", "minus", "multiplication", "operation", "plus", "subtraction", "summation", "times"],
    "arithmetic progression": ["patterned advance", "progression"],
    "arithmetical": ["arithmetic"],
    "arithmetically": [],
    "arithmetician": ["mathematician"],
    "arity": ["number"],
    "arius": [],
    "arizona": ["az", "grand canyon state"],
    "arizona ash": ["ash", "ash tree", "fraxinus velutina"],
    "arizona cypress": ["cupressus arizonica", "cypress", "cypress tree"],
    "arizona sycamore": ["plane tree", "platan", "platanus wrightii", "sycamore"],
    "arizona white oak": ["quercus arizonica", "white oak"],
    "arizonan": ["american", "arizonian"],
    "arjuna": [],
    "ark": ["ark of the covenant"],
    "ark shell": ["bivalve", "lamellibranch", "pelecypod"],
    "arkansan": ["american", "arkansawyer"],
    "arkansas": ["arkansas river"],
    "arkansas kingbird": ["kingbird", "tyrannus tyrannus", "western kingbird"],
    "arlington": [],
    "arm": ["furnish", "munition", "provide", "rearm", "render", "supply"],
    "arm bone": ["elbow bone", "humerus", "long bone", "os longum", "radius", "ulna"],
    "arm exercise": ["chin-up", "exercise", "exercising", "physical exercise", "physical exertion", "press-up", "pull-up", "pushup", "workout"],
    "arm guard": ["arm pad", "protective garment"],
    "arm's length": ["distance", "length"],
    "arm-twisting": ["persuasion", "suasion"],
    "armada": ["fleet"],
    "armadillidiidae": ["arthropod family", "family armadillidiidae"],
    "armadillidium": ["arthropod genus", "genus armadillidium"],
    "armadillo": ["apar", "burmeisteria retusa", "cabassous", "cabassous unicinctus", "chlamyphore", "chlamyphorus truncatus", "dasypus novemcinctus", "edentate", "euphractus sexcinctus", "fairy armadillo", "giant armadillo", "greater pichiciego", "nine-banded armadillo", "peba", "peludo", "pichiciago", "pichiciego", "poyou", "priodontes giganteus", "tatou", "tatouay", "tatu", "texas armadillo", "three-banded armadillo", "tolypeutes tricinctus"],
    "armageddon": [],
    "armagnac": ["brandy"],
    "armament": ["armory", "armoury", "arms", "arsenal", "artillery", "broadside", "gun", "heavy weapon", "implements of war", "launcher", "munition", "ordnance", "ordnance store", "rocket launcher", "torpedo", "weaponry", "weapons system"],
    "armamentarium": ["accumulation", "aggregation", "assemblage", "collection"],
    "armata corsa": ["corsican army"],
    "armature": ["coil", "rotor", "rotor coil"],
    "armband": ["visual signal"],
    "armchair": ["captain's chair", "chair", "easy chair", "fauteuil", "lounge chair", "lounger", "morris chair", "overstuffed chair", "recliner", "reclining chair"],
    "armchair liberal": ["liberal", "liberalist", "progressive"],
    "armed": [],
    "armed forces censorship": ["military censorship", "primary censorship", "secondary censorship"],
    "armed forces day": ["day"],
    "armed islamic group": ["gia"],
    "armed robbery": ["heist", "holdup", "robbery", "stickup"],
    "armenia": ["hayastan", "republic of armenia"],
    "armenian": ["asian", "asiatic"],
    "armenian church": ["armenian apostolic orthodox church", "christian church", "church"],
    "armenian monetary unit": ["dram", "lumma", "monetary unit"],
    "armenian secret army for the liberation of armenia": ["3rd october organization", "asala", "orly group"],
    "armeria": ["dicot genus", "genus armeria", "magnoliopsid genus"],
    "armet": ["helmet"],
    "armful": ["containerful"],
    "armhole": ["hole"],
    "armiger": ["armor-bearer", "squire"],
    "armilla": ["bangle", "bracelet"],
    "armillaria": ["fungus genus", "genus armillaria"],
    "armillaria caligata": ["agaric", "booted armillaria"],
    "armillaria ponderosa": ["agaric", "white matsutake"],
    "armillaria zelleri": ["agaric"],
    "armillariella": ["fungus genus", "genus armillariella"],
    "armillary": [],
    "armillary sphere": ["armilla", "celestial globe"],
    "arming": ["armament", "equipping", "militarisation", "militarization", "mobilisation", "mobilization", "outfitting", "rearmament"],
    "arminian": ["adherent", "disciple"],
    "arminian baptist": ["baptist denomination", "general baptist"],
    "arminian church": ["protestant denomination"],
    "arminianism": ["protestantism"],
    "arminius": ["jacob harmensen", "jacobus arminius", "jakob hermandszoon"],
    "armistice": ["cease-fire", "peace", "truce"],
    "armless": [],
    "armlet": ["arm band", "band"],
    "armlike": [],
    "armoire": ["closet", "press", "wardrobe"],
    "armor": ["armour", "equip", "fit", "fit out", "outfit"],
    "armor plate": ["aegis", "armor plating", "armour plate", "backplate", "beaver", "brassard", "breastplate", "cannon", "chamfron", "chanfron", "cubitiere", "cuisse", "egis", "epauliere", "fauld", "front-stall", "frontstall", "gorget", "greave", "helmet", "jambeau", "knee piece", "nosepiece", "palette", "pallette", "plate", "plate armor", "plate armour", "roundel", "sabaton", "scale", "shell", "skirt of tasses", "solleret", "tasse", "tasset", "testiere", "tuille", "visor", "vizor"],
    "armor-clad": ["armor-plated", "armour-clad", "armour-plated", "steel-plated"],
    "armoracia": ["dilleniid dicot genus", "genus armoracia"],
    "armored": ["panoplied"],
    "armored car": ["armored vehicle", "armoured car", "armoured vehicle"],
    "armored catfish": ["catfish", "siluriform fish"],
    "armored dinosaur": ["ankylosaur", "ankylosaurus", "ornithischian", "ornithischian dinosaur", "stegosaur", "stegosaur stenops", "stegosaurus"],
    "armored personnel carrier": ["apc", "armored vehicle", "armoured personnel carrier", "armoured vehicle"],
    "armored scale": ["aspidiotus perniciosus", "san jose scale", "scale insect"],
    "armored searobin": ["armored sea robin", "peristedion miniatum", "sea robin", "searobin"],
    "armored vehicle": ["apc", "armored car", "armored combat vehicle", "armored personnel carrier", "armoured car", "armoured combat vehicle", "armoured personnel carrier", "armoured vehicle", "army tank", "assault gun", "self-propelled vehicle", "tank", "tank destroyer"],
    "armorer": ["armourer", "skilled worker", "skilled workman", "trained worker"],
    "armorial": [],
    "armory": ["armoury", "imagination", "inventory", "resource", "resourcefulness"],
    "armpit": ["axilla", "axillary cavity", "axillary fossa", "bodily cavity", "cavity", "cavum"],
    "armrest": ["arm", "rest"],
    "arms control": ["limitation", "restriction"],
    "arms deal": ["business deal", "deal", "trade"],
    "arms manufacturer": ["manufacturer", "producer"],
    "arms race": ["race"],
    "armstrong": ["neil armstrong"],
    "army": ["armed service", "army of the confederacy", "confederate army", "continental army", "ground forces", "host", "legion", "military service", "regular army", "service", "standing army", "union army"],
    "army ant": ["ant", "driver ant", "emmet", "legionary ant", "pismire"],
    "army attache": ["military attache"],
    "army base": ["base", "base of operations"],
    "army brat": ["child", "kid"],
    "army cutworm": ["chorizagrotis auxiliaris", "cutworm"],
    "army engineer": ["applied scientist", "engineer", "military engineer", "sapper", "technologist"],
    "army for the liberation of rwanda": ["alir", "far", "former armed forces", "interahamwe"],
    "army high performance computing research center": ["ahpcrc"],
    "army intelligence": ["agency", "ai", "authority", "bureau", "federal agency", "government agency", "office"],
    "army national guard": ["arng", "home reserve", "national guard"],
    "army officer": ["military officer", "officer", "quartermaster"],
    "army unit": ["army corps", "artillery", "artillery unit", "battalion", "battle group", "brigade", "cavalry", "company", "corps", "detachment", "division", "foot", "force", "infantry", "military force", "military group", "military unit", "musketry", "platoon", "regiment", "section", "squad", "troop", "van", "vanguard"],
    "armyworm": ["army worm", "caterpillar", "pseudaletia unipuncta"],
    "arnhem": [],
    "arnica": ["tincture"],
    "arnica montana": ["wild flower", "wildflower"],
    "arno": ["arno river", "river arno"],
    "arnold": ["matthew arnold"],
    "arnold of brescia": [],
    "arnold-chiari deformity": ["deformity", "malformation", "misshapenness"],
    "arnoseris": ["asterid dicot genus", "genus arnoseris"],
    "aroeira blanca": ["schinus chichita", "tree"],
    "aroid": ["araceous"],
    "aroma": ["fragrance", "incense", "odor", "odour", "olfactory perception", "olfactory sensation", "perfume", "scent", "smell"],
    "aromatherapy": ["therapy"],
    "aromatic": [],
    "aromatic aster": ["aster"],
    "aromatic compound": ["hydrocarbon"],
    "aromatic hydrocarbon": ["benzene", "benzine", "benzol", "hydrocarbon"],
    "around": [],
    "around the clock": ["for 24 hours", "round the clock"],
    "around-the-clock": ["day-and-night", "nonstop", "round-the-clock"],
    "arousal": ["alerting", "alertness", "desire", "emotional arousal", "excitation", "innervation", "irritation", "physical condition", "physiological condition", "physiological state", "sexual arousal"],
    "arouse": ["move", "stir"],
    "aroused": ["wound up"],
    "arp": ["hans arp", "jean arp"],
    "arpeggio": ["chord"],
    "arpent": ["area unit", "square measure"],
    "arquebus": ["hackbut", "hagbut", "harquebus", "muzzle loader"],
    "arrack": ["arak", "booze", "hard drink", "hard liquor", "john barleycorn", "liquor", "spirits", "strong drink"],
    "arraign": [],
    "arraignment": ["instrument", "legal document", "legal instrument", "official document"],
    "arrange": ["compose", "prearrange", "put", "set", "table", "tabularise", "tabularize", "tabulate", "transpose", "write"],
    "arranged": ["ordered"],
    "arrangement": ["aestivation", "array", "categorisation", "categorization", "classification", "contrivance", "estivation", "floral arrangement", "flower arrangement", "formation", "group", "grouping", "lash-up", "order", "ordering", "ordination", "scaffold", "tableau", "tableau vivant", "venation", "vernation"],
    "arranger": ["adapter", "musician", "orchestrator", "transcriber"],
    "arrant": ["complete", "consummate", "double-dyed", "everlasting", "gross", "perfect", "pure", "sodding", "staring", "stark", "thoroughgoing", "unadulterated", "utter"],
    "array": ["arrangement", "bank", "column", "matrix", "panoply", "row", "spectrum", "table", "tabular array"],
    "arrayed": ["panoplied"],
    "arrears": ["financial obligation", "indebtedness", "liability"],
    "arrest": ["check", "countercheck", "halt", "hitch", "inaction", "inactiveness", "inactivity", "logjam", "stay", "stop", "stoppage"],
    "arrested development": ["abnormalcy", "abnormality", "fixation", "infantile fixation", "regression"],
    "arrester": ["arrester hook", "constraint", "restraint"],
    "arresting": ["sensational", "stunning"],
    "arrhenatherum": ["genus arrhenatherum", "plant genus"],
    "arrhenius": ["svante august arrhenius"],
    "arrhythmic": ["jerking", "jerky"],
    "arrival": ["arriver", "comer", "early bird", "latecomer", "newcomer", "traveler", "traveller"],
    "arrival gate": ["gate"],
    "arrival time": ["point", "point in time", "time of arrival"],
    "arrive": ["bring home the bacon", "come through", "deliver the goods", "get in", "go far", "make it", "succeed", "win"],
    "arroba": ["weight", "weight unit"],
    "arrogance": ["condescension", "contemptuousness", "disdainfulness", "domineeringness", "haughtiness", "hauteur", "high-handedness", "hubris", "imperiousness", "lordliness", "overbearingness", "pride", "snobbery", "snobbishness", "snobbism", "superbia", "superciliousness", "superiority"],
    "arrogant": ["chesty", "self-important"],
    "arrogantly": [],
    "arrogate": ["arrogate", "assign", "claim", "lay claim"],
    "arrogator": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "arrow": ["mark", "pointer"],
    "arrow arum": ["aquatic plant", "green arrow arum", "hydrophyte", "hydrophytic plant", "peltandra virginica", "tuckahoe", "water plant"],
    "arrow grass": ["bog plant", "marsh plant", "swamp plant", "triglochin maritima"],
    "arrow leaved aster": ["aster"],
    "arrow wood": ["bush", "shrub", "viburnum recognitum"],
    "arrowhead": ["point"],
    "arrowleaf groundsel": ["senecio triangularis", "wild flower", "wildflower"],
    "arrowroot": ["amylum", "starch"],
    "arrowsmith": ["smith"],
    "arrowworm": ["chaetognath", "sagitta", "worm"],
    "arroyo": ["gully"],
    "arroyo willow": ["salix lasiolepis", "willow", "willow tree"],
    "arroz con pollo": ["chicken and rice"],
    "arse": ["anus", "arsehole", "asshole", "bunghole"],
    "arsenal": ["armament", "armory", "armoury"],
    "arsenate": ["salt"],
    "arsenic": ["arsenic trioxide", "arsenous anhydride", "arsenous oxide", "ratsbane", "trioxide", "white arsenic"],
    "arsenic acid": ["acid"],
    "arsenical": ["drug", "pesticide"],
    "arsenide": ["chemical compound", "compound"],
    "arsenious": [],
    "arsenopyrite": ["mineral", "mispickel"],
    "arsine": ["gas"],
    "arson": ["burning", "combustion", "fire-raising", "incendiarism"],
    "arsonist": ["barnburner", "criminal", "crook", "felon", "firebug", "incendiary", "malefactor", "outlaw"],
    "art": ["airmanship", "artistry", "aviation", "enology", "eristic", "falconry", "fortification", "homiletics", "horology", "minstrelsy", "musicianship", "oenology", "prowess", "puppetry", "superior skill", "taxidermy", "telescopy", "ventriloquism", "ventriloquy"],
    "art class": ["class", "course", "course of instruction", "course of study", "life class"],
    "art collection": ["accumulation", "aggregation", "assemblage", "collection", "loan collection"],
    "art critic": ["critic"],
    "art dealer": ["bargainer", "dealer", "monger", "print seller", "trader"],
    "art department": ["academic department"],
    "art director": ["stage director"],
    "art editor": ["editor", "editor in chief"],
    "art exhibition": ["exhibition", "expo", "exposition", "retrospective"],
    "art form": ["architectural style", "form", "kind", "sonata form", "sort", "style of architecture", "type of architecture", "variety"],
    "art historian": ["historian", "historiographer"],
    "art history": ["arts", "humanistic discipline", "humanities", "iconology", "liberal arts"],
    "art nouveau": ["art movement", "artistic movement", "school"],
    "art paper": ["paper"],
    "art school": ["conservatoire", "conservatory"],
    "art student": ["educatee", "pupil", "student"],
    "art teacher": ["instructor", "teacher"],
    "artamidae": ["bird family", "family artamidae"],
    "artamus": ["bird genus", "genus artamus"],
    "artaxerxes i": ["artaxerxes"],
    "artaxerxes ii": ["artaxerxes"],
    "artemia": ["arthropod genus", "chirocephalus", "genus artemia", "genus chirocephalus"],
    "artemis": ["cynthia"],
    "artemisia": ["artemisia dracunculus", "bush", "estragon", "shrub", "tarragon"],
    "artemision at ephesus": [],
    "arterial": [],
    "arterial blood": ["blood"],
    "arterial blood gases": ["measure", "measurement", "measuring", "mensuration"],
    "arterial plaque": ["plaque"],
    "arterial pressure": ["blood pressure"],
    "arterial road": ["highway", "main road"],
    "arterialize": ["alter", "arterialise", "change", "modify"],
    "arteriectasis": ["arteriectasia", "pathology"],
    "arteriogram": ["roentgenogram", "x ray", "x-ray", "x-ray photograph", "x-ray picture"],
    "arteriography": ["arthrography"],
    "arteriolar": [],
    "arteriole": ["arteria", "arterial blood vessel", "arteriola", "artery", "capillary artery"],
    "arteriolosclerosis": ["induration", "sclerosis"],
    "arteriosclerosis": ["arterial sclerosis", "arteriosclerosis obliterans", "atherosclerosis", "coronary artery disease", "coronary-artery disease", "hardening of the arteries", "induration", "induration of the arteries", "sclerosis"],
    "arteriosclerosis obliterans": ["arterial sclerosis", "arteriosclerosis", "coronary-artery disease", "hardening of the arteries", "induration of the arteries"],
    "arteriosclerotic": [],
    "arteriovenous": [],
    "arteritis": ["inflammation", "periarteritis", "polyarteritis", "pulseless disease", "redness", "rubor", "takayasu's arteritis", "temporal arteritis"],
    "artery": ["alveolar artery", "angular artery", "aorta", "appendicular artery", "arcuate artery", "arcuate artery of the kidney", "areteria cervicalis", "arteria", "arteria alveolaris", "arteria angularis", "arteria appendicularis", "arteria arcuata", "arteria ascendens", "arteria auricularis", "arteria axillaris", "arteria basilaris", "arteria brachialis", "arteria buccalis", "arteria bulbi penis", "arteria bulbi vestibuli", "arteria carotis", "arteria celiaca", "arteria centralis retinae", "arteria cerebelli", "arteria cerebri", "arteria choroidea", "arteria ciliaris", "arteria colica", "arteria communicans", "arteria coronaria", "arteria cystica", "arteria digitalis", "arteria epigastrica", "arteria ethmoidalis", "arteria femoralis", "arteria gastrica", "arteria glutes", "arteria hepatica", "arteria ileocolica", "arteria ileum", "arteria iliaca", "arteria iliolumbalis", "arteria infraorbitalis", "arteria intercostalis", "arteria labialis", "arteria lacrimalis", "arteria laryngea", "arteria lienalis", "arteria lingualis", "arteria lumbalis", "arteria maxillaris", "arteria meningea", "arteria mesenterica", "arteria metacarpea", "arteria metatarsea", "arteria musculophrenica", "arteria nutricia", "arteria ophthalmica", "arteria ovarica", "arteria palatina", "arteria pancreatica", "arteria perinealis", "arteria poplitea", "arteria pudenda", "arteria pulmonalis", "arteria radialis", "arteria rectalis", "arteria renalis", "arteria subclavia", "arteria testicularis", "arteria ulnaris", "arteria uterina", "arteria vaginalis", "arteria vertebralis", "arterial blood vessel", "arteriola", "arteriole", "artery of the labyrinth", "artery of the penis bulb", "artery of the vestibule bulb", "ascending artery", "auricular artery", "axillary artery", "basilar artery", "blood vessel", "brachial artery", "bronchial artery", "buccal artery", "capillary artery", "carotid artery", "celiac artery", "celiac trunk", "central artery of the retina", "cerebellar artery", "cerebral artery", "cervical artery", "choroidal artery", "ciliary artery", "circle of willis", "circumflex artery", "colic artery", "communicating artery", "coronary artery", "cystic artery", "digital arteries", "epigastric artery", "ethmoidal artery", "femoral artery", "gastric artery", "gluteal artery", "hepatic artery", "ileal artery", "ileocolic artery", "iliac artery", "iliolumbar artery", "infraorbital artery", "innominate artery", "intercostal artery", "internal auditory artery", "internal spermatic artery", "intestinal artery", "jejunal artery", "labial artery", "labyrinthine artery", "lacrimal artery", "laryngeal artery", "lienal artery", "lingual artery", "lumbar artery", "maxillary artery", "meningeal artery", "mesenteric artery", "metacarpal artery", "metatarsal artery", "musculophrenic artery", "nutrient artery", "ophthalmic artery", "ovarian artery", "palatine artery", "pancreatic artery", "perineal artery", "popliteal artery", "pudendal artery", "pulmonary artery", "radial artery", "rectal artery", "renal artery", "splenic artery", "subclavian artery", "testicular artery", "truncus celiacus", "ulnar artery", "uterine artery", "vaginal artery", "vertebral artery"],
    "artery of the penis bulb": ["arteria", "arteria bulbi penis", "arterial blood vessel", "artery"],
    "artery of the vestibule bulb": ["arteria", "arteria bulbi vestibuli", "arterial blood vessel", "artery"],
    "artesian": [],
    "artesian well": ["well"],
    "artful": [],
    "artfully": [],
    "artfulness": ["cunning", "disingenuousness"],
    "arthralgia": ["hurting", "pain"],
    "arthralgic": [],
    "arthritic": ["patient"],
    "arthritis": ["atrophic arthritis", "degenerative arthritis", "degenerative joint disease", "gout", "gouty arthritis", "inflammatory disease", "osteoarthritis", "rheumatism", "rheumatoid arthritis", "spondylarthritis", "urarthritis"],
    "arthrocentesis": ["centesis"],
    "arthrodesis": ["arthroplasty"],
    "arthrogram": ["roentgenogram", "x ray", "x-ray", "x-ray photograph", "x-ray picture"],
    "arthrography": ["arteriography", "roentgenography", "venography", "x-ray photography"],
    "arthromere": ["external body part"],
    "arthromeric": [],
    "arthropathy": ["pathology"],
    "arthroplasty": ["arthrodesis", "operation", "surgery", "surgical operation", "surgical procedure", "surgical process"],
    "arthropod": ["arachnid", "arachnoid", "asian horseshoe crab", "centipede", "class merostomata", "crustacean", "eurypterid", "garden centipede", "garden symphilid", "horseshoe crab", "insect", "instar", "invertebrate", "king crab", "limulus polyphemus", "merostomata", "millepede", "milliped", "millipede", "myriapod", "onychophoran", "pentastomid", "peripatus", "pycnogonid", "scutigerella immaculata", "sea spider", "symphilid", "tardigrade", "tongue worm", "trilobite", "velvet worm", "xiphosurus polyphemus"],
    "arthropod family": ["acaridae", "acrididae", "adelgidae", "aleyrodidae", "andrenidae", "anobiidae", "aphididae", "aphidoidea", "apidae", "apoidea", "arctiidae", "argasidae", "argiopidae", "armadillidiidae", "asilidae", "astacidae", "astacura", "atropidae", "balanidae", "belostomatidae", "blattidae", "bombycidae", "bombyliidae", "bruchidae", "calliphoridae", "cancridae", "capsidae", "carabidae", "cecidomyidae", "cerambycidae", "ceratopogonidae", "cercopidae", "cetoniidae", "chalcidae", "chalcididae", "chermidae", "chironomidae", "chrysomelidae", "chrysopidae", "cicadellidae", "cicadidae", "cicindelidae", "cimicidae", "cleridae", "coccidae", "coccinellidae", "coccoidea", "coreidae", "corixidae", "corydalidae", "crangonidae", "cryptocercidae", "ctenizidae", "culicidae", "curculionidae", "cuterebridae", "cynipidae", "dactylopiidae", "danaidae", "dermestidae", "diaspididae", "dorylinae", "drosophilidae", "dytiscidae", "elateridae", "ephemeridae", "family", "family acaridae", "family acrididae", "family adelgidae", "family aleyrodidae", "family andrenidae", "family anobiidae", "family aphididae", "family apidae", "family arctiidae", "family argasidae", "family argiopidae", "family armadillidiidae", "family asilidae", "family astacidae", "family atropidae", "family balanidae", "family belostomatidae", "family blattidae", "family bombycidae", "family bombyliidae", "family bruchidae", "family calliphoridae", "family cancridae", "family capsidae", "family carabidae", "family cecidomyidae", "family cerambycidae", "family ceratopogonidae", "family cercopidae", "family chalcidae", "family chalcididae", "family chermidae", "family chironomidae", "family chrysomelidae", "family chrysopidae", "family cicadellidae", "family cicadidae", "family cicindelidae", "family cimicidae", "family cleridae", "family coccidae", "family coccinellidae", "family coreidae", "family corixidae", "family corydalidae", "family crangonidae", "family cryptocercidae", "family ctenizidae", "family culicidae", "family curculionidae", "family cuterebridae", "family cynipidae", "family dactylopiidae", "family danaidae", "family dermestidae", "family diaspididae", "family drosophilidae", "family dytiscidae", "family elateridae", "family ephemeridae", "family forficulidae", "family formicidae", "family fulgoridae", "family gasterophilidae", "family gelechiidae", "family geometridae", "family geophilidae", "family gerridae", "family gerrididae", "family glossinidae", "family gracilariidae", "family gryllidae", "family gyrinidae", "family halictidae", "family hemerobiidae", "family hippoboscidae", "family homaridae", "family hypodermatidae", "family ichneumonidae", "family ipidae", "family ixodidae", "family jassidae", "family kalotermitidae", "family lampyridae", "family lasiocampidae", "family lepadidae", "family lepismatidae", "family limulidae", "family lithodidae", "family locustidae", "family lucanidae", "family lycaenidae", "family lycosidae", "family lygaeidae", "family lymantriidae", "family machilidae", "family majidae", "family manteidae", "family mantidae", "family mantispidae", "family mastotermitidae", "family megachilidae", "family meloidae", "family membracidae", "family miridae", "family muscidae", "family mycetophylidae", "family myrmeleontidae", "family mysidae", "family nephropsidae", "family nepidae", "family noctuidae", "family notonectidae", "family nymphalidae", "family oestridae", "family oniscidae", "family orchestiidae", "family paguridae", "family palaemonidae", "family palinuridae", "family pediculidae", "family peneidae", "family peripatidae", "family peripatopsidae", "family phalangiidae", "family phasmatidae", "family phasmidae", "family phillidae", "family phthiriidae", "family phyllidae", "family phylloxeridae", "family pieridae", "family pinnotheridae", "family porcellionidae", "family portunidae", "family pseudococcidae", "family psocidae", "family psychodidae", "family psyllidae", "family pulicidae", "family pyralidae", "family pyralididae", "family pyrrhocoridae", "family raphidiidae", "family reduviidae", "family rhinotermitidae", "family sarcoptidae", "family saturniidae", "family satyridae", "family scarabaeidae", "family sciaridae", "family scolytidae", "family scutigeridae", "family sialidae", "family simuliidae", "family sisyridae", "family sphecidae", "family sphingidae", "family squillidae", "family staphylinidae", "family stenopelmatidae", "family stizidae", "family tabanidae", "family tachinidae", "family tenebrionidae", "family tenthredinidae", "family termitidae", "family tetranychidae", "family tettigoniidae", "family theraphosidae", "family theridiidae", "family thripidae", "family tineidae", "family tingidae", "family tipulidae", "family tortricidae", "family trephritidae", "family triopidae", "family trombiculidae", "family trombidiidae", "family trypetidae", "family vespidae", "forficulidae", "formicidae", "fulgoridae", "gasterophilidae", "gelechiidae", "geometridae", "geophilidae", "gerridae", "gerrididae", "glossinidae", "gracilariidae", "gracillariidae", "gryllidae", "gyrinidae", "halictidae", "hemerobiidae", "hippoboscidae", "homaridae", "hypodermatidae", "ichneumonidae", "ipidae", "ixodidae", "jassidae", "kalotermitidae", "lamellicornia", "lampyridae", "lasiocampidae", "lepadidae", "lepismatidae", "limulidae", "lithodidae", "locustidae", "lucanidae", "lycaenidae", "lycosidae", "lygaeidae", "lymantriidae", "machilidae", "majidae", "manteidae", "mantidae", "mantispidae", "mastotermitidae", "megachilidae", "meloidae", "melolonthidae", "membracidae", "miridae", "muscidae", "muscoidea", "mycetophilidae", "myrmeleontidae", "mysidae", "nephropsidae", "nepidae", "noctuidae", "notonectidae", "nymphalidae", "oestridae", "oniscidae", "orb-weaver", "orchestiidae", "paguridae", "palaemonidae", "palinuridae", "pediculidae", "peneidae", "peripatidae", "peripatopsidae", "phalangiidae", "phasmatidae", "phasmidae", "phillidae", "phthiriidae", "phyllidae", "phylloxeridae", "pieridae", "pinnotheridae", "porcellionidae", "portunidae", "pseudococcidae", "psocidae", "psychodidae", "psyllidae", "pulicidae", "pyralidae", "pyralididae", "pyrrhocoridae", "raphidiidae", "reduviidae", "rhinotermitidae", "sarcoptidae", "saturniidae", "satyridae", "scarabaeidae", "sciaridae", "scolytidae", "scutigeridae", "sialidae", "simuliidae", "sisyridae", "sphecidae", "sphecoidea", "sphingidae", "squillidae", "staphylinidae", "stenopelmatidae", "stizidae", "subfamily cetoniidae", "subfamily dorylinae", "subfamily melolonthidae", "superfamily aphidoidea", "superfamily apoidea", "superfamily coccoidea", "superfamily lamellicornia", "superfamily muscoidea", "superfamily sphecoidea", "superfamily tineoidea", "tabanidae", "tachinidae", "tenebrionidae", "tenthredinidae", "termitidae", "tetranychidae", "tettigoniidae", "theraphosidae", "theridiidae", "thripidae", "tineidae", "tineoidea", "tingidae", "tipulidae", "tortricidae", "trephritidae", "triopidae", "trombiculidae", "trombidiidae", "trypetidae", "vespidae"],
    "arthropod genus": ["acanthoscelides", "acherontia", "acheta", "actias", "adalia", "adelges", "aedes", "aleyrodes", "alsophila", "amphibolips", "anabrus", "anagasta", "anasa", "andricus", "anomala", "anopheles", "antheraea", "anthidium", "anthonomus", "apatura", "aphis", "aphrophora", "apis", "aranea", "araneus", "argiope", "argynnis", "argyrotaenia", "arilus", "armadillidium", "artemia", "aspidiotus", "astacus", "atticus", "automeris", "balanus", "bemisia", "blaberus", "blatta", "blattella", "blissus", "bombus", "bombyx", "brachinus", "bruchus", "cadra", "callimorpha", "callinectes", "calliphora", "cambarus", "camponotus", "cancer", "caprella", "carpocapsa", "catacala", "cerapteryx", "ceratitis", "ceratopogon", "cetonia", "chalcis", "chelifer", "chirocephalus", "chironomus", "chorizagrotis", "cimex", "corixa", "corydalis", "corydalus", "crangon", "cryptocercus", "cryptotermes", "ctenocephalides", "culex", "cuterebra", "cyamus", "cynips", "dactylopius", "danaus", "dendroctonus", "dermacentor", "dermatobia", "dialeurodes", "dysdercus", "eacles", "echidnophaga", "ephestia", "epilachna", "eriosoma", "eumenes", "euproctis", "fenusa", "forficula", "formica", "frankliniella", "galleria", "gasterophilus", "gelechia", "genus", "genus acanthoscelides", "genus acherontia", "genus acheta", "genus actias", "genus adalia", "genus adelges", "genus aedes", "genus aleyrodes", "genus alsophila", "genus amphibolips", "genus anabrus", "genus anagasta", "genus anasa", "genus andrena", "genus andricus", "genus anomala", "genus anopheles", "genus antheraea", "genus anthidium", "genus anthonomus", "genus apatura", "genus aphis", "genus aphrophora", "genus apis", "genus aranea", "genus araneus", "genus architeuthis", "genus argiope", "genus argynnis", "genus argyrotaenia", "genus arilus", "genus armadillidium", "genus artemia", "genus aspidiotus", "genus astacus", "genus atticus", "genus automeris", "genus balanus", "genus bemisia", "genus blaberus", "genus blatta", "genus blattella", "genus blissus", "genus bombus", "genus bombyx", "genus brachinus", "genus bruchus", "genus cadra", "genus callimorpha", "genus callinectes", "genus calliphora", "genus calosoma", "genus cambarus", "genus camponotus", "genus cancer", "genus caprella", "genus carpocapsa", "genus catacala", "genus cerapteryx", "genus ceratitis", "genus ceratopogon", "genus cetonia", "genus chalcis", "genus chelifer", "genus chirocephalus", "genus chironomus", "genus chorizagrotis", "genus cicada", "genus cimex", "genus coccus", "genus corixa", "genus corydalis", "genus corydalus", "genus crangon", "genus cryptocercus", "genus cryptotermes", "genus ctenocephalides", "genus culex", "genus cuterebra", "genus cyamus", "genus cyclops", "genus cynips", "genus dactylopius", "genus danaus", "genus daphnia", "genus dendroctonus", "genus dermacentor", "genus dermatobia", "genus dialeurodes", "genus diapheromera", "genus drosophila", "genus dysdercus", "genus eacles", "genus echidnophaga", "genus ephestia", "genus epilachna", "genus eriosoma", "genus eumenes", "genus euproctis", "genus forficula", "genus formica", "genus frankliniella", "genus galleria", "genus gasterophilus", "genus gelechia", "genus geophilus", "genus gerris", "genus glossina", "genus haematobia", "genus heliothis", "genus hippobosca", "genus hippodamia", "genus homarus", "genus homona", "genus hyalophora", "genus hyphantria", "genus hypoderma", "genus inachis", "genus ixodes", "genus kalotermes", "genus lasiocampa", "genus latrodectus", "genus lepas", "genus lepisma", "genus leptinotarsa", "genus leptoglossus", "genus limenitis", "genus limulus", "genus liposcelis", "genus locusta", "genus loxostege", "genus lucilia", "genus lycaena", "genus lycosa", "genus lygus", "genus lymantria", "genus macrocheira", "genus macrodactylus", "genus magicicada", "genus maia", "genus maja", "genus malacosoma", "genus manduca", "genus mantis", "genus mastigoproctus", "genus mastotermes", "genus mayetiola", "genus megachile", "genus melanoplus", "genus melolontha", "genus melophagus", "genus menippe", "genus menopon", "genus microcentrum", "genus monochamus", "genus monomorium", "genus musca", "genus myrmecia", "genus myrmeleon", "genus mysis", "genus nepa", "genus nephrops", "genus noctua", "genus nomia", "genus notonecta", "genus nymphalis", "genus oecanthus", "genus oestrus", "genus oniscus", "genus orchestia", "genus ovalipes", "genus pagurus", "genus palaemon", "genus paleacrita", "genus palinurus", "genus panonychus", "genus paralithodes", "genus pediculus", "genus peneus", "genus peripatopsis", "genus peripatus", "genus periplaneta", "genus phalangium", "genus philaenus", "genus philophylla", "genus phlebotomus", "genus phthirius", "genus phthirus", "genus phthorimaea", "genus phyllium", "genus phylloxera", "genus pieris", "genus pineus", "genus pinnotheres", "genus planococcus", "genus plicatoperipatus", "genus poecilocapsus", "genus polistes", "genus polyergus", "genus polygonia", "genus popillia", "genus porcellio", "genus portunus", "genus praunus", "genus prociphilus", "genus pseudaletia", "genus pseudococcus", "genus psithyrus", "genus pulex", "genus pyralis", "genus pyrausta", "genus pyrophorus", "genus ranatra", "genus reticulitermes", "genus rhagoletis", "genus rodolia", "genus samia", "genus sarcophaga", "genus sarcoptes", "genus saturnia", "genus scarabaeus", "genus sceliphron", "genus sciara", "genus scolytus", "genus scutigera", "genus scutigerella", "genus sialis", "genus simulium", "genus sitophylus", "genus sitotroga", "genus solenopsis", "genus sphecius", "genus spodoptera", "genus spyeria", "genus squilla", "genus stenopelmatus", "genus strymon", "genus tachypleus", "genus termes", "genus thermobia", "genus thrips", "genus tibicen", "genus tinea", "genus tineola", "genus tortrix", "genus trialeurodes", "genus triatoma", "genus tribolium", "genus trichophaga", "genus triops", "genus trogium", "genus trombicula", "genus tunga", "genus uca", "genus vanessa", "genus vedalia", "genus vespa", "genus vespula", "genus xylocopa", "genus-fenusa", "geophilus", "gerris", "haematobia", "heliothis", "hippobosca", "hippodamia", "homarus", "homona", "hyalophora", "hyphantria", "hypoderma", "inachis", "ixodes", "kalotermes", "lasiocampa", "latrodectus", "lepas", "lepisma", "leptinotarsa", "leptoglossus", "limenitis", "limulus", "liposcelis", "locusta", "loxostege", "lucilia", "lycaena", "lycosa", "lygus", "lymantria", "macrocheira", "macrodactylus", "magicicada", "maia", "maja", "malacosoma", "manduca", "mastigoproctus", "mastotermes", "mayetiola", "megachile", "melanoplus", "melolontha", "melophagus", "menippe", "menopon", "microcentrum", "monochamus", "monomorium", "musca", "myrmecia", "myrmeleon", "mysis", "nepa", "nephrops", "noctua", "nomia", "notonecta", "nymphalis", "oecanthus", "oestrus", "oniscus", "orchestia", "ovalipes", "pagurus", "palaemon", "paleacrita", "palinurus", "panonychus", "paralithodes", "pediculus", "peneus", "peripatopsis", "periplaneta", "phalangium", "philaenus", "philophylla", "phlebotomus", "phthirius", "phthirus", "phthorimaea", "phyllium", "phylloxera", "pieris", "pineus", "pinnotheres", "planococcus", "plicatoperipatus", "poecilocapsus", "polistes", "polyergus", "polygonia", "popillia", "porcellio", "portunus", "praunus", "prociphilus", "pseudaletia", "pseudococcus", "psithyrus", "pulex", "pyralis", "pyrausta", "pyrophorus", "ranatra", "reticulitermes", "rhagoletis", "rodolia", "samia", "sarcophaga", "sarcoptes", "saturnia", "sceliphron", "scolytus", "scutigera", "scutigerella", "sialis", "simulium", "sitophylus", "sitotroga", "solenopsis", "sphecius", "spodoptera", "spyeria", "stenopelmatus", "strymon", "tachypleus", "termes", "thermobia", "tibicen", "tinea", "tineola", "trialeurodes", "triatoma", "tribolium", "trichophaga", "triops", "trogium", "trombicula", "tunga", "uca", "vanessa", "vespa", "vespula", "xylocopa"],
    "arthropoda": ["phylum", "phylum arthropoda"],
    "arthropodal": ["arthropodan", "arthropodous"],
    "arthropteris": ["fern genus", "genus arthropteris"],
    "arthroscope": ["endoscope"],
    "arthroscopy": ["operation", "surgery", "surgical operation", "surgical procedure", "surgical process"],
    "arthrospore": ["cell"],
    "arthrosporic": ["arthrosporous"],
    "arthur": ["chester a. arthur", "chester alan arthur", "president arthur"],
    "arthurian": [],
    "arthurian legend": ["fable", "legend"],
    "artichoke": ["artichoke plant", "cynara scolymus", "globe artichoke", "vegetable"],
    "artichoke heart": ["veg", "vegetable", "veggie"],
    "article": ["bind", "hold", "obligate", "oblige"],
    "article of commerce": ["article", "tinware", "ware"],
    "article of faith": ["credendum", "dogma", "tenet"],
    "articles of agreement": ["contract", "shipping articles"],
    "articles of confederation": [],
    "articles of incorporation": ["instrument", "legal document", "legal instrument", "official document"],
    "articular": ["articulary"],
    "articular muscle": ["musculus articularis cubiti", "musculus articularis genus", "skeletal muscle", "striated muscle"],
    "articulate": ["connect", "join", "link", "link up", "unite"],
    "articulated": ["articulate"],
    "articulated ladder": ["ladder"],
    "articulately": ["eloquently"],
    "articulation": ["connection", "connexion", "esophagogastric junction", "join", "joint", "junction", "juncture", "link", "oesophagogastric junction"],
    "articulator": ["communicator", "speaker", "subvocaliser", "subvocalizer", "talker", "utterer", "verbaliser", "verbalizer"],
    "articulatory": ["articulative"],
    "articulatory system": ["system"],
    "artifact": ["americana", "anachronism", "antiquity", "artefact", "article", "bed", "block", "building material", "button", "cloth", "commodity", "cone", "construction", "covering", "creation", "cushioning", "decker", "decoration", "duplicate", "electroplate", "excavation", "extra", "fabric", "facility", "fixture", "flat solid", "float", "good", "insert", "inset", "installation", "instrumentality", "instrumentation", "layer", "lemon", "line", "marker", "material", "mystification", "opening", "ornament", "ornamentation", "padding", "pavement", "paving", "paving material", "plaything", "ready-made", "restoration", "sheet", "slip", "sphere", "square", "squeaker", "stinker", "strip", "structure", "surface", "textile", "thing", "toy", "track", "trade good", "unit", "way", "weight", "whole"],
    "artifactual": ["artefactual"],
    "artificial": [],
    "artificial blood": ["liquid"],
    "artificial flower": ["art", "fine art"],
    "artificial heart": ["implant", "jarvik artificial heart", "jarvik heart"],
    "artificial horizon": ["flight indicator", "gyro horizon", "navigational instrument"],
    "artificial insemination": ["ai", "insemination"],
    "artificial intelligence": ["ai", "computer science", "computing", "machine translation", "mt", "robotics"],
    "artificial joint": ["implant"],
    "artificial kidney": ["dialysis machine", "dialyzer", "hemodialyzer"],
    "artificial language": ["antido", "arulo", "basic english", "blaia zimondal", "esperantido", "esperanto", "europan", "idiom neutral", "ido", "interlingua", "language", "latinesce", "latino", "lingualumina", "linguistic communication", "lingvo kosmopolita", "monario", "nov-esperanto", "nov-latin", "novial", "occidental", "optez", "pasigraphy", "pidgin", "programing language", "programming language", "ro", "romanal", "solresol", "volapuk"]
}
