synonyms = {
    "fitted out": ["outfitted"],
    "fitted sheet": ["contour sheet"],
    "fitter": ["healthier"],
    "fitting": ["try-on", "trying on"],
    "fitzgerald": ["edward fitzgerald"],
    "five": ["cinque", "fin", "fivesome", "little phoebe", "pentad", "phoebe", "quint", "quintet", "quintuplet"],
    "five hundred": ["500"],
    "five-hitter": ["5-hitter"],
    "five-hundredth": ["500th"],
    "five-membered": ["5-membered"],
    "five-petaled": ["five-petalled"],
    "five-point bishop's cap": ["mitella pentandra"],
    "five-spot": ["nemophila maculata"],
    "fiver": ["five dollar bill", "five-spot"],
    "fix": ["gear up", "prepare", "ready", "set", "set up"],
    "fixate": ["fix"],
    "fixation": ["fixing"],
    "fixed": ["rigid", "set"],
    "fixed charge": ["fixed cost", "fixed costs"],
    "fixed oil": ["fatty oil"],
    "fixed-point notation": ["fixed-point representation system"],
    "fixedness": ["unalterability"],
    "fixer": ["influence peddler"],
    "fixing agent": ["fixer"],
    "fixings": ["trimmings"],
    "fizzing": ["fizzy"],
    "fjord": ["fiord"],
    "flabbergast": ["boggle", "bowl over"],
    "flabbiness": ["flaccidity", "limpness"],
    "flacourtia": ["genus flacourtia"],
    "flacourtiaceae": ["family flacourtiaceae", "flacourtia family"],
    "flag": ["signal flag"],
    "flag day": ["june 14"],
    "flag waving": ["jingoism"],
    "flagellate": ["scourge"],
    "flageolet": ["haricot"],
    "flagfish": ["american flagfish", "jordanella floridae"],
    "flagitious": ["heinous"],
    "flagpole": ["flagstaff"],
    "flail": ["thresh"],
    "flair": ["genius"],
    "flak catcher": ["flack", "flack catcher", "flak"],
    "flaky": ["flakey"],
    "flamboyance": ["floridity", "floridness", "showiness"],
    "flamboyant": ["showy", "splashy"],
    "flamboyantly": ["flashily", "showily"],
    "flame fish": ["apogon maculatus", "flamefish"],
    "flame flower": ["flame-flower", "flameflower", "talinum aurantiacum"],
    "flame tree": ["christmas tree", "fire tree", "nuytsia floribunda"],
    "flame-colored": ["flame-coloured"],
    "flamenco": ["gypsy dancing"],
    "flameproof": ["flame-retardant"],
    "flamingo flower": ["anthurium andraeanum", "anthurium scherzerianum", "flamingo plant"],
    "flaminius": ["gaius flaminius"],
    "flammability": ["inflammability"],
    "flammable": ["inflammable"],
    "flammulina": ["genus flammulina"],
    "flange": ["rim"],
    "flank": ["wing"],
    "flanker back": ["flanker"],
    "flannel": ["gabardine", "tweed", "white"],
    "flannelbush": ["california beauty", "flannel bush"],
    "flap": ["flapping", "flutter", "fluttering"],
    "flare": ["flame"],
    "flare out": ["flare"],
    "flare pass": ["flare"],
    "flash": ["blink", "twinkle", "wink", "winkle"],
    "flash card": ["flashcard"],
    "flash flood": ["flashflood"],
    "flash point": ["flashpoint"],
    "flash welding": ["flash butt welding"],
    "flash-frozen": ["frozen", "quick-frozen"],
    "flashboard": ["flashboarding"],
    "flashiness": ["brashness", "garishness", "gaudiness", "glitz", "loudness", "meretriciousness", "tawdriness"],
    "flashlight": ["torch"],
    "flashlight fish": ["photoblepharon palpebratus"],
    "flashy": ["gaudy", "jazzy", "showy", "sporty"],
    "flask": ["flaskful"],
    "flat": ["flat tire"],
    "flat arch": ["straight arch"],
    "flat coat": ["ground", "primer", "primer coat", "priming", "priming coat", "undercoat"],
    "flat out": ["like blue murder"],
    "flat panel display": ["fpd"],
    "flat pea": ["platylobium formosum"],
    "flat-bottomed": ["flat-bottom"],
    "flat-topped": ["flat-top"],
    "flatbed press": ["cylinder press"],
    "flatbottom": ["flatbottomed"],
    "flatcar": ["flat", "flatbed"],
    "flatfoot": ["patrolman"],
    "flathead catfish": ["goujon", "mudcat", "pylodictus olivaris", "shovelnose catfish", "spoonbill catfish"],
    "flatly": ["categorically", "unconditionally"],
    "flatness": ["lusterlessness", "lustrelessness", "mat", "matt", "matte"],
    "flatten": ["flatten out"],
    "flatter": ["blandish"],
    "flatterer": ["adulator"],
    "flatulence": ["flatulency", "gas"],
    "flatware": ["silver"],
    "flatwork": ["flat wash"],
    "flatworm": ["platyhelminth"],
    "flaubert": ["gustave flaubert"],
    "flaunt": ["flash", "ostentate", "show off", "swank"],
    "flavor": ["flavour"],
    "flavorer": ["flavoring", "flavourer", "flavouring", "seasoner", "seasoning"],
    "flavorful": ["flavorous", "flavorsome", "flavourful", "flavourous", "flavoursome", "sapid", "saporous"],
    "flavorlessness": ["flavourlessness", "savorlessness", "savourlessness", "tastelessness"],
    "flavorsomeness": ["flavoursomeness", "savoriness"],
    "flaw": ["blemish"],
    "flawless": ["unflawed"],
    "flawlessly": ["cleanly"],
    "flax rust": ["flax rust fungus", "melampsora lini"],
    "flaxen": ["sandy"],
    "fleabane": ["feabane mullet", "pulicaria dysenterica"],
    "fleawort": ["plantago psyllium", "psyllium", "spanish psyllium"],
    "flecainide": ["tambocor"],
    "fledge": ["flight"],
    "fledged": ["mature"],
    "fledgling": ["fledgeling"],
    "flee": ["fly", "take flight"],
    "fleece": ["shear"],
    "fleeceable": ["green", "gullible"],
    "fleet": ["swift"],
    "fleet admiral": ["five-star admiral"],
    "fleeting": ["fugitive", "momentaneous", "momentary"],
    "fleming": ["ian fleming", "ian lancaster fleming"],
    "flemish": ["flemish dialect"],
    "flesh fly": ["sarcophaga carnaria"],
    "flesh-colored": ["flesh-coloured"],
    "flesh-eating": ["meat-eating", "zoophagous"],
    "fleshed out": ["full-clad"],
    "fleshiness": ["corpulency", "obesity"],
    "fleshy": ["sarcoid"],
    "fletcher": ["john fletcher"],
    "fleur-de-lis": ["fleur-de-lys"],
    "flex": ["bend"],
    "flexibility": ["flexibleness"],
    "flexible": ["flexile"],
    "flexion": ["flexure"],
    "flexor muscle": ["flexor"],
    "flexure": ["flection", "flexion"],
    "flibbertigibbet": ["foolish woman"],
    "flick": ["flip", "leaf", "riff", "riffle", "thumb"],
    "flicker": ["flick"],
    "flickering": ["aflicker"],
    "flickertail": ["citellus richardsoni", "richardson ground squirrel"],
    "flier": ["flyer"],
    "flight": ["flight of stairs", "flight of steps"],
    "flight deck": ["landing deck"],
    "flight feather": ["pinion", "quill", "quill feather"],
    "flight maneuver": ["airplane maneuver"],
    "flight simulator": ["trainer"],
    "flightiness": ["arbitrariness", "capriciousness", "whimsey", "whimsicality", "whimsy"],
    "flighty": ["flyaway", "head-in-the-clouds", "scatterbrained"],
    "flim-flam": ["fob", "fox", "play a joke on", "play a trick on", "play tricks", "pull a fast one on", "trick"],
    "flimsiness": ["shoddiness"],
    "flimsy": ["fragile", "slight", "tenuous", "thin"],
    "flinch": ["cringe", "funk", "quail", "recoil", "shrink", "squinch", "wince"],
    "flinders": ["matthew flinders", "sir matthew flinders"],
    "flindersia": ["genus flindersia"],
    "flint": ["flint river"],
    "flint corn": ["flint maize", "yankee corn", "zea mays indurata"],
    "flintlock": ["firelock"],
    "flinty": ["flint", "granitic", "obdurate", "stony"],
    "flip": ["twitch"],
    "flip one's lid": ["blow a fuse", "blow one's stack", "blow up", "combust", "flip one's wig", "fly off the handle", "go ballistic", "have a fit", "have kittens", "hit the ceiling", "hit the roof", "lose one's temper", "throw a fit"],
    "flip-flop": ["thong"],
    "flippancy": ["light-mindedness"],
    "flippant": ["light-minded"],
    "flippantly": ["airily"],
    "flipper": ["fin"],
    "flirt": ["coquetry", "dalliance", "flirtation", "flirting", "toying"],
    "flit": ["dart", "fleet", "flutter"],
    "flitch": ["side of bacon"],
    "float": ["swim"],
    "floater": ["floating policy"],
    "floating": ["natation"],
    "floating dock": ["floating dry dock"],
    "floating fern": ["ceratopteris thalictroides"],
    "floating mine": ["marine mine"],
    "floating-moss": ["salvinia auriculata", "salvinia rotundifolia"],
    "floating-point notation": ["floating-point representation system"],
    "floating-point operation": ["flop"],
    "floatplane": ["pontoon plane"],
    "floccose chanterelle": ["cantharellus floccosus"],
    "floccule": ["floc"],
    "flocculent": ["woolly", "wooly"],
    "flock": ["fold"],
    "flodden": ["battle of flodden field"],
    "flog": ["lash", "lather", "slash", "strap", "trounce", "welt", "whip"],
    "flogger": ["scourger"],
    "flood": ["glut", "oversupply"],
    "flood tide": ["flood", "rising tide"],
    "floodlit": ["floodlighted"],
    "floodplain": ["flood plain"],
    "floor": ["base"],
    "floor cover": ["floor covering"],
    "floorboard": ["floor board"],
    "floorwalker": ["shopwalker"],
    "flop": ["dud", "washout"],
    "flophouse": ["dosshouse"],
    "floral": ["flowered"],
    "florence fennel": ["foeniculum dulce", "foeniculum vulgare dulce"],
    "florentine iris": ["iris florentina", "iris germanica florentina", "orris"],
    "florest's cineraria": ["pericallis hybrida"],
    "floret": ["floweret"],
    "florey": ["howard florey", "sir howard walter florey"],
    "florida": ["everglade state", "fl", "sunshine state"],
    "florida gallinule": ["gallinula chloropus cachinnans"],
    "florida pompano": ["trachinotus carolinus"],
    "florida selaginella": ["selaginella eatonii"],
    "florida smoothhound": ["mustelus norrisi"],
    "florida strap fern": ["cow-tongue fern", "hart's-tongue fern"],
    "florida yew": ["taxus floridana"],
    "florilegium": ["garland", "miscellany"],
    "florio": ["john florio"],
    "florist": ["florist shop", "flower store"],
    "florist's chrysanthemum": ["chrysanthemum morifolium", "dendranthema grandifloruom", "florists' chrysanthemum", "mum"],
    "florist's gloxinia": ["gloxinia spesiosa", "sinningia speciosa"],
    "flory": ["paul john flory"],
    "flotation": ["floatation"],
    "flotsam": ["jetsam"],
    "flour beetle": ["flour weevil"],
    "flourish": ["brandish"],
    "flow": ["flux"],
    "flow away": ["flow off"],
    "flow chart": ["flow diagram", "flow sheet", "flowchart"],
    "flow out": ["effuse"],
    "flower": ["bloom", "blossom", "efflorescence", "flush", "heyday", "peak", "prime"],
    "flower arrangement": ["floral arrangement"],
    "flower gardening": ["floriculture"],
    "flower people": ["hippies", "hipsters"],
    "flower-of-an-hour": ["black-eyed susan", "bladder ketmia", "flowers-of-an-hour", "hibiscus trionum"],
    "flowerbed": ["bed of flowers", "flower bed"],
    "flowering almond": ["prunus triloba"],
    "flowering ash": ["fraxinus dipetala"],
    "flowering fern": ["helminthostachys zeylanica"],
    "flowering raspberry": ["purple-flowering raspberry", "rubus odoratus", "thimbleberry"],
    "flowering tobacco": ["jasmine tobacco", "nicotiana alata"],
    "flowering wintergreen": ["bird-on-the-wing", "fringed polygala", "gaywings", "polygala paucifolia"],
    "flowerless": ["nonflowering"],
    "flowery": ["ornate"],
    "fluctuate": ["vacillate", "waver"],
    "fluctuation": ["wavering"],
    "flue pipe": ["flue", "labial pipe"],
    "fluency": ["articulateness", "volubility"],
    "fluent": ["fluid", "liquid", "smooth"],
    "fluff up": ["plump up", "shake up"],
    "flugelhorn": ["fluegelhorn"],
    "fluid": ["runny"],
    "fluid mechanics": ["hydraulics"],
    "fluidity": ["fluidness", "liquidity", "liquidness", "runniness"],
    "fluidounce": ["fluid ounce"],
    "fluidram": ["drachm", "fluid drachm", "fluid dram"],
    "fluke": ["flue"],
    "flump": ["flump down"],
    "flunitrazepan": ["rohypnol"],
    "flunky": ["flunkey", "stooge", "yes-man"],
    "fluorescein": ["fluoresceine", "fluorescent dye", "resorcinolphthalein"],
    "fluorescein isothiocyanate": ["fluorescein isocyanate"],
    "fluorescent": ["fluorescent fixture"],
    "fluoridate": ["fluoridise", "fluoridize"],
    "fluoridation": ["fluoridisation", "fluoridization"],
    "fluorine": ["atomic number 9"],
    "fluorite": ["fluor", "fluorspar"],
    "fluoroform": ["trifluoromethane"],
    "fluoroscope": ["roentgenoscope"],
    "fluosilicic acid": ["hydrofluosilicic acid"],
    "fluoxetine": ["fluoxetine hydrocholoride", "prozac", "sarafem"],
    "flurazepam": ["dalmane", "flurazepam hydrochloride"],
    "flurbiprofen": ["ansaid"],
    "flurry": ["snow flurry"],
    "flush": ["even", "even out", "level"],
    "flush toilet": ["lavatory"],
    "flushed": ["rose-cheeked", "rosy", "rosy-cheeked"],
    "flustered": ["hot and bothered", "perturbed", "rattled"],
    "flute": ["champagne flute", "flute glass"],
    "flutist": ["flautist", "flute player"],
    "fluvastatin": ["lescol"],
    "flux": ["state of flux"],
    "flux density": ["flux"],
    "flux unit": ["magnetic flux unit"],
    "fly": ["fell", "vanish"],
    "fly agaric": ["amanita muscaria"],
    "fly gallery": ["fly floor"],
    "fly in the face of": ["fly in the teeth of"],
    "fly orchid": ["ophrys insectifera", "ophrys muscifera"],
    "fly poison": ["amianthum muscaetoxicum", "amianthum muscitoxicum"],
    "fly-by-night": ["shady"],
    "fly-fish": ["flyfish"],
    "flyblown": ["maggoty"],
    "flying": ["fast", "quick"],
    "flying bridge": ["fly bridge", "flybridge", "monkey bridge"],
    "flying buttress": ["arc-boutant"],
    "flying colors": ["flying colours"],
    "flying gecko": ["fringed gecko", "ptychozoon homalocephalum"],
    "flying gurnard": ["butterflyfish", "flying robin"],
    "flying lemur": ["colugo", "flying cat"],
    "flying phalanger": ["flying opossum", "flying squirrel"],
    "flying start": ["running start"],
    "flyover": ["fly-by", "flypast"],
    "foam": ["effervesce", "fizz", "form bubbles", "froth", "sparkle"],
    "foam at the mouth": ["froth at the mouth"],
    "foamflower": ["coolwart", "false miterwort", "false mitrewort", "tiarella cordifolia"],
    "foaming": ["foamy", "frothing"],
    "fob": ["watch pocket"],
    "focal distance": ["focal length"],
    "focal ratio": ["f number", "speed", "stop number"],
    "focalization": ["focalisation"],
    "focus": ["focalise", "focalize"],
    "focus on": ["center", "center on", "concentrate on", "revolve about", "revolve around"],
    "focused": ["focussed"],
    "foe": ["enemy"],
    "foeniculum": ["genus foeniculum"],
    "fog": ["fogginess", "murk", "murkiness"],
    "fogged": ["foggy"],
    "foghorn": ["fogsignal"],
    "fogyish": ["moss-grown", "mossy", "stick-in-the-mud", "stodgy"],
    "fohn": ["foehn"],
    "foie gras": ["pate de foie gras"],
    "foil": ["enhancer"],
    "foist off": ["fob off", "palm off"],
    "fold": ["fold up", "turn up"],
    "foldable": ["foldaway", "folding"],
    "folderal": ["falderol", "frill", "gimcrack", "gimcrackery", "nonsense", "trumpery"],
    "folderol": ["applesauce", "codswallop", "rubbish", "trash", "tripe", "trumpery", "wish-wash"],
    "folding door": ["accordion door"],
    "foldout": ["gatefold"],
    "foliaceous": ["foliaged", "foliose"],
    "foliate": ["page", "paginate"],
    "foliation": ["leafing"],
    "folk": ["common people", "folks"],
    "folk dancing": ["folk dance"],
    "folk music": ["ethnic music", "folk"],
    "folk singer": ["jongleur", "minstrel", "poet-singer", "troubadour"],
    "folk song": ["folk ballad", "folksong"],
    "folktale": ["folk tale"],
    "follicle-stimulating hormone": ["fsh"],
    "follow": ["come after"],
    "follow through": ["carry out", "follow out", "follow up", "go through", "implement", "put through"],
    "follow-up": ["followup"],
    "following": ["followers"],
    "folly": ["craziness", "foolishness", "madness"],
    "fomentation": ["instigation"],
    "fomes": ["genus fomes"],
    "fomite": ["vehicle"],
    "fomor": ["fomorian"],
    "fond": ["partial"],
    "fonda": ["jane fonda"],
    "fondly": ["lovingly"],
    "fondness": ["fancy", "partiality"],
    "fondue": ["fondu"],
    "font": ["case", "face", "fount", "typeface"],
    "font cartridge": ["cartridge font"],
    "fontanelle": ["fontanel", "soft spot"],
    "fontanne": ["lynn fontanne"],
    "fontenoy": ["battle of fontenoy"],
    "fonteyn": ["dame margot fonteyn"],
    "food": ["solid food"],
    "food additive": ["artificial additive"],
    "food and agriculture organization": ["fao", "food and agriculture organization of the united nations"],
    "food and drug administration": ["fda"],
    "food poisoning": ["gastrointestinal disorder"],
    "food web": ["food cycle"],
    "foodstuff": ["food product"],
    "fool": ["befool", "gull"],
    "fool's parsley": ["aethusa cynapium", "lesser hemlock"],
    "foolhardy": ["heady", "rash", "reckless"],
    "fooling": ["casual"],
    "foolishly": ["unwisely"],
    "foolproof": ["unfailing"],
    "foot": ["pick"],
    "foot-and-mouth disease": ["hoof-and-mouth disease"],
    "foot-lambert": ["ft-l"],
    "football": ["football game"],
    "football field": ["gridiron"],
    "football player": ["footballer"],
    "football team": ["eleven"],
    "footbridge": ["overcrossing", "pedestrian bridge"],
    "footfall": ["footstep", "step"],
    "foothold": ["footing"],
    "footing": ["terms"],
    "footlocker": ["locker"],
    "footnote": ["footer"],
    "footpad": ["padder"],
    "footprint": ["footmark", "step"],
    "footrace": ["foot race", "run"],
    "footstep": ["pace", "step", "stride"],
    "footsteps-of-spring": ["sanicula arctopoides"],
    "footstool": ["footrest", "ottoman", "tuffet"],
    "footwear": ["footgear"],
    "foppishness": ["dandyism"],
    "for a song": ["at a low price", "for a bargain price"],
    "for all practical purposes": ["for all intents and purposes", "to all intents and purposes"],
    "for example": ["e.g.", "for instance"],
    "for love or money": ["for all the world", "for any price", "for anything"],
    "for the asking": ["on request"],
    "for the moment": ["for the time being"],
    "foraging": ["forage"],
    "foram": ["foraminifer"],
    "foramen": ["hiatus"],
    "foraminifera": ["order foraminifera"],
    "foray": ["maraud", "raid"],
    "foray into": ["raid"],
    "forbear": ["hold back"],
    "forbearing": ["longanimous"],
    "forbid": ["disallow", "interdict", "nix", "prohibit", "proscribe", "veto"],
    "forbidden": ["out", "prohibited", "proscribed", "taboo", "tabu", "verboten"],
    "force": ["drive", "ram"],
    "force out": ["crowd out"],
    "forced feeding": ["gavage"],
    "forced landing": ["emergency landing"],
    "forceless": ["unforceful"],
    "forcemeat": ["farce"],
    "forces of umar al-mukhtar": ["umar al-mukhtar forces"],
    "forcible": ["physical", "strong-arm"],
    "ford": ["john ford"],
    "fore": ["forward"],
    "fore edge": ["foredge"],
    "forebear": ["forbear"],
    "foreboding": ["boding", "premonition", "presentiment"],
    "forebrain": ["prosencephalon"],
    "forecast": ["calculate"],
    "forecaster": ["predictor", "prognosticator", "soothsayer"],
    "forecastle": ["fo'c'sle"],
    "forefather": ["father", "sire"],
    "forefront": ["head"],
    "foregone conclusion": ["matter of course"],
    "foreground": ["highlight", "play up", "spotlight"],
    "foreground processing": ["foregrounding"],
    "forehand": ["forehand shot", "forehand stroke"],
    "foreign": ["strange"],
    "foreign bill": ["foreign draft"],
    "foreign intelligence service": ["sluzhba vneshney razvedki", "svr"],
    "foreign intelligence surveillance act": ["fisa"],
    "foreign intelligence surveillance court": ["f.i.s.c."],
    "foreign minister": ["secretary of state"],
    "foreign-born": ["nonnative"],
    "foreigner": ["outsider"],
    "foreignness": ["curiousness", "strangeness"],
    "forelock": ["foretop"],
    "foreman": ["boss", "chief", "gaffer", "honcho"],
    "foremost": ["first"],
    "forensic medicine": ["forensic pathology"],
    "foreordained": ["predestinate", "predestined"],
    "foreplay": ["arousal", "stimulation"],
    "foresight": ["foresightedness", "foresightfulness"],
    "forest": ["timber", "timberland", "woodland"],
    "forest goat": ["pseudoryx nghetinhensis", "spindle horn"],
    "forest red gum": ["eucalypt tereticornis"],
    "forest tent caterpillar": ["malacosoma disstria"],
    "forester": ["c. s. forester", "cecil scott forester"],
    "foreswear": ["quit", "relinquish", "renounce"],
    "forever": ["forever and a day"],
    "forewarn": ["previse"],
    "forewarning": ["premonition"],
    "forewing": ["fore wing", "fore-wing"],
    "forewoman": ["forelady"],
    "foreword": ["preface", "prolusion"],
    "forfeit": ["forego", "forgo", "give up", "throw overboard", "waive"],
    "forficula": ["genus forficula"],
    "forficulidae": ["family forficulidae"],
    "forge": ["spirt", "spurt"],
    "forger": ["counterfeiter"],
    "forget": ["leave"],
    "forget-me-not": ["mouse ear", "myosotis scorpiodes"],
    "forgetful": ["oblivious"],
    "forgiveness": ["pardon"],
    "forgivingness": ["kindness"],
    "fork": ["crotch"],
    "forked lightning": ["chain lightning"],
    "forlornness": ["desolation", "loneliness"],
    "form": ["spring", "take form", "take shape"],
    "formaldehyde": ["methanal"],
    "formalin": ["formol"],
    "formalistic": ["formalised", "formalized"],
    "formality": ["formalities"],
    "formalization": ["formalisation"],
    "formalize": ["formalise"],
    "formalized": ["formalised"],
    "formally": ["officially"],
    "formalwear": ["evening clothes", "evening dress", "eveningwear"],
    "format": ["arrange"],
    "formation": ["shaping"],
    "formative": ["plastic", "shaping"],
    "former": ["late", "previous"],
    "formica": ["genus formica"],
    "formicariidae": ["family formicariidae"],
    "formicarius": ["genus formicarius"],
    "formicidae": ["family formicidae"],
    "formidability": ["toughness"],
    "formidable": ["redoubtable", "unnerving"],
    "formula": ["chemical formula"],
    "formularize": ["formularise"],
    "formulary": ["pharmacopeia"],
    "formulation": ["preparation"],
    "fornix": ["trigonum cerebrale"],
    "forsaking": ["giving up"],
    "fort": ["fort up"],
    "fort meade": ["fort george g. meade", "fort george gordon meade"],
    "fort ticonderoga": ["ticonderoga"],
    "forte": ["long suit", "metier", "speciality", "specialty", "strength", "strong point", "strong suit"],
    "forth": ["forth river"],
    "forties": ["1940s"],
    "fortieth": ["40th"],
    "fortification": ["munition"],
    "fortify": ["fort"],
    "fortissimo": ["very loudly"],
    "fortnight": ["two weeks"],
    "fortnightly": ["biweekly"],
    "fortress": ["fort"],
    "fortunate": ["golden"],
    "fortunately": ["as luck would have it", "fortuitously", "luckily"],
    "fortune": ["circumstances", "destiny", "fate", "lot", "luck", "portion"],
    "fortunella": ["genus fortunella"],
    "fortuneteller": ["fortune teller"],
    "forty": ["40", "xl"],
    "forty-eight": ["48", "xlviii"],
    "forty-eighth": ["48th"],
    "forty-fifth": ["45th"],
    "forty-first": ["41st"],
    "forty-five": ["45", "xlv"],
    "forty-four": ["44", "xliv"],
    "forty-fourth": ["44th"],
    "forty-nine": ["49", "il"],
    "forty-ninth": ["49th"],
    "forty-one": ["41", "xli"],
    "forty-second": ["42nd"],
    "forty-seven": ["47", "xlvii"],
    "forty-seventh": ["47th"],
    "forty-six": ["46", "xlvi"],
    "forty-sixth": ["46th"],
    "forty-third": ["43rd"],
    "forty-three": ["43", "xliii"],
    "forty-two": ["42", "xlii"],
    "forum": ["assembly", "meeting place"],
    "forward": ["send on"],
    "forward pass": ["aerial"],
    "forwarding": ["furtherance", "promotion"],
    "fosbury": ["dick fosbury", "richard d. fosbury"],
    "fossa": ["genus fossa"],
    "fossilization": ["fossilisation"],
    "fossilize": ["fossilise"],
    "fossilized": ["fossilised", "ossified"],
    "foster": ["further"],
    "foster-brother": ["foster brother"],
    "foster-child": ["foster child", "fosterling"],
    "foster-daughter": ["foster daughter"],
    "foster-father": ["foster father"],
    "foster-mother": ["foster mother"],
    "foster-parent": ["foster parent"],
    "foster-sister": ["foster sister"],
    "foster-son": ["foster son"],
    "fostering": ["fosterage"],
    "fothergilla": ["witch alder"],
    "foucault": ["jean bernard leon foucault"],
    "foul": ["befoul", "defile", "maculate"],
    "foul shot": ["charity shot", "charity throw", "charity toss", "free throw", "penalty free throw"],
    "foul-mouthed": ["foul-spoken"],
    "foully": ["insultingly"],
    "foulness": ["raininess"],
    "foundation": ["grounding"],
    "foundation garment": ["foundation"],
    "founder": ["beginner", "father", "founding father"],
    "foundering": ["going under"],
    "foundling": ["abandoned infant"],
    "foundry": ["metalworks"],
    "fountain": ["jet"],
    "fountain grass": ["pennisetum ruppelii", "pennisetum setaceum"],
    "fountainhead": ["head", "headspring"],
    "fouquieria": ["genus fouquieria"],
    "fouquieriaceae": ["family fouquieriaceae"],
    "four": ["foursome", "iv", "little joe", "quadruplet", "quartet", "quatern", "quaternary", "quaternion", "quaternity", "tetrad"],
    "four hundred": ["400", "cd"],
    "four-dimensional": ["4-dimensional"],
    "four-hitter": ["4-hitter"],
    "four-hundredth": ["400th"],
    "four-letter word": ["four-letter anglo-saxon word"],
    "four-lined plant bug": ["four-lined leaf bug", "poecilocapsus lineatus"],
    "four-membered": ["4-membered"],
    "four-petaled": ["four-petalled"],
    "four-spot": ["four"],
    "four-stroke engine": ["four-stroke internal-combustion engine"],
    "four-wheel": ["four-wheeled"],
    "four-wheel drive": ["4wd"],
    "fourfold": ["four times"],
    "fourier": ["baron jean baptiste joseph fourier", "jean baptiste joseph fourier"],
    "fourier analysis": ["harmonic analysis"],
    "fourpence": ["groat"],
    "fourteen": ["14", "xiv"],
    "fourteenth": ["14th"],
    "fourth": ["4th", "quaternary"],
    "fourth dimension": ["time"],
    "fourthly": ["fourth"],
    "fovea": ["fovea centralis"],
    "fowler": ["henry watson fowler"],
    "fox": ["charles james fox"],
    "fox grape": ["vitis labrusca"],
    "fox hunting": ["foxhunt"],
    "fox squirrel": ["eastern fox squirrel", "sciurus niger"],
    "fox-trot": ["foxtrot"],
    "foxglove": ["digitalis"],
    "foxhole": ["fox hole"],
    "foxtail": ["foxtail grass"],
    "foxtail grass": ["lycopodium alopecuroides"],
    "foxtail millet": ["hungarian grass", "italian millet", "setaria italica"],
    "fractional monetary unit": ["subunit"],
    "fractionation": ["fractional process"],
    "fractious": ["recalcitrant", "refractory"],
    "fracture": ["break"],
    "fragaria": ["genus fragaria"],
    "fragility": ["breakability", "frangibility", "frangibleness"],
    "fragmental": ["fragmentary"],
    "fragmentation bomb": ["anti-personnel bomb", "antipersonnel bomb", "daisy cutter"],
    "fragonard": ["jean honore fragonard"],
    "fragrant agrimony": ["agrimonia procera"],
    "fragrant cliff fern": ["dryopteris fragrans", "fragrant shield fern", "fragrant wood fern"],
    "fragrant orchid": ["gymnadenia conopsea"],
    "fragrant sumac": ["lemon sumac", "rhus aromatica"],
    "frailty": ["vice"],
    "frame": ["frame up"],
    "frame of reference": ["frame"],
    "frame-up": ["setup"],
    "framework": ["fabric"],
    "france": ["anatole france", "jacques anatole francois thibault"],
    "franchise": ["dealership"],
    "francis ferdinand": ["franz ferdinand"],
    "francis ii": ["emperor francis ii"],
    "francis joseph": ["francis joseph i", "franz josef i", "franz joseph"],
    "francis of assisi": ["giovanni di bernardone", "saint francis", "saint francis of assisi", "st. francis", "st. francis of assisi"],
    "franciscan": ["grey friar"],
    "francisella": ["genus francisella"],
    "francium": ["atomic number 87", "fr"],
    "franck": ["cesar franck"],
    "franco": ["el caudillo", "francisco franco", "general franco"],
    "francoa": ["genus francoa"],
    "francophile": ["francophil"],
    "frangipani": ["frangipanni"],
    "frank": ["dog", "frankfurter", "hot dog", "hotdog", "weenie", "wiener", "wienerwurst"],
    "frank breech": ["frank breech delivery"],
    "frankenstein": ["frankenstein's monster"],
    "frankfort": ["capital of kentucky"],
    "frankfurt on the main": ["frankfort", "frankfurt"],
    "frankfurter bun": ["hotdog bun"],
    "frankincense": ["gum olibanum", "olibanum", "thus"],
    "franklin": ["john hope franklin"],
    "frankliniella": ["genus frankliniella"],
    "frankness": ["outspokenness"],
    "frantic": ["frenetic", "frenzied", "phrenetic"],
    "fraser fir": ["abies fraseri"],
    "frasera": ["genus frasera"],
    "fratercula": ["genus fratercula"],
    "fraternal": ["biovular"],
    "fraternal twin": ["dizygotic twin"],
    "fraternity": ["frat"],
    "fraternization": ["fraternisation"],
    "fraternize": ["fraternise"],
    "fraud": ["dupery", "fraudulence", "hoax", "humbug", "put-on"],
    "fraud in fact": ["positive fraud"],
    "fraudulence": ["duplicity"],
    "fraught": ["pregnant"],
    "fraxinella": ["burning bush", "dictamnus alba", "dittany", "gas plant"],
    "fraxinus": ["genus fraxinus"],
    "fray": ["frazzle"],
    "frazer": ["james george frazer", "sir james george frazer"],
    "freak": ["lusus naturae", "monster", "monstrosity"],
    "freak out": ["freak", "gross out"],
    "freckle": ["lentigo"],
    "freckled": ["lentiginose", "lentiginous"],
    "frederick i": ["barbarossa", "frederick barbarossa"],
    "frederick ii": ["frederick the great"],
    "frederick william": ["great elector"],
    "fredericksburg": ["battle of fredericksburg"],
    "free": ["release"],
    "free agent": ["free spirit", "freewheeler"],
    "free burning": ["sustained"],
    "free french": ["fighting french"],
    "free hand": ["blank check"],
    "free morpheme": ["free form"],
    "free port": ["free zone"],
    "free radical": ["radical"],
    "free rein": ["play"],
    "free state": ["orange free state"],
    "free time": ["spare time"],
    "free verse": ["vers libre"],
    "free will": ["discretion"],
    "free-and-easy": ["casual"],
    "free-base": ["base"],
    "free-living": ["nonparasitic", "nonsymbiotic"],
    "free-soil": ["non-slave", "slaveless"],
    "free-swimming": ["unattached"],
    "free-thinking": ["latitudinarian", "undogmatic", "undogmatical"],
    "freebie": ["freebee"],
    "freedman": ["freedwoman"],
    "freedom from self-incrimination": ["privilege against self incrimination"],
    "freehand": ["freehanded"],
    "freelance": ["free-lance", "self-employed"],
    "freelancer": ["free lance", "free-lance", "freelance", "independent", "self-employed person"],
    "freeman": ["freewoman"],
    "freemason": ["mason"],
    "freemasonry": ["masonry"],
    "freestanding": ["separate"],
    "freetail": ["free-tailed bat", "freetailed bat"],
    "freetown": ["capital of sierra leone"],
    "freewheel": ["drift"],
    "freeze": ["stop dead"],
    "freeze-drying": ["lyophilisation", "lyophilization"],
    "freezing point": ["melting point"],
    "fregata": ["genus fregata"],
    "fregatidae": ["family fregatidae"],
    "freight": ["freight rate", "freightage"],
    "freight elevator": ["service elevator"],
    "freight liner": ["liner train"],
    "freight train": ["rattler"],
    "fremont": ["john c. fremont", "john charles fremont"],
    "fremontodendron": ["fremontia", "genus fremontia", "genus fremontodendron"],
    "french": ["daniel chester french"],
    "french blue": ["french ultramarine", "french ultramarine blue"],
    "french dressing": ["sauce vinaigrette", "vinaigrette"],
    "french foreign office": ["quai d'orsay"],
    "french fries": ["chips", "french-fried potatoes", "fries"],
    "french fritter": ["beignet"],
    "french honeysuckle": ["hedysarum coronarium", "sulla"],
    "french horn": ["horn"],
    "french lavender": ["lavandula stoechas"],
    "french marigold": ["tagetes patula"],
    "french polish": ["french polish shellac"],
    "french polynesia": ["french oceania"],
    "french riviera": ["cote d'azur"],
    "french sorrel": ["garden sorrel", "rumex scutatus"],
    "french-fry": ["deep-fry"],
    "frenchman": ["french person", "frenchwoman"],
    "frenzied": ["manic"],
    "frenziedly": ["hectically"],
    "frequency": ["frequence", "oftenness"],
    "frequency band": ["waveband"],
    "frequency modulation": ["fm"],
    "frequency-response curve": ["frequency-response characteristic"],
    "frequent": ["haunt"],
    "frequently": ["oft", "often", "oftentimes", "ofttimes"],
    "fresh": ["invigorated", "refreshed", "reinvigorated"],
    "fresh food": ["fresh foods"],
    "fresh start": ["clean slate", "tabula rasa"],
    "fresh water": ["freshwater"],
    "freshen": ["freshen up", "refresh", "refreshen"],
    "freshet": ["spate"],
    "freshman": ["fresher"],
    "freshness": ["glow"],
    "freshwater bass": ["bass"],
    "freshwater bream": ["bream"],
    "freshwater mussel": ["freshwater clam"],
    "fresnel": ["augustin jean fresnel"],
    "fret": ["eat away"],
    "fretful": ["querulous", "whiney", "whiny"],
    "fretted": ["interlaced", "latticed", "latticelike"],
    "freud": ["sigmund freud"],
    "frey": ["freyr"],
    "freya": ["freyja"],
    "friar": ["mendicant"],
    "friar's lantern": ["ignis fatuus", "jack-o'-lantern", "will-o'-the-wisp"],
    "friar's-cowl": ["arisarum vulgare"],
    "fricative": ["continuant", "sibilant", "spirant", "strident"],
    "fricative consonant": ["fricative", "spirant"],
    "frick": ["henry clay frick"],
    "friction": ["rubbing"],
    "friction tape": ["insulating tape"],
    "friday": ["fri"],
    "fried": ["deep-fried"],
    "fried rice": ["chinese fried rice"],
    "friedan": ["betty friedan", "betty naomi friedan", "betty naomi goldstein friedan"],
    "friedman": ["milton friedman"],
    "friedman test": ["rabbit test"],
    "friedreich's ataxia": ["herediatry spinal ataxia"],
    "friend": ["quaker"],
    "friendless": ["outcast"],
    "friendly": ["favorable", "well-disposed"],
    "friendly fire": ["fratricide"],
    "friendship": ["friendly relationship"],
    "friendship plant": ["panamica", "panamiga", "pilea involucrata"],
    "friesian": ["holstein", "holstein-friesian"],
    "frigate bird": ["man-of-war bird"],
    "frigg": ["frigga"],
    "frighten": ["affright", "fright", "scare"],
    "frightened": ["scared"],
    "frighteningly": ["scarily"],
    "frightful": ["awful", "terrible", "tremendous"],
    "frigid": ["frosty", "frozen", "glacial", "icy", "wintry"],
    "frigid zone": ["polar region", "polar zone"],
    "frigidity": ["frigidness"],
    "frill": ["ruff"],
    "frilled": ["frilly", "ruffled"],
    "frilled lizard": ["chlamydosaurus kingi"],
    "fringe": ["interference fringe"],
    "fringe benefit": ["perk", "perquisite"],
    "fringe bush": ["chionanthus virginicus"],
    "fringe-toed lizard": ["uma notata"],
    "fringed": ["laciniate"],
    "fringed grass of parnassus": ["parnassia fimbriata"],
    "fringed loosestrife": ["lysimachia ciliatum"],
    "fringed orchis": ["fringed orchid"],
    "fringed pink": ["dianthus supurbus"],
    "fringed poppy mallow": ["callirhoe digitata"],
    "fringepod": ["lacepod"],
    "fringilla": ["genus fringilla"],
    "fringillidae": ["family fringillidae"],
    "fringy": ["marginal"],
    "frisch": ["otto frisch", "otto robert frisch"],
    "frisk": ["frisking"],
    "friskiness": ["frolicsomeness", "sportiveness"],
    "frisson": ["chill", "quiver", "shiver", "shudder", "thrill", "tingle"],
    "fritillaria": ["genus fritillaria"],
    "fritillary": ["checkered lily"],
    "fritter": ["dissipate", "fool", "fool away", "fritter away", "frivol away", "shoot"],
    "friulian": ["friuli"],
    "frivol": ["trifle"],
    "frivolity": ["frivolousness"],
    "frobisher": ["sir martin frobisher"],
    "froebel": ["friedrich froebel", "friedrich wilhelm august froebel"],
    "froelichia": ["genus froelichia"],
    "frog": ["gaul"],
    "frog orchid": ["coeloglossum viride"],
    "frogbit": ["frog's-bit", "hydrocharis morsus-ranae"],
    "frolic": ["cavort", "disport", "frisk", "gambol", "lark", "lark about", "rollick", "romp", "run around", "skylark", "sport"],
    "from pillar to post": ["hither and thither"],
    "from way back": ["since a long time ago"],
    "front": ["face", "look"],
    "front door": ["front entrance"],
    "front man": ["figurehead", "front", "nominal head", "straw man", "strawman"],
    "front matter": ["prelims"],
    "front tooth": ["anterior"],
    "front-porch campaigning": ["front-porch campaign"],
    "front-runner": ["favorite", "favourite"],
    "frontage road": ["service road"],
    "frontal": ["head-on"],
    "frontal bone": ["forehead", "os frontale"],
    "frontal lobe": ["frontal cortex"],
    "frontal suture": ["sutura frontalis"],
    "frontier settlement": ["outpost"],
    "frontiersman": ["backwoodsman", "mountain man"],
    "frontlet": ["frontal"],
    "frost": ["ice"],
    "frost heave": ["frost heaving"],
    "frost's bolete": ["boletus frostii"],
    "frostbite": ["cryopathy"],
    "frosted bat": ["vespertilio murinus"],
    "frostily": ["frigidly"],
    "frostiness": ["hoariness"],
    "frosting": ["ice", "icing"],
    "frostweed": ["crocanthemum canadense", "frost-weed", "frostwort", "helianthemum canadense"],
    "frosty": ["rimed", "rimy"],
    "froth": ["spume", "suds"],
    "froward": ["headstrong", "self-willed", "wilful", "willful"],
    "frown": ["glower", "lour", "lower"],
    "frown on": ["frown upon"],
    "frowsy": ["frowzy", "slovenly"],
    "frozen": ["rooted", "stock-still"],
    "frozen custard": ["soft ice cream"],
    "frozen food": ["frozen foods"],
    "frozen orange juice": ["orange-juice concentrate"],
    "fructify": ["set"],
    "fructose": ["fruit sugar", "laevulose", "levulose"],
    "frugality": ["frugalness"],
    "fruit bat": ["megabat"],
    "fruit drink": ["ade"],
    "fruit fly": ["pomace fly"],
    "fruit juice": ["fruit crush"],
    "fruitfulness": ["fecundity"],
    "fruitlessness": ["aridity", "barrenness"],
    "frump": ["dog"],
    "frustrating": ["frustrative", "thwarting"],
    "frustration": ["defeat"],
    "fry": ["roger eliot fry", "roger fry"],
    "frye": ["herman northrop frye", "northrop frye"],
    "fryer": ["frier", "pullet"],
    "frying": ["sauteing"],
    "frying pan": ["frypan", "skillet"],
    "fucaceae": ["family fucaceae"],
    "fucales": ["order fucales"],
    "fuchs": ["emil klaus julius fuchs", "klaus fuchs"],
    "fuck": ["ass", "fucking", "nookie", "nooky", "piece of ass", "piece of tail", "roll in the hay", "screw", "screwing", "shag", "shtup"],
    "fucked-up": ["snafu"],
    "fucoid": ["fucoid algae"],
    "fudge": ["cook", "fake", "falsify", "manipulate", "misrepresent", "wangle"],
    "fudge together": ["throw together"],
    "fuel": ["fire"],
    "fuel gauge": ["fuel indicator"],
    "fuel injection": ["fuel injection system"],
    "fuel line": ["gas line", "petrol line"],
    "fuel oil": ["heating oil"],
    "fuel-air explosive": ["fae"],
    "fueling": ["refueling"],
    "fuentes": ["carlos fuentes"],
    "fugacity": ["fugaciousness"],
    "fugard": ["athol fugard"],
    "fugitive": ["fleer", "runaway"],
    "fugue": ["psychogenic fugue"],
    "fuji": ["fuji cherry", "prunus incisa"],
    "fula": ["ful", "fulani", "peul"],
    "fulani": ["fellata", "fula", "fulah", "fulbe"],
    "fulbright": ["james william fulbright", "william fulbright"],
    "fulfillment": ["fulfilment"],
    "fulgoridae": ["family fulgoridae"],
    "fulica": ["genus fulica"],
    "full": ["replete"],
    "full moon": ["full", "full phase of the moon", "full-of-the-moon"],
    "full of life": ["lively", "vital"],
    "full-blooded": ["blooded", "full-blood"],
    "full-blown": ["matured"],
    "full-bodied": ["racy", "rich", "robust"],
    "full-dress": ["dress"],
    "full-fashioned": ["fully fashioned"],
    "full-fledged": ["fully fledged"],
    "full-length": ["uncut"],
    "fuller": ["melville w. fuller", "melville weston fuller"],
    "fuller's teasel": ["dipsacus sativus"],
    "fullness": ["voluminosity", "voluminousness"],
    "fully": ["full", "to the full"],
    "fulmar": ["fulmar petrel", "fulmarus glacialis"],
    "fulmarus": ["genus fulmarus"],
    "fulminate": ["rail"],
    "fulmination": ["diatribe"],
    "fulsomeness": ["oiliness", "oleaginousness", "smarminess", "unction", "unctuousness"],
    "fulton": ["robert fulton"],
    "fumaria": ["genus fumaria"],
    "fumariaceae": ["family fumariaceae", "fumitory family"],
    "fumble": ["blunder"],
    "fume": ["smoke"],
    "fumewort": ["corydalis solida", "fumeroot"],
    "fumigate": ["fume"],
    "fumitory": ["fumaria officinalis", "fumeroot", "fumewort"],
    "fun": ["play", "sport"],
    "funambulism": ["tightrope walking"],
    "funambulist": ["tightrope walker"],
    "function": ["go", "operate", "run", "work"],
    "function word": ["closed-class word"],
    "functional": ["operable", "operational", "usable", "useable"],
    "functional anatomy": ["morphophysiology", "physiological anatomy"],
    "functional magnetic resonance imaging": ["fmri"],
    "fund": ["monetary fund"],
    "fund-raise": ["fund raise", "fundraise"],
    "fund-raising campaign": ["fund-raising drive", "fund-raising effort"],
    "fundamental": ["first harmonic", "fundamental frequency"],
    "fundamental analysis": ["fundamentals analysis"],
    "fundamental law": ["constitution", "organic law"],
    "fundamental quantity": ["fundamental measure"],
    "fundamentalist": ["fundamentalistic"],
    "fundamentals": ["basic principle", "basics", "bedrock", "fundamental principle"],
    "funds": ["cash in hand", "finances", "monetary resource", "pecuniary resource"],
    "fundulus": ["genus fundulus"],
    "funeral home": ["funeral chapel", "funeral church", "funeral parlor", "funeral parlour", "funeral-residence"],
    "funeral march": ["dead march"],
    "funereal": ["sepulchral"],
    "fungal": ["fungous"],
    "fungal infection": ["mycosis"],
    "fungi": ["fungus kingdom", "kingdom fungi"],
    "fungia": ["genus fungia"],
    "fungicidal": ["antifungal"],
    "fungoid": ["funguslike"],
    "fungus gnat": ["sciara", "sciarid"],
    "funicle": ["funiculus"],
    "funk": ["blue funk"],
    "funky": ["low-down"],
    "funnel": ["funnel shape"],
    "funny bone": ["crazy bone"],
    "funny story": ["funny", "funny remark", "good story"],
    "funrun": ["fun run"],
    "fur": ["pelt"],
    "furan": ["furane", "furfuran"],
    "furcation": ["forking"],
    "furfural": ["furfuraldehyde"],
    "furled": ["rolled"],
    "furlough": ["lay off"],
    "furnace lining": ["refractory"],
    "furnariidae": ["family furnariidae"],
    "furnarius": ["genus furnarius"],
    "furnished": ["equipped"],
    "furnishing": ["trappings"],
    "furniture": ["article of furniture", "piece of furniture"],
    "furnivall": ["frederick james furnivall"],
    "furor": ["furore"],
    "furosemide": ["lasix"],
    "furred": ["furry"],
    "furring strip": ["furring"],
    "furrow": ["crease", "wrinkle"],
    "furrowed": ["rugged"],
    "further": ["farther"],
    "furthermore": ["moreover", "what is more"],
    "furthest": ["farthest"],
    "furtive": ["sneak", "sneaky", "stealthy", "surreptitious"],
    "furtively": ["on the sly"],
    "furtiveness": ["sneakiness", "stealthiness"],
    "fury": ["erinyes", "eumenides"],
    "fuscoboletinus": ["genus fuscoboletinus"],
    "fuscous": ["taupe"],
    "fuse": ["electrical fuse", "safety fuse"],
    "fusee": ["fuzee"],
    "fusee drive": ["fusee"],
    "fusiform": ["cigar-shaped", "spindle-shaped"],
    "fusillade": ["burst", "salvo", "volley"],
    "fusion": ["nuclear fusion", "nuclear fusion reaction"],
    "fuss": ["fret", "niggle"]
}
