synonyms = {
    "batter": ["batsman", "hitter", "slugger"],
    "battered": ["beat-up", "beaten-up"],
    "battering": ["banging"],
    "battery": ["stamp battery"],
    "battery acid": ["electrolyte acid"],
    "batting": ["batten"],
    "batting average": ["hitting average"],
    "batting cage": ["cage"],
    "batting order": ["card", "lineup"],
    "battle": ["combat"],
    "battle damage": ["combat casualty"],
    "battle fatigue": ["combat fatigue", "combat neurosis", "shell shock"],
    "battle of the ardennes bulge": ["ardennes counteroffensive", "battle of the bulge"],
    "battle of the marne": ["belleau wood", "chateau-thierry", "marne river"],
    "battle of wake": ["battle of wake island"],
    "battle sight": ["battlesight"],
    "battle-ax": ["battle-axe"],
    "battledore": ["battledore and shuttlecock"],
    "battlefield": ["battleground", "field", "field of battle", "field of honor"],
    "battlefront": ["front", "front line"],
    "battleful": ["bellicose", "combative"],
    "battlement": ["crenelation", "crenellation"],
    "battleship": ["battlewagon"],
    "baud": ["baud rate"],
    "baudelaire": ["charles baudelaire", "charles pierre baudelaire"],
    "bauhinia": ["genus bauhinia"],
    "baum": ["frank baum", "lyman frank brown"],
    "bawdry": ["bawdy"],
    "bawdy": ["off-color", "ribald"],
    "bawl": ["bellow"],
    "bay": ["quest"],
    "bay myrtle": ["myrica cerifera", "puckerbush"],
    "bay scallop": ["pecten irradians"],
    "bay willow": ["laurel willow", "salix pentandra"],
    "bay window": ["bow window"],
    "baya": ["ploceus philippinus"],
    "bayard": ["chevalier de bayard", "pierre de terrail", "pierre terrail", "seigneur de bayard"],
    "bayberry": ["bay-rum tree", "jamaica bayberry", "pimenta acris", "wild cinnamon"],
    "bayberry wax": ["bayberry tallow"],
    "bayes": ["thomas bayes"],
    "bayrut": ["beirut", "capital of lebanon"],
    "bazaar": ["bazar"],
    "bb": ["bb shot"],
    "bc": ["b.c.", "before christ"],
    "bce": ["b.c.e."],
    "be": ["live"],
    "be active": ["move"],
    "be due": ["flow from"],
    "be-all and end-all": ["be all and end all"],
    "beach ball": ["beachball"],
    "beach flea": ["sand flea", "sand hopper", "sandhopper"],
    "beach heather": ["hudsonia tomentosa", "poverty grass"],
    "beach pancake": ["abronia maritima"],
    "beach pea": ["lathyrus japonicus", "lathyrus maritimus", "sea pea"],
    "beach plum": ["beach plum bush", "prunus maritima"],
    "beach sand verbena": ["abronia umbellata", "pink sand verbena"],
    "beach strawberry": ["chilean strawberry", "fragaria chiloensis"],
    "beach wagon": ["beach waggon", "estate car", "station waggon", "station wagon", "waggon", "wagon"],
    "beachhead": ["foothold"],
    "beacon": ["beacon fire"],
    "bead tree": ["jumby bean", "jumby tree", "ormosia monosperma"],
    "beaded lizard": ["heloderma horridum", "mexican beaded lizard"],
    "beading": ["beadwork"],
    "beadle": ["george beadle", "george wells beadle"],
    "beads": ["string of beads"],
    "beadsman": ["bedesman"],
    "beady": ["beadlike", "buttonlike", "buttony"],
    "beak": ["honker", "hooter", "nozzle", "schnoz", "schnozzle", "snoot", "snout"],
    "beaked hazelnut": ["corylus cornuta"],
    "beaked salmon": ["gonorhynchus gonorhynchus", "sandfish"],
    "beam": ["electron beam", "ray"],
    "beaming": ["glad"],
    "beamish": ["smiling", "twinkly"],
    "bean": ["bean plant"],
    "bean caper": ["syrian bean caper", "zygophyllum fabago"],
    "bean curd": ["tofu"],
    "bean trefoil": ["anagyris foetida", "stinking bean trefoil"],
    "bean weevil": ["acanthoscelides obtectus"],
    "beanball": ["beaner"],
    "beanie": ["beany"],
    "bear": ["hold"],
    "bear claw": ["bear paw"],
    "bear down": ["overbear"],
    "bear down on": ["bear down upon"],
    "bear grass": ["yucca smalliana"],
    "bear oak": ["quercus ilicifolia"],
    "bear's breech": ["acanthus mollis", "bear's breeches", "sea holly"],
    "bear's-paw fern": ["aglaomorpha meyeniana"],
    "bearable": ["endurable", "sufferable", "supportable"],
    "bearberry": ["ilex decidua", "possum haw", "winterberry"],
    "bearberry willow": ["salix uva-ursi"],
    "beard": ["face fungus", "whiskers"],
    "beard lichen": ["beard moss", "usnea barbata"],
    "beard worm": ["pogonophoran"],
    "bearded": ["barbate", "bewhiskered", "whiskered", "whiskery"],
    "bearded seal": ["erignathus barbatus", "squareflipper square flipper"],
    "bearded vulture": ["gypaetus barbatus", "lammergeier", "lammergeyer"],
    "bearded wheatgrass": ["agropyron subsecundum"],
    "beardless": ["whiskerless"],
    "bearing": ["aim", "heading"],
    "bearing rein": ["checkrein"],
    "bearskin": ["busby", "shako"],
    "beast": ["brute", "savage", "wildcat", "wolf"],
    "beast of burden": ["jument"],
    "beastliness": ["meanness"],
    "beastly": ["god-awful", "hellish"],
    "beat": ["bunk"],
    "beat around the bush": ["equivocate", "palter", "prevaricate", "tergiversate"],
    "beat down": ["bargain down"],
    "beat generation": ["beatniks", "beats"],
    "beat out": ["tap out", "thump out"],
    "beat up": ["drum up", "rally"],
    "beatable": ["vanquishable", "vincible"],
    "beatified": ["blessed"],
    "beating": ["whipping"],
    "beating-reed instrument": ["reed", "reed instrument"],
    "beatnik": ["beat"],
    "beats per minute": ["bpm", "m.m.", "metronome marking"],
    "beaufort scale": ["wind scale"],
    "beaugregory": ["pomacentrus leucostictus"],
    "beaumont": ["william beaumont"],
    "beaumontia": ["genus beaumontia"],
    "beautician": ["cosmetician"],
    "beautifully": ["attractively"],
    "beauty": ["beaut"],
    "beauty bush": ["kolkwitzia amabilis"],
    "beauvoir": ["simone de beauvoir"],
    "beaver": ["beaver away"],
    "beaverbrook": ["1st baron beaverbrook", "william maxwell aitken"],
    "bechtel crab": ["flowering crab"],
    "becket": ["saint thomas a becket", "st. thomas a becket", "thomas a becket"],
    "beckett": ["samuel beckett"],
    "beckon": ["wave"],
    "become": ["suit"],
    "becoming": ["comely", "comme il faut", "decent", "decorous", "seemly"],
    "becquerel": ["antoine henri becquerel", "henri becquerel"],
    "bed": ["bottom"],
    "bed and breakfast": ["bed-and-breakfast"],
    "bed down": ["bunk down"],
    "bed ground": ["bed-ground", "bedground"],
    "bed-hop": ["bedhop", "sleep around"],
    "bedaub": ["besmear"],
    "bedbug": ["bed bug", "chinch", "cimex lectularius"],
    "bedclothes": ["bed clothing", "bedding"],
    "bedder": ["bedding plant"],
    "bedding material": ["bedding", "litter"],
    "bede": ["baeda", "beda", "saint baeda", "saint beda", "saint bede", "st. baeda", "st. beda", "st. bede", "the venerable bede"],
    "bedewed": ["dewy"],
    "bedfast": ["bedrid", "bedridden", "sick-abed"],
    "bedizen": ["dizen"],
    "bedlam": ["booby hatch", "crazy house", "cuckoo's nest", "funny farm", "funny house", "loony bin", "madhouse", "nut house", "nuthouse", "sanatorium", "snake pit"],
    "bedouin": ["beduin"],
    "bedraggle": ["draggle"],
    "bedraggled": ["broken-down", "derelict", "dilapidated", "ramshackle", "tatterdemalion", "tumble-down"],
    "bedrest": ["bed rest"],
    "bedroom": ["bedchamber", "chamber", "sleeping accommodation", "sleeping room"],
    "bedroom suite": ["bedroom set"],
    "bedsitting room": ["bedsit", "bedsitter"],
    "bedsore": ["decubitus ulcer", "pressure sore"],
    "bedspread": ["bed cover", "bed covering", "bedcover", "counterpane", "spread"],
    "bedstead": ["bedframe"],
    "bedwetter": ["bed wetter", "wetter"],
    "bee balm": ["beebalm", "monarda fistulosa"],
    "bee moth": ["galleria mellonella", "wax moth"],
    "bee orchid": ["ophrys apifera"],
    "beebread": ["ambrosia"],
    "beech": ["beechwood"],
    "beecher": ["henry ward beecher"],
    "beef": ["boeuf"],
    "beef bourguignonne": ["boeuf bourguignonne"],
    "beef broth": ["beef stock"],
    "beef fondue": ["boeuf fondu bourguignon"],
    "beef roast": ["roast beef"],
    "beef tea": ["bovril"],
    "beef wellington": ["filet de boeuf en croute"],
    "beefsteak begonia": ["begonia erythrophylla", "begonia feastii", "kidney begonia"],
    "beefsteak fungus": ["fistulina hepatica"],
    "beefsteak plant": ["perilla frutescens crispa"],
    "beefwood": ["grevillea striata"],
    "beefy": ["buirdly", "burly", "husky", "strapping"],
    "beehive": ["hive"],
    "beekeeper": ["apiarist", "apiculturist"],
    "beekeeping": ["apiculture"],
    "beep": ["bleep"],
    "beeper": ["pager"],
    "beer barrel": ["beer keg"],
    "beer drinker": ["ale drinker"],
    "beer mug": ["stein"],
    "beerbohm": ["max beerbohm", "sir henry maxmilian beerbohm"],
    "beet": ["beta vulgaris", "common beet"],
    "beet armyworm": ["spodoptera exigua"],
    "beethoven": ["ludwig van beethoven", "van beethoven"],
    "beetle": ["beetling"],
    "beetle-browed": ["scowling"],
    "beetroot": ["beta vulgaris rubra"],
    "befall": ["bechance", "betide"],
    "befit": ["beseem", "suit"],
    "befogged": ["befuddled"],
    "befouled": ["fouled"],
    "befoulment": ["defilement", "pollution"],
    "befuddle": ["fuddle"],
    "beg": ["implore", "pray"],
    "beget": ["bring forth", "engender", "father", "generate", "get", "mother", "sire"],
    "beggar": ["pauperise", "pauperize"],
    "beggar's lice": ["beggar lice"],
    "beggar-my-neighbor": ["beggar-my-neighbour", "strip-jack-naked"],
    "beggar-my-neighbor policy": ["beggar-my-neighbor strategy", "beggar-my-neighbour policy", "beggar-my-neighbour strategy"],
    "beggarly": ["mean"],
    "beggarweed": ["desmodium purpureum", "desmodium tortuosum"],
    "beggary": ["mendicancy", "mendicity"],
    "begin": ["start"],
    "beginning": ["commencement", "first", "get-go", "kickoff", "offset", "outset", "showtime", "start", "starting time"],
    "begoniaceae": ["begonia family", "family begoniaceae"],
    "begrimed": ["dingy", "grimy", "grubby", "grungy", "raunchy"],
    "begrudge": ["resent"],
    "beguiled": ["captivated", "charmed", "delighted", "enthralled", "entranced"],
    "beguilement": ["distraction"],
    "behave": ["comport"],
    "behavior": ["behaviour"],
    "behavior therapy": ["behavior modification"],
    "behavioral": ["behavioural"],
    "behaviorism": ["behavioristic psychology", "behaviourism", "behaviouristic psychology"],
    "behaviorist": ["behaviourist"],
    "behavioristic": ["behaviorist", "behaviourist", "behaviouristic"],
    "beheaded": ["decapitated"],
    "behind": ["slow"],
    "behold": ["lay eyes on"],
    "behoove": ["behove"],
    "behrens": ["peter behrens"],
    "beige": ["ecru"],
    "beijing": ["capital of red china", "peiping", "peking"],
    "being": ["beingness", "existence"],
    "bejewel": ["jewel"],
    "belabor": ["belabour"],
    "belabour": ["belabor"],
    "belamcanda": ["genus belamcanda"],
    "belarus": ["belorussia", "byelarus", "byelorussia", "republic of belarus", "white russia"],
    "belarusian": ["byelorussian", "white russian"],
    "belated": ["late", "tardy"],
    "belch": ["belching", "burp", "burping", "eructation"],
    "beldam": ["beldame"],
    "belem": ["feliz lusitania", "para", "santa maria de belem", "st. mary of bethlehem"],
    "belemnitidae": ["family belemnitidae"],
    "belemnoidea": ["order belemnoidea"],
    "belfast": ["capital of northern ireland"],
    "belgian endive": ["french endive", "witloof"],
    "belgian hare": ["leporide"],
    "belgian sheepdog": ["belgian shepherd"],
    "belgium": ["belgique", "kingdom of belgium"],
    "belgrade": ["beograd", "capital of serbia and montenegro"],
    "believe": ["trust"],
    "believer": ["truster"],
    "belittled": ["diminished", "small"],
    "belittling": ["deprecating", "deprecative", "deprecatory", "depreciative", "depreciatory", "slighting"],
    "belize": ["british honduras"],
    "bell": ["ship's bell"],
    "bell apple": ["sweet cup", "water lemon", "yellow granadilla"],
    "bell buoy": ["gong buoy"],
    "bell cote": ["bell cot"],
    "bell heather": ["erica cinerea", "fine-leaved heath", "heather bell"],
    "bell jar": ["bell glass"],
    "bell ringer": ["bull's eye", "home run", "mark"],
    "bell ringing": ["carillon", "carillon playing"],
    "bell seat": ["balloon seat"],
    "bell-bottomed": ["bell-bottom", "bellbottom"],
    "belladonna": ["atropa belladonna", "belladonna plant", "deadly nightshade"],
    "belladonna lily": ["amaryllis belladonna", "naked lady"],
    "bellarmine": ["bellarmino", "cardinal bellarmine", "roberto francesco romolo bellarmine"],
    "bellbottom trousers": ["bell-bottoms", "bellbottom pants"],
    "bellboy": ["bellhop", "bellman"],
    "belle isle cress": ["american cress", "american watercress", "barbarea praecox", "barbarea verna", "early winter cress", "land cress"],
    "belles-lettres": ["belles lettres"],
    "bellicosity": ["bellicoseness"],
    "bellied": ["bellying", "bulbous", "bulging", "bulgy", "protuberant"],
    "belligerence": ["belligerency"],
    "belligerent": ["militant", "war-ridden", "warring"],
    "belligerently": ["hostilely"],
    "bellini": ["vincenzo bellini"],
    "bellis": ["genus bellis"],
    "belloc": ["hilaire belloc", "joseph hilaire peter belloc"],
    "bellow": ["roar"],
    "bellwort": ["merry bells", "wild oats"],
    "belly": ["belly out"],
    "belly dance": ["belly dancing", "danse du ventre"],
    "belly dancer": ["exotic belly dancer", "exotic dancer"],
    "belly flop": ["belly flopper", "belly whop", "belly whopper"],
    "belly laugh": ["howler", "riot", "scream", "sidesplitter", "thigh-slapper", "wow"],
    "bellyless": ["flat-bellied"],
    "belmont park": ["belmont"],
    "belong": ["go"],
    "belong to": ["belong"],
    "belonidae": ["family belonidae"],
    "belostomatidae": ["family belostomatidae"],
    "beloved": ["dear", "dearest", "honey", "love"],
    "below": ["infra"],
    "belowground": ["underground"],
    "belt": ["belt ammunition", "belted ammunition"],
    "belt out": ["belt"],
    "belted kingfisher": ["ceryle alcyon"],
    "belted sandfish": ["serranus subligarius"],
    "beltlike": ["belt-like"],
    "beltway": ["bypass", "ring road", "ringway"],
    "beluga": ["acipenser huso", "hausen", "white sturgeon"],
    "bemisia": ["genus bemisia"],
    "bemused": ["deep in thought", "lost", "preoccupied"],
    "ben gurion": ["david ben gurion", "david grun"],
    "ben sira": ["ecclesiasticus", "sirach", "wisdom of jesus the son of sirach"],
    "bench warrant": ["arrest warrant"],
    "benchley": ["robert benchley", "robert charles benchley"],
    "benchmark": ["bench mark"],
    "bend": ["flex"],
    "bendability": ["pliability"],
    "bendable": ["pliable", "pliant", "waxy"],
    "bended": ["bent"],
    "bending": ["bend"],
    "benedick": ["benedict"],
    "benedict": ["ruth benedict", "ruth fulton"],
    "benedict xiv": ["prospero lambertini"],
    "benedict xv": ["giacomo della chiesa"],
    "benedictine order": ["order of saint benedict"],
    "benediction": ["blessing"],
    "benedictory": ["benedictive"],
    "benefactive role": ["beneficiary"],
    "benefactor": ["helper"],
    "benefice": ["ecclesiastical benefice"],
    "beneficent": ["benevolent", "eleemosynary", "philanthropic"],
    "beneficial": ["good"],
    "beneficiary": ["donee"],
    "benefit": ["do good"],
    "benet": ["stephen vincent benet"],
    "benevolence": ["benefaction"],
    "benevolent": ["freehearted"],
    "bengali": ["bangla"],
    "benight": ["bedim"],
    "benighted": ["nighted"],
    "benign": ["benignant"],
    "benign prostatic hyperplasia": ["bph"],
    "benign tumor": ["benign tumour", "nonmalignant neoplasm", "nonmalignant tumor", "nonmalignant tumour"],
    "benignant": ["gracious"],
    "benignity": ["benignancy", "graciousness"],
    "benignly": ["benignantly"],
    "benin": ["dahomey", "republic of benin"],
    "bennet": ["geum virginianum", "white avens"],
    "bennett": ["floyd bennett"],
    "bennettitaceae": ["family bennettitaceae"],
    "bennettitales": ["order bennettitales"],
    "bennettitis": ["genus bennettitis"],
    "benny": ["benjamin kubelsky", "jack benny"],
    "bent": ["bent grass", "bent-grass"],
    "bentham": ["jeremy bentham"],
    "benthic": ["benthal", "benthonic"],
    "benthos": ["benthic division", "benthonic zone"],
    "benton": ["thomas hart benton"],
    "benzedrine": ["bennie"],
    "benzene": ["benzine", "benzol"],
    "benzene formula": ["benzene nucleus", "benzene ring", "kekule formula"],
    "benzoate of soda": ["sodium benzoate"],
    "benzocaine": ["ethyl aminobenzoate"],
    "benzofuran": ["coumarone", "cumarone"],
    "benzoin": ["asa dulcis", "benjamin", "gum benjamin", "gum benzoin"],
    "benzoyl group": ["benzoyl radical"],
    "benzyl": ["benzyl group", "benzyl radical"],
    "bequeath": ["leave", "will"],
    "bequest": ["legacy"],
    "berating": ["blowing up"],
    "berberidaceae": ["barberry family", "family berberidaceae"],
    "berberis": ["genus berberis"],
    "berbers": ["arab-berbers"],
    "bercy": ["bercy butter"],
    "bereaved": ["bereaved person"],
    "bereft": ["lovelorn", "unbeloved"],
    "berg": ["alban berg"],
    "bergamot": ["bergamot orange", "citrus bergamia"],
    "bergamot mint": ["eau de cologne mint", "lemon mint", "mentha citrata"],
    "bergman": ["ingrid bergman"],
    "bergson": ["henri bergson", "henri louis bergson"],
    "beria": ["lavrenti pavlovich beria"],
    "bering": ["behring", "vitus behring", "vitus bering"],
    "bering time": ["bering standard time"],
    "berith": ["berit", "bris", "briss", "brith"],
    "berkeley": ["bishop berkeley", "george berkeley"],
    "berkelium": ["atomic number 97", "bk"],
    "berkshires": ["berkshire hills"],
    "berlage": ["hendrik petrus berlage"],
    "berlin": ["irving berlin", "israel baline"],
    "berlin doughnut": ["bismark", "jelly doughnut"],
    "berlioz": ["hector berlioz", "louis-hector berlioz"],
    "bermuda": ["bermudas"],
    "bermuda buttercup": ["english-weed", "oxalis cernua", "oxalis pes-caprae"],
    "bermuda cedar": ["juniperus bermudiana"],
    "bermuda chub": ["kyphosus sectatrix", "rudderfish"],
    "bermuda grass": ["bahama grass", "cynodon dactylon", "devil grass", "doob", "kweek", "scutch grass", "star grass"],
    "bermuda maidenhair": ["adiantum bellum", "bermuda maidenhair fern"],
    "bermuda rig": ["bermudan rig", "bermudian rig", "marconi rig"],
    "bermuda shorts": ["jamaica shorts"],
    "bermudan": ["bermudian"],
    "bern": ["berne", "capital of switzerland"],
    "bernard": ["claude bernard"],
    "bernhardt": ["henriette rosine bernard", "sarah bernhardt"],
    "bernini": ["giovanni lorenzo bernini"],
    "bernoulli": ["daniel bernoulli"],
    "bernoulli's law": ["law of large numbers"],
    "bernstein": ["leonard bernstein"],
    "berra": ["lawrence peter berra", "yogi", "yogi berra"],
    "berried": ["baccate", "bacciferous"],
    "berry": ["charles edward berry", "chuck berry"],
    "berserker": ["berserk"],
    "berteroa": ["genus berteroa"],
    "berth": ["built in bed", "bunk"],
    "bertholletia": ["genus bertholletia"],
    "bertillon": ["alphonse bertillon"],
    "bertolucci": ["bernardo bertolucci"],
    "berycomorphi": ["order berycomorphi"],
    "beryllium": ["atomic number 4", "be", "glucinium"],
    "berzelius": ["jons jakob berzelius"],
    "beseeching": ["imploring", "pleading"],
    "beseechingly": ["entreatingly", "imploringly", "importunately", "pleadingly"],
    "beset": ["set upon"],
    "besides": ["also", "as well", "likewise", "too"],
    "besiege": ["beleaguer", "circumvent", "hem in", "surround"],
    "besot": ["stupefy"],
    "besotted": ["blind drunk", "blotto", "cockeyed", "crocked", "fuddled", "loaded", "pie-eyed", "pissed", "pixilated", "plastered", "slopped", "sloshed", "smashed", "soaked", "soused", "sozzled", "squiffy", "stiff", "tight", "wet"],
    "bespeak": ["betoken", "indicate", "point", "signal"],
    "bespectacled": ["monocled", "spectacled"],
    "bespoke": ["bespoken", "made-to-order", "tailor-made", "tailored"],
    "bespoken": ["betrothed"],
    "bessel": ["friedrich wilhelm bessel"],
    "bessemer": ["sir henry bessemer"],
    "bessera": ["genus bessera"],
    "besseya": ["genus besseya"],
    "best": ["c. h. best", "charles herbert best"],
    "best seller": ["bestseller"],
    "bestiality": ["zooerastia", "zooerasty"],
    "bestialize": ["bestialise"],
    "bestially": ["brutishly", "in a beastly manner"],
    "bestir": ["rouse"],
    "bestowal": ["bestowment"],
    "bestubbled": ["stubbled", "stubbly"],
    "bet": ["play", "wager"],
    "bet on": ["back", "gage", "game", "punt", "stake"],
    "beta": ["genus beta"],
    "beta blocker": ["beta-adrenergic blocker", "beta-adrenergic blocking agent", "beta-blocking agent"],
    "beta radiation": ["beta ray", "electron radiation"],
    "beta receptor": ["beta-adrenergic receptor", "beta-adrenoceptor"],
    "beta rhythm": ["beta wave"],
    "betatron": ["induction accelerator"],
    "betel": ["betel pepper", "piper betel"],
    "betel nut": ["areca nut"],
    "betel palm": ["areca catechu"],
    "betelgeuse": ["alpha orionis"],
    "bethe": ["hans albrecht bethe", "hans bethe"],
    "bethlehem": ["bayt lahm", "bethlehem ephrathah", "bethlehem-judah"],
    "bethune": ["mary mcleod bethune"],
    "betray": ["sell"],
    "betroth": ["affiance", "engage", "plight"],
    "betrothal": ["engagement", "troth"],
    "better": ["break"],
    "bettongia": ["genus bettongia"],
    "bettor": ["better", "punter", "wagerer"],
    "betula": ["genus betula"],
    "betulaceae": ["birch family", "family betulaceae"],
    "between": ["betwixt"],
    "between decks": ["'tween decks"],
    "bevel": ["chamfer"],
    "bevel gear": ["pinion and crown wheel", "pinion and ring gear"],
    "beverage": ["drink", "drinkable", "potable"],
    "beveridge": ["first baron beveridge", "william henry beveridge"],
    "bevin": ["ernest bevin"],
    "beware": ["mind"],
    "bewhisker": ["whisker"],
    "bewick's swan": ["cygnus columbianus bewickii"],
    "bewilder": ["bemuse", "discombobulate", "throw"],
    "bewilderingly": ["confusingly"],
    "bewilderment": ["bafflement", "befuddlement", "bemusement", "mystification", "obfuscation", "puzzlement"],
    "bewitched": ["ensorcelled"],
    "bewitchery": ["animal magnetism", "beguilement"],
    "bewitching": ["captivating", "enchanting", "enthralling", "entrancing", "fascinating"],
    "bewitchingly": ["captivatingly", "enchantingly", "enthrallingly"],
    "beyond doubt": ["indubitable"],
    "bezant": ["bezzant", "byzant", "solidus"],
    "bezoar goat": ["capra aegagrus", "pasang"],
    "bhadon": ["bhadrapada"],
    "bhagavad-gita": ["bhagavadgita", "gita"],
    "bhutan": ["kingdom of bhutan"],
    "bhutanese": ["bhutani"],
    "bialy": ["bialystoker"],
    "bias": ["predetermine"],
    "biased": ["colored", "coloured", "one-sided", "slanted"],
    "biaxial": ["biaxal", "biaxate"],
    "bible": ["book", "christian bible", "good book", "holy scripture", "holy writ", "scripture", "word", "word of god"],
    "biblical": ["scriptural"],
    "bibliographic": ["bibliographical"],
    "bibliolatry": ["bible-worship"],
    "bibliophile": ["book lover", "booklover"],
    "bibliopole": ["bibliopolist"],
    "bibliothecal": ["bibliothecarial"],
    "bibos": ["genus bibos"],
    "bibulous": ["boozy", "drunken", "sottish"],
    "bicameral": ["two-chambered"],
    "bicarbonate": ["hydrogen carbonate"],
    "bicarbonate of soda": ["baking soda", "saleratus", "sodium bicarbonate", "sodium hydrogen carbonate"],
    "bicentennial": ["bicentenary"],
    "biceps brachii": ["biceps humeri", "musculus biceps brachii"],
    "bichromate": ["dichromate"],
    "bicker": ["bickering", "fuss", "pettifoggery", "spat", "squabble", "tiff"],
    "bicolor": ["bichrome", "bicolored", "bicolour", "bicoloured", "dichromatic"],
    "bicolor lespediza": ["ezo-yama-hagi", "lespedeza bicolor"],
    "biconcave": ["concavo-concave"],
    "biconvex": ["convexo-convex", "lenticular", "lentiform"],
    "bicorn": ["bicorne"],
    "bicuspid": ["bicuspidate"],
    "bicycle": ["bike", "cycle", "pedal", "wheel"],
    "bicycle clip": ["trouser clip"],
    "bicycle seat": ["saddle"],
    "bicycle-built-for-two": ["tandem", "tandem bicycle"],
    "bid": ["call"],
    "bidding": ["summons"],
    "bide": ["abide", "stay"],
    "bidens": ["genus bidens"],
    "biennial": ["biyearly"],
    "biennially": ["biyearly"],
    "bierce": ["ambrose bierce", "ambrose gwinett bierce"],
    "biface": ["bifacial"],
    "bifurcate": ["biramous", "branched", "forficate", "fork-like", "forked", "pronged", "prongy"],
    "big": ["heavy"],
    "big blue": ["blu-82"],
    "big brown bat": ["eptesicus fuscus"],
    "big cat": ["cat"],
    "big dipper": ["charles's wain", "dipper", "plough", "wagon", "wain"],
    "big h": ["hell dust", "nose drops", "scag", "skag", "smack", "thunder"],
    "big sagebrush": ["artemisia tridentata", "blue sage", "seriphidium tridentatum"],
    "big shellbark": ["big shagbark", "big shellbark hickory", "carya laciniosa", "king nut", "king nut hickory"],
    "big shot": ["big cheese", "big deal", "big enchilada", "big fish", "big gun", "big wheel", "head honcho"],
    "big spender": ["high roller"],
    "big toe": ["great toe", "hallux"],
    "big-bang theory": ["big bang theory"],
    "big-bellied": ["great bellied"],
    "big-chested": ["chesty"],
    "big-cone spruce": ["big-cone douglas fir", "pseudotsuga macrocarpa"],
    "big-eared bat": ["megaderma lyra"],
    "big-shouldered": ["broad-shouldered", "square-shouldered"],
    "big-ticket": ["high-ticket"],
    "big-tree plum": ["prunus mexicana"],
    "bigeye scad": ["big-eyed scad", "goggle-eye", "selar crumenophthalmus"],
    "bigfoot": ["sasquatch"],
    "bigger": ["larger"],
    "biggish": ["largish"],
    "bigheaded": ["persnickety", "snooty", "snot-nosed", "snotty", "stuck-up", "too big for one's breeches", "uppish"],
    "bighorn": ["bighorn river"],
    "bigmouthed": ["blabbermouthed", "blabby", "talkative"],
    "bignonia": ["genus bignonia"],
    "bignoniaceae": ["family bignoniaceae"],
    "bigotry": ["dogmatism"],
    "bijugate leaf": ["bijugous leaf", "twice-pinnate"],
    "bikini": ["two-piece"],
    "bilabiate": ["two-lipped"],
    "bilateral": ["bilaterally symmetric", "bilaterally symmetrical", "isobilateral"],
    "bilaterality": ["bilateral symmetry", "bilateralism"],
    "bilberry": ["blaeberry", "viccinium myrtillus", "whinberry", "whortleberry"],
    "bile": ["gall"],
    "bilge": ["take in water"],
    "bilimbi": ["averrhoa bilimbi"],
    "bilingual": ["bilingualist"],
    "bilious": ["biliary"],
    "bilirubin": ["haematoidin", "hematoidin"],
    "bill": ["bank bill", "bank note", "banker's bill", "banknote", "federal reserve note", "government note", "greenback", "note"],
    "bill of lading": ["waybill"],
    "bill poster": ["bill sticker", "poster"],
    "billboard": ["hoarding"],
    "billiard room": ["billiard hall", "billiard parlor", "billiard parlour", "billiard saloon"],
    "billion": ["1000000000000", "one million million"],
    "billow": ["wallow"],
    "billowy": ["billowing", "surging"],
    "billy": ["billy goat", "he-goat"],
    "billyo": ["all get out", "billy-ho", "billyoh"],
    "bilobate": ["bilobated", "bilobed"],
    "bilocular": ["biloculate"],
    "bimetal": ["bimetallic"],
    "bimetallistic": ["bimetallic"],
    "bimillennium": ["bimillenary"],
    "bimonthly": ["bimestrial"],
    "bin": ["binful"],
    "bin laden": ["osama bin laden", "usama bin laden"],
    "binary": ["binary program"],
    "binary numeration system": ["binary number system", "binary system", "pure binary numeration system"],
    "binary star": ["binary", "double star"],
    "binaural": ["biaural"],
    "binaurally": ["in both ears", "to both ears"],
    "bind": ["attach", "bond", "tie"],
    "bindable": ["bondable"],
    "binder": ["reaper binder"],
    "binder's board": ["binder board"],
    "binding": ["back", "book binding", "cover"],
    "binding energy": ["separation energy"],
    "binet": ["alfred binet"],
    "binoculars": ["field glasses", "opera glasses"],
    "binomial": ["binominal"],
    "binomial distribution": ["bernoulli distribution"],
    "binturong": ["arctictis bintourong", "bearcat"],
    "binucleate": ["binuclear", "binucleated"],
    "bioassay": ["bio-assay"],
    "biogenesis": ["biogeny"],
    "biogeographic": ["biogeographical"],
    "biographic": ["biographical"],
    "biography": ["life", "life history", "life story"],
    "biological": ["biologic"],
    "biological agent": ["biohazard"],
    "biological defense": ["biodefence", "biodefense", "biological defence"],
    "biological warfare": ["bioattack", "biologic attack", "biological attack", "bw"],
    "biological warfare defense": ["biological warfare defence", "bw defence", "bw defense"],
    "biologist": ["life scientist"],
    "biology": ["biological science"],
    "biology department": ["department of biology"],
    "biology lab": ["bio lab", "biology laboratory"],
    "biometric identification": ["biometric authentication", "identity verification"],
    "biometrics": ["biometry", "biostatistics"],
    "biosynthesis": ["biogenesis"],
    "biosystematics": ["biosystematy"],
    "biota": ["biology"],
    "biotechnology": ["biotech"],
    "bioterrorism": ["biological terrorism"],
    "biotin": ["vitamin h"],
    "bioweapon": ["bioarm", "biological weapon"],
    "biparous": ["twinning"],
    "bipartisan": ["bipartizan", "two-party", "two-way"],
    "bipartite": ["two-part", "two-way"],
    "bipedal": ["biped", "two-footed"],
    "biplane flying fish": ["four-wing flying fish"],
    "bipolar disorder": ["manic depression", "manic depressive illness", "manic-depressive psychosis"],
    "biquadrate": ["biquadratic", "fourth power", "quartic"],
    "biquadratic": ["biquadratic polynomial", "quartic polynomial"],
    "biquadratic equation": ["biquadratic"],
    "birch": ["birch tree"],
    "birch leaf miner": ["fenusa pusilla"],
    "birchbark canoe": ["birch bark", "birchbark"],
    "bird": ["birdwatch"],
    "bird cherry": ["bird cherry tree"],
    "bird feed": ["bird food", "birdseed"],
    "bird feeder": ["birdfeeder", "feeder"],
    "bird louse": ["biting louse", "louse"],
    "bird of paradise": ["caesalpinia gilliesii", "poinciana", "poinciana gilliesii"],
    "bird of prey": ["raptor", "raptorial bird"],
    "bird pepper": ["capsicum baccatum", "capsicum frutescens baccatum"],
    "bird shot": ["buckshot", "duck shot"],
    "bird watcher": ["birder"],
    "bird's eye view": ["panoramic view"],
    "bird's foot trefoil": ["trigonella ornithopodioides"],
    "bird's nest": ["bird nest", "birdnest"],
    "bird's nest fern": ["asplenium nidus"],
    "bird's-eye": ["panoramic"],
    "bird's-eye bush": ["ochna serrulata"],
    "bird's-foot fern": ["pellaea mucronata", "pellaea ornithopus"],
    "bird's-foot violet": ["johnny-jump-up", "pansy violet", "viola pedata", "wood violet"],
    "birdcall": ["birdsong", "call", "song"],
    "birdlime": ["lime"],
    "birdnest": ["bird-nest"],
    "biretta": ["berretta", "birretta"],
    "birl": ["birle"],
    "birling": ["logrolling"],
    "birmingham": ["pittsburgh of the south"],
    "birth": ["nascence", "nascency", "nativity"],
    "birth control": ["birth prevention", "family planning"],
    "birth defect": ["congenital abnormality", "congenital anomaly", "congenital defect", "congenital disorder"],
    "birth pangs": ["labor pains", "labour pains"],
    "birth-control campaigner": ["birth-control reformer"],
    "birthday": ["natal day"],
    "birthday present": ["birthday gift"],
    "birthmark": ["nevus"],
    "birthplace": ["cradle", "place of origin", "provenance", "provenience"],
    "birthrate": ["birth rate", "fertility", "fertility rate", "natality"],
    "birthright": ["patrimony"],
    "birthwort": ["aristolochia clematitis"],
    "biryani": ["biriani"],
    "biscutella": ["genus biscutella"],
    "bise": ["bize"],
    "biserial correlation coefficient": ["biserial correlation"],
    "bisexual": ["bisexual person"],
    "bishkek": ["biskek", "capital of kyrgyzstan", "frunze"],
    "bishop pine": ["bishop's pine", "pinus muricata"],
    "bishopry": ["episcopate"],
    "bismarck": ["iron chancellor", "otto von bismarck", "prince otto eduard leopold von bismarck", "prince otto von bismarck", "von bismarck"],
    "bismarck sea": ["battle of the bismarck sea"],
    "bismuth": ["atomic number 83", "bi"],
    "bissau": ["capital of guinea-bissau"],
    "bister": ["bistre"],
    "bistered": ["bistred"],
    "bit": ["chip", "flake", "fleck", "scrap"],
    "bit part": ["minor role"],
    "bit-by-bit": ["in small stages", "piecemeal", "step-by-step", "stepwise"],
    "bitchy": ["cattish", "catty"],
    "bite": ["burn", "sting"],
    "bite plate": ["biteplate"],
    "biting": ["bitter"],
    "bitis": ["genus bitis"],
    "bitmap": ["electronic image"],
    "bits per inch": ["bpi"],
    "bits per second": ["bps"],
    "bittacidae": ["family bittacidae"],
    "bitter": ["bitterness"],
    "bitter almond": ["amygdalus communis amara", "prunus dulcis amara"],
    "bitter betch": ["vicia orobus"],
    "bitter cassava": ["gari", "mandioc", "mandioca", "manihot esculenta", "manihot utilissima", "manioc", "tapioca plant"],
    "bitter chocolate": ["baking chocolate", "cooking chocolate"],
    "bitter dock": ["broad-leaved dock", "rumex obtusifolius", "yellow dock"],
    "bitter orange": ["seville orange", "sour orange"],
    "bittercress": ["bitter cress"],
    "bitterish": ["sharp-tasting"],
    "bitterness": ["bitter"],
    "bitternut": ["bitter hickory", "bitter pignut", "bitternut hickory", "carya cordiformis", "swamp hickory"],
    "bitterroot": ["lewisia rediviva"],
    "bittersweet": ["bittersweet nightshade", "climbing nightshade", "deadly nightshade", "poisonous nightshade", "solanum dulcamara", "woody nightshade"],
    "bittersweet chocolate": ["dark chocolate", "semi-sweet chocolate"],
    "bitty": ["bittie", "itsy-bitsy", "itty-bitty", "teensy", "teensy-weensy", "teentsy", "teeny", "teeny-weeny", "wee", "weensy", "weeny"],
    "bituminize": ["bituminise"],
    "bituminoid": ["bitumenoid"],
    "bituminous coal": ["soft coal"],
    "bivalent": ["divalent"],
    "bivalve": ["lamellibranch", "pelecypod"],
    "bivalvia": ["class bivalvia", "class lamellibranchia", "class pelecypoda", "lamellibranchia"],
    "bizarre": ["eccentric", "flakey", "flaky", "freakish", "freaky", "gonzo", "off-the-wall", "outlandish", "outre"],
    "bizet": ["georges bizet"],
    "blabbermouthed": ["leaky", "talebearing", "tattling"],
    "blaberus": ["genus blaberus"],
    "black": ["joseph black"],
    "black and gold garden spider": ["argiope aurantia"],
    "black and white": ["monochrome"],
    "black ash": ["basket ash", "brown ash", "fraxinus nigra", "hoop ash"],
    "black bamboo": ["kuri-chiku", "phyllostachys nigra"],
    "black bean": ["turtle bean"],
    "black bee": ["german bee"],
    "black beech": ["nothofagus solanderi"],
    "black bile": ["melancholy"],
    "black birch": ["betula nigra", "red birch", "river birch"],
    "black body": ["blackbody", "full radiator"],
    "black bread": ["pumpernickel"],
    "black bream": ["chrysophrys australis"],
    "black bryony": ["black bindweed", "tamus communis"],
    "black buffalo": ["ictiobus niger"],
    "black calla": ["arum palaestinum"],
    "black caraway": ["nigella sativa", "nutmeg flower", "roman coriander"],
    "black catechu": ["catechu"],
    "black cherry": ["black cherry tree", "prunus serotina", "rum cherry"],
    "black cohosh": ["black snakeroot", "cimicifuga racemosa", "rattle-top"],
    "black cottonwood": ["populus trichocarpa", "western balsam poplar"],
    "black crappie": ["pomoxis nigromaculatus"],
    "black currant": ["european black currant", "ribes nigrum"],
    "black cypress pine": ["callitris calcarata", "callitris endlicheri", "red cypress pine"],
    "black death": ["black plague"],
    "black disease": ["distomatosis", "liver rot", "sheep rot"],
    "black duck": ["anas rubripes"],
    "black flag": ["blackjack", "jolly roger", "pirate flag"],
    "black forest": ["schwarzwald"],
    "black grama": ["bouteloua eriopoda"],
    "black guillemot": ["cepphus grylle"],
    "black haw": ["viburnum prunifolium"],
    "black hawk": ["makataimeshekiakiak"],
    "black horehound": ["ballota nigra", "black archangel", "fetid horehound", "stinking horehound"],
    "black huckleberry": ["gaylussacia baccata"],
    "black humor": ["black humour"],
    "black kite": ["milvus migrans"],
    "black locust": ["robinia pseudoacacia", "yellow locust"],
    "black maire": ["olea cunninghamii"],
    "black mallee": ["black gum", "black sally", "eucalytus stellulata"],
    "black mamba": ["dendroaspis augusticeps"],
    "black mangrove": ["aegiceras majus"],
    "black marlin": ["makaira marlina", "makaira mazara"],
    "black medick": ["hop clover", "medicago lupulina", "nonesuch clover", "yellow trefoil"],
    "black morel": ["conic morel", "morchella angusticeps", "morchella conica", "narrowhead morel"],
    "black mulberry": ["morus nigra"],
    "black music": ["african-american music"],
    "black mustard": ["brassica nigra"],
    "black nightshade": ["common nightshade", "poison-berry", "poisonberry", "solanum nigrum"],
    "black oak": ["quercitron", "quercitron oak", "quercus velutina", "yellow oak"],
    "black olive": ["ripe olive"],
    "black out": ["blacken out"],
    "black pea": ["lathyrus niger"],
    "black pine": ["pinus nigra"],
    "black poplar": ["populus nigra"],
    "black race": ["negro race", "negroid race"],
    "black raspberry": ["blackcap", "blackcap raspberry", "rubus occidentalis", "thimbleberry"],
    "black rat": ["rattus rattus", "roof rat"],
    "black rat snake": ["blacksnake", "elaphe obsoleta", "mountain blacksnake", "pilot blacksnake"],
    "black rhinoceros": ["diceros bicornis"],
    "black root rot fungus": ["xylaria mali"],
    "black sage": ["california romero", "trichostema lanatum", "wooly blue curls"],
    "black salsify": ["scorzonera", "scorzonera hispanica", "viper's grass"],
    "black sea": ["euxine sea"],
    "black sea bass": ["black bass", "centropistes striata"],
    "black spleenwort": ["asplenium adiantum-nigrum"],
    "black spruce": ["picea mariana", "spruce pine"],
    "black stork": ["ciconia nigra"],
    "black swan": ["cygnus atratus"],
    "black turnstone": ["arenaria-melanocephala"],
    "black vulture": ["carrion crow", "coragyps atratus"],
    "black walnut": ["black hickory", "black walnut tree", "juglans nigra"],
    "black wattle": ["acacia auriculiformis"],
    "black widow": ["latrodectus mactans"],
    "black-and-blue": ["livid"],
    "black-and-white": ["black and white"],
    "black-backed gull": ["cob", "great black-backed gull", "larus marinus"],
    "black-billed cuckoo": ["coccyzus erythropthalmus"],
    "black-body radiation": ["blackbody radiation"],
    "black-capped chickadee": ["blackcap", "parus atricapillus"],
    "black-crowned night heron": ["nycticorax nycticorax"],
    "black-eyed pea": ["cowpea"],
    "black-eyed susan": ["black-eyed susan vine", "thunbergia alata"],
    "black-footed albatross": ["diomedea nigripes", "gooney", "gooney bird", "goonie", "goony"],
    "black-footed ferret": ["ferret", "mustela nigripes"],
    "black-fronted bush shrike": ["chlorophoneus nigrifrons"],
    "black-grey": ["black-gray", "blackish-gray", "blackish-grey"],
    "black-necked cobra": ["naja nigricollis", "spitting cobra"],
    "black-necked grebe": ["eared grebe", "podiceps nigricollis"],
    "black-necked stilt": ["himantopus mexicanus"],
    "black-stem spleenwort": ["black-stemmed spleenwort", "little ebony spleenwort"],
    "black-tailed deer": ["blacktail", "blacktail deer", "odocoileus hemionus columbianus"],
    "black-winged stilt": ["himantopus himantopus"],
    "blackberry": ["blackberry bush"],
    "blackberry-lily": ["belamcanda chinensis", "leopard lily"],
    "blackbird": ["european blackbird", "merl", "merle", "ousel", "ouzel", "turdus merula"],
    "blackboard": ["chalkboard"],
    "blackbuck": ["antilope cervicapra", "black buck"],
    "blackburn": ["blackburnian warbler", "dendroica fusca"],
    "blackcap": ["silvia atricapilla"],
    "blackcock": ["black cock"],
    "blacken": ["black", "melanise", "melanize", "nigrify"],
    "blackening": ["darkening"],
    "blackfly": ["aphis fabae", "bean aphid"],
    "blackfoot daisy": ["melampodium leucanthum"],
    "blackhead": ["comedo"],
    "blackheart": ["blackheart cherry"],
    "blackjack": ["cosh", "sap"],
    "blackjack oak": ["blackjack", "jack oak", "quercus marilandica"],
    "blacklist": ["black book", "shitlist"],
    "blackmail": ["blackjack", "pressure"],
    "blackmailer": ["extortioner", "extortionist"],
    "blackmouth bass": ["synagrops bellus"],
    "blackout": ["brownout", "dimout"],
    "blackpoll": ["dendroica striate"],
    "blacksnake": ["black racer", "coluber constrictor"],
    "blacktail jackrabbit": ["lepus californicus"],
    "blacktail prairie dog": ["cynomys ludovicianus"],
    "blackthorn": ["prunus spinosa", "sloe"],
    "blacktip shark": ["carcharhinus limbatus", "sandbar shark"],
    "blacktop": ["blacktopping"],
    "blackwash": ["black lotion"],
    "blackwood": ["blackwood tree"],
    "bladder": ["vesica"],
    "bladder campion": ["silene uniflora", "silene vulgaris"],
    "bladder senna": ["colutea arborescens"],
    "bladder sphincter": ["musculus sphincter vesicae"],
    "bladder stone": ["cystolith"],
    "bladderwrack": ["ascophyllum nodosum"],
    "bladdery": ["bladderlike"],
    "blade": ["leaf blade"],
    "blair": ["anthony charles lynton blair", "tony blair"],
    "blake": ["william blake"],
    "blame": ["find fault", "pick"],
    "blameless": ["inculpable", "irreproachable", "unimpeachable"],
    "blamelessness": ["guiltlessness", "inculpability", "inculpableness"],
    "blameworthiness": ["culpability", "culpableness"],
    "blameworthy": ["blamable", "blameable", "blameful", "censurable", "culpable"],
    "blanch": ["parboil"],
    "bland": ["flat", "flavorless", "flavourless", "insipid", "savorless", "savourless", "vapid"],
    "bland diet": ["ulcer diet"],
    "blandfordia": ["genus blandfordia"],
    "blandishment": ["cajolery", "palaver"],
    "blandness": ["insipidity", "insipidness"],
    "blank": ["blank shell", "dummy"],
    "blank check": ["blank cheque"],
    "blank endorsement": ["endorsement in blank"],
    "blanket": ["mantle"],
    "blanket flower": ["fire wheel", "fire-wheel", "gaillardia pulchella", "indian blanket"],
    "blanquillo": ["tilefish"],
    "blare": ["blaring", "cacophony", "clamor", "din"],
    "blare out": ["blat out"],
    "blarina": ["genus blarina"],
    "blaring": ["blasting"],
    "blarney": ["coaxing", "soft soap", "sweet talk"],
    "blase": ["worldly"],
    "blasphemous": ["profane", "sacrilegious"],
    "blast": ["blare"],
    "blasted": ["blame", "blamed", "blessed", "damn", "damned", "darned", "deuced", "goddam", "goddamn", "goddamned", "infernal"],
    "blastemal": ["blastematic", "blastemic"],
    "blaster": ["chargeman"],
    "blasting": ["ruinous"],
    "blastocladia": ["genus blastocladia"],
    "blastocladiales": ["order blastocladiales"],
    "blastocoel": ["blastocele", "blastocoele", "cleavage cavity", "segmentation cavity"],
    "blastocyst": ["blastodermic vessicle"],
    "blastoderm": ["blastodisc", "germinal area", "germinal disc"],
    "blastodermatic": ["blastodermic"],
    "blastodiaceae": ["family blastodiaceae"],
    "blastoff": ["shot"],
    "blastoma": ["blastocytoma", "embryonal carcinosarcoma"],
    "blastomyces": ["genus blastomyces"],
    "blastoporal": ["blastoporic"],
    "blastospheric": ["blastular"],
    "blastula": ["blastosphere"],
    "blatant": ["blazing", "conspicuous"],
    "blather": ["blatherskite"],
    "blatta": ["genus blatta"],
    "blattella": ["genus blattella"],
    "blattidae": ["family blattidae"],
    "blattodea": ["blattaria", "suborder blattaria", "suborder blattodea"],
    "blaze": ["blaze out"],
    "blaze away": ["blaze"],
    "blazer": ["sport coat", "sport jacket", "sports coat", "sports jacket"],
    "blazing": ["blinding", "dazzling", "fulgent", "glaring", "glary"],
    "blazing star": ["mentzelia laevicaulis", "mentzelia livicaulis"],
    "bleach": ["bleach out", "decolor", "decolorise", "decolorize", "decolour", "decolourise", "decolourize", "discolorise", "discolorize", "discolourise"],
    "bleached": ["colored", "coloured", "dyed"],
    "bleaching agent": ["blanching agent", "bleach", "whitener"],
    "bleaching clay": ["bleaching earth"],
    "bleaching powder": ["chloride of lime", "chlorinated lime"],
    "bleak": ["cutting", "raw"],
    "bleakness": ["bareness", "desolation", "nakedness"],
    "bleary": ["blear", "blear-eyed", "bleary-eyed"],
    "bleat": ["baa", "blat", "blate"],
    "blebbed": ["blebby"],
    "blebby": ["blistery"],
    "blechnaceae": ["family blechnaceae"],
    "blechnum": ["genus blechnum"],
    "bleed": ["leech", "phlebotomise", "phlebotomize"],
    "bleeding": ["haemorrhage", "hemorrhage"],
    "bleeding heart": ["dicentra spectabilis", "lyre-flower", "lyreflower"],
    "bleeding tooth": ["nerita peloronta"],
    "blemish": ["spot"],
    "blemished": ["flawed"],
    "blend": ["blend in", "go"],
    "blend in": ["mix in"],
    "blended whiskey": ["blended whisky"],
    "blender": ["liquidiser", "liquidizer"],
    "blenniidae": ["family blenniidae"],
    "blennioid fish": ["blennioid"],
    "blennioidea": ["suborder blennioidea"],
    "blennius": ["genus blennius"],
    "blenny": ["combtooth blenny"],
    "blephilia": ["genus blephilia"],
    "bleriot": ["louis bleriot"],
    "bless": ["sign"],
    "blessed": ["blest"],
    "blessed event": ["happy event"],
    "blessed thistle": ["cnicus benedictus", "sweet sultan"],
    "blessedness": ["beatification", "beatitude"],
    "blessing": ["boon"],
    "bletilla": ["genus bletilla"],
    "bletilla striata": ["bletia striata"],
    "bleu": ["blue cheese"],
    "bleu cheese dressing": ["blue cheese dressing"],
    "blewits": ["clitocybe nuda"],
    "bligh": ["captain bligh", "william bligh"],
    "blighia": ["genus blighia"],
    "blight": ["plague"],
    "blighted": ["spoilt"],
    "blimp": ["sausage", "sausage balloon"],
    "blind": ["dim"],
    "blind alley": ["cul de sac", "dead-end street", "impasse"],
    "blind curve": ["blind bend"],
    "blind flying": ["blind landing"],
    "blind snake": ["worm snake"],
    "blind spot": ["optic disc", "optic disk"],
    "blindfold": ["blindfolded"],
    "blindman's bluff": ["blindman's buff"],
    "blindness": ["cecity", "sightlessness"],
    "blindworm": ["anguis fragilis", "slowworm"],
    "bling": ["bling bling"],
    "blini": ["bliny"],
    "blink": ["nictate", "nictitate", "wink"],
    "blink of an eye": ["flash", "heartbeat", "instant", "jiffy", "new york minute", "split second", "trice", "twinkling", "wink"],
    "blinker": ["trafficator", "turn indicator", "turn signal"],
    "blinking": ["winking"],
    "blinks": ["blinking chickweed", "montia lamprosperma", "water chickweed"],
    "blintz": ["blintze"],
    "blip": ["pip", "radar target"],
    "bliss": ["blissfulness", "cloud nine", "seventh heaven", "walking on air"],
    "blissus": ["genus blissus"],
    "blister": ["scald", "whip"],
    "blister beetle": ["meloid"],
    "blister pack": ["bubble pack"],
    "blister rust": ["white pine blister rust", "white-pine rust"],
    "blistering": ["blistery"],
    "blithe": ["blithesome", "light-hearted", "lighthearted", "lightsome"],
    "blitz": ["blitzkrieg"],
    "blitzstein": ["marc blitzstein"],
    "blizzard": ["snowstorm"],
    "bloc": ["axis"],
    "bloch": ["ernest bloch"],
    "block": ["cube"],
    "block letter": ["block capital"],
    "blockade": ["block off"],
    "blockage": ["block", "closure", "occlusion", "stop", "stoppage"],
    "blockbuster": ["megahit", "smash hit"],
    "blocked": ["out of use"],
    "blocker": ["blocking agent"],
    "blockheaded": ["boneheaded", "duncical", "duncish", "fatheaded", "loggerheaded", "thick", "thick-skulled", "thickheaded", "wooden-headed"],
    "blocking": ["block"],
    "blockish": ["blocky"],
    "blok": ["aleksandr aleksandrovich blok", "alexander alexandrovich blok"],
    "blolly": ["chiococca alba", "west indian snowberry"],
    "blond": ["blonde"]
}
