synonyms = {
    "bombus": ["genus bombus"],
    "bombycid": ["bombycid moth", "silkworm moth"],
    "bombycidae": ["family bombycidae"],
    "bombycilla": ["genus bombycilla"],
    "bombycillidae": ["family bombycillidae"],
    "bombyliidae": ["family bombyliidae"],
    "bombyx": ["genus bombyx"],
    "bon mot": ["mot"],
    "bonasa": ["genus bonasa"],
    "bond": ["bring together", "draw together"],
    "bondage": ["slavery", "thraldom", "thrall", "thralldom"],
    "bonderize": ["bonderise"],
    "bonding": ["soldering"],
    "bondman": ["bondsman"],
    "bondsman": ["bondswoman"],
    "bonduc": ["bonduc tree", "caesalpinia bonduc", "caesalpinia bonducella"],
    "bonduc nut": ["nicker nut", "nicker seed"],
    "bondwoman": ["bondmaid", "bondswoman"],
    "bone": ["debone"],
    "bone black": ["animal black", "animal charcoal", "bone char"],
    "boned": ["deboned"],
    "bonefish": ["albula vulpes"],
    "bones": ["castanets", "clappers", "finger cymbals"],
    "boneset": ["agueweed", "eupatorium perfoliatum", "thoroughwort"],
    "bonfire": ["balefire"],
    "bonfire night": ["guy fawkes night"],
    "bongo": ["bongo drum"],
    "bonhoeffer": ["dietrich bonhoeffer"],
    "boniface": ["apostle of germany", "saint boniface", "winfred", "wynfrith"],
    "boniface viii": ["benedetto caetani"],
    "bonito": ["katsuwonus pelamis", "oceanic bonito"],
    "bonito shark": ["blue pointed", "isurus glaucus"],
    "bonnet": ["poke bonnet"],
    "bonnet macaque": ["bonnet monkey", "capped macaque", "crown monkey", "macaca radiata"],
    "bonney": ["billie the kid"],
    "bonny": ["bonnie", "comely", "fair", "sightly"],
    "bontemps": ["arna wendell bontemps"],
    "bonus": ["incentive"],
    "bony": ["cadaverous", "emaciated", "gaunt", "haggard", "pinched", "skeletal", "wasted"],
    "bony labyrinth": ["osseous labyrinth"],
    "bonyness": ["boniness", "emaciation", "gauntness", "maceration"],
    "boo": ["hiss"],
    "boodle": ["bread", "cabbage", "clams", "dinero", "dough", "gelt", "kale", "lettuce", "lolly", "loot", "lucre", "moolah", "pelf", "scratch", "shekels", "simoleons", "sugar", "wampum"],
    "boojum tree": ["cirio", "fouquieria columnaris", "idria columnaris"],
    "book": ["rule book"],
    "book fair": ["bookfair"],
    "book jacket": ["dust cover", "dust jacket", "dust wrapper"],
    "book scorpion": ["chelifer cancroides"],
    "bookdealer": ["book seller"],
    "booked": ["engaged"],
    "booker": ["booking agent"],
    "booking": ["reservation"],
    "bookish": ["studious"],
    "bookkeeping": ["clerking"],
    "booklet": ["brochure", "folder", "leaflet", "pamphlet"],
    "booklouse": ["book louse", "deathwatch", "liposcelis divinatorius"],
    "bookmaker": ["bookie"],
    "bookmark": ["bookmarker"],
    "bookplate": ["ex libris"],
    "bookshop": ["bookstall", "bookstore"],
    "boole": ["george boole"],
    "boolean logic": ["boolean algebra"],
    "boolean operation": ["binary arithmetic operation", "binary operation"],
    "boom": ["din"],
    "boomerang": ["throw stick", "throwing stick"],
    "booming": ["flourishing", "palmy", "prospering", "prosperous", "roaring", "thriving"],
    "boone": ["daniel boone"],
    "boorish": ["loutish", "neandertal", "neanderthal", "oafish", "swinish"],
    "boorishness": ["uncouthness"],
    "boost": ["advance", "supercharge"],
    "booster": ["lifter", "shoplifter"],
    "boot": ["bring up", "reboot"],
    "bootblack": ["shoeblack"],
    "bootee": ["bootie"],
    "booth": ["john wilkes booth"],
    "bootleg": ["black", "contraband", "smuggled"],
    "bootlegger": ["moonshiner"],
    "bootless": ["fruitless", "futile", "sleeveless", "vain"],
    "bootlicking": ["fawning", "obsequious", "sycophantic", "toadyish"],
    "bootmaker": ["boot maker"],
    "bop": ["bebop"],
    "borage": ["borago officinalis", "tailwort"],
    "boraginaceae": ["borage family", "family boraginaceae"],
    "borago": ["genus borago"],
    "borassus": ["genus borassus"],
    "bordeaux": ["bordeaux wine"],
    "border": ["edge"],
    "border on": ["approach"],
    "borderland": ["border district", "march", "marchland"],
    "borderline": ["marginal"],
    "borderline schizophrenia": ["latent schizophrenia"],
    "bore": ["tire"],
    "bore bit": ["borer", "rock drill", "stone drill"],
    "boreal": ["circumboreal"],
    "boredom": ["ennui", "tedium"],
    "borges": ["jorge borges", "jorge luis borges"],
    "borgia": ["duchess of ferrara", "lucrezia borgia"],
    "boric": ["boracic"],
    "boric acid": ["orthoboric acid"],
    "boring": ["drilling", "oil production"],
    "boringly": ["tediously", "tiresomely"],
    "boringness": ["dreariness", "insipidity", "insipidness"],
    "born": ["max born"],
    "borneo": ["kalimantan"],
    "bornite": ["peacock ore"],
    "borodin": ["aleksandr borodin", "aleksandr porfirevich borodin"],
    "borrelia burgdorferi": ["lime disease spirochete"],
    "borrowing": ["adoption"],
    "borsch": ["borscht", "borsh", "borshch", "borsht", "bortsch"],
    "borscht circuit": ["borscht belt", "borsht belt", "borsht circuit"],
    "borzoi": ["russian wolfhound"],
    "bos": ["genus bos"],
    "bosch": ["hieronymus bosch", "jerom bos"],
    "bose": ["satyendra nath bose"],
    "boselaphus": ["genus boselaphus"],
    "bosky": ["brushy"],
    "bosnia and herzegovina": ["bosna i hercegovina", "bosnia", "republic of bosnia and herzegovina"],
    "bosomy": ["busty", "buxom", "curvaceous", "curvy", "sonsie", "sonsy", "stacked", "voluptuous"],
    "boss": ["hirer"],
    "boston": ["bean town", "beantown", "capital of massachusetts", "hub of the universe"],
    "boston bull": ["boston terrier"],
    "boston fern": ["nephrolepis exaltata", "nephrolepis exaltata bostoniensis"],
    "boston ivy": ["japanese ivy", "parthenocissus tricuspidata"],
    "boswell": ["james boswell"],
    "boswellia": ["genus boswellia"],
    "botanic": ["botanical"],
    "botanist": ["phytologist", "plant scientist"],
    "botanize": ["botanise"],
    "botany": ["phytology"],
    "botaurus": ["genus botaurus"],
    "botch": ["ball up", "blow", "bobble", "bodge", "bollix", "bollix up", "bollocks", "bollocks up", "botch up", "bumble", "bungle", "flub", "fluff", "foul up", "fuck up", "fumble", "louse up", "mess up", "mishandle", "muck up", "muff", "screw up", "spoil"],
    "botchy": ["butcherly", "unskillful"],
    "bothered": ["daunted", "fazed"],
    "bothidae": ["family bothidae"],
    "bothrops": ["genus bothrops"],
    "botonee": ["botonnee"],
    "botrychium": ["genus botrychium"],
    "botryoid": ["botryoidal", "boytrose"],
    "botswana": ["republic of botswana"],
    "botticelli": ["alessandro di mariano dei filipepi", "sandro botticelli"],
    "bottle": ["bottleful"],
    "bottle gourd": ["calabash", "lagenaria siceraria"],
    "bottlenose dolphin": ["bottlenose"],
    "bottom": ["bottom of the inning"],
    "bottom quark": ["beauty quark"],
    "bottom rot fungus": ["corticium solani"],
    "bottomland": ["bottom"],
    "bottommost": ["lowermost", "nethermost"],
    "botulin": ["botulinus toxin", "botulismotoxin"],
    "botulinum toxin a": ["botox"],
    "botulinus": ["botulinum", "clostridium botulinum"],
    "bouffant": ["puffy"],
    "bougainville": ["louis antoine de bougainville"],
    "boulder": ["bowlder"],
    "boulez": ["pierre boulez"],
    "boulle": ["boule", "buhl"],
    "bounce": ["jounce"],
    "bouncing": ["bouncy", "peppy", "spirited", "zippy"],
    "bouncy": ["live", "lively", "resilient", "springy"],
    "bound": ["border"],
    "bound morpheme": ["bound form"],
    "bound up": ["wrapped up"],
    "boundary": ["bound", "edge"],
    "boundary line": ["border", "borderline", "delimitation", "mete"],
    "bounded": ["delimited"],
    "bounder": ["leaper"],
    "boundless": ["limitless", "unbounded"],
    "boundlessly": ["immeasurably", "infinitely"],
    "bountiful": ["plentiful"],
    "bountifully": ["bounteously", "plenteously", "plentifully"],
    "bounty": ["premium"],
    "bouquet": ["fragrance", "fragrancy", "redolence", "sweetness"],
    "bourbon": ["bourbon dynasty"],
    "bourgeois": ["burgher"],
    "bourgogne": ["burgundy"],
    "bourguignon": ["bourguignon sauce", "burgundy sauce"],
    "bourn": ["bourne"],
    "bourtree": ["black elder", "common elder", "elderberry", "european elder", "sambucus nigra"],
    "bouteloua": ["genus bouteloua"],
    "boutique": ["dress shop"],
    "bouvier des flandres": ["bouviers des flandres"],
    "bouyei": ["buyi"],
    "bovidae": ["family bovidae"],
    "bovinae": ["subfamily bovinae"],
    "bovine": ["bovid"],
    "bovine spongiform encephalitis": ["bse", "mad cow disease"],
    "bovini": ["tribe bovini"],
    "bow": ["bow down"],
    "bow leg": ["bandy legs", "bow legs"],
    "bow out": ["withdraw"],
    "bow tie": ["bowtie"],
    "bowditch": ["nathaniel bowditch"],
    "bowdler": ["thomas bowdler"],
    "bowdlerization": ["bowdlerisation"],
    "bowdlerize": ["bowdlerise", "castrate", "expurgate", "shorten"],
    "bowed": ["bowing"],
    "bowed down": ["loaded down", "overburdened", "weighed down"],
    "bowed stringed instrument": ["string"],
    "bowel movement": ["bm", "movement"],
    "bower actinidia": ["actinidia arguta", "tara vine"],
    "bowerbird": ["catbird"],
    "bowfin": ["amia calva", "dogfish", "grindle"],
    "bowhead": ["balaena mysticetus", "bowhead whale", "greenland whale"],
    "bowie": ["james bowie", "jim bowie"],
    "bowiea": ["genus bowiea"],
    "bowl": ["trough"],
    "bowleg": ["bandy leg", "bandyleg", "bow leg", "genu varum", "tibia vara"],
    "bowler hat": ["bowler", "derby", "derby hat", "plug hat"],
    "bowline": ["bowline knot"],
    "bowling alley": ["alley", "skittle alley"],
    "bowling ball": ["bowl"],
    "bowling pin": ["pin"],
    "bowse": ["bouse"],
    "box": ["package"],
    "box beam": ["box girder"],
    "box camera": ["box kodak"],
    "box elder": ["acer negundo"],
    "box huckleberry": ["gaylussacia brachycera"],
    "box in": ["box up"],
    "box office": ["ticket booth", "ticket office"],
    "box turtle": ["box tortoise"],
    "box wrench": ["box end wrench"],
    "boxed": ["boxed in"],
    "boxer": ["pugilist"],
    "boxfish": ["trunkfish"],
    "boxing": ["fisticuffs", "pugilism"],
    "boxing glove": ["glove"],
    "boxing ring": ["prize ring"],
    "boxlike": ["boxy"],
    "boxwood": ["turkish boxwood"],
    "boyfriend": ["beau", "fellow", "swain", "young man"],
    "boyish": ["boylike", "schoolboyish"],
    "boyishly": ["boylike"],
    "boykinia": ["genus boykinia"],
    "boyle": ["kay boyle"],
    "boyne": ["battle of boyne"],
    "boysenberry": ["boysenberry bush"],
    "brace": ["poise"],
    "braced": ["buttressed"],
    "bracelet": ["bangle"],
    "bracelet wood": ["jacquinia armillaris"],
    "bracer": ["armguard"],
    "brachial artery": ["arteria brachialis"],
    "brachial plexus": ["plexus brachialis"],
    "brachial vein": ["vena brachialis"],
    "brachinus": ["genus brachinus"],
    "brachiocephalic vein": ["innominate vein", "vena brachiocephalica"],
    "brachiopod": ["lamp shell", "lampshell"],
    "brachiopoda": ["phylum brachiopoda"],
    "brachycephalic": ["brachycranial", "brachycranic"],
    "brachycephaly": ["brachycephalism"],
    "brachychiton": ["genus brachychiton"],
    "brachycome": ["genus brachycome"],
    "brachydactylic": ["brachydactylous"],
    "brachydactyly": ["brachydactylia"],
    "brachystegia": ["genus brachystegia"],
    "brachyura": ["suborder brachyura"],
    "bracing": ["brisk", "fresh", "refreshful", "refreshing", "tonic"],
    "bracken": ["pteridium esculentum"],
    "bracket": ["bracket out"],
    "bracket fungus": ["shelf fungus"],
    "brackish": ["briny"],
    "bracteate": ["bracted"],
    "bracteole": ["bractlet"],
    "bradawl": ["pricker"],
    "bradbury": ["ray bradbury", "ray douglas bradbury"],
    "bradford": ["william bradford"],
    "bradley": ["thomas bradley", "tom bradley"],
    "bradley method of childbirth": ["bradley method"],
    "bradstreet": ["anne bradstreet", "anne dudley bradstreet"],
    "brady": ["diamond jim", "diamond jim brady", "james buchanan brady"],
    "bradypodidae": ["family bradypodidae"],
    "bradypus": ["genus bradypus"],
    "brag": ["bragging", "crow", "crowing", "gasconade", "vaporing"],
    "bragg": ["braxton bragg"],
    "braggadocio": ["bluster", "rhodomontade", "rodomontade"],
    "bragger": ["blowhard", "boaster", "braggart", "vaunter"],
    "bragi": ["brage"],
    "brahe": ["tycho brahe"],
    "brahman": ["brahmin"],
    "brahmanism": ["brahminism"],
    "brahmaputra": ["brahmaputra river"],
    "brahminic": ["brahminical"],
    "brahms": ["johannes brahms"],
    "braid": ["lace", "plait"],
    "braille": ["louis braille"],
    "brain": ["brainpower", "learning ability", "mental capacity", "mentality", "wit"],
    "brain death": ["cerebral death"],
    "brain disorder": ["brain disease", "encephalopathy"],
    "brain tumor": ["brain tumour"],
    "brainless": ["headless"],
    "brainsick": ["crazy", "demented", "disturbed", "mad", "sick", "unbalanced", "unhinged"],
    "brainstem": ["brain stem"],
    "brainwave": ["brain wave", "cortical potential"],
    "brainy": ["brilliant", "smart as a whip"],
    "brake cylinder": ["hydraulic brake cylinder", "master cylinder"],
    "brake drum": ["drum"],
    "brake shoe": ["shoe", "skid"],
    "brake system": ["brakes"],
    "braky": ["brambly"],
    "brama": ["genus brama"],
    "bramante": ["donato bramante"],
    "brambling": ["fringilla montifringilla"],
    "bramidae": ["family bramidae"],
    "branch": ["fork", "furcate", "ramify", "separate"],
    "branch line": ["spur", "spur track"],
    "branched": ["branching", "ramate", "ramose", "ramous"],
    "branchiate": ["gilled"],
    "branching": ["fork", "forking", "ramification"],
    "branchiobdella": ["genus branchiobdella"],
    "branchiobdellidae": ["family branchiobdellidae"],
    "branchiopod": ["branchiopodan", "branchiopodous"],
    "branchiopod crustacean": ["branchiopod", "branchiopodan"],
    "branchiopoda": ["subclass branchiopoda"],
    "branchiostegidae": ["family branchiostegidae"],
    "branchiura": ["order branchiura"],
    "branchlet": ["sprig", "twig"],
    "brancusi": ["constantin brancusi"],
    "brand": ["brandmark", "trademark"],
    "brandish": ["flourish", "wave"],
    "brandt": ["willy brandt"],
    "brant": ["brant goose", "brent", "brent goose"],
    "branta": ["genus branta"],
    "braque": ["georges braque"],
    "brasenia": ["genus brasenia"],
    "brash": ["cheeky", "nervy"],
    "brasilia": ["brazilian capital", "capital of brazil"],
    "brass": ["memorial tablet", "plaque"],
    "brass buttons": ["cotula coronopifolia"],
    "brass knucks": ["brass knuckles", "knuckle duster", "knuckles", "knucks"],
    "brass section": ["brass"],
    "brassia": ["genus brassia"],
    "brassica": ["genus brassica"],
    "brassiere": ["bandeau", "bra"],
    "brassy": ["brasslike"],
    "bratislava": ["capital of slovakia", "pozsony", "pressburg"],
    "bratty": ["brattish"],
    "bratwurst": ["brat"],
    "braun": ["eva braun"],
    "braunschweig": ["brunswick"],
    "bravado": ["bluster"],
    "brave": ["braw", "gay"],
    "bravely": ["courageously"],
    "brawl": ["wrangle"],
    "brawn": ["brawniness", "heftiness", "muscle", "muscularity", "sinew"],
    "brawny": ["hefty", "muscular", "powerful", "sinewy"],
    "brazier": ["brasier"],
    "brazil": ["brasil", "federative republic of brazil"],
    "brazil nut": ["bertholletia excelsa"],
    "brazilian guava": ["psidium guineense"],
    "brazilian ironwood": ["caesalpinia ferrea"],
    "brazilian pepper tree": ["schinus terebinthifolius"],
    "brazilian rosewood": ["caviuna wood", "dalbergia nigra", "jacaranda"],
    "brazilian trumpeter": ["psophia crepitans"],
    "brazilwood": ["caesalpinia echinata", "peachwood", "pernambuco wood"],
    "brazos": ["brazos river"],
    "bread": ["breadstuff", "staff of life"],
    "bread mold": ["rhizopus nigricans"],
    "breadboard": ["bread board"],
    "breadfruit": ["artocarpus altilis", "artocarpus communis", "breadfruit tree"],
    "breadline": ["bread line"],
    "breadroot": ["indian breadroot", "pomme blanche", "pomme de prairie", "psoralea esculenta"],
    "breadth": ["comprehensiveness", "largeness"],
    "breadthwise": ["breadthways", "broadwise"],
    "break": ["break away"],
    "break dance": ["break"],
    "break dancing": ["break dance"],
    "break down": ["lose it", "snap"],
    "break in": ["break"],
    "break through": ["crack"],
    "break up": ["fragment", "fragmentise", "fragmentize"],
    "breakage": ["break", "breaking"],
    "breakaway": ["breaking away"],
    "breakax": ["breakaxe", "sloanea jamaicensis"],
    "breakdown": ["equipment failure"],
    "breaker": ["ledgeman"],
    "breakfast area": ["breakfast nook"],
    "breaking off": ["abruption"],
    "breakwater": ["bulwark", "groin", "groyne", "jetty", "mole", "seawall"],
    "bream": ["freshwater bream"],
    "breast": ["white meat"],
    "breastfeed": ["give suck", "lactate", "nurse", "suck", "suckle"],
    "breastplate": ["aegis", "egis"],
    "breath": ["breather", "breathing place", "breathing space", "breathing spell", "breathing time"],
    "breathalyze": ["breathalyse"],
    "breathalyzer": ["breathalyser"],
    "breathe": ["respire", "suspire", "take a breath"],
    "breathed": ["voiceless"],
    "breathing": ["external respiration", "respiration", "ventilation"],
    "breathing device": ["breathing apparatus", "breathing machine", "ventilator"],
    "breathing room": ["breathing space"],
    "breathless": ["breathtaking"],
    "brecht": ["bertolt brecht"],
    "breech": ["rear of barrel", "rear of tube"],
    "breech delivery": ["breech birth", "breech presentation"],
    "breechblock": ["breech closer"],
    "breechcloth": ["breechclout", "loincloth"],
    "breeched": ["pantalooned", "trousered"],
    "breeches": ["knee breeches", "knee pants", "knickerbockers", "knickers"],
    "breed": ["cover"],
    "breeder": ["stock breeder"],
    "breeding": ["genteelness", "gentility"],
    "breeze": ["air", "gentle wind", "zephyr"],
    "breeze through": ["ace", "nail", "pass with flying colors", "sail through", "sweep through"],
    "breeziness": ["windiness"],
    "bren": ["bren gun"],
    "bretagne": ["breiz", "brittany"],
    "breuer": ["marcel lajos breuer"],
    "brevity": ["briefness", "transience"],
    "brevoortia": ["genus brevoortia"],
    "brew": ["brewage"],
    "brewer": ["beer maker"],
    "brezhnev": ["leonid brezhnev", "leonid ilyich brezhnev"],
    "briar": ["briar pipe"],
    "briarwood": ["brierwood"],
    "bribe": ["buy", "corrupt"],
    "briber": ["suborner"],
    "bribery": ["graft"],
    "brick in": ["brick over", "brick up"],
    "brickellia": ["genus brickelia"],
    "brickyard": ["brickfield"],
    "bridal": ["espousal"],
    "bridal gown": ["wedding dress", "wedding gown"],
    "bridal wreath": ["francoa ramosa"],
    "bridesmaid": ["maid of honor"],
    "bridge": ["bridge over"],
    "bridge player": ["hand"],
    "bridgehead": ["foothold"],
    "bridges": ["harry bridges"],
    "bridget": ["bride", "brigid", "saint bride", "saint bridget", "saint brigid"],
    "bridgetown": ["capital of barbados"],
    "bridle": ["check", "curb"],
    "bridle path": ["bridle road"],
    "brief": ["legal brief"],
    "briefs": ["jockey shorts"],
    "brier": ["brier patch", "brierpatch"],
    "brigadier": ["brigadier general"],
    "brigantine": ["hermaphrodite brig"],
    "bright": ["brilliant"],
    "brighten": ["lighten", "lighten up"],
    "brightness": ["cleverness", "smartness"],
    "brill": ["scophthalmus rhombus"],
    "brilliance": ["genius"],
    "brilliant": ["superb"],
    "brilliantly": ["bright", "brightly"],
    "brim": ["lip", "rim"],
    "brimful": ["brimfull", "brimming"],
    "brimstone": ["native sulfur", "native sulphur"],
    "brindled": ["brinded", "brindle", "tabby"],
    "brine shrimp": ["artemia salina"],
    "bring": ["convey", "take"],
    "bring around": ["cure", "heal"],
    "bring in": ["introduce"],
    "bring out": ["let out"],
    "bring round": ["bring around"],
    "bring to": ["bring around", "bring back", "bring round"],
    "brininess": ["salinity"],
    "brink": ["threshold", "verge"],
    "brinton": ["daniel garrison brinton"],
    "briquette": ["briquet"],
    "brisk": ["brisk up", "brisken"],
    "brisling": ["clupea sprattus", "sprat"],
    "bristle": ["stand up", "uprise"],
    "bristle at": ["bridle at", "bridle up", "bristle up"],
    "bristle fern": ["filmy fern"],
    "bristlecone pine": ["pinus aristata", "rocky mountain bristlecone pine"],
    "bristlegrass": ["bristle grass"],
    "bristly": ["prickly", "splenetic", "waspish"],
    "bristly locust": ["moss locust", "robinia hispida", "rose acacia"],
    "bristly sarsaparilla": ["aralia hispida", "bristly sarsparilla", "dwarf elder"],
    "brit": ["britt"],
    "british": ["british people", "brits"],
    "british capacity unit": ["imperial capacity unit"],
    "british commonwealth": ["commonwealth of nations"],
    "british imperial system": ["british system", "english system"],
    "british labour party": ["labor", "labour", "labour party"],
    "british pound": ["british pound sterling", "pound", "pound sterling", "quid"],
    "british shilling": ["bob", "shilling"],
    "british thermal unit": ["btu"],
    "britisher": ["brit", "briton"],
    "britten": ["benjamin britten", "edward benjamin britten", "lord britten of aldeburgh"],
    "brittle": ["toffee", "toffy"],
    "brittle bladder fern": ["brittle fern", "cystopteris fragilis", "fragile fern"],
    "brittle maidenhair": ["adiantum tenerum", "brittle maidenhair fern"],
    "brittle star": ["serpent star"],
    "brittlebush": ["brittle bush", "encelia farinosa", "incienso"],
    "brittleness": ["crispiness", "crispness"],
    "brno": ["brunn"],
    "broach": ["initiate"],
    "broad": ["spacious", "wide"],
    "broad bean": ["fava bean", "horsebean"],
    "broad beech fern": ["dryopteris hexagonoptera", "phegopteris hexagonoptera", "southern beech fern", "thelypteris hexagonoptera"],
    "broad interpretation": ["judicial activism"],
    "broad jump": ["long jump"],
    "broadax": ["broadaxe"],
    "broadband": ["wideband"],
    "broadcast": ["program", "programme"],
    "broadcast medium": ["broadcasting"],
    "broadcaster": ["spreader"],
    "broadcasting station": ["broadcast station"]
}
