synonyms = {
    "positive correlation": ["correlation", "correlational statistics", "direct correlation"],
    "positive feedback": ["feedback", "regeneration", "vicious circle", "vicious cycle"],
    "positive identification": ["card", "charge card", "charge plate", "countersign", "credit card", "debit card", "green card", "i.d.", "id", "identification", "identification number", "identity card", "key", "number", "parole", "password", "plastic", "smart card", "watchword", "word"],
    "positive pole": ["pole", "terminal"],
    "positive reinforcing stimulus": ["positive reinforcer", "reinforcement", "reinforcer", "reinforcing stimulus"],
    "positive stimulus": ["bonus", "delight", "fillip", "input", "joy", "pleasure", "stimulant", "stimulation", "stimulus"],
    "positively": [],
    "positivism": ["comtism", "empiricism", "empiricist philosophy", "logical positivism", "sensationalism"],
    "positivist": ["logical positivist", "nonreligious person", "rationalist"],
    "positivity": ["polarity", "positiveness", "sign"],
    "positron": ["antielectron", "antilepton"],
    "positron emission tomography": ["imaging", "pet", "tomography"],
    "positron emission tomography scanner": ["pet scanner", "tomograph"],
    "posology": ["materia medica", "pharmacological medicine", "pharmacology"],
    "posse": ["constabulary", "law", "police", "police force", "posse comitatus"],
    "posseman": ["adult male", "man"],
    "possess": ["dominate"],
    "possession": ["enchantment", "spell", "trance"],
    "possessive": ["genitive"],
    "possessively": [],
    "possessiveness": ["greed"],
    "posset": ["drink"],
    "possibility": ["achievability", "attainability", "attainableness", "being", "beingness", "chance", "conceivability", "conceivableness", "existence", "opportunity", "possibleness", "potency", "potential", "potentiality"],
    "possible": ["applicant", "applier"],
    "possibly": [],
    "post": ["list"],
    "post and lintel": ["construction", "structure"],
    "post chaise": ["carriage", "equipage", "rig"],
    "post exchange": ["commissary", "px"],
    "post hoc": ["logical fallacy", "post hoc ergo propter hoc"],
    "post horn": ["wind", "wind instrument"],
    "post horse": ["equus caballus", "horse", "post-horse", "poster"],
    "post meridiem": ["p.m."],
    "post oak": ["box white oak", "brash oak", "iron oak", "oak", "oak tree", "quercus stellata"],
    "post office": ["arm", "branch", "local post office", "subdivision"],
    "post road": ["road", "route"],
    "post-communist": [],
    "post-free": ["post-paid"],
    "post-haste": [],
    "post-it": ["notepaper"],
    "post-maturity": ["matureness", "maturity", "post-menopause"],
    "post-obit bond": ["bond", "bond certificate"],
    "post-office box": ["call box", "compartment", "letter box", "po box", "pob"],
    "post-office box number": ["box number", "mailing address", "po box no", "po box number"],
    "post-rotational nystagmus": ["nystagmus"],
    "postage": ["charge"],
    "postage meter": ["meter"],
    "postal": [],
    "postal clerk": ["clerk", "mail clerk"],
    "postal rate commission": ["independent agency"],
    "postbiblical": [],
    "postbox": ["letter box", "mailbox", "maildrop", "pillar box"],
    "postcard": ["card", "lettercard", "mailing-card", "picture postcard", "post card", "postal card"],
    "postcentral gyrus": ["central gyrus"],
    "postdate": ["follow"],
    "postdiluvian": ["being", "organism"],
    "postdoc": ["bookman", "investigator", "post doc", "research worker", "researcher", "scholar", "scholarly person", "student"],
    "postdoctoral": ["grant-in-aid", "post doc", "postdoc"],
    "poste restante": ["annotation", "notation", "note"],
    "posted": [],
    "poster": ["bill", "card", "flash card", "flashcard", "notice", "placard", "posting", "show bill", "show card", "sign", "theatrical poster"],
    "poster boy": ["poster child"],
    "poster child": ["child", "fry", "kid", "minor", "nestling", "nipper", "poster boy", "poster girl", "shaver", "small fry", "tiddler", "tike", "tyke", "youngster"],
    "poster girl": ["poster child"],
    "posterior": [],
    "posterior cardinal vein": ["cardinal vein"],
    "posterior cerebral artery": ["arteria cerebri", "cerebral artery"],
    "posterior meningeal artery": ["arteria meningea", "meningeal artery"],
    "posterior naris": ["naris"],
    "posterior pituitary": ["ductless gland", "endocrine", "endocrine gland", "neurohypophysis", "pars nervosa", "posterior pituitary gland"],
    "posterior serratus muscle": ["musculus serratus posterior", "serratus", "serratus muscles", "serratus posterior", "serratus posterior inferior", "serratus posterior superior"],
    "posterior subcapsular cataract": ["cataract"],
    "posterior synechia": ["synechia"],
    "posterior temporal artery": ["arteria temporalis posterior", "temporal artery"],
    "posterior vein of the left ventricle": ["vein", "vena", "vena posterior ventriculi sinistri", "venous blood vessel"],
    "posteriority": ["position", "spatial relation"],
    "posterity": ["generation"],
    "postern": ["gate"],
    "postexilic": [],
    "postfix notation": ["parenthesis-free notation", "reverse polish notation", "suffix notation"],
    "postganglionic": [],
    "postglacial": [],
    "posthitis": ["inflammation", "redness", "rubor"],
    "posthole": ["hole", "post hole"],
    "posthole digger": ["post-hole digger", "shovel"],
    "posthouse": ["auberge", "hostel", "hostelry", "inn", "lodge", "post house"],
    "posthumous": [],
    "posthumous birth": ["birth", "nascence", "nascency", "nativity"],
    "posthumously": [],
    "posthypnotic amnesia": ["selective amnesia"],
    "posthypnotic suggestion": ["suggestion"],
    "postictal": [],
    "postilion": ["equestrian", "horseback rider", "horseman", "postillion"],
    "postimpressionist": ["painter", "post-impressionist"],
    "postindustrial": [],
    "posting": ["list", "listing"],
    "postlude": ["voluntary"],
    "postmark": ["frank", "stamp"],
    "postmaster": ["master", "postmistress"],
    "postmaster general": ["functionary", "official"],
    "postmature infant": ["neonate", "newborn", "newborn baby", "newborn infant"],
    "postmenopausal": [],
    "postmeridian": [],
    "postmillennial": [],
    "postmistress": ["postmaster"],
    "postmodernism": ["genre"],
    "postmodernist": ["postmodern"],
    "postmortem": ["discussion", "give-and-take", "post-mortem", "word"],
    "postnasal drip": ["symptom"],
    "postnatal": ["postpartum"],
    "postnuptial": [],
    "postoperative": [],
    "postoperatively": [],
    "postpaid": ["prepaid"],
    "postpone": ["call", "defer", "delay", "hold", "hold over", "probate", "prorogue", "put off", "put over", "remit", "reprieve", "respite", "set back", "shelve", "suspend", "table"],
    "postponement": ["adjournment", "deferment", "deferral", "delay", "holdup"],
    "postpose": ["lay", "place", "pose", "position", "put", "set"],
    "postposition": ["place", "position"],
    "postpositive": [],
    "postprandial": [],
    "postscript": ["annotation", "notation", "note", "ps"],
    "posttraumatic epilepsy": ["epilepsy", "traumatic epilepsy"],
    "posttraumatic stress disorder": ["anxiety disorder", "battle fatigue", "combat fatigue", "combat neurosis", "ptsd", "shell shock"],
    "postulant": ["petitioner", "requester", "suppliant", "supplicant"],
    "postulate": ["assert", "insist", "posit", "presuppose", "suppose"],
    "postulation": ["declaration", "predication"],
    "postulator": ["clergyman", "man of the cloth", "reverend"],
    "postum": ["coffee substitute"],
    "postural": [],
    "posturer": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "posturing": ["conceit", "conceitedness", "vanity"],
    "postwar": [],
    "pot": ["embed", "engraft", "imbed", "implant", "plant", "repot"],
    "pot farm": ["garden"],
    "pot metal": ["cast iron"],
    "pot plant": ["flora", "plant", "plant life"],
    "pot roast": ["bottom round", "joint", "roast"],
    "pot-au-feu": ["stew"],
    "potage": ["pottage", "soup"],
    "potamogalidae": ["family potamogalidae", "mammal family"],
    "potamogeton": ["genus potamogeton", "liliopsid genus", "monocot genus"],
    "potamogetonaceae": ["family potamogetonaceae", "liliopsid family", "monocot family", "pondweed family"],
    "potamophis": ["genus potamophis", "reptile genus"],
    "potash": ["caustic potash", "hydrated oxide", "hydroxide", "lye", "potassium hydroxide"],
    "potassium": ["atomic number 19", "k", "metal", "metallic element"],
    "potassium bicarbonate": ["bicarbonate", "hydrogen carbonate", "potassium acid carbonate", "potassium hydrogen carbonate"],
    "potassium bromide": ["restrainer", "salt"],
    "potassium carbonate": ["carbonate", "pearl ash"],
    "potassium chlorate": ["salt"],
    "potassium chloride": ["chloride", "k-dur 20", "k-lor", "k-lyte", "kaochlor", "klorvess", "potash muriate", "potassium muriate"],
    "potassium cyanide": ["cyanide"],
    "potassium dichromate": ["salt"],
    "potassium ferrocyanide": ["ferrocyanide", "yellow prussiate of potash"],
    "potassium iodide": ["iodide"],
    "potassium nitrate": ["niter", "nitrate", "nitre", "saltpeter", "saltpetre"],
    "potassium permanganate": ["permanganate", "permanganate of potash"],
    "potassium-argon dating": ["dating", "geological dating"],
    "potation": ["drinking", "imbibing", "imbibition"],
    "potato": ["solanum tuberosum", "vine", "white potato", "white potato vine"],
    "potato blight": ["blight", "potato disease", "potato mildew", "potato mold", "potato murrain"],
    "potato fern": ["fern", "marattia salicina"],
    "potato fungus": ["fungus", "pellicularia filamentosa", "rhizoctinia solani"],
    "potato mosaic": ["mosaic"],
    "potato moth": ["gelechiid", "gelechiid moth", "phthorimaea operculella", "potato tuber moth", "splitworm"],
    "potato pancake": ["battercake", "flannel cake", "flannel-cake", "flapcake", "flapjack", "griddlecake", "hot cake", "hotcake", "latke", "pancake"],
    "potato race": ["race"],
    "potato salad": ["salad"],
    "potato scab bacteria": ["streptomyces", "streptomyces scabies"],
    "potato skin": ["potato peel", "potato peelings", "snack food"],
    "potato tree": ["brazilian potato tree", "bush", "shrub", "solanum macranthum", "solanum wrightii"],
    "potato tuberworm": ["caterpillar", "phthorimaea operculella"],
    "potato vine": ["giant potato creeper", "solanum wendlandii", "vine"],
    "potato wart": ["plant disease"],
    "potato wart fungus": ["fungus", "synchytrium endobioticum"],
    "potato yellow-dwarf virus": ["plant virus"],
    "potawatomi": ["algonquian", "algonquin"],
    "potbelly": ["cooking stove", "kitchen range", "kitchen stove", "potbelly stove", "range", "stove"],
    "potboiler": ["literary composition", "literary work"],
    "potbound": ["rootbound"],
    "potboy": ["employee", "potman"],
    "poteen": ["irish", "irish whiskey", "irish whisky"],
    "potemkin": ["grigori aleksandrovich potemkin", "grigori potemkin", "grigori potyokin", "military officer", "officer", "pol", "political leader", "politician", "politico", "potyokin"],
    "potemkin village": ["fake", "postiche", "sham"],
    "potency": ["physical condition", "physiological condition", "physiological state", "potence"],
    "potent": ["powerful"],
    "potential": ["chance", "latency", "possibility", "possibleness", "potency", "potentiality", "prospect"],
    "potential divider": ["pot", "potentiometer", "resistance", "resistor", "voltage divider"],
    "potential energy": ["elastic energy", "elastic potential energy", "mechanical energy", "p.e."],
    "potential unit": ["abvolt", "electromagnetic unit", "emu", "femtovolt", "kilovolt", "kv", "microvolt", "millivolt", "mv", "nanovolt", "picovolt", "v", "volt"],
    "potentially": [],
    "potentiate": ["enhance", "heighten", "raise"],
    "potentiation": ["synergism", "synergy"],
    "potentilla": ["genus potentilla", "rosid dicot genus"],
    "potentiometer": ["measuring device", "measuring instrument", "measuring system"],
    "potently": ["powerfully"],
    "poterium": ["genus poterium", "rosid dicot genus"],
    "pothead": ["head"],
    "pother": ["agitate", "charge", "charge up", "commove", "excite", "rouse", "turn on"],
    "potherb": ["veg", "vegetable", "veggie"],
    "potholder": ["pad"],
    "pothole": ["chuckhole", "hole", "hollow"],
    "potholer": ["adventurer", "explorer", "spelaeologist", "speleologist", "spelunker"],
    "pothook": ["claw", "hook", "trammel"],
    "pothos": ["liana"],
    "pothunter": ["archaeologist", "archeologist"],
    "potion": ["beverage", "drink", "drinkable", "elixir", "love-philter", "love-philtre", "love-potion", "philter", "philtre", "potable"],
    "potlatch": ["ceremonial", "ceremonial occasion", "ceremony", "feast", "fete", "fiesta", "observance"],
    "potluck": ["meal", "repast"],
    "potomac": ["potomac river"],
    "potoroinae": ["mammal family", "subfamily potoroinae"],
    "potoroo": ["kangaroo rat", "rat kangaroo"],
    "potorous": ["genus potorous", "mammal genus"],
    "potos": ["genus potos", "mammal genus"],
    "potpie": ["dish"],
    "potpourri": ["essence", "perfume"],
    "potsdam": [],
    "potsdam conference": [],
    "potsherd": ["fragment", "shard", "sherd"],
    "potshot": ["criticism", "unfavorable judgment"],
    "pott's disease": ["t.b.", "tb", "tuberculosis"],
    "pottage": ["stew"],
    "potted": [],
    "potter": ["busy", "occupy", "putter"],
    "potter bee": ["bee"],
    "potter wasp": ["vespid", "vespid wasp"],
    "potter's clay": ["clay", "potter's earth", "slip"],
    "potter's field": ["burial ground", "burial site", "burying ground", "cemetery", "graveyard", "memorial park", "necropolis"],
    "potter's wheel": ["wheel"],
    "pottery": ["shop", "workshop"],
    "pottle": ["pot"],
    "potto": ["kinkajou", "lemur", "perodicticus potto"],
    "potty": [],
    "potty seat": ["can", "commode", "crapper", "pot", "potty", "potty chair", "stool", "throne", "toilet"],
    "potty-trained": ["pot-trained", "toilet-trained"],
    "pouch": ["bag"],
    "pouched": [],
    "pouched mole": ["marsupial", "marsupial mole", "notoryctus typhlops", "pouched mammal"],
    "pouched mouse": ["dasyurid", "dasyurid marsupial", "marsupial mouse", "marsupial rat"],
    "poulenc": ["francis poulenc"],
    "poulette": ["sauce"],
    "poultice": ["dress", "plaster"],
    "poultry": ["bird", "chicken", "dove", "duck", "fowl", "goose", "guinea hen", "poulet", "rock cornish hen", "squab", "turkey", "volaille"],
    "poultryman": ["merchandiser", "merchant", "poulterer"],
    "pounce": ["come down", "descend", "fall", "go down", "stoop", "swoop"],
    "pound": ["partition", "partition off", "pound off"],
    "pound cake": ["cake", "loaf"],
    "pound net": ["trap"],
    "pound-foolish": [],
    "poundage": ["charge"],
    "poundal": ["force unit", "pdl"],
    "pounder": ["force unit"],
    "pounding": ["blow", "buffeting", "bump"],
    "pounds per square inch": ["pressure unit", "psi"],
    "pour": ["pelt", "rain", "rain buckets", "rain cats and dogs", "rain down", "sheet", "sluice", "sluice down", "stream"],
    "pour out": ["express", "give tongue to", "utter", "verbalise", "verbalize"],
    "pousse-cafe": ["cordial", "liqueur"],
    "poussin": ["nicolas poussin"],
    "pout": ["grimace", "make a face", "mop", "mow", "pull a face"],
    "pouter pigeon": ["pigeon", "pouter"],
    "pouteria": ["dicot genus", "genus pouteria", "magnoliopsid genus"],
    "poutingly": [],
    "poverty": ["deprivation", "destitution", "financial condition", "impecuniousness", "impoverishment", "indigence", "need", "neediness", "pauperism", "pauperization", "pennilessness", "penuriousness", "penury", "poorness", "privation", "want"],
    "poverty line": ["personal income", "poverty level"],
    "poverty trap": ["position", "situation"],
    "powder": ["make up", "talc"],
    "powder and shot": ["ammo", "ammunition"],
    "powder blue": ["blue", "blueness"],
    "powder horn": ["container", "powder flask"],
    "powder keg": ["danger"],
    "powder metallurgy": ["metallurgy"],
    "powder monkey": ["assistant", "help", "helper", "supporter"],
    "powder photography": ["photography", "powder method", "powder technique"],
    "powder-post termite": ["cryptotermes brevis", "dry-wood termite"],
    "powder-puff": [],
    "powdered": ["fine-grained", "powdery", "pulverised", "pulverized", "small-grained"],
    "powdered milk": ["dried milk", "dry milk", "milk", "milk powder", "nonfat dry milk"],
    "powdered mustard": ["dry mustard", "emetic", "mustard", "nauseant", "table mustard", "vomit", "vomitive"],
    "powdered sugar": ["caster sugar", "castor sugar", "granulated sugar", "icing sugar"],
    "powderer": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "powderize": ["disintegrate", "powderise", "pulverise", "pulverize"],
    "powderpuff": ["pad", "puff"],
    "powdery": [],
    "powdery mildew": ["mildew"],
    "powell": ["colin luther powell", "colin powell"],
    "power": ["cater", "drive", "ply", "provide", "supply"],
    "power brake": ["airbrake", "brake"],
    "power breakfast": ["breakfast", "get together", "meeting"],
    "power broker": ["important person", "influential person", "personage", "powerbroker"],
    "power company": ["electric company", "light company", "power service", "public utility", "public utility company", "public-service corporation", "utility"],
    "power cord": ["cord", "electric cord"],
    "power couple": ["couple", "match", "mates"],
    "power dive": ["dive", "nose dive", "nosedive"],
    "power drill": ["drill", "electric drill", "pneumatic drill", "power tool"],
    "power hunger": ["ambition", "ambitiousness", "status seeking"],
    "power line": ["cable", "line", "power cable", "transmission line"],
    "power loading": ["loading"],
    "power loom": ["loom"],
    "power module": ["module"],
    "power mower": ["lawn mower", "motor mower", "mower", "riding mower"],
    "power of appointment": ["authorisation", "authority", "authorization", "dominance", "potency", "say-so"],
    "power of attorney": ["instrument", "legal document", "legal instrument", "official document", "proxy", "stock power"],
    "power outage": ["blackout", "breakdown", "equipment failure", "flame-out", "power failure"],
    "power pack": ["electrical converter"],
    "power play": ["attempt", "effort", "endeavor", "endeavour", "squeeze", "squeeze play", "try"],
    "power politics": ["diplomacy", "diplomatic negotiations", "gunboat diplomacy"],
    "power saw": ["band saw", "bandsaw", "buzz saw", "chain saw", "chainsaw", "circular saw", "fretsaw", "gangsaw", "jigsaw", "power tool", "reciprocating saw", "saber saw", "saw", "sawing machine", "sawmill", "scroll saw"],
    "power series": ["series"],
    "power shovel": ["backhoe", "digger", "dredge", "excavator", "machine", "shovel", "steam shovel"],
    "power station": ["power plant", "powerhouse", "station", "wind energy facility", "wind farm", "wind park"],
    "power steering": ["power-assisted steering", "steering mechanism", "steering system"],
    "power system": ["facility", "grid", "installation", "power grid"],
    "power takeoff": ["device", "pto"],
    "power tool": ["buffer", "burr", "drum sander", "electric sander", "hammer", "machine", "plane", "planer", "planing machine", "polisher", "power drill", "power hammer", "power saw", "router", "sander", "saw", "sawing machine", "smoother", "stamper", "stamping machine", "tool"],
    "power trip": ["control"],
    "power unit": ["abwatt", "electromagnetic unit", "emu", "h.p.", "horsepower", "hp", "kilovolt-ampere", "kilowatt", "kw", "megawatt", "milliwatt", "var", "volt-ampere", "w", "watt"],
    "power user": ["computer user"],
    "power walking": ["cardiopulmonary exercise"],
    "power worker": ["power-station worker", "skilled worker", "skilled workman", "trained worker"],
    "power-assisted": [],
    "power-dive": ["dive", "plunge", "plunk"],
    "power-driven": [],
    "powered": [],
    "powerful": [],
    "powerfully": ["strongly"],
    "powerhouse": ["actor", "ball of fire", "doer", "fireball", "human dynamo", "self-starter", "worker"],
    "powerless": [],
    "powerlessly": [],
    "powerlessness": ["helplessness", "impotence", "impotency", "impuissance", "ineffectiveness", "ineffectuality", "ineffectualness", "paper tiger", "quality", "uninterestingness", "unpersuasiveness", "voicelessness", "weakness"],
    "powhatan": ["wahunsonacock"],
    "powwow": ["discuss", "hash out", "talk over"],
    "powys": ["llewelyn powys"],
    "pox": ["chickenpox", "contagion", "contagious disease", "cowpox", "smallpox", "vaccinia", "varicella", "variola", "variola major"],
    "poxvirus": ["animal virus", "myxoma virus", "smallpox virus", "variola virus"],
    "poyang": [],
    "practicability": ["feasibility", "feasibleness", "practicableness", "usefulness", "utility"],
    "practicably": ["feasibly"],
    "practical": [],
    "practical joke": ["antic", "april fool", "caper", "hotfoot", "joke", "prank", "put-on", "rag", "snipe hunt", "trick"],
    "practicality": ["functionality", "pragmatism", "realism", "sensibleness", "usefulness", "utility", "viability"],
    "practically": [],
    "practice": ["do", "exercise", "practise", "shamanise", "shamanize"],
    "practice range": ["driving range", "firing range", "golf range", "range", "target range"],
    "practiced": ["practised"],
    "practitioner": ["clinician", "gongorist", "homeopath", "homoeopath", "practician", "professional", "professional person"],
    "praenomen": ["first name", "forename", "given name"],
    "praetor": ["judge", "jurist", "justice", "pretor"],
    "praetorian": ["praetorial", "pretorial", "pretorian"],
    "praetorian guard": ["bodyguard", "escort", "praetorian"],
    "praetorium": ["collapsible shelter", "pretorium", "tent"],
    "praetorship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "pragmatic": ["pragmatical"],
    "pragmatic sanction": ["imperial decree", "pragmatic"],
    "pragmatically": [],
    "pragmatics": ["linguistics"],
    "pragmatism": ["instrumentalism", "philosophical doctrine", "philosophical theory"],
    "pragmatist": ["realist"],
    "prague": ["czech capital", "prag", "praha"],
    "praia": ["capital of cape verde", "cidade de praia"],
    "prairia sabbatia": ["sabbatia", "sabbatia campestris", "texas star"],
    "prairial": ["revolutionary calendar month"],
    "prairie": ["grassland"],
    "prairie aster": ["aster", "aster turbinellis"],
    "prairie bird's-foot trefoil": ["compass plant", "lotus americanus", "prairie lotus", "prairie trefoil", "subshrub", "suffrutex"],
    "prairie chicken": ["greater prairie chicken", "grouse", "heath hen", "lesser prairie chicken", "prairie fowl", "prairie grouse", "tympanuchus cupido", "tympanuchus cupido cupido", "tympanuchus pallidicinctus"],
    "prairie coneflower": ["coneflower", "ratibida tagetes"],
    "prairie cordgrass": ["cord grass", "cordgrass", "freshwater cordgrass", "slough grass", "spartina pectinmata"],
    "prairie dog": ["blacktail prairie dog", "cynomys gunnisoni", "cynomys ludovicianus", "gnawer", "prairie marmot", "rodent", "whitetail prairie dog"],
    "prairie gentian": ["bluebell", "eustoma grandiflorum", "tulip gentian", "wild flower", "wildflower"],
    "prairie gourd": ["fruit"],
    "prairie mallow": ["false mallow", "globe mallow", "malvastrum coccineum", "red false mallow", "sphaeralcea coccinea"],
    "prairie mimosa": ["desmanthus ilinoensis", "herb", "herbaceous plant", "prickle-weed"],
    "prairie orchid": ["fringed orchid", "fringed orchis", "habenaria leucophaea", "prairie white-fringed orchis"],
    "prairie rattlesnake": ["crotalus viridis", "prairie rattler", "rattler", "rattlesnake", "western rattlesnake"],
    "prairie rocket": ["flower"],
    "prairie smoke": ["avens", "geum triflorum", "purple avens"],
    "prairie soil": ["dirt", "soil"],
    "prairie star": ["lithophragma parviflorum", "wild flower", "wildflower"],
    "prairie sunflower": ["helianthus", "helianthus petiolaris", "sunflower"],
    "prairie vole": ["field mouse", "microtus ochrogaster", "vole"],
    "prairie wake-robin": ["prairie trillium", "trillium", "trillium recurvatum", "wake-robin", "wood lily"],
    "prairie white-fringed orchid": ["orchid", "orchidaceous plant", "platanthera leucophea"],
    "prairie willow": ["salix humilis", "willow", "willow tree"],
    "praise": ["advertise", "advertize", "applaud", "appraise", "assess", "blandish", "commend", "compliment", "congratulate", "eulogise", "eulogize", "evaluate", "exalt", "extol", "flatter", "glorify", "gush", "laud", "measure", "proclaim", "promote", "puff", "puff up", "push", "rave", "recommend", "salute", "sonnet", "troll", "valuate", "value"],
    "praiseworthiness": ["laudability", "laudableness", "worthiness"],
    "praisworthiness": ["worth"],
    "prajapati": [],
    "prakrit": ["indic", "indo-aryan"],
    "prakritic": [],
    "praline": ["candy", "confect"],
    "prance": ["go", "locomote", "move", "travel"],
    "prancer": ["mount", "riding horse", "saddle horse"],
    "prandial": [],
    "prang": ["crash"],
    "prank": ["adorn", "beautify", "decorate", "embellish", "grace", "ornament"],
    "prankishness": ["badness", "mischievousness", "naughtiness", "rascality", "roguishness"],
    "prankster": ["bad hat", "cut-up", "hoaxer", "mischief-maker", "practical joker", "tricker", "trickster", "trouble maker", "troublemaker", "troubler"],
    "praseodymium": ["atomic number 59", "metal", "metallic element", "pr"],
    "prate": ["blether", "cackle", "chatter", "chin music", "idle talk", "prattle", "yack", "yak", "yakety-yak"],
    "pratfall": ["fall", "spill", "tumble"],
    "pratincole": ["glareole", "limicoline bird", "shore bird", "shorebird"],
    "prattler": ["speaker", "talker", "utterer", "verbaliser", "verbalizer"],
    "praunus": ["arthropod genus", "genus praunus"],
    "pravastatin": ["lipid-lowering medication", "lipid-lowering medicine", "pravachol", "statin", "statin drug"],
    "prawn": ["fish"],
    "praxiteles": [],
    "pray": ["commune"],
    "praya": ["siphonophore"],
    "prayer": ["beadsman", "bedesman", "religious person", "supplicant"],
    "prayer book": ["book", "book of psalms", "breviary", "missal", "prayerbook", "psalter"],
    "prayer meeting": ["divine service", "prayer service", "religious service", "service"],
    "prayer of azariah and song of the three children": [],
    "prayer rug": ["carpet", "carpeting", "prayer mat", "rug"],
    "prayer shawl": ["shawl", "tallis", "tallith"],
    "prayer wheel": ["orison", "petition", "prayer"],
    "prayerful": [],
    "praying mantis": ["mantid", "mantis", "mantis religioso", "praying mantid"],
    "prazosin": ["alpha blocker", "alpha-adrenergic blocker", "alpha-adrenergic blocking agent", "alpha-blocker", "antihypertensive", "antihypertensive drug", "minipress"],
    "pre-christian": [],
    "pre-columbian": [],
    "pre-eminently": ["preeminently"],
    "pre-emptive strike": ["coup de main", "surprise attack"],
    "pre-jurassic": [],
    "pre-raphaelite": ["artist", "creative person"],
    "pre-socratic": ["philosopher"],
    "preach": ["evangelise", "evangelize", "lecture", "prophesy", "talk"],
    "preacher": ["clergyman", "evangelist", "gospeler", "gospeller", "man of the cloth", "preacher man", "reverend", "revivalist", "sermoniser", "sermonizer"],
    "preachification": ["moralisation", "moralization", "moralizing"],
    "preachy": [],
    "preakness": ["thoroughbred race"],
    "preamble": ["introduce", "precede", "preface", "premise"],
    "preanal": [],
    "prearrange": ["arrange", "set"],
    "prearrangement": ["agreement", "arrangement", "reservation"],
    "prebend": ["stipend"],
    "prebendary": ["canon"],
    "precambrian": ["precambrian aeon", "precambrian eon", "precambrian period"],
    "precancerous": [],
    "precarious": ["shaky"],
    "precariously": [],
    "precariousness": ["dangerousness"],
    "precast": [],
    "precatory": ["precative"],
    "precaution": ["caution", "circumspection"],
    "precautionary": ["precautional"],
    "precede": ["lie", "predate"],
    "precedence": ["back burner", "front burner", "high status", "precedency", "priority"],
    "precedent": ["subject", "theme", "topic"],
    "precedented": [],
    "precedentedly": [],
    "precedential": [],
    "preceding": [],
    "precentorship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "precentral gyrus": ["central gyrus"],
    "preceptor": ["don", "instructor", "teacher"],
    "preceptorship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "precess": ["go", "locomote", "move", "travel"],
    "precession": ["motion"],
    "precession of the equinoxes": ["action", "activity", "natural action", "natural process"],
    "prechlorination": ["chlorination"],
    "precinct": ["city district", "election district", "police precinct", "voting precinct"],
    "preciosity": ["affectedness", "preciousness"],
    "precious": ["preciously"],
    "precious metal": ["bullion", "gold", "silver", "valuable"],
    "precipice": ["cliff", "drop", "drop-off"],
    "precipitant": ["agent", "dimethylglyoxime"],
    "precipitate": ["come down", "fall", "hail", "rain", "rain down", "sleet", "snow", "spat"],
    "precipitating": [],
    "precipitation": ["indefinite quantity"],
    "precipitator": ["cottrell precipitator", "electrical device", "electrostatic precipitator"],
    "precipitin": ["antibody"],
    "precipitously": ["sharply"],
    "precis": ["resume", "sum up", "summarise", "summarize"],
    "precise": [],
    "precisely": ["exactly", "on the button", "on the dot", "on the nose"],
    "preciseness": ["clarity", "clearcutness", "clearness", "limpidity", "lucidity", "lucidness", "pellucidity"],
    "precision cookie": ["cookie"],
    "preclinical": ["presymptomatic"],
    "preclinical trial": ["preclinical phase", "preclinical test", "run", "test", "trial"],
    "preclude": ["close out", "eliminate", "obviate", "rid of", "rule out"],
    "preclusive": ["obviating"],
    "precocial": [],
    "precocious": [],
    "precocious dentition": ["dentition", "odontiasis", "teething"],
    "precociously": [],
    "precociousness": ["intelligence", "precocity"],
    "precognition": ["clairvoyance", "e.s.p.", "esp", "extrasensory perception", "foreknowledge", "second sight"],
    "preconceive": ["conceive", "conceptualise", "conceptualize", "gestate"],
    "preconceived": [],
    "preconception": ["opinion", "parti pris", "persuasion", "preconceived idea", "preconceived notion", "preconceived opinion", "prepossession", "sentiment", "thought", "view"],
    "preconcerted": [],
    "precondition": ["fix", "gear up", "prepare", "ready", "set", "set up"],
    "preconditioned": [],
    "precook": ["cook", "fix", "make", "prepare", "ready"],
    "precooked": [],
    "precooled": [],
    "precordial": [],
    "precordium": ["external organ"],
    "precursor": ["material", "stuff"],
    "precursory": ["premonitory"],
    "predaceous": ["predacious", "predatory"],
    "predacious": ["predaceous"],
    "predate": ["antecede", "antedate", "forego", "forgo", "precede"],
    "predation": ["hunt", "hunting"],
    "predator": ["animal", "animate being", "beast", "brute", "carnivore", "creature", "fauna", "predatory animal"],
    "predatory": ["rapacious", "raptorial", "ravening", "vulturine", "vulturous"],
    "predecease": ["buy the farm", "cash in one's chips", "choke", "conk", "croak", "decease", "die", "drop dead", "exit", "expire", "give-up the ghost", "go", "kick the bucket", "pass", "pass away", "perish", "pop off", "snuff it"],
    "predecessor": ["forefather", "forerunner", "precursor"],
    "predestinarian": [],
    "predestinarianism": ["protestantism"],
    "predestination": ["destiny", "fate"],
    "predestine": ["ordain"],
    "predetermination": ["conclusion", "decision", "determination"],
    "predetermine": ["determine", "foreordain", "influence", "mold", "predestinate", "predestine", "preordain", "regulate", "shape"],
    "predicament": ["box", "care", "corner", "difficulty", "hot water", "plight", "quandary"],
    "predicate": ["interrelate", "relate"],
    "predicate calculus": ["formal logic", "functional calculus", "mathematical logic", "symbolic logic"],
    "predicative": [],
    "predicatively": [],
    "predicator": ["construction", "expression", "grammatical construction"],
    "predict": ["anticipate", "augur", "bet", "calculate", "call", "forebode", "forecast", "foretell", "guess", "hazard", "outguess", "pretend", "prognosticate", "promise", "prophesy", "read", "second-guess", "vaticinate", "venture", "wager"],
    "predictability": ["certainty", "definiteness", "determinateness", "foregone conclusion", "sure thing"],
    "predictable": [],
    "predictably": [],
    "prediction": ["divination", "extropy", "forecast", "forecasting", "foretelling", "fortunetelling", "horoscope", "meteorology", "prognosis", "prognostication", "prophecy", "statement", "weather forecasting"],
    "predictive": ["prognostic", "prognosticative"],
    "predictor": ["information"],
    "predictor variable": ["variable", "variable quantity"],
    "predigest": ["digest"],
    "predigested": [],
    "predilection": ["orientation", "predisposition", "preference"],
    "predispose": ["dispose", "incline"],
    "predisposed": [],
    "predisposition": ["disposition", "inclination", "orientation", "predilection", "preference", "tendency"],
    "prednisolone": ["anti-inflammatory", "anti-inflammatory drug", "glucocorticoid", "pediapred", "prelone"],
    "prednisone": ["anti-inflammatory", "anti-inflammatory drug", "deltasone", "glucocorticoid", "liquid pred", "meticorten", "orasone"],
    "predominance": ["ascendance", "ascendancy", "ascendence", "ascendency", "control", "dominance", "predomination", "prepotency"],
    "predominantly": ["preponderantly"],
    "predominate": ["dominate", "outbalance", "outweigh", "overarch", "overbalance", "override", "preponderate", "prevail", "reign", "rule"],
    "predomination": ["noticeability", "noticeableness", "obviousness", "patency", "predominance"],
    "preeclampsia": ["pre-eclampsia", "toxaemia", "toxaemia of pregnancy", "toxemia", "toxemia of pregnancy"],
    "preemployment training program": ["training program"],
    "preempt": ["displace", "replace", "supercede", "supersede", "supervene upon", "supplant"],
    "preemption": ["judicial doctrine", "judicial principle", "legal principle", "pre-emption"],
    "preemptive": ["pre-emptive"],
    "preemptive bid": ["bid", "bidding", "pre-empt", "preempt"],
    "preemptive right": ["pre-emption", "preemption"],
    "preemptor": ["appropriator", "pre-emptor"],
    "preen": ["arrange", "clean", "make clean", "plume", "set up"],
    "preexist": ["be", "exist"],
    "preexistence": ["being", "beingness", "existence"],
    "preexistent": ["pre-existent", "pre-existing", "preexisting"],
    "prefab": ["construction", "structure"],
    "prefabricate": ["create", "make", "preassemble", "produce"],
    "prefabrication": ["fabrication", "manufacture", "manufacturing"],
    "prefaded": [],
    "prefect": ["administrator", "executive"],
    "prefectural": [],
    "prefecture": ["administrative district", "administrative division", "territorial division"],
    "prefer": ["pay"],
    "preferable": ["preferred"],
    "preferably": ["rather", "sooner"],
    "preference": ["acquired taste", "liking", "penchant", "predilection", "taste", "weakness"],
    "preferentially": [],
    "preferment": ["accusal", "accusation"],
    "preferred stock": ["cumulative preferred", "cumulative preferred stock", "preference shares", "preferred shares", "stock"],
    "prefiguration": ["example", "model"],
    "prefigure": ["conceive of", "envisage", "ideate", "imagine"],
    "prefix": ["affix"],
    "prefix notation": ["lukasiewicz notation", "parenthesis-free notation", "polish notation"],
    "prefixation": ["affixation"],
    "preform": ["forge", "form", "mold", "mould", "shape", "work"],
    "preformation": ["theory", "theory of preformation"],
    "prefrontal": [],
    "prefrontal lobe": ["lobe", "prefrontal cortex"],
    "pregnancy": ["eccyesis", "ectopic gestation", "ectopic pregnancy", "entopic pregnancy", "extrauterine gestation", "extrauterine pregnancy", "gestation", "gravida", "gravidation", "gravidity", "gravidness", "maternity", "metacyesis", "para", "parity", "physical condition", "physiological condition", "physiological state", "placenta previa", "trouble"],
    "pregnancy test": ["bio-assay", "bioassay", "friedman test", "rabbit test"],
    "pregnanediol": ["chemical compound", "compound"],
    "pregnant": [],
    "preheat": ["heat", "heat up"],
    "prehensile": [],
    "prehensor": ["leg"],
    "prehistoric": [],
    "prehistory": ["period", "period of time", "prehistoric culture", "time period"],
    "preisolate": ["isolate"],
    "prejudge": ["evaluate", "judge", "pass judgment"],
    "prejudgment": ["judgement", "judging", "judgment", "prejudgement"],
    "prejudice": ["disadvantage", "disfavor", "disfavour"],
    "prejudiced": [],
    "prejudicial": ["prejudicious"],
    "prelacy": ["clergy", "prelature"],
    "prelapsarian": [],
    "preliminary": ["athletic competition", "athletic contest", "athletics", "prelim"],
    "preliminary examination": ["exam", "examination", "prelim", "preliminary exam", "test"],
    "preliminary prospectus": ["course catalog", "course catalogue", "prospectus", "red herring"],
    "preliterate": [],
    "prelude": ["function", "serve"],
    "premature": [],
    "premature baby": ["neonate", "newborn", "newborn baby", "newborn infant", "preemie", "premature infant", "premie", "preterm baby", "preterm infant"],
    "premature ejaculation": ["ejaculation"],
    "premature labor": ["childbed", "confinement", "labor", "labour", "lying-in", "parturiency", "premature labour", "travail"],
    "premature ventricular contraction": ["arrhythmia", "cardiac arrhythmia", "pvc"],
    "prematurely": [],
    "prematureness": ["immatureness", "immaturity", "prematurity"],
    "premedical": [],
    "premeditate": ["consider", "debate", "deliberate", "moot", "turn over"],
    "premeditated": [],
    "premeditation": ["forethought", "planning", "preparation", "provision"],
    "premenopausal": [],
    "premenstrual": [],
    "premenstrual syndrome": ["pms", "syndrome"],
    "premier": ["premiere"],
    "premiere": ["performance", "public presentation"],
    "premiership": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "premise": ["exposit", "expound", "set forth"],
    "premises": ["land site", "site"],
    "premium": ["economic value", "value"],
    "premium bond": ["bond", "bond certificate"],
    "premolar": ["bicuspid", "tooth"],
    "prenanthes": ["asterid dicot genus", "genus prenanthes"],
    "prenatal": ["antenatal", "antepartum"],
    "prenatal diagnosis": ["amnio", "amniocentesis", "diagnostic procedure", "diagnostic technique", "echography", "fetoscopy", "foetoscopy", "sonography", "ultrasonography", "ultrasound"],
    "prenuptial": ["antenuptial", "premarital"],
    "preoccupancy": ["moving in", "occupancy", "occupation", "preoccupation"],
    "preoccupation": ["fixation", "hang-up", "hobbyhorse", "idea", "obsession", "self-absorption", "thought"],
    "preoccupy": ["arrogate", "assume", "seize", "take over", "usurp"],
    "preoperative": [],
    "prepackaged": ["prepacked"],
    "preparation": ["harmony", "musical harmony"],
    "preparation fire": ["fire", "firing"],
    "preparatory": ["preparative", "propaedeutic"],
    "preparatory school": ["choir school", "gymnasium", "lycee", "lyceum", "middle school", "prep school", "schola cantorum", "secondary school"],
    "prepare": ["dispose", "educate", "groom", "qualify", "train"],
    "prepared": [],
    "prepay": ["pay"],
    "prepayment": ["defrayal", "defrayment", "payment"],
    "preponderance": ["power", "powerfulness"],
    "preponderate": ["dominate", "outbalance", "outweigh", "overbalance", "predominate", "prevail", "reign", "rule"],
    "prepose": ["lay", "place", "pose", "position", "put", "set"],
    "preposition": ["place", "position"],
    "prepositional": [],
    "prepositional object": ["object", "object of a preposition"],
    "prepositional phrase": ["phrase"],
    "prepositionally": [],
    "prepossess": ["have", "own", "possess"],
    "prepossessing": [],
    "prepossession": ["condition", "status"],
    "preprandial": [],
    "prepuberty": ["time of life"],
    "prepubescent": ["prepubertal"],
    "prepuce": ["cutis", "foreskin", "skin", "tegument"],
    "prepupal": [],
    "prepyloric vein": ["vein", "vena", "vena pylorica", "venous blood vessel"],
    "prerecord": ["record", "tape"],
    "prerecorded": [],
    "prerequisite": ["academic requirement", "duty", "essential condition", "obligation", "precondition", "requirement", "responsibility", "sine qua non"],
    "prerogative": ["easement", "exclusive right", "perquisite", "privilege", "privilege of the floor", "right"],
    "presage": ["boding", "foreboding", "premonition", "presentiment"],
    "presbyope": ["visually impaired person"],
    "presbyopia": ["farsightedness", "hypermetropia", "hypermetropy", "hyperopia", "longsightedness"],
    "presbyter": ["elder"],
    "presbyterian": ["protestant"],
    "presbyterian church": ["protestant denomination"],
    "presbyterianism": ["protestantism"],
    "presbytery": ["building", "edifice"],
    "presbytes": ["genus presbytes", "mammal genus", "mammal semnopithecus"],
    "preschool": ["educational institution", "kindergarten", "nursery school", "play group", "playschool"],
    "preschooler": ["child", "fry", "kid", "kindergartener", "kindergartner", "minor", "nestling", "nipper", "shaver", "small fry", "tiddler", "tike", "tyke", "youngster"],
    "prescience": ["capacity", "mental ability", "prevision"],
    "prescient": [],
    "presciently": ["cannily"],
    "prescott": [],
    "prescribed": [],
    "prescription": ["direction", "instruction"],
    "prescription drug": ["ethical drug", "medicament", "medication", "medicinal drug", "medicine", "prescription", "prescription medicine", "refill"],
    "prescriptive": ["normative"],
    "prescriptive grammar": ["grammar"],
    "prescriptive linguistics": ["linguistics"],
    "prescriptivism": ["doctrine", "ism", "philosophical system", "philosophy", "school of thought"],
    "preseason": ["season", "spring training"],
    "presence": ["being", "beingness", "existence", "hereness", "immanence", "immanency", "inherence", "inherency", "occurrence", "omnipresence", "shadow", "thereness", "ubiety", "ubiquitousness", "ubiquity"],
    "presence chamber": ["room"],
    "presence of mind": ["possession", "self-command", "self-control", "self-possession", "self-will", "will power", "willpower"],
    "presenile dementia": ["alzheimer's", "alzheimer's disease", "alzheimers", "dementedness", "dementia", "pick's disease"],
    "present": ["be", "comprise", "constitute", "make up", "pose", "represent"],
    "present participle": ["participial", "participle"],
    "present perfect": ["perfect", "perfect tense", "perfective", "perfective tense", "present perfect tense"],
    "present progressive": ["continuous tense", "imperfect", "imperfect tense", "present progressive tense", "progressive", "progressive tense"],
    "presentable": [],
    "presentably": [],
    "presentation": ["debut", "informing", "intro", "introduction", "making known", "reintroduction"],
    "presentational": [],
    "presenter": ["communicator"],
    "presentism": ["doctrine", "ism", "philosophical system", "philosophy", "school of thought"],
    "presentist": ["theologian", "theologiser", "theologist", "theologizer"],
    "presently": ["currently"],
    "presentment": ["billing", "charge"],
    "presentness": ["currency", "currentness", "nowness", "timing", "up-to-dateness"],
    "preservable": [],
    "preservation": ["condition", "status"],
    "preservationist": ["crusader", "meliorist", "reformer", "reformist", "social reformer"],
    "preservative": ["chemical compound", "compound", "spice"],
    "preserve": ["hold", "keep", "maintain"],
    "preserved": [],
    "preserver": ["cook", "salter"],
    "preset": ["predetermined"],
    "preside": ["command", "control"],
    "presidency": ["administration", "incumbency", "presidential term", "tenure", "term of office"],
    "president": ["chair", "chairman", "chairperson", "chairwoman", "kalon tripa", "presiding officer", "vice chairman"],
    "president of the united states": ["chief executive", "chief of state", "head of state", "president", "united states president"],
    "presidential": [],
    "presidential directive": ["directive"],
    "presidentially": [],
    "presidents' day": ["legal holiday", "national holiday", "public holiday"],
    "presiding officer": ["chair", "chairman", "chairperson", "chairwoman", "leader", "moderator", "president", "speaker"],
    "presidio": ["fort", "fortress"],
    "presidium": ["commission", "committee", "praesidium"],
    "presley": ["elvis aron presley", "elvis presley"],
    "presocratic": ["pre-socratic"],
    "press": ["be"],
    "press agent": ["pr man", "public relations man", "publiciser", "publicist", "publicity man", "publicizer"],
    "press box": ["box"],
    "press conference": ["backgrounder", "conference", "group discussion", "news conference"],
    "press corps": ["occupational group", "vocation"],
    "press down": ["depress", "displace", "move"],
    "press gallery": ["area"],
    "press gang": ["detachment"],
    "press lord": ["newspaper publisher", "publisher"],
    "press of sail": ["canvas", "canvass", "press of canvas", "sail", "sheet"],
    "press on": ["advance", "go on", "march on", "move on", "pass on", "plough on", "progress", "push on"],
    "press out": ["acquire", "express", "extract", "get", "ream"],
    "press photographer": ["lensman", "photographer"],
    "pressed": [],
    "pressing": ["part", "portion"],
    "pressingly": [],
    "pressor": [],
    "pressure": ["distress"],
    "pressure cabin": ["cabin"],
    "pressure cooker": ["autoclave", "steriliser", "sterilizer"],
    "pressure dome": ["dome"],
    "pressure gauge": ["gage", "gauge", "manometer", "pressure gage", "sphygmomanometer"],
    "pressure point": ["point"],
    "pressure suit": ["anti-g suit", "g suit", "protective garment", "spacesuit"],
    "pressure unit": ["atm", "atmosphere", "bar", "bar absolute", "barye", "microbar", "millibar", "millimeter of mercury", "mm hg", "pa", "pascal", "pounds per square inch", "psi", "standard atmosphere", "standard pressure", "torr", "unit", "unit of measurement"],
    "pressure-cook": ["cook"],
    "pressure-wash": ["launder", "powerwash", "wash"],
    "pressurize": ["hold", "keep", "maintain", "pressurise"],
    "pressurized water reactor": ["pwr", "water-cooled reactor"],
    "prestidigitation": ["conjuration", "conjuring trick", "deception", "illusion", "legerdemain", "magic", "magic trick", "sleight of hand", "thaumaturgy", "trick"],
    "prestige": ["prestigiousness", "standing"],
    "prestigious": [],
    "prestissimo": [],
    "presto": [],
    "presumable": ["supposable", "surmisable"],
    "presumably": ["presumptively"],
    "presume": ["bear witness", "evidence", "prove", "show", "testify"],
    "presumption": ["illation", "inference"],
    "presumptive": [],
    "presumptuously": [],
    "presuppose": ["assume", "posit", "postulate", "premise", "premiss", "presume", "suppose", "take for granted"],
    "presupposition": ["supposal", "supposition"],
    "preteen": ["juvenile", "juvenile person", "preteenager"],
    "pretend": ["arrogate", "claim", "lay claim"],
    "pretender": ["claimant"],
    "pretense": ["bluff", "deceit", "deception", "dissembling", "feigning", "hypocrisy", "lip service", "misrepresentation", "pretence", "pretext", "stalking-horse"],
    "pretension": ["claim"],
    "pretentious": [],
    "pretentiously": [],
    "pretentiousness": ["largeness", "ostentation", "pretension", "unnaturalness"],
    "preterist": ["theologian", "theologiser", "theologist", "theologizer"],
    "preterit": ["past", "past tense", "preterite"],
    "pretermission": ["omission"],
    "pretermit": ["disregard", "ignore", "neglect"],
    "preternatural": ["uncanny"],
    "preternaturally": ["supernaturally"],
    "pretext": ["dissembling", "feigning", "pretence", "pretense", "putoff", "stalking-horse"],
    "pretoria": ["capital of south africa"],
    "pretrial": ["conference", "group discussion", "pretrial conference"],
    "prettily": [],
    "prettiness": ["beauty", "cuteness"],
    "pretty": [],
    "pretty much": [],
    "pretty-pretty": [],
    "pretzel": ["cracker", "soft pretzel"],
    "prevail": ["be", "exist", "hold", "obtain"],
    "prevailing": ["dominant", "predominant", "prevalent", "rife"],
    "prevailing party": ["litigant", "litigator"],
    "prevailing westerly": ["west wind", "wester", "westerly"],
    "prevailing wind": ["air current", "antitrade", "antitrade wind", "antitrades", "current of air", "trade", "trade wind", "wind"],
    "prevalence": ["ratio"],
    "prevent": ["avert", "avoid", "baffle", "bilk", "block", "blockade", "cross", "debar", "deflect", "embarrass", "fend off", "foil", "forbid", "foreclose", "forefend", "forestall", "forfend", "frustrate", "halt", "head off", "hinder", "kibosh", "make unnecessary", "obstruct", "obviate", "preclude", "queer", "save", "scotch", "spoil", "stave off", "stop", "stymie", "stymy", "thwart", "ward off"],
    "preventable": [],
    "prevention": ["averting", "bar", "crushing", "debarment", "disqualification", "forestalling", "hinderance", "hindrance", "interception", "interference", "non-proliferation", "nonproliferation", "obviation", "preclusion", "prophylaxis", "quelling", "save", "stifling", "suppression"],
    "preventive": ["curative", "cure", "preventative", "prophylactic", "remedy", "therapeutic"],
    "preventive medicine": ["medicine", "practice of medicine"],
    "preventive strike": ["preventive attack", "strike"],
    "preview": ["catch", "see", "take in", "view", "watch"],
    "previous": ["premature"],
    "previous question": ["gesture", "motion", "order", "parliamentary law", "parliamentary procedure", "rules of order"],
    "previously": ["antecedently"],
    "prevision": ["farsightedness", "foresight", "knowing", "prospicience"],
    "prewar": [],
    "prey": ["exploit", "feed", "work"],
    "priacanthidae": ["family priacanthidae", "fish family"],
    "priacanthus": ["fish genus", "genus priacanthus"],
    "priam": [],
    "priapic": [],
    "priapism": ["pathology"],
    "priapus": [],
    "price": ["determine", "manipulate", "mark up", "overprice", "rig", "set", "underquote"],
    "price bracket": ["bracket"],
    "price control": ["control"],
    "price cutting": ["cut", "price cut"],
    "price floor": ["base", "floor"],
    "price freeze": ["freeze"],
    "price gouging": ["pricing"],
    "price increase": ["increase", "increment"],
    "price index": ["consumer price index", "cost-of-living index", "cpi", "index", "index number", "indicant", "indicator", "price level", "producer price index", "retail price index", "wholesale price index"],
    "price list": ["list", "listing"],
    "price support": ["subsidy"],
    "price tag": ["tag", "ticket"],
    "price war": ["competition", "price competition"],
    "price-controlled": [],
    "price-fixing": ["control"],
    "price-to-earnings ratio": ["p/e ratio", "ratio"],
    "pricing": ["evaluation", "price gouging", "rating", "valuation"],
    "pricing system": ["system"],
    "prick": ["ache", "hurt", "prick", "prickle", "sting", "suffer", "twinge"],
    "prick up": ["cock up", "erect", "prick", "rear"],
    "pricket": ["spike"],
    "prickle": ["prick", "sting", "twinge"],
    "prickle cell": ["skin cell"],
    "prickleback": ["blennioid", "blennioid fish", "eelblenny", "lumpenus lumpretaeformis", "snakeblenny"],
    "prickliness": ["bristliness", "raggedness", "roughness", "spininess", "thorniness"],
    "prickling": ["pins and needles", "somaesthesia", "somatesthesia", "somatic sensation", "somesthesia", "tingle", "tingling"],
    "prickly ash": ["hercules'-club", "hercules'-clubs", "hercules-club", "sea ash", "toothache tree", "tree", "zanthoxylum americanum", "zanthoxylum clava-herculis", "zanthoxylum fraxineum"],
    "prickly heat": ["efflorescence", "heat rash", "miliaria", "rash", "roseola", "skin rash"],
    "prickly lettuce": ["compass flower", "compass plant", "horse thistle", "lactuca scariola", "lactuca serriola"],
    "prickly pear": ["cactus", "nopal", "opuntia lindheimeri", "opuntia tuna", "prickly pear cactus", "tuna"],
    "prickly poppy": ["argemone", "argemone mexicana", "devil's fig", "herb", "herbaceous plant", "mexican poppy", "white thistle"],
    "prickly-edged leaf": ["foliage", "leaf", "leafage"],
    "prickly-leaved": ["prickly-leafed"],
    "pride": ["congratulate", "experience", "feel", "plume"],
    "pride of barbados": ["caesalpinia pulcherrima", "flamboyant tree", "flowering shrub", "paradise flower", "poinciana pulcherrima"],
    "pride of california": ["lathyrus splendens", "wild pea"],
    "pride of place": ["place", "position"],
    "prie-dieu": ["bench"],
    "priest": ["druid", "flamen", "hoodoo", "lama", "magus", "non-christian priest", "priest-doctor", "shaman", "spiritual leader", "votary"],
    "priest-penitent privilege": ["privilege"],
    "priestcraft": ["intrigue", "machination"],
    "priestess": ["priest"],
    "priesthood": ["clergy", "ministry", "profession", "rabbinate"],
    "priestley": ["joseph priestley"],
    "priestly": ["hieratic", "hieratical", "sacerdotal"],
    "priggish": ["prim", "prissy", "prudish", "puritanical", "square-toed", "straight-laced", "straightlaced", "strait-laced", "straitlaced", "tight-laced", "victorian"],
    "priggishly": [],
    "priggishness": ["correctitude", "primness", "properness", "propriety"],
    "prim": ["change"],
    "prima": ["dessert apple", "eating apple"],
    "prima ballerina": ["ballerina", "danseuse"],
    "prima donna": ["disagreeable person", "unpleasant person"],
    "prima facie": [],
    "primacy": ["grandness", "importance"],
    "primality": ["property"],
    "primaquine": ["antimalarial", "antimalarial drug"],
    "primarily": ["in the first place"],
    "primary": ["celestial body", "heavenly body"],
    "primary amenorrhea": ["amenia", "amenorrhea", "amenorrhoea"],
    "primary care": ["medical aid", "medical care"],
    "primary care physician": ["doc", "doctor", "dr.", "md", "medico", "physician"],
    "primary censorship": ["armed forces censorship"],
    "primary coil": ["coil", "primary", "primary winding"],
    "primary color": ["color", "coloring", "colour", "colouring", "primary color for light", "primary color for pigments", "primary colour", "primary colour for light", "primary colour for pigments"],
    "primary color for light": ["primary color", "primary colour", "primary colour for light", "primary subtractive color for light", "primary subtractive colour for light"],
    "primary color for pigments": ["primary color", "primary colour", "primary colour for pigments"],
    "primary dentition": ["dentition", "teeth"],
    "primary dysmenorrhea": ["dysmenorrhea"],
    "primary health care": ["health care"],
    "primary sex characteristic": ["primary sex character", "primary sexual characteristic", "sex character", "sex characteristic", "sexual characteristic"],
    "primary subtractive color for light": ["primary color for light", "primary colour for light", "primary subtractive colour for light"],
    "primary syphilis": ["lues", "lues venerea", "pox", "syph", "syphilis"],
    "primary tooth": ["baby tooth", "deciduous tooth", "milk tooth", "tooth"],
    "primate": ["anthropoid", "ape", "eutherian", "eutherian mammal", "hominid", "hominoid", "lemur", "monkey", "placental", "placental mammal", "prosimian", "simian", "tarsier"],
    "primates": ["animal order", "order primates"],
    "primateship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "primatology": ["mammalogy"],
    "primaxin": ["antibiotic", "antibiotic drug"],
    "prime": ["ground", "paint", "undercoat"],
    "prime factor": ["divisor", "factor"],
    "prime interest rate": ["interest rate", "rate of interest"],
    "prime meridian": ["line of longitude", "meridian"],
    "prime minister": ["chief of state", "head of state", "pm", "premier"],
    "prime number": ["prime", "prime quantity"],
    "prime time": ["clock time", "time"],
    "primer": ["hornbook", "school text", "schoolbook", "speller", "text", "text edition", "textbook"],
    "primidone": ["anticonvulsant", "anticonvulsant drug", "antiepileptic", "antiepileptic drug", "mysoline"],
    "primigravida": ["gravida", "gravida i"],
    "priming": ["preparation", "readying"],
    "primipara": ["female parent", "mother", "para i"],
    "primiparous": [],
    "primitive": ["ape-man", "aryan", "autochthon", "barbarian", "basket maker", "cave dweller", "cave man", "caveman", "feral man", "heidelberg man", "homo heidelbergensis", "individual", "indo-european", "missing link", "mortal", "mound builder", "person", "piltdown hoax", "piltdown man", "primitive person", "savage", "somebody", "someone", "soul", "troglodyte", "wild man"],
    "primitively": ["in the beginning", "originally"],
    "primitivism": ["genre"],
    "primly": ["prissily"],
    "primness": ["grundyism", "modestness", "modesty", "prudery", "prudishness"],
    "primo": ["part", "voice"],
    "primogeniture": ["heritage", "inheritance"],
    "primordial dwarf": ["dwarf", "hypoplastic dwarf", "midget", "nanus", "normal dwarf", "true dwarf"],
    "primordium": ["anlage", "organ"],
    "primping": ["dressing", "grooming"],
    "primrose": ["auricula", "bear's ear", "chinese primrose", "cowslip", "english primrose", "herb", "herbaceous plant", "oxlip", "paigle", "polyanthus", "primula", "primula auricula", "primula elatior", "primula polyantha", "primula sinensis", "primula veris", "primula vulgaris"],
    "primrose jasmine": ["jasmine", "jasminum mesnyi"],
    "primrose path": ["path", "way", "way of life"],
    "primulaceae": ["dicot family", "family primulaceae", "magnoliopsid family", "primrose family"],
    "primulales": ["order primulales", "plant order"],
    "primus": ["bishop"],
    "primus stove": ["cooking stove", "kitchen range", "kitchen stove", "primus", "range", "stove"],
    "prince": ["archduke", "aristocrat", "blue blood", "crown prince", "dauphin", "elector", "grand duke", "maharaja", "maharajah", "patrician", "prince consort", "prince of wales", "princeling"],
    "prince albert": ["frock coat"],
    "prince albert yew": ["conifer", "coniferous tree", "prince albert's yew", "saxe-gothea conspicua"],
    "prince charming": ["suer", "suitor", "wooer"],
    "prince consort": ["consort", "prince"],
    "prince edward island": [],
    "prince of wales": ["prince"],
    "prince's-feather": ["kiss-me-over-the-garden-gate", "polygonum orientale", "prince's-plume", "princess feather", "subshrub", "suffrutex"],
    "prince-of-wales'-heath": ["erica", "erica perspicua", "prince of wales heath", "true heath"],
    "princedom": ["rank"],
    "princeling": ["prince"],
    "princely": [],
    "princess": ["archduchess", "aristocrat", "blue blood", "crown princess", "maharanee", "maharani", "patrician", "princess royal"],
    "princess royal": ["princess"],
    "princeton": [],
    "princeton university": ["princeton"],
    "princewood": ["cordia gerascanthus", "spanish elm", "tree"],
    "principal": ["debt"],
    "principal axis": ["axis", "optic axis"],
    "principal investigator": ["pi", "scientist"],
    "principality": ["demesne", "domain", "land", "princedom"],
    "principalship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "principe": [],
    "principle": ["caveat emptor", "higher law", "hypothetical imperative", "moral principle", "precept", "prescript", "rule"],
    "principle of equivalence": ["principle", "rule"],
    "principle of liquid displacement": ["principle", "rule"],
    "principle of relativity": ["law", "law of nature"],
    "principle of superposition": ["principle", "rule", "superposition", "superposition principle"],
    "principled": [],
    "prinia": ["bird genus", "genus prinia"],
    "prink": ["dress", "get dressed"],
    "print": ["engrave", "etch", "lithograph", "reproduce", "silkscreen", "stencil"],
    "print buffer": ["buffer", "buffer storage", "buffer store"],
    "print media": ["journalism", "medium", "news media", "press", "public press", "samizdat", "underground press"],
    "print run": ["press run", "run", "split run"],
    "print seller": ["art dealer"],
    "print shop": ["printing shop", "shop", "workshop"],
    "printable": [],
    "printed circuit": ["add-in", "board", "card", "circuit board", "circuit card", "computer circuit", "plug-in"],
    "printer": ["compositor", "pressman", "proofreader", "reader", "setter", "skilled worker", "skilled workman", "trained worker", "typesetter", "typographer"],
    "printer cable": ["cable", "line", "transmission line"],
    "printer's devil": ["apprentice", "learner", "prentice"],
    "printer's ink": ["ink", "printing ink"],
    "printing": ["carbon process", "composition", "gravure", "intaglio", "intaglio printing", "letterpress", "offset", "offset printing", "planographic printing", "planography", "printing process", "process printing", "relief printing", "typography", "writing"],
    "printing concern": ["company", "printing business", "printing company"],
    "printing operation": ["carriage return", "line feed", "new line", "operation"],
    "printing unit": ["milline", "unit", "unit of measurement"],
    "printmaker": ["artist", "creative person", "engraver", "graphic artist", "lithographer"],
    "printmaking": ["art", "artistic creation", "artistic production", "engraving", "etching", "lithography", "serigraphy"],
    "printout": ["output", "output signal"],
    "priodontes": ["genus priodontes", "mammal genus"],
    "prion": ["particle", "subatomic particle"],
    "prionace": ["fish genus", "genus prionace"],
    "prionotus": ["fish genus", "genus prionotus"],
    "prior": ["superior"],
    "prioritize": ["grade", "order", "place", "prioritise", "range", "rank", "rate"],
    "priority": ["antecedence", "antecedency", "anteriority", "earliness", "precedence", "precedency"],
    "priority processing": ["background processing", "backgrounding", "data processing", "foreground processing", "foregrounding"],
    "priorship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "priory": ["cloister", "religious residence"],
    "prism": ["parallelepiped", "parallelepipedon", "parallelopiped", "parallelopipedon", "polyhedron", "quadrangular prism", "triangular prism"],
    "prismatic": [],
    "prismatoid": ["polyhedron", "prismoid"],
    "prismoid": ["prismatoid"],
    "prison": ["prison house", "situation", "state of affairs"],
    "prison camp": ["camp", "gulag", "internment camp", "pow camp", "prisoner of war camp"],
    "prison chaplain": ["chaplain"],
    "prison guard": ["gaoler", "jailer", "jailor", "keeper", "law officer", "lawman", "peace officer", "screw", "turnkey"],
    "prison term": ["hard time", "life", "life sentence", "sentence", "term", "time"],
    "prisoner": ["captive", "con", "convict", "detainee", "hostage", "inmate", "internee", "political detainee", "political prisoner", "pow", "prisoner of war", "surety", "unfortunate", "unfortunate person", "yard bird", "yardbird"],
    "prisoner of war": ["captive", "pow", "prisoner"],
    "prisoner of war censorship": ["military censorship"],
    "prisoner's base": ["game"],
    "prisonlike": [],
    "pristidae": ["family pristidae", "fish family"],
    "pristine": [],
    "pristis": ["fish genus", "genus pristis"],
    "pritzelago": ["dilleniid dicot genus", "genus pritzelago"],
    "privacy": ["bosom", "concealment", "confidentiality", "covertness", "hiddenness", "hiding", "isolation", "privateness", "secrecy"],
    "private": ["buck private", "common soldier", "enlisted man"],
    "private citizen": ["citizen"],
    "private detective": ["detective", "hotel detective", "house detective", "house dick", "inquiry agent", "operative", "pi", "private eye", "private investigator", "shamus", "sherlock", "store detective"],
    "private foundation": ["charity"],
    "private line": ["line", "phone line", "subscriber line", "telephone circuit", "telephone line"]
}
