synonyms = {
    "tactually": ["haptically"],
    "tad": ["shade"],
    "tadalafil": ["cialis"],
    "tadarida": ["genus tadarida"],
    "tadorna": ["genus tadorna"],
    "tadpole": ["polliwog", "pollywog"],
    "tae kwon do": ["taekwondo"],
    "taegu": ["tegu"],
    "taenia": ["fillet", "tenia"],
    "taeniidae": ["family taeniidae"],
    "taft": ["lorado taft"],
    "tag": ["label", "mark"],
    "tagasaste": ["chamaecytisus palmensis", "cytesis proliferus"],
    "tageteste": ["genus tagetes"],
    "tagger": ["tagging program"],
    "tagore": ["rabindranath tagore", "sir rabindranath tagore"],
    "taguan": ["flying cat", "flying marmot", "petaurista petaurista"],
    "tagus": ["tagus river"],
    "tahoka daisy": ["machaeranthera tanacetifolia", "tansy leaf aster"],
    "tai dam": ["black tai"],
    "tai long": ["shan"],
    "tai lue": ["xishuangbanna dai"],
    "tai nuea": ["chinese shan", "dehong dai"],
    "tai yuan": ["kam muang"],
    "tail": ["tail end"],
    "tail fin": ["fin", "tailfin"],
    "tailed frog": ["ascaphus trui", "bell toad", "ribbed toad", "tailed toad"],
    "tailgate": ["tailboard"],
    "tailless tenrec": ["tenrec ecaudatus"],
    "taillight": ["rear lamp", "rear light", "tail lamp"],
    "tailor": ["orient"],
    "tailorbird": ["orthotomus sutorius"],
    "tailored": ["trim"],
    "tailspin": ["spin"],
    "taimyr peninsula": ["taymyr peninsula"],
    "taipan": ["oxyuranus scutellatus"],
    "taipei": ["capital of taiwan", "taipeh"],
    "taiwan": ["china", "nationalist china", "republic of china"],
    "taiwanese": ["chinese", "formosan"],
    "tajik": ["tadzhik"],
    "tajiki": ["tadzhik", "tajik"],
    "tajikistan": ["republic of tajikistan", "tadjik", "tadzhik", "tadzhikistan", "tajik"],
    "take": ["occupy", "use up"],
    "take a dare": ["pick up the gauntlet"],
    "take a hit": ["snort"],
    "take a look": ["get a load", "have a look"],
    "take after": ["follow"],
    "take away": ["bear away", "bear off", "carry away", "carry off"],
    "take back": ["repossess"],
    "take care": ["mind"],
    "take down": ["degrade", "demean", "disgrace", "put down"],
    "take heart": ["buck up"],
    "take hold": ["take charge", "take control"],
    "take home": ["bring home"],
    "take in": ["take up"],
    "take off": ["take time off"],
    "take out": ["move out", "remove"],
    "take over": ["relieve"],
    "take pains": ["be at pains"],
    "take pride": ["pride oneself"],
    "take the count": ["remain down"],
    "take the fifth": ["take the fifth amendment"],
    "take the stage": ["take stage"],
    "take up": ["fasten on", "hook on", "latch on", "seize on"],
    "takeout": ["takeaway", "takeout food"],
    "takilman": ["takelma"],
    "takin": ["budorcas taxicolor", "gnu goat"],
    "taklimakan desert": ["taklamakan desert"],
    "talapoin": ["cercopithecus talapoin"],
    "talbot": ["fox talbot", "william henry fox talbot"],
    "talc": ["talcum"],
    "talcum": ["talcum powder"],
    "talented": ["gifted"],
    "taliban": ["taleban"],
    "talinum": ["genus talinum"],
    "talipot": ["corypha umbraculifera", "talipot palm"],
    "talk": ["speak"],
    "talk of": ["talk about"],
    "talk show": ["chat show"],
    "talking picture": ["talkie"],
    "tall bellflower": ["campanula americana"],
    "tall cupflower": ["nierembergia frutescens"],
    "tall mallow": ["cheese", "cheeseflower", "high mallow", "malva sylvestris"],
    "tall oat grass": ["arrhenatherum elatius", "evergreen grass", "false oat", "french rye", "tall meadow grass"],
    "tall order": ["large order"],
    "tallahassee": ["capital of florida"],
    "tallapoosa": ["tallapoosa river"],
    "tallchief": ["maria tallchief"],
    "talleyrand": ["charles maurice de talleyrand"],
    "tallinn": ["capital of estonia", "tallin"],
    "tallis": ["thomas tallis"],
    "tally": ["chalk up"],
    "tallyman": ["tally clerk"],
    "talpidae": ["family talpidae"],
    "talus": ["scree"],
    "tam": ["tammy"],
    "tamable": ["tameable"],
    "tamandua": ["lesser anteater", "tamandu", "tamandua tetradactyla"],
    "tamarau": ["anoa mindorensis", "bubalus mindorensis", "tamarao"],
    "tamaricaceae": ["family tamaricaceae", "tamarisk family"],
    "tamarin": ["leoncita", "lion marmoset", "lion monkey"],
    "tamarind": ["tamarind tree", "tamarindo", "tamarindus indica"],
    "tamarindus": ["genus tamarindus"],
    "tamarisk gerbil": ["meriones unguiculatus"],
    "tamarix": ["genus tamarix"],
    "tambour": ["embroidery frame", "embroidery hoop"],
    "tame": ["chasten", "subdue"],
    "tameness": ["domestication"],
    "tamerlane": ["tamburlaine", "timur", "timur lenk"],
    "tamias": ["genus tamias"],
    "tamiasciurus": ["genus tamiasciurus"],
    "tamil nadu": ["madras"],
    "tamm": ["igor tamm", "igor yevgeneevich tamm"],
    "tammany hall": ["tammany", "tammany society"],
    "tammuz": ["thammuz"],
    "tamp": ["tamper", "tamping bar"],
    "tamp down": ["pack", "tamp"],
    "tamper": ["fiddle", "monkey"],
    "tampere": ["tammerfors"],
    "tampion": ["tompion"],
    "tamponade": ["tamponage"],
    "tamus": ["genus tamus"],
    "tan": ["bronze"],
    "tanacetum": ["genus tanacetum"],
    "tanakh": ["hebrew scripture", "tanach"],
    "tanbark oak": ["lithocarpus densiflorus"],
    "tandem": ["in tandem"],
    "tandy": ["jessica tandy"],
    "tanekaha": ["phyllocladus trichomanoides"],
    "taney": ["roger brooke taney", "roger taney"],
    "tang": ["tang dynasty"],
    "tange": ["kenzo tange"],
    "tangelo": ["citrus tangelo", "tangelo tree", "ugli fruit"],
    "tangent": ["tan"],
    "tangerine": ["tangerine tree"],
    "tangibility": ["palpability", "tangibleness"],
    "tangible": ["touchable"],
    "tangible possession": ["material possession"],
    "tangier": ["tangiers"],
    "tangier pea": ["lalthyrus tingitanus", "tangier peavine"],
    "tangle": ["maze", "snarl"],
    "tanglebush": ["desert olive", "forestiera neomexicana"],
    "tanguy": ["yves tanguy"],
    "tank": ["tankful"],
    "tank car": ["tank"],
    "tank engine": ["tank locomotive"],
    "tanker": ["tank driver"],
    "tannenberg": ["battle of tannenberg"],
    "tannin": ["tannic acid"],
    "tanoan": ["tanoan language"],
    "tansy": ["golden buttons", "scented fern", "tanacetum vulgare"],
    "tansy mustard": ["descurainia pinnata"],
    "tantalizer": ["tantaliser"],
    "tantalizing": ["tantalising"],
    "tantalizingly": ["invitingly"],
    "tantalum": ["ta"],
    "tantilla": ["genus tantilla"],
    "tantra": ["tantrism"],
    "tantric": ["tantrik"],
    "tanzania": ["united republic of tanzania"],
    "tanzanian shilling": ["shilling"],
    "taoism": ["hsuan chiao"],
    "taoist": ["tao"],
    "tap": ["knock", "pink", "rap"],
    "tap dancer": ["tapper"],
    "tap dancing": ["tap dance"],
    "tapa": ["tapa bark", "tappa", "tappa bark"],
    "tapdance": ["tap"],
    "tape": ["tape measure", "tapeline"],
    "tape drive": ["tape transport", "transport"],
    "tape grass": ["eelgrass", "vallisneria spiralis", "wild celery"],
    "tape recorder": ["tape machine"],
    "taper off": ["fizzle", "fizzle out", "peter out"],
    "tapered": ["narrowing", "tapering"],
    "tapestry": ["tapis"],
    "tapeworm": ["cestode"],
    "tapiridae": ["family tapiridae"],
    "tapirus": ["genus tapirus"],
    "tappan": ["arthur tappan"],
    "tapper": ["phone tapper", "wiretapper"],
    "tapster": ["tapper"],
    "tarabulus": ["trablous", "tripoli"],
    "tarahumara frog": ["rana tarahumarae"],
    "tarantella": ["tarantelle"],
    "tarantino": ["quentin jerome tarantino", "quentin tarantino"],
    "tarawa": ["bairiki"],
    "taraxacum": ["genus taraxacum"],
    "tarbell": ["ida minerva tarbell", "ida tarbell"],
    "tardigrada": ["class tardigrada"],
    "tareekh e kasas": ["movement for revenge"],
    "target": ["aim", "direct", "place", "point"],
    "target company": ["takeover target"],
    "taricha": ["genus taricha"],
    "tarkovsky": ["andrei arsenevich tarkovsky", "andrei tarkovsky"],
    "tarmacadam": ["tarmac"],
    "tarnish": ["defile", "maculate", "stain", "sully"],
    "tarnished plant bug": ["lygus lineolaris"],
    "taro": ["cocoyam", "dasheen", "eddo"],
    "tarot card": ["tarot"],
    "tarpan": ["equus caballus gomelini"],
    "tarpaulin": ["tarp"],
    "tarpon": ["tarpon atlanticus"],
    "tarquin": ["lucius tarquinius superbus", "tarquin the proud", "tarquinius", "tarquinius superbus"],
    "tarragon": ["artemisia dracunculus", "estragon"],
    "tarriance": ["lingering"],
    "tarrietia": ["genus tarrietia"],
    "tarry": ["linger"],
    "tarsal": ["tarsal bone"],
    "tarsiidae": ["family tarsiidae"],
    "tarsioidea": ["suborder tarsioidea"],
    "tarsius": ["genus tarsius"],
    "tartan": ["plaid"],
    "tartar": ["calculus", "tophus"],
    "tartar emetic": ["antimony potassium tartrate"],
    "tartare sauce": ["tartar sauce"],
    "tartary": ["tatary"],
    "tartuffe": ["tartufe"],
    "tarwood": ["dacrydium bidwilli", "halocarpus bidwilli", "new zealand mountain pine"],
    "tarzan": ["tarzan of the apes"],
    "tashkent": ["capital of uzbek", "taskent"],
    "tashmit": ["tashmitum"],
    "tasman": ["abel janszoon tasman", "abel tasman"],
    "tasman dwarf pine": ["microstrobos niphophilus"],
    "tasmanian devil": ["sarcophilus hariisi", "ursine dasyure"],
    "tassel flower": ["emilia sagitta"],
    "tassel hyacinth": ["muscari comosum"],
    "tasseled": ["tasselled"],
    "tasset": ["tasse"],
    "tasso": ["torquato tasso"],
    "taste": ["savor", "savour"],
    "taste cell": ["gustatory cell"],
    "tastebud": ["gustatory organ", "taste bud"],
    "tastefully": ["tastily"],
    "taster": ["sampler", "taste tester"],
    "tasting": ["degustation", "relishing", "savoring", "savouring"],
    "tat": ["intertwine"],
    "tatar": ["mongol tatar", "tartar"],
    "tate": ["allen tate", "john orley allen tate"],
    "tati": ["jacques tati", "jacques tatischeff"],
    "tatouay": ["cabassous", "cabassous unicinctus"],
    "tattered": ["tatterdemalion"],
    "tattle": ["singing", "telling"],
    "tattletale": ["blabbermouth", "talebearer", "taleteller", "tattler", "telltale"],
    "tattletale grey": ["tattletale gray"],
    "tatum": ["edward lawrie tatum"],
    "tau coefficient of correlation": ["kendall rank correlation"],
    "tauntingly": ["teasingly"],
    "taurotragus": ["genus taurotragus"],
    "taurus": ["bull"],
    "taut": ["tight"],
    "tauten": ["firm"],
    "tautog": ["blackfish", "tautoga onitis"],
    "tautoga": ["genus tautoga"],
    "tautogolabrus": ["genus tautogolabrus"],
    "tavern": ["tap house"],
    "taw": ["shooter"],
    "tawney": ["richard henry tawney"],
    "tawny eagle": ["aquila rapax"],
    "tawny owl": ["strix aluco"],
    "tax": ["assess"],
    "tax assessor": ["assessor"],
    "tax benefit": ["tax break"],
    "tax collector": ["collector of internal revenue", "exciseman", "internal revenue agent", "taxman"],
    "tax income": ["revenue", "tax revenue", "taxation"],
    "tax program": ["tax policy"],
    "tax return": ["income tax return", "return"],
    "tax shelter": ["shelter"],
    "taxable": ["nonexempt"],
    "taxaceae": ["family taxaceae", "yew family"],
    "taxales": ["order taxales"],
    "taxi": ["cab"],
    "taxidea": ["genus taxidea"],
    "taxidermist": ["animal stuffer", "stuffer"],
    "taxidriver": ["cabby", "cabdriver", "cabman", "hack driver", "livery driver", "taximan"],
    "taxiway": ["taxi strip"],
    "taxodiaceae": ["redwood family", "subfamily taxodiaceae"],
    "taxodium": ["genus taxodium"],
    "taxonomic": ["systematic", "taxonomical"],
    "taxonomic group": ["taxon", "taxonomic category"],
    "taxonomist": ["systematist", "taxonomer"],
    "taxopsida": ["class taxopsida", "subdivision taxophytina", "taxophytina"],
    "taxus": ["genus taxus"],
    "tayalic": ["atayalic"],
    "tayassu": ["genus pecari", "genus tayassu"],
    "tayassuidae": ["family tayassuidae"],
    "taylor": ["deems taylor", "joseph deems taylor"],
    "tayra": ["eira barbara", "taira"],
    "tbilisi": ["capital of georgia", "tiflis"],
    "tchaikovsky": ["peter ilich tchaikovsky", "peter tchaikovsky", "pyotr ilych tchaikovsky", "pyotr tchaikovsky"],
    "te kanawa": ["dame kiri janette te kanawa", "dame kiri te kanawa"],
    "tea": ["camellia sinensis"],
    "tea cart": ["tea trolley", "tea wagon", "teacart"],
    "tea ceremony": ["chanoyu"],
    "tea rose": ["rosa odorata"],
    "tea service": ["tea set"],
    "tea tortrix": ["homona coffearia", "tortrix"],
    "teaberry": ["checkerberry", "creeping wintergreen", "gaultheria procumbens", "groundberry", "mountain tea", "wintergreen"],
    "teacake": ["tea biscuit"],
    "teach": ["instruct", "learn"],
    "teacher": ["instructor"],
    "teaching": ["commandment", "precept"],
    "teaching method": ["pedagogics", "pedagogy"],
    "teacup": ["teacupful"],
    "teak": ["teakwood"],
    "team": ["team up"],
    "teammate": ["mate"],
    "teamster": ["truck driver", "trucker"],
    "teapot dome": ["teapot dome scandal"],
    "tear": ["buck", "charge", "shoot", "shoot down"],
    "tear away": ["tear off"],
    "tear gas": ["lachrymator", "lacrimator", "teargas"],
    "teasdale": ["sara teasdale"],
    "tease": ["badger", "beleaguer", "bug", "pester"],
    "teased": ["titillated"],
    "teasel": ["teasle", "teazel"],
    "teashop": ["tea parlor", "tea parlour", "teahouse", "tearoom"],
    "teaspoon": ["teaspoonful"],
    "tebaldi": ["renata tebaldi"],
    "tebet": ["tevet"],
    "tebibit": ["tibit"],
    "techie": ["tekki"],
    "technetium": ["tc"],
    "technical": ["technological"],
    "technical analysis": ["technical analysis of stock trends"],
    "technical foul": ["technical"],
    "technical knockout": ["tko"],
    "technical school": ["tech"],
    "technicality": ["trifle", "triviality"],
    "technology": ["engineering"],
    "tecophilaeacea": ["family tecophilaeacea"],
    "tectaria": ["genus tectaria"],
    "tectona": ["genus tectona"],
    "tectonic": ["architectonic"],
    "tectonics": ["plate tectonic theory", "plate tectonics"],
    "tecumseh": ["tecumtha"],
    "ted": ["teddy boy"],
    "teddy": ["teddy bear"],
    "tediousness": ["tedium", "tiresomeness"],
    "tee": ["tee up"],
    "tee hinge": ["t hinge"],
    "teem": ["pullulate", "swarm"],
    "teeter": ["seesaw", "totter"],
    "teething": ["dentition", "odontiasis"],
    "teetotaler": ["teetotalist", "teetotaller"],
    "teetotaling": ["teetotalism"],
    "teff": ["eragrostic abyssinica", "eragrostis tef", "teff grass"],
    "teflon": ["polytetrafluoroethylene"],
    "tegucigalpa": ["honduran capital"],
    "teheran": ["capital of iran", "iranian capital", "tehran"],
    "teiid lizard": ["teiid"],
    "teiidae": ["family teiidae"],
    "teilhard de chardin": ["pierre teilhard de chardin"],
    "telanthera": ["genus telanthera"],
    "telecast": ["televise"],
    "telecom hotel": ["telco building"],
    "telecommunication": ["telecom"],
    "telecommunication system": ["telecom equipment", "telecom system", "telecommunication equipment"],
    "telecommuting": ["teleworking"],
    "teleconference": ["teleconferencing"],
    "telegram": ["wire"],
    "telegraph": ["telegraphy"],
    "telegraph plant": ["codariocalyx motorius", "desmodium gyrans", "desmodium motorium", "semaphore plant"],
    "telegrapher": ["telegraph operator", "telegraphist"],
    "telegraphic signal": ["radiotelegraphic signal"],
    "telegraphically": ["tersely"],
    "telekinesis": ["psychokinesis"],
    "telemann": ["georg philipp telemann"],
    "telemarketing": ["telecommerce", "teleselling"],
    "telemetry intelligence": ["telint"],
    "teleost fish": ["teleost", "teleostan"],
    "teleostei": ["subclass teleostei"],
    "telepathist": ["mental telepathist", "mind reader"],
    "telepathize": ["telepathise"],
    "telepathy": ["thought transference"],
    "telephone": ["telephony"],
    "telephone booth": ["call box", "phone booth", "telephone box", "telephone kiosk"],
    "telephone company": ["phone company", "phone service", "telco", "telephone service"],
    "telephone cord": ["phone cord"],
    "telephone jack": ["phone jack"],
    "telephone line": ["line", "phone line", "subscriber line", "telephone circuit"],
    "telephone operator": ["switchboard operator", "telephonist"],
    "telephone plug": ["phone plug"],
    "telephone pole": ["telegraph pole", "telegraph post"],
    "telephone receiver": ["receiver"],
    "telephone system": ["phone system"],
    "telephone wire": ["telegraph line", "telegraph wire", "telephone line"],
    "telephoto lens": ["zoom lens"],
    "telephotograph": ["telephoto"],
    "telescope": ["scope"],
    "telescoped": ["shortened"],
    "telescopic sight": ["telescope sight"],
    "teletypewriter": ["teleprinter", "teletype machine", "telex", "telex machine"],
    "television": ["telecasting", "tv", "video"],
    "television camera": ["camera", "tv camera"],
    "television equipment": ["video equipment"],
    "television monitor": ["tv monitor"],
    "television program": ["television show", "tv program", "tv show"],
    "television receiver": ["boob tube", "goggle box", "idiot box", "television", "television set", "telly", "tv", "tv set"],
    "television reporter": ["television newscaster", "tv newsman", "tv reporter"],
    "television room": ["tv room"],
    "television star": ["tv star"],
    "television station": ["tv station"],
    "tell": ["evidence"],
    "tell off": ["brush down"],
    "teller": ["edward teller"],
    "tellima": ["genus tellima"],
    "telling": ["apprisal", "notification"],
    "tellurian": ["earthling", "earthman", "worldling"],
    "tellurium": ["te"],
    "telopea": ["genus telopea"],
    "telosporidia": ["subclass telosporidia"],
    "telpher": ["telfer"],
    "telpherage": ["telferage"],
    "temazepam": ["restoril"],
    "temnospondyli": ["order temnospondyli"],
    "temp": ["temporary", "temporary worker"],
    "temper": ["harden"],
    "tempera": ["poster color", "poster colour", "poster paint"],
    "temperance": ["moderation"],
    "tempered": ["hardened", "toughened", "treated"],
    "template": ["guide", "templet"],
    "temple of apollo": ["delphic oracle", "oracle of apollo", "oracle of delphi"],
    "temple of jerusalem": ["temple of solomon"],
    "temple orange": ["citrus nobilis", "king orange", "tangor", "temple orange tree"],
    "templetonia": ["genus templetonia"],
    "tempo": ["pace"],
    "temporal arrangement": ["temporal order"],
    "temporal bone": ["os temporale"],
    "temporal lobe": ["temporal ccortex"],
    "temporal role": ["temporal"],
    "temporal vein": ["vena temporalis"],
    "temporalis muscle": ["musculus temporalis", "temporal muscle", "temporalis"],
    "temporalty": ["temporality"],
    "temporary hookup": ["patch"],
    "temporary injunction": ["interlocutory injunction"],
    "temporize": ["temporise"],
    "temporizer": ["temporiser"],
    "tempt": ["invite"],
    "temptation": ["enticement"],
    "ten": ["decade", "tenner"],
    "ten thousand": ["myriad"],
    "tenant": ["renter"],
    "tench": ["tinca tinca"],
    "tend": ["be given", "incline", "lean", "run"],
    "tendency": ["trend"],
    "tendentious": ["tendencious"],
    "tender": ["tenderise", "tenderize"],
    "tender loving care": ["tlc"],
    "tendergreen": ["brassica perviridis", "brassica rapa perviridis", "spinach mustard"],
    "tenderization": ["tenderisation"],
    "tenderized": ["tenderised"],
    "tenderizer": ["tenderiser"],
    "tenderloin": ["undercut"],
    "tenderness": ["rawness", "soreness"],
    "tendinitis": ["tendonitis", "tenonitis"],
    "tendinous": ["sinewy"],
    "tendon": ["sinew"],
    "tenebrionidae": ["family tenebrionidae"],
    "tenebrous": ["tenebrific", "tenebrious"],
    "tenement": ["tenement house"],
    "tenfold": ["denary"],
    "tenner": ["ten dollar bill"],
    "tennessean": ["volunteer"],
    "tennessee": ["tennessee river"],
    "tennessee walker": ["plantation walking horse", "tennessee walking horse", "walking horse"],
    "tenniel": ["sir john tenniel"],
    "tennis": ["lawn tennis"],
    "tennis elbow": ["lateral epicondylitis", "lateral humeral epicondylitis"],
    "tennis pro": ["professional tennis player"],
    "tennis racket": ["tennis racquet"],
    "tennis stroke": ["tennis shot"],
    "tennyson": ["alfred lord tennyson", "alfred tennyson", "first baron tennyson"],
    "tenor": ["tenor voice"],
    "tenor saxophonist": ["tenorist"],
    "tenosynovitis": ["tendonous synovitis", "tendosynovitis"],
    "tenpins": ["tenpin bowling"],
    "tenrec": ["tendrac"],
    "tenrecidae": ["family tenrecidae"],
    "tense": ["tense up"],
    "tension": ["tautness", "tenseness", "tensity"],
    "tent": ["collapsible shelter"],
    "tentaculata": ["class tentaculata"],
    "tenthredinidae": ["family tenthredinidae"],
    "tenure": ["incumbency", "term of office"],
    "tepary bean": ["phaseolus acutifolius latifolius"],
    "tepee": ["teepee", "tipi"],
    "tephrosia": ["genus tephrosia"],
    "tepidness": ["lukewarmness"],
    "tera": ["pidlimdi", "yamaltu"],
    "terabit": ["tb", "tbit"],
    "terabyte": ["tb"],
    "teraflop": ["trillion floating point operations per second"],
    "terahertz": ["thz"],
    "terazosin": ["hytrin"],
    "terbinafine": ["lamisil"],
    "terbium": ["tb"],
    "terce": ["tierce"],
    "tercentennial": ["tercentenary", "triennial"],
    "terebella": ["genus terebella"],
    "terebellidae": ["family terebellidae"]
}
