synonyms = {
    "platonistic": [],
    "platoon": ["social group"],
    "platt national park": [],
    "platte": ["platte river"],
    "platte river penstemon": ["penstemon cyananthus", "wild flower", "wildflower"],
    "platter": ["flatware"],
    "platy": ["live-bearer", "platypoecilus maculatus", "poeciliid", "poeciliid fish", "topminnow"],
    "platycephalidae": ["family platycephalidae", "fish family"],
    "platycerium": ["fern genus", "genus platycerium"],
    "platyctenea": ["animal order", "order platyctenea"],
    "platyctenean": ["comb jelly", "ctenophore"],
    "platyhelminthes": ["phylum", "phylum platyhelminthes"],
    "platylobium": ["genus platylobium", "rosid dicot genus"],
    "platymiscium": ["genus platymiscium", "rosid dicot genus"],
    "platypoecilus": ["fish genus", "genus platypoecilus"],
    "platypus": ["duck-billed platypus", "duckbill", "duckbilled platypus", "egg-laying mammal", "monotreme", "ornithorhynchus anatinus"],
    "platyrrhine": ["broadnosed", "platyrhine", "platyrhinian", "platyrrhinian", "platyrrhinic"],
    "platyrrhini": ["mammal family", "superfamily platyrrhini"],
    "platysma": ["facial muscle"],
    "platystemon": ["dilleniid dicot genus", "genus platystemon"],
    "plausibility": ["believability", "credibility", "credibleness", "plausibleness", "reasonableness", "tenability", "tenableness"],
    "plausible": [],
    "plautus": ["titus maccius plautus"],
    "play": [],
    "play along": ["collaborate", "cooperate", "get together", "go along", "join forces"],
    "play around": ["betray", "cheat", "cheat on", "cuckold", "fool around", "wander"],
    "play back": ["replay", "reproduce"],
    "play it by ear": ["act", "move"],
    "play out": ["perform"],
    "play possum": ["affect", "dissemble", "feign", "pretend", "sham"],
    "play reading": ["performance", "public presentation"],
    "play therapy": ["psychotherapy"],
    "playable": [],
    "playback": ["electronic equipment"],
    "playbill": ["bill", "program", "programme"],
    "playbook": ["notebook"],
    "playbox": ["box", "play-box"],
    "playboy": ["corinthian", "hedonist", "man-about-town", "pagan", "pleasure seeker"],
    "played": [],
    "played out": [],
    "player": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "playful": [],
    "playfully": [],
    "playfulness": ["archness", "facetiousness", "friskiness", "frivolity", "frivolousness", "frolicsomeness", "fun", "humor", "humour", "impertinence", "impishness", "mischievousness", "perkiness", "pertness", "puckishness", "sauciness", "sense of humor", "sense of humour", "sportiveness", "whimsicality"],
    "playgoer": ["first-nighter", "groundling", "looker", "spectator", "theatergoer", "theatregoer", "viewer", "watcher", "witness"],
    "playground": ["curtilage", "grounds", "yard"],
    "playhouse": ["plaything", "toy", "tree house", "wendy house"],
    "playing": ["bowing", "musical performance", "piping", "stopping", "transposition"],
    "playing card": ["ace", "card", "club", "court card", "crib", "deuce", "diamond", "draw", "face card", "gaming card", "heart", "hole card", "joker", "picture card", "singleton", "spade", "spot", "stopper", "suit", "three", "trey", "trump", "trump card", "two", "wild card"],
    "playing field": ["circumstance"],
    "playing period": ["amount", "golf hole", "hole", "measure", "period of play", "play", "quantity", "set"],
    "playlet": ["drama", "dramatic play", "play"],
    "playlist": ["list", "listing", "play list"],
    "playmaker": ["participant", "player"],
    "playmate": ["associate", "companion", "comrade", "familiar", "fellow", "playfellow"],
    "playoff": ["competition", "contest", "world series"],
    "playoff game": ["game"],
    "playpen": ["enclosure", "pen"],
    "playschool": ["play group", "preschool"],
    "playsuit": ["getup", "outfit", "rig", "turnout"],
    "plaything": ["artefact", "artifact", "ball", "balloon", "catapult", "cockhorse", "dandle board", "doll", "doll's house", "dollhouse", "dolly", "frisbee", "hobby", "hobbyhorse", "hula-hoop", "jack-in-the-box", "jumping jack", "jungle gym", "kaleidoscope", "kite", "lego", "lego set", "meccano", "meccano set", "pea shooter", "pinata", "pinwheel", "pinwheel wind collector", "playground slide", "playhouse", "pogo stick", "popgun", "rattle", "rocking horse", "sandbox", "sandpile", "sandpit", "seesaw", "slide", "sliding board", "sling", "slingshot", "spinning top", "squirt gun", "squirter", "stick horse", "swing", "teddy", "teddy bear", "teeter", "teeter-totter", "teeterboard", "teetertotter", "teetotum", "tilting board", "top", "toy", "train set", "water gun", "water pistol", "wendy house", "whirligig", "yo-yo"],
    "playtime": ["leisure", "leisure time", "playday"],
    "plaza": ["piazza", "place", "public square", "square"],
    "plea": ["answer", "counterplea", "dilatory plea", "insanity plea", "plea of insanity"],
    "plea bargain": ["bargaining", "plea bargaining"],
    "plea-bargain": ["agree"],
    "pleach": ["enlace", "entwine", "interlace", "intertwine", "lace", "plash", "twine"],
    "plead": ["allege", "aver", "demur", "say"],
    "pleading": ["affirmative pleading", "alternative pleading", "answer", "charge", "complaint", "defective pleading", "demurrer", "pleading in the alternative", "rebuttal", "rebutter", "rejoinder", "replication", "special pleading", "statement", "surrebuttal", "surrebutter", "surrejoinder"],
    "pleasance": ["retreat"],
    "pleasant": [],
    "pleasant-smelling": [],
    "pleasantly": ["cheerily", "sunnily"],
    "pleasantness": ["afterglow", "pleasance", "pleasure"],
    "pleasantry": ["jest", "jocularity", "joke"],
    "please": ["care", "like", "wish"],
    "pleased": ["proud of"],
    "pleaser": ["entertainer"],
    "pleasing": ["gratification"],
    "pleasingly": [],
    "pleasingness": ["palatability", "palatableness", "tastiness"],
    "pleasure": ["comfort", "delectation", "delight", "enjoyment", "feeling", "pleasance", "pleasantness", "sexual pleasure"],
    "pleasure principle": ["pleasure-pain principle", "pleasure-unpleasure principle", "principle"],
    "pleat": ["fold", "fold up", "plicate", "turn up"],
    "plebeian": ["anti-intellectual", "common man", "common person", "commoner", "lowbrow", "philistine", "pleb"],
    "plebiscite": ["vote"],
    "plecoptera": ["animal order", "order plecoptera"],
    "plecotus": ["genus plecotus", "mammal genus"],
    "plectania": ["fungus genus", "genus plectania"],
    "plectognath": ["acanthopterygian", "blowfish", "boxfish", "filefish", "globefish", "headfish", "mola", "ocean sunfish", "plectognath fish", "puffer", "pufferfish", "spiny puffer", "spiny-finned fish", "sunfish", "triggerfish", "trunkfish"],
    "plectognathi": ["animal order", "order plectognathi", "order tetraodontiformes"],
    "plectomycetes": ["class", "class plectomycetes"],
    "plectophera": ["ephemerid", "ephemeropteran"],
    "plectorrhiza": ["genus plectorrhiza", "liliopsid genus", "monocot genus"],
    "plectranthus": ["houseplant"],
    "plectrophenax": ["bird genus", "genus plectrophenax"],
    "pledge": ["donate", "subscribe"],
    "pledge taker": ["unpaid worker", "volunteer"],
    "pledged": ["sworn"],
    "pledgee": ["adult", "grownup", "pawnbroker"],
    "pledger": ["adult", "grownup"],
    "pleiades": ["nymph"],
    "pleione": ["genus pleione", "liliopsid genus", "monocot genus"],
    "pleiospilos": ["caryophylloid dicot genus", "genus pleiospilos"],
    "pleistocene": ["glacial epoch", "pleistocene epoch"],
    "plenarily": [],
    "plenary": [],
    "plenipotentiary": ["diplomat", "diplomatist"],
    "plentiful": [],
    "plenty": ["abundance", "copiousness", "plenitude", "plenteousness", "plentifulness", "plentitude", "teemingness"],
    "plenum": ["group meeting", "meeting"],
    "pleochroic": [],
    "pleochroism": ["dichroism", "optical phenomenon", "trichroism"],
    "pleomorphic": [],
    "pleomorphic rhabdomyosarcoma": ["pleomorphic rhabdosarcoma", "rhabdomyosarcoma", "rhabdosarcoma"],
    "pleomorphism": ["organic phenomenon"],
    "pleonasm": ["verboseness", "verbosity"],
    "pleonastic": ["redundant", "tautologic", "tautological"],
    "plesianthropus": ["genus plesianthropus", "mammal genus"],
    "plesiosaur": ["archosaur", "archosaurian", "archosaurian reptile", "plesiosaurus"],
    "plesiosauria": ["animal order", "suborder plesiosauria"],
    "plethodon": ["amphibian genus", "genus plethodon"],
    "plethodontidae": ["amphibian family", "family plethodontidae"],
    "plethysmograph": ["body plethysmograph", "digital plethysmograph", "measuring device", "measuring instrument", "measuring system"],
    "pleura": ["parietal pleura", "serosa", "serous membrane", "visceral pleura"],
    "pleural": [],
    "pleural cavity": ["bodily cavity", "cavity", "cavum"],
    "pleural space": ["space"],
    "pleurisy": ["inflammatory disease", "pleuropneumonia", "purulent pleurisy"],
    "pleurobrachia": ["ctenophore genus", "genus pleurobrachia"],
    "pleurobrachiidae": ["ctenophore family", "family pleurobrachiidae"],
    "pleurocarp": ["moss", "pleurocarpous moss"],
    "pleurocarpous": [],
    "pleurodont": ["animal", "animate being", "beast", "brute", "creature", "fauna"],
    "pleurodynia": ["costalgia", "hurting", "pain", "pleuralgia"],
    "pleuronectes": ["fish genus", "genus pleuronectes"],
    "pleuronectidae": ["family pleuronectidae", "fish family"],
    "pleuropneumonia": ["pleurisy", "pneumonia"],
    "pleuropneumonialike organism": ["mycoplasma", "pplo"],
    "pleurosorus": ["fern genus", "genus pleurosorus"],
    "pleurothallis": ["orchid", "orchidaceous plant"],
    "pleurotus": ["fungus genus", "genus pleurotus"],
    "plevna": ["pleven"],
    "plexiglas": ["plexiglass", "polymethyl methacrylate"],
    "pleximeter": ["plate", "plessimeter"],
    "plexor": ["hammer", "percussor", "plessor"],
    "plexus": ["anatomical structure", "aortic plexus", "bodily structure", "body structure", "choroid plexus", "complex body part", "lumbar plexus", "nerve plexus", "plexus choroideus", "plexus lumbalis", "pterygoid plexus", "rete", "rete testis", "structure"],
    "plexus dentalis": ["nerve plexus"],
    "pliability": ["adaptability", "pliancy", "pliantness", "suppleness"],
    "pliancy": ["bendability", "pliability", "pliantness", "suppleness"],
    "plication": ["fold", "folding", "pleating"],
    "plicatoperipatus": ["arthropod genus", "genus plicatoperipatus"],
    "plicatoperipatus jamaicensis": ["onychophoran", "peripatus", "velvet worm"],
    "plier": ["plyer", "worker"],
    "pliers": ["compound lever", "hand tool", "locking pliers", "needlenose pliers", "pair of pliers", "plyers", "pump-type pliers", "rib joint pliers", "slip-joint pliers"],
    "plight": ["assurance", "pledge", "troth"],
    "plimsoll": ["gym shoe", "sneaker", "tennis shoe"],
    "plinian eruption": ["eruption", "volcanic eruption"],
    "pliny": ["gaius plinius caecilius secundus", "pliny the younger"],
    "pliocene": ["pliocene epoch"],
    "ploce": ["repetition"],
    "ploceidae": ["bird family", "family ploceidae"],
    "ploceus": ["bird genus", "genus ploceus"],
    "plodder": ["drudge", "hack", "hacker", "slogger"],
    "plodding": ["plod", "walk", "walking"],
    "ploddingly": [],
    "plonk": ["vino", "wine"],
    "plonk down": ["drop", "plank down", "plump down"],
    "plop": ["drop"],
    "plosion": ["explosion", "release", "tone ending"],
    "plot": ["contrive", "design", "plan", "project"],
    "plot element": ["component", "constituent", "element", "factor", "ingredient", "macguffin", "mcguffin"],
    "plotinus": [],
    "plott hound": ["hound", "hound dog"],
    "plotter": ["clerk", "mapper"],
    "ploughman's lunch": ["meal", "repast"],
    "plovdiv": ["philippopolis"],
    "plover": ["charadrius melodus", "charadrius morinellus", "charadrius vociferus", "dotrel", "dotterel", "eudromias morinellus", "golden plover", "green plover", "kildeer", "killdeer", "killdeer plover", "lapwing", "limicoline bird", "peewit", "pewit", "piping plover", "shore bird", "shorebird", "turnstone"],
    "plow": ["go", "locomote", "move", "plough", "travel"],
    "plow horse": ["plough horse", "workhorse"],
    "plowboy": ["boy", "male child", "ploughboy"],
    "plowed": ["ploughed"],
    "plowing": ["ploughing", "tilling"],
    "plowman": ["farm worker", "farmhand", "field hand", "fieldhand", "ploughman", "plower"],
    "plowshare": ["ploughshare", "share", "wedge"],
    "plowwright": ["ploughwright", "wright"],
    "ploy": ["gambit", "maneuver", "manoeuvre", "stratagem", "tactical maneuver", "tactical manoeuvre"],
    "pluck": ["draw", "force", "pick off", "pull", "pull off", "tweak", "tweeze"],
    "plucked": [],
    "pluckily": [],
    "plug": ["chink", "close", "cork", "cork up", "fill up", "secure", "stop up", "stopper", "stopple", "tampon"],
    "plug away": ["keep one's nose to the grindstone", "keep one's shoulder to the wheel", "peg away", "slog", "work"],
    "plug fuse": ["electrical fuse", "fuse", "safety fuse"],
    "plug in": ["connect", "enter", "infix", "insert", "introduce", "plug into"],
    "plugged": [],
    "plughole": ["hole"],
    "plum": ["big-tree plum", "bullace", "canada plum", "cherry plum", "common plum", "fruit tree", "japanese plum", "myrobalan", "myrobalan plum", "pacific plum", "plum tree", "prunus cerasifera", "prunus domestica", "prunus insititia", "prunus mexicana", "prunus nigra", "prunus salicina", "prunus subcordata", "sierra plum", "wild plum", "wild plum tree"],
    "plum pudding": ["christmas pudding", "pudding"],
    "plum sauce": ["sauce"],
    "plum tomato": ["cherry tomato", "lycopersicon esculentum cerasiforme"],
    "plum-fruited yew": ["conifer", "coniferous tree", "prumnopitys andina", "prumnopitys elegans"],
    "plum-yew": ["conifer", "coniferous tree"],
    "plumaged": [],
    "plumate": ["plumed", "plumose"],
    "plumb": ["burden", "burthen", "weight", "weight down"],
    "plumb bob": ["bob", "plumb", "plummet"],
    "plumb level": ["carpenter's level"],
    "plumb line": ["cord", "lead line", "perpendicular", "plumb rule", "sounding line"],
    "plumb rule": ["perpendicular", "plumb line"],
    "plumbaginaceae": ["dicot family", "family plumbaginaceae", "leadwort family", "magnoliopsid family", "sea-lavender family"],
    "plumbaginaceous": [],
    "plumbaginales": ["order plumbaginales", "plant order"],
    "plumbago": ["herb", "herbaceous plant"],
    "plumber": ["artificer", "artisan", "craftsman", "journeyman", "pipe fitter"],
    "plumber's snake": ["auger", "hand tool", "snake"],
    "plumbic": ["plumbous"],
    "plumbing": ["plumbing system", "utility"],
    "plumbing fixture": ["can", "commode", "crapper", "fixture", "fount", "fountain", "hydrant", "pot", "potty", "shower", "sink", "stool", "tap", "throne", "toilet", "urinal", "water faucet", "water tap"],
    "plumcot": ["fruit tree", "plumcot tree"],
    "plume": ["bedeck", "bedight", "deck"],
    "plume grass": ["erianthus ravennae", "grass", "ravenna grass", "wool grass"],
    "plume poppy": ["bocconia", "macleaya cordata", "poppy"],
    "plume thistle": ["boar thistle", "brook thistle", "bull thistle", "canada thistle", "cirsium arvense", "cirsium flodmanii", "cirsium lanceolatum", "cirsium rivulare", "cirsium vulgare", "creeping thistle", "plumed thistle", "spear thistle", "thistle", "woolly thistle"],
    "plume-tipped": [],
    "plumed": ["plumy"],
    "plumed scorpionfish": ["scorpaena grandicornis", "scorpion fish", "scorpionfish", "sea scorpion"],
    "plumed tussock": ["arundo richardii", "cortaderia richardii", "grass", "toe toe", "toetoe"],
    "plumelike": ["plumy"],
    "plumeria": ["dicot genus", "genus plumeria", "magnoliopsid genus", "plumiera"],
    "plumlike": [],
    "plummet": ["drop", "plump"],
    "plummy": [],
    "plump": ["choose", "go", "pick out", "select", "take"],
    "plump in": ["arrive", "come", "get"],
    "plump out": ["depart", "quit", "take leave"],
    "plumping": [],
    "plumpness": ["buxomness", "chubbiness", "corpulency", "embonpoint", "fleshiness", "obesity", "pudginess", "rolypoliness", "roundness", "tubbiness"],
    "plumule": ["down", "down feather"],
    "plunder": ["deplume", "despoil", "displume", "foray", "loot", "pillage", "ransack", "reave", "rifle", "strip", "take"],
    "plunderage": ["defalcation", "embezzlement", "misapplication", "misappropriation", "peculation"],
    "plunderer": ["buccaneer", "despoiler", "freebooter", "looter", "pillager", "pirate", "raider", "sea robber", "sea rover", "spoiler", "stealer", "thief"],
    "plundering": ["aggression", "banditry", "depredation", "despoilation", "despoilment", "despoliation", "devastation", "hostility", "looting", "pillage", "pillaging", "predation", "rape", "rapine", "ravaging", "robbery", "sack", "spoil", "spoilation", "spoliation"],
    "plunge": ["drop", "dump"],
    "plunger": ["hand tool", "plumber's helper"],
    "plunk": ["sound"],
    "pluperfect": [],
    "plural": ["descriptor", "form", "plural form", "signifier", "word form"],
    "pluralism": ["social organisation", "social organization", "social structure", "social system", "structure"],
    "pluralist": ["churchman", "cleric", "divine", "ecclesiastic"],
    "pluralistic": [],
    "plurality": ["state"],
    "pluralization": ["inflection", "inflexion", "pluralisation"],
    "pluralize": ["inflect", "pluralise"],
    "plus": [],
    "plus fours": ["breeches", "knee breeches", "knee pants", "knickerbockers", "knickers"],
    "plus sign": ["sign"],
    "plush": ["cloth", "fabric", "material", "textile"],
    "plushy": ["plush-like"],
    "plutarch": [],
    "pluteaceae": ["family pluteaceae", "fungus family"],
    "pluteus": ["fungus genus", "genus pluteus", "roof mushroom"],
    "pluteus aurantiorugosus": ["agaric"],
    "pluteus magnus": ["agaric", "sawdust mushroom"],
    "pluto": [],
    "plutocracy": ["form of government", "political system"],
    "plutocrat": ["have", "rich person", "wealthy person"],
    "plutocratic": ["plutocratical"],
    "plutonium": ["atomic number 94", "chemical element", "element", "plutonium 239", "pu"],
    "plutonium 239": ["atomic number 94", "plutonium", "pu", "weapon-grade plutonium", "weapons plutonium"],
    "plutonium trigger": ["plutonium pit", "trigger"],
    "pluvialis": ["bird genus", "genus pluvialis"],
    "pluvianus": ["bird genus", "genus pluvianus"],
    "pluviose": ["revolutionary calendar month"],
    "ply": ["do", "perform"],
    "plymouth": [],
    "plymouth colony": [],
    "plymouth rock": [],
    "plywood": ["laminate", "plyboard"],
    "pneumatic": [],
    "pneumatic drill": ["power drill"],
    "pneumatic tire": ["flat", "flat tire", "pneumatic tyre", "radial", "radial tire", "radial-ply tire", "snow tire", "tire", "tubeless", "tubeless tire", "tyre"],
    "pneumatically": [],
    "pneumatics": ["mechanics"],
    "pneumatophore": ["root"],
    "pneumococcal": [],
    "pneumococcal pneumonia": ["pneumonia"],
    "pneumococcal vaccine": ["pneumovax", "vaccine", "vaccinum"],
    "pneumococcus": ["diplococcus", "diplococcus pneumoniae"],
    "pneumoconiosis": ["anthracosis", "asbestosis", "black lung", "black lung disease", "coal miner's lung", "pneumonoconiosis", "respiratory disease", "respiratory disorder", "respiratory illness", "siderosis", "silicosis"],
    "pneumocytosis": ["interstitial plasma cell pneumonia", "pneumocystis carinii pneumonia", "pneumocystis pneumonia", "pneumonia"],
    "pneumogastric": [],
    "pneumonectomy": ["ablation", "cutting out", "excision", "extirpation"],
    "pneumonia": ["bronchial pneumonia", "bronchopneumonia", "interstitial plasma cell pneumonia", "lobar pneumonia", "pleuropneumonia", "pneumococcal pneumonia", "pneumocystis carinii pneumonia", "pneumocystis pneumonia", "pneumocytosis", "respiratory disease", "respiratory disorder", "respiratory illness", "viral pneumonia"],
    "pneumonic": [],
    "pneumonic plague": ["pest", "pestilence", "pestis", "plague", "plague pneumonia", "pulmonic plague"],
    "pneumonitis": ["inflammation", "redness", "rubor"],
    "pneumothorax": ["abnormalcy", "abnormality"],
    "po": ["po river"],
    "po-faced": [],
    "poa": ["genus poa", "liliopsid genus", "monocot genus"],
    "poach": ["hunt", "hunt down", "run", "track down"],
    "poached egg": ["dish", "dropped egg"],
    "poacher": ["appropriator"],
    "poaching": ["cookery", "cooking", "preparation"],
    "pobeda peak": ["pobedy peak"],
    "pocahontas": ["matoaka", "rebecca rolfe"],
    "pocatello": [],
    "pochard": ["aythya ferina", "duck"],
    "pock": ["pustule"],
    "pocked": ["pockmarked", "potholed"],
    "pocket": ["bag", "steal"],
    "pocket battleship": ["battleship", "battlewagon"],
    "pocket borough": ["borough"],
    "pocket dictionary": ["dictionary", "lexicon", "little dictionary"],
    "pocket flap": ["flap"],
    "pocket money": ["cash", "hard cash", "hard currency", "pin money", "spending money"],
    "pocket mouse": ["hispid pocket mouse", "liomys irroratus", "mexican pocket mouse", "perognathus flavescens", "perognathus flavus", "perognathus hispidus", "plains pocket mouse", "pocket rat", "silky pocket mouse"],
    "pocket rat": ["desert rat", "dipodomys phillipsii", "dwarf pocket rat", "gopher", "kangaroo mouse", "kangaroo rat", "pocket gopher", "pocket mouse", "pouched rat", "rat"],
    "pocket veto": ["veto"],
    "pocket watch": ["ticker", "watch"],
    "pocket-handkerchief": ["handkerchief", "hankey", "hankie", "hanky"],
    "pocket-size": ["pocket-sized", "pocketable"],
    "pocketbook": ["means", "substance"],
    "pocketbook issue": ["bread-and-butter issue", "issue"],
    "pocketcomb": ["comb", "pocket comb"],
    "pocketed bat": ["free-tailed bat", "freetail", "freetailed bat", "pocketed freetail bat", "tadirida femorosacca"],
    "pocketful": ["containerful"],
    "pocketknife": ["clasp knife", "flick knife", "flick-knife", "jackknife", "knife", "penknife", "pocket knife", "switchblade", "switchblade knife"],
    "pockmark": ["mark", "pit", "pock", "scar"],
    "pod": ["shell"],
    "podalgia": ["hurting", "pain"],
    "podalyria": ["genus podalyria", "rosid dicot genus"],
    "podargidae": ["bird family", "family podargidae"],
    "podargus": ["bird genus", "genus podargus"],
    "podaxaceae": ["gasteromycete", "gastromycete", "stalked puffball"],
    "podcast": ["broadcast", "circularise", "circularize", "circulate", "diffuse", "disperse", "disseminate", "distribute", "pass around", "propagate", "spread"],
    "podetium": ["enation", "plant process", "seta"],
    "podiatry": ["chiropody", "medical specialty", "medicine"],
    "podiceps": ["bird genus", "genus podiceps"],
    "podicipedidae": ["bird family", "family podicipedidae"],
    "podicipitiform seabird": ["grebe", "sea bird", "seabird", "seafowl"],
    "podicipitiformes": ["animal order", "colymbiformes", "order colymbiformes", "order podicipediformes", "order podicipitiformes", "podicipediformes"],
    "podilymbus": ["bird genus", "genus podilymbus"],
    "podlike": [],
    "podocarp": ["conifer", "coniferous tree"],
    "podocarpaceae": ["family podocarpaceae", "gymnosperm family", "podocarpus family"],
    "podocarpus": ["genus podocarpus", "gymnosperm genus"],
    "podophyllum": ["genus podophyllum", "magnoliid dicot genus"],
    "podzol": ["dirt", "podsol", "podsol soil", "podsolic soil", "podzol soil", "soil"],
    "poe": ["edgar allan poe"],
    "poeciliidae": ["family poeciliidae", "fish family"],
    "poecilocapsus": ["arthropod genus", "genus poecilocapsus"],
    "poecilogale": ["genus poecilogale", "mammal genus"],
    "poem": ["abecedarius", "alcaic", "alcaic verse", "ballad", "ballade", "blank verse", "elegy", "epic", "epic poem", "epos", "free verse", "haiku", "heroic poem", "lament", "lay", "literary composition", "literary work", "lyric", "lyric poem", "rhyme", "rondeau", "rondel", "sonnet", "tanka", "terza rima", "vers libre", "verse", "verse form", "versicle"],
    "poephila": ["bird genus", "genus poephila"],
    "poet": ["author", "bard", "elegist", "odist", "poet laureate", "poetess", "sonneteer", "writer"],
    "poet laureate": ["poet"],
    "poetess": ["poet"],
    "poetic": [],
    "poetic justice": ["final result", "just deserts", "outcome", "result", "resultant", "termination"],
    "poetic license": ["licence", "license"],
    "poetic rhythm": ["beat", "cadence", "measure", "meter", "metre", "prosody", "rhythmic pattern", "sprung rhythm", "versification"],
    "poetically": [],
    "poetics": ["literary study", "metrics", "prosody"],
    "poetry": ["expressive style", "style"],
    "pogge": ["agonus cataphractus", "armed bullhead", "poacher", "sea poacher", "sea poker"],
    "pogo stick": ["plaything", "toy"],
    "pogonia": ["orchid", "orchidaceous plant"],
    "pogonion": ["craniometric point"],
    "pogonophora": ["phylum", "phylum pogonophora"],
    "pogostemon": ["asterid dicot genus", "genus pogostemon"],
    "pogrom": ["persecution"],
    "poi": ["dish"],
    "poignance": ["poignancy", "sadness", "sorrow", "sorrowfulness"],
    "poignant": [],
    "poikilotherm": ["animal", "animate being", "beast", "brute", "creature", "ectotherm", "fauna"],
    "poikilothermic": ["ectothermic", "heterothermic", "poikilothermous"],
    "poilu": ["soldier"],
    "poinciana": ["rosid dicot genus", "subgenus poinciana"],
    "poinsettia": ["christmas flower", "christmas star", "euphorbia pulcherrima", "lobster plant", "mexican flameleaf", "painted leaf", "spurge"],
    "point": ["label", "mark", "tag"],
    "point after": ["conversion", "extra point", "point", "point after touchdown"],
    "point duty": ["traffic control"],
    "point jam": ["block", "jam"],
    "point lace": ["lace", "needlepoint"],
    "point man": ["leader"],
    "point mutation": ["chromosomal mutation", "gene mutation", "genetic mutation", "mutation"],
    "point of honor": ["concern"],
    "point of order": ["order", "parliamentary law", "parliamentary procedure", "rules of order"],
    "point of view": ["angle", "cityscape", "complexion", "landscape", "position", "posture", "slant", "stance", "stand", "standpoint", "viewpoint"],
    "point source": ["beginning", "origin", "root", "rootage", "source"],
    "point system": ["metric", "system of measurement"],
    "point the way": ["direct"],
    "point up": ["accent", "accentuate", "emphasise", "emphasize", "punctuate", "stress"],
    "point woman": ["leader"],
    "point-and-shoot camera": ["camera", "photographic camera"],
    "point-blank": [],
    "point-of-sale": [],
    "pointed": [],
    "pointed arch": ["arch", "drop arch", "gothic arch", "keel arch", "ogee arch", "trefoil arch"],
    "pointed-leaf maple": ["acer argutum", "maple"],
    "pointedly": [],
    "pointedness": ["directness", "straightness"],
    "pointer": ["electronic stylus", "hand", "indicator", "light pen", "needle"],
    "pointillism": ["art movement", "artistic movement", "school"],
    "pointillist": ["painter"],
    "pointing out": ["indicant", "indication"],
    "pointing trowel": ["trowel"],
    "pointless": ["unpointed"],
    "pointlessly": [],
    "pointsman": ["traffic cop"],
    "pointy-toed": ["pointed-toe"],
    "poise": ["hover"],
    "poised": [],
    "poison": ["corrupt", "debase", "debauch", "demoralise", "demoralize", "deprave", "misdirect", "pervert", "profane", "subvert", "vitiate"],
    "poison ash": ["poison dogwood", "poison sumac", "poisonous plant", "rhus vernix", "toxicodendron vernix"],
    "poison bush": ["bush", "gastrolobium", "poison pea", "shrub"],
    "poison camas": ["death camas", "zigadene", "zigadenus nuttalli"],
    "poison gas": ["blistering agent", "chemical weapon", "dichloroethyl sulfide", "gas", "mustard agent", "mustard gas", "nerve agent", "nerve gas", "sulfur mustard"],
    "poison ivy": ["rhus dermatitis"],
    "poison milkweed": ["asclepias subverticillata", "horsetail milkweed", "milkweed", "silkweed"],
    "poison oak": ["rhus dermatitis"],
    "poison pill": ["porcupine provision", "shark repellent", "suicide pill"],
    "poison sumac": ["rhus dermatitis"],
    "poisoner": ["killer", "slayer"],
    "poisoning": ["alkali poisoning", "caffeine intoxication", "caffeinism", "carbon monoxide poisoning", "cyanide poisoning", "ergotism", "intoxication", "mercury poisoning", "naphthalene poisoning", "nicotine poisoning", "ophidism", "paraquat poisoning", "pesticide poisoning", "physical condition", "physiological condition", "physiological state", "salicylate poisoning", "toxic condition"],
    "poisonous": ["toxicant"],
    "poisonous parasol": ["lepiota", "lepiota morgani"],
    "poisonous plant": ["aconite", "aethusa cynapium", "american holly", "baneberry", "california fern", "chinese lacquer tree", "christmas holly", "cicuta verosa", "climbing lily", "cohosh", "common snowberry", "conium maculatum", "creeping lily", "dogbane", "eastern poison oak", "flora", "fool's parsley", "gloriosa", "gloriosa superba", "glory lily", "hellebore", "hemlock", "hemlock water dropwort", "herb christopher", "japanese lacquer tree", "japanese sumac", "japanese varnish tree", "lacquer tree", "lantana", "lesser hemlock", "markweed", "nebraska fern", "nerium oleander", "oenanthe aquatica", "oenanthe crocata", "oleander", "plant", "plant life", "poison ash", "poison dogwood", "poison hemlock", "poison ivy", "poison mercury", "poison oak", "poison parsley", "poison sumac", "rhus diversiloba", "rhus quercifolia", "rhus radicans", "rhus toxicodenedron", "rhus verniciflua", "rhus vernix", "rose bay", "snowberry", "spotted cowbane", "spotted hemlock", "spotted water hemlock", "symphoricarpos alba", "toxicodendron diversilobum", "toxicodendron quercifolium", "toxicodendron radicans", "toxicodendron vernicifluum", "toxicodendron vernix", "varnish tree", "water dropwort", "water fennel", "water hemlock", "waxberry", "western poison oak", "winter fern"],
    "poisonously": ["venomously"],
    "poisson distribution": ["distribution", "statistical distribution"],
    "poitier": ["sidney poitier"],
    "poitiers": ["battle of poitiers"],
    "poitou-charentes": ["poitou"],
    "poke": ["agitate", "commove", "disturb", "raise up", "shake up", "stir up", "vex"],
    "poke check": ["check"],
    "poke into": ["penetrate", "perforate"],
    "poke milkweed": ["asclepias exaltata", "milkweed", "silkweed"],
    "poker": ["fire hook", "fire iron", "salamander", "stove poker"],
    "poker alumroot": ["alumbloom", "alumroot", "heuchera cylindrica", "poker heuchera"],
    "poker face": ["countenance", "visage"],
    "poker hand": ["deal", "flush", "full house", "hand", "pair", "royal flush", "straight", "straight flush"],
    "poker plant": ["flame flower", "flame-flower", "flameflower", "kniphofia", "kniphofia praecox", "kniphofia uvaria", "red-hot poker", "tritoma"],
    "pokeweed": ["bella sombra", "garget", "herb", "herbaceous plant", "indian poke", "ombu", "phytolacca acinosa", "phytolacca americana", "phytolacca dioica", "pigeon berry", "poke", "scoke"],
    "pokomo": ["bantoid language", "bantu"],
    "polack": ["pole"],
    "poland": ["polska", "republic of poland"],
    "polanisia": ["dilleniid dicot genus", "genus polanisia"],
    "polar": [],
    "polar body": ["cell"],
    "polar circle": ["latitude", "line of latitude", "parallel", "parallel of latitude"],
    "polar coordinate": ["co-ordinate", "coordinate"],
    "polar glacier": ["continental glacier"],
    "polar hare": ["arctic hare", "hare", "lepus arcticus"],
    "polar opposition": ["gradable opposition"],
    "polarimeter": ["optical device", "polariscope"],
    "polaris": ["north star", "polar star", "pole star", "polestar"],
    "polarity": ["negativeness", "negativity", "oppositeness", "opposition", "positiveness", "positivity", "sign"],
    "polarization": ["condition", "polarisation", "status"],
    "polarize": ["alter", "change", "modify", "polarise"],
    "polarographic": [],
    "polarography": ["chemical analysis", "qualitative analysis"],
    "polaroid": ["film", "plastic film"],
    "polaroid camera": ["camera", "photographic camera", "polaroid land camera"],
    "polder": ["ground", "land", "soil"],
    "pole": ["hold", "hold up", "support", "sustain"],
    "pole bean": ["bean", "bean plant", "dutch case-knife bean", "phaseolus coccineus", "phaseolus multiflorus", "runner bean", "scarlet runner", "scarlet runner bean"],
    "pole horse": ["trotter", "trotting horse"],
    "pole position": ["place", "position"],
    "pole vault": ["field event", "pole jump", "pole jumping", "pole vaulting"],
    "poleax": ["cut down", "drop", "fell", "poleaxe", "strike down"],
    "polecat": ["ferret", "fitch", "foulmart", "foumart", "mustela putorius", "mustelid", "musteline", "musteline mammal"],
    "polemic": ["arguing", "argument", "contention", "contestation", "controversy", "disceptation", "disputation", "tilt"],
    "polemicist": ["author", "polemic", "polemist", "writer"],
    "polemics": ["christian theology"],
    "polemize": ["altercate", "argufy", "dispute", "polemicise", "polemicize", "polemise", "quarrel", "scrap"],
    "polemoniaceae": ["asterid dicot family", "family polemoniaceae", "phlox family"],
    "polemoniaceous": [],
    "polemoniales": ["order polemoniales", "plant order"],
    "polemonium": ["charity", "greek valerian", "herb", "herbaceous plant", "jacob's ladder", "northern jacob's ladder", "polemonium boreale", "polemonium caeruleum", "polemonium reptans", "polemonium van-bruntiae", "polemonium viscosum", "polymonium caeruleum van-bruntiae", "skunk-weed", "skunkweed"],
    "polenta": ["cornmeal mush", "mush"],
    "polianthes": ["genus polianthes", "liliid monocot genus"],
    "police": ["constabulary", "european law enforcement organisation", "europol", "force", "gendarmerie", "gendarmery", "law", "law enforcement agency", "mounties", "mutawa", "mutawa'een", "new scotland yard", "personnel", "police force", "posse", "posse comitatus", "rcmp", "royal canadian mounted police", "schutzstaffel", "scotland yard", "secret police", "ss"],
    "police academy": ["academy"],
    "police action": ["action", "military action"],
    "police boat": ["boat"],
    "police commissioner": ["commissioner"],
    "police court": ["court", "judicature", "tribunal"],
    "police department": ["department of local government", "local department"],
    "police dog": ["working dog"],
    "police matron": ["meter maid", "officer", "police officer", "policeman", "policewoman"],
    "police precinct": ["precinct"],
    "police sergeant": ["buck sergeant", "desk sergeant", "deskman", "law officer", "lawman", "peace officer", "sergeant", "station keeper"],
    "police squad": ["platoon", "special weapons and tactics squad", "special weapons and tactics team", "squad", "swat squad", "swat team", "team", "vice squad"],
    "police state": ["absolutism", "authoritarianism", "caesarism", "despotism", "dictatorship", "monocracy", "one-man rule", "shogunate", "stalinism", "totalitarianism", "tyranny"],
    "police station": ["police headquarters", "station", "station house"],
    "police van": ["black maria", "paddy wagon", "patrol wagon", "police wagon", "van", "wagon"],
    "police work": ["detecting", "detection", "detective work", "forensics", "investigating", "investigation", "police investigation", "roundup", "sleuthing", "surveillance"],
    "policeman": ["bobby", "bull", "captain", "constable", "cop", "copper", "detective", "fuzz", "gendarme", "inspector", "investigator", "law officer", "lawman", "motorcycle cop", "motorcycle policeman", "mountie", "officer", "peace officer", "pig", "police captain", "police chief", "police constable", "police detective", "police matron", "police officer", "policewoman", "shoofly", "speed cop", "state trooper", "tec", "traffic cop", "trooper"],
    "policeman bird": ["black-necked stork", "jabiru", "stork", "xenorhyncus asiaticus"],
    "policy": ["argument", "argumentation", "clericalism", "economic policy", "foreign policy", "line", "line of reasoning", "logical argument", "party line", "plank", "social policy", "zero-tolerance policy", "zionism"],
    "policy maker": ["important person", "influential person", "personage"],
    "policy-making": [],
    "policyholder": ["client", "customer", "holder"],
    "poliomyelitis": ["acute anterior poliomyelitis", "infantile paralysis", "infectious disease", "polio"],
    "polioptila": ["bird genus", "genus polioptila"],
    "poliosis": ["depigmentation"],
    "poliovirus": ["enterovirus"],
    "poliovirus vaccine": ["ipv", "opv", "oral poliovirus vaccine", "sabin vaccine", "salk vaccine", "topv", "trivalent live oral poliomyelitis vaccine", "vaccine", "vaccinum"],
    "polish": ["beautify", "buff", "burnish", "embellish", "fancify", "furbish", "gloss", "prettify", "shine", "simonise", "simonize", "sleek", "slick", "smooth", "smoothen"],
    "polish monetary unit": ["grosz", "monetary unit", "zloty"],
    "polished": ["refined", "svelte", "urbane"],
    "polistes": ["arthropod genus", "genus polistes"],
    "polistes annularis": ["paper wasp"],
    "politburo": ["commission", "committee"],
    "polite": [],
    "politely": ["courteously"],
    "politeness": ["courtesy", "good manners", "niceness"],
    "politic": [],
    "political": [],
    "political action committee": ["commission", "committee", "pac"],
    "political arena": ["area", "arena", "domain", "field", "orbit", "political sphere", "sphere"],
    "political campaign": ["campaign", "campaign for governor", "governor's race", "race", "run", "senate campaign", "senate race"],
    "political contribution": ["contribution", "donation", "political donation", "soft money"],
    "political correctness": ["correctness", "political correctitude"],
    "political dissident": ["contestant", "dissenter", "dissident", "objector", "protester"],
    "political incorrectness": ["incorrectness"],
    "political movement": ["foreign terrorist organization", "front", "fto", "movement", "palestine liberation organization", "plo", "red guard", "sinn fein", "social movement", "syndicalism", "terrorist group", "terrorist organization"],
    "political orientation": ["absolutism", "anarchism", "autocracy", "centrism", "collectivism", "communism", "conservatism", "conservativism", "constitutionalism", "democracy", "domino theory", "dovishness", "elitism", "extremism", "fascism", "federalism", "hawkishness", "ideology", "imperialism", "leftism", "liberalism", "libertarianism", "meritocracy", "moderatism", "monarchism", "negritude", "orientation", "orleanism", "political theory", "progressivism", "radicalism", "reactionism", "republicanism", "rightism", "segregationism", "social democracy", "socialism", "theocracy", "totalism", "totalitarianism", "utopianism"],
    "political prisoner": ["captive", "prisoner"],
    "political scientist": ["social scientist"],
    "political system": ["autarchy", "autocracy", "commonwealth", "constitutionalism", "democracy", "diarchy", "dyarchy", "form of government", "gerontocracy", "gynarchy", "gynecocracy", "hegemony", "mobocracy", "ochlocracy", "oligarchy", "plutocracy", "republic", "social group", "technocracy", "theocracy"],
    "political unit": ["amphictyony", "body politic", "cadre", "cell", "commonwealth", "country", "holy roman empire", "land", "lobby", "lunatic fringe", "nation", "palestine authority", "palestine national authority", "palestinian national authority", "political entity", "pressure group", "res publica", "revolutionary group", "social unit", "state", "third house", "union", "unit"],
    "politically": [],
    "politically correct": [],
    "politically incorrect": [],
    "politician": ["plotter", "schemer"],
    "politicize": ["alter", "change", "modify", "politicise"],
    "politick": ["engage", "logroll", "prosecute", "pursue"],
    "politics": ["political relation", "social relation"],
    "polity": ["authorities", "government", "organisation", "organization", "regime"],
    "polk": ["james k. polk", "james knox polk", "james polk", "president polk"],
    "polka": ["dance", "trip the light fantastic", "trip the light fantastic toe"],
    "polka dot": ["design", "figure", "pattern"],
    "poll": ["vote"],
    "poll tax": ["capitation"],
    "pollachius": ["fish genus", "genus pollachius"],
    "pollack": ["sydney pollack"],
    "pollard": ["tree"],
    "pollen": ["pollinium", "ragweed pollen", "spore"],
    "pollen count": ["count"],
    "pollen tube": ["plant part", "plant structure"],
    "pollinate": ["cross-pollinate", "fecundate", "fertilise", "fertilize", "inseminate", "pollenate"],
    "pollination": ["cross-pollination", "fecundation", "fertilisation", "fertilization", "impregnation", "pollenation", "self-pollination"],
    "pollinator": ["insect"],
    "polling booth": ["booth", "cubicle", "kiosk", "stall"],
    "polling day": ["day", "election day"],
    "polling place": ["place", "polling station", "spot", "topographic point"],
    "pollinium": ["pollen"],
    "pollock": ["jackson pollock"],
    "polls": ["place", "position"],
    "pollster": ["asker", "canvasser", "enquirer", "headcounter", "inquirer", "poll taker", "querier", "questioner"],
    "pollucite": ["mineral"],
    "pollutant": ["cfc", "chlorofluorocarbon", "ddt", "dichlorodiphenyltrichloroethane", "halon", "nitrogen oxide", "sulfur dioxide", "sulphur dioxide", "waste", "waste material", "waste matter", "waste product"],
    "pollute": ["begrime", "bemire", "colly", "contaminate", "dirty", "foul", "grime", "infect", "soil", "taint"],
    "polluter": ["bad person", "defiler"],
    "pollution": ["air pollution", "biodegradable pollution", "environmental condition", "impureness", "impurity", "noise pollution", "nonbiodegradable pollution", "sound pollution", "thermal pollution", "water pollution"],
    "pollux": [],
    "polo": ["marco polo"],
    "polo ball": ["ball"],
    "polo mallet": ["mallet", "polo stick", "stick"],
    "polo pony": ["equus caballus", "horse"],
    "polo shirt": ["shirt", "sport shirt"],
    "polonaise": ["dress", "frock"],
    "polonium": ["atomic number 84", "metal", "metallic element", "po"],
    "polony": ["bologna", "bologna sausage"],
    "poltergeist": ["ghost"],
    "poltroon": ["coward", "craven", "recreant"],
    "poltroonery": ["pusillanimity", "pusillanimousness"],
    "polyamide": ["nylon", "polymer", "polymeric amide"],
    "polyandrist": ["polygamist"],
    "polyandrous": [],
    "polyandry": ["polygamy"],
    "polyangiaceae": ["bacteria family", "family myxobacteriaceae", "family polyangiaceae", "myxobacteriaceae"],
    "polyangium": ["bacteria genus", "genus polyangium"],
    "polyanthus": ["primrose", "primula", "primula polyantha"],
    "polyarteritis": ["arteritis"],
    "polyatomic": [],
    "polyborus": ["bird genus", "genus polyborus"],
    "polybotrya": ["fern genus", "genus polybotria", "genus polybotrya", "polybotria"],
    "polybutylene": ["butene", "butylene", "polybutene"],
    "polycarp": ["martyr", "saint polycarp", "st. polycarp"],
    "polychaeta": ["class", "class polychaeta"],
    "polychaete": ["annelid", "annelid worm", "bloodworm", "lobworm", "lug", "lugworm", "polychaete worm", "polychete", "polychete worm", "sea mouse", "segmented worm"],
    "polychromatic": ["polychrome", "polychromic"],
    "polychrome": ["color", "color in", "colorise", "colorize", "colour", "colour in", "colourise", "colourize", "polychromise", "polychromize"],
    "polycirrus": ["genus polycirrus", "worm genus"],
    "polyconic projection": ["conic projection", "conical projection"],
    "polycrystalline": [],
    "polycystic kidney disease": ["kidney disease", "nephropathy", "nephrosis", "pkd", "renal disorder"],
    "polycythemia": ["blood disease", "blood disorder"],
    "polydactyl": ["polydactylous"],
    "polydactylus": ["fish genus", "genus polydactylus"],
    "polydactyly": ["birth defect", "congenital abnormality", "congenital anomaly", "congenital defect", "congenital disorder", "hyperdactyly"],
    "polydipsia": ["thirst", "thirstiness"],
    "polyelectrolyte": ["electrolyte"],
    "polyergus": ["arthropod genus", "genus polyergus"],
    "polyester": ["polyester fiber", "synthetic resin"],
    "polyester fiber": ["polyester"],
    "polyestrous": ["polyoestrous"],
    "polyethylene": ["polythene", "synthetic resin"],
    "polyfoam": ["polyurethan", "polyurethane", "polyurethane foam"],
    "polygala": ["genus polygala", "rosid dicot genus"],
    "polygalaceae": ["family polygalaceae", "milkwort family", "rosid dicot family"],
    "polygamist": ["better half", "married person", "mate", "partner", "polyandrist", "polygynist", "spouse"],
    "polygamous": [],
    "polygamy": ["marriage", "matrimony", "polyandry", "polygyny", "spousal relationship", "union", "wedlock"],
    "polygene": ["cistron", "factor", "gene"],
    "polygenic": [],
    "polygenic disorder": ["congenital disease", "diabetes", "genetic abnormality", "genetic defect", "genetic disease", "genetic disorder", "hereditary condition", "hereditary disease", "inherited disease", "inherited disorder", "polygenic disease"],
    "polyglot": [],
    "polygon": ["concave polygon", "convex polygon", "decagon", "dodecagon", "heptagon", "hexagon", "isogon", "nonagon", "octagon", "pentagon", "plane figure", "polygonal shape", "quadrangle", "quadrilateral", "spherical polygon", "tetragon", "triangle", "trigon", "trilateral", "two-dimensional figure", "undecagon"],
    "polygonaceae": ["buckwheat family", "dicot family", "family polygonaceae", "magnoliopsid family"],
    "polygonal": [],
    "polygonales": ["order polygonales", "plant order"],
    "polygonally": [],
    "polygonatum": ["genus polygonatum", "liliid monocot genus"],
    "polygonia": ["arthropod genus", "genus polygonia"],
    "polygonum": ["dicot genus", "genus polygonum", "magnoliopsid genus"],
    "polygraph": ["lie detector", "medical instrument"],
    "polygynist": ["polygamist"],
    "polygynous": [],
    "polygyny": ["polygamy"],
    "polyhedral": [],
    "polyhedral angle": ["angle"],
    "polyhedron": ["concave polyhedron", "convex polyhedron", "decahedron", "dodecahedron", "hexahedron", "icosahedron", "ideal solid", "octahedron", "pentahedron", "platonic body", "platonic solid", "prism", "prismatoid", "pyramid", "regular convex polyhedron", "regular convex solid", "regular polyhedron", "solid", "tetrahedron", "trapezohedron"],
    "polyhymnia": [],
    "polymastigina": ["animal order", "order polymastigina"],
    "polymastigote": ["flagellate", "flagellate protozoan", "flagellated protozoan", "mastigophoran", "mastigophore"],
    "polymath": ["initiate", "learned person", "pundit", "savant"],
    "polymer": ["chemical compound", "compound", "copolymer", "deoxyribonucleic acid", "desoxyribonucleic acid", "dna", "lignin", "polyamide", "polymeric amide", "polyurethan", "polyurethane", "ribonucleic acid", "rna", "silicone", "silicone polymer", "synthetic resin", "trimer"],
    "polymerase": ["dna polymerase", "enzyme", "reverse transcriptase", "rna polymerase", "transcriptase"],
    "polymeric": [],
    "polymerization": ["chemical action", "chemical change", "chemical process", "polymerisation"],
    "polymerize": ["change integrity", "polymerise"],
    "polymethyl methacrylate": ["acrylate resin", "acrylic", "acrylic resin", "lucite", "perspex", "plexiglas", "plexiglass"],
    "polymorph": ["being", "organism"],
    "polymorphemic": [],
    "polymorphic": ["polymorphous"],
    "polymorphism": ["organic phenomenon", "single nucleotide polymorphism", "snp"],
    "polymorphous": ["polymorphic"],
    "polymyositis": ["myositis"],
    "polymyxin": ["antibiotic", "antibiotic drug"],
    "polynemidae": ["family polynemidae", "fish family"],
    "polynesia": [],
    "polynesian": ["austronesian", "fijian", "samoan", "tahitian", "tongan"],
    "polynesian tattler": ["heteroscelus incanus", "tattler"],
    "polyneuritis": ["guillain-barre syndrome", "infectious polyneuritis", "landry's paralysis", "multiple neuritis", "neuritis"],
    "polynomial": ["biquadratic", "biquadratic polynomial", "function", "homogeneous polynomial", "map", "mapping", "mathematical function", "monic polynomial", "multinomial", "quadratic", "quadratic polynomial", "quartic polynomial", "series", "single-valued function"],
    "polynya": ["body of water", "water"],
    "polyodon": ["fish genus", "genus polyodon"],
    "polyodontidae": ["family polyodontidae", "fish family"],
    "polyoma": ["papovavirus", "polyoma virus"],
    "polyp": ["adenomatous polyp", "growth", "pedunculated polyp", "polypus", "sessile polyp"],
    "polypectomy": ["operation", "surgery", "surgical operation", "surgical procedure", "surgical process"],
    "polypedates": ["amphibian genus", "genus polypedates"],
    "polypedatidae": ["amphibian family", "family polypedatidae"],
    "polypeptide": ["peptide"],
    "polypetalous": [],
    "polyphemus moth": ["antheraea polyphemus", "saturniid", "saturniid moth"],
    "polyphone": ["alphabetic character", "letter", "letter of the alphabet", "polyphonic letter"],
    "polyphonic": [],
    "polyphonic prose": ["prose"],
    "polyphonically": [],
    "polyphony": ["concerted music", "counterpoint", "music", "polyphonic music"],
    "polyphosphate": ["salt"],
    "polyphosphoric acid": ["metaphosphoric acid", "oxyacid", "oxygen acid", "pyrophosphoric acid"],
    "polyplacophora": ["class", "class polyplacophora"],
    "polyploid": ["being", "organism"],
    "polyploidy": ["condition"],
    "polypodiaceae": ["family polypodiaceae", "fern family"],
    "polypodium": ["fern genus", "genus polypodium"],
    "polypody": ["adder's fern", "american wall fern", "coast polypody", "common polypody", "fern", "golden maidenhair", "golden polypody", "gray polypody", "grey polypody", "leatherleaf", "leathery polypody", "licorice fern", "polypodium glycyrrhiza", "polypodium polypodioides", "polypodium scouleri", "polypodium virgianum", "polypodium vulgare", "resurrection fern", "rock brake", "rock polypody", "sweet fern", "wall fern"],
    "polyporaceae": ["family polyporaceae", "fungus family"],
    "polypore": ["albatrellus dispansus", "albatrellus ovinus", "basidiomycete", "basidiomycetous fungi", "beefsteak fungus", "bracket fungus", "fistulina hepatica", "neolentinus ponderosus", "nigroporus vinosus", "oligoporus leucospongia", "polyporus squamosus", "polyporus tenuiculus", "pore fungus", "pore mushroom", "scaly polypore", "sheep polypore", "shelf fungus"],
    "polyporus": ["fungus genus", "genus polyporus"],
    "polyporus squamosus": ["polypore", "pore fungus", "pore mushroom", "scaly polypore"],
    "polyporus tenuiculus": ["polypore", "pore fungus", "pore mushroom"],
    "polyprion": ["fish genus", "genus polyprion"],
    "polypropenonitrile": ["acrilan", "acrylate resin", "acrylic", "acrylic resin"],
    "polypropylene": ["plastic", "polypropene"],
    "polyptoton": ["repetition"],
    "polysaccharide": ["amylum", "animal starch", "carbohydrate", "cellulose", "chitin", "dextrin", "glycogen", "heparin", "inulin", "lipo-hepin", "liquaemin", "mucopolysaccharide", "polyose", "saccharide", "starch", "sugar"],
    "polysemant": ["polysemantic word", "polysemous word", "word"],
    "polysemous": ["polysemantic"],
    "polysemy": ["ambiguity", "equivocalness", "lexical ambiguity"],
    "polysomy": ["birth defect", "congenital abnormality", "congenital anomaly", "congenital defect", "congenital disorder"],
    "polystichum": ["fern genus", "genus polystichum"],
    "polystyrene": ["cinnamene", "phenylethylene", "styrene", "styrofoam", "vinylbenzene"],
    "polysyllabic": [],
    "polysyllabically": [],
    "polysyllable": ["jawbreaker", "polysyllabic word", "sesquipedalia", "sesquipedalian", "word"],
    "polysyndeton": ["rhetorical device"],
    "polytechnic institute": ["engineering school", "polytechnic", "tech", "technical school"],
    "polytheism": ["theism", "tritheism"],
    "polytheist": ["theist"],
    "polytheistic": [],
    "polytonal": [],
    "polytonality": ["music", "polytonalism"],
    "polyunsaturated": [],
    "polyunsaturated fat": ["fat"],
    "polyunsaturated fatty acid": ["linoleic acid", "linolic acid", "omega-3", "omega-3 fatty acid", "omega-6", "omega-6 fatty acid", "unsaturated fatty acid"],
    "polyurethane": ["polyfoam", "polymer", "polyurethan", "polyurethane foam"],
    "polyuria": ["kidney disease", "nephropathy", "nephrosis", "renal disorder"],
    "polyvalence": ["multivalence", "multivalency", "polyvalency", "state"],
    "polyvalent": [],
    "polyvinyl acetate": ["polyvinyl resin", "pva", "vinyl polymer", "vinyl resin"],
    "polyvinyl chloride": ["polyvinyl resin", "pvc", "vinyl polymer", "vinyl resin"],
    "polyvinyl-formaldehyde": ["plastic"],
    "pomacanthus": ["fish genus", "genus pomacanthus"],
    "pomacentridae": ["family pomacentridae", "fish family"],
    "pomacentrus": ["fish genus", "genus pomacentrus"],
    "pomade": ["groom", "neaten"],
    "pomaded": [],
    "pomaderris": ["dicot genus", "genus pomaderris", "magnoliopsid genus"],
    "pomatomidae": ["family pomatomidae", "fish family"],
    "pomatomus": ["fish genus", "genus pomatomus"],
    "pome": ["apple", "false fruit", "fruit", "pear", "quince"],
    "pomegranate": ["fruit tree", "pomegranate tree", "punica granatum"],
    "pomelo": ["citrus", "citrus decumana", "citrus grandis", "citrus maxima", "citrus tree", "pomelo tree", "pummelo", "shaddock"],
    "pomeranian": ["spitz"],
    "pomfret": ["brama raii", "bream", "sea bream"],
    "pommel": ["grip", "handgrip", "handle", "hold"],
    "pommel horse": ["gymnastic horse", "horse", "side horse"],
    "pommy": ["english person", "pom"],
    "pomo": ["hoka", "hokan"],
    "pomolobus": ["fish genus", "genus pomolobus"],
    "pomologist": ["botanist", "phytologist", "plant scientist"],
    "pomology": ["botany", "phytology"],
    "pomoxis": ["fish genus", "genus pomoxis"],
    "pomp": ["eclat", "elegance"],
    "pompadour": ["style"],
    "pompano": ["saltwater fish"],
    "pompeii": [],
    "pompey": ["gnaeus pompeius magnus", "pompey the great"],
    "pompon": ["adornment", "pom-pom"],
    "pompous": ["ceremonious"],
    "pompously": [],
    "ponca": ["dhegiha", "ponka"],
    "ponce": ["adult male", "man"],
    "ponce de leon": ["juan ponce de leon", "navigator"],
    "poncho": ["cloak"],
    "poncirus": ["genus poncirus", "rosid dicot genus"],
    "pond": ["fishpond", "horsepond", "lake", "mere", "millpond", "pool", "swimming hole", "water hole"],
    "pond apple": ["annona glabra", "custard apple", "custard apple tree", "pond-apple tree"],
    "pond cypress": ["bald cypress", "cypress", "taxodium ascendens"],
    "pond pine": ["pine", "pine tree", "pinus serotina", "true pine"],
    "pond scum": ["chlorophyte", "green algae"],
    "pond-scum parasite": ["fungus"],
    "ponderable": [],
    "ponderosa": ["bull pine", "pinus ponderosa", "ponderosa pine", "western yellow pine", "yellow pine"],
    "ponderous": [],
    "ponderously": [],
    "ponderousness": ["heaviness", "uninterestingness"],
    "pondweed": ["aquatic plant", "curled leaf pondweed", "curly pondweed", "frog's lettuce", "horned pondweed", "hydrophyte", "hydrophytic plant", "loddon pondweed", "potamogeton americanus", "potamogeton crispus", "potamogeton gramineous", "potamogeton nodosus", "variously-leaved pondweed", "water plant", "zannichellia palustris"],
    "pongamia": ["genus pongamia", "rosid dicot genus"],
    "pongee": ["cloth", "fabric", "material", "textile"],
    "pongidae": ["family pongidae", "mammal family"],
    "pongo": ["genus pongo", "mammal genus"],
    "poniard": ["knife", "stab"],
    "pons": ["alice-josephine pons", "lily pons"],
    "pons asinorum": ["problem"],
    "ponselle": ["rosa melba ponselle", "rosa ponselle"],
    "ponte 25 de abril": [],
    "pontederia": ["genus pontederia", "liliopsid genus", "monocot genus"],
    "pontederiaceae": ["family pontederiaceae", "liliopsid family", "monocot family", "pickerelweed family"],
    "pontiac": [],
    "pontifex": ["priest"],
    "pontifical": ["vestment"],
    "pontificate": ["administer", "administrate"],
    "pontoon": ["barge", "flatboat", "hoy", "lighter"],
    "pontoon bridge": ["bateau bridge", "bridge", "floating bridge", "span"],
    "pontus": ["greek deity", "pontos"],
    "pony": ["crib", "interlingual rendition", "rendering", "translation", "trot", "version"],
    "pony cart": ["cart", "donkey cart", "ponycart", "tub-cart"],
    "pony express": ["express", "express mail"],
    "pony-trekking": ["equitation", "horseback riding", "riding"],
    "ponytail": ["coif", "coiffure", "hair style", "hairdo", "hairstyle"],
    "pooch": ["pooch out", "purse"],
    "pood": ["weight", "weight unit"],
    "poodle": ["canis familiaris", "dog", "domestic dog", "large poodle", "miniature poodle", "poodle dog", "standard poodle", "toy poodle"],
    "pooecetes": ["bird genus", "genus pooecetes"],
    "pooh-pooh": ["express", "give tongue to", "utter", "verbalise", "verbalize"],
    "pool": ["share"],
    "pool ball": ["ball", "eight ball"],
    "pool player": ["participant", "player"],
    "pool table": ["billiard table", "game equipment", "snooker table", "table"],
    "pooler": ["partaker", "sharer"],
    "pooling of interest": ["accounting", "accounting system", "method of accounting"],
    "poolroom": ["room"],
    "poon": ["wood"],
    "poop deck": ["shelter deck", "weather deck"],
    "poop out": ["conk out", "fatigue", "jade", "pall", "peter out", "run down", "run out", "tire", "weary"],
    "poor": [],
    "poor box": ["alms box", "box", "mite box"],
    "poor devil": ["victim", "wretch"],
    "poor law": ["law"],
    "poor people": ["homeless", "needy", "people", "poor"],
    "poor person": ["down-and-out", "drifter", "floater", "have-not", "pauper", "poor white trash", "unfortunate", "unfortunate person", "vagabond", "vagrant", "white trash"],
    "poor rates": ["rates"],
    "poorhouse": ["establishment", "workhouse"],
    "poorness": ["aridity", "barrenness", "fruitlessness"],
    "poorwill": ["caprimulgid", "goatsucker", "nightjar", "phalaenoptilus nuttallii"],
    "pop": ["sound"],
    "pop art": ["art movement", "artistic movement"],
    "pop bottle": ["bottle", "soda bottle"],
    "pop fly": ["fly", "fly ball", "pop-fly", "pop-up"],
    "pop group": ["ensemble", "indie"],
    "pop in": ["come in", "enter", "get in", "get into", "go in", "go into", "move into"],
    "pop music": ["pop", "popular music", "popular music genre"],
    "pop off": ["go away", "go forth", "leave"],
    "pop out": ["exit", "get out", "go out", "leave"],
    "pop quiz": ["quiz"],
    "pop tent": ["collapsible shelter", "tent"],
    "pop-up book": ["book", "pop-up"],
    "popcorn": ["corn", "indian corn", "maize", "zea mays", "zea mays everta"],
    "popcorn ball": ["candy", "confect"],
    "pope": ["alexander pope"],
    "popery": ["papism", "pattern", "practice"],
    "popeyed": [],
    "popgun": ["plaything", "toy"],
    "popillia": ["arthropod genus", "genus popillia"],
    "popinjay": ["egoist", "egotist", "swellhead"],
    "popishly": [],
    "poplar": ["wood"],
    "poplar bluff": [],
    "poplin": ["cloth", "fabric", "material", "textile"],
    "popliteal": [],
    "popliteal artery": ["arteria", "arteria poplitea", "arterial blood vessel", "artery"],
    "popliteal vein": ["vein", "vena", "vena poplitea", "venous blood vessel"],
    "popover": ["gem", "muffin"],
    "popper": ["karl popper", "philosopher", "sir karl raimund popper"],
    "poppet": ["poppet valve", "valve"],
    "poppy": ["arctic poppy", "blue poppy", "bocconia", "california poppy", "celandine", "celandine poppy", "chelidonium majus", "corn poppy", "creamcups", "eschscholtzia californica", "field poppy", "flaming poppy", "flanders poppy", "flower", "golden cup", "greater celandine", "hunnemania fumariifolia", "iceland poppy", "macleaya cordata", "meconopsis betonicifolia", "meconopsis cambrica", "mexican tulip poppy", "opium poppy", "oriental poppy", "papaver alpinum", "papaver argemone", "papaver californicum", "papaver heterophyllum", "papaver nudicaule", "papaver orientale", "papaver rhoeas", "papaver somniferum", "platystemon californicus", "plume poppy", "prickly poppy", "stylomecon heterophyllum", "stylophorum diphyllum", "swallow wort", "swallowwort", "welsh poppy", "western poppy", "wind poppy", "wood poppy"],
    "poppy mallow": ["callirhoe digitata", "callirhoe involucrata", "callirhoe triangulata", "clustered poppy mallow", "fringed poppy mallow", "mallow", "purple poppy mallow"],
    "poppy seed": ["flavorer", "flavoring", "flavourer", "flavouring", "seasoner", "seasoning"],
    "populace": ["admass", "people", "public", "world"],
    "popular": [],
    "popular front": ["alignment", "alinement", "alliance", "coalition"],
    "popular front for the liberation of palestine": ["pflp"],
    "popular front for the liberation of palestine-general command": ["pflp-gc"],
    "popular music": ["ballroom music", "dance music", "danceroom music", "disco", "disco music", "ethnic music", "folk", "folk music", "genre", "hip-hop", "jazz", "macumba", "music genre", "musical genre", "musical style", "pop", "pop music", "popular music genre", "r and b", "rap", "rap music", "reggae", "rhythm and blues", "rock", "rock 'n' roll", "rock and roll", "rock music", "rock'n'roll", "rock-and-roll", "rockabilly", "skiffle"],
    "popular struggle front": ["psf"],
    "popularism": ["music"],
    "popularity": ["hot stuff", "quality"],
    "popularity contest": ["contest"],
    "popularization": ["interpretation", "popularisation"],
    "popularize": ["broadcast", "circularise", "circularize", "circulate", "diffuse", "disperse", "disseminate", "distribute", "generalise", "generalize", "pass around", "popularise", "propagate", "spread", "vulgarise", "vulgarize"],
    "popularizer": ["communicator", "populariser", "vulgariser", "vulgarizer"],
    "popularly": [],
    "populate": ["be", "bivouac", "board", "camp", "camp out", "cohabit", "domicile", "domiciliate", "dwell", "encamp", "inhabit", "live", "live together", "lodge", "lodge in", "neighbor", "neighbour", "nest", "occupy", "overpopulate", "people", "reside", "room", "shack", "shack up", "tenant", "tent"],
    "populated": [],
    "population": ["integer", "whole number"],
    "population commission": ["economic and social council commission", "ecosoc commission"],
    "population control": ["social control"],
    "population growth": ["growth", "increase", "increment", "irruption"],
    "population profile": ["profile"],
    "population shift": ["shift", "transformation", "transmutation"],
    "populism": ["doctrine", "ism", "philosophical system", "philosophy", "school of thought"],
    "populous": ["thickly settled"],
    "populus": ["genus populus", "hamamelid dicot genus"],
    "porbeagle": ["lamna nasus", "mackerel shark"],
    "porcelain": ["ceramic ware", "china", "spode"],
    "porcelainize": ["coat", "surface"],
    "porcellio": ["arthropod genus", "genus porcellio"],
    "porcellionidae": ["arthropod family", "family porcellionidae"],
    "porch": ["back porch", "construction", "deck", "front porch", "gallery", "portico", "stoep", "stoop", "structure", "veranda", "verandah"],
    "porcine": [],
    "porcupine": ["gnawer", "hedgehog", "new world porcupine", "old world porcupine", "rodent"],
    "porcupine ball": ["meatball", "porcupines"],
    "porcupinefish": ["diodon hystrix", "porcupine fish", "spiny puffer"],
    "pore": ["hole"],
    "porgy": ["saltwater fish", "scup"],
    "porifera": ["phylum", "phylum porifera"],
    "pork": ["cochon de lait", "meat", "pigs' feet", "pigs' knuckles", "porc", "salt pork", "suckling pig"],
    "pork and beans": ["dish"],
    "pork barrel": ["appropriation", "pork"],
    "pork belly": ["side of pork"],
    "pork butcher": ["butcher", "meatman"],
    "pork loin": ["cut of pork"],
    "pork pie": ["pasty"],
    "pork roast": ["joint", "roast", "roast pork"],
    "pork sausage": ["banger", "brat", "bratwurst", "linguica", "sausage", "saveloy"],
    "pork tenderloin": ["tenderloin", "undercut"],
    "pork-and-veal goulash": ["goulash", "gulyas", "hungarian goulash"],
    "pork-barreling": ["acquisition"],
    "porkchop": ["chop"],
    "porker": ["grunter", "hog", "pig", "squealer", "sus scrofa"],
    "porkfish": ["anisotremus virginicus", "grunt", "pork-fish"],
    "porkholt": ["goulash", "gulyas", "hungarian goulash"],
    "porkpie": ["porkpie hat", "snap-brim hat"],
    "pornographer": ["impresario", "porn merchant", "promoter", "showman"],
    "pornographic": ["adult"],
    "pornographically": [],
    "pornography": ["child pornography", "creation", "creative activity", "erotica", "kiddie porn", "kiddy porn", "porn", "porno", "smut"],
    "poronotus": ["fish genus", "genus poronotus"],
    "porose": [],
    "porosity": ["body", "consistence", "consistency", "eubstance", "permeability", "permeableness", "porousness", "sponginess"],
    "porous": [],
    "porphyra": ["genus porphyra", "protoctist genus"],
    "porphyria": ["congenital disease", "genetic abnormality", "genetic defect", "genetic disease", "genetic disorder", "hereditary condition", "hereditary disease", "inherited disease", "inherited disorder"],
    "porphyrin": ["pigment"],
    "porphyrio": ["bird genus", "genus porphyrio"],
    "porphyritic": [],
    "porphyrula": ["bird genus", "genus porphyrula"],
    "porphyry": ["igneous rock", "porphyritic rock"],
    "porpoise": ["dolphin", "harbor porpoise", "herring hog", "phocoena phocoena", "phocoena sinus", "vaquita"],
    "porpoise oil": ["animal oil"],
    "porridge": ["burgoo", "dish", "gruel", "hasty pudding", "oatmeal"],
    "porringer": ["bowl"],
    "port": ["turn"],
    "port arthur": [],
    "port jackson fig": ["botany bay fig", "ficus rubiginosa", "fig tree", "little-leaf fig", "rusty rig"],
    "port jackson heath": ["epacris", "epacris purpurascens"],
    "port jackson pine": ["callitris cupressiformis", "cypress pine"],
    "port louis": [],
    "port moresby": ["capital of papua new guinea"],
    "port of call": ["harbor", "harbour", "haven", "seaport"],
    "port of entry": ["point of entry", "port"],
    "port of spain": ["capital of trinidad and tobago", "port-of-spain"],
    "port orford cedar": ["cedar", "cedarwood"],
    "port sudan": [],
    "port vila": ["capital of vanuatu", "vila"],
    "port-access coronary bypass surgery": ["closed-heart surgery"],
    "port-au-prince": ["haitian capital"],
    "port-wine stain": ["birthmark", "nevus", "nevus flammeus"],
    "porta hepatis": ["opening", "orifice", "porta"],
    "portability": ["movability", "movableness"],
    "portable": ["typewriter"],
    "portable circular saw": ["buzz saw", "circular saw", "portable saw"],
    "portable computer": ["briefcase computer", "hand-held computer", "hand-held microcomputer", "laptop", "laptop computer", "microcomputer", "notebook", "notebook computer", "pc", "personal computer"],
    "portacaval shunt": ["shunt"],
    "portage": ["cost"],
    "portal": ["entrance", "entranceway", "entree", "entry", "entryway"],
    "portal hypertension": ["malignant hypertension"],
    "portal site": ["internet site", "portal", "site", "web site", "website"],
    "portal system": ["vascular system"],
    "portal vein": ["hepatic portal vein", "portal", "vein", "vena", "vena portae", "venous blood vessel"],
    "portcullis": ["gate"],
    "porte": ["court", "royal court", "sublime porte"],
    "porte-cochere": ["entrance", "entranceway", "entree", "entry", "entryway"],
    "portentous": ["prodigious"],
    "portentously": [],
    "porter": ["carry", "transport"],
    "porterage": ["charge"],
    "porterhouse": ["beefsteak", "porterhouse steak"],
    "portfolio": ["set"],
    "porthole": ["window"],
    "portia tree": ["bendy tree", "seaside mahoe", "thespesia populnea", "tulipwood tree"],
    "portico": ["narthex", "porch"],
    "portiere": ["curtain", "drape", "drapery", "mantle", "pall"],
    "portland": [],
    "portly": ["stout"],
    "portmanteau": ["bag", "gladstone", "gladstone bag", "grip", "suitcase", "traveling bag", "travelling bag"],
    "porto": ["oporto"],
    "porto novo": ["capital of benin"],
    "portrait": ["half-length", "likeness", "portrayal", "self-portrait", "semblance"],
    "portrait camera": ["camera", "photographic camera"],
    "portrait lens": ["camera lens", "optical lens"],
    "portraitist": ["limner", "painter", "portrait painter", "portrayer"],
    "portraiture": ["delineation", "depiction", "portrayal"],
    "portray": ["commend", "interpret", "present", "represent"],
    "portrayal": ["characterisation", "characterization", "delineation", "depiction", "picture", "portrait", "portraiture", "word picture", "word-painting"],
    "portsmouth": [],
    "portugal": ["portuguese republic"],
    "portuguese": ["european"],
    "portuguese escudo": ["escudo", "portuguese monetary unit"],
    "portuguese man-of-war": ["jellyfish", "man-of-war", "siphonophore"],
    "portuguese monetary unit": ["conto", "escudo", "monetary unit", "portuguese escudo"],
    "portulaca": ["flower", "portulaca grandiflora", "rose moss", "sun plant"],
    "portulacaceae": ["caryophylloid dicot family", "family portulacaceae", "purslane family"],
    "portunidae": ["arthropod family", "family portunidae"],
    "portunus": ["arthropod genus", "genus portunus"],
    "portwatcher": ["port watcher", "security guard", "watcher", "watchman"],
    "porzana": ["bird genus", "genus porzana"],
    "pose": ["acquit", "attitudinise", "attitudinize", "bear", "behave", "carry", "comport", "conduct", "deport", "posture"],
    "posed": [],
    "poseidon": [],
    "poser": ["problem", "sticker", "stumper", "toughie"],
    "poseur": ["exhibitionist", "poser", "poseuse", "show-off"],
    "poseuse": ["poser", "poseur"],
    "position": ["aim", "deploy", "direct", "dress", "lay", "line up", "orient", "place", "pose", "position", "put", "set", "square", "take", "take aim", "train"],
    "position effect": ["consequence", "effect", "event", "issue", "outcome", "result", "upshot"],
    "position paper": ["report", "study", "written report"],
    "positionable": [],
    "positional": [],
    "positional notation": ["binary number system", "binary numeration system", "binary system", "decimal number system", "decimal numeration system", "decimal system", "duodecimal number system", "duodecimal system", "hexadecimal number system", "hexadecimal system", "number representation system", "number system", "numeration system", "octal number system", "octal numeration system", "positional representation system", "pure binary numeration system", "sexadecimal number system", "system of numeration"],
    "positive": ["adjective", "adverb", "positive degree"],
    "positive charge": ["charge", "electric charge"],
    "positive chemotaxis": ["chemotaxis"]
}
