synonyms = {
    "broadly": ["broadly speaking", "generally", "loosely"],
    "broadtail": ["caracul", "karakul"],
    "broadway": ["great white way"],
    "brocaded": ["embossed", "raised"],
    "broccoli": ["brassica oleracea italica"],
    "broccoli raab": ["brassica rapa ruvo", "broccoli rabe"],
    "broccoli rabe": ["broccoli raab"],
    "brockhouse": ["bertram brockhouse"],
    "brogan": ["brogue", "clodhopper", "work shoe"],
    "broglie": ["de broglie", "louis victor de broglie"],
    "broil": ["bake"],
    "broiled": ["grilled"],
    "broke": ["bust", "skint"],
    "broken": ["broken in"],
    "brokenhearted": ["heartbroken", "heartsick"],
    "brokerage": ["brokerage firm", "securities firm"],
    "brokerage house": ["brokerage"],
    "bromate": ["brominate"],
    "brome": ["bromegrass"],
    "bromeliaceae": ["family bromeliaceae", "pineapple family"],
    "bromidic": ["corny", "platitudinal", "platitudinous"],
    "bromine": ["br"],
    "bromoform": ["tribromomethane"],
    "bromophenol blue": ["bromphenol blue"],
    "bromothymol blue": ["bromthymol blue"],
    "brompheniramine maleate": ["dimetane"],
    "brompton stock": ["matthiola incana"],
    "bromus": ["genus bromus"],
    "bronchial vein": ["vena bronchialis"],
    "bronchopneumonia": ["bronchial pneumonia"],
    "bronchus": ["bronchial tube"],
    "bronco": ["bronc", "broncho"],
    "bronte": ["anne bronte"],
    "bronze": ["bronzy"],
    "bronze star medal": ["bronze star"],
    "bronzed": ["suntanned", "tanned"],
    "brooch": ["clasp"],
    "brood": ["bulk large", "hover", "loom"],
    "brood hen": ["broody", "broody hen", "setting hen", "sitter"],
    "brooding": ["incubation"],
    "broodmare": ["stud mare"],
    "brook": ["creek"],
    "brook thistle": ["cirsium rivulare"],
    "brook trout": ["speckled trout"],
    "brooke": ["rupert brooke"],
    "brooklime": ["european brooklime", "veronica beccabunga"],
    "brooks": ["van wyck brooks"],
    "brookweed": ["samolus floribundus", "samolus parviflorus"],
    "broom beard grass": ["andropogon scoparius", "prairie grass", "schizachyrium scoparium", "wire grass"],
    "broom sedge": ["andropogon virginicus"],
    "broom tree": ["genista anglica", "needle furze", "petty whin"],
    "broomcorn": ["sorghum vulgare technicum"],
    "broomcorn millet": ["hog millet", "panicum miliaceum"],
    "broomstick": ["broom handle"],
    "broomweed": ["gutierrezia texana"],
    "brosmius": ["genus browmius"],
    "broth": ["stock"],
    "broth of a boy": ["broth of a man"],
    "brother": ["comrade"],
    "brotherhood": ["fraternity", "sodality"],
    "brotherly": ["brotherlike", "fraternal"],
    "brotulidae": ["family brotulidae"],
    "broussonetia": ["genus broussonetia"],
    "brow": ["forehead"],
    "browbeat": ["bully", "swagger"],
    "brown": ["robert brown"],
    "brown bear": ["bruin", "ursus arctos"],
    "brown bells": ["fritillaria micrantha", "fritillaria parviflora"],
    "brown bread": ["boston brown bread"],
    "brown butter": ["beurre noisette"],
    "brown creeper": ["american creeper", "certhia americana"],
    "brown hyena": ["hyaena brunnea", "strand wolf"],
    "brown lacewing": ["hemerobiid", "hemerobiid fly"],
    "brown lemming": ["lemmus trimucronatus"],
    "brown pine": ["podocarpus elatus", "rockingham podocarp"],
    "brown rat": ["norway rat", "rattus norvegicus"],
    "brown root rot fungus": ["thielavia basicola"],
    "brown rot gummosis": ["gummosis"],
    "brown sauce": ["sauce espagnole"],
    "brown snail": ["helix aspersa"],
    "brown soft scale": ["coccus hesperidum"],
    "brown thrasher": ["brown thrush", "toxostoma rufums"],
    "brown trout": ["salmo trutta", "salmon trout"],
    "brown university": ["brown"],
    "browne": ["hablot knight browne", "phiz"],
    "brownian movement": ["brownian motion", "pedesis"],
    "browning": ["john moses browning"],
    "browning automatic rifle": ["bar"],
    "browning machine gun": ["peacemaker"],
    "browntail": ["euproctis phaeorrhoea"],
    "browse": ["surf"],
    "browser": ["web browser"],
    "bruce": ["david bruce", "sir david bruce"],
    "brucellosis": ["contagious abortion"],
    "bruch": ["max bruch"],
    "bruchidae": ["family bruchidae"],
    "bruchus": ["genus bruchus"],
    "bruckenthalia": ["genus bruckenthalia"],
    "bruckner": ["anton bruckner"],
    "brueghel": ["breughel", "breughel the elder", "bruegel", "pieter breughel", "pieter bruegel", "pieter brueghel", "pieter brueghel the elder"],
    "bruges": ["city of bridges"],
    "brugmansia": ["genus brugmansia"],
    "bruise": ["contuse"],
    "brumal": ["hibernal", "hiemal"],
    "brummell": ["beau brummell", "george bryan brummell"],
    "brummie": ["brummy"],
    "brumous": ["foggy", "hazy", "misty"],
    "brunanburh": ["battle of brunanburh"],
    "brunei": ["negara brunei darussalam"],
    "brunelleschi": ["filippo brunelleschi"],
    "brunet": ["brunette"],
    "brunfelsia": ["genus brunfelsia"],
    "brunhild": ["brunnhilde", "brynhild"],
    "bruno": ["saint bruno"],
    "brush": ["sweep"],
    "brush turkey": ["alectura lathami"],
    "brushed": ["fleecy", "napped"],
    "brusque": ["brusk", "curt", "short"],
    "brussels sprout": ["brassica oleracea gemmifera"],
    "brutal": ["unrelenting"],
    "brutality": ["barbarism", "barbarity", "savagery"],
    "brutalization": ["brutalisation"],
    "brutalize": ["brutalise"],
    "brutus": ["marcus junius brutus"],
    "bruxelles": ["belgian capital", "brussels", "capital of belgium"],
    "brya": ["genus brya"],
    "bryaceae": ["family bryaceae"],
    "bryales": ["order bryales"],
    "bryan": ["boy orator of the platte", "great commoner", "william jennings bryan"],
    "bryony": ["briony"],
    "bryophyta": ["division bryophyta"],
    "bryophyte": ["nonvascular plant"],
    "bryopsida": ["class bryopsida", "class musci", "musci"],
    "bryozoa": ["phylum bryozoa", "polyzoa"],
    "bryozoan": ["moss animal", "polyzoan", "sea mat", "sea moss"],
    "brythonic": ["brittanic"],
    "bryum": ["genus bryum"],
    "bubalus": ["genus bubalus", "tribe bubalus"],
    "bubble jet printer": ["bubblejet"],
    "bubble over": ["overflow", "spill over"],
    "bubble up": ["intumesce"],
    "bubbliness": ["effervescence", "frothiness"],
    "bubbling": ["bubbly", "effervescing", "foaming", "foamy", "frothy", "spumy"],
    "buber": ["martin buber"],
    "bubo": ["genus bubo"],
    "bubonic plague": ["glandular plague", "pestis bubonica"],
    "bubulcus": ["genus bubulcus"],
    "buccal artery": ["arteria buccalis"],
    "buccinidae": ["family buccinidae"],
    "bucconidae": ["family bucconidae"],
    "bucephala": ["genus bucephala"],
    "buceros": ["genus buceros"],
    "bucerotidae": ["family bucerotidae"],
    "buchanan": ["james buchanan", "president buchanan"],
    "bucharest": ["bucharesti", "bucuresti", "capital of romania"],
    "buchloe": ["genus buchloe"],
    "buchner": ["eduard buchner"],
    "buck": ["go against"],
    "bucked up": ["encouraged"],
    "bucket": ["bucketful"],
    "buckeye": ["conker", "horse chestnut"],
    "buckle": ["clasp"],
    "buckler mustard": ["biscutalla laevigata"],
    "buckleya": ["buckleya distichophylla"],
    "buckminsterfullerene": ["buckyball"],
    "buckthorn berry": ["yellow berry"],
    "buckwheat": ["fagopyrum esculentum", "polygonum fagopyrum"],
    "bucolic": ["pastoral"],
    "bud brush": ["artemis spinescens", "bud sagebrush"],
    "budapest": ["capital of hungary", "hungarian capital"],
    "buddha": ["gautama", "gautama buddha", "gautama siddhartha", "siddhartha"],
    "buddhist": ["buddhistic"],
    "buddy": ["brother", "chum", "crony", "pal", "sidekick"],
    "budge": ["don budge", "john donald budge"],
    "budgerigar": ["budgereegah", "budgerygah", "budgie", "grass parakeet", "lovebird", "melopsittacus undulatus", "shell parakeet"],
    "budorcas": ["genus budorcas"],
    "buenos aires": ["capital of argentina"],
    "buff": ["burnish", "furbish"],
    "buffalo bur": ["solanum rostratum"],
    "buffalo carpet beetle": ["anthrenus scrophulariae"],
    "buffalo clover": ["trifolium reflexum", "trifolium stoloniferum"],
    "buffalo fish": ["buffalofish"],
    "buffalo grass": ["buchloe dactyloides"],
    "buffalo nut": ["elk nut", "oil nut"],
    "buffel grass": ["cenchrus ciliaris", "pennisetum cenchroides"],
    "buffer": ["buffer storage", "buffer store"],
    "buffer state": ["buffer country"],
    "buffer zone": ["buffer"],
    "buffered aspirin": ["bufferin"],
    "buffet": ["batter", "knock about"],
    "bufflehead": ["bucephela albeola", "butterball", "dipper"],
    "buffoonery": ["clowning", "frivolity", "harlequinade", "japery", "prank"],
    "buffoonish": ["clownish", "clownlike", "zany"],
    "bufonidae": ["family bufonidae"],
    "bug": ["glitch"],
    "bugbear": ["hobgoblin"],
    "bugger all": ["fanny adams", "fuck all", "sweet fanny adams"],
    "buggy": ["roadster"],
    "bugle": ["bugleweed"],
    "bugleweed": ["lycopus virginicus"],
    "bugloss": ["alkanet", "anchusa officinalis"],
    "build": ["establish"],
    "build up": ["build", "ramp up", "work up"],
    "builder": ["detergent builder"],
    "building": ["edifice"],
    "building complex": ["complex"],
    "building supply store": ["building supply house"],
    "built": ["reinforced"],
    "bujumbura": ["capital of burundi", "usumbura"],
    "bukharin": ["nikolai ivanovich bukharin"],
    "bulbar conjunctiva": ["conjunctival layer of bulb", "tunica conjunctiva bulbi"],
    "bulbil": ["bulblet"],
    "bulblet fern": ["berry fern", "bulblet bladder fern", "cystopteris bulbifera"],
    "bulblike": ["bulbous"],
    "bulgaria": ["republic of bulgaria"],
    "bulge": ["bag"],
    "bulgur": ["bulghur", "bulgur wheat"],
    "bulimarexia": ["bulima nervosa"],
    "bulk": ["mass", "volume"],
    "bulkiness": ["massiveness"],
    "bull": ["bull through"],
    "bull run": ["battle of bull run"],
    "bull shark": ["carcharhinus leucas", "cub shark"],
    "bull thistle": ["boar thistle", "cirsium lanceolatum", "cirsium vulgare", "spear thistle"],
    "bullace": ["prunus insititia"],
    "bullbrier": ["briar", "brier", "catbrier", "greenbrier", "horse brier", "smilax rotundifolia"],
    "bulldog": ["english bulldog"],
    "bulldog clip": ["alligator clip"],
    "bulldozer": ["dozer"],
    "bullet": ["slug"],
    "bullet train": ["bullet"],
    "bulletin board": ["notice board"],
    "bulletin board system": ["bbs", "bulletin board", "electronic bulletin board"],
    "bullfight": ["corrida"],
    "bullfighter": ["toreador"],
    "bullfighting": ["tauromachy"],
    "bullfinch": ["charles bullfinch"],
    "bullfrog": ["rana catesbeiana"],
    "bullhead": ["bullhead catfish"],
    "bullheaded": ["pigheaded"],
    "bullhorn": ["loud hailer"],
    "bullnose": ["bullnosed plane"],
    "bullock": ["steer"],
    "bullpen": ["detention cell", "detention centre"],
    "bullshit": ["bull", "crap", "dogshit", "horseshit", "irish bull", "shit"],
    "bullterrier": ["bull terrier"],
    "bully": ["hooligan", "roughneck", "rowdy", "ruffian", "tough", "yob", "yobbo", "yobo"],
    "bully beef": ["corn beef", "corned beef"],
    "bullying": ["intimidation"],
    "bulnesia": ["genus bulnesia"],
    "bulrush": ["bullrush", "common rush", "juncus effusus", "soft rush"],
    "bultmann": ["rudolf bultmann", "rudolf karl bultmann"],
    "bum": ["arse about", "arse around", "bum about", "bum around", "frig around", "fuck off", "loaf", "loll", "loll around", "lounge about", "lounge around"],
    "bumble": ["falter", "stammer", "stutter"],
    "bumblebee": ["humblebee"],
    "bumbling": ["bungling", "butterfingered", "handless"],
    "bumelia": ["genus bumelia"],
    "bumf": ["bumph"],
    "bump": ["knock"],
    "bumper car": ["dodgem"],
    "bumpkinly": ["hick", "rustic", "unsophisticated"],
    "bumptiousness": ["cockiness", "forwardness", "pushiness"],
    "bun": ["roll"],
    "buna": ["buna rubber"],
    "bunch": ["bunch up", "bundle", "clump", "cluster"],
    "bunch together": ["bunch", "bunch up"],
    "bunchberry": ["cornus canadensis", "crackerberry", "dwarf cornel", "pudding berry"],
    "bunche": ["ralph bunche", "ralph johnson bunche"],
    "bunchgrass": ["bunch grass"],
    "bunco": ["bunco game", "bunko", "bunko game", "con", "con game", "confidence game", "confidence trick", "flimflam", "gyp", "hustle", "sting"],
    "bundle": ["bundle up", "roll up"],
    "bung": ["spile"],
    "bungalow": ["cottage"],
    "bungarus": ["genus bungarus"],
    "bungee": ["bungee cord"],
    "bungled": ["botched"],
    "bungler": ["blunderer", "botcher", "bumbler", "butcher", "fuckup", "fumbler", "sad sack", "stumbler"],
    "bungling": ["clumsy", "fumbling", "incompetent"],
    "bunk": ["buncombe", "bunkum", "guff", "hogwash", "rot"],
    "bunk bed": ["bunk"],
    "bunk off": ["play hooky"],
    "bunker": ["dugout"],
    "bunker hill": ["battle of bunker hill"],
    "bunny": ["bunny girl"],
    "bunsen": ["robert bunsen", "robert wilhelm bunsen"],
    "bunsen burner": ["bunsen", "etna"],
    "bunt": ["drag a bunt"],
    "bunuel": ["luis bunuel"],
    "bunya bunya": ["araucaria bidwillii", "bunya bunya tree"],
    "bunyan": ["john bunyan"],
    "buoy": ["buoy up"],
    "buoyancy": ["perkiness"],
    "buoyant": ["floaty"],
    "buoyantly": ["chirpily"],
    "buphthalmum": ["genus buphthalmum"],
    "bur": ["burr"],
    "bur marigold": ["burr marigold", "sticktight"],
    "bur oak": ["burr oak", "mossycup oak", "quercus macrocarpa"],
    "bura": ["pabir"],
    "burbage": ["richard burbage"],
    "burbank": ["luther burbank"],
    "burbling": ["burbly", "effusive", "gushing"],
    "burbot": ["cusk", "eelpout", "ling", "lota lota"],
    "burden": ["burthen", "weight", "weight down"],
    "burdened": ["loaded down"],
    "burdenless": ["unburdened"],
    "burdensome": ["onerous", "taxing"],
    "burdensomeness": ["heaviness", "onerousness", "oppressiveness"],
    "burdock": ["clotbur"],
    "bureau of alcohol tobacco and firearms": ["atf"],
    "bureau of customs": ["customs bureau", "customs service", "uscb"],
    "bureau of diplomatic security": ["ds"],
    "bureau of intelligence and research": ["inr"],
    "bureau of justice assistance": ["bja"],
    "bureau of justice statistics": ["bjs"],
    "bureau of the census": ["census bureau"],
    "bureaucracy": ["bureaucratism"],
    "bureaucrat": ["administrative official"],
    "bureaucratic procedure": ["red tape"],
    "burette": ["buret"],
    "burger": ["warren burger", "warren earl burger"],
    "burgess": ["anthony burgess"],
    "burglarize": ["burglarise", "burgle", "heist"],
    "burgoyne": ["gentleman johnny", "john burgoyne"],
    "burgrass": ["bur grass"],
    "burgundy": ["burgundy wine"],
    "burhinidae": ["family burhinidae"],
    "burhinus": ["genus burhinus"],
    "burial": ["entombment", "inhumation", "interment", "sepulture"],
    "burial chamber": ["sepulcher", "sepulchre", "sepulture"],
    "burial mound": ["barrow", "grave mound", "tumulus"],
    "buried": ["inhumed", "interred"],
    "burk": ["burke", "calamity jane", "martha jane burk", "martha jane burke"],
    "burke": ["edmund burke"],
    "burkina faso": ["upper volta"],
    "burlap": ["gunny"],
    "burma padauk": ["burmese rosewood", "pterocarpus macrocarpus"],
    "burmannia": ["genus burmannia"],
    "burmanniaceae": ["family burmanniaceae"],
    "burmeisteria": ["genus burmeisteria"],
    "burn": ["glow"],
    "burn down": ["burn up", "go up"],
    "burn off": ["burn", "burn up"],
    "burn plant": ["aloe vera"],
    "burnable": ["ignitable", "ignitible"],
    "burned": ["burnt"],
    "burnett": ["frances eliza hodgson burnett", "frances hodgson burnett"],
    "burnham": ["daniel hudson burnham"],
    "burning": ["burning at the stake"],
    "burnous": ["burnoose", "burnouse"],
    "burns": ["george burns", "nathan birnbaum"],
    "burnside": ["ambrose everett burnside"],
    "burp": ["belch", "bubble", "eruct"],
    "burp gun": ["machine pistol"],
    "burqa": ["burka"],
    "burr": ["aaron burr"],
    "burrawong": ["macrozamia communis", "macrozamia spiralis"],
    "burroughs": ["william burroughs", "william seward burroughs"],
    "burrow": ["tunnel"],
    "bursa": ["brusa"],
    "bursa omentalis": ["lesser peritoneal cavity", "omental bursa"],
    "bursera": ["genus bursera"],
    "burseraceae": ["family burseraceae", "torchwood family"],
    "bursiform": ["pouchlike", "saclike"],
    "burst": ["bust"],
    "burst in on": ["burst upon"],
    "burt": ["cyril burt", "cyril lodowic burt"],
    "burton": ["richard burton", "sir richard burton", "sir richard francis burton"],
    "burundi": ["republic of burundi"],
    "burweed marsh elder": ["false ragweed", "iva xanthifolia"],
    "bury": ["entomb", "inhume", "inter", "lay to rest"],
    "burying": ["burial"],
    "bus": ["heap", "jalopy"],
    "bus company": ["bus service"],
    "bus fare": ["carfare"],
    "bus terminal": ["bus depot", "bus station", "coach station"],
    "bus topology": ["bus"],
    "busbar": ["bus"],
    "bush": ["dubya", "dubyuh", "george bush", "george walker bush", "president bush"],
    "bush clover": ["lespedeza"],
    "bush hibiscus": ["hibiscus farragei", "radyera farragei"],
    "bush honeysuckle": ["lonicera tatarica", "tartarian honeysuckle"],
    "bush nasturtium": ["tropaeolum minus"],
    "bush poppy": ["tree poppy"],
    "bush vetch": ["vicia sepium"],
    "bush violet": ["browallia"],
    "bush willow": ["combretum erythrophyllum"],
    "bushbuck": ["guib", "tragelaphus scriptus"],
    "bushing": ["cylindrical lining"],
    "bushnell": ["david bushnell", "father of the submarine"],
    "bushtit": ["bush tit"],
    "bushy": ["shaggy"],
    "bushy aster": ["aster dumosus"],
    "business": ["business concern", "business organisation", "business organization", "concern"],
    "business activity": ["commercial activity"],
    "business cycle": ["trade cycle"],
    "business district": ["downtown"],
    "business expense": ["trade expense"],
    "business life": ["professional life"],
    "business loan": ["commercial loan"],
    "business people": ["businesspeople"],
    "businesslike": ["earnest"],
    "businessman": ["man of affairs"],
    "businessmen": ["business community"],
    "businessperson": ["bourgeois"],
    "buskin": ["combat boot", "desert boot", "half boot", "top boot"],
    "busman": ["bus driver"],
    "buspirone": ["buspar"],
    "bust": ["binge", "bout", "tear"],
    "bust up": ["wrack", "wreck"],
    "buster": ["bronco buster", "broncobuster"],
    "bustle": ["bustle about", "hustle"],
    "busy": ["occupy"],
    "busybody": ["quidnunc"],
    "busyness": ["hum"],
    "butacaine": ["butacaine sulfate"],
    "butanone": ["methyl ethyl ketone"],
    "butch": ["dike", "dyke"],
    "butcher": ["slaughter"],
    "butcher board": ["butcher block"],
    "butcher shop": ["meat market"],
    "butchery": ["butchering"],
    "butea": ["genus butea"],
    "buteo": ["genus buteo"],
    "butler": ["samuel butler"],
    "butt": ["bunt"],
    "butt joint": ["butt"],
    "butterbur": ["bog rhubarb", "petasites hybridus", "petasites vulgaris"],
    "buttercup": ["butterflower", "crowfoot", "goldcup", "kingcup"],
    "butterfield": ["william butterfield"],
    "butterfish": ["stromateid", "stromateid fish"],
    "butterfly": ["butterfly stroke"],
    "butterfly bush": ["buddleia"],
    "butterfly flower": ["schizanthus"],
    "butterfly orchid": ["butterfly orchis", "encyclia venosa", "epidendrum venosum"],
    "butterfly pea": ["clitoria mariana"],
    "butterfly plant": ["phalaenopsis amabilis"],
    "butterfly weed": ["asclepias tuberosa", "chigger flower", "chiggerflower", "indian paintbrush", "orange milkweed", "pleurisy root", "tuber root"],
    "buttermilk biscuit": ["soda biscuit"],
    "butternut": ["butternut tree", "juglans cinerea", "white walnut"],
    "butternut squash": ["cucurbita maxima"],
    "butterweed": ["ragwort", "senecio glabellus"],
    "buttery": ["fulsome", "oily", "oleaginous", "smarmy", "soapy", "unctuous"],
    "buttock": ["cheek"],
    "buttocks": ["arse", "ass", "backside", "behind", "bottom", "bum", "buns", "butt", "can", "derriere", "fanny", "fundament", "hind end", "hindquarters", "keister", "nates", "posterior", "prat", "rear", "rear end", "rump", "seat", "stern", "tail", "tail end", "tooshie", "tush"],
    "button fern": ["pellaea rotundifolia"],
    "button pink": ["dianthus latifolius"],
    "button quail": ["bustard quail", "hemipode"],
    "button snakeroot": ["eryngium aquaticum"],
    "button tree": ["button mangrove", "conocarpus erectus"],
    "buttoned": ["fastened"],
    "buttonhole": ["button hole"],
    "buttress": ["buttressing"],
    "butut": ["butat"],
    "butyl alcohol": ["butanol"],
    "butyl nitrite": ["isobutyl nitrite"],
    "butylene": ["butene"],
    "butyric acid": ["butanoic acid"],
    "buxaceae": ["box family", "family buxaceae"],
    "buxom": ["zaftig", "zoftig"],
    "buxus": ["genus buxus"],
    "buy": ["purchase"],
    "buy back": ["repurchase"],
    "buy it": ["pip out"],
    "buy off": ["pay off"],
    "buyer": ["emptor", "purchaser", "vendee"],
    "buying": ["purchasing"],
    "buzz": ["bombilate", "bombinate"],
    "buzz bomb": ["doodlebug", "flying bomb", "robot bomb"],
    "buzzard": ["cathartes aura", "turkey buzzard", "turkey vulture"],
    "buzzword": ["cant"],
    "by": ["past"],
    "by and by": ["later"],
    "by and large": ["generally", "more often than not", "mostly"],
    "by chance": ["accidentally", "circumstantially", "unexpectedly"],
    "by far": ["far and away", "out and away"],
    "by heart": ["by memory"],
    "by hook or by crook": ["by any means"],
    "by inches": ["by small degrees", "little by little"],
    "by no means": ["not by a blame sight", "not by a long sight"],
    "by rights": ["properly"],
    "by the piece": ["one by one"],
    "by the way": ["apropos", "by the bye", "incidentally"],
    "by word of mouth": ["viva voce"],
    "bydgoszcz": ["bromberg"],
    "bye": ["pass"],
    "byelorussian": ["belorussian", "white russian"],
    "bygone": ["water under the bridge"],
    "bypass": ["get around", "go around"],
    "bypass condenser": ["bypass capacitor"],
    "byrd": ["william byrd"],
    "byron": ["lord george gordon byron", "sixth baron byron of rochdale"],
    "byssus": ["beard"],
    "byway": ["bypath", "byroad"],
    "byzantine": ["convoluted", "involved", "knotty", "tangled", "tortuous"],
    "byzantine empire": ["byzantium", "eastern roman empire"],
    "c major": ["c major scale", "scale of c major"],
    "cab": ["cabriolet"],
    "cab fare": ["taxi fare"],
    "cabal": ["camarilla", "faction", "junto"]
}
