synonyms = {
    "radish": ["daikon", "japanese radish", "raphanus sativus longipinnatus"],
    "radish plant": ["radish"],
    "radium": ["ra"],
    "radium therapy": ["curietherapy"],
    "radome": ["radar dome"],
    "radon": ["rn"],
    "radyera": ["genus radyera"],
    "raffia": ["raphia"],
    "raffia palm": ["raffia farinifera", "raffia ruffia"],
    "raffle": ["raffle off"],
    "raffles": ["sir thomas raffles", "sir thomas stamford raffles"],
    "rafflesiaceae": ["family rafflesiaceae"],
    "rafter": ["balk", "baulk"],
    "raftsman": ["rafter", "raftman"],
    "rag": ["rag week"],
    "ragamuffin": ["tatterdemalion"],
    "rage": ["passion"],
    "ragged orchid": ["green fringed orchis", "habenaria lacera", "ragged orchis"],
    "ragged robin": ["cuckoo flower", "lychins floscuculi"],
    "raggedly": ["unevenly"],
    "ragtime": ["rag"],
    "ragweed": ["ambrosia", "bitterweed"],
    "ragwort": ["benweed", "ragweed", "senecio jacobaea", "tansy ragwort"],
    "raid": ["bust"],
    "rail": ["rail in"],
    "rail technology": ["railroading"],
    "railing": ["rail"],
    "railroad ticket": ["train ticket"],
    "railroad track": ["railroad", "railway"],
    "railroad vine": ["beach morning glory"],
    "railway": ["railroad", "railroad line", "railway line", "railway system"],
    "railway station": ["railroad station", "railroad terminal", "train depot", "train station"],
    "rain": ["rain down"],
    "rain forest": ["rainforest"],
    "rain gauge": ["pluviometer", "rain gage", "udometer"],
    "rain out": ["wash out"],
    "rain tree": ["albizia saman", "monkey pod", "monkeypod", "saman", "zaman", "zamang"],
    "rainbow lorikeet": ["trichoglossus moluccanus"],
    "rainbow runner": ["elagatis bipinnulata"],
    "rainbow seaperch": ["hipsurus caryi", "rainbow perch"],
    "rainbow shower": ["cassia javonica"],
    "rainbow smelt": ["osmerus mordax"],
    "rainbow trout": ["salmo gairdneri"],
    "raincoat": ["waterproof"],
    "rainproof": ["waterproof", "waterproofed"],
    "raisable": ["raiseable"],
    "raise": ["leaven", "prove"],
    "raise hell": ["make a stink", "raise a stink"],
    "raised": ["elevated"],
    "raisin moth": ["cadra figulilella"],
    "raising": ["nurture", "rearing"],
    "raising hell": ["hell raising"],
    "raja": ["rajah"],
    "rajidae": ["family rajidae"],
    "rajiformes": ["batoidei", "order batoidei", "order rajiformes"],
    "rajput": ["rajpoot"],
    "rake": ["blood", "profligate", "rakehell", "rip", "roue"],
    "rake in": ["shovel in"],
    "rakishly": ["carelessly", "raffishly"],
    "raleigh": ["ralegh", "sir walter ralegh", "sir walter raleigh", "walter ralegh", "walter raleigh"],
    "rallentando": ["ritardando", "ritenuto"],
    "rallidae": ["family rallidae"],
    "rally": ["rebound"],
    "ram": ["pound", "ram down"],
    "ramalina": ["genus ramalina"],
    "ramble": ["meander"],
    "ramble on": ["jog", "ramble"],
    "rambutan": ["nephelium lappaceum", "rambotan", "rambutan tree"],
    "ramekin": ["ramequin"],
    "rameses": ["ramesses", "ramses"],
    "rameses ii": ["rameses the great", "ramesses ii", "ramesses the great", "ramses ii", "ramses the great"],
    "ramie": ["boehmeria nivea", "china grass", "chinese silk plant", "ramee"],
    "ramify": ["branch"],
    "ramipril": ["altace"],
    "ramjet": ["atherodyde", "athodyd", "flying drainpipe", "ramjet engine"],
    "ramon y cajal": ["santiago ramon y cajal"],
    "ramp": ["rage", "storm"],
    "rampage": ["violent disorder"],
    "rampant": ["rearing"],
    "rampantly": ["wild"],
    "rampart": ["bulwark", "wall"],
    "ramphastidae": ["family ramphastidae"],
    "ramphomicron": ["genus ramphomicron"],
    "rampion": ["campanula rapunculus", "rampion bellflower"],
    "rana": ["genus rana"],
    "ranales": ["order ranales", "order ranunculales", "ranunculales"],
    "ranatra": ["genus ranatra"],
    "ranch": ["cattle farm", "cattle ranch", "spread"],
    "rand": ["ayn rand"],
    "random variable": ["chance variable", "stochastic variable", "variant", "variate"],
    "randomization": ["randomisation"],
    "randomize": ["randomise"],
    "randomized": ["randomised"],
    "randomly": ["arbitrarily", "at random", "every which way", "haphazardly", "indiscriminately"],
    "randomness": ["entropy"],
    "range": ["run"],
    "range in": ["home in", "zero in"],
    "range pole": ["flagpole", "ranging pole"],
    "rangefinder": ["range finder"],
    "rangifer": ["genus rangifer"],
    "rangpur": ["citrus limonia", "lemanderin", "rangpur lime"],
    "rani": ["ranee"],
    "ranidae": ["family ranidae"],
    "ranier": ["mount ranier", "mount tacoma"],
    "ranitidine": ["zantac"],
    "rank": ["outrank"],
    "rank and file": ["rank"],
    "rankin": ["jeannette rankin"],
    "ranking": ["superior"],
    "ransacking": ["rummage"],
    "ransom": ["redeem"],
    "ransomed": ["redeemed"],
    "rant": ["jabber", "mouth off", "rabbit on", "rave", "spout"],
    "ranter": ["raver"],
    "ranunculaceae": ["buttercup family", "crowfoot family", "family ranunculaceae"],
    "ranunculus": ["genus ranunculus"],
    "raoulia": ["genus raoulia"],
    "rap": ["knap"],
    "rapacious": ["ravening", "voracious"],
    "rapateaceae": ["family rapateaceae"],
    "rape": ["assault", "dishonor", "dishonour", "outrage", "ravish", "violate"],
    "rape oil": ["colza oil", "rapeseed oil"],
    "raper": ["rapist"],
    "raphael": ["raffaello santi", "raffaello sanzio"],
    "raphanus": ["genus raphanus"],
    "raphe": ["rhaphe"],
    "raphicerus": ["genus raphicerus"],
    "raphidae": ["family raphidae"],
    "raphidiidae": ["family raphidiidae"],
    "raphus": ["genus raphus"],
    "rapid": ["speedy"],
    "rapid climb": ["rapid growth", "zoom"],
    "rapid transit": ["mass rapid transit"],
    "rapier": ["tuck"],
    "rappahannock": ["rappahannock river"],
    "rappel": ["abseil", "rope down"],
    "rapport": ["resonance"],
    "raptores": ["order raptores"],
    "rare": ["rarefied", "rarified"],
    "rare bird": ["rara avis"],
    "rare earth": ["lanthanide", "lanthanoid", "lanthanon"],
    "rarefy": ["sublimate", "subtilize"],
    "rarely": ["seldom"],
    "rarity": ["infrequency", "rareness"],
    "rascality": ["shiftiness", "slipperiness", "trickiness"],
    "rascally": ["blackguardly", "roguish", "scoundrelly"],
    "rash": ["efflorescence", "roseola", "skin rash"],
    "rasht": ["resht"],
    "rashtriya swayamsevak sangh": ["national volunteers association"],
    "rask": ["rasmus christian rask"],
    "raskolnikov": ["rodya raskolnikov"],
    "rasmussen": ["kund johan victor rasmussen"],
    "rasp": ["rasping"],
    "raspberry": ["raspberry bush"],
    "rasputin": ["grigori efimovich rasputin"],
    "rastafari": ["rastas"],
    "rastafarian": ["rasta"],
    "rat cheese": ["store cheese"],
    "rat kangaroo": ["kangaroo rat"],
    "rat terrier": ["ratter"],
    "ratability": ["rateability"],
    "ratable": ["rateable"],
    "ratables": ["rateables"],
    "ratafia": ["ratafee"],
    "ratbite fever bacterium": ["spirillum minus"],
    "ratchet": ["rachet up", "ratchet down"],
    "rate": ["value"],
    "rate of depreciation": ["depreciation rate"],
    "rate of exchange": ["exchange rate"],
    "ratel": ["honey badger", "mellivora capensis"],
    "rather": ["instead"],
    "ratibida": ["genus ratibida"],
    "ratification": ["confirmation"],
    "ratified": ["sanctioned"],
    "rating system": ["scoring system"],
    "ration": ["ration out"],
    "rational number": ["rational"],
    "rationale": ["principle"],
    "rationalism": ["freethinking"],
    "rationality": ["reason", "reasonableness"],
    "rationalization": ["rationalisation"],
    "rationalize": ["rationalise"],
    "rationalize away": ["rationalise away"],
    "ratitae": ["superorder ratitae"],
    "ratite": ["flightless bird", "ratite bird"],
    "ratline": ["ratlin"],
    "rattail cactus": ["aporocactus flagelliformis"],
    "rattan": ["calamus rotang", "rattan palm"],
    "rattigan": ["sir terence mervyn rattigan", "terence rattigan"],
    "rattle": ["rale", "rattling"],
    "rattle down": ["rattle off", "reel off", "roll off", "spiel off"],
    "rattlebrained": ["rattlepated", "scatterbrained", "scatty"],
    "rattlesnake": ["rattler"],
    "rattlesnake fern": ["botrychium virginianum"],
    "rattlesnake master": ["button snakeroot", "eryngium yuccifolium"],
    "rattlesnake plantain": ["helleborine"],
    "rattlesnake root": ["prenanthes purpurea"],
    "rattlesnake weed": ["hieracium venosum"],
    "rattus": ["genus rattus"],
    "raucous": ["rowdy"],
    "rauli beech": ["nothofagus procera"],
    "rauwolfia": ["rauvolfia"],
    "ravage": ["depredation"],
    "ravaging": ["devastation"],
    "rave": ["gush"],
    "ravel": ["ravel out", "unravel"],
    "raveling": ["ravelling"],
    "raven": ["predate", "prey"],
    "ravenna": ["battle of ravenna"],
    "ravenna grass": ["erianthus ravennae", "wool grass"],
    "ravigote": ["ravigotte"],
    "raving": ["ravingly"],
    "raving mad": ["wild"],
    "ravioli": ["cappelletti"],
    "raw": ["altogether", "birthday suit"],
    "raw material": ["staple"],
    "raw vegetable": ["rabbit food"],
    "ray flower": ["ray floret"],
    "rayleigh": ["john william strutt", "lord rayleigh", "third baron rayleigh"],
    "razing": ["wrecking"],
    "razor clam": ["jackknife clam"],
    "razorback": ["razorback hog", "razorbacked hog"],
    "razorbill": ["alca torda"],
    "re": ["ray"],
    "reabsorb": ["resorb"],
    "reach": ["extend to", "touch"],
    "react": ["oppose"],
    "reaction": ["response"],
    "reaction time": ["latency", "latent period", "response time"],
    "reactionary": ["ultraconservative"],
    "reactive": ["responsive"],
    "read": ["say"],
    "read method of childbirth": ["read method"],
    "readiness": ["preparation", "preparedness"],
    "reading": ["reading material"],
    "readjust": ["reset"],
    "ready cash": ["cold cash", "ready money"],
    "reagan": ["president reagan", "ronald reagan", "ronald wilson reagan"],
    "real": ["existent"],
    "real estate broker": ["estate agent", "house agent", "land agent", "real estate agent"],
    "real estate investment trust": ["reit"],
    "real estate loan": ["mortgage loan"],
    "real gross national product": ["real gnp"],
    "real ira": ["dissident irish republican army", "real irish republican army", "rira"],
    "real mccoy": ["real stuff", "real thing"],
    "real number": ["real"],
    "real property": ["immovable", "real estate", "realty"],
    "real world": ["real life"],
    "realign": ["realine"],
    "realism": ["naive realism"],
    "reality": ["realism", "realness"],
    "realization": ["realisation"],
    "realize": ["realise"],
    "reallotment": ["reallocation", "reapportionment"],
    "realpolitik": ["practical politics"],
    "reamer": ["juice reamer", "juicer"],
    "reanimated": ["revived"],
    "reap": ["draw"],
    "reappearance": ["return"],
    "reapportion": ["reallocate"],
    "reappraisal": ["reassessment", "revaluation", "review"],
    "rear": ["bring up", "nurture", "parent", "raise"],
    "rearward": ["reverse"],
    "reason": ["conclude", "reason out"],
    "reasonable": ["sensible"],
    "reasonableness": ["moderateness", "modestness"],
    "reasonably": ["fairly", "jolly", "middling", "moderately", "passably", "pretty", "somewhat"],
    "reasoned": ["sound"],
    "reasoner": ["ratiocinator"],
    "reasoning": ["abstract thought", "logical thinking"],
    "reassembly": ["refabrication"],
    "reassertion": ["reaffirmation"],
    "reassess": ["reevaluate"],
    "reassure": ["assure"],
    "reaumur": ["rene antoine ferchault de reaumur"],
    "rebarbative": ["repellant", "repellent"],
    "rebate": ["discount"],
    "rebecca": ["rebekah"],
    "rebel": ["renegade"],
    "rebellion": ["insurrection", "revolt", "rising", "uprising"],
    "rebelliously": ["contumaciously", "defiantly"],
    "rebirth": ["renaissance", "renascence"],
    "reboxetine": ["edronax"],
    "rebuff": ["repel", "snub"],
    "rebuild": ["reconstruct"],
    "rebuke": ["reprehension", "reprimand", "reproof", "reproval"],
    "reburying": ["reburial"],
    "rebutter": ["confuter", "disprover", "refuter"],
    "recall": ["call back", "call in", "withdraw"],
    "recapitulate": ["recap"],
    "recapitulation": ["recap", "review"],
    "recapture": ["retake"],
    "recast": ["remold", "remould"],
    "recce": ["recco", "reccy"],
    "receding": ["fadeout"],
    "receive": ["have"],
    "receiver": ["pass catcher", "pass receiver"],
    "recency": ["recentness"],
    "recently": ["late", "lately", "latterly", "of late"],
    "reception": ["response"],
    "receptive": ["open"],
    "receptiveness": ["openness", "receptivity"],
    "recess": ["corner", "niche", "recession"],
    "recession": ["recessional"],
    "recessionary": ["recessive"],
    "recessive allele": ["recessive"],
    "recharge": ["reload"],
    "recidivist": ["habitual criminal", "repeater"],
    "recife": ["pernambuco"],
    "recipe": ["formula"],
    "recipient": ["receiver"],
    "recipient role": ["recipient"],
    "reciprocal": ["mutual"],
    "reciprocal cross": ["reciprocal"],
    "reciprocality": ["reciprocity"],
    "reciprocative": ["reciprocatory"],
    "recission": ["rescission"],
    "recitation": ["reading", "recital"],
    "recite": ["retell"],
    "recklessness": ["foolhardiness", "rashness"],
    "reckon": ["count"],
    "reckoner": ["ready reckoner"],
    "reckoning": ["tally"],
    "reclaim": ["repossess"],
    "reclaimable": ["recyclable", "reusable"],
    "reclamation": ["rehabilitation", "renewal"],
    "recliner": ["lounger", "reclining chair"],
    "recluse": ["reclusive", "withdrawn"],
    "recognition": ["acknowledgement", "acknowledgment"],
    "recognizable": ["placeable", "recognisable"],
    "recognizance": ["recognisance"],
    "recognize": ["recognise"],
    "recognized": ["recognised"],
    "recoil": ["kick"],
    "recombinant deoxyribonucleic acid": ["recombinant dna"],
    "recombinant human insulin": ["humulin"],
    "recommend": ["advocate", "urge"],
    "recommendation": ["good word", "testimonial"],
    "recompense": ["compensation"],
    "reconcile": ["conciliate", "make up", "patch up", "settle"],
    "reconciliation": ["rapprochement"],
    "reconditeness": ["abstruseness", "abstrusity", "profoundness", "profundity"],
    "reconnaissance": ["reconnaissance mission"],
    "reconnaissance vehicle": ["scout car"],
    "reconsideration": ["afterthought", "rethink", "second thought"],
    "reconstruct": ["construct", "retrace"],
    "reconstruction": ["reconstruction period"],
    "reconstructive": ["rehabilitative"],
    "record": ["register"],
    "record changer": ["changer"],
    "record player": ["phonograph"],
    "record sleeve": ["record cover"],
    "recorder": ["recording equipment", "recording machine"],
    "recording": ["transcription"],
    "recoup": ["reimburse"],
    "recourse": ["refuge", "resort"],
    "recover": ["recoup", "recuperate"],
    "recovery": ["retrieval"],
    "recreant": ["renegade"],
    "recreation room": ["rec room"],
    "recreational facility": ["recreation facility"],
    "recreational vehicle": ["rv"],
    "recriminative": ["recriminatory"],
    "recruit": ["levy", "raise"],
    "recruitment": ["enlisting"],
    "rectal artery": ["arteria rectalis"],
    "rectangularity": ["oblongness"],
    "rectify": ["amend", "remediate", "remedy", "repair"],
    "rectilinear": ["rectilineal"],
    "rectocele": ["proctocele"],
    "rectorship": ["rectorate"],
    "recumb": ["recline", "repose"],
    "recuperate": ["convalesce", "recover"],
    "recuperative": ["restorative"],
    "recur": ["go back"],
    "recurrence": ["return"],
    "recurring": ["revenant"],
    "recurved": ["recurvate"],
    "recurvirostra": ["genus recurvirostra"],
    "recurvirostridae": ["family recurvirostridae"],
    "recusation": ["recusal"],
    "recycle": ["reprocess", "reuse"],
    "red": ["red river"],
    "red admiral": ["vanessa atalanta"],
    "red alder": ["alnus rubra", "oregon alder"],
    "red army faction": ["raf"],
    "red ash": ["downy ash", "fraxinus pennsylvanica"],
    "red baneberry": ["actaea rubra", "redberry", "snakeberry"],
    "red bat": ["lasiurus borealis"],
    "red beech": ["booyong", "brown oak", "heritiera trifoliolata", "silky elm", "stave wood", "terrietia trifoliolata"],
    "red blood cell": ["erythrocyte", "rbc"],
    "red brass": ["guinea gold"],
    "red brigades": ["br", "brigate rosse"],
    "red bryony": ["bryonia dioica", "wild hop"],
    "red campion": ["lychnis dioica", "silene dioica"],
    "red clintonia": ["clintonia andrewsiana"],
    "red clover": ["purple clover", "trifolium pratense"],
    "red currant": ["garden current", "ribes rubrum"],
    "red deer": ["american elk", "cervus elaphus", "elk", "wapiti"],
    "red drum": ["channel bass", "redfish", "sciaenops ocellatus"],
    "red dwarf": ["red dwarf star"],
    "red eft": ["notophthalmus viridescens"],
    "red fox": ["celosia argentea"],
    "red giant": ["red giant star"],
    "red ginger": ["alpinia purpurata"],
    "red goatfish": ["mullus auratus"],
    "red goosefoot": ["chenopodium rubrum", "french spinach"],
    "red grouse": ["lagopus scoticus", "moorbird", "moorfowl", "moorgame"],
    "red gum": ["eucalyptus calophylla", "marri"],
    "red hand defenders": ["rhd"],
    "red haw": ["crataegus coccinea", "crataegus pedicellata"],
    "red helleborine": ["cephalanthera rubra"],
    "red herring": ["smoked herring"],
    "red jungle fowl": ["gallus gallus"],
    "red kauri": ["agathis lanceolata"],
    "red lauan": ["red lauan tree", "shorea teysmanniana"],
    "red laver": ["laver"],
    "red lead": ["minium"],
    "red light": ["warning light"],
    "red maids": ["calandrinia ciliata", "redmaids"],
    "red maple": ["acer rubrum", "scarlet maple", "swamp maple"],
    "red marrow": ["red bone marrow"],
    "red mulberry": ["morus rubra"],
    "red osier": ["american dogwood", "cornus stolonifera", "red dogwood", "red osier dogwood", "redbrush"],
    "red phalarope": ["phalaropus fulicarius"],
    "red pine": ["canadian red pine", "pinus resinosa"],
    "red porgy": ["pagrus pagrus"],
    "red rockfish": ["sebastodes ruberrimus"],
    "red salmon": ["sockeye", "sockeye salmon"],
    "red sandalwood": ["pterocarpus santalinus", "red sanders", "red sanderswood", "red saunders"],
    "red shift": ["redshift"],
    "red shrubby penstemon": ["redwood penstemon"],
    "red siskin": ["carduelis cucullata"],
    "red snapper": ["lutjanus blackfordi"],
    "red spider": ["panonychus ulmi", "red spider mite"],
    "red spruce": ["eastern spruce", "picea rubens", "yellow spruce"],
    "red squirrel": ["cat squirrel", "sciurus vulgaris"],
    "red trillium": ["sessile trillium", "toadshade", "trillium sessile"],
    "red underwing": ["catocala nupta"],
    "red valerian": ["centranthus ruber", "french honeysuckle"],
    "red wolf": ["canis niger", "canis rufus", "maned wolf"],
    "redact": ["redactor", "reviser", "rewrite man", "rewriter"],
    "redberry": ["rhamnus croceus"],
    "redbud": ["cercis canadensis"],
    "redcoat": ["lobsterback"],
    "reddish brown": ["burnt sienna", "mahogany", "sepia", "venetian red"],
    "reddish purple": ["royal purple"],
    "rede": ["interpret"],
    "redeem": ["pay off"],
    "redeemable": ["reformable"],
    "redemption": ["salvation"],
    "redemptive": ["redemptional", "redemptory"],
    "redeployment": ["redisposition"],
    "redevelop": ["reformulate"],
    "redeye": ["redeye flight"],
    "redfin pickerel": ["barred pickerel", "esox americanus"],
    "redfish": ["ocean perch", "rosefish"],
    "redford": ["charles robert redford", "robert redford"],
    "redhead": ["carrottop", "redheader"],
    "redheaded woodpecker": ["melanerpes erythrocephalus", "redhead"],
    "redhorse": ["redhorse sucker"],
    "redirect": ["airt"],
    "redirect examination": ["reexamination"],
    "redneck": ["cracker"],
    "redolent": ["smelling"],
    "redpoll": ["carduelis hornemanni"],
    "redress": ["remediation", "remedy"],
    "redshank": ["tringa totanus"],
    "redskin": ["injun", "red man"],
    "redstart": ["redtail"],
    "redstem storksbill": ["alfilaria", "alfileria", "clocks", "erodium cicutarium", "filaree", "filaria", "pin clover", "pin grass"],
    "redtail": ["buteo jamaicensis"],
    "reduce": ["bring down", "cut", "cut back", "cut down", "trim", "trim back", "trim down"],
    "reduced instruction set computing": ["reduced instruction set computer", "risc"],
    "reducing agent": ["reducer", "reductant"],
    "reducing diet": ["obesity diet"],
    "reductio ad absurdum": ["reductio"],
    "reduction": ["reducing"],
    "redundancy": ["redundance"],
    "reduplicate": ["geminate"],
    "reduplication": ["reiteration"],
    "reduviidae": ["family reduviidae"],
    "redwing": ["turdus iliacus"],
    "reed": ["john reed"],
    "reed bunting": ["emberiza schoeniclus"],
    "reed canary grass": ["phalaris arundinacea", "ribbon grass"],
    "reed meadow grass": ["glyceria grandis"],
    "reed rhapis": ["rhapis humilis", "slender lady palm"],
    "reedy": ["wheezy"],
    "reef knot": ["flat knot"],
    "reef squirrelfish": ["holocentrus coruscus"],
    "reefy": ["shelfy", "shelvy", "shoaly"],
    "reek": ["stink"],
    "reeking": ["watery"],
    "reel": ["scottish reel"],
    "reel off": ["unreel"],
    "reelect": ["return"],
    "reentrant angle": ["reentering angle"],
    "reentrant polygon": ["reentering polygon"],
    "refer": ["bear on", "come to", "concern", "pertain", "relate", "touch", "touch on"]
}
