synonyms = {
    "medical evacuation": ["evacuation", "medevac", "medivac"],
    "medical expense": ["disbursal", "disbursement", "expense"],
    "medical history": ["anamnesis", "case history", "medical record"],
    "medical institution": ["clinic", "establishment", "extended care facility", "hospital", "institution"],
    "medical instrument": ["auriscope", "auroscope", "ballistocardiograph", "bronchoscope", "cardiograph", "dialysis machine", "dialyzer", "diathermy machine", "electrocardiograph", "electroencephalograph", "electromyograph", "endoscope", "fiberscope", "instrument", "keratoscope", "laryngoscope", "ophthalmoscope", "otoscope", "polygraph", "rhinoscope", "speculum", "stethoscope", "surgical instrument", "syringe", "thermograph"],
    "medical literature analysis and retrieval system": ["medlars"],
    "medical officer": ["flight surgeon", "medic", "medical man", "medical practitioner", "surgeon general"],
    "medical practice": ["empiricism", "family medicine", "family practice", "group practice", "practice", "quackery"],
    "medical practitioner": ["caregiver", "dental practitioner", "dentist", "doc", "doctor", "dr.", "health care provider", "health professional", "inoculator", "md", "medic", "medical man", "medical officer", "medico", "pcp", "physician", "primary care provider", "tooth doctor", "vaccinator"],
    "medical procedure": ["dental procedure", "operation", "procedure", "process", "surgery", "surgical operation", "surgical procedure", "surgical process"],
    "medical profession": ["health profession", "medical community"],
    "medical relation": ["doctor-patient relation", "nurse-patient relation", "professional relation"],
    "medical report": ["report", "study", "written report"],
    "medical school": ["grad school", "graduate school", "school of medicine"],
    "medical science": ["bioscience", "life science", "medical specialty", "medicine", "neurology", "orthopaedics", "orthopedics", "pathology", "radiology", "serology", "surgery"],
    "medical scientist": ["epidemiologist", "immunologist", "scientist", "serologist", "toxicologist"],
    "medical student": ["educatee", "medico", "pupil", "student"],
    "medically": [],
    "medicare": ["health care"],
    "medicare check": ["bank check", "check", "cheque", "medicare payment"],
    "medicate": ["impregnate", "saturate"],
    "medication": ["administration", "antipyresis", "giving medication", "therapy"],
    "medicative": ["medicinal"],
    "medici": ["house"],
    "medicinal leech": ["bloodsucker", "hirudinean", "hirudo medicinalis", "leech"],
    "medicinally": [],
    "medicine": ["accident surgery", "allergology", "anesthesiology", "angiology", "bacteriology", "biomedicine", "cardiology", "chiropody", "clinical neurology", "dental medicine", "dentistry", "dermatology", "diagnostics", "emergency medicine", "endocrinology", "epidemiology", "forensic medicine", "forensic pathology", "gastroenterology", "general medicine", "geriatrics", "gerontology", "gynaecology", "gynecology", "haematology", "hematology", "hygiene", "hygienics", "immunology", "internal medicine", "materia medica", "medical science", "medical specialty", "midwifery", "nephrology", "neurology", "neuropsychiatry", "nosology", "nuclear medicine", "ob", "obstetrics", "odontology", "oncology", "ophthalmology", "otolaryngology", "otology", "otorhinolaryngology", "paediatrics", "pediatric medicine", "pediatrics", "pedology", "pharmaceutics", "pharmacological medicine", "pharmacology", "pharmacy", "podiatry", "proctology", "prosthetics", "psychiatry", "psychological medicine", "psychopathology", "rheumatology", "rhinolaryngology", "space medicine", "sports medicine", "therapeutics", "thoracic medicine", "tocology", "traumatology", "tropical medicine", "urogenital medicine", "urology", "veterinary medicine", "virology"],
    "medicine ball": ["ball"],
    "medicine chest": ["cabinet", "medicine cabinet"],
    "medicine man": ["priest-doctor", "rainmaker", "shaman"],
    "medicolegal": [],
    "medieval": ["mediaeval"],
    "medieval greek": ["byzantine greek", "greek", "hellenic", "hellenic language", "middle greek"],
    "medieval latin": ["low latin"],
    "medina": ["al madinah"],
    "medinilla": ["genus medinilla", "rosid dicot genus"],
    "medinilla magnifica": ["bush", "shrub"],
    "mediocre": ["second-rate"],
    "meditation": ["contemplation", "musing", "reflection", "reflexion", "rumination", "thoughtfulness"],
    "meditatively": [],
    "mediterranean": ["mare nostrum", "mediterranean sea"],
    "mediterranean anchovy": ["anchovy", "engraulis encrasicholus"],
    "mediterranean flour moth": ["anagasta kuehniella", "pyralid", "pyralid moth"],
    "mediterranean fruit fly": ["ceratitis capitata", "fruit fly", "medfly", "pomace fly"],
    "mediterranean snapdragon": ["antirrhinum majus", "snapdragon"],
    "mediterranean water shrew": ["neomys anomalus", "water shrew"],
    "medium": ["liquid", "magilp", "megilp"],
    "medium frequency": ["mf", "radio frequency"],
    "medium of exchange": ["criterion", "currency", "legal tender", "measure", "monetary system", "money", "stamp", "standard", "tender", "touchstone"],
    "medium steel": ["steel"],
    "medium wave": ["radio emission", "radio radiation", "radio wave"],
    "medium-dry": [],
    "medium-large": [],
    "medium-sized": ["medium-size", "moderate-size", "moderate-sized"],
    "medlar": ["fruit tree", "medlar tree", "mespilus germanica"],
    "medley": ["composition", "musical composition", "opus", "pastiche", "piece", "piece of music", "potpourri"],
    "medline": ["phone system", "telephone system"],
    "medoc": ["bordeaux", "bordeaux wine", "red wine"],
    "medroxyprogesterone": ["progestin", "progestogen", "provera"],
    "medulla": ["adrenal medulla", "animal tissue", "plant tissue"],
    "medulla oblongata": ["bulb", "medulla", "neural structure"],
    "medullary": [],
    "medullary sheath": ["case", "myelin sheath", "sheath"],
    "medullated nerve fiber": ["myelinated nerve fiber", "nerve fiber", "nerve fibre"],
    "medusa": ["gorgon"],
    "medusa's head": ["euphorbia caput-medusae", "euphorbia medusae", "spurge"],
    "medusoid": [],
    "meed": ["reward"],
    "meek": ["tame"],
    "meekly": [],
    "meekness": ["humbleness", "humility", "submission"],
    "meerkat": ["mierkat", "slender-tailed meerkat", "suricata suricatta", "suricata tetradactyla", "suricate", "viverrine", "viverrine mammal"],
    "meerschaum": ["mineral", "sepiolite"],
    "meet": ["encounter", "experience", "have", "receive"],
    "meet up with": ["meet"],
    "meeting": ["appointment", "conventicle", "date", "engagement", "get together", "lunch meeting", "luncheon meeting", "power breakfast", "seance", "session", "sitting", "social affair", "social gathering", "visit"],
    "meeting house": ["aquilege", "aquilegia", "aquilegia canadensis", "columbine", "honeysuckle"],
    "mefenamic acid": ["nonsteroidal anti-inflammatory", "nonsteroidal anti-inflammatory drug", "nsaid", "ponstel"],
    "mefloquine": ["antimalarial", "antimalarial drug", "larium", "mefloquine hydrochloride", "mephaquine"],
    "megabit": ["computer memory unit", "mb", "mbit"],
    "megabyte": ["computer memory unit", "m", "mb"],
    "megachile": ["arthropod genus", "genus megachile"],
    "megachilidae": ["arthropod family", "family megachilidae"],
    "megachiroptera": ["animal order", "suborder megachiroptera"],
    "megacolon": ["colon"],
    "megadeath": ["death", "decease", "expiry"],
    "megaderma": ["genus megaderma", "mammal genus"],
    "megadermatidae": ["family megadermatidae", "mammal family"],
    "megaera": ["erinyes", "eumenides", "fury"],
    "megaflop": ["mflop", "million floating point operations per second", "unit", "unit of measurement"],
    "megagametophyte": ["gametophyte"],
    "megahertz": ["mc", "megacycle", "megacycle per second", "mhz", "rate"],
    "megakaryocyte": ["bone cell"],
    "megakaryocytic": [],
    "megalith": ["cromlech", "dolmen", "megalithic structure", "memorial", "menhir", "monument", "portal tomb", "standing stone"],
    "megalithic": [],
    "megalobatrachus": ["amphibian genus", "genus megalobatrachus"],
    "megaloblast": ["erythrocyte", "rbc", "red blood cell"],
    "megaloblastic": [],
    "megaloblastic anemia": ["malignant anaemia", "malignant anemia", "megaloblastic anaemia", "pernicious anaemia", "pernicious anemia"],
    "megalocyte": ["erythrocyte", "macrocyte", "rbc", "red blood cell"],
    "megalomania": ["mental disease", "mental illness", "psychopathy"],
    "megalomaniac": ["egoist", "egotist", "swellhead"],
    "megalomaniacal": ["megalomanic"],
    "megalonychidae": ["family megalonychidae", "mammal family"],
    "megalopolis": ["populated area", "urban area"],
    "megaloptera": ["animal order", "suborder megaloptera"],
    "megalosaur": ["bird-footed dinosaur", "megalosaurus", "theropod", "theropod dinosaur"],
    "megalosauridae": ["family megalosauridae", "reptile family"],
    "megaphone": ["acoustic device"],
    "megapode": ["alectura lathami", "brush turkey", "gallinacean", "gallinaceous bird", "leipoa", "leipoa ocellata", "lowan", "macrocephalon maleo", "maleo", "mallee fowl", "mound bird", "mound builder", "mound-bird", "scrub fowl"],
    "megapodiidae": ["bird family", "family megapodiidae"],
    "megapodius": ["bird genus", "genus-megapodius"],
    "megaptera": ["genus megaptera", "mammal genus"],
    "megascopic": ["gross"],
    "megasporangium": ["macrosporangium", "sporangium", "spore case", "spore sac"],
    "megaspore": ["macrospore", "spore"],
    "megasporophyll": ["sporophyl", "sporophyll"],
    "megatherian": ["edentate", "ground sloth", "megathere", "megatherian mammal", "megatheriid"],
    "megatheriidae": ["family megatheriidae", "mammal family"],
    "megatherium": ["genus megatherium", "mammal genus"],
    "megaton": ["avoirdupois unit"],
    "megaton bomb": ["atomic weapon", "bomb", "nuclear weapon"],
    "megavitamin therapy": ["therapy"],
    "megawatt": ["power unit"],
    "megestrol": ["megestrol acetate", "progestin", "progestogen"],
    "megillah": ["account", "report"],
    "megilp": ["magilp", "medium"],
    "megohm": ["resistance unit"],
    "meibomian gland": ["glandulae sebaceae", "sebaceous follicle", "sebaceous gland", "tarsal gland"],
    "meiji tenno": ["mutsuhito"],
    "meiosis": ["cell division", "cellular division", "miosis", "nondisjunction", "reduction division"],
    "meiotic": [],
    "meir": ["golda meir"],
    "meissner": ["georg meissner"],
    "meitner": ["lise meitner"],
    "meitnerium": ["atomic number 109", "chemical element", "element", "element 109", "mt"],
    "mekong": ["mekong river"],
    "melagra": ["hurting", "pain"],
    "melamine": ["alkali", "base", "cyanuramide"],
    "melamine resin": ["synthetic resin"],
    "melampodium": ["asterid dicot genus", "genus melampodium"],
    "melampsora": ["fungus genus", "genus melampsora"],
    "melampsoraceae": ["family melampsoraceae", "fungus family"],
    "melancholia": ["depression"],
    "melancholic": ["depressive", "melancholiac"],
    "melancholy": ["depression"],
    "melancholy thistle": ["cirsium helenioides", "cirsium heterophylum", "thistle"],
    "melanchthon": ["philipp melanchthon", "philipp schwarzerd"],
    "melanerpes": ["bird genus", "genus melanerpes"],
    "melanesia": [],
    "melanesian": [],
    "melanin": ["animal pigment"],
    "melanitta": ["bird genus", "genus melanitta"],
    "melanize": ["convert", "melanise"],
    "melanoblast": ["epidermal cell"],
    "melanocyte": ["epidermal cell"],
    "melanocyte-stimulating hormone": ["endocrine", "hormone", "internal secretion", "msh"],
    "melanoderma": ["pigmentation"],
    "melanogrammus": ["fish genus", "genus melanogrammus"],
    "melanoma": ["malignant melanoma", "skin cancer"],
    "melanoplus": ["arthropod genus", "genus melanoplus"],
    "melanosis": ["disease of the skin", "melanism", "skin disease", "skin disorder"],
    "melanotis": ["bird genus", "genus melanotis"],
    "melanthiaceae": ["family melanthiaceae", "liliid monocot family"],
    "melastoma": ["genus melastoma", "rosid dicot genus"],
    "melastomataceae": ["family melastomaceae", "family melastomataceae", "meadow-beauty family", "melastomaceae", "rosid dicot family"],
    "melatonin": ["endocrine", "hormone", "internal secretion"],
    "melba": ["dame nellie melba", "helen porter mitchell"],
    "melba toast": ["toast"],
    "melbourne": [],
    "melchior": ["lauritz lebrecht hommel melchior", "lauritz melchior"],
    "meld": ["announce", "denote"],
    "meleagrididae": ["bird family", "family meleagrididae"],
    "meleagris": ["bird genus", "genus meleagris"],
    "melee": ["battle royal", "disturbance", "scrimmage"],
    "melena": ["bm", "dejection", "faecal matter", "faeces", "fecal matter", "feces", "melaena", "ordure", "stool"],
    "meles": ["genus meles", "mammal genus"],
    "melia": ["genus melia", "rosid dicot genus"],
    "meliaceae": ["family meliaceae", "mahogany family", "rosid dicot family"],
    "melicoccus": ["dicot genus", "genus melicocca", "genus melicoccus", "magnoliopsid genus", "melicocca"],
    "melicytus": ["dilleniid dicot genus", "genus melicytus"],
    "melilotus": ["ligneous plant", "melilot", "melilotus alba", "melilotus officinalis", "sweet clover", "white melilot", "white sweet clover", "woody plant", "yellow sweet clover"],
    "melinae": ["mammal family", "subfamily melinae"],
    "melioration": ["drift"],
    "meliorism": ["belief"],
    "meliphagidae": ["bird family", "family meliphagidae"],
    "melissa": ["asterid dicot genus", "genus melissa"],
    "melkite": ["christian", "melchite"],
    "mellivora": ["genus mellivora", "mammal genus"],
    "mellon": ["andrew mellon", "andrew w. mellon", "andrew william mellon"],
    "mellow": ["soften"],
    "mellowing": ["ageing", "aging", "ripening"],
    "mellowingly": [],
    "mellowly": ["mellow"],
    "mellowness": ["kind-heartedness", "kindheartedness"],
    "melocactus": ["caryophylloid dicot genus", "genus melocactus"],
    "melodic": [],
    "melodically": [],
    "melodious": ["melodic", "musical"],
    "melodiously": ["tunefully"],
    "melodiousness": ["musicality", "musicalness", "tunefulness"],
    "melodize": ["compose", "melodise", "write"],
    "melodrama": ["comedy"],
    "melodramatic": [],
    "melodramatically": [],
    "melody": ["musical perception", "tonal pattern"],
    "melogale": ["genus melogale", "mammal genus"],
    "meloidae": ["arthropod family", "family meloidae"],
    "melolontha": ["arthropod genus", "genus melolontha"],
    "melolonthid beetle": ["cockchafer", "macrodactylus subspinosus", "may beetle", "may bug", "melolontha melolontha", "rose bug", "rose chafer", "scarabaean", "scarabaeid", "scarabaeid beetle"],
    "melolonthidae": ["arthropod family", "subfamily melolonthidae"],
    "melon": ["citrullus vulgaris", "cucumber", "cucumber vine", "cucumis melo", "cucumis sativus", "gourd", "gourd vine", "melon vine", "muskmelon", "sweet melon", "sweet melon vine", "watermelon", "watermelon vine"],
    "melon ball": ["melon"],
    "melophagus": ["arthropod genus", "genus melophagus"],
    "melopsittacus": ["bird genus", "genus melopsittacus"],
    "melosa": ["chile tarweed", "madia oil plant", "madia sativa", "tarweed"],
    "melospiza": ["bird genus", "genus melospiza"],
    "melphalan": ["alkeran", "antineoplastic", "antineoplastic drug", "cancer drug"],
    "melpomene": [],
    "melt": ["break up", "dissolve", "fuse", "melt down", "render", "resolve", "run", "try"],
    "meltable": ["disintegrable"],
    "meltdown": ["nuclear meltdown", "overheating"],
    "melted": ["liquid", "liquified"],
    "melter": ["worker"],
    "melting pot": ["environment", "environs", "surround", "surroundings"],
    "meltwater": ["h2o", "water"],
    "melursus": ["genus melursus", "mammal genus"],
    "melville": ["herman melville"],
    "mem": ["alphabetic character", "letter", "letter of the alphabet"],
    "member": ["component", "component part", "constituent", "part", "portion"],
    "member bank": ["bank", "banking company", "banking concern", "depository financial institution"],
    "membered": [],
    "memberless": [],
    "membership": ["relationship"],
    "membership card": ["card", "identity card", "union card"],
    "membracidae": ["arthropod family", "family membracidae"],
    "membrane": ["adventitia", "animal tissue", "axolemma", "basilar membrane", "bowman's capsule", "capsula glomeruli", "chorioallantoic membrane", "chorioallantois", "choroid", "choroid coat", "ciliary body", "cornea", "diaphragm", "eardrum", "endocranium", "endosteum", "ependyma", "fertilization membrane", "fetal membrane", "glomerular capsule", "hyaloid", "hyaloid membrane", "intima", "iris", "lamella", "meninges", "meninx", "midriff", "mucosa", "mucous membrane", "myringa", "periosteum", "perithelium", "retina", "sarcolemma", "semipermeable membrane", "serosa", "serous membrane", "synovial membrane", "synovium", "tissue layer", "trophoblast", "tunic", "tunica", "tympanic membrane", "tympanum", "web"],
    "membrane bone": ["bone", "forehead", "frontal bone", "occipital bone", "os", "os frontale", "parietal bone"],
    "membranous": [],
    "membranous labyrinth": ["anatomical structure", "bodily structure", "body structure", "complex body part", "structure"],
    "meme": ["acculturation", "culture"],
    "memento": ["reminder", "souvenir"],
    "memento mori": ["reminder"],
    "memo": ["aide-memoire", "memoranda", "memorandum", "note", "position paper"],
    "memoir": ["autobiography"],
    "memorabilia": ["record"],
    "memorability": ["quality"],
    "memorable": [],
    "memorably": ["unforgettably"],
    "memorial": ["commemoration", "credit", "epitaph", "festschrift", "recognition", "remembrance"],
    "memorial day": ["decoration day", "legal holiday", "national holiday", "public holiday"],
    "memorialize": ["address", "memorialise", "speak"],
    "memorization": ["acquisition", "committal to memory", "learning", "memorisation", "rote", "rote learning"],
    "memorize": ["alternate", "con", "hit the books", "learn", "memorise", "study", "understudy"],
    "memorizer": ["assimilator", "learner", "memoriser", "scholar", "study"],
    "memory": ["cognitive psychology"],
    "memory chip": ["chip", "micro chip", "microchip", "microprocessor chip", "read-only memory chip", "silicon chip"],
    "memory device": ["acoustic storage", "auxiliary storage", "buffer", "buffer storage", "buffer store", "computer memory", "computer storage", "device", "disc", "disk", "external storage", "mag tape", "magnetic disc", "magnetic disk", "magnetic tape", "memory", "memory board", "optical disc", "optical disk", "push-down storage", "push-down store", "recording", "register", "secondary storage", "stack", "storage", "storage device", "store", "tape"],
    "memory image": ["afterimage", "aftersensation", "image", "memory picture", "mental image"],
    "memory picture": ["memory image"],
    "memphis": [],
    "memsahib": ["sahib"],
    "men's room": ["comfort station", "convenience", "men's", "public convenience", "public lavatory", "public toilet", "restroom", "toilet facility", "wash room"],
    "menace": ["evince", "express", "show"],
    "menacingly": ["threateningly"],
    "menage a trois": ["family", "home", "house", "household", "menage"],
    "menagerie": ["accumulation", "aggregation", "assemblage", "collection"],
    "menai strait": [],
    "menander": [],
    "menarche": ["start"],
    "mencken": ["h. l. mencken", "henry louis mencken"],
    "mend": ["ameliorate", "better", "heal", "improve", "meliorate"],
    "mendacious": [],
    "mendaciously": ["untruthfully"],
    "mendacity": ["untruthfulness"],
    "mendel": ["gregor mendel", "johann mendel"],
    "mendel's law": ["law", "law of independent assortment", "law of nature", "law of segregation"],
    "mendelevium": ["atomic number 101", "chemical element", "element", "md", "mv"],
    "mendeleyev": ["dmitri ivanovich mendeleev", "dmitri ivanovich mendeleyev", "dmitri mendeleev", "dmitri mendeleyev", "mendeleev"],
    "mendelian": ["follower"],
    "mendelism": ["mendelianism", "theory of inheritance"],
    "mendelsohn": ["erich mendelsohn"],
    "mendelssohn": ["felix mendelssohn", "jakob ludwig felix mendelssohn-bartholdy"],
    "mendenhall glacier": ["great mendenhall glacier"],
    "mender": ["darner", "fixer", "maintenance man", "repairer", "repairman", "service man", "skilled worker", "skilled workman", "trained worker"],
    "mendicant": [],
    "mending": ["garment"],
    "menelaus": [],
    "menhaden": ["brevoortia tyrannis", "clupeid", "clupeid fish"],
    "menhaden oil": ["animal oil"],
    "menhir": ["megalith", "megalithic structure", "standing stone"],
    "menial": ["retainer", "servant"],
    "menially": [],
    "meniere": ["prosper meniere"],
    "meniere's disease": ["disease"],
    "meningeal": [],
    "meningeal artery": ["anterior meningeal artery", "arteria", "arteria meningea", "arterial blood vessel", "artery", "middle meningeal artery", "posterior meningeal artery"],
    "meningeal veins": ["vein", "vena", "venae meningeae", "venous blood vessel"],
    "meningioma": ["neoplasm", "tumor", "tumour"],
    "meningism": ["symptom"],
    "meningitis": ["brain fever", "cerebromeningitis", "cerebrospinal fever", "cerebrospinal meningitis", "choriomeningitis", "encephalomeningitis", "epidemic meningitis", "infectious disease", "leptomeningitis", "meningoencephalitis"],
    "meningocele": ["birth defect", "congenital abnormality", "congenital anomaly", "congenital defect", "congenital disorder"],
    "meningoencephalitis": ["cephalitis", "cerebromeningitis", "encephalitis", "encephalomeningitis", "meningitis", "phrenitis"],
    "meninx": ["arachnoid", "arachnoid membrane", "dura", "dura mater", "leptomeninges", "membrane", "meninges", "pia mater", "tissue layer"],
    "menippe": ["arthropod genus", "genus menippe"],
    "meniscectomy": ["ablation", "cutting out", "excision", "extirpation"],
    "meniscium": ["fern genus", "genus meniscium"],
    "meniscus": ["cartilage", "gristle", "semilunar cartilage"],
    "menispermaceae": ["family menispermaceae", "magnoliid dicot family", "moonseed family"],
    "menispermum": ["genus menispermum", "magnoliid dicot genus"],
    "menninger": ["william claire menninger", "william menninger"],
    "mennonite": ["amish", "anabaptist"],
    "mennonite church": ["protestant denomination"],
    "mennonitism": ["protestantism"],
    "meno mosso": ["pacing", "tempo"],
    "menomini": ["algonquian", "algonquin", "menominee"],
    "menopausal": [],
    "menopause": ["biological time", "change of life", "climacteric"],
    "menopon": ["arthropod genus", "genus menopon"],
    "menorah": ["candelabra", "candelabrum"],
    "menorrhagia": ["catamenia", "flow", "hypermenorrhea", "menses", "menstruation", "menstruum", "period", "symptom"],
    "menorrhea": ["blood", "menstrual blood", "menstrual flow"],
    "menotti": ["gian carlo menotti"],
    "menotyphla": ["animal order", "suborder menotyphla"],
    "mens rea": ["malice aforethought", "planning", "premeditation", "preparation", "provision"],
    "mensa": [],
    "mensal": [],
    "mensch": ["good person", "mensh"],
    "menshevik": ["socialist"],
    "menstrual": ["catamenial"],
    "menstrual cycle": ["cycle", "oscillation"],
    "menstrual phase": ["phase", "stage"],
    "menstruate": ["bleed", "flow", "hemorrhage", "shed blood"],
    "menstruation": ["catamenia", "discharge", "emission", "expelling", "flow", "hypermenorrhea", "menorrhagia", "menses", "menstruum", "oligomenorrhea", "period"],
    "menstruum": ["dissolvent", "dissolver", "dissolving agent", "resolvent", "solvent"],
    "mensural": [],
    "mental": [],
    "mental abnormality": ["abnormalcy", "abnormality", "organic brain syndrome"],
    "mental age": ["age"],
    "mental anguish": ["pain", "painfulness"],
    "mental disorder": ["aberration", "affective disorder", "anxiety disorder", "asperger's syndrome", "conversion disorder", "conversion hysteria", "conversion reaction", "delirium", "delusional disorder", "disorder", "dissociative disorder", "disturbance", "emotional disorder", "emotional disturbance", "encopresis", "folie", "folie a deux", "major affective disorder", "mental disturbance", "neurosis", "neuroticism", "personality disorder", "psychological disorder", "psychoneurosis", "psychosomatic disorder", "schizothymia", "upset"],
    "mental exhaustion": ["brain-fag", "exhaustion"],
    "mental health": ["mental balance", "mental condition", "mental soundness", "mental state", "psychological condition", "psychological state", "saneness", "sanity"],
    "mental hospital": ["asylum", "bedlam", "booby hatch", "crazy house", "cuckoo's nest", "funny farm", "funny house", "hospital", "infirmary", "insane asylum", "institution", "loony bin", "madhouse", "mental home", "mental institution", "nut house", "nuthouse", "psychiatric hospital", "sanatorium", "snake pit"],
    "mental illness": ["insanity", "megalomania", "mental condition", "mental disease", "mental state", "psychological condition", "psychological state", "psychopathy", "psychosis"],
    "mental measurement": ["measure", "measurement", "measuring", "mensuration", "mental test", "mental testing", "psychometric test", "test"],
    "mental note": ["attention"],
    "mental picture": ["image", "impression", "mental image", "picture"],
    "mental quickness": ["intelligence", "quick-wittedness", "quickness"],
    "mental reservation": ["arriere pensee", "doubt", "doubtfulness", "dubiety", "dubiousness", "incertitude", "reservation", "uncertainty"],
    "mental soundness": ["mental balance", "mental health"],
    "mentalism": ["philosophical doctrine", "philosophical theory"],
    "mentality": ["attitude", "mental attitude", "mind-set", "mindset", "outlook"],
    "mentally": [],
    "mentally ill": ["unsound", "unstable"],
    "mentally retarded": ["developmentally challenged", "people", "retarded"],
    "mentha": ["asterid dicot genus", "genus mentha"],
    "menthol": ["chemical compound", "compound"],
    "mentholated": [],
    "mentholated salve": ["balm", "ointment", "salve", "unction", "unguent"],
    "menticirrhus": ["fish genus", "genus menticirrhus"],
    "mention": ["advert", "appeal", "bring up", "cite", "commend", "cross-refer", "drag up", "dredge up", "have in mind", "invoke", "mean", "name", "namedrop", "quote", "raise", "refer", "remember", "speak of the devil", "think of", "touch on"],
    "mentioner": ["speaker", "talker", "utterer", "verbaliser", "verbalizer"],
    "mentor": ["instruct", "learn", "teach"],
    "mentum": ["plant part", "plant structure"],
    "mentzelia": ["dilleniid dicot genus", "genus mentzelia"],
    "menu": ["fare"],
    "menuhin": ["sir yehudi menuhin", "yehudi menuhin"],
    "menura": ["bird genus", "genus menura"],
    "menurae": ["animal order", "suborder menurae"],
    "menuridae": ["bird family", "family menuridae"],
    "menyanthaceae": ["buckbean family", "dicot family", "family menyanthaceae", "magnoliopsid family"],
    "menyanthes": ["dicot genus", "genus menyanthes", "magnoliopsid genus"],
    "menziesia": ["dilleniid dicot genus", "genus menziesia"],
    "meow": ["emit", "let loose", "let out", "mew", "utter"],
    "meperidine": ["demerol", "meperidine hydrochloride", "narcotic"],
    "mephenytoin": ["anticonvulsant", "anticonvulsant drug", "antiepileptic", "antiepileptic drug", "mesantoin"],
    "mephistopheles": [],
    "mephitinae": ["mammal family", "subfamily mephitinae"],
    "mephitis": ["gas"],
    "mephobarbital": ["anticonvulsant", "anticonvulsant drug", "antiepileptic", "antiepileptic drug", "barbiturate", "mebaral"],
    "meprobamate": ["antianxiety drug", "anxiolytic", "anxiolytic drug", "equanil", "meprin", "miltown", "minor tranquilizer", "minor tranquilliser", "minor tranquillizer"],
    "meralgia": ["hurting", "pain"],
    "merbromine": ["antiseptic", "mercurochrome"],
    "mercalli scale": ["graduated table", "ordered series", "scale", "scale of measurement"],
    "mercantile": [],
    "mercantile agency": ["agency", "commercial agency"],
    "mercantile establishment": ["business establishment", "center", "country store", "department store", "discount house", "discount store", "discounter", "emporium", "general store", "mall", "market", "market place", "marketplace", "mart", "outlet", "place of business", "plaza", "retail store", "sales outlet", "shop", "shopping center", "shopping centre", "shopping mall", "store", "strip mall", "trading post", "wholesale house"],
    "mercantile law": ["commercial law", "jurisprudence", "law", "law merchant"],
    "mercantilism": ["managed economy", "mercantile system"],
    "mercaptopurine": ["antimetabolite", "immune suppressant drug", "immunosuppressant", "immunosuppressive", "immunosuppressive drug", "immunosuppressor", "purinethol"],
    "mercator": ["gerardus mercator", "gerhard kremer"],
    "mercator projection": ["map projection", "mercator's projection"],
    "mercedario": [],
    "mercenaria": ["genus mercenaria", "mollusk genus"],
    "mercenary": ["adventurer", "ninja", "soldier of fortune", "venturer"],
    "mercer": ["john mercer"],
    "mercerize": ["mercerise", "process", "treat"],
    "mercerized": ["mercerised"],
    "merchandise": ["business line", "cargo", "commodity", "consignment", "contraband", "dreck", "feature", "freight", "generic", "good", "inventory", "ironmongery", "irregular", "lading", "line", "line of business", "line of merchandise", "line of products", "load", "loading", "number", "payload", "piece goods", "product", "product line", "refill", "release", "schlock", "second", "shipment", "shlock", "software package", "software product", "stock", "top of the line", "trade good", "ware", "yard goods"],
    "merchant": ["baker", "bargainer", "book seller", "bookdealer", "bourgeois", "businessperson", "butcher", "clothier", "dealer", "grain merchant", "grocer", "haberdasher", "hatmaker", "hatter", "jeweler", "jeweller", "market keeper", "marketer", "meatman", "merchandiser", "merchant-venturer", "milliner", "modiste", "monger", "poulterer", "poultryman", "retail merchant", "retailer", "rug merchant", "salt merchant", "salter", "schlockmeister", "seller", "shlockmeister", "shopkeeper", "stationer", "stationery seller", "storekeeper", "trader", "tradesman", "trafficker", "vender", "vendor", "venturer", "vintner", "wine merchant"],
    "merchant bank": ["acquirer", "bank", "banking company", "banking concern", "depository financial institution"],
    "merchant marine": ["crew"],
    "merchantability": ["sale", "state"],
    "merciful": [],
    "mercifully": [],
    "mercifulness": ["compassion", "compassionateness", "forgiveness", "mercy"],
    "merciless": ["unmerciful"],
    "mercilessly": ["pitilessly", "remorselessly", "unmercifully"],
    "mercilessness": ["inexorability", "inexorableness", "inhumaneness", "inhumanity", "pitilessness", "relentlessness", "ruthlessness", "unmercifulness"],
    "merckx": ["eddy merckx"],
    "mercouri": ["anna amalia mercouri", "melina mercouri"],
    "mercurial": [],
    "mercurial ointment": ["balm", "ointment", "salve", "unction", "unguent"],
    "mercurialis": ["genus mercurialis", "rosid dicot genus"],
    "mercuric": ["mercurous"],
    "mercuric chloride": ["bichloride of mercury", "corrosive sublimate", "mercury chloride", "sublimate"],
    "mercury": ["atomic number 80", "hg", "hydrargyrum", "metal", "metallic element", "quicksilver"],
    "mercury barometer": ["barometer"],
    "mercury cell": ["galvanic cell", "primary cell", "voltaic cell"],
    "mercury fulminate": ["fulminate", "fulminate of mercury", "fulminating mercury"],
    "mercury poisoning": ["intoxication", "minamata disease", "poisoning", "toxic condition"],
    "mercury program": [],
    "mercury thermometer": ["beckman thermometer", "clinical thermometer", "mercury-in-glass clinical thermometer", "mercury-in-glass thermometer", "thermometer"],
    "mercury-contaminated": [],
    "mercury-vapor lamp": ["quartz lamp", "sun lamp", "sun-ray lamp", "sunlamp", "sunray lamp", "ultraviolet lamp", "ultraviolet source"],
    "mercy": ["blessing", "boon"],
    "mercy seat": ["throne"],
    "mere": ["pond", "pool"],
    "meredith": ["james howard meredith", "james meredith"],
    "merely": ["but", "just", "only", "simply"],
    "merestone": ["landmark", "mearstone", "meerestone"],
    "meretricious": [],
    "meretriciously": ["flashily"],
    "merganser": ["american merganser", "fish duck", "goosander", "hooded merganser", "hooded sheldrake", "lophodytes cucullatus", "mergus albellus", "mergus merganser", "mergus merganser americanus", "mergus serrator", "red-breasted merganser", "sawbill", "sea duck", "sheldrake", "smew"],
    "mergenthaler": ["ottmar mergenthaler"],
    "merger agreement": ["acquisition agreement", "contract"],
    "merginae": ["bird family", "subfamily merginae"],
    "merging": ["coming together", "concourse", "confluence", "convergence", "convergency", "converging", "meeting"],
    "mergus": ["bird genus", "genus mergus"],
    "mericarp": ["carpel"],
    "merida": [],
    "meridian": [],
    "meridional": [],
    "meringue": ["topping"],
    "meringue kiss": ["candy kiss", "kiss"],
    "merino": ["domestic sheep", "merino sheep", "ovis aries"],
    "meriones": ["genus meriones", "mammal genus"],
    "meristem": ["plant tissue"],
    "merit": ["virtue", "worth"],
    "merit badge": ["badge"],
    "merit pay": ["earnings", "pay", "remuneration", "salary", "wage"],
    "merit system": ["system", "system of rules"],
    "merited": ["deserved"],
    "meritocracy": ["social organisation", "social organization", "social structure", "social system", "structure"],
    "meritocratic": [],
    "meritorious": ["meritable"],
    "meritoriously": [],
    "merlangus": ["fish genus", "genus merlangus"],
    "merlin": [],
    "merlon": ["bulwark", "rampart", "wall"],
    "merlot": ["common grape vine", "vinifera", "vinifera grape", "vitis vinifera"],
    "merluccius": ["fish genus", "genus merluccius"],
    "mermaid": ["imaginary being", "imaginary creature"],
    "merman": ["ethel merman"],
    "meromelia": ["adactylia", "adactylism", "adactyly", "birth defect", "congenital abnormality", "congenital anomaly", "congenital defect", "congenital disorder", "phocomelia", "seal limbs"],
    "meronym": ["part name", "word"],
    "meronymy": ["part to whole relation", "semantic relation"],
    "meropidae": ["bird family", "family meropidae"],
    "merops": ["bird genus", "genus merops"],
    "merostomata": ["arthropod", "class merostomata"],
    "merovingian": ["crowned head", "monarch", "sovereign"],
    "merozoite": ["sporozoan"],
    "merrimac": [],
    "merrimack": ["merrimack river"],
    "merry-go-round": ["cycle"],
    "merrymaking": ["celebration", "conviviality", "festivity", "high jinks", "high jinx", "hijinks", "jinks", "jollification", "revel", "revelry"],
    "mertensia": ["genus mertensia", "plant genus"],
    "merton": ["thomas merton"],
    "meryta": ["genus meryta", "rosid dicot genus"],
    "mesa": ["plateau", "table", "tableland"],
    "mesa verde national park": [],
    "mesabi range": [],
    "mesalliance": ["misalliance"],
    "mesasamkranti": ["holiday"],
    "mescal": ["cactus", "lophophora williamsii", "mezcal", "peyote"],
    "mescal bean": ["coral bean", "frijolillo", "frijolito", "sophora secundiflora", "tree"],
    "mescal button": ["magic mushroom", "plant organ", "sacred mushroom"],
    "mescaline": ["hallucinogen", "hallucinogenic drug", "peyote", "psychedelic drug", "psychodelic drug"],
    "mesembryanthemum": ["caryophylloid dicot genus", "genus mesembryanthemum"],
    "mesenchyme": ["mesoblast", "mesoderm"],
    "mesenteric": [],
    "mesenteric artery": ["arteria", "arteria mesenterica", "arterial blood vessel", "artery", "inferior mesenteric artery", "superior mesenteric artery"],
    "mesenteric plexus": ["nerve plexus", "plexus mesentericus"],
    "mesenteric vein": ["vein", "vena", "vena mesenterica", "venous blood vessel"],
    "mesentery": ["mesocolon", "peritoneum"],
    "mesh": ["relate"],
    "mesh topology": ["mesh", "network topology", "topology"],
    "meshed": [],
    "meshugaas": ["craziness", "folly", "foolery", "indulgence", "lunacy", "mishegaas", "mishegoss", "tomfoolery"],
    "meshugge": ["meshuga", "meshugga", "meshuggeneh", "meshuggener"],
    "meshuggeneh": ["fool", "meshuggener", "muggins", "sap", "saphead", "tomfool"],
    "mesial": [],
    "mesic": [],
    "mesmer": ["franz anton mesmer", "friedrich anton mesmer"],
    "mesne lord": ["lord", "noble", "nobleman"],
    "mesoamerica": [],
    "mesoamerican": ["american"],
    "mesoblastic": ["mesodermal"],
    "mesocarp": ["pericarp", "seed vessel"],
    "mesocolon": ["mesentery"],
    "mesocricetus": ["genus mesocricetus", "mammal genus"],
    "mesoderm": ["chordamesoderm", "chordomesoderm", "germ layer", "mesenchyme", "mesoblast"],
    "mesohippus": ["equus caballus", "horse"],
    "mesolithic": [],
    "mesolithic age": ["epipaleolithic", "mesolithic"],
    "mesomorph": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "mesomorphic": ["muscular"],
    "meson": ["b-meson", "boson", "hadron", "j particle", "k particle", "k-meson", "kaon", "kappa-meson", "mesotron", "pi-meson", "pion", "psi particle"],
    "mesonic": ["mesic"],
    "mesophyte": ["mesophytic plant", "tracheophyte", "vascular plant"],
    "mesophytic": [],
    "mesopotamia": [],
    "mesosphere": ["layer"],
    "mesothelioma": ["carcinoma"],
    "mesothelium": ["epithelial tissue", "epithelium"],
    "mesozoic": ["age of reptiles", "mesozoic era"],
    "mespilus": ["genus mespilus", "rosid dicot genus"],
    "mesquite": ["algarroba", "bush", "honey mesquite", "mesquit", "prosopis glandulosa", "prosopis juliflora", "prosopis juliiflora", "prosopis pubescens", "screw bean", "screwbean", "screwbean mesquite", "shrub", "tornillo", "western honey mesquite"],
    "mesquite gum": ["gum"],
    "mess": ["eat"],
    "mess jacket": ["jacket", "monkey jacket", "shell jacket"],
    "mess kit": ["kit", "outfit"],
    "mess of pottage": ["economic value", "value"],
    "message": ["communicate", "pass", "pass along", "pass on", "put across"],
    "message pad": ["pad", "pad of paper", "tablet", "writing pad"],
    "messaging": ["electronic communication", "electronic messaging"],
    "messenger": ["bearer", "conveyer", "conveyor", "courier", "dispatch rider", "errand boy", "herald", "messenger boy", "process-server", "runner", "traveler", "traveller", "trumpeter"],
    "messenger boy": ["courier", "errand boy", "messenger", "page", "pageboy"],
    "messenger rna": ["informational rna", "mrna", "ribonucleic acid", "rna", "template rna"],
    "messiah": ["christ", "deliverer", "rescuer", "savior", "saviour"],
    "messiahship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "messianic": [],
    "messidor": ["revolutionary calendar month"],
    "messily": ["untidily"],
    "messina": [],
    "messmate": ["acquaintance", "friend"],
    "messuage": ["abode", "domicile", "dwelling", "dwelling house", "habitation", "home"],
    "messy": ["mussy"],
    "mestiza": ["adult female", "woman"],
    "mestizo": ["individual", "ladino", "mortal", "person", "somebody", "someone", "soul"],
    "mestranol": ["estrogen", "oestrogen"],
    "mesua": ["dilleniid dicot genus", "genus mesua"],
    "metabolic": [],
    "metabolic acidosis": ["acidosis"],
    "metabolic alkalosis": ["alkalosis"],
    "metabolic disorder": ["alcaptonuria", "alkaptonuria", "disorder", "hyperlipoproteinemia", "hypolipoproteinemia", "inborn error of metabolism", "lipidosis", "lysine intolerance", "upset"],
    "metabolic rate": ["basal metabolic rate", "bmr", "rate"],
    "metabolically": [],
    "metabolism": ["basal metabolism", "biological process", "cellular respiration", "fat metabolism", "glycolysis", "internal respiration", "metabolic process", "organic process", "respiration"],
    "metabolite": ["substance"],
    "metabolize": ["metabolise"],
    "metacarpal": ["bone", "metacarpal bone", "os"],
    "metacarpal artery": ["arteria", "arteria metacarpea", "arterial blood vessel", "artery"],
    "metacarpal vein": ["vein", "vena", "vena metacarpus", "venous blood vessel"],
    "metacarpus": ["skeletal structure"],
    "metacenter": ["intersection", "intersection point", "metacentre", "point of intersection"],
    "metacentric": [],
    "metacentric chromosome": ["chromosome"],
    "metadata": ["data", "information"],
    "metagenesis": ["alternation of generations", "digenesis", "heterogenesis", "xenogenesis"],
    "metagrobolized": ["metagrabolised", "metagrabolized", "metagrobolised", "mystified"],
    "metaknowledge": ["cognitive content", "content", "mental object"],
    "metal": ["coat", "surface"],
    "metal detector": ["detector", "sensing element", "sensor"],
    "metal filing": ["filing", "iron filing"],
    "metal screw": ["screw"],
    "metal wood": ["wood"],
    "metal-colored": ["metal-coloured", "metallic-colored", "metallic-coloured"],
    "metal-cutting": [],
    "metalanguage": ["language", "linguistic communication", "syntax language"],
    "metalepsis": ["metonymy"],
    "metalhead": ["buff", "devotee", "fan", "lover"],
    "metalize": ["coat", "metallize", "surface"],
    "metallic": ["cloth", "fabric", "material", "textile"],
    "metallic bond": ["bond", "chemical bond"],
    "metallic element": ["al", "alkali metal", "alkaline earth", "alkaline metal", "alkaline-earth metal", "aluminium", "aluminum", "am", "americium", "antimony", "atomic number 100", "atomic number 11", "atomic number 12", "atomic number 13", "atomic number 19", "atomic number 20", "atomic number 21", "atomic number 22", "atomic number 23", "atomic number 24", "atomic number 25", "atomic number 26", "atomic number 27", "atomic number 28", "atomic number 29", "atomic number 3", "atomic number 30", "atomic number 31", "atomic number 37", "atomic number 38", "atomic number 39", "atomic number 4", "atomic number 40", "atomic number 41", "atomic number 42", "atomic number 43", "atomic number 44", "atomic number 45", "atomic number 46", "atomic number 48", "atomic number 49", "atomic number 50", "atomic number 51", "atomic number 55", "atomic number 56", "atomic number 57", "atomic number 58", "atomic number 59", "atomic number 60", "atomic number 61", "atomic number 62", "atomic number 63", "atomic number 64", "atomic number 65", "atomic number 66", "atomic number 67", "atomic number 68", "atomic number 69", "atomic number 70", "atomic number 71", "atomic number 72", "atomic number 73", "atomic number 74", "atomic number 75", "atomic number 76", "atomic number 77", "atomic number 80", "atomic number 81", "atomic number 82", "atomic number 83", "atomic number 84", "atomic number 87", "atomic number 88", "atomic number 90", "atomic number 91", "atomic number 92", "atomic number 93", "atomic number 95", "atomic number 96", "atomic number 97", "atomic number 98", "atomic number 99", "ba", "barium", "base metal", "be", "berkelium", "beryllium", "bi", "bismuth", "bk", "ca", "cadmium", "caesium", "calcium", "californium", "cd", "ce", "cerium", "cesium", "cf", "chemical element", "chromium", "cm", "co", "cobalt", "copper", "cr", "cs", "cu", "curium", "dy", "dysprosium", "e", "einsteinium", "element", "er", "erbium", "es", "eu", "europium", "fe", "fermium", "fm", "fr", "francium", "ga", "gadolinium", "gallium", "gd", "glucinium", "hafnium", "heavy metal", "hf", "hg", "ho", "holmium", "hydrargyrum", "in", "indium", "ir", "iridium", "iron", "k", "la", "lanthanum", "lead", "li", "lithium", "lu", "lutecium", "lutetium", "magnesium", "manganese", "mercury", "metal", "mg", "mn", "mo", "molybdenum", "na", "nb", "nd", "neodymium", "neptunium", "ni", "nickel", "niobium", "noble metal", "np", "os", "osmium", "pa", "palladium", "pb", "pd", "pm", "po", "polonium", "potassium", "pr", "praseodymium", "promethium", "protactinium", "protoactinium", "quicksilver", "ra", "radium", "rb", "re", "rh", "rhenium", "rhodium", "ru", "rubidium", "ruthenium", "samarium", "sb", "sc", "scandium", "sm", "sn", "sodium", "sr", "strontium", "ta", "tantalum", "tb", "tc", "technetium", "terbium", "th", "thallium", "thorium", "thulium", "ti", "tin", "titanium", "tl", "tm", "tungsten", "u", "uranium", "v", "vanadium", "w", "wolfram", "y", "yb", "ytterbium", "yttrium", "zinc", "zirconium", "zn", "zr"],
    "metallike": ["metal-looking", "metallic-looking"],
    "metallized dye": ["acid dye"],
    "metalloid": [],
    "metallurgical": ["metallurgic"],
    "metallurgist": ["applied scientist", "engineer", "metallurgical engineer", "technologist"],
    "metallurgy": ["powder metallurgy", "science", "scientific discipline"],
    "metalware": ["tole", "ware"],
    "metalwork": ["piece of work", "work"],
    "metalworking": ["formation", "metalwork", "shaping"],
    "metamathematics": ["pure mathematics"],
    "metamere": ["segment", "somite"],
    "metameric": ["segmental", "segmented"],
    "metamorphic": ["metamorphous"],
    "metamorphic rock": ["amphibolite", "gneiss", "hornfels", "hornstone", "marlite", "marlstone", "rock", "schist", "stone"],
    "metamorphism": ["anamorphism", "epigenesis", "geologic process", "geological process", "katamorphism"],
    "metamorphopsia": ["vision defect", "visual defect", "visual disorder", "visual impairment"],
    "metamorphose": ["change by reversal", "reverse", "transfigure", "transmogrify", "turn"],
    "metamorphosis": ["biological process", "hemimetabolism", "hemimetaboly", "hemimetamorphosis", "heterometabolism", "heterometaboly", "holometabolism", "holometaboly", "metabolism", "organic process"],
    "metamorphous": [],
    "metaphase": ["phase of cell division"],
    "metaphor": ["dead metaphor", "figure", "figure of speech", "frozen metaphor", "image", "mixed metaphor", "synesthetic metaphor", "trope"],
    "metaphorical": ["metaphoric"],
    "metaphorically": [],
    "metaphosphoric acid": ["polyphosphoric acid"],
    "metaphysical": [],
    "metaphysically": [],
    "metaphysics": ["cosmology", "ontology", "philosophy"],
    "metaphysis": ["appendage", "outgrowth", "process"],
    "metaplastic anemia": ["malignant anaemia", "malignant anemia", "metaplastic anaemia", "pernicious anaemia", "pernicious anemia"],
    "metaproterenol": ["alupent", "bronchodilator"],
    "metarule": ["formula", "rule"],
    "metasequoia": ["conifer", "coniferous tree", "dawn redwood", "metasequoia glyptostrodoides"],
    "metastability": ["constancy", "stability"],
    "metastable": [],
    "metastasis": ["pathologic process", "pathological process"],
    "metastasize": ["distribute", "metastasise", "spread"],
    "metastatic": [],
    "metatarsal": ["bone", "os"],
    "metatarsal arch": ["arch"],
    "metatarsal artery": ["arteria", "arteria metatarsea", "arterial blood vessel", "artery"],
    "metatarsal vein": ["vein", "vena", "vena metatarsus", "venous blood vessel"],
    "metatarsus": ["skeletal structure"],
    "metatheria": ["class", "subclass metatheria"],
    "metatherian": ["mammal", "mammalian", "marsupial", "pouched mammal"],
    "metathesis": ["linguistic process"],
    "metaurus river": [],
    "metazoa": ["subkingdom", "subkingdom metazoa"],
    "metazoan": ["animal", "animate being", "beast", "brute", "creature", "fauna"],
    "metchnikoff": ["elie metchnikoff", "elie metchnikov", "ilya ilich metchnikov", "metchnikov"],
    "metempsychosis": ["phenomenon", "rebirth"],
    "metencephalon": ["hindbrain", "rhombencephalon"],
    "meteor": ["bolide", "fireball", "light", "shooting star", "visible light", "visible radiation"],
    "meteor shower": ["atmospheric phenomenon", "meteor stream"],
    "meteor swarm": ["meteor", "meteoroid"],
    "meteoric": [],
    "meteorite": ["aerolite", "meteor", "meteoroid", "micrometeor", "micrometeorite", "micrometeoroid", "pallasite", "siderite"],
    "meteoritic": ["meteoritical"],
    "meteoroid": ["estraterrestrial body", "extraterrestrial object", "meteor", "meteor swarm", "meteorite"],
    "meteorologic": ["meteoric", "meteorological"],
    "meteorological balloon": ["balloon", "pilot balloon"],
    "meteorological conditions": ["environmental condition"],
    "meteorological observation post": ["lookout", "observation post", "weather station"],
    "meteorologically": [],
    "meteorologist": ["specialiser", "specialist", "specializer", "weather forecaster", "weatherman"],
    "meteorology": ["forecasting", "foretelling", "prediction", "prognostication", "weather forecasting"],
    "meteortropism": ["tropism"],
    "meter": ["stamp"],
    "meter maid": ["police matron", "policewoman"],
    "meterstick": ["metrestick", "rule", "ruler"],
    "metformin": ["antidiabetic", "antidiabetic drug", "glucophage"],
    "methacholine": ["mecholyl", "medicament", "medication", "medicinal drug", "medicine"],
    "methacrylic acid": ["2-methylpropenoic acid", "acid"],
    "methadone": ["dolophine hydrochloride", "fixer", "methadon", "methadone hydrochloride", "narcotic", "synthetic heroin"],
    "methamphetamine": ["amphetamine", "chalk", "chicken feed", "controlled substance", "crank", "deoxyephedrine", "glass", "ice", "meth", "methamphetamine hydrochloride", "methedrine", "pep pill", "shabu", "speed", "trash", "upper"],
    "methane": ["alkane", "alkane series", "gas", "marsh gas", "methane series", "paraffin", "paraffin series"],
    "methane series": ["aliphatic compound", "alkane", "alkane series", "amine", "aminoalkane", "butane", "c2h6", "ethane", "heptane", "hexane", "methane", "paraffin", "paraffin series"],
    "methanogen": ["archaebacteria", "archaebacterium", "archaeobacteria", "archeobacteria"],
    "methanol": ["alcohol", "fuel", "methyl alcohol", "wood alcohol", "wood spirit"],
    "methapyrilene": ["antihistamine"],
    "methaqualone": ["quaalude", "sedative-hypnotic", "sedative-hypnotic drug"],
    "metharbital": ["anticonvulsant", "anticonvulsant drug", "antiepileptic", "antiepileptic drug", "gemonil"],
    "metheglin": ["mead"],
    "methenamine": ["antibacterial", "antibacterial drug", "bactericide", "mandelamine", "urex"],
    "methicillin": ["penicillin"],
    "methionine": ["essential amino acid"],
    "methocarbamol": ["muscle relaxant", "robaxin"],
    "method": ["know-how", "method of choice", "methodology", "mnemonics", "pedagogics", "pedagogy", "solution", "statistical method", "statistical procedure", "system", "system of rules", "teaching method", "technicolor", "technique", "wrinkle"],
    "method acting": ["acting", "method", "performing", "playacting", "playing"],
    "method of choice": ["method"],
    "methodical": [],
    "methodically": [],
    "methodism": ["protestantism"],
    "methodist": ["protestant", "wesleyan"],
    "methodist church": ["methodists", "protestant denomination"],
    "methodist denomination": ["evangelical united brethren church", "protestant denomination", "united methodist church", "wesleyan methodist church", "wesleyan methodists"],
    "methodological": [],
    "methodologically": [],
    "methodology": ["epistemology", "methodological analysis"],
    "methotrexate": ["amethopterin", "antimetabolite", "immune suppressant drug", "immunosuppressant", "immunosuppressive", "immunosuppressive drug", "immunosuppressor", "methotrexate sodium"],
    "methuselah": [],
    "methyl": ["alkyl", "alkyl group", "alkyl radical", "aminomethane", "hydroxymethyl", "methyl group", "methyl radical"],
    "methyl bromide": ["bromide"],
    "methyl orange": ["acid-base indicator", "azo dye"],
    "methyl salicylate": ["birch oil", "salicylate", "sweet-birch oil"],
    "methylated": [],
    "methylated spirit": ["denatured alcohol", "surgical spirit"],
    "methyldopa": ["aldomet", "alpha methyl dopa", "antihypertensive", "antihypertensive drug"],
    "methylene blue": ["methylthionine chloride", "stain", "thiazine"],
    "methylene chloride": ["chloride", "dichloromethane"],
    "methylene group": ["chemical group", "group", "methylene", "methylene radical", "radical"],
    "methylenedioxymethamphetamine": ["adam", "club drug", "cristal", "disco biscuit", "ecstasy", "go", "hug drug", "mdma", "x", "xtc"],
    "methylphenidate": ["excitant", "ritalin", "stimulant", "stimulant drug"],
    "methyltestosterone": ["androgen", "androgenic hormone"],
    "metic": ["alien", "foreigner", "noncitizen", "outlander"],
    "metical": ["mozambique monetary unit"],
    "meticulous": ["punctilious"],
    "meticulously": [],
    "meticulousness": ["conscientiousness", "meticulosity", "painstakingness", "punctiliousness", "scrupulousness"],
    "metier": ["business", "job", "line", "line of work", "medium", "occupation"],
    "metis": ["mixed-blood"],
    "metonym": ["word"],
    "metonymic": ["metonymical"],
    "metonymically": [],
    "metonymy": ["figure", "figure of speech", "image", "metalepsis", "trope"],
    "metopion": ["craniometric point"],
    "metoprolol": ["beta blocker", "beta-adrenergic blocker", "beta-adrenergic blocking agent", "beta-blocking agent", "lopressor"],
    "metralgia": ["hurting", "pain"],
    "metrazol shock": ["metrazol shock therapy", "metrazol shock treatment", "shock therapy", "shock treatment"],
    "metric": ["metrical"],
    "metric capacity unit": ["capacity measure", "capacity unit", "cc", "centiliter", "centilitre", "cl", "cubage unit", "cubature unit", "cubic centimeter", "cubic centimetre", "cubic content unit", "cubic decimeter", "cubic decimetre", "cubic kilometer", "cubic kilometre", "cubic measure", "cubic meter", "cubic metre", "cubic millimeter", "cubic millimetre", "dal", "decaliter", "decalitre", "deciliter", "decilitre", "dekaliter", "dekalitre", "displacement unit", "dkl", "dl", "hectoliter", "hectolitre", "hl", "kiloliter", "kilolitre", "l", "liter", "litre", "metric", "metric unit", "mil", "milliliter", "millilitre", "ml", "volume unit"],
    "metric function": ["function", "map", "mapping", "mathematical function", "metric", "single-valued function"],
    "metric linear unit": ["a", "angstrom", "angstrom unit", "centimeter", "centimetre", "cm", "dam", "decameter", "decametre", "decimeter", "decimetre", "dekameter", "dekametre", "dkm", "dm", "femtometer", "femtometre", "fermi", "hectometer", "hectometre", "hm", "kilometer", "kilometre", "klick", "km", "linear measure", "linear unit", "m", "meter", "metre", "metric", "metric unit", "micrometer", "micromicron", "micromillimeter", "micromillimetre", "micron", "millimeter", "millimetre", "millimicron", "mm", "mym", "myriameter", "myriametre", "nanometer", "nanometre", "nm", "picometer", "picometre"],
    "metric space": ["euclidean space", "hilbert space", "mathematical space", "topological space"],
    "metric system": ["cgs", "cgs system", "international system", "international system of units", "si", "si system", "si unit", "system of weights and measures", "systeme international", "systeme international d'unites"],
    "metric ton": ["metric weight unit", "mt", "t", "tonne", "weight unit"],
    "metric unit": ["metric", "metric capacity unit", "metric linear unit", "metric weight unit", "unit", "unit of measurement", "weight unit"],
    "metric weight unit": ["carat", "centner", "dag", "decagram", "decigram", "dekagram", "dg", "dkg", "doppelzentner", "g", "gm", "grain", "gram", "gram atom", "gram molecule", "gram-atomic weight", "gramme", "hectogram", "hg", "hundredweight", "kg", "kilo", "kilogram", "mass unit", "mcg", "metric", "metric grain", "metric hundredweight", "metric ton", "metric unit", "mg", "microgram", "milligram", "mol", "mole", "mt", "myg", "myriagram", "nanogram", "ng", "quintal", "t", "tonne", "weight unit"],
    "metrical foot": ["amphibrach", "anapaest", "anapest", "beat", "cadence", "dactyl", "dibrach", "foot", "iamb", "iambus", "measure", "meter", "metre", "metrical unit", "pyrrhic", "spondee", "trochee"],
    "metrically": [],
    "metricize": ["metricise", "transform", "translate"],
    "metrification": ["authorship", "composition", "penning", "writing"],
    "metrify": ["poetise", "poetize", "verse", "versify"],
    "metritis": ["endometritis", "inflammation", "redness", "rubor"],
    "metro": ["railroad", "railroad line", "railway", "railway line", "railway system", "subway", "subway system", "tube", "underground"],
    "metrological": [],
    "metrology": ["science", "scientific discipline"],
    "metronidazole": ["antiprotozoal", "antiprotozoal drug", "flagyl"],
    "metronome": ["pendulum"],
    "metropolitan": ["archbishop"],
    "metroptosis": ["descensus", "descensus uteri", "prolapse", "prolapsus"],
    "metrorrhagia": ["bleeding", "haemorrhage", "hemorrhage"],
    "metroxylon": ["genus metroxylon", "liliopsid genus", "monocot genus"],
    "metternich": ["klemens metternich", "prince klemens wenzel nepomuk lothar von metternich"],
    "mettlesome": [],
    "mettlesomeness": ["high-spiritedness"],
    "meuniere butter": ["butter", "lemon butter"],
    "meuse": ["meuse river"],
    "mew": ["emit", "let loose", "let out", "utter"],
    "mews": ["street"],
    "mexicali": [],
    "mexican": ["central american", "chicano", "greaser", "mexican-american", "mexicano", "taco", "wetback"],
    "mexican bean beetle": ["bean beetle", "epilachna varivestis", "lady beetle", "ladybeetle", "ladybird", "ladybird beetle", "ladybug"],
    "mexican cypress": ["cedar of goa", "cupressus lusitanica", "cypress", "cypress tree", "portuguese cypress"],
    "mexican hairless": ["canis familiaris", "dog", "domestic dog"],
    "mexican hat": ["coneflower", "ratibida columnaris"],
    "mexican hyssop": ["agastache mexicana", "giant hyssop"],
    "mexican juniper": ["drooping juniper", "juniper", "juniperus flaccida"],
    "mexican mint": ["sage", "salvia", "salvia divinorum"],
    "mexican monetary unit": ["mexican peso", "monetary unit", "peso"],
    "mexican peso": ["mexican monetary unit", "peso"],
    "mexican pocket mouse": ["liomys irroratus", "pocket mouse"],
    "mexican poppy": ["argemone", "argemone mexicana", "devil's fig", "prickly poppy", "white thistle"],
    "mexican revolution": [],
    "mexican spanish": ["spanish"],
    "mexican standoff": ["situation"],
    "mexican sunflower": ["flower", "tithonia"],
    "mexican war": [],
    "mexican-american": ["mexican", "mexicano"],
    "mexico": ["united mexican states"],
    "mexico city": ["capital of mexico", "ciudad de mexico", "mexican capital"],
    "mexiletine": ["antiarrhythmic", "antiarrhythmic drug", "antiarrhythmic medication", "mexitil"],
    "meyerbeer": ["giacomo meyerbeer", "jakob liebmann beer"],
    "meyerhof": ["otto fritz meyerhof", "otto meyerhof"],
    "mezereon": ["daphne", "daphne mezereum", "february daphne"],
    "mezereum": ["bark"],
    "mezuzah": ["mezuza", "section", "subdivision"],
    "mezzanine": ["balcony", "first balcony"],
    "mezzo-relievo": ["embossment", "half-relief", "mezzo-rilievo", "relief", "relievo", "rilievo", "sculptural relief"],
    "mezzo-soprano": ["mezzo", "soprano"],
    "mezzotint": ["print"],
    "mho": ["conductance unit", "reciprocal ohm", "s", "siemens"],
    "mi": ["solfa syllable"],
    "miami": ["algonquian", "algonquin"],
    "miami beach": [],
    "miaou": ["emit", "let loose", "let out", "miaow", "utter"],
    "miasma": ["ambiance", "ambience", "atmosphere", "miasm"],
    "miasmal": ["miasmic", "vaporous", "vapourous"],
    "miasmic": ["mephitic"],
    "mica": ["biotite", "isinglass", "lepidolite", "mineral", "muscovite", "paragonite", "phlogopite", "translucent substance", "transparent substance", "zinnwaldite"],
    "micaceous": [],
    "micah": ["micheas"],
    "micawber": ["wilkins micawber"],
    "micelle": ["particle", "subatomic particle"],
    "michael": ["archangel"],
    "michaelmas": ["michaelmas day", "quarter day", "september 29"],
    "michaelmas daisy": ["aster", "aster novi-belgii", "new york aster"],
    "michaelmastide": ["season"],
    "michelangelesque": [],
    "michelangelo": ["michelangelo buonarroti"],
    "michelson": ["a. a. michelson", "albert abraham michelson", "albert michelson"],
    "michelson-morley experiment": ["experiment", "experimentation"],
    "michener": ["james albert michener", "james michener"],
    "michigan": ["great lakes state", "mi", "wolverine state"],
    "michigan lily": ["lilium michiganense", "lily"],
    "michigander": ["american", "wolverine"],
    "mickey finn": ["knockout drops"],
    "mickey mouse": [],
    "micmac": ["algonquian", "algonquin", "mikmaq"],
    "miconazole": ["antifungal", "antifungal agent", "antimycotic", "antimycotic agent", "fungicide", "monistat"],
    "micro": [],
    "microbalance": ["balance"],
    "microbe": ["bug", "germ", "micro-organism", "microorganism"],
    "microbial": ["microbic"],
    "microbiologist": ["biologist", "life scientist", "virologist"],
    "microbiology": ["biological science", "biology"],
    "microbrachia": ["abnormalcy", "abnormality"],
    "microbrewery": ["brewery"],
    "microcentrum": ["arthropod genus", "genus microcentrum"],
    "microcephalic": ["microcephalous", "nanocephalic"],
    "microcephaly": ["abnormalcy", "abnormality", "microcephalus", "nanocephaly"],
    "microchiroptera": ["animal order", "suborder microchiroptera"],
    "micrococcaceae": ["bacteria family", "family micrococcaceae"],
    "micrococcus": ["bacteria genus", "genus micrococcus"],
    "microcopy": ["photocopy", "run off", "xerox"],
    "microcosm": ["example", "model"],
    "microcosmic": [],
    "microcosmic salt": ["salt"],
    "microcrystalline": [],
    "microcyte": ["erythrocyte", "rbc", "red blood cell"],
    "microcytic anemia": ["anaemia", "anemia", "microcytic anaemia"],
    "microcytosis": ["blood disease", "blood disorder"],
    "microdesmidae": ["family microdesmidae", "fish family"],
    "microdipodops": ["genus microdipodops", "mammal genus"],
    "microdot": ["exposure", "photo", "photograph", "pic", "picture"],
    "microeconomic": [],
    "microeconomics": ["economic science", "economics", "political economy"],
    "microeconomist": ["economic expert", "economist", "microeconomic expert"],
    "microelectronic": [],
    "microelectronics": ["electronics"],
    "microevolution": ["evolution", "organic evolution", "phylogenesis", "phylogeny"],
    "microfarad": ["capacitance unit"],
    "microfiche": ["microfilm"],
    "microfilm": ["film"],
    "microflora": ["flora", "micro-organism", "microorganism", "plant", "plant life"],
    "microfossil": ["fossil"],
    "microgametophyte": ["gametophyte"],
    "microgauss": ["flux density unit"],
    "microglia": ["glia", "neuroglia"],
    "microgliacyte": ["glial cell", "neurogliacyte", "neuroglial cell"],
    "microgram": ["mcg", "metric weight unit", "weight unit"],
    "microgramma": ["fern genus", "genus microgramma"],
    "microhylidae": ["amphibian family", "brevicipitidae", "family brevicipitidae", "family microhylidae"],
    "micromeria": ["asterid dicot genus", "genus micromeria"],
    "micrometeoric": [],
    "micrometeorite": ["meteorite", "micrometeor", "micrometeoroid"],
    "micrometeoritic": [],
    "micrometer": ["caliper", "calliper", "micrometer caliper", "micrometer gauge"],
    "micrometry": ["measure", "measurement", "measuring", "mensuration"],
    "micromyx": ["genus micromyx", "mammal genus"],
    "micron": ["metric linear unit", "micrometer"],
    "micronesia": ["federated states of micronesia", "tt"],
    "micronor": ["anovulant", "anovulatory drug", "birth control pill", "contraceptive pill", "oral contraceptive", "oral contraceptive pill", "pill"],
    "micronutrient": ["food", "nutrient"],
    "microorganism": ["bacteria", "bacterium", "being", "bug", "germ", "intestinal flora", "micro-organism", "microbe", "microflora", "monad", "moneran", "moneron", "organism", "pathogen", "protist", "protistan", "protoctist", "virus"],
    "micropaleontology": ["fossilology", "palaeontology", "paleontology"],
    "micropenis": ["member", "microphallus", "penis", "phallus"],
    "microphage": ["neutrophil", "neutrophile"],
    "microphone": ["bug", "capacitor microphone", "condenser microphone", "crystal microphone", "directional microphone", "electro-acoustic transducer", "mike", "spike mike"],
    "microphoning": ["transduction"],
    "microphotometer": ["densitometer"],
    "micropogonias": ["fish genus", "genus micropogonias"],
    "microprocessor": ["chip", "micro chip", "microchip", "microprocessor chip", "silicon chip"],
    "micropterus": ["fish genus", "genus micropterus"],
    "micropylar": [],
    "micropyle": ["aperture"],
    "microradian": ["angular unit"],
    "microscope": ["angioscope", "electron microscope", "light microscope", "magnifier"],
    "microscopic": ["microscopical"],
    "microscopic anatomy": ["anatomy", "cytology", "general anatomy", "histology"],
    "microscopic field": ["field", "field of view"],
    "microscopically": [],
    "microscopist": ["scientist"],
    "microscopium": [],
    "microscopy": ["dark field illumination", "dark ground illumination", "electron microscopy", "fluorescence microscopy", "research"],
    "microsecond": ["time unit", "unit of time"],
    "microsomal": [],
    "microsome": ["granule"],
    "microsorium": ["fern genus", "genus microsorium"],
    "microsporangium": ["sporangium", "spore case", "spore sac"],
    "microspore": ["spore"],
    "microsporidian": ["sporozoan"],
    "microsporophyll": ["sporophyl", "sporophyll"],
    "microsporum": ["fungus genus", "genus microsporum"],
    "microstomus": ["fish genus", "genus microstomus"],
    "microstrobos": ["genus microstrobos", "gymnosperm genus"],
    "microsurgery": ["operation", "robotic telesurgery", "surgery", "surgical operation", "surgical procedure", "surgical process"],
    "microtaggant": ["identification particle"],
    "microtome": ["scientific instrument"],
    "microtubule": ["tubule"],
    "microtus": ["genus microtus", "mammal genus"],
    "microvolt": ["potential unit"],
    "microwave": ["cook", "micro-cook", "nuke", "zap"],
    "microwave bomb": ["bomb", "e-bomb"],
    "microwave diathermy machine": ["diathermy machine"],
    "microwave linear accelerator": ["linac", "linear accelerator"],
    "microwave spectroscopy": ["electron paramagnetic resonance", "electron spin resonance", "esr", "spectrographic analysis", "spectrometry", "spectroscopic analysis", "spectroscopy", "spectrum analysis"],
    "microwave spectrum": ["spectrum"],
    "micruroides": ["genus micruroides", "reptile genus"],
    "micrurus": ["genus micrurus", "reptile genus"],
    "micturition": ["elimination", "evacuation", "excreting", "excretion", "leak", "lithuresis", "making water", "nocturia", "nycturia", "oliguria", "passing water", "pee", "peeing", "piss", "pissing", "urination", "voiding", "wetting"],
    "micturition reflex": ["inborn reflex", "innate reflex", "instinctive reflex", "physiological reaction", "reflex", "reflex action", "reflex response", "unconditioned reflex"],
    "mid": [],
    "mid-april": ["period", "period of time", "time period"],
    "mid-atlantic ridge": [],
    "mid-atlantic states": [],
    "mid-august": ["period", "period of time", "time period"],
    "mid-calf": ["calf", "sura"],
    "mid-december": ["period", "period of time", "time period"],
    "mid-february": ["period", "period of time", "time period"],
    "mid-january": ["period", "period of time", "time period"],
    "mid-july": ["period", "period of time", "time period"],
    "mid-june": ["period", "period of time", "time period"],
    "mid-march": ["period", "period of time", "time period"],
    "mid-may": ["period", "period of time", "time period"],
    "mid-november": ["period", "period of time", "time period"],
    "mid-october": ["period", "period of time", "time period"],
    "mid-off": ["position"],
    "mid-on": ["position"],
    "mid-september": ["period", "period of time", "time period"],
    "mid-water": ["body of water", "water"],
    "midafternoon": ["day", "daylight", "daytime"],
    "midair": ["point"],
    "midas": [],
    "midas touch": ["ability"],
    "midazolam": ["benzodiazepine", "versed"],
    "midbrain": ["mesencephalon", "neural structure"],
    "middle": ["lay", "place", "pose", "position", "put", "set"],
    "middle age": ["time of life"],
    "middle ages": ["dark ages"],
    "middle atlantic": ["mid-atlantic"],
    "middle c": ["musical note", "note", "tone"],
    "middle cerebral artery": ["arteria cerebri", "cerebral artery"],
    "middle cerebral vein": ["cerebral vein", "deep middle cerebral vein", "superficial middle cerebral vein", "vena cerebri", "vena cerebri media"],
    "middle class": ["bourgeoisie", "class", "petit bourgeois", "petite bourgeoisie", "petty bourgeoisie", "social class", "socio-economic class", "stratum"],
    "middle distance": ["aspect", "panorama", "prospect", "scene", "view", "vista"],
    "middle ear": ["bodily cavity", "cavity", "cavum", "tympanic cavity", "tympanum"],
    "middle east": ["mideast", "near east"],
    "middle eastern": [],
    "middle english": ["east midland", "english", "english language", "kentish", "northern", "southwestern", "west midland", "west saxon"],
    "middle finger": ["finger"],
    "middle high german": ["german", "german language", "high german"],
    "middle irish": ["irish", "irish gaelic"],
    "middle low german": ["low german", "plattdeutsch"],
    "middle meningeal artery": ["arteria meningea", "meningeal artery"],
    "middle name": ["name"],
    "middle paleolithic": [],
    "middle temporal vein": ["temporal vein", "vena temporalis"],
    "middle term": ["term"],
    "middle thyroid vein": ["thyroid vein", "vena thyroidea"],
    "middle-aged": [],
    "middle-aged man": ["adult male", "dirty old man", "man"],
    "middle-class": [],
    "middle-level": [],
    "middle-of-the-road": [],
    "middlebrow": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "middlemost": ["midmost"],
    "middleton": ["thomas middleton"],
    "middleweight": ["boxer", "pugilist"],
    "middling": ["commodity", "good", "trade good"],
    "middy": ["blouse", "middy blouse"],
    "midfield": ["center", "centre", "eye", "heart", "middle"],
    "midgard": ["fictitious place", "imaginary place", "mythical place"],
    "midge": ["gnat"],
    "midgrass": ["grass"],
    "midi": [],
    "midi-pyrenees": [],
    "midinette": ["salesgirl", "saleslady", "saleswoman"],
    "midiron": ["iron", "two iron"],
    "midland": [],
    "midmost": ["in the midst"],
    "midnight": ["hour", "time of day"],
    "midnight sun": ["atmospheric phenomenon"],
    "midplane": ["midline", "plane", "sheet"],
    "midrash": ["comment", "commentary"],
    "midrib": ["midvein", "nervure", "vein"],
    "midshipman": ["cadet", "plebe"],
    "midst": ["inside", "interior", "thick"],
    "midstream": ["center", "centre", "eye", "heart", "middle"],
    "midsummer day": ["june 24", "midsummer's day", "quarter day", "st john's day"],
    "midsummer eve": ["day", "june 23", "midsummer night", "st john's eve", "st john's night"],
    "midterm": ["point", "point in time"],
    "midterm examination": ["exam", "examination", "midterm", "midterm exam", "test"],
    "midway": ["parcel", "parcel of land", "piece of ground", "piece of land", "tract"],
    "midway islands": [],
    "midweek": ["period", "period of time", "time period"],
    "midweekly": [],
    "midwest": ["middle west", "midwestern united states"],
    "midwestern": [],
    "midwife": ["accoucheuse", "nurse"],
    "midwife toad": ["alytes cisternasi", "anuran", "batrachian", "frog", "salientian", "toad", "toad frog"],
    "midwifery": ["delivery", "obstetrical delivery"],
    "midwinter": ["period", "period of time", "time period"]
}
