synonyms = {
    "courtly love": ["code of behavior", "code of conduct"],
    "courtship": ["appeal", "bundling", "courting", "entreaty", "prayer", "suit", "wooing"],
    "couscous": ["dish"],
    "cousin": ["cousin-german", "first cousin", "full cousin", "relation", "relative"],
    "cousinly": [],
    "cousteau": ["jacques costeau", "jacques yves costeau"],
    "couth": [],
    "couthie": ["couthy"],
    "couture": ["dressmaking"],
    "couturier": ["clothes designer", "costume designer", "costumer", "costumier", "creator", "designer", "fashion designer"],
    "couvade": ["custom", "usage", "usance"],
    "couverture": ["chocolate"],
    "covalence": ["covalency", "valence", "valency"],
    "covalent": [],
    "covalent bond": ["bond", "chemical bond", "coordinate bond", "dative bond", "double bond"],
    "covariance": ["variance"],
    "covariant": [],
    "covariation": ["variation"],
    "cove": ["cave"],
    "coven": ["assembly"],
    "covenant": ["bar mitzvah", "bat mitzvah", "confirm", "pledge", "plight"],
    "coventry": [],
    "cover": ["be", "constellate", "continue", "cross", "dot", "extend", "overlap", "overspread", "ridge", "span", "spread", "stud", "sweep", "traverse"],
    "cover charge": ["cover", "fixed charge", "fixed cost", "fixed costs"],
    "cover crop": ["crop"],
    "cover for": ["protect"],
    "cover girl": ["lovely", "photographer's model", "pin-up"],
    "cover glass": ["cover slip", "plate glass", "sheet glass"],
    "cover plate": ["covering"],
    "cover-up": ["blue wall", "blue wall of silence", "concealing", "concealment", "hiding", "wall of silence"],
    "coverage": ["amount", "amount of money", "insurance coverage", "sum", "sum of money"],
    "coverall": ["boilers suit", "boilersuit", "dust coat", "duster", "gabardine", "gaberdine", "jumper", "overall", "protective garment", "smock"],
    "covered": [],
    "covered bridge": ["bridge", "span"],
    "covered couch": ["litter"],
    "covered option": ["option"],
    "covered smut": ["smut", "smut fungus"],
    "covered wagon": ["conestoga", "conestoga wagon", "prairie schooner", "prairie wagon", "waggon", "wagon"],
    "covering": ["bark", "blanket", "body covering", "cap", "case", "chlamys", "cover", "crust", "eggshell", "encrustation", "envelope", "floral envelope", "hood", "incrustation", "indument", "indumentum", "indusium", "integument", "mantle", "natural covering", "natural object", "perianth", "pericarp", "peridium", "perigone", "perigonium", "roof", "sac", "scale", "seed vessel", "sheath", "shell", "skim", "slough", "snowcap", "test", "theca", "vesture"],
    "covering letter": ["cover letter", "letter", "missive"],
    "covering material": ["building material", "fiberglass", "fibreglass", "lino", "linoleum", "plaster", "puddle"],
    "coverlet": ["bed cover", "bed covering", "bedcover", "bedspread", "counterpane", "spread"],
    "covert": ["flock"],
    "covert operation": ["black operation", "military operation", "operation"],
    "covertly": [],
    "covet": ["begrudge", "drool", "envy", "salivate"],
    "coveted": ["desired", "in demand", "sought after"],
    "covetous": ["envious", "jealous"],
    "covetousness": ["enviousness", "envy"],
    "covey": ["assemblage", "gathering"],
    "cow": ["disagreeable woman", "unpleasant woman"],
    "cow manure": ["manure"],
    "cow parsley": ["anthriscus sylvestris", "herb", "herbaceous plant", "wild chervil"],
    "cow parsnip": ["heracleum sphondylium", "herb", "herbaceous plant", "hogweed"],
    "cow pasture": ["grazing land", "lea", "ley", "pasture", "pastureland"],
    "cow pen": ["cattle pen", "corral", "pen"],
    "cow pie": ["cowpie", "droppings", "dung", "muck"],
    "cow pony": ["mount", "riding horse", "saddle horse"],
    "cow shark": ["hexanchus griseus", "shark", "six-gilled shark"],
    "cow town": ["cowtown", "town"],
    "cowage": ["pod", "seedpod"],
    "coward": ["noel coward", "sir noel pierce coward"],
    "cowardice": ["cowardliness", "cravenness", "dastardliness", "fearfulness", "spirit"],
    "cowardly": ["fearful"],
    "cowbarn": ["barn", "byre", "cow barn", "cowhouse", "cowshed"],
    "cowbell": ["bell"],
    "cowberry": ["cranberry", "foxberry", "lingberry", "lingenberry", "lingonberry", "mountain cranberry", "vaccinium vitis-idaea"],
    "cowbird": ["blackbird", "new world blackbird"],
    "cowboy": ["performer", "performing artist", "rodeo rider"],
    "cowboy boot": ["boot"],
    "cowboy hat": ["chapeau", "hat", "lid", "ten-gallon hat"],
    "cowfish": ["boxfish", "lactophrys quadricornis", "trunkfish"],
    "cowgirl": ["cattleman", "cowboy", "cowhand", "cowherd", "cowman", "cowpoke", "cowpuncher", "puncher"],
    "cowherb": ["cow cockle", "flower", "saponaria vaccaria", "vaccaria hispanica", "vaccaria pyramidata"],
    "cowhide": ["flog", "lash", "lather", "slash", "strap", "trounce", "welt", "whip"],
    "cowl": ["cover"],
    "cowl-shaped": [],
    "cowled": [],
    "cowlick": ["hair"],
    "cownose ray": ["cow-nosed ray", "eagle ray", "rhinoptera bonasus"],
    "cowpea": ["black-eyed pea", "legume"],
    "cowpen daisy": ["butter daisy", "crown beard", "crown-beard", "crownbeard", "golden crown beard", "golden crownbeard", "verbesina encelioides", "ximenesia encelioides"],
    "cowpens": ["battle of cowpens"],
    "cowper": ["william cowper"],
    "cowper's gland": ["bulbourethral gland", "duct gland", "exocrine", "exocrine gland"],
    "cowpox": ["animal disease", "pox", "vaccinia"],
    "cowrie": ["cowry", "cypraea moneta", "cypraea tigris", "gastropod", "money cowrie", "tiger cowrie", "univalve"],
    "cows' milk": ["milk"],
    "cowslip": ["paigle", "primrose", "primula", "primula veris"],
    "cox": ["be", "follow"],
    "cox's orange pippin": ["pippin"],
    "cox-2 inhibitor": ["anti-inflammatory", "anti-inflammatory drug", "bextra", "celebrex", "celecoxib", "rofecoxib", "valdecoxib", "vioxx"],
    "coxcomb": ["beau", "clotheshorse", "cockscomb", "dandy", "dude", "fashion plate", "fop", "gallant", "sheik", "swell"],
    "coxsackievirus": ["coxsackie virus", "enterovirus"],
    "coxswain": ["cox", "helmsman", "steerer", "steersman"],
    "coy": ["demure", "overmodest"],
    "coydog": ["brush wolf", "canis latrans", "coyote", "prairie wolf"],
    "coyly": [],
    "coyness": ["affectedness", "demureness"],
    "coyol": ["acrocomia vinifera", "coyol palm", "feather palm"],
    "coyote": ["contrabandist", "moon curser", "moon-curser", "runner", "smuggler"],
    "coyote brush": ["baccharis pilularis", "bush", "chaparral broom", "coyote bush", "kidney wort", "shrub"],
    "coypu": ["gnawer", "myocastor coypus", "nutria", "rodent"],
    "cozen": ["cheat", "chisel"],
    "cozily": ["cosily"],
    "coziness": ["comfort", "comfortableness", "cosiness", "snugness"],
    "cozy": ["informal", "intimate"],
    "cozy up": ["cotton up", "ingratiate", "play up", "shine up", "sidle up", "suck up"],
    "cpu board": ["add-in", "board", "card", "circuit board", "circuit card", "mother board", "plug-in"],
    "crab": ["channelise", "channelize", "direct", "guide", "head", "maneuver", "manoeuver", "manoeuvre", "point", "steer"],
    "crab apple": ["apple tree", "cherry apple", "cherry crab", "crabapple", "cultivated crab apple", "flowering crab", "malus angustifolia", "malus baccata", "siberian crab", "siberian crab apple", "southern crab apple"],
    "crab cactus": ["cactus", "schlumbergera truncatus", "thanksgiving cactus", "zygocactus truncatus"],
    "crab cocktail": ["cocktail"],
    "crab legs": ["crab", "crabmeat"],
    "crab louis": ["salad"],
    "crab louse": ["crab", "louse", "phthirius pubis", "pubic louse", "sucking louse"],
    "crab nebula": [],
    "crab-eating dog": ["crab-eating fox", "dusicyon cancrivorus", "wild dog"],
    "crab-eating macaque": ["croo monkey", "macaca irus", "macaque"],
    "crab-eating opossum": ["opossum", "possum"],
    "crab-eating raccoon": ["procyon cancrivorus", "raccoon", "racoon"],
    "crabapple jelly": ["apple jelly"],
    "crabbed": ["bad-tempered", "crabby", "cross", "fussy", "grouchy", "grumpy", "ill-tempered"],
    "crabbiness": ["crabbedness", "crossness", "ill nature"],
    "crabeater seal": ["crab-eating seal", "seal"],
    "crabgrass": ["crab grass", "crowfoot grass", "dactyloctenium aegypticum", "digitaria ischaemum", "digitaria sanguinalis", "egyptian grass", "finger grass", "grass", "hairy finger grass", "large crabgrass", "smooth crabgrass"],
    "crabwise": ["sideways"],
    "cracidae": ["bird family", "family cracidae"],
    "crack": ["break", "break in"],
    "crack addict": ["binger", "drug addict", "junkie", "junky"],
    "crack up": ["break up", "collapse", "crack", "crock up", "get", "have", "suffer", "sustain"],
    "crack willow": ["brittle willow", "salix fragilis", "snap willow", "willow", "willow tree"],
    "crackbrained": ["idiotic"],
    "crackdown": ["crushing", "quelling", "stifling", "suppression"],
    "cracked wheat": ["wheat", "wheat berry"],
    "cracked-wheat bread": ["bread", "breadstuff", "staff of life"],
    "cracker": ["coder", "computer programmer", "programmer", "software engineer"],
    "cracker crumbs": ["crumb"],
    "cracker-barrel": ["folksy", "homespun"],
    "cracking": ["chemical action", "chemical change", "chemical process", "hydrocracking"],
    "crackle": ["alter", "change", "vary"],
    "cracklings": ["edible fat"],
    "crackpot": ["crank", "eccentric", "eccentric person", "flake", "fruitcake", "geek", "nut", "nut case", "oddball", "screwball"],
    "cracow": ["krakau", "krakow"],
    "cracticidae": ["bird family", "family cracticidae"],
    "cracticus": ["bird genus", "genus cracticus"],
    "cradle": ["bring up", "nurture", "parent", "raise", "rear"],
    "cradle cap": ["dermatitis"],
    "craft": ["fashion", "filigree", "forge", "handcraft"],
    "craft fair": ["bazaar", "fair"],
    "craft union": ["brotherhood", "labor union", "trade union", "trades union", "union"],
    "craftily": ["artfully", "cunningly", "foxily", "knavishly", "slyly", "trickily"],
    "craftiness": ["deceitfulness", "disingenuousness", "guile"],
    "craftsman": ["professional", "professional person"],
    "crafty": ["cunning", "dodgy", "foxy", "guileful", "knavish", "slick", "sly", "tricksy", "tricky", "wily"],
    "crag": ["cliff", "drop", "drop-off"],
    "cragfast": [],
    "cragged": ["craggy", "hilly", "mountainous"],
    "craigie": ["sir william alexander craigie", "william a. craigie"],
    "crake": ["corncrake", "crex crex", "land rail", "porzana porzana", "rail", "spotted crake"],
    "cram": ["lay", "place", "pose", "position", "put", "set", "stuff"],
    "crambe": ["dilleniid dicot genus", "genus crambe"],
    "crammer": ["educatee", "pupil", "student"],
    "cramp": ["fasten", "fix", "secure"],
    "cramped": [],
    "crampon": ["crampoon", "grapnel", "grapple", "grappler", "grappling hook", "grappling iron"],
    "cran": ["capacity measure", "capacity unit", "cubage unit", "cubature unit", "cubic content unit", "cubic measure", "displacement unit", "volume unit"],
    "cranberry": ["american cranberry", "bush", "cowberry", "european cranberry", "foxberry", "large cranberry", "lingberry", "lingenberry", "lingonberry", "mountain cranberry", "shrub", "small cranberry", "vaccinium macrocarpon", "vaccinium oxycoccus", "vaccinium vitis-idaea"],
    "cranberry bush": ["american cranberry bush", "bush", "cranberry tree", "highbush cranberry", "shrub", "viburnum trilobum"],
    "cranberry culture": ["culture"],
    "cranberry juice": ["fruit crush", "fruit juice"],
    "cranberry sauce": ["condiment"],
    "crane": ["extend", "stretch", "stretch out"],
    "crane fly": ["daddy longlegs", "dipteran", "dipteron", "dipterous insect", "two-winged insects"],
    "cranesbill": ["crane's bill", "dove's foot geranium", "geranium", "geranium maculatum", "geranium molle", "geranium pratense", "geranium richardsonii", "geranium robertianum", "geranium viscosissimum", "herb robert", "herb roberts", "herbs robert", "meadow cranesbill", "richardson's geranium", "spotted cranesbill", "sticky geranium", "wild geranium"],
    "crangon": ["arthropod genus", "genus crangon"],
    "crangonidae": ["arthropod family", "family crangonidae"],
    "cranial": [],
    "cranial cavity": ["bodily cavity", "cavity", "cavum", "intracranial cavity"],
    "cranial nerve": ["abducens", "abducens nerve", "abducent", "abducent nerve", "accessory nerve", "acoustic nerve", "auditory nerve", "eighth cranial nerve", "eleventh cranial nerve", "facial", "facial nerve", "fifth cranial nerve", "first cranial nerve", "fourth cranial nerve", "glossopharyngeal nerve", "hypoglossal", "hypoglossal nerve", "nerve", "nervii olfactorii", "nervus", "nervus abducens", "nervus accessorius", "nervus facialis", "nervus glossopharyngeus", "nervus hypoglosus", "nervus oculomotorius", "nervus opticus", "nervus trigeminus", "nervus vagus", "nervus vestibulocochlearis", "ninth cranial nerve", "oculomotor", "oculomotor nerve", "olfactory nerve", "optic nerve", "optic tract", "pneumogastric", "pneumogastric nerve", "second cranial nerve", "seventh cranial nerve", "sixth cranial nerve", "spinal accessory", "tenth cranial nerve", "third cranial nerve", "trigeminal", "trigeminal nerve", "trigeminus", "trochlear", "trochlear nerve", "trochlearis", "twelfth cranial nerve", "vagus", "vagus nerve", "vestibulocochlear nerve", "wandering nerve"],
    "craniology": ["bioscience", "life science", "phrenology"],
    "craniometer": ["measuring device", "measuring instrument", "measuring system"],
    "craniometric": ["craniometrical"],
    "craniometric point": ["acanthion", "alveolar point", "asterion", "auricular point", "auriculare", "bregma", "condylion", "coronion", "crotaphion", "dacryon", "entomion", "glabella", "gnathion", "gonion", "inion", "jugal point", "jugale", "lambda", "landmark", "mastoidale", "mesophyron", "metopion", "nasion", "obelion", "ophryon", "orbital point", "orbitale", "pogonion", "prostheon", "prosthion", "pterion", "rhinion", "sphenion", "stephanion", "symphysion"],
    "craniometry": ["physical anthropology"],
    "craniotomy": ["operation", "surgery", "surgical operation", "surgical procedure", "surgical process"],
    "cranium": ["bone", "braincase", "brainpan", "os"],
    "crank": ["crank up", "start", "start up"],
    "crank call": ["call", "phone call", "telephone call"],
    "crank handle": ["crank", "starter", "starting handle"],
    "crank letter": ["letter", "missive"],
    "crankcase": ["housing"],
    "crankiness": ["contrariness", "crotchetiness", "grumpiness", "ill nature"],
    "crankshaft": ["rotating shaft", "shaft"],
    "cranky": ["fractious", "irritable", "nettlesome", "peckish", "peevish", "pettish", "petulant", "scratchy", "techy", "testy", "tetchy"],
    "crannied": [],
    "cranny": ["hole"],
    "crap": ["bm", "dejection", "dirt", "faecal matter", "faeces", "fecal matter", "feces", "ordure", "poop", "shit", "shite", "stool", "turd"],
    "crap shooting": ["crap game", "craps", "crapshoot"],
    "crap up": ["back up", "choke", "choke off", "clog", "clog up", "congest", "foul"],
    "crapaud": ["anuran", "batrachian", "frog", "leptodactylus pentadactylus", "salientian", "south american bullfrog", "toad", "toad frog"],
    "crape": ["cover", "crepe"],
    "crape fern": ["fern", "leptopteris superba", "prince-of-wales feather", "prince-of-wales fern", "prince-of-wales plume", "todea superba"],
    "crape jasmine": ["adam's apple", "bush", "coffee rose", "crepe gardenia", "crepe jasmine", "east indian rosebay", "nero's crown", "pinwheel flower", "shrub", "tabernaemontana divaricate"],
    "crape myrtle": ["bush", "crepe flower", "crepe myrtle", "lagerstroemia indica", "shrub"],
    "crappie": ["sunfish"],
    "craps": ["2", "deuce", "ii", "snake eyes", "two"],
    "crapshoot": ["danger", "peril", "risk"],
    "crapshooter": ["gambler"],
    "crapulent": ["crapulous"],
    "crapulous": [],
    "crash": ["lodge in", "occupy", "reside"],
    "crash barrier": ["barrier"],
    "crash course": ["course of study", "crash program", "crash programme", "curriculum", "program", "programme", "syllabus"],
    "crash dive": ["descent"],
    "crash helmet": ["helmet", "skid lid"],
    "crash land": ["ditch", "land", "set down"],
    "crash landing": ["emergency landing", "forced landing"],
    "crash-dive": ["dive", "plunge", "plunk"],
    "craspedia": ["asterid dicot genus", "genus craspedia"],
    "crass": [],
    "crassness": ["crassitude", "insensitiveness", "insensitivity"],
    "crassostrea": ["genus crassostrea", "mollusk genus"],
    "crassula": ["genus crassula", "plant genus"],
    "crassulaceae": ["family crassulaceae", "plant family", "stonecrop family"],
    "crataegus": ["genus crataegus", "rosid dicot genus"],
    "crate": ["case", "encase", "incase"],
    "crater": [],
    "crater lake national park": [],
    "crateva": ["dilleniid dicot genus", "genus crateva"],
    "craton": ["part", "piece"],
    "cravat": ["ascot", "neckcloth", "neckwear", "stock"],
    "crave": ["desire", "hunger", "lust", "starve", "thirst", "want"],
    "craved": ["desired"],
    "craven": ["recreant"],
    "cravenness": ["cowardice", "cowardliness"],
    "craving": ["addiction", "appetence", "appetency", "appetite", "desire"],
    "craw": ["breadbasket", "crop", "stomach", "tum", "tummy"],
    "crawford": ["thomas crawford"],
    "crawl": ["feel"],
    "crawler": ["creeper", "individual", "mortal", "person", "somebody", "someone", "soul"],
    "crawlspace": ["crawl space", "space"],
    "crax": ["bird genus", "genus crax"],
    "crayfish": ["crawdad", "crawfish", "ecrevisse", "shellfish"],
    "crayon": ["draw"],
    "craze": ["crack"],
    "crazed": ["deranged", "half-crazed"],
    "craziness": ["daftness", "flakiness", "insanity"],
    "crazy": ["looney", "loony", "lunatic", "madman", "maniac", "nutcase", "weirdo"],
    "crazy glue": ["epoxy", "epoxy glue", "epoxy resin"],
    "crazy horse": ["tashunca-uitco"],
    "crazy quilt": ["patchwork", "patchwork quilt"],
    "creak": ["creaking", "noise"],
    "creakily": ["creakingly", "screakily"],
    "creaky": ["decrepit", "derelict", "flea-bitten", "run-down", "woebegone"],
    "cream": ["beat", "scramble"],
    "cream cheese": ["cheese", "double cream", "mascarpone"],
    "cream of tartar": ["potassium bitartrate", "potassium hydrogen tartrate", "salt", "tartar"],
    "cream off": ["choose", "pick out", "select", "skim off", "take"],
    "cream pitcher": ["creamer", "ewer", "pitcher"],
    "cream puff": ["chou", "eclair", "puff"],
    "cream sauce": ["bechamel", "bechamel sauce", "white sauce"],
    "cream soda": ["soft drink"],
    "cream-colored": ["creamy-colored", "creamy-white"],
    "cream-colored courser": ["courser", "cursorius cursor"],
    "cream-of-tartar tree": ["adansonia gregorii", "angiospermous tree", "flowering tree", "sour gourd"],
    "creamcups": ["platystemon californicus", "poppy"],
    "creamery": ["work", "workplace"],
    "creaminess": ["soupiness", "thickness"],
    "creamy": [],
    "creamy-yellow": [],
    "creaseless": ["uncreased"],
    "creaseproof": ["crease-resistant", "wrinkle-resistant", "wrinkleproof"],
    "create": ["appoint", "charge"],
    "create by mental act": ["conceive", "conceive of", "conceptualise", "conceptualize", "concoct", "construct", "contrive", "create", "create mentally", "design", "develop", "devise", "draw", "dream up", "envisage", "evolve", "excogitate", "forge", "formulate", "germinate", "gestate", "give birth", "hatch", "ideate", "imagine", "invent", "make", "plan", "program", "programme", "project", "re-create", "schematize", "think of", "think up", "write"],
    "create from raw material": ["bake", "brew", "coin", "cook", "create", "create from raw stuff", "crochet", "dip", "fix", "forge", "form", "formulate", "intertwine", "knit", "knot", "make", "mint", "mold", "mould", "prepare", "ready", "reform", "shape", "spin", "strike", "tat", "tissue", "weave", "work"],
    "create verbally": ["coin", "compose", "create", "indite", "make", "pen", "publish", "rhyme", "rime", "write"],
    "creatine": ["amino acid", "aminoalkanoic acid", "creatin"],
    "creating by mental acts": ["actualisation", "actualization", "composing", "composition", "computer programing", "computer programming", "conceptualisation", "conceptualization", "creation", "creative activity", "design", "designing", "formation", "formulation", "invention", "programing", "programming", "realisation", "realization", "verbal creation"],
    "creating by removal": ["boring", "carving", "creation", "creative activity", "cutting", "dig", "digging", "drilling", "excavation", "film editing", "gouge"],
    "creating from raw materials": ["baking", "building", "casting", "concoction", "confection", "construction", "creation", "creative activity", "fabrication", "lamination", "manufacture", "manufacturing", "molding", "recording", "transcription"],
    "creation": ["beginning", "conception", "fecundation", "fertilisation", "fertilization", "impregnation"],
    "creation science": ["creationism"],
    "creationism": ["creation science", "doctrine", "ism", "philosophical system", "philosophy", "school of thought"],
    "creative": ["originative"],
    "creatively": [],
    "creativity": ["ability", "cleverness", "conception", "creative thinking", "creativeness", "design", "excogitation", "fecundity", "flight", "fruitfulness", "genius", "imagination", "imaginativeness", "ingeniousness", "ingenuity", "innovation", "invention", "inventiveness", "power", "vision", "wizardry"],
    "creator": ["architect", "artificer", "artist", "builder", "choreographer", "clothes designer", "conceiver", "couturier", "crafter", "craftsman", "creative person", "designer", "developer", "discoverer", "fantasist", "farmer", "fashion designer", "granger", "husbandman", "individual", "inventor", "maker", "mastermind", "modeler", "modeller", "mortal", "originator", "person", "producer", "shaper", "sodbuster", "somebody", "someone", "soul"],
    "creature": ["puppet", "slave", "tool"],
    "creche": ["representation"],
    "crecy": ["battle of crecy"],
    "credence": ["acceptance", "attitude", "fatalism", "mental attitude", "recognition"],
    "credentialled": [],
    "credenza": ["buffet", "counter", "credence", "sideboard"],
    "credibility": ["authenticity", "believability", "cogency", "cred", "credibleness", "genuineness", "legitimacy", "plausibility", "plausibleness", "quality", "rigor", "rigour", "street cred", "street credibility", "validity"],
    "credible": [],
    "credibly": ["believably", "plausibly", "probably"],
    "credit": ["account", "calculate", "finance"],
    "credit account": ["charge account", "charge account credit", "open account", "open-end credit", "revolving charge account", "revolving credit"],
    "credit analyst": ["analyst"],
    "credit application": ["application"],
    "credit bureau": ["agency"],
    "credit card": ["bank card", "calling card", "cash card", "cashcard", "charge account credit", "charge card", "charge plate", "open-end credit", "phone card", "plastic", "positive identification", "revolving credit"],
    "credit crunch": ["financial condition", "liquidity crisis", "squeeze"],
    "credit line": ["bank line", "consumer credit", "credit", "line", "line of credit", "personal credit line", "personal line of credit"],
    "credit order": ["bill-me order", "open account", "order", "purchase order"],
    "credit rating": ["approximation", "credit", "estimate", "estimation", "idea"],
    "credit side": ["accounting", "accounting system", "method of accounting"],
    "credit system": ["system"],
    "credit union": ["bank", "banking company", "banking concern", "depository financial institution"],
    "creditable": [],
    "credited": [],
    "creditor": ["individual", "mortal", "mortgage holder", "mortgagee", "person", "somebody", "someone", "soul"],
    "credits": ["acknowledgement", "acknowledgment", "list", "listing"],
    "creditworthiness": ["trustiness", "trustworthiness"],
    "creditworthy": ["responsible"],
    "credulity": ["overcredulity", "trust", "trustfulness", "trustingness"],
    "credulous": [],
    "credulously": ["believingly"],
    "credulousness": ["gullibility", "naiveness", "naivete", "naivety"],
    "cree": ["algonquian", "algonquin"],
    "creed": ["athanasian creed", "credo", "doctrine", "ism", "philosophical system", "philosophy", "school of thought", "testament"],
    "creedal": ["credal"],
    "creek": ["american indian", "indian", "red indian"],
    "creek confederacy": ["confederacy", "confederation", "federation"],
    "creel": ["basket", "handbasket"],
    "creep": ["diffuse", "fan out", "spread", "spread out"],
    "creep feed": ["feed", "provender"],
    "creep up": ["advance", "go on", "march on", "move on", "pass on", "progress", "sneak up"],
    "creeper": ["tracheophyte", "vascular plant"],
    "creepiness": ["feeling", "tactile sensation", "tactual sensation", "touch", "touch sensation"],
    "creeping bellflower": ["bellflower", "campanula", "campanula rapunculoides"],
    "creeping bent": ["agrostis palustris", "bent", "bent grass", "bent-grass", "creeping bentgrass"],
    "creeping bugle": ["ajuga reptans", "bugle", "bugleweed"],
    "creeping buttercup": ["butter-flower", "buttercup", "butterflower", "creeping crowfoot", "crowfoot", "goldcup", "kingcup", "ranunculus repens"],
    "creeping fern": ["climbing fern", "hartford fern", "lygodium palmatum"],
    "creeping juniper": ["juniper", "juniperus horizontalis"],
    "creeping oxalis": ["creeping wood sorrel", "oxalis", "oxalis corniculata", "sorrel", "wood sorrel"],
    "creeping snowberry": ["gaultheria hispidula", "maidenhair berry", "moxie plum", "shrublet"],
    "creeping soft grass": ["grass", "holcus mollis"],
    "creeping spike rush": ["eleocharis palustris", "spike rush"],
    "creeping st john's wort": ["hypericum calycinum", "st john's wort"],
    "creeping willow": ["salix repens", "willow", "willow tree"],
    "creeping zinnia": ["herb", "herbaceous plant", "sanvitalia procumbens"],
    "creeps": ["animal disease"],
    "creepy": [],
    "creepy-crawlies": ["dislike"],
    "creepy-crawly": ["animal", "animate being", "beast", "brute", "creature", "fauna"],
    "cremains": ["cadaver", "clay", "corpse", "remains", "stiff"],
    "cremate": ["burn", "burn down", "fire"],
    "cremation": ["incineration"],
    "crematory": ["crematorium", "dead room", "morgue", "mortuary"],
    "creme anglais": ["custard"],
    "creme brulee": ["custard"],
    "creme caramel": ["custard"],
    "creme de cacao": ["cordial", "liqueur"],
    "creme de fraise": ["cordial", "liqueur"],
    "creme de menthe": ["cordial", "liqueur"],
    "cremona": [],
    "crenate": ["crenated", "scalloped"],
    "crenate leaf": ["foliage", "leaf", "leafage"],
    "crenel": ["crenelate", "crenellate", "furnish", "provide", "render", "supply"],
    "crenelation": ["building", "construction", "crenellation"],
    "crenulate": ["crenulated"],
    "creole": ["american"],
    "creole-fish": ["grouper", "paranthias furcifer"],
    "creolize": ["change"],
    "creon": [],
    "creosol": ["phenol"],
    "creosote": ["process", "treat"],
    "creosote bush": ["bush", "coville", "hediondilla", "larrea tridentata", "shrub"],
    "crepe": ["crepe paper", "paper"],
    "crepe de chine": ["crape", "crepe"],
    "crepe fern": ["fern", "king fern", "todea barbara"],
    "crepe rubber": ["caoutchouc", "gum elastic", "india rubber", "natural rubber", "rubber"],
    "crepe suzette": ["crape", "crepe", "french pancake"],
    "crepis": ["asterid dicot genus", "genus crepis"],
    "crepitate": ["crackle", "rattle"],
    "crepitation rale": ["rale", "rattle", "rattling", "symptom"],
    "crepuscular": [],
    "crescendo": ["increase"],
    "crescent": ["curve", "curved shape"],
    "crescent roll": ["bun", "croissant", "roll"],
    "crescent wrench": ["adjustable spanner", "adjustable wrench"],
    "crescentia": ["asterid dicot genus", "genus crescentia"],
    "cresol": ["lysol", "methyl phenol", "phenol"],
    "cress": ["arabidopsis lyrata", "arabidopsis thaliana", "arabis glabra", "bitter cress", "bittercress", "cochlearia officinalis", "common garden cress", "common scurvy grass", "cress plant", "crucifer", "cruciferous plant", "garden pepper cress", "lepidium sativum", "mouse-ear cress", "pepper grass", "pepperwort", "rock cress", "rockcress", "scurvy grass", "st. barbara's herb", "tower cress", "tower mustard", "turritis glabra", "watercress", "winter cress"],
    "cress green": ["cresson", "watercress"],
    "crest": ["peak", "top out"],
    "crested": [],
    "crested cariama": ["cariama cristata", "seriema", "wader", "wading bird"],
    "crested coral root": ["hexalectris spicata", "orchid", "orchidaceous plant"],
    "crested myna": ["acridotheres tristis", "mina", "minah", "myna", "myna bird", "mynah", "mynah bird"],
    "crested screamer": ["chaja", "chauna torquata", "screamer"],
    "crested wheatgrass": ["agropyron cristatum", "crested wheat grass", "fairway crested wheat grass", "wheat-grass", "wheatgrass"],
    "cretaceous": ["cretaceous period"],
    "cretan": ["european", "minoan"],
    "crete": ["kriti"],
    "cretinism": ["hypothyroidism"],
    "cretinous": [],
    "cretonne": ["cloth", "fabric", "material", "textile"],
    "creutzfeldt-jakob disease": ["brain disease", "brain disorder", "cjd", "encephalopathy", "jakob-creutzfeldt disease"],
    "crevalle jack": ["caranx hippos", "jack", "jack crevalle"],
    "crevasse": ["cleft", "crack", "crevice", "fissure", "scissure"],
    "crevice": ["chap", "crack", "cranny", "depression", "fissure", "impression", "imprint"],
    "crew": ["man"],
    "crew cut": ["flattop", "haircut"],
    "crew neck": ["crew neckline", "neckline"],
    "crewelwork": ["embroidery", "fancywork"],
    "crewman": ["aircrewman", "crew member", "privateer", "privateersman", "skilled worker", "skilled workman", "trained worker"],
    "crex": ["bird genus", "genus crex"],
    "crib": ["cheat", "chisel"],
    "cribbage": ["card game", "cards", "crib"],
    "cribbage board": ["board", "gameboard"],
    "cricetidae": ["family cricetidae", "mammal family"],
    "cricetus": ["genus cricetus", "mammal genus"],
    "crichton": ["james crichton", "the admirable crichton"],
    "crick": ["twist"],
    "cricket": ["play"],
    "cricket ball": ["ball", "cricket equipment"],
    "cricket bat": ["bat", "cricket equipment"],
    "cricket equipment": ["bat", "cricket ball", "cricket bat", "sports equipment", "wicket"],
    "cricket frog": ["acris crepitans", "acris gryllus", "eastern cricket frog", "northern cricket frog", "tree frog", "tree toad", "tree-frog"],
    "cricket match": ["match"],
    "cricket-bat willow": ["salix alba caerulea", "willow", "willow tree"],
    "cricketer": ["athlete", "bowler", "fielder", "fieldsman", "jock", "wicket-keeper"],
    "crier": ["bawler", "bellower", "hawker", "packman", "peddler", "pedlar", "pitchman", "roarer", "screamer", "screecher", "shouter", "yeller"],
    "crime": ["evildoing", "transgression"],
    "crime rate": ["rate"],
    "crime wave": ["rise"],
    "crimea": [],
    "crimea-congo hemorrhagic fever": ["haemorrhagic fever", "hemorrhagic fever", "vhf", "viral haemorrhagic fever", "viral hemorrhagic fever"],
    "crimean war": [],
    "criminal": ["abductor", "accessary", "accessory", "arsonist", "blackmailer", "bootlegger", "briber", "coconspirator", "conspirator", "contrabandist", "crook", "desperado", "desperate criminal", "drug dealer", "drug peddler", "drug trafficker", "extortioner", "extortionist", "felon", "firebug", "fugitive", "fugitive from justice", "gangster", "gangster's moll", "gaolbird", "goon", "gun moll", "habitual criminal", "highbinder", "highjacker", "hijacker", "hood", "hoodlum", "incendiary", "jail bird", "jailbird", "kidnaper", "kidnapper", "law offender", "lawbreaker", "liquidator", "machinator", "mafioso", "malefactor", "manslayer", "mobster", "moll", "moon curser", "moon-curser", "moonshiner", "murderer", "outlaw", "parolee", "peddler", "plotter", "principal", "probationer", "punk", "pusher", "racketeer", "raper", "rapist", "recidivist", "repeater", "runner", "scofflaw", "smuggler", "snatcher", "stealer", "strong-armer", "suborner", "thief", "thug", "tough", "toughie", "traitor", "treasonist", "violator"],
    "criminal contempt": ["contempt of court"],
    "criminal court": ["court", "judicature", "night court", "old bailey", "tribunal"],
    "criminal intelligence services of canada": ["cisc", "international intelligence agency"],
    "criminal investigation command": ["cid", "law enforcement agency"],
    "criminal law": ["legal code"],
    "criminal negligence": ["carelessness", "culpable negligence", "neglect", "negligence", "nonperformance"],
    "criminal possession": ["illegal possession", "ownership", "possession"],
    "criminal record": ["list", "listing", "record"],
    "criminal suit": ["case", "causa", "cause", "lawsuit", "suit"],
    "criminalism": ["criminality", "criminalness", "guilt", "guiltiness"],
    "criminalization": ["criminalisation", "lawmaking", "legislating", "legislation"],
    "criminalize": ["do by", "handle", "treat"],
    "criminally": ["reprehensively"],
    "criminative": ["criminatory", "incriminating", "incriminatory"],
    "criminological": [],
    "criminologist": ["specialiser", "specialist", "specializer"],
    "criminology": ["penology", "poenology", "sociology"],
    "crimp": ["flute", "fold", "fold up", "pinch", "turn up"],
    "crimson": ["deep red", "red", "redness", "ruby"],
    "crimson clover": ["clover", "italian clover", "trefoil", "trifolium incarnatum"],
    "crimson-magenta": [],
    "crimson-purple": [],
    "crimson-yellow": [],
    "cringing": ["groveling", "grovelling", "wormlike", "wormy"],
    "cringle": ["eyelet", "fastener", "fastening", "fixing", "grommet", "grummet", "holdfast", "loop"],
    "crinkled": ["crinkly", "rippled", "wavelike", "wavy"],
    "crinkleroot": ["bitter cress", "bittercress", "cardamine diphylla", "crinkle root", "crinkle-root", "dentaria diphylla", "pepper root", "toothwort"],
    "crinoid": ["comatulid", "echinoderm", "feather star", "sea lily"],
    "crinoidea": ["class", "class crinoidea"],
    "crinoline": ["half-slip", "petticoat", "underskirt"],
    "criollo": ["hispanic", "hispanic american", "spanish american"],
    "cripple": ["stultify", "weaken"],
    "crippled": ["game", "gimpy", "halt", "halting", "lame"],
    "crippling": ["disabling", "incapacitating"],
    "crisis": ["critical point", "crossroads", "depression", "dunkirk", "economic crisis", "exigency", "juncture", "situation", "slump"],
    "crisis intervention": ["psychotherapy"],
    "crisp": ["crispy"],
    "crispate": [],
    "crispen": ["crisp", "heat", "heat up", "toast"],
    "crisphead lettuce": ["iceberg", "iceberg lettuce", "lettuce"],
    "crispin": ["saint crispin", "st. crispin"],
    "crispness": ["terseness"],
    "crisscross": ["cover", "cross", "cut across", "cut through", "get across", "get over", "pass over", "track", "traverse"],
    "cristobalite": ["mineral"],
    "criterial": ["criterional"],
    "criterion": ["control", "control condition", "design criteria", "ideal", "standard"],
    "crith": ["weight", "weight unit"],
    "critic": ["art critic", "drama critic", "literary critic", "music critic", "newspaper critic", "professional", "professional person", "theater critic"],
    "critical": [],
    "critical angle": ["angle of incidence", "incidence angle"],
    "critical appraisal": ["appraisal", "assessment", "critical analysis", "criticism", "critique"],
    "critical mass": ["amount"],
    "criticality": ["criticalness", "cruciality", "urgency"],
    "critically": [],
    "criticism": ["attack", "blast", "brickbat", "carping", "disapproval", "faultfinding", "fire", "flack", "flak", "potshot", "rebuke", "reprehension", "reprimand", "reproof", "reproval", "slating", "static", "stricture", "thrust", "unfavorable judgment"],
    "criticize": ["act", "criticise"],
    "critter": ["animal", "animate being", "beast", "brute", "creature", "fauna"],
    "crius": [],
    "cro-magnon": ["homo sapiens"],
    "croak": ["cronk", "emit", "let loose", "let out", "utter"],
    "croaker": ["saltwater fish"],
    "croaky": ["guttural"],
    "croatia": ["hrvatska", "republic of croatia"],
    "croatian": ["croat", "slav"],
    "crocethia": ["bird genus", "genus crocethia"],
    "crochet": ["create from raw material", "create from raw stuff", "double crochet", "double stitch", "shell stitch", "single crochet", "single stitch"],
    "crochet needle": ["crochet hook", "needle"],
    "crochet stitch": ["chain stitch", "double crochet", "double stitch", "shell stitch", "single crochet", "single stitch", "stitch"],
    "crocheting": ["handicraft"],
    "crock": ["bleed", "run"],
    "crock pot": ["cooker"],
    "crockery": ["china", "chinaware", "cup", "dish", "dishware", "egg cup", "eggcup", "ovenware", "tableware"],
    "crocket": ["architectural ornament"],
    "crocketed": [],
    "crockett": ["david crockett", "davy crockett"],
    "crocodile": ["african crocodile", "asian crocodile", "crocodilian", "crocodilian reptile", "crocodylus niloticus", "crocodylus porosus", "morlett's crocodile", "nile crocodile"],
    "crocodile bird": ["courser", "pluvianus aegyptius"],
    "crocodile tears": ["hypocrisy", "lip service"],
    "crocodilian reptile": ["alligator", "caiman", "cayman", "crocodile", "crocodilian", "diapsid", "diapsid reptile", "false gavial", "gator", "gavial", "gavialis gangeticus", "tomistoma schlegeli"],
    "crocodylia": ["animal order", "crocodilia", "order crocodilia", "order crocodylia"],
    "crocodylidae": ["family crocodylidae", "reptile family"],
    "crocodylus": ["crocodilus", "genus crocodilus", "genus crocodylus", "reptile genus"],
    "crocolite": ["mineral"],
    "crocus": ["crocus sativus", "iridaceous plant", "saffron", "saffron crocus"],
    "crocuta": ["genus crocuta", "mammal genus"],
    "croesus": [],
    "croft": ["farm"],
    "crofter": ["small farmer"],
    "crohn": ["burrill bernard crohn"],
    "croix de guerre": ["decoration", "laurel wreath", "medal", "medallion", "palm", "ribbon"],
    "cromwell": ["ironsides", "oliver cromwell"],
    "cromwellian": [],
    "cronartium": ["fungus genus", "genus cronartium"],
    "cronus": [],
    "cronyism": ["discrimination", "favoritism", "favouritism"],
    "cronyn": ["hume blake cronyn", "hume cronyn"],
    "crook": ["bend", "curve", "flex", "recurve"],
    "crookback": ["crookbacked", "gibbous", "humpbacked", "humped", "hunchbacked", "kyphotic"],
    "crooked": ["corrupt"],
    "crooked-stemmed aster": ["aster"],
    "crookedness": ["configuration", "conformation", "contour", "form", "shape"],
    "crookes": ["sir william crookes", "william crookes"],
    "crookes radiometer": ["radiometer"],
    "crookes tube": ["cathode-ray tube", "crt"],
    "crookneck": ["crookneck squash", "summer crookneck", "yellow squash"],
    "croon": ["sing"],
    "crooner": ["balladeer", "singer", "vocaliser", "vocalist", "vocalizer"],
    "crooning": ["singing", "vocalizing"],
    "crop": ["bear", "turn out"],
    "crop failure": ["failure"],
    "crop up": ["appear", "pop", "pop up"],
    "crop-dusting": ["diffusion", "dispersal", "dispersion", "dissemination", "spraying"],
    "cropped": [],
    "croquet": ["hit"],
    "croquet ball": ["ball", "croquet equipment"],
    "croquet equipment": ["croquet ball", "croquet mallet", "hoop", "sports equipment", "wicket"],
    "croquet mallet": ["croquet equipment", "mallet"],
    "croquette": ["dish"],
    "crore": ["large integer"],
    "crosby": ["bing crosby", "harry lillis crosby"],
    "crosier": ["crozier", "staff"],
    "cross": ["continue", "cover", "extend", "span", "sweep", "traverse"],
    "cross bit": ["bore bit", "borer", "rock drill", "stone drill"],
    "cross bun": ["coffee roll", "hot cross bun", "sweet roll"],
    "cross country": ["iditarod", "iditarod trail dog sled race", "race"],
    "cross examine": ["cross question", "examine"],
    "cross hair": ["cross wire", "line"],
    "cross off": ["cross out", "mark", "strike off", "strike out", "take away", "take out"],
    "cross oneself": ["gesticulate", "gesture", "motion"],
    "cross section": ["plane section", "profile", "section"],
    "cross street": ["street"],
    "cross vine": ["bignonia capreolata", "quarter-vine", "quartervine", "trumpet flower", "vine"],
    "cross-banded": [],
    "cross-check": ["ascertain", "assure", "check", "control", "ensure", "insure", "see", "see to it"],
    "cross-classification": ["categorisation", "categorization", "classification", "cross-division", "sorting"],
    "cross-country": [],
    "cross-country riding": ["cross-country jumping", "equestrian sport"],
    "cross-country skiing": ["skiing"],
    "cross-cultural": [],
    "cross-dress": ["dress", "get dressed"],
    "cross-examination": ["examination", "interrogation", "interrogatory"],
    "cross-examiner": ["asker", "cross-questioner", "enquirer", "inquirer", "querier", "questioner"],
    "cross-eye": ["convergent strabismus", "crossed eye", "esotropia", "squint", "strabismus"],
    "cross-eyed": [],
    "cross-fertilization": ["allogamy", "cross-fertilisation", "fecundation", "fertilisation", "fertilization", "impregnation"],
    "cross-fertilize": ["change state", "cross-fertilise", "turn"],
    "cross-file": ["campaign", "register", "run", "slate"],
    "cross-florida waterway": ["okeechobee waterway"],
    "cross-index": ["index"],
    "cross-leaved heath": ["bell heather", "erica", "erica tetralix", "true heath"],
    "cross-legged": [],
    "cross-linguistic": [],
    "cross-linguistically": [],
    "cross-link": ["conjoin", "join"],
    "cross-modal": [],
    "cross-ply": [],
    "cross-pollinating": [],
    "cross-pollination": ["pollenation", "pollination"],
    "cross-purpose": ["aim", "design", "intent", "intention", "purpose"],
    "cross-question": ["interrogation", "interrogative", "interrogative sentence", "question"],
    "cross-refer": ["advert", "bring up", "cite", "mention", "name", "refer"],
    "cross-reference": ["acknowledgment", "citation", "cite", "credit", "cross-index", "mention", "quotation", "reference"],
    "cross-section": ["cross-sectional"],
    "cross-sectional": [],
    "cross-sentential": [],
    "cross-shaped": [],
    "cross-stitch": ["embroidery stitch", "half cross stitch", "sewing stitch"],
    "crossbar": ["bar", "doubletree", "swingletree", "whiffletree", "whippletree"],
    "crossbench": ["seat"],
    "crossbencher": ["legislator"],
    "crossbill": ["finch", "loxia curvirostra"],
    "crossbones": ["symbol", "symbolic representation", "symbolisation", "symbolization"],
    "crossbow": ["bow"],
    "crossbred": [],
    "crossbreed": ["backcross", "breed", "cross", "hybridise", "hybridize", "interbreed"],
    "crosscheck": ["check", "confirmation", "substantiation", "verification"],
    "crosscut": ["cut", "cut across"],
    "crosscut saw": ["carpenter's saw", "crosscut handsaw", "cutoff saw", "hand saw", "handsaw"],
    "crosse": ["racket", "racquet"],
    "crossed": [],
    "crossfire": ["conversation"],
    "crosshairs": ["center", "center of attention", "centre", "centre of attention"],
    "crosshatch": ["fill in", "shade"],
    "crosshead": ["block"],
    "crossheading": ["crosshead", "head", "header", "heading"],
    "crossing": ["point"],
    "crossing guard": ["lollipop lady", "lollipop woman", "traffic cop"],
    "crossing over": ["biological process", "crossover", "organic process"],
    "crossjack": ["canvas", "canvass", "mizzen course", "sail", "sheet"],
    "crossly": ["grouchily", "grumpily"],
    "crossopterygian": ["bony fish", "coelacanth", "latimeria chalumnae", "lobe-finned fish", "lobefin"],
    "crossopterygii": ["class", "subclass crossopterygii"],
    "crossover": ["adoption", "borrowing"],
    "crossover voter": ["crossover", "elector", "voter"],
    "crosspiece": ["brace", "bracing", "cross thwart", "crossbar", "round", "rundle", "rung", "spoke", "stave", "thwart", "transom", "traverse"],
    "crossroads": ["convergence", "intersection", "overlap"],
    "crossruff": ["ruff", "trump"],
    "crosstalk": ["disturbance", "interference", "noise", "xt"],
    "crosstown": [],
    "crosswind": ["air current", "current of air", "wind"],
    "crosswise": [],
    "crossword puzzle": ["crossword", "puzzle"],
    "crotalaria": ["american rattlebox", "crotalaria sagitallis", "crotalaria spectabilis", "herb", "herbaceous plant", "indian rattlebox", "rattlebox"],
    "crotalidae": ["family crotalidae", "reptile family"],
    "crotalus": ["genus crotalus", "reptile genus"],
    "crotaphion": ["craniometric point"],
    "crotaphytus": ["genus crotaphytus", "reptile genus"],
    "crotch": ["angle", "fork"],
    "crotchet": ["hook"],
    "croton": ["bush", "codiaeum variegatum", "shrub"],
    "croton oil": ["oil"],
    "crotophaga": ["bird genus", "genus crotophaga"],
    "crottle": ["crotal", "crottal", "lichen"],
    "crouch": ["bend", "bow", "cower", "flex", "huddle", "squinch", "stoop"],
    "croup": ["angina", "spasmodic laryngitis"],
    "croupier": ["gambler"],
    "croupier's rake": ["rake"],
    "croupy": [],
    "crouse": ["russel crouse"],
    "crouton": ["bread", "breadstuff", "staff of life"],
    "crow": ["emit", "let loose", "let out", "utter"],
    "crow garlic": ["allium vineale", "false garlic", "field garlic", "stag's garlic", "wild garlic", "wild onion"],
    "crow pheasant": ["centropus sinensis", "coucal"],
    "crow's foot": ["crease", "crinkle", "crow's feet", "furrow", "laugh line", "line", "seam", "wrinkle"],
    "crow's nest": ["platform"],
    "crow-sized": [],
    "crowbait": ["crow-bait", "mount", "riding horse", "saddle horse"],
    "crowbar": ["jemmy", "jim crow", "jimmy", "lever", "pry", "pry bar", "wrecking bar"],
    "crowberry": ["bush", "shrub"],
    "crowd": ["fill", "occupy"],
    "crowd control": ["control"],
    "crowded": [],
    "crowding": ["congestion", "over-crowding", "situation", "state of affairs"],
    "crown": ["head"],
    "crown colony": ["colony", "dependency"],
    "crown daisy": ["chrysanthemum", "chrysanthemum coronarium"],
    "crown fire": ["forest fire"],
    "crown gall": ["hairy root", "plant disease"],
    "crown glass": ["glass"],
    "crown imperial": ["checkered lily", "fritillaria imperialis", "fritillary"],
    "crown jewel": ["assets"],
    "crown jewels": ["crown", "diadem", "regalia"],
    "crown land": ["acres", "demesne", "estate", "land", "landed estate"],
    "crown lens": ["lens", "lens system", "lense"],
    "crown of thorns": ["christ plant", "christ thorn", "euphorbia milii", "spurge"],
    "crown prince": ["prince"],
    "crown princess": ["married woman", "wife"],
    "crown saw": ["saw"],
    "crown wart": ["plant disease"],
    "crownbeard": ["actinomeris alternifolia", "butter daisy", "composite", "composite plant", "cowpen daisy", "crown beard", "crown-beard", "frost-weed", "frostweed", "golden crown beard", "golden crownbeard", "golden honey plant", "golden ironweed", "gravelweed", "verbesina alternifolia", "verbesina encelioides", "verbesina helianthoides", "verbesina virginica", "virginia crownbeard", "wingstem", "ximenesia encelioides", "yellow ironweed"],
    "crowned": [],
    "crowning": [],
    "crucial": [],
    "crucially": [],
    "crucian carp": ["carassius carassius", "carassius vulgaris", "cyprinid", "cyprinid fish"],
    "cruciate": ["cruciform"],
    "crucible": ["melting pot", "vessel"],
    "crucible steel": ["steel"],
    "crucifer": ["alliaria officinalis", "alyssum", "anastatica hierochuntica", "bok choi", "bok choy", "borecole", "brassica oleracea", "brassica oleracea acephala", "brassica oleracea botrytis", "brassica oleracea gemmifera", "brassica oleracea gongylodes", "brassica oleracea italica", "brassica perviridis", "brassica rapa chinensis", "brassica rapa pekinensis", "brassica rapa perviridis", "brassica rapa ruvo", "broccoli", "broccoli raab", "broccoli rabe", "brussels sprout", "cabbage", "camelina sativa", "capsella bursa-pastoris", "cauliflower", "celery cabbage", "chinese cabbage", "chinese white cabbage", "cole", "colewort", "cress", "cress plant", "cruciferous plant", "cultivated cabbage", "garlic mustard", "gold of pleasure", "hedge garlic", "herb", "herbaceous plant", "jack-by-the-hedge", "kail", "kale", "kohlrabi", "madwort", "malheur wire lettuce", "mustard", "napa", "pak choi", "pakchoi", "pe-tsai", "radish", "radish plant", "resurrection plant", "rose of jericho", "sauce-alone", "shepherd's pouch", "shepherd's purse", "spinach mustard", "stephanomeria malheurensis", "tendergreen", "turnip plant", "wild cabbage"],
    "cruciferae": ["brassicaceae", "dilleniid dicot family", "family brassicaceae", "family cruciferae", "mustard family"],
    "cruciferous": [],
    "cruciferous vegetable": ["broccoli", "broccoli raab", "broccoli rabe", "brussels sprouts", "cabbage", "cauliflower", "chou", "indian mustard", "kohlrabi", "leaf mustard", "mustard", "mustard greens", "radish", "turnip", "turnip cabbage", "veg", "vegetable", "veggie"],
    "crucifix": ["cross", "rood", "rood-tree"],
    "crucifix fish": ["sea catfish"],
    "crucifixion": [],
    "crucify": ["execute", "put to death"],
    "crud": ["snow"],
    "cruddy": ["filthy", "foul", "nasty", "smutty"],
    "crude": ["rough"],
    "crudely": [],
    "crudeness": ["crudity", "natural state", "primitiveness", "primitivism", "rudeness", "state of nature", "wild"],
    "crudites": ["appetiser", "appetizer", "carrot stick", "celery stick", "starter"],
    "cruel and unusual punishment": ["penalisation", "penalization", "penalty", "punishment"],
    "cruel plant": ["araujia sericofera", "vine"],
    "cruelly": [],
    "cruelty": ["coldheartedness", "hardheartedness", "heartlessness", "mercilessness", "pitilessness", "ruthlessness"],
    "cruet": ["bottle", "crewet"],
    "cruet-stand": ["rack", "stand"],
    "cruise": ["look", "search"],
    "cruise control": ["control", "controller"],
    "cruise missile": ["aircraft", "bomb"],
    "cruise ship": ["cruise liner", "liner", "ocean liner"],
    "cruiser": ["auto", "automobile", "car", "machine", "motorcar", "panda car", "patrol car", "police car", "police cruiser", "prowl car", "squad car"],
    "cruller": ["friedcake", "twister"],
    "crumb": ["coat", "surface"],
    "crumb cake": ["cake"],
    "crumble": ["break down", "change integrity", "collapse", "crumple", "tumble"],
    "crumbliness": ["breakableness", "friability"],
    "crumbly": ["friable"],
    "crump": ["crackle", "crunch", "scranch", "scraunch", "scrunch", "thud"],
    "crumpet": ["cake"],
    "crunch": ["cranch", "craunch", "grind", "press"],
    "crupper": ["strap"],
    "crural": [],
    "crus": ["limb"],
    "crusade": ["advertise", "advertize", "agitate", "campaign", "fight", "press", "promote", "push"],
    "crusader": ["warrior"],
    "cruse": ["jar"],
    "crush": ["abase", "chagrin", "demolish", "humble", "humiliate", "mortify", "smash"],
    "crushed": [],
    "crushed leather": ["crush", "leather"],
    "crusher": ["device"],
    "crushing": ["devastating"],
    "crushingly": [],
    "crust": ["change surface"],
    "crustacea": ["class", "class crustacea"],
    "crustacean": ["arthropod", "barnacle", "brachyuran", "branchiopod", "branchiopod crustacean", "branchiopodan", "cirriped", "cirripede", "copepod", "copepod crustacean", "decapod", "decapod crustacean", "malacostracan crustacean", "mussel shrimp", "ostracod", "seed shrimp", "stomatopod", "stomatopod crustacean"],
    "crustaceous": ["crustacean"],
    "crustal": [],
    "crustal movement": ["motion", "movement", "tectonic movement"],
    "crusted": ["crustlike", "crusty", "encrusted"],
    "crustose": [],
    "crustose thallus": ["thallus"],
    "crusty": ["curmudgeonly", "gruff", "ill-humored", "ill-humoured"],
    "crutch": ["staff"],
    "crux": ["alpha and omega", "crux of the matter", "point"],
    "cry": ["need", "require", "want"],
    "cry out for": ["ask", "call for", "cry for", "demand", "involve", "necessitate", "need", "postulate", "require", "take"],
    "cryesthesia": ["cryaesthesia", "hypersensitivity"],
    "crying": ["activity", "bawling", "bodily function", "bodily process", "body process", "snivel", "sniveling", "sob", "sobbing", "tears", "wailing", "weeping"],
    "cryoanesthesia": ["anaesthesia", "anesthesia", "cryoanaesthesia"],
    "cryobiology": ["biological science", "biology", "cryonics"],
    "cryocautery": ["cauterant", "cautery"],
    "cryogen": ["liquid air", "liquid nitrogen", "refrigerant"],
    "cryogenic": [],
    "cryogenics": ["cryogeny", "natural philosophy", "physics"],
    "cryolite": ["greenland spar", "mineral"],
    "cryometer": ["thermometer"],
    "cryonic": [],
    "cryonics": ["cryobiology"],
    "cryophobia": ["simple phobia"],
    "cryoscope": ["measuring device", "measuring instrument", "measuring system"],
    "cryostat": ["thermoregulator", "thermostat"],
    "cryosurgery": ["operation", "surgery", "surgical operation", "surgical procedure", "surgical process"],
    "crypt": ["burial chamber", "sepulcher", "sepulchre", "sepulture"],
    "cryptacanthodes": ["fish genus", "genus cryptacanthodes"],
    "cryptanalysis": ["cryptanalytics", "cryptography", "cryptology", "science", "scientific discipline"],
    "cryptanalyst": ["cryptographer", "cryptologist", "decipherer", "decoder"],
    "cryptanalytic": ["cryptographic", "cryptographical", "cryptologic", "cryptological"],
    "cryptic": ["cryptical", "deep", "inscrutable", "mysterious", "mystifying"],
    "cryptic coloration": ["protective coloration"],
    "cryptically": ["enigmatically", "mysteriously"],
    "cryptobiosis": ["physical condition", "physiological condition", "physiological state"],
    "cryptobiotic": [],
    "cryptobranchidae": ["amphibian family", "family cryptobranchidae"],
    "cryptobranchus": ["amphibian genus", "genus cryptobranchus"],
    "cryptocercidae": ["arthropod family", "family cryptocercidae"],
    "cryptocercus": ["arthropod genus", "genus cryptocercus"],
    "cryptococcosis": ["fungal infection", "mycosis"],
    "cryptocoryne": ["aquatic plant", "hydrophyte", "hydrophytic plant", "water plant", "water trumpet"],
    "cryptogam": ["flora", "plant", "plant life", "thallophyte"],
    "cryptogamia": ["division"],
    "cryptogamic": ["cryptogamous"],
    "cryptogram": ["cryptograph", "piece of writing", "secret writing", "writing", "written material"],
    "cryptogramma": ["fern genus", "genus cryptogramma"],
    "cryptogrammataceae": ["family cryptogrammataceae", "fern family"],
    "cryptograph": ["device"],
    "cryptographically": [],
    "cryptography": ["coding", "committal to writing", "decipherment", "decoding", "decryption", "encoding", "encryption", "recoding", "secret writing", "steganography", "writing"],
    "cryptomeria": ["genus cryptomeria", "gymnosperm genus"],
    "cryptomonad": ["alga", "algae", "cryptophyte"],
    "cryptophyceae": ["class", "class cryptophyceae"],
    "cryptophyta": ["phylum", "phylum cryptophyta"],
    "cryptoprocta": ["civet", "civet cat", "genus cryptoprocta"],
    "cryptorchidy": ["abnormalcy", "abnormality", "cryptorchidism", "cryptorchism", "monorchidism", "monorchism"],
    "cryptotermes": ["arthropod genus", "genus cryptotermes"],
    "cryptotis": ["genus cryptotis", "mammal genus"],
    "crystal": ["diamond dust", "flake", "frost mist", "frost snow", "gem", "gemstone", "ice", "ice crystal", "ice needle", "poudrin", "snow mist", "snowflake", "solid", "stone", "twins", "water ice"],
    "crystal ball": ["ball", "globe", "orb"],
    "crystal counter": ["counter tube"],
    "crystal detector": ["detector"],
    "crystal gazing": ["prognostication", "prophecy", "vaticination"],
    "crystal microphone": ["microphone", "mike"],
    "crystal oscillator": ["oscillator", "quartz oscillator"],
    "crystal pickup": ["cartridge", "pickup"],
    "crystal set": ["radio", "radio receiver", "radio set", "receiving set", "tuner", "wireless"],
    "crystalline": [],
    "crystallite": ["crystal", "crystallization"],
    "crystallization": ["bloom", "chemical phenomenon", "crystallisation", "crystallizing", "efflorescence"],
    "crystallize": ["change integrity", "crystalise", "crystalize", "crystallise"],
    "crystallized": ["crystallised"],
    "crystallized ginger": ["candied fruit", "crystallized fruit", "succade"],
    "crystallographer": ["specialiser", "specialist", "specializer"],
    "crystallography": ["natural philosophy", "physics"],
    "ctene": ["comb-plate", "organ"],
    "ctenidium": ["branchia", "gill"],
    "ctenizidae": ["arthropod family", "family ctenizidae"],
    "ctenocephalides": ["arthropod genus", "ctenocephalus", "genus ctenocephalides", "genus ctenocephalus"],
    "ctenocephalus": ["ctenocephalides", "genus ctenocephalides", "genus ctenocephalus"],
    "ctenoid": ["comb-like"],
    "ctenophora": ["phylum", "phylum ctenophora"],
    "ctenophore": ["beroe", "cestum veneris", "comb jelly", "invertebrate", "platyctenean", "sea gooseberry", "venus's girdle"],
    "ctenophore family": ["cestidae", "family", "family cestidae", "family pleurobrachiidae", "pleurobrachiidae"],
    "ctenophore genus": ["cestum", "genus", "genus beroe", "genus cestum", "genus pleurobrachia", "pleurobrachia"],
    "cub": ["bear", "birth", "deliver", "give birth", "have"],
    "cub scout": ["boy scout"],
    "cuba": ["republic of cuba"],
    "cuban": ["west indian"],
    "cuban bast": ["blue mahoe", "hibiscus", "hibiscus elatus", "mahagua", "mahoe", "majagua"],
    "cuban heel": ["heel"],
    "cuban monetary unit": ["cuban peso", "monetary unit", "peso"],
    "cuban peso": ["cuban monetary unit", "peso"],
    "cuban revolution": [],
    "cubby": ["cubbyhole", "room", "snug", "snuggery"],
    "cubbyhole": ["compartment", "pigeonhole"],
    "cube": ["cut", "dice"],
    "cube root": ["root"],
    "cubeb": ["fruit"],
    "cubelike": ["cube-shaped", "cubical", "cubiform", "cuboid", "cuboidal"],
    "cubic": ["three-dimensional"],
    "cubic foot": ["capacity measure", "capacity unit", "cu ft", "cubage unit", "cubature unit", "cubic content unit", "cubic measure", "displacement unit", "volume unit"],
    "cubic inch": ["capacity measure", "capacity unit", "cu in", "cubage unit", "cubature unit", "cubic content unit", "cubic measure", "displacement unit", "volume unit"],
    "cubic kilometer": ["cubic kilometre", "metric capacity unit"],
    "cubic millimeter": ["cubic millimetre", "metric capacity unit"],
    "cubic yard": ["capacity measure", "capacity unit", "cubage unit", "cubature unit", "cubic content unit", "cubic measure", "displacement unit", "volume unit", "yard"],
    "cubicity": ["third-dimensionality", "three-dimensionality"],
    "cubism": ["analytical cubism", "art movement", "artistic movement", "synthetic cubism"],
    "cubist": ["painter"],
    "cubit": ["linear measure", "linear unit"],
    "cubital": [],
    "cubitiere": ["armor plate", "armor plating", "armour plate", "plate armor", "plate armour"],
    "cubitus": ["limb"],
    "cuboid": ["parallelepiped", "parallelepipedon", "parallelopiped", "parallelopipedon"],
    "cuboid bone": ["bone", "os"],
    "cuboidal cell": ["cuboidal epithelial cell", "epithelial cell"],
    "cucking stool": ["ducking stool", "instrument of punishment"],
    "cuckold": ["hubby", "husband", "married man", "wittol"],
    "cuckoldom": ["marriage", "matrimony", "spousal relationship", "union", "wedlock"],
    "cuckoldry": ["score", "sexual conquest"],
    "cuckoo": ["echo", "repeat"],
    "cuckoo clock": ["clock"],
    "cuckoo-bumblebee": ["bee"],
    "cuckoopint": ["aroid", "arum", "arum maculatum", "jack-in-the-pulpit", "lords-and-ladies"],
    "cuculidae": ["bird family", "family cuculidae"],
    "cuculiform bird": ["bird", "cuckoo", "touraco", "turaco", "turacou", "turakoo"],
    "cuculiformes": ["animal order", "order cuculiformes"],
    "cuculus": ["bird genus", "genus cuculus"],
    "cucumber": ["cucumber vine", "cucumis sativus", "melon", "melon vine"],
    "cucumber tree": ["magnolia", "magnolia acuminata"],
    "cucumber-shaped": [],
    "cucumis": ["dicot genus", "genus cucumis", "magnoliopsid genus"],
    "cucurbit": ["cucurbitaceae", "family cucurbitaceae", "gourd family"],
    "cucurbita": ["dicot genus", "genus cucurbita", "magnoliopsid genus"],
    "cucurbitaceae": ["cucurbit", "dicot family", "family cucurbitaceae", "gourd family", "magnoliopsid family"],
    "cucurbitaceous": [],
    "cud": ["feed", "provender", "rechewed food"],
    "cuddle": ["bosom", "embrace", "hug", "squeeze"],
    "cuddlesome": ["cuddly"],
    "cuddy": ["caboose", "cookhouse", "galley", "ship's galley"],
    "cudgel": ["fustigate", "hit"],
    "cudweed": ["chafeweed", "everlasting", "everlasting flower", "gnaphalium sylvaticum", "wood cudweed"],
    "cue": ["actor's line", "prompt", "prompting", "speech", "words"],
    "cue ball": ["billiard ball"],
    "cuff": ["slap", "whomp"],
    "cufflink": ["jewellery", "jewelry"],
    "cuirass": ["body armor", "body armour", "cataphract", "coat of mail", "suit of armor", "suit of armour"],
    "cuirassier": ["cavalryman", "trooper"],
    "cuisine": ["cookery", "cooking", "culinary art", "dim sum", "gastronomy", "haute cuisine", "nouvelle cuisine", "preparation", "rechauffe"],
    "cuisse": ["armor plate", "armor plating", "armour plate", "plate armor", "plate armour"],
    "cul": ["cul de sac", "dead end", "passage"],
    "culbertson": ["ely culbertson"],
    "culcita": ["fern genus", "genus culcita"],
    "culdoscope": ["endoscope"],
    "culdoscopy": ["endoscopy"],
    "culebra": [],
    "culex": ["arthropod genus", "genus culex"],
    "culex quinquefasciatus": ["culex fatigans", "mosquito"],
    "culiacan": [],
    "culicidae": ["arthropod family", "family culicidae"],
    "culinary": [],
    "cull": ["get rid of", "remove"],
    "cull out": ["choose", "pick out", "select", "take", "winnow"],
    "cullis": ["gutter", "trough"],
    "culm": ["stalk", "stem"],
    "culminate": ["accomplish", "achieve", "attain", "reach"],
    "culmination": ["celestial point"],
    "culotte": ["skirt"],
    "cult": ["faith", "macumba", "obeah", "obi", "organized religion", "rastafari", "rastafarian", "rastas", "religion", "voodoo", "wicca"],
    "cult of personality": ["fashion"],
    "cultism": ["devotion"],
    "cultist": ["follower"],
    "cultivar": ["tracheophyte", "variety", "vascular plant"],
    "cultivate": ["farm", "grow", "produce", "raise"],
    "cultivated": [],
    "cultivated land": ["fallow", "farmland", "ground", "land", "ploughland", "plowland", "soil", "tillage", "tilled land", "tilth"],
    "cultivated parsnip": ["parsnip", "pastinaca sativa"],
    "cultivated plant": ["tracheophyte", "vascular plant"],
    "cultivated rice": ["oryza sativa", "rice"],
    "cultivation": ["development", "growing", "growth", "maturation", "ontogenesis", "ontogeny"],
    "cultivator": ["farm machine", "harrow", "tiller"],
    "cultural": [],
    "cultural attache": ["attache"],
    "cultural movement": ["front", "humanism", "movement", "social movement"],
    "cultural revolution": ["great proletarian cultural revolution", "revolution"],
    "culturally": [],
    "culturati": ["clerisy", "intelligentsia"],
    "culture": ["grow"],
    "culture medium": ["agar", "food", "medium", "nutrient", "nutrient agar"],
    "culture shock": ["disorientation"],
    "culver's root": ["asterid dicot genus", "culver's physic", "culvers physic", "culvers root", "veronicastrum virginicum", "whorlywort"],
    "culverin": ["cannon"],
    "culvert": ["drain", "drainpipe", "waste pipe"],
    "cum laude": [],
    "cumana": [],
    "cumberland": ["butcher cumberland", "duke of cumberland", "william augustus"],
    "cumberland gap": [],
    "cumberland mountains": ["cumberland plateau"],
    "cumbersome": ["cumbrous"],
    "cumbria": [],
    "cumin": ["cuminum cyminum", "herb", "herbaceous plant"],
    "cuminum": ["genus cuminum", "rosid dicot genus"],
    "cummerbund": ["cincture", "girdle", "sash", "waistband", "waistcloth"],
    "cummings": ["e. e. cummings", "edward estlin cummings"],
    "cumulative preferred": ["cumulative preferred stock", "preference shares", "preferred shares", "preferred stock"],
    "cumulative vote": ["election"],
    "cumulatively": [],
    "cumuliform": [],
    "cumulonimbus": ["cloud", "cumulonimbus cloud", "thundercloud"],
    "cumulous": [],
    "cumulus": ["altocumulus", "altocumulus cloud", "cloud", "cumulus cloud", "thunderhead"],
    "cunaxa": ["battle of cunaxa"],
    "cuneate": ["wedge-shaped"],
    "cuneate leaf": ["simple leaf"],
    "cuneiform": ["babylonian", "script"],
    "cuniculus": ["genus cuniculus", "mammal genus"],
    "cunner": ["bergall", "tautogolabrus adspersus", "wrasse"],
    "cunnilingus": ["cunnilinctus", "head", "oral sex"],
    "cunning": ["artfulness"],
    "cunningham": ["merce cunningham"],
    "cunningly": ["cutely"],
    "cunoniaceae": ["cunonia family", "family cunoniaceae", "rosid dicot family"],
    "cunt": ["bitch", "disagreeable person", "unpleasant person"],
    "cuon": ["cyon", "genus cuon", "genus cyon", "mammal genus"],
    "cup": ["form", "shape"],
    "cup final": ["final"],
    "cup hook": ["hook"],
    "cup of tea": ["activity", "bag", "dish"],
    "cup tie": ["game"],
    "cupbearer": ["attendant", "attender", "tender"],
    "cupboard": ["airing cupboard", "broom closet", "closet", "safe", "storage space", "supply closet"],
    "cupboard love": ["benignity", "kindness"],
    "cupcake": ["cake"],
    "cupflower": ["herb", "herbaceous plant", "nierembergia", "nierembergia frutescens", "nierembergia repens", "nierembergia rivularis", "tall cupflower", "whitecup"],
    "cupid": ["amor"],
    "cupid's bow": ["curve", "curved shape"],
    "cuplike": [],
    "cupola": ["furnace"],
    "cuppa": ["cupper", "tea"],
    "cupping": ["bloodletting"],
    "cupressaceae": ["cypress family", "family cupressaceae", "gymnosperm family"],
    "cupressus": ["genus cupressus", "gymnosperm genus"],
    "cupric": ["cuprous"],
    "cuprite": ["mineral"],
    "cupronickel": ["copper-base alloy"],
    "cupular": ["cupulate"],
    "cupule": ["acorn cup", "cup"],
    "cuquenan": ["cuquenan falls", "kukenaam", "kukenaam falls"],
    "cur": ["caitiff", "coward"],
    "curability": ["characteristic", "curableness"],
    "curable": [],
    "curacao": [],
    "curacy": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "curandera": ["healer", "therapist"],
    "curandero": ["healer", "therapist"],
    "curassow": ["gallinacean", "gallinaceous bird"],
    "curate": ["clergyman", "man of the cloth", "minister", "minister of religion", "ministrant", "parson", "pastor", "rector", "reverend"]
}
