synonyms = {
    "monotheist": ["believer", "worshiper", "worshipper"],
    "monotheistic": [],
    "monothelitism": ["heresy", "theological doctrine", "unorthodoxy"],
    "monotone": ["musical note", "note", "tone"],
    "monotonic": ["monotone"],
    "monotonously": [],
    "monotony": ["humdrum", "sameness", "unvariedness"],
    "monotremata": ["animal order", "order monotremata"],
    "monotreme": ["anteater", "duck-billed platypus", "duckbill", "duckbilled platypus", "echidna", "egg-laying mammal", "ornithorhynchus anatinus", "platypus", "prototherian", "spiny anteater"],
    "monotropa": ["dilleniid dicot genus", "genus monotropa"],
    "monotropaceae": ["dilleniid dicot family", "family monotropaceae"],
    "monotype": ["taxon", "taxonomic category", "taxonomic group"],
    "monotypic": [],
    "monounsaturated": [],
    "monounsaturated fatty acid": ["elaidic acid", "oleic acid", "unsaturated fatty acid"],
    "monovalent": [],
    "monoxide": ["carbon monoxide", "carbon monoxide gas", "co", "oxide"],
    "monozygotic": [],
    "monroe": ["marilyn monroe", "norma jean baker"],
    "monroe doctrine": ["foreign policy"],
    "monrovia": ["capital of liberia", "liberian capital"],
    "mons": ["adipose tissue", "fat", "fatty tissue", "mons pubis", "mons veneris"],
    "monsieur": ["adult male", "man"],
    "monsignor": ["priest"],
    "monsoon": ["rainy season"],
    "monster": ["demon", "demoniac", "devil", "disagreeable person", "fiend", "ogre", "unpleasant person"],
    "monstera": ["ceriman", "liana", "monstera deliciosa"],
    "monstrance": ["ostensorium", "vessel"],
    "monstrosity": ["malformation", "miscreation"],
    "monstrous": [],
    "mont blanc": ["monte bianco"],
    "montagu": ["ashley montagu"],
    "montagu's harrier": ["circus pygargus", "harrier"],
    "montaigne": ["michel eyquem montaigne", "michel montaigne"],
    "montan wax": ["wax"],
    "montana": ["mt", "treasure state"],
    "montanan": ["american"],
    "montane": [],
    "monte": ["card game", "cards", "four-card monte", "three-card monte"],
    "monte carlo": [],
    "montego bay": [],
    "montenegro": ["crna gora"],
    "monterey": [],
    "monterey bay": [],
    "monterey cypress": ["cupressus macrocarpa", "cypress", "cypress tree"],
    "monterey pine": ["pine", "pine tree", "pinus radiata", "true pine"],
    "monterrey": [],
    "montespan": ["francoise-athenais de rochechouart", "marquise de montespan"],
    "montesquieu": ["baron de la brede et de montesquieu", "charles louis de secondat"],
    "montessori": ["maria montesorri"],
    "monteverdi": ["claudio monteverdi"],
    "montevideo": ["capital of uruguay"],
    "montez": ["lola montez", "marie dolores eliza rosanna gilbert"],
    "montezuma": ["tree"],
    "montezuma cypress": ["ahuehuete", "cypress", "mexican swamp cypress", "taxodium mucronatum", "tule tree"],
    "montezuma ii": [],
    "montezuma's revenge": ["diarrhea", "diarrhoea", "looseness", "looseness of the bowels"],
    "montfort": ["earl of leicester", "simon de montfort"],
    "montgolfier": ["jacques etienne montgolfier"],
    "montgomery": ["l. m. montgomery", "lucy maud montgomery"],
    "montgomery's tubercle": ["glandulae sebaceae", "sebaceous follicle", "sebaceous gland"],
    "month": ["anomalistic month", "lunar month", "lunation", "moon", "sidereal month", "solar month", "synodic month", "time unit", "unit of time"],
    "month by month": [],
    "month of sundays": ["age", "long time", "years"],
    "monthlong": [],
    "monthly": ["serial", "serial publication", "series"],
    "montia": ["caryophylloid dicot genus", "genus montia"],
    "montmartre": [],
    "montpelier": ["capital of vermont"],
    "montrachet": ["burgundy", "burgundy wine", "white wine"],
    "montreal": [],
    "montserrat": [],
    "montserratian": ["west indian"],
    "monument": ["land site", "market cross", "site"],
    "monumental": [],
    "monumentalize": ["commemorate", "immortalise", "immortalize", "memorialise", "memorialize", "monumentalise", "record"],
    "moo": ["emit", "let loose", "let out", "low", "utter"],
    "moo goo gai pan": ["dish"],
    "mooch": ["bum", "cadge", "freeload", "grub", "obtain", "sponge"],
    "moocher": ["beggar", "cadger", "mendicant", "mooch", "schnorrer", "scrounger", "shnorrer"],
    "mood": ["common mood", "declarative", "declarative mood", "fact mood", "grammatical relation", "imperative", "imperative form", "imperative mood", "indicative", "indicative mood", "interrogative", "interrogative mood", "jussive mood", "modality", "mode", "optative", "optative mood", "subjunctive", "subjunctive mood"],
    "moodily": [],
    "moodiness": ["distemper", "glumness", "ill humor", "ill humour", "moroseness", "sullenness"],
    "moody": ["helen newington wills", "helen wills", "helen wills moody"],
    "moon": ["idle", "laze", "moon around", "moon on", "slug", "stagnate"],
    "moon blindness": ["animal disease", "mooneye"],
    "moon carrot": ["herb", "herbaceous plant", "stone parsley"],
    "moon shell": ["moonshell", "seasnail"],
    "moon shot": ["rocket firing", "rocket launching"],
    "moon trefoil": ["medic", "medicago arborea", "medick", "trefoil"],
    "moon-faced": ["round-faced"],
    "moon-splashed": [],
    "moon-worship": ["selenolatry", "worship"],
    "moonbeam": ["beam", "beam of light", "irradiation", "light beam", "moon ray", "moon-ray", "ray", "ray of light", "shaft", "shaft of light"],
    "moonfish": ["atlantic moonfish", "carangid", "carangid fish", "dollarfish", "horse-head", "horsefish", "horsehead", "lookdown", "lookdown fish", "selene setapinnis", "selene vomer"],
    "moonflower": ["belle de nuit", "ipomoea alba", "morning glory"],
    "moonie": ["religious person"],
    "moonless": [],
    "moonlight": ["do work", "work"],
    "moonlighter": ["worker"],
    "moonlike": ["moon-round"],
    "moonlit": ["moony"],
    "moonseed": ["canada moonseed", "carolina moonseed", "cocculus carolinus", "common moonseed", "menispermum canadense", "vine", "yellow parilla"],
    "moonshine": ["distil", "distill", "extract"],
    "moonstone": ["feldspar", "felspar", "transparent gem"],
    "moonwalk": ["dance step", "step"],
    "moonwort": ["botrychium lunaria", "common moonwort", "grape fern"],
    "moor": ["berth", "fasten", "fix", "secure", "tie up", "wharf"],
    "moorage": ["fee"],
    "moorcock": ["lagopus scoticus", "moor-bird", "moorbird", "moorfowl", "moorgame", "red grouse"],
    "moore": ["douglas moore"],
    "moorhen": ["gallinula chloropus", "gallinule", "marsh hen", "swamphen", "water hen"],
    "mooring": ["anchorage", "anchorage ground", "berth", "moorage", "slip"],
    "mooring anchor": ["anchor", "ground tackle"],
    "mooring tower": ["mooring mast", "tower"],
    "moorish": ["architectural style", "moorish architecture", "style of architecture", "type of architecture"],
    "moorish arch": ["horseshoe arch", "round arch"],
    "moosewood": ["acer pennsylvanicum", "goosefoot maple", "maple", "moose-wood", "striped dogwood", "striped maple"],
    "moot": ["case", "causa", "cause", "lawsuit", "suit"],
    "moot court": ["court", "judicature", "tribunal"],
    "mop handle": ["grip", "handgrip", "handle", "hold"],
    "mop-headed": [],
    "mope": ["mope around", "move"],
    "moped": ["minibike", "motorbike"],
    "mopper": ["worker"],
    "moppet": ["female child", "girl", "little girl"],
    "moquelumnan": ["miwok", "penutian"],
    "moquette": ["cloth", "fabric", "material", "textile"],
    "moraceae": ["dicot family", "family moraceae", "magnoliopsid family", "mulberry family"],
    "moraceous": [],
    "moraine": ["earth", "ground"],
    "moral": ["import", "lesson", "meaning", "significance", "signification"],
    "moral certainty": ["certainty", "foregone conclusion", "sure thing"],
    "moral force": ["dynamic", "incentive", "inducement", "motivator"],
    "moral hazard": ["endangerment", "hazard", "jeopardy", "peril", "risk"],
    "moral obligation": ["duty", "obligation", "responsibility"],
    "moral principle": ["categorical imperative", "precept", "principle"],
    "morale": ["mental condition", "mental state", "psychological condition", "psychological state"],
    "morale builder": ["influence"],
    "morale building": ["boost", "encouragement", "morale booster"],
    "moralism": ["axiom", "maxim"],
    "moralist": ["egalitarian", "elitist", "equalitarian", "philosopher", "utilitarian"],
    "moralistic": [],
    "morality": ["chastity", "conscience", "good", "goodness", "quality", "righteousness", "rightness", "sexual morality", "virtue"],
    "morality play": ["drama", "dramatic play", "play"],
    "moralization": ["moralisation", "reform"],
    "moralize": ["interpret", "moralise", "rede"],
    "moralizing": ["moralisation", "moralization", "philosophizing", "preachification"],
    "morally": ["virtuously"],
    "moranzanist patriotic front": [],
    "moratorium": ["delay", "hold", "postponement", "time lag", "wait"],
    "moravia": [],
    "moravian": [],
    "moray": ["eel", "moray eel"],
    "moray firth": [],
    "morbid": [],
    "morbidity": ["incidence", "relative incidence"],
    "morbidly": [],
    "morbilliform": [],
    "morceau": ["composition", "musical composition", "opus", "piece", "piece of music"],
    "morchella": ["fungus genus", "genus morchella"],
    "morchella crassipes": ["morel", "thick-footed morel"],
    "morchella semilibera": ["cow's head", "half-free morel", "morel"],
    "morchellaceae": ["family morchellaceae", "fungus family"],
    "mordacious": [],
    "mordaciously": [],
    "mordacity": ["disposition"],
    "mordant": ["antimony potassium tartrate", "chrome alum", "color", "coloring material", "colour", "colouring material", "sodium bichromate", "sodium dichromate", "tartar emetic"],
    "mordva": ["mordvin", "mordvinian", "russian"],
    "more": ["sir thomas more", "thomas more"],
    "moreau river": [],
    "moreen": ["cloth", "fabric", "material", "textile"],
    "morel": ["bell morel", "black morel", "common morel", "conic morel", "cow's head", "cup morel", "disciotis venosa", "half-free morel", "morchella angusticeps", "morchella conica", "morchella crassipes", "morchella esculenta", "morchella semilibera", "mushroom", "narrowhead morel", "sponge morel", "sponge mushroom", "thick-footed morel", "verpa"],
    "morello": ["prunus cerasus", "prunus cerasus austera", "sour cherry", "sour cherry tree"],
    "mores": ["convention", "formula", "normal", "pattern", "rule"],
    "moreton bay": [],
    "moreton bay chestnut": ["australian chestnut", "bean tree"],
    "moreton bay tulipwood": ["harpullia", "harpullia pendula"],
    "morgan": ["lewis henry morgan"],
    "morgan city": [],
    "morgan le fay": ["faerie", "faery", "fairy", "fay", "sprite"],
    "morganatic": ["left-handed"],
    "morganite": ["beryl", "transparent gem"],
    "morgantown": [],
    "morgen": ["area unit", "square measure"],
    "morgue": ["building", "crematorium", "crematory", "dead room", "edifice", "funeral chapel", "funeral church", "funeral home", "funeral parlor", "funeral parlour", "funeral-residence", "mortuary"],
    "moribund": [],
    "morion": ["cabasset", "helmet"],
    "morlett's crocodile": ["crocodile"],
    "morley": ["e. w. morley", "edward morley", "edward williams morley"],
    "mormon": [],
    "mormon cricket": ["anabrus simplex", "katydid"],
    "mormonism": ["protestantism"],
    "mornay sauce": ["cheese sauce"],
    "morning": ["forenoon", "morn", "morning time", "period", "period of time", "time period"],
    "morning dress": ["attire", "dress", "garb"],
    "morning glory": ["beach morning glory", "belle de nuit", "common morning glory", "cypress vine", "imperial japanese morning glory", "indian pink", "ipomoea alba", "ipomoea batatas", "ipomoea coccinea", "ipomoea fastigiata", "ipomoea imperialis", "ipomoea leptophylla", "ipomoea nil", "ipomoea orizabensis", "ipomoea panurata", "ipomoea pes-caprae", "ipomoea purpurea", "ipomoea quamoclit", "ipomoea tricolor", "japanese morning glory", "man-of-the-earth", "manroot", "moonflower", "quamoclit pennata", "railroad vine", "red morning-glory", "scammony", "scammonyroot", "star ipomoea", "star-glory", "sweet potato", "sweet potato vine", "vine", "wild potato vine", "wild sweet potato vine"],
    "morning room": ["front room", "living room", "living-room", "parlor", "parlour", "sitting room"],
    "morning sickness": ["nausea", "sickness"],
    "morning star": ["daystar", "lucifer", "major planet", "phosphorus", "planet"],
    "morning-after pill": ["birth control device", "contraceptive", "contraceptive device", "preventative", "preventive", "prophylactic device"],
    "moro": ["filipino"],
    "moro islamic liberation front": [],
    "moroccan": ["african"],
    "moroccan dirham": ["dirham", "moroccan monetary unit"],
    "moroccan monetary unit": ["dirham", "monetary unit", "moroccan dirham"],
    "morocco": ["leather", "levant", "levant morocco"],
    "moron": [],
    "morone": ["fish genus", "genus morone"],
    "moronic": [],
    "moronity": ["backwardness", "mental deficiency", "mental retardation", "retardation", "slowness", "subnormality"],
    "morosely": [],
    "moroseness": ["glumness", "moodiness", "sullenness"],
    "morosoph": ["fool", "muggins", "sap", "saphead", "tomfool"],
    "morph": ["alter", "change", "modify"],
    "morphallaxis": ["regeneration"],
    "morphea": ["dermatosclerosis", "scleroderma"],
    "morpheme": ["allomorph", "bound form", "bound morpheme", "classifier", "ending", "free form", "free morpheme", "language unit", "linguistic unit", "termination"],
    "morphemic": [],
    "morpheus": [],
    "morphine": ["analgesic", "anodyne", "apomorphine", "morphia", "opiate", "pain pill", "painkiller"],
    "morphogenesis": ["development", "growing", "growth", "maturation", "ontogenesis", "ontogeny"],
    "morphologic": ["morphological"],
    "morphological rule": ["linguistic rule", "rule", "rule of morphology"],
    "morphologically": [],
    "morphology": ["accidence", "compound morphology", "derivational morphology", "grammar", "inflectional morphology"],
    "morphophoneme": ["allomorph"],
    "morphophonemic": [],
    "morphophonemic system": ["language system"],
    "morphophonemics": ["descriptive linguistics"],
    "morrigan": ["morrigu"],
    "morris": ["esther hobart mcquigg slack morris", "esther morris"],
    "morris chair": ["armchair"],
    "morris dance": ["folk dance", "folk dancing", "morris dancing"],
    "morris dancer": ["folk dancer"],
    "morrison": ["james douglas morrison", "jim morrison"],
    "morristown": [],
    "morrow": ["24-hour interval", "day", "mean solar day", "solar day", "twenty-four hour period", "twenty-four hours"],
    "morrow's honeysuckle": ["honeysuckle", "lonicera morrowii"],
    "mors": [],
    "morse": ["samuel f. b. morse", "samuel finley breese morse", "samuel morse"],
    "morsel": ["small indefinite amount", "small indefinite quantity"],
    "mortal": [],
    "mortal enemy": ["enemy", "foe"],
    "mortal sin": ["acedia", "anger", "avarice", "avaritia", "covetousness", "deadly sin", "envy", "gluttony", "greed", "gula", "invidia", "ira", "ire", "laziness", "lust", "luxuria", "overeating", "pride", "rapacity", "sin", "sinning", "sloth", "superbia", "wrath"],
    "mortality": ["impermanence", "impermanency"],
    "mortality table": ["actuarial table", "statistical table"],
    "mortally": [],
    "mortar": ["daub", "plaster"],
    "mortar fire": ["artillery fire", "cannon fire"],
    "mortarboard": ["board", "hawk"],
    "mortgage": ["bond", "owe"],
    "mortgage application": ["loan application"],
    "mortgage deed": ["deed", "deed of conveyance", "title"],
    "mortgage-backed security": ["certificate", "security"],
    "mortgaged": [],
    "mortgagee": ["creditor", "holder", "mortgage holder"],
    "mortgagor": ["debitor", "debtor", "mortgager"],
    "mortice": ["bring together", "join", "mortise"],
    "mortician": ["embalmer", "funeral director", "funeral undertaker", "skilled worker", "skilled workman", "trained worker", "undertaker"],
    "mortification": ["self-control", "self-denial", "self-discipline"],
    "mortify": ["check", "condition", "crucify", "discipline", "mortify", "subdue", "train"],
    "mortimer": ["roger de mortimer"],
    "mortise": ["cut", "mortice"],
    "mortise joint": ["dovetail", "dovetail joint", "joint", "mortise-and-tenon joint", "tongue and groove joint"],
    "mortmain": ["dead hand", "immovable", "real estate", "real property", "realty"],
    "morton": ["ferdinand joseph la menthe morton", "jelly roll morton"],
    "mortuary": [],
    "morula": ["conceptus", "embryo", "fertilized egg"],
    "morus": ["dicot genus", "genus morus", "magnoliopsid genus"],
    "mosaic": ["plant disease", "potato mosaic", "tobacco mosaic"],
    "mosaic culture": ["culture"],
    "mosaic gold": ["pigment", "stannic sulfide"],
    "mosaic law": ["jurisprudence", "law", "law of moses"],
    "mosaicism": ["condition"],
    "mosan": ["american indian", "american-indian language", "amerind", "amerindian language", "chemakuan", "indian", "salish", "salishan", "wakashan", "wakashan language"],
    "mosander": ["carl gustaf mossander"],
    "moschus": ["genus moschus", "mammal genus"],
    "moscow": ["capital of the russian federation", "russian capital"],
    "moselle": ["white wine"],
    "moses": ["anna mary robertson moses", "grandma moses"],
    "moshav": ["settlement", "small town", "village"],
    "mosque": ["house of god", "house of prayer", "house of worship", "place of worship"],
    "mosquito": ["aedes aegypti", "aedes albopictus", "anopheline", "asian tiger mosquito", "common mosquito", "culex fatigans", "culex pipiens", "culex quinquefasciatus", "dipteran", "dipteron", "dipterous insect", "gnat", "malaria mosquito", "malarial mosquito", "two-winged insects", "yellow-fever mosquito"],
    "mosquito bite": ["bite", "insect bite", "sting"],
    "mosquito fern": ["aquatic fern", "azolla caroliniana", "carolina pond fern", "floating fern", "water fern"],
    "mosquito net": ["screen"],
    "mosquitofish": ["gambusia affinis", "live-bearer", "poeciliid", "poeciliid fish", "topminnow"],
    "moss": ["acrocarp", "acrocarpous moss", "bog moss", "bryophyte", "nonvascular plant", "peat moss", "pleurocarp", "pleurocarpous moss", "sphagnum", "sphagnum moss"],
    "moss agate": ["agate"],
    "moss campion": ["campion", "catchfly", "silene", "silene acaulis"],
    "moss family": ["anthocerotaceae", "bryaceae", "dicranaceae", "family", "family anthocerotaceae", "family bryaceae", "family dicranaceae", "family jungermanniaceae", "family marchantiaceae", "family mniaceae", "family sphaerocarpaceae", "jungermanniaceae", "marchantiaceae", "mniaceae", "sphaerocarpaceae"],
    "moss genus": ["andreaea", "anthoceros", "bryum", "dicranum", "genus", "genus andreaea", "genus anthoceros", "genus bryum", "genus dicranum", "genus marchantia", "genus mnium", "genus sphaerocarpos", "genus sphaerocarpus", "genus sphagnum", "marchantia", "mnium", "sphaerocarpos", "sphaerocarpus"],
    "moss green": ["mosstone"],
    "moss pink": ["dwarf phlox", "moss phlox", "mountain phlox", "phlox", "phlox subulata"],
    "moss-grown": ["mossy"],
    "moss-trooper": ["marauder", "piranha", "predator", "vulture"],
    "mossad": ["international intelligence agency"],
    "mossback": ["conservative", "conservativist"],
    "mossbauer": ["rudolf ludwig mossbauer"],
    "mossy saxifrage": ["breakstone", "rockfoil", "saxifraga hypnoides", "saxifrage"],
    "most": [],
    "most valuable player": ["mvp", "participant", "player"],
    "most-favored-nation": [],
    "most-valuable": [],
    "mostaccioli": ["alimentary paste", "pasta"],
    "mosul": [],
    "mot": ["ministry of transportation test", "mot test", "run", "test", "trial"],
    "mot juste": ["choice of words", "diction", "phraseology", "phrasing", "verbiage", "wording"],
    "motacilla": ["bird genus", "genus motacilla"],
    "motacillidae": ["bird family", "family motacillidae"],
    "motel": ["court", "motor hotel", "motor inn", "motor lodge", "tourist court"],
    "motel room": ["bedchamber", "bedroom", "chamber", "sleeping accommodation", "sleeping room"],
    "motet": ["composition", "musical composition", "opus", "piece", "piece of music"],
    "moth": ["arctiid", "arctiid moth", "bombycid", "bombycid moth", "gelechiid", "gelechiid moth", "geometrid", "geometrid moth", "hawk moth", "hawkmoth", "hummingbird moth", "lasiocampid", "lasiocampid moth", "lepidopteran", "lepidopteron", "lepidopterous insect", "lymantriid", "malacosoma americana", "miller", "moth miller", "noctuid", "noctuid moth", "owlet moth", "pyralid", "pyralid moth", "saturniid", "saturniid moth", "silkworm moth", "sphingid", "sphinx moth", "tent-caterpillar moth", "tineoid", "tineoid moth", "tortricid", "tortricid moth", "tussock moth"],
    "moth bean": ["legume", "leguminous plant", "phaseolus aconitifolius", "vigna aconitifolia"],
    "moth miller": ["miller", "moth"],
    "moth mullein": ["flannel leaf", "mullein", "velvet plant", "verbascum blattaria"],
    "moth orchid": ["butterfly plant", "moth plant", "orchid", "orchidaceous plant", "phalaenopsis amabilis"],
    "moth-eaten": ["ratty", "shabby", "tatty"],
    "mothball": ["store"],
    "mother": ["care", "fuss", "give care", "overprotect"],
    "mother carey's chicken": ["mother carey's hen", "oceanites oceanicus", "storm petrel"],
    "mother cell": ["cell", "spore mother cell"],
    "mother figure": ["adult female", "woman"],
    "mother goose": [],
    "mother hen": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "mother hubbard": ["dress", "frock", "muumuu"],
    "mother lode": ["champion lode", "load", "lode"],
    "mother tongue": ["first language", "maternal language", "natural language", "tongue"],
    "mother's boy": ["boy", "mama's boy", "mamma's boy", "son"],
    "mother's daughter": ["daughter", "girl"],
    "mother's day": ["day"],
    "mother's milk": ["milk"],
    "mother's son": ["male", "male person"],
    "mother-in-law": ["female parent", "in-law", "mother", "relative-in-law"],
    "mother-in-law's tongue": ["bowstring hemp", "sansevieria", "sansevieria trifasciata", "snake plant"],
    "mother-naked": ["in one's birthday suit", "in your birthday suit", "naked as the day one was born", "naked as the day you were born"],
    "mother-of-pearl": ["nacre", "shell"],
    "motherhood": ["family relationship", "kinship", "maternity", "relationship"],
    "motherless": [],
    "motherlike": [],
    "motherliness": ["maternal quality", "maternalism", "maternity", "parental quality"],
    "motherly": [],
    "motherwell": ["robert motherwell"],
    "motherwort": ["herb", "herbaceous plant", "leonurus cardiaca"],
    "mothproof": ["protect"],
    "mothy": [],
    "motif": ["idea", "melodic theme", "motive", "musical theme", "obbligato", "obligato", "theme"],
    "motile": ["beholder", "observer", "perceiver", "percipient"],
    "motilin": ["gastrointestinal hormone", "gi hormones"],
    "motility": ["mobility"],
    "motion": ["flow", "palpitation", "perpetual motion", "precession", "quiver", "quivering", "shakiness", "shaking", "state", "stream", "trembling", "vibration"],
    "motion sickness": ["ailment", "air sickness", "airsickness", "car sickness", "complaint", "ill", "kinetosis", "mal de mer", "naupathia", "nausea", "seasickness", "sickness"],
    "motion-picture camera": ["camera", "cine-camera", "movie camera", "photographic camera", "sound camera"],
    "motion-picture film": ["cine-film", "film", "movie film", "photographic film", "sound film"],
    "motional": [],
    "motionlessly": [],
    "motionlessness": ["fixedness", "immobility", "lifelessness", "state", "stationariness", "stillness"],
    "motivate": ["actuate", "cause", "do", "incite", "make", "move", "prompt", "propel"],
    "motivated": [],
    "motivation": ["condition", "status"],
    "motivational": [],
    "motivative": ["motivating", "motive"],
    "motive": ["motor"],
    "motiveless": ["unprovoked", "wanton"],
    "motley": ["color", "color in", "colorise", "colorize", "colour", "colour in", "colourise", "colourize", "parti-color"],
    "motmot": ["coraciiform bird", "momot"],
    "motor": ["agent"],
    "motor aphasia": ["aphasia", "ataxic aphasia", "broca's aphasia", "expressive aphasia", "nonfluent aphasia"],
    "motor area": ["cortical area", "cortical region", "excitable area", "motor cortex", "motor region", "rolando's area"],
    "motor control": ["control"],
    "motor fiber": ["efferent fiber", "nerve fiber", "nerve fibre"],
    "motor hotel": ["court", "hotel", "motel", "motor inn", "motor lodge", "tourist court"],
    "motor memory": ["long-term memory", "ltm", "muscle memory"],
    "motor nerve": ["anterior horn", "anterior root", "corticospinal tract", "efferent", "efferent nerve", "nerve", "nervus", "pyramidal motor system", "pyramidal tract", "ventral horn", "ventral root"],
    "motor neuron": ["efferent neuron", "motoneuron", "motor nerve fiber", "nerve cell", "neuron"],
    "motor oil": ["lube", "lubricant", "lubricating substance", "lubricator", "oil"],
    "motor pool": ["fleet"],
    "motor scooter": ["scooter", "wheeled vehicle"],
    "motor vehicle": ["4wd", "amphibian", "amphibious vehicle", "auto", "automobile", "automotive vehicle", "bike", "bloodmobile", "car", "doodlebug", "four-wheel drive", "go-kart", "golf cart", "golfcart", "hearse", "machine", "motorcar", "motorcycle", "motortruck", "self-propelled vehicle", "snowplough", "snowplow", "truck"],
    "motor-assisted": [],
    "motorbike": ["cycle", "motorcycle", "ride"],
    "motorboat": ["boat"],
    "motorcade": ["procession"],
    "motorcycle": ["automotive vehicle", "bike", "dirt bike", "minibike", "motor vehicle", "motorbike", "scrambler", "trail bike"],
    "motorcycle cop": ["motorcycle policeman", "officer", "police officer", "policeman", "speed cop"],
    "motorcycling": ["cycling"],
    "motorcyclist": ["traveler", "traveller"],
    "motoring": ["driving"],
    "motorist": ["automobilist", "driver"],
    "motorization": ["effectuation", "implementation", "motorisation"],
    "motorize": ["equip", "fit", "fit out", "outfit"],
    "motorized": ["motored", "motorised"],
    "motorized wheelchair": ["wheelchair"],
    "motorman": ["manipulator", "operator"],
    "motormouth": ["speaker", "talker", "utterer", "verbaliser", "verbalizer"],
    "mott": ["lucretia coffin mott"],
    "mottle": ["blotch", "color", "color in", "colorise", "colorize", "colour", "colour in", "colourise", "colourize", "streak"],
    "mottling": ["marking"],
    "motto": ["battle cry", "catch phrase", "catchphrase", "catchword", "cry", "expression", "locution", "mantra", "rallying cry", "saying", "shibboleth", "slogan", "war cry", "watchword"],
    "mouflon": ["moufflon", "mountain sheep", "ovis musimon"],
    "moulmein": ["mawlamyine"],
    "mound": ["forge", "form", "mold", "mould", "mound over", "shape", "work"],
    "mound builder": ["primitive", "primitive person"],
    "mound over": ["mound"],
    "mounded over": [],
    "mount": ["devise", "get up", "machinate", "organise", "organize", "prepare", "put on", "rerun"],
    "mount bartle frere": [],
    "mount carmel": [],
    "mount elbert": [],
    "mount ranier national park": [],
    "mount saint helens": ["mount st. helens", "mt. st. helens"],
    "mount vernon": [],
    "mountain": ["alp", "ben", "elevation", "mount", "natural elevation", "seamount", "volcano"],
    "mountain ash": ["american mountain ash", "angiospermous tree", "european mountain ash", "flowering tree", "rowan", "rowan tree", "service tree", "sorb apple", "sorb apple tree", "sorbus americana", "sorbus aucuparia", "sorbus domestica", "sorbus sitchensis", "western mountain ash"],
    "mountain avens": ["dryas octopetala", "subshrub", "suffrutex"],
    "mountain beaver": ["aplodontia rufa", "gnawer", "rodent", "sewellel"],
    "mountain bike": ["all-terrain bike", "bicycle", "bike", "cycle", "off-roader", "wheel"],
    "mountain bladder fern": ["bladder fern", "cystopteris montana"],
    "mountain chinchilla": ["gnawer", "mountain viscacha", "rodent"],
    "mountain climbing": ["alpinism", "climb", "mount", "mountaineering"],
    "mountain devil": ["moloch", "moloch horridus", "spiny lizard"],
    "mountain ebony": ["angiospermous tree", "bauhinia variegata", "flowering tree", "orchid tree"],
    "mountain everlasting": ["antennaria dioica", "cat's feet", "cat's foot", "pussytoes"],
    "mountain fern": ["dryopteris oreopteris", "fern", "oreopteris limbosperma"],
    "mountain four o'clock": ["four o'clock", "mirabilis oblongifolia"],
    "mountain goat": ["goat antelope", "oreamnos americanus", "rocky mountain goat"],
    "mountain gorilla": ["gorilla", "gorilla gorilla", "gorilla gorilla beringei"],
    "mountain heath": ["bryanthus taxifolius", "heath", "phyllodoce caerulea"],
    "mountain hemlock": ["black hemlock", "hemlock", "hemlock tree", "tsuga mertensiana"],
    "mountain hollyhock": ["iliamna acerifolia", "iliamna ruvularis", "mallow"],
    "mountain lady's slipper": ["cypripedium montanum", "ladies' slipper", "lady's slipper", "lady-slipper", "slipper orchid"],
    "mountain laurel": ["american laurel", "calico bush", "kalmia", "kalmia latifolia", "wood laurel"],
    "mountain lily": ["lilium auratum", "lily"],
    "mountain male fern": ["dryopteris oreades", "wood fern", "wood-fern", "woodfern"],
    "mountain maple": ["acer spicatum", "maple", "mountain alder"],
    "mountain mint": ["basil mint", "herb", "herbaceous plant", "pycnanthemum virginianum"],
    "mountain nyala": ["antelope", "tragelaphus buxtoni"],
    "mountain paca": ["gnawer", "rodent"],
    "mountain peak": ["crest", "crown", "peak", "summit", "tip", "top"],
    "mountain pride": ["penstemon newberryi", "wild flower", "wildflower"],
    "mountain quail": ["mountain partridge", "oreortyx picta palmeri", "partridge"],
    "mountain rice": ["indian millet", "oryzopsis hymenoides", "rice grass", "ricegrass", "silk grass", "silkgrass"],
    "mountain rimu": ["bush", "dacridium laxifolius", "lepidothamnus laxifolius", "shrub"],
    "mountain rose": ["rosa pendulina", "rose", "rosebush"],
    "mountain sandwort": ["arenaria groenlandica", "mountain daisy", "mountain starwort", "sandwort"],
    "mountain sheep": ["bighorn", "bighorn sheep", "cimarron", "moufflon", "mouflon", "ovis canadensis", "ovis musimon", "rocky mountain bighorn", "rocky mountain sheep", "wild sheep"],
    "mountain sickness": ["altitude sickness"],
    "mountain skink": ["eumeces callicephalus", "scincid", "scincid lizard", "skink"],
    "mountain spleenwort": ["asplenium montanum", "spleenwort"],
    "mountain swamp gum": ["eucalypt", "eucalyptus", "eucalyptus camphora", "eucalyptus tree"],
    "mountain tent": ["collapsible shelter", "tent"],
    "mountain time": ["civil time", "local time", "mountain standard time", "mst", "standard time"],
    "mountain trail": ["trail"],
    "mountain zebra": ["equus zebra zebra", "zebra"],
    "mountaineer": ["climb", "climb up", "go up", "mount"],
    "mountainous": [],
    "mountainside": ["incline", "side", "slope", "versant"],
    "mountebank": ["beguiler", "charlatan", "cheat", "cheater", "craniologist", "deceiver", "phrenologist", "quack", "slicker", "trickster"],
    "mounted": [],
    "mounter": ["skilled worker", "skilled workman", "trained worker"],
    "mountie": ["officer", "police officer", "policeman"],
    "mounting": ["chassis", "framework", "mat", "matting", "mount", "passe-partout", "setting"],
    "mourn": ["celebrate", "keep", "observe"],
    "mourner": ["bearer", "griever", "lamenter", "pallbearer", "sorrower", "unfortunate", "unfortunate person", "wailer", "weeper"],
    "mournful": ["plaintive"],
    "mournfully": [],
    "mournfulness": ["plaintiveness", "ruthfulness", "sorrow", "sorrowfulness", "woe", "woefulness"],
    "mourning": ["bereavement", "sadness", "sorrow", "sorrowfulness"],
    "mourning cloak": ["brush-footed butterfly", "camberwell beauty", "four-footed butterfly", "mourning cloak butterfly", "nymphalid", "nymphalid butterfly", "nymphalis antiopa"],
    "mourning dove": ["dove", "zenaidura macroura"],
    "mourning ring": ["band", "ring"],
    "mouse": ["manipulate"],
    "mouse button": ["button", "push", "push button"],
    "mouse nest": ["mouse's nest", "nest"],
    "mouse-ear chickweed": ["alpine mouse-ear", "arctic mouse-ear", "cerastium alpinum", "cerastium arvense", "cerastium tomentosum", "chickweed", "clammy chickweed", "field chickweed", "field mouse-ear", "herb", "herbaceous plant", "love-in-a-mist", "mouse ear", "mouse eared chickweed", "snow-in-summer"],
    "mouse-ear hawkweed": ["hawkweed", "hieracium pilocella", "pilosella officinarum"],
    "mouse-eared": [],
    "mouse-eared bat": ["carnivorous bat", "microbat"],
    "mouse-sized": [],
    "mouse-tooth forceps": ["forceps"],
    "mousepad": ["mat", "mouse mat"],
    "mouser": ["domestic cat", "felis catus", "felis domesticus", "house cat"],
    "mousetrap": ["trap"],
    "moussaka": ["dish"],
    "mousse": ["gel", "groom", "neaten"],
    "mousseline de sole": ["cloth", "fabric", "material", "textile"],
    "mousy": ["mousey"],
    "mouth": ["touch"],
    "mouth hole": ["hole"],
    "mouth-watering": ["savory", "savoury"],
    "mouthbreeder": ["fish"],
    "mouthful": ["containerful"],
    "mouthlike": [],
    "mouthpart": ["appendage", "extremity", "member"],
    "mouthpiece": ["interpreter", "mouth", "representative", "spokesperson", "voice"],
    "mouton": ["meat", "mutton"],
    "movability": ["looseness", "mobility", "movableness", "play", "portability", "ricketiness", "unsteadiness"],
    "movable": [],
    "movable barrier": ["barrier", "chicane", "door", "gate", "hatch"],
    "movable feast": ["easter", "feast day", "feast of the unleavened bread", "fete day", "moveable feast", "passover", "pesach", "pesah"],
    "move": ["live"],
    "move back and forth": ["flicker", "flitter", "flutter", "move", "quiver", "rock", "shake", "sway", "swing", "waver"],
    "move in": ["lodge in", "occupy", "reside"],
    "move in on": ["take charge", "take control", "take hold"],
    "move involuntarily": ["didder", "jerk", "move", "move reflexively", "shake", "shiver", "shudder", "twitch"],
    "move out": ["clear out", "move"],
    "move over": ["ease up", "give", "give way", "move", "yield"],
    "moved": ["affected", "stirred", "touched"],
    "movement": ["art movement", "artistic movement", "boy scouts", "civil rights movement", "common front", "cultural movement", "ecumenism", "falun gong", "fighting french", "free french", "front", "oecumenism", "political movement", "reform movement", "religious movement", "social group", "social movement", "zionism", "zionist movement"],
    "mover": ["remover", "working man", "working person", "workingman", "workman"],
    "movie": ["3-d", "3d", "cinema verite", "collage film", "coming attraction", "docudrama", "documentary", "documentary film", "feature", "feature film", "film", "film noir", "final cut", "flick", "home movie", "infotainment", "motion picture", "motion-picture show", "moving picture", "moving-picture show", "musical", "musical comedy", "musical theater", "pic", "picture", "picture show", "product", "production", "rough cut", "shoot-'em-up", "short subject", "show", "silent movie", "silent picture", "silents", "skin flick", "slow motion", "talkie", "talking picture", "telefilm", "three-d"],
    "movie projector": ["bioscope", "cine projector", "film projector", "projector"],
    "moviegoer": ["looker", "motion-picture fan", "spectator", "viewer", "watcher", "witness"],
    "moviemaking": ["devising", "fashioning", "film making", "making", "movie making"],
    "moving": [],
    "moving expense": ["disbursal", "disbursement", "expense"],
    "moving van": ["pantechnicon", "van"],
    "moving-coil galvanometer": ["ballistic galvanometer", "galvanometer"],
    "movingly": [],
    "mow": ["cut", "cut down", "scythe"],
    "mown": ["cut"],
    "moynihan": ["daniel patrick moynihan"],
    "mozambican": ["african"],
    "mozambique": ["mocambique", "republic of mozambique"],
    "mozambique channel": [],
    "mozambique monetary unit": ["metical", "monetary unit"],
    "mozart": ["wolfgang amadeus mozart"],
    "mozartian": ["mozartean"],
    "mozzarella": ["cheese"],
    "mpeg": ["compression"],
    "mr": ["mr. moto"],
    "mrs": ["form of address", "mrs.", "title", "title of respect"],
    "ms": ["form of address", "ms.", "title", "title of respect"],
    "ms-dos": ["microsoft disk operating system"],
    "msasa": ["brachystegia speciformis", "tree"],
    "mu": ["alphabetic character", "letter", "letter of the alphabet"],
    "mubarak": ["hosni mubarak"],
    "much": ["large indefinite amount", "large indefinite quantity"],
    "much as": ["very much like"],
    "muchness": ["magnitude"],
    "mucic acid": ["carboxylic acid"],
    "muciferous": [],
    "mucilage": ["gum"],
    "mucin": ["glycoprotein"],
    "mucinoid": [],
    "mucinous": [],
    "muck": ["remove", "take", "take away", "withdraw"],
    "muckrake": ["break", "bring out", "disclose", "discover", "divulge", "expose", "give away", "let on", "let out", "reveal", "unwrap"],
    "muckraker": ["depreciator", "detractor", "disparager", "knocker", "mudslinger"],
    "muckraking": ["exposure"],
    "mucky": ["muddy"],
    "mucocutaneous": [],
    "mucocutaneous leishmaniasis": ["american leishmaniasis", "kala azar", "leishmaniasis", "leishmaniasis americana", "leishmaniosis", "nasopharyngeal leishmaniasis", "new world leishmaniasis"],
    "mucoid": ["glycoprotein"],
    "mucopolysaccharide": ["hyaluronic acid", "polyose", "polysaccharide"],
    "mucopolysaccharidosis": ["congenital disease", "dysostosis multiplex", "gargoylism", "genetic abnormality", "genetic defect", "genetic disease", "genetic disorder", "hereditary condition", "hereditary disease", "hurler's disease", "hurler's syndrome", "inherited disease", "inherited disorder", "lipochondrodystrophy"],
    "mucopurulent": [],
    "mucor": ["mold", "mould"],
    "mucoraceae": ["family mucoraceae", "fungus family"],
    "mucorales": ["fungus order", "order mucorales"],
    "mucosal": [],
    "mucous": ["mucose"],
    "mucous membrane": ["conjunctiva", "endometrium", "hymen", "maidenhead", "membrane", "mucosa", "tissue layer", "virginal membrane"],
    "mucuna": ["bengal bean", "benghal bean", "bush", "cowage", "florida bean", "mucuna aterrima", "mucuna deeringiana", "mucuna pruriens utilis", "shrub", "stizolobium deeringiana", "velvet bean"],
    "mucus": ["booger", "leucorrhea", "leukorrhea", "mucous secretion", "phlegm", "secretion", "snot", "sputum"],
    "mud": ["daub", "plaster"],
    "mud bath": ["bath"],
    "mud brick": ["brick"],
    "mud dauber": ["sphecoid", "sphecoid wasp"],
    "mud flat": ["parcel", "parcel of land", "piece of ground", "piece of land", "tract"],
    "mud midget": ["bogmat", "duckweed", "wolffiella gladiata"],
    "mud pie": ["clay", "mud"],
    "mud puddle": ["pool", "puddle", "wallow"],
    "mud puppy": ["necturus maculosus", "salamander"],
    "mud stain": ["discoloration", "discolouration", "stain"],
    "mud turtle": ["musk turtle", "stinkpot", "turtle"],
    "mud-beplastered": [],
    "mud-brick": [],
    "mudder": ["bangtail", "race horse", "racehorse"],
    "muddle": ["puddle", "rile", "roil"],
    "muddy": ["begrime", "bemire", "colly", "dirty", "grime", "muddy up", "soil"],
    "mudguard": ["fender", "splash guard", "splash-guard", "wing"],
    "mudhif": ["hovel", "hut", "hutch", "shack", "shanty"],
    "mudra": ["gesture"],
    "mudskipper": ["goby", "gudgeon", "mudspringer"],
    "mudslide": ["landslide", "landslip"],
    "mudwrestle": ["mud-wrestle", "wrestle"],
    "muenster": ["cheese"],
    "muesli": ["breakfast food"],
    "muezzin": ["announcer", "muadhdhin", "muazzin"],
    "muff": ["fail", "neglect"],
    "muffin": ["bran muffin", "corn muffin", "gem", "popover", "quick bread"],
    "muffin man": ["hawker", "packman", "peddler", "pedlar", "pitchman"],
    "muffle": ["damp", "dampen", "dull", "mute", "soften", "tone down"],
    "muffled": [],
    "muffler": ["scarf"],
    "mufti": ["grand mufti", "jurist", "legal expert"],
    "mug": ["hold up", "stick up"],
    "mug file": ["data file", "file", "mug book"],
    "mug shot": ["exposure", "mugshot", "photo", "photograph", "pic", "picture"],
    "mug's game": ["attempt", "effort", "endeavor", "endeavour", "try"],
    "muggee": ["victim"],
    "mugger": ["robber"],
    "mugginess": ["humidity", "humidness"],
    "mugging": ["assault"],
    "muggy": ["steamy", "sticky"],
    "mugil": ["fish genus", "genus mugil"],
    "mugilidae": ["family mugilidae", "fish family"],
    "mugiloidea": ["animal order", "suborder mugiloidea"],
    "mugwort": ["artemisia gnaphalodes", "artemisia ludoviciana", "artemisia vulgaris", "common mugwort", "cudweed", "prairie sage", "western mugwort", "white sage", "wormwood"],
    "mugwump": ["pol", "political leader", "politician", "politico"],
    "muhammad": ["elijah muhammad"],
    "muhammadan": ["mohammedan"],
    "muharram": ["islamic calendar month", "moharram", "muharrum"],
    "muhlenbergia": ["genus muhlenbergia", "liliopsid genus", "monocot genus"],
    "muir": ["john muir"],
    "muishond": ["ictonyx frenata", "ictonyx striata", "poecilogale albinucha", "snake muishond", "striped muishond", "weasel", "zoril"],
    "mujahedeen khalq": ["mujahadeen", "mujahadein", "mujahadin", "mujahedeen", "mujahedin", "mujahideen", "mujahidin"],
    "mujahedeen kompak": [],
    "mujahid": ["moslem", "muslim"],
    "mujahidin": ["force", "military force", "military group", "military unit", "mujahadeen", "mujahadein", "mujahadin", "mujahedeen", "mujahedeen khalq", "mujahedin", "mujahideen"],
    "mujahidin-e khalq organization": ["mek", "mko", "people's mujahidin of iran"],
    "mujtihad": ["bookman", "moslem", "muslim", "scholar", "scholarly person", "student"],
    "mukalla": ["al-mukalla"],
    "mukataa": ["central office", "headquarters", "home base", "home office", "main office"],
    "mulatto": ["mixed-blood"],
    "mulberry": ["black mulberry", "fruit tree", "morus alba", "morus nigra", "morus rubra", "mulberry tree", "red mulberry", "white mulberry"],
    "mulch": ["cover"],
    "mulct": ["impose", "levy"],
    "mule": ["carpet slipper", "scuff", "slipper"],
    "mule deer": ["black-tailed deer", "blacktail", "blacktail deer", "burro deer", "cervid", "deer", "odocoileus hemionus", "odocoileus hemionus columbianus"],
    "mule fat": ["baccharis viminea", "bush", "shrub"],
    "mule's ears": ["wild flower", "wildflower", "wyethia amplexicaulis"],
    "muleteer": ["jack", "laborer", "labourer", "manual laborer", "mule driver", "mule skinner", "skinner"],
    "mull": ["dulcify", "dulcorate", "edulcorate", "sweeten"],
    "mullah": ["mollah", "moslem", "mulla", "muslim"],
    "mullah omar": ["mullah mohammed omar"],
    "mulled cider": ["sweet cider"],
    "mulled wine": ["bishop", "negus", "vino", "wine"],
    "mullein": ["aaron's rod", "common mullein", "flannel leaf", "flannel mullein", "great mullein", "herb", "herbaceous plant", "moth mullein", "purple mullein", "torch", "velvet plant", "verbascum blattaria", "verbascum lychnitis", "verbascum phoeniceum", "verbascum thapsus", "white mullein", "woolly mullein"],
    "mullein pink": ["catchfly", "dusty miller", "gardener's delight", "lychnis", "lychnis coronaria", "rose campion"],
    "muller": ["paul hermann muller"],
    "mullet": ["fish", "gray mullet", "grey mullet"],
    "mullidae": ["family mullidae", "fish family"],
    "mulligan stew": ["irish burgoo", "mulligan", "stew"],
    "mulligatawny": ["soup"],
    "mullion": ["slip", "strip"],
    "mullioned": [],
    "mulloidichthys": ["fish genus", "genus mulloidichthys"],
    "mulloway": ["jewfish", "sciaena antarctica", "sciaenid", "sciaenid fish"],
    "mullus": ["fish genus", "genus mullus"],
    "multi-billionaire": ["have", "rich person", "wealthy person"],
    "multi-seeded": ["several-seeded"],
    "multi-stemmed": [],
    "multibank holding company": ["bank holding company"],
    "multicellular": [],
    "multichannel recorder": ["recorder", "recording equipment", "recording machine"],
    "multicollinearity": ["multiple correlation", "multiple regression"],
    "multicultural": [],
    "multiculturalism": ["doctrine", "ism", "philosophical system", "philosophy", "school of thought"],
    "multidimensional": [],
    "multidimensional language": ["decision table", "flow chart", "flow diagram", "flow sheet", "flowchart", "logic diagram", "logical diagram", "programing language", "programming language"],
    "multiengine airplane": ["aeroplane", "airplane", "multiengine plane", "plane"],
    "multiethnic": ["multi-ethnic"],
    "multifactorial": [],
    "multiflora": ["baby rose", "japanese rose", "multiflora rose", "rosa multiflora", "rose", "rosebush"],
    "multifocal lens implant": ["interocular lens implant", "iol", "lens implant", "multifocal iol"],
    "multiform": [],
    "multilane": [],
    "multilateral": ["many-sided"],
    "multilaterally": [],
    "multilevel": [],
    "multilingual": [],
    "multimedia": ["hypermedia", "hypermedia system", "interactive multimedia", "interactive multimedia system", "multimedia system", "transmission"],
    "multinational": ["transnational"],
    "multinucleate": [],
    "multiparous": [],
    "multipartite": [],
    "multiphase": ["polyphase"],
    "multiple": ["double", "lcm", "least common multiple", "lowest common multiple", "mathematical product", "product", "quadruple", "triple"],
    "multiple correlation coefficient": ["coefficient of correlation", "correlation", "correlation coefficient"],
    "multiple mononeuropathy": ["neuropathy"],
    "multiple myeloma": ["myeloma"],
    "multiple regression": ["multicollinearity", "multiple correlation", "multivariate analysis"],
    "multiple sclerosis": ["autoimmune disease", "autoimmune disorder", "degenerative disorder", "disseminated multiple sclerosis", "disseminated sclerosis", "induration", "ms", "sclerosis"],
    "multiple star": ["star", "trapezium"],
    "multiple voting": ["ballot", "balloting", "vote", "voting"],
    "multiple-choice": [],
    "multiplex": ["telecom", "telecommunication"],
    "multiplex operation": ["operation"],
    "multiplexer": ["data multiplexer", "electronic device"],
    "multiplicand": ["number"],
    "multiplication": ["doubling", "growth", "increase", "increment", "quadrupling", "quintupling", "tripling"],
    "multiplicative": [],
    "multiplicative inverse": ["inverse", "opposite", "reciprocal"],
    "multiplicatively": [],
    "multiplicity": ["magnitude"],
    "multiplied": [],
    "multiplier": ["multiplier factor", "number", "scale factor"],
    "multiply": ["calculate", "cipher", "compute", "cube", "cypher", "figure", "raise", "reckon", "square", "work out"],
    "multipotent": [],
    "multiprocessing": ["data processing", "parallel processing"],
    "multiprocessor": ["digital computer"],
    "multiprogramming": ["concurrent execution", "execution", "instruction execution"],
    "multipurpose": [],
    "multiracial": [],
    "multistage": ["period", "period of time", "time period"],
    "multistage rocket": ["projectile", "rocket", "step rocket"],
    "multistory": ["multistorey", "multistoried"],
    "multitude": ["assemblage", "concourse", "gathering", "herd", "hive", "horde", "host", "legion", "ruck", "throng"],
    "multitudinousness": ["multiplicity", "numerosity", "numerousness"],
    "multivalent": [],
    "multivariate": [],
    "multivariate analysis": ["analysis of variance", "anova", "correlational analysis", "multiple correlation", "multiple regression", "regression analysis", "statistical method", "statistical procedure"],
    "multiversity": ["university"],
    "multivitamin": ["multivitamin pill", "vitamin pill"],
    "mum": ["secrecy", "secretiveness", "silence"],
    "mumbai": ["bombay"],
    "mumble": ["chew", "gum", "jaw", "manducate", "masticate"],
    "mumblety-peg": ["child's game", "mumble-the-peg"],
    "mumbling": ["diction", "enunciation"],
    "mumbo jumbo": ["gibber", "gibberish"],
    "mummery": ["bunk", "flummery", "hokum", "meaninglessness", "nonsense", "nonsensicality"],
    "mummichog": ["fundulus heteroclitus", "killifish"],
    "mummification": ["condition", "status"],
    "mummify": ["bear on", "carry on", "continue", "preserve", "uphold"],
    "mummy": ["body", "dead body"],
    "mumps": ["epidemic parotitis", "infectious disease"],
    "mumpsimus": ["notion"],
    "munch": ["edvard munch"],
    "munchausen's syndrome": ["munchausen syndrome", "syndrome"],
    "muncher": ["chewer"],
    "munchhausen": ["baron munchausen", "karl friedrich hieronymus von munchhausen", "munchausen"],
    "muncie": [],
    "munda": ["austro-asiatic", "austro-asiatic language", "munda-mon-khmer"],
    "mundane": ["terrestrial"],
    "mundanely": ["terrestrially"],
    "mung": ["golden gram", "green gram", "legume", "leguminous plant", "mung bean", "phaseolus aureus", "vigna radiata"],
    "munich": ["muenchen"],
    "munich beer": ["lager", "lager beer", "munchener"],
    "municipal": [],
    "municipal bond": ["bond", "bond certificate", "utility bond", "utility revenue bond"],
    "municipal government": ["commission plan", "local government"],
    "municipal note": ["note", "note of hand", "promissory note"],
    "municipality": ["administrative district", "administrative division", "city", "metropolis", "populated area", "territorial division", "town", "urban area", "urban center"],
    "municipally": [],
    "munificence": ["largess", "largesse", "liberality", "liberalness", "magnanimity", "openhandedness"],
    "muniments": ["title deed"],
    "munition": ["arm"],
    "munitions industry": ["arms industry", "industry"],
    "munj": ["grass", "munja", "saccharum bengalense", "saccharum munja"],
    "munro": ["h. h. munro", "hector hugh munro", "saki"],
    "muntiacus": ["genus muntiacus", "mammal genus"],
    "muntingia": ["dilleniid dicot genus", "genus muntingia"],
    "muntjac": ["barking deer", "cervid", "deer"],
    "muon": ["lepton", "mu-meson", "negative muon"],
    "muraenidae": ["family muraenidae", "fish family"],
    "mural": ["fresco", "painting", "picture", "wall painting"],
    "muralist": ["painter"],
    "murder": ["bump off", "burke", "dispatch", "execute", "hit", "kill", "off", "polish off", "remove", "slay"],
    "murder charge": ["bill of indictment", "indictment", "murder indictment"],
    "murder conviction": ["condemnation", "conviction", "judgment of conviction", "sentence"],
    "murder mystery": ["mystery", "mystery story", "whodunit"],
    "murder suspect": ["suspect"],
    "murdered": [],
    "murderee": ["victim"],
    "murderer": ["assassin", "assassinator", "bravo", "butcher", "criminal", "crook", "cutthroat", "felon", "fratricide", "gun", "gun for hire", "gunman", "gunslinger", "hatchet man", "hired gun", "hit man", "hitman", "iceman", "infanticide", "killer", "liquidator", "malefactor", "manslayer", "mass murderer", "murderess", "outlaw", "parricide", "ripper", "serial killer", "serial murderer", "shooter", "slayer", "torpedo", "triggerman"],
    "murderess": ["liquidator", "manslayer", "murderer"],
    "murderously": [],
    "murderousness": ["hate", "hatred"],
    "murdoch": ["keith rupert murdoch", "rupert murdoch"],
    "muriatic acid": ["chlorohydric acid", "hydrochloric acid"],
    "muridae": ["family muridae", "mammal family"],
    "murillo": ["bartolome esteban murillo"],
    "murine": ["gnawer", "rodent"],
    "murine typhus": ["endemic typhus", "rat typhus", "typhus", "typhus fever", "urban typhus"],
    "murk": ["darken"],
    "murkily": [],
    "murky": ["mirky"],
    "murmansk": [],
    "murmur": ["coo", "mouth", "speak", "susurrate", "talk", "utter", "verbalise", "verbalize"],
    "murmur vowel": ["murmur", "schwa", "shwa"],
    "murmuring": ["susurrant", "whispering"],
    "murmurous": ["rustling", "soughing", "susurrous"],
    "muroidea": ["mammal family", "superfamily muroidea"],
    "murphy bed": ["bed"],
    "murphy's law": ["gnome", "sod's law"],
    "murrain": ["animal disease"],
    "murray": ["george gilbert aime murphy", "gilbert murray"],
    "murre": ["common murre", "guillemot", "thick-billed murre", "uria aalge", "uria lomvia"],
    "murrow": ["edward r. murrow", "edward roscoe murrow"],
    "murrumbidgee": ["murrumbidgee river"],
    "mus": ["genus mus", "mammal genus"],
    "musa": ["genus musa", "liliopsid genus", "monocot genus"],
    "musaceae": ["banana family", "family musaceae", "liliopsid family", "monocot family"],
    "musales": ["order musales", "plant order"],
    "musca": [],
    "musca volitans": ["floater", "muscae volitantes", "spots", "symptom"],
    "muscadet": ["common grape vine", "vinifera", "vinifera grape", "vitis vinifera"],
    "muscadine": ["grape", "grape vine", "grapevine", "vitis rotundifolia"],
    "muscardinus": ["genus muscardinus", "mammal genus"],
    "muscari": ["genus muscari", "liliid monocot genus"],
    "muscat": ["common grape vine", "muskat", "vinifera", "vinifera grape", "vitis vinifera"],
    "muscicapa": ["bird genus", "genus muscicapa"],
    "muscicapidae": ["bird family", "family muscicapidae"],
    "muscidae": ["arthropod family", "family muscidae"],
    "muscivora": ["bird genus", "genus muscivora"],
    "muscle": ["go across", "go through", "pass"],
    "muscle cell": ["fiber", "fibre", "muscle fiber", "muscle fibre", "smooth muscle cell", "somatic cell", "striated muscle cell", "striated muscle fiber", "vegetative cell"],
    "muscle into": ["force", "push"],
    "muscle relaxant": ["benzodiazepine", "cyclobenzaprine", "flaxedil", "flexeril", "gallamine", "kavrin", "kemadrin", "methocarbamol", "norflex", "orphenadrine", "papaverine", "procyclidine", "relaxant", "robaxin", "succinylcholine"],
    "muscle-bound": [],
    "muscleman": ["bully", "hooligan", "muscle", "roughneck", "rowdy", "ruffian", "tough", "yob", "yobbo", "yobo"],
    "muscoidea": ["arthropod family", "superfamily muscoidea"],
    "muscovite": ["damourite", "isinglass", "mica"],
    "muscovy": [],
    "muscovy duck": ["cairina moschata", "duck", "musk duck"],
    "muscular": [],
    "muscular dystrophy": ["becker muscular dystrophy", "congenital disease", "distal muscular dystrophy", "duchenne's muscular dystrophy", "dystrophy", "genetic abnormality", "genetic defect", "genetic disease", "genetic disorder", "hereditary condition", "hereditary disease", "inherited disease", "inherited disorder", "limb-girdle muscular dystrophy", "myotonia atrophica", "myotonic dystrophy", "myotonic muscular dystrophy", "oculopharyngeal muscular dystrophy", "pseudohypertrophic dystrophy", "steinert's disease"],
    "muscular structure": ["diaphragm", "esophagus", "gorge", "gullet", "midriff", "muscle system", "musculature", "oesophagus", "system"],
    "muscular tonus": ["muscle tone", "tone", "tonicity", "tonus"],
    "muscularity": ["physical condition", "physiological condition", "physiological state"],
    "musculophrenic artery": ["arteria", "arteria musculophrenica", "arterial blood vessel", "artery"],
    "musculophrenic vein": ["vein", "vena", "vena musculophrenica", "venous blood vessel"],
    "musculoskeletal": [],
    "musculoskeletal system": ["system"],
    "musculus abductor digiti minimi manus": ["abductor", "abductor muscle"],
    "musculus abductor digiti minimi pedis": ["abductor", "abductor muscle"],
    "musculus abductor hallucis": ["abductor", "abductor muscle"],
    "musculus abductor pollicis": ["abductor", "abductor muscle"],
    "musculus adductor brevis": ["adductor", "adductor muscle"],
    "musculus adductor hallucis": ["adductor", "adductor muscle"],
    "musculus adductor longus": ["adductor", "adductor muscle"],
    "musculus adductor magnus": ["adductor", "adductor muscle", "great adductor muscle"],
    "musculus articularis cubiti": ["articular muscle"],
    "musculus articularis genus": ["articular muscle"],
    "musculus biceps femoris": ["biceps", "femoral biceps"],
    "musculus sphincter ani externus": ["skeletal muscle", "striated muscle"],
    "musculus sphincter ani internus": ["involuntary muscle", "smooth muscle"],
    "musculus sphincter ductus choledochi": ["anatomical sphincter", "sphincter", "sphincter muscle"],
    "musculus sphincter ductus pancreatici": ["anatomical sphincter", "sphincter", "sphincter muscle"],
    "muse": ["greek deity"],
    "muser": ["muller", "ponderer", "ruminator", "thinker"],
    "musette": ["bagpipe", "shepherd's pipe"],
    "musette pipe": ["hautbois", "hautboy", "oboe"],
    "museum": ["deposit", "depositary", "depository", "repository", "science museum"],
    "musgu": ["biu-mandara", "mulwi", "munjuk"],
    "mush": ["drive"],
    "musher": ["traveler", "traveller"],
    "mushiness": ["pulpiness", "softness"],
    "mushroom": ["cull", "pick", "pluck"],
    "mushroom anchor": ["anchor", "ground tackle"],
    "mushroom coral": ["madrepore", "madriporian coral", "stony coral"],
    "mushroom pimple": ["family hypocreaceae", "green mushroom pimple", "hypocreaceae", "orange mushroom pimple"],
    "mushroom poisoning": ["food poisoning", "gastrointestinal disorder"],
    "mushroom sauce": ["sauce"],
    "mushy": [],
    "mushy peas": ["entremets", "side dish", "side order"],
    "musial": ["stan musial", "stan the man", "stanley frank musial"],
    "music": ["air", "antiphony", "auditory communication", "bach", "ballet", "beethoven", "brahms", "chopin", "chorus", "composition", "concerted music", "dance music", "genre", "gilbert and sullivan", "handel", "harmony", "haydn", "instrumental music", "line", "melodic line", "melodic phrase", "melody", "monody", "monophonic music", "monophony", "mozart", "music genre", "musical composition", "musical genre", "musical harmony", "musical style", "opus", "overture", "part music", "piece", "piece of music", "pizzicato", "polyphonic music", "polyphony", "polytonalism", "polytonality", "popularism", "prelude", "refrain", "section", "serial music", "serialism", "strain", "stravinsky", "subdivision", "syncopation", "ta'ziyeh", "tune", "vocal", "vocal music", "wagner"],
    "music box": ["instrument", "musical box", "musical instrument"],
    "music critic": ["critic"],
    "music department": ["academic department", "department of music"],
    "music genre": ["african-american music", "black music", "church music", "classical", "classical music", "expressive style", "genre", "march", "marching music", "music", "musical genre", "musical style", "popular music", "popular music genre", "religious music", "serious music", "style"],
    "music hall": ["house", "theater", "theatre", "vaudeville theater", "vaudeville theatre"],
    "music lesson": ["lesson", "piano lesson", "violin lesson"],
    "music of the spheres": ["euphony", "music"],
    "music paper": ["paper", "score paper"],
    "music school": ["conservatory", "school of music"],
    "music stand": ["music rack", "rack", "stand"],
    "music stool": ["piano stool", "stool"],
    "music teacher": ["instructor", "piano teacher", "teacher"],
    "musical": ["film", "flick", "motion picture", "motion-picture show", "movie", "moving picture", "moving-picture show", "musical comedy", "musical theater", "pic", "picture", "picture show", "play"],
    "musical arrangement": ["arrangement", "composition", "instrumentation", "musical composition", "opus", "orchestration", "piece", "piece of music"],
    "musical chairs": ["child's game", "going to jerusalem"],
    "musical composition": ["adagio", "allegretto", "allegro", "andante", "arrangement", "bagatelle", "canon", "capriccio", "composition", "divertimento", "duet", "duette", "duo", "etude", "fantasia", "idyl", "idyll", "incidental music", "intermezzo", "introit", "larghetto", "largo", "medley", "morceau", "motet", "movement", "music", "musical arrangement", "musical passage", "nocturne", "notturno", "octet", "octette", "opus", "passage", "pastiche", "pastoral", "pastorale", "piece", "piece of music", "potpourri", "program music", "programme music", "quartet", "quartette", "quintet", "quintette", "realisation", "realization", "septet", "septette", "serenade", "sestet", "sextet", "sextette", "sheet music", "solo", "song", "study", "suite", "symphonic poem", "toccata", "tone poem", "trio", "vocal"],
    "musical drama": ["opera"],
    "musical instrument": ["barrel organ", "bass", "calliope", "device", "electronic instrument", "electronic musical instrument", "grind organ", "hand organ", "hurdy gurdy", "hurdy-gurdy", "instrument", "jew's harp", "jews' harp", "keyboard instrument", "mouth bow", "music box", "musical box", "percussion instrument", "percussive instrument", "steam organ", "street organ", "stringed instrument", "wind", "wind instrument"],
    "musical instrument digital interface": ["communications protocol", "midi", "protocol"],
    "musical notation": ["accidental", "atonalism", "atonality", "bar", "bar line", "cancel", "clef", "fermata", "flat", "interval", "key", "key signature", "measure", "musical interval", "musical note", "musical scale", "musical time signature", "natural", "notation", "notational system", "note", "rest", "scale", "segno", "sforzando", "sharp", "signature", "slur", "solmisation", "solmization", "staff", "stave", "tablature", "time signature", "tonality", "tone"],
    "musical organization": ["band", "chorus", "dance band", "dance orchestra", "duet", "duette", "duo", "ensemble", "musical group", "musical organisation", "octet", "octette", "orchestra", "organisation", "organization", "quartet", "quartette", "quintet", "quintette", "section", "septet", "septette", "sestet", "sextet", "sextette", "trio"],
    "musical perception": ["auditory perception", "melody", "sound perception", "tonal pattern"],
    "musical performance": ["jam session", "performance", "performing arts", "playing", "singing", "vocalizing"],
    "musical soiree": ["soiree", "soiree musicale"],
    "musical time": ["beat", "common measure", "common time", "duple time", "four-four time", "in time", "musical rhythm", "pacing", "quadruple time", "rhythm", "tempo", "time", "triple time"],
    "musicality": ["lyricality", "lyricism", "melodiousness", "musicalness", "songfulness", "sound property", "texture", "tunefulness"],
    "musically": [],
    "musician": ["accompanist", "accompanyist", "accordionist", "bagpiper", "bandsman", "bassist", "bassoonist", "bell ringer", "carillonneur", "cellist", "clarinetist", "clarinettist", "cornetist", "fiddler", "flautist", "flute player", "flutist", "gambist", "guitar player", "guitarist", "harmoniser", "harmonizer", "harper", "harpist", "harpsichordist", "hornist", "instrumentalist", "jazz musician", "jazzman", "keyboardist", "koto player", "lutanist", "lutenist", "lutist", "oboist", "organist", "percussionist", "performer", "performing artist", "pianist", "piano player", "piper", "player", "recorder player", "rhythm and blues musician", "rock 'n' roll musician", "rocker", "saxist", "saxophonist", "singer", "sitar player", "soloist", "trombone player", "trombonist", "trumpeter", "vibist", "vibraphonist", "violinist", "violist", "violoncellist", "vocaliser", "vocalist", "vocalizer"],
    "musicianship": ["art", "artistry", "prowess"],
    "musicogenic epilepsy": ["reflex epilepsy"],
    "musicological": [],
    "musicologically": [],
    "musicologist": ["bookman", "scholar", "scholarly person", "student"],
    "musicology": ["arts", "humanistic discipline", "humanities", "liberal arts"],
    "musingly": [],
    "musk": ["secretion"],
    "musk clover": ["erodium moschatum", "heron's bill", "muskus grass", "storksbill", "white-stemmed filaree"],
    "musk deer": ["cervid", "deer", "moschus moschiferus"],
    "musk kangaroo": ["hypsiprymnodon moschatus", "kangaroo"],
    "musk mallow": ["mallow", "malva moschata", "mus rose"],
    "musk ox": ["bovid", "musk sheep", "ovibos moschatus"],
    "musk rose": ["rosa moschata", "rose", "rosebush"],
    "musk thistle": ["carduus nutans", "nodding thistle", "thistle"],
    "musk turtle": ["mud turtle", "stinkpot"],
    "musk-scented": ["musky-scented"],
    "muskellunge": ["pike"],
    "musket": ["blunderbuss", "culverin", "fusil", "matchlock", "muzzle loader"],
    "musket ball": ["ball", "pellet", "shot"],
    "musketeer": ["foot soldier", "footslogger", "infantryman", "marcher"],
    "musketry": ["army unit"],
    "muskhogean": ["alabama", "american indian", "choctaw", "hitchiti", "indian", "koasati", "muskogean", "muskogee", "red indian", "seminole"],
    "muskiness": ["aroma", "odor", "odour", "olfactory property", "scent", "smell"],
    "muskmelon": ["cantaloup", "cantaloupe", "melon", "net melon", "netted melon", "nutmeg melon", "sweet melon", "winter melon"],
    "muskogee": ["muskhogean", "muskogean"],
    "muskrat": ["fur", "hudson seal", "muskrat fur", "pelt"],
    "muskwood": ["daisy bush", "daisy-bush", "daisybush", "olearia argophylla"],
    "musky": [],
    "muslim": ["assassin", "begum", "calif", "caliph", "fakeer", "fakir", "faqir", "faquir", "hakeem", "hakim", "imam", "imaum", "islamist", "jihadist", "kalif", "kaliph", "khalif", "khalifah", "mollah", "moor", "moslem", "mujahid", "mujtihad", "mulla", "mullah", "muslimah", "religious person", "saracen", "shi'ite", "shi'ite muslim", "shia muslim", "shiite", "shiite muslim", "sufi", "sunni", "sunni muslim", "sunnite", "wahabi", "wahhabi"],
    "muslimah": ["moslem", "muslim", "niqaabi"],
    "muslin": ["cloth", "fabric", "material", "nainsook", "organdie", "organdy", "textile"],
    "musnud": ["throne"],
    "musophaga": ["bird genus", "genus musophaga"],
    "musophagidae": ["bird family", "family musophagidae"],
    "musophobia": ["zoophobia"],
    "muss": ["disarrange", "tussle"],
    "mussel": ["shellfish"],
    "musset": ["alfred de musset", "louis charles alfred de musset"],
    "mussolini": ["benito mussolini", "il duce"],
    "mussorgsky": ["modest moussorgsky", "modest mussorgsky", "modest petrovich moussorgsky", "modest petrovich mussorgsky", "moussorgsky"],
    "must": ["essential", "necessary", "necessity", "requirement", "requisite"],
    "mustache": ["facial hair", "handle-bars", "moustache", "moustachio", "mustachio", "soup-strainer", "toothbrush", "walrus moustache", "walrus mustache"],
    "mustache cup": ["cup", "moustache cup"],
    "mustachio": ["handle-bars", "moustache", "moustachio", "mustache"],
    "mustachioed": ["mustached"],
    "mustang": ["bronc", "broncho", "bronco", "pony"],
    "mustang mint": ["herb", "herbaceous plant", "monardella lanceolata"],
    "mustard": ["black mustard", "brassica hirta", "brassica juncea", "brassica kaber", "brassica napus", "brassica nigra", "chadlock", "charlock", "chinese mustard", "colza", "crucifer", "cruciferous plant", "field mustard", "gai choi", "indian mustard", "leaf mustard", "rape", "sinapis alba", "sinapis arvensis", "white mustard", "wild mustard"],
    "mustard gas": ["blistering agent", "dichloroethyl sulfide", "mustard agent", "poison gas", "sulfur mustard", "vesicant", "vesicatory"],
    "mustard oil": ["oil"],
    "mustard plaster": ["cataplasm", "plaster", "poultice", "sinapism"],
    "mustard sauce": ["sauce"],
    "mustard seed": ["flavorer", "flavoring", "flavourer", "flavouring", "seasoner", "seasoning"],
    "mustela": ["genus mustela", "mammal genus"],
    "mustelidae": ["family mustelidae", "mammal family"],
    "musteline mammal": ["badger", "black-footed ferret", "carcajou", "carnivore", "eira barbara", "enhydra lutris", "ferret", "fitch", "foulmart", "foumart", "galictis vittatus", "glutton", "grison", "grison vittatus", "gulo gulo", "gulo luscus", "honey badger", "marten", "marten cat", "mellivora capensis", "mink", "mustela nigripes", "mustela putorius", "mustelid", "musteline", "otter", "polecat", "ratel", "sea otter", "skunk", "skunk bear", "taira", "tayra", "weasel", "wolverine", "wood pussy"],
    "mustelus": ["fish genus", "genus mustelus"],
    "muster": ["collect", "come up", "garner", "gather", "muster up", "pull together", "rally", "summon"],
    "muster call": ["roll call"],
    "muster roll": ["roll", "roster"],
    "musth": ["phase", "stage"],
    "mustiness": ["moldiness", "must", "staleness"],
    "mutability": ["alterability", "changeability", "changeableness", "mutableness", "vicissitude"],
    "mutable": ["changeable"],
    "mutafacient": [],
    "mutagen": ["agent"],
    "mutagenesis": ["cause", "insertional mutagenesis"],
    "mutagenic": [],
    "mutant": ["being", "freak", "lusus naturae", "monster", "monstrosity", "mutation", "organism", "sport", "variation"],
    "mutant gene": ["cftr", "cistron", "cystic fibrosis transport regulator", "factor", "gene"],
    "mutate": ["change", "revert"],
    "mutation": ["alteration", "change", "chromosomal mutation", "deletion", "gene mutation", "genetic mutation", "inversion", "modification", "point mutation", "reversion", "saltation", "transposition"],
    "mutational": [],
    "mutatis mutandis": [],
    "mutative": [],
    "mutawa'een": ["constabulary", "law", "mutawa", "police", "police force"],
    "mutchkin": ["liquid measure", "liquid unit"],
    "mute": ["deaf person", "deaf-and-dumb person", "deaf-mute", "dummy", "silent person"],
    "mute swan": ["cygnus olor", "swan"],
    "mutely": ["silently", "taciturnly", "wordlessly"],
    "muteness": ["silence", "uncommunicativeness"],
    "mutilate": ["cut up", "damage", "mangle"],
    "mutilation": ["accidental injury", "dismemberment", "injury", "taking apart"],
    "mutilator": ["individual", "maimer", "mangler", "mortal", "person", "somebody", "someone", "soul"],
    "mutillidae": ["family mutillidae", "hymenopter", "hymenopteran", "hymenopteron", "hymenopterous insect"],
    "mutineer": ["freedom fighter", "insurgent", "insurrectionist", "rebel"],
    "mutinous": [],
    "mutinus": ["fungus genus", "genus mutinus"],
    "mutiny": ["arise", "rebel", "rise", "rise up"],
    "mutisia": ["bush", "shrub"],
    "mutism": ["condition", "deaf-muteness", "deaf-mutism", "muteness", "status"],
    "muton": ["base", "nucleotide"],
    "mutter": ["murmur", "murmuration", "murmuring", "mussitation", "muttering", "sound"],
    "mutterer": ["mumbler", "murmurer", "speaker", "talker", "utterer", "verbaliser", "verbalizer"],
    "mutton chop": ["chop"],
    "mutton snapper": ["lutjanus analis", "muttonfish", "snapper"],
    "mutton tallow": ["tallow"],
    "mutual aid": ["international logistic support", "logistic assistance", "logistic support"],
    "mutual fund": ["etf", "exchange traded fund", "fund", "index fund", "monetary fund"],
    "mutual induction": ["inductance", "induction"],
    "mutual opposition": ["oppositeness", "opposition", "polarity"],
    "mutual resemblance": ["resemblance"],
    "mutual savings bank": ["msb", "savings bank"],
    "mutual understanding": ["mutual affection", "sympathy"],
    "mutuality": ["mutualness", "reciprocality", "reciprocity"],
    "mutually": ["reciprocally"],
    "muybridge": ["eadweard muybridge", "edward james muggeridge"],
    "muzhik": ["bucolic", "moujik", "mujik", "muzjik", "peasant", "provincial"],
    "muztag": ["muztagh"]
}
