synonyms = {
    "get around": ["get about"],
    "get cracking": ["bestir oneself", "get going", "get moving", "get rolling", "get started", "get weaving"],
    "get down": ["begin", "commence", "get", "set about", "set out", "start", "start out"],
    "get even": ["get back"],
    "get in": ["get into"],
    "get in touch": ["connect", "touch base"],
    "get into": ["tangle with"],
    "get off": ["escape", "get away", "get by", "get out"],
    "get off the ground": ["take off"],
    "get on": ["be on"],
    "get rid of": ["remove"],
    "get the best": ["have the best", "overcome"],
    "get the better of": ["defeat", "overcome"],
    "get through": ["come through"],
    "get up": ["arise", "rise", "turn out", "uprise"],
    "get well": ["bounce back", "get over"],
    "get worse": ["relapse"],
    "getaway": ["lam"],
    "gettable": ["getable", "obtainable", "procurable"],
    "gettysburg": ["battle of gettysburg"],
    "geum": ["genus geum"],
    "ghana": ["gold coast", "republic of ghana"],
    "ghanaian": ["ghanese", "ghanian"],
    "ghastliness": ["grimness", "gruesomeness", "luridness"],
    "ghastly": ["grim", "grisly", "gruesome", "macabre", "sick"],
    "ghatti": ["ghatti gum"],
    "gheg": ["gheg dialect"],
    "ghetto blaster": ["boom box"],
    "ghettoize": ["ghettoise"],
    "ghillie": ["gillie"],
    "ghost": ["ghostwrite"],
    "ghostwriter": ["ghost"],
    "ghoulish": ["morbid"],
    "giacometti": ["alberto giacometti"],
    "giant": ["heavyweight", "hulk", "whale"],
    "giant armadillo": ["priodontes giganteus", "tatou", "tatu"],
    "giant bamboo": ["dendrocalamus giganteus"],
    "giant buttercup": ["laccopetalum giganteum"],
    "giant cane": ["arundinaria gigantea", "cane reed"],
    "giant chinkapin": ["castanea chrysophylla", "castanopsis chrysophylla", "chrysolepis chrysophylla", "golden chinkapin"],
    "giant clam": ["tridacna gigas"],
    "giant conch": ["strombus gigas"],
    "giant coreopsis": ["coreopsis gigantea"],
    "giant crab": ["macrocheira kaempferi"],
    "giant eland": ["taurotragus derbianus"],
    "giant hornet": ["vespa crabro"],
    "giant kangaroo": ["great grey kangaroo", "macropus giganteus"],
    "giant moa": ["dinornis giganteus"],
    "giant northwest shipworm": ["bankia setaceae"],
    "giant panda": ["ailuropoda melanoleuca", "coon bear", "panda", "panda bear"],
    "giant petrel": ["giant fulmar", "macronectes giganteus"],
    "giant puffball": ["calvatia gigantea"],
    "giant red paintbrush": ["castilleja miniata"],
    "giant reed": ["arundo donax"],
    "giant ryegrass": ["elymus condensatus", "leymus condensatus"],
    "giant salamander": ["megalobatrachus maximus"],
    "giant scrambling fern": ["diplopterygium longissimum"],
    "giant sequoia": ["big tree", "sequoia gigantea", "sequoia wellingtonia", "sequoiadendron giganteum", "sierra redwood"],
    "giant silkworm moth": ["silkworm moth"],
    "giant star": ["giant"],
    "giant star grass": ["cynodon plectostachyum"],
    "giant sunflower": ["helianthus giganteus", "indian potato", "tall sunflower"],
    "giant taro": ["alocasia macrorrhiza"],
    "giant timber bamboo": ["madake", "phyllostachys bambusoides"],
    "giantism": ["gigantism", "overgrowth"],
    "gibberish": ["gibber"],
    "gibbon": ["edward gibbon"],
    "gibbous": ["gibbose"],
    "gibbs": ["josiah willard gibbs"],
    "gibibit": ["gibit"],
    "giblet": ["giblets"],
    "gibraltar": ["calpe", "rock of gibraltar"],
    "gibran": ["kahlil gibran"],
    "gibson": ["charles dana gibson"],
    "giddiness": ["silliness"],
    "gide": ["andre gide", "andre paul guillaume gide"],
    "gidgee": ["acacia cambegei", "stinking wattle"],
    "gielgud": ["arthur john gielgud", "sir john gielgud"],
    "gift shop": ["novelty shop"],
    "gigabit": ["gb", "gbit"],
    "gigabyte": ["gb"],
    "gigahertz": ["gc", "ghz", "gigacycle", "gigacycle per second"],
    "gigantic": ["mammoth"],
    "gigantism": ["giantism"],
    "gigartinaceae": ["family gigartinaceae"],
    "giggle": ["titter"],
    "gila": ["gila river"],
    "gila monster": ["heloderma suspectum"],
    "gilbert": ["gb", "gi"],
    "gild": ["begild", "engild"],
    "gild the lily": ["paint the lily"],
    "gilded": ["meretricious", "specious"],
    "gilded flicker": ["colaptes chrysoides"],
    "gill": ["lamella"],
    "gill arch": ["branchial arch", "gill bar"],
    "gill slit": ["branchial cleft", "gill cleft"],
    "gillespie": ["dizzy gillespie", "john birks gillespie"],
    "gillette": ["king camp gilette"],
    "gilman": ["charlotte anna perkins gilman"],
    "gilmer": ["dorothy dix", "elizabeth merriwether gilmer"],
    "gilt": ["gilding"],
    "gin": ["gin rummy", "knock rummy"],
    "ginger": ["powdered ginger"],
    "ginger ale": ["ginger pop"],
    "gingersnap": ["ginger nut", "ginger snap", "snap"],
    "gingiva": ["gum"],
    "ginglymostoma": ["genus ginglymostoma"],
    "ginkgo": ["gingko", "ginkgo biloba", "maidenhair tree"],
    "ginkgoaceae": ["family ginkgoaceae", "ginkgo family"],
    "ginkgoales": ["order ginkgoales"],
    "ginkgopsida": ["class ginkgophytina", "class ginkgopsida", "ginkgophytina", "subdivision ginkgophyta", "subdivision ginkgophytina"],
    "ginsberg": ["allen ginsberg"],
    "ginseng": ["panax ginseng", "panax pseudoginseng", "panax schinseng"],
    "giotto": ["giotto di bondone"],
    "gipsywort": ["gypsywort", "lycopus europaeus"],
    "giraffa": ["genus giraffa"],
    "giraffe": ["camelopard", "giraffa camelopardalis"],
    "giraffidae": ["family giraffidae"],
    "girandole": ["girandola"],
    "girard": ["stephen girard"],
    "giraudoux": ["hippolyte jean giraudoux", "jean giraudoux"],
    "gird": ["encircle"],
    "girdle": ["deaden"],
    "girl": ["fille", "miss", "missy", "young lady", "young woman"],
    "girlfriend": ["girl", "lady friend"],
    "girlhood": ["maidenhood", "maidhood"],
    "girlish": ["schoolgirlish"],
    "giro": ["giro cheque"],
    "girondist": ["girondin"],
    "gish": ["lillian gish"],
    "give": ["apply"],
    "give birth": ["bear", "birth", "deliver", "have"],
    "give it a whirl": ["give it a try"],
    "give the axe": ["give the bounce", "give the gate"],
    "give the eye": ["give the once over"],
    "give up": ["allow"],
    "give voice": ["articulate", "formulate", "phrase", "word"],
    "give way": ["yield"],
    "given": ["precondition", "presumption"],
    "giving": ["gift"],
    "giving up": ["surrender", "yielding"],
    "giza": ["el giza", "gizeh"],
    "gizzard": ["gastric mill", "ventriculus"],
    "gjellerup": ["karl gjellerup"],
    "glabella": ["mesophyron"],
    "glacier lily": ["erythronium grandiflorum", "snow lily"],
    "glad": ["happy"],
    "gladden": ["joy"],
    "gladdened": ["exhilarated"],
    "glade mallow": ["napaea dioica"],
    "gladiolus": ["glad", "gladiola", "sword lily"],
    "gladly": ["fain", "lief"],
    "gladness": ["gladfulness", "gladsomeness"],
    "gladstone": ["william ewart gladstone", "william gladstone"],
    "glamor": ["glamour"],
    "glamorization": ["glamorisation", "glamourisation", "glamourization"],
    "glamorize": ["glamorise", "glamourise", "glamourize"],
    "glamorous": ["glamourous"],
    "glance": ["glint", "peek"],
    "gland": ["secreter", "secretor", "secretory organ"],
    "glandular disease": ["adenosis", "gland disease", "glandular disorder"],
    "glare": ["blaze", "brilliance"],
    "glareola": ["genus glareola"],
    "glareolidae": ["family glareolidae"],
    "glaser": ["donald arthur glaser", "donald glaser"],
    "glass": ["glaze"],
    "glass cutter": ["glassworker", "glazer", "glazier"],
    "glass lizard": ["glass snake", "joint snake"],
    "glassware": ["glasswork"],
    "glasswort": ["salicornia europaea", "samphire"],
    "glassy": ["vitreous", "vitrified"],
    "glaucium": ["genus glaucium"],
    "glaucomys": ["genus glaucomys"],
    "glaux": ["genus glaux"],
    "glaze": ["glass", "glass over", "glaze over"],
    "glazed": ["glassed"],
    "gleam": ["glimmer"],
    "glechoma": ["genus glechoma"],
    "gleditsia": ["genus gleditsia"],
    "gleefully": ["joyfully", "joyously"],
    "gleichenia": ["genus gleichenia"],
    "gleicheniaceae": ["family gleicheniaceae"],
    "glendower": ["owen glendower"],
    "glenn": ["john glenn"],
    "glenoid fossa": ["mandibular fossa"],
    "glib": ["pat", "slick"],
    "glibly": ["slickly"],
    "glibness": ["slickness"],
    "glide": ["gliding", "sailing", "sailplaning", "soaring"],
    "glider": ["sailplane"],
    "gliding joint": ["articulatio plana"],
    "glinka": ["mikhail glinka", "mikhail ivanovich glinka"],
    "glioblastoma": ["spongioblastoma"],
    "glipizide": ["glucotrol"],
    "gliridae": ["family gliridae"],
    "glis": ["genus glis"],
    "glistening": ["glossy", "lustrous", "sheeny", "shining", "shiny"],
    "glitter": ["gleam", "glint", "glisten", "shine"],
    "gloat": ["crow", "triumph"],
    "global": ["planetary", "world", "worldwide"],
    "global aphasia": ["total aphasia"],
    "global positioning system": ["gps"],
    "globalization": ["globalisation"],
    "globalize": ["globalise"],
    "globe amaranth": ["gomphrena globosa"],
    "globe lily": ["fairy lantern"],
    "globe mallow": ["false mallow"],
    "globeflower": ["globe flower"],
    "globetrotter": ["world traveler"],
    "globicephala": ["genus globicephala"],
    "globigerinidae": ["family globigerinidae"],
    "globin": ["haematohiston", "hematohiston"],
    "glochidium": ["glochid"],
    "glockenspiel": ["orchestral bells"],
    "gloom": ["gloominess", "glumness"],
    "gloominess": ["lugubriousness", "sadness"],
    "glooming": ["gloomful", "gloomy", "sulky"],
    "gloomy": ["blue", "depressed", "dispirited", "down", "down in the mouth", "downcast", "downhearted", "grim", "low"],
    "gloriosa": ["climbing lily", "creeping lily", "gloriosa superba", "glory lily"],
    "glorious": ["resplendent", "splendid", "splendiferous"],
    "glory": ["glorification"],
    "glory hole": ["lazaretto"],
    "glory pea": ["clianthus"],
    "gloss": ["annotate", "comment"],
    "gloss over": ["skate over", "skimp over", "slur over", "smooth over"],
    "glossalgia": ["glossodynia"],
    "glossary": ["gloss"],
    "glossinidae": ["family glossinidae"],
    "glossodia": ["genus glossodia"],
    "glossopharyngeal nerve": ["nervus glossopharyngeus", "ninth cranial nerve"],
    "glossopsitta": ["genus glossopsitta"],
    "glossy": ["calendered"],
    "glossy snake": ["arizona elegans"],
    "glottal stop": ["glottal catch", "glottal plosive"],
    "glow": ["beam", "radiate", "shine"],
    "glower": ["glare"],
    "gluck": ["christoph willibald von gluck"],
    "glue": ["paste"],
    "glued": ["pasted"],
    "gluey": ["glutinous", "gummy", "mucilaginous", "pasty", "sticky", "viscid", "viscous"],
    "glut": ["oversupply", "surfeit"],
    "glutamic acid": ["glutaminic acid"],
    "glutamic oxalacetic transaminase": ["glutamic oxaloacetic transaminase"],
    "gluteal artery": ["arteria glutes"],
    "gluteal vein": ["vena gluteus"],
    "glutethimide": ["doriden"],
    "gluteus": ["glute", "gluteal muscle", "gluteus muscle"],
    "glutted": ["overfull"],
    "glutton": ["gourmand", "gourmandizer", "trencherman"],
    "gluttonize": ["fress", "gluttonise"],
    "gluttony": ["gula", "overeating"],
    "glyburide": ["diabeta", "micronase"],
    "glyceraldehyde": ["glyceric aldehyde"],
    "glyceria": ["genus glyceria"],
    "glyceride": ["acylglycerol"],
    "glycerite": ["glycerole"],
    "glycerogelatin": ["glycerogel"],
    "glycerol": ["glycerin", "glycerine"],
    "glycerolize": ["glycerolise"],
    "glycine": ["genus glycine"],
    "glycogen": ["animal starch"],
    "glycolic acid": ["glycollic acid", "hydroxyacetic acid"],
    "glycyrrhiza": ["genus glycyrrhiza"],
    "glyptic art": ["glyptography"],
    "glyptics": ["lithoglyptics"],
    "gnaphalium": ["genus gnaphalium"],
    "gnarled": ["gnarly", "knobbed", "knotted", "knotty"],
    "gnathostomata": ["superclass gnathostomata"],
    "gnetaceae": ["family gnetaceae"],
    "gnetales": ["order gnetales"],
    "gnetopsida": ["class gnetopsida", "gnetophyta", "gnetophytina", "subdivision gnetophytina"],
    "gnetum": ["gnetum gnemon"],
    "gnome": ["dwarf"],
    "gnu": ["wildebeest"],
    "go": ["lead"],
    "go ahead": ["plow ahead"],
    "go all out": ["give full measure"],
    "go around": ["circulate", "spread"],
    "go back": ["date back", "date from"],
    "go by": ["go under"],
    "go far": ["go deep"],
    "go home": ["head home"],
    "go off": ["come off", "go over"],
    "go on": ["come on", "come up"],
    "go steady": ["date", "go out", "see"],
    "go to bed": ["bed", "crawl in", "go to sleep", "hit the hay", "hit the sack", "kip down", "retire", "sack out", "turn in"],
    "go to pot": ["go to the dogs"],
    "go to war": ["take arms", "take up arms"],
    "goad": ["prick"],
    "goal": ["end"],
    "goalkeeper": ["goalie", "goaltender", "netkeeper", "netminder"],
    "goat": ["caprine animal"],
    "goat cheese": ["chevre"],
    "goat grass": ["aegilops triuncalis"],
    "goat herder": ["goatherd"],
    "goat willow": ["pussy willow", "salix caprea"],
    "goatfish": ["mullus surmuletus", "red mullet", "surmullet"],
    "goatsfoot": ["oxalis caprina"],
    "goatsucker": ["caprimulgid", "nightjar"],
    "gobble": ["bolt"],
    "gobi": ["gobi desert"],
    "gobiesocidae": ["family gobiesocidae"],
    "gobiesox": ["genus gobiesox"],
    "gobiidae": ["family gobiidae"],
    "gobio": ["genus gobio"],
    "goblin": ["hob", "hobgoblin"],
    "goby": ["gudgeon"],
    "god": ["supreme being"],
    "godard": ["jean luc godard"],
    "goddam": ["goddamn", "goddamned"],
    "goddard": ["robert hutchings goddard"],
    "godel": ["kurt godel"],
    "godforsaken": ["waste", "wild"],
    "godhead": ["almighty", "creator", "divine", "god almighty", "jehovah", "lord", "maker"],
    "godiva": ["lady godiva"],
    "godless": ["irreverent"],
    "godly": ["reverent", "worshipful"],
    "godunov": ["boris fyodorovich godunov", "boris godunov"],
    "goebbels": ["joseph goebbels", "paul joseph goebbels"],
    "goethals": ["george washington goethals"],
    "goethe": ["johann wolfgang von goethe"],
    "goethean": ["goethian"],
    "goethite": ["gothite"],
    "goffer": ["gopher"],
    "goggle": ["gape", "gawk", "gawp"],
    "gogol": ["nikolai vasilievich gogol"],
    "going": ["sledding"],
    "goiter": ["goitre", "struma", "thyromegaly"],
    "golan heights": ["golan"],
    "gold": ["au"],
    "gold fern": ["pityrogramma chrysophylla"],
    "gold miner": ["gold digger", "gold panner"],
    "gold of pleasure": ["camelina sativa"],
    "goldberg": ["reuben lucius goldberg", "rube goldberg"],
    "goldcrest": ["regulus regulus"],
    "golden": ["halcyon", "prosperous"],
    "golden barrel cactus": ["echinocactus grusonii"],
    "golden clematis": ["clematis tangutica"],
    "golden club": ["orontium aquaticum"],
    "golden cup": ["hunnemania fumariifolia", "mexican tulip poppy"],
    "golden delicious": ["yellow delicious"],
    "golden eagle": ["aquila chrysaetos"],
    "golden fern": ["pityrogramma calomelanos aureoflava"],
    "golden fig": ["ficus aurea", "florida strangler fig", "strangler fig", "wild fig"],
    "golden glow": ["double gold", "hortensia", "rudbeckia laciniata hortensia"],
    "golden groundsel": ["golden ragwort", "packera aurea", "senecio aureus"],
    "golden hamster": ["mesocricetus auratus", "syrian hamster"],
    "golden larch": ["pseudolarix amabilis"],
    "golden oriole": ["oriolus oriolus"],
    "golden pheasant": ["chrysolophus pictus"],
    "golden polypody": ["phlebodium aureum", "polypodium aureum", "serpent fern"],
    "golden pothos": ["epipremnum aureum", "ivy arum", "pothos", "scindapsus aureus"],
    "golden saxifrage": ["golden spleen"],
    "golden section": ["golden mean"],
    "golden shiner": ["notemigonus crysoleucas"],
    "golden shower tree": ["canafistola", "canafistula", "cassia fistula", "drumstick tree", "pudding pipe tree", "purging cassia"],
    "golden star": ["bloomeria crocea", "golden stars"],
    "golden wattle": ["acacia pycnantha"],
    "golden willow": ["salix alba vitellina", "salix vitellina"],
    "golden yarrow": ["eriophyllum lanatum"],
    "goldeneye": ["bucephela clangula", "whistler"],
    "goldenseal": ["golden seal", "hydrastis canadensis", "turmeric root", "yellow root"],
    "goldfields": ["lasthenia chrysostoma"],
    "goldfinch": ["carduelis carduelis"],
    "goldfish": ["carassius auratus"],
    "goldfish bowl": ["fish bowl", "fishbowl"],
    "goldilocks": ["aster linosyris", "goldilocks aster", "linosyris vulgaris"],
    "golding": ["sir william gerald golding", "william golding"],
    "goldman": ["emma goldman"],
    "goldmark": ["peter carl goldmark", "peter goldmark"],
    "goldmine": ["gold mine"],
    "goldoni": ["carlo goldoni"],
    "goldplate": ["gold plate"],
    "goldsmith": ["oliver goldsmith"],
    "goldthread": ["coptis groenlandica", "coptis trifolia groenlandica", "golden thread"],
    "goldwyn": ["sam goldwyn", "samuel goldwyn"],
    "golf": ["golf game"],
    "golf club": ["club"],
    "golf course": ["links course"],
    "golf pro": ["professional golfer"],
    "golf range": ["driving range"],
    "golf stroke": ["golf shot", "swing"],
    "golfcart": ["golf cart"],
    "golfer": ["golf player", "linksman"],
    "golgi": ["camillo golgi"],
    "golgi body": ["dictyosome", "golgi apparatus", "golgi complex"],
    "goliath frog": ["rana goliath"],
    "golliwog": ["golliwogg"],
    "gombrowicz": ["witold gombrowicz"],
    "gomorrah": ["gomorrha"],
    "gompers": ["samuel gompers"],
    "gomphotheriidae": ["family gomphotheriidae"],
    "gomphotherium": ["genus gomphotherium"],
    "gomphrena": ["genus gomphrena"],
    "gonad": ["sex gland"],
    "gonadotropic": ["gonadotrophic"],
    "gonadotropin": ["gonadotrophic hormone", "gonadotrophin", "gonadotropic hormone"],
    "goncalo alves": ["astronium fraxinifolium"],
    "goncourt": ["jules alfred huot de goncourt", "jules de goncourt"],
    "gondang wax": ["fig wax"],
    "gondola car": ["gondola"],
    "gondolier": ["gondoliere"],
    "goner": ["toast"],
    "gongora": ["luis de gongora y argote"],
    "gonif": ["ganef", "ganof", "goniff"],
    "goniopteris": ["genus goniopteris"],
    "gonne": ["maud gonne"],
    "gonococcus": ["neisseria gonorrhoeae"],
    "gonorhynchidae": ["family gonorhynchidae"],
    "gonorhynchus": ["genus gonorhynchus"],
    "gonorrhea": ["clap", "gonorrhoea"],
    "good": ["goodness"],
    "good afternoon": ["afternoon"],
    "good continuation": ["continuation", "law of continuation"],
    "good faith": ["straightness"],
    "good fortune": ["good luck", "luckiness"],
    "good health": ["healthiness"],
    "good humor": ["amiability", "good humour", "good temper"],
    "good luck": ["fluke", "good fortune"],
    "good morning": ["morning"],
    "good old boy": ["good ole boy"],
    "good time": ["blast"],
    "good will": ["goodwill"],
    "goodall": ["jane goodall"],
    "goodeniaceae": ["family goodeniaceae", "goodenia family"],
    "goodly": ["goodish", "healthy", "hefty", "respectable", "sizable", "sizeable", "tidy"],
    "goodman": ["benjamin david goodman", "benny goodman", "king of swing"],
    "goodyear": ["charles goodyear"],
    "goodyera": ["genus goodyera"],
    "gooey": ["icky"],
    "goofproof": ["foolproof"],
    "googly": ["bosie", "bosie ball"],
    "goosander": ["mergus merganser"],
    "goose barnacle": ["gooseneck barnacle", "lepas fascicularis"],
    "goose grass": ["panicum texanum", "texas millet"],
    "gooseberry": ["gooseberry bush", "ribes grossularia"],
    "goosefish": ["allmouth", "angler", "angler fish", "anglerfish", "lophius americanus", "lotte", "monkfish"],
    "gooseneck loosestrife": ["lysimachia clethroides duby"],
    "gopher": ["pocket gopher", "pouched rat"],
    "gopher snake": ["pituophis melanoleucus"],
    "gopher tortoise": ["gopher", "gopher turtle", "gopherus polypemus"],
    "gopherus": ["genus gopherus"],
    "goral": ["naemorhedus goral"],
    "gorbachev": ["mikhail gorbachev", "mikhail sergeyevich gorbachev"],
    "gordimer": ["nadine gordimer"],
    "gore": ["al gore"],
    "gorgas": ["william crawford gorgas"],
    "gorge": ["binge", "englut", "engorge", "glut", "gormandise", "gormandize", "gourmandize", "ingurgitate", "overeat", "overgorge", "overindulge", "pig out", "satiate", "scarf out", "stuff"],
    "gorgeously": ["magnificently", "resplendently", "splendidly"],
    "gorgerin": ["necking"],
    "gorgonacea": ["gorgoniacea", "suborder gorgonacea", "suborder gorgoniacea"],
    "gorgonian": ["gorgonian coral"],
    "gorgonocephalus": ["genus gorgonocephalus"],
    "gorilla": ["gorilla gorilla"],
    "goring": ["goering", "hermann goering", "hermann goring", "hermann wilhelm goring"],
    "gorky": ["aleksey maksimovich peshkov", "aleksey maximovich peshkov", "gorki", "maksim gorky", "maxim gorki"],
    "gorse": ["furze", "irish gorse", "ulex europaeus", "whin"],
    "gory": ["butcherly", "sanguinary", "sanguineous", "slaughterous"],
    "goshawk": ["accipiter gentilis"],
    "gospel": ["gospel singing"],
    "gossip": ["gossiper", "gossipmonger", "newsmonger", "rumormonger", "rumourmonger"],
    "gossiping": ["gossipmongering"],
    "gossypium": ["genus gossypium"],
    "goteborg": ["goeteborg", "gothenburg"],
    "gothic": ["black letter"],
    "gotterdammerung": ["ragnarok", "twilight of the gods"],
    "gouda": ["gouda cheese"],
    "goudy": ["frederic goudy", "frederic william goudy"],
    "gouge": ["force out"],
    "goulash": ["gulyas", "hungarian goulash"],
    "gould": ["stephen jay gould"],
    "gounod": ["charles francois gounod"],
    "gourd": ["gourd vine"],
    "gout": ["gouty arthritis", "urarthritis"],
    "govern": ["rule"],
    "government": ["authorities", "regime"],
    "government accounting office": ["gao", "united states government accounting office"],
    "government income": ["government revenue"],
    "government officials": ["officialdom"],
    "government security": ["agency security"],
    "governor": ["regulator"],
    "gowen cypress": ["cupressus goveniana"],
    "gown": ["scrubs", "surgical gown"],
    "goya": ["francisco de goya", "francisco goya", "francisco jose de goya", "francisco jose de goya y lucientes", "goya y lucientes"],
    "grab": ["seize"],
    "grace": ["saving grace", "state of grace"],
    "grace note": ["acciaccatura", "appoggiatura"],
    "graceless": ["unpleasing"],
    "gracelessness": ["ungracefulness"],
    "gracilariid": ["gracilariid moth"],
    "gracilariidae": ["family gracilariidae", "gracillariidae"],
    "gracile": ["willowy"],
    "graciously": ["gracefully"],
    "grackle": ["crow blackbird"],
    "gracula": ["genus gracula"],
    "grad": ["grade"],
    "gradation": ["step"],
    "gradational": ["gradatory", "graduated"],
    "grade": ["mark", "score"],
    "grade point average": ["gpa"]
}
