synonyms = {
    "buckminsterfullerene": ["buckyball"],
    "buckthorn berry": ["yellow berry"],
    "buckwheat": ["fagopyrum esculentum", "polygonum fagopyrum"],
    "bucolic": ["pastoral"],
    "bud brush": ["artemis spinescens", "bud sagebrush"],
    "budapest": ["capital of hungary", "hungarian capital"],
    "buddha": ["gautama", "gautama buddha", "gautama siddhartha", "siddhartha"],
    "buddhist": ["buddhistic"],
    "buddy": ["brother", "chum", "crony", "pal", "sidekick"],
    "budge": ["don budge", "john donald budge"],
    "budgerigar": ["budgereegah", "budgerygah", "budgie", "grass parakeet", "lovebird", "melopsittacus undulatus", "shell parakeet"],
    "budorcas": ["genus budorcas"],
    "buenos aires": ["capital of argentina"],
    "buff": ["burnish", "furbish"],
    "buff-colored": ["buff-coloured"],
    "buffalo bur": ["solanum rostratum"],
    "buffalo carpet beetle": ["anthrenus scrophulariae"],
    "buffalo clover": ["trifolium reflexum", "trifolium stoloniferum"],
    "buffalo fish": ["buffalofish"],
    "buffalo grass": ["buchloe dactyloides"],
    "buffalo nut": ["elk nut", "oil nut"],
    "buffel grass": ["cenchrus ciliaris", "pennisetum cenchroides"],
    "buffer": ["buffer storage", "buffer store"],
    "buffer state": ["buffer country"],
    "buffer zone": ["buffer"],
    "buffered aspirin": ["bufferin"],
    "buffet": ["batter", "knock about"],
    "buffeted": ["storm-tossed", "tempest-swept", "tempest-tossed", "tempest-tost"],
    "bufflehead": ["bucephela albeola", "butterball", "dipper"],
    "buffoonery": ["clowning", "frivolity", "harlequinade", "japery", "prank"],
    "buffoonish": ["clownish", "clownlike", "zany"],
    "bufonidae": ["family bufonidae"],
    "bug": ["glitch"],
    "bugbear": ["hobgoblin"],
    "bugger all": ["fanny adams", "fuck all", "sweet fanny adams"],
    "buggy": ["roadster"],
    "bugle": ["bugleweed"],
    "bugleweed": ["lycopus virginicus"],
    "bugloss": ["alkanet", "anchusa officinalis"],
    "build": ["establish"],
    "build up": ["build", "ramp up", "work up"],
    "builder": ["detergent builder"],
    "building": ["edifice"],
    "building complex": ["complex"],
    "building supply store": ["building supply house"],
    "built": ["reinforced"],
    "built-in": ["constitutional", "inbuilt", "inherent", "integral"],
    "bujumbura": ["capital of burundi", "usumbura"],
    "bukharin": ["nikolai ivanovich bukharin"],
    "bulbar conjunctiva": ["conjunctival layer of bulb", "tunica conjunctiva bulbi"],
    "bulbil": ["bulblet"],
    "bulblet fern": ["berry fern", "bulblet bladder fern", "cystopteris bulbifera"],
    "bulblike": ["bulb-shaped", "bulbous"],
    "bulgaria": ["republic of bulgaria"],
    "bulge": ["bag"],
    "bulgur": ["bulghur", "bulgur wheat"],
    "bulimarexia": ["binge-purge syndrome", "binge-vomit syndrome", "bulima nervosa"],
    "bulimia": ["binge-eating syndrome"],
    "bulk": ["mass", "volume"],
    "bulkiness": ["massiveness"],
    "bull": ["bull through"],
    "bull run": ["battle of bull run"],
    "bull shark": ["carcharhinus leucas", "cub shark"],
    "bull snake": ["bull-snake"],
    "bull thistle": ["boar thistle", "cirsium lanceolatum", "cirsium vulgare", "spear thistle"],
    "bull's eye": ["bull"],
    "bullace": ["prunus insititia"],
    "bullbrier": ["briar", "brier", "catbrier", "greenbrier", "horse brier", "horse-brier", "smilax rotundifolia"],
    "bulldog": ["english bulldog"],
    "bulldog clip": ["alligator clip"],
    "bulldozer": ["dozer"],
    "bullet": ["slug"],
    "bullet train": ["bullet"],
    "bulletin board": ["notice board"],
    "bulletin board system": ["bbs", "bulletin board", "electronic bulletin board"],
    "bullfight": ["corrida"],
    "bullfighter": ["toreador"],
    "bullfighting": ["tauromachy"],
    "bullfinch": ["charles bullfinch"],
    "bullfrog": ["rana catesbeiana"],
    "bullhead": ["bullhead catfish"],
    "bullheaded": ["bullet-headed", "pigheaded"],
    "bullhorn": ["loud hailer", "loud-hailer"],
    "bullnose": ["bullnosed plane"],
    "bullock": ["steer"],
    "bullock's heart": ["annona reticulata", "bullock heart", "bullock's heart tree"],
    "bullock's oriole": ["icterus galbula bullockii"],
    "bullpen": ["detention cell", "detention centre"],
    "bullshit": ["bull", "crap", "dogshit", "horseshit", "irish bull", "shit"],
    "bullterrier": ["bull terrier"],
    "bully": ["hooligan", "roughneck", "rowdy", "ruffian", "tough", "yob", "yobbo", "yobo"],
    "bully beef": ["corn beef", "corned beef"],
    "bullying": ["intimidation"],
    "bulnesia": ["genus bulnesia"],
    "bulrush": ["bullrush", "common rush", "juncus effusus", "soft rush"],
    "bultmann": ["rudolf bultmann", "rudolf karl bultmann"],
    "bum": ["arse about", "arse around", "bum about", "bum around", "frig around", "fuck off", "loaf", "loll", "loll around", "lounge about", "lounge around", "waste one's time"],
    "bumble": ["falter", "stammer", "stutter"],
    "bumblebee": ["humblebee"],
    "bumbling": ["bungling", "butterfingered", "ham-fisted", "ham-handed", "handless", "heavy-handed", "left-handed"],
    "bumelia": ["genus bumelia"],
    "bumf": ["bumph"],
    "bump": ["knock"],
    "bumper car": ["dodgem"],
    "bumpkinly": ["hick", "rustic", "unsophisticated"],
    "bumptious": ["self-assertive"],
    "bumptiousness": ["cockiness", "forwardness", "pushiness"],
    "bun": ["roll"],
    "buna": ["buna rubber"],
    "bunch": ["bunch up", "bundle", "clump", "cluster"],
    "bunch together": ["bunch", "bunch up"],
    "bunchberry": ["cornus canadensis", "crackerberry", "dwarf cornel", "pudding berry"],
    "bunche": ["ralph bunche", "ralph johnson bunche"],
    "bunchgrass": ["bunch grass"],
    "bunco": ["bunco game", "bunko", "bunko game", "con", "con game", "confidence game", "confidence trick", "flimflam", "gyp", "hustle", "sting"],
    "bundle": ["bundle up", "roll up"],
    "bunfight": ["bun-fight"],
    "bung": ["spile"],
    "bungalow": ["cottage"],
    "bungarus": ["genus bungarus"],
    "bungee": ["bungee cord"],
    "bungled": ["botched"],
    "bungler": ["blunderer", "botcher", "bumbler", "butcher", "fuckup", "fumbler", "sad sack", "stumbler"],
    "bungling": ["clumsy", "fumbling", "incompetent"],
    "bunji-bunji": ["flindersia schottiana"],
    "bunk": ["buncombe", "bunkum", "guff", "hogwash", "rot"],
    "bunk bed": ["bunk"],
    "bunk off": ["play hooky"],
    "bunker": ["dugout"],
    "bunker buster": ["gbu-28", "guided bomb unit-28"],
    "bunker hill": ["battle of bunker hill"],
    "bunny": ["bunny girl"],
    "bunsen": ["robert bunsen", "robert wilhelm bunsen"],
    "bunsen burner": ["bunsen", "etna"],
    "bunt": ["drag a bunt"],
    "bunuel": ["luis bunuel"],
    "bunya bunya": ["araucaria bidwillii", "bunya bunya tree"],
    "bunyan": ["john bunyan"],
    "buoy": ["buoy up"],
    "buoyancy": ["perkiness"],
    "buoyant": ["floaty"],
    "buoyantly": ["chirpily"],
    "buphthalmum": ["genus buphthalmum"],
    "bur": ["burr"],
    "bur marigold": ["beggar's-ticks", "beggar-ticks", "burr marigold", "sticktight"],
    "bur oak": ["burr oak", "mossy-cup oak", "mossycup oak", "quercus macrocarpa"],
    "bura": ["pabir"],
    "burbage": ["richard burbage"],
    "burbank": ["luther burbank"],
    "burbling": ["burbly", "effusive", "gushing"],
    "burbot": ["cusk", "eelpout", "ling", "lota lota"],
    "burden": ["burthen", "weight", "weight down"],
    "burdened": ["heavy-laden", "loaded down"],
    "burdenless": ["unburdened"],
    "burdensome": ["onerous", "taxing"],
    "burdensomeness": ["heaviness", "onerousness", "oppressiveness"],
    "burdock": ["clotbur"],
    "bureau of alcohol tobacco and firearms": ["atf"],
    "bureau of customs": ["customs bureau", "customs service", "uscb"],
    "bureau of diplomatic security": ["ds"],
    "bureau of intelligence and research": ["inr"],
    "bureau of justice assistance": ["bja"],
    "bureau of justice statistics": ["bjs"],
    "bureau of the census": ["census bureau"],
    "bureaucracy": ["bureaucratism"],
    "bureaucrat": ["administrative official"],
    "bureaucratic procedure": ["red tape"],
    "burette": ["buret"],
    "burger": ["warren burger", "warren e. burger", "warren earl burger"],
    "burgess": ["anthony burgess"],
    "burglarize": ["burglarise", "burgle", "heist"],
    "burgoyne": ["gentleman johnny", "john burgoyne"],
    "burgrass": ["bur grass"],
    "burgundy": ["burgundy wine"],
    "burhinidae": ["family burhinidae"],
    "burhinus": ["genus burhinus"],
    "burial": ["entombment", "inhumation", "interment", "sepulture"],
    "burial chamber": ["sepulcher", "sepulchre", "sepulture"],
    "burial mound": ["barrow", "grave mound", "tumulus"],
    "buried": ["inhumed", "interred"],
    "burk": ["burke", "calamity jane", "martha jane burk", "martha jane burke"],
    "burke": ["edmund burke"],
    "burkina faso": ["upper volta"],
    "burlap": ["gunny"],
    "burma padauk": ["burmese rosewood", "pterocarpus macrocarpus"],
    "burmannia": ["genus burmannia"],
    "burmanniaceae": ["family burmanniaceae"],
    "burmeisteria": ["genus burmeisteria"],
    "burn": ["glow"],
    "burn down": ["burn up", "go up"],
    "burn off": ["burn", "burn up"],
    "burn plant": ["aloe vera"],
    "burnable": ["ignitable", "ignitible"],
    "burned": ["burnt"],
    "burned-out": ["burnt-out"],
    "burnett": ["frances eliza hodgson burnett", "frances hodgson burnett"],
    "burnham": ["daniel hudson burnham"],
    "burning": ["burning at the stake"],
    "burnous": ["burnoose", "burnouse"],
    "burns": ["george burns", "nathan birnbaum"],
    "burnside": ["a. e. burnside", "ambrose everett burnside"],
    "burp": ["belch", "bubble", "eruct"],
    "burp gun": ["machine pistol"],
    "burqa": ["burka"],
    "burr": ["aaron burr"],
    "burrawong": ["macrozamia communis", "macrozamia spiralis"],
    "burroughs": ["william burroughs", "william s. burroughs", "william seward burroughs"],
    "burrow": ["tunnel"],
    "bursa": ["brusa"],
    "bursa omentalis": ["lesser peritoneal cavity", "omental bursa"],
    "bursera": ["genus bursera"],
    "burseraceae": ["family burseraceae", "torchwood family"],
    "bursiform": ["pouch-shaped", "pouchlike", "saclike"],
    "burst": ["bust"],
    "burst in on": ["burst upon"],
    "burt": ["cyril burt", "cyril lodowic burt"],
    "burton": ["richard burton", "sir richard burton", "sir richard francis burton"],
    "burundi": ["republic of burundi"],
    "burweed marsh elder": ["false ragweed", "iva xanthifolia"],
    "bury": ["entomb", "inhume", "inter", "lay to rest"],
    "burying": ["burial"],
    "bus": ["heap", "jalopy"],
    "bus company": ["bus service"],
    "bus fare": ["carfare"],
    "bus terminal": ["bus depot", "bus station", "coach station"],
    "bus topology": ["bus"],
    "busbar": ["bus"],
    "busboy": ["waiter's assistant"],
    "bush": ["dubya", "dubyuh", "george bush", "george w. bush", "george walker bush", "president bush", "president george w. bush"],
    "bush clover": ["lespedeza"],
    "bush hibiscus": ["hibiscus farragei", "radyera farragei"],
    "bush honeysuckle": ["lonicera tatarica", "tartarian honeysuckle"],
    "bush nasturtium": ["tropaeolum minus"],
    "bush poppy": ["tree poppy"],
    "bush vetch": ["vicia sepium"],
    "bush violet": ["browallia"],
    "bush willow": ["combretum erythrophyllum"],
    "bush-league": ["bush"],
    "bushbuck": ["guib", "tragelaphus scriptus"],
    "bushing": ["cylindrical lining"],
    "bushman's poison": ["acocanthera oppositifolia", "acocanthera venenata", "ordeal tree"],
    "bushnell": ["david bushnell", "father of the submarine"],
    "bushtit": ["bush tit"],
    "bushy": ["shaggy", "shaggy-coated", "shaggy-haired"],
    "bushy aster": ["aster dumosus"],
    "business": ["business concern", "business organisation", "business organization", "concern"],
    "business activity": ["commercial activity"],
    "business cycle": ["trade cycle"],
    "business district": ["downtown"],
    "business expense": ["trade expense"],
    "business life": ["professional life"],
    "business loan": ["commercial loan"],
    "business people": ["businesspeople"],
    "businesslike": ["earnest"],
    "businessman": ["man of affairs"],
    "businessmen": ["business community"],
    "businessperson": ["bourgeois"],
    "buskin": ["combat boot", "desert boot", "half boot", "top boot"],
    "busman": ["bus driver"],
    "buspirone": ["buspar"],
    "bust": ["binge", "bout", "tear"],
    "bust up": ["wrack", "wreck"],
    "buster": ["bronco buster", "broncobuster"],
    "bustle": ["bustle about", "hustle"],
    "busy": ["occupy"],
    "busybody": ["nosey-parker", "nosy-parker", "quidnunc"],
    "busyness": ["hum"],
    "busywork": ["make-work"],
    "butacaine": ["butacaine sulfate"],
    "butanone": ["methyl ethyl ketone"],
    "butch": ["dike", "dyke"],
    "butcher": ["slaughter"],
    "butcher board": ["butcher block"],
    "butcher shop": ["meat market"],
    "butcher's broom": ["ruscus aculeatus"],
    "butchery": ["butchering"],
    "butea": ["genus butea"],
    "buteo": ["genus buteo"],
    "butler": ["samuel butler"],
    "butt": ["bunt"],
    "butt joint": ["butt"],
    "butt weld": ["butt-weld"],
    "butt welding": ["butt-welding"],
    "butt-weld": ["buttweld"],
    "butter up": ["brown-nose"],
    "butterbur": ["bog rhubarb", "petasites hybridus", "petasites vulgaris"],
    "buttercup": ["butter-flower", "butterflower", "crowfoot", "goldcup", "kingcup"],
    "butterfield": ["william butterfield"],
    "butterfish": ["stromateid", "stromateid fish"],
    "butterfly": ["butterfly stroke"],
    "butterfly bush": ["buddleia"],
    "butterfly flower": ["poor man's orchid", "schizanthus"],
    "butterfly orchid": ["butterfly orchis", "encyclia venosa", "epidendrum venosum"],
    "butterfly pea": ["clitoria mariana"],
    "butterfly plant": ["phalaenopsis amabilis"],
    "butterfly weed": ["asclepias tuberosa", "chigger flower", "chiggerflower", "indian paintbrush", "orange milkweed", "pleurisy root", "tuber root"],
    "buttermilk biscuit": ["soda biscuit"],
    "butternut": ["butternut tree", "juglans cinerea", "white walnut"],
    "butternut squash": ["cucurbita maxima"],
    "butterweed": ["ragwort", "senecio glabellus"],
    "buttery": ["fulsome", "oily", "oleaginous", "smarmy", "soapy", "unctuous"],
    "buttock": ["cheek"],
    "buttocks": ["arse", "ass", "backside", "behind", "bottom", "bum", "buns", "butt", "can", "derriere", "fanny", "fundament", "hind end", "hindquarters", "keister", "nates", "posterior", "prat", "rear", "rear end", "rump", "seat", "stern", "tail", "tail end", "tooshie", "tush"],
    "button fern": ["pellaea rotundifolia"],
    "button pink": ["dianthus latifolius"],
    "button quail": ["bustard quail", "button-quail", "hemipode"],
    "button snakeroot": ["eryngium aquaticum"],
    "button tree": ["button mangrove", "conocarpus erectus"],
    "button-down": ["buttoned-down", "conservative"],
    "buttoned": ["fastened"],
    "buttonhole": ["button hole"],
    "buttress": ["buttressing"],
    "butut": ["butat"],
    "butyl alcohol": ["butanol"],
    "butyl nitrite": ["isobutyl nitrite"],
    "butylene": ["butene"],
    "butyric acid": ["butanoic acid"],
    "buxaceae": ["box family", "family buxaceae"],
    "buxom": ["zaftig", "zoftig"],
    "buxus": ["genus buxus"],
    "buy": ["purchase"],
    "buy back": ["repurchase"],
    "buy it": ["pip out"],
    "buy off": ["pay off"],
    "buyer": ["emptor", "purchaser", "vendee"],
    "buyer's market": ["buyers' market", "soft market"],
    "buying": ["purchasing"],
    "buzz": ["bombilate", "bombinate"],
    "buzz bomb": ["doodlebug", "flying bomb", "robot bomb", "v-1"],
    "buzzard": ["cathartes aura", "turkey buzzard", "turkey vulture"],
    "buzzword": ["cant"],
    "bvd": ["bvd's"],
    "by": ["past"],
    "by and by": ["later"],
    "by and large": ["generally", "more often than not", "mostly"],
    "by chance": ["accidentally", "circumstantially", "unexpectedly"],
    "by far": ["far and away", "out and away"],
    "by heart": ["by memory"],
    "by hook or by crook": ["by any means"],
    "by inches": ["by small degrees", "little by little"],
    "by no means": ["not by a blame sight", "not by a long sight"],
    "by rights": ["properly"],
    "by the piece": ["one by one"],
    "by the way": ["apropos", "by the bye", "incidentally"],
    "by word of mouth": ["viva voce"],
    "by-catch": ["bycatch"],
    "by-election": ["bye-election"],
    "by-line": ["credit line"],
    "by-product": ["byproduct"],
    "bydgoszcz": ["bromberg"],
    "bye": ["pass"],
    "byelorussian": ["belorussian", "white russian"],
    "bygone": ["water under the bridge"],
    "bypass": ["get around", "go around", "short-circuit"],
    "bypass condenser": ["bypass capacitor"],
    "byrd": ["william byrd"],
    "byron": ["lord george gordon byron", "sixth baron byron of rochdale"],
    "byssus": ["beard"],
    "byway": ["bypath", "byroad"],
    "byzantine": ["convoluted", "involved", "knotty", "tangled", "tortuous"],
    "byzantine empire": ["byzantium", "eastern roman empire"],
    "c major": ["c major scale", "scale of c major"],
    "c-horizon": ["c horizon"],
    "c-reactive protein": ["crp"],
    "cab": ["cabriolet"],
    "cab fare": ["taxi fare"],
    "cabal": ["camarilla", "faction", "junto"],
    "cabala": ["cabbala", "cabbalah", "kabala", "kabbala", "kabbalah", "qabala", "qabalah"],
    "cabalist": ["kabbalist"],
    "cabalistic": ["cryptic", "cryptical", "kabbalistic", "qabalistic", "sibylline"],
    "cabaret": ["club", "night club", "nightclub", "nightspot"],
    "cabbage": ["brassica oleracea", "cultivated cabbage"],
    "cabbage bark": ["andira inermis", "cabbage tree", "cabbage-bark tree"],
    "cabbage palm": ["roystonea oleracea"],
    "cabbage palmetto": ["cabbage palm", "sabal palmetto"],
    "cabbage tree": ["cordyline australis", "grass tree"],
    "cabbageworm": ["pieris rapae"],
    "cabell": ["james branch cabell"],
    "cabernet": ["cabernet sauvignon"],
    "cabin car": ["caboose"],
    "cabin class": ["economy class", "second class"],
    "cabin cruiser": ["cruiser", "pleasure boat", "pleasure craft"],
    "cabinet": ["locker", "storage locker"],
    "cabinetmaker": ["furniture maker"],
    "cabinetmaking": ["joinery"],
    "cabinetwork": ["cabinetry"],
    "cable": ["telegraph", "wire"],
    "cable car": ["car"],
    "cable railway": ["funicular", "funicular railway"],
    "cable television": ["cable"],
    "cabomba": ["genus cabomba"],
    "cabombaceae": ["subfamily cabombaceae", "water-shield family"],
    "cabot": ["sebastian cabot"],
    "cabstand": ["taxi rank", "taxistand"],
    "cacajao": ["genus cacajao"],
    "cacalia": ["genus cacalia"],
    "cacao": ["cacao tree", "chocolate tree", "theobroma cacao"],
    "cacao bean": ["cocoa bean"],
    "cache": ["memory cache"],
    "cachet": ["seal", "seal of approval"],
    "cachexia": ["cachexy", "wasting"],
    "cacicus": ["genus cacicus"],
    "cacique": ["cazique"],
    "cackly": ["squawky"],
    "cacodemon": ["cacodaemon"],
    "cacodemonic": ["cacodaemonic"],
    "cacodyl": ["tetramethyldiarsine"],
    "cacophonous": ["cacophonic"],
    "cactaceae": ["cactus family", "family cactaceae"],
    "cactus mouse": ["peromyscus eremicus"],
    "cacuminal": ["retroflex"],
    "cad": ["blackguard", "bounder", "dog", "heel", "hound"],
    "cadaster": ["cadastre"],
    "cadaver": ["clay", "corpse", "remains", "stiff"],
    "cadaverous": ["cadaveric"],
    "caddie": ["caddy"],
    "caddis fly": ["caddice fly", "caddice-fly", "caddis-fly"],
    "caddish": ["unchivalrous", "ungallant"],
    "caddisworm": ["strawworm"],
    "caddo": ["caddoan", "caddoan language"],
    "caddy": ["tea caddy"],
    "cadence": ["cadency"],
    "cadenced": ["cadent"],
    "cadet": ["plebe"],
    "cadmium": ["atomic number 48", "cd"],
    "cadra": ["genus cadra"],
    "caducous": ["shed"],
    "caecilian": ["blindworm"],
    "caeciliidae": ["caeciliadae", "family caeciliadae", "family caeciliidae"],
    "caenolestes": ["genus caenolestes"],
    "caenolestidae": ["family caenolestidae"],
    "caesalpinia": ["genus caesalpinia"],
    "caesalpiniaceae": ["family caesalpiniaceae"],
    "caesalpinioideae": ["subfamily caesalpinioideae"],
    "caesar": ["sid caesar", "sidney caesar"],
    "caesarian": ["caesarean"],
    "caespitose": ["cespitose", "tufted"],
    "cafe": ["coffee bar", "coffee shop", "coffeehouse"],
    "cafe noir": ["demitasse"],
    "cafe royale": ["coffee royal"],
    "caffe latte": ["latte"],
    "caffeine": ["caffein"],
    "caffeine addict": ["caffein addict"],
    "caffeinism": ["caffeine intoxication"],
    "caftan": ["kaftan"],
    "cage": ["cage in"],
    "cagey": ["cagy", "canny", "clever"],
    "cagily": ["circumspectly"],
    "cagliostro": ["count alessandro di cagliostro", "giuseppe balsamo"],
    "cagney": ["james cagney", "jimmy cagney"],
    "caiman": ["cayman"],
    "cairina": ["genus cairina"],
    "cairn": ["cairn terrier"],
    "cairngorm": ["smoky quartz"],
    "cairo": ["al qahira", "capital of egypt", "egyptian capital", "el qahira"],
    "caisson": ["ammunition chest"],
    "cajan pea": ["dahl", "pigeon pea"],
    "cajanus": ["genus cajanus"],
    "cake": ["bar"],
    "cakile": ["genus cakile"],
    "calaba": ["calophyllum calaba", "santa maria tree"],
    "calabar bean": ["ordeal bean"],
    "calabar-bean vine": ["physostigma venenosum"],
    "calabash": ["calabash tree", "crescentia cujete"],
    "calamagrostis": ["genus calamagrostis"],
    "calamintha": ["genus calamintha"],
    "calamity": ["cataclysm", "catastrophe", "disaster", "tragedy"],
    "calamus": ["genus calamus"],
    "calandrinia": ["genus calandrinia"],
    "calash": ["caleche"],
    "calcareous": ["chalky"],
    "calcarine sulcus": ["calcarine fissure"],
    "calced": ["shod"],
    "calceolaria": ["slipperwort"],
    "calceolate": ["calceiform"],
    "calcitonin": ["thyrocalcitonin"],
    "calcium": ["atomic number 20", "ca"],
    "calcium blocker": ["calcium-channel blocker"],
    "calcium hydride": ["hydrolith"],
    "calcium hydroxide": ["calcium hydrate", "caustic lime", "hydrated lime", "lime", "lime hydrate", "slaked lime"],
    "calcium ion": ["factor iv"],
    "calcium oxide": ["burnt lime", "calcined lime", "calx", "fluxing lime", "lime", "quicklime", "unslaked lime"],
    "calcium stearate": ["calcium octadecanoate"],
    "calcium sulphate": ["calcium sulfate"],
    "calcium-cyanamide": ["cyanamide"],
    "calculate": ["aim", "direct"],
    "calculating": ["calculative", "conniving", "scheming", "shrewd"],
    "calculation": ["computation", "figuring", "reckoning"],
    "calculator": ["computer", "estimator", "figurer", "reckoner"],
    "calculus": ["concretion"],
    "calder": ["alexander calder"],
    "calderon": ["calderon de la barca", "pedro calderon de la barca"],
    "caldron": ["cauldron"],
    "caldwell": ["erskine caldwell", "erskine preston caldwell"],
    "calefacient": ["warming"],
    "calefaction": ["incalescence"],
    "calefactory": ["calefactive"],
    "calendar day": ["civil day"],
    "calendar month": ["month"],
    "calendar year": ["civil year"],
    "calendric": ["calendrical"],
    "calf": ["calfskin"],
    "calibrate": ["fine-tune", "graduate"],
    "calibrated": ["graduated"],
    "calibration": ["standardisation", "standardization"],
    "caliche": ["hardpan"],
    "calidris": ["genus calidris"],
    "california": ["ca", "calif.", "golden state"],
    "california black oak": ["quercus kelloggii"],
    "california black walnut": ["juglans californica"],
    "california bluebell": ["phacelia minor", "phacelia whitlavia", "whitlavia"],
    "california box elder": ["acer negundo californicum"],
    "california condor": ["gymnogyps californianus"],
    "california four o'clock": ["mirabilis californica", "mirabilis laevis"],
    "california fuchsia": ["epilobium canum canum", "humming bird's trumpet", "zauschneria californica"],
    "california lady's slipper": ["cypripedium californicum"],
    "california laurel": ["california bay tree", "california olive", "mountain laurel", "oregon myrtle", "pepperwood", "sassafras laurel", "spice tree", "umbellularia californica"],
    "california newt": ["taricha torosa"],
    "california nutmeg": ["nutmeg-yew", "torreya californica"],
    "california personality inventory": ["cpi"],
    "california pitcher plant": ["darlingtonia californica"],
    "california poppy": ["eschscholtzia californica"],
    "california privet": ["ligustrum ovalifolium"],
    "california quail": ["lofortyx californicus"],
    "california redwood": ["coast redwood", "sequoia sempervirens"],
    "california sagebrush": ["artemisia californica", "california sage"],
    "california sea lion": ["zalophus californianus", "zalophus californicus"],
    "california single-leaf pinyon": ["pinus californiarum"],
    "california sycamore": ["platanus racemosa"],
    "california whipsnake": ["masticophis lateralis", "striped racer"],
    "california white oak": ["quercus lobata", "roble", "valley oak", "valley white oak"],
    "californium": ["atomic number 98", "cf"],
    "caligula": ["gaius", "gaius caesar"],
    "caliper": ["calliper"],
    "caliph": ["calif", "kalif", "kaliph", "khalif", "khalifah"],
    "calisaya": ["cinchona calisaya", "cinchona ledgeriana", "cinchona officinalis"],
    "calisthenics": ["callisthenics"],
    "calixtus ii": ["guy of burgundy"],
    "calixtus iii": ["alfonso borgia", "borgia"],
    "calk": ["calkin"],
    "call": ["call in"],
    "call at": ["out in"],
    "call center": ["call centre"],
    "call it quits": ["call it a day"],
    "call loan": ["demand loan"],
    "call mark": ["call number", "pressmark"],
    "call on": ["turn"],
    "call on the carpet": ["bawl out", "berate", "call down", "chew out", "chew up", "chide", "dress down", "have words", "jaw", "lambast", "lambaste", "lecture", "rag", "rebuke", "remonstrate", "reprimand", "reproof", "scold", "take to task", "trounce"],
    "call option": ["call"],
    "call the shots": ["call the tune", "wear the trousers"],
    "call up": ["mobilise", "mobilize", "rally"],
    "calla": ["genus calla"],
    "calla lily": ["arum lily", "calla", "zantedeschia aethiopica"],
    "callas": ["maria callas", "maria meneghini callas"],
    "caller": ["caller-out"],
    "callicebus": ["genus callicebus"],
    "calligrapher": ["calligraphist"],
    "calligraphic": ["calligraphical"],
    "calligraphy": ["chirography", "penmanship"],
    "callimorpha": ["genus callimorpha"],
    "callinectes": ["genus callinectes"],
    "calling card": ["phone card"],
    "calling into question": ["demand for explanation"],
    "callionymidae": ["family callionymidae"],
    "calliope": ["steam organ"],
    "calliophis": ["callophis", "genus calliophis", "genus callophis"],
    "calliopsis": ["coreopsis tinctoria"],
    "calliphora": ["genus calliphora"],
    "calliphoridae": ["family calliphoridae"],
    "callipygian": ["callipygous"],
    "callirhoe": ["genus callirhoe"],
    "callisaurus": ["genus callisaurus"],
    "callistephus": ["genus callistephus"],
    "callithricidae": ["family callithricidae"],
    "callithrix": ["genus callithrix"],
    "callithump": ["callathump", "callithump parade"],
    "callitrichaceae": ["family callitrichaceae"],
    "callitriche": ["genus callitriche"],
    "callitris": ["genus callitris"],
    "callorhinus": ["genus callorhinus"],
    "callosity": ["callus"],
    "callosotomy": ["callosectomy"],
    "callous": ["cauterise", "cauterize"],
    "calloused": ["callous", "thickened"],
    "callously": ["unfeelingly"],
    "callowness": ["jejuneness", "juvenility"],
    "calluna": ["genus calluna"],
    "calm": ["calm down", "lull", "quiet", "quieten", "still", "tranquilize", "tranquillise", "tranquillize"],
    "calm air": ["calm"],
    "calocarpum": ["genus calocarpum"],
    "calocedrus": ["genus calocedrus"],
    "calochortus": ["genus calochortus"],
    "calomel": ["mercurous chloride"],
    "caloosahatchee": ["caloosahatchee river"],
    "calophyllum": ["genus calophyllum"],
    "calopogon": ["genus calopogon"],
    "calorie": ["kilocalorie", "kilogram calorie", "large calorie", "nutritionist's calorie"],
    "calostomataceae": ["family calostomataceae"],
    "calpac": ["calpack", "kalpac"],
    "calque": ["calque formation", "loan translation"],
    "caltha": ["genus caltha"],
    "caltrop": ["devil's weed", "tribulus terestris"],
    "calumet": ["peace pipe", "pipe of peace"],
    "calumniatory": ["calumnious", "defamatory", "denigrating", "denigrative", "denigratory", "libellous", "libelous", "slanderous"],
    "calvaria": ["skullcap"],
    "calvary": ["golgotha"],
    "calvary clover": ["medicago echinus", "medicago intertexta"],
    "calvary cross": ["cross of calvary"],
    "calvatia": ["genus calvatia"],
    "calve": ["break up"],
    "calves' liver": ["calf's liver"],
    "calvin": ["melvin calvin"],
    "calvinist": ["genevan"],
    "calvinistic baptist": ["particular baptist"],
    "calvino": ["italo calvino"],
    "calycanthaceae": ["calycanthus family", "family calycanthaceae", "strawberry-shrub family"],
    "calycanthus": ["genus calycanthus"],
    "calyceal": ["calycinal", "calycine"],
    "calycophyllum": ["genus calycophyllum"],
    "calycular": ["calicular"],
    "calyculate": ["calycled"],
    "calyculus": ["caliculus", "calycle"],
    "calymmatobacterium": ["genus calymmatobacterium"],
    "calypso": ["calypso bulbosa", "fairy-slipper"],
    "calystegia": ["genus calystegia"],
    "cam": ["cam river", "river cam"],
    "camail": ["aventail", "ventail"],
    "camas": ["camash", "camass", "camosh", "quamash"],
    "camassia": ["genus camassia", "genus quamassia", "quamassia"],
    "cambarus": ["genus cambarus"],
    "cambodia": ["kampuchea", "kingdom of cambodia"],
    "cambodian": ["kampuchean"],
    "cambrian": ["cambrian period"],
    "cambridge university": ["cambridge"],
    "camel's hair": ["camelhair"],
    "camelidae": ["family camelidae"],
    "camelina": ["false flax", "genus camelina"],
    "camellia": ["camelia"],
    "camelus": ["genus camelus"],
    "camera": ["photographic camera"],
    "camera lens": ["optical lens"],
    "cameraman": ["camera operator", "cinematographer"],
    "cameroon": ["cameroun", "republic of cameroon"],
    "camisole": ["underbodice"],
    "camouflage": ["camo"],
    "camp": ["bivouac", "camp out", "encamp", "tent"],
    "campaign": ["run"],
    "campaigner": ["candidate", "nominee"],
    "campaigning": ["candidacy", "candidature", "electioneering", "political campaign"],
    "campanile": ["belfry"],
    "campanula": ["bellflower"],
    "campanulaceae": ["bellflower family", "family campanulaceae"],
    "campanulales": ["order campanulales"],
    "campanulate": ["campanular", "campanulated"],
    "campbell": ["joseph campbell"],
    "campephilus": ["genus campephilus"],
    "camper": ["camping bus", "motor home"],
    "camphor daisy": ["haplopappus phyllocephalus"],
    "camphor dune tansy": ["tanacetum camphoratum"],
    "camphor tree": ["cinnamomum camphora"],
    "camping": ["bivouacking", "encampment", "tenting"],
    "camponotus": ["genus camponotus"],
    "campsite": ["bivouac", "campground", "camping area", "camping ground", "camping site", "encampment"],
    "camptosorus": ["genus camptosorus"],
    "campyloneurum": ["genus campyloneurum"],
    "campylorhynchus": ["genus campylorhynchus", "genus heleodytes", "heleodytes"],
    "camus": ["albert camus"],
    "camwood": ["african sandalwood", "baphia nitida"],
    "can": ["put up", "tin"],
    "can opener": ["tin opener"],
    "canaanitic": ["canaanitic language"],
    "canachites": ["genus canachites"],
    "canada anemone": ["anemone canadensis"],
    "canada garlic": ["allium canadense", "meadow leek", "rose leek"],
    "canada ginger": ["asarum canadense", "black snakeroot"],
    "canada jay": ["camp robber", "gray jay", "grey jay", "perisoreus canadensis", "whisker jack"],
    "canada lily": ["lilium canadense", "meadow lily", "wild meadow lily", "wild yellow lily"],
    "canada lynx": ["lynx canadensis"],
    "canada plum": ["prunus nigra"],
    "canada porcupine": ["erethizon dorsatum"],
    "canada thistle": ["cirsium arvense", "creeping thistle"],
    "canada violet": ["tall white violet", "viola canadensis", "white violet"],
    "canada wild rye": ["elymus canadensis"],
    "canadian": ["canadian river"],
    "canadian aspen": ["big-toothed aspen", "bigtooth aspen", "bigtoothed aspen", "large tooth aspen", "large-toothed aspen", "populus grandidentata"],
    "canadian dollar": ["loonie"],
    "canadian falls": ["horseshoe falls"],
    "canadian pondweed": ["elodea canadensis"],
    "canadian security intelligence service": ["csis"],
    "canal": ["canalise", "canalize"],
    "canal boat": ["narrow boat", "narrowboat"],
    "canal of schlemm": ["schlemm's canal", "sinus venosus sclerae"],
    "canalization": ["canalisation"],
    "canandaigua lake": ["lake canandaigua"],
    "cananga": ["canangium", "genus cananga", "genus canangium"],
    "canary": ["canary bird"],
    "canary grass": ["birdseed grass", "phalaris canariensis"],
    "canary island hare's foot fern": ["davallia canariensis"],
    "canary islands": ["canaries"],
    "canary yellow": ["canary"],
    "canarybird flower": ["canary creeper", "canarybird vine", "tropaeolum peregrinum"],
    "canasta": ["basket rummy", "meld"],
    "canavalia": ["genus canavalia"],
    "canberra": ["australian capital", "capital of australia"],
    "cancel": ["offset", "set off"],
    "cancel out": ["wipe out"],
    "cancellate": ["cancellated", "clathrate"],
    "cancer": ["malignant neoplastic disease"],
    "cancerweed": ["cancer weed", "salvia lyrata"],
    "cancridae": ["family cancridae"],
    "cancroid": ["squamous cell carcinoma"],
    "candelabrum": ["candelabra"],
    "candelilla": ["pedilanthus bracteatus", "pedilanthus pavonis"],
    "candid": ["heart-to-heart", "open"],
    "candida albicans": ["monilia albicans"],
    "candidate": ["prospect"],
    "candidiasis": ["monilia disease", "moniliasis"],
    "candied": ["sugar-coated"],
    "candied apple": ["candy apple", "caramel apple", "taffy apple", "toffee apple"],
    "candied fruit": ["crystallized fruit", "succade"],
    "candle": ["candela", "cd", "standard candle"],
    "candlelight": ["candle flame"],
    "candlemas": ["candlemas day", "feb 2"],
    "candlenut": ["aleurites moluccana", "varnish tree"],
    "candlepins": ["candlepin bowling"],
    "candlepower": ["light intensity"],
    "candlestick": ["candle holder"],
    "candor": ["candidness", "candour", "directness", "forthrightness", "frankness"],
    "candy": ["confect"],
    "cane": ["flog", "lambast", "lambaste"],
    "canebrake rattlesnake": ["canebrake rattler", "crotalus horridus atricaudatus"],
    "canella": ["canella bark", "white cinnamon"],
    "canellaceae": ["canella family", "family canellaceae"],
    "canescent": ["hoary"],
    "canetti": ["elias canetti"],
    "canidae": ["family canidae"],
    "canine": ["canine tooth", "cuspid", "dogtooth", "eye tooth", "eyetooth"],
    "canine chorea": ["chorea"],
    "canis": ["genus canis"],
    "canis major": ["great dog"],
    "canis minor": ["little dog"],
    "canistel": ["canistel tree", "pouteria campechiana nervosa"],
    "canister": ["cannister", "tin"],
    "canker": ["canker sore"],
    "cankerous": ["ulcerated", "ulcerous"],
    "canna lily": ["canna generalis"],
    "cannabidaceae": ["family cannabidaceae", "hemp family"],
    "cannabin": ["cannabis resin"],
    "cannabis": ["hemp"],
    "cannaceae": ["family cannaceae"],
    "canned": ["transcribed"],
    "canned food": ["canned foods", "canned goods", "tinned goods"],
    "canned meat": ["tinned meat"],
    "cannibal": ["anthropophagite", "anthropophagus", "man-eater"],
    "cannibalize": ["cannibalise"],
    "cannon": ["shank"],
    "cannon fodder": ["fodder", "fresh fish"],
    "cannonade": ["drumfire"],
    "cannonball": ["cannon ball", "round shot"],
    "cannulate": ["cannulise", "cannulize", "canulate", "intubate"],
    "cannulation": ["cannulisation", "cannulization", "canulation", "canulisation", "canulization", "intubation"],
    "canoeist": ["paddler"],
    "canola oil": ["canola"],
    "canon law": ["ecclesiastical law"],
    "canonic": ["canonical"],
    "canonization": ["canonisation"],
    "canonize": ["canonise"],
    "canonized": ["canonised", "glorified"],
    "canopic jar": ["canopic vase"],
    "canorous": ["songful"],
    "cant": ["cant over", "pitch", "slant", "tilt"],
    "cantabile": ["singing"],
    "cantala": ["cebu maguey", "manila maguey"],
    "cantaloup": ["cantaloupe"],
    "cantaloupe": ["cantaloup", "cantaloup vine", "cantaloupe vine", "cucumis melo cantalupensis"],
    "cantankerous": ["crotchety", "ornery"],
    "cantata": ["oratorio"],
    "canteen": ["mobile canteen"],
    "canter": ["lope"],
    "canterbury bell": ["gloxinia perennis"],
    "cantharellus": ["genus cantharellus"],
    "canticle of simeon": ["nunc dimittis"],
    "cantor": ["hazan"],
    "canute": ["canute the great", "cnut", "knut"],
    "canvas": ["canvass"],
    "canvas tent": ["canvas", "canvass"],
    "canvasback": ["aythya valisineria", "canvasback duck"],
    "canvass": ["canvas"],
    "canyon": ["canon"],
    "canyon oak": ["canyon live oak", "iron oak", "maul oak", "quercus chrysolepis"],
    "canyon treefrog": ["hyla arenicolor"],
    "cap": ["crest"],
    "cap-a-pie": ["from head to toe"],
    "capability": ["capacity"],
    "capable": ["open", "subject"],
    "capaciousness": ["roominess"],
    "capacitance": ["capacity", "electrical capacity"],
    "capacitor": ["capacitance", "condenser", "electrical condenser"],
    "capacity": ["content"],
    "caparison": ["bard", "barde", "dress up"],
    "cape": ["ness"],
    "cape aloe": ["aloe ferox"],
    "cape buffalo": ["synercus caffer"],
    "cape canaveral": ["cape kennedy"],
    "cape forget-me-not": ["anchusa riparia"],
    "cape gooseberry": ["physalis peruviana", "purple ground cherry"],
    "cape jasmine": ["cape jessamine", "gardenia augusta", "gardenia jasminoides"],
    "cape lobster": ["homarus capensis"],
    "cape marigold": ["star of the veldt", "sun marigold"],
    "cape may warbler": ["dendroica tigrina"],
    "cape passero": ["passero cape"],
    "cape province": ["cape colony", "cape of good hope province"],
    "cape tulip": ["haemanthus coccineus"],
    "cape verde": ["republic of cape verde"],
    "cape verde escudo": ["escudo"],
    "cape yellowwood": ["african yellowwood", "podocarpus elongatus"],
    "capek": ["karel capek"],
    "capelin": ["capelan", "caplin"],
    "caper": ["job"],
    "caper spurge": ["euphorbia lathyris", "mole plant", "myrtle spurge"],
    "caper tree": ["bay-leaved caper", "capparis flexuosa"],
    "capercaillie": ["capercailzie", "horse of the wood", "tetrao urogallus"],
    "capet": ["hugh capet"],
    "capillarity": ["capillary action"],
    "capillary": ["capillary vessel"],
    "capital": ["working capital"],
    "capitalism": ["capitalist economy"],
    "capitalist": ["capitalistic"],
    "capitalistic": ["capitalist"],
    "capitalization": ["capitalisation"],
    "capitalize": ["capitalise"],
    "capitate": ["capitate bone", "os capitatum"],
    "capitol": ["capitol building"],
    "capitol hill": ["the hill"],
    "capitonidae": ["family capitonidae"],
    "capitular": ["capitulary"],
    "capitulation": ["fall", "surrender"],
    "capitulum": ["head"],
    "capone": ["al capone", "alphonse capone", "scarface"],
    "caponize": ["caponise"],
    "caporetto": ["battle of caporetto"],
    "capote": ["hooded coat"],
    "capparidaceae": ["caper family", "family capparidaceae"],
    "capparis": ["genus capparis"],
    "cappuccino": ["cappuccino coffee", "coffee cappuccino"],
    "capra": ["frank capra"],
    "caprella": ["genus caprella"],
    "capreolus": ["genus capreolus"],
    "capric acid": ["decanoic acid"],
    "caprice": ["impulse", "whim"],
    "capricious": ["freakish"],
    "capriciously": ["freakishly"],
    "capriciousness": ["unpredictability"],
    "capricorn": ["goat"],
    "capricornis": ["genus capricornis"],
    "capricornus": ["capricorn"],
    "caprifig": ["ficus carica sylvestris"],
    "caprifoliaceae": ["family caprifoliaceae", "honeysuckle family"],
    "caprimulgidae": ["family caprimulgidae"],
    "caprimulgiformes": ["order caprimulgiformes"],
    "caprimulgus": ["genus caprimulgus"],
    "caproic acid": ["hexanoic acid"],
    "caproidae": ["family caproidae"],
    "capromyidae": ["family capromyidae"],
    "capros": ["genus capros"],
    "capsella": ["genus capsella"],
    "capsicum": ["capsicum pepper plant", "pepper"],
    "capsize": ["turn turtle", "turtle"],
    "capstone": ["copestone", "coping stone", "stretcher"],
    "capsulate": ["capsulated"],
    "capsule": ["capsulate", "capsulise", "capsulize"],
    "captain": ["chieftain"],
    "captainship": ["captaincy"],
    "caption": ["legend"],
    "captious": ["faultfinding"],
    "captivated": ["charmed"],
    "captivation": ["enchantment", "enthrallment", "fascination"],
    "captive": ["confined", "imprisoned", "jailed"],
    "captivity": ["immurement", "imprisonment", "incarceration"],
    "captopril": ["capoten"],
    "captor": ["capturer"],
    "capture": ["becharm", "beguile", "bewitch", "captivate", "catch", "charm", "enamor", "enamour", "enchant", "entrance", "fascinate", "trance"],
    "capuchin": ["cebus capucinus", "ringtail"],
    "capulin": ["capulin tree", "prunus capuli"],
    "capybara": ["capibara", "hydrochoerus hydrochaeris"],
    "car": ["gondola"],
    "car battery": ["automobile battery"],
    "car boot sale": ["boot sale"],
    "car company": ["auto company"],
    "car manufacturer": ["auto maker", "auto manufacturer", "automaker", "car maker", "carmaker"],
    "car rental": ["hire car", "rent-a-car", "self-drive", "u-drive", "you-drive"],
    "car tire": ["auto tire", "automobile tire", "rubber tire"],
    "carabidae": ["family carabidae"],
    "carabiner": ["karabiner", "snap ring"],
    "caracal": ["desert lynx", "lynx caracal"],
    "caracas": ["capital of venezuela"],
    "caracolito": ["ruptiliocarpon caracolito"],
    "carafe": ["decanter"],
    "carambola": ["averrhoa carambola", "carambola tree"],
    "caramel": ["caramelized sugar"],
    "caramelize": ["caramelise"],
    "carancha": ["polyborus plancus"],
    "caranday": ["caranda", "caranda palm", "copernicia alba", "copernicia australis", "wax palm"],
    "carangid fish": ["carangid"],
    "carangidae": ["family carangidae"],
    "caranx": ["genus caranx"],
    "carapace": ["cuticle", "shell", "shield"],
    "carapidae": ["family carapidae"],
    "carassius": ["genus carassius"],
    "caravaggio": ["michelangelo merisi da caravaggio"],
    "caravan": ["train", "wagon train"],
    "caravansary": ["caravan inn", "caravanserai", "khan"],
    "caraway": ["carum carvi"],
    "carbineer": ["carabineer", "carabinier"],
    "carbohydrate": ["saccharide", "sugar"],
    "carbohydrate loading": ["carbo loading"],
    "carbolic acid": ["hydroxybenzene", "oxybenzene", "phenol", "phenylic acid"],
    "carbon": ["atomic number 6"],
    "carbon arc lamp": ["carbon arc"],
    "carbon black": ["crock", "lampblack", "smut", "soot"],
    "carbon dioxide": ["carbonic acid gas", "co2"],
    "carbon monoxide": ["carbon monoxide gas", "co"],
    "carbon nanotube": ["nanotube"],
    "carbon paper": ["carbon"],
    "carbon tetrachloride": ["carbon tet", "perchloromethane", "tetrachloromethane"],
    "carbonaceous": ["carbonic", "carboniferous", "carbonous"],
    "carbonado": ["black diamond"],
    "carboniferous": ["carboniferous period"],
    "carbonization": ["carbonisation"],
    "carbonize": ["carbonise", "carburise", "carburize"],
    "carbonnade flamande": ["belgian beef stew"],
    "carbonyl": ["carbonylic"],
    "carboxyl": ["carboxyl group"],
    "carbuncled": ["carbuncular"],
    "carburetor": ["carburettor"],
    "carcase": ["carcass"],
    "carcharhinidae": ["family carcharhinidae"],
    "carcharhinus": ["genus carcharhinus"],
    "carcharias": ["genus carcharias", "genus odontaspis", "odontaspis"],
    "carchariidae": ["family carchariidae", "family odontaspididae", "odontaspididae"],
    "carcharodon": ["genus carcharodon"],
    "carcinoma in situ": ["preinvasive cancer"],
    "card": ["scorecard"],
    "card catalog": ["card catalogue"],
    "card game": ["cards"],
    "card index": ["card catalog", "card catalogue"],
    "cardamine": ["genus cardamine"],
    "cardamom": ["cardamon", "elettaria cardamomum"],
    "cardboard": ["composition board"],
    "cardiac arrhythmia": ["arrhythmia"],
    "cardiac glycoside": ["cardiac glucoside"],
    "cardiac massage": ["heart massage"],
    "cardiac monitor": ["heart monitor"],
    "cardiac muscle": ["heart muscle"],
    "cardiac plexus": ["plexus cardiacus"],
    "cardiac rhythm": ["heart rhythm"],
    "cardigan": ["cardigan welsh corgi"],
    "cardiidae": ["family cardiidae"],
    "cardinal": ["carmine"],
    "cardinal flower": ["indian pink", "lobelia cardinalis"],
    "cardinal number": ["cardinal"],
    "cardinal tetra": ["paracheirodon axelrodi"],
    "cardiograph": ["electrocardiograph"],
    "cardiography": ["electrocardiography"],
    "cardiologist": ["heart specialist", "heart surgeon"],
    "cardiomegaly": ["enlarged heart", "megacardia", "megalocardia"],
    "cardiomyopathy": ["myocardiopathy"],
    "cardiopulmonary": ["cardiorespiratory"],
    "cardiopulmonary resuscitation": ["cardiac resuscitation", "cpr", "kiss of life", "mouth-to-mouth resuscitation"],
    "cardiospermum": ["genus cardiospermum"],
    "cardium": ["genus cardium"],
    "cardoon": ["cynara cardunculus"],
    "cardsharp": ["card shark", "card sharp", "card sharper", "cardsharper", "sharper", "sharpie", "sharpy"],
    "carducci": ["giosue carducci"],
    "carduelinae": ["subfamily carduelinae"],
    "carduelis": ["genus carduelis"],
    "carduus": ["genus carduus"],
    "care": ["give care"],
    "care a hang": ["give a damn", "give a hang", "give a hoot"],
    "care for": ["cherish", "hold dear", "treasure"],
    "care-laden": ["heavy-laden"],
    "careen": ["shift", "tilt", "wobble"],
    "career": ["calling", "vocation"],
    "carefree": ["unworried"],
    "carefreeness": ["insouciance", "lightheartedness", "lightsomeness"],
    "careful": ["heedful"],
    "careless": ["regardless"],
    "carelessly": ["heedlessly"],
    "carelessness": ["sloppiness"],
    "caress": ["fondle"],
    "caressing": ["cuddling", "fondling", "hugging", "kissing", "necking", "petting", "smooching", "snuggling"],
    "caretta": ["genus caretta"],
    "carew": ["thomas carew"],
    "careworn": ["drawn", "haggard", "raddled", "worn"],
    "carex": ["genus carex"],
    "cargo": ["consignment", "freight", "lading", "load", "loading", "payload", "shipment"],
    "cargo area": ["cargo deck", "cargo hold", "hold", "storage area"],
    "cargo ship": ["cargo vessel"],
    "cariama": ["genus cariama"],
    "cariamidae": ["family cariamidae"]
}
