synonyms = {
    "blood cell": ["blood corpuscle", "corpuscle"],
    "blood clot": ["grume"],
    "blood coagulation": ["blood clotting"],
    "blood cup": ["fairy cup", "peziza coccinea"],
    "blood disease": ["blood disorder"],
    "blood flower": ["asclepias curassavica", "swallowwort"],
    "blood group": ["blood type"],
    "blood poisoning": ["septicaemia", "septicemia"],
    "blood relation": ["blood relative", "cognate", "sib"],
    "blood sausage": ["black pudding", "blood pudding"],
    "blood sugar": ["blood glucose"],
    "blood-oxygenation level dependent functional magnetic resonance imaging": ["bold fmri"],
    "bloodbath": ["battue", "bloodletting", "bloodshed"],
    "bloodberry": ["blood berry", "rivina humilis", "rouge plant", "rougeberry"],
    "bloodcurdling": ["hair-raising", "nightmarish"],
    "bloodhound": ["sleuthhound"],
    "bloodiness": ["bloodthirstiness"],
    "bloodless": ["exsanguine", "exsanguinous"],
    "bloodroot": ["puccoon", "redroot", "sanguinaria canadensis", "tetterwort"],
    "bloodshed": ["gore"],
    "bloodstained": ["gory"],
    "bloodstone": ["heliotrope"],
    "bloodstream": ["blood stream"],
    "bloodthirsty": ["bloody-minded", "sanguinary"],
    "bloodwood tree": ["kiaat", "pterocarpus angolensis"],
    "bloody": ["all-fired", "damn"],
    "bloody-minded": ["cantankerous"],
    "bloom": ["blossom", "flower"],
    "bloomeria": ["genus bloomeria"],
    "bloomers": ["drawers", "knickers", "pants"],
    "bloomfield": ["leonard bloomfield"],
    "blooming": ["bloom"],
    "blossom": ["blossom forth", "blossom out", "unfold"],
    "blossoming": ["anthesis", "efflorescence", "florescence", "flowering", "inflorescence"],
    "blot": ["smear", "smirch", "spot", "stain"],
    "blotch": ["splodge", "splotch"],
    "blotched": ["blotchy", "splotched"],
    "blotted out": ["obliterate", "obliterated"],
    "blotter": ["charge sheet", "day book", "police blotter", "rap sheet"],
    "blotting paper": ["blotter"],
    "blow": ["bump"],
    "blow gas": ["blowing gas"],
    "blow out": ["blow", "burn out"],
    "blow up": ["enlarge", "magnify"],
    "blowback": ["backfire"],
    "blowfish": ["puffer", "pufferfish", "sea squab"],
    "blowfly": ["blow fly"],
    "blowgun": ["blow tube", "blowpipe", "blowtube"],
    "blown": ["pursy", "short-winded", "winded"],
    "blown-up": ["enlarged"],
    "blowsy": ["blowzy", "slatternly", "sluttish"],
    "blowtorch": ["blowlamp", "torch"],
    "blowtube": ["blow tube", "blowpipe"],
    "blowy": ["breezy", "windy"],
    "blubber": ["blubber out"],
    "blucher": ["g. l. von blucher", "gebhard leberecht von blucher", "von blucher"],
    "blue": ["blueness"],
    "blue ash": ["fraxinus quadrangulata"],
    "blue catfish": ["blue cat", "blue channel cat", "blue channel catfish"],
    "blue cheese dressing": ["roquefort dressing"],
    "blue chip": ["blue-chip stock"],
    "blue cohosh": ["blueberry root", "caulophyllum thalictrioides", "caulophyllum thalictroides", "papoose root", "papooseroot", "squaw root", "squawroot"],
    "blue columbine": ["aquilegia caerulea", "aquilegia scopulorum calcarea"],
    "blue crab": ["callinectes sapidus"],
    "blue daisy": ["blue marguerite", "felicia amelloides"],
    "blue elder": ["blue elderberry", "sambucus caerulea"],
    "blue false indigo": ["baptisia australis"],
    "blue flag": ["iris versicolor"],
    "blue fleabane": ["erigeron acer"],
    "blue goose": ["chen caerulescens"],
    "blue grama": ["bouteloua gracilis"],
    "blue gum": ["eucalyptus globulus", "fever tree"],
    "blue jasmine": ["blue jessamine", "clematis crispa", "curly clematis", "marsh clematis"],
    "blue jay": ["cyanocitta cristata", "jaybird"],
    "blue lotus": ["nymphaea stellata"],
    "blue marlin": ["makaira nigricans"],
    "blue mockingbird": ["melanotis caerulescens"],
    "blue mold fungus": ["peronospora tabacina"],
    "blue mountain tea": ["solidago odora", "sweet goldenrod"],
    "blue orchid": ["vanda caerulea"],
    "blue pea": ["butterfly pea", "clitoria turnatea"],
    "blue peafowl": ["pavo cristatus"],
    "blue pike": ["blue pickerel", "blue pikeperch", "blue walleye", "strizostedion vitreum glaucum"],
    "blue pimpernel": ["blue skullcap", "mad-dog skullcap", "mad-dog weed", "scutellaria lateriflora"],
    "blue poppy": ["meconopsis betonicifolia"],
    "blue racer": ["coluber constrictor flaviventris"],
    "blue ribbon": ["cordon bleu"],
    "blue ribbon commission": ["blue ribbon committee"],
    "blue ridge mountains": ["blue ridge"],
    "blue sage": ["salvia lancifolia", "salvia reflexa"],
    "blue shark": ["great blue shark", "prionace glauca"],
    "blue sky": ["blue", "blue air", "wild blue yonder"],
    "blue star": ["amsonia tabernaemontana"],
    "blue succory": ["catananche caerulea", "cupid's dart"],
    "blue tit": ["parus caeruleus", "tomtit"],
    "blue toadflax": ["linaria canadensis", "old-field toadflax"],
    "blue vitriol": ["blue copperas", "blue stone", "chalcanthite"],
    "blue wall of silence": ["blue wall", "wall of silence"],
    "blue whale": ["balaenoptera musculus", "sulfur bottom"],
    "blue-black": ["bluish black"],
    "blue-eyed": ["fair-haired", "white-haired"],
    "blue-eyed african daisy": ["arctotis stoechadifolia", "arctotis venusta"],
    "blue-eyed mary": ["collinsia verna"],
    "blue-grey": ["blue-gray", "bluish-gray", "bluish-grey"],
    "blue-headed vireo": ["vireo solitarius solitarius"],
    "blue-lilac": ["bluish-lilac"],
    "blue-purple": ["bluish-purple"],
    "blue-ribbon": ["select"],
    "blue-violet": ["bluish-violet"],
    "blue-white": ["bluish-white", "cool-white"],
    "blueberry": ["blueberry bush"],
    "bluebonnet": ["buffalo clover", "lupinus subcarnosus", "texas bluebonnet"],
    "bluebottle": ["calliphora vicina"],
    "bluefin": ["bluefin tuna"],
    "bluefish": ["pomatomus saltatrix"],
    "bluegill": ["lepomis macrochirus"],
    "bluegrass": ["blue grass"],
    "bluehead": ["thalassoma bifasciatum"],
    "bluejack oak": ["quercus incana", "turkey oak"],
    "bluejacket": ["navy man", "sailor", "sailor boy"],
    "bluepoint": ["blue point"],
    "blueprint": ["draft", "draught"],
    "blues": ["blue devils", "megrims", "vapors", "vapours"],
    "bluestem": ["andropogon furcatus", "andropogon gerardii", "blue stem"],
    "bluestocking": ["bas bleu"],
    "bluethroat": ["erithacus svecicus"],
    "bluethroat pikeblenny": ["chaenopsis ocellata"],
    "blueweed": ["blue devil", "blue thistle", "echium vulgare", "viper's bugloss"],
    "bluewing": ["anas discors", "blue-winged teal"],
    "bluff": ["bluff out"],
    "bluffer": ["four-flusher"],
    "bluffly": ["bluntly", "brusquely", "flat out", "roundly"],
    "bluing": ["blue", "blueing"],
    "bluish green": ["blue green", "teal"],
    "blunder": ["bloomer", "blooper", "boner", "boo-boo", "botch", "bungle", "flub", "foul-up", "fuckup", "pratfall"],
    "blunt": ["candid", "forthright", "frank", "free-spoken", "outspoken", "plainspoken", "point-blank", "straight-from-the-shoulder"],
    "blunted": ["dulled"],
    "blur": ["blear"],
    "blurred": ["clouded"],
    "blurt out": ["blunder", "blunder out", "blurt", "ejaculate"],
    "blush": ["crimson", "flush", "redden"],
    "blush wine": ["pink wine", "rose", "rose wine"],
    "blushful": ["blushing", "red-faced"],
    "blushing mushroom": ["amanita rubescens", "blusher"],
    "blustering": ["blusterous", "blustery"],
    "blustery": ["bullying"],
    "bo hai": ["po hai"],
    "boa constrictor": ["constrictor constrictor"],
    "board": ["room"],
    "board meeting": ["committee meeting"],
    "boarding": ["embarkation", "embarkment"],
    "boarding card": ["boarding pass"],
    "boarding house": ["boardinghouse"],
    "boardroom": ["council chamber"],
    "boarfish": ["capros aper"],
    "boast": ["blow", "bluster", "brag", "gas", "gasconade", "shoot a line", "swash", "tout", "vaunt"],
    "boastful": ["big", "braggart", "bragging", "braggy", "cock-a-hoop", "crowing", "self-aggrandising", "self-aggrandizing"],
    "boastfully": ["big", "large", "vauntingly"],
    "boastfulness": ["vainglory"],
    "boatbill": ["boat-billed heron", "broadbill", "cochlearius cochlearius"],
    "boater": ["leghorn", "panama", "panama hat", "sailor", "skimmer", "straw hat"],
    "boating": ["yachting"],
    "boatload": ["carload", "shipload"],
    "boatman": ["boater", "waterman"],
    "boatswain": ["bo's'n", "bo'sun", "bos'n", "bosun"],
    "boatswain's chair": ["bosun's chair"],
    "bob": ["bobber", "bobfloat", "cork"],
    "bob around": ["bob about"],
    "bobbin": ["reel", "spool"],
    "bobby pin": ["grip", "hairgrip"],
    "bobbysoxer": ["bobby-socker"],
    "bobcat": ["bay lynx", "lynx rufus"],
    "bobolink": ["dolichonyx oryzivorus", "reedbird", "ricebird"],
    "bobsled": ["bob"],
    "bobtail": ["bob", "dock"],
    "bobwhite": ["bobwhite quail", "partridge"],
    "boccaccio": ["giovanni boccaccio"],
    "bocce": ["bocci", "boccie"],
    "bocce ball": ["bocci ball", "boccie ball"],
    "bocconia": ["bocconia frutescens", "tree celandine"],
    "bock": ["bock beer"],
    "bode": ["augur", "auspicate", "betoken", "forecast", "foreshadow", "foretell", "omen", "portend", "predict", "prefigure", "presage", "prognosticate"],
    "bodhisattva": ["boddhisatva"],
    "bodied": ["corporal", "corporate", "embodied", "incarnate"],
    "bodiless": ["bodyless"],
    "bodily": ["corporal", "corporeal", "somatic"],
    "bodily process": ["activity", "bodily function", "body process"],
    "bodkin": ["threader"],
    "bodo-garo": ["barish"],
    "bodoni": ["gianbattista bodoni"],
    "body": ["personify"],
    "body armor": ["body armour", "cataphract", "coat of mail", "suit of armor", "suit of armour"],
    "body bag": ["human remains pouch", "personnel pouch"],
    "body louse": ["cootie", "pediculus corporis"],
    "body mass index": ["bmi"],
    "body odor": ["b.o.", "body odour"],
    "body of water": ["water"],
    "body temperature": ["blood heat"],
    "body type": ["somatotype"],
    "body waste": ["excrement", "excreta", "excretion", "excretory product"],
    "bodybuilder": ["muscle builder", "muscle-builder", "musclebuilder", "muscleman"],
    "bodybuilding": ["anaerobic exercise", "muscle building", "musclebuilding"],
    "bodyguard": ["escort"],
    "boehme": ["behmen", "boehm", "bohme", "jakob behmen", "jakob boehm", "jakob boehme", "jakob bohme"],
    "boehmenism": ["behmenism"],
    "boehmeria": ["genus boehmeria"],
    "boell": ["heinrich boell", "heinrich theodor boell"],
    "boethius": ["anicius manlius severinus boethius"],
    "bog": ["peat bog"],
    "bog bilberry": ["bog whortleberry", "moor berry", "vaccinium uliginosum alpinum"],
    "bog down": ["bog"],
    "bog pimpernel": ["anagallis tenella"],
    "bog rein orchid": ["bog candles", "habenaria dilatata"],
    "bog rose": ["arethusa bulbosa", "dragon's mouth", "wild pink"],
    "bog rosemary": ["andromeda glaucophylla", "moorwort"],
    "bog star": ["parnassia palustris"],
    "bogart": ["humphrey bogart", "humphrey deforest bogart"],
    "bogey": ["bogie", "bogy"],
    "bogeyman": ["booger", "boogeyman", "bugaboo", "bugbear"],
    "boggy": ["marshy", "miry", "mucky", "muddy", "quaggy", "sloppy", "sloughy", "soggy", "squashy", "swampy", "waterlogged"],
    "bogota": ["capital of colombia"],
    "bogus": ["bastard", "fake", "phoney", "phony"],
    "bogy": ["bogey", "bogie"],
    "bohemian waxwing": ["bombycilla garrulus"],
    "bohr": ["niels bohr", "niels henrik david bohr"],
    "bohrium": ["atomic number 107", "bh", "element 107"],
    "boidae": ["family boidae"],
    "boil": ["furuncle"],
    "boil down": ["concentrate", "decoct", "reduce"],
    "boil over": ["overboil"],
    "boil smut": ["ustilago maydis"],
    "boiled": ["poached", "stewed"],
    "boiled dinner": ["new england boiled dinner"],
    "boiled egg": ["coddled egg"],
    "boiler": ["steam boiler"],
    "boiling": ["simmering", "stewing"],
    "boiling point": ["boil"],
    "boiling water reactor": ["bwr"],
    "boise": ["capital of idaho"],
    "boisterous": ["knockabout"],
    "bok choy": ["bok choi", "brassica rapa chinensis", "chinese white cabbage", "pak choi", "pakchoi"],
    "bokmal": ["bokmaal", "dano-norwegian"],
    "bolbitis": ["genus bolbitis"],
    "boldface": ["bold", "bold face"],
    "boldness": ["daring", "hardihood", "hardiness"],
    "bole": ["bolanci"],
    "boletaceae": ["family boletaceae"],
    "boletellus": ["genus boletellus"],
    "boletus": ["genus boletus"],
    "boleyn": ["anne boleyn"],
    "bolide": ["fireball"],
    "bolivar": ["el libertador", "simon bolivar"],
    "bolivia": ["republic of bolivia"],
    "boll weevil": ["anthonomus grandis"],
    "bollard": ["bitt"],
    "bollock": ["bullock block"],
    "bolo": ["bolo knife"],
    "bolo tie": ["bola", "bola tie", "bolo"],
    "bologna": ["bologna sausage"],
    "bologram": ["bolograph"],
    "bolshevik": ["bolshevist"],
    "bolshevism": ["collectivism", "sovietism"],
    "bolshy": ["stroppy"],
    "bolster": ["bolster up"],
    "bolt": ["deadbolt"],
    "bolti": ["tilapia nilotica"],
    "boltonia": ["genus boltonia"],
    "boltzmann": ["ludwig boltzmann"],
    "bomarea": ["genus bomarea"],
    "bomb calorimeter": ["bomb"],
    "bomb shelter": ["air-raid shelter", "bombproof"],
    "bombacaceae": ["family bombacaceae"],
    "bombard": ["bomb"],
    "bombardon": ["bombard"],
    "bombast": ["blah", "claptrap", "fustian", "rant"],
    "bombastic": ["declamatory", "large", "orotund", "tumid", "turgid"],
    "bombastically": ["grandiosely"],
    "bombax": ["genus bombax"],
    "bomber": ["cuban sandwich", "grinder", "hero", "hero sandwich", "hoagie", "hoagy", "italian sandwich", "poor boy", "sub", "submarine", "submarine sandwich", "torpedo", "wedge", "zep"],
    "bomber crew": ["bomber aircrew"],
    "bombina": ["genus bombina"],
    "bombing": ["bombardment"],
    "bomblet": ["cluster bomblet"],
    "bombproof": ["shellproof"],
    "bombshell": ["thunderbolt", "thunderclap"],
    "bombus": ["genus bombus"],
    "bombycid": ["bombycid moth", "silkworm moth"],
    "bombycidae": ["family bombycidae"],
    "bombycilla": ["genus bombycilla"],
    "bombycillidae": ["family bombycillidae"],
    "bombyliidae": ["family bombyliidae"],
    "bombyx": ["genus bombyx"],
    "bon mot": ["mot"],
    "bon voyage": ["send-off"],
    "bonasa": ["genus bonasa"],
    "bond": ["bring together", "draw together"],
    "bond trading": ["bond-trading activity"],
    "bondage": ["slavery", "thraldom", "thrall", "thralldom"],
    "bonderize": ["bonderise"],
    "bonding": ["soldering"],
    "bondman": ["bondsman"],
    "bondsman": ["bondswoman"],
    "bonduc": ["bonduc tree", "caesalpinia bonduc", "caesalpinia bonducella"],
    "bonduc nut": ["nicker nut", "nicker seed"],
    "bondwoman": ["bondmaid", "bondswoman"],
    "bone": ["debone"],
    "bone black": ["animal black", "animal charcoal", "bone char"],
    "bone oil": ["dippel's oil"],
    "bone-ash cup": ["cupel", "refractory pot"],
    "bone-dry": ["bone dry"],
    "bone-idle": ["bone-lazy"],
    "boned": ["deboned"],
    "bonefish": ["albula vulpes"],
    "bones": ["castanets", "clappers", "finger cymbals"],
    "boneset": ["agueweed", "eupatorium perfoliatum", "thoroughwort"],
    "bonfire": ["balefire"],
    "bonfire night": ["guy fawkes night"],
    "bongo": ["bongo drum"],
    "bonhoeffer": ["dietrich bonhoeffer"],
    "boniface": ["apostle of germany", "saint boniface", "st. boniface", "winfred", "wynfrith"],
    "boniface viii": ["benedetto caetani"],
    "bonito": ["katsuwonus pelamis", "oceanic bonito"],
    "bonito shark": ["blue pointed", "isurus glaucus"],
    "bonnet": ["poke bonnet"],
    "bonnet macaque": ["bonnet monkey", "capped macaque", "crown monkey", "macaca radiata"],
    "bonney": ["billie the kid", "william h. bonney"],
    "bonny": ["bonnie", "comely", "fair", "sightly"],
    "bontemps": ["arna wendell bontemps"],
    "bonus": ["incentive"],
    "bony": ["cadaverous", "emaciated", "gaunt", "haggard", "pinched", "skeletal", "wasted"],
    "bony labyrinth": ["osseous labyrinth"],
    "bonyness": ["boniness", "emaciation", "gauntness", "maceration"],
    "boo": ["hiss"],
    "boodle": ["bread", "cabbage", "clams", "dinero", "dough", "gelt", "kale", "lettuce", "lolly", "loot", "lucre", "moolah", "pelf", "scratch", "shekels", "simoleons", "sugar", "wampum"],
    "boogie": ["boogie-woogie"],
    "boojum tree": ["cirio", "fouquieria columnaris", "idria columnaris"],
    "book": ["rule book"],
    "book fair": ["bookfair"],
    "book jacket": ["dust cover", "dust jacket", "dust wrapper"],
    "book scorpion": ["chelifer cancroides"],
    "bookdealer": ["book seller"],
    "booked": ["engaged", "set-aside"],
    "booker": ["booking agent"],
    "booking": ["reservation"],
    "bookish": ["studious"],
    "bookkeeping": ["clerking"],
    "booklet": ["brochure", "folder", "leaflet", "pamphlet"],
    "booklouse": ["book louse", "deathwatch", "liposcelis divinatorius"],
    "bookmaker": ["bookie"],
    "bookmark": ["bookmarker"],
    "bookplate": ["ex libris"],
    "bookshop": ["bookstall", "bookstore"],
    "boole": ["george boole"],
    "boolean logic": ["boolean algebra"],
    "boolean operation": ["binary arithmetic operation", "binary operation"],
    "boom": ["din"],
    "boomerang": ["throw stick", "throwing stick"],
    "booming": ["flourishing", "palmy", "prospering", "prosperous", "roaring", "thriving"],
    "boone": ["daniel boone"],
    "boorish": ["loutish", "neandertal", "neanderthal", "oafish", "swinish"],
    "boorishness": ["uncouthness"],
    "boost": ["advance", "supercharge"],
    "booster": ["lifter", "shoplifter"],
    "boot": ["bring up", "reboot"],
    "bootblack": ["shoeblack"],
    "bootee": ["bootie"],
    "booth": ["john wilkes booth"],
    "bootleg": ["black", "black-market", "contraband", "smuggled"],
    "bootlegger": ["moonshiner"],
    "bootless": ["fruitless", "futile", "sleeveless", "vain"],
    "bootlicking": ["fawning", "obsequious", "sycophantic", "toadyish"],
    "bootmaker": ["boot maker"],
    "bop": ["bebop"],
    "borage": ["borago officinalis", "tailwort"],
    "boraginaceae": ["borage family", "family boraginaceae"],
    "borago": ["genus borago"],
    "borassus": ["genus borassus"],
    "bordeaux": ["bordeaux wine"],
    "border": ["edge"],
    "border on": ["approach"],
    "borderland": ["border district", "march", "marchland"],
    "borderline": ["marginal"],
    "borderline schizophrenia": ["latent schizophrenia"],
    "bore": ["tire"],
    "bore bit": ["borer", "rock drill", "stone drill"],
    "boreal": ["circumboreal"],
    "bored": ["world-weary"],
    "boredom": ["ennui", "tedium"],
    "borges": ["jorge borges", "jorge luis borges"],
    "borgia": ["duchess of ferrara", "lucrezia borgia"],
    "boric": ["boracic"],
    "boric acid": ["orthoboric acid"],
    "boring": ["drilling", "oil production"],
    "boringly": ["tediously", "tiresomely"],
    "boringness": ["dreariness", "insipidity", "insipidness"],
    "born": ["max born"],
    "born-again": ["converted", "reborn"],
    "borneo": ["kalimantan"],
    "bornite": ["peacock ore"],
    "borodin": ["aleksandr borodin", "aleksandr porfirevich borodin"],
    "boron": ["atomic number 5"],
    "borrelia burgdorferi": ["lime disease spirochete"],
    "borrowing": ["adoption"],
    "borsch": ["borscht", "borsh", "borshch", "borsht", "bortsch"],
    "borscht circuit": ["borscht belt", "borsht belt", "borsht circuit"],
    "borzoi": ["russian wolfhound"],
    "bos": ["genus bos"],
    "bosch": ["hieronymus bosch", "jerom bos"],
    "bose": ["satyendra n. bose", "satyendra nath bose"],
    "boselaphus": ["genus boselaphus"],
    "bosky": ["brushy"],
    "bosnia and herzegovina": ["bosna i hercegovina", "bosnia", "bosnia-herzegovina", "republic of bosnia and herzegovina"],
    "bosomy": ["busty", "buxom", "curvaceous", "curvy", "full-bosomed", "sonsie", "sonsy", "stacked", "voluptuous", "well-endowed"],
    "boss": ["hirer"],
    "boston": ["bean town", "beantown", "capital of massachusetts", "hub of the universe"],
    "boston bull": ["boston terrier"],
    "boston fern": ["nephrolepis exaltata", "nephrolepis exaltata bostoniensis"],
    "boston ivy": ["japanese ivy", "parthenocissus tricuspidata"],
    "boswell": ["james boswell"],
    "boswellia": ["genus boswellia"],
    "botanic": ["botanical"],
    "botanist": ["phytologist", "plant scientist"],
    "botanize": ["botanise"],
    "botany": ["phytology"],
    "botaurus": ["genus botaurus"],
    "botch": ["ball up", "blow", "bobble", "bodge", "bollix", "bollix up", "bollocks", "bollocks up", "botch up", "bumble", "bungle", "flub", "fluff", "foul up", "fuck up", "fumble", "louse up", "mess up", "mishandle", "muck up", "muff", "screw up", "spoil"],
    "botchy": ["butcherly", "unskillful"],
    "bothered": ["daunted", "fazed"],
    "bothidae": ["family bothidae"],
    "bothrops": ["genus bothrops"],
    "botonee": ["botonnee"],
    "botrychium": ["genus botrychium"],
    "botryoid": ["botryoidal", "boytrose"],
    "botswana": ["republic of botswana"],
    "botticelli": ["alessandro di mariano dei filipepi", "sandro botticelli"],
    "bottle": ["bottleful"],
    "bottle gourd": ["calabash", "lagenaria siceraria"],
    "bottle-nosed whale": ["bottlenose", "bottlenose whale", "hyperoodon ampullatus"],
    "bottle-tree": ["bottle tree"],
    "bottlenose dolphin": ["bottle-nosed dolphin", "bottlenose"],
    "bottom": ["bottom of the inning"],
    "bottom quark": ["beauty quark"],
    "bottom rot fungus": ["corticium solani"],
    "bottom-feeder": ["bottom-dweller"],
    "bottomland": ["bottom"],
    "bottommost": ["lowermost", "nethermost"],
    "botulin": ["botulinus toxin", "botulismotoxin"],
    "botulinum toxin a": ["botox"],
    "botulinus": ["botulinum", "clostridium botulinum"],
    "bouffant": ["puffy"],
    "bougainville": ["louis antoine de bougainville"],
    "boughten": ["store-bought"],
    "boulder": ["bowlder"],
    "boulez": ["pierre boulez"],
    "boulle": ["boule", "buhl"],
    "bounce": ["jounce"],
    "bouncer": ["chucker-out"],
    "bouncing": ["bouncy", "peppy", "spirited", "zippy"],
    "bouncy": ["live", "lively", "resilient", "springy"],
    "bound": ["border"],
    "bound morpheme": ["bound form"],
    "bound up": ["wrapped up"],
    "boundary": ["bound", "edge"],
    "boundary line": ["border", "borderline", "delimitation", "mete"],
    "bounded": ["delimited"],
    "bounder": ["leaper"],
    "boundless": ["limitless", "unbounded"],
    "boundlessly": ["immeasurably", "infinitely"],
    "bountiful": ["plentiful"],
    "bountifully": ["bounteously", "plenteously", "plentifully"],
    "bounty": ["premium"],
    "bouquet": ["fragrance", "fragrancy", "redolence", "sweetness"],
    "bourbon": ["bourbon dynasty"],
    "bourgeois": ["burgher"],
    "bourgogne": ["burgundy"],
    "bourguignon": ["bourguignon sauce", "burgundy sauce"],
    "bourn": ["bourne"],
    "bourtree": ["black elder", "common elder", "elderberry", "european elder", "sambucus nigra"],
    "bouteloua": ["genus bouteloua"],
    "boutique": ["dress shop"],
    "bouvier des flandres": ["bouviers des flandres"],
    "bouyei": ["buyi"],
    "bovidae": ["family bovidae"],
    "bovinae": ["subfamily bovinae"],
    "bovine": ["bovid"],
    "bovine spongiform encephalitis": ["bse", "mad cow disease"],
    "bovini": ["tribe bovini"],
    "bow": ["bow down"],
    "bow leg": ["bandy legs", "bow legs"],
    "bow out": ["withdraw"],
    "bow tie": ["bow-tie", "bowtie"],
    "bowditch": ["nathaniel bowditch"],
    "bowdler": ["thomas bowdler"],
    "bowdlerization": ["bowdlerisation"],
    "bowdlerize": ["bowdlerise", "castrate", "expurgate", "shorten"],
    "bowed": ["bowing"],
    "bowed down": ["loaded down", "overburdened", "weighed down"],
    "bowed stringed instrument": ["string"],
    "bowel movement": ["bm", "movement"],
    "bower actinidia": ["actinidia arguta", "tara vine"],
    "bowerbird": ["catbird"],
    "bowfin": ["amia calva", "dogfish", "grindle"],
    "bowhead": ["balaena mysticetus", "bowhead whale", "greenland whale"],
    "bowie": ["james bowie", "jim bowie"],
    "bowiea": ["genus bowiea"],
    "bowl": ["trough"],
    "bowleg": ["bandy leg", "bandyleg", "bow leg", "genu varum", "tibia vara"],
    "bowler hat": ["bowler", "derby", "derby hat", "plug hat"],
    "bowline": ["bowline knot"],
    "bowling alley": ["alley", "skittle alley"],
    "bowling ball": ["bowl"],
    "bowling pin": ["pin"],
    "bowman's capsule": ["capsula glomeruli", "glomerular capsule"],
    "bowse": ["bouse"],
    "box": ["package"],
    "box beam": ["box girder"],
    "box camera": ["box kodak"],
    "box elder": ["acer negundo", "ash-leaved maple"],
    "box huckleberry": ["gaylussacia brachycera"],
    "box in": ["box up"],
    "box office": ["ticket booth", "ticket office"],
    "box turtle": ["box tortoise"],
    "box wrench": ["box end wrench"],
    "boxed": ["boxed in", "boxed-in"],
    "boxer": ["pugilist"],
    "boxfish": ["trunkfish"],
    "boxing": ["fisticuffs", "pugilism"],
    "boxing glove": ["glove"],
    "boxing ring": ["prize ring"],
    "boxlike": ["box-shaped", "boxy"],
    "boxwood": ["turkish boxwood"],
    "boyfriend": ["beau", "fellow", "swain", "young man"],
    "boyish": ["boylike", "schoolboyish"],
    "boyishly": ["boylike"],
    "boykinia": ["genus boykinia"],
    "boyle": ["kay boyle"],
    "boyle's law": ["mariotte's law"],
    "boyne": ["battle of boyne"],
    "boysenberry": ["boysenberry bush"],
    "brace": ["poise"],
    "braced": ["buttressed"],
    "bracelet": ["bangle"],
    "bracelet wood": ["jacquinia armillaris"],
    "bracer": ["armguard"],
    "brachial artery": ["arteria brachialis"],
    "brachial plexus": ["plexus brachialis"],
    "brachial vein": ["vena brachialis"],
    "brachinus": ["genus brachinus"],
    "brachiocephalic vein": ["innominate vein", "vena brachiocephalica"],
    "brachiopod": ["lamp shell", "lampshell"],
    "brachiopoda": ["phylum brachiopoda"],
    "brachycephalic": ["brachycranial", "brachycranic"],
    "brachycephaly": ["brachycephalism"],
    "brachychiton": ["genus brachychiton"],
    "brachycome": ["genus brachycome"],
    "brachydactylic": ["brachydactylous"],
    "brachydactyly": ["brachydactylia"],
    "brachypterous": ["short-winged"],
    "brachystegia": ["genus brachystegia"],
    "brachyura": ["suborder brachyura"],
    "bracing": ["brisk", "fresh", "refreshful", "refreshing", "tonic"],
    "bracken": ["pteridium esculentum"],
    "bracket": ["bracket out"],
    "bracket fungus": ["shelf fungus"],
    "brackish": ["briny"],
    "bracteate": ["bracted"],
    "bracteole": ["bractlet"],
    "bradawl": ["pricker"],
    "bradbury": ["ray bradbury", "ray douglas bradbury"],
    "bradford": ["william bradford"],
    "bradley": ["thomas bradley", "tom bradley"],
    "bradley method of childbirth": ["bradley method"],
    "bradley's spleenwort": ["asplenium bradleyi"],
    "bradstreet": ["anne bradstreet", "anne dudley bradstreet"],
    "brady": ["mathew b. brady"],
    "bradypodidae": ["family bradypodidae"],
    "bradypus": ["genus bradypus"],
    "brag": ["bragging", "crow", "crowing", "gasconade", "line-shooting", "vaporing"],
    "bragg": ["braxton bragg"],
    "braggadocio": ["bluster", "rhodomontade", "rodomontade"],
    "bragger": ["blowhard", "boaster", "braggart", "line-shooter", "vaunter"],
    "bragi": ["brage"],
    "brahe": ["tycho brahe"],
    "brahman": ["brahmin"],
    "brahmanism": ["brahminism"],
    "brahmaputra": ["brahmaputra river"],
    "brahminic": ["brahminical"],
    "brahms": ["johannes brahms"],
    "braid": ["lace", "plait"],
    "braille": ["louis braille"],
    "brain": ["brainpower", "learning ability", "mental capacity", "mentality", "wit"],
    "brain death": ["cerebral death"],
    "brain disorder": ["brain disease", "encephalopathy"],
    "brain tumor": ["brain tumour"],
    "brainless": ["headless"],
    "brainsick": ["crazy", "demented", "disturbed", "mad", "sick", "unbalanced", "unhinged"],
    "brainstem": ["brain stem", "brain-stem"],
    "brainwave": ["brain wave", "cortical potential"],
    "brainworker": ["brain-worker"],
    "brainy": ["brilliant", "smart as a whip"],
    "brake cylinder": ["hydraulic brake cylinder", "master cylinder"],
    "brake drum": ["drum"],
    "brake shoe": ["shoe", "skid"],
    "brake system": ["brakes"],
    "braky": ["brambly"],
    "brama": ["genus brama"],
    "bramante": ["donato bramante", "donato d'agnolo bramante"],
    "brambling": ["fringilla montifringilla"],
    "bramidae": ["family bramidae"],
    "branch": ["fork", "furcate", "ramify", "separate"],
    "branch line": ["spur", "spur track"],
    "branched": ["branching", "ramate", "ramose", "ramous"],
    "branchiate": ["gilled"],
    "branching": ["fork", "forking", "ramification"],
    "branchiobdella": ["genus branchiobdella"],
    "branchiobdellidae": ["family branchiobdellidae"],
    "branchiopod": ["branchiopodan", "branchiopodous"],
    "branchiopod crustacean": ["branchiopod", "branchiopodan"],
    "branchiopoda": ["subclass branchiopoda"],
    "branchiostegidae": ["family branchiostegidae"],
    "branchiura": ["order branchiura"],
    "branchlet": ["sprig", "twig"],
    "brancusi": ["constantin brancusi"],
    "brand": ["brandmark", "trademark"],
    "brand-name drug": ["proprietary drug"],
    "brand-new": ["bran-new", "spic-and-span", "spick-and-span"],
    "brandish": ["flourish", "wave"],
    "brandt": ["willy brandt"],
    "brant": ["brant goose", "brent", "brent goose"],
    "branta": ["genus branta"],
    "braque": ["georges braque"],
    "brasenia": ["genus brasenia"],
    "brash": ["cheeky", "nervy"],
    "brasilia": ["brazilian capital", "capital of brazil"],
    "brass": ["memorial tablet", "plaque"],
    "brass buttons": ["cotula coronopifolia"],
    "brass knucks": ["brass knuckles", "knuckle duster", "knuckles", "knucks"],
    "brass section": ["brass"],
    "brassia": ["genus brassia"],
    "brassica": ["genus brassica"],
    "brassiere": ["bandeau", "bra"],
    "brassy": ["brasslike"],
    "bratislava": ["capital of slovakia", "pozsony", "pressburg"],
    "bratty": ["brattish"],
    "bratwurst": ["brat"],
    "braun": ["eva braun"],
    "braun's holly fern": ["polystichum braunii", "prickly shield fern"],
    "braunschweig": ["brunswick"],
    "bravado": ["bluster"],
    "brave": ["braw", "gay"],
    "bravely": ["courageously"],
    "brawl": ["wrangle"],
    "brawn": ["brawniness", "heftiness", "muscle", "muscularity", "sinew"],
    "brawny": ["hefty", "muscular", "powerful", "sinewy"],
    "braxton-hicks contraction": ["false labor"],
    "brazier": ["brasier"],
    "brazil": ["brasil", "federative republic of brazil"],
    "brazil nut": ["bertholletia excelsa", "brazil-nut tree"],
    "brazilian guava": ["psidium guineense"],
    "brazilian ironwood": ["caesalpinia ferrea"],
    "brazilian pepper tree": ["schinus terebinthifolius"],
    "brazilian rosewood": ["caviuna wood", "dalbergia nigra", "jacaranda"],
    "brazilian trumpeter": ["psophia crepitans"],
    "brazilwood": ["caesalpinia echinata", "peach-wood", "peachwood", "pernambuco wood"],
    "brazos": ["brazos river"],
    "bread": ["breadstuff", "staff of life"],
    "bread mold": ["rhizopus nigricans"],
    "bread-bin": ["breadbox"],
    "breadboard": ["bread board"],
    "breadfruit": ["artocarpus altilis", "artocarpus communis", "breadfruit tree"],
    "breadline": ["bread line"],
    "breadroot": ["indian breadroot", "pomme blanche", "pomme de prairie", "psoralea esculenta"],
    "breadstick": ["bread-stick"],
    "breadth": ["comprehensiveness", "largeness"],
    "breadthwise": ["breadthways", "broadwise"],
    "break": ["break away"],
    "break dance": ["break", "break-dance"],
    "break dancing": ["break dance"],
    "break down": ["lose it", "snap"],
    "break in": ["break"],
    "break through": ["crack"],
    "break up": ["fragment", "fragmentise", "fragmentize"],
    "breakage": ["break", "breaking"],
    "breakaway": ["breaking away"],
    "breakax": ["break-axe", "breakaxe", "sloanea jamaicensis"],
    "breakdown": ["crack-up"],
    "breaker": ["ledgeman"],
    "breakfast area": ["breakfast nook"],
    "breaking off": ["abruption"],
    "breakwater": ["bulwark", "groin", "groyne", "jetty", "mole", "seawall"],
    "bream": ["freshwater bream"],
    "breast": ["white meat"],
    "breast of lamb": ["poitrine d'agneau"],
    "breast-deep": ["breast-high"],
    "breastfeed": ["give suck", "lactate", "nurse", "suck", "suckle", "wet-nurse"],
    "breastplate": ["aegis", "egis"],
    "breath": ["breather", "breathing place", "breathing space", "breathing spell", "breathing time"],
    "breathalyze": ["breathalyse"],
    "breathalyzer": ["breathalyser"],
    "breathe": ["respire", "suspire", "take a breath"],
    "breathed": ["voiceless"],
    "breathing": ["external respiration", "respiration", "ventilation"],
    "breathing device": ["breathing apparatus", "breathing machine", "ventilator"],
    "breathing room": ["breathing space"],
    "breathless": ["breathtaking"],
    "brecht": ["bertolt brecht"],
    "breech": ["rear of barrel", "rear of tube"],
    "breech delivery": ["breech birth", "breech presentation"],
    "breechblock": ["breech closer"],
    "breechcloth": ["breechclout", "loincloth"],
    "breeched": ["pantalooned", "trousered"],
    "breeches": ["knee breeches", "knee pants", "knickerbockers", "knickers"],
    "breed": ["cover"],
    "breeder": ["stock breeder"],
    "breeding": ["genteelness", "gentility"],
    "breeze": ["air", "gentle wind", "zephyr"],
    "breeze through": ["ace", "nail", "pass with flying colors", "sail through", "sweep through"],
    "breeziness": ["windiness"],
    "bren": ["bren gun"],
    "bretagne": ["breiz", "brittany"],
    "breuer": ["marcel lajos breuer"],
    "brevity": ["briefness", "transience"],
    "brevoortia": ["genus brevoortia"],
    "brew": ["brewage"],
    "brewer": ["beer maker"],
    "brewer's mole": ["hair-tailed mole", "parascalops breweri"],
    "brezhnev": ["leonid brezhnev", "leonid ilyich brezhnev"],
    "briar": ["briar pipe"],
    "briarwood": ["brier-wood", "brierwood"],
    "bribe": ["buy", "corrupt", "grease one's palms"],
    "briber": ["suborner"],
    "bribery": ["graft"],
    "bric-a-brac": ["knickknack", "knickknackery", "nicknack", "whatnot"],
    "brick in": ["brick over", "brick up"],
    "brick trowel": ["mason's trowel"],
    "brickellia": ["genus brickelia"],
    "brickyard": ["brickfield"],
    "bridal": ["espousal"],
    "bridal gown": ["wedding dress", "wedding gown"],
    "bridal wreath": ["bridal-wreath", "francoa ramosa"],
    "bridesmaid": ["maid of honor"],
    "bridge": ["bridge over"],
    "bridge player": ["hand"],
    "bridgehead": ["foothold"],
    "bridges": ["harry bridges"],
    "bridget": ["bride", "brigid", "saint bride", "saint bridget", "saint brigid", "st. bride", "st. bridget", "st. brigid"],
    "bridgetown": ["capital of barbados"],
    "bridle": ["check", "curb"],
    "bridle path": ["bridle road"],
    "brief": ["legal brief"],
    "briefs": ["jockey shorts"],
    "brier": ["brier patch", "brierpatch"],
    "brigadier": ["brigadier general"],
    "brigantine": ["hermaphrodite brig"],
    "bright": ["brilliant"],
    "bright-red": ["raspberry-red"],
    "brighten": ["lighten", "lighten up"],
    "brightly-colored": ["brightly-coloured"],
    "brightness": ["cleverness", "smartness"],
    "brill": ["scophthalmus rhombus"],
    "brilliance": ["genius"],
    "brilliant": ["superb"],
    "brilliantly": ["bright", "brightly"],
    "brim": ["lip", "rim"],
    "brimful": ["brimfull", "brimming"],
    "brimstone": ["native sulfur", "native sulphur"],
    "brindled": ["brinded", "brindle", "tabby"],
    "brine shrimp": ["artemia salina"],
    "bring": ["convey", "take"],
    "bring around": ["cure", "heal"],
    "bring in": ["introduce"],
    "bring out": ["let out"],
    "bring round": ["bring around"],
    "bring to": ["bring around", "bring back", "bring round"],
    "brininess": ["salinity"],
    "brink": ["threshold", "verge"],
    "brinton": ["daniel garrison brinton"],
    "briquette": ["briquet"],
    "brisk": ["brisk up", "brisken"],
    "brisling": ["clupea sprattus", "sprat"],
    "bristle": ["stand up", "uprise"],
    "bristle at": ["bridle at", "bridle up", "bristle up"],
    "bristle fern": ["filmy fern"],
    "bristlecone pine": ["pinus aristata", "rocky mountain bristlecone pine"],
    "bristlegrass": ["bristle grass"],
    "bristly": ["prickly", "splenetic", "waspish"],
    "bristly locust": ["moss locust", "robinia hispida", "rose acacia"],
    "bristly sarsaparilla": ["aralia hispida", "bristly sarsparilla", "dwarf elder"],
    "brit": ["britt"],
    "british": ["british people", "brits"],
    "british capacity unit": ["imperial capacity unit"],
    "british commonwealth": ["commonwealth of nations"],
    "british imperial system": ["british system", "english system"],
    "british labour party": ["labor", "labour", "labour party"],
    "british pound": ["british pound sterling", "pound", "pound sterling", "quid"],
    "british shilling": ["bob", "shilling"],
    "british thermal unit": ["b.th.u.", "btu"],
    "britisher": ["brit", "briton"],
    "britten": ["benjamin britten", "edward benjamin britten", "lord britten of aldeburgh"],
    "brittle": ["toffee", "toffy"],
    "brittle bladder fern": ["brittle fern", "cystopteris fragilis", "fragile fern"],
    "brittle maidenhair": ["adiantum tenerum", "brittle maidenhair fern"],
    "brittle star": ["brittle-star", "serpent star"],
    "brittlebush": ["brittle bush", "encelia farinosa", "incienso"],
    "brittleness": ["crispiness", "crispness"],
    "brno": ["brunn"],
    "broach": ["initiate"],
    "broad": ["spacious", "wide"],
    "broad bean": ["fava bean", "horsebean"],
    "broad beech fern": ["dryopteris hexagonoptera", "phegopteris hexagonoptera", "southern beech fern", "thelypteris hexagonoptera"],
    "broad buckler-fern": ["dryopteris dilatata"],
    "broad interpretation": ["judicial activism"],
    "broad jump": ["long jump"],
    "broad-headed": ["roundheaded", "short-headed"],
    "broad-leaved everlasting pea": ["lathyrus latifolius", "perennial pea"],
    "broad-leaved montia": ["montia cordifolia"],
    "broad-leaved plantain": ["cart-track plant", "common plantain", "plantago major", "white-man's foot", "whiteman's foot"],
    "broad-leaved twayblade": ["listera convallarioides"],
    "broadax": ["broadaxe"],
    "broadband": ["wideband"],
    "broadcast": ["program", "programme"],
    "broadcast medium": ["broadcasting"],
    "broadcaster": ["spreader"],
    "broadcasting station": ["broadcast station"],
    "broadleaf": ["broad-leafed", "broad-leaved"],
    "broadly": ["broadly speaking", "generally", "loosely"],
    "broadtail": ["caracul", "karakul"],
    "broadway": ["great white way"],
    "broca": ["pierre-paul broca"],
    "broca's area": ["broca's center", "broca's convolution", "broca's gyrus", "convolution of broca"],
    "brocaded": ["embossed", "raised"],
    "broccoli": ["brassica oleracea italica"],
    "broccoli raab": ["brassica rapa ruvo", "broccoli rabe"],
    "broccoli rabe": ["broccoli raab"],
    "brockhouse": ["bertram brockhouse"],
    "brogan": ["brogue", "clodhopper", "work shoe"],
    "broglie": ["de broglie", "louis victor de broglie"],
    "broil": ["bake"],
    "broiled": ["grilled"],
    "broke": ["bust", "skint", "stone-broke", "stony-broke"],
    "broken": ["broken in"],
    "broken-backed": ["hogged"],
    "brokenhearted": ["heartbroken", "heartsick"],
    "brokerage": ["brokerage firm", "securities firm"],
    "brokerage house": ["brokerage"],
    "bromate": ["brominate"],
    "brome": ["bromegrass"],
    "bromeliaceae": ["family bromeliaceae", "pineapple family"],
    "bromidic": ["corny", "platitudinal", "platitudinous"],
    "bromine": ["atomic number 35", "br"],
    "bromoform": ["tribromomethane"],
    "bromophenol blue": ["bromphenol blue", "tetrabromo-phenolsulfonephthalein"],
    "bromothymol blue": ["bromthymol blue"],
    "brompheniramine maleate": ["dimetane"],
    "brompton stock": ["matthiola incana"],
    "bromus": ["genus bromus"],
    "bronchial vein": ["vena bronchialis"],
    "bronchopneumonia": ["bronchial pneumonia"],
    "bronchus": ["bronchial tube"],
    "bronco": ["bronc", "broncho"],
    "bronte": ["anne bronte"],
    "bronze": ["bronzy"],
    "bronze star medal": ["bronze star"],
    "bronzed": ["suntanned", "tanned"],
    "brooch": ["clasp"],
    "brood": ["bulk large", "hover", "loom"],
    "brood hen": ["broody", "broody hen", "setting hen", "sitter"],
    "brooding": ["incubation"],
    "broodmare": ["stud mare"],
    "brook": ["creek"],
    "brook thistle": ["cirsium rivulare"],
    "brook trout": ["speckled trout"],
    "brooke": ["rupert brooke"],
    "brooklime": ["european brooklime", "veronica beccabunga"],
    "brooks": ["van wyck brooks"],
    "brookweed": ["samolus floribundus", "samolus parviflorus"],
    "broom beard grass": ["andropogon scoparius", "prairie grass", "schizachyrium scoparium", "wire grass"],
    "broom sedge": ["andropogon virginicus"],
    "broom tree": ["genista anglica", "needle furze", "petty whin"],
    "broomcorn": ["sorghum vulgare technicum"],
    "broomcorn millet": ["hog millet", "panicum miliaceum"],
    "broomstick": ["broom handle"],
    "broomweed": ["broom-weed", "gutierrezia texana"],
    "brosmius": ["genus browmius"],
    "broth": ["stock"],
    "broth of a boy": ["broth of a man"],
    "brother": ["comrade"],
    "brotherhood": ["fraternity", "sodality"],
    "brotherly": ["brotherlike", "fraternal"],
    "brotulidae": ["family brotulidae"],
    "broussonetia": ["genus broussonetia"],
    "brow": ["forehead"],
    "browbeat": ["bully", "swagger"],
    "brown": ["robert brown"],
    "brown bear": ["bruin", "ursus arctos"],
    "brown bells": ["fritillaria micrantha", "fritillaria parviflora"],
    "brown bread": ["boston brown bread"],
    "brown butter": ["beurre noisette"],
    "brown creeper": ["american creeper", "certhia americana"],
    "brown hyena": ["hyaena brunnea", "strand wolf"],
    "brown lacewing": ["hemerobiid", "hemerobiid fly"],
    "brown lemming": ["lemmus trimucronatus"],
    "brown pine": ["podocarpus elatus", "rockingham podocarp"],
    "brown rat": ["norway rat", "rattus norvegicus"],
    "brown root rot fungus": ["thielavia basicola"],
    "brown rot gummosis": ["gummosis"],
    "brown sauce": ["sauce espagnole"],
    "brown snail": ["helix aspersa"],
    "brown soft scale": ["coccus hesperidum"],
    "brown thrasher": ["brown thrush", "toxostoma rufums"],
    "brown trout": ["salmo trutta", "salmon trout"],
    "brown university": ["brown"],
    "brown-black": ["brownish-black"],
    "brown-green": ["brownish-green"],
    "brown-grey": ["brown-gray", "brownish-gray", "brownish-grey"],
    "brown-purple": ["brownish-purple"],
    "brown-speckled": ["brownish-speckled"],
    "brown-striped": ["brownish-striped"],
    "browne": ["hablot knight browne", "phiz"],
    "brownian movement": ["brownian motion", "pedesis"],
    "browning": ["john m. browning", "john moses browning"],
    "browning automatic rifle": ["bar"],
    "browning machine gun": ["peacemaker"],
    "browntail": ["brown-tail moth", "euproctis phaeorrhoea"],
    "browse": ["surf"],
    "browser": ["web browser"],
    "bruce": ["david bruce", "sir david bruce"],
    "brucellosis": ["bang's disease", "contagious abortion"],
    "bruch": ["max bruch"],
    "bruchidae": ["family bruchidae"],
    "bruchus": ["genus bruchus"],
    "bruckenthalia": ["genus bruckenthalia"],
    "bruckner": ["anton bruckner"],
    "brueghel": ["breughel", "breughel the elder", "bruegel", "pieter breughel", "pieter bruegel", "pieter brueghel", "pieter brueghel the elder"],
    "bruges": ["city of bridges"],
    "brugmansia": ["genus brugmansia"],
    "bruise": ["contuse"],
    "brumal": ["hibernal", "hiemal"],
    "brummell": ["beau brummell", "george bryan brummell"],
    "brummie": ["brummy"],
    "brumous": ["foggy", "hazy", "misty"],
    "brunanburh": ["battle of brunanburh"],
    "brunei": ["negara brunei darussalam"],
    "brunelleschi": ["filippo brunelleschi"],
    "brunet": ["brunette"],
    "brunfelsia": ["genus brunfelsia"],
    "brunhild": ["brunnhilde", "brynhild"],
    "bruno": ["saint bruno", "st. bruno"],
    "brush": ["sweep"],
    "brush turkey": ["alectura lathami"],
    "brush-tailed phalanger": ["trichosurus vulpecula"],
    "brush-tailed porcupine": ["brush-tail porcupine"],
    "brushed": ["fleecy", "napped"],
    "brusque": ["brusk", "curt", "short"],
    "brussels sprout": ["brassica oleracea gemmifera"],
    "brutal": ["unrelenting"],
    "brutality": ["barbarism", "barbarity", "savagery"],
    "brutalization": ["brutalisation"],
    "brutalize": ["brutalise"],
    "brutus": ["marcus junius brutus"],
    "bruxelles": ["belgian capital", "brussels", "capital of belgium"],
    "brya": ["genus brya"],
    "bryaceae": ["family bryaceae"],
    "bryales": ["order bryales"],
    "bryan": ["boy orator of the platte", "great commoner", "william jennings bryan"],
    "bryony": ["briony"],
    "bryophyta": ["division bryophyta"],
    "bryophyte": ["nonvascular plant"],
    "bryopsida": ["class bryopsida", "class musci", "musci"],
    "bryozoa": ["phylum bryozoa", "polyzoa"],
    "bryozoan": ["moss animal", "polyzoan", "sea mat", "sea moss"],
    "brythonic": ["brittanic"],
    "bryum": ["genus bryum"],
    "bubalus": ["genus bubalus", "tribe bubalus"],
    "bubble jet printer": ["bubble-jet printer", "bubblejet"],
    "bubble over": ["overflow", "spill over"],
    "bubble up": ["intumesce"],
    "bubbliness": ["effervescence", "frothiness"],
    "bubbling": ["bubbly", "effervescing", "foaming", "foamy", "frothy", "spumy"],
    "buber": ["martin buber"],
    "bubo": ["genus bubo"],
    "bubonic plague": ["glandular plague", "pestis bubonica"],
    "bubulcus": ["genus bubulcus"],
    "buccal artery": ["arteria buccalis"],
    "buccinidae": ["family buccinidae"],
    "bucconidae": ["family bucconidae"],
    "bucephala": ["genus bucephala"],
    "buceros": ["genus buceros"],
    "bucerotidae": ["family bucerotidae"],
    "buchanan": ["james buchanan", "president buchanan"],
    "bucharest": ["bucharesti", "bucuresti", "capital of romania"],
    "buchloe": ["genus buchloe"],
    "buchner": ["eduard buchner"],
    "buck": ["go against"],
    "bucked up": ["encouraged"],
    "bucket": ["bucketful"],
    "buckeye": ["conker", "horse chestnut"],
    "buckle": ["clasp"],
    "buckler mustard": ["biscutalla laevigata"],
    "buckleya": ["buckleya distichophylla"]
}
