synonyms = {
    "chemical defense": ["chemical defence"],
    "chemical element": ["element"],
    "chemical equilibrium": ["equilibrium"],
    "chemical process": ["chemical action", "chemical change"],
    "chemical reaction": ["reaction"],
    "chemical warfare": ["chemical operations"],
    "chemise": ["shift", "shimmy", "slip", "teddy"],
    "chemisorption": ["chemosorption"],
    "chemisorptive": ["chemosorptive"],
    "chemistry": ["alchemy", "interpersonal chemistry"],
    "chemistry department": ["department of chemistry"],
    "chemistry lab": ["chem lab", "chemistry laboratory"],
    "chemotherapeutic": ["chemotherapeutical"],
    "chen": ["subgenus chen"],
    "chenille": ["chenille cord"],
    "chennai": ["madras"],
    "chenopodiaceae": ["family chenopodiaceae", "goosefoot family"],
    "chenopodium": ["genus chenopodium"],
    "cheops": ["khufu"],
    "cheque": ["check out"],
    "cheremis": ["cheremiss", "mari"],
    "cherimoya": ["annona cherimola", "cherimoya tree"],
    "cherished": ["precious", "treasured", "wanted"],
    "cherokee rose": ["rosa laevigata"],
    "cherry": ["cherry tree"],
    "cherry laurel": ["laurel cherry", "prunus laurocerasus"],
    "cherry pepper": ["capsicum annuum cerasiforme"],
    "cherry plum": ["myrobalan", "myrobalan plum", "prunus cerasifera"],
    "cherry tomato": ["lycopersicon esculentum cerasiforme"],
    "cherrystone": ["cherrystone clam"],
    "cherubini": ["luigi cherubini", "maria luigi carlo zenobio cherubini"],
    "chervil": ["anthriscus cereifolium", "beaked parsley"],
    "chess": ["bromus secalinus", "cheat"],
    "chessboard": ["chess board"],
    "chessman": ["chess piece"],
    "chest cavity": ["thoracic cavity"],
    "chest of drawers": ["bureau", "chest", "dresser"],
    "chest register": ["chest tone", "chest voice"],
    "chesterfield": ["fourth earl of chesterfield", "philip dormer stanhope"],
    "chesterton": ["gilbert keith chesterton"],
    "chestnut": ["chestnut tree"],
    "chestnut blight": ["chestnut canker"],
    "chevalier": ["maurice chevalier"],
    "cheviots": ["cheviot hills"],
    "chevron": ["grade insignia", "stripe", "stripes"],
    "chevrotain": ["mouse deer"],
    "chew": ["jaw", "manducate", "masticate"],
    "chew over": ["contemplate", "excogitate", "meditate", "mull", "mull over", "muse", "ponder", "reflect", "ruminate", "speculate", "think over"],
    "chew the fat": ["chaffer", "chat", "chatter", "chitchat", "claver", "confab", "confabulate", "gossip", "jaw", "natter", "shoot the breeze", "visit"],
    "chewa": ["cewa", "chichewa"],
    "chewable": ["cuttable"],
    "chewing gum": ["gum"],
    "chewink": ["cheewink", "pipilo erythrophthalmus"],
    "cheyenne": ["capital of wyoming"],
    "chi": ["khi"],
    "chiasma": ["chiasm", "decussation"],
    "chiasmal": ["chiasmatic", "chiasmic"],
    "chic": ["chichi", "chicness", "last word", "modishness", "smartness", "stylishness", "swank"],
    "chicago": ["windy city"],
    "chichipe": ["lemaireocereus chichipe"],
    "chick": ["biddy"],
    "chickamauga": ["battle of chickamauga"],
    "chickasaw plum": ["hog plum", "hog plum bush", "prunus angustifolia"],
    "chicken": ["poulet", "volaille"],
    "chicken broth": ["chicken stock"],
    "chicken cacciatore": ["chicken cacciatora"],
    "chicken coop": ["coop", "hencoop", "henhouse"],
    "chicken feed": ["scratch"],
    "chicken hawk": ["hen hawk"],
    "chicken leg": ["chicken drumstick"],
    "chicken louse": ["menopon gallinae", "menopon palladum", "shaft louse"],
    "chicken out": ["back down", "back off", "bow out", "pull out"],
    "chicken paprika": ["chicken paprikash"],
    "chicken roundworm": ["ascaridia galli"],
    "chicken yard": ["chicken run", "fowl run", "hen yard"],
    "chickenpox": ["varicella"],
    "chickeree": ["douglas squirrel", "tamiasciurus douglasi"],
    "chickpea": ["garbanzo"],
    "chickweed phlox": ["phlox bifida", "phlox stellaria", "sand phlox"],
    "chicle": ["chicle gum"],
    "chicory": ["chicory root"],
    "chicory escarole": ["endive", "escarole"],
    "chiding": ["objurgation", "scolding"],
    "chief": ["main", "master", "primary", "principal"],
    "chief executive officer": ["ceo", "chief operating officer"],
    "chief financial officer": ["cfo"],
    "chiefly": ["in the main", "mainly", "primarily", "principally"],
    "chieftaincy": ["chieftainship"],
    "chiffonier": ["commode"],
    "chigetai": ["dziggetai", "equus hemionus hemionus"],
    "chigoe": ["chigger", "chigoe flea", "tunga penetrans"],
    "chihuahuan spotted whiptail": ["cnemidophorus exsanguis"],
    "chilblain": ["chilblains", "pernio"],
    "child": ["baby"],
    "child pornography": ["kiddie porn", "kiddy porn"],
    "child prodigy": ["infant prodigy", "wonder child"],
    "child welfare agency": ["child welfare service"],
    "childbirth": ["accouchement", "childbearing", "vaginal birth"],
    "childcare": ["child care"],
    "childhood": ["puerility"],
    "childish": ["infantile"],
    "childishness": ["puerility"],
    "childlike": ["simple"],
    "chile": ["republic of chile"],
    "chile bonito": ["chilean bonito", "pacific bonito", "sarda chiliensis"],
    "chilean cedar": ["austrocedrus chilensis"],
    "chilean firebush": ["chilean flameflower", "embothrium coccineum"],
    "chilean jasmine": ["mandevilla laxa"],
    "chilean nut": ["chile hazel", "chile nut", "chilean hazelnut", "guevina avellana", "guevina heterophylla"],
    "chilean peso": ["peso"],
    "chilean rimu": ["lepidothamnus fonkii"],
    "chili": ["chili con carne"],
    "chill": ["shivering"],
    "chilliness": ["coolness", "nip"],
    "chilling": ["scarey", "scary", "shivery", "shuddery"],
    "chilly": ["parky"],
    "chilomastix": ["genus chilomastix"],
    "chilomeniscus": ["genus chilomeniscus"],
    "chilomycterus": ["genus chilomycterus"],
    "chilopoda": ["class chilopoda"],
    "chilopsis": ["genus chilopsis"],
    "chimaeridae": ["family chimaeridae"],
    "chimaphila": ["genus chimaphila"],
    "chime": ["bell", "gong"],
    "chime in": ["barge in", "break in", "butt in", "chisel in", "cut in", "put in"],
    "chimera": ["chimaera"],
    "chimeric": ["chimeral", "chimerical"],
    "chimney corner": ["inglenook"],
    "chimney plant": ["campanula pyramidalis", "chimney bellflower"],
    "chimney swift": ["chateura pelagica", "chimney swallow"],
    "chimneysweeper": ["chimneysweep", "sweep"],
    "chimonanthus": ["genus chimonanthus"],
    "chimpanzee": ["chimp", "pan troglodytes"],
    "chin": ["chin up"],
    "china": ["cathay", "communist china", "mainland china", "prc", "red china"],
    "china aster": ["callistephus chinensis"],
    "china cabinet": ["china closet"],
    "china clay": ["china stone", "kaolin", "kaoline", "porcelain clay", "terra alba"],
    "china pink": ["dianthus chinensis", "rainbow pink"],
    "china rose": ["bengal rose", "rosa chinensis"],
    "china tree": ["chinaberry", "false dogwood", "jaboncillo", "sapindus saponaria"],
    "chinaberry": ["azedarach", "azederach", "china tree", "chinaberry tree", "melia azedarach", "melia azederach", "persian lilac"],
    "chinaware": ["china"],
    "chincapin": ["chinkapin", "chinquapin"],
    "chinch bug": ["blissus leucopterus"],
    "chincherinchee": ["ornithogalum thyrsoides", "wonder flower"],
    "chinchilla": ["chinchilla laniger"],
    "chinchillidae": ["family chinchillidae"],
    "chinese alligator": ["alligator sinensis"],
    "chinese angelica": ["aralia stipulata", "chinese angelica tree"],
    "chinese anise": ["star anise", "star aniseed"],
    "chinese brown sauce": ["brown sauce"],
    "chinese cabbage": ["brassica rapa pekinensis", "celery cabbage", "napa"],
    "chinese checkers": ["chinese chequers"],
    "chinese chestnut": ["castanea mollissima"],
    "chinese cork oak": ["quercus variabilis"],
    "chinese elm": ["ulmus parvifolia"],
    "chinese evergreen": ["aglaonema modestum", "japanese leaf"],
    "chinese goose": ["anser cygnoides"],
    "chinese gooseberry": ["actinidia chinensis", "actinidia deliciosa", "kiwi", "kiwi vine"],
    "chinese holly": ["ilex cornuta"],
    "chinese lantern plant": ["bladder cherry", "physalis alkekengi", "winter cherry"],
    "chinese mustard": ["brassica juncea", "gai choi", "indian mustard", "leaf mustard"],
    "chinese paddlefish": ["psephurus gladis"],
    "chinese parasol tree": ["chinese parasol", "firmiana simplex", "japanese varnish tree", "phoenix tree"],
    "chinese pea tree": ["caragana sinica"],
    "chinese primrose": ["primula sinensis"],
    "chinese privet": ["ligustrum lucidum", "white wax tree"],
    "chinese rhubarb": ["rheum palmatum"],
    "chinese wall": ["great wall", "great wall of china"],
    "chinese wistaria": ["wisteria chinensis"],
    "chink": ["chinaman"],
    "chinook": ["chinook wind", "snow eater"],
    "chinook jargon": ["oregon jargon"],
    "chinook salmon": ["chinook", "king salmon"],
    "chinookan": ["chinook"],
    "chinquapin oak": ["chinkapin oak", "quercus muehlenbergii", "yellow chestnut oak"],
    "chiococca": ["genus chiococca"],
    "chionanthus": ["genus chionanthus"],
    "chios": ["khios"],
    "chip": ["break away", "break off", "chip off", "come off"],
    "chip away": ["chip away at"],
    "chipboard": ["hardboard"],
    "chipewyan": ["chippewaian", "chippewyan"],
    "chippendale": ["thomas chippendale"],
    "chipper": ["debonair", "debonaire", "jaunty"],
    "chipping sparrow": ["spizella passerina"],
    "chirico": ["giorgio de chirico"],
    "chironomidae": ["family chironomidae"],
    "chironomus": ["genus chironomus"],
    "chiropodist": ["foot doctor", "podiatrist"],
    "chiroptera": ["order chiroptera"],
    "chirrup": ["twitter"],
    "chitchat": ["causerie", "chin wag", "chin wagging", "chit chat", "gab", "gabfest", "gossip", "small talk"],
    "chiton": ["polyplacophore", "sea cradle"],
    "chitter": ["twitter"],
    "chitterlings": ["chitlings", "chitlins"],
    "chivalric": ["knightly", "medieval"],
    "chivalrous": ["gallant", "knightly"],
    "chivalry": ["knightliness"],
    "chives": ["allium schoenoprasum", "chive", "cive", "schnittlaugh"],
    "chlamydera": ["genus chlamydera"],
    "chlamydiaceae": ["family chlamydiaceae"],
    "chlamydomonadaceae": ["family chlamydomonadaceae"],
    "chlamydomonas": ["genus chlamydomonas"],
    "chlamydosaurus": ["genus chlamydosaurus"],
    "chlamyphorus": ["genus chlamyphorus"],
    "chloasma": ["mask of pregnancy", "melasma"],
    "chlorambucil": ["leukeran"],
    "chloramphenicol": ["chloromycetin"],
    "chloranthaceae": ["family chloranthaceae"],
    "chloranthus": ["genus chloranthus"],
    "chlordiazepoxide": ["libritabs", "librium"],
    "chlorine": ["cl"],
    "chloris": ["genus chloris"],
    "chloroacetophenone": ["cn gas"],
    "chlorobenzylidenemalononitrile": ["cs gas"],
    "chlorococcales": ["order chlorococcales"],
    "chlorococcum": ["genus chlorococcum"],
    "chlorofluorocarbon": ["cfc"],
    "chloroform": ["trichloromethane"],
    "chlorophis": ["genus chlorophis"],
    "chlorophoneus": ["genus chlorophoneus"],
    "chlorophthalmidae": ["family chlorophthalmidae"],
    "chlorophyceae": ["class chlorophyceae"],
    "chlorophyll": ["chlorophyl"],
    "chlorophyll c": ["chlorofucin"],
    "chlorophyllose": ["chlorophyllous"],
    "chlorophyta": ["division chlorophyta"],
    "chloropicrin": ["nitrochloroform"],
    "chlorosis": ["greensickness"],
    "chlorothiazide": ["diuril"],
    "chlorotic": ["greensick"],
    "chloroxylon": ["genus chloroxylon"],
    "chlorpheniramine maleate": ["coricidin"],
    "chlorpromazine": ["thorazine"],
    "chlortetracycline": ["aureomycin"],
    "chlorthalidone": ["hygroton", "thalidone"],
    "chlorura": ["genus chlorura"],
    "choanocyte": ["collar cell"],
    "chock": ["wedge"],
    "chockablock": ["chockful", "cram full"],
    "chocolate": ["burnt umber", "coffee", "deep brown", "umber"],
    "chocolate chip cookie": ["toll house cookie"],
    "chocolate sauce": ["chocolate syrup"],
    "choctaw": ["chahta"],
    "choeronycteris": ["genus choeronycteris"],
    "choice": ["pick", "selection"],
    "choice morsel": ["tidbit", "titbit"],
    "choir": ["chorus"],
    "choir school": ["schola cantorum"],
    "choirmaster": ["cantor", "precentor"],
    "choke": ["scrag"],
    "choke off": ["choke back", "choke down"],
    "chokecherry": ["chokecherry tree", "prunus virginiana"],
    "choked": ["clogged"],
    "chokedamp": ["blackdamp"],
    "chokehold": ["choke hold"],
    "choker": ["collar", "dog collar", "neckband"],
    "chokey": ["choky"],
    "choking": ["strangling", "strangulation", "throttling"],
    "cholera": ["asiatic cholera", "epidemic cholera", "indian cholera"],
    "cholera morbus": ["collywobbles"],
    "choleric": ["hotheaded", "irascible"],
    "cholesterol": ["cholesterin"],
    "cholla": ["opuntia cholla"],
    "choloepus": ["genus choloepus"],
    "chomp": ["champ"],
    "chomsky": ["noam chomsky"],
    "chondrichthyes": ["class chondrichthyes"],
    "chondritic": ["granular"],
    "chondrus": ["genus chondrus"],
    "chongqing": ["chungking"],
    "choose": ["opt", "prefer"],
    "choosy": ["choosey"],
    "chop": ["chop up"],
    "chopin": ["kate chopin"],
    "chopine": ["platform"],
    "chopped": ["shredded", "sliced"],
    "chopped steak": ["beef patty", "chop steak", "chopsteak", "hamburger steak"],
    "chopper": ["pearly"],
    "choppiness": ["rough water", "roughness"],
    "chopping board": ["cutting board"],
    "choppy": ["jerky"],
    "chorale": ["choral"],
    "chordamesoderm": ["chordomesoderm"],
    "chordata": ["phylum chordata"],
    "chordeiles": ["genus chordeiles"],
    "chordospartium": ["genus chordospartium"],
    "chorioallantois": ["chorioallantoic membrane"],
    "chorionic villus sampling": ["chorionic villus biopsy"],
    "choriotis": ["genus choriotis"],
    "chorizagrotis": ["genus chorizagrotis"],
    "chorizema": ["genus chorizema"],
    "choroid": ["choroid coat"],
    "choroid plexus": ["plexus choroideus"],
    "choroid vein": ["vena choroidea"],
    "choroidal artery": ["arteria choroidea"],
    "chortle": ["chuckle"],
    "chorus": ["chorus line"],
    "chorus girl": ["chorine", "showgirl"],
    "chosen": ["elect"],
    "chow": ["chuck", "eats", "grub"],
    "chrism": ["chrisom", "holy oil", "sacramental oil"],
    "christendom": ["christianity"],
    "christian church": ["disciples of christ"],
    "christian era": ["common era"],
    "christian name": ["baptismal name"],
    "christian science": ["church of christ scientist"],
    "christianity": ["christian religion"],
    "christianization": ["christianisation"],
    "christianize": ["christianise"],
    "christie": ["agatha christie", "dame agatha mary clarissa christie"],
    "christless": ["nonchristian"],
    "christlike": ["christly"],
    "christmas": ["christmastide", "christmastime", "noel", "yule", "yuletide"],
    "christmas begonia": ["begonia cheimantha"],
    "christmas bush": ["ceratopetalum gummiferum", "christmas tree"],
    "christmas cactus": ["schlumbergera baridgesii", "schlumbergera buckleyi"],
    "christmas factor": ["factor ix"],
    "christmas fern": ["canker brake", "dagger fern", "evergreen wood fern", "polystichum acrostichoides"],
    "christmas present": ["christmas gift"],
    "christmas rose": ["black hellebore", "helleborus niger", "winter rose"],
    "christmasberry": ["christmas berry", "lycium carolinianum"],
    "christopher": ["saint christopher"],
    "chromatic color": ["chromatic colour", "spectral color", "spectral colour"],
    "chromatin": ["chromatin granule"],
    "chromatographic": ["chromatographical"],
    "chromesthesia": ["chromaesthesia"],
    "chromium": ["cr"],
    "chromosomal aberration": ["chromosomal anomaly", "chromosonal disorder", "chrosomal abnormality"],
    "chronic": ["continuing"],
    "chronic myelocytic leukemia": ["myeloid leukemia"],
    "chronic renal failure": ["chronic kidney failure"],
    "chronically": ["inveterate"],
    "chronologize": ["chronologise"],
    "chronoperates": ["genus chronoperates"],
    "chrysaora": ["genus chrysaora"],
    "chrysemys": ["genus chrysemys"],
    "chrysobalanus": ["genus chrysobalanus"],
    "chrysochloridae": ["family chrysochloridae"],
    "chrysochloris": ["genus chrysochloris"],
    "chrysolepis": ["genus chrysolepis"],
    "chrysolophus": ["genus chrysolophus"],
    "chrysomelidae": ["family chrysomelidae"],
    "chrysophrys": ["genus chrysophrys"],
    "chrysophyceae": ["class chrysophyceae", "class heterokontae", "heterokontae"],
    "chrysophyllum": ["genus chrysophyllum"],
    "chrysophyta": ["division chrysophyta"],
    "chrysopidae": ["family chrysopidae"],
    "chrysopsis": ["genus chrysopsis"],
    "chrysosplenium": ["genus chrysosplenium"],
    "chrysothamnus": ["genus chrysothamnus"],
    "chthonian": ["chthonic", "nether"],
    "chub": ["leuciscus cephalus"],
    "chub mackerel": ["scomber japonicus", "tinker"],
    "chubbiness": ["pudginess", "rolypoliness", "tubbiness"],
    "chubby": ["embonpoint", "plump"],
    "chuck": ["ditch"],
    "chuckle": ["chortle", "laugh softly"],
    "chuckwalla": ["sauromalus obesus"],
    "chufa": ["cyperus esculentus", "earth almond", "ground almond", "rush nut", "yellow nutgrass"],
    "chukchi": ["chukchi language"],
    "chukka": ["chukka boot"],
    "chukker": ["chukka"],
    "chum salmon": ["chum", "oncorhynchus keta"],
    "chumminess": ["camaraderie", "comradeliness", "comradery", "comradeship"],
    "chummy": ["matey", "pally"],
    "chump": ["fall guy", "fool", "gull", "mark", "mug", "patsy", "soft touch", "sucker"],
    "chunga": ["chunga burmeisteri", "seriema"],
    "chunky": ["dumpy", "squat", "squatty", "stumpy"],
    "chunnel": ["channel tunnel"],
    "church": ["christian church"],
    "church calendar": ["ecclesiastical calendar"],
    "church father": ["father", "father of the church"],
    "church of the brethren": ["dippers", "dunkers"],
    "church school": ["parochial school"],
    "church service": ["church"],
    "church year": ["christian year"],
    "churchgoer": ["church member"],
    "churchill": ["duke of marlborough", "first duke of marlborough", "john churchill"],
    "churlishly": ["surlily"],
    "churn": ["boil", "moil", "roil"],
    "churning": ["roiled", "roiling", "roily", "turbulent"],
    "churr": ["whirr"],
    "chute": ["jump", "parachute"],
    "chutney": ["indian relish"],
    "chutzpa": ["chutzpah", "hutzpah"],
    "chylaceous": ["chylous"],
    "chylific": ["chylifactive", "chylifactory"],
    "chytridiaceae": ["family chytridiaceae"],
    "chytridiales": ["order chytridiales"],
    "chytridiomycetes": ["class chytridiomycetes"],
    "ciardi": ["john anthony ciardi", "john ciardi"],
    "cibotium": ["genus cibotium"],
    "cicada": ["cicala"],
    "cicada killer": ["sphecius speciosis"],
    "cicadellidae": ["family cicadellidae"],
    "cicadidae": ["family cicadidae"],
    "cicatrize": ["cicatrise"],
    "cicer": ["genus cicer"],
    "cicero": ["marcus tullius cicero", "tully"],
    "cichlid": ["cichlid fish"],
    "cichlidae": ["family cichlidae"],
    "cichorium": ["genus cichorium"],
    "cicindelidae": ["family cicindelidae"],
    "ciconia": ["genus ciconia"],
    "ciconiidae": ["family ciconiidae"],
    "ciconiiformes": ["order ciconiiformes"],
    "cicuta": ["genus cicuta"],
    "cider": ["cyder"],
    "cider gum": ["eucalypt gunnii"],
    "cigar lighter": ["cigarette lighter", "pocket lighter"],
    "cigarette": ["butt", "cigaret", "coffin nail", "fag"],
    "cigarette paper": ["rolling paper"],
    "ciliary": ["cilial", "ciliate"],
    "ciliary artery": ["arteria ciliaris"],
    "ciliary veins": ["venae ciliares"],
    "ciliata": ["ciliophora", "class ciliata", "class ciliophora"],
    "ciliate": ["ciliated protozoan", "ciliophoran"],
    "cimabue": ["giovanni cimabue"],
    "cimarron": ["cimarron river"],
    "cimetidine": ["tagamet"],
    "cimex": ["genus cimex"],
    "cimicidae": ["family cimicidae"],
    "cimicifuga": ["genus cimicifuga"],
    "cinch": ["girth"],
    "cinchona": ["cinchona bark", "peruvian bark"],
    "cinchona tree": ["cinchona pubescens"],
    "cincinnatus": ["lucius quinctius cincinnatus"],
    "cinclidae": ["family cinclidae"],
    "cinclus": ["genus cinclus"],
    "cinder": ["clinker"],
    "cinder block": ["breeze block", "clinker block"],
    "cinema": ["movie house", "movie theater", "movie theatre", "picture palace"],
    "cinematize": ["cinematise"],
    "cineraria": ["pericallis cruenta", "senecio cruentus"],
    "cingulate gyrus": ["gyrus cinguli"],
    "cinnabar": ["callimorpha jacobeae", "cinnabar moth"],
    "cinnabar chanterelle": ["cantharellus cinnabarinus"],
    "cinnamomum": ["genus cinnamomum"],
    "cinnamon": ["cinnamon bark"],
    "cinnamon colored": ["cinnamon coloured"],
    "cinnamon fern": ["fiddlehead", "fiddlehead fern", "osmunda cinnamonea"],
    "cinnamon roll": ["cinnamon bun", "cinnamon snail"],
    "cinnamon stone": ["essonite", "hessonite"],
    "cinnamon vine": ["chinese yam", "dioscorea batata"],
    "cipher": ["cypher", "nobody", "nonentity"],
    "ciprofloxacin": ["cipro"],
    "circaea": ["genus circaea"],
    "circaetus": ["genus circaetus"],
    "circle": ["circulate"],
    "circle of curvature": ["osculating circle"],
    "circuit": ["electric circuit", "electrical circuit"],
    "circuit board": ["board", "card", "circuit card"],
    "circuit breaker": ["breaker"],
    "circuitous": ["roundabout"],
    "circular": ["bill", "broadsheet", "broadside", "flier", "flyer", "handbill", "throwaway"],
    "circular plane": ["compass plane"],
    "circular saw": ["buzz saw"],
    "circularity": ["disk shape"],
    "circularization": ["circularisation"],
    "circularize": ["circularise"],
    "circulate": ["distribute", "pass around", "pass on"],
    "circulating decimal": ["recurring decimal", "repeating decimal"],
    "circulative": ["circulatory"],
    "circulatory system": ["cardiovascular system"],
    "circumambulate": ["walk around"],
    "circumcision": ["feast of the circumcision"],
    "circumference": ["circuit"],
    "circumflex artery of the thigh": ["arteria circumflexa femoris"],
    "circumflex femoral vein": ["vena circumflexus femoris"],
    "circumflex humeral artery": ["arteria circumflexa humeri"],
    "circumflex iliac artery": ["arteria circumflexa ilium"],
    "circumflex iliac vein": ["vena circumflexa ilium"],
    "circumflex scapular artery": ["arteria circumflexa scapulae"],
    "circumflex vein": ["vena circumflexa"],
    "circumlocution": ["ambage", "periphrasis"],
    "circumlocutious": ["ambagious", "circumlocutory", "periphrastic"],
    "circumnavigate": ["compass"],
    "circumscribed": ["limited"],
    "circumspect": ["discreet"],
    "circumspection": ["caution"],
    "circumstance": ["condition", "consideration"],
    "circumstantial evidence": ["indirect evidence"],
    "circus": ["genus circus"],
    "circus tent": ["big top", "round top", "top"],
    "cirque": ["corrie", "cwm"],
    "cirrhosis": ["cirrhosis of the liver"],
    "cirripedia": ["subclass cirripedia"],
    "cirrocumulus": ["cirrocumulus cloud"],
    "cirrostratus": ["cirrostratus cloud"],
    "cirrus": ["cirrhus"],
    "cirsium": ["genus cirsium"],
    "cisalpine": ["ultramontane"],
    "cisco": ["coregonus artedi", "lake herring"],
    "cistaceae": ["family cistaceae", "rockrose family"],
    "cistern": ["water tank"],
    "cisterna": ["cistern"],
    "cistothorus": ["genus cistothorus"]
}
