synonyms = {
    "slam dancing": ["slam dance"],
    "slam-bang": ["slap-bang"],
    "slanderously": ["calumniously"],
    "slang": ["slang expression", "slang term"],
    "slant": ["angle", "weight"],
    "slantingly": ["slopingly"],
    "slantwise": ["slantways"],
    "slap": ["smack"],
    "slap on": ["clap on", "slam on"],
    "slapdash": ["slam-bang"],
    "slapper": ["spanker"],
    "slash": ["cut down"],
    "slat": ["spline"],
    "slate": ["slating"],
    "slate-grey": ["slate-gray", "slatey", "slaty", "slaty-gray", "slaty-grey", "stone-gray", "stone-grey"],
    "slattern": ["slovenly woman", "slut", "trollop"],
    "slatternliness": ["sluttishness"],
    "slaughter": ["butchery", "carnage", "mass murder", "massacre"],
    "slave": ["break one's back", "buckle down", "knuckle down"],
    "slave driver": ["simon legree"],
    "slave trade": ["slave traffic"],
    "slave-making ant": ["slave-maker"],
    "slaveholder": ["slave owner", "slaver"],
    "slaver": ["slave dealer", "slave trader"],
    "slavery": ["slaveholding"],
    "slavic": ["slavic language", "slavonic", "slavonic language"],
    "slavic people": ["slavic race"],
    "slavish": ["submissive", "subservient"],
    "slavonic": ["slavic"],
    "sled": ["sleigh"],
    "sled dog": ["sledge dog"],
    "sledgehammer": ["sledge"],
    "sleep": ["catch some z's", "kip", "log z's", "slumber"],
    "sleep late": ["sleep in"],
    "sleep over": ["stay over"],
    "sleep talking": ["somniloquism", "somniloquy"],
    "sleep terror disorder": ["pavor nocturnus"],
    "sleep together": ["bang", "be intimate", "bed", "bonk", "do it", "eff", "fuck", "get it on", "get laid", "have a go at it", "have intercourse", "have it away", "have it off", "have sex", "hump", "jazz", "know", "lie with", "love", "make love", "make out", "roll in the hay", "screw", "sleep with"],
    "sleep-learning": ["hypnopedia"],
    "sleeper": ["slumberer"],
    "sleepiness": ["drowsiness", "somnolence"],
    "sleeping car": ["sleeper", "wagon-lit"],
    "sleeping pill": ["sleeping capsule", "sleeping draught", "sleeping tablet"],
    "sleeping sickness": ["encephalitis lethargica", "epidemic encephalitis", "lethargic encephalitis", "sleepy sickness"],
    "sleepwalk": ["somnambulate"],
    "sleepwalker": ["noctambulist", "somnambulist"],
    "sleepwalking": ["noctambulation", "noctambulism", "somnambulation", "somnambulism"],
    "sleepy": ["sleepy-eyed", "sleepyheaded"],
    "sleeve": ["arm"],
    "sleigh bell": ["cascabel"],
    "slender": ["thin"],
    "slender loris": ["loris gracilis"],
    "slender rush": ["juncus tenuis"],
    "slender salamander": ["worm salamander"],
    "slender wheatgrass": ["agropyron pauciflorum", "agropyron trachycaulum", "elymus trachycaulos"],
    "slender wild oat": ["avena barbata"],
    "slender-tailed meerkat": ["suricata suricatta"],
    "slender-waisted": ["slim-waisted", "wasp-waisted"],
    "slenderize": ["slenderise"],
    "slenderly": ["slightly", "slimly"],
    "slenderness": ["slightness", "slimness"],
    "sleuth": ["sleuthhound"],
    "slice": ["slice up"],
    "slice into": ["slice through"],
    "slick": ["sleek"],
    "slickness": ["slick", "slip", "slipperiness"],
    "slide": ["playground slide", "sliding board"],
    "slide fastener": ["zip", "zip fastener", "zipper"],
    "slide rule": ["slipstick"],
    "slider": ["pseudemys scripta", "yellow-bellied terrapin"],
    "slight": ["cold-shoulder"],
    "slightly": ["more or less", "somewhat"],
    "slim-bodied": ["slender-bodied", "thin-bodied"],
    "slime mold": ["slime mould"],
    "slimed": ["slimy"],
    "sling": ["catapult"],
    "slingback": ["sling"],
    "slingshot": ["catapult", "sling"],
    "slip": ["sneak"],
    "slip away": ["sneak away", "sneak off", "sneak out", "steal away"],
    "slip clutch": ["slip friction clutch"],
    "slip coach": ["slip carriage"],
    "slip in": ["insert", "sneak in", "stick in"],
    "slipper": ["carpet slipper"],
    "slipper spurge": ["slipper plant"],
    "slippery": ["tricky"],
    "slippery dick": ["halicoeres bivittatus"],
    "slippery elm": ["red elm", "ulmus rubra"],
    "slipping": ["slithering"],
    "slipstream": ["airstream", "backwash", "race", "wash"],
    "slit": ["slice"],
    "slither": ["slide"],
    "sliver": ["splinter"],
    "sloanea": ["genus sloanea"],
    "slob": ["pig", "sloven", "slovenly person"],
    "slog": ["footslog", "pad", "plod", "tramp", "trudge"],
    "slop": ["swill"],
    "slop basin": ["slop bowl"],
    "slop pail": ["slop jar"],
    "slope": ["incline", "pitch"],
    "sloppiness": ["slovenliness", "unkemptness"],
    "slopseller": ["slop-seller"],
    "slopshop": ["slopseller's shop"],
    "slosh": ["slosh around", "slush", "slush around"],
    "slot": ["expansion slot"],
    "slot machine": ["coin machine"],
    "sloth": ["slothfulness"],
    "sloth bear": ["melursus ursinus", "ursus ursinus"],
    "slovakia": ["slovak republic"],
    "slovenia": ["republic of slovenia", "slovenija"],
    "slow": ["slow down", "slow up"],
    "slow loris": ["nycticebus pygmaeus", "nycticebus tardigradua"],
    "slowdown": ["lag", "retardation"],
    "slowgoing": ["unenergetic"],
    "slowly": ["easy", "slow", "tardily"],
    "slowness": ["deliberateness", "deliberation", "unhurriedness"],
    "slub": ["burl", "knot"],
    "sludge": ["goo", "gook", "goop", "guck", "gunk", "muck", "ooze", "slime"],
    "slug": ["slog", "swig"],
    "sluggard": ["slug"],
    "slugger": ["slogger"],
    "sluggish": ["sulky"],
    "sluice": ["sluice down"],
    "sluicegate": ["floodgate", "head gate", "penstock", "sluice valve", "water gate"],
    "slum": ["slum area"],
    "slumberous": ["slumbrous"],
    "slump": ["slouch"],
    "slurred": ["thick"],
    "smack": ["reek", "smell"],
    "small": ["little"],
    "small business administration": ["sba"],
    "small cane": ["arundinaria tecta", "switch cane"],
    "small capital": ["small cap"],
    "small change": ["chickenfeed", "chump change"],
    "small civet": ["viverricula indica", "viverricula malaccensis"],
    "small computer system interface": ["scsi"],
    "small indefinite quantity": ["small indefinite amount"],
    "small letter": ["lower-case letter", "lowercase", "minuscule"],
    "small print": ["fine print"],
    "small white": ["pieris rapae"],
    "small-capitalization": ["small-cap", "small-capitalisation"],
    "small-for-gestational-age infant": ["sga infant"],
    "small-leaved linden": ["small-leaved lime", "tilia cordata"],
    "smaller": ["littler"],
    "smalley": ["richard e. smalley", "richard errett smalley", "richard smalley"],
    "smalleye hammerhead": ["sphyrna tudes"],
    "smallmouth": ["micropterus dolomieu", "smallmouth bass", "smallmouth black bass", "smallmouthed bass", "smallmouthed black bass"],
    "smallness": ["littleness"],
    "smallpox": ["variola", "variola major"],
    "smalltooth sawfish": ["pristis pectinatus"],
    "smart": ["smarting", "smartness"],
    "smartly": ["modishly", "sprucely"],
    "smash": ["blast", "boom", "nail"],
    "smasher": ["beauty", "dish", "knockout", "looker", "lulu", "mantrap", "peach", "ravisher", "stunner", "sweetheart"],
    "smashing": ["shattering"],
    "smear": ["blur", "smudge", "smutch"],
    "smell": ["sense", "smell out"],
    "smelter": ["smeltery"],
    "smetana": ["bedrich smetana"],
    "smew": ["mergus albellus"],
    "smilacaceae": ["subfamily smilacaceae"],
    "smilax": ["genus smilax"],
    "smile": ["grin", "grinning", "smiling"],
    "smiledon": ["genus smiledon"],
    "smilo": ["oryzopsis miliacea", "smilo grass"],
    "smirch": ["besmirch"],
    "smirk": ["simper"],
    "smith": ["ian douglas smith", "ian smith"],
    "smitten": ["stricken", "struck"],
    "smog": ["smogginess"],
    "smoke": ["smoking"],
    "smoke bomb": ["smoke grenade"],
    "smoke screen": ["smokescreen"],
    "smoke tree": ["smoke bush"],
    "smoked": ["smoke-cured", "smoke-dried"],
    "smokehouse": ["meat house"],
    "smokeless powder": ["ballistite"],
    "smoker": ["tobacco user"],
    "smokestack": ["stack"],
    "smolder": ["smoulder"],
    "smoldering": ["smouldering"],
    "smolderingly": ["smoulderingly"],
    "smollett": ["tobias george smollett", "tobias smollett"],
    "smooch": ["spoon"],
    "smooth": ["smooth out"],
    "smooth alder": ["alnus serrulata", "hazel alder"],
    "smooth crabgrass": ["digitaria ischaemum"],
    "smooth darling pea": ["swainsona galegifolia"],
    "smooth green snake": ["opheodrys vernalis"],
    "smooth hammerhead": ["sphyrna zygaena"],
    "smooth lip fern": ["alabama lip fern", "cheilanthes alabamensis"],
    "smooth muscle": ["involuntary muscle"],
    "smooth plane": ["smoothing plane"],
    "smooth softshell": ["trionyx muticus"],
    "smooth sumac": ["rhus glabra", "scarlet sumac", "vinegar tree"],
    "smooth woodsia": ["woodsia glabella"],
    "smooth-leaved elm": ["european field elm", "ulmus carpinifolia"],
    "smoothed": ["smoothened"],
    "smoothhound": ["mustelus mustelus", "smoothhound shark"],
    "smoothie": ["charmer", "smoothy", "sweet talker"],
    "smoothly": ["swimmingly"],
    "smother": ["asphyxiate", "suffocate"],
    "smothered": ["stifled", "strangled", "suppressed"],
    "smothering": ["suffocating", "suffocative"],
    "smoulder": ["smolder"],
    "smudge": ["blot", "daub", "slur", "smear", "smirch", "spot"],
    "smug": ["self-satisfied"],
    "smuggler": ["contrabandist", "moon curser", "moon-curser", "runner"],
    "smut": ["smut fungus"],
    "smut grass": ["blackseed", "carpet grass", "sporobolus poiretii"],
    "smuts": ["jan christian smuts"],
    "smuttily": ["vulgarly"],
    "smuttiness": ["sootiness"],
    "smyrnium": ["genus smyrnium"],
    "snack bar": ["buffet", "snack counter"],
    "snaffle": ["snaffle bit"],
    "snail darter": ["percina tanasi"],
    "snailfish": ["liparis liparis", "sea snail", "seasnail"],
    "snailflower": ["corkscrew flower", "phaseolus caracalla", "snail bean", "snail flower", "snail-flower", "vigna caracalla"],
    "snake": ["snake in the grass"],
    "snake mackerel": ["gempylus serpens"],
    "snake muishond": ["poecilogale albinucha"],
    "snake polypody": ["microgramma-piloselloides"],
    "snake's head fritillary": ["checkered daffodil", "fritillaria meleagris", "guinea-hen flower", "leper lily"],
    "snakebird": ["anhinga", "darter"],
    "snakeblenny": ["lumpenus lumpretaeformis"],
    "snakewood": ["rauwolfia serpentina"],
    "snap": ["crack"],
    "snap at": ["bite off"],
    "snap bean": ["snap"],
    "snap up": ["grab", "snaffle"],
    "snapper": ["chrysophrys auratus"],
    "snapping shrimp": ["pistol shrimp"],
    "snappish": ["snappy"],
    "snappy": ["whipping"],
    "snapshot": ["shot", "snap"],
    "snare": ["gin", "noose"],
    "snare drum": ["side drum", "snare"],
    "snarl": ["embrangle", "snarl up"],
    "snatch": ["snap", "snatch up"],
    "snead": ["sam snead", "samuel jackson snead"],
    "sneak": ["creep", "mouse", "pussyfoot"],
    "sneak in": ["creep in"],
    "sneak thief": ["pilferer", "snitcher"],
    "sneaking": ["unavowed"],
    "sneaky": ["underhand", "underhanded"],
    "sneer": ["leer"],
    "sneerer": ["scorner"],
    "sneeringly": ["snidely", "superciliously"],
    "sneeze": ["sneezing", "sternutation"],
    "sneezeweed yarrow": ["achillea ptarmica", "sneezewort"],
    "snellen": ["hermann snellen"],
    "snicker": ["snigger"],
    "sniff": ["whiff"],
    "sniff out": ["nose out", "scent out", "smell out"],
    "sniffler": ["sniveler"],
    "sniffly": ["snuffling", "snuffly"],
    "snifter": ["brandy glass", "brandy snifter"],
    "snip": ["clip", "crop", "cut back", "dress", "lop", "prune", "trim"],
    "snipefish": ["bellows fish"],
    "sniper rifle": ["precision rifle"],
    "snips": ["tinsnips"],
    "snivel": ["whine"],
    "snob": ["prig", "snoot", "snot"],
    "snobbery": ["snobbishness", "snobbism"],
    "snobbishly": ["snootily", "uppishly"],
    "snog": ["buss", "kiss", "osculate"],
    "snoop": ["snooper"],
    "snooze": ["doze", "drowse"],
    "snore": ["saw logs", "saw wood"],
    "snorkel": ["breather", "schnorchel", "schnorkel", "snorkel breather"],
    "snorkeling": ["snorkel diving"],
    "snotty": ["snot-nosed"],
    "snout": ["rostrum"],
    "snow": ["snowfall"],
    "snow bunting": ["plectrophenax nivalis", "snowbird", "snowflake"],
    "snow gum": ["eucalyptus coriacea", "eucalyptus pauciflora", "ghost gum", "white ash"],
    "snow leopard": ["ounce", "panthera uncia"],
    "snow mushroom": ["tremella fuciformis"],
    "snow pea": ["sugar pea"],
    "snow plant": ["sarcodes sanguinea"],
    "snow thrower": ["snow blower"],
    "snow-blind": ["snow-blinded"],
    "snow-clad": ["snow-covered", "snowy"],
    "snow-in-summer": ["cerastium tomentosum", "love-in-a-mist"],
    "snow-on-the-mountain": ["euphorbia marginata", "ghost weed", "snow-in-summer"],
    "snow-white": ["snowy"],
    "snowball": ["abronia elliptica", "sweet sand verbena"],
    "snowbank": ["snow bank"],
    "snowbell": ["styrax obassia"],
    "snowberry": ["common snowberry", "symphoricarpos alba", "waxberry"],
    "snowblindness": ["snow-blindness"],
    "snowdrop anemone": ["anemone sylvestris", "snowdrop windflower"],
    "snowflake": ["flake"],
    "snowplow": ["snowplough"],
    "snowshoe hare": ["lepus americanus", "snowshoe rabbit", "varying hare"],
    "snowy egret": ["egretta thula", "snowy heron"],
    "snowy orchid": ["habenaria nivea"],
    "snowy tree cricket": ["oecanthus fultoni"],
    "snub": ["cold shoulder", "cut"],
    "snuff": ["snuffle"],
    "snuff out": ["blow out", "extinguish", "quench"],
    "snuff-color": ["snuff-colour"],
    "snuffbox fern": ["dryopteris thelypteris pubescens", "meadow fern", "thelypteris palustris pubescens"],
    "snuffer": ["snuff user"],
    "snuffle": ["snivel"],
    "so far": ["yet"],
    "soak": ["imbue"],
    "soaking": ["dripping", "sopping"],
    "soap": ["lather"],
    "soap powder": ["built-soap powder", "washing powder"],
    "soapberry": ["soapberry tree"],
    "soapstone": ["soap-rock", "soaprock", "steatite"],
    "soapsuds": ["lather", "suds"],
    "soapweed": ["soap tree", "soap-weed", "yucca elata"],
    "soapwort": ["bouncing bess", "bouncing bet", "hedge pink", "saponaria officinalis"],
    "soapwort gentian": ["gentiana saponaria"],
    "soar": ["soar up", "soar upwards", "surge", "zoom"],
    "sob": ["sobbing"],
    "sob story": ["sob stuff"],
    "sober up": ["sober"],
    "soberness": ["sobriety"],
    "sobriety": ["dryness"],
    "soccer": ["association football"],
    "sociability": ["sociableness"],
    "sociable": ["mixer", "social"],
    "social": ["societal"],
    "social anthropologist": ["cultural anthropologist"],
    "social anthropology": ["cultural anthropology"],
    "social climber": ["climber"],
    "social gathering": ["social affair"],
    "social organization": ["social organisation", "social structure", "social system", "structure"],
    "social security administration": ["ssa"],
    "social station": ["rank", "social rank", "social status"],
    "social welfare": ["public assistance", "welfare"],
    "social worker": ["caseworker", "welfare worker"],
    "socialism": ["socialist economy"],
    "socialistic": ["socialist"],
    "socialization": ["socialisation"],
    "socialize": ["socialise"],
    "socialized": ["socialised"],
    "socializer": ["socialiser"],
    "society": ["beau monde", "bon ton", "high society", "smart set"],
    "society of jesus": ["jesuit order"],
    "socinus": ["fausto paolo sozzini", "faustus socinus"],
    "sociobiologic": ["sociobiological"],
    "sociology department": ["department of sociology"],
    "sociopath": ["psychopath"],
    "sock": ["bash", "bonk", "bop", "whap", "whop"],
    "sockeye": ["blueback salmon", "oncorhynchus nerka", "red salmon", "sockeye salmon"],
    "socotra begonia": ["begonia socotrana"],
    "socratic method": ["maieutic method"],
    "sod house": ["adobe house", "soddy"],
    "soda jerk": ["soda jerker"],
    "soda water": ["carbonated water", "club soda", "seltzer", "sparkling water"],
    "sodden": ["soppy"],
    "soddy": ["frederick soddy"],
    "sodium": ["atomic number 11", "na"],
    "sodium carbonate": ["sal soda", "soda", "soda ash", "washing soda"],
    "sodium chloride": ["common salt"],
    "sodium dichromate": ["sodium bichromate"],
    "sodium hydroxide": ["caustic soda"],
    "sodium lauryl sulphate": ["sls", "sodium lauryl sulfate"],
    "sodium nitrate": ["soda niter"],
    "sodium phosphate": ["sodium orthophosphate"],
    "sodium pyrophosphate": ["tetrasodium pyrophosphate"],
    "sodium sulphate": ["sodium sulfate"],
    "sodium thiopental": ["luminal", "phenobarbital", "phenobarbitone", "purple heart"],
    "sodium-vapor lamp": ["sodium-vapour lamp"],
    "sodoku": ["spirillum fever"],
    "sodomite": ["bugger", "sod", "sodomist"],
    "sodomize": ["sodomise"],
    "sodomy": ["anal intercourse", "anal sex", "buggery"],
    "sofa": ["couch", "lounge"],
    "sofia": ["bulgarian capital", "serdica"],
    "soft": ["diffuse", "diffused"],
    "soft corn": ["flour corn", "squaw corn", "zea mays amylacea"],
    "soft diet": ["pap", "spoon food"],
    "soft palate": ["velum"],
    "soft shield fern": ["polystichum setiferum"],
    "soft soap": ["green soap"],
    "soft tick": ["argasid"],
    "soft tree fern": ["dicksonia antarctica"],
    "soft-finned fish": ["malacopterygian"],
    "soft-shell clam": ["long-neck clam", "steamer", "steamer clam"],
    "soft-shell crab": ["soft-shelled crab"],
    "soft-shelled turtle": ["pancake turtle"],
    "soft-shoe": ["soft-shoe dancing", "soft-shoe shuffle"],
    "softball": ["playground ball"],
    "softhearted": ["soft-boiled"],
    "softheartedness": ["tenderness"],
    "softish": ["semisoft"],
    "softly": ["quietly"],
    "software": ["computer software", "package", "software package", "software program", "software system"],
    "software documentation": ["documentation"],
    "software error": ["programming error"],
    "software package": ["software product"],
    "softwood": ["deal"],
    "softy": ["softie"],
    "soho": ["south of houston"],
    "soigne": ["soignee"],
    "soil": ["dirt"],
    "soiling": ["dirtying", "soilure"],
    "soissons": ["battle of soissons-reims", "battle of the aisne", "battle of the chemin-des-dames"],
    "soixante-neuf": ["sixty-nine"],
    "sojourn": ["visit"],
    "sol": ["colloidal solution", "colloidal suspension"],
    "solace": ["solacement"],
    "solan": ["solan goose", "solant goose", "sula bassana"],
    "solanaceae": ["family solanaceae", "potato family"],
    "solandra": ["genus solandra"],
    "solanopteris": ["genus solanopteris"],
    "solanum": ["genus solanum"],
    "solar array": ["solar battery", "solar panel"],
    "solar cell": ["photovoltaic cell"],
    "solar dish": ["solar collector", "solar furnace"],
    "solar energy": ["solar power"],
    "solar flare": ["flare"],
    "solar halo": ["parhelic circle", "parhelic ring"],
    "solar plexus": ["abdominal nerve plexus", "coeliac plexus", "plexus celiacus"],
    "solar year": ["astronomical year", "equinoctial year", "tropical year"],
    "solarization": ["solarisation"],
    "solarize": ["solarise"],
    "soldierfish": ["soldier-fish"],
    "soldiering": ["soldiership"],
    "soldierly": ["martial", "soldierlike", "warriorlike"],
    "sole": ["resole"],
    "solea": ["genus solea"],
    "soleidae": ["family soleidae"],
    "solemnity of mary": ["january 1"],
    "solemnize": ["solemnise"],
    "solenichthyes": ["order solenichthyes"],
    "solenidae": ["family solenidae"],
    "solenogaster": ["aplacophoran"],
    "solenogastres": ["aplacophora", "order aplacophora", "order solenogastres"],
    "solenopsis": ["genus solenopsis"],
    "solenostemon": ["genus solenostemon"],
    "soleus": ["soleus muscle"],
    "solfege": ["solfeggio"],
    "solferino": ["purplish pink"],
    "solicit": ["beg", "tap"],
    "solicitation": ["appeal", "collection", "ingathering"],
    "solicitor": ["canvasser"],
    "solicitude": ["solicitousness"],
    "solid": ["solid state", "solidness"],
    "solid figure": ["three-dimensional figure"],
    "solid solution": ["primary solid solution"],
    "solid-colored": ["solid-coloured"],
    "solidago": ["genus solidago"],
    "solidity": ["solidness"],
    "solidus": ["diagonal", "separatrix", "slash", "stroke", "virgule"],
    "soliloquy": ["monologue"],
    "solitaire": ["pezophaps solitaria"],
    "solitary confinement": ["solitary"],
    "solitary vireo": ["vireo solitarius"],
    "soliton": ["solitary wave", "soliton wave"],
    "solitude": ["purdah"],
    "solleret": ["sabaton"],
    "solmization": ["solmisation"],
    "solo homer": ["solo blast"],
    "solomons": ["solomon islands"],
    "soluble glass": ["sodium silicate", "water glass"],
    "solution": ["root"],
    "solvability": ["solubility"],
    "solvable": ["resolvable"],
    "solvay": ["ernest solvay"],
    "solve": ["figure out", "lick", "puzzle out", "work", "work out"],
    "solved": ["resolved"],
    "solvent": ["dissolvent", "dissolver", "dissolving agent", "resolvent"],
    "solzhenitsyn": ["aleksandr i. solzhenitsyn", "aleksandr solzhenitsyn", "alexander isayevich solzhenitsyn"],
    "soma": ["haoma", "sarcostemma acidum"],
    "somali peninsula": ["horn of africa"],
    "somalian": ["somali"],
    "somalian shilling": ["shilling"],
    "soman": ["gd"],
    "somateria": ["genus somateria"],
    "somatic cell": ["vegetative cell"],
    "somatic cell nuclear transplantation": ["nuclear transplantation", "scnt", "somatic cell nuclear transfer"],
    "somatogenic": ["somatogenetic"],
    "somatotropin": ["growth hormone", "human growth hormone", "somatotrophic hormone", "somatotrophin", "somatotropic hormone", "sth"],
    "somber": ["melancholy", "sombre"],
    "somberly": ["sombrely"],
    "somehow": ["in some manner", "in some way", "someway", "someways"],
    "somersault": ["flip", "somersaulting", "somerset", "summersault", "summerset"],
    "somesthesia": ["somaesthesia", "somatesthesia", "somatic sensation"],
    "somewhere": ["someplace"],
    "somme": ["battle of the somme", "somme river"],
    "sommelier": ["wine steward", "wine waiter"],
    "somrai": ["sibine"],
    "son": ["boy"],
    "sonant": ["voiced sound"],
    "sonar": ["asdic", "echo sounder"],
    "sonchus": ["genus sonchus"],
    "sondheim": ["stephen sondheim"],
    "song": ["vocal"],
    "song of songs": ["canticle of canticles", "canticles", "song of solomon"],
    "song sparrow": ["melospiza melodia"],
    "song thrush": ["mavis", "throstle", "turdus philomelos"],
    "songbird": ["songster"],
    "songwriter": ["ballad maker", "songster"],
    "sonic": ["transonic"],
    "sonic barrier": ["sound barrier"],
    "sonic depth finder": ["fathometer"],
    "sonogram": ["echogram"],
    "sonography": ["echography", "ultrasonography", "ultrasound"],
    "sonora": ["genus sonora"],
    "sonoran lyre snake": ["trimorphodon lambda"],
    "sonoran whipsnake": ["masticophis bilineatus"],
    "sonorously": ["rotundly"],
    "sontag": ["susan sontag"],
    "soon": ["before long", "presently", "shortly"],
    "sooner": ["earlier"],
    "soonest": ["earliest"],
    "soot-black": ["sooty-black"],
    "sop": ["soak through"],
    "sophism": ["sophistication", "sophistry"],
    "sophistic": ["sophistical"],
    "sophisticate": ["doctor", "doctor up"],
    "sophistication": ["mundaneness", "mundanity", "worldliness"],
    "sophomore": ["soph"],
    "sophora": ["genus sophora"],
    "soporific": ["hypnotic"],
    "soprano": ["treble"],
    "sorb": ["take up"],
    "sorbent": ["sorbent material"],
    "sorbian": ["lusatian"],
    "sorbus": ["genus sorbus"],
    "sorcerer": ["magician", "necromancer", "thaumaturge", "thaumaturgist", "wizard"],
    "sorcerize": ["sorcerise"],
    "sorcery": ["black art", "black magic", "necromancy"],
    "sordidly": ["squalidly"],
    "sordidness": ["squalidness", "squalor"],
    "sore throat": ["pharyngitis", "raw throat"],
    "sorensen": ["soren peter lauritz sorensen"],
    "sorex": ["genus sorex"],
    "sorghum": ["sorghum molasses"],
    "sorgo": ["sorgho", "sugar sorghum", "sweet sorghum"],
    "soricidae": ["family soricidae"],
    "sorrel": ["common sorrel"],
    "sorrel tree": ["oxydendrum arboreum", "sourwood", "titi"],
    "sorrow": ["regret", "rue", "ruefulness"],
    "sort": ["sorting"],
    "sort program": ["sorting program"],
    "sortie": ["sally"],
    "sotto voce": ["in a low voice"],
    "souari": ["caryocar nuciferum", "souari nut", "souari tree"],
    "soubise": ["white onion sauce"],
    "souchong": ["soochong"],
    "soufflot": ["jacques germain soufflot"],
    "sough": ["purl"],
    "sought": ["sought-after"],
    "soul": ["psyche"],
    "soul kiss": ["deep kiss", "french kiss"],
    "soul patch": ["attilio"],
    "soul-searching": ["self-analysis"],
    "sound": ["go"],
    "sound off": ["strike up"],
    "sound pressure": ["instantaneous sound pressure"],
    "sound recording": ["audio", "audio recording"],
    "sound spectrum": ["acoustic spectrum"],
    "sound wave": ["acoustic wave"],
    "soundbox": ["body"],
    "sounding board": ["soundboard"],
    "soup up": ["hop up", "hot up"],
    "soup-strainer": ["toothbrush"],
    "soupfin shark": ["galeorhinus zyopterus", "soup-fin", "soupfin"],
    "soupspoon": ["soup spoon"],
    "sour": ["acetify", "acidify", "acidulate"],
    "sour bread": ["sourdough bread"],
    "sour cherry": ["prunus cerasus", "sour cherry tree"],
    "sour cream": ["soured cream"],
    "sour dock": ["garden sorrel", "rumex acetosa"],
    "sour gourd": ["monkey bread"],
    "sour gum": ["black gum", "nyssa sylvatica", "pepperidge"],
    "sour mash": ["sour mash whiskey"],
    "sour orange": ["bigarade", "bitter orange", "bitter orange tree", "citrus aurantium", "marmalade orange", "seville orange"],
    "source": ["germ", "seed"],
    "sourdine": ["sordino"],
    "sourness": ["acidity", "sour"],
    "sourpuss": ["gloomy gus", "picklepuss", "pouter"],
    "soursop": ["annona muricata", "prickly custard apple", "soursop tree"],
    "sousa": ["john philip sousa", "march king"],
    "souse": ["hit it up", "inebriate", "soak"],
    "sousse": ["susa", "susah"],
    "south": ["due south", "southward"],
    "south africa": ["republic of south africa"],
    "south american country": ["south american nation"],
    "south american sea lion": ["otaria byronia"],
    "south american staghorn": ["platycerium andinum"],
    "south by east": ["sbe"],
    "south by west": ["sbw"],
    "south carolina": ["palmetto state", "sc"],
    "south dakota": ["coyote state", "mount rushmore state", "sd"],
    "south korea": ["republic of korea"],
    "south korean won": ["won"],
    "south platte": ["south platte river"],
    "south southeast": ["sou'-sou'-east", "sse"],
    "south southwest": ["sou'-sou'-west", "ssw"],
    "south wind": ["souther", "southerly"],
    "south-african yellowwood": ["podocarpus latifolius"],
    "south-polar": ["antarctic"],
    "south-southeast": ["sou'-sou'-east"],
    "south-southwest": ["sou'-sou'-west"],
    "southbound": ["southward"],
    "southeast": ["se", "sou'-east", "southeastward"],
    "southeast by east": ["sebe"],
    "southeast by south": ["sebs"],
    "southeaster": ["sou'easter"],
    "southeasterly": ["southeast"],
    "southeastern pocket gopher": ["geomys pinetis"],
    "southeastward": ["southeastwardly"],
    "southerly": ["southward", "southwards"],
    "southern beech": ["evergreen beech"],
    "southern blue flag": ["iris virginica"],
    "southern bog lemming": ["synaptomys cooperi"],
    "southern buckthorn": ["bumelia lycioides", "mock orange", "shittim", "shittimwood"],
    "southern cabbage butterfly": ["pieris protodice"],
    "southern crab apple": ["flowering crab", "malus angustifolia"],
    "southern cross": ["crux", "crux australis"],
    "southern dewberry": ["rubus trivialis"],
    "southern flounder": ["paralichthys lethostigmus"],
    "southern flying squirrel": ["glaucomys volans"],
    "southern harebell": ["campanula divaricata"],
    "southern live oak": ["quercus virginiana"],
    "southern magnolia": ["bull bay", "evergreen magnolia", "large-flowering magnolia", "magnolia grandiflora"],
    "southern red cedar": ["juniperus silicicola"],
    "southern red oak": ["quercus falcata", "swamp red oak", "turkey oak"],
    "southern spadefoot": ["scaphiopus multiplicatus"],
    "southern spatterdock": ["nuphar sagittifolium"],
    "southern white cedar": ["atlantic white cedar", "chamaecyparis thyoides", "coast white cedar", "white cedar", "white cypress"],
    "southernmost": ["southmost"],
    "southernwood": ["artemisia abrotanum"],
    "southey": ["robert southey"],
    "southwest": ["sou'-west", "southwestward", "sw"],
    "southwest by south": ["swbs"],
    "southwest by west": ["swbw"],
    "southwester": ["sou'wester"],
    "southwesterly": ["southwest"],
    "southwestern": ["west saxon"],
    "southwestern lip fern": ["cheilanthes eatonii"],
    "southwestern toad": ["bufo microscaphus"],
    "southwestern white pine": ["pinus strobiformis"],
    "southwestward": ["southwestwardly"],
    "soutine": ["chaim soutine"],
    "souvlaki": ["souvlakia"],
    "sovereign": ["crowned head", "monarch"],
    "soviet russia": ["russia", "russian soviet federated socialist republic"],
    "soviet union": ["russia", "union of soviet socialist republics", "ussr"],
    "sovietize": ["sovietise"],
    "sow": ["seed"],
    "sow one's oats": ["sow one's wild oats"],
    "sow thistle": ["milk thistle"],
    "sowbane": ["chenopodium hybridum", "red goosefoot"],
    "sowbread": ["cyclamen hederifolium", "cyclamen neopolitanum"],
    "soy": ["soya bean", "soybean"],
    "soy sauce": ["soy"],
    "soya milk": ["soybean milk", "soymilk"],
    "soybean meal": ["soy flour", "soybean flour"],
    "soybean oil": ["soyabean oil"],
    "space": ["blank"],
    "space capsule": ["capsule"],
    "space lattice": ["bravais lattice", "crystal lattice"],
    "space station": ["space laboratory", "space platform"],
    "space-time": ["space-time continuum"],
    "spacecraft": ["ballistic capsule", "space vehicle"],
    "spacecraft clock time": ["sclk"],
    "spacecraft event time": ["scet"],
    "spaced-out": ["spacey", "spacy"],
    "spaceflight": ["space travel", "spacefaring"],
    "spaceward": ["spacewards"],
    "spacing": ["spatial arrangement"],
    "spackle": ["spackling compound"],
    "spade-shaped": ["spade-like"],
    "spadefish": ["angelfish", "chaetodipterus faber"],
    "spadefoot": ["spadefoot toad"],
    "spaghetti sauce": ["pasta sauce"],
    "spain": ["espana", "kingdom of spain"],
    "spalacidae": ["family spalacidae"],
    "spalax": ["genus spalax"],
    "spall": ["spawl"],
    "spallanzani": ["lazzaro spallanzani"],
    "spam": ["junk e-mail"],
    "spandrel": ["spandril"],
    "spang": ["bang"],
    "spangle": ["bespangle"],
    "spanish": ["spanish people"],
    "spanish american": ["hispanic", "hispanic american"],
    "spanish armada": ["invincible armada"],
    "spanish bayonet": ["yucca baccata"],
    "spanish broom": ["spartium junceum", "weaver's broom"],
    "spanish cedar": ["cedrela odorata", "spanish cedar tree"],
    "spanish dagger": ["yucca gloriosa"],
    "spanish elm": ["cordia alliodora", "cypre", "equador laurel", "princewood", "salmwood"],
    "spanish grunt": ["haemulon macrostomum"],
    "spanish heath": ["erica lusitanica", "portuguese heath"],
    "spanish iris": ["iris xiphium", "xiphium iris"],
    "spanish lime": ["genip", "ginep", "honey berry", "mamoncillo", "melicocca bijuga", "melicocca bijugatus", "spanish lime tree"],
    "spanish mackerel": ["scomber colias"],
    "spanish moss": ["black moss", "long moss", "old man's beard", "tillandsia usneoides"],
    "spanish needles": ["beggar-ticks"],
    "spanish oak": ["quercus texana"],
    "spanish oyster plant": ["scolymus hispanicus"],
    "spanish tamarind": ["vangueria madagascariensis"],
    "spanish-american war": ["spanish war"],
    "spank": ["larrup", "paddle"],
    "spar": ["sparring"],
    "sparaxis": ["genus sparaxis"],
    "spare": ["save"],
    "spare part": ["spare"],
    "spare time": ["free time"],
    "spare tire": ["love handle"],
    "sparganiaceae": ["bur-reed family", "family sparganiaceae"],
    "sparganium": ["genus sparganium"],
    "sparid": ["sparid fish"],
    "sparidae": ["family sparidae"],
    "spark": ["sparkle"],
    "spark advance": ["lead"],
    "spark arrester": ["sparker"],
    "spark chamber": ["spark counter"],
    "spark plug": ["plug", "sparking plug"],
    "sparkle": ["coruscate", "scintillate"],
    "sparkling": ["effervescent"],
    "sparling": ["european smelt", "osmerus eperlanus"],
    "sparmannia": ["genus sparmannia"],
    "sparring partner": ["sparring mate"],
    "sparrow": ["true sparrow"],
    "sparrow hawk": ["american kestrel", "falco sparverius", "kestrel"],
    "sparse": ["thin"],
    "sparseness": ["spareness", "sparsity", "thinness"],
    "spartina": ["genus spartina"],
    "spartium": ["genus spartium"],
    "spasm": ["cramp", "muscle spasm"],
    "spasmodically": ["jerkily"],
    "spassky": ["boris spassky", "boris vasilevich spassky"],
    "spat": ["gaiter"],
    "spatangoida": ["order spatangoida"],
    "spathiphyllum": ["peace lily", "spathe flower"],
    "spatial": ["spacial"],
    "spatial property": ["spatiality"],
    "spatiotemporal": ["spaciotemporal"],
    "spatter": ["bespatter"],
    "spatterdock": ["cow lily", "nuphar advena", "yellow pond lily"],
    "spatulate": ["spatula-shaped"],
    "speak": ["talk"],
    "speakable": ["utterable"],
    "speaker": ["talker", "utterer", "verbaliser", "verbalizer"],
    "speaker identification": ["talker identification"],
    "speaking": ["speech production"],
    "spear": ["spear up"],
    "spearhead": ["spear-point", "spearpoint"],
    "spearmint": ["mentha spicata"],
    "special air service": ["sas"],
    "special drawing rights": ["paper gold"],
    "special forces": ["u. s. army special forces", "united states army special forces"],
    "special jury": ["blue ribbon jury"],
    "special relativity": ["einstein's special theory of relativity", "special relativity theory", "special theory of relativity"],
    "specialist": ["medical specialist"],
    "specialization": ["differentiation", "specialisation"],
    "specialize": ["specialise"],
    "specialized": ["specialised"],
    "specially": ["especially"],
    "speciate": ["differentiate", "specialise", "specialize"],
    "specification": ["spec"],
    "specify": ["define", "delimit", "delimitate", "delineate"],
    "specious": ["spurious"],
    "speciousness": ["meretriciousness"],
    "speck": ["pinpoint"],
    "speckle": ["bespeckle"],
    "speckled alder": ["alnus rugosa"],
    "speckled rattlesnake": ["crotalus mitchellii"],
    "spectacled caiman": ["caiman sclerops"],
    "spectacles": ["eyeglasses", "glasses", "specs"],
    "spectacularly": ["stunningly"],
    "spectator": ["looker", "viewer", "watcher", "witness"],
    "spectator pump": ["spectator"],
    "spectrogram": ["spectrograph"],
    "spectroscope": ["prism spectroscope"],
    "spectroscopic": ["spectroscopical"],
    "spectroscopy": ["spectrographic analysis", "spectrometry", "spectroscopic analysis", "spectrum analysis"],
    "speculate": ["job"],
    "speculation": ["venture"],
    "speculator": ["plunger"],
    "speech": ["language", "oral communication", "speech communication", "spoken communication", "spoken language", "voice communication"],
    "speech disorder": ["defect of speech", "speech defect"],
    "speech organ": ["organ of speech", "vocal organ"],
    "speechless": ["dumb"],
    "speed": ["velocity"],
    "speed of light": ["light speed"],
    "speed skate": ["racing skate"],
    "speeder": ["speed demon"],
    "speedometer": ["speed indicator"],
    "speedskater": ["speed skater"],
    "speer": ["albert speer"],
    "speke": ["john hanning speke", "john speke"],
    "speleology": ["spelaeology"],
    "spell": ["write"],
    "spell-checker": ["spelling checker"],
    "speller": ["good speller", "poor speller"],
    "spelling bee": ["spelldown", "spelling contest"],
    "spelt": ["triticum aestivum spelta", "triticum spelta"],
    "spencer": ["herbert spencer"],
    "spend": ["pass"],
    "spender": ["sir stephen harold spender", "stephen spender"],
    "spending": ["disbursal", "disbursement", "outlay"],
    "spendthrift": ["scattergood", "spend-all", "spender"],
    "spengler": ["oswald spengler"],
    "spenser": ["edmund spenser"],
    "spergula": ["genus spergula"],
    "spergularia": ["genus spergularia"],
    "sperm": ["sperm cell", "spermatozoan", "spermatozoon"],
    "sperm whale": ["black whale", "cachalot", "physeter catodon"],
    "spermatophyta": ["division spermatophyta"],
    "spermatophyte": ["phanerogam", "seed plant"],
    "spermicide": ["spermatocide"],
    "spermous": ["spermatic"],
    "sperry": ["elmer ambrose sperry"],
    "spew": ["eruct", "spew out"],
    "sphacelotheca": ["genus sphacelotheca"],
    "sphaeralcea": ["genus sphaeralcea"],
    "sphaeriaceae": ["family sphaeriaceae"],
    "sphaeriales": ["order sphaeriales"],
    "sphaerobolaceae": ["family sphaerobolaceae"],
    "sphaerocarpaceae": ["family sphaerocarpaceae"],
    "sphaerocarpales": ["order sphaerocarpales"],
    "sphaerocarpus": ["genus sphaerocarpos", "genus sphaerocarpus", "sphaerocarpos"],
    "sphagnales": ["order sphagnales"],
    "sphagnum": ["bog moss", "peat moss", "sphagnum moss"],
    "sphecidae": ["family sphecidae"],
    "sphecius": ["genus sphecius"],
    "sphecoid wasp": ["sphecoid"],
    "sphecoidea": ["superfamily sphecoidea"],
    "sphecotheres": ["genus sphecotheres"],
    "spheniscidae": ["family spheniscidae"],
    "sphenisciformes": ["order sphenisciformes"],
    "spheniscus": ["genus spheniscus"],
    "sphenodon": ["genus sphenodon"],
    "sphenoid bone": ["os sphenoidale", "sphenoid"],
    "sphenoid fontanelle": ["sphenoid fontanel", "sphenoidal fontanel", "sphenoidal fontanelle"],
    "sphenopsida": ["class equisetatae", "class sphenopsida", "equisetatae"],
    "sphere": ["area", "arena", "domain", "field", "orbit"],
    "sphericity": ["globosity", "globularness", "rotundity", "rotundness", "sphericalness"],
    "spheroid": ["ellipsoid of revolution"],
    "sphincter": ["anatomical sphincter", "sphincter muscle"],
    "sphingidae": ["family sphingidae"],
    "sphyraena": ["genus sphyraena"],
    "sphyraenidae": ["family sphyraenidae"],
    "sphyrapicus": ["genus sphyrapicus"],
    "sphyrna": ["genus sphyrna"],
    "sphyrnidae": ["family sphyrnidae"],
    "spic": ["spick", "spik"],
    "spiccato": ["spiccato bowing"],
    "spice": ["spice up"],
    "spicebush": ["american spicebush", "benjamin bush", "benzoin odoriferum", "lindera benzoin", "spice bush"],
    "spiciness": ["spice", "spicery"],
    "spicule": ["spiculum"],
    "spider": ["wanderer"],
    "spider angioma": ["spider nevus", "vascular spider"],
    "spider brake": ["pteris multifida", "spider fern"],
    "spider flower": ["cleome hassleriana", "spider plant"],
    "spider mite": ["tetranychid"],
    "spider monkey": ["ateles geoffroyi"],
    "spider orchid": ["brassia verrucosa"],
    "spider web": ["spider's web"],
    "spiderflower": ["cleome"],
    "spiderwort": ["dayflower"],
    "spiegeleisen": ["spiegel", "spiegel iron"],
    "spiel": ["line of gab", "patter"],
    "spielberg": ["steven spielberg"],
    "spielmeyer-vogt disease": ["juvenile amaurotic idiocy"],
    "spike": ["spike out"],
    "spike heath": ["bruckenthalia spiculifolia"],
    "spike heel": ["spike", "stiletto heel"],
    "spike lavender": ["french lavender", "lavandula latifolia"],
    "spike lavender oil": ["spike oil"],
    "spikemoss": ["little club moss", "spike moss"],
    "spill": ["run out"],
    "spill over": ["pour out", "spill out"],
    "spill the beans": ["babble", "babble out", "blab", "blab out", "let the cat out of the bag", "peach", "sing", "talk", "tattle"],
    "spillane": ["frank morrison spillane", "mickey spillane"],
    "spillway": ["spill", "wasteweir"],
    "spilogale": ["genus spilogale"],
    "spin": ["gyrate", "reel", "spin around", "whirl"],
    "spin doctor": ["spinmeister"],
    "spin dryer": ["spin drier"],
    "spin the plate": ["spin the platter"],
    "spina bifida": ["rachischisis", "schistorrhachis"],
    "spinach": ["prickly-seeded spinach", "spinach plant", "spinacia oleracea"],
    "spinacia": ["genus spinacia"],
    "spinal anesthesia": ["spinal", "spinal anaesthesia"],
    "spinal anesthetic": ["spinal anaesthetic"],
    "spinal canal": ["canalis vertebralis", "vertebral canal"],
    "spinal column": ["back", "backbone", "rachis", "spine", "vertebral column"],
    "spinal cord": ["medulla spinalis"],
    "spinal fluid": ["cerebrospinal fluid"],
    "spinal nerve": ["nervus spinalis"],
    "spinal vein": ["vena spinalis"],
    "spindle": ["arbor", "mandrel", "mandril"],
    "spindle tree": ["spindleberry", "spindleberry tree"],
    "spindle-legged": ["spindle-shanked"],
    "spindlelegs": ["spindleshanks"],
    "spindrift": ["spoondrift"],
    "spine": ["pricker", "prickle", "spikelet", "sticker", "thorn"],
    "spinel ruby": ["ruby spinel"],
    "spinnable": ["spinnbar"],
    "spinner": ["spinster", "thread maker"],
    "spinous": ["spiny"],
    "spinoza": ["baruch de spinoza", "benedict de spinoza", "de spinoza"],
    "spinster": ["old maid"],
    "spinus": ["genus spinus"],
    "spiny lobster": ["crayfish", "langouste", "rock lobster"],
    "spiny softshell": ["trionyx spiniferus"],
    "spiny talinum": ["talinum spinescens"],
    "spiny-finned fish": ["acanthopterygian"],
    "spiny-leaved": ["spiny-leafed"],
    "spiraea": ["genus spiraea"],
    "spiral": ["volute"],
    "spiral galaxy": ["spiral nebula"],
    "spiral ratchet screwdriver": ["ratchet screwdriver"],
    "spiranthes": ["genus spiranthes"],
    "spirea": ["astilbe japonica", "spiraea"],
    "spirillaceae": ["family spirillaceae"],
    "spirillum": ["spirilla"],
    "spirit": ["inspirit", "spirit up"],
    "spirit away": ["spirit off"],
    "spiritize": ["spiritise"],
    "spirits of ammonia": ["sal volatile"],
    "spiritual": ["negro spiritual"],
    "spiritual being": ["supernatural being"],
    "spiritual world": ["spiritual domain", "unseen"],
    "spiritualistic": ["spiritualist"],
    "spirituality": ["otherworldliness", "spiritism", "spiritualism"],
    "spiritualization": ["spiritualisation"],
    "spiritualize": ["spiritualise"],
    "spiritualty": ["church property", "spirituality"],
    "spirituous": ["spiritous"],
    "spirochaeta": ["genus spirochaeta"],
    "spirochaetaceae": ["family spirochaetaceae"],
    "spirochaetales": ["order spirochaetales"],
    "spirochete": ["spirochaete"],
    "spirodela": ["genus spirodela"],
    "spironolactone": ["aldactone"],
    "spirula": ["spirula peronii"],
    "spirulidae": ["family spirulidae"],
    "spit": ["spit out"],
    "spit curl": ["kiss curl"],
    "spitball": ["spitter"],
    "spitsbergen": ["spitzbergen"],
    "spitter": ["expectorator"],
    "spittle insect": ["spittlebug"],
    "spittoon": ["cuspidor"],
    "spizella": ["genus spizella"],
    "splash": ["slosh", "slush", "splosh"],
    "splashboard": ["dashboard", "splasher"],
    "splayfooted": ["splayfoot"],
    "spleen": ["lien"],
    "splenic": ["lienal", "splenetic"],
    "splenic vein": ["vena lienalis"],
    "splenius": ["splenius muscle"],
    "splice": ["splicing"],
    "splinter": ["sliver"],
    "splintery": ["slivery"],
    "split": ["split up", "stock split"],
    "split personality": ["multiple personality"],
    "split rail": ["fence rail"],
    "split-half correlation": ["chance-half correlation"],
    "splitter": ["divider"],
    "splurge": ["fling"],
    "splutter": ["spit out", "sputter"],
    "spock": ["benjamin spock"],
    "spode": ["josiah spode"],
    "spodoptera": ["genus spodoptera"],
    "spoil": ["go bad"],
    "spoilage": ["spoiling"],
    "spoiled": ["spoilt"],
    "spoilsport": ["killjoy", "party pooper", "wet blanket"],
    "spoke": ["radius", "wheel spoke"],
    "spokesperson": ["interpreter", "representative", "voice"],
    "spondaize": ["spondaise"],
    "spondias": ["genus spondias"],
    "sponge": ["parazoan", "poriferan"],
    "sponge down": ["sponge off"],
    "spongefly": ["spongillafly"],
    "spongy": ["spongelike", "squashy", "squishy"],
    "sponsor": ["patronise", "patronize"],
    "spontaneity": ["spontaneousness"],
    "spontaneous": ["self-generated"],
    "spontaneous abortion": ["miscarriage", "stillbirth"],
    "spoof": ["burlesque", "parody"],
    "spoon": ["spoonful"],
    "spoon bread": ["batter bread"],
    "sporadically": ["periodically"],
    "sporangium": ["spore case", "spore sac"],
    "sporobolus": ["genus sporobolus"],
    "sporocarp": ["spore case"],
    "sporophyll": ["sporophyl"],
    "sporozoa": ["class sporozoa"],
    "sport": ["boast", "feature"],
    "sport kite": ["stunt kite"],
    "sport utility": ["s.u.v.", "sport utility vehicle", "suv"],
    "sporting dog": ["gun dog"]
}
