synonyms = {
    "restlessness": ["impatience"],
    "restore": ["reconstruct"],
    "restrain": ["hold back", "keep", "keep back"],
    "restrained": ["reticent", "unemotional"],
    "restrainer": ["controller"],
    "restraint": ["control"],
    "restrict": ["curb", "curtail", "cut back"],
    "restricted": ["qualified"],
    "restriction": ["limitation"],
    "restriction endonuclease": ["restriction enzyme", "restriction nuclease"],
    "restructure": ["reconstitute"],
    "result": ["ensue"],
    "resultant": ["end point"],
    "resultant role": ["result"],
    "resume": ["take up"],
    "resumption": ["recommencement"],
    "resurgent": ["renascent"],
    "resurrect": ["rise", "uprise"],
    "resurrection": ["christ's resurrection", "resurrection of christ"],
    "resurrection plant": ["rose of jericho", "selaginella lepidophylla"],
    "resuscitate": ["revive"],
    "retailer": ["retail merchant"],
    "retain": ["continue", "keep", "keep on"],
    "retained": ["maintained"],
    "retainer": ["consideration"],
    "retaliate": ["strike back"],
    "retaliation": ["revenge"],
    "retaliatory": ["relatiative", "retributive", "retributory", "vindicatory"],
    "retama": ["genus retama"],
    "retardant": ["retardation", "retardent"],
    "retardation": ["backwardness", "mental retardation", "slowness", "subnormality"],
    "retem": ["genista raetam", "juniper", "juniper bush", "raetam", "retama raetam"],
    "retention": ["holding", "keeping"],
    "retentive": ["long", "recollective", "tenacious"],
    "retentiveness": ["retentivity"],
    "reticent": ["untalkative"],
    "reticle": ["graticule", "reticule"],
    "reticular activating system": ["ras"],
    "reticular formation": ["rf"],
    "reticulate": ["reticular"],
    "reticulated python": ["python reticulatus"],
    "reticulitermes": ["genus reticulitermes"],
    "reticuloendothelial system": ["res"],
    "reticulum": ["second stomach"],
    "retinal detachment": ["detached retina", "detachment of the retina"],
    "retinene": ["retinal"],
    "retire": ["withdraw"],
    "retiree": ["retired person"],
    "retirement": ["retreat"],
    "retirement community": ["retirement complex"],
    "retiring": ["unassuming"],
    "retool": ["revise"],
    "retort": ["come back", "rejoin", "repay", "return", "riposte"],
    "retract": ["draw back", "pull back"],
    "retraction": ["abjuration", "recantation"],
    "retral": ["retrograde"],
    "retread": ["remold", "remould"],
    "retreat": ["back away", "back out", "crawfish", "crawfish out", "pull back", "pull in one's horns", "withdraw"],
    "retrenchment": ["curtailment", "downsizing"],
    "retribution": ["requital"],
    "retributive": ["retributory", "vindicatory"],
    "retroflection": ["retroflexion"],
    "retroflex": ["replicate"],
    "retrograde": ["retreat"],
    "retromandibular vein": ["posterior facial vein", "vena retromandibularis"],
    "retrophyllum": ["genus retrophyllum"],
    "retrousse": ["tip-tilted", "upturned"],
    "retroversion": ["retroflection", "retroflexion"],
    "return": ["bring back", "take back"],
    "return key": ["return"],
    "return on invested capital": ["return on investment", "roi"],
    "returning": ["reverting"],
    "reunify": ["reunite"],
    "reunion": ["reunification"],
    "reuptake": ["re-uptake"],
    "rev up": ["step up"],
    "revealing": ["telling", "telltale"],
    "reveille": ["wake-up signal"],
    "revel": ["jollify", "make happy", "make merry", "make whoopie", "racket", "wassail", "whoop it up"],
    "revelation": ["divine revelation"],
    "reveler": ["merrymaker", "reveller"],
    "revenge": ["avenge", "retaliate"],
    "revengeful": ["vengeful", "vindictive"],
    "revengefully": ["vengefully", "vindictively"],
    "revenue stamp": ["stamp"],
    "revere": ["paul revere"],
    "reverence": ["fear", "revere", "venerate"],
    "reverend": ["sublime"],
    "reverentially": ["reverently"],
    "reverie": ["air castle", "castle in spain", "castle in the air", "daydream", "daydreaming", "oneirism", "revery"],
    "revers": ["revere"],
    "reversal": ["turn around"],
    "reverse": ["contrary", "opposite"],
    "reverse split": ["reverse stock split", "split down"],
    "reversible": ["two-sided"],
    "reversion": ["reversal", "reverse", "turnabout", "turnaround"],
    "reversionary annuity": ["survivorship annuity"],
    "revert": ["regress", "retrovert", "return", "turn back"],
    "revetment": ["revetement", "stone facing"],
    "review": ["critique"],
    "reviewer": ["reader", "referee"],
    "revision": ["rescript", "revisal", "revise"],
    "revitalize": ["revitalise"],
    "revitalized": ["revitalised"],
    "revival": ["revival meeting"],
    "revive": ["resurrect"],
    "revocable": ["revokable"],
    "revocation": ["annulment"],
    "revoke": ["annul", "countermand", "lift", "overturn", "repeal", "rescind", "reverse", "vacate"],
    "revolutionary": ["radical"],
    "revolutionary armed forces of colombia": ["farc", "fuerzas armadas revolucionarios de colombia"],
    "revolutionary organization 17 november": ["17 november"],
    "revolutionary people's liberation party": ["revolutionary people's liberation front"],
    "revolutionary people's struggle": ["ela"],
    "revolutionary proletarian nucleus": ["nipr", "revolutionary proletarian initiative nuclei"],
    "revolutionary united front": ["ruf"],
    "revolutionist": ["revolutionary", "subversive", "subverter"],
    "revolutionize": ["inspire", "revolutionise"],
    "revolutions per minute": ["rev", "rpm"],
    "revolve": ["go around", "rotate"],
    "revolve around": ["circle around", "circle round"],
    "revolver": ["six-gun", "six-shooter"],
    "revolving door": ["revolver"],
    "revue": ["review"],
    "rewa-rewa": ["new zealand honeysuckle"],
    "reward": ["pay back", "repay"],
    "rewording": ["recasting", "rephrasing"],
    "rework": ["make over", "retread"],
    "rewrite": ["rescript", "revision"],
    "rewriting": ["revising"],
    "rex begonia": ["beefsteak geranium", "begonia rex", "king begonia", "painted-leaf begonia"],
    "reykjavik": ["capital of iceland"],
    "reynolds": ["sir joshua reynolds"],
    "rh-negative blood type": ["rh negative", "rh-negative blood"],
    "rh-positive blood type": ["rh positive"],
    "rhabdomyosarcoma": ["rhabdosarcoma"],
    "rhaeto-romance": ["rhaeto-romanic"],
    "rhagoletis": ["genus rhagoletis"],
    "rhamnaceae": ["buckthorn family", "family rhamnaceae"],
    "rhamnales": ["order rhamnales"],
    "rhamnus": ["genus rhamnus"],
    "rhapis": ["genus rhapis"],
    "rhapsodize": ["rhapsodise"],
    "rhea": ["nandu", "pterocnemia pennata"],
    "rhea silvia": ["rea silvia"],
    "rheidae": ["family rheidae"],
    "rheiformes": ["order rheiformes"],
    "rheims": ["reims"],
    "rhenium": ["atomic number 75", "re"],
    "rheologic": ["rheological"],
    "rheostat": ["variable resistor"],
    "rhesus": ["macaca mulatta", "rhesus monkey"],
    "rhesus factor": ["rh", "rh factor"],
    "rheum": ["genus rheum"],
    "rheumatoid arthritis": ["atrophic arthritis", "rheumatism"],
    "rhexia": ["genus rhexia"],
    "rhinal": ["nasal"],
    "rhincodon": ["genus rhincodon"],
    "rhincodontidae": ["family rhincodontidae"],
    "rhine": ["j. b. rhine", "joseph banks rhine"],
    "rhine wine": ["hock", "rhenish"],
    "rhineland": ["rheinland"],
    "rhinencephalon": ["olfactory brain"],
    "rhinitis": ["coryza"],
    "rhinobatidae": ["family rhinobatidae"],
    "rhinoceros": ["rhino"],
    "rhinocerotidae": ["family rhinocerotidae", "rhinoceros family"],
    "rhinolaryngology": ["otolaryngology", "otorhinolaryngology"],
    "rhinolophidae": ["family rhinolophidae"],
    "rhinonicteris": ["genus rhinonicteris"],
    "rhinophyma": ["brandy nose", "copper nose", "hammer nose", "hypertrophic rosacea", "potato nose", "rum nose", "rum-blossom", "toper's nose"],
    "rhinoptera": ["genus rhinoptera"],
    "rhinotermitidae": ["family rhinotermitidae"],
    "rhipsalis": ["genus rhipsalis"],
    "rhizobiaceae": ["family rhizobiaceae"],
    "rhizobium": ["genus rhizobium"],
    "rhizome": ["rootstalk", "rootstock"],
    "rhizophora": ["genus rhizophora"],
    "rhizophoraceae": ["family rhizophoraceae", "mangrove family"],
    "rhizopod": ["rhizopodan"],
    "rhizopoda": ["subclass rhizopoda"],
    "rhizopogon": ["genus rhizopogon"],
    "rhizopogonaceae": ["family rhizopogonaceae"],
    "rhode island": ["little rhody", "ocean state", "ri"],
    "rhodes": ["cecil j. rhodes", "cecil john rhodes", "cecil rhodes"],
    "rhodes grass": ["chloris gayana"],
    "rhodesian man": ["homo rhodesiensis"],
    "rhodium": ["atomic number 45", "rh"],
    "rhodophyceae": ["class rhodophyceae"],
    "rhodophyta": ["division rhodophyta"],
    "rhodosphaera": ["genus rhodosphaera"],
    "rhodymenia": ["genus rhodymenia"],
    "rhodymeniaceae": ["family rhodymeniaceae"],
    "rhoeadales": ["order papaverales", "order rhoeadales", "papaverales"],
    "rhombohedral": ["trigonal"],
    "rhomboid": ["rhomboid muscle"],
    "rhomboid minor muscle": ["lesser rhomboid muscle", "musculus rhomboideus minor"],
    "rhomboideus major muscle": ["greater rhomboid muscle", "musculus rhomboideus major"],
    "rhombus": ["diamond", "rhomb"],
    "rhone": ["rhone river"],
    "rhubarb": ["rhubarb plant"],
    "rhumb line": ["loxodrome", "rhumb"],
    "rhumba": ["rumba"],
    "rhus": ["genus rhus"],
    "rhyacotriton": ["genus rhyacotriton"],
    "rhyme": ["rime"],
    "rhymed": ["rhyming", "riming"],
    "rhymer": ["poetiser", "poetizer", "rhymester", "versifier"],
    "rhynchocephalia": ["order rhynchocephalia"],
    "rhynchoelaps": ["genus rhynchoelaps"],
    "rhyncostylis": ["genus rhyncostylis"],
    "rhynia": ["genus rhynia"],
    "rhyniaceae": ["family rhyniaceae"],
    "rhythm": ["beat", "musical rhythm"],
    "rhythm and blues": ["r and b"],
    "rhythm method of birth control": ["calendar method", "calendar method of birth control", "rhythm", "rhythm method"],
    "rhythmical": ["rhythmic"],
    "rib": ["costa"],
    "rib roast": ["standing rib roast"],
    "riband": ["ribband"],
    "ribavirin": ["virazole"],
    "ribbon": ["thread"],
    "ribbon fern": ["pteris serrulata", "spider fern"],
    "ribbon snake": ["thamnophis sauritus"],
    "ribbon tree": ["plagianthus betulinus", "plagianthus regius", "ribbonwood"],
    "ribbon worm": ["nemertean", "nemertine", "proboscis worm"],
    "ribbonlike": ["ribbony"],
    "ribes": ["genus ribes"],
    "ribhus": ["rhibhus"],
    "ribonuclease": ["ribonucleinase", "rnase"],
    "ribonucleic acid": ["rna"],
    "ricardo": ["david ricardo"],
    "rice": ["sir tim rice", "timothy miles bindon rice"],
    "rice rat": ["oryzomys palustris"],
    "rice weevil": ["black weevil", "sitophylus oryzae"],
    "ricegrass": ["rice grass"],
    "rich people": ["rich"],
    "rich person": ["have", "wealthy person"],
    "richard i": ["richard coeur de lion", "richard the lion-hearted", "richard the lionheart"],
    "richards": ["i. a. richards", "ivor armstrong richards"],
    "richardson": ["henry hobson richardson"],
    "richardson's geranium": ["geranium richardsonii"],
    "richea": ["genus richea"],
    "richelieu": ["armand jean du plessis", "cardinal richelieu", "duc de richelieu"],
    "richler": ["mordecai richler"],
    "richmond": ["capital of virginia"],
    "richmondena": ["genus richmondena"],
    "richness": ["fertility", "prolificacy", "rankness"],
    "richweed": ["clearweed", "dead nettle", "pilea pumilla"],
    "ricin": ["ricin toxin"],
    "ricinus": ["genus ricinus"],
    "rickenbacker": ["eddie rickenbacker", "edward vernon rickenbacker"],
    "rickets": ["rachitis"],
    "rickettsiaceae": ["family rickettsiaceae"],
    "rickettsial disease": ["rickettsiosis"],
    "rickettsiales": ["order rickettsiales"],
    "rickety": ["rachitic"],
    "rickover": ["hyman george rickover", "hyman rickover"],
    "rickrack": ["ricrac"],
    "ricochet": ["carom"],
    "rid": ["disembarrass", "free"],
    "riddle": ["screen"],
    "ride": ["sit"],
    "ride off": ["ride away"],
    "ride roughshod": ["run roughshod"],
    "ride the bench": ["warm the bench"],
    "ridge": ["ridgeline"],
    "ridged": ["carinate", "carinated", "keeled"],
    "ridgeling": ["ridgel", "ridgil", "ridgling"],
    "ridicule": ["blackguard", "guy", "jest at", "laugh at", "make fun", "poke fun", "rib", "roast"],
    "riding": ["equitation", "horseback riding"],
    "riding crop": ["hunting crop"],
    "riemann": ["bernhard riemann", "georg friedrich bernhard riemann"],
    "riesman": ["david riesman", "david riesman jr."],
    "rifampin": ["rifadin", "rimactane"],
    "riff": ["riffian"],
    "rifle": ["go"],
    "rifle range": ["rifle shot"],
    "riflebird": ["ptloris paradisea"],
    "rifleman bird": ["acanthisitta chloris"],
    "rig": ["set up"],
    "riga": ["capital of latvia"],
    "rigel": ["beta orionis"],
    "rigger": ["oil rigger"],
    "rigging": ["tackle"],
    "right": ["compensate", "correct", "redress"],
    "right ascension": ["celestial longitude", "ra"],
    "right atrium": ["atrium dextrum", "right atrium of the heart"],
    "right field": ["right", "rightfield"],
    "right gastric artery": ["ateria gastrica dextra"],
    "right hemisphere": ["right brain"],
    "right to vote": ["suffrage", "vote"],
    "right triangle": ["right-angled triangle"],
    "right-hand man": ["chief assistant", "man friday"],
    "right-handed pitcher": ["right-hander"],
    "right-handedness": ["dextrality"],
    "right-hander": ["right hander", "righthander"],
    "righteye flounder": ["righteyed flounder"],
    "rightfully": ["truly"],
    "rightist": ["right-winger"],
    "rightly": ["justifiedly", "justly"],
    "rights offering": ["rights issue"],
    "rigid": ["strict"],
    "rigidify": ["ossify", "petrify"],
    "rigidity": ["rigidness"],
    "rigidly": ["bolt", "stiffly"],
    "rigmarole": ["rigamarole"],
    "rigorous": ["strict"],
    "rigorously": ["strictly"],
    "rijsttaffel": ["rijstafel", "rijstaffel"],
    "riksmal": ["riksmaal"],
    "riley": ["james whitcomb riley"],
    "rilke": ["rainer maria rilke"],
    "rima glottidis": ["glottis vera", "rima vocalis", "true glottis"],
    "rima vestibuli": ["false glottis", "glottis spuria", "rima respiratoria"],
    "rimbaud": ["arthur rimbaud", "jean nicholas arthur rimbaud"],
    "rimsky-korsakov": ["nikolai andreyevich rimski-korsakov", "nikolai andreyevich rimsky-korsakov", "rimski-korsakov"],
    "rimu": ["dacrydium cupressinum", "imou pine", "red pine"],
    "rinderpest": ["cattle plague"],
    "ring": ["knell"],
    "ring finger": ["annualry"],
    "ring ouzel": ["ring blackbird", "ring thrush", "turdus torquatus"],
    "ring rot": ["ring disease", "tobacco wilt"],
    "ring rot bacteria": ["pseudomonas solanacearum"],
    "ring-around-the-rosy": ["ring-a-rosy", "ring-around-a-rosy"],
    "ring-necked parakeet": ["psittacula krameri"],
    "ring-necked pheasant": ["phasianus colchicus"],
    "ringdove": ["streptopelia risoria"],
    "ringer": ["clone", "dead ringer"],
    "ringer's solution": ["ringer solution"],
    "ringhals": ["hemachatus haemachatus", "rinkhals", "spitting snake"],
    "ringlet": ["ringlet butterfly"],
    "ringling": ["charles ringling"],
    "ringneck snake": ["ring snake", "ring-necked snake"],
    "ringside": ["ringside seat"],
    "ringworm bush": ["cassia alata", "ringworm cassia", "ringworm shrub", "senna alata"],
    "rink": ["skating rink"],
    "rinse": ["rinse off"],
    "rio de janeiro": ["rio"],
    "rio de la plata": ["la plata", "plata river"],
    "rio grande": ["rio bravo"],
    "riot": ["public violence"],
    "riot control": ["riot control operation"],
    "rioting": ["riot"],
    "rip": ["rent", "snag", "split", "tear"],
    "riparia": ["genus riparia"],
    "ripe": ["mature"],
    "ripen": ["mature"],
    "ripening": ["ageing", "aging"],
    "ripple": ["babble", "bubble", "burble", "guggle", "gurgle"],
    "rippled": ["ruffled"],
    "ripsaw": ["splitsaw"],
    "riptide": ["rip current"],
    "rise": ["lift", "rear"],
    "riser": ["riser main", "riser pipe", "riser pipeline"],
    "risk": ["lay on the line", "put on the line"],
    "risk arbitrage": ["takeover arbitrage"],
    "risk-free": ["riskless", "unhazardous"],
    "riskiness": ["peril"],
    "risotto": ["italian rice"],
    "rissa": ["genus rissa"],
    "rite": ["religious rite"],
    "ritonavir": ["norvir"],
    "rittenhouse": ["david rittenhouse"],
    "ritual": ["rite"],
    "ritual dancing": ["ceremonial dance", "ritual dance"],
    "ritualize": ["ritualise"],
    "ritz": ["cesar ritz"],
    "rival": ["challenger", "competition", "competitor", "contender"],
    "river basin": ["basin", "catchment area", "catchment basin", "drainage area", "drainage basin", "watershed"],
    "river limpet": ["ancylus fluviatilis", "freshwater limpet"],
    "river otter": ["lutra canadensis"],
    "river red gum": ["eucalyptus camaldulensis", "eucalyptus rostrata", "river gum"],
    "river shad": ["alosa chrysocloris"],
    "rivera": ["diego rivera"],
    "riverbank": ["riverside"],
    "riverbed": ["river bottom"],
    "riveter": ["rivetter"],
    "riveting machine": ["riveter", "rivetter"],
    "rivina": ["genus rivina"],
    "rivulet": ["rill", "run", "runnel", "streamlet"],
    "riyadh": ["capital of saudi arabia"],
    "riyal-omani": ["omani rial", "rial"],
    "roach": ["rutilus rutilus"],
    "roach clip": ["roach holder"],
    "road": ["route"],
    "road hog": ["roadhog"],
    "road map": ["guideline"],
    "roadblock": ["barricade"],
    "roadman": ["road mender"],
    "roadrunner": ["chaparral cock", "geococcyx californianus"],
    "roads": ["roadstead"],
    "roadster": ["runabout", "two-seater"],
    "roar": ["howl"],
    "roarer": ["bawler", "bellower", "screamer", "screecher", "shouter", "yeller"],
    "roast": ["joint"],
    "robber fly": ["bee killer"],
    "robbins": ["jerome robbins"],
    "robert": ["henry m. robert", "henry martyn robert"],
    "robert e lee's birthday": ["january 19", "lee's birthday", "robert e lee day"],
    "roberts": ["richard j. roberts", "richard john roberts"],
    "robertson": ["oscar palmer robertson", "oscar robertson"],
    "robeson": ["paul bustill robeson", "paul robeson"],
    "robespierre": ["maxmillien marie isidore de robespierre"],
    "robin": ["erithacus rubecola", "old world robin", "redbreast", "robin redbreast"],
    "robin's plantain": ["erigeron pulchellus"],
    "robinia": ["genus robinia"],
    "robinson": ["robert robinson", "sir robert robinson"],
    "roble": ["platymiscium trinitatis"],
    "roble beech": ["nothofagus obliqua"],
    "robusta coffee": ["coffea canephora", "coffea robusta", "rio nunez coffee"],
    "robustness": ["hardiness", "lustiness", "validity"],
    "roccella": ["roccella tinctoria"],
    "roccellaceae": ["family roccellaceae"],
    "roccus": ["genus roccus"],
    "rochambeau": ["comte de rochambeau", "jean baptiste donatien de vimeur"],
    "rochelle salt": ["potassium sodium tartrate", "rochelle salts"],
    "rochon prism": ["wollaston prism"],
    "rock": ["sway"],
    "rock 'n' roll": ["rock", "rock and roll", "rock music", "rock'n'roll", "rock-and-roll"],
    "rock bass": ["ambloplites rupestris", "rock sunfish"],
    "rock beauty": ["holocanthus tricolor"],
    "rock bit": ["roller bit"],
    "rock candy": ["rock"],
    "rock climber": ["cragsman"],
    "rock crab": ["cancer irroratus"],
    "rock cress": ["rockcress"],
    "rock crystal": ["transparent quartz"],
    "rock dove": ["columba livia", "rock pigeon"],
    "rock elm": ["ulmus thomasii"],
    "rock garden": ["rockery"],
    "rock geranium": ["heuchera americana"],
    "rock group": ["rock band"],
    "rock gunnel": ["butterfish", "pholis gunnellus"],
    "rock hind": ["epinephelus adscensionis"],
    "rock hopper": ["crested penguin"],
    "rock hyrax": ["procavia capensis", "rock rabbit"],
    "rock penstemon": ["cliff penstemon", "penstemon rupicola"],
    "rock pink": ["talinum calycinum"],
    "rock polypody": ["american wall fern", "polypodium virgianum", "rock brake"],
    "rock python": ["python sebae", "rock snake"],
    "rock rattlesnake": ["crotalus lepidus"],
    "rock sandwort": ["arenaria stricta"],
    "rock sea bass": ["centropristis philadelphica", "rock bass"],
    "rock spikemoss": ["dwarf lycopod", "selaginella rupestris"],
    "rock squirrel": ["citellus variegatus"],
    "rock wallaby": ["rock kangaroo"],
    "rock wren": ["xenicus gilviventris"],
    "rock-ribbed": ["rockbound"],
    "rockefeller": ["john d. rockefeller", "john davison rockefeller"],
    "rocker": ["rock 'n' roll musician"],
    "rocker arm": ["valve rocker"],
    "rockers": ["bikers"],
    "rocket": ["skyrocket"],
    "rocket engineer": ["rocket scientist"],
    "rocket firing": ["rocket launching"],
    "rocket fuel": ["rocket propellant", "rocket propellent"],
    "rocket larkspur": ["consolida ambigua", "delphinium ajacis"],
    "rockies": ["rocky mountains"],
    "rocking chair": ["rocker"],
    "rockingham": ["charles watson-wentworth", "second marquis of rockingham"],
    "rockrose": ["rock rose"],
    "rockwell": ["norman rockwell"],
    "rocky": ["bouldered", "bouldery", "stony"],
    "rocky mountain bee plant": ["cleome serrulata", "stinking clover"],
    "rocky mountain dogbane": ["apocynum pumilum"],
    "rocky mountain jay": ["perisoreus canadensis capitalis"],
    "rocky mountain pinon": ["pinus edulis"],
    "rocky mountain spotted fever": ["mountain fever", "tick fever"],
    "rocky mountain whitefish": ["prosopium williamsonii"],
    "rocroi": ["battle of rocroi"],
    "rod": ["retinal rod", "rod cell"],
    "rod-shaped": ["rodlike"],
    "rodent": ["gnawer"],
    "rodentia": ["order rodentia"],
    "rodgers": ["richard rodgers"],
    "rodin": ["auguste rodin", "francois auguste rene rodin"],
    "rodolia": ["genus rodolia", "genus vedalia"],
    "roe": ["hard roe"],
    "roe deer": ["capreolus capreolus"],
    "roebling": ["john augustus roebling", "john roebling"],
    "roentgen": ["rontgen", "wilhelm konrad roentgen", "wilhelm konrad rontgen"],
    "roentgenium": ["atomic number 111", "element 111", "rg"],
    "roentgenogram": ["x ray", "x-ray", "x-ray photograph", "x-ray picture"],
    "roentgenography": ["x-ray photography"],
    "rofecoxib": ["vioxx"],
    "rogers": ["will rogers", "william penn adair rogers"],
    "roget": ["peter mark roget"],
    "rogue": ["knave", "rapscallion", "rascal", "scalawag", "scallywag", "varlet"],
    "rogue state": ["renegade state", "rogue nation"],
    "roil": ["rile"],
    "roll": ["undulate"],
    "roll of tobacco": ["smoke"],
    "roll out": ["straighten"],
    "roll up": ["accumulate", "amass", "collect", "compile", "hoard", "pile up"],
    "rollback": ["push back"],
    "rolled": ["rolling", "trilled"],
    "roller": ["roll", "rolling wave"],
    "roller coaster": ["big dipper", "chute-the-chute"],
    "rollickingly": ["boisterously"],
    "rollo": ["hrolf", "rolf"],
    "roly-poly": ["roly-poly pudding"],
    "romaic": ["demotic"],
    "roman": ["roman letters", "roman print", "roman type"],
    "roman alphabet": ["latin alphabet"],
    "roman arch": ["semicircular arch"],
    "roman catholic": ["church of rome", "roman catholic church", "roman church", "western church"],
    "roman emperor": ["emperor of rome"],
    "roman hyacinth": ["hyacinthus orientalis albulus"],
    "roman inquisition": ["congregation of the inquisition"],
    "roman law": ["civil law", "jus civile", "justinian code"],
    "roman nettle": ["urtica pipulifera"],
    "roman nose": ["hooknose"],
    "roman wormwood": ["artemis pontica"],
    "romance": ["latinian language", "romance language"],
    "romanesque": ["romanesque architecture"],
    "romania": ["roumania", "rumania"],
    "romanian": ["rumanian"],
    "romanism": ["papism", "roman catholicism"],
    "romanize": ["latinise", "latinize", "romanise"],
    "romanov": ["romanoff"],
    "romansh": ["rumansh"],
    "romantic": ["romanticist", "romanticistic"],
    "romanticism": ["romantic movement"],
    "romanticist": ["romantic"],
    "romanticize": ["glamorize", "glamourise", "romanticise"],
    "romany": ["gypsy"],
    "romberg": ["sigmund romberg"],
    "rome": ["capital of italy", "eternal city", "italian capital", "roma"],
    "rommel": ["desert fox", "erwin rommel"],
    "romneya": ["genus romneya"],
    "romper": ["romper suit"],
    "ron": ["bokkos", "daffo"],
    "rondeau": ["rondel"],
    "rondo": ["rondeau"],
    "roofing paper": ["tar paper"],
    "rooibos": ["aspalathus cedcarbergensis", "aspalathus linearis"],
    "rook": ["corvus frugilegus"],
    "room": ["elbow room", "way"],
    "roomily": ["spaciously"],
    "roommate": ["roomie", "roomy"],
    "roomy": ["spacious"],
    "roosevelt": ["anna eleanor roosevelt", "eleanor roosevelt"],
    "root": ["base", "radical", "root word", "stem", "theme"],
    "root cellar": ["cellar"],
    "rootage": ["root system"],
    "rootless": ["vagabond"],
    "rope": ["leash"],
    "rope in": ["cordon off", "rope off"],
    "ropemaker": ["rope-maker", "roper"],
    "ropewalk": ["rope yard"],
    "ropewalker": ["ropedancer"],
    "ropey": ["ropy"],
    "ropy": ["ropey"],
    "roridulaceae": ["family roridulaceae"],
    "rorippa": ["genus rorippa"],
    "rorqual": ["razorback"],
    "rorschach": ["inkblot test", "rorschach test"],
    "rosa": ["genus rosa"],
    "rosaceae": ["family rosaceae", "rose family"],
    "rosales": ["order rosales"],
    "rosary": ["prayer beads"],
    "rose": ["rosebush"],
    "rose apple": ["eugenia jambos", "jambosa", "rose-apple tree"],
    "rose bed": ["bed of roses"],
    "rose chafer": ["cetonia aurata", "rose beetle"],
    "rose chestnut": ["ironwood", "ironwood tree", "mesua ferrea"],
    "rose geranium": ["pelargonium graveolens", "sweet-scented geranium"],
    "rose globe lily": ["calochortus amoenus"],
    "rose gum": ["eucalypt grandis"],
    "rose mallow": ["common rose mallow", "hibiscus moscheutos", "swamp mallow", "swamp rose mallow"],
    "rose moss": ["portulaca grandiflora", "sun plant"],
    "rose of jericho": ["anastatica hierochuntica", "resurrection plant"],
    "rose of sharon": ["hibiscus syriacus"],
    "rose window": ["rosette"],
    "rose-colored": ["rosy"],
    "rose-colored starling": ["pastor roseus", "pastor sturnus", "rose-colored pastor"],
    "rose-lilac": ["rose-lavender"],
    "rose-purple": ["rosy-purple"],
    "rose-root": ["midsummer-men", "sedum rosea"],
    "rose-tinted": ["rose-tinged"],
    "roseate spoonbill": ["ajaia ajaja"],
    "rosebay": ["rhododendron maxima"],
    "rosebud cherry": ["prunus subhirtella", "winter flowering cherry"],
    "rosebud orchid": ["cleistes rosea", "pogonia rosea"],
    "rosefish": ["ocean perch", "sebastodes marinus"],
    "roselle": ["hibiscus sabdariffa", "jamaica sorrel", "red sorrel", "rozelle", "sorrel"],
    "rosellinia": ["genus rosellinia"],
    "rosemary": ["rosmarinus officinalis"],
    "rosewood": ["rosewood tree"],
    "rosh hashanah": ["jewish new year", "rosh hashana", "rosh hashona", "rosh hashonah"],
    "rosh hodesh": ["rosh chodesh"],
    "rosidae": ["subclass rosidae"],
    "rosilla": ["helenium puberulum"],
    "rosinweed": ["silphium laciniatum"],
    "rosita": ["centaurium calycosum"],
    "rosmarinus": ["genus rosmarinus"],
    "ross": ["john ross", "sir john ross"],
    "rossbach": ["battle of rossbach"],
    "rossetti": ["dante gabriel rossetti"],
    "rossini": ["giloacchino antonio rossini"],
    "rostand": ["edmond rostand"],
    "rostov": ["rostov na donu", "rostov on don"],
    "rosy boa": ["lichanura trivirgata"],
    "rotary actuator": ["positioner"],
    "rotary club": ["rotary international"],
    "rotate": ["circumvolve"],
    "rotated": ["revolved"],
    "rotating shaft": ["shaft"],
    "rotation": ["gyration", "revolution"],
    "rotational latency": ["latency"],
    "rotatory": ["revolutionary"],
    "rote": ["rote learning"],
    "roth": ["philip milton roth", "philip roth"],
    "rothko": ["mark rothko"],
    "rotifera": ["phylum rotifera"],
    "rotor": ["rotor coil"],
    "rotor blade": ["rotary wing"],
    "rotor head": ["rotor shaft"],
    "rottenstone": ["tripoli"],
    "rotter": ["bum", "crumb", "dirty dog", "git", "lowlife", "puke", "rat", "scum bag", "skunk", "so-and-so", "stinker", "stinkpot"],
    "rouge": ["blusher", "paint"],
    "rouge et noir": ["trente-et-quarante"],
    "rough": ["bumpy", "jolting", "jolty", "jumpy", "rocky"],
    "rough bindweed": ["smilax aspera"],
    "rough green snake": ["opheodrys aestivus"],
    "rough in": ["rough", "rough out"],
    "rough-and-tumble": ["bare-knuckle", "bare-knuckled"],
    "rough-hew": ["roughcast"],
    "rough-legged hawk": ["buteo lagopus", "roughleg"],
    "rough-skinned newt": ["taricha granulosa"],
    "roughage": ["fiber"],
    "roughhewn": ["rough-cut"],
    "roughly": ["rough"],
    "roughness": ["raggedness"],
    "roughtail stingray": ["dasyatis centroura"],
    "roulette": ["line roulette"],
    "roulette wheel": ["wheel"],
    "round": ["labialise", "labialize"],
    "round dance": ["ring dance"],
    "round ligament of the uterus": ["ligamentum teres uteri"],
    "round of golf": ["round"],
    "round off": ["round", "round down", "round out"],
    "round out": ["finish out"],
    "round scad": ["cigarfish", "decapterus punctatus", "quiaquia"],
    "round table": ["round-table conference", "roundtable"],
    "round whitefish": ["menominee whitefish", "prosopium cylindraceum"],
    "round-bottomed": ["round-bottom"],
    "round-headed leek": ["allium sphaerocephalum"],
    "round-leaved rein orchid": ["habenaria orbiculata"],
    "round-tailed muskrat": ["florida water rat", "neofiber alleni"],
    "round-trip light time": ["rtlt"],
    "round-trip ticket": ["return ticket"],
    "roundedness": ["bulginess"],
    "rounding": ["rounding error"],
    "roundness": ["rotundity"],
    "rous": ["francis peyton rous", "peyton rous"],
    "rousing": ["stirring"],
    "rousseau": ["henri rousseau", "le douanier rousseau"],
    "rout": ["root", "rootle"],
    "rout out": ["drive out", "force out", "rouse"],
    "rout up": ["rout out"],
    "routine": ["function", "procedure", "subprogram", "subroutine"],
    "rover": ["scouter"],
    "row house": ["town house"],
    "rowan": ["european mountain ash", "rowan tree", "sorbus aucuparia"],
    "rowdily": ["raucously"],
    "rowdiness": ["disorderliness", "roughness", "rowdyism"],
    "rowing": ["row"],
    "royal": ["royal stag"],
    "royal academy": ["royal academy of arts"],
    "royal agaric": ["amanita caesarea", "caesar's agaric"],
    "royal air force": ["raf"],
    "royal canadian mounted police": ["mounties", "rcmp"],
    "royal fern": ["ditch fern", "french bracken", "king fern", "osmunda regalis", "royal osmund"],
    "royal palm": ["roystonea regia"],
    "royal poinciana": ["delonix regia", "flamboyant", "flame tree", "peacock flower", "poinciana regia"],
    "royal society": ["royal society of london for improving natural knowledge"],
    "royal tennis": ["court tennis", "real tennis"],
    "royally": ["like kings", "like royalty"],
    "royalty": ["royal family", "royal house", "royal line"],
    "roystonea": ["genus roystonea"],
    "rub": ["itch", "scratch"],
    "rub al-khali": ["ar rimsal", "dahna", "great sandy desert"],
    "rub-a-dub": ["drumbeat", "rataplan"],
    "rubber": ["synthetic rubber"],
    "rubber band": ["elastic", "elastic band"],
    "rubber boa": ["charina bottae", "tow-headed snake"],
    "rubber boot": ["gum boot"],
    "rubber eraser": ["pencil eraser", "rubber"],
    "rubberize": ["rubber", "rubberise"],
    "rubberneck": ["rubbernecker"],
    "rubberstamp": ["handstamp"],
    "rubbery": ["rubberlike"],
    "rubbish": ["scrap", "trash"],
    "rubbishy": ["trashy"],
    "rubens": ["peter paul rubens", "sir peter paul rubens"],
    "rubia": ["genus rubia"],
    "rubiaceae": ["family rubiaceae", "madder family"],
    "rubiales": ["order rubiales"],
    "rubicon": ["point of no return"],
    "rubicund": ["florid", "ruddy", "sanguine"],
    "rubidium": ["atomic number 37", "rb"],
    "rubinstein": ["arthur rubinstein", "artur rubinstein"],
    "ruble": ["rouble"],
    "rubus": ["genus rubus"],
    "ruby wood": ["red sandalwood"],
    "ruby-crowned kinglet": ["regulus calendula", "ruby-crowned wren"],
    "ruck": ["herd"],
    "rudapithecus": ["dryopithecus rudapithecus hungaricus"],
    "rudbeckia": ["genus rudbeckia"],
    "rudd": ["scardinius erythrophthalmus"],
    "rudderfish": ["banded rudderfish", "seriola zonata"],
    "rudderpost": ["rudderstock"],
    "ruddiness": ["rosiness"],
    "ruddle": ["raddle", "reddle"],
    "ruddy duck": ["oxyura jamaicensis"],
    "ruddy turnstone": ["arenaria interpres"],
    "rudiment": ["abc", "abc's", "abcs", "alphabet", "first principle", "first rudiment"],
    "rue": ["herb of grace", "ruta graveolens"],
    "rue anemone": ["anemonella thalictroides"],
    "ruefully": ["contritely", "remorsefully"],
    "ruff": ["philomachus pugnax"],
    "ruffed grouse": ["bonasa umbellus", "partridge"],
    "ruffianly": ["tough"],
    "ruffle": ["fluff"],
    "rug": ["carpet", "carpeting"],
    "rugby": ["rugby football", "rugger"],
    "rugel's plantain": ["broad-leaved plantain", "plantago rugelii"],
    "rugged": ["tough"],
    "ruggedization": ["ruggedisation"],
    "ruggedize": ["ruggedise"],
    "rugulah": ["rugelach", "ruggelach"],
    "ruhr": ["ruhr river"],
    "ruin": ["ruination"],
    "rule": ["find"],
    "rule out": ["rule in"],
    "ruler": ["swayer"],
    "ruling class": ["people in power"],
    "rumba": ["rhumba"],
    "rumble": ["grumble"],
    "rumen": ["first stomach"],
    "rumex": ["genus rumex"],
    "ruminantia": ["suborder ruminantia"],
    "rummage sale": ["jumble sale"],
    "rummy": ["rum"],
    "rumohra": ["genus rumohra"],
    "rumor": ["bruit", "rumour"],
    "rumple": ["crease", "crinkle", "crumple", "wrinkle"],
    "rumpus room": ["game room", "playroom"],
    "run": ["go"],
    "run batted in": ["rbi"],
    "run down": ["check out"],
    "run dry": ["dry out"],
    "run into": ["encounter"],
    "run low": ["go", "run short"],
    "run off": ["beetle off", "bolt", "bolt out", "run out"],
    "run on": ["keep going"],
    "run out": ["expire"],
    "run-of-the-mill": ["mine run", "run-of-the-mine", "unexceptional"],
    "runaway": ["blowout", "laugher", "romp", "shoo-in", "walkaway"],
    "rundle": ["rung", "spoke"],
    "rundstedt": ["karl rudolf gerd von rundstedt", "von rundstedt"],
    "rune": ["runic letter"],
    "rung": ["round", "stave"],
    "runner": ["blue runner", "caranx crysos"],
    "runner-up": ["second best"],
    "running": ["functional", "operative", "working"],
    "running head": ["running headline"],
    "running pine": ["lycopodium clavitum"],
    "runproof": ["ladder-proof", "run-resistant"],
    "runt": ["half-pint", "peewee", "shrimp"],
    "runup": ["run-up"],
    "runyon": ["alfred damon runyon", "damon runyon"],
    "rupert": ["prince rupert"],
    "rupestral": ["rupicolous"],
    "rupestral plant": ["rupestrine plant", "rupicolous plant", "saxicolous plant"],
    "rupicapra": ["genus rupicapra"],
    "rupicola": ["genus rupicola"],
    "ruptiliocarpon": ["genus ruptiliocarpon"],
    "rupture": ["breach", "break", "falling out", "rift", "severance"],
    "rupturewort": ["hernaria glabra"],
    "rural free delivery": ["rfd"],
    "ruralism": ["rusticism"],
    "rurality": ["ruralism"],
    "ruscaceae": ["family ruscaceae"],
    "ruscus": ["genus ruscus"],
    "ruse": ["artifice"],
    "rush": ["belt along", "bucket along", "cannonball along", "hasten", "hie", "hotfoot", "pelt along", "race", "rush along", "speed", "step on it"],
    "rush grass": ["rush-grass"],
    "rush off": ["rush away"],
    "rush rose": ["helianthemum scoparium"],
    "rushdie": ["ahmed salman rushdie", "salman rushdie"],
    "rushlight": ["rush candle"],
    "rushlike": ["sedgelike"],
    "rushmore": ["mount rushmore", "mt. rushmore"],
    "ruskin": ["john ruskin"],
    "russell": ["charles taze russell"],
    "russell's body": ["cancer body"],
    "russia": ["russian federation"],
    "russian almond": ["dwarf russian almond", "prunus tenella"],
    "russian bank": ["crapette"],
    "russian dandelion": ["kok-saghyz", "kok-sagyz", "taraxacum kok-saghyz"],
    "russian dressing": ["russian mayonnaise"],
    "russian olive": ["elaeagnus augustifolia", "silver berry"],
    "russian revolution": ["october revolution"],
    "russian thistle": ["russian cactus", "russian tumbleweed", "salsola kali tenuifolia", "tumbleweed"],
    "russula": ["genus russula"],
    "russulaceae": ["family russulaceae"],
    "rust": ["rusting"],
    "rust-red": ["rusty-red"],
    "rusticity": ["gaucherie"],
    "rustle": ["lift"],
    "rustler": ["cattle thief"],
    "rustproof": ["rustproofed"],
    "rusty blackbird": ["euphagus carilonus", "rusty grackle"],
    "rusty woodsia": ["fragrant woodsia", "oblong woodsia", "woodsia ilvensis"],
    "rut": ["groove"],
    "ruta": ["genus ruta"],
    "rutabaga": ["brassica napus napobrassica", "rutabaga plant", "swede", "swedish turnip", "turnip cabbage"],
    "rutaceae": ["family rutaceae", "rue family"],
    "ruth": ["babe ruth", "george herman ruth", "sultan of swat"],
    "ruthenium": ["atomic number 44", "ru"],
    "rutherford": ["daniel rutherford"],
    "rutherfordium": ["atomic number 104", "element 104", "rf", "unnilquadium", "unq"],
    "rutilus": ["genus rutilus"],
    "rutledge": ["john rutledge"],
    "rutted": ["rutty"],
    "rwanda": ["ruanda", "rwandese republic"],
    "rwandan": ["ruandan"],
    "rya": ["rya rug"],
    "rydberg": ["rydberg constant", "rydberg unit"],
    "rydberg's penstemon": ["penstemon rydbergii"],
    "rye": ["secale cereale"],
    "rye grass": ["ryegrass"],
    "rynchopidae": ["family rynchopidae"],
    "rynchops": ["genus rynchops"],
    "rypticus": ["genus rypticus"],
    "sa": ["storm troops", "sturmabteilung"],
    "saale": ["saale river"],
    "saarinen": ["eliel saarinen"],
    "sabah": ["north borneo"],
    "sabal": ["genus sabal"],
    "sabbat": ["witches' sabbath"],
    "sabbatical": ["sabbatical leave"],
    "saber": ["sabre"],
    "saber rattling": ["sabre rattling"],
    "saber saw": ["jigsaw", "reciprocating saw"],
    "saber-toothed": ["sabertoothed", "sabre-toothed"],
    "saber-toothed tiger": ["sabertooth"],
    "sabicu": ["sabicu wood"],
    "sabin": ["albert bruce sabin", "albert sabin"],
    "sabin vaccine": ["opv", "oral poliovirus vaccine", "topv", "trivalent live oral poliomyelitis vaccine"],
    "sabine": ["sabine river"],
    "sabinea": ["genus sabinea"],
    "sable": ["sable brush", "sable's hair pencil"],
    "sable antelope": ["hippotragus niger"],
    "sabot": ["wooden shoe"],
    "sabotage": ["counteract", "countermine", "subvert", "undermine", "weaken"],
    "saboteur": ["diversionist", "wrecker"],
    "sabre": ["saber"],
    "sacagawea": ["sacajawea"],
    "saccharomyces": ["genus saccharomyces"],
    "saccharomycetaceae": ["family saccharomycetaceae"],
    "saccharum": ["genus saccharum"],
    "sacco": ["nicola sacco"],
    "sacculated": ["sacculate"],
    "saccule": ["sacculus"],
    "sachem": ["sagamore"],
    "sack": ["plunder"],
    "sacking": ["bagging"],
    "sacral plexus": ["plexus sacralis"],
    "sacral vein": ["vena sacralis"],
    "sacramento": ["capital of california"],
    "sacred college": ["college of cardinals"],
    "sacred ibis": ["threskiornis aethiopica"],
    "sacred text": ["religious text", "religious writing", "sacred writing"],
    "sacrifice": ["give"],
    "sadat": ["anwar el-sadat", "anwar sadat"],
    "saddle blanket": ["horse blanket", "saddlecloth"],
    "saddle block anesthesia": ["saddle block anaesthesia"],
    "saddle hackle": ["saddle feather"],
    "saddle horse": ["mount", "riding horse"],
    "saddle oxford": ["saddle shoe"],
    "saddle oyster": ["anomia ephippium"],
    "saddle soap": ["leather soap"],
    "saddle sore": ["gall"],
    "saddleback": ["saddle"],
    "saddlebill": ["ephippiorhynchus senegalensis", "jabiru"],
    "sade": ["comte donatien alphonse francois de sade", "de sade", "marquis de sade"],
    "sadhu": ["saddhu"],
    "sadleria": ["genus sadleria"],
    "sadly": ["unhappily"],
    "sadness": ["sorrow", "sorrowfulness"],
    "safar": ["saphar"],
    "safe and sound": ["unhurt"],
    "safe-conduct": ["safeguard"],
    "safe-deposit": ["deposit box", "lockbox", "safe-deposit box", "safety deposit box", "safety-deposit"],
    "safebreaker": ["cracksman", "safecracker"],
    "safety": ["refuge"],
    "safety belt": ["life belt", "safety harness"],
    "safety bicycle": ["safety bike"],
    "safety blitz": ["blitz", "linebacker blitzing"],
    "safety bolt": ["safety lock"],
    "safety catch": ["safety lock"],
    "safety factor": ["factor of safety"],
    "safety glass": ["laminated glass", "shatterproof glass"],
    "safety lamp": ["davy lamp"],
    "safety match": ["book matches"],
    "safety rail": ["guardrail"],
    "safety squeeze play": ["safety squeeze"],
    "safety valve": ["escape", "escape cock", "escape valve", "relief valve"],
    "safflower": ["carthamus tinctorius", "false saffron"],
    "saffron": ["crocus sativus", "saffron crocus"],
    "safranine": ["saffranine", "safranin"],
    "sag": ["sag down"],
    "sagacity": ["discernment", "judgement", "judgment", "sagaciousness"],
    "sage": ["salvia"],
    "sage grouse": ["centrocercus urophasianus", "sage hen"],
    "sagebrush": ["sage brush"],
    "sagebrush buttercup": ["ranunculus glaberrimus"],
    "sagebrush lizard": ["sceloporus graciosus"],
    "sagebrush mariposa tulip": ["calochortus macrocarpus"],
    "sagina": ["genus sagina"],
    "sagittal suture": ["interparietal suture", "sutura sagittalis"],
    "sagittaria": ["genus sagittaria"],
    "sagittariidae": ["family sagittariidae"],
    "sagittarius": ["archer"],
    "sagittate": ["arrow-shaped", "sagittiform"],
    "sagittate-leaf": ["sagittiform leaf"],
    "sago palm": ["cycas revoluta"],
    "saguaro": ["carnegiea gigantea", "sahuaro"],
    "sahara": ["sahara desert"],
    "saiga": ["saiga tatarica"],
    "saigon cinnamon": ["cinnamomum loureirii"],
    "sail": ["canvas", "canvass", "sheet"],
    "sailboat": ["sailing boat"],
    "sailing master": ["navigator"],
    "sailing vessel": ["sailing ship"],
    "sailing-race": ["yacht race"],
    "sailor": ["crewman"],
    "sailor's-choice": ["haemulon parra", "sailors choice"],
    "sailplane": ["soar"],
    "saimiri": ["genus saimiri"],
    "sainfoin": ["esparcet", "holy clover", "onobrychis viciaefolia", "onobrychis viciifolia", "sanfoin"],
    "saint": ["angel", "holy man", "holy person"],
    "saint agnes's eve": ["january 20"],
    "saint bernard": ["st bernard"],
    "saint christopher": ["saint kitts", "st. christopher", "st. kitts"],
    "saint cloud": ["st. cloud"],
    "saint eustatius": ["st. eustatius"],
    "saint francis": ["saint francis river", "st. francis", "st. francis river"],
    "saint john": ["saint john river", "st. john", "st. john river"],
    "saint john's": ["st. john's"],
    "saint johns": ["saint johns river", "st. johns", "st. johns river"],
    "saint joseph": ["march 19", "st joseph"],
    "saint kitts and nevis": ["federation of saint kitts and nevis", "saint christopher-nevis", "st. christopher-nevis", "st. kitts and nevis"],
    "saint lawrence": ["saint lawrence river", "st. lawrence", "st. lawrence river"],
    "saint lawrence seaway": ["st. lawrence seaway"],
    "saint louis": ["gateway to the west", "st. louis"],
    "saint lucia": ["st. lucia"],
    "saint martin": ["saint maarten", "st. maarten", "st. martin"],
    "saint paul": ["capital of minnesota", "st. paul"],
    "saint vincent": ["st. vincent"],
    "saint vincent and the grenadines": ["st. vincent and the grenadines"],
    "saint-bernard's-lily": ["anthericum liliago"],
    "saint-mihiel": ["battle of st mihiel", "st mihiel"],
    "saint-saens": ["charles camille saint-saens"],
    "saintpaulia": ["genus saintpaulia"],
    "saints peter and paul": ["june 29"],
    "sake": ["rice beer", "saki"],
    "sakharov": ["andrei dimitrievich sakharov", "andrei sakharov"],
    "salability": ["salableness"],
    "salable": ["saleable"],
    "salad burnet": ["burnet bloodwort", "pimpernel", "poterium sanguisorba"],
    "salad green": ["salad greens"],
    "salad plate": ["salad bowl"],
    "saladin": ["salah-ad-din yusuf ibn-ayyub"],
    "salafism": ["salafi movement"],
    "salafist group": ["gspc", "salafast group for call and combat"],
    "salai": ["boswellia serrata"],
    "salal": ["gaultheria shallon", "shallon"],
    "salamandra": ["genus salamandra"],
    "salamandridae": ["family salamandridae"],
    "salat": ["salaah", "salaat", "salah"],
    "sale": ["sales agreement"],
    "sale in gross": ["contract of hazard"],
    "salem": ["capital of oregon"],
    "sales department": ["sales division", "sales force"],
    "sales talk": ["pitch", "sales pitch"],
    "sales tax": ["nuisance tax"],
    "salesclerk": ["clerk", "shop assistant", "shop clerk"],
    "salesgirl": ["saleslady", "saleswoman"],
    "salesperson": ["sales rep", "sales representative"],
    "salian frank": ["salian"],
    "salicaceae": ["family salicaceae", "willow family"],
    "salicales": ["order salicales"],
    "salicornia": ["genus salicornia"],
    "salicylic acid": ["2-hydroxybenzoic acid"],
    "salience": ["saliency", "strikingness"]
}
