synonyms = {
    "salientia": ["anura", "batrachia", "order anura", "order batrachia", "order salientia"],
    "saline solution": ["saline"],
    "salinger": ["j. d. salinger", "jerome david salinger"],
    "salish": ["salishan"],
    "saliva": ["spit", "spittle"],
    "salivate": ["drool"],
    "salix": ["genus salix"],
    "salk": ["jonas edward salk", "jonas salk"],
    "salk vaccine": ["ipv"],
    "sallet": ["salade"],
    "sallow": ["sickly"],
    "sally": ["sallying forth"],
    "sally forth": ["sally out"],
    "salmo": ["genus salmo"],
    "salmon": ["salmon river"],
    "salmonberry": ["rubus parviflorus", "salmon berry", "thimbleberry"],
    "salmonella enteritidis": ["gartner's bacillus"],
    "salmonidae": ["family salmonidae"],
    "salol": ["phenyl salicylate"],
    "salomon": ["haym salomon"],
    "salon": ["beauty parlor", "beauty parlour", "beauty salon", "beauty shop"],
    "salp": ["salpa"],
    "salpichroa": ["genus salpichroa"],
    "salpidae": ["family salpidae"],
    "salpinctes": ["genus salpinctes"],
    "salsify": ["oyster plant"],
    "salsilla": ["bomarea salsilla"],
    "salsola": ["genus salsola"],
    "salt": ["common salt", "table salt"],
    "salt flat": ["salt plain"],
    "salt lake city": ["capital of utah"],
    "salt lick": ["lick"],
    "salt marsh mallow": ["kosteletzya virginica"],
    "salt reed grass": ["spartina cynosuroides"],
    "salt rush": ["juncus leseurii"],
    "salt tree": ["halimodendron argenteum", "halimodendron halodendron"],
    "salted": ["brine-cured", "salt-cured"],
    "salter": ["salt merchant"],
    "saltiness": ["coarseness"],
    "saltshaker": ["salt shaker"],
    "saltwort": ["barilla", "glasswort", "kali", "kelpwort", "salsola kali", "salsola soda"],
    "salubrity": ["salubriousness"],
    "saluki": ["gazelle hound"],
    "salutatorian": ["salutatory speaker"],
    "salutatory address": ["salutatory", "salutatory oration"],
    "salute": ["present"],
    "salvadora": ["genus salvadora"],
    "salvadoraceae": ["family salvadoraceae", "salvadora family"],
    "salvadoran": ["salvadorean", "salvadorian"],
    "salvage": ["relieve", "salve", "save"],
    "salvager": ["salvor"],
    "salvelinus": ["genus salvelinus"],
    "salvinia": ["genus salvinia"],
    "salviniaceae": ["family salviniaceae"],
    "salwar": ["shalwar"],
    "samara": ["key", "key fruit"],
    "samarium": ["atomic number 62", "sm"],
    "samarkand": ["samarcand"],
    "sambar": ["cervus unicolor", "sambur"],
    "sambre": ["sambre river"],
    "sambucus": ["genus sambucus"],
    "samia": ["genus samia"],
    "samisen": ["shamisen"],
    "samizdat": ["underground press"],
    "samoa": ["independent state of samoa", "samoa i sisifo", "western samoa"],
    "samolus": ["genus samolus"],
    "samoyed": ["samoyede"],
    "samoyedic": ["samoyed"],
    "sample": ["taste", "try", "try out"],
    "sample distribution": ["sample", "sampling"],
    "sampling station": ["sampler"],
    "san jose": ["capital of costa rica"],
    "san jose scale": ["aspidiotus perniciosus"],
    "san marino": ["capital of san marino"],
    "san salvador": ["salvadoran capital"],
    "sana": ["sana'a", "sanaa"],
    "sanatorium": ["sanatarium", "sanitarium"],
    "sanchez": ["andres martinez", "carlos", "carlos the jackal", "glen gebhard", "hector hevodidbon", "ilich ramirez sanchez", "ilich sanchez", "michael assat", "salim", "taurus"],
    "sanctimoniously": ["self-righteously"],
    "sanctimoniousness": ["sanctimony"],
    "sanction": ["countenance", "endorsement", "imprimatur", "indorsement", "warrant"],
    "sanctionative": ["sanctioning"],
    "sanctum": ["sanctum sanctorum"],
    "sand": ["amandine aurore lucie dupin", "baroness dudevant", "george sand"],
    "sand blackberry": ["rubus cuneifolius"],
    "sand cherry": ["prunus cuneata", "prunus pumila", "prunus pumilla susquehanae", "prunus susquehanae"],
    "sand cricket": ["jerusalem cricket", "stenopelmatus fuscus"],
    "sand devil's claw": ["martynia arenaria", "proboscidea arenaria"],
    "sand dropseed": ["sporobolus cryptandrus"],
    "sand fly": ["phlebotomus papatasii", "sandfly"],
    "sand lance": ["launce", "sand eel", "sand launce"],
    "sand leek": ["allium scorodoprasum", "giant garlic", "rocambole", "spanish garlic"],
    "sand lizard": ["lacerta agilis"],
    "sand myrtle": ["leiophyllum buxifolium"],
    "sand rat": ["meriones longifrons"],
    "sand sage": ["artemisia filifolia", "silvery wormwood"],
    "sand sedge": ["carex arenaria", "sand reed"],
    "sand sole": ["psettichthys melanostichus"],
    "sand spurry": ["sea spurry", "spergularia rubra"],
    "sand tiger": ["carcharias taurus", "odontaspis taurus", "sand shark"],
    "sandaled": ["sandalled"],
    "sandalwood tree": ["santalum album", "true sandalwood"],
    "sandarac": ["citronwood"],
    "sandbag": ["stun"],
    "sandbar": ["sand bar"],
    "sandbar shark": ["carcharhinus plumbeus"],
    "sandbox": ["sandpile", "sandpit"],
    "sandbur": ["cenchrus tribuloides", "field sandbur", "sandspur"],
    "sandburg": ["carl sandburg"],
    "sanderling": ["crocethia alba"],
    "sandfly fever": ["pappataci fever", "phlebotomus"],
    "sandgrouse": ["sand grouse"],
    "sandpaper": ["sand"],
    "sandwort": ["moehringia mucosa"],
    "sandy mushroom": ["tricholoma populinum"],
    "sanely": ["reasonably", "sensibly"],
    "sangapenum": ["gum sangapenum"],
    "sangaree": ["sangria"],
    "sanger": ["fred sanger", "frederick sanger"],
    "sanguinaria": ["genus sanguinaria"],
    "sanguinary ant": ["formica sanguinea"],
    "sanguinity": ["sanguineness"],
    "sanicle": ["snakeroot"],
    "sanicula": ["genus sanicula"],
    "sanitary": ["healthful"],
    "sanitary code": ["health code"],
    "sanitary napkin": ["kotex", "sanitary towel"],
    "sanitation": ["sanitisation", "sanitization"],
    "sanitize": ["hygienise", "hygienize", "sanitise"],
    "sanitized": ["sanitised"],
    "sanity": ["saneness"],
    "sannyasi": ["sannyasin", "sanyasi"],
    "sans serif": ["helvetica"],
    "sansevieria": ["bowstring hemp"],
    "sanskrit": ["sanskritic language"],
    "santa anna": ["antonio lopez de santa ana", "antonio lopez de santa anna", "santa ana"],
    "santa catalina": ["catalina island"],
    "santa claus": ["father christmas", "kriss kringle", "saint nicholas", "saint nick", "santa", "st. nick"],
    "santa cruz cypress": ["cupressus abramsiana", "cupressus goveniana abramsiana"],
    "santa fe": ["capital of new mexico"],
    "santa lucia fir": ["abies bracteata", "abies venusta", "bristlecone fir"],
    "santalaceae": ["family santalaceae", "sandalwood family"],
    "santalales": ["order santalales"],
    "santalum": ["genus santalum"],
    "santee": ["eastern sioux", "santee dakota", "santee sioux"],
    "santiago": ["santiago de cuba"],
    "santiago de cuba": ["santiago"],
    "santiago de los caballeros": ["santiago"],
    "santo domingo": ["capital of the dominican republic", "ciudad trujillo"],
    "santolina": ["genus santolina"],
    "sanvitalia": ["genus sanvitalia"],
    "sao tome and principe": ["democratic republic of sao tome and principe", "sao thome e principe", "sao tome e principe", "st. thomas and principe"],
    "saone": ["saone river"],
    "saphenous nerve": ["nervus saphenus"],
    "saphenous vein": ["vena saphena"],
    "sapidity": ["sapidness"],
    "sapiential book": ["wisdom book", "wisdom literature"],
    "sapindaceae": ["family sapindaceae", "soapberry family"],
    "sapindales": ["order sapindales"],
    "sapindus": ["genus sapindus"],
    "sapir": ["edward sapir"],
    "sapodilla": ["achras zapota", "manilkara zapota", "sapodilla tree"],
    "saponaceous": ["soapy"],
    "saponaria": ["genus saponaria"],
    "sapotaceae": ["family sapotaceae", "sapodilla family"],
    "sapote": ["mammee", "marmalade plum"],
    "sapremia": ["sapraemia"],
    "saprolegnia": ["genus saprolegnia"],
    "saprolegniales": ["order saprolegniales"],
    "saprophagous": ["saprozoic"],
    "saprophyte": ["saprophytic organism"],
    "saqqara": ["sakkara", "saqqarah"],
    "saquinavir": ["invirase"],
    "saratoga": ["battle of saratoga"],
    "saratoga spittlebug": ["aphrophora saratogensis"],
    "sarazen": ["gene sarazen"],
    "sarcasm": ["caustic remark", "irony", "satire"],
    "sarcastically": ["sardonically"],
    "sarcenet": ["sarsenet"],
    "sarcobatus": ["genus sarcobatus"],
    "sarcocephalus": ["genus sarcocephalus"],
    "sarcochilus": ["genus sarcochilus"],
    "sarcocystis": ["genus sarcocystis"],
    "sarcodes": ["genus sarcodes"],
    "sarcodina": ["class sarcodina"],
    "sarcodinian": ["sarcodine"],
    "sarcolemmic": ["sarcolemnous"],
    "sarcophaga": ["genus sarcophaga"],
    "sarcophilus": ["genus sarcophilus"],
    "sarcoptes": ["genus sarcoptes"],
    "sarcoptidae": ["family sarcoptidae"],
    "sarcorhamphus": ["genus sarcorhamphus"],
    "sarcoscypha coccinea": ["scarlet cup"],
    "sarcoscyphaceae": ["family sarcoscyphaceae"],
    "sarcosporidia": ["order sarcosporidia"],
    "sarcosporidian": ["sarcocystidean", "sarcocystieian"],
    "sarcostemma": ["genus sarcostemma"],
    "sard": ["sardine", "sardius"],
    "sarda": ["genus sarda"],
    "sardina": ["genus sardina", "genus sardinia"],
    "sardine": ["pilchard"],
    "sardinia": ["sardegna"],
    "sardinops": ["genus sardinops"],
    "sargent": ["john singer sargent"],
    "sari": ["saree"],
    "sarin": ["gb"],
    "sarnoff": ["david sarnoff"],
    "saronic gulf": ["gulf of aegina"],
    "saroyan": ["william saroyan"],
    "sarpanitu": ["zarpanit", "zirbanit"],
    "sarracenia": ["genus sarracenia"],
    "sarraceniaceae": ["family sarraceniaceae", "pitcher-plant family"],
    "sarraceniales": ["order sarraceniales"],
    "sartorius": ["musculus sartorius", "sartorius muscle"],
    "sartre": ["jean-paul sartre"],
    "sash": ["window sash"],
    "sash cord": ["sash line"],
    "sash fastener": ["sash lock", "window lock"],
    "saskatoon": ["juneberry", "serviceberry", "shadberry"],
    "sass": ["back talk", "backtalk", "lip", "mouth", "sassing"],
    "sassaby": ["damaliscus lunatus", "topi"],
    "sassafras": ["sassafras albidum", "sassafras tree"],
    "satan": ["beelzebub", "devil", "lucifer", "old nick", "prince of darkness", "the tempter"],
    "satanist": ["diabolist"],
    "satellite": ["planet"],
    "satellite television": ["satellite tv"],
    "satiable": ["satisfiable"],
    "satiate": ["fill", "replete", "sate"],
    "satie": ["erik alfred leslie satie", "erik satie"],
    "satin bowerbird": ["ptilonorhynchus violaceus", "satin bird"],
    "satinet": ["satinette"],
    "satinleaf": ["caimitillo", "chrysophyllum oliviforme", "damson plum", "satin leaf"],
    "satinwood": ["west indian satinwood", "zanthoxylum flavum"],
    "satiny": ["silken", "silklike", "silky", "sleek", "slick"],
    "satirical": ["satiric"],
    "satirist": ["ironist", "ridiculer"],
    "satirize": ["lampoon", "satirise"],
    "satisfactory": ["acceptable"],
    "satisfice": ["satisfise"],
    "satisfy": ["fulfil", "fulfill", "live up to"],
    "satsuma": ["satsuma tree"],
    "saturated": ["concentrated"],
    "saturation": ["chroma", "intensity", "vividness"],
    "saturday": ["sabbatum", "sat"],
    "satureja": ["genus satureia", "genus satureja", "satureia"],
    "saturnia": ["genus saturnia"],
    "saturniid": ["saturniid moth"],
    "saturniidae": ["family saturniidae"],
    "satyr": ["lech", "lecher", "letch"],
    "satyr orchid": ["coeloglossum bracteatum"],
    "satyric": ["satyrical"],
    "satyridae": ["family satyridae"],
    "saucer magnolia": ["chinese magnolia", "magnolia soulangiana"],
    "saucer-eyed": ["round-eyed"],
    "saudi": ["saudi arabian"],
    "saudi arabia": ["kingdom of saudi arabia"],
    "saudi arabian riyal": ["riyal"],
    "saudi-arabian": ["saudi"],
    "sauk": ["sac"],
    "sauna": ["sweat room"],
    "saunterer": ["ambler", "stroller"],
    "sauria": ["lacertilia", "suborder lacertilia", "suborder sauria"],
    "saurian": ["lacertilian"],
    "saurischia": ["order saurischia"],
    "saurischian": ["saurischian dinosaur"],
    "sauromalus": ["genus sauromalus"],
    "sauropod": ["sauropod dinosaur"],
    "sauropoda": ["suborder sauropoda"],
    "sauropodomorpha": ["suborder sauropodomorpha"],
    "sauropterygia": ["order sauropterygia"],
    "saurosuchus": ["genus saurosuchus"],
    "saururaceae": ["family saururaceae", "lizard's-tail family"],
    "saururus": ["genus saururus"],
    "saury": ["billfish", "scomberesox saurus"],
    "sausage dog": ["sausage hound"],
    "saussurea": ["genus saussurea"],
    "saute": ["sauteed"],
    "sauterne": ["sauternes"],
    "savage": ["blast", "crucify", "pillory"],
    "savageness": ["savagery"],
    "savanna": ["savannah"],
    "savannah": ["savannah river"],
    "save": ["bring through", "carry through", "pull through"],
    "savings": ["nest egg"],
    "savings account trust": ["savings bank trust", "totten trust", "trust account", "trustee account"],
    "savings and loan": ["savings and loan association"],
    "savings bank": ["bank", "coin bank", "money box"],
    "savior": ["deliverer", "rescuer", "saviour"],
    "savoir-faire": ["address"],
    "savonarola": ["girolamo savonarola"],
    "savor": ["savour"],
    "savory": ["micromeria juliana"],
    "savoy cabbage": ["savoy"],
    "saw palmetto": ["scrub palmetto", "serenoa repens"],
    "sawan": ["sravana"],
    "sawed-off": ["sawn-off", "shortened"],
    "sawhorse": ["buck", "horse", "sawbuck"],
    "sawwort": ["serratula tinctoria"],
    "sawyer": ["sawyer beetle"],
    "sax": ["adolphe sax"],
    "saxe": ["comte de saxe", "hermann maurice saxe", "marshal saxe"],
    "saxe-gothea": ["genus saxe-gothea", "genus saxegothea", "saxegothea"],
    "saxicola": ["genus saxicola"],
    "saxicolous": ["saxatile", "saxicoline"],
    "saxifraga": ["genus saxifraga"],
    "saxifragaceae": ["family saxifragaceae", "saxifrage family"],
    "saxifrage": ["breakstone", "rockfoil"],
    "saxony": ["sachsen", "saxe"],
    "saxophonist": ["saxist"],
    "sayda": ["saida", "sidon"],
    "sayeret matkal": ["sayeret", "sayeret mat'kal"],
    "sayers": ["dorothy l. sayers", "dorothy leigh sayers", "dorothy sayers"],
    "saying": ["expression", "locution"],
    "sayornis": ["genus sayornis"],
    "scab": ["blackleg", "rat", "strikebreaker"],
    "scabies": ["itch"],
    "scabious": ["scabiosa"],
    "scaffolding": ["staging"],
    "scalar product": ["dot product", "inner product"],
    "scalawag": ["scallywag"],
    "scale": ["surmount"],
    "scale fern": ["asplenium ceterach", "ceterach officinarum", "scaly fern"],
    "scale wax": ["paraffin scale"],
    "scalenus": ["musculus scalenus", "scalene muscle"],
    "scaling": ["grading"],
    "scallop": ["escallop"],
    "scallopine": ["scallopini"],
    "scaly": ["scaled", "scaley"],
    "scaly lentinus": ["lentinus lepideus"],
    "scam": ["cozenage"],
    "scammony": ["ipomoea orizabensis"],
    "scamper": ["scramble", "scurry"],
    "scan": ["glance over", "rake", "run down", "skim"],
    "scandal": ["outrage"],
    "scandalization": ["scandalisation"],
    "scandalmongering": ["sensationalistic", "yellow"],
    "scandentia": ["order scandentia"],
    "scandinavia": ["scandinavian peninsula"],
    "scandinavian": ["norse", "northman"],
    "scandinavian country": ["scandinavian nation"],
    "scandium": ["atomic number 21", "sc"],
    "scanner": ["digital scanner", "image scanner"],
    "scant": ["skimp"],
    "scantily": ["barely"],
    "scantling": ["stud"],
    "scape": ["flower stalk"],
    "scapegoat": ["whipping boy"],
    "scapegrace": ["black sheep"],
    "scaphiopus": ["genus scaphiopus"],
    "scaphoid bone": ["navicular", "os scaphoideum"],
    "scaphopoda": ["class scaphopoda"],
    "scaphosepalum": ["genus scaphosepalum"],
    "scapula": ["shoulder blade", "shoulder bone"],
    "scapular": ["scapulary"],
    "scar": ["mark", "pit", "pock"],
    "scarab": ["scarabaeus", "scarabaeus sacer"],
    "scarabaeid beetle": ["scarabaean", "scarabaeid"],
    "scarabaeidae": ["family scarabaeidae"],
    "scaramouch": ["scaramouche"],
    "scarcity": ["scarceness"],
    "scardinius": ["genus scardinius"],
    "scare": ["panic attack"],
    "scarecrow": ["bird-scarer", "scarer", "straw man", "strawman"],
    "scaremonger": ["stirrer"],
    "scarf joint": ["scarf"],
    "scaridae": ["family scaridae"],
    "scarlet": ["orange red", "vermilion"],
    "scarlet bugler": ["penstemon centranthifolius"],
    "scarlet bush": ["coloradillo", "hamelia erecta", "hamelia patens", "scarlet hamelia"],
    "scarlet clematis": ["clematis texensis"],
    "scarlet fever": ["scarlatina"],
    "scarlet fritillary": ["fritillaria recurva"],
    "scarlet haw": ["crataegus biltmoreana"],
    "scarlet lychnis": ["lychins chalcedonica", "maltese cross"],
    "scarlet musk flower": ["nyctaginia capitata"],
    "scarlet oak": ["quercus coccinea"],
    "scarlet pimpernel": ["anagallis arvensis", "poor man's weatherglass", "red pimpernel"],
    "scarlet plume": ["euphorbia fulgens"],
    "scarlet runner": ["dutch case-knife bean", "phaseolus coccineus", "phaseolus multiflorus", "runner bean", "scarlet runner bean"],
    "scarlet tanager": ["firebird", "piranga olivacea", "redbird"],
    "scarlet wisteria tree": ["sesbania grandiflora", "vegetable hummingbird"],
    "scartella": ["genus scartella"],
    "scat": ["break away", "bunk", "escape", "fly the coop", "head for the hills", "hightail it", "lam", "run", "run away", "scarper", "take to the woods", "turn tail"],
    "scathing": ["vituperative"],
    "scathingly": ["unsparingly"],
    "scatter": ["disperse", "dot", "dust", "sprinkle"],
    "scatter rug": ["throw rug"],
    "scatterbrain": ["forgetful person"],
    "scattering": ["sprinkling"],
    "scaup": ["bluebill", "broadbill", "scaup duck"],
    "scauper": ["scorper"],
    "scavenge": ["clean"],
    "sceliphron": ["genus sceliphron"],
    "sceloglaux": ["genus sceloglaux"],
    "sceloporus": ["genus sceloporus"],
    "scend": ["surge"],
    "scene": ["shot"],
    "scenery": ["scene"],
    "sceneshifter": ["shifter"],
    "scenic artist": ["scene painter"],
    "scent": ["nose", "wind"],
    "scented fern": ["mohria caffrorum"],
    "scentless camomile": ["corn mayweed", "matricaria inodorum", "scentless false camomile", "scentless hayweed", "scentless mayweed", "tripleurospermum inodorum"],
    "scepter": ["sceptre"],
    "sceptically": ["skeptically"],
    "schaffneria": ["genus schaffneria"],
    "schaffneria nigripes": ["asplenium nigripes", "scolopendrium nigripes"],
    "scheduling": ["programing", "programming"],
    "scheele": ["karl scheele", "karl wilhelm scheele"],
    "schefflera": ["genus schefflera"],
    "scheldt": ["scheldt river"],
    "schema": ["scheme"],
    "schematic": ["schematic drawing"],
    "schematization": ["diagramming", "schematisation"],
    "schematize": ["schematise"],
    "scheme": ["connive", "intrigue"],
    "schemer": ["plotter"],
    "schemozzle": ["shemozzle"],
    "scheuchzeriaceae": ["arrow-grass family", "family juncaginaceae", "family scheuchzeriaceae", "juncaginaceae"],
    "schiaparelli": ["giovanni virginio schiaparelli"],
    "schiller": ["johann christoph friedrich von schiller"],
    "schilling": ["austrian schilling"],
    "schinus": ["genus schinus"],
    "schism": ["split"],
    "schismatic": ["schismatical"],
    "schistosoma": ["genus schistosoma"],
    "schistosomatidae": ["family schistosomatidae"],
    "schistosome": ["blood fluke"],
    "schistosome dermatitis": ["swimmer's itch"],
    "schistosomiasis": ["bilharzia", "bilharziasis"],
    "schizachyrium": ["genus schizachyrium"],
    "schizaea": ["genus schizaea"],
    "schizaeaceae": ["family schizaeaceae"],
    "schizoid": ["schizophrenic"],
    "schizomycetes": ["class schizomycetes"],
    "schizopetalon": ["schizopetalon walkeri"],
    "schizophragma": ["genus schizophragma"],
    "schizophrenia": ["dementia praecox", "schizophrenic disorder", "schizophrenic psychosis"],
    "schizophyta": ["division schizophyta"],
    "schizosaccharomyces": ["genus schizosaccharomyces"],
    "schizosaccharomycetaceae": ["family schizosaccharomycetaceae"],
    "schizotypal personality": ["schizoid"],
    "schleiden": ["m. j. schleiden", "matthias schleiden"],
    "schlemiel": ["shlemiel"],
    "schlep": ["shlep"],
    "schlepper": ["schlep", "shlep", "shlepper"],
    "schlesinger": ["arthur meier schlesinger jr.", "arthur schlesinger", "arthur schlesinger jr."],
    "schliemann": ["heinrich schliemann"],
    "schlimazel": ["shlimazel"],
    "schlock": ["dreck", "shlock"],
    "schlockmeister": ["shlockmeister"],
    "schlumbergera": ["genus schlumbergera"],
    "schmaltz": ["schmalz", "shmaltz"],
    "schmeer": ["schmear", "shmear"],
    "schmidt": ["helmut heinrich waldemar schmidt", "helmut schmidt"],
    "schmidt telescope": ["schmidt camera"],
    "schmuck": ["schmo", "shmo", "shmuck"],
    "schnabel": ["artur schnabel"],
    "schnapps": ["schnaps"],
    "schnitzel": ["wiener schnitzel"],
    "schnook": ["shnook"],
    "schnorr": ["cadge", "scrounge", "shnorr"],
    "schnorrer": ["shnorrer"],
    "scholar": ["bookman", "scholarly person", "student"],
    "scholasticism": ["academicism", "academism"],
    "scholium": ["scholia"],
    "schomburgkia": ["genus schomburgkia"],
    "schonbein": ["christian friedrich schonbein", "christian schonbein"],
    "schonberg": ["arnold schoenberg", "arnold schonberg", "schoenberg"],
    "school": ["school day", "schooltime"],
    "school assignment": ["schoolwork"],
    "school board": ["board of education"],
    "school newspaper": ["school paper"],
    "school ship": ["training ship"],
    "school term": ["academic session", "academic term", "session"],
    "school year": ["academic year"],
    "schoolchild": ["pupil", "school-age child"],
    "schoolcraft": ["henry rowe schoolcraft"],
    "schooldays": ["schooltime"],
    "schoolman": ["medieval schoolman"],
    "schoolmarm": ["mistress", "schoolma'am", "schoolmistress"],
    "schoolmaster": ["lutjanus apodus"],
    "schoolmate": ["class fellow", "classmate", "schoolfellow"],
    "schoolteacher": ["school teacher"],
    "schopenhauer": ["arthur schopenhauer"],
    "schrod": ["scrod"],
    "schrodinger": ["erwin schrodinger"],
    "schrodinger equation": ["schrodinger wave equation"],
    "schubert": ["franz peter schubert", "franz schubert", "franz seraph peter schubert"],
    "schulz": ["charles m. schulz", "charles munroe schulz", "charles schulz"],
    "schumann": ["clara josephine schumann"],
    "schumann-heink": ["ernestine schumann-heink"],
    "schumpeter": ["joseph alois schumpeter", "joseph schumpeter"],
    "schutzstaffel": ["ss"],
    "schwa": ["shwa"],
    "schwann": ["theodor schwann"],
    "schweitzer": ["albert schweitzer"],
    "sciadopityaceae": ["family sciadopityaceae"],
    "sciadopitys": ["genus sciadopitys"],
    "sciaena": ["genus sciaena"],
    "sciaenid fish": ["sciaenid"],
    "sciaenidae": ["family sciaenidae"],
    "sciaenops": ["genus sciaenops"],
    "sciaridae": ["family sciaridae"],
    "sciatic nerve": ["nervus ischiadicus"],
    "science": ["scientific discipline"],
    "scientific research": ["research project"],
    "scientology": ["church of scientology"],
    "scilla": ["squill"],
    "scilly islands": ["isles of scilly"],
    "scincella": ["genus scincella"],
    "scincidae": ["family scincidae"],
    "scincus": ["genus scincus"],
    "scindapsus": ["genus pothos", "genus scindapsus"],
    "scintillating scotoma": ["flittering scotoma"],
    "scipio": ["publius cornelius scipio", "publius cornelius scipio africanus major", "scipio africanus", "scipio africanus major", "scipio the elder"],
    "scirpus": ["genus scirpus"],
    "scissors": ["pair of scissors"],
    "scissortail": ["muscivora-forficata", "scissortailed flycatcher"],
    "sciuridae": ["family sciuridae"],
    "sciuromorpha": ["suborder sciuromorpha"],
    "sciurus": ["genus sciurus"],
    "sclera": ["sclerotic coat"],
    "scleral veins": ["venae sclerales"],
    "scleranthus": ["genus scleranthus"],
    "scleroderma": ["dermatosclerosis"],
    "scleroderma bovista": ["smooth earthball"],
    "scleroderma citrinum": ["scleroderma aurantium"],
    "scleroderma flavidium": ["star earthball"],
    "sclerodermataceae": ["family sclerodermataceae"],
    "sclerodermatales": ["order sclerodermatales"],
    "scleropages": ["genus scleropages"],
    "scleroparei": ["order scleroparei"],
    "scleroprotein": ["albuminoid"],
    "sclerosis": ["induration"],
    "sclerotic": ["sclerosed"],
    "sclerotiniaceae": ["family sclerotiniaceae"],
    "sclerotium": ["genus sclerotium"],
    "sclerotium disease": ["sclerotium rot"],
    "scoff": ["flout"],
    "scoffer": ["gorger"],
    "scoinson arch": ["sconcheon arch"],
    "scold": ["common scold", "nag", "nagger", "scolder"],
    "scolion": ["banquet song"],
    "scolopacidae": ["family scolopacidae"],
    "scolopax": ["genus scolopax"],
    "scolymus": ["genus scolymus"],
    "scolytidae": ["family ipidae", "family scolytidae", "ipidae"],
    "scolytus": ["genus scolytus"],
    "scomber": ["genus scomber"],
    "scomberesocidae": ["family scomberesocidae", "family scombresocidae", "scombresocidae"],
    "scomberesox": ["genus scomberesox", "genus scombresox", "scombresox"],
    "scomberomorus": ["genus scomberomorus"],
    "scombridae": ["family scombridae"],
    "scombroid": ["scombroid fish"],
    "scombroidea": ["suborder scombroidea"],
    "scoop": ["lift out", "scoop out", "scoop up", "take up"],
    "scope": ["ambit", "compass", "orbit", "range", "reach"],
    "scopes": ["john scopes", "john thomas scopes"],
    "scophthalmus": ["genus scophthalmus"],
    "scopolamine": ["hyoscine"],
    "scopolia": ["genus scopolia"],
    "scorch": ["sear", "singe"],
    "scorcher": ["screamer"],
    "score": ["mark", "nock"],
    "scorekeeper": ["scorer"],
    "scoreless": ["goalless", "hitless"],
    "scorpaena": ["genus scorpaena"],
    "scorpaenid": ["scorpaenid fish"],
    "scorpaenidae": ["family scorpaenidae"],
    "scorpaenoid": ["scorpaenoid fish"],
    "scorpaenoidea": ["suborder scorpaenoidea"],
    "scorpio": ["scorpion"],
    "scorpionfish": ["scorpion fish", "sea scorpion"],
    "scorpionida": ["order scorpionida"],
    "scorpionweed": ["phacelia", "scorpion weed"],
    "scorpius": ["scorpio"],
    "scorsese": ["martin scorsese"],
    "scorzonera": ["black salsify"],
    "scot": ["scotchman", "scotsman"],
    "scotch": ["malt whiskey", "malt whisky", "scotch malt whiskey", "scotch malt whisky", "scotch whiskey", "scotch whisky"],
    "scotch asphodel": ["tofieldia pusilla"],
    "scotch laburnum": ["alpine golden chain", "laburnum alpinum"],
    "scotch pine": ["pinus sylvestris", "scotch fir", "scots pine"],
    "scotch tape": ["sellotape"],
    "scotch terrier": ["scottie", "scottish terrier"],
    "scoter": ["scooter"],
    "scotland yard": ["new scotland yard"],
    "scots": ["scotch", "scottish"],
    "scotswoman": ["scotchwoman"],
    "scott": ["george c. scott"],
    "scottish": ["scots", "scots english"],
    "scottish deerhound": ["deerhound"],
    "scottish gaelic": ["scots gaelic"],
    "scour": ["abrade"],
    "scourge": ["flagellum"],
    "scouring rush": ["equisetum hyemale", "equisetum hyemale robustum", "equisetum robustum", "rough horsetail"],
    "scout": ["reconnoiter", "reconnoitre"],
    "scouting": ["exploratory survey", "reconnoitering", "reconnoitring"],
    "scrabbly": ["scrubby"],
    "scrag": ["scrag end"],
    "scraggy": ["boney", "scrawny", "skinny", "underweight", "weedy"],
    "scram": ["bugger off", "buzz off", "fuck off", "get"],
    "scramble": ["jumble", "throw together"],
    "scrape": ["genuflect", "kowtow"],
    "scrape along": ["rub along", "scrape by", "scratch along", "squeak by", "squeeze by"],
    "scratch": ["engrave", "grave", "inscribe"],
    "scratch out": ["cut out"],
    "scratch pad": ["scratch paper", "scribbling block"],
    "scrawler": ["scribbler"],
    "scrawniness": ["scrubbiness"],
    "scrawny": ["scrubby", "stunted"],
    "screaky": ["screechy", "squeaking", "squeaky", "squealing"],
    "scream": ["screaming", "screech", "screeching", "shriek", "shrieking"],
    "screech": ["scream", "screaming", "screeching", "shriek", "shrieking"],
    "screech owl": ["otus asio"],
    "screen": ["test"],
    "screen actor": ["movie actor"],
    "screen door": ["screen"],
    "screen font": ["raster font"],
    "screen off": ["separate off"],
    "screening": ["showing", "viewing"],
    "screenwriter": ["film writer"],
    "screw": ["drive in"],
    "screw augur": ["spiranthes cernua"],
    "screw bean": ["prosopis pubescens", "screwbean", "screwbean mesquite", "tornillo"],
    "screw thread": ["thread"],
    "screw-loose": ["screwy"],
    "scriabin": ["aleksandr nikolayevich scriabin", "aleksandr scriabin"],
    "scribble": ["scrawl"],
    "scribe": ["augustin eugene scribe"],
    "scriber": ["scratch awl", "scribe"],
    "scrimmage line": ["line of scrimmage"],
    "scrimp": ["skimp", "stint"],
    "scripps": ["edward wyllis scripps"],
    "script": ["book", "playscript"],
    "scripted": ["written"],
    "scripture": ["sacred scripture"],
    "scrod": ["schrod"],
    "scrofula": ["king's evil", "struma"],
    "scroll": ["roll"],
    "scrophularia": ["genus scrophularia"],
    "scrophulariaceae": ["family scrophulariaceae", "figwort family", "foxglove family"],
    "scrophulariales": ["order scrophulariales"],
    "scrotal vein": ["vena scrotalis"],
    "scrounge": ["forage"],
    "scrub": ["scour"],
    "scrub beefwood": ["beefwood", "stenocarpus salignus"],
    "scrub brush": ["scrubber", "scrubbing brush"],
    "scrub pine": ["jersey pine", "pinus virginiana", "virginia pine"],
    "scrubbird": ["scrub bird", "scrub-bird"],
    "scruffy": ["seedy"],
    "scrum": ["scrummage"],
    "scruple": ["misgiving", "qualm"],
    "scrupulously": ["conscientiously", "religiously"],
    "scrutineer": ["canvasser"],
    "scrutinizer": ["scrutiniser"],
    "scud": ["rack"],
    "scuff": ["drag"],
    "scuffle": ["tussle"],
    "sculpt": ["sculpture"],
    "sculptor": ["carver", "sculpturer", "statue maker"],
    "sculpture": ["carving"],
    "scup": ["southern porgy", "southern scup", "stenotomus aculeatus"],
    "scurrility": ["billingsgate"],
    "scurry": ["scamper", "scuttle", "skitter"],
    "scurvy": ["scorbutus"],
    "scurvy grass": ["cochlearia officinalis", "common scurvy grass"],
    "scut work": ["shitwork"],
    "scutellaria": ["genus scutellaria"],
    "scutigera": ["genus scutigera"],
    "scutigerella": ["genus scutigerella"],
    "scutigeridae": ["family scutigeridae"],
    "scuttle": ["coal scuttle"],
    "scyliorhinidae": ["family scyliorhinidae"],
    "scyphozoa": ["class scyphozoa"],
    "scythian lamb": ["cibotium barometz"],
    "sea anchor": ["drogue"],
    "sea anemone": ["anemone"],
    "sea aster": ["aster tripolium", "sea starwort"],
    "sea bass": ["bass"],
    "sea bream": ["bream"],
    "sea cow": ["sirenian", "sirenian mammal"],
    "sea cucumber": ["holothurian"],
    "sea dahlia": ["coreopsis maritima"],
    "sea hare": ["aplysia punctata"],
    "sea holly": ["eryngium maritimum", "sea eryngium", "sea holm"],
    "sea island cotton": ["gossypium barbadense", "tree cotton"],
    "sea kale": ["crambe maritima", "sea cole"],
    "sea ladder": ["sea steps"],
    "sea lamprey": ["petromyzon marinus"],
    "sea lavender": ["marsh rosemary", "statice"],
    "sea lettuce": ["laver"],
    "sea louse": ["sea slater"],
    "sea lyme grass": ["elymus arenarius", "european dune grass", "leymus arenaria"],
    "sea mile": ["mile"],
    "sea milkwort": ["black saltwort", "glaux maritima", "sea trifoly"],
    "sea of azov": ["sea of azof", "sea of azoff"],
    "sea of japan": ["east sea"],
    "sea otter": ["enhydra lutris"],
    "sea raven": ["hemitripterus americanus"],
    "sea robin": ["searobin"],
    "sea scallop": ["giant scallop", "pecten magellanicus"],
    "sea slug": ["nudibranch"],
    "sea spider": ["pycnogonid"],
    "sea squill": ["sea onion", "squill", "urginea maritima"],
    "sea swallow": ["sterna hirundo"],
    "sea tangle": ["tang"],
    "sea trout": ["salmon trout"],
    "sea turtle": ["marine turtle"],
    "sea wormwood": ["artemisia maritima", "seriphidium maritimum"],
    "sea wrack": ["wrack"],
    "sea-duty": ["service abroad", "shipboard duty"],
    "sea-rocket": ["cakile maritima"],
    "seabeach sandwort": ["arenaria peploides"],
    "seabird": ["sea bird", "seafowl"],
    "seaborg": ["glenn t. seaborg", "glenn theodore seaborg"],
    "seaborgium": ["atomic number 106", "element 106", "sg"],
    "seafaring": ["navigation", "sailing"],
    "seahorse": ["sea horse"],
    "seal": ["seal off"],
    "sealant": ["sealer"],
    "sealed": ["certain"],
    "sealed instrument": ["contract under seal", "special contract"],
    "sealing wax": ["seal"],
    "sealyham terrier": ["sealyham"],
    "seam": ["bed"],
    "seaman": ["elizabeth cochrane seaman", "elizabeth seaman", "nellie bly"],
    "seamanlike": ["seamanly"],
    "seamless": ["unlined", "unseamed"],
    "seamy": ["seedy", "sleazy", "sordid", "squalid"],
    "seanad eireann": ["seanad"],
    "seance": ["session", "sitting"],
    "seaplane": ["hydroplane"],
    "seaport": ["harbor", "harbour", "haven"],
    "seaquake": ["submarine earthquake"],
    "sear": ["scorch"],
    "search": ["look"],
    "searcher": ["calosoma scrutator", "searcher beetle"],
    "searching": ["trenchant"],
    "seascape": ["waterscape"],
    "seashore": ["coast", "sea-coast", "seacoast"],
    "seasickness": ["mal de mer", "naupathia"],
    "seaside": ["seaboard"],
    "seaside alder": ["alnus maritima"],
    "seaside daisy": ["beach aster", "erigeron glaucous"],
    "seaside goldenrod": ["beach goldenrod", "solidago sempervirens"],
    "season": ["flavor", "flavour"],
    "seasonableness": ["timeliness"],
    "seasonably": ["apropos", "timely", "well-timed"],
    "seasonal worker": ["seasonal"],
    "seasoned": ["veteran"],
    "seat": ["sit", "sit down"],
    "seat belt": ["seatbelt"],
    "seated": ["sitting"],
    "seating": ["seating area", "seating room", "seats"],
    "seaward": ["asea", "seawards"],
    "seawater": ["brine", "saltwater"],
    "seaway": ["sea lane", "ship route", "trade route"],
    "seaworthiness": ["fitness"],
    "sebaceous cyst": ["pilar cyst", "steatocystoma", "wen"],
    "sebaceous gland": ["glandulae sebaceae", "sebaceous follicle"],
    "sebacic acid": ["decanedioic acid"],
    "sebastiana": ["genus sebastiana"],
    "sebastodes": ["genus sebastodes"],
    "sebastopol": ["sevastopol"],
    "seborrheic dermatitis": ["seborrheic eczema"],
    "sec": ["unsweet"],
    "secale": ["genus secale"],
    "secant": ["sec"],
    "secede": ["break away", "splinter"],
    "secession": ["sezession"],
    "seckel": ["seckel pear"],
    "seclude": ["sequester", "sequestrate", "withdraw"],
    "secobarbital sodium": ["red devil", "secobarbital", "seconal"],
    "second": ["back", "endorse", "indorse"],
    "second balcony": ["family circle", "peanut gallery", "upper balcony"],
    "second base": ["second"],
    "second baseman": ["second sacker"],
    "second coming": ["advent", "parousia", "second advent", "second coming of christ"],
    "second epistel of john": ["ii john"],
    "second epistle of paul the apostle to the corinthians": ["ii corinthians", "second epistle to the corinthians"],
    "second epistle of paul the apostle to the thessalonians": ["ii thessalonians", "second epistle to the thessalonians"],
    "second epistle of paul the apostle to timothy": ["ii timothy", "second epistle to timothy"],
    "second epistle of peter": ["ii peter"],
    "second estate": ["lords temporal"],
    "second fiddle": ["second banana"],
    "second gear": ["second"],
    "second half": ["last half"],
    "second joint": ["thigh"],
    "second law of motion": ["newton's second law", "newton's second law of motion"],
    "second lieutenant": ["2nd lieutenant"],
    "second vatican council": ["vatican ii"],
    "second-guess": ["outguess"],
    "second-place finish": ["runner-up finish"],
    "second-rater": ["mediocrity"],
    "secondary coil": ["secondary", "secondary winding"],
    "secondary school": ["gymnasium", "lycee", "lyceum", "middle school"],
    "secondary sex characteristic": ["secondary sex character", "secondary sexual characteristic"],
    "secondhand": ["used"],
    "secotiaceae": ["family secotiaceae"],
    "secotiales": ["order secotiales"],
    "secrecy": ["secretiveness", "silence"],
    "secret": ["arcanum"],
    "secret agent": ["intelligence agent", "intelligence officer", "operative"],
    "secret intelligence service": ["mi", "military intelligence section 6"],
    "secretariat": ["secretariate"],
    "secretary": ["secretarial assistant"],
    "secretary bird": ["sagittarius serpentarius"],
    "secretary of agriculture": ["agriculture secretary"],
    "secretary of commerce": ["commerce secretary"],
    "secretary of defense": ["defense secretary"],
    "secretary of education": ["education secretary"],
    "secretary of energy": ["energy secretary"],
    "secretary of labor": ["labor secretary"],
    "secretary of the interior": ["interior secretary"],
    "secretary of the navy": ["navy secretary"],
    "secretary of the treasury": ["treasury secretary"],
    "secretary of transportation": ["transportation secretary"],
    "secretary of war": ["war secretary"],
    "secrete": ["release"],
    "secretion": ["secernment"],
    "secretly": ["in secret", "on the q.t.", "on the qt"],
    "secretory phase": ["luteal phase"],
    "sect": ["religious order", "religious sect"],
    "sectarian": ["sectarist", "sectary"],
    "sectarianism": ["denominationalism"],
    "section": ["plane section"],
    "sectional": ["sectioned"],
    "sectionalism": ["localism", "provincialism"],
    "sectionalize": ["sectionalise"],
    "sector": ["sphere"],
    "secularization": ["secularisation"],
    "secularize": ["secularise"],
    "secundigravida": ["gravida ii"],
    "secure": ["unafraid", "untroubled"],
    "securely": ["firmly"],
    "securities and exchange commission": ["sec"],
    "security": ["certificate"],
    "security council": ["sc"],
    "security force": ["private security force"],
    "security intelligence review committee": ["sirc"],
    "security service": ["mi", "military intelligence section 5"],
    "security system": ["security", "security measure"],
    "sedan": ["sedan chair"],
    "sedate": ["calm", "tranquilize", "tranquillise", "tranquillize"],
    "sedately": ["calmly"],
    "sedateness": ["solemness", "solemnity", "staidness"],
    "sedation": ["drugging"],
    "sedative": ["depressant", "downer", "sedative drug"],
    "sedative-hypnotic": ["sedative-hypnotic drug"],
    "seder": ["passover supper"],
    "sedge warbler": ["acrocephalus schoenobaenus", "reedbird", "sedge bird", "sedge wren"],
    "sedge wren": ["cistothorus platensis", "short-billed marsh wren"],
    "sediment": ["deposit"],
    "seduce": ["make", "score"],
    "seducer": ["ladies' man", "lady killer"],
    "seduction": ["conquest"],
    "seductively": ["temptingly"],
    "sedulity": ["sedulousness"],
    "see": ["escort"],
    "seed beetle": ["seed weevil"],
    "seed catalog": ["seed catalogue"],
    "seed corn": ["seed grain"],
    "seed fern": ["pteridosperm"],
    "seed shrimp": ["mussel shrimp", "ostracod"],
    "seedcake": ["seed cake"],
    "seeded": ["sown"],
    "seeded player": ["seed"],
    "seeder": ["cloud seeder"],
    "seedless raisin": ["sultana"],
    "seedsman": ["seedman"],
    "seeger": ["pete seeger", "peter seeger"],
    "seeker": ["quester", "searcher"],
    "seemliness": ["grace"],
    "seep": ["ooze"],
    "seepage": ["ooze", "oozing"],
    "seesaw": ["dandle board", "teeter", "teeter-totter", "teeterboard", "teetertotter", "tilting board"],
    "seethe": ["boil"],
    "segal": ["george segal"],
    "segment": ["section"],
    "sego lily": ["calochortus nuttallii"],
    "segovia": ["andres segovia"],
    "segregated": ["unintegrated"],
    "segregation": ["separatism"],
    "segregator": ["segregationist"],
    "segway": ["segway ht", "segway human transporter"],
    "sei whale": ["balaenoptera borealis"],
    "seidlitz powder": ["rochelle powder", "seidlitz powders"],
    "seigneury": ["seigniory", "signory"],
    "seigniory": ["feudal lordship", "seigneury"],
    "seine": ["seine river"],
    "seismic": ["seismal"],
    "seismological": ["seismologic"],
    "seismosaurus": ["genus seismosaurus"],
    "seiurus": ["genus seiurus"],
    "seize": ["clutch", "prehend"],
    "seizure": ["ictus", "raptus"],
    "sekhet": ["eye of ra"],
    "selaginella": ["genus selaginella"],
    "selaginellaceae": ["family selaginellaceae"],
    "selaginellales": ["order selaginellales"],
    "selar": ["genus selar"],
    "selective service": ["selective service system", "sss"],
    "selective-serotonin reuptake inhibitor": ["ssri"],
    "selector": ["selector switch"],
    "selenarctos": ["genus selenarctos"],
    "selene": ["genus selene"],
    "selenicereus": ["genus selenicereus"],
    "selenipedium": ["genus selenipedium"],
    "selenium": ["atomic number 34", "se"],
    "seles": ["monica seles"],
    "seleucus": ["seleucus i", "seleucus i nicator"],
    "self": ["ego"],
    "self-absorbed": ["self-involved"],
    "self-accusation": ["self-condemnation"],
    "self-acting": ["self-activating", "self-moving", "self-regulating"],
    "self-aggrandizement": ["ego trip", "self-aggrandisement"],
    "self-aggrandizing": ["self-aggrandising"],
    "self-assured": ["self-confident"],
    "self-conscious": ["self-aware"],
    "self-consciousness": ["uncomfortableness", "uneasiness"],
    "self-constituted": ["self-established"],
    "self-control": ["possession", "self-command", "self-possession", "self-will", "will power", "willpower"],
    "self-deception": ["self-deceit"],
    "self-defense": ["self-defence", "self-protection"],
    "self-denial": ["self-control", "self-discipline"],
    "self-denying": ["self-giving", "self-sacrificing"],
    "self-destruct": ["self-destroy"],
    "self-destructive": ["suicidal"],
    "self-discipline": ["self-denial"],
    "self-disciplined": ["self-restraining"],
    "self-disgust": ["self-hatred"],
    "self-education": ["self-cultivation"],
    "self-esteem": ["self-pride"],
    "self-feeder": ["feeder"],
    "self-fertilization": ["self-fertilisation"],
    "self-fertilized": ["self-fertilised", "self-pollinated"],
    "self-fulfillment": ["self-realisation", "self-realization"],
    "self-generated": ["self-produced"],
    "self-government": ["self-determination", "self-rule"],
    "self-gratification": ["head trip"],
    "self-heal": ["heal all", "prunella vulgaris"],
    "self-improvement": ["self-reformation"],
    "self-love": ["narcism", "narcissism"],
    "self-organization": ["self-organisation"],
    "self-propelled": ["self-propelling"],
    "self-report personality inventory": ["self-report inventory"],
    "self-reproach": ["self-reproof"],
    "self-restraint": ["temperateness"],
    "self-rising flour": ["self-raising flour"],
    "self-seeded": ["self-sowed", "self-sown"],
    "self-serving": ["self-seeking"],
    "self-stimulation": ["self-abuse"],
    "self-styled": ["soi-disant"],
    "self-sufficient": ["self-sufficing", "self-sustaining"],
    "self-torture": ["self-torment"],
    "selflessness": ["self-sacrifice"],
    "selkirk": ["alexander selcraig", "alexander selkirk", "selcraig"],
    "selkup": ["ostyak-samoyed"],
    "sell out": ["liquidize", "sell up"],
    "seller": ["marketer", "trafficker", "vender", "vendor"],
    "seller's market": ["sellers' market"],
    "sellers": ["peter sellers"],
    "selling": ["marketing", "merchandising"],
    "selsyn": ["synchro"],
    "selvage": ["selvedge"],
    "selznick": ["david o. selznick", "david oliver selznick"],
    "semantic error": ["run-time error", "runtime error"],
    "semantic role": ["participant role"],
    "semanticist": ["semiotician"],
    "semarang": ["samarang"],
    "semblance": ["color", "colour", "gloss"],
    "semen": ["come", "cum", "ejaculate", "seed", "seminal fluid"],
    "semester hour": ["credit hour"],
    "semestral": ["semestrial"],
    "semi-automatize": ["semi-automatise"],
    "semi-evergreen": ["half-evergreen"],
    "semiannual": ["biannual", "biyearly", "half-yearly"],
    "semiannually": ["biyearly"],
    "semiaquatic": ["subaquatic"],
    "semiautomatic pistol": ["semiautomatic"],
    "semicentennial": ["semicentenary"],
    "semicircle": ["hemicycle"],
    "semiconducting": ["semiconductive"],
    "semiconductor": ["semiconducting material"],
    "semiconductor device": ["semiconductor", "semiconductor unit"],
    "semifinal": ["semi"],
    "semiformal": ["black-tie", "semi-formal"],
    "semimonthly": ["bimonthly"],
    "seminarian": ["seminarist"],
    "seminoma": ["testicular cancer"],
    "semiotic": ["semiotical"],
    "semiotics": ["semiology"],
    "semiprofessional": ["semipro"],
    "semite": ["semitic"],
    "semitone": ["half step"],
    "semitrailer": ["semi"],
    "semivowel": ["glide"],
    "semiweekly": ["biweekly"]
}
