synonyms = {
    "michelangelo": ["michelangelo buonarroti"],
    "michelson": ["a. a. michelson", "albert abraham michelson", "albert michelson"],
    "michener": ["james albert michener", "james michener"],
    "michigan": ["great lakes state", "mi", "wolverine state"],
    "michigan lily": ["lilium michiganense"],
    "michigander": ["wolverine"],
    "micmac": ["mikmaq"],
    "miconazole": ["monistat"],
    "microbe": ["bug", "germ"],
    "microbial": ["microbic"],
    "microcentrum": ["genus microcentrum"],
    "microcephalic": ["microcephalous", "nanocephalic"],
    "microcephaly": ["microcephalus", "nanocephaly"],
    "microchiroptera": ["suborder microchiroptera"],
    "micrococcaceae": ["family micrococcaceae"],
    "micrococcus": ["genus micrococcus"],
    "microcytic anemia": ["microcytic anaemia"],
    "microdesmidae": ["family microdesmidae"],
    "microdipodops": ["genus microdipodops"],
    "microeconomist": ["microeconomic expert"],
    "microgram": ["mcg"],
    "microgramma": ["genus microgramma"],
    "microhylidae": ["brevicipitidae", "family brevicipitidae", "family microhylidae"],
    "micromeria": ["genus micromeria"],
    "micrometeorite": ["micrometeor", "micrometeoroid"],
    "micrometer": ["micrometer caliper", "micrometer gauge"],
    "micromyx": ["genus micromyx"],
    "micron": ["micrometer"],
    "micronesia": ["federated states of micronesia", "tt"],
    "microorganism": ["micro-organism"],
    "micropenis": ["microphallus"],
    "microphone": ["mike"],
    "micropogonias": ["genus micropogonias"],
    "micropterus": ["genus micropterus"],
    "microscopic": ["microscopical"],
    "microsorium": ["genus microsorium"],
    "microsporum": ["genus microsporum"],
    "microstomus": ["genus microstomus"],
    "microstrobos": ["genus microstrobos"],
    "microtus": ["genus microtus"],
    "microwave": ["micro-cook", "nuke", "zap"],
    "microwave bomb": ["e-bomb"],
    "micruroides": ["genus micruroides"],
    "micrurus": ["genus micrurus"],
    "micturition": ["urination"],
    "midazolam": ["versed"],
    "midbrain": ["mesencephalon"],
    "middle": ["midriff", "midsection"],
    "middle ages": ["dark ages"],
    "middle atlantic": ["mid-atlantic"],
    "middle cerebral vein": ["vena cerebri media"],
    "middle class": ["bourgeoisie"],
    "middle ear": ["tympanic cavity", "tympanum"],
    "middle east": ["mideast", "near east"],
    "middlemost": ["midmost"],
    "middleton": ["thomas middleton"],
    "middy": ["middy blouse"],
    "midiron": ["two iron"],
    "midmost": ["in the midst"],
    "midplane": ["midline"],
    "midrib": ["midvein"],
    "midst": ["thick"],
    "midsummer day": ["june 24", "midsummer's day", "st john's day"],
    "midsummer eve": ["june 23", "midsummer night", "st john's eve", "st john's night"],
    "midterm examination": ["midterm", "midterm exam"],
    "midway": ["battle of midway"],
    "midwest": ["middle west", "midwestern united states"],
    "midwife": ["accoucheuse"],
    "midwife toad": ["alytes cisternasi"],
    "mies van der rohe": ["ludwig mies van der rohe"],
    "might": ["mightiness", "power"],
    "mighty": ["mightily", "powerful", "right"],
    "mignonette": ["reseda odorata", "sweet reseda"],
    "migraine": ["hemicrania", "megrim", "sick headache"],
    "migrant": ["migrator"],
    "migrant shrike": ["lanius ludovicianus migrans"],
    "migrate": ["transmigrate"],
    "migration route": ["flyway"],
    "migratory locust": ["locusta migratoria"],
    "migratory quail": ["coturnix communis", "coturnix coturnix"],
    "mikado": ["tenno"],
    "mikania": ["genus mikania"],
    "milan": ["milano"],
    "mild silver protein": ["argyrol"],
    "mild steel": ["low-carbon steel", "soft-cast steel"],
    "mildew": ["mold", "mould"],
    "mildness": ["clemency"],
    "mile": ["roman mile"],
    "mileage": ["fuel consumption rate", "gas mileage", "gasoline mileage"],
    "miles per hour": ["mph"],
    "milestone": ["milepost"],
    "milhaud": ["darius milhaud"],
    "milieu": ["surroundings"],
    "militant": ["activist"],
    "militarist": ["warmonger"],
    "militarize": ["militarise"],
    "militarized": ["militarised"],
    "military": ["armed forces", "armed services", "military machine", "war machine"],
    "military action": ["action"],
    "military adviser": ["military advisor"],
    "military capability": ["military posture", "military strength", "posture", "strength"],
    "military chaplain": ["holy joe", "padre", "sky pilot"],
    "military government": ["stratocracy"],
    "military intelligence": ["military intelligence agency"],
    "military junta": ["junta"],
    "military march": ["martial music", "military music"],
    "military officer": ["officer"],
    "military personnel": ["soldiery", "troops"],
    "military police": ["mp"],
    "military policeman": ["mp"],
    "military position": ["position"],
    "military post": ["post"],
    "military rank": ["military rating", "paygrade", "rating"],
    "military reserve": ["reserve"],
    "military service": ["armed service", "service"],
    "military unit": ["force", "military force", "military group"],
    "militia": ["reserves"],
    "milk": ["milk river"],
    "milk leg": ["phlegmasia alba dolens", "white leg"],
    "milk snake": ["checkered adder", "house snake", "lampropeltis triangulum", "milk adder"],
    "milk thistle": ["blessed thistle", "holy thistle", "lady's thistle", "our lady's mild thistle", "silybum marianum"],
    "milk vetch": ["milk-vetch"],
    "milk wagon": ["milkwagon"],
    "milkcap": ["lactarius delicioso"],
    "milkshake": ["milk shake", "shake"],
    "milkweed": ["silkweed"],
    "milky": ["milklike", "whitish"],
    "milky way": ["milky way galaxy", "milky way system"],
    "mill": ["mill about", "mill around"],
    "mill-hand": ["factory worker"],
    "millais": ["sir john everett millais"],
    "millay": ["edna millay", "edna saint vincent millay"],
    "milled": ["polished"],
    "millenarian": ["chiliast", "millenarist"],
    "millenarianism": ["chiliasm", "millenarism", "millenniumism"],
    "millennial": ["millennian"],
    "millennium": ["millenary"],
    "miller": ["alton glenn miller", "glenn miller"],
    "millet": ["jean francois millet"],
    "milliampere": ["ma"],
    "milliequivalent": ["meq"],
    "milligram": ["mg"],
    "millikan": ["robert andrews millikan"],
    "milliliter": ["cc", "cubic centimeter", "cubic centimetre", "mil", "millilitre", "ml"],
    "millimeter": ["millimetre", "mm"],
    "millinery": ["hat shop"],
    "million": ["billion", "gazillion", "jillion", "trillion", "zillion"],
    "millionfold": ["a million times"],
    "millipede": ["millepede", "milliped"],
    "millisecond": ["msec"],
    "millivolt": ["mv"],
    "millrace": ["millrun"],
    "mills": ["robert mills"],
    "millwheel": ["mill wheel"],
    "milne": ["a. a. milne", "alan alexander milne"],
    "milo": ["milo maize"],
    "milt": ["soft roe"],
    "milton": ["john milton"],
    "miltonia": ["genus miltonia"],
    "milvus": ["genus-milvus"],
    "mime": ["pantomime"],
    "mimeograph": ["mimeo"],
    "mimic": ["mime"],
    "mimidae": ["family mimidae"],
    "mimosa": ["buck's fizz"],
    "mimosaceae": ["family mimosaceae"],
    "mimosoideae": ["subfamily mimosoideae"],
    "mimus": ["genus mimus"],
    "min": ["amoy", "fukien", "fukkianese", "hokkianese", "min dialect", "taiwanese"],
    "mince": ["moderate", "soften"],
    "mincer": ["mincing machine"],
    "mind": ["bear in mind"],
    "mind reader": ["telepathist", "thought-reader"],
    "mind-bending": ["mind-blowing"],
    "minden": ["battle of minden"],
    "mindful": ["aware"],
    "mindfully": ["advertently", "heedfully"],
    "mindfulness": ["heedfulness"],
    "mindless": ["reasonless", "senseless"],
    "mindlessly": ["senselessly"],
    "miner": ["mineworker"],
    "mineral extraction": ["beneficiation", "mineral dressing", "mineral processing", "ore dressing", "ore processing"],
    "mineral wool": ["rock wool"],
    "ming": ["ming dynasty"],
    "miniate": ["rubricate"],
    "miniature": ["illumination"],
    "miniature fan palm": ["bamboo palm", "fern rhapis", "rhapis excelsa"],
    "miniaturization": ["miniaturisation"],
    "miniaturize": ["miniaturise"],
    "minibar": ["cellaret"],
    "minibike": ["motorbike"],
    "minimal": ["minimum"],
    "minimalism": ["minimal art", "reductivism"],
    "minimization": ["minimisation"],
    "minimize": ["belittle", "denigrate", "derogate"],
    "minimum": ["lower limit"],
    "mining": ["minelaying"],
    "miniskirt": ["mini"],
    "minister": ["government minister"],
    "minisub": ["minisubmarine"],
    "mink": ["mink coat"],
    "minkowski": ["hermann minkowski"],
    "minnesota": ["gopher state", "mn", "north star state"],
    "minnesota multiphasic personality inventory": ["mmpi"],
    "minnesotan": ["gopher"],
    "minniebush": ["menziesia pilosa", "minnie bush"],
    "minnow": ["phoxinus phoxinus"],
    "minoan civilization": ["minoan civilisation", "minoan culture"],
    "minocycline": ["minocin"],
    "minor": ["venial"],
    "minor key": ["minor mode"],
    "minor league": ["bush league", "minors"],
    "minor leaguer": ["bush leaguer"],
    "minor planet": ["planetoid"],
    "minor premise": ["minor premiss", "subsumption"],
    "minor scale": ["minor diatonic scale"],
    "minor tranquilizer": ["antianxiety drug", "anxiolytic", "anxiolytic drug", "minor tranquilliser", "minor tranquillizer"],
    "minor-league team": ["minor-league club"],
    "minority": ["nonage"],
    "minoxidil": ["loniten", "rogaine"],
    "minsk": ["capital of belarus"],
    "mint": ["coin", "strike"],
    "minuartia": ["genus minuartia"],
    "minuit": ["minnewit", "peter minnewit", "peter minuit"],
    "minus": ["negative"],
    "minuscule": ["minuscular"],
    "minute": ["min"],
    "minute hand": ["big hand"],
    "minutely": ["circumstantially"],
    "minutes": ["proceedings", "transactions"],
    "miocene": ["miocene epoch"],
    "miotic": ["myotic"],
    "miotic drug": ["miotic", "myotic", "myotic drug"],
    "mips": ["million instructions per second"],
    "mirabeau": ["comte de mirabeau", "honore-gabriel victor riqueti"],
    "mirabilis": ["genus mirabilis"],
    "miracle man": ["miracle worker"],
    "miraculous food": ["manna", "manna from heaven"],
    "mire": ["bog down"],
    "miri": ["abor", "dafla", "mirish"],
    "mirid bug": ["capsid", "mirid"],
    "miridae": ["capsidae", "family capsidae", "family miridae"],
    "miro": ["black pine", "podocarpus ferruginea", "prumnopitys ferruginea"],
    "mirounga": ["genus mirounga"],
    "mirror image": ["reflection", "reflexion"],
    "mirrorlike": ["specular"],
    "misadvise": ["misguide"],
    "misanthrope": ["misanthropist"],
    "misanthropic": ["misanthropical"],
    "misapply": ["misuse"],
    "misbehave": ["misconduct", "misdemean"],
    "misbehavior": ["misbehaviour", "misdeed"],
    "misbranded": ["mislabeled"],
    "miscalculate": ["misestimate"],
    "miscalculation": ["misestimation", "misreckoning"],
    "miscarriage": ["abortion"],
    "miscegenation": ["crossbreeding", "interbreeding"],
    "mischief": ["devilment", "devilry", "deviltry", "mischief-making", "mischievousness", "rascality", "roguery", "roguishness", "shenanigan"],
    "miscible": ["mixable"],
    "misconstrual": ["misconstruction"],
    "misconstrue": ["be amiss", "misapprehend", "misconceive", "misinterpret", "misunderstand"],
    "misdemeanor": ["infraction", "infringement", "misdemeanour", "violation"],
    "misdirect": ["misaddress"],
    "mise en scene": ["setting", "stage setting"],
    "miserable": ["suffering", "wretched"],
    "misery": ["miserableness", "wretchedness"],
    "misfire": ["dud"],
    "misfortune": ["bad luck", "ill luck", "tough luck"],
    "misgiving": ["distrust", "mistrust", "suspicion"],
    "misgovernment": ["misrule"],
    "misguided": ["mistaken"],
    "mishap": ["misadventure", "mischance"],
    "mishna": ["mishnah"],
    "mishpocha": ["mishpachah"],
    "misinform": ["mislead"],
    "misinterpretation": ["mistaking", "misunderstanding"],
    "mislaid": ["misplaced"],
    "mislead": ["lead astray", "misdirect", "misguide"],
    "mismanage": ["misconduct", "mishandle"],
    "mismanagement": ["misdirection"],
    "mismatched": ["uneven"],
    "misname": ["miscall"],
    "misogynist": ["woman hater"],
    "misogynous": ["misogynistic"],
    "misogyny": ["misogynism"],
    "misplace": ["lose", "mislay"],
    "misprint": ["erratum", "literal", "literal error", "typo", "typographical error"],
    "mispronounce": ["misspeak"],
    "misquotation": ["misquote"],
    "misread": ["misinterpret"],
    "misrepresent": ["belie"],
    "misrepresentation": ["deceit", "deception"],
    "miss": ["lack"],
    "missel thrush": ["mistle thrush", "mistletoe thrush", "turdus viscivorus"],
    "missile defense system": ["missile defence system"],
    "missing link": ["ape-man"],
    "mission": ["foreign mission", "missionary post", "missionary station"],
    "mission bells": ["black fritillary", "fritillaria biflora"],
    "missionary": ["missioner"],
    "mississippi": ["mississippi river"],
    "mississippian": ["lower carboniferous", "lower carboniferous period", "missippian period"],
    "missouri": ["missouri river"],
    "missouri goldenrod": ["solidago missouriensis"],
    "missouri primrose": ["oenothera macrocarpa", "ozark sundrops"],
    "missus": ["missis"],
    "mist": ["mist over"],
    "mistake": ["misidentify"],
    "mistakenly": ["erroneously"],
    "mister": ["mr", "mr."],
    "mistflower": ["ageratum", "conoclinium coelestinum", "eupatorium coelestinum", "mist-flower"],
    "mistletoe": ["false mistletoe"],
    "mistletoe fig": ["ficus deltoidea", "ficus diversifolia", "mistletoe rubber plant"],
    "mistreat": ["abuse", "ill-treat", "ill-use", "maltreat", "step"],
    "mistress": ["fancy woman", "kept woman"],
    "misuse": ["abuse"],
    "mitchell": ["r. j. mitchell", "reginald joseph mitchell"],
    "mitchella": ["genus mitchella"],
    "mitchum": ["robert mitchum"],
    "mitella": ["genus mitella"],
    "miter": ["mitre"],
    "miter box": ["mitre box"],
    "miter joint": ["miter", "mitre", "mitre joint"],
    "miterwort": ["bishop's cap", "mitrewort"],
    "mitford": ["jessica lucy mitford", "jessica mitford"],
    "mithraic": ["mithraistic"],
    "mithraism": ["mithraicism"],
    "mithramycin": ["mithracin"],
    "mithras": ["mithra"],
    "mithridates": ["mithridates the great", "mithridates vi"],
    "mitochondrion": ["chondriosome"],
    "mitomycin": ["mutamycin"],
    "mitral stenosis": ["mitral valve stenosis"],
    "mitral valve": ["bicuspid valve", "left atrioventricular valve"],
    "mitterrand": ["francois maurice marie mitterrand", "francois mitterrand"],
    "mitzvah": ["mitsvah"],
    "mix": ["amalgamate", "commix", "mingle", "unify"],
    "mizzen": ["mizen"],
    "mizzenmast": ["mizen", "mizenmast", "mizzen"],
    "mnemonic": ["mnemotechnic", "mnemotechnical"],
    "mniaceae": ["family mniaceae"],
    "mnium": ["genus mnium"],
    "moat": ["fosse"],
    "mob": ["rabble", "rout"],
    "mobbish": ["moblike"],
    "mobile": ["mobile river"],
    "mobile home": ["manufactured home"],
    "mobilization": ["mobilisation"],
    "mobilize": ["mobilise"],
    "mobius": ["august f. mobius", "august ferdinand mobius"],
    "mobocracy": ["ochlocracy"],
    "mobula": ["genus mobula"],
    "mobulidae": ["family mobulidae"],
    "moccasin": ["mocassin"],
    "moccasin flower": ["cypripedium acaule", "nerveroot"],
    "mocha": ["mocha coffee"],
    "mock": ["bemock"],
    "mock orange": ["philadelphus coronarius", "syringa"],
    "mockernut": ["big-bud hickory", "black hickory", "carya tomentosa", "mockernut hickory", "white-heart hickory"],
    "mocking": ["quizzical", "teasing"],
    "mockingbird": ["mimus polyglotktos", "mocker"],
    "mod": ["modern", "modernistic"],
    "modal": ["average"],
    "modal auxiliary verb": ["modal", "modal auxiliary", "modal verb"],
    "modality": ["mode"],
    "mode": ["musical mode"],
    "model": ["pose", "posture", "sit"],
    "modeled": ["sculptural", "sculptured", "sculpturesque"],
    "modeler": ["modeller"],
    "modeling": ["modelling", "molding", "moulding"],
    "moderate": ["chair", "lead"],
    "moderate gale": ["near gale"],
    "moderation": ["moderateness"],
    "modern": ["bodoni", "bodoni font", "modern font"],
    "modern greek": ["new greek"],
    "modern jazz": ["neo jazz", "new jazz"],
    "modern times": ["contemporary world", "modern world", "present times"],
    "modernity": ["contemporaneity", "contemporaneousness", "modernism", "modernness"],
    "modernization": ["modernisation"],
    "modernize": ["develop", "modernise"],
    "modernized": ["modernised"],
    "modest": ["small"],
    "modesty": ["modestness"],
    "modification": ["limiting", "qualifying"],
    "modifier": ["qualifier"],
    "modify": ["qualify"],
    "modigliani": ["amedeo modigliano"],
    "modulation": ["inflection"],
    "moehringia": ["genus moehringia"],
    "moeller's glossitis": ["glossodynia exfoliativa"],
    "mogadishu": ["capital of somalia", "mogadiscio"],
    "mogul": ["moghul"],
    "mohammed": ["mahomet", "mahound", "mohammad", "muhammad"],
    "mohammed ali": ["mehemet ali", "muhammad ali"],
    "mohammedan": ["muhammadan", "muhammedan"],
    "mohave": ["mojave"],
    "mohawk": ["mohawk haircut"],
    "mohican": ["mahican"],
    "mohorovicic": ["andrija mohorovicic"],
    "mohorovicic discontinuity": ["moho"],
    "mohria": ["genus mohria"],
    "moiety": ["mediety"],
    "moirai": ["moirae"],
    "moire": ["watered-silk"],
    "moisten": ["dampen", "wash"],
    "moistening": ["dampening"],
    "moisture": ["wet"],
    "mojave": ["mohave", "mohave desert", "mojave desert"],
    "mojave aster": ["machaeranthera tortifoloia"],
    "mojave rattlesnake": ["crotalus scutulatus"],
    "molality": ["molal concentration"],
    "molar": ["grinder"],
    "molarity": ["molar concentration"],
    "mold": ["mildew"],
    "moldboard": ["mouldboard"],
    "moldboard plow": ["mouldboard plough"],
    "molding": ["moulding"],
    "moldova": ["moldavia", "republic of moldova"],
    "moldy": ["mouldy", "musty"],
    "mole salamander": ["ambystoma talpoideum"],
    "molecular weight": ["relative molecular mass"],
    "molidae": ["family molidae"],
    "moliere": ["jean-baptiste poquelin"],
    "molindone": ["moban"],
    "moll": ["gangster's moll", "gun moll"],
    "mollie": ["molly"],
    "mollienesia": ["genus mollienesia"],
    "molluga": ["genus molluga"],
    "mollusca": ["phylum mollusca"],
    "mollusk": ["mollusc", "shellfish"],
    "molly miller": ["scartella cristata"],
    "molnar": ["ferenc molnar"],
    "moloch": ["molech"],
    "molokai": ["molokai island"],
    "molossidae": ["family molossidae"],
    "molothrus": ["genus molothrus"],
    "molotov": ["vyacheslav mikhailovich molotov"],
    "molotov cocktail": ["gasoline bomb", "petrol bomb"],
    "molt": ["ecdysis", "molting", "moult", "moulting"],
    "molten": ["liquefied", "liquified"],
    "molter": ["moulter"],
    "molucca balm": ["bells of ireland", "molucella laevis"],
    "moluccas": ["spice islands"],
    "molucella": ["genus molucella"],
    "molva": ["genus molva"],
    "molybdenum": ["atomic number 42", "mo"],
    "mombin": ["jocote", "mombin tree", "spondias purpurea"],
    "moment": ["bit", "minute", "mo", "second"],
    "momentarily": ["momently"],
    "momentum": ["impulse"],
    "momism": ["overprotection", "overshielding"],
    "mommsen": ["theodor mommsen"],
    "momordica": ["genus momordica"],
    "momotidae": ["family momotidae"],
    "momotus": ["genus momotus"],
    "momus": ["momos"],
    "monacan": ["monegasque"],
    "monaco": ["principality of monaco"],
    "monad": ["monas"],
    "monadic operation": ["unary operation"],
    "monal": ["monaul"],
    "monarch": ["danaus plexippus", "milkweed butterfly", "monarch butterfly"],
    "monarchal": ["monarchical"],
    "monarchist": ["royalist"],
    "monarda": ["wild bergamot"],
    "monardella": ["genus monardella"],
    "monatomic": ["monoatomic"],
    "monaurally": ["in one ear", "to one ear"],
    "monday": ["mon"],
    "mondrian": ["piet mondrian"],
    "monegasque": ["monacan"],
    "monel metal": ["monell metal"],
    "monera": ["kingdom monera", "kingdom prokaryotae", "prokayotae"],
    "moneran": ["moneron"],
    "moneses": ["genus moneses"],
    "monestrous": ["monoestrous"],
    "monet": ["claude monet"],
    "monetary": ["pecuniary"],
    "monetary value": ["cost", "price"],
    "monetization": ["monetisation"],
    "monetize": ["monetise"],
    "money cowrie": ["cypraea moneta"],
    "money handler": ["money dealer"],
    "money order": ["postal order"],
    "moneyed": ["monied"],
    "moneymaker": ["cash cow", "money-spinner"],
    "moneywort": ["creeping charlie", "creeping jenny", "lysimachia nummularia"],
    "mongol": ["mongolian"],
    "mongolia": ["mongolian people's republic", "outer mongolia"],
    "mongolian": ["mongolic", "mongolic language"],
    "mongolism": ["down syndrome", "down's syndrome", "mongolianism", "trisomy 21"],
    "mongrelize": ["mongrelise"],
    "moniliaceae": ["family moniliaceae"],
    "moniliales": ["order moniliales"],
    "monition": ["process of monition"],
    "monitor": ["supervise"],
    "monitor program": ["monitoring program"],
    "monk": ["thelonious monk", "thelonious sphere monk"],
    "monkey puzzle": ["araucaria araucana", "chile pine"],
    "monkey-wrench": ["monkey wrench"],
    "monkshood": ["aconitum napellus", "helmet flower", "helmetflower"],
    "monmouth court house": ["battle of monmouth", "battle of monmouth court house"],
    "monnet": ["jean monnet"],
    "mono": ["monophonic", "single-channel"],
    "monoamine oxidase": ["mao"],
    "monoamine oxidase inhibitor": ["maoi"],
    "monocanthidae": ["family monocanthidae"],
    "monocanthus": ["genus monocanthus"],
    "monocarp": ["monocarpic plant", "monocarpous plant"],
    "monochamus": ["genus monochamus"],
    "monochromacy": ["monochromasy", "monochromatic vision", "monochromatism", "monochromia"],
    "monochromatic": ["monochrome", "monochromic", "monochromous"],
    "monocle": ["eyeglass"],
    "monoclonal antibody": ["monoclonal"],
    "monocot": ["endogen", "liliopsid", "monocotyledon"],
    "monocot family": ["liliopsid family"],
    "monocot genus": ["liliopsid genus"],
    "monocotyledones": ["class liliopsida", "class monocotyledonae", "class monocotyledones", "liliopsida", "monocotyledonae"],
    "monocytic leukemia": ["histiocytic leukaemia", "histiocytic leukemia", "monoblastic leukaemia", "monoblastic leukemia", "monocytic leukaemia"],
    "monod": ["jacques lucien monod", "jacques monod"],
    "monodic": ["monodical"],
    "monodon": ["genus monodon"],
    "monodontidae": ["family monodontidae"],
    "monoecious": ["monecious", "monoicous"],
    "monofocal lens implant": ["monofocal iol"],
    "monogamist": ["monogynist"],
    "monogamy": ["monogamousness"],
    "monogenesis": ["sporulation"],
    "monogenic disorder": ["monogenic disease"],
    "monogynous": ["monogynic"],
    "monologuize": ["monologuise", "soliloquise", "soliloquize"],
    "monomania": ["possession"],
    "monomorium": ["genus monomorium"],
    "monongahela": ["monongahela river"],
    "mononuclear": ["mononucleate"],
    "mononuclear phagocyte system": ["mps", "system of macrophages"],
    "monophony": ["monody", "monophonic music"],
    "monophysite": ["monophysitic"],
    "monoplane flying fish": ["two-wing flying fish"],
    "monopolist": ["monopoliser", "monopolizer"],
    "monopolization": ["monopolisation"],
    "monopolize": ["monopolise"],
    "monorchism": ["monorchidism"],
    "monosaccharide": ["monosaccharose", "simple sugar"],
    "monosodium glutamate": ["msg"],
    "monosyllable": ["monosyllabic word"],
    "monotone": ["drone", "droning"],
    "monotonic": ["monotone"],
    "monotony": ["humdrum", "sameness"],
    "monotremata": ["order monotremata"],
    "monotreme": ["egg-laying mammal"],
    "monotropa": ["genus monotropa"],
    "monotropaceae": ["family monotropaceae"],
    "monovalent": ["univalent"],
    "monroe": ["marilyn monroe", "norma jean baker"],
    "monrovia": ["capital of liberia", "liberian capital"],
    "mons": ["mons pubis", "mons veneris"],
    "monster": ["demon", "devil", "fiend", "ogre"],
    "monstrance": ["ostensorium"],
    "mont blanc": ["monte bianco"],
    "montagu": ["ashley montagu"],
    "montagu's harrier": ["circus pygargus"],
    "montaigne": ["michel eyquem montaigne", "michel montaigne"],
    "montana": ["mt", "treasure state"],
    "monte": ["four-card monte", "three-card monte"],
    "montenegro": ["crna gora"],
    "monterey cypress": ["cupressus macrocarpa"],
    "monterey pine": ["pinus radiata"],
    "montespan": ["francoise-athenais de rochechouart", "marquise de montespan"],
    "montesquieu": ["baron de la brede et de montesquieu", "charles louis de secondat"],
    "montessori": ["maria montesorri"],
    "monteverdi": ["claudio monteverdi"],
    "montevideo": ["capital of uruguay"],
    "montez": ["lola montez", "marie dolores eliza rosanna gilbert"],
    "montezuma cypress": ["mexican swamp cypress", "taxodium mucronatum"],
    "montfort": ["earl of leicester", "simon de montfort"],
    "montgolfier": ["jacques etienne montgolfier"],
    "montgomery": ["l. m. montgomery", "lucy maud montgomery"],
    "montia": ["genus montia"],
    "montpelier": ["capital of vermont"],
    "monumentalize": ["monumentalise"],
    "moo": ["low"],
    "mooch": ["bum", "cadge", "grub", "sponge"],
    "moocher": ["cadger", "mooch", "scrounger"],
    "mood": ["modality", "mode"],
    "moody": ["helen newington wills", "helen wills", "helen wills moody"],
    "moon": ["moon around", "moon on"],
    "moon blindness": ["mooneye"],
    "moon carrot": ["stone parsley"],
    "moon shell": ["moonshell"],
    "moon trefoil": ["medicago arborea"],
    "moon-faced": ["round-faced"],
    "moon-worship": ["selenolatry"],
    "moonbeam": ["moon ray", "moon-ray"],
    "moonfish": ["atlantic moonfish", "dollarfish", "horse-head", "horsefish", "horsehead", "selene setapinnis"],
    "moonflower": ["belle de nuit", "ipomoea alba"],
    "moonlight": ["moon", "moonshine"],
    "moonlike": ["moon-round"],
    "moonlit": ["moony"],
    "moonshine": ["bootleg", "corn liquor"],
    "moonwort": ["botrychium lunaria", "common moonwort"],
    "moor": ["berth", "tie up"],
    "moore": ["douglas moore"],
    "moorhen": ["gallinula chloropus"],
    "mooring": ["berth", "moorage", "slip"],
    "mooring tower": ["mooring mast"],
    "moorish": ["moorish architecture"],
    "moorish arch": ["horseshoe arch"],
    "moosewood": ["acer pennsylvanicum", "goosefoot maple", "moose-wood", "striped dogwood", "striped maple"],
    "mope": ["mope around"],
    "moquelumnan": ["miwok"],
    "moraceae": ["family moraceae", "mulberry family"],
    "moral": ["lesson"],
    "moral force": ["dynamic"],
    "morale building": ["morale booster"],
    "moralization": ["moralisation"],
    "moralize": ["moralise"],
    "moralizing": ["moralisation", "moralization"],
    "morally": ["virtuously"],
    "moray": ["moray eel"],
    "morbidity": ["morbidness"],
    "morchella": ["genus morchella"],
    "morchella crassipes": ["thick-footed morel"],
    "morchella semilibera": ["cow's head", "half-free morel"],
    "morchellaceae": ["family morchellaceae"],
    "mordva": ["mordvin", "mordvinian"],
    "more": ["sir thomas more", "thomas more"],
    "morello": ["prunus cerasus austera"],
    "moreton bay chestnut": ["australian chestnut"],
    "moreton bay tulipwood": ["harpullia pendula"],
    "morgan": ["lewis henry morgan"],
    "morganatic": ["left-handed"],
    "morgue": ["dead room", "mortuary"],
    "morion": ["cabasset"],
    "morley": ["e. w. morley", "edward morley", "edward williams morley"],
    "mormon cricket": ["anabrus simplex"],
    "morning": ["forenoon", "morn", "morning time"],
    "morning star": ["daystar", "lucifer", "phosphorus"],
    "moroccan": ["maroc"],
    "moroccan dirham": ["dirham"],
    "morocco": ["al-magrib", "kingdom of morocco", "maroc", "marruecos"],
    "morone": ["genus morone"],
    "moronity": ["mental deficiency"],
    "moroseness": ["glumness", "sullenness"],
    "morphine": ["morphia"],
    "morphologic": ["morphological"],
    "morphological rule": ["rule of morphology"],
    "morphology": ["sound structure", "syllable structure", "word structure"],
    "morrigan": ["morrigu"],
    "morris": ["esther hobart mcquigg slack morris", "esther morris"],
    "morris dance": ["morris dancing"],
    "morrison": ["james douglas morrison", "jim morrison"],
    "morrow's honeysuckle": ["lonicera morrowii"],
    "morse": ["samuel f. b. morse", "samuel finley breese morse", "samuel morse"],
    "morsel": ["bit", "bite"],
    "mortal sin": ["deadly sin"],
    "mortar": ["howitzer", "trench mortar"],
    "mortarboard": ["hawk"],
    "mortgagee": ["mortgage holder"],
    "mortgagor": ["mortgager"],
    "mortice": ["mortise"],
    "mortician": ["funeral director", "funeral undertaker", "undertaker"],
    "mortify": ["crucify", "subdue"],
    "mortimer": ["roger de mortimer"],
    "mortise": ["mortice"],
    "mortise joint": ["mortise-and-tenon joint"],
    "mortmain": ["dead hand"],
    "morton": ["ferdinand joseph la menthe morton", "jelly roll morton"],
    "morus": ["genus morus"],
    "mosaic": ["arial mosaic", "photomosaic"],
    "mosaic gold": ["stannic sulfide"],
    "mosaic law": ["law of moses"],
    "mosander": ["carl gustaf mossander"],
    "moschus": ["genus moschus"],
    "moscow": ["capital of the russian federation", "russian capital"],
    "moses": ["anna mary robertson moses", "grandma moses"],
    "mosquito fern": ["azolla caroliniana", "carolina pond fern", "floating fern"],
    "mosquitofish": ["gambusia affinis"],
    "moss campion": ["silene acaulis"],
    "moss green": ["mosstone"],
    "moss pink": ["dwarf phlox", "moss phlox", "mountain phlox", "phlox subulata"],
    "moss-grown": ["mossy"],
    "mossbauer": ["rudolf ludwig mossbauer"],
    "mossy saxifrage": ["saxifraga hypnoides"],
    "most": ["to the highest degree"],
    "most valuable player": ["mvp"],
    "mot": ["ministry of transportation test", "mot test"],
    "motacilla": ["genus motacilla"],
    "motacillidae": ["family motacillidae"],
    "moth bean": ["phaseolus aconitifolius", "vigna aconitifolia"],
    "moth miller": ["miller"],
    "moth mullein": ["verbascum blattaria"],
    "moth orchid": ["moth plant"],
    "moth-eaten": ["ratty", "shabby", "tatty"],
    "mothball": ["camphor ball"],
    "mother": ["fuss", "overprotect"],
    "mother carey's chicken": ["mother carey's hen", "oceanites oceanicus"],
    "mother hubbard": ["muumuu"],
    "mother lode": ["champion lode"],
    "mother tongue": ["first language", "maternal language"],
    "mother's boy": ["mama's boy", "mamma's boy"],
    "mother-in-law's tongue": ["sansevieria trifasciata", "snake plant"],
    "mother-naked": ["in one's birthday suit", "in your birthday suit", "naked as the day one was born", "naked as the day you were born"],
    "mother-of-pearl": ["nacre"],
    "motherhood": ["maternity"],
    "motherliness": ["maternal quality", "maternalism", "maternity"],
    "motherwell": ["robert motherwell"],
    "motherwort": ["leonurus cardiaca"],
    "mothproof": ["moth-resistant"],
    "motif": ["motive"],
    "motion": ["question"],
    "motion sickness": ["kinetosis"],
    "motion-picture camera": ["cine-camera", "movie camera"],
    "motion-picture film": ["cine-film", "movie film"],
    "motionlessness": ["lifelessness", "stillness"],
    "motivate": ["actuate", "incite", "move", "prompt", "propel"],
    "motivation": ["motivating"],
    "motivative": ["motivating", "motive"],
    "motive": ["motor"],
    "motiveless": ["unprovoked", "wanton"],
    "motley": ["parti-color"],
    "motmot": ["momot"],
    "motor aphasia": ["ataxic aphasia", "broca's aphasia", "expressive aphasia", "nonfluent aphasia"],
    "motor area": ["excitable area", "motor cortex", "motor region", "rolando's area"],
    "motor fiber": ["efferent fiber"],
    "motor hotel": ["court", "motor inn", "motor lodge", "tourist court"],
    "motor memory": ["muscle memory"],
    "motor nerve": ["efferent", "efferent nerve"],
    "motor neuron": ["efferent neuron", "motoneuron", "motor nerve fiber"],
    "motor scooter": ["scooter"],
    "motor vehicle": ["automotive vehicle"],
    "motorbike": ["cycle", "motorcycle"],
    "motorboat": ["powerboat"],
    "motorcycle": ["bike"],
    "motorcycle cop": ["motorcycle policeman", "speed cop"],
    "motorist": ["automobilist"],
    "motorization": ["motorisation"],
    "motorized": ["motored", "motorised"],
    "mott": ["lucretia coffin mott"],
    "mottle": ["blotch", "streak"],
    "motto": ["catchword", "shibboleth", "slogan"],
    "mouflon": ["moufflon", "ovis musimon"],
    "moulmein": ["mawlamyine"],
    "mound": ["hill", "pitcher's mound"],
    "mount": ["put on"],
    "mount saint helens": ["mount st. helens", "mt. st. helens"],
    "mountain": ["mount"],
    "mountain ash": ["eucalyptus regnans"],
    "mountain avens": ["dryas octopetala"],
    "mountain beaver": ["aplodontia rufa", "sewellel"],
    "mountain bike": ["all-terrain bike", "off-roader"],
    "mountain bladder fern": ["cystopteris montana"],
    "mountain chinchilla": ["mountain viscacha"],
    "mountain climbing": ["mountaineering"],
    "mountain devil": ["moloch horridus", "spiny lizard"],
    "mountain ebony": ["bauhinia variegata", "orchid tree"],
    "mountain fern": ["dryopteris oreopteris", "oreopteris limbosperma"],
    "mountain four o'clock": ["mirabilis oblongifolia"],
    "mountain goat": ["oreamnos americanus", "rocky mountain goat"],
    "mountain gorilla": ["gorilla gorilla beringei"],
    "mountain heath": ["bryanthus taxifolius", "phyllodoce caerulea"],
    "mountain hemlock": ["black hemlock", "tsuga mertensiana"],
    "mountain hollyhock": ["iliamna acerifolia", "iliamna ruvularis"],
    "mountain lady's slipper": ["cypripedium montanum"],
    "mountain laurel": ["american laurel", "calico bush", "kalmia latifolia", "wood laurel"],
    "mountain lily": ["lilium auratum"],
    "mountain male fern": ["dryopteris oreades"],
    "mountain maple": ["acer spicatum", "mountain alder"],
    "mountain nyala": ["tragelaphus buxtoni"],
    "mountain pride": ["penstemon newberryi"],
    "mountain quail": ["mountain partridge", "oreortyx picta palmeri"],
    "mountain rice": ["indian millet", "oryzopsis hymenoides", "silk grass", "silkgrass"],
    "mountain rimu": ["dacridium laxifolius", "lepidothamnus laxifolius"],
    "mountain rose": ["rosa pendulina"],
    "mountain sandwort": ["arenaria groenlandica", "mountain daisy", "mountain starwort"],
    "mountain skink": ["eumeces callicephalus"],
    "mountain spleenwort": ["asplenium montanum"],
    "mountain swamp gum": ["eucalyptus camphora"],
    "mountain time": ["mountain standard time", "mst"],
    "mountain zebra": ["equus zebra zebra"],
    "mountaineer": ["mountain climber"],
    "mountainside": ["versant"],
    "mountebank": ["charlatan"],
    "mounter": ["climber"],
    "mourner": ["griever", "lamenter", "sorrower"],
    "mournful": ["plaintive"],
    "mournfulness": ["ruthfulness", "sorrowfulness"],
    "mourning": ["bereavement"],
    "mourning cloak": ["camberwell beauty", "mourning cloak butterfly", "nymphalis antiopa"],
    "mourning dove": ["zenaidura macroura"],
    "mouse": ["computer mouse"],
    "mouse nest": ["mouse's nest"],
    "mouse-ear chickweed": ["chickweed", "clammy chickweed", "mouse ear", "mouse eared chickweed"],
    "mouse-ear hawkweed": ["hieracium pilocella", "pilosella officinarum"],
    "mousepad": ["mouse mat"],
    "mousetrap": ["trap play"],
    "mousse": ["gel"],
    "mousy": ["mousey"],
    "mouth": ["oral cavity", "oral fissure", "rima oris"],
    "mouth-watering": ["savory", "savoury"],
    "mouthpiece": ["mouth"],
    "mouton": ["mutton"],
    "movability": ["movableness"],
    "movable": ["moveable", "transferable", "transferrable", "transportable"],
    "movable feast": ["moveable feast"],
    "move": ["displace"],
    "move involuntarily": ["move reflexively"],
    "move over": ["ease up", "give", "give way", "yield"],
    "moved": ["affected", "stirred", "touched"],
    "movement": ["front", "social movement"],
    "mover": ["moving company", "public mover", "removal company", "removal firm"],
    "movie": ["film", "flick", "motion picture", "motion-picture show", "moving picture", "moving-picture show", "pic", "picture", "picture show"],
    "movie projector": ["cine projector", "film projector"],
    "moviegoer": ["motion-picture fan"],
    "moviemaking": ["film making", "movie making"],
    "mow": ["cut down"],
    "mown": ["cut"],
    "moynihan": ["daniel patrick moynihan"],
    "mozambique": ["mocambique", "republic of mozambique"],
    "mozart": ["wolfgang amadeus mozart"],
    "mozartian": ["mozartean"],
    "mr": ["mr. moto"],
    "mrs": ["mrs."],
    "ms": ["ms."],
    "ms-dos": ["microsoft disk operating system"],
    "msasa": ["brachystegia speciformis"],
    "mubarak": ["hosni mubarak"],
    "much": ["a great deal", "often"],
    "much as": ["very much like"],
    "muckraker": ["mudslinger"],
    "mucky": ["muddy"],
    "mucocutaneous leishmaniasis": ["american leishmaniasis", "leishmaniasis americana", "nasopharyngeal leishmaniasis", "new world leishmaniasis"],
    "mucoid": ["mucoidal"],
    "mucoraceae": ["family mucoraceae"],
    "mucorales": ["order mucorales"],
    "mucous": ["mucose"],
    "mucous membrane": ["mucosa"],
    "mucus": ["mucous secretion"],
    "mud": ["clay"],
    "mud midget": ["bogmat", "wolffiella gladiata"],
    "mud puppy": ["necturus maculosus"],
    "muddle": ["puddle"],
    "muddy": ["muddy up"],
    "mudguard": ["splash guard", "splash-guard"],
    "mudskipper": ["mudspringer"],
    "mudwrestle": ["mud-wrestle"],
    "muezzin": ["muadhdhin", "muazzin"],
    "muffin": ["gem"],
    "muffle": ["damp", "dampen", "dull", "mute", "tone down"],
    "mug": ["mugful"],
    "mug file": ["mug book"],
    "mug shot": ["mugshot"],
    "muggy": ["steamy", "sticky"],
    "mugil": ["genus mugil"],
    "mugilidae": ["family mugilidae"],
    "mugiloidea": ["suborder mugiloidea"],
    "mugwump": ["fencesitter", "independent"],
    "muhammad": ["elijah muhammad"],
    "muhammadan": ["mohammedan"],
    "muharram": ["moharram", "muharrum"],
    "muhlenbergia": ["genus muhlenbergia"],
    "muir": ["john muir"],
    "mujahidin": ["mujahadeen", "mujahadein", "mujahadin", "mujahedeen", "mujahedin", "mujahideen"],
    "mujahidin-e khalq organization": ["mek", "mko", "people's mujahidin of iran"],
    "mukalla": ["al-mukalla"],
    "mulberry": ["mulberry tree"],
    "mule": ["scuff"],
    "mule deer": ["burro deer", "odocoileus hemionus"],
    "mule fat": ["baccharis viminea"],
    "mule's ears": ["wyethia amplexicaulis"],
    "muleteer": ["mule driver", "mule skinner", "skinner"],
    "mullah": ["mollah", "mulla"],
    "mullah omar": ["mullah mohammed omar"],
    "mullein": ["flannel leaf", "velvet plant"],
    "mullein pink": ["dusty miller", "gardener's delight", "lychnis coronaria", "rose campion"],
    "muller": ["paul hermann muller"],
    "mullet": ["gray mullet", "grey mullet"],
    "mullidae": ["family mullidae"],
    "mulligan stew": ["irish burgoo", "mulligan"],
    "mulloidichthys": ["genus mulloidichthys"],
    "mulloway": ["jewfish", "sciaena antarctica"],
    "mullus": ["genus mullus"],
    "multi-seeded": ["several-seeded"],
    "multiengine airplane": ["multiengine plane"],
    "multiethnic": ["multi-ethnic"],
    "multiflora": ["baby rose", "japanese rose", "multiflora rose", "rosa multiflora"],
    "multifocal lens implant": ["multifocal iol"],
    "multilateral": ["many-sided"],
    "multimedia": ["multimedia system"],
    "multinational": ["transnational"],
    "multiphase": ["polyphase"],
    "multiple regression": ["multiple correlation"],
    "multiple sclerosis": ["disseminated multiple sclerosis", "disseminated sclerosis", "ms"],
    "multiplication": ["times"],
    "multiplicative inverse": ["reciprocal"],
    "multiplier": ["multiplier factor"],
    "multiply": ["manifold"],
    "multiprocessing": ["parallel processing"],
    "multiprogramming": ["concurrent execution"],
    "multistage rocket": ["step rocket"],
    "multistory": ["multistorey", "multistoried"],
    "multitude": ["concourse", "throng"],
    "multivalent": ["multi-valued"],
    "multivitamin": ["multivitamin pill"],
    "mum": ["silent"],
    "mumbai": ["bombay"],
    "mumble": ["gum"],
    "mumblety-peg": ["mumble-the-peg"],
    "mumbling": ["gumming"],
    "mummery": ["flummery"],
    "mummichog": ["fundulus heteroclitus"],
    "mummify": ["dry up"],
    "mumps": ["epidemic parotitis"],
    "munch": ["edvard munch"],
    "munchausen's syndrome": ["munchausen syndrome"],
    "munchhausen": ["baron munchausen", "karl friedrich hieronymus von munchhausen", "munchausen"],
    "mundane": ["terrestrial"],
    "mundanely": ["terrestrially"],
    "mung": ["golden gram", "green gram", "mung bean", "phaseolus aureus", "vigna radiata"],
    "munich": ["muenchen"],
    "munich beer": ["munchener"],
    "munificence": ["largess", "largesse", "magnanimity", "openhandedness"],
    "munition": ["ordnance", "ordnance store"],
    "munitions industry": ["arms industry"],
    "munj": ["munja", "saccharum bengalense", "saccharum munja"],
    "munro": ["h. h. munro", "hector hugh munro", "saki"],
    "muntiacus": ["genus muntiacus"],
    "muntingia": ["genus muntingia"],
    "muntjac": ["barking deer"],
    "muon": ["mu-meson", "negative muon"],
    "muraenidae": ["family muraenidae"],
    "mural": ["wall painting"],
    "murder": ["bump off", "dispatch", "hit", "off", "polish off", "remove", "slay"],
    "murder charge": ["murder indictment"],
    "murderer": ["liquidator", "manslayer"],
    "murdoch": ["keith rupert murdoch", "rupert murdoch"],
    "muridae": ["family muridae"],
    "murillo": ["bartolome esteban murillo"],
    "murine typhus": ["endemic typhus", "rat typhus", "urban typhus"],
    "murky": ["mirky"],
    "murmur": ["croak", "gnarl", "grumble", "mutter"],
    "murmur vowel": ["murmur"],
    "murmuring": ["susurrant", "whispering"],
    "murmurous": ["rustling", "soughing", "susurrous"],
    "muroidea": ["superfamily muroidea"],
    "murphy's law": ["sod's law"],
    "murray": ["george gilbert aime murphy", "gilbert murray"],
    "murrow": ["edward r. murrow", "edward roscoe murrow"],
    "murrumbidgee": ["murrumbidgee river"],
    "mus": ["genus mus"],
    "musa": ["genus musa"],
    "musaceae": ["banana family", "family musaceae"],
    "musales": ["order musales"],
    "musca": ["genus musca"],
    "musca volitans": ["floater", "muscae volitantes", "spots"],
    "muscadine": ["vitis rotundifolia"],
    "muscardinus": ["genus muscardinus"],
    "muscari": ["genus muscari"],
    "muscat": ["muskat"],
    "muscicapa": ["genus muscicapa"],
    "muscicapidae": ["family muscicapidae"],
    "muscidae": ["family muscidae"],
    "muscivora": ["genus muscivora"],
    "muscle": ["musculus"],
    "muscle cell": ["muscle fiber", "muscle fibre"],
    "muscleman": ["muscle"],
    "muscoidea": ["superfamily muscoidea"],
    "muscovy duck": ["cairina moschata", "musk duck"],
    "muscular dystrophy": ["dystrophy"],
    "muscular structure": ["muscle system", "musculature"],
    "muscular tonus": ["muscle tone"],
    "musculophrenic artery": ["arteria musculophrenica"],
    "musculophrenic vein": ["vena musculophrenica"],
    "musculus adductor magnus": ["great adductor muscle"],
    "musculus biceps femoris": ["femoral biceps"],
    "muser": ["muller", "ponderer", "ruminator"],
    "musette": ["shepherd's pipe"],
    "musgu": ["mulwi", "munjuk"],
    "mush": ["cornmeal mush"],
    "mushiness": ["pulpiness"],
    "mushroom": ["mushroom cloud", "mushroom-shaped cloud"],
    "musial": ["stan musial", "stan the man", "stanley frank musial"],
    "music": ["euphony"],
    "music box": ["musical box"],
    "music department": ["department of music"],
    "music genre": ["genre", "musical genre", "musical style"],
    "music hall": ["vaudeville theater", "vaudeville theatre"],
    "music paper": ["score paper"],
    "music school": ["school of music"],
    "music stand": ["music rack"],
    "music stool": ["piano stool"],
    "musical": ["musical comedy", "musical theater"],
    "musical arrangement": ["arrangement"],
    "musical chairs": ["going to jerusalem"],
    "musical composition": ["composition", "opus", "piece", "piece of music"],
    "musical instrument": ["instrument"],
    "musical instrument digital interface": ["midi"],
    "musical organization": ["musical group", "musical organisation"],
    "musical soiree": ["soiree musicale"],
    "musicality": ["musicalness"],
    "musician": ["instrumentalist", "player"]
}
