synonyms = {
    "artificial respiration": ["breathing", "emergency procedure", "external respiration", "respiration", "ventilation"],
    "artificial skin": ["covering"],
    "artificiality": ["pretence", "pretense", "pretension", "staginess", "theatricality", "unnaturalness"],
    "artificially": ["by artificial means", "unnaturally"],
    "artillery": ["army unit", "artillery unit", "battery"],
    "artillery fire": ["cannon fire", "cannonade", "drumfire", "fire", "firing", "high-angle fire", "mortar fire", "zone fire"],
    "artillery plant": ["nettle", "pilea microphylla"],
    "artillery shell": ["shell"],
    "artilleryman": ["cannoneer", "gunner", "machine gunner", "man", "military man", "military personnel", "serviceman"],
    "artiodactyl": ["artiodactylous", "even-toed"],
    "artiodactyla": ["animal order", "order artiodactyla"],
    "artisan's lien": ["lien"],
    "artist": ["carver", "classic", "classicist", "constructivist", "creative person", "creator", "decorator", "draftsman", "drawer", "etcher", "expressionist", "graphic artist", "illustrator", "indiana", "lensman", "maestro", "master", "minimalist", "modernist", "musician", "ornamentalist", "painter", "photographer", "pre-raphaelite", "printmaker", "pyrographer", "robert indiana", "romantic", "romanticist", "sculptor", "sculpturer", "statue maker", "stylist", "surrealist", "symbolist"],
    "artist's loft": ["artist's workroom", "atelier", "loft"],
    "artist's model": ["model", "poser", "sitter"],
    "artist's workroom": ["artist's loft", "atelier", "studio"],
    "artiste": ["performer", "performing artist"],
    "artistic": [],
    "artistic movement": ["abstract expressionism", "action painting", "art deco", "art movement", "art nouveau", "ash can", "ashcan school", "avant-garde", "constructivism", "cubism", "dada", "dadaism", "deco", "eight", "expressionism", "fauvism", "front", "futurism", "hudson river school", "imagism", "impressionism", "lake poets", "luminism", "minimal art", "minimalism", "movement", "naturalism", "neoromanticism", "new wave", "nouvelle vague", "pointillism", "pop art", "realism", "reductivism", "romantic realism", "secession", "sezession", "social movement", "suprematism", "surrealism", "symbolism", "van", "vanguard"],
    "artistic style": ["baroque", "baroqueness", "classical style", "classicalism", "classicism", "fashion", "high renaissance", "idiom", "manner", "mode", "neoclassicism", "order", "rococo", "romantic movement", "romanticism", "style", "treatment", "way"],
    "artistically": [],
    "artless": [],
    "artlessly": ["crudely", "inexpertly"],
    "artlessness": ["ingenuousness", "innocence", "innocency", "naiveness", "naivete", "naivety", "naturalness"],
    "artocarpus": ["dicot genus", "genus artocarpus", "magnoliopsid genus"],
    "artois": [],
    "arts and crafts": ["art", "artistic creation", "artistic production", "handicraft"],
    "artsy-craftsy": ["arty-crafty"],
    "artwork": ["art", "drawing", "graphics", "illustration", "nontextual matter", "visual communication"],
    "arty": [],
    "aruba": [],
    "arulo": ["artificial language"],
    "arum": ["amylum", "starch"],
    "arundinaceous": [],
    "arundinaria": ["genus arundinaria", "liliopsid genus", "monocot genus"],
    "arundo": ["genus arundo", "liliopsid genus", "monocot genus"],
    "aruru": [],
    "arvicola": ["genus arvicola", "mammal genus"],
    "aryan": ["caucasian", "white", "white person"],
    "arytenoid": ["arytaenoid", "arytenoid cartilage", "cartilage", "gristle"],
    "as far as possible": ["as much as possible"],
    "as follows": [],
    "as it is": [],
    "as it were": ["so to speak"],
    "as needed": ["as required", "prn", "pro re nata"],
    "as the crow flies": [],
    "as usual": [],
    "as we say": ["so to speak"],
    "asafetida": ["asafoetida", "natural resin"],
    "asahikawa": [],
    "asama": ["mount asama"],
    "asana": ["attitude", "matsyendra", "position", "posture"],
    "asanga": [],
    "asap": [],
    "asarabacca": ["asarum europaeum", "wild ginger"],
    "asarh": ["asadha", "hindu calendar month"],
    "asarum": ["dicot genus", "genus asarum", "magnoliopsid genus"],
    "asbat al-ansar": ["band of partisans"],
    "asbestos": ["amphibole", "chrysotile", "tremolite"],
    "asbestos abatement": ["abatement of a nuisance", "nuisance abatement"],
    "asbestosis": ["pneumoconiosis", "pneumonoconiosis"],
    "ascaphidae": ["amphibian family", "family ascaphidae"],
    "ascaphus": ["amphibian genus", "genus ascaphus"],
    "ascariasis": ["infestation"],
    "ascaridae": ["family ascaridae", "worm family"],
    "ascaridia": ["genus ascaridia", "worm genus"],
    "ascaris": ["genus ascaris", "worm genus"],
    "ascend": ["date back", "date from", "go back"],
    "ascendable": ["ascendible", "climbable"],
    "ascendant": ["ascendance", "ascendancy", "ascendence", "ascendency", "ascendent", "control", "dominance"],
    "ascender": ["climber", "mounter", "mover"],
    "ascending": [],
    "ascending aorta": ["aorta"],
    "ascending artery": ["arteria", "arteria ascendens", "arterial blood vessel", "artery"],
    "ascending colon": ["colon"],
    "ascending node": ["node"],
    "ascension": ["ascension day", "ascension of the lord", "holy day of obligation"],
    "ascensional": [],
    "ascent": ["acclivity", "climb", "incline", "raise", "rise", "side", "slope", "upgrade", "uphill"],
    "ascertain": ["discover", "find out", "get a line", "get wind", "get word", "hear", "learn", "pick up", "price", "see"],
    "ascertainable": ["discoverable"],
    "ascertained": ["discovered", "observed"],
    "ascetic": ["ascetical"],
    "ascetically": [],
    "asceticism": ["doctrine", "ism", "philosophical system", "philosophy", "school of thought"],
    "asch": ["shalom asch", "sholem asch", "sholom asch"],
    "ascidiaceae": ["class", "class ascidiaceae"],
    "ascidian": ["sea squirt", "tunicate", "urochord", "urochordate"],
    "ascidian tadpole": ["larva"],
    "ascii character": ["ascii control character", "character", "control character", "grapheme", "graphic symbol"],
    "ascii character set": [],
    "ascii text file": ["document", "source code", "text file"],
    "ascites": ["pathology"],
    "ascitic": [],
    "asclepiad": ["herb", "herbaceous plant"],
    "asclepiadaceae": ["dicot family", "family asclepiadaceae", "magnoliopsid family", "milkweed family"],
    "asclepiadaceous": [],
    "asclepias": ["dicot genus", "genus asclepias", "magnoliopsid genus"],
    "ascocarp": ["apothecium", "ascoma", "cleistocarp", "cleistothecium", "fruiting body", "perithecium"],
    "ascocarpous": [],
    "ascolichen": ["lichen"],
    "ascoma": ["ascocarp"],
    "ascomycete": ["ascomycetous fungus", "clavicipitaceae", "cup fungus", "discomycete", "fungus", "geglossaceae", "grainy club mushrooms", "sarcosomataceae"],
    "ascomycetes": ["class", "class ascomycetes"],
    "ascomycetous": [],
    "ascomycota": ["ascomycotina", "division", "subdivision ascomycota", "subdivision ascomycotina"],
    "ascophyllum": ["genus ascophyllum", "protoctist genus"],
    "ascospore": ["spore"],
    "ascosporic": ["ascosporous"],
    "ascot": ["cravat"],
    "ascribable": ["due", "imputable", "referable"],
    "ascus": ["reproductive structure"],
    "asepsis": ["antisepsis", "sanitariness", "sterileness", "sterility"],
    "aseptic": ["sterile"],
    "asexual": ["nonsexual"],
    "asexual reproduction": ["agamogenesis", "apomixis", "blastogenesis", "budding", "fission", "fissiparity", "gemmation", "monogenesis", "parthenogenesis", "parthenogeny", "pullulation", "reproduction", "sporulation", "virgin birth"],
    "asexuality": ["physiological property", "sexlessness"],
    "asexually": [],
    "asgard": ["fictitious place", "imaginary place", "mythical place"],
    "ash": ["alter", "change", "modify"],
    "ash can": ["art movement", "artistic movement", "ashcan school"],
    "ash grey": ["ash gray", "gray", "grayness", "grey", "greyness", "silver", "silver gray", "silver grey"],
    "ash wednesday": ["christian holy day"],
    "ash-blonde": ["platinum-blonde", "towheaded"],
    "ash-grey": ["ash-gray", "ashy"],
    "ash-key": ["seed"],
    "ash-pan": ["receptacle"],
    "ashamed": [],
    "ashamedly": [],
    "ashcake": ["ash cake", "corn tash", "cornbread"],
    "ashcan": ["ash bin", "ash-bin", "ashbin", "bin", "dustbin", "garbage can", "trash barrel", "trash bin", "trash can", "wastebin"],
    "ashcan school": ["art movement", "artistic movement", "eight", "school"],
    "ashe": ["arthur ashe", "arthur robert ashe"],
    "ashen": [],
    "asheville": [],
    "ashkenazi": ["hebrew", "israelite", "jew"],
    "ashkhabad": ["capital of turkmenistan"],
    "ashlar": ["building block", "stone"],
    "ashore": [],
    "ashram": ["retreat"],
    "ashton": ["sir frederick ashton"],
    "ashtray": ["receptacle"],
    "ashur": ["ashir"],
    "ashurbanipal": ["assurbanipal", "asurbanipal"],
    "asia": [],
    "asia minor": ["anatolia"],
    "asian": ["afghan", "afghanistani", "altaic", "annamese", "armenian", "asiatic", "bangladeshi", "bengali", "bhutanese", "bhutani", "burmese", "byzantine", "cambodian", "chinese", "coolie", "cooly", "dardan", "dardanian", "denizen", "dweller", "east indian", "eurasian", "habitant", "hindoo", "hindu", "hindustani", "hmong", "iberian", "indian", "indonesian", "indweller", "inhabitant", "iraki", "irani", "iranian", "iraqi", "israeli", "israelite", "japanese", "jordanian", "kampuchean", "kazakhstani", "korean", "kurd", "kuwaiti", "lao", "laotian", "lebanese", "malay", "malayan", "malaysian", "maldivan", "maldivian", "miao", "mongoloid", "nepalese", "nepali", "nipponese", "oriental", "oriental person", "pakistani", "parthian", "persian", "person of color", "person of colour", "sherpa", "siamese", "singaporean", "singhalese", "sinhalese", "sri lankan", "syrian", "tadzhik", "tai", "taiwanese", "tajik", "thai", "tibetan", "timorese", "trojan", "turki", "vietnamese"],
    "asian american": ["american"],
    "asian black grouse": ["black grouse", "lyrurus mlokosiewiczi"],
    "asian coral snake": ["coral snake", "old world coral snake"],
    "asian country": ["asian nation", "country", "land", "state"],
    "asian crocodile": ["crocodile", "crocodylus porosus"],
    "asian horseshoe crab": ["arthropod"],
    "asian influenza": ["asiatic flu", "flu", "grippe", "influenza"],
    "asian longhorned beetle": ["anoplophora glabripennis", "beetle"],
    "asian russia": [],
    "asian tiger mosquito": ["aedes albopictus", "mosquito"],
    "asian wild ox": ["bibos frontalis", "bibos gaurus", "gaur", "gayal", "mithan", "ox", "wild ox"],
    "asiatic black bear": ["bear", "black bear", "selenarctos thibetanus", "ursus thibetanus"],
    "asiatic flying squirrel": ["flying cat", "flying marmot", "petaurista petaurista", "squirrel", "taguan"],
    "asiatic shrew mole": ["shrew mole", "uropsilus soricipes"],
    "asiatic sweetleaf": ["flowering shrub", "sapphire berry", "symplocus paniculata"],
    "aside": ["actor's line", "speech", "words"],
    "asilidae": ["arthropod family", "family asilidae"],
    "asimina": ["genus asimina", "magnoliid dicot genus"],
    "asimov": ["isaac asimov"],
    "asin": ["asvina", "hindu calendar month"],
    "asinine": ["fatuous", "inane", "mindless", "vacuous"],
    "asininity": ["folly", "foolishness", "unwiseness"],
    "asio": ["bird genus", "genus asio"],
    "ask": ["demand"],
    "ask for it": ["ask for trouble", "hang in", "hang on", "hold on", "persevere", "persist"],
    "ask jeeves": [],
    "ask out": ["bespeak", "call for", "invite out", "quest", "request", "take out"],
    "askance": [],
    "askew": ["awry", "skew-whiff"],
    "asking price": ["damage", "list price", "offer price", "price", "selling price", "terms", "upset price"],
    "asl": ["american sign language", "sign language", "signing"],
    "aslant": [],
    "asleep": [],
    "asmara": ["asmera"],
    "asocial": [],
    "asp": ["asp viper", "viper", "vipera aspis"],
    "aspalathus": ["genus aspalathus", "rosid dicot genus"],
    "asparagaceae": ["family asparagaceae", "liliid monocot family"],
    "asparaginase": ["antineoplastic", "antineoplastic drug", "cancer drug", "elspar"],
    "asparagine": ["amino acid", "aminoalkanoic acid"],
    "asparagus": ["asparagus officinales", "edible asparagus", "herb", "herbaceous plant"],
    "asparagus bean": ["legume", "leguminous plant", "vigna sesquipedalis", "vigna unguiculata sesquipedalis", "yard-long bean"],
    "asparagus bed": ["bed"],
    "asparagus fern": ["asparagus plumosus", "asparagus setaceous", "herb", "herbaceous plant"],
    "aspartame": ["sweetener", "sweetening"],
    "aspartic acid": ["amino acid", "aminoalkanoic acid"],
    "aspect": ["durative", "durative aspect", "grammatical relation", "inchoative", "inchoative aspect", "iterative", "iterative aspect", "perfective", "perfective aspect"],
    "aspect ratio": ["ratio"],
    "aspectual": [],
    "aspen": ["american aspen", "american quaking aspen", "big-toothed aspen", "bigtooth aspen", "bigtoothed aspen", "canadian aspen", "european quaking aspen", "large tooth aspen", "large-toothed aspen", "poplar", "poplar tree", "populus grandidentata", "populus tremula", "populus tremuloides", "quaking aspen"],
    "asper": ["turkish monetary unit"],
    "asperger's syndrome": ["disturbance", "folie", "mental disorder", "mental disturbance", "psychological disorder"],
    "aspergill": ["aspersorium", "device"],
    "aspergillaceae": ["family aspergillaceae", "fungus family"],
    "aspergillosis": ["animal disease", "brooder pneumonia"],
    "aspergillus": ["fungus genus", "genus aspergillus"],
    "aspergillus fumigatus": ["fungus"],
    "asperity": ["difficultness", "difficulty", "grimness", "hardship", "rigor", "rigorousness", "rigour", "rigourousness", "severeness", "severity", "sternness"],
    "aspersion": ["depreciation", "derogation", "disparagement", "ethnic slur", "slur"],
    "aspersorium": ["basin"],
    "asperula": ["asterid dicot genus", "genus asperula"],
    "asphalt": ["pave"],
    "asphaltic": [],
    "aspheric": ["aspherical"],
    "asphodel": ["asphodeline lutea", "jacob's rod", "king's spear", "liliaceous plant", "yellow asphodel"],
    "asphodelaceae": ["family asphodelaceae", "liliid monocot family"],
    "asphodeline": ["genus asphodeline", "liliid monocot genus"],
    "asphodelus": ["genus asphodelus", "liliid monocot genus"],
    "asphyxia": ["physical condition", "physiological condition", "physiological state"],
    "asphyxiated": [],
    "asphyxiating": [],
    "aspic": ["gelatin", "jelly"],
    "aspidelaps": ["genus aspidelaps", "reptile genus"],
    "aspidiotus": ["arthropod genus", "genus aspidiotus"],
    "aspidistra": ["aspidistra elatio", "bar-room plant", "cast-iron plant", "herb", "herbaceous plant"],
    "aspidophoroides": ["fish genus", "genus aspidophoroides"],
    "aspirant": ["applicant", "applier", "aspirer", "hopeful", "wannabe", "wannabee"],
    "aspirate": ["draw out", "remove", "suck out", "take", "take away", "withdraw"],
    "aspiration": ["articulation"],
    "aspiration pneumonia": ["bronchial pneumonia", "bronchopneumonia"],
    "aspirator": ["pump"],
    "aspirin": ["acetylsalicylic acid", "analgesic", "anodyne", "aspirin powder", "bayer", "buffered aspirin", "bufferin", "empirin", "enteric-coated aspirin", "headache powder", "pain pill", "painkiller", "salicylate", "st. joseph"],
    "aspirin powder": ["acetylsalicylic acid", "aspirin", "bayer", "empirin", "headache powder", "powder", "st. joseph"],
    "aspleniaceae": ["family aspleniaceae", "fern family"],
    "asplenium": ["fern genus", "genus asplenium"],
    "ass": ["fool", "muggins", "sap", "saphead", "tomfool"],
    "assail": ["assault", "attack", "bait", "beset", "blindside", "bulldog", "desecrate", "dishonor", "dishonour", "jump", "molest", "outrage", "profane", "rape", "ravish", "reassail", "rush", "savage", "set", "set on", "set upon", "sic", "violate"],
    "assailability": ["vulnerability"],
    "assailable": ["open", "undefendable", "undefended"],
    "assam": [],
    "assamese": ["indian"],
    "assassin": ["moslem", "muslim"],
    "assassin bug": ["arilus cristatus", "big bedbug", "cone-nosed bug", "conenose", "conenose bug", "heteropterous insect", "kissing bug", "reduviid", "wheel bug"],
    "assassinate": ["kill"],
    "assassinated": [],
    "assassination": ["execution", "murder", "slaying"],
    "assault": [],
    "assault gun": ["armored vehicle", "armoured vehicle"],
    "assault rifle": ["assault gun", "automatic", "automatic rifle", "machine rifle"],
    "assaultive": ["attacking"],
    "assay": ["analyse", "analyze", "bioassay", "canvas", "canvass", "examine", "study"],
    "assayer": ["analyst"],
    "assegai": ["assagai", "lance", "shaft", "spear"],
    "assemble": ["gather", "get together", "make"],
    "assembler": ["assembly program", "computer program", "computer programme", "program", "programme"],
    "assemblies of god": ["protestant denomination"],
    "assembly": ["areopagus", "assemblage", "bench", "chamber", "chapter", "council", "court", "coven", "deliberative assembly", "gathering", "general assembly", "judicature", "law-makers", "legislative assembly", "legislative body", "legislature", "sabbat", "states general", "tribunal", "witches' sabbath"],
    "assembly hall": ["auditorium"],
    "assembly language": ["programing language", "programming language"],
    "assembly plant": ["factory", "manufactory", "manufacturing plant", "maquiladora", "mill"],
    "assemblyman": ["representative"],
    "assemblywoman": ["representative"],
    "assent": ["accede", "acquiesce", "agree", "connive"],
    "assenter": ["answerer", "respondent", "responder"],
    "assentient": [],
    "assert": ["acquit", "bear", "behave", "carry", "comport", "conduct", "deport", "put forward"],
    "assert oneself": ["behave", "comport"],
    "asserted": [],
    "asserter": ["affirmer", "asseverator", "avower", "communicator", "declarer", "postulator"],
    "assertion": ["accusation", "affirmation", "asseveration", "averment", "avouchment", "avowal", "charge", "claim", "contention", "declaration", "denial", "disaffirmation", "ipse dixit", "ipsedixitism", "testimony"],
    "assertive": ["self-asserting", "self-assertive"],
    "assertively": [],
    "assertiveness": ["bumptiousness", "cockiness", "forwardness", "positiveness", "positivism", "positivity", "pushiness", "self-assertiveness"],
    "assertiveness training": ["behavior modification", "behavior therapy"],
    "assess": ["bill", "charge"],
    "assessable": [],
    "assessee": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "assessment": ["charge"],
    "asset": ["advantage", "forte", "long suit", "metier", "plus", "quality", "resource", "speciality", "specialty", "strength", "strong point", "strong suit", "vantage"],
    "assets": ["accounts receivable", "amount", "amount of money", "capital", "cash in hand", "credit", "crown jewel", "current assets", "deep pocket", "equity", "finances", "funds", "hole card", "intangible", "intangible asset", "investment", "investment funds", "liquid assets", "material resource", "monetary resource", "overage", "part", "pecuniary resource", "percentage", "portion", "possession", "protection", "quick assets", "receivables", "reserve assets", "resource", "security", "share", "sum", "sum of money", "tax base", "working capital"],
    "asshole": ["bastard", "cocksucker", "dickhead", "disagreeable person", "mother fucker", "motherfucker", "prick", "shit", "sob", "son of a bitch", "unpleasant person", "whoreson"],
    "assibilate": ["sibilate"],
    "assibilation": ["development", "evolution"],
    "assiduity": ["assiduousness", "concentration", "diligence", "engrossment", "industriousness", "industry", "intentness", "singleness"],
    "assiduous": ["sedulous"],
    "assiduously": [],
    "assign": ["administer", "allocate", "allot", "allow", "apportion", "appropriate", "deal", "deal out", "dish out", "dispense", "distribute", "dole out", "earmark", "lot", "mete out", "parcel out", "portion", "reserve", "set aside", "shell out"],
    "assignable": ["conveyable", "negotiable", "transferable", "transferrable"],
    "assignation": ["rendezvous", "tryst"],
    "assigned": [],
    "assignee": ["party", "receiver", "recipient"],
    "assignment": ["instrument", "legal document", "legal instrument", "official document"],
    "assignor": ["party"],
    "assimilable": [],
    "assimilate": ["absorb", "imbibe"],
    "assimilating": ["assimilative", "assimilatory"],
    "assimilation": ["relationship"],
    "assimilative": [],
    "assist": ["abet", "protect", "work"],
    "assistant": ["accomplice", "actor's assistant", "aide", "attendant", "attender", "auxiliary", "bat boy", "birthing coach", "cat's-paw", "chief assistant", "coadjutor", "confederate", "dental assistant", "deputy", "doula", "dresser", "enforcer", "event planner", "facilitator", "fashion model", "flower girl", "foot soldier", "girl friday", "hatchet man", "help", "helper", "instrument", "labor coach", "lieutenant", "man friday", "manakin", "manikin", "mannequin", "mannikin", "model", "monitrice", "paraprofessional", "pawn", "poser", "powder monkey", "prompter", "right-hand man", "secretarial assistant", "secretary", "sidesman", "subordinate", "subsidiary", "supporter", "tender", "theater prompter", "underboss", "underling", "water boy", "waterer", "whipper-in", "worker"],
    "assistant professor": ["prof", "professor"],
    "assisted": ["aided"],
    "assisted suicide": ["physician-assisted suicide", "self-annihilation", "self-destruction", "suicide"],
    "assistive": [],
    "assize": ["ordinance", "regulation"],
    "assizes": ["court", "court of assize", "court of assize and nisi prius", "judicature", "tribunal"],
    "associability": ["associableness", "capability", "capableness"],
    "associable": [],
    "associate": ["cerebrate", "cogitate", "colligate", "connect", "correlate", "free-associate", "have in mind", "identify", "interrelate", "link", "link up", "mean", "relate", "remember", "think", "think of", "tie in"],
    "associate degree": ["aa", "aas", "academic degree", "an", "associate", "associate in applied science", "associate in arts", "associate in nursing", "degree"],
    "associate in applied science": ["aas", "associate", "associate degree"],
    "associate in arts": ["aa", "associate", "associate degree"],
    "associate in nursing": ["an", "associate", "associate degree"],
    "associate professor": ["prof", "professor"],
    "associateship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "association": ["unification", "union"],
    "association area": ["association cortex", "cortical area", "cortical region"],
    "association for the advancement of retired persons": ["aarp", "association"],
    "association of southeast asian nations": ["asean", "association"],
    "associational": [],
    "associationism": ["association theory", "scientific theory"],
    "associative": ["associatory"],
    "assonance": ["rhyme", "rime", "vowel rhyme"],
    "assonant": [],
    "assonate": ["rhyme", "rime"],
    "assortative mating": ["conjugation", "coupling", "mating", "pairing", "sexual union", "union"],
    "assorted": ["various"],
    "assortment": ["accumulation", "aggregation", "alphabet soup", "assemblage", "collection", "farrago", "gallimaufry", "grab bag", "hodgepodge", "hotchpotch", "melange", "mingle-mangle", "miscellanea", "miscellany", "mishmash", "mixed bag", "mixture", "motley", "oddments", "odds and ends", "omnium-gatherum", "potpourri", "ragbag", "range", "salmagundi", "sampler", "selection", "smorgasbord", "variety", "witch's brew", "witches' brew", "witches' broth"],
    "assuasive": ["soothing"],
    "assume": ["adopt", "resume", "take office", "take on", "take over"],
    "assumed": ["false", "fictitious", "fictive", "pretended", "put on", "sham"],
    "assumed name": ["dba", "doing business as", "fictitious name", "name"],
    "assumption": ["assumption of mary", "august 15", "holy day of obligation"],
    "assumptive": ["assuming", "presumptuous"],
    "assur": ["ashur", "asur"],
    "assurance": ["insurance"],
    "assure": ["affirm", "assert", "aver", "avow", "swan", "swear", "tell", "verify"],
    "assured": [],
    "assuredly": [],
    "assurgent": [],
    "assuring": [],
    "assyria": [],
    "assyrian": ["semite"],
    "assyrian akkadian": ["akkadian", "assyrian"],
    "assyrian neo-aramaic": ["aramaic", "assyrian"],
    "assyriology": ["archaeology", "archeology"],
    "astacidae": ["arthropod family", "astacura", "family astacidae"],
    "astacus": ["arthropod genus", "genus astacus"],
    "astaire": ["fred astaire"],
    "astana": ["akmola", "capital of kazakhstan"],
    "astarte": ["ashtoreth"],
    "astasia": ["disability", "disablement", "handicap", "impairment"],
    "astatic": [],
    "astatic coils": ["coil"],
    "astatic galvanometer": ["galvanometer"],
    "astatine": ["at", "atomic number 85", "chemical element", "element", "halogen"],
    "aster": ["annual salt-marsh aster", "aromatic aster", "arrow leaved aster", "aster acuminatus", "aster arenosus", "aster dumosus", "aster ericoides", "aster falcatus", "aster linarifolius", "aster linosyris", "aster novae-angliae", "aster novi-belgii", "aster ptarmicoides", "aster shortii", "aster tripolium", "aster turbinellis", "azure aster", "bog aster", "bushy aster", "calico aster", "crooked-stemmed aster", "eastern silvery aster", "flat-topped white aster", "flower", "goldilocks", "goldilocks aster", "heath aster", "late purple aster", "linosyris vulgaris", "michaelmas daisy", "new england aster", "new york aster", "panicled aster", "perennial salt marsh aster", "prairie aster", "purple-stemmed aster", "rough-leaved aster", "rush aster", "schreiber's aster", "sea aster", "sea starwort", "short's aster", "small white aster", "smooth aster", "southern aster", "starved aster", "stiff aster", "tradescant's aster", "upland white aster", "wavy-leaved aster", "western silvery aster", "white prairie aster", "whorled aster", "willow aster", "wood aster"],
    "astereognosis": ["agnosia", "tactile agnosia"],
    "asteriated": [],
    "asterid dicot family": ["acanthaceae", "acanthus family", "ambrosiaceae", "aster family", "asteraceae", "avicenniaceae", "bignoniaceae", "caprifoliaceae", "compositae", "dicot family", "dipsacaceae", "family acanthaceae", "family ambrosiaceae", "family asteraceae", "family avicenniaceae", "family bignoniaceae", "family caprifoliaceae", "family compositae", "family dipsacaceae", "family gesneriaceae", "family hydrophyllaceae", "family labiatae", "family lamiaceae", "family polemoniaceae", "family rubiaceae", "family scrophulariaceae", "family solanaceae", "family valerianaceae", "family verbenaceae", "figwort family", "foxglove family", "gesneria family", "gesneriaceae", "honeysuckle family", "hydrophyllaceae", "labiatae", "lamiaceae", "madder family", "magnoliopsid family", "mint family", "phlox family", "polemoniaceae", "potato family", "rubiaceae", "scrophulariaceae", "solanaceae", "valerian family", "valerianaceae", "verbena family", "verbenaceae", "vervain family", "waterleaf family"],
    "asterid dicot genus": ["acinos", "acroclinium", "actinomeris", "aegiceras", "agalinis", "agastache", "ageratina", "ajuga", "alsobia", "amberboa", "anacyclus", "anaphalis", "antennaria", "anthemis", "antheropeas", "antirrhinum", "arctium", "arctotis", "argyranthemum", "argyroxiphium", "arnoseris", "asperula", "atropa", "aureolaria", "avicennia", "baccharis", "ballota", "balsamorhiza", "bellis", "besseya", "bidens", "bignonia", "blephilia", "boltonia", "brachycome", "brickellia", "brugmansia", "brunfelsia", "buphthalmum", "cacalia", "calamintha", "callistephus", "calycophyllum", "capsicum", "carduus", "carlina", "carthamus", "castilleia", "castilleja", "centaurea", "centranthus", "cestrum", "chamaemelum", "chelone", "chilopsis", "chiococca", "chrysopsis", "chrysothamnus", "cichorium", "cirsium", "clinopodium", "cnicus", "coffea", "collinsia", "collinsonia", "conoclinium", "conradina", "conyza", "cotula", "craspedia", "crepis", "crescentia", "culver's physic", "culver's root", "culvers physic", "culvers root", "cynara", "cyphomandra", "datura", "delairea", "dendranthema", "dicot genus", "diervilla", "dimorphotheca", "dipsacus", "doronicum", "dracocephalum", "echinacea", "echinops", "elephantopus", "emilia", "emmanthe", "encelia", "enceliopsis", "erigeron", "eriodictyon", "eriophyllum", "eupatorium", "fabiana", "felicia", "galeopsis", "galium", "genus abelia", "genus acanthus", "genus achillea", "genus achimenes", "genus acinos", "genus acroclinium", "genus actinomeris", "genus aegiceras", "genus aeschynanthus", "genus agalinis", "genus agastache", "genus ageratina", "genus ageratum", "genus ajuga", "genus alsobia", "genus amberboa", "genus ambrosia", "genus ammobium", "genus anacyclus", "genus anaphalis", "genus andryala", "genus antennaria", "genus anthemis", "genus antheropeas", "genus antirrhinum", "genus arctium", "genus arctotis", "genus argyranthemum", "genus argyroxiphium", "genus arnica", "genus arnoseris", "genus artemisia", "genus asperula", "genus aster", "genus atropa", "genus aureolaria", "genus avicennia", "genus baccharis", "genus ballota", "genus balsamorhiza", "genus bellis", "genus besseya", "genus bidens", "genus bignonia", "genus blephilia", "genus boltonia", "genus brachycome", "genus brickelia", "genus browallia", "genus brugmansia", "genus brunfelsia", "genus buphthalmum", "genus cacalia", "genus calamintha", "genus calceolaria", "genus calendula", "genus callistephus", "genus calycophyllum", "genus capsicum", "genus carduus", "genus carlina", "genus carthamus", "genus castilleia", "genus castilleja", "genus catalpa", "genus catananche", "genus centaurea", "genus centranthus", "genus cestrum", "genus chaenactis", "genus chamaemelum", "genus chelone", "genus chilopsis", "genus chinchona", "genus chiococca", "genus chrysanthemum", "genus chrysopsis", "genus chrysothamnus", "genus cichorium", "genus cinchona", "genus cirsium", "genus clinopodium", "genus cnicus", "genus coffea", "genus coleus", "genus collinsia", "genus collinsonia", "genus columnea", "genus conoclinium", "genus conradina", "genus conyza", "genus coreopsis", "genus cosmos", "genus cotula", "genus craspedia", "genus crepis", "genus crescentia", "genus cynara", "genus cyphomandra", "genus dahlia", "genus datura", "genus delairea", "genus dendranthema", "genus diervilla", "genus digitalis", "genus dimorphotheca", "genus dipsacus", "genus doronicum", "genus dracocephalum", "genus echinacea", "genus echinops", "genus elephantopus", "genus elsholtzia", "genus emilia", "genus emmanthe", "genus encelia", "genus enceliopsis", "genus engelmannia", "genus episcia", "genus erechtites", "genus erigeron", "genus eriodictyon", "genus eriophyllum", "genus eupatorium", "genus fabiana", "genus felicia", "genus filago", "genus gaillardia", "genus galeopsis", "genus galium", "genus gardenia", "genus gazania", "genus genipa", "genus gerardia", "genus gerbera", "genus gerea", "genus gesneria", "genus glechoma", "genus gloxinia", "genus gnaphalium", "genus graptophyllum", "genus grindelia", "genus gutierrezia", "genus gynura", "genus haastia", "genus hamelia", "genus haplopappus", "genus hazardia", "genus hedeoma", "genus helenium", "genus helianthus", "genus helichrysum", "genus heliopsis", "genus helipterum", "genus heterotheca", "genus hieracium", "genus homogyne", "genus hulsea", "genus hyalosperma", "genus hydrophyllum", "genus hyoscyamus", "genus hypochaeris", "genus hypochoeris", "genus hyssopus", "genus inula", "genus iva", "genus koellia", "genus kohleria", "genus kolkwitzia", "genus krigia", "genus lactuca", "genus lagenophera", "genus lamium", "genus lasthenia", "genus lavandula", "genus layia", "genus leonotis", "genus leontodon", "genus leontopodium", "genus leonurus", "genus lepechinia", "genus leucanthemum", "genus leucogenes", "genus leycesteria", "genus liatris", "genus ligularia", "genus linaria", "genus lindheimera", "genus linnaea", "genus lonas", "genus lonicera", "genus lycium", "genus lycopersicon", "genus lycopersicum", "genus lycopus", "genus machaeranthera", "genus madia", "genus majorana", "genus mandragora", "genus marrubium", "genus matricaria", "genus melampodium", "genus melissa", "genus mentha", "genus micromeria", "genus mikania", "genus mitchella", "genus molucella", "genus monarda", "genus mutisia", "genus nabalus", "genus nauclea", "genus nemophila", "genus nepeta", "genus nicandra", "genus nicotiana", "genus nierembergia", "genus ocimum", "genus olearia", "genus onopordon", "genus onopordum", "genus origanum", "genus othonna", "genus ozothamnus", "genus packera", "genus parthenium", "genus penstemon", "genus pericallis", "genus perilla", "genus petasites", "genus petunia", "genus phacelia", "genus phlomis", "genus pholistoma", "genus physalis", "genus physostegia", "genus picris", "genus pilosella", "genus pinckneya", "genus piqueria", "genus plectranthus", "genus pogostemon", "genus polemonium", "genus prenanthes", "genus prunella", "genus psychotria", "genus pteropogon", "genus pulicaria", "genus pycnanthemum", "genus pyrethrum", "genus raoulia", "genus ratibida", "genus rhodanthe", "genus rosmarinus", "genus rubia", "genus rudbeckia", "genus saintpaulia", "genus salpichroa", "genus salpiglossis", "genus salvia", "genus sambucus", "genus santolina", "genus sanvitalia", "genus sarcocephalus", "genus satureia", "genus satureja", "genus saussurea", "genus scabiosa", "genus schizanthus", "genus scolymus", "genus scopolia", "genus scorzonera", "genus scrophularia", "genus scutellaria", "genus senecio", "genus sericocarpus", "genus seriphidium", "genus serratula", "genus sideritis", "genus silphium", "genus silybum", "genus sinningia", "genus solandra", "genus solanum", "genus solenostemon", "genus solidago", "genus sonchus", "genus sphacele", "genus stachys", "genus stenotus", "genus stevia", "genus stokesia", "genus streptocarpus", "genus streptosolen", "genus symphoricarpos", "genus tagetes", "genus tanacetum", "genus taraxacum", "genus tectona", "genus tetraneuris", "genus teucrium", "genus thunbergia", "genus thymus", "genus tithonia", "genus townsendia", "genus tragopogon", "genus trichostema", "genus trilisa", "genus triostium", "genus tripleurospermum", "genus tussilago", "genus ursinia", "genus valeriana", "genus valerianella", "genus vangueria", "genus verbascum", "genus verbena", "genus verbesina", "genus vernonia", "genus veronica", "genus viburnum", "genus weigela", "genus wyethia", "genus xanthium", "genus xeranthemum", "genus zinnia", "gerbera", "gerea", "glechoma", "gnaphalium", "graptophyllum", "grindelia", "gutierrezia", "gynura", "haastia", "haplopappus", "hazardia", "hedeoma", "helenium", "helichrysum", "helipterum", "heterotheca", "hieracium", "homogyne", "hulsea", "hyalosperma", "hydrophyllum", "hyoscyamus", "hypochaeris", "hypochoeris", "hyssopus", "koellia", "kolkwitzia", "lactuca", "lagenophera", "lamium", "lasthenia", "lavandula", "layia", "leonotis", "leontodon", "leontopodium", "leonurus", "lepechinia", "leucanthemum", "leucogenes", "leycesteria", "liatris", "ligularia", "linaria", "lindheimera", "linnaea", "lonas", "lonicera", "lycium", "lycopersicon", "lycopersicum", "lycopus", "machaeranthera", "madia", "magnoliopsid genus", "majorana", "mandragora", "marrubium", "matricaria", "melampodium", "melissa", "mentha", "micromeria", "mikania", "mitchella", "molucella", "nabalus", "nauclea", "nepeta", "nicandra", "nicotiana", "ocimum", "olearia", "onopordon", "onopordum", "ozothamnus", "packera", "parthenium", "penstemon", "pericallis", "perilla", "petasites", "petunia", "pholistoma", "physalis", "picris", "pilosella", "pinckneya", "piqueria", "pogostemon", "prenanthes", "prunella", "psychotria", "pulicaria", "pycnanthemum", "pyrethrum", "raoulia", "ratibida", "rosmarinus", "rubia", "rudbeckia", "saintpaulia", "salpichroa", "sambucus", "santolina", "sanvitalia", "sarcocephalus", "satureia", "satureja", "saussurea", "scolymus", "scopolia", "scrophularia", "scutellaria", "senecio", "sericocarpus", "seriphidium", "serratula", "sideritis", "silphium", "silybum", "sinningia", "solandra", "solanum", "solenostemon", "solidago", "sonchus", "sphacele", "stachys", "stenotus", "stokesia", "streptosolen", "subgenus calliopsis", "symphoricarpos", "tageteste", "tanacetum", "taraxacum", "tectona", "tetraneuris", "teucrium", "thunbergia", "thymus", "townsendia", "tragopogon", "trichostema", "trilisa", "triostium", "tripleurospermum", "tussilago", "valeriana", "valerianella", "vangueria", "verbascum", "verbesina", "veronicastrum virginicum", "viburnum", "whorlywort", "xanthium"],
    "asteridae": ["class", "subclass asteridae"],
    "asterion": ["craniometric point"],
    "asterisk": ["character", "grapheme", "graphic symbol", "star"],
    "asterisked": ["starred"],
    "asterism": ["star"],
    "asterismal": [],
    "astern": [],
    "asternal": [],
    "asteroid": ["chiron", "minor planet", "planetoid"],
    "asteroid belt": ["belt"],
    "asteroidal": [],
    "asteroidea": ["class", "class asteroidea"],
    "asthenia": ["astheny", "debility", "feebleness", "frailness", "frailty", "infirmity", "valetudinarianism"],
    "asthenic": [],
    "asthenic type": ["body type", "ectomorphy", "somatotype"],
    "asthenosphere": ["layer"],
    "asthma": ["asthma attack", "bronchial asthma", "respiratory disease", "respiratory disorder", "respiratory illness", "status asthmaticus"],
    "asthmatic": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "astigmatic": [],
    "astigmatism": ["ametropia", "astigmia", "keratectasia", "keratoconus"],
    "astilbe": ["astilbe biternata", "astilbe chinensis pumila", "astilbe japonica", "dwarf astilbe", "false goatsbeard", "herb", "herbaceous plant", "spiraea", "spirea"],
    "astir": ["up"],
    "astomatal": [],
    "astomatous": ["mouthless"],
    "astonishing": ["astounding", "staggering", "stupefying"],
    "astonishment": ["admiration", "amazement", "feeling", "stupefaction", "surprise", "wonder", "wonderment"],
    "astor": ["nancy witcher astor", "viscountess astor"],
    "astounding": ["dumbfounding", "dumfounding"],
    "astragalar": [],
    "astragalus": ["genus astragalus", "rosid dicot genus"],
    "astrakhan": ["fur", "pelt"],
    "astrantia": ["astrantia major", "greater masterwort", "herb", "herbaceous plant", "masterwort"],
    "astraphobia": ["simple phobia"],
    "astray": [],
    "astreus": ["fungus genus", "genus astreus"],
    "astreus hygrometricus": ["earthstar"],
    "astreus pteridis": ["earthstar"],
    "astride": [],
    "astringe": ["compact", "compress", "constrict", "contract", "press", "squeeze"],
    "astringency": ["astringence", "gustatory perception", "gustatory sensation", "taste", "taste perception", "taste sensation"],
    "astringent": ["alum", "astringent drug", "medicament", "medication", "medicinal drug", "medicine", "styptic"],
    "astrocyte": ["fibrous astrocyte", "glial cell", "neurogliacyte", "neuroglial cell", "protoplasmic astrocyte"],
    "astrocytic": [],
    "astrodome": ["dome"],
    "astrodynamics": ["astronomy", "uranology"],
    "astrogate": ["navigate", "pilot"],
    "astrogator": ["navigator"],
    "astroglia": ["glia", "macroglia", "neuroglia"],
    "astrolabe": ["sextant"],
    "astrolatry": ["worship", "worship of heavenly bodies"],
    "astrologer": ["astrologist", "forecaster", "predictor", "prognosticator", "soothsayer"],
    "astrological": [],
    "astrology": ["horoscopy", "pseudoscience", "star divination"],
    "astroloma": ["dilleniid dicot genus", "genus astroloma"],
    "astrometry": ["astronomy", "uranology"],
    "astronaut": ["cosmonaut", "spaceman", "spacewalker", "traveler", "traveller"],
    "astronautic": ["astronautical"],
    "astronium": ["dicot genus", "genus astronium", "magnoliopsid genus"],
    "astronomer": ["astrophysicist", "cosmologist", "physicist", "stargazer", "uranologist"],
    "astronomic": ["astronomical"],
    "astronomical telescope": ["optical telescope", "radio reflector", "radio telescope", "scope", "telescope"],
    "astronomical unit": ["astronomy unit", "au"],
    "astronomically": [],
    "astronomy": ["astrodynamics", "astrometry", "astrophysics", "celestial mechanics", "natural philosophy", "physics", "radio astronomy", "selenology", "solar physics", "uranology"],
    "astronomy satellite": ["artificial satellite", "orbiter", "satellite"],
    "astronomy unit": ["astronomical unit", "au", "light hour", "light minute", "light second", "light year", "light-year", "linear measure", "linear unit", "parsec", "secpar"],
    "astrophysical": [],
    "astrophysicist": ["astronomer", "stargazer", "uranologist"],
    "astrophysics": ["astronomy", "cosmogeny", "cosmogony", "cosmology", "uranology"],
    "astrophyton": ["echinoderm genus", "genus astrophyton"],
    "astrophyton muricatum": ["basket fish", "basket star"],
    "astropogon": ["fish genus", "genus astropogon"],
    "astute": ["sharp", "shrewd"],
    "astutely": ["acutely", "sagaciously", "sapiently", "shrewdly"],
    "astuteness": ["deepness", "depth", "profoundness", "profundity", "sapience", "wisdom"],
    "astylar": [],
    "asuncion": ["capital of paraguay"],
    "asunder": [],
    "asura": [],
    "asvins": ["hindu deity"],
    "aswan": ["assouan", "assuan"],
    "aswan high dam": ["high dam"],
    "asymmetrical": ["asymmetric"],
    "asymmetrically": ["unsymmetrically"],
    "asymmetry": ["dissymmetry", "eyedness", "footedness", "geometrical irregularity", "handedness", "imbalance", "irregularity", "laterality", "lopsidedness", "radial asymmetry", "skewness", "spatial property", "spatiality"],
    "asymptomatic": ["symptomless"],
    "asymptote": ["straight line"],
    "asymptotic": [],
    "asymptotically": [],
    "asynchronism": ["asynchrony", "desynchronisation", "desynchronization", "desynchronizing", "temporal relation"],
    "asynchronous": [],
    "asynchronous operation": ["operation"],
    "asynchronous transfer mode": ["atm", "data communication", "digital communication"],
    "asynclitism": ["abnormalcy", "abnormality", "obliquity"],
    "asyndetic": [],
    "asyndeton": ["rhetorical device"],
    "asynergic": [],
    "asynergy": ["asynergia", "pathology"],
    "asystole": ["cardiac arrest", "cardiopulmonary arrest", "pathology"],
    "at": ["laotian monetary unit"],
    "at a loss": [],
    "at a time": ["at once", "at one time"],
    "at all": ["in the least", "the least bit"],
    "at all costs": ["at any cost", "at any expense"],
    "at arm's length": [],
    "at bay": ["cornered", "trapped", "treed"],
    "at best": ["at the best"],
    "at fault": [],
    "at first blush": ["when first seen"],
    "at first sight": ["at first glance"],
    "at hand": ["close at hand"],
    "at heart": ["at bottom", "deep down", "in spite of appearance", "inside"],
    "at home": ["reception"],
    "at large": ["in a broad way"],
    "at least": ["at any rate", "leastways", "leastwise"],
    "at leisure": ["leisurely"],
    "at loggerheads": [],
    "at most": ["at the most"],
    "at odds": ["conflicting", "contradictory", "self-contradictory"],
    "at rest": [],
    "at stake": [],
    "at the ready": [],
    "at variance": ["discrepant", "dissonant"],
    "at will": [],
    "at work": [],
    "at worst": ["at the worst"],
    "atacama desert": [],
    "atacama trench": [],
    "atactic abasia": ["abasia", "ataxic abasia"],
    "atakapa": ["attacapan", "buffalo indian", "plains indian"],
    "ataractic": ["ataraxic", "sedative", "tranquilising", "tranquilizing", "tranquillising", "tranquillizing"],
    "ataraxia": ["placidity", "quiet", "repose", "serenity", "tranquility", "tranquillity"],
    "ataturk": ["kemal ataturk", "kemal pasha", "mustafa kemal"],
    "atavism": ["recurrence", "return", "reversion", "throwback"],
    "atavist": ["being", "organism", "throwback"],
    "atavistic": ["throwback"],
    "ataxia": ["ataxy", "dyssynergia", "friedreich's ataxia", "herediatry spinal ataxia", "hereditary cerebellar ataxia", "motor ataxia", "nervous disorder", "neurological disease", "neurological disorder"],
    "ataxic": ["atactic"],
    "ate": [],
    "atelectasis": ["pathology"],
    "ateleiosis": ["ateliosis", "infantilism"],
    "ateleiotic": [],
    "ateles": ["genus ateles", "mammal genus"],
    "aten": ["aton"],
    "atenolol": ["beta blocker", "beta-adrenergic blocker", "beta-adrenergic blocking agent", "beta-blocking agent", "tenormin"],
    "athanasian creed": ["credo", "creed"],
    "athanasianism": ["theological doctrine"],
    "athanasius": ["athanasius the great", "saint athanasius", "st. athanasius"],
    "athanor": ["furnace"],
    "athapaskan": ["american indian", "apache", "athabascan", "athabaskan", "athapascan", "chipewyan", "hupa", "indian", "mattole", "navaho", "navajo", "red indian"],
    "atharva-veda": [],
    "atheism": ["godlessness", "religious orientation"],
    "atheist": ["disbeliever", "nonbeliever", "unbeliever"],
    "atheistic": ["atheistical", "unbelieving"],
    "athelstan": [],
    "athena": ["athene", "pallas", "pallas athena", "pallas athene"],
    "athenaeum": ["atheneum", "club", "gild", "guild", "lodge", "order", "social club", "society"],
    "athene": ["bird genus", "genus athene"],
    "athenian": ["greek", "hellene"],
    "athens": [],
    "atherinidae": ["family atherinidae", "fish family"],
    "atherinopsis": ["fish genus", "genus atherinopsis"],
    "atherogenesis": ["pathology"],
    "atheroma": ["adipose tissue", "fat", "fatty tissue"],
    "atheromatous": ["atheromatic"],
    "atherosclerosis": ["arterial sclerosis", "arteriosclerosis", "coronary artery disease", "coronary-artery disease", "hardening of the arteries", "induration of the arteries"],
    "atherosclerotic": [],
    "atherurus": ["genus atherurus", "mammal genus"],
    "athetosis": ["nervous disorder", "neurological disease", "neurological disorder"],
    "athiorhodaceae": ["bacteria family", "family athiorhodaceae"],
    "athirst": ["hungry", "thirsty"],
    "athlete": ["acrobat", "amateur", "ball hawk", "ballplayer", "baseball player", "basketball player", "basketeer", "cager", "climber", "contestant", "cricketer", "football player", "footballer", "gymnast", "hockey player", "hooker", "hurdler", "ice-hockey player", "jock", "jumper", "lacrosse player", "letterman", "lifter", "olympian", "pentathlete", "pole jumper", "pole vaulter", "pro", "professional", "reserve", "runner", "second-stringer", "sharpshooter", "shot putter", "skater", "skier", "sledder", "soccer player", "sport", "sportsman", "sportswoman", "striker", "substitute", "swimmer", "swinger", "tennis player", "vaulter", "weightlifter", "winger"],
    "athlete's heart": ["heart", "pump", "ticker"],
    "athletic": [],
    "athletic contest": ["athletic competition", "athletics", "competition", "contest", "decathlon", "hop-step-and-jump", "meet", "olympiad", "olympic games", "olympics", "pentathlon", "prelim", "preliminary", "special olympics", "sports meeting", "triple jump", "tug-of-war"],
    "athletic facility": ["facility", "field house", "football stadium", "gym", "gymnasium", "installation", "natatorium", "swimming bath", "swimming pool"],
    "athletic game": ["athletics", "court game", "game", "hockey", "hockey game", "ice hockey", "outdoor game", "sport", "tetherball", "water polo"],
    "athletic sock": ["sock", "sweat sock", "varsity sock"],
    "athletic supporter": ["jock", "jockstrap", "man's clothing", "protective garment", "supporter", "suspensor"],
    "athletic training": ["fartlek", "grooming", "preparation", "training"],
    "athletic type": ["body type", "mesomorphy", "somatotype"],
    "athleticism": ["energy", "strenuosity", "vigor", "vigour", "zip"],
    "athletics": ["extracurricular activity"],
    "athos": ["mount athos"],
    "athrotaxis": ["genus athrotaxis", "gymnosperm genus"],
    "athwart": [],
    "athyrium": ["fern genus", "genus athyrium"],
    "atilt": ["canted", "leaning", "tilted", "tipped"],
    "atlanta": ["capital of georgia"],
    "atlantic": ["atlantic ocean"],
    "atlantic bottlenose dolphin": ["bottle-nosed dolphin", "bottlenose", "bottlenose dolphin", "tursiops truncatus"],
    "atlantic city": [],
    "atlantic coast": [],
    "atlantic cod": ["cod", "codfish", "gadus morhua"],
    "atlantic croaker": ["croaker", "micropogonias undulatus"],
    "atlantic halibut": ["hippoglossus hippoglossus", "righteye flounder", "righteyed flounder"],
    "atlantic herring": ["clupea harangus", "clupea harengus harengus", "herring"],
    "atlantic manta": ["devilfish", "manta", "manta birostris", "manta ray"],
    "atlantic puffin": ["fratercula arctica", "puffin"],
    "atlantic ridley": ["bastard ridley", "bastard turtle", "lepidochelys kempii", "ridley"],
    "atlantic sailfish": ["istiophorus albicans", "sailfish"],
    "atlantic salmon": ["salmon"],
    "atlantic sea bream": ["archosargus rhomboidalis", "bream", "sea bream"],
    "atlantic spiny dogfish": ["spiny dogfish", "squalus acanthias"],
    "atlantic time": ["atlantic standard time", "civil time", "local time", "standard time"],
    "atlantic tripletail": ["lobotes surinamensis", "tripletail"],
    "atlantic walrus": ["odobenus rosmarus", "sea horse", "seahorse", "walrus"],
    "atlantis": ["fictitious place", "imaginary place", "mythical place"],
    "atlas": [],
    "atlas cedar": ["cedar", "cedar tree", "cedrus atlantica", "true cedar"],
    "atlas moth": ["atticus atlas", "giant silkworm moth", "silkworm moth"],
    "atlas mountains": [],
    "atmometer": ["evaporometer", "measuring device", "measuring instrument", "measuring system"],
    "atmosphere": ["ambiance", "ambience", "condition", "feel", "feeling", "flavor", "flavour", "genius loci", "gloom", "gloominess", "glumness", "look", "miasm", "miasma", "smell", "spirit", "status", "tone"],
    "atmospheric": ["atmospherical"],
    "atmospheric electricity": ["atmospheric phenomenon", "blue jet", "electrical discharge", "elves", "jet", "lightning", "red sprites", "reverse lightning", "sprites"],
    "atmospheric phenomenon": ["afterglow", "air hole", "air pocket", "atmospheric condition", "atmospheric electricity", "aurora", "cloud", "condensate", "condensation", "conditions", "front", "greenhouse effect", "greenhouse warming", "halo", "inversion", "meteor shower", "meteor stream", "midnight sun", "physical phenomenon", "pocket", "storm", "sunrise", "sunset", "violent storm", "weather", "weather condition"],
    "atmospheric pressure": ["air pressure", "barometric pressure", "compartment pressure", "gas pressure", "overpressure", "pressure", "sea-level pressure"],
    "atole": ["cornmeal mush", "mush"],
    "atoll": ["coral reef"],
    "atom": ["carbon atom", "free radical", "hydrogen atom", "isotope", "monad", "radical", "substance"],
    "atom bomb": ["a-bomb", "atomic bomb", "atomic weapon", "bomb", "clean bomb", "dirty bomb", "fission bomb", "neutron bomb", "nuclear weapon", "plutonium bomb"],
    "atom-bomb": ["bomb", "bombard", "nuke"],
    "atomic": [],
    "atomic clock": ["ammonia clock", "caesium clock", "horologe", "timekeeper", "timepiece"],
    "atomic cocktail": ["medicament", "medication", "medicinal drug", "medicine"],
    "atomic energy": ["atomic power", "energy", "free energy", "nuclear energy", "nuclear power"],
    "atomic energy commission": ["aec", "executive agency"],
    "atomic mass": ["atomic weight", "combining weight", "eq", "equivalent", "equivalent weight", "mass", "meq", "milliequivalent", "relative atomic mass"],
    "atomic mass unit": ["mass unit"],
    "atomic number": ["magic number", "number"],
    "atomic pile": ["atomic reactor", "chain reactor", "nuclear reactor", "pile", "reactor"],
    "atomic power": ["atomic energy", "nuclear energy", "nuclear power"],
    "atomic spectrum": ["spectrum"],
    "atomic theory": ["bohr theory", "rutherford atom", "scientific theory"],
    "atomic warhead": ["load", "nuclear warhead", "nuke", "payload", "thermonuclear warhead", "warhead"],
    "atomism": ["scientific theory"],
    "atomistic": ["atomistical"],
    "atomization": ["atomisation", "division", "fragmentation"],
    "atomize": ["atomise", "spray"],
    "atomizer": ["airbrush", "atomiser", "dispenser", "nebuliser", "nebulizer", "spray", "sprayer"],
    "atonal": ["unkeyed"],
    "atonalistic": [],
    "atonality": ["atonalism", "musical notation"],
    "atonally": [],
    "atonement": ["amends", "damages", "expiation", "indemnification", "indemnity", "redress", "restitution", "satisfaction"],
    "atonic": [],
    "atonicity": ["amyotonia", "atonia", "atony", "condition", "status"],
    "atop": [],
    "atopic dermatitis": ["atopic eczema", "dermatitis"],
    "atopognosia": ["atopognosis", "nervous disorder", "neurological disease", "neurological disorder"],
    "atorvastatin": ["lipid-lowering medication", "lipid-lowering medicine", "lipitor", "statin", "statin drug"],
    "atrabilious": ["bilious", "dyspeptic", "liverish"],
    "atrazine": ["herbicide", "weed killer", "weedkiller"],
    "atresia": ["abnormalcy", "abnormality"],
    "atreus": [],
    "atrial": [],
    "atrial artery": ["arteria coronaria", "coronary artery"],
    "atrial fibrillation": ["arrhythmia", "cardiac arrhythmia", "fibrillation"],
    "atrial septal defect": ["septal defect"],
    "atrichornis": ["bird genus", "genus atrichornis"],
    "atrichornithidae": ["bird family", "family atrichornithidae"],
    "atrioventricular": ["auriculoventricular"],
    "atrioventricular bundle": ["atrioventricular trunk", "bundle of his", "cardiac muscle", "heart muscle", "truncus atrioventricularis"],
    "atrioventricular nodal rhythm": ["cardiac rhythm", "heart rhythm", "nodal rhythm"],
    "atrioventricular node": ["cardiac muscle", "heart muscle"],
    "atrioventricular valve": ["bicuspid valve", "cardiac valve", "heart valve", "left atrioventricular valve", "mitral valve", "right atrioventricular valve", "tricuspid valve"],
    "atriplex": ["caryophylloid dicot genus", "genus atriplex"],
    "atrium": ["atrium cordis", "atrium of the heart", "chamber"],
    "atrium cordis": ["atrium", "atrium dextrum", "atrium of the heart", "atrium sinistrum", "left atrium", "left atrium of the heart", "right atrium", "right atrium of the heart"],
    "atrocious": ["flagitious", "grievous", "monstrous"],
    "atrocity": ["atrociousness", "barbarity", "barbarousness", "heinousness", "inhumaneness", "inhumanity"],
    "atropa": ["asterid dicot genus", "genus atropa"],
    "atrophic": [],
    "atrophied": ["diminished", "wasted"],
    "atrophy": ["shrink", "shrivel", "shrivel up", "wither"],
    "atropidae": ["arthropod family", "family atropidae"],
    "atropine": ["alkaloid", "antidote", "antispasmodic", "antispasmodic agent", "belladonna", "counterpoison", "mydriatic", "mydriatic drug", "poison", "poisonous substance", "spasmolytic", "toxicant"],
    "atropos": [],
    "atsugewi": ["hoka", "hokan"],
    "attach": ["add on", "affix", "append", "band", "bell", "bind", "catch", "clip", "connect", "couple", "couple on", "couple up", "enter", "fasten", "fix", "fixate", "glue", "hang on", "harness", "hinge", "hitch", "hook up", "infix", "insert", "introduce", "label", "limber", "limber up", "link", "link up", "mark", "mount", "nail", "paste", "peg", "peg down", "pin down", "pin up", "ring", "saddle", "secure", "stick on", "supplement", "tack", "tack on", "tackle", "tag", "tag on", "tape", "tether", "tie", "yoke"],
    "attach to": ["accompany", "attend", "co-occur with", "collocate with", "come with", "construe with", "cooccur with", "go with", "rule"],
    "attachable": [],
    "attache": ["cultural attache", "military attache", "specialiser", "specialist", "specializer"],
    "attache case": ["attache", "briefcase"],
    "attached": [],
    "attachment": ["affection", "affectionateness", "fond regard", "fondness", "heart", "philia", "tenderness", "warmheartedness", "warmness"],
    "attack": ["assail", "beleaguer", "besiege", "blitz", "bomb", "bombard", "bust", "cannonade", "circumvent", "contend", "counterattack", "counterstrike", "fight", "gas", "hem in", "hit", "invade", "occupy", "pelt", "pepper", "raid", "storm", "strafe", "strike", "struggle", "submarine", "surprise", "surround", "torpedo"],
    "attack dog": ["guard dog", "watchdog"],
    "attack submarine": ["pigboat", "sub", "submarine", "u-boat"],
    "attacker": ["aggressor", "ambusher", "assailant", "assaulter", "avenger", "beast", "bludgeoner", "brute", "bully", "harasser", "harrier", "hooligan", "iconoclast", "lapidator", "marauder", "night rider", "nightrider", "offender", "piranha", "predator", "raper", "rapist", "retaliator", "roughneck", "rowdy", "ruffian", "savage", "shedder", "slasher", "spiller", "stabber", "stoner", "tough", "vulture", "wildcat", "wolf", "wrongdoer", "yob", "yobbo", "yobo"],
    "attainable": ["come-at-able"],
    "attainder": ["cancellation", "civil death"],
    "attained": [],
    "attainment": ["accession", "accomplishment", "achievement", "course credit", "credit", "record", "rise to power", "success"],
    "attaint": ["condemn"],
    "attalea": ["genus attalea", "liliopsid genus", "monocot genus"],
    "attar": ["atar", "athar", "attar of roses", "essential oil", "ottar", "rose oil", "volatile oil"],
    "attar of roses": ["atar", "athar", "attar", "ottar", "rose oil"],
    "attemper": ["modify"],
    "attempt": ["activity", "batting", "battle", "best", "bid", "contribution", "crack", "effort", "endeavor", "endeavour", "essay", "fling", "foray", "go", "liberation", "mug's game", "nisus", "offer", "pains", "part", "pass", "play", "power play", "run", "seeking", "share", "shot", "squeeze", "squeeze play", "stab", "strain", "striving", "struggle", "takeover attempt", "test", "trial", "try", "whirl", "worst"],
    "attempted": [],
    "attend": ["accompany", "attach to", "come with", "go with"],
    "attend to": ["bear in mind", "mind", "take to heart"],
    "attendance": ["frequence", "frequency", "oftenness"],
    "attendance check": ["roll call"],
    "attendant": ["arouser", "assistant", "attender", "baggageman", "batman", "bellboy", "bellhop", "bellman", "bridesmaid", "caddie", "checker", "companion", "courtier", "cupbearer", "equerry", "escort", "esquire", "famulus", "flight attendant", "gallant", "gillie", "golf caddie", "groomsman", "help", "helper", "hospital attendant", "lifeguard", "lifesaver", "linkboy", "linkman", "litter-bearer", "loader", "maid of honor", "matron of honor", "orderly", "page", "racker", "rocker", "rouser", "second", "servitor", "squire", "steward", "stretcher-bearer", "supporter", "tender", "trainbearer", "varlet", "waker"],
    "attended": ["tended to"],
    "attention": ["attracter", "attraction", "attractive feature", "attractor", "enhancer", "foil", "magnet"],
    "attention deficit disorder": ["add", "adhd", "attention deficit hyperactivity disorder", "hyperkinetic syndrome", "mbd", "minimal brain damage", "minimal brain dysfunction", "syndrome"],
    "attention span": ["span"],
    "attention-getting": ["eye-catching"],
    "attentional": [],
    "attentive": [],
    "attentively": [],
    "attentiveness": ["advertence", "advertency", "attending", "attention", "heed", "paying attention", "regard"],
    "attenuate": ["refine", "weaken"],
    "attenuated": [],
    "attenuation": ["fading", "weakening"],
    "attenuator": ["electrical device"],
    "attest": ["authenticate", "bear witness", "certify", "condemn", "demonstrate", "evidence", "manifest", "notarise", "notarize", "prove", "reflect", "show", "testify"],
    "attestation": ["testimony"],
    "attestation service": ["attestation report", "consulting service", "financial audit"],
    "attested": ["authenticated", "documented"],
    "attester": ["attestant", "informant", "witness", "witnesser"],
    "attic": ["ancient greek", "classical greek", "ionic", "ionic dialect"],
    "attic fan": ["exhaust fan"],
    "attica": [],
    "atticus": ["arthropod genus", "genus atticus"],
    "attila": ["attila the hun", "scourge of god", "scourge of the gods"],
    "attire": ["activewear", "ao dai", "article of clothing", "athletic wear", "clothing", "costume", "disguise", "dress", "ecclesiastical attire", "ecclesiastical robe", "evening clothes", "evening dress", "eveningwear", "false hair", "finery", "formalwear", "garb", "getup", "habiliment", "habit", "hairpiece", "morning dress", "outfit", "postiche", "riding habit", "rig", "sportswear", "turnout", "vesture", "wear", "wearable"],
    "attitude": ["orientation", "trim"],
    "attitudinal": [],
    "attitudinize": ["attitudinise", "pose", "posture"],
    "attlee": ["1st earl attlee", "clement attlee", "clement richard attlee"],
    "attorn": ["acknowledge", "admit"],
    "attorney general": ["secretary", "united states attorney general", "us attorney general"],
    "attorney-client privilege": ["privilege"],
    "attorneyship": ["berth", "billet", "office", "place", "position", "post", "situation", "spot"],
    "attosecond": ["time unit", "unit of time"],
    "attract": ["appeal", "becharm", "beckon", "beguile", "bewitch", "captivate", "capture", "catch", "charm", "enamor", "enamour", "enchant", "entrance", "fascinate", "trance"],
    "attractable": [],
    "attraction": ["affinity", "attractive force", "bond", "chemical bond", "force", "gravitation", "gravitational attraction", "gravitational force", "gravity", "magnetic attraction", "magnetic force", "magnetism", "van der waal's forces"],
    "attractive": [],
    "attractive nuisance": ["nuisance"],
    "attractiveness": ["adorability", "adorableness", "animal magnetism", "appeal", "appealingness", "beauty", "beguilement", "bewitchery", "charisma", "charm", "desirability", "desirableness", "oomph", "personal appeal", "personal magnetism", "sex appeal", "spiff"],
    "attractor": ["attracter", "chaotic attractor", "point", "strange attractor"],
    "attributable": [],
    "attribute": ["abstract entity", "abstraction", "ballast", "character", "cheer", "cheerfulness", "common denominator", "depth", "eidos", "ethos", "form", "heritage", "human nature", "infinite", "inheritance", "personality", "property", "quality", "shape", "space", "state", "sunniness", "sunshine", "thing", "time", "trait", "uncheerfulness"],
    "attribution": ["ascription", "categorisation", "categorization", "classification", "sorting", "zoomorphism"],
    "attributive": ["prenominal"],
    "attributive genitive": ["attributive genitive case", "genitive", "genitive case", "possessive", "possessive case"],
    "attributively": [],
    "attrited": [],
    "attrition": ["contriteness", "contrition", "regret", "rue", "ruefulness", "sorrow"],
    "attrition rate": ["rate", "rate of attrition"],
    "attritional": [],
    "attune": ["adjust", "correct", "set"],
    "atypical": ["untypical"],
    "atypical pneumonia": ["mycoplasmal pneumonia", "ornithosis", "parrot fever", "primary atypical pneumonia", "psittacosis", "respiratory disease", "respiratory disorder", "respiratory illness"],
    "atypicality": ["abnormalcy", "abnormality", "untypicality"],
    "atypically": ["untypically"],
    "au gratin": [],
    "au jus": [],
    "au pair": ["alien", "au pair girl", "foreigner", "noncitizen", "outlander"],
    "au pair girl": ["au pair"],
    "auburn": [],
    "auchincloss": ["louis auchincloss", "louis stanton auchincloss"],
    "auckland": [],
    "auction": ["auction off", "auctioneer", "sell"],
    "auction block": ["block", "platform"],
    "auction house": ["business firm", "firm", "house"],
    "auctioneer": ["agent", "broker", "factor"],
    "aucuba": ["genus aucuba", "rosid dicot genus"],
    "audacious": ["brave", "dauntless", "fearless", "hardy", "intrepid", "unfearing"],
    "audaciously": [],
    "audacity": ["audaciousness", "boldness", "daring", "hardihood", "hardiness", "temerity"],
    "auden": ["w. h. auden", "wystan hugh auden"],
    "audenesque": [],
    "audibility": ["audibleness", "perceptibility"],
    "audible": ["football play"],
    "audibly": [],
    "audience": ["hoi polloi", "mass", "masses", "multitude", "people", "readership", "the great unwashed", "tv audience", "viewers", "viewing audience"],
    "audile": ["beholder", "observer", "perceiver", "percipient"],
    "audio": ["auditory communication", "sound"],
    "audio amplifier": ["amplifier"],
    "audio cd": ["audio compact disc", "cd", "compact disc", "compact disk"],
    "audio lingual acquisition": ["language learning"],
    "audio system": ["electronic equipment", "recording system", "reproducer", "sound system", "system"],
    "audio-lingual": [],
    "audiocassette": ["cassette"],
    "audiogram": ["representation"],
    "audiology": ["audiometry", "otology"],
    "audiometer": ["measuring device", "measuring instrument", "measuring system", "sonometer"],
    "audiometric": [],
    "audiometry": ["measure", "measurement", "measuring", "mensuration"],
    "audiotape": ["audio", "audio recording", "dat", "digital audiotape", "sound recording", "tape", "tape recording", "taping"],
    "audiovisual": ["audiovisual aid", "teaching aid"],
    "audit": ["analyse", "analyze", "canvas", "canvass", "examine", "inspect", "scrutinise", "scrutinize", "study"],
    "audit program": ["audit programme", "plan", "program", "programme"],
    "audited account": ["accounting", "accounting system", "audit", "financial audit", "limited audit", "method of accounting"],
    "audition": ["perform", "read", "try out"],
    "auditor": ["educatee", "pupil", "student"],
    "auditorium": ["area", "assembly hall"],
    "auditory": ["audile", "auditive"],
    "auditory agnosia": ["agnosia"],
    "auditory aphasia": ["acoustic aphasia", "aphasia", "word deafness"],
    "auditory apparatus": ["apparatus"],
    "auditory area": ["auditory cortex", "cortical area", "cortical region"],
    "auditory center": ["center", "centre", "nerve center", "nerve centre"],
    "auditory communication": ["audio", "communication", "language", "music", "oral communication", "sound", "speech", "speech communication", "spoken communication", "spoken language", "utterance", "vocalization", "voice communication"],
    "auditory hallucination": ["acousma", "hallucination"],
    "auditory image": ["image", "mental image"],
    "auditory meatus": ["acoustic meatus", "auditory canal", "ear canal", "external auditory canal", "meatus"],
    "auditory ossicle": ["anvil", "bonelet", "hammer", "incus", "malleus", "ossicle", "ossiculum", "stapes", "stirrup"],
    "auditory perception": ["musical perception", "perception", "sound perception", "speech perception"],
    "auditory system": ["sensory system"],
    "audubon": ["john james audubon"],
    "audubon's caracara": ["caracara", "polyborus cheriway audubonii"],
    "audubon's warbler": ["audubon warbler", "dendroica auduboni", "new world warbler", "wood warbler"],
    "augean": [],
    "augean stables": [],
    "augeas": [],
    "augend": ["number"],
    "auger": ["drill", "gimlet", "screw auger", "wimble"],
    "augite": ["mineral"],
    "augitic": [],
    "augment": ["grow"],
    "augmentation": ["increase"],
    "augmentative": [],
    "augmented": [],
    "augsburg confession": [],
    "augur": ["anticipate", "call", "forebode", "foretell", "predict", "prognosticate", "promise"],
    "augury": ["experience", "foretoken", "omen", "portent", "preindication", "presage", "prodigy", "prognostic", "prognostication", "sign", "war cloud"],
    "august": ["aug", "gregorian calendar month"],
    "augusta": ["capital of maine"],
    "augustan": [],
    "augustine": ["augustine of hippo", "saint augustine", "st. augustine"],
    "augustinian": ["austin friar", "friar", "mendicant"],
    "augustinian canons": ["augustinian order"],
    "augustinian hermits": ["augustinian order"],
    "augustinian order": ["augustinian canons", "augustinian hermits", "austin friars", "monastic order", "order"],
    "augustus": ["gaius julius caesar octavianus", "gaius octavianus", "octavian"],
    "auk": ["alca torda", "auklet", "dovekie", "great auk", "guillemot", "little auk", "pinguinus impennis", "plautus alle", "razor-billed auk", "razorbill", "sea bird", "seabird", "seafowl"],
    "auklet": ["auk"],
    "aulacorhyncus": ["bird genus", "genus aulacorhyncus"],
    "auld": [],
    "auld langsyne": ["good old days", "langsyne", "old times", "past", "past times", "yesteryear"],
    "aulostomidae": ["family aulostomidae", "fish family"],
    "aulostomus": ["fish genus", "genus aulostomus"],
    "aum shinrikyo": ["aum", "supreme truth"],
    "aunt": ["auntie", "aunty", "grandaunt", "great-aunt", "kinswoman", "maiden aunt"],
    "aura": ["symptom"],
    "aural": [],
    "aurally": [],
    "aureate": ["flamboyant", "florid"],
    "aureolaria": ["asterid dicot genus", "genus aureolaria"],
    "aureole": ["corona", "glow", "glowing", "radiance"],
    "auricle": ["atrial auricle", "auricula atrii", "pocket", "pouch"],
    "auricula": ["bear's ear", "primrose", "primula", "primula auricula"],
    "auricular": [],
    "auricular artery": ["arteria", "arteria auricularis", "arterial blood vessel", "artery"],
    "auricular vein": ["vein", "vena", "vena auricularis", "venous blood vessel"],
    "auriculare": ["auricular point", "craniometric point"],
    "auricularia": ["fungus genus", "genus auricularia"],
    "auriculariaceae": ["family auriculariaceae", "fungus family"],
    "auriculariales": ["fungus order", "order auriculariales"],
    "auriculate": ["auriculated"],
    "auriferous": ["gold-bearing"],
    "auriform": ["ear-like", "ear-shaped"],
    "aurify": ["metamorphose", "transform", "transmute"],
    "auriga": ["charioteer"],
    "auriparus": ["bird genus", "genus auriparus"],
    "aurochs": ["bos primigenius", "ox", "urus", "wild ox"],
    "aurora": ["atmospheric phenomenon", "aurora australis", "aurora borealis", "northern lights", "southern lights"],
    "aurora australis": ["aurora", "southern lights"],
    "aurora borealis": ["aurora", "northern lights"],
    "auroral": [],
    "aurous": ["auric"],
    "auschwitz": [],
    "auscultate": ["examine", "see"],
    "auscultation": ["diagnostic procedure", "diagnostic technique", "hearing", "listening", "percussion", "pleximetry", "succussion"],
    "auscultatory": [],
    "auspicate": ["begin", "commence", "get", "get down", "set about", "set out", "start", "start out"],
    "auspice": ["omen", "portent", "presage", "prodigy", "prognostic", "prognostication"],
    "auspices": ["aegis", "endorsement", "indorsement", "protection"],
    "auspicious": [],
    "auspiciously": ["propitiously"],
    "auspiciousness": ["advantageousness", "favorableness", "favourableness", "positiveness", "positivity", "profitableness", "propitiousness"],
    "austen": ["jane austen"],
    "austenite": ["primary solid solution", "solid solution"],
    "austenitic": [],
    "austenitic steel": ["steel"],
    "austere": ["severe", "stark", "stern"],
    "austerely": [],
    "austereness": ["plainness", "severeness", "severity"],
    "austerity": ["asceticism", "monasticism", "nonindulgence", "self-denial", "self-discipline"],
    "austerlitz": [],
    "austin": ["capital of texas"],
    "austin friar": ["augustinian"],
    "austin friars": ["augustinian order"],
    "austral": ["argentine monetary unit"],
    "australasia": [],
    "australasian": [],
    "australia": [],
    "australian": ["abo", "aboriginal", "aborigine", "aussie", "australian aborigine", "denizen", "dweller", "habitant", "indweller", "inhabitant", "native australian"],
    "australian alps": [],
    "australian arowana": ["dawson river salmon", "fish species", "saratoga", "scleropages leichardti", "spotted barramundi", "spotted bonytongue"],
    "australian blacksnake": ["elapid", "elapid snake", "pseudechis porphyriacus"],
    "australian bonytongue": ["fish species", "northern barramundi", "scleropages jardinii"],
    "australian cockroach": ["cockroach", "periplaneta australasiae", "roach"],
    "australian coral snake": ["coral snake", "old world coral snake", "rhynchoelaps australis"],
    "australian desert": ["great australian desert"],
    "australian dollar": ["dollar"],
    "australian grass tree": ["australian heath", "richea dracophylla"],
    "australian hare's foot": ["davallia pyxidata", "hare's-foot fern"],
    "australian heath": ["australian grass tree", "bush", "epacris", "grass tree", "richea dracophylla", "richea pandanifolia", "shrub", "tree heath"],
    "australian labor party": ["labor party", "labour party"],
    "australian lungfish": ["endangered species", "neoceratodus forsteri", "queensland lungfish"],
    "australian magpie": ["bell magpie", "butcherbird", "currawong", "gymnorhina tibicen", "oscine", "oscine bird", "piping crow", "piping crow-shrike"],
    "australian nettle": ["australian nettle tree", "tree"],
    "australian pea": ["dipogon lignosus", "dolichos lignosus", "vine"],
    "australian pine": ["beefwood", "casuarina equisetfolia"],
    "australian pitcher plant": ["cephalotus follicularis", "herb", "herbaceous plant"],
    "australian reed grass": ["calamagrostic quadriseta", "reed grass"],
    "australian sea lion": ["sea lion", "zalophus lobatus"],
    "australian state": ["province", "state"],
    "australian sumac": ["angiospermous yellowwood", "rhodosphaera rhodanthema", "rhus rhodanthema"],
    "australian terrier": ["terrier"],
    "australian turtledove": ["dove", "stictopelia cuneata", "turtledove"],
    "australopithecine": ["australopithecus afarensis", "australopithecus africanus", "australopithecus boisei", "australopithecus robustus", "genus paranthropus", "genus zinjanthropus", "hominid", "paranthropus", "zinjanthropus"],
    "australopithecus afarensis": ["australopithecine"],
    "australopithecus africanus": ["australopithecine"],
    "australopithecus boisei": ["australopithecine"],
    "australopithecus robustus": ["australopithecine"],
    "austria": ["oesterreich", "republic of austria"],
    "austria-hungary": [],
    "austrian": ["european"],
    "austrian monetary unit": ["austrian schilling", "groschen", "monetary unit", "schilling"],
    "austro-asiatic": ["austro-asiatic language", "mon-khmer", "munda", "munda-mon-khmer", "natural language", "tongue"],
    "austrocedrus": ["genus austrocedrus", "gymnosperm genus"],
    "austronesia": [],
    "austronesian": ["denizen", "dweller", "habitant", "indweller", "inhabitant", "nauruan", "polynesian"],
    "austrotaxus": ["genus austrotaxus", "gymnosperm genus"],
    "autacoid": ["autocoid", "prostaglandin", "secretion"],
    "autacoidal": [],
    "autarchic": ["autarchical", "autarkical"],
    "autarkic": ["autarkical"],
    "autarky": ["autarchy", "independence", "independency"],
    "auteur": ["film maker", "film producer", "filmmaker", "movie maker"],
    "authentic": ["reliable"],
    "authentically": ["genuinely"],
    "authenticate": ["attest", "certify", "demonstrate", "evidence", "manifest", "prove"],
    "authentication": ["assay-mark", "hallmark", "mark", "marker", "marking"],
    "authenticity": ["believability", "credibility", "credibleness", "genuineness", "legitimacy", "real mccoy", "real stuff", "real thing"],
    "author": ["co-author", "compose", "ghost", "ghostwrite", "indite", "pen", "write"],
    "authoress": ["author", "writer"],
    "authorial": ["auctorial"],
    "authoring language": ["computer software", "package", "software", "software package", "software program", "software system"],
    "authoritarian": ["big brother", "dictator", "disciplinarian", "martinet", "moralist", "oppressor"],
    "authoritarian state": ["authoritarian regime", "authorities", "government", "regime"],
    "authoritative": ["classic", "classical", "definitive"],
    "authoritatively": ["magisterially"],
    "authority": ["abrogator", "allocator", "approver", "authoriser", "authority figure", "authorizer", "civil authority", "civil officer", "distributor", "individual", "mandator", "mortal", "pacha", "pasha", "person", "rebuker", "reproacher", "reprover", "somebody", "someone", "soul", "upbraider", "withdrawer"],
    "authority figure": ["authority"],
    "authorization": ["authorisation", "certification", "commission", "commissioning", "delegating", "delegation", "deputation", "direction", "empowerment", "enfranchisement", "license", "loan approval", "management", "permission", "permit", "relegating", "relegation", "rubber stamp", "sanction"],
    "authorize": ["allow", "approbate", "approve", "authorise", "certificate", "certify", "clear", "commission", "countenance", "declare", "formalise", "formalize", "let", "licence", "license", "o.k.", "okay", "pass", "permit", "sanction", "validate"],
    "authorized": ["authorised"],
    "authorized shares": ["authorized stock", "capital stock", "stock"],
    "authorized version": ["king james bible", "king james version"],
    "authorizer": ["authoriser", "authority"],
    "authorship": ["creation", "foundation", "founding", "initiation", "innovation", "instauration", "institution", "introduction", "origination", "paternity"],
    "autism": ["infantile autism", "syndrome"],
    "autistic": [],
    "auto accessory": ["accessory", "add-on", "appurtenance", "supplement"],
    "auto limitation": ["social control"],
    "auto mechanics": ["craft", "trade"],
    "auto part": ["car part", "component", "constituent", "element"],
    "auto racing": ["car racing", "racing"],
    "auto-da-fe": ["burning", "burning at the stake"],
    "autoantibody": ["antibody", "rheumatoid factor"],
    "autobahn": ["expressway", "freeway", "motorway", "pike", "state highway", "superhighway", "throughway", "thruway"],
    "autobiographer": ["biographer"],
    "autobiographical": ["autobiographic"],
    "autobiography": ["biography", "life", "life history", "life story", "memoir"],
    "autocatalysis": ["catalysis", "contact action"],
    "autocatalytic": [],
    "autochthon": ["primitive", "primitive person"],
    "autochthonal": ["autochthonic", "autochthonous", "endemic", "indigenous"],
    "autochthonous": [],
    "autoclave": ["sterilise", "sterilize"],
    "autocracy": ["absolutism", "autarchy", "authoritarianism", "caesarism", "despotism", "dictatorship", "form of government", "monarchy", "monocracy", "one-man rule", "political system", "shogunate", "stalinism", "totalitarianism", "tyranny"],
    "autocratic": ["bossy", "dominating", "high-and-mighty", "magisterial", "peremptory"],
    "autocratically": [],
    "autodidact": ["individual", "mortal", "person", "somebody", "someone", "soul"],
    "autodidactic": [],
    "autoecious": ["homoecious"],
    "autoerotic": [],
    "autoeroticism": ["autoerotism", "masturbation", "onanism", "sex", "sex activity", "sexual activity", "sexual practice"],
    "autofluorescence": ["fluorescence"],
    "autofluorescent": [],
    "autofocus": ["optical device"],
    "autogamous": ["autogamic"],
    "autogamy": ["self-fertilisation", "self-fertilization"],
    "autogenetic": [],
    "autogenic therapy": ["autogenic training", "autogenics", "intervention", "treatment"],
    "autogenous": ["autogenic"],
    "autogiro": ["autogyro", "gyroplane", "heavier-than-air craft"],
    "autograft": ["autoplasty", "graft", "transplant"],
    "autograph": ["inscribe", "sign"],
    "autograph album": ["album"],
    "autographed": [],
    "autographic": [],
    "autoicous": [],
    "autoimmune": [],
    "autoimmune disease": ["ankylosing spondylitis", "atrophic arthritis", "autoimmune diabetes", "autoimmune disorder", "dermatosclerosis", "discoid lupus erythematosus", "disease", "disseminated multiple sclerosis", "disseminated sclerosis", "dle", "exophthalmic goiter", "graves' disease", "growth-onset diabetes", "hashimoto's disease", "iddm", "idiopathic thrombocytopenic purpura", "insulin-dependent diabetes mellitus", "juvenile diabetes", "juvenile-onset diabetes", "ketoacidosis-prone diabetes", "ketosis-prone diabetes", "le", "lupus erythematosus", "marie-strumpell disease", "ms", "multiple sclerosis", "myasthenia", "myasthenia gravis", "pemphigus", "purpura hemorrhagica", "rheumatism", "rheumatoid arthritis", "rheumatoid spondylitis", "scleroderma", "thrombocytopenic purpura", "type i diabetes", "werlhof's disease"],
    "autoimmunity": ["pathology"],
    "autoinjector": ["hypo", "hypodermic", "hypodermic syringe"],
    "autoloader": ["automatic firearm", "automatic gun", "automatic weapon", "firearm", "piece", "self-loader", "semiautomatic firearm", "small-arm"],
    "autoloading": ["self-loading", "semiautomatic"],
    "autologous": [],
    "autolysis": ["lysis", "self-digestion"],
    "autolytic": [],
    "automat": ["vending machine"],
    "automated": ["machine-controlled", "machine-driven"],
    "automatic": ["reflex", "reflexive"],
    "automatic choke": ["choke"],
    "automatic data processing": ["adp", "data processing", "edp", "electronic data processing", "idp", "integrated data processing"],
    "automatic firearm": ["autoloader", "automatic", "automatic gun", "automatic pistol", "automatic rifle", "automatic weapon", "machine gun", "machine rifle", "self-loader"],
    "automatic pilot": ["autopilot", "unconsciousness"],
    "automatic pistol": ["automatic", "automatic firearm", "automatic gun", "automatic weapon", "handgun", "pistol", "shooting iron", "side arm"],
    "automatic rifle": ["assault gun", "assault rifle", "automatic", "automatic firearm", "automatic gun", "automatic weapon", "bar", "browning automatic rifle", "machine gun", "machine rifle"],
    "automatic transmission": ["automatic drive", "transmission", "transmission system"],
    "automatically": [],
    "automation": ["condition", "status"],
    "automatism": ["reaction", "response"],
    "automatize": ["alter", "automatise", "change", "modify"],
    "automaton": ["anomaly", "unusual person", "zombi", "zombie"],
    "automeris": ["arthropod genus", "genus automeris"],
    "automobile": ["go", "locomote", "move", "travel"],
    "automobile engine": ["engine"],
    "automobile factory": ["auto factory", "car factory", "factory", "manufactory", "manufacturing plant", "mill"]
}
